### ISSUE TITLE
Escort retained hired crews

### ISSUE THREAD

**Issue by adamsnd** [endless-sky/endless-sky#101]
After hiring max allowable (all bunks filled) crews in a Dreadnought, then purchasing a Bactrian and rotating it to be my flagship (via Shipyard drag+drop), the Dreadnought retained its max crew, including making me pay their additional daily wages. I was able to remedy this by rotating back to the escort with extra crews (again, via the Shipyard drag+drop method), firing all extra crews on the Dreadnought, then rotating back to the desired flagship.

I assume this isn't intended since the only purpose (to my knowledge) that additional crews could serve on an escort is resisting capture by AI.

I recommend auto-firing all extra crews upon changing the flagship to be an escort, especially since there is no hiring fee, only the daily wage. Perhaps with a popup notification that all extra crews were fired, for clarity's sake.

Unless:
1. player-owned merchant ships face a real possibility of being captured by AI, or,
2. you add a fleet-level command directing escorts to "disable and capture,"

there are no or only minimal reasons for maintaining high crew populations across escorts. I would be interested in the mechanics for item 2, which would allow for a different style of gameplay whereby a flagship could be small and maneuverable or even a merchant, with AI warship escorts serving a prize-capturing function. There should probably be another issue opened for item 2 if that's a feature you're interested in due to the implications of death payouts being incurred by AI escorts and other considerations.

**Comment by endless-sky** [comment]
This will be fixed in the next release. Right now the AI never tries to capture ships, so there's no point in having extra crew. In the fixed version, the way it will be handled is that each ship remembers how many extra crew you had given it, but you only need to pay salaries for the required crew if it is not your flagship. That means that if you switch flagships, then switch back to your old flagship, it will still have any extra crew it had previously.

**Comment by endless-sky** [comment]
I've tested and verified that this is fixed in release 0.8.4.
