### ISSUE TITLE
Fleet jump - additional command

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#1026]
If my fleet jumps in a hairy but undecisive situation, I'd like my ships to prepare their jump but without actually jumping or jumping as soon as I release the buton. What seemed bad enough 10 seconds before when the jump order was issued might not be so any more.

As of 0.9.0, if I press "J" all my ships jump as their complete their preparations. Instead of having 10 ships to divide their firepower at, now the enemy may focus on the slower ships and likely disable them.
Also as of 0.9.0 (and before, I guess) , keeping J pressed makes all ships in fleet prepare for jump (that nice green indicator) and when J is released, every ready ship jumps, while the others follow when ready.

What I propose is a Shift J command that starts jump prep across the fleet (alignment and almost no speed, ships don't maneuver anymore)

If later I press J, the ready ships jump and the others follow when ready. 
If I don't press J, the ready status remains "on" until I order a fleet command.

Say Shift J was issued 10 seconds ago, all 5 ships are aligned, 2 of them were damaged by enemy fire, still a few enemies in system.
I maneuver my ship towards the enemy (my ship looses jump preparedness). I press J, the rest of the fleet jumps out (presumably out of harm's way), my ship attempts the same for a split second but I continue my attack, deal with the pirates and jump finally after the rest of the fleet.

Not much of an ideea, granted, but could be interesting to have.

**Comment by Wrzlprnft** [comment]
What about your ships jumping back into the danger zone in order to follow you?

**Comment by wargwargwarg** [comment]
not sure if that calling back agrees with the lore of this game...
perhaps the ship scan microjump (1 light hour away would be enough on sublight) then jump back when things calm down?

either way, I'd like more options to manage a fleet

**Comment by LocalGod79** [comment]
if you tell your fleet to 'hold position' as a "jump prep", you'll have already over the half of the whole jump preparation process completed.

if you 'gather' your fleet *immediately after* you actually hit your 'jump' key, you'd have to have some pretty terrible steering on an escort for them to be more than a second behind you...

**Comment by abouillon** [comment]
I was about to post something similar and found this. I like this idea, but I don't like the idea of having this command allow ships that are ready to jump while those that are not ready jump when they are ready. That is pretty much the current functionality. That also makes completing escort missions that much harder because you will have to hold the jump button until the ship you are escorting is ready before jumping. The better way to handle this would be to have the entire fleet wait to jump until everyone is ready. There should be no possibility of leaving a ship or ships behind jump hyperspace jumps.

**Comment by puddlejumper9** [comment]
2 simple additions:

1. Jump alignment command - entire fleet stops and faces jump direction for instant jumping with the issue of the jump command
2. Fleet jump toggle - toggles between jump-when-ready mode and a synchronized-jump mode and maybe keep the current mode which would be a follow mode

- In the current jump mode, fleet ships align and wait until your ship jumps, so any ships that align faster will wait for you and any slower ships will jump to follow you to the next system
- In jump-when-ready mode each ship would align and jump on it's own as soon as it's ready irrespective of the status of any other ship including yours
- In synchronized-jump mode all ships would align and once the entire fleet is aligned they all jump together, which is how AI fleets operate

**Comment by tehhowch** [comment]
@puddlejumper9 
 - In the current jump mode... hold `J`. Hold it until the escort icons for those that are in-system are white again (or whatever the color you've set for `escort ready` in a plugin's `data/interfaces.txt` equivalent).
 - Your escorts do everything they can to protect you - they're your escorts, after all - and this means coming to your system if they are not otherwise ordered to go elsewhere (since giving a right-click movement order embeds a system target). So even if they jumped out of your system, they'll jump right back because they aren't doing what you're paying them to do: escort your ship.
 - "Synchronized jump" mode was proposed in #2648. It was likely closed for inactivity (i.e. conflicts in the implementation that needed addressing, but the author did not address them).

I have a pending self-assigned task of enabling a method of sending a move-to order into a different system #2678 , #3070 , which would allow you to send vulnerable ships elsewhere without first going there, and they would then stay there until you issued them a different command. This would be essentially your "jump-when-ready" mode, albeit requiring you to open the map in order to choose the destination system.
