### ISSUE TITLE
Can't disable the Drak Archon ships

### ISSUE THREAD

**Issue by XOwnagex** [endless-sky/endless-sky#1028]
I managed to finally beat a Drak ship,but wasn't able to disable it and instead ended up destroying it.Is this intentional?
If so how do you get their tech?

**Comment by lehgogh** [comment]
Drak ships cannot be disabled, and as far as I am aware, there is no way to obtain Draki tech without cheating.

**Comment by endless-sky** [comment]
Yes, it's intentional that you can't board the Archons.

**Comment by Isaacssv552** [comment]
You can removed the neverdisable tag from them in your savefile if you wish to capture them anyway.

**Comment by Gkramme** [comment]
Is this intended because the Anchon is the Drak?

**Comment by endless-sky** [comment]
Well, the answer to that is complicated. :)

The Archons are living creatures, not ships, which is why you can't board
them or make use of their "technology." It's not as if you could cut off an
Archon's head, mount it on your ship, and have it spit antimatter
projectiles on your command.

The Archons are what the Quarg, the Hai, etc. are referring to when they
talk about "the Drak."

On the other hand, the Archons just refer to themselves as "the Archons,"
never as "the Drak." Similarly, the Pug will never refer to them as "the
Drak." So whether the Archons are the Drak depends on who you ask.

**Comment by Gkramme** [comment]
Oh, I thought so. The anchons looked too creaturistic for a ship

**Comment by XOwnagex** [comment]
I thought they were ships as well,but now it makes sense why you can't board them.

**Comment by jafdy** [comment]
Could you give them some animation so they look more . . . alive and less like a very strange shaped ship?

**Comment by Wrzlprnft** [comment]
I thought they have a animation... But right... It is not playing ingame.

**Comment by Bladewood** [comment]
That... is absolutely terrifying.

**Comment by Isaacssv552** [comment]
The Drak Displacer was formerly crash prone (#1029), but has been fixed in a recent commit. You can just remove them from your save file if you want to fix the crash without updating.

**Comment by Bladewood** [comment]
I saw that, but thanks, now I know for sure it was that.
