### ISSUE TITLE
Find galaxy map function

### ISSUE THREAD

**Issue by Disiuze** [endless-sky/endless-sky#1030]
http://steamcommunity.com/app/404410/discussions/2/364040166692565759/

**Comment by endless-sky** [comment]
It's already possible to search for a particular system within that galaxy to view it, e.g. "World" to center the map on World's End. Since the galaxy itself never has a name displayed, I don't know what you would expect the player to search for to view it.

**Comment by Loke85** [comment]
Just a tip, I believe this doesn't work as if the route to the other galaxy is through a wormhole with "hidden connection"(the lack of a purple line, present in "puglaxy"), the game can't find a path to the destination and will center on (5000, 3500)(the middle).

Test it for yourself, I think it can be fixed by changing the check of the search function from "can find path" to "has visited".

Also, I presume the ability to prevent the purple line from appearing comes from the inability to get 'visited "Pug Wormhole"'in the save file. If so, how do you do that?, What causes the "visited" check?

**Comment by jafdy** [comment]
You can't map a path through the Pug wormhole because the end points are in different galaxies. Simply there is no direction to draw the line in.

**Comment by Loke85** [comment]
Um, actually that's wrong. Galaxies in the code are simply background pictures in a grid. The empty pug galaxy is really just some systems with background approximately 3 "screen diagonals" from the usual galaxy.
[Proof](http://imgur.com/RdyfGAy)
You could even edit in a hyperlink between the different "galaxies" and it would work.

**Comment by jafdy** [comment]
I should just read the files more carefully. I was making my guess from never having scrolled to it (despite trying) and from not being able to use the find function between them.

**Comment by endless-sky** [comment]
It's a little non-intuitive, but the purple wormhole lines will only be drawn if there is an explicit "planet" object corresponding to the wormhole:

```bash
planet "Wormhole Alpha"
```

Also, at least with the latest code, searching for "World" or "Incognita" (for example) in the map brings you to the Pug galaxy.

**Comment by Loke85** [comment]
Yeah, i might have an outdated version.
