### ISSUE TITLE
Intimidation Attribute.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1037]
Based on your combat rating, and ship value. If your the terror of the galaxy, pirate furrys should probably know better than to tangle with you

**Comment by toilethinges** [comment]
Although it would be tiring to do, this could be an attribute in every single weapon and ship, instead of cost, so that it is more accurate - if there was, say, a weapon with "no market value" (Intrusion Countermeasures, but a real weapon) it wouldn't affect the ships value, therefore doing nothing for intimidation, even if it was, say, a Quarg Skylance.

**Comment by endless-sky** [comment]
Pirates do already leave the player alone if your fleet is much more powerful than theirs, unless you're so close to them that combat is unavoidable.

**Comment by wambat1** [comment]
this proposal; applying to every weapon system; seems to assume all pirates know what your outfits are without having to scan your ship, if there was a way to activate this response after a pirate has actually scanned your ship, but then it might be just a likely he would call in a large fleet to try to take the valuable outfits.
