### ISSUE TITLE
Pressing 'i' twice should return you to the game screen

### ISSUE THREAD

**Issue by lshart** [endless-sky/endless-sky#1049]
basically when i want to do a quick checkup on my ship or pilot status I'll press 'i', but if i press 'i' again I go to the map, for some reason.  It'd be way better if it returned to the game screen

**Comment by LocalGod79** [comment]
'i' after the player info screen, is m[i]ssions map (which can then be toggled to [p]orts, [o]utfitters, [s]hipyayds.

to exit the player info screen, you can press [escape] or [d]one.

the existing key bindings are "way better" than your proposal...

**Comment by DingusShingleton** [comment]
Actually, he has a point. If you press [I] and hold alt, the [M] in missions is underlined, not the I, and in fact, both keys bring you to the missions map. I have personally hit I twice, intuitively thinking that the key that opened it would also close it. Surely the missions map doesn't need two hotkeys from the info screen?

**Comment by LocalGod79** [comment]
perhaps i've just been playing so long that the 'i' has become the default for viewing the missions map for me.

you are correct that 'm' also brings up the missions screen (from the player info panel).

so the question becomes - which is less awkward, having three key bindings to exit the player info panel ('esc', 'd', 'i'), and just one for the mission map screen (which is incongruous with other map screen key bindings), or the existing two and two (which has a somewhat counter-intuitive "open a different screen, rather than close this one" in this instance)...

i'm inclined to the latter (because, as i've said, i've adapted to the current system)...also because it requires less coding.  i have a feeling that this request is more complicated than it seems...

**Comment by DingusShingleton** [comment]
Well as you know I certainly can't comment on the coding lol. I just wanted to throw my 2c in that I too had in fact been burned by this peculiarity. Of course, if there's one thing people are good at, it's getting used to stuff. So at the end of the day it's fine as is.

**Comment by tehhowch** [comment]
See https://github.com/endless-sky/endless-sky/pull/4012

The reason `i` opens the mission panel from the player info panel despite not being the shortcut for it is because of the default key bindings. And I too agree that it is much more sensible for `i` to toggle the player info panel.
