### ISSUE TITLE
Dialogue for "Summons from the Gegno" mission not triggering on landing on planet

### ISSUE THREAD

**Issue by TygerTung** [endless-sky/endless-sky#10566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After completing the mining missions for the Gegno and their space station, I visited the Quarg ringworld. I was told that the Gegno are not pleased with me and I am summoned to their home planet, Dueyu Eitch, within 8 days. Upon landing the mission does not progress, it is just the same as landing on any regular planet.

### Steps to Reproduce

1. Go to 'Giaru Gegno in the Aleit system to trigger the Summons mission'
2. Travel to Heutesl System and land on Dueyu Eitch
3. Nothing happens now.

### Expected Behavior

I would expect the dialogue for the mission to trigger on landing on the planet, but nothing happens.

### Link to save file

[Unicorn Princess~ON WAY TO GEGNO.txt](https://github.com/user-attachments/files/17299306/Unicorn.Princess.ON.WAY.TO.GEGNO.txt)

### Operating System

Xubuntu 24.04

### Game Source

Other (please describe)

### Game Version

Ubuntu Snap version 0.10.9-alpha

### Additional Information

I am concerned that I can't play the game any further than this as it might lock me out of the Gegno if I fail this mission.

**Comment by Saugia** [comment]
This was reported on discord; the mission you're getting is based on something called "Gegno Encounters", which leads to the main interaction mission on the homeworld. One version of this is "Gegno Intervention", which offers if you have 3-5 of these encounters. The other, "Gegno Apprehension" is if you get all 6. What you're getting is the latter mission, which is simply an alternative telling of the former. As it stands, that is the end of current Gegno content; what you're getting shouldn't be happening in the first place, but does because nothing is preventing it from offering currently.

[This PR](https://github.com/endless-sky/endless-sky/pull/10554) fixes this by making sure the latter does not offer after you have gone through the former. I'll keep this issue open and tied to the PR so others can see until next update. Thanks for reporting!
