### ISSUE TITLE
Create delay for enemy attacks.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1058]
I've noticed when you jump into a system, you immediately get attacked. Shouldn't there be a few seconds delay before enemies start shooting you out of the sky?

**Comment by jafdy** [comment]
It might be related to ships firing one shot as other ships jump in.

**Comment by toilethinges** [comment]
f69442e

**Comment by endless-sky** [comment]
I've added a half-second delay, which I think is reasonable - I know when I see something yellow jump into the system I target it almost immediately. The half second will avoid having ships think that the target is moving so fast that it will reach them within the lifetime of their turret fire, which is why they'll occasionally fire a shot.
