### ISSUE TITLE
Feature request: Ability for escorts to scan on demand

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1068]
Reason: It's annoying when you need just 1 more outfit space to install dat scanner :|

Also, I'm referring to escorts that you own, not people like the Navy. Assuming they CAN scan while they're escorts.

**Comment by wambat1** [comment]
so, with this feature, you would still have to target the ship, and only scanner equipped ships would respond? this would give me some use for those Republic surveillance drones in my storage.

**Comment by endless-sky** [comment]
As with many other feature requests, the real question here is whether this would make the game more interesting or add new variety to the player's behavior. I don't think wanting escorts to be able to scan ships just so you could complete certain missions without a scanner on your flagship is a good enough reason, and it would add all sorts of complications - when your escort scans a ship, do you still get to see the scan results? If the ship hails you in response to the scan, wouldn't they hail the escort instead of your flagship? And, is there now going to need to be a dedicated key to command escorts to scan a target?

**Comment by jafdy** [comment]
Would it be simpler if you could scan any ship in range of any scanner in your fleet using the current key. If you don't add an AI behavior for it it. You could say that escorts transmit the data directly to you so people detect the transference and hail you.
Seems like alot of effort.

**Comment by wambat1** [comment]
i am not sure i can give credit to these objections. we already have an attack button which all your armed escorts will respond to. true we have a separate fleet attack button, but scanning seems an innocent enough action that having any scanner equipped ship in your fleet respond to that same key does not seem out of line.
as far as communicating some simple scanner information between fleet members: we, with our presumably inferior pre-galactic empire technology could accomplish this. in the context of the game world, we already have instantaneous communication across galactic distances with the hold and gather fleet commands. and, yes, an npc dialogue would be addressed to you, even if one of the fleet ships picked up the signal, it would simply be relayed to the flagship; no problem there. i am afraid all these objections are chimera.  

    On Friday, May 20, 2016 6:06 AM, jafdy <notifications@github.com> wrote:
 

 Would it be simpler if you could scan any ship in range of any scanner in your fleet using the current key. If you don't add an AI behavior for it it. You could say that escorts transmit the data directly to you so people detect the transference and hail you.
Seems like alot of effort. —
