### ISSUE TITLE
Add indicator on Spaceport button if plot mission is available

### ISSUE THREAD

**Issue by MrPetovan** [endless-sky/endless-sky#10765]
### Problem Description

When I'm on a regular mission route and I stop at stations mid-way, I don't always check the Spaceport. Even when I do, I'm not always offered a plot mission. The spaceport descriptions are nice, but the novelty wears off rapidly when nothing is offered on systems you land in more than once.

I've received the plot mission that encourages players to look at the Spaceport more often, but it is counter-productive as the player did look at the Spaceport to get this mission (if I remember correctly), and it fizzles out immediately which possibly obscures another plot mission that would have had more content to it.

### Related Issue Links

Issues related to plot missions awareness:
- #9482
- #7961
- #7798 (knowing that a mission is available could assuage the delay issue)
- #3663

### Desired Solution

The "Spaceport" button should have an indicator when a plot mission is available. Ideally, the indicator would be of a different color whether it is a one-off mission or part of a storyline (like the Free World storyline that apparently unlocks game contents which I figured out in this bug tracker while looking for something else, validating #3663 ).

![image](https://github.com/user-attachments/assets/5784cf75-8eb1-44c7-a32f-c8a2031ec038)

### Alternative Approaches

- Plot mission map marker like in #9482
- Triggering plot missions directly on landing?

**Comment by Saugia** [comment]
The same issue has been opened and suggested in the past, with the original developer of Endless Sky responding with [this comment](https://github.com/endless-sky/endless-sky/pull/1292#issuecomment-230361064).

**Comment by MrPetovan** [comment]
Thank you for the response and sorry I didn't think to look for closed PRs!

**Comment by Saugia** [comment]
No worries - there are a ton of things open. Thanks for understanding.

**Comment by MrPetovan** [comment]
Just realizing that my alternative "Trigger mission on land" would fit in this "stumble" approach without requiring a click on a mostly dead zone of the station screen. The plot mission trigger chance would have to be drastically lowered across the board, and it could highlight storyline missions by making them appear more consistently. Please let me know if i should open a separate issue for this or if it a non-starter!

**Comment by Saugia** [comment]
A majority of the missions in-game actually do trigger on land, as well as the spaceport. I'm not sure we would change *every* mission in the game to trigger upon landing though. A lot of what happens in the story is you running into these individuals in the spaceport, and not immediately landing upon the planet, so there's some separation there in terms of landing interaction.

ES is indeed a separate game, and we are inspired but not trying to cop of it, but the Escape Velocity series, which the game developer based the game on, similarly relied specifically on the spaceport for unique missions and story content. If we move main story content to specifically occur upon landing only, then the spaceport would be a bit trivialized to only minor story missions, and nothing important like the campaign, which was the design purpose of it in both EV and ES.

There may be specific missions that are better triggered upon landing or immediately, so if there are any you believe apply to this, feel free to suggest them, though bear in mind some may have already been brought up and had a decision made on them. But overall, I don't think we would make all plot missions happen directly on landing, no.

Something to think about, although with a smaller portion, is that the game itself isn't entirely about the plot, a lot of people enjoy the game for its base gameplay, so I feel we would avoid missions like that always popping up for those who just want a relaxed experience. The spaceport is meant to be that level of interaction you are meant to go into in order to actively push yourself into the story. In fact, there are missions that offer in other buttons on the planetary level, so to some extent, the spaceport is just as important as a button of all others. Just because it doesn't offer an amenity such as ships or outfitters, doesn't mean it's less important for the player - its amenity *is* the important missions. :)

**Comment by MrPetovan** [comment]
Thank you for the elaboration! Some planets don't have a Spaceport so plot missions obviously wouldn't trigger on these, but for planets/stations that have a spaceport, this would always be the first point of contact of the player's fleet, which gave me the idea about the automatic trigger.

But you are right, some plot missions already trigger on land, and it has been confusing me about the relative importance of these missions. Also missions can present differently, either with a side panel or with a popup, but it isn't entirely clear whether it is significant towards accepting/rejecting the mission.

I do understand the mindset of wanting to run cargo without being harassed by random encounters, but the game doesn't cleanly provide this experience either because of the landing-triggered plot missions. In the end it's the lack of consistency and the ambiguity about the importance (or lack thereof) of the plot missions that I wanted to address in this issue.

**Comment by Saugia** [comment]
The pop up vs. side panel conversation is more so a style choice of the given mission. Something that is a more involved read, or longer, would be on the side panel, meanwhile a pop-up is more quick and to the point. If I recall correctly, there are no plot missions that *start* with a pop up, but there are a few cases where pop-up is used as a quick bridge between events or conversations rather than advocating half of the screen for a few words.

However, there are small, casual missions that do make use of the pop up on start (such as illegal missions). In either case, they are about a quick note or mission "in your face". I would argue that both have their importance - the in your face, and the longer storytelling of a panel Though, I would say that for pop-ups, they probably aren't a huge deal, considering it is only a few words there for the player to read. If you do happen to find a case where a pop-up seems it should be more important, let us know that as well (or possibly the reverse, of some things that maybe shouldn't be pop-ups).
