### ISSUE TITLE
"Yeah, right. Don't push your luck."

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#1077]
When you bribe some hostile faction off, usually pirates, it may be after being disabled or cornered in a system with no fuel. Immediately after that, you may want help with those problems. After bribing, asking for help right after with give the titular response. However, if you leave the hail and just hail them again, they'll be all too happy to fix you up. Within, like, one second of them firing on you.

Since there was the double-bribe and attack fix, I think this could be done easily.

**Comment by endless-sky** [comment]
I think this is one of those cases where the most important question is what makes the game fun and non-aggravating, not what is most "realistic" - after all, this is a *game*.

The current behavior is an intentional choice to strike a balance between realism vs. annoyance for the player: for the sake of realism you can't ask for help right after bribing a hostile ship, but if you're stuck in a system with no ships of other factions you can hail that ship again (or another) and ask for help then.

**Comment by Alkallid** [comment]
Ah.
