### ISSUE TITLE
OSX: support for homebrew libraries 

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#108]
I managed to compile endless-sky by installing required libraries with homebrew (sdl2, jpeg-turbo, libpng). However, I had to add a different set of linked libraries in my XCode project:

![screen shot 2015-09-20 at 16 59 16](https://cloud.githubusercontent.com/assets/238652/9981271/461b5aa8-5fb9-11e5-8894-c97eff6f587b.png)

Is it somehow possible, that the XCode project can be made universal, so that it works with your and my build configuration? 

Or maybe you are willing to switch to the homebrew provided libraries, too?

**Comment by schlamar** [comment]
And I had to change the hard coded include:

![screen shot 2015-09-20 at 17 05 34](https://cloud.githubusercontent.com/assets/238652/9981300/e82f78b0-5fb9-11e5-9470-a5a1ec08def3.png)

**Comment by endless-sky** [comment]
I've applied the changes you suggested to the ImageBuffer.cpp file, so that you can compile using the homebrew libraries without modifying the code. It's still necessary to modify the library paths, though; I can't see any way to have the project capable of switching between those two locations automatically.
