### ISSUE TITLE
[Bug] Starting from commit c14ed8779e6854c349e3be683dac834f8ea8405b, missions with `minor` can no longer offer

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#10816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Any mission that has the `minor` tag cannot offer if you play any version from https://github.com/endless-sky/endless-sky/commit/c14ed8779e6854c349e3be683dac834f8ea8405b to current continuous, but does offer if you play a previous version, such as v0.10.10 release.

### Steps to Reproduce

1. Load save file
2. Depart
3. Land
4. Hit spaceport
5. See how the free worlds mission only offers prior to https://github.com/endless-sky/endless-sky/commit/c14ed8779e6854c349e3be683dac834f8ea8405b

### Expected Behavior

Missions with `minor` can offer

### Screenshots

n/a

### Link to save file

Thanks arachi for the save and initial report
[Yuri Nuttz~minor.txt](https://github.com/user-attachments/files/17896964/Yuri.Nuttz.minor.txt)

### Operating System

Debian 12 Bookworm

### Game Source

Built from source

### Game Version

https://github.com/endless-sky/endless-sky/commit/c14ed8779e6854c349e3be683dac834f8ea8405b

**Comment by warp-core** [comment]
The spaceport reminder mission name was changed from starting with "00" to "aa".
"minor" missions are offered in reverse alphabetical order: if multiple "minor" missions are available, the one with the "highest" name will be offered.
Starting with "00" meant that the mission would never block any other (vanilla) "minor" mission from offering.
Starting with "aa" means it now pretty much always blocks them, because they all start with capital letters.
