### ISSUE TITLE
Faster "Fast Forward" Speeds

### ISSUE THREAD

**Issue by TygerTung** [endless-sky/endless-sky#10853]
### Problem Description

Sometimes when one is running a heavily min-maxed ship with really small engines, it is incredibly slow to move around. It would be nice to sometimes have the possibility of speeding up time more than 2x. Would it be possible to add this feature?

### Related Issue Links

None I could see

### Desired Solution

Perhaps an additional key for 3 or 4 time speed

### Alternative Approaches

The existing key could be toggled a number of times for different speed increases.

**Comment by Saugia** [comment]
The current in-game speedup is 3x.

I generally don't think we'd add additional game speeds, especially if the reasoning for it is because of a small portion of players with very min-maxed ships; the game isn't all about things like capturing - if you have a min-maxed ship and it is extremely slow, that should be intentionally a reason why its gameplay is subpar. Making even faster modes just to make something that's supposed to be slow just be faster isn't really good gameplay design.

**Comment by TomGoodIdea** [comment]
#3887
