### ISSUE TITLE
I don't get fined if I don't have enough money

### ISSUE THREAD

**Issue by ixPost** [endless-sky/endless-sky#10868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I bought 113 Nerve Gas Grenades in Sargas and went to Republic Space where I got scanned by a surveillance drone after it scanned me, it said that I got fined a million bucks by the Republic authorities, but nothing happened to my money.

### Steps to Reproduce

1. Buy as much Nerve Gas Grenades at Sargas as possible
2. Get scanned by a Surveillance Drone

### Expected Behavior

I expected them to shoot me down, and take all my money.

### Operating System

Linux Mint 21.3 Cinnamon

### Game Source

Other (please describe)

### Game Version

0.10.10 from Flathub

### Additional Information

Actually I don't lose money even if I have enough!

**Comment by Rob59er** [comment]
Fines are charged to the bank tab (like a loan) rather than an immediate lump sum. If you look to the bottom left you should see every time you enter a new system/land and depart you pay part of the fine. If you have no money you won't pay anything but the fine will go up because of interest. 

If there's nothing there in the bank tab something did break, but I just tested getting fined with no money on the latest continuous and all was working as normal there.

**Comment by ixPost** [comment]
Thanks, I didn't realize this.
