### ISSUE TITLE
[enhancement] Auto-fire Weapons

### ISSUE THREAD

**Issue by Haravikk** [endless-sky/endless-sky#1098]
One big reason I struggle with energy drain or heat generation is because I'm firing weapons that I can't possibly hit with, for example firing off my guns uncontrollably just so I can shoot an enemy behind me with a turret.

Since crew need to be assigned to a turret I'd like to be able to set turrets to auto-fire at hostile ships in range, allowing me to focus on bringing my guns to bear and/or firing secondary weapons. This should prioritise firing upon a selected enemy ship if it's in range, otherwise just firing at will.

Not sure where would be the best place to put this, since there's no ship management screen (unless I missed it somehow) so this should probably be an option in the outfitter or crew screens somewhere.

An alternative option would be to have separate buttons for fire guns, fire turrets and fire both, allowing me to adapt myself, though firing automatically would allow my ship to hit multiple targets (e.g- fire on fighters while I focus guns on a bigger target) so it'd my preference for playing with a single ship.

**Comment by Gkramme** [comment]
There is already this option. Go to settings on the main screen, and then turn auto-fire on.

**Comment by jafdy** [comment]
The UI layout is not great at the moment. I would recommend poking around the wiki I think there is a full list of keys in there.

**Comment by Haravikk** [comment]
> There is already this option. Go to settings on the main screen, and then turn auto-fire on.

Sorry, just found it. But is this for turrets only or for all weapons? I also found the player screen, not sure how I missed that, with the ability to change weapon layout it may make sense to be able to toggle auto-fire for individual turrets on this screen, though I think in general it will be an all or nothing proposition (you either want all or none of them to fire, except for anti-missile turrets of course which would always fire automatically as they do now).

**Comment by Gkramme** [comment]
All guns fire automatically.

**Comment by Haravikk** [comment]
> All guns fire automatically.

Ah, that's not ideal then, it's only really turrets that I want to fire automatically, as it's when you have both turrets and guns that you start wasting energy and heat by firing off your guns while trying to hit something behind you.

**Comment by Gkramme** [comment]
No only when the ship is in front of you. Your guns only fire if they're going to hit your target.

**Comment by Pointedstick** [comment]
Yes, this already exists. Turn on auto-fire and any guns/turrets that are in range and line of sight will fire at the current target. Guns will only auto-fire if your ship is pointed at the target.

**Comment by Haravikk** [comment]
Sorry that's not what I meant; I meant I only really want auto-fire so I can have my turrets shoot at enemies to my sides/rear, I don't want to rely on auto-fire for my guns as well as I still want to fire those myself.

Also, I haven't been able to get a situation where I can test it out, but does auto-fire currently keep shooting once a target is disabled? I'd like my turret(s) to shoot automatically at enemies that get to my side/rear but to only disable them, while I can focus on blasting stuff (potentially other stuff) with my guns to either disable or kill as I prefer.

**Comment by psychiclegume** [comment]
Auto-fire stops shooting when the target gets disabled (laser weapons), but will not fire on targets you do not have targeted. Therefore you cannot have your turrets shot down enemy fighters while you kill the carrier with your guns. Also Auto-fire controls all weapons, so you cannot, say, have your turrets auto-fire and your guns be manual.

**Comment by wambat1** [comment]
currently all weapons can be set to automatically fire at your current target until it is disabled. only continuous fire weapons (like lasers) will do this reliably. you can then press the fire button with a disabled ship targeted to finish it off at your discretion. be aware that your fleet will automatically select another hostile to fire at once their initial target is disabled, so they will destroy that Republic Carrier you have your eyes on if a drone they have decided to target flies around to place the disabled ship between your fleet and the drone. there isn't too much you can do about that beside find another carrier to board.

**Comment by Haravikk** [comment]
Okay, well even so I think the issue stands; I'd like to be able to set my turrets to auto-fire/fire at all while I focus on my other weapons manually. That's still an enhancement over the current auto-fire feature.

**Comment by jafdy** [comment]
You can still fire weapons manually in the normal way. The auto fire is normally better at hitting.

**Comment by Wrzlprnft** [comment]
I think we need some sort of enabling and disabling weapons, or weapon groups, as well as the ability to assign fire keys to weapon groups, sooner or later, since it really can improve the possibilities on fighting and outfitting for the player. Those who don't care could just not touch the default settings and fly as they are used to.

**Comment by wambat1** [comment]
adding this kind of feature; independent auto aim for turrets; would definitely enhance the cinematic quality of the game. it would not make practical sense, since concentration of fire, and fire control are two military doctrines most players would miss. i would suggest developing this idea as a mod, as it might be very attractive for developers of Star Wars/Star Trek mods to recreate the kind of battle visuals seen in those franchises. it is an idea which might also become relevant if turrets ever having restricted traverse speed, or fire arcs. 

    On Thursday, May 19, 2016 5:10 AM, Wrzlprnft <notifications@github.com> wrote:
 

 I think we need some sort of enabling and disabling weapons, or weapon groups, as well as the ability to assign fire keys to weapon groups, sooner or later, since it really can improve the possibilities on fighting and outfitting for the player. Those who don't care could just not touch the default settings and fly as they are used to.—

**Comment by jafdy** [comment]
The game handles plugins for things but I don't think that would extend to code changes. (Would need to recompile code?)

**Comment by Haravikk** [comment]
> adding this kind of feature; independent auto aim for turrets; would definitely enhance the cinematic quality of the game. it would not make practical sense, since concentration of fire, and fire control are two military doctrines most players would miss.

I'm not sure I follow; no capabilities should be lost, I'm talking about an option so players would remain free to fire all weapons manually if they wanted.

It just occurred to me that an alternative could be to add a class of point-defence weapons; we currently have anti-missile turrets, basically point defence would be more focused on fighters and small ships, but firing automatically in the same way.

**Comment by wambat1** [comment]
i do believe a proposal along the lines of the point defense is on the github forum. you might check that out and see if that is what you have in mind. this one, i think:https://github.com/endless-sky/endless-sky/issues/1098


 

    On Friday, May 20, 2016 7:29 AM, Haravikk <notifications@github.com> wrote:
 

 
adding this kind of feature; independent auto aim for turrets; would definitely enhance the cinematic quality of the game. it would not make practical sense, since concentration of fire, and fire control are two military doctrines most players would miss.
I'm not sure I follow; no capabilities should be lost, I'm talking about an option so players would remain free to fire all weapons manually if they wanted.It just occurred to me that an alternative could be to add a class of point-defence weapons; we currently have anti-missile turrets, basically point defence would be more focused on fighters and small ships, but firing automatically in the same way.—

**Comment by jafdy** [comment]
@wambat1 You have referenced this issue. A bit cyclic for my liking.

**Comment by wambat1** [comment]
sorry about that. i am responding on email and thought this was a google thread. if you can erase that post, please do, i will not be able to log in for several hours. 

    On Friday, May 20, 2016 1:19 PM, jafdy <notifications@github.com> wrote:
 

 @wambat1 You have referenced this issue. A bit cyclic for my liking.—

**Comment by Haravikk** [comment]
I just thought of another possible way this could be implemented; if I could instead designate weapons as secondary, then I could fire these using the secondary weapon controls.

For example, I currently have a ship with a bunch of plasma turrets and some particle cannons, if I could designate the particle cannons as a secondary weapon (with unlimited "ammo") then I could fire them separately.

Not saying that all guns should be reclassified, just that if I could set them as secondary on the info screen I could switch to controlling them separately (since I don't have any missiles/torpedoes anyway).

**Comment by wambat1** [comment]
what about this: what if the classification itself; secondary or primary; became the player's option for each weapon system? this, i think, would give players all the control they desire, would require less effort on the part of the player than other weapon selection options i have seen proposed, and might require the least departure from the current game mechanics. 

    On Saturday, May 21, 2016 12:30 PM, Haravikk <notifications@github.com> wrote:
 

 I just thought of another possible way this could be implemented; if I could instead designate weapons as secondary, then I could fire these using the secondary weapon controls.For example, I currently have a ship with a bunch of plasma turrets and some particle cannons, if I could designate the particle cannons as a secondary weapon (with unlimited "ammo") then I could fire them separately.Not saying that all guns should be reclassified, just that if I could set them as secondary on the info screen I could switch to controlling them separately (since I don't have any missiles/torpedoes anyway).—
