### ISSUE TITLE
[Question] Auto Aiming Turrets / Independent Targeting

### ISSUE THREAD

**Issue by CodeDraken** [endless-sky/endless-sky#1124]
Is there a way to make turrets each shoot their own target closest to it, without needing to press R and target a unit. It's weird if you're using a giant ship with 12 turrets and they all target 1 little ship, and having to spam R. Also is the range of the turret calculated by lifetime/velocity or how does that work?

**Comment by jafdy** [comment]
#1098 

Try `R`. I use laser turrets so its not in my experience.

Its lifetime x velocity.

No ship in the base game has 12 turrets.

**Comment by evan153** [comment]
I mean R not Tab. I'm working on a star wars imperial destroyer and it has 18 turrets lol.

**Comment by toilethinges** [comment]
#993?

Suggesting that, say, you have tons of turrets, and are being swarmed by fighters. You don't want to select one ship and focus fire on that one ship, but instead target each fighter with a single turret?

**Comment by evan153** [comment]
Yes, like that. Lets say you have a huge ship with turrets in the front and turrets in the back. There's an enemy in the front in range of the front turrets only and the one in the back is in the range of the back turrets only. You can only target one ship and only shoot half of your turrets. Need a way for turrets to target individually. I mean they're suppose to be humans operating them why can't they target their own targets?

**Comment by toilethinges** [comment]
Makes sense.

**Comment by LocalGod79** [comment]
"Yes, like that" means this is a duplicate issue.

i'm seeing a lot of new issues by people who aren't following the rules.

there are basically three - this is not hard, people.
https://github.com/endless-sky/endless-sky/blob/master/CONTRIBUTING.md

**Comment by evan153** [comment]
I'm guessing that means there's no way to achieve this? D:

**Comment by LocalGod79** [comment]
i'm guessing that anybody who's capable, doesn't really desire the feature enough to set about programming it ahead of others.

you're not the first to request it, it may eventually become a feature.

**Comment by evan153** [comment]
I imagine it would be similar to how the anti-missile turrets work. As far as I know there's no way to mod it and would require editing code.

**Comment by endless-sky** [comment]
One of the most computationally intensive parts of the game right now is the code for AI ships to determine whether or not to fire their weapons, by tracing the expected flight path of those weapons and calculating whether it will intercept the flight path of any ships. If turrets were allowed to fire at "targets of opportunity" it would make that calculation even more time consuming.

In the future if I manage to optimize other things (e.g. collision detection) sufficiently to gain some CPU headroom I might consider adding independently targeting turrets, but it's not a high priority because concentrating fire is nearly always the better approach.

**Comment by tehhowch** [comment]
PS: this is done :+1:
