### ISSUE TITLE
Negative Attribute Message

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1128]
I said this on #1100, but I think it deserves its own post. 

It's never fun getting the negative attributes message and not knowing why you're getting it. Could it be possible to allow the message to specify what is negative instead of being like "Oh, SOMETHING is negative, and it could be any of these things. Or it could be something else, I won't tell you."

**Comment by LocalGod79** [comment]
this might be as simple as a subroutine that grabs the name of the outfit granting the negative attribute, but i don't know how to do that...

**Comment by DingusShingleton** [comment]
I often wondered why that message needs to pop up the second you try to make something negative. There is already precedent for allowing the player to remove engines without an error. Why can't the negative number check happen when you try to leave the outfitter? I would guess that 90% of the time it pops up it's because someone is trying to change power plants. I mean, presumably when you are changing engines and power plants etc, everything is powered down anyway, so why would a negative stat matter unless you were trying to take off?

**Comment by LocalGod79** [comment]
or merging #852

**Comment by LocalGod79** [comment]
has anybody gotten the negative attribute check recently?  there *is* a pointer telling you which outfit is causing it...

**Comment by jafdy** [comment]
there is sometimes a pointer
I have had both types recently. (with and without pointers)

**Comment by Alkallid** [comment]
Trying to buy too many of something brings up the ambiguous one, selling the specific one.

**Comment by LocalGod79** [comment]
the "pointer" comes up if you try to sell an item that would make attributes negative (i.e. point to shield gennies, when selling power)

if you try to buy something that would drive an attribute negative, you get the "ambiguous" one (because the negative attribute is displayed in the outfit description).

**Comment by Amazinite** [comment]
Yeah, I haven't found a case in a long time where it doesn't give you any helpful information. Must have been added in one of the v0.9.x updates, because I remember getting the unhelpful pointer before when it could have told you what is causing the problem.
