### ISSUE TITLE
Transfer to today's monetary value?

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#1139]
I noticed that your crew appeared to be underpaid, and then I realised that the worth of money had skyrocketed. I propose changing prices to today's prices.

**Comment by johndh** [comment]
To what currency at what exchange rate?  Even when accounting for inflation, the value of labor and commodities obviously fluctuates greatly from time to time.

**Comment by Amazinite** [comment]
Not trying to be rude, but don't keep assuming everything will be the same a thousand years down the road as now. 

100 credits (36,500 credits a year) is probably good money in the ES universe where slave labor is practically thing (although technically abolished, workers are still pretty much just paid slaves in Syndicate industry and mining worlds), even though it might not seem like much to the player who is buying multi-ton spaceships. And I don't really think they're underpaid considering that you provide them a place to live and likely provide their food as well. So pretty much they're paying for nothing while getting cash for manning your turrets and making sure the reactor doesn't blow up. There's also the fact that it doesn't seem like they even need to worry about taxes since the player isn't getting taxed for making money or anything.

**Comment by Gkramme** [comment]
I understand that, but buying a ton of food for $300 means crazy deinflation. Todays average trip to the store costs $300 :)

**Comment by VrykoMonkeylord** [comment]
The mission where you need to pick up a data library and bring it to a Hai technologist states that "39.99" (currency units) is equivalent to a fraction of a credit. So it is reasonable to assume that a single "credit" is worth 100 or so "dollars", meaning you are paying each crew $10,000 a day, and your starting ship costs on the order of 40 million "dollars". Thinking about this from the perspective of a modern-day commercial crab fisherman (like in deadliest catch), who will make probably around $100k in a six-month pair of seasons, that comes out to around $500-600 a day. Assuming a merchant spaceship captain will pay a crew something around that, we can assume that a single "dollar" at this point in the future is worth around 1/20 of a modern USD, so a credit is worth 5 modern USD, putting a ton of food (we're assuming cheap rations here) at ~1500 USD. This means the starter ship is on the order of 2 million USD in today's currency (spaceships right now cost much more than this, but we can assume they will be cheaper to make in the future). All of this seems entirely reasonable to me.

**Comment by Amazinite** [comment]
It's only crazy deflation if you assume that 1 credit = 1 dollar. It's much more likely that it is the case that Vryko proposed.

**Comment by toilethinges** [comment]
@VrykoMonkeylord, actually, 39.99 credits, not 39.9% of a credit. It meant that that's a rip-off, considering **empty** data chips cost a fraction of a credit.

**Comment by Amazinite** [comment]
Yup. And the mission charges you 40 credits on complete.

**Comment by Gkramme** [comment]
Thanks, @toilethinges.

**Comment by endless-sky** [comment]
Remember that this is a game, not an economics simulation! The salaries, prices, etc. are all chosen in order to be balanced with each other and to create a game where there are interesting trade-offs.
