### ISSUE TITLE
[enhancement] ships with no weapons chase flotsam

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1142]
perhaps only if it's possible for them to intercept it before it vanishes, or if it's within a certain range?

the idea occurred to me when discussing the Boxwing as a "cargo fighter" with someone.

what does a cargo fighter fight?
cargo.
how does it fight it?
collect.

_really_ low priority - i don't know how many people have escorts with no weapons installed - probably not many.

**Comment by toilethinges** [comment]
Perhaps a new personality, or edits to old ones, that make this happen, as well?

I could see pirates, with "plunders" personality, going out of their way to collect fallen cargo.

**Comment by endless-sky** [comment]
Eventually, my plan is to add an "appeasing" personality type that dumps cargo to try to get out of combat - "Please, just take my cargo and leave me alone." Paired with that would be a "harvesting" personality that suspends combat (except for taking opportunity shots) when there is flotsam available to grab. And of course, eventually there will also be a "mining" personality that goes around looking for asteroids to blow up and then harvesting the flotsam they create.

**Comment by Amazinite** [comment]
Yeah boi.

**Comment by wambat1** [comment]
would a "harvesting" personality seek to jump once it has filled its cargo hold? would "appeasing" personality bump all its cargo at the first sign of trouble, or just a small amount likely to fill the cargo of a pirate? would players be able to get free cargo from merchants by waiting for pirates to scare the flotsam out of them and then snag it before the pirates do? would than have a negative impact on standings with either party?

**Comment by LocalGod79** [comment]
i thought M.Z. was pretty clear with his explanations.
so, as i understand it, and quickly;
Q1 - 
> suspends combat (except for taking opportunity shots) when there is flotsam available to grab.
otherwise behaves according to other applied personality tags.

Q2 -
> dumps cargo to try to get out of combat
so yes, probably all of it.

Q3 - yes

Q4 - the "appeasing" personality will probably jump immediately after jettisoning the cargo, and the "harvesting" personality is probably going to come after you next (since you're closest) - so whatever outcome of that battle...

**Comment by wambat1** [comment]
Q5 - would a ship with the harvesting personality continue to go after cargo after its hold is full?
Q6 - does the harvesting ship actually collect the flotsam in its hold, or it more like a celestial pac-man eating up flotsam indefinitely?
Q7 - would a player be able to paralyze a harvester personality by dropping bits of cargo all the while shooting up the distracted ship? 
just a suggestion, for the sake of realism. i don't think any of the stock pirate ships have a greater than 100ton cargo capacity. verisimilitude might suggest that, or some appropriate value, as the limit of what an individual merchant would be willing to dump to distract a pirate. given the fleets merchants tend to travel in, that is still more than the average pirate fleet could absorb. 

    On Friday, May 27, 2016 7:49 AM, LocalGod79 <notifications@github.com> wrote:
 

 i thought M.Z. was pretty clear with his explanations.
so, as i understand it, and quickly;
Q1 - 
suspends combat (except for taking opportunity shots) when there is flotsam available to grab.
otherwise behaves according to other applied personality tags.
Q2 -
dumps cargo to try to get out of combat
so yes, probably all of it.
Q3 - yesQ4 - the "appeasing" personality will probably jump immediately after jettisoning the cargo, and the "harvesting" personality is probably going to come after you next (since you're closest) - so whatever outcome of that battle...—

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
