### ISSUE TITLE
[bug]republic drones have capital ship names in free worlds middle

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#1158]
fighters, too.

**Comment by endless-sky** [comment]
Can you give an example mission that has the problem? I can't find any place where a fleet contains fighters where fighter names aren't specified. I went through every time in the free worlds data where republic capital names are used, and the only time fighter names aren't specified as well is when the fleet contains no fighters.

**Comment by LocalGod79** [comment]
the second time it happened to me was "FW Rand 1", but the code appears intact.

i wonder if this is another of my "phantom" bugs, that will disappear tomorrow...

i only noticed because i captured a carrier (abnormal for me) and some drones/fighters to fill its bays.

unfortunately, i've not been making snapshots, and the autosave is already 1B: active

**Comment by LocalGod79** [comment]
https://groups.google.com/forum/#!category-topic/endless-sky/7JMkJ76oeJw

**Comment by LocalGod79** [comment]
as it turns out, the Free Worlds Fighters are not being named correctly, either...

**Comment by LocalGod79** [comment]
i believe the problem may reside at line 121 of NPC.cpp

**Comment by endless-sky** [comment]
It was because in Fleet, if a fleet is placed but explicitly asked to create fighters already launched rather than carried, it was giving them non-fighter names.

Fixed in bb2f54a, although the fix is hard to see because I did a lot of refactoring and cleanup of duplicated code as well. (And fixed a few other potential bugs in the process.)
