### ISSUE TITLE
Auto Pilot w/ only Afterburners or Reverse Thrusters

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1170]
If you decide to for some reason place only afterburners on your ship and then warp to another system, land on a planet, or really just do anything that requires the auto pilot, you have to manually move yourself into position as the auto pilot does not use the afterburners.

Not sure if this is something worth fixing, but given that we just got the ability to launch with only afterburners it makes sense to have the auto pilot use them.

Edit: and when you do manually slow down to go to another system, you spawn into the system moving backwards...

Edit: It also can't use only the reverse engines when landing and boarding, but it can when jumping to another system.

**Comment by Gkramme** [comment]
Reverse thrusters are used, they are just so weak that it is easier to use the main engines instead.

**Comment by Amazinite** [comment]
I'm talking about when you only have reverse engines installed. The auto pilot won't do anything when attempting to board or land because it doesn't recognize how to use the reverse engines.

**Comment by endless-sky** [comment]
This seems like really low priority: none of the stock ships are configured that way, and if the player chooses to make a ship with no ordinary thrusters, that's their own fault. :)

**Comment by Amazinite** [comment]
Rip my dream of flying around the galaxy in reverse.

**Comment by KiLEdEnNis** [comment]
@Amazinite it would never work out, you don't have guns facing backwards :(

**Comment by KevinKorzekwa** [comment]
It might be worth noting that I only put afterburners on my escort ships (not my flagship) because the AI on escorts actually uses it while the AI for landing/jumping with the flagship does not use the afterburners.  So I can't use them without excessive micromanaging that ends up taking longer than letting the much weaker engines installed just do their thing.

Granted it's a bit different than having only reverse thrusters and afterburners, but it is still afterburner behaviour on the flagship :/
