### ISSUE TITLE
Weight

### ISSUE THREAD

**Issue by egony** [endless-sky/endless-sky#1177]
Since you are in space and there isn't gravity in space, instead of using weight we should use a volume system.

For example, a small cargo ship has 50 m^3 of cargo space. And outfits are class specific and use 1 slot. 

For example, the small cargo ship has 1 gun slot, one shield slot, one engine slot, one power slot, 1 cooling slot, and one misc. slot. 

That small cargo ship can only equip Light freighter outfits. When plundered outfits are put in the cargo bay they use "X" amount of space but equipped they don't use any space since they are on the outside hull.

**Comment by Alkallid** [comment]
No, this isn't the game's scope.

**Comment by toilethinges** [comment]
Sounds like several other games I've played.

**Comment by LocalGod79** [comment]
i've never seen any references to "weight" in Endless Sky.

"mass" and "weight" are not the same thing (even if they are strongly correlated).  when calculating acceleration and velocity, one must consider the forces at work on a body, and its *mass*.

volume is irrelevant in space.  mass is not.

**Comment by endless-sky** [comment]
A "slots" system would eliminate most of the customizability of the ship hulls: there would no longer be trade-off decisions like installing smaller engines in order to have more room for other outfits. It would all just come down to what the best outfit of each slot type is.

In terms of mass vs. volume, it doesn't actually matter to the game mechanics whether you call it m^3 or kL or T. For the game text "tons" just happens to be a less awkward label than "cubic meters." Also, it's consistent with present-day cargo transportation where "tons" / "tonnes" are the standard measure unless you're dealing with a sufficient amount of cargo to measure it in [TEUs](https://en.wikipedia.org/wiki/Twenty-foot_equivalent_unit).

It's possible, even in the current game mechanics, for different outfits to have different densities, but it's strongly discouraged because it would be so confusing to the player. And if one m^3 is always one T, there's no reason not to use the simpler label.

**Comment by Amazinite** [comment]
This isn't Eve: Online.
