### ISSUE TITLE
bad Landing priorities

### ISSUE THREAD

**Issue by DanielT** [endless-sky/endless-sky#1179]
Firstly, I would expect the command to land to always apply first to the selected planet, even if it is further away.
Secondly, I've experienced situations where only one of two planets in a system was friendly / dominated, but the landing command took my fleet to the other one. Not useful.

**Comment by Gkramme** [comment]
You can scroll through the planets/moons/stations you wish to land on by pressing the land button multiple times.

**Comment by DanielT** [comment]
Sure, but that doesn't mean it shouldn't be gotten right the first time round in general.

**Comment by jafdy** [comment]
What logical order do you propose.

**Comment by DanielT** [comment]
First the selected planet, if any.
Then, *among those that will permit landing*, do whatever is done currently.

**Comment by Amazinite** [comment]
If you click to select a planet then it should already be trying to land there. Pressing your land button again is what is switching it away from landing on the planet you have selected.

**Comment by DanielT** [comment]
That's not what happens for me.
If I click on a planet it gets a blue frame. Landing happens after a double click.
There are other situations too: you've just talked to the planet and it surrendered and now you'd like to land there.

**Comment by endless-sky** [comment]
Right now, the behavior is:

* If you have no planet selected, pressing "land" selects the nearest planet.
* If you have a planet selected and it has been more than a second since you last pressed the "land" key, pressing "land" has you start landing on the currently selected planet.
* If you press "land" more rapidly than once per second, it cycles through all planets in system.

What you're proposing is that if you have no planet selected, the "land" key should select the nearest planet that you can land on, instead of the nearest planet. I'm not convinced that that's a better approach: in UI design, you want to do what is going to be least surprising to the user, and I suspect most users, if they're right near a planet and press "land," would expect that planet to be selected as the target regardless of its status. If the behavior were switched, we'd start getting lots of users saying, "The land key keeps taking me to the wrong planet."

**Comment by endless-sky** [comment]
In d34f523 I fixed some of the behaviors mentioned in this post - in particular, it turned out that pressing "land" after a long delay was sometimes still switching your target.
