### ISSUE TITLE
Save file corruption - no "planet" data

### ISSUE THREAD

**Issue by ThunderSock** [endless-sky/endless-sky#119]
When I landed on a planet this happened:
![screenshot from 2015-10-22 16 21 14](https://cloud.githubusercontent.com/assets/14982889/10677215/f3938678-78d8-11e5-9695-b076b23834e7.png)
The same thing happens every time I load that save.
(I can't upload the save file because it is a .txt , but .png is allowed?)
![screenshot from 2015-10-22 16 16 31](https://cloud.githubusercontent.com/assets/14982889/10677148/9bac7974-78d8-11e5-8539-d162ec82cb6d.png)
The problem is resolved by adding "planet Sundive" under "system Sheratan". This may have been caused because I had changed the game files. I changed the fleet frequency in Sheratan, I added credits and ships to my fleet, but I did not personally delete the planet data - I think the game did that.

**Comment by endless-sky** [comment]
Normally each individual ship defines its own system and planet. So, if
that Pug Maboro is a ship that you pasted into your saved file instead of
acquiring it legitimately in-game, it would have been missing those lines,
which may have caused this bug.

Or, is it possible that when editing the Sheratan system, you may have
temporarily added a line in the "fleet" section with the wrong indentation?
That could have made the parser assume that the system definition ended
there, causing it to ignore all the later data for that system (including
stellar objects). That may have caused the planet line to be cleared, and
it would then overwrite the saved game, causing the problem to persist.

**Comment by ThunderSock** [comment]
Okay thanks, I guess I'll close this since it does not happen anymore and it probably is not a bug...
