### ISSUE TITLE
Park/Unpark multiple ships at a time

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1192]
http://steamcommunity.com/app/404410/discussions/0/357287935554556916/

**Comment by endless-sky** [comment]
There already is a "park / unpark all" button. I feel like adding a "park / unpark all on this planet" button on top of that would be confusing.

In general, by the time a player has such a big fleet that managing it is difficult using the existing UI, they are already strong enough that very little in the game is going to be a challenge to them. And the story line is designed so that having more than one ship is not even necessary. So in terms of development time, I see it as a higher priority to optimize the early-game experience for new players. Eventually there will be much more powerful fleet management tools, but that isn't my primary focus at the moment.

**Comment by jafdy** [comment]
A Shift select option on the fleet management panel would work.

**Comment by Isaacssv552** [comment]
It would be very nice to have the shift/control selections work in fleet management as well as the outfitter/shipbuilder.

**Comment by Alkallid** [comment]
Yes, very.

**Comment by endless-sky** [comment]
As of commit 8dba537 you can select multiple ships in the info panel and park or unpark them all at once.
