### ISSUE TITLE
Sell button should sell from installed first

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1203]
If you have an outfit that is installed on your ship and you also have a number of them in cargo, the sell button will always sell from cargo first, making it difficult if you only want to uninstall the outfit but keep the other ones in cargo.

I see the reason as to why it is in this order, say you plunder the same outfit you have installed, but it would be nice to at least have an option to switch between selling what is in cargo and what is installed.

**Comment by endless-sky** [comment]
You can always sell and then buy back some of the outfits you sold, but I'm guessing that people will more often want to sell plunder than uninstall outfits but keep the plunder.

I don't want to add too many different modes and options, because that risks having a UI that's so complicated that the user can't have an accurate mental model of how it works. Better to have a simple UI, even if it means that you needs to do something a bit roundabout to accomplish certain rare tasks.

**Comment by Amazinite** [comment]
This was really only an issue at the time because I only had one ship and couldn't deselect it to put stuff back into cargo, so fixing #1161 would easily fix this issue as well.
