### ISSUE TITLE
shipyards with outfits that aren't sold on a planet may as well sell them

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1213]
If you buy a ship and sell it back its outfits become available in the outfitter which allows you to buy outfits that otherwise aren't sold at a particular planet.
While this is a natural consequence of allowing your own sold ships parts to be reclaimed before you leave port it is a little strange.
An example use of this oddity is buying a single Behemoth at Alpha Centaury and selling it back immediately, doing this a few times will create a stock of heavy laser turrets you can outfit your fleet with. This is also useful practice if you need heavy anti-missile turrets since those are sold in few locations.

Now this is more of a mechanical oddity than an issue, if you can afford a behemoth you can afford to fly to where they stock its parts, if a resolution is desired though there's a couple options:
It may be reasonable to simply make the outfitter sell the outfits of the ships the shipyard stocks, this process could even be automated since by scanning the shipyard's ship list you know what outfits are necessary.
Another option is to make unmodified ships you just bought on planet not spit back their outfits when they're sold, this wouldn't prevent people from simply leaving and re-landing and then selling the ship but that may be enough of an effort addition a person considers just flying to where the item is stocked.

**Comment by jafdy** [comment]
The first option would end up with most things being stocked most places. I am aware that that is the effect anyway but it seem unnecessary to advertise it.
The second has an even easier workaround than yours, move the parts you want before selling the hull back.

**Comment by endless-sky** [comment]
Aside from modifying the stock ships to use only outfits from the local area where they are sold, I can't see any way of changing this that would not be worse than the current behavior.

I see it as kind of equivalent to if you're shopping and something is not available for individual sale, but is available as part of a bundle. For example, a computer store that sells both parts and pre-made PCs might not individually sell all the parts that go into the pre-made PCs, because those were shipped to them already assembled.

**Comment by Bladewood** [comment]
I was going to say something about the Bactrian and sidewinders, but then I saw that Naos, which sells Bactrians, also sells sidewinders.

**Comment by MarcelineVQ** [comment]
Good points by all, it's more of an oddity than an issue but I wanted to make sure there was awareness of it.

**Comment by topromulan** [comment]
This would become less attractive if/when ships depreciate in value after purchase

**Comment by LocalGod79** [comment]
@topromulan indeed, #852 does in fact lessen the desirability of buying and immediately selling a ship to stock the outfitter - you may find that outfit a day later at half the price, or plunder a quite worn one (and lose value of the wear and tear you put on the brand new one you bought)...

**Comment by XHawk87** [comment]
> modifying the stock ships to use only outfits from the local area where they are sold

That actually sounds quite cool. Details like this make suspension of disbelief that much easier.

Shipyards could locally source fittings, or import them in bulk increasing the price of the ship. This would mean if you're using this method to get fittings outside of their normal area you're paying a premium for them.

**Comment by LocalGod79** [comment]
@XHawk87 that sounds more like part of #928, which could theoretically also be applied to ship hulls as well, making complete ships (and variants) completely dynamically priced throughout human space.

huge undertaking, though. i'm not envious of the person that needs to figure out the new "obvious balance metric", and future fleet balancing efforts get *really* complicated...

**Comment by pcordes** [comment]
As a player, buying a ship and selling it back so I could buy the outfits feels like cheating, or exploiting the fact that the sell price and the buy price are the same.  Since I know I could just fly somewhere else to get what I want, I don't mind doing it, but I can see how the game was intended to work.

The real issue here is that outfitters/shipyards don't make *any* profit, and will buy stuff from you for the exact same price they sell it for.  Even a tiny % difference is enough to make it not worth it to buy/sell a 20M$ ship to get a 100k$ outfit from it.

**Comment by geojak** [comment]
ships prices in the shipyard could be modified to be sold at
hull price + outfitts(sold here) + outfits (not sold here)*1.1

while the selling price stays as it is without the extra multiplier.

this would slightly increase the price of some ships but put a penalty on the exploit disccused here.

would "only" need to alter the price finding code for the shipyards to scan trought the outfits sold.
I imagine it doable.

**Comment by KiLEdEnNis** [comment]
imagine a giant car shop where ya can buy thousands of cars
they don't sell the individual car parts, but one could just buy several cars and have some car parts transferred to other cars at a local garage
the only unrealistic part is that ya can sell the leftover parts back, but reducing the selling price of stuff as soon as ya buy them would be very annoying and discourage using saving & loading to test various loadouts

**Comment by geojak** [comment]
Ok how about this: when an ship and outfits that are regularly not available come for sale then add an if class

If (at 100% value (non deprecated) and the item has limited amounts available) 
{set the sell price to 110%}
Else do nothing 

This would only affect items that come from new ships immidielty sold because everything else is not at 100% value anymore

So the player has to pay extra for those items ripped out of the ships

**Comment by geojak** [comment]
Oh no, can edit my typos on the phone... Hope you get what I tried to say

**Comment by tehhowch** [comment]
Switch to Desktop view, you can edit there (and also delete any posts of yours you wish to delete :wink: ).
