### ISSUE TITLE
Hai/Hai-Unfetted color swap

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1225]
Ya know it just occurred to me that it would make more sense for the color swizzle of the regular Hai to be purple and the unfetted to be orange since Hai government color shows up purple on the map. Just a thought

**Comment by jafdy** [comment]
I think the unfettered color is purple as well.

**Comment by Alkallid** [comment]
Isn't Hai pale blue on the map?

**Comment by Alkallid** [comment]
Wait nevermind, wrong aliens.

**Comment by Bladewood** [comment]
I think the current swizzles are fine as they are. The current Hai have the same color as the Republic, and just as the Republic rules human space, the Hai rule Hai space.

**Comment by endless-sky** [comment]
The government colors are partly picked to be different enough that you can tell them apart, and from that perspective it would probably make more sense to swap the government colors, not the swizzles, because the regular Hai are near to the purplish Kor Efret and the Unfettered are near to the reddish Kor Sestor.

**Comment by Bladewood** [comment]
...wait, so who represents the Kor Mereti?

**Comment by jafdy** [comment]
Merchants. There both blue.

**Comment by endless-sky** [comment]
By "near to" I just mean physically close on the map.

**Comment by mdsmestad** [comment]
@endless-sky I said swizzle, but just color swap is what I meant.

**Comment by endless-sky** [comment]
Fixed in b9a990c.
