### ISSUE TITLE
Prioritize boarding/repairing capital ships over boarding/repairing drones/fighters

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1229]
It's annoying how we always default to repairing combat drones instead of their own Carriers when we fight the Pug for the first time.

**Comment by MarcelineVQ** [comment]
This is consistently an issue when a system becomes littered with Kor Mereti drones and fighters and you want to try to grab some big ships before more warp in. Prioritizing by ship credit value would be a possible solution.

**Comment by toilethinges** [comment]
Well, @MarcelineVQ, I have more of the problem of having Met Par Tek 53s littering the entire system, stopping me from being able to get fighters/drones (which I will likely never deploy, because it takes forever to get more.)

**Comment by Alkallid** [comment]
It could be a toggleable preference

**Comment by MarcelineVQ** [comment]
@toilethinges
Hehe, well, that's certainly the flip side. Though as fleets enter there would typically be less Tek 53's than fighters/drones which means less targets to clear if you need to. By the time you're killing Sestor fleets, afaict, the time it takes to position your ships to fire on disabled units uses more time than finishing them off.
So far during play anytime I'm not just hunting for fighters I would have preferred that 'b' chose something more expensive so I can board it quickly, usually because my escorts tend to blow them up due to their size causing them to be in the way and I have trouble using my mouse (to pick out ships) and keyboard at the same time in the game.
Possibly the solution to that is simply a more comprehensive keymapping interface so wasd can be used for steering.

Currently when you hit 'b' without a target selected it chooses whichever enemy is closest to you and since fighters tend to outnumber other ships they're more likely to be nearby and are chosen first. Nearest-ship is a good middle ground to account for various playstyles but it can sometimes be frustrating. I wonder if it would naturally be alleviated by being able to zoom out so your mouse can click on specific ships easier.

**Comment by LocalGod79** [comment]
@MarcelineVQ #814 contains conversation relevant to your last paragraph

**Comment by tehhowch** [comment]
This could be achieved by weighting the target range by either the mass or the cost of the ship in question. I'd probably opt to use a sqrt or log function on the weighting factor so that range is still an important part in choosing the boarding target.

**Comment by endless-sky** [comment]
The trouble is that "board closest ship" is a much easier concept for the player to grasp than "board ship with highest ratio of cost to distance" or something like that. In general, I try to avoid having the game do something "smart" that just ends up seeming random or inscrutable to the play. (I can guarantee that if such a change were made, a lot of people would start complaining that the "board" key seemed to be selecting random ships.)

**Comment by tehhowch** [comment]
I think if done right, biasing based on mass or cost would not be unintuitive. I think (hope?) players are smart enough to figure out after a few presses in a cost-weighted scheme that the game is "helping" them by prioritizing more valuable targets when being given a "generic" board command.

A compromise could be to make pressing the board key advance through a list of boarding targets (which would probably have to be rebuilt every press, or at least indexed to a point and rebuilt if too far away) so that (with a bit of keypressing), the selection of a capital ship while tiny ships are nearby is at least possible.

**Comment by jafdy** [comment]
You have far to much confidence in the intelligence of players. There are lots of people who can't work out how to make the map come up, even after being told to press M.

**Comment by 22144418** [comment]
It would be best as a toggle option, alternating between "most valuable" "closest" and "lowest remaining health percentage" in the settings.
