### ISSUE TITLE
[bug/question] Automatons respond to hails...

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1230]
...for help, and try to fly over you, but can't repair you. My two problems with this:

1. Drones (automatons) are unmanned - how can they respond to hails for help, and actually do this?
2. The answer to number one is that they are programmed to respond for help hails, and to repair the ship - _but they can't do it._

This can be fixed by either not letting you hail/ask for help from drones, or making them able to repair you.

http://steamcommunity.com/sharedfiles/filedetails/?id=702438283
http://steamcommunity.com/sharedfiles/filedetails/?id=702438317

**Comment by Bladewood** [comment]
I'm pretty sure this also happens with fighters.

**Comment by jafdy** [comment]
That's fine for maned fighters. Probably best to make them able to repair to make it future proof.

**Comment by wambat1** [comment]
this is an issue with Earth Shapers as well, and they have hyperspace fuel they will not give you either.

**Comment by wambat1** [comment]
this is an issue with Earth Shapers as well, and they have hyperspace fuel they will not give you either.

**Comment by jafdy** [comment]
If your using a jump drive it's because they only have 300 fuel themselves.

**Comment by Bladewood** [comment]
Earth shapers use hyperdrives, not jump drives, so if they just left a planet and you just jumped in, they could give you 200 fuel for your jump drive and leave with their 100 fuel for their hyperdrive.

**Comment by MarcelineVQ** [comment]
Fighters/Drones can't complete a dock with you because in Ship::Move their docking target check prevents them from docking with anything but their parent.
`Ship.cpp:1109: shared_ptr<const Ship> target = (CanBeCarried() ? GetParent() : GetTargetShip());`

While just changing that line will allow them to complete their dock, it may have unseen implications in the boarding logic since there's a couple special cases for fighters/drones strewn about Ship::Move, Ship::Board, and AI.cpp. Because of that I'm not confident in doing the fix, but maybe having it narrowed down helps you @endless-sky ?

This is the mission I used to test:
[fighters.txt](https://github.com/endless-sky/endless-sky/files/328714/fighters.txt)

**Comment by endless-sky** [comment]
I think it's reasonable that drones could be programmed to assist you. In commit 438be57 I've fixed two problems addressed in this thread:

* Drones and fighters are now able to assist ships other than their motherships.

* If you as a ship with "surveillance" personality (such as an Earth Shaper) for help, they will now tell you they are too busy instead of promising to help and then ignoring you.
