### ISSUE TITLE
Lost allied ship

### ISSUE THREAD

**Issue by JohnDFord** [endless-sky/endless-sky#125]
So one of my allied ships got disabled in a uninhabited system, is there any way to get it back?

**Comment by endless-sky** [comment]
If pirates haven't yanked out its engines or its hyperdrive, you can go back to that system and repair it by clicking on it to target it, then pressing 'B'.

**Comment by CubicDolphin** [comment]
On that note, what if it HAS had its hyperdrive yanked out? I disabled and captured a pirate ship, accidentally taking its hyperdrive out when doing so. Now it can't leave that system, I can't equip it with a new hyperdrive because the system it is on has no Outfitters, can't sell it because no shipyard, and it has a crew member on board that is charging me per day. Is there any way I can put a new hyperdrive in, or destroy it?
