### ISSUE TITLE
Suggestion: When landing, prioritize planets with more "utilities"

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1274]
For example, I would normally prefer landing on Glaze instead of Charon Station, since Glaze has a shipyard and an outfitter, which Charon Station doesn't.

**Comment by jafdy** [comment]
Just double tap `l`. the mechanic was changed after someone complained about the previous way it worked.

**Comment by MarcelineVQ** [comment]
It's going to be different for everybody, I'd prefer it to land on planets which will complete missions with the least time remaining, then any mission location, then by utilities as you suggest.

On the subject, fairly often I get the "You can't land on a gas giant." and the like and until you asked this question I had no idea it was because I was directly on top of them and that it was a special case of being on top of them and not some failure in planet targeting.

**Comment by Bladewood** [comment]
> I'd prefer it to land on planets which will complete missions with the least time remaining, then any mission location, then by utilities as you suggest.

Yes, this is what I'd prefer as well.

**Comment by XHawk87** [comment]
Total planet mission payout is also a consideration.

**Comment by Alkallid** [comment]
What about major or minor spaceport missions? Priority under time, I'd say?

**Comment by LocalGod79** [comment]
ftr; the current priority (when no missions are active in the system) is alphabetic.

**Comment by endless-sky** [comment]
If the criterion for deciding which planet the "land" key selects is too complicated, it's just going to seem random to the user and they will not be able to figure out why it is selecting whatever planet it selects. Right now it just selects the nearest inhabited planet you can land on, which is already slightly more complicated than I'd prefer.
