### ISSUE TITLE
Steam Cloud Save? [Question]

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1279]
Anybody has an idea how difficult it may be to enable it for the game?

If not, i can look it up, it would just be a major quality of life improvement for the ravening hordes.

**Comment by endless-sky** [comment]
Steam's API is secret and is shared with Steam developers only on the condition that they do not share the details of it with anyone else. Publishing code that accesses their API would certainly count as an infringement of that agreement, so the only way to support Steam saves would be if the Steam version of the program was closed-source - which would create all sorts of new licensing problems because every contributor would have to agree to releasing a closed-source version. So, it's very unlikely to happen. 

The only realistic way it could be done would be to have some sort of closed-source "parent" program that is launched by Steam, which is just responsible for updating the Steam saves, then launching Endless Sky, waiting for the game to quit, and updating the saves again.

**Comment by MarcelineVQ** [comment]
If anybody is interested in the api and doesn't have a steam partnership to check it out with: valve has made it available to peruse in the "[src/public/steam](https://github.com/ValveSoftware/source-sdk-2013/tree/master/sp/src/public/steam)" dirs in source-sdk-2013 on ValveSoftware's github repo. I doubt it's current but it's likely pretty cool.

**Comment by mdsmestad** [comment]
So because of how the licensing for Endless Sky is set to open source, could you legally change the licensing if you wanted to?

**Comment by jafdy** [comment]
But then it would be harder for everyone to work on it.

**Comment by Wrzlprnft** [comment]
I'd like the workaround solution since the licensing on ES shouldn't be changed.
but, up to the point where someone actually does the hole lot of work, i'd say ill leave this open, but resting.

**Comment by lheckemann** [comment]
@mdsmestad Almost every one of these people https://github.com/endless-sky/endless-sky/graphs/contributors is a copyright holder on Endless Sky (although my contribution so far has been next to nothing so maybe not myself). In any case, you would need all of those people's consent, or to remove all of their contributions, in order to be able to relicence Endless Sky under a proprietary licence.

For the wrapper, I'm not sure even that would be OK, because the whole program (wrapper + ES) is definitely a derivative work of ES, and the GPL is a bit particular about even *combining* with proprietary software.

**Comment by endless-sky** [comment]
The "wrapper" would have to be a completely separate program. Then there would be no licensing issues, the same way that a GPLed OS can launch a proprietary program. So legally speaking it would be doable, but given how invested I am in the game being open source I'm probably not going to put a lot of effort into integrating it with a proprietary API any time soon.

**Comment by jafdy** [comment]
On a slightly related note, would it be possible to use Steam's mod service (or whatever it's called)?

**Comment by Wrzlprnft** [comment]
The problem with that is that plugins aren't steam only. So if we use the workshop, the game inevitably gets connected to steam.

**Comment by jafdy** [comment]
I have several games where I have mods from steam and mods from other sites. It appears that steam can put files in a specified folder.

(Sorry for delayed response, I have been on holiday.)

**Comment by jafdy** [comment]
This looks new. I don't think it was there when I looked into it.

**Comment by tehhowch** [comment]
Looks promising to me. Can possibly also sync a player's plugins as well, depending on the directory passed to the auto-cloud.

**Comment by jafdy** [comment]
Heck, it might even let us have workshop support.

**Comment by KiLEdEnNis** [comment]
yeah it'll make mods easier to install for new players, if it works it'll be a great improvement

thanks for telling us @frymaster

**Comment by endless-sky** [comment]
That does look like it would work. It could also be set up to sync any local plugins, but you need to specify the maximum number of files and total size for each game for Steam Cloud, and I'd be a bit worried about what would happen if a plugin only half-fits within that quota.

Right now each saved game snapshot can be as big as 0.2 MB. Does anyone know how much storage space per game would be typical for Steam Cloud?

**Comment by tehhowch** [comment]
I can't answer that bit, but we could trim down filesize with a function that trims the `changes` node to the minimum necessary.
I.e. it takes as input the player and does a comparison between the newgame state and the current state, returning the minimal change. 
We'd need to define a subtraction operator for the game classes.
There could be some issue with mods but I think if the compared object doesn't exist in GameData then we know it applies to a currently removed mod item, and should be preserved as-is.

**Comment by lheckemann** [comment]
The save file format is also extremely verbose and as such compresses rather well. In a very unscientific test I just did, I got a 600k save down to 40k, and I presume most saves would be similar in terms of compressiblity. But a few other games I have in my library use ~10MB or so per save game so I don't think even 0.6MB would be a problem.

**Comment by Shanesan** [comment]
Should this be reopened for a reval?

**Comment by MCOfficer** [comment]
bump - if it "could work", this should definitely be reopened.

in my book, 0.2MB is acceptable for up- and download, so we might not even have to cut down the savefile.
if do, however, i want to throw deflate compression or something similar into the ring.

**Comment by zikalify** [comment]
Is there anything happening with this? If not, I think a save importer and exporter in-game would be nice so it's easy to move saves between devices.

**Comment by MCOfficer** [comment]
Steam Cloud support is now live. Apologies for not reopening this while we were looking into it.
