### ISSUE TITLE
Credit Score can be raised artificially

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1280]
One steam review mentioned that, after paying the initial mortgage back, one can get a 200 credits loan, and pay it back credit per credit to improve the credit score. I don't haven't double checked this.

Edit: http://steamcommunity.com/id/Inaptitude/recommended/404410/

**Comment by Joeppie** [comment]
I can confirm this. 

So long as you make good on your payment to the bank, your credit score improves.
Perhaps the credit score should be weighted, so that it looks at the amount of payments made; a 200 credit loan might still improve the score, but maybe 50 times less fast than a 2 million credit loan would?

**Comment by XHawk87** [comment]
I don't know if this is really a major exploit. It doesn't take long to max out credit score at which point there is no reason to keep a loan that you can simply pay off. The amount you save most likely won't add up to much in the long run.

Nevertheless, it doesn't entirely make good sense that you'd gain credit score for making payments on loans that are a tiny fraction of your income. Fixing little immersion-breaking details like this can make a game feel more polished, so if it can be addressed quickly, I don't see why it shouldn't be.

**Comment by Joeppie** [comment]
>Fixing little immersion-breaking details like this can make a game feel more polished

This is what irked me; as a programmer, I was tempted to try and 'exploit'  this, to become more immersed and impressed if it had indeed failed.

What if for the 'credit gain' there was a function like the following pseudo involved?

> score +=  gain * ( Math.Min(score,maxScore-100)/maxScore).

A 20 base gain at 400 would only get you a nett gain of 10 creditscore extra, and the same gain with a credit score of 700 and height only gets you 2.1875 ~= 2.

The base gain would need to be tweaked a bit, I guess, and could depend on the amount of payments made to crew/bank. (I've no idea if crew already works into credit score)

However, If credit is an integer, this might be punitive/cap out creditscore below 800, and it would ruin my little scheme for sure.

**Comment by XHawk87** [comment]
It would appear that the credit score is indeed an integer, clamped between 200 and 800. It rises by 1 per day while you have debts that are being paid, and down by 5 if you have debts that are unpaid.

https://github.com/endless-sky/endless-sky/blob/c7338a29288de7516884057cf53029af120195cb/source/Account.cpp#L187

**Comment by Joeppie** [comment]
Hmm tricky..

Perhaps the current credit score should only account for a part of the total credit score, and other factors should take a role: a fighter ship should be seen as riskier than a cargo ship, which should be seen as riskier than a passenger transport.. perhaps armaments would reduce this risk. Other factors such as payment/income history and traveled systems might also play roles.

Theoretically, It would be great for immersion if you could see this kind of risk reflected and was visible, albeit difficult to integrate in the code that obviously only deals with the financials :)


--------------

But that would be a feature, not a fix :) - Perhaps a minimum to the payments in order to improve credit score is a good short-term fix. That way I can't boost  my credit score from 500 to 800 for a lowly 300 credits.

**Comment by endless-sky** [comment]
Think of this a different way: if credit score did *not* increase when paying off a tiny loan, then the game would essentially be penalizing you if you pay off your loan early. By allowing a player to use this trick, someone who pays off their loan early will reach the maximum credit score at the same time as someone who just puts the minimum into their loan every day.
