### ISSUE TITLE
In the Pug galaxy, ramscoops appear to be more effective when near the wormhole than when near the stars

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1281]

**Comment by jafdy** [comment]
The wormhole counts as the star as for as the game is concerned. Both are just sprites.

**Comment by Bladewood** [comment]
Yes, I figured as much.

**Comment by MarcelineVQ** [comment]
Ramscoop and solar collection effectiveness is determined by the ship's distance from the center of the system it's in. Typically what's at the center is a star. You can see this with the stars in map.txt, they don't typically have a distance attribute, meaning they're at the system's center.

Of the wormholes I could find in the game's data directory only the "Over the Rainbow" system has a wormhole in the center with a star orbiting it. In that case the wormhole will indeed be the 'source' of the fuel for your ramscoop, because it's in the center.
