### ISSUE TITLE
[Bug] (content) Militia defends republic planets during war

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#1289]
Planets in the Dirt Belt that are members of the Republic will still have Free Worlds Militia fleets defending them if tribute is demanded during the Free Worlds war. This seems a little odd... :)

**Comment by Disiuze** [comment]
Neither the Free Worlders nor the Republic have fleets in that area, so it kind of makes sense.

**Comment by Amazinite** [comment]
Not all system members of the Republic are defended by the Navy. This was the whole reason for the Free Worlds being created. It would just appear that some planets in the Dirt Belt were fine with having to use local militia as defense fleets and didn't want to leave the Republic, probably because the amount of piracy in the Dirt Belt is not as high as in the Free Worlds areas.

**Comment by lheckemann** [comment]
I don't see how this makes sense during the war though, where the planets are regularly patrolled by Navy fleets and there's not a trace of green to be seen around there until tribute is demanded... And isn't the Militia associated with the Free Worlds?

**Comment by Bladewood** [comment]
The South's militia, yes, but not necessarily the Dirt Belt's militia.

**Comment by Amazinite** [comment]
The militia of the south became the Free Worlds, but being part of a militia does not directly correlate to being part of the Free Worlds. Can they are being patrolled by Navy fleets, but that's just one or two ships visiting the system every one in a while, not an entire defense fleet being present.

**Comment by toilethinges** [comment]
What Amazinite said.

By Militia, it doesn't mean the Southern Defense Pact (that is, the ships that run around before Free Worlds). It just means the same thing as militia in reality - citizen soldiers, rising up to protect their homeland. The citizens of said planet jump into ships and embark to fight against the invaders.

**Comment by lheckemann** [comment]
I see, so they're green but not connected to the Free Worlds. But @Amazinite I wouldn't say it's just one or two ships visiting, I experienced quite a significant Navy presence. The hard way :p

**Comment by Jojobees** [comment]
This should not be closed, because they *ARE* connected to the free worlds. If you demand tribute from these 'republic' systems during the war you become hostile with free worlds, which just doesn't make sense.

**Comment by jafdy** [comment]
Suppose you are a security guard working for some bank and you have heard about a person who would turn up at a bank, shoot any security guards and take any cash they can find. What would you think if this person turned up at the bank you were working at? You have two options:
A: Assume that because he hasn't attacked any of your bank's branches he won't shoot you.
B: Assume that because he has attacked other bank's branches that he is going to try to shoot you.

Lets consider this example in the context of ES. Suppose you are in charge of a militia fleet of a Free Worlds planet (the entire free worlds force is effectively a militia) and you have heard about a person who turns up at a planet, kills the entire militia and take a constant "tribute" from that planet. What would you think if this person turned up near your fleet? You have two options: 
A: Assume that because he hasn't attacked any Free Worlds planets he won't shoot you.
B: Assume that because he has attacked other militias that he is going to try to shoot you.

**Comment by Jojobees** [comment]
@jafdy I'm a member of the FW parliament and the world is a republic controlled world... Even if what you said was true it should still be in the lore somewhere, or you should be able to find out who is defended by militia and who is defended by the navy so I can get tribute from the right worlds.

**Comment by MCOfficer** [comment]
i doubt that needs a mention in the lore, after all it's the very definition of the word militia. the interaction between the navy, dirt belt and paradise planet could be highlighted more outside of story missions, though.

> you should be able to find out who is defended by militia and who is defended by the navy so I can get tribute from the right worlds.

that is probably not going to happen, tributes are not currently the focus of this game and thus won't receive that much attention.

**Comment by Jojobees** [comment]
Yes, the interaction should be highlighted more outside story missions. I completely agree. And on the subject of tributes, they should be higher, and so should my per diem as a member of the FW parliament. I can only afford to hire 25 crew members on my per diem when a bactrian requires 75 ish and can hold more than 200.

**Comment by MCOfficer** [comment]
a bactrian for the initial FW missions is overkill, you do get a raise later in the story, enough for a heavy warship.

**Comment by Jojobees** [comment]
Umm... It's underkill for many missions where I'm at, I need my entire fleet, which includes the bactrian, and several navy frigates, cruisers, and carriers. And I'm making 2,500 per diem while my fleet costs me 165,000 per diem.

**Comment by jafdy** [comment]
The simplest solution to this problem is to delete the tribute system entirely, because it doesn't really fit within the game's vision anyway.
