### ISSUE TITLE
Engaging cloak in animated ships skips frame

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#1309]
I built an animated ship the other day, and tried engaging cloak. It still works of course but instead of "phasing" out it just blinks into the cloak which looks odd.

**Comment by Alkallid** [comment]
This? https://github.com/endless-sky/endless-sky/pull/1308

**Comment by endless-sky** [comment]
That's because the cloaking fade uses the same mechanism as the animation frame fade - that is, right now the OpenGL shader for sprites takes two images to fade between, and cloaking is implemented by giving it a totally transparent image as one of the two frames. That could be changed, but it's not terribly high priority at the moment.

**Comment by mdsmestad** [comment]
@endless-sky But didn't this just get fixed w/ your last pull?

**Comment by endless-sky** [comment]
There's two separate issues. The #1308 PR fixed a new bug that was introduced (in the 0.9.3 working code, not the released code) that broke the cloaking fade completely. But there's a second issue that while cloaking, an animated ship will jump from frame to frame rather than fading smoothly between them.
