### ISSUE TITLE
circumventing death benefits

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1319]
I have another "bug" (more like circumventing boarding mechanics):

if you board a ship and capture it after taking casualties, you have to pay death benefits

if you board a ship, kill as much enemies w/o capturing (and losing crew), retreat, press done, board AGAIN and then kill the few enemies to capture the ship, only the casualties from the last boarding count

for example: you can board a cruiser which has 84 crew, you have 160, you kill 20 each attack while losing 3 yourself, you can attack 4x, losing 12, killing 80, retreat & press done, THEN board again, kill the 4 others w/o losses; no death benefits
can that be classified as a bug? (it's technically not a bug)

**Comment by XHawk87** [comment]
I'd call that an exploit. 

For clarity, you may want to rename it to "Death Benefits" rather than Mortgage, as a Mortgage is only the voluntary type of loan, the others being fines and death benefits.

**Comment by KiLEdEnNis** [comment]
oh yeah thanks

**Comment by endless-sky** [comment]
The thing is, if you board a ship, try to capture it, fail, and half to limp away with half your crew dead, I don't want you to have to pay death benefits on top of that. So, there are two ways this could be addressed:

1. Make the player pay death benefits when they fail a capture attempt (more realistic, but annoying).

2. Track how many crew the player has lost in previous boarding attempts for any currently active ships (doable, but adds a lot of complexity).

**Comment by KiLEdEnNis** [comment]
the second one should actually be the right fix, but if people want to cheat they can edit their save file either way
good luck fixing it, love your game :D

**Comment by XHawk87** [comment]
At the moment if you try to capture a ship, lose crew, succeed and then it gets blown up before you can get it back to port, you pay some hefty death benefits without anything to show for it. Granted most people would just reload at this point, however if ironman/hardcore/permadeath type features are added later this would make boarding a ludicrously risky endeavour, given how vulnerable ships are just after capture. 

Perhaps death benefits should paid out on the value of all captured ships that make it back to port, based on the total crew killed since setting out? For this, you would just need a flag on each ship as captured and a record of number of crew when leaving a port.

**Comment by KiLEdEnNis** [comment]
no what I mean is you can board a ship, kill off almost all crew, retreat & press done, board again, kill the few remaining without any losses, and you have no death benefits to pay

**Comment by XHawk87** [comment]
I am fully aware of what you meant and agreed it was an exploit. I am now highlighting two additional related issues and proposing a fix that would solve all 3.

**Comment by davidwhitman** [comment]
Your proposed fix could have unintended side effects down the road, though. A feature could be added that modifies the number of crew on board while you're still in space (for example a story mission where you jump into a system, bomb goes off on your ship, and you need to fight with ship partially disabled), and that would cause the benefits to be incorrectly calculated when you landed. Basically, it adds some state to the game, and it's always better to aim for statelessness if possible. 

It also causes some "annoying" behavior, as the dev put it, where if you lose 100 crew boarding, abort the board, then capture a different ship, you'll still have to pay death benefits for the crew in the boarding attempt you abandoned. While I think that's realistic, it seems counter to what the dev wants. 

I don't have a good answer, other than the dev's #2 solution.

**Comment by KiLEdEnNis** [comment]
I wasn't sure if it really needs a fix anyway, it's singleplayer so it doesn't matter, and if people want to cheat, they can edit the save file (I heard someone speak about hardcore mode or whatever too), so unless they encrypt the save file (which would be annoying) people can always cheat, although it's their choice

**Comment by davidwhitman** [comment]
Just because you can cheat, it doesn't mean that balance doesn't matter. It probably doesn't even cross the mind of most gamers that they could find a save game on their computer, open it as a text file, and edit it. 

This game is about the journey, not about scoreboards. If the journey has issues, then the game is flawed. 

This is off topic, but I wouldn't mind seeing a *hidden* option to encrypt your save file.The game would read/write to it in binary. The option would have to be hidden because there's no reason to tip people off that there's a possibility of editing their save file - simply knowing that you can cheat will taint the game experience for many people. 

Anyway, I'm sure MZ will decide on a solution for this.

**Comment by KiLEdEnNis** [comment]
what I mean is that if someone wants to cheat (s)he will do it anyway, but I didn't say Endless Sky should tell people how or anything

**Comment by XHawk87** [comment]
A lot of people want to play the game fairly in single-player for the challenge. However where exploits exist, there is often a grey area about whether or not it is an intended or allowable feature. 

Closing exploits in single-player isn't as much about preventing cheating than it is about explicitly defining the rules of the game so that people can enjoy the challenge the way the developers intended. 

There are also a lot of players who would prefer not to be tempted to cheat with an easily accessible exploit, as by using it they rob themselves of some of the challenge, some of the experience, and come to regret it later. Making it more difficult to cheat can make the game more enjoyable.

**Comment by KiLEdEnNis** [comment]
yes I know (sometimes I "cheat", but that's mostly just removing licenses from Navy ships & having 1 planet sell more stuff since I hate flying around an hour just to make a new ship), but this exploit isn't well-known, and I didn't think it'd be that important, but reported it anyway in case it's gonna be changed
