### ISSUE TITLE
[enhancement] Government personality tags...

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1322]
...similar to fleet tags, but affecting reputations towards you and other governments:
1. "never friendly" which makes it where you can't go over -1 reputation, or doesn't let you gain reputation at all.
2. "murderous" which makes it where this faction is hostile with all other factions in the game (this could include things in plugins, too, but preferably excepting the Bounty faction).
3. "greedy" government's reputation is affected by the worth of the ships that you destroy (similar to combat rating) instead of the number of people killed (@Amazinite).
4. "always friendly" exact opposite of "never friendly," where a government can't go below 1 reputation, or can't lose reputation (@Amazinite).
5. "abhorrent" this government kills everything in sight, including its own ships (@Amazinite).
6. "pacifists" opposite of murderous, friendly to all other governments.
7. "homebound", "fleets with this tag will only enter sectors that their government owns (or uninhabited sectors maybe?)" (@KiLEdEnNis)

Perhaps also let them be changed by events (FW campaign, add never friendly tag to extremists and such). 

This could open up many new possibilities, but I can tell this might take a lot of code changes.

I will add any tag suggestions here to the original post.

**Comment by Amazinite** [comment]
"Pacifist": although already a fleet personality, maybe also have this be the opposite of murderous and make every single ship of a government friendly to all others. 

And another thing, we should probably choose whether or not fleet personalities supersede government personalities that may conflict.

**Comment by endless-sky** [comment]
Governments already have "penalty for" tags (although they aren't used in any of the existing game data) which lets you change how severely they respond to different actions. That can be used to create a government where your reputation never changes regardless of what you do to them.

I suppose I could add a "default attitude" tag. That would specify the government's attitude toward anyone not specifically listed in their "attitude toward" section. But that would cause odd reputation effects with the player, because everything of any faction that you killed would affect what that government thought of you.

**Comment by KiLEdEnNis** [comment]
pacifist should still fire back after being hit (although pairing it with forbearing may help) (good idea)

always friendly should only be applied to escorts though, unless MZ adds content where you can conquer some planets & actually govern them, and have your own ships patrol which would get the tag, so this one seems a bit bad

I don't see why abhorrent is a good idea though, except if there are plans of having an alien species that became an anarchy (and even then the ships of 1 fleet should still stay friendly to each other as they are escorts)

for the rest I see possibilities, great idea in fact, and the "never friendly" tag could fix Extremists/Alpha issues, and such upcoming issues

**Comment by Alkallid** [comment]
Pacifist is meant to oppose conflict. That would make it just the default friendly personality.

**Comment by Amazinite** [comment]
I thought of abhorrent when also thinking of making a storyline that involves some faction infighting. It isn't something that would be used for any current content, but could be used later on. As for pacifist, the whole point of being a pacifist is tha you don't fight at all, so it would be exactly like the fleet personality.

**Comment by KiLEdEnNis** [comment]
after saying that about the pacifist it seems logical, but it's weird that ships would stay friendly while you are destroying them, since anyone would either fight, bribe or run

and about abhorrent, he described it that they shoot every ship, even their own
"infighting" means there are several small factions within a government, but abhorrent would mean every individual ship shoots at everyone, so it's not do-able, the only way is to create sub-governments, meaning that fleets are all one government but are hostile to others

**Comment by Amazinite** [comment]
Yes, a pacifist government would run at the first sign of trouble. It doesn't mean that they sit there and die while doing nothing. 

And the usability of the abhorrent tag is all dependent on the story that it's used in. While infighting does involve different factions, exactly like how the civil war works, there could be times when there's mass confusion as the fighting first starts, or it could be used to leave the player in the dark as to what is going on. Say you enter a system and a ton of pirates are fighting each other. There's no way to differentiate between any of them and they all have the same government. Instead of having having to make a bunch of different pirate governments with different numbers of spaces to make them look the same, you just have the single government with the abhorrent personality to create that same effect. It would be likely that the abhorrent personality would effect fleets, so that within a single fleet the ships are friendly to each other but they are hostile to all other fleets of the same government. And in that case it would probably be better off as a fleet personality as opposed to a government personality.

**Comment by KiLEdEnNis** [comment]
abhorrent as fleet personality is a great idea yes, and after you explaining the others a bit I see a lot of options for new mission types, so I hope it gets added

**Comment by KiLEdEnNis** [comment]
just got an idea for another tag
"homebound", fleets with this tag will only enter sectors that their government owns (or uninhabited sectors maybe?)
so fleets that people want in their own sectors don't move to hostile space

how I came up with it; since I'm editing some stuff & added a part of space, and I made 2 fleets that are intended to stay in their space (transport & defense fleet) it's annoying that they move to hostile sectors

I don't know if that's do-able but it'd sure be a nice addition

**Comment by Wrzlprnft** [comment]
As far as i know fleets are already bound to the systems they are defined to appear. Except they are mission fleets.

**Comment by Alkallid** [comment]
But they can be chased out or jump out. I think this would be a no-flee thing.

**Comment by KiLEdEnNis** [comment]
yes that they can appear in their sectors, but if they flee, they only flee to their OWN systems, so they can't be chased into enemy space, so basically they'll never move out of their space (because what would a transport fleet do in an empty hostile sector to get annihilated)

**Comment by Alkallid** [comment]
The Pug have jumped to Earth before. I chased a Sparrow into the deep Deep.

**Comment by KiLEdEnNis** [comment]
also, maybe a "patriotic" or whatever, fleets with that are friendly, but hostile in home sectors

**Comment by Amazinite** [comment]
A lot of these seem like they're actually possible now.

> "never friendly" which makes it where you can't go over -1 reputation, or doesn't let you gain reputation at all.
> "always friendly" exact opposite of "never friendly," where a government can't go below 1 reputation, or can't lose reputation

This can be achieved by making it so that the government has no enemies that you gain reputation for attacking, change the `"penalty for"` so that you can't gain reputation for assisting them, or the reverse for "always friendly".

> "murderous" which makes it where this faction is hostile with all other factions in the game (this could include things in plugins, too, but preferably excepting the Bounty faction).
> "pacifists" opposite of murderous, friendly to all other governments.

Now possible with the `"default attitude"` node added by #9438.

> "abhorrent" this government kills everything in sight, including its own ships

Not possible at the moment, although we do simulate this with multiple governments that display with the same name.

> "homebound", "fleets with this tag will only enter sectors that their government owns (or uninhabited sectors maybe?)"

Possible with travel restrictions.

> "greedy" government's reputation is affected by the worth of the ships that you destroy (similar to combat rating) instead of the number of people killed

This is the only one that's not possible at the moment, although having a single idea for a personality that a government could have doesn't seem like much of a feature.

**Comment by Amazinite** [comment]
Closing, as I've moved the one feature request that still isn't possible to #9764.
