### ISSUE TITLE
Allow different damage types of the same projectile to have different blast radii

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1328]
Is there already an attribute implemented under "weapon", such that it can cause a ship to deal ion damage (or perhaps some other obscure damage type) on explosion?

If not, can you add it?

On a note that may or may not be related, can you make it such that I can define ranges for damage types separately? (e.g. I want to make an explosion to deal shield damage over a huge area, but to only deal hull damage within a relatively small area)

**Comment by MarcelineVQ** [comment]
Since base ship attributes are stored as an Outfit type the ship weapon should be exactly the same as an outfit weapon, it's just that it's fired once on death. So any stat you can find on an Outfit weapon should be usable.
An example explosion weapon like you seek might be:
```
weapon
	"blast radius" 600
	"ion damage" 20000
	"shield damage" 800
	"hit force" 500
	"submunition" "MyShipsHullExplosion" 1
```
```
outfit "MyShipsHullExplosion"
	weapon
		"blast radius" 200
		"hull damage" 300
```

I haven't tried this but I don't see a reason why it wouldn't work, so give it a shot.
I thought it would be kind of cute if the Flycatcher launched anti-missile submunitions on death.

**Comment by Bladewood** [comment]
I have never thought about designing an explosion that way, you are a genius.

**Comment by Bladewood** [comment]
...
Up until now, I was too lazy to check to see if this actually worked. And now I just checked.
It doesn't.
> [ship stuff]
	weapon
		"blast radius" 3600
		"shield damage" 2000000
		"ion damage" 100000
		"hull damage" 40
		"hit force" 200
		"submunition" "Hull Explosion" 1

> outfit "Hull Explosion"
	weapon
		"blast radius" 175
		"hull damage" 7500
		"hit force" 20000

(It's indented, don't worry.)

The shield explosion has an absurdly long range, dealing immense damage to shields while also dealing extreme ion damage, but with very little hull damage and very little force. It also has a submunition, with a comparably short-ranged but powerful hull explosion.

I found out that the submunition's damage also applied to the shield explosion.

Proof: I used it in the solar system.
After the ship exploded, every single ship in the system was destroyed (except for my own, I was flying an Archon, though it was still disabled via ion damage).

**Comment by endless-sky** [comment]
If a projectile hits something, all the damage its submunitions do is also dealt to its targets, because the submunitions are still "inside" the projectile at that point. (Otherwise, weapons like the Proton Cannon would deal no damage if they struck a ship right after being fired.

You could achieve the effect you want by making the projectile split into two submunitions immediately after being fired. Have one be invisible, and use your normal projectile sprite for the other. Don't alter the velocity, etc. of either one, so that they actually fly along exactly the same path. Have one submunition do the ion damage, and the other make the explosion.
