### ISSUE TITLE
bribing is only 1.000 credits if net worth is above 2B

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1342]
so I bribed an Unfetterd Hai planet & ships in the Alpha Surveillance story; both bribes were 1000 credits, my save file says my net worth is 2B (it is 3,5B), and because bribing is scaled on net worth (if I am right), it's related to this

**Comment by MarcelineVQ** [comment]
It's scaled on the size of your unparked fleet and essentially 1000 is the minimum bribe you can pay.
Specifically it's the square root of your fleet's total value times the bribe value of the planet or government you're bribing, rounded down to the nearest integer and multiplied by 1000.
Or more tersely:
`bribe = 1000 * static_cast<int>(sqrt(value) * scale);`

The unfettered don't have bribe values for their planets so it'll be based on the government bribe value, which is 0.02
Given that value it would only take a fleet valued at 4000 credits to cost a 2000 credit bribe so something is off. I suspect an overflow of int since it's only guaranteed to count up to 2,147,483,647 (2.15B) worth of value.

**Comment by KiLEdEnNis** [comment]
I have about 2.35B net value (although all escorts are parked), if the count can't go higher then at least make it so that if you are above the max you have to pay as if you had the max

**Comment by endless-sky** [comment]
Fixed in #1347 and future-proofed in 3afff1b.

**Comment by Sinsling** [comment]
I just downloaded the most recent build, and attempted to compile, but received this error pertaining to the bribe line:

HailPanel.cpp error: " 'sqrt' was not declared in this scope."

I am on windows 10. Found it interesting that I located an update pertaining to the error line I am recieving.

**Comment by MarcelineVQ** [comment]
Does adding
`#include <cmath>`
under
`#include <algorithm>`
allow you to complile?

**Comment by Sinsling** [comment]
It allows me to move past that error.

I now get the same error for lines 301, 308, and 448 in MapPanel.cpp for log and pow.

Is this related to windows 10 or simple some missing lines that are not included in the source-code download?

**Comment by MarcelineVQ** [comment]
A little of both possibly, your environment might lack some includes that are implicit for other people. Everyone's a little different.
Add cmath to the files you need to and list them here please so @endless-sky can add them where neccesary.
A quick check shows that'll probably be MapPanel.cpp as you've noted and possibly InfoPanel.cpp

**Comment by Sinsling** [comment]
MapPanel and HailPanel.cpp where the only files that gave me that issue, atleast until I destroyed my compiler.

I had to change the builder options as I did not use C: as my install directory. After getting for enough along to realize I had to change my file locations for libmingw32.a and libopengl32.a, I ended up with a massive wall of undefined references.

I will have to attempt to install all files into their base directories so that I do not have to change any file pathing, and see if I can compile from there.

**Comment by Sinsling** [comment]
I managed to compile, but received missing dll errors. I copied the dlls over from my steam folder, but now the code::blocks compiler gives me and error titled "EndlessSky.exe - Entry Point Not Found".

When I try to use the exe that was created from the failed launch with missing dlls, I recieve a message about a missing libgcc_s_sjlj-1.dll that is not located in my endless sky steam folder.
