### ISSUE TITLE
Rim Archeology 3B: "Oxyrhynchus" has electron beams before the Deep creates them

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1352]
Or at least before the Deep lets the Navy use them.

edit: and later on, when Zug is attacked, I find a ship using ionic afterburners...

edit 2: and the Quarg ship that arrives after ^ does not have the `forbearing` tag...
this is an entertaining series of discoveries.

**Comment by KiLEdEnNis** [comment]
the no forbearing tag is understandable, since it's a guard
but such side stories may go against timelines, like, I finished the main story, yet never tested flamethrowers, even though the FW use them
I don't think it should actually be fixed, since it'd ruin these missions, so playability above realism I guess (like someone taught me in a previous issue about splash damage not angering friendlies)

**Comment by LocalGod79** [comment]
this was originally addressed in #872 

basically, the ship is a one-off and whoever (game character) modified it, also had the knowledge to make one-off weapons/engines that were close enough to the advanced outfits for me to not create new ones (there are also S-270 and Pulse Cannons on a couple of other Marauder ships) for the half dozen instances of advanced tech in 29 ships.
