### ISSUE TITLE
should players be able to buy ships after selling them?

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1355]
as the title says, the idea is that players can buy ships back after selling them, like an outfit that's not for sale, you can buy that back too
I looked around if there was a similar issue but I didn't find it

**Comment by toilethinges** [comment]
#852 has this and many, _many_ more shop changes - the ship's hull will go to the "junkyard" for a day after sale, with no outfits still inside(?).

**Comment by Amazinite** [comment]
I believe you're correct on the no outfits inside. Jim said that junkyard ship hulls don't come with outfits. And when you sell ships right now, the outfits go to the outfitter, so that would likely remain the same.

**Comment by jmhorjus** [comment]
Yep; in #852 the junkyard ships come with no outfits installed at all.  When you sell a ship the outfits go to the outfitter and the hull to the junkyard.  Hulls purchased from the junkyard will obviously not pass flight check right away, so you get a little notification that the ship will be automatically "parked" when you buy it. You can park/unpark ships in the outfitter screen and the ships outline will be color coded to indicate if it is passing flight check or missing a hyperdrive.

**Comment by KiLEdEnNis** [comment]
I saw that #852 one but that's empty hull & junkyard part, I meant just like the outfitter

**Comment by jmhorjus** [comment]
If you were able to buy back the ship with all its outfits, "just the way it was" then you could not also send the ship's outfits to the outfitter or they would be duplicated.  

It would be possible to have a "buy-back" option that only lasted until you left the shipyard, but personally I'm not sure I would want that - because if I'm going to sell a ship just to buy it back again, it's probably because I *wanted* to quickly strip the hull of all its outfits so I could re-equip it from scratch.

**Comment by KiLEdEnNis** [comment]
I mean that the outfits are at the outfitter then, but if you buy limiteds, the ship won't have them
or make an empty hull & give basic outfits

**Comment by jmhorjus** [comment]
It actually is implemented - fully implemented and working without any known bugs and has been for months at this point.  
It has not been merged to the master branch and thus is not part of the current Steam release, but the implementation is 100% finished. 
If you clone the branch from #852 and build it, you can play with all the upgrades right now. :)

**Comment by BorkBorkGoesTheCode** [comment]
Why haven't you PR'd?

**Comment by jmhorjus** [comment]
@BorkBorkGoesTheCode I have. The link #852 *is* a link to a PR (Pull Request). :) The PR has been open for a very long time, during most of which time it has been free of conflicts and of known bugs. 

Just now it needs to be merged up with the latest in the master branch to resolve new conflicts - I hadn't looked at it for weeks since there were no new comments and I'd lost interest in Endless Sky in the mean time.  You can read the whole development history and the latest comments from MZ (from June 11) on the #852 page.

**Comment by KiLEdEnNis** [comment]
so you mean it's made but not in the Steam version or what?

**Comment by jmhorjus** [comment]
@KiLEdEnNis This site, github, is designed for developers to work on projects collaboratively.  So each project has a "master" branch (or version) that each developer can copy into their own workspace (called a "fork") and then make changes.  

Once they are done making their change, they can ask the owner of the master branch (in this case the "endless-sky" user) to "merge" their changes into the main branch - this is called "making a pull request".  If there are no conflicts, then "merging" just means pushing a button, basically saying "_I approve, this change is now part of the master version._"  During this stage, when the "pull request" is open anyone can review or copy and build for themselves the modified version just as they could do with the master branch.  

But just being in the master version of the code here is not the same as being on Steam.  Steam is not affiliated with github, and they only ever change what is distributed on Steam when MZ (the game's creator) goes through a manual process of building and publishing a new official version of the game for all the supported platforms and delivering that to Steam.  

For those of us who are developers, we never (or very rarely) play the game on Steam, because Steam releases are quite infrequent and so it is usually far out of date from the master branch here on github. (I don't know all what's involved but it's probably an annoying process and you don't want to accidentally put something up that has a bug in it; MZ is only one guy after all.)

So the changes that I've been answering questions about here are fully implemented (in the context of development "implemented" means "programmed and working"), have been debugged and tested extensively, and have been submitted for approval, but have not yet been approved.  It is possible they will never be approved, and even if they were approved today it might still be quite some time before they were published to steam with the next release. 

So what should you do?  Go here: "https://github.com/endless-sky/endless-sky/wiki/BuildInstructions" Learn about git, follow the build instructions, and join the developers in always being able to play with the very latest version of the game. :)

**Comment by KiLEdEnNis** [comment]
@jmhorjus thanks for the help <3
