### ISSUE TITLE
"never disabled" tag doesn't apply on variants

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1367]
so I was editing some more on my "project", but variants of the ships I created could be disabled while I gave the original ships the "never disabled" tag
I checked for typo's but everything is fine

edit: giving the tag to a variant (below the name, above the "outfits" tag) seems to help, is this intentional?

**Comment by Amazinite** [comment]
I would think so. It's possibly that someone would want a normal ship that can not be disabled but can a variant that can be, so it makes sense that you would need to give the variant the never disable tag again.

**Comment by KiLEdEnNis** [comment]
seems logical in one way, but a variant is just the exact same ship with other outfits, while you'd expect that it keeps tags like that

**Comment by Amazinite** [comment]
I think it's a matter of documentation. I'm not sure if the wiki specifies that tags like never disabled get cleared on variants and need to be readded.

**Comment by jafdy** [comment]
With out adding a new tag it is necessary to clear tags like `never disabled` otherwise it would be impossible to make a variant that can be disabled. The variant only replaces things that are specified and removes tags, it the tag was not remove there would be nothing to replace the tag the so it couldn't be removed.

**Comment by KiLEdEnNis** [comment]
still weird but it seems logical now
