### ISSUE TITLE
Reverse Thrusters and Auto-pilot again

### ISSUE THREAD

**Issue by Darkmage2160** [endless-sky/endless-sky#1377]
Hey, I know there was already an issue with auto-pilot on freighters not using reverse thrusters, and as of 0.8.8 it was supposedly fixed, but i'm playing 0.9.2 (or i think i am since i just downloaded it yesterday) and found some atomic thrusters, specifically A250, A255 steering, and AR120 Reverse. I'm flying a freighter. Is this an AI issue? or does the math work out to be faster if he turns around, slows with the a250s, turns BACK around, and then goes along? I feel like it would be easier just to slow down using the ar120s, even though they only have about half the power of the reg thrusters, especially docking on a planet, which he always does a 180 to slow down for

**Comment by KiLEdEnNis** [comment]
I don't think it's faster, as it takes a lot of time to turn around, so probably an AI issue

**Comment by Wrzlprnft** [comment]
AI uses the reverse thruster when it's faster than turning around. Since most halfway larger ships have the mass and the engine capacity for larger thrusters, they rather use them, than a -in comparison- somewhat weak  reverse thruster. seems like the math works out that way, but feel free to do tests if you like or doubt it.

**Comment by Amazinite** [comment]
Install one A120 and one AR120 engine. They both have the same thrust, so it should be faster to use the reverse engines. Test if the AI uses them.

**Comment by endless-sky** [comment]
The math for deciding which thruster to apply is only an approximation, because it doesn't take "drag" into account.

But then again, *everything* in the AI is just an approximation. The AI is designed to use a set of comparatively simple heuristics that achieve believable and reasonably good behavior, rather than using the extremely complicated calculations that would be needed to achieve completely optimal behavior.

**Comment by KiLEdEnNis** [comment]
@endless-sky  did you keep it simple so the game wouldn't become too heavy for bad computers? (because you can basically play it on a DS)

**Comment by endless-sky** [comment]
If a big fight is going on (say, in Korath space) the game will slow down right now even on the most powerful CPUs. So, it has to be optimized for those situations, not just ordinary, smaller fights.

Also, I've got a strong preference for closed-form equations that are approximately correct, compared to the iterative solutions that are necessary to plan out future flight paths perfectly taking steering and acceleration into account.

**Comment by KiLEdEnNis** [comment]
about the slowing down, I know how that feels, getting tribute from Earth isn't only hard because of the massive fleet, but also because of the projectiles which make the game slow to 1fps until the missiles are gone (went up to 400% CPU once)
