### ISSUE TITLE
circumventing crew salary mechanics possible

### ISSUE THREAD

**Issue by kitsunemochi** [endless-sky/endless-sky#1397]
it's possible to simply park a fleet, travel to another system in a 1 man ship, land and unpark the fleet, depart and wait in orbit for your fleet to arrive and not pay crew salaries

**Comment by KiLEdEnNis** [comment]
the only way to fix that would be for each ship to independently have their crew salaries on each jump, which is too much to do, too annoying and it hardly matters

**Comment by jafdy** [comment]
This has been known for a while. It is best to think about it as a for of cheating.

**Comment by KiLEdEnNis** [comment]
more like exploiting the mechanics, like #1319

**Comment by jafdy** [comment]
I would call exploiting a form of cheating.

**Comment by KiLEdEnNis** [comment]
it is, since it's circumventing game rules (personally I see cheating more as editing files)

**Comment by endless-sky** [comment]
I don't see this as much of a problem, because if you do that:

1. your fleet can't carry any commodities, and
2. your fleet isn't around to protect you.

So, doing this basically eliminates all the benefits you might get from a fleet. The only thing it gains you is being able to move your fleet to a different system a bit more cheaply, but that's more than offset by the fact that you then have to wait around for the fleet to arrive.
