### ISSUE TITLE
[question] what does "random" do?

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1403]
I looked around through issues but I couldn't find any issue
I am playing on a new save file again (heavy warship before initial deployment was done) and I actually can't trigger the story because of a high "random value", so everytime I land I have to save, set random to 0, press spaceport and hope I get a FW mission (because if you hijack random pirates for a living you tend to get a "random" value of 80+)

**Comment by jafdy** [comment]
Erm . . . Random is . . . well Random. It picks a number between 0 and 99 and compares that to the value stated in the mission plain text.

See:
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions#conditions

**Comment by KiLEdEnNis** [comment]
so the value switches between it all the time? because how I experience it is; do missions, random stays low, just hijack & don't do missions; random gets higher and higher

**Comment by MarcelineVQ** [comment]
Note that the source for `mission "FW Katya 1"` is `government "Free Worlds"` so if you try too early you can't trigger the story start because there aren't Free Worlds planets to trigger it from.

It can be a bit of a chore to start the story when you want to do it on purpose so just keep at it, you can keep landing on the same Free World's planet and checking the Space Port because landing is what changes the random value for each mission.
If you're going to edit to start the mission, editing `random` to be under 30 will absolutely trigger the mission if you're landed on a Free World's planet and check the Space Port after you load.

**Comment by KiLEdEnNis** [comment]
the thing is, it was after the initial deployment was done and there were Free Worlds planets (I killed the rat pack for example), but I only got the mission where Katya tries to headshot me after 2+ in-game months (even though all the requirements were met)

although editing my random seems to be the best way to try and trigger the story, it's just annoying when you are able to get a heavy warship before Geminus was bombed (meaning you have like nothing to do; my net worth is already 300M)

**Comment by jafdy** [comment]
I think someone put a mod on steam that removed the randoms from missions.

**Comment by KiLEdEnNis** [comment]
the only one that may cheat in my game is me D:
I'll look it up though
