### ISSUE TITLE
New Tibet no tribute, threshold, or fleet

### ISSUE THREAD

**Issue by kitsunemochi** [endless-sky/endless-sky#1406]
Don't know if it's intentional or not, but there is nothing defined for New Tibet under the tribute mechanics.

**Comment by KiLEdEnNis** [comment]
oh yeah, I think I saw that once (never reported)
I wish the Hai had tribute fleets though D:

**Comment by kitsunemochi** [comment]
Just noticed since i'm in the neighborhood conquering the galaxy, Harmony has no tribute stuff either.  Maybe since these are religious planets?

**Comment by Amazinite** [comment]
They're a peaceful planet of monks.

**Comment by kitsunemochi** [comment]
seems like an easy mark, i'm not playing the good guy over here

**Comment by Bladewood** [comment]
We were all aware of the existence of worlds which cannot give tribute, but we were all too lazy to report it to Michael.

**Comment by kitsunemochi** [comment]
yea, by no means complaining.  just noticed it and searched and there was nothing here.  seems super simple to fix, copy/paste 3 lines to a few places, and i think it'd soothe a lot of my fellow completionists who want to dominate _all_ of human space.

**Comment by Amazinite** [comment]
I don't think that we should be able to dominate _all_ of human space for the sake of lore like the peaceful monk planet, but you could download this plugin: https://github.com/Disiuze/TributePlus

It allows you to dominate every single inhabited planet in the game. May or may not be up to date with the Korath, haven't checked.

**Comment by KiLEdEnNis** [comment]
with tribute it's basically give money or I'll do orbital bombardment, so the planets should have some defense, even if it's just 1-2 "local fleets" & gives 100 credits

**Comment by Isaacssv552** [comment]
Is it possible to change the tribute stats of a planet by event? If not it would make sense that Deneb can't be dominated.

**Comment by KiLEdEnNis** [comment]
it'd make sense that there would be some Navy defense fleet, but if that happens a player could dominate a planet when the defense fleet is the weakest (like Large Navy: 5 vs Large Pug: 20 for example)
and it could break the game by accident by dominating a planet that later changes defense fleet

**Comment by TELunus** [comment]
Did we ever hear whether this was intentional, or just not worth fixing, or what?  I'm seeing that it's been closed, but no rational for not fixing it (or saying that it's fixed), and it still seems to be an issue in my version of the game.

**Comment by KiLEdEnNis** [comment]
they're a neutral peaceful planet of monks who reach out to pirates, so they have no reason to have a defense fleet besides an alien invasion in which case all human factions would defend

**Comment by Wrzlprnft** [comment]
i think the shorter answer is best: it is intentional.

**Comment by TELunus** [comment]
Thanks Wrzlprnft, that is a helpful answer.

The description on the planet says:

description `New Tibet is a world of jagged mountains and deeply shadowed valleys. Although it has been inhabited for centuries, in many places the terrain is so rugged that roads cannot be built, leaving several of the smaller towns almost completely isolated. Taking advantage of this isolation, several orders of Buddhist monks have built monasteries here.`
description `	In the lowlands, large farms support sprawling cities full of factories, a striking contrast to the simplicity and isolation of the mountain villages.`

I'm getting that from that first bit you're saying the first part says it's a peaceful world of monks who won't resist you and also won't pay you, but I would say that the second part there disproves that argument.  It's a planet with sprawling cities full of factories, which also has some monks up in the mountains.

I mean, unless you're saying that the first part is supposed to tell me that there are sprawling cities worth of monks.  That's a valid possibility, but if that's the case I'll be opening another issue to say the wording should make that more clear.

**Comment by jafdy** [comment]
It's a late game feature for players who have done everything else. It's about that complex.

**Comment by Lineth** [comment]
Yeah, the world should definitely have the defense fleet/tribute, even if only a small one.

**Comment by TELunus** [comment]
jafdy I'm not really sure what you're trying to say by that.

**Comment by KiLEdEnNis** [comment]
tribute itself

**Comment by Wrzlprnft** [comment]
tribute itself was introduced not as a deripus (meant to type serious) game feature, rather a measure to create playtime in the super late game.

that said, if we have a late game story,it can fall into it's place, but otherwise i don't see any major changes coming to it.
additionally, if you demand tribute, you do not gain control over thr planet, but the planet's government decides to pay you some money so you leave them alone, as well as free landing, so you don't shoot your way down here. since you have no means to actually damage or conquer (at least if we stick partly to the lore) a planet, that' about it. so,on those planets,the influence of the monks as some sort of spiritual leader probably shows them that you can do no substantial damage.

**Comment by KiLEdEnNis** [comment]
they pay you to leave them alone but all you can do is shoot ships that are in the system
& they still pay you then

**Comment by TELunus** [comment]
"so,on those planets,the influence of the monks as some sort of spiritual leader probably shows them that you can do no substantial damage." 

I'll note that from my end this looks a lot like "well, ok the population isn't all monks, but we can still think of a reason to justify this" 

I from the quote note particularly the "probably", which points out that you're not even sure that's the reason you can't demand tribute from them. 

So what I'm taking away at this point is that you don't really have a reason it's better this way, but since the bug isn't being fixed you're finding ways to call it a feature. 

I sincerely hope I'm not just being really annoying at this point.  It's just that this would be really easy to change, so if we're not going to I want to be it's because there is a good reason the game really is demonstrably better if you can't demand tribute from New Tibet than if you can, and it still to me sounds like the opposite of that is true.

**Comment by Amazinite** [comment]
>bug

It's not a bug.

>A few planets in human space are "pacifists" and refuse to engage your demands for tribute. The same is true of all alien worlds, at the moment.

This is a quote from MZ himself saying that it isn't a bug.

**Comment by whismerhill** [comment]
so ... I'm jumping in here after seeing this fact by myself in my game
if it's intentional that monks do not tribute you
I think it should still have null fleet & zero tribute instead of the current "null" value
why ? that way you can dominate it to force the ability to land during war without paying tribute
just saying .....
Alternatively, since it's just a world of monks, having to pay them a bribe for the authorization to land seems counter-intuitive ^^

**Comment by ldsgsm** [comment]
If they don't have a fleet, why do they mock you for demanding tribute?

**Comment by KiLEdEnNis** [comment]
I have 2 options
- they mock you because they have no defense fleet anyway
- they say that because they think you're joking because they have no defense fleet

**Comment by ThrawnCA** [comment]
If New Tibet is too peaceful to defend itself, then perhaps it should never become hostile and refuse to let you land?

Pacifism is reasonable, but you can't have it both ways. If you're going to deny entry, you have to be prepared to back that up. A world with no defence fleet should not be able to stop the player from landing.
