### ISSUE TITLE
Ship sprite scaling in the shipyard

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1411]
http://steamcommunity.com/app/404410/discussions/2/360671727316173214/

**Comment by MarcelineVQ** [comment]
Hopefully I'm not being obtuse by saying so but I actually can't tell what the problem is with the examples that were given, the thumbs look just like the ships.
It does seem reasonable to be able to specify separate thumbnail pictures for ships though, perhaps something as simple as using the `thumbnail` attribute in the `attributes` list if one is present. That would make it easy to grab using existing logic: ship->Attributes()->Thumbnail() for example, then the shop panel could use one if present and otherwise scale the the ship image as it does now.
It might be weird to separate where the `sprite` and `thumbnail` are though, nesting-wise.
```
ship "Aerie"
	sprite "ship/aerie"
	attributes
		thumbnail "ship/aerie-thumb"
```

**Comment by comnom** [comment]
![capture](https://cloud.githubusercontent.com/assets/17083697/17466050/137eca3a-5cd4-11e6-82c6-7abfd4da3846.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17083697/17466055/3b000cfe-5cd4-11e6-998d-49e64b6ada0f.PNG)

@MarcelineVQ  The problem is simply the jaggies. Hopefully the circles illustrate it better. Or perhaps I'm simply being anal about it if other people can't readily tell. Either way, it looks rough to my eyes, and seems a shame to leave it that way when scaling it +/- 10 pixels or so and a little blur would get rid of it.

**Comment by Amazinite** [comment]
I notice it, but it isn't really something that bothers me much. Even so, it would still be nice to be able to fix it some way that didn't involve having to change the ship's in-space sprite until both the in-space and in-yard sprites looks good.

**Comment by comnom** [comment]
> Even so, it would still be nice to be able to fix it some way that didn't involve having to change the ship's in-space sprite until both the in-space and in-yard sprites looks good.

That would be fantastic, but I think short of being an actual artist (which I'm not) and avoiding geometry in the modeling phase that would scale poorly, actually hand editing two different sprites is the easiest method I've found. I often look to the dev's ships for inspiration in these situations, but while he manages to avoid it most of the time, it just seems inevitable sometimes.
![capture3](https://cloud.githubusercontent.com/assets/17083697/17466246/5f646fa4-5cd9-11e6-9834-202296b197d5.PNG)

Also would like to clarify, the in-space sprite had to be edited that way regardless, so the only additional effort is in a second, smaller sprite.

**Comment by Sinsling** [comment]
I suck at modeling - I am only using paint placeholders - but would it be possible to open the eventual png you get in a program like piskel and use the rescale to get a shipyard-sized image to try with MarcelineVQ's method?

I suggest avoiding paint all together for re-sizing. It does a terrible job in my experience. -kik for being a modeling newb-

**Comment by KiLEdEnNis** [comment]
I see the problem; 6 anti-missiles and 6 missile launchers, get some other weapons

anyway, do you mean the ship is so big that it's scaled down to a size where it looks weird (not HD)?

**Comment by Sinsling** [comment]
He is talking about the rescale causing un-sightly jaggedness in the shipyard due to pixelation.

**Comment by endless-sky** [comment]
The "right" way to do this would be with mipmapping, which would increase the VRAM usage of the game by 33%. If it ever becomes possible to scale the view to less than 100% (i.e. a zoomed out tactical view) that will probably be necessary, but in the meantime I don't think it would be worthwhile just to fix this one issue.

The other option would be a custom sprite shader just for shrinking big ship images for display in the shipyard, but that seems like too much effort for a modest improvement. Also, in my testing I've found that the "jaggies" also increase the apparent detail of the ships at times (left, below), whereas blurring tends to smooth those features out (right, below).

![jaggy](https://cloud.githubusercontent.com/assets/11450262/17499188/e2cf7f62-5d99-11e6-8853-a4440315dddc.png) ![smooth](https://cloud.githubusercontent.com/assets/11450262/17499193/e7539186-5d99-11e6-8f63-636919f09b5a.png)

**Comment by comnom** [comment]
> The "right" way to do this would be with mipmapping, which would increase the VRAM usage of the game by 33%. If it ever becomes possible to scale the view to less than 100% (i.e. a zoomed out tactical view) that will probably be necessary, but in the meantime I don't think it would be worthwhile just to fix this one issue.

Agreed, after just a few comments in this thread I'd have to say the effect isn't that pronounced to be worth it. (ie some can't tell at all, and some can but it doesn't bother them). If a secondary sprite image isn't viable, then I see no reason to add something so resource intensive.

As for the blurring, you're absolutely correct in that it reduces detail (more evident in the smaller details than in say, the nose) which is why I only apply a selective blur; literally just few pixels on the problem areas, a sort of heavy handed anti-alias.

So fair enough I say, I'll just use what I have and make the best of it. I appreciate the time taken to respond.
