### ISSUE TITLE
[enhancement] Lifeform Scanners

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1424]
Which would go along with Cargo Scanners and Outfit Scanners, showing the enemy ship's crew count. Maybe too advanced for humans, but it might help with finding a low enough crew ship to capture in some future late game scenarios.

(I think this has been suggested before, but I can't find it.)

Edit: on a completely unrelated note, does killing one crew deduct one point from reputation, or what?

**Comment by KiLEdEnNis** [comment]
that's a great idea o:
(maybe a ship stats scanner would be an idea but that'd be too complicated, so unlikely)
I wish atmosphere scanning got an actual use (maybe for missions) though

**Comment by Alkallid** [comment]
It's all crew as soon as you disable the ship.

**Comment by toilethinges** [comment]
Yeah, I knew that it was depending on disabled/killed ship crew, but is there any kind of stacking such as 1 rep point for each crew, and five points for every ten killed, or is it just the raw number?

**Comment by KiLEdEnNis** [comment]
I don't know, I only know that the more crew you kill the more the reputations change

**Comment by warp-core** [comment]
There are 6 ship events that have permanent affects on reputations with governments:
Assist, disable, board, capture, destroy and atrocity.
Assisting a ship results in your reputation with that government improving by 0.1 for every crew member on that ship (I assume that the value is multiplied by number of crew however I am not certain);
Disabling results in a decrease of 0.5 per crew member;
Boarding results in a decrease of 0.3 per crew member;
Capturing results in a decrease of 1 per crew member;
Destroying has the same effect as capturing;
Atrocity first sets the reputation to negative and then there is a decrease of 10 for each crew member however I'm not quite sure what this applies to (perhaps nuclear weapons?).
So, to answer your question, (I think) killing individual crew while capturing does not affect reputation if you do not capture the ship however your reputation will have already been affected by disabling and boarding it and if you destroy it instead of capturing it, your reputation will be lowered by the same as if you had captured it. Having said that, if you were to disable and board a ship and kill all but 1 of its crew and then destroy it instead of capturing it, would its destruction only affect the reputation by 1 or would it consider all the crew the ship had when it was disabled?
The information about the ship events is in 'ShipEvent.h' and 'Government.cpp'.

**Comment by toilethinges** [comment]
@warp-core, for one, thanks so much. That helps my understanding a lot. Second, one example of an atrocity:

> If the cargo is marked as "illegal," governments that care about such things will levy the given fine against you if you are caught carrying this cargo. If the fine is negative, being caught with this cargo while in flight is counted as an "atrocity" (the government that catches you immediately becomes your enemy, no matter how good your reputation was previously), and if you are caught in a spaceport with the cargo the result is a death sentence (game over).

From CreatingMissions.

**Comment by KiLEdEnNis** [comment]
@toilethinges that's not in the game itself yet is it?

**Comment by warp-core** [comment]
@toilethinges thanks for the example.
@KiLEdEnNis the only illegal outfit in the game that I'm aware of is nerve gas and that has a positive fine so doesn't count as an atrocity so, as far as I know, it isn't used in the game yet.

**Comment by Nechochwen-D** [comment]
Made a patch for this on my fork [Crew-Damage](https://github.com/Nechochwen-D/endless-sky/tree/Crew-Damage) and also put together an example outfit that uses it [bioscan.txt](http://filehost.loretracker.net/bioscan.txt).
