### ISSUE TITLE
Ability to make specific governments find specific things illegal

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1429]
Currently, the illegal attribute is a blanket thing. If something is marked illegal, then everyone who cares about illegal things will fine you for it. But what if you could choose which things were considered illegal by different governments?

Example situation:
Let's say we have two items. Item A and item B, as well as three governments, 1, 2 and 3. 

Government 1 hates all illegal things, and will fine you for possession of both A and B. 
But government 2 is a little more laid back. They only thinks that A should be illegal, but B is completely fine. 
And government 3 is the exact opposite of 2, finding B illegal but saying A is fine.

Right now only nerve gas is illegal (at least in terms of outfits), but this feature could probably open up more possibilities. My first thought is a drug transportation job that you have to do through Republic space. These cargo items would be illegal in Republic space, but may be completely legal in Syndicate or Free World space where the destination may be. They would pay a lot of money so that the more you get fined, the less and less money you gain off of the job. (So pretty much job versions of the current drug running missions with a twist.)

**Comment by KiLEdEnNis** [comment]
great idea, could also add things where alien outfits are ok for them but illegal in human space

**Comment by endless-sky** [comment]
That's how ship licenses used to work - for example the Republic required you to have a "Freight license" but the Free Worlds did not. It ended up being super annoying because you would buy a ship legally in one part of human space, then fly to another region and get fined for operating a ship without a license. The same would hold true with illegal outfits - it would be annoying to get fined every time you accidentally enter a different region of space.

Right now, some governments just have a much lower security level than others, which I think is a reasonable compromise.

Also, note that if different things were legal in different regions of space, there would need to be some way to communicate that to the player so that they know where they're allowed to use it and where they're not. That's introducing a lot of complexity for a feature that's going to see relatively limited use.

**Comment by KiLEdEnNis** [comment]
what does the "security" thing do anyway?

**Comment by endless-sky** [comment]
"security" is the probability that they'll check your ship for illegal outfits / cargo when you land.

**Comment by Amazinite** [comment]
Closing because #1452 was milestoned.

**Comment by tehhowch** [comment]
One way to do this would be with a data structure in Politics that pairs an illegal outfit with a LocationFilter. this outfit would then be illegal in any system, planet, or to any ship that matches the LocationFilter.
To display this to the player would be a matter of reworking the Shipyard & Outfitter view in the Map Panel:
 - opening the respective panel (i.e. no ship / outfit selected)
   - Systems that have shipyards / outfitters are displayed in blue (perhaps using the saturation method to convey the number of items each has for sale, so it is still possible to identify "large" shops), i.e. current behavior.
   - Every system that will fine you for any outfits in your fleet (carried as cargo or installed on an unparked ship in your fleet) is displayed in red (possibly with the severity of the fine displayed with the saturation method).
     - These rings could perhaps have different radii as it's quite likely that a system might fine you for your current items, but also have a shipyard or outfitter.
 - After selecting a ship or outfit:
   - Systems in which it can be purchased are yellow (current behavior) 
   - Systems that have outfitters/shipyards are otherwise blue
   - Systems that find that outfit (or any of the outfits on the selected ship) illegal are displayed red, again in perhaps a second ring

**Comment by Amazinite** [comment]
Reopening because #1452 doesn't exactly cover every possible use case of wanting limited-illegal outfits (#1452 ties limited-legality of all illegal outfits to missions and governments, not scans and not specific outfits), and this is an often-requested feature that I think we should look into implementing.

**Comment by warp-core** [comment]
I think #6407 completes this?
