### ISSUE TITLE
Align gatling gun sprite with guns

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1437]
https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits
The gatling gun shouldn't be aligned with secondary weapons, since it is (as the name says) a "gun".
We know that there are other weapons that are secondary weapons but which have sprites aligned with guns, e.g. the flamethrower.

**Comment by KiLEdEnNis** [comment]
I don't know if it'd still look good then (because of the back part which would be half the gun)
other than that you're right though

**Comment by Wrzlprnft** [comment]
As i made the image i've been sticking strictly to the rules. It's up to MZ, who made the famethrower and the rules, to decide here. I think i can make it look good the other way, if it doesn't already

**Comment by Amazinite** [comment]
The Flamethrower is the only exception to the secondary weapons rule when it comes to alignment.
It's also the only secondary weapon that does not need its ammunition bought.
Coincidence? I think not.

**Comment by endless-sky** [comment]
I don't have strong feelings either way, so it's up to the people who designed it to decide if they want to change the sprite. But if anything, I think changing the flamethrower thumbnail would make more sense.

**Comment by LocalGod79** [comment]
as @Wrzlprnft indicated, we followed the rules laid out for alignment laid out in the wiki.

if you want to get technical, the Gatling Gun fires "missiles" (the bullets have `missile strength`, and trigger a/m) - so not technically a `gun`, in spite of its name...

and as @Amazinite has indicated, the Flamethrower's ammo is not purchasable and does not trigger a/m, so its outfitter sprite alignment is probably correct as it is (aligned as a "gun" rather than a "missile launcher")...

**Comment by Bladewood** [comment]
fein
