### ISSUE TITLE
[feature request] Command to make escorts focus fire while holding position at the same time

### ISSUE THREAD

**Issue by ReimeiSky** [endless-sky/endless-sky#1438]

**Comment by tehhowch** [comment]
How would this work when some ships are not in range of the designated target? As is, ships which are holding position in a tight formation will tend to select the same target due to the prioritization of weakened targets, and the prioritization of the parent's target (e.g. the ship you are targeting).

**Comment by Amazinite** [comment]
Would this be a separate key entirely? I don't think it'd make much sense to do that, as we're already have a LOT of keys that we're using; it seems absurd to reach the point where nearly every key on a keyboard is bound to a command. So then we'd need to make it so that hold position and focus fire aren't mutually exclusive commands. That is, telling your escorts to do one wouldn't cancel the other command. This would be a change in behavior that would likely annoy many players, as they would now need to remember to tell their ships to stop holding position in order for them to actually follow the focus fire order and track down the targeted ship.
