### ISSUE TITLE
Add a warning message if you attempt to board a ship while cloaked

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1442]
I cloak, sit in a warzone, wait for a few minutes, then target a random ship and press B.
But when my ship reaches the "boarding area", it does not stop and hover over the target ship as it does while uncloaked. It "slides" off of it. And when it leaves the "boarding area", it attempts to return to it. And it "slides" off of it again.
I could just decloak a few seconds before I reach the target ship, and that is what I do as a workaround, or alternatively I could actually use my keyboard to direct my ship towards the target, but right now this is very annoying, I don't want to press arrow keys in a process that should be automated :(

**Comment by KiLEdEnNis** [comment]
if you are cloaked you can't board anyway though

**Comment by Bladewood** [comment]
Cloaking lets me "land" on the ship without being attacked. When the situation is safe, I would decloak and board the ship.

**Comment by MarcelineVQ** [comment]
'Should be automated' is one of those phrases that's pretty different for everyone.
I would suggest a, possibly one-time, message of "You can't board a ship while cloaked." when you reach the ship so people understand immediately what's happening. But as it stands I'm very much for the current manual decloaking while 'b' takes you in approach that already exists. Getting the timing perfect is fun.

Cloaking is kind of broken at the moment for building a god-fleet since you can just hang out cloaked in a heavy sestor/mereti warzone with some stacked wanderer ramscoops and snipe-steal disabled 349's since their hull causes them to survive most fights.

**Comment by KiLEdEnNis** [comment]
I solo'd the Solar system w/ 1 ship (w/ cloak device), they are a bit too strong

**Comment by endless-sky** [comment]
Fixed in 0f297f2.

**Comment by Bladewood** [comment]
there we go
