### ISSUE TITLE
nemesis enemies stop all action with disabled player

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1451]
nemesis personality ships are unable to find a new target if the player has no undisabled ships in the system. This results in them taking no action at all and simply drifting, allowing themselves to be attacked and disabled or destroyed. This is most commonly seen in the low end escort jobs.

**Comment by KiLEdEnNis** [comment]
I've seen that too, but my ships weren't disabled, they were missile-interceptors who created some distance and then drifted away because they lost their target
basically if I jumped to another system they'd follow, create distance to bombard but after about 2 seconds they drifted away again, like they have a small AI range

**Comment by endless-sky** [comment]
This should be fixed by commit 76be613.

**Comment by SolraBizna** [comment]
Does seem to be fixed now.

**Comment by MarcelineVQ** [comment]
lgtm
