### ISSUE TITLE
Have mission clearance stop security checks

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1452]
Make clearance stop security checks on the planet that you were given clearance to. You were just allowed to land on the planet for some special reason, so I doubt they are going to go through your cargo and fine you for some nerve gas grenades when you're there for some special reason.
This could also be used for missions where you supposedly land somewhere other than the spaceport, as it makes no sense for you to get fined in those missions.

Also possibly allow government clearances that would stop a government from fining you for the duration of the mission, effectively closing #1429.

**Comment by KiLEdEnNis** [comment]
it's weird how a big gunboat can even find a small can of nerve gas with scanners, and if they'd check a ship you could "hide" the nerve gas, because it's a small box in a big ship

anyway maybe it'd help if the Republic wouldn't scan/fine you for illegal outfits during the war (first invasion to either end), because it's annoying if you have nerve gas knowing the enemy Republic won't scan you and at a ceasefire they do scan and fine you

**Comment by Amazinite** [comment]
Yeah, it would make sense if the Republic couldn't find you for having illegals during cease fires, since technically at that time they have no jurisdiction over you. Maybe use the hostility attribute instead in that situation.

**Comment by Bladewood** [comment]
This could work for missions with the `infiltration` tag (or something like that).

In the war, you would still be fined because nerve gas is not just banned by the Republic, it is banned in all of human space, by interstellar law. The Laws of War are the few things warring human factions will agree on.

**Comment by KiLEdEnNis** [comment]
@Bladewood although nukes should be illegal as well, in the checkmate the FW allows them, although that would be a part of the Laws of War

**Comment by Bladewood** [comment]
The Free Worlds allow them because you're a bloody council member. If you were any lower in rank, you'd be sentenced to death anywhere in human space.

**Comment by KiLEdEnNis** [comment]
a democracy where only certain people may use nukes, bless the FW

**Comment by Amazinite** [comment]
Looks to me that this is the case now.

https://github.com/endless-sky/endless-sky/blob/9b58c03f934c18b1d4e4a62acff8d28c2efc57e8/source/PlayerInfo.cpp#L2618-L2622

**Comment by tehhowch** [comment]
The bit about stopping fines from government x is why this wasn't closed, I think

**Comment by Amazinite** [comment]
I get the sense that that is already possible.

https://github.com/endless-sky/endless-sky/blob/2a73b3a97a0ffeff8db7bfe68ae08bb65ef81f57/data/free%20worlds%20start.txt#L276-L277

If you don't get fined by planets with clearance, then "FW Syndicate Diplomacy 1" makes it so that you never get fined on any planet in the Dirt Belt, and I assume that you could have a clearance work for any planet of a specific government instead of just any planet with a specific attributes.

**Comment by NomadicVolcano** [comment]
This issue is already resolved.

This is the code that implements it in PlayerInfo.cpp:

```
        // Planets should not fine you if you have mission clearance or are infiltrating.                                      
        for(const Mission &mission : missions)
                if(mission.HasClearance(planet) || (!mission.HasFullClearance() &&
	                                (mission.Destination() == planet || mission.Stopovers().count(planet))))
	                return;
```

I confirmed it works using this:

```
mission test
        description `do horribly illegal things`
        name `do horribly illegal things`
        landing
        repeat
        illegal -1
        clearance
        to complete
                never
        destination
                distance 1
        on offer
                dialog `Do horribly illegal things?`
```

I also tried with "infiltrating" instead of "clearance" and that works too.

This issue should probably either be closed or @Amazinite should give it the "waiting on OP" label to indicate that he's waiting for himself to respond.

**Comment by quyykk** [comment]
As nomadic says, this is already a thing.
