### ISSUE TITLE
[question/content] alien drives

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1455]
the only outfit every species uses (apart from jump drives on some) is the hyperdrive, although the Hai, Wanderers, and the Korath would have created their own "hyperdrive" at a time (because the humans, Wanderers, Korath and Hai all use the exact same drives now)
so the question is if there is a plan for race-specific drives? (it's more realistic, but not important, which is why I asked it)
if they were added at some point they could get different fuel consumption, size, even stats, but they'd require new images, changing alien ships' outfits etc.

side note, is there a plan for giving the scram drive it's own image?

**Comment by Wrzlprnft** [comment]
as local and i were working on the hai outfits, we planned to make drives for all alien races, but since we didn't know if there are any other plans by MZ to make them differ more than just images, so they are low priority.

I'd still be able to make images and also would like to do so.

**Comment by jafdy** [comment]
I could swear someone brought this up before but I can't for the life of me find the issue for it.
I support this.

**Comment by Wrzlprnft** [comment]
#1002 answer one and two.

**Comment by jafdy** [comment]
Right, well I stand by everything I said there. 
Needs a separate pull.

**Comment by KiLEdEnNis** [comment]
@jafdy I found #800 but it's a bit different in some way

**Comment by Bladewood** [comment]
...those aren't _even_ hyperdrives :|

**Comment by Amazinite** [comment]
Quick, think of cool alternate hyperdrive names so we don't end up with "Korath Hyperdrive," "Hai Hyperdrive," "Wanderer Hyperdrive," etc.

Slip Drive
Warp Drive
Null Drive

I'm done.

**Comment by KiLEdEnNis** [comment]
@Bladewood they behave similar but they are indeed not actual hyperdrives (closest issue I found though)
@Amazinite I think "drive" is in the name to make it clear what they do, but why not names like; Wanderers: "Travel Drive"
(^ was a good idea in my opinion, spent like 15 minutes on the other 2 and I like them a bit less)
Hai: "Hopper Drive" (because bug name ships), IF there are plans for the Unfettered too: "Hunting Drive"
Korath: "War Drive" (or something, I didn't know anymore, if there are plans to give more advanced species cool technology on their drives, War Drive could do, maybe for the Korath they could use some heat AND fuel to make a jump)

**Comment by Wrzlprnft** [comment]
I'm still on holiday-trip, but if next week monday there are no images, i'd take it as my turn and make some.

**Comment by KiLEdEnNis** [comment]
@Wrzlprnft I'm not sure if anyone is working on any, I doubt it, but it can wait anyway
have a nice trip :)

**Comment by MarcelineVQ** [comment]
While I'm all for flavor it doesn't make a lot of sense to assign a bunch of different names to the exact same item. Note the response MZ makes here https://github.com/endless-sky/endless-sky/pull/1002#issuecomment-215248507

To keep things interesting you'll likely want a game change to make fuel cost be determined by the drive outfit attributes instead of drive type as it is now.
If you change the scram/jump speed limit without changing the fuel cost you immediately create a best outfit. And if you don't change those all you can tweak currently is to add oddities like power generation or cooling to a jump drive; maybe it's 'always on' a little bit and that radiates your heat away or generates power due to some gravitic mumbo-jumbo. Or maybe an unplunderable drive could provide some capture defense through gravity control. Though that opens up the player to wondering how ship gravity works in ES so maybe it's best left alone.

I suppose currently you could fill that fuel cost role with higher outfit space cost, it's a little bland though.

**Comment by Amazinite** [comment]
>it doesn't make a lot of sense to assign a bunch of different names to the exact same item. Note the response MZ makes here #1002 (comment)

I don't really see how that comment suggests that everything should be named similarly, just that it shouldn't have the same stats. And it's not as if we're giving them completely different names, the "drive" part of the name remains to suggest exactly what it does, just like all the batteries have a different beginning but end in "battery" or "battery pack."

**Comment by KiLEdEnNis** [comment]
@MarcelineVQ what I meant is giving the different alien drives different stats (which I think I stated quite clear but I'm unclear often), the space, fuel and jump speed should differ at the very least, but giving it small extra stats (something different for the Wanderers, the Hai would just have a better hyperdrive, and the Korath AI would get something like cooling on it
from what I understand the jump fuel can't be changed yet though

**Comment by KevinKorzekwa** [comment]
@KiLEdEnNis There is a pull request for changing drive fuel consumption #1446 

I'm not sure the code in his commit is working yet, but it is recent.

**Comment by KiLEdEnNis** [comment]
@KevinKorzekwa I saw that one, but it's indeed not added yet :/

**Comment by LocalGod79** [comment]
while `jump fuel` might not be alterable, `ramscoop` is definitely an attribute that would, for most intents and purposes, accomplish the same effect.

**Comment by KevinKorzekwa** [comment]
@hdhdhd95 I was thinking you still had to change lines 1740-1742 back to their original values. You had mentioned forgetting to change them back.

**Comment by hdhdhd95** [comment]
I think those values are redundant.

**Comment by KiLEdEnNis** [comment]
still, it adds differences that can reflect on the species using it, and it will be some fun, maybe some species can have a big drive that actually functions as something else, like a generator, battery or cooling

**Comment by hdhdhd95** [comment]
@KiLEdEnNis If you can get the models I could integrate it to the commit I made.

**Comment by KiLEdEnNis** [comment]
what I can do is design differences, but it has to wait until fuel consumption can vary, then I'd have to look at all ships/variants that use the new drives and look if they have positive outfit space, and someone else would need to make the sprites
for now I'll wait

**Comment by hdhdhd95** [comment]
I made that commit so you could use that for now.

**Comment by Wrzlprnft** [comment]
I have a prototype for a hai hyperdrive and am working on a wanderer one, korath following.
![hai hyperdrive](https://cloud.githubusercontent.com/assets/15857993/17895830/a8739fd6-694e-11e6-96df-999110f3e871.png)
opinions?
PS: not ready for use yet, needs postprocessing.

**Comment by KiLEdEnNis** [comment]
@Wrzlprnft perhaps some details on the black outline of the cube (like thin green lines going over them or something)
but looking good :)

**Comment by Wrzlprnft** [comment]
![wanderer hyperdrive](https://cloud.githubusercontent.com/assets/15857993/17898032/92bffe66-6956-11e6-9df2-2ce530c425e1.png)
i tried to make a mixture of generator and ramscoop here. the hexagon structure will be postprocessed to a more ramscoopish color, if this idea makes it through.

**Comment by jafdy** [comment]
Nice hyperdrive. I think your generator/ramscoop will get a lot of people thinking "What ~~on earth~~ in the galaxy?".

**Comment by Bladewood** [comment]
Is that supposed to be a wanderer hyperdrive?
Because if so, you don't need to integrate a ramscoop, their already-existing ramscoops are awesome enough...

**Comment by KiLEdEnNis** [comment]
still, extra ramscoop is nice, and if I remember, the Wanderers will get a scram drive instead
it looks like a bee hive, I like it :P

**Comment by Bladewood** [comment]
source?

**Comment by KiLEdEnNis** [comment]
@Bladewood found it, it's actually a pull request though https://github.com/endless-sky/endless-sky/pull/1446/commits/18a12e3a0ce11e45cd19f1b24b5fb48410a97d4e

**Comment by Wrzlprnft** [comment]
I was just going for the visuals, the stats are up to others.

**Comment by KiLEdEnNis** [comment]
@Wrzlprnft looking good though, keep it up :)
and sometime I'll need images for my outfits, so if I need tips or help making them, I hope you can help :P (although images will be one of the last things)

**Comment by endless-sky** [comment]
I'm trying to avoid adding even more ways where, when outfitting a new ship, you have to go around and collect the best outfit of a particular kind from each species - e.g. Korath cooling plus Deep atomic thrusters, etc. So I'm not sure I like the idea of the hyperdrive becoming one more thing that is different for every species.

**Comment by LocalGod79** [comment]
@endless-sky i think that the immersion that would be gained from having species-unique hyperdrives is worth more than you might realize, and i understand your hesitance to create the situation you've described but; have you looked at my plugin "Ursa Polaris"?

i believe that arc could easily be expanded as the E.S. universe grows, and would nearly eliminate the concern you've expressed, while virtually forcing a fair bit of story content and making this (and probably other) immersion content more viable.

personally, i always thought that the regional exclusivity and "pain-in-the-butt to customize a new ship" was intentional...

with that said, i think "Hyperdrive: Hai", "Hyperdrive: Wanderer", "Hyperdrive: Korath", etc. would make better nomenclature (so that they are collected in their category).

i believe that if we are hoping to attract more story writers, the more visual "eye-candy" depth we can display, the more likely we are to impress upon potential writers the full depth that this engine is capable of (which is a heckuva lot)...

**Comment by KiLEdEnNis** [comment]
@LocalGod79 haven't seen the plugin but based on what you said I'd say some place where different species all sell their stuff?

and the drives don't have to have a "best" one, if they all excel at something it's a choice

**Comment by Wrzlprnft** [comment]
I think the drives are something that can just be reskinned for lore purpose.

By the way, i love the idea i had for the korath ones (magewise, of course), you'll see :)

**Comment by LocalGod79** [comment]
@KiLEdEnNis you should also check the plugin out.  you seem to have some of the idea, but the plugin itself applies a story and limitations (for instance, Korath tech is not ever stocked at Ursa Polaris Station, and some of it needs to be plundered to stock Wanderer outfits, for instance), and the whole game-year, you're spending hundreds of millions of credits to do it...

there is always a "best" one - it may be different for different outfit styles, but there will always be one that suits your preferred load out better than others - the situation of having to travel to the four corners of the galaxy *will* be exacerbated by unique drives, but it can be mitigated by a location like Ursa Polaris Station...

**Comment by Wrzlprnft** [comment]
![korath hyperdrive](https://cloud.githubusercontent.com/assets/15857993/18389648/35b5da98-76a7-11e6-9574-6e3571f2813d.png)
pre-postprocessing idea for korath hyperdrive.
Since i am not sure if wanderer and korath should share a "centralized" design, so i put together a quick idea:
![korath hyperdrive alternative](https://cloud.githubusercontent.com/assets/15857993/18389752/9b59924a-76a7-11e6-95b9-3502d77792a6.png)


i am sorry it took so long, but never was very satisfied with the wanderer nor korath hyperdrives

**Comment by Alkallid** [comment]
It sort of lools like a steampunk generator.

**Comment by KiLEdEnNis** [comment]
looks cool :)
