### ISSUE TITLE
Should H2H outfits have mass too?

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1457]
Just for the sake of consistency, because everything else that can be loaded into your cargo has mass now too.

**Comment by gunqqer** [comment]
because a rifle weighs so much. Even 450 rifles wo- Uhhh... Someone math this out to see how heavy it'd all be!

**Comment by Sinsling** [comment]
Given that very few ships can effectively carry an amount to make a weight difference with small hand to hand items, it might be something unnecessary. I imagine laser rifles and grenades can't weigh more than .001, and a bactrian at max passenger outfit would only effectively hold enough to generate ~.3 mass.

Then there is the problem of all other items with mass have some form of limiting the amount you can hold, from cargo to launcher ammo. Hand-to-hand items do not have this limit, so in theory a person could load themselves down with billions of hand to hand items and make acceleration/turning impossible due to high mass.

Then that also brings up whether crew and passengers should add mass as well.

**Comment by KevinKorzekwa** [comment]
I prefer not, since I like having 500 of every H2H. I assume the game decides which is best to use, even though I will never check.

**Comment by Sinsling** [comment]
Yes Kevin, the highest attack and defense items are automatically used.

**Comment by Amazinite** [comment]
You should only have as many H2H items as you have crew, and the game will always use the best weapon possible in the situation.

Even though there is no cap to how many H2H weapons you can have "installed," that's a situation that would be on the player for having all those H2H weapons to weigh them down. But it's not like they're going to be 1 ton a piece, so even if you do have 500 of each H2H weapon, it wouldn't impact much. I was thinking of giving them only about .01 mass, making 500 H2H weapons only equal 5 mass anyways.

**Comment by MarcelineVQ** [comment]
I use ammo and, after getting to the first shipyard, H2H weapons as hard currencies to dodge the bank eating my free cash when I'm playing a captures-only game, so it can be a bit of an exploit in the case of H2H where it's free storage.
I think H2H should ignore mass for as many bunks as you have and cost mass afterwards. The fluff explanation could be that there's space set aside for a H2H in each bunk.

This issue is possibly one of the things that could be solved  or mitigated by item-value deterioration which has been suggested in the past. https://github.com/endless-sky/endless-sky/issues/428 https://github.com/endless-sky/endless-sky/issues/312 etc

**Comment by LocalGod79** [comment]
i think that being able to carry an infinite amount of a *consumable* outfit introduced balance issues - specifically, negating ammo availability as a balance point for launcher weapons.

being able to stock a million frag grenades doesn't seem to present any real issues though, does it?

**Comment by BorkBorkGoesTheCode** [comment]
Why not add volume to the h2h equipment, so x number of h2h equipment takes up cargo space.

**Comment by KiLEdEnNis** [comment]
@BorkBorkGoesTheCode that's horrible, if you would buy 1 H2H you wouldn't have an entire outfit space, if the volume would be .01, having 1 would leave .99 useless space
and it's not even an outfit

**Comment by Amazinite** [comment]
He never mentioned outfit space...

**Comment by KiLEdEnNis** [comment]
cargo space is just as bad in my opinion

**Comment by Amazinite** [comment]
Then you must really hate it when you plunder ammunition and it isn't a whole number in mass.

**Comment by KiLEdEnNis** [comment]
I never plunder, I straight-out hijack ships (or I loot as much as I can and fill with as much ammo as I can)
but it doesn't make that much sense to store H2H in cargo, the idea I read somewhere that every H2H outfit has a capacity on max bunks is a good idea though

**Comment by endless-sky** [comment]
Hand to hand weapons aren't plunderable, so it's a bit of a moot point.
