### ISSUE TITLE
swizzle applied incorrectly to fighters/drones occasionally

### ISSUE THREAD

**Issue by kitsunemochi** [endless-sky/endless-sky#1462]
Not talking about captured fighters before you leave the system or land, that makes sense.  This seems to be the merchant blue swizzle, after joining FW; 
![2016-08-17-173045_551x350_scrot](https://cloud.githubusercontent.com/assets/11692143/17753995/6a8ecf36-64a0-11e6-880a-b4e91ecdce95.png)
![2016-08-17-173058_557x332_scrot](https://cloud.githubusercontent.com/assets/11692143/17754004/77c2c14e-64a0-11e6-8825-c86dd5a0a4d7.png)
Zoom/Crop for clarity, can give full screens or whatever if you'd like.

**Comment by MarcelineVQ** [comment]
Seems to occur for externally docked units any time a game is loaded, colors change once launched.

**Comment by KiLEdEnNis** [comment]
@MarcelineVQ so you mean the fighter/drone swizzle won't "update" as they can't launch independently (which does change it)?
just asking, the more I know :)

**Comment by MarcelineVQ** [comment]
Basically when you load a game all your ships are set to the player's government, doing so also sets their swizzle `Ship::SetGovernment`. When you first load though your government is based on the "Escort" government in goverments.txt which has swizzle 5, blue, so all your ships have blue swizzle.
After loading is done `PlayerInfo::ApplyChanges` is called which will apply things like:
```
changes
	government Escort
		swizzle 2
```
That are found in the player's save file, this one for example sets the Escort government the player uses to swizzle 2, free worlds green. However by the time ApplyChanges is called ship swizzles have already been set so they're all blue.
When you leave a planet `Engine::Place` is called which at the end of it will update any active ships by calling `Ship::Place` which also updates the government and swizzle of ships, fighters and drones are in bays at this time so they're not in the active ships list and won't have their government and swizzle updated until they are launched.

Since it's only really called once `PlayerInfo::ApplyChanges` is likely the best place to apply swizzle updates to ships after loading if someone wanted to try fixing this.

**Comment by KiLEdEnNis** [comment]
so that means if you land and depart again it does show the correct swizzle afterwards?
side question; is it "spam" to ask a question every now and then? (it is learning about the game etc.)

**Comment by MarcelineVQ** [comment]
It's probably spam if it's not relevant to the original asker so we might be a bit off topic by this point. Learning isn't ever a bad thing but keep in mind it emails anyone involved in the conversation when you make a comment so you want to be sure it's a useful comment when there's enough people participating.

Landing and departing won't fix it on its own, it's specifically the call to Ship::Place that updates ship governments currently and that isn't called for fighters and drones unless you launch them.

**Comment by Bladewood** [comment]
Wait.
Why is he using fighters again?

**Comment by kitsunemochi** [comment]
> Wait.
> Why is he using fighters again?

I'm not actually using fighters, lol. I'm collecting them. Just end-game stuff after all the quests, trying to collect full fleets of all the races, all the variant ships, etc.

**Comment by KiLEdEnNis** [comment]
change a Drak ship by removing "never disabled", and try to get it :)

**Comment by Bladewood** [comment]
The Drak are VERY strong.
They annihilated my fleet (literally, they use antimatter) of 32 shield beetles, each with 4 skylances. We only managed to bring it down to 1/4 shields.

**Comment by KiLEdEnNis** [comment]
it'd take like 40 Kar Ik Vot's with Quarg technology or something, but the shield is 4/5th, - hull repair it's like 2/3th the work
anyway I'm dragging this conversation in another direction, sorry about that :P
