### ISSUE TITLE
[bug] Licenses can be purchased no matter the location

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1465]
So say you have a ship that requires a license to own, and that license is also purchasable in some way. Even if the license is not offered on the same planet as the ship, you are still able to pay for the license to own the ship.

Prompted to buy license.
![screenshot_50](https://cloud.githubusercontent.com/assets/17688683/17816261/58524c8c-6606-11e6-8de4-8c1ab2bdf907.png)
 No license on planet.
![screenshot_1](https://cloud.githubusercontent.com/assets/17688683/17816265/5ebe9670-6606-11e6-9f12-7714bef42db7.png)

**Comment by kitsunemochi** [comment]
what version is this? is this a plugin?

**Comment by Amazinite** [comment]
Yeah, I've got a few plugins on.

**Comment by kitsunemochi** [comment]
i do not get the offer to purchase a navy license... well, anywhere.  to get one in the game as of now you have to edit saves or use a plugin like you are doing.  as such, i do not believe this bug is actually in the game, it is in the plugin you are using.  

i don't know the plans for the navy license, perhaps it will be like the militia licenses and not be sold anywhere, requiring a quest to obtain, thereby eliminating this from even possibly showing up in the game once they're implemented. 

a possible solution is editing the plugin to sell the navy licenses everywhere the ships which require them are sold, which seems logical anyway.  the alternative would be trying to create some sort of check within the plugin that would determine if the license required is sold at the outfitter of the planet you are at.  if that is even possible, i don't know.

**Comment by KiLEdEnNis** [comment]
the plugin adds Navy licenses, but the "FWCarrier" license is given and is permanently given, shouldn't the Navy license be the same way?

**Comment by Amazinite** [comment]
It is not a problem with the plugin nor is it something that the plugin can fix; it is a problem with how the game checks to see if a license can be purchased for a ship. Right now it does not care for the location of the license, it just checks to see if the license can be purchased and then asks if you want to purchase it regardless of license location.

**Comment by kitsunemochi** [comment]
wasn't trying to say it should be disregarded, sorry if i gave that impression.  i didn't realize that this was using a mechanic which is in the game to offer the license in the shipyard.  i get this same thing when editing a planet to not sell pilot's licenses and removing the pilot's license from my save.

**Comment by KiLEdEnNis** [comment]
basically bugs in plugins that are caused by the vanilla system are actual bugs, good to remember that :)

**Comment by endless-sky** [comment]
I'd say this behavior is better than having a situation where the player is all ready to buy a ship, then can't just because a license is not available for sale.

**Comment by Amazinite** [comment]
(Going back through some of my closed issues)
How is that any different than not being able to buy a ship because you haven't unlocked the license?
