### ISSUE TITLE
Trinket in Sargas can fine you for having Nerve Gas that it sells.

### ISSUE THREAD

**Issue by MarcelineVQ** [endless-sky/endless-sky#1466]
Not unexplainable, the player can imagine that arrival customs are different security than the vendors, but a little weird.

**Comment by kilobyte** [comment]
How is this different from real life, where this tends to be the case for illegal goods not sold by the government itself (and even then, possibly catching you if you fail to bribe the right person)?

In places that are not outright lawless I imagine purchasing illegal weapons as looking for the right person, who tells you whom to contact, you go there, pass the money (as the Endless Sky universe seems to use physical cash), and have a beaten truck come to your ship with a load of "refrigerator parts".

**Comment by Bladewood** [comment]
Endless Sky does not quite use physical cash.
It uses data chips, or something like that.
So we're writing (typing?) checks.

**Comment by kilobyte** [comment]
There are "credit chips" which are a form of cash.  They get passed in situations where one would expect anonymity, and aren't easy to "write", judging from phrases like "He hands Katya a large stack of credit chips".

This part of universe lore, though, has little bearing on how you purchase illegal goods.  While existing text strongly suggest you meet in shady bars and pass physical cash, if there's a way to make an anonymous electronic transaction (and with no cash, there surely would be one as otherwise crime is next to impossible, something criminals would invent a way to remedy), instead of meeting the contact in person you'd do this over the 'net, not seeing anyone but the truck.

**Comment by KiLEdEnNis** [comment]
it's like real life; if you don't give physical credits it can be tracked (I guess) by others

**Comment by endless-sky** [comment]
The "outfitter" is meant to represent all the outfits that you can buy on a particular planet, even if they're not all available from the same place. For example, on bigger worlds there might be one outfitter selling Syndicate goods, etc., but they all get shown to you combined into one outfitter view. Illegal outfits work the same way - presumably they're not being sold in the open in the spaceport, but having a separate outfitter for each "vendor" would be rather annoying.
