### ISSUE TITLE
Feature request: Scrollbar in fleet info screen

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1483]
A steam user using a touchpad request a scrollbar in the fleet listing in the info panel.
Might actually be useful.
http://steamcommunity.com/app/404410/discussions/2/361798516959633886/

Edit: feels somewhat familiar the issue. haven't found anything... yet.

**Comment by VonZorch** [comment]
I was going to ask for an integrated fleet readiness indicator, just a small circle under the fleet listing.  Red if any ship cannot jump, green when all ships are ready, otherwise white.
Related, ships with drone/fighter capability will not report ready until all bays on an individual ship are filled or all drones/fighters have been recovered.

**Comment by Wrzlprnft** [comment]
as far as i know there are enough keys as page up and down and arrow keys to scroll through that.
