### ISSUE TITLE
[bug/mechanics] Ships that immediately run after taking damage

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1488]
If a ship has the timid personality and no shields (as in the ship has no shields stat/a shield stat of 0), they will run after taking any damage at all, no matter the hull strength remaining.

**Comment by BorkBorkGoesTheCode** [comment]
Seems reasonable.

**Comment by Amazinite** [comment]
Ship has 100,000 hull strength and no shields.
Gets hit once.
"RUN AWAY!! ABORT!!! ABORT!!!"

**Comment by BorkBorkGoesTheCode** [comment]
"Gasp, my paint job is ruined!"

**Comment by KiLEdEnNis** [comment]
timid makes ships flee as soon as their shields are down (idk what happens if you use armor piercing weapons on them though), it should be "flee when hull is <50% or less than for example 5k
anyway I can't edit so have fun :P

**Comment by Amazinite** [comment]
On the topic of timid and piercing, #1183.

**Comment by Amazinite** [comment]
Maybe if a ship is nothing but hull, it would run at 75% or 66% hull instead of running away from any damage at all.

**Comment by KevinKorzekwa** [comment]
> Maybe if a ship is nothing but hull, it would run at 75% or 66% hull instead of running away from any damage at all.

If that's done, it may also make sense to make a low shield rule that works off a %, where if the max shields is =< .01*hull, then act as if there are 0 shields.

**Comment by tehhowch** [comment]
`timid` has only two effects as of 56c880a16d276c6a621, and neither cause a ship to flee from combat.
The first causes it to return to its parents side:
https://github.com/endless-sky/endless-sky/blob/c3e40f6e24938f7b7593a1ba40027682cfcf39b6/source/AI.cpp#L641-L643
And the second seems pretty nonsensical since most ships will switch targets anyway once their current becomes disabled:
https://github.com/endless-sky/endless-sky/blob/c3e40f6e24938f7b7593a1ba40027682cfcf39b6/source/AI.cpp#L813-L815

The `coward` personality causes a ship that satisfies `hull/totalHull + .5 * shields / totalShields < 1` to abandon its allies (which seems to be this issue and the linked from here):
https://github.com/endless-sky/endless-sky/blob/c3e40f6e24938f7b7593a1ba40027682cfcf39b6/source/AI.cpp#L377-L384

https://github.com/endless-sky/endless-sky/issues/2658 has some relevance to this discussion.

I do agree that a tweak of the health equation / response / general personalities is in order.
In #1971 I configured the fighter/drone "return for healing/repair" behavior to use a relative health remaining check, that considers when a ship will become disabled when making combat decisions.

**Comment by endless-sky** [comment]
That second check is to keep merchants from going out of their way to finish off a disabled pirate.

**Comment by Hurleveur** [comment]
We could add control over the coward personality so we can customize the % of health at which the ship will run (rn it's 35% iirc)?
Then a keyword could be used (or another personality) specifically for no shields, too

**Comment by Amazinite** [comment]
AI has been using Ship::Health for these such checks for some time now, which takes the total HP of the ship into account instead of only looking at the shields.
