### ISSUE TITLE
Korath Redemption

### ISSUE THREAD

**Issue by hdhdhd95** [endless-sky/endless-sky#1490]
I want to write a mission line where the Korath see the mistakes they have made and ask the player to convince the Wanderers to teach them how to renew planets. Of course you will need the help of the Pug or Quarg to allow this to happen. Do you think it might be a good story line?

**Comment by jafdy** [comment]
MZ is already working on the wanderers fixing korath planets. If you want to write a story try starting with a side story, nothing to grandiose.

**Comment by KiLEdEnNis** [comment]
@jafdy I think he means the Core-ath (I'm so funny), you know, the ones attacking Syndicate?
if he does mean the Efret, indeed :P

**Comment by jafdy** [comment]
I would still keep out of that general area for now.

**Comment by KiLEdEnNis** [comment]
I'd say that if someone has a plan they should ask MZ or github (unless they make a new species)

**Comment by hdhdhd95** [comment]
@KiLEdEnNis how can I contact him?

**Comment by jafdy** [comment]
By asking a question or making a point and putting @endless-sky some where.

**Comment by KiLEdEnNis** [comment]
@hdhdhd95 you draw a 6-pointed star made of blood in a dark room, put candles around, and say "Oh mighty Zahniser, I summon you today, I offer you my soul, if you answer me okay?"
then add @endless-sky to finish the ritual

**Comment by jafdy** [comment]
But what time zone would that be in?

**Comment by KiLEdEnNis** [comment]
@jafdy whichever you are in
(had to edit it, I don't remember all details)

**Comment by Bladewood** [comment]
It is best to leave everything Korath to Michael.

**Comment by endless-sky** [comment]
The basic rule is, if you invent your own aliens, you can do whatever you want with them. If you want to use someone else's aliens, you may end up interfering with their plot ideas. :) The Korath, including the exiles, will eventually be involved in the Wanderer story line, so you'll need to wait until I finish writing that main story line in order to see what room is left for side plots involving them.

If you're just starting out writing missions, I'd suggest trying to add a minor human story line first - say, working for a particular corporation, investigating some region of space, etc. There's a somewhat outdated list of [ideas](https://github.com/endless-sky/endless-sky/wiki/Story-Ideas) for side plots in the wiki, or you could come up with something different.
