### ISSUE TITLE
[bug/content/enhancement] Pirate system fleets not changed from Militia

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1496]
Militia fleets can still appear in Nunki (possibly other systems, too, but I've only seen Nunki) until modified by the event "albatross joins free worlds".

Edit: Shaula, also.

**Comment by endless-sky** [comment]
I'm uncertain what the problem is - Militia fleets don't cease to exist simply because the Free Worlds becomes a government. Each planet still has its own militia (including plenty of Republic worlds) and those fleets patrol their region of space.

**Comment by KiLEdEnNis** [comment]
also, asking tribute in the Dirt Belt or The Rim during the war spawns massive fleets of Militia from the planet, and the FW say they can't beat the Navy then (tribute is just a weird add-on)
but every planet should still have some "pirate defense"

**Comment by Wrzlprnft** [comment]
The FW military doesn't command the militia troops, as well as the navy does't command the republic sided militia troops. They just defend their planet.

**Comment by toilethinges** [comment]
What I'm saying is that the original "Militia" government fleets are not changed to Free Worlds - I belive no Free Worlds fleets come into either of these systems, being only Militia and Pirate instead.

**Comment by toilethinges** [comment]
I just looked at the "FW abandoned bloodsea" event and realized that it must not be a mistake.

**Comment by toilethinges** [comment]
Talked with Amazinite and finally decided that it WAS in fact an odd situation, made a pull.

**Comment by Amazinite** [comment]
(Given that this is still open)

The issue is this:
Before the Free Worlds become a thing, all law enforcement fleets in the south are under the Militia government. But, after the Free Worlds is formed, all but a few systems switch over to using Free World fleets.

I guess this issue is more of a question then; is it intentional that these certain systems are the only systems that have militia fleets, or should they to have been switched over to Free Worlds?
(This isn't related to planets still spawning militia fleets when you demand tribute, but the fleets that randomly spawn in systems.)
