### ISSUE TITLE
Secondary Turrets

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#1498]
I recently added a Fuel Damage attribute to my fork ( #1492 ) to allow me to create interdictor ships however I have yet to find where the secondary weapons are defined or how to make turrets behave that way.

Any information regarding this would be greatly appreciated.

Respectfully,
Nechochwen.

**Comment by Bladewood** [comment]
Here, let me show you an example weapon I made. (does not have anything to do with the fuel damage attribute, but it's still an example)
> outfit "Tractor Beam"
	category "Secondary Weapons"
	thumbnail "outfit/unknown"
	"cost" 85000000
	"turret mounts" -1
	weapon
		sound "atomic medium"
		icon "icon/tractor"
		"inaccuracy" 0.
		"velocity" 2000
		"lifetime" 3
		"reload" 1
		"firing energy" 24
		"firing heat" 4
		"hit force" -160
		"slowing damage" .4

Placing it under the "Secondary Weapons" category does not have any real effect, other than organization of outfits.
The important part is that the weapon has a `"turret mounts" -1` tag, causing it to take up a turret port, and that it has an `icon "icon/icon name"` tag, so that it can be selected like other secondary weapons and fired at will.

**Comment by Nechochwen-D** [comment]
Thanks that fixed it.

If you like check out the pull request. You may just be able to use it.
