### ISSUE TITLE
Anti-Crew ship weapons

### ISSUE THREAD

**Issue by Nechochwen-D** [endless-sky/endless-sky#1503]
After Making a damage profile for draining or giving fuel (#1492) I started thinking about other elements that were lacking in the game and I realized that there was no direct threat to the crew of ships unless they are boarded.

So my question is this. Would anyone be interested in seeing this implemented in the game.

**Comment by toilethinges** [comment]
So that we can all see the answers across both threads: http://steamcommunity.com/app/404410/discussions/0/359547436757347088/

**Comment by endless-sky** [comment]
I originally had plans for highly illegal "radiation beam" weapons, but even if they're so illegal that getting caught with one is a death sentence, they would still be a major balance issue.

**Comment by Nechochwen-D** [comment]
The way I was thinking about it there would be four possible ways of killing crew.

1. Toxin
2. Hard Radiation
3. Physical (jostling as the ship gets hit)
4. Vacuum (opon piercing damage)

For the first one the toxin (-1 heinous) would be delivered by a missile. Upon striking the craft a random number would be generated which would then be run through an equasion that takes into accaunt the lethality and volume of the agent along with the mass of the ship, the percentage of volume occupied by crew, and any outfits that would negate the effect of toxins. If the result came back fully negative there would then be another RNG to see if ONE person was just unlucky enough to get caught in the cloud. I am still working up the ratios but it should hopefully turn out fairly ballanced.

For radiation it would be much simpler if shields are up and the hull is in good shape almost no damage would be taken and would increase in inverse ratio to the shields and hull. Again haven't figured out the math yet but this one should be fairly straightforward.

Pyhsical would be fairly easy if the weapon hitting it imparts a severe hit force there would be a calculation involving the current vector of the ship, the strike vector, and the inertial dampener stat of the ship. This one would be the least likely to actually kill crew.

Vacuum is the most straightforward of the group. If a missile with hull piercing hits your ship a random number is generated which is then run through an algorithim which looks at the state of the hull and strength of the projectile and decides wether or not it pierces the hull or if it merely damages it. After piercing another random number would be generated and run through yet another algorithim which calculates based on ship size and crew if and if so how many crew were exposed to vacuum before bulkheads were sealed.

Assuming that each of these attributes can be properly balanced, and weapons are also balanced. I believe that this could add (in my opinion) a missing flavor to the game.

**Comment by KevinKorzekwa** [comment]
What if anti-crew made it so that the ship was then unable to be captured, with the idea that there would be remnants of whatever killed the original crew (hard vacuum, radiation, toxins) left over to kill any boarding crew as well. 

Then you can kill the crew of a ship and leave it floating without really changing the balance of capturing ships much.

**Comment by Nechochwen-D** [comment]
That could be overcome by having hazard suits issued to crew and the opposing ship could also have them equipped as well.

The way I would balance things out is by having a far greater chance of the ship blowing up on you.

**Comment by KevinKorzekwa** [comment]
I could see how hull breeches in many parts could give that high chance of exploding, but what about radiation and toxicity? I suppose internal parts of the ship might not be protected against radiation, but if something can penetrate the outer hull and reach people I would thing it would would affect the internal stuff too.

**Comment by Nechochwen-D** [comment]
The ship would not be blowing up due to damage. Rather the pirates or other faction that you are commandeering the ship from would have safeguards in place in the event that someone decided to try to takeover their ship. As you successfully, and not so successfully try to capture ships that rate will go down.

**Comment by Bladewood** [comment]
A variable `self destruct` value?

**Comment by Nechochwen-D** [comment]
Yes and no. The current rate ships self destruct at seems to reflect the propensity of their crews to trigger the self destruct manually. What I would propose is a SD rate of around 80% at first and then gradually falling to or even slightly below the current rate as you and your crew gain experience capturing ships.

**Comment by Nechochwen-D** [comment]
Hi all.

I have implemented one of the elements I talked about earlier in my fork here [https://github.com/Nechochwen-D/endless-sky/tree/Crew-Damage](url).

If you could, check it out and let me know what you think.

**Comment by toilethinges** [comment]
#1424 now included. Hooray.

**Comment by beccabunny** [comment]
Could this be reopened? With some balance, this is a feature I would really appreaciate having, if only to give more alien variety weapons. A possible equation for each hit could be something akin to:
"crew killed" = "crew left" * "crew damage" * ("crew left" / "original crew") * "hull percentage" / 10
with crew damage being the variable set on the weapon and hull percentage being equal to
"original hull" / "hull left", but never higher than 10. If the "crew killed" would be lower than 1, then the game multiplies this number by 100 and rolls a number between 1 and 100; if the resulting number is lower than "crew killed" * 100, then 1 crew is killed; otherwise, none are killed. So, if we are shooting a weapon with 0.1 crew damage against a Kimek Spire with 100 crew and full health, the first shot will kill only 1 crew; if that Spire had 1/10 hull or less, that same shot would have killed 10 crew instead. Continuing with the 1/10 hull case, the second shot will kill 8.1 crew, rounding to 8; the third will kill 6.724 crew, rounding to 6, and so on.
When part of your crew is killed, a message should be shown; perhaps "You lost <x> crew" if it is your flagship to lose crew, and "Your ship <name> lost <x> crew" if it is an escort; given that the same happens for picking up cargo, they shouldn't get too spammy

**Comment by ravenshining** [comment]
Crunched some numbers on Discord.  Came up with a formula:
Deaths = roundup [ ( Radiation • Crew • Crew • 5000 ) / ( Mass • Bunks • Bunks • max( hull%, 10% ) ) ]

Eight test cases:
![radiationbeam](https://user-images.githubusercontent.com/31712538/79069662-ac2a0000-7c6b-11ea-931d-fd6b4fe9652b.png)
[radiationbeam.ods.zip](https://github.com/endless-sky/endless-sky/files/4466388/radiationbeam.ods.zip)

**Comment by Zitchas** [comment]
Why "roundup"? I would think that "rounding up" would result in a guaranteed minimum of 1 casualty per shot. 

Seems perfectly normal to me that sometimes a shot will hit an area that either a) doesn't have any people in it, and/or b) The people that typically inhabit that section are already dead. When one starts getting into the more extreme scenarios (for instance, trying to pick off crew on a ship that has a comparatively small number of crew on a comparatively large ship), you are basically trying to pinpoint where the people are in a really big metal can. It *should* be really hard to do that; not a guaranteed 1 per shot. 

Actually, given the scale differences between people and ships, I would fine it incredibly odd and unrealistic if every shot hit at least one person. 

In numeric terms, most weapons in ES shoot at least once per second, many shoot several times per second. So, assuming that a radiation gun fires at somewhere close to the same rate. On the crew side, out of all the ships in ES, only 5 have minimum crew higher than 100. Those five are the Carrier, Wardragon Skylark, Raider, and World-Ship. So having a weapon that kills crew and rounds up guarantees that even these top-level ships (some of which are massive) can be neutralized in roughly 100 shots, which seems OP, right there. Given how badly ships handle below minimum crew, a weapon that can reduce a ship to less than required crew in just a few shots is basically a "guaranteed win" weapon. It'll make heat-based disabling look weak in comparison. 

Balance problems:
- Unlike every other stat in the game, crew cannot be regenerated. (counter: Cloning facilities, medical bays that "restore" a ship up to required crew?)
- Being below minimum crew is a permanent, debilitating effect that cripples a ship, making weapons that target crew an instant, unrecoverable, crippling effect.
- Being able to kill crew makes the capture/sell gameplay even easier than it is currently, because any ship that can mount a crew killing weapon can now disable and capture any ship in the game. So long as it can carry enough crew to get the target ship back to an inhabited planet, it's good. The ship won't even need H2H weapons, because there will be no crew left to oppose them.
- Making the formula round up casualties favours the attacker, and guarantees that all ships will eventually succumb to crew targeting weapons, because no matter how much shields, hull, mass, or crew they have, there's nothing in that formula that can reduce the final value to less than or equal to 0. Which means that it will always round up to 1. (basic algebra: Where all values of a and b are positive and greater than 0, given the formula of z = a/b, (which is a simplified version of your formula), there is no circumstance where z will be 0. It can be really, really, really close. But never 0)

All of the above basically means that the only way that a crew-targeting weapon could ever be introduced in the game and be considered balanced, would be to introduce it in the form of a weapon that is explicitly expected to be OP. For instance, the Drak Anti Matter Canon. Such a weapon would never be available for sale, the player could never have more than one, and it would have to be so slow as to prevent it from being a primary engagement weapon. 

Of course, we all know exactly what the point of crew targeting weapons is: Capturing World-Ships and Wardragons.

**Comment by Foyolle** [comment]
Crew should wear spacesuits and have time to put on helmets during combat situations. This should make crew immune to non-corrosive chemical weapons and vacuum. Also should be noted that high-speed particles (e.g. Electron Beam, Proton Cannon) can produce hard radiation during hull impact according to real-world physics
