### ISSUE TITLE
Special weapon visual effects on ships with very large "holes" in their hulls

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1511]
For example, sending a horde of ferocious Kar Ik Vot 349s armed with Korath detainers at a lone Model 512.
The 512 is slowed into oblivion.
And then the graphical effects appear. In the middle. Where there is nothing but a vacuum.

It tends to look very unnatural.

**Comment by jafdy** [comment]
Could you create a thin line with transparent pixels through the ring so the coalition mesh covers the inside of the sprite as well.

**Comment by KiLEdEnNis** [comment]
also if you fire on a 512 when you're basically inside it; the empty inner part still counts as a hitbox

**Comment by LocalGod79** [comment]
it's the weapon's visual effect "crawling" over the shield matrix (which spans gaps in the hull).

geez, we used to use our imaginations to explain why things are the way they are...

**Comment by Amazinite** [comment]
That's all good until the shields are gone.

**Comment by KiLEdEnNis** [comment]
making shield hitboxes go between the gaps and hull just on the visual outlines would be kinda realistic I guess, but if you want realism; why would you ever actually go that close

**Comment by LocalGod79** [comment]
i see no reason that the visible effect wouldn't still hang around where the matrix used to be - it's just a visual representation, so anything goes, right?

**Comment by KiLEdEnNis** [comment]
wouldn't that mean you would see the residue go between each other over open gaps?
LocalGod fixed ES \( ͡° ͜ʖ ͡°)/

**Comment by Bladewood** [comment]
oh, also, jump drive effect includes the inside of the ship.

**Comment by LocalGod79** [comment]
same explanation - whatever is going on to jump the ship has a visual effect associated with the shield matrix of it...

**Comment by jafdy** [comment]
But weren't we saying before that the shield was very close to the hull to avoid having to draw a bubble around each ship to represent the shield.

**Comment by endless-sky** [comment]
Right now, each ship's collision mask is just a single polygon, which makes collision detection relatively simple and efficient. So, the options are:

1. Modify the collision masks to allow holes in them. That will only affect collision detection if your ship is "inside" a 512, and will make collision detection more complicated.

2. Add a second sort of mask to be used only for placing "effects" on the ship.

3. Leave it the way it is.

I terms of added complexity versus improvement to the game play, it just doesn't seem worth it to change how this works, especially since so few ships have large holes in them.

**Comment by jafdy** [comment]
My main irritation at this game is the way the effects spill into the hole in the 512. In practice it would only be a visual improvement, and of coarse you get the final say.

**Comment by KiLEdEnNis** [comment]
the only way I can think of is changing the collision detection; instead of it picking an outer point, going clock-wise, starting at a -90 degrees angle and then hopping to the first pixel it detects, it should count all non-100% "invisible" pixels as a part, and then somehow filter the inner parts, and that'll take a long amount of time and work
I prefer new Wanderer missions above an entirely new collision detection that makes the game look a little bit better

**Comment by LocalGod79** [comment]
@KiLEdEnNis your solution is brute-force, and would probably drive cpu-usage beyond the capabilities of much of our user base.

that's what M.Z. meant when he said
> and will make collision detection more complicated.

**Comment by jafdy** [comment]
What about somehow marking the sprite to use a more complete way of finding the collation box (of special efects box).

**Comment by Bladewood** [comment]
unrelated to topic at hand, but korath piercers make the "hole in the shield" effect on asteroids!

**Comment by jafdy** [comment]
And presumably on ships without shields.

**Comment by KiLEdEnNis** [comment]
@LocalGod79 indeed it would, I said it's the only way I could think of, and it's way too much for way too little

and maybe asteroids do have shields? how else can they survive Antimatter cannon fire :P

**Comment by Bladewood** [comment]
*minable asteroids*

**Comment by KiLEdEnNis** [comment]
@Bladewood well played :(

**Comment by Bladewood** [comment]
oh, also, even if they did have shields, how come my disruptors don't do anything to it?
not even effects appear.

**Comment by Amazinite** [comment]
#3621 works on this.
