### ISSUE TITLE
Mortgage Interest Rates

### ISSUE THREAD

**Issue by hdhdhd95** [endless-sky/endless-sky#1516]
@endless-sky I think way the mortages work now in the game is not the usual compound interest but don't know if I'm wrong about it.

**Comment by endless-sky** [comment]
There are two differences:

* The mortgage is paid every day, and the quoted interest rate is the daily interest.
* Paying extra on a mortgage reduces its future payments, rather than reducing its term.

Other than that, mortgages work exactly the way real ones do:

payment amount = principal * (rate * (1 + rate)^n) / ((1 + rate)^n - 1)

**Comment by ScienceDiscoverer** [comment]
Something is not right here...  If you multiply 0.4% daily interest by 365 you get 146% yearly interest. But if you then multiply principal of 480 000 for a ship by `1 + yearly_interest` you get 1 180 800 credits total to pay. Yet, if you multiply actual daily payments of `2503 * 365` you get 913 595 credits, which is less then stated interest rate! What is going on in here, can anybody explain this to me?

**Comment by ziproot** [comment]
Wouldn't the total interest paid be 433,595 credits? I think the banker says 434,000 credits.
