### ISSUE TITLE
Buff Wanderer shield systems

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1518]
Currently, I never use dark storm shielding, because it just draws so much more energy than other shield generators. Instead, I either buy a diamond regenerator or farm Raiders for a medium systems core, which each take up only a few more units of outfit space for a much lower level of energy drain, and in the latter case, much faster recharging anyway, along with several other bonuses.
I propose that you make Wanderer shield generators
A: more energy-efficient.
or B: more effective at recharging shields.
Because otherwise I literally never use them.

**Comment by MarcelineVQ** [comment]
Consider though that wanderer's haven't had a need for shield gens until this point so they may get better naturally, it's a very good subject to bring up though.

I only use korath systems cores for my ship shields, mostly because the combination of battery and shield gen is a disgustingly good space savings, and the hull regen is entirely free on top of that.
Consider that batteries alone for 5200+ energy are at least 45 outfit space.

**Comment by KiLEdEnNis** [comment]
the base shields may need to be better (like the Sunbeam, the Wanderers never needed it but it's strong)
but they'd need a "new" one for their Derecho and Hurricane when they come

**Comment by gunqqer** [comment]
You're still using non Quarg shield gen? Ew.
Eww.

the most I would do would be small system core just so when I land both hull and shield will be refilled

**Comment by Bladewood** [comment]
Trust me, everyone here knows that quantum shield generators are the best, but this issue is not about tier 3 shielding, it is about tier 2 shielding.

**Comment by endless-sky** [comment]
I just gave them a 25% boost (bec11fb). That's enough to make their generators significantly more space-efficient than a Systems Core.

**Comment by Bladewood** [comment]
Was expecting a bit more, but this is good enough, I suppose.
