### ISSUE TITLE
Only mineral-laden asteroids are destructible

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1550]
That's a bit odd. If I whale away on an ordinary asteroid with a couple of electron beams, I'd expect it to eventually blow up just like a mineral-rich one, even if it doesn't yield anything salable.

**Comment by endless-sky** [comment]
That's intentional, for two reasons:

1. I figured that the game of spotting visually which asteroids are minable is more fun than a game of just blasting everything apart and hoping to get lucky would be.

2. Normal asteroids can't be destructible because [the asteroid field is tiled](https://github.com/endless-sky/endless-sky/wiki/TiledAsteroids).

**Comment by Pointedstick** [comment]
Hmm, okay. Spotting the mineral-laden ones is still pretty obvious because they look different from the normal ones. I do understand the problems of the tiles asteroid field, though.
