### ISSUE TITLE
Improvements to Firefly Mode (dangerous space weather, etc.)

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1553]
I saw Michael talking about how he envisions this game having essentially three modes, one of which is "Firefly Mode"--roughly corresponding to the beginning of the game, where you're small and weak and just trying to get by. However, it's far too easy right now, so Firefly mode doesn't last very long! The average player will quickly and easily overcome the basic limitations of the start of the game: your mortgage, small ship, and dangerous space pirates. You're really only in "harried star captain mode" for maybe an hour before your debts are paid off, you've got a better ship, and you're on an upwardly mobile trajectory. I think it could be made more fun and evocative in a number of ways:
- Make it harder or less lucrative to get rich quickly by selling captured outfits: #1535, #227 
- Make money truly more scarce. Other captains are all griping about money but the ease with which you transcend your initial poverty makes them seem like a bunch of whiners. Lots of ideas here: #275 #329 #486 #428
- More options to do things that seem rough or desperate: scavenging space debris, mining asteroids, listening to local gossip from old spacers, gambling, etc. #325 #1552
- Make the galaxy itself seem more hostile and threatening. Asteroid storms that can damage the player's ship; systems with high radiation levels that prevent passage; Navy quarantines that reinforce their awesome power; annoying bureaucrats and rules to make you feel more sympathy with the Free Worlds, etc.

**Comment by toilethinges** [comment]
Mining asteroids is already in.

On the very last part, then we'd need more tales of horror about the Free Worlds at the same time, once the Republic and Syndicate arcs are out.

Otherwise, agreed.

**Comment by endless-sky** [comment]
One difficulty is that already there are a lot of people who find the early game so challenging that they give up - which, I know, is hard for a more experienced player to imagine. Like, there are plenty of people who post on Steam who still have not paid off their mortgages after four hours.

The game originally had licenses that the Republic required you to pay for to get almost any type of ship. For example, buying a bulk freighter would require a capital ship license and a freight license in addition to the pilot's license. That gave the player a better sense of how annoying Republic bureaucracy is - but it was also a huge pain and made the game less fun.

**Comment by Pointedstick** [comment]
I totally get it, believe me. There's a fine line between challenging and annoying; evocative, and limiting. "Hard but fun" is the goal. To that end, money management is really hard for a lot of people and fun for few. Perhaps get rid of the mortgage entirely? As a new player, I remember feeling really stressed about about the constant money burn every single day--it drove me to pay it off as ASAP, but not everyone has that instinct.

If instead you started with enough money to buy a ship without debt, then the early game could be made commensurately more challenging by reducing the payments for early missions and creating financial pressure through things like landing fees, hull repair fees, shield recharge fees, or even minor sales taxes. These kinds of fees and taxes would represent a far lower background level of money burn than the mortgage does, but provide a diminished yet still atmospheric level of financial pressure and the danger of needing to repeatedly borrow small amounts of money to pay them in the early game. Also, you wouldn't be able to simply do away with them like you can with the mortgage. The irritation of these fees and taxes would never jeopardize your career, but provide a constant reminder of the galaxy's governments and bureaucracies. It could also be used to differentiate them from one another, à la #275

**Comment by endless-sky** [comment]
As I think about this more, I think the real goal should not be to slow down the very early game (the rise from a $0.5M ship to a $2M ship or so), but to slow down the next phase after that (rising from a $2M ship to a $20-30M ship). The real issue is that once you can capture ships easily, you can earn almost arbitrary amounts of money very quickly. (Arguably, there are other ways to increase your wealth quickly at that point, like the exponential star barge strategy, but capturing ships is still the easiest source of massive income.)

The best way to make plundering and capturing ships less lucrative would be to add a depreciation mechanic, where ships and outfits slowly lose value and captured ships and outfits are highly depreciated (say, worth only 25% of their purchase value).

The mechanic would have to take into account the fact that outfits and ship hulls are completely fungible. That is, suppose I have two ships and I want to sell the energy blaster on one of them. If depreciation were tracked for individual outfits, I'd have to figure out which of the two ships was holding a less depreciated blaster, sell that one, and then transfer the other blaster to the other ship if necessary. That would be a huge pain.

But instead, depreciation could track purchase dates for outfits and ships, but not bother to record which specific outfits and ships those are. That is, "If you sell an energy blaster, the first one you sell (regardless of which one) will be 20% depreciated, and the next one will be 70% depreciated..." Not only would that be much simpler, it would also solve the fungibility issue.

A side effect of depreciation would be a constant invisible drain on your net worth, which would reduce the size of mortgage you can prequalify and also reduce your ship's trade-in value, thus reducing how big a step up you can make each time you upgrade to a new ship. If depreciation were an exponential decay, the day-to-day loss would be much more significant for a player who is buying lots of small ships all the time (exponential star barges) than for a player who holds onto a ship long after it is fully depreciated.

**Comment by Wrzlprnft** [comment]
Umm... We have a PR with a , imho, quite good deprecation system. Might just need some polish and adjusted values.

**Comment by KiLEdEnNis** [comment]
making small missions a little bit more "lucrative" (together with nerfing plundering) could make it easier?

**Comment by Pointedstick** [comment]
FWIW, I am working on a couple small missions and random events that should increase the atmosphere for captains in the early-to-early-mid game.

**Comment by KiLEdEnNis** [comment]
good luck :D

**Comment by endless-sky** [comment]
@Wrzlprnft, the existing PR makes outfits non-fungible (which, as I explained above, I don't think is a good idea) and also merges quite a few different proposed features into one PR, which makes it impossible to just pull out one particular idea and merge it in.

**Comment by egony** [comment]
Maybe having a difficulty setting (Easy, Medium, Hard, Hardcore) which adjusts your ships damage, health and vise versa with the enemies. Then, the newbies can choose the easy setting, to learn the game and the experienced can choose the hard or hardcore mode for their challenge.

**Comment by KiLEdEnNis** [comment]
you mean easy gives you a "damage mitigation" & "damage increase" while hard gives you a "negative damage mitigation (so you take more) & "damage reduction"?
seems a bit hard to do

**Comment by jafdy** [comment]
Much of the point of this game is that the enemy ships are the exact same ships that you can get, that won't change. A "hardcore" mode is planed but not top priority.

**Comment by endless-sky** [comment]
Because it's a sandbox game, there are essentially already "easy" and "hard" modes built in: if you want easy mode, you can just stick to less risky ways of earning money, or less dangerous parts of the galaxy. Or, you can choose not to start the story line until you're flying a massive alien warship.

**Comment by KiLEdEnNis** [comment]
what I do (because I'm very experienced) is just the simple idea of only using 1 ship (or max. 3)
keeps it more fun

**Comment by Bladewood** [comment]
@KiLEdEnNis For campaign missions, I only ever use 1 ship in my fleet, because I tend to get feels when I watch another ship belonging to my fleet blow up. And also because I don't want to go through the effort of rebuilding my fleet.

**Comment by KiLEdEnNis** [comment]
I went from Star Barge (Sparrow start gets boring) to Clipper, Osprey, Falcon, then campaign started
got Dreadnought, captured a Cruiser & Carrier & used them as escorts until I could buy the Derecho
one day we may see a system that balances big fights a bit on the player (like, every Heavy Warship you have, the enemy gets a Small Fleet, up to 3)
not very accurate because different ships vary, but it's more accurate

**Comment by AlbertNewton** [comment]
I usually start the campaign in my starter Sparrow or occasionally an upgrade such as a Beserker, although in my first pilot I had a Scout that I used instead of my starter Shuttle.
