### ISSUE TITLE
Nerf Korath heat shunts

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1557]
http://steamcommunity.com/app/404410/discussions/0/350541595116300660/
The large heat shunts, I mean.
I don't think they really care about the small heat shunts.

**Comment by MarcelineVQ** [comment]
I think as Wanderer's ramp up the gap will be closed or made moot; it's a nice piece of hardware compared to other tech but that's also the point I think. The triple plasma and the heat shunt are there to make you go, "Oh my god this species is insane."

**Comment by endless-sky** [comment]
The only way to nerf the heat shunts would be to also reduce the heat production of the Korath generators (and maybe their engines and some of their weapons as well). But, the end result of that would be to erode the distinction between the two current "tier 2" sets of technology: the Wanderers and the Korath.

Pound for pound, the large heat shunt is about 50% more effective than the human cooling systems. That's a significant difference, but not unreasonable given the intended difference in technology levels. (Plus, the Korath have presumably spent a *lot* of time working on cooling technology.)

**Comment by Waladil** [comment]
@endless-sky I don't agree with the sentiment that the only way to nerf the LHS would be to cool off the other Korath outfits. I need to look at the basic Korath designs but from what I've seen they don't have any heating problems. A plain nerf to the LHS wouldn't force other improvements in their systems -- especially because the number that seems to be good is 3,300, down from 3,600. Maybe, MAYBE a few of their least efficient ships would shut down from overheating due to moving, shooting, and regenerating shields all at once, but even then those shutdowns would be sporadic, and could be resolved through altering ship designs (adding a small heat shunt, for example). 

P.S. Same "Waladil" from the Steam thread, BTW.

**Comment by endless-sky** [comment]
I think you're right that a 10% reduction would be safe. Based on my testing, the only ship that would regularly start overheating with that change is a stock MPT-53, because of their large number of Repeaters. Here's a plof of the current heat generation vs. maximum dissipation for all ships, with the Korath in red:

![heat generation](https://cloud.githubusercontent.com/assets/11450262/18458837/b3751a88-7932-11e6-908b-876deba57c62.png)

If I reduce the heat shunt cooling by 10% *and* decrease the (currently ridiculously high) Repeater heat generation by 20%, that turns into this:

![repeater and shunts](https://cloud.githubusercontent.com/assets/11450262/18458856/cf0c7b24-7932-11e6-85ae-f2a690c9fdb4.png)

Most Korath ships are now above the danger line (meaning it's possible for them to overheat if firing all weapons and engines simultaneously), but given how massive they are, it takes them a long time to build up that much heat.

**Comment by endless-sky** [comment]
Changed in 64844ef.

**Comment by Waladil** [comment]
Looks like about how I envisioned it -- not much of a change to AI ships but will allow for some more diverse ship designs.

**Comment by KiLEdEnNis** [comment]
the nerf may be useful, but for future things; the Korath specialize in heat dissipation/cooling, if there are more species that specialize in other things, and you would pick all best outfits (even if they're all same tier) of course they'd be a lot better together
