### ISSUE TITLE
Allow mission directives inside conversations (payment, event, npc, outfit, reputation, etc)

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1564]
I'm trying to write a gambling mission and feel like I'm fighting the system (#1563, #1562). As an alternative to addressing either of those concerns, it to occurs to me that all I really want to do is be able to change the player's money within a conversation. Essentially I'd like to be able to do this:

```
mission "Pirate gambling"
    description "Gamble with pirates."
    minor
    repeat
    to offer
        random < 5
    source
        attributes "dirt belt" south rim

on offer
    conversation
            `Do you want to gamble with pirates?`
            choice
                `No way!`
                    defer
                `Absolutely!`
                    goto gamble

        label gamble
        branch "good luck" "bad luck"
            random < 50

        label "good luck"
        `You win some money!`
            payment 5000
            defer

        label "bad luck"
        `The pirates are cheating! Do you call them out on it?`
         choice
             `(Sure, what could possibly go wrong?)`
                 goto "bad idea"
             `(Keep your mouth shut.)`
                 goto "lose"

        label lose
        `You lose some of money to the pirates!`
            payment -10000
            defer

        label "bad idea"
        `The pirates pull out their guns and demand all the money you're carrying!`
        choice
            `(Comply.)
                 goto "lose a lot"
             `(Grab the pot and run for it!)
                 goto "really really bad idea"

        label "lose a lot"
        `The pirates take a lot of your money!`
             payment -50000
             defer

        label "really really bad idea"
        `The pirates shoot you dead!`
             die
```

You can see how it would be useful to be able to add or subtract credits at multiple points, not just in the "on complete" or "on fail" sections.

Same things with NPCs; I'd like to have some outcomes spawn NPC ships, and some not. The current mechanism of "on accept" and "on decline" isn't nearly flexible enough to accommodate this (see #1563).

**Comment by KiLEdEnNis** [comment]
"The pirates shoot you dead!"
not sure if that grammar is correct

**Comment by toilethinges** [comment]
Being shot dead is, remarkably, correct.

**Comment by Amazinite** [comment]
Not just payments, but any condition really. Events, rep, etc.

**Comment by KiLEdEnNis** [comment]
@toilethinges thanks
in Dutch (my language) it would be "de piraten schieten je dood", literally translated word by word you would get "the pirates shoot you dead", and I'm not used to Dutch grammar in English

**Comment by EndrosG** [comment]
I would like to add something to this enhancement issue.

As of now, PlayerInfo::CreateMissions() is created upon **landing** and thus checks upon landing, if a mission can be offered or not. Mission::CanOffer() then checks MissionAction::CanBeDone() for each action.

For missions which are offered in the spaceport this might not always be the "best" behaviour.
Regarding negative payments this can be particularly bad if those missions are offered in the spaceport and if the negative payment exceeds the players credits when landing, but if the player has enough commodities / outfits in cargo space / ... to be able to pay that payment.

In issue #1216 a commit ef9c175 is referenced which somewhat addresses this issue but this commit was then part of pull #1219 which was not merged (there numbered as commit 7086319)

My current usecase : I want a player to invest a certain amount of money. In a contract signing mission (on a specific planet) I tell the PC how much it would cost but I can't process the payment in this mission because the mission would not get offered if the player didnt have enough cash.
But since the contract signing mission is intended to be a close follow up after the negotiating mission, the player would consider it as a bug if the contract signing mission would not be offered (because of not having a so far *unknown* amount of cash).

-----

Ideally I want the PC to be able to sign the contract and **if** he/she has enough cash at hands to decide whether to pay immediately or later, otherway have only the option to pay later.
And I dont want to write duplicate missions for "player has enough money, so offer him a signing+payment mission" versus "player does not have enough cash right now, so offer him a pure signing mission". - Well, I dont even know how to filter the latter case explicitely, since I dont know off a cash filter condition.

**Comment by Amazinite** [comment]
Reputation can already be altered in a conversation using an `apply` node. #5157 adds the ability to use `payment` and `event` in a conversation.

**Comment by Amazinite** [comment]
#5157 now also allows for the creation of log entries within a conversation.
#5161 allows for conversation choices to trigger NPCs by using `apply` to change conditions that must be present in order for NPCs to spawn.
Should one want to fail a mission within a conversation, you should use `apply` to set a condition that triggers the `to fail` of another mission. 

Aside from `require` (ref: #2494) and `outfit` (this would be more difficult to allow in conversations, if we even want to in the first place, as there's more overhead to granting outfits than other actions like granting payments), that means that everything that can be done for a mission action can be done in a conversation.
