### ISSUE TITLE
Mass expansion can end up having negative cargo space free

### ISSUE THREAD

**Issue by luiges90** [endless-sky/endless-sky#159]
1. Ensure your cargo hold is full
2. Do some Mass Expansion outfit
3. You can end up having more cargo than you could carry

**Comment by endless-sky** [comment]
It should automatically sell off the extra cargo if you try to leave the planet. Negative cargo space basically represents that you have a stack of cargo outside your ship that you have not loaded yet - it's necessary because otherwise you could not do things like selling off a freighter if it is carrying cargo.

**Comment by luiges90** [comment]
ya, that make sense :smile:
