### ISSUE TITLE
Delivery missions allow exceeding cargo limit

### ISSUE THREAD

**Issue by sodium70mg** [endless-sky/endless-sky#16]
It appears that it is sometimes possible to exceed the cargo capacity on a ship by purchasing goods and then taking on delivery missions. After accepting the mission the Cargo Space Free indicates a negative value. The bug doesn't seem to occur if the mission is taken first: I can't buy goods beyond my listed free space.

**Comment by endless-sky** [comment]
This is actually by design: you are allowed to take on a mission if it is possible to do so by automatically selling ordinary commodities or firing crew members who are extra. This is so that if a special mission is available to the player at any point - e.g. to continue a plot line - they will not be silently blocked from being offered that mission just because they do not have any cargo space free.

The new feature I've added where a mission can display a message to the user if it is "blocked" from being offered due to lack of cargo space makes this less necessary, so maybe the ability to take on excess cargo could be eliminated by having every single special mission involve a "blocked" message. There are still times when just automatically forcing the player to sell excess cargo seems simpler, though.

Also, I suppose it might make sense to only allow special missions to force you to take on excess cargo or crew, rather than allowing ordinary "jobs" to do that.

**Comment by sodium70mg** [comment]
Yeah, I can see how this solves problems for special missions. I think an argument could be made in some cases that a player should be properly outfitted for special missions but that could run into all sorts of complications.

I am still fairly new to this game so I haven't really completed that many special missions but I don't think it makes sense to allow the basic cargo/transit missions to exceed the capacity of the current ship. It is particularly troublesome that buying goods first is allowed but buying them after is not.

**Comment by akien-mga** [comment]
As @endless-sky pointed out, this is by design and IMO this is a great feature. Please note that this is not something incoherent: you can't *exceed* your cargo limit by getting hired for a delivery mission. It will show your free cargo space as a negative number, and then you have two possibilities:
- Sell yourselves the ordinary goods that you want to discard to make place for the mission cargo until the "free cargo space" value reaches 0.
- Or leave the space station, then your excess cargo will be sold automatically (I don't know based on which creterion, whether it's random or whether the cargo that will give the best income is sold).

Once you've played as a freighter for a bit, this is a must-have feature IMO. Basically you always want your ship to be full of goods, and mission cargo will often give you a better profit. And since you'll always try to have your cargo full of ordinary goods, it's a great feature that you can still apply for jobs and discard the "lesser goods" afterwards.

Note that you can't exceed your ship's cargo limit in mission goods, that's why some missions are greyed out when you don't have enough cargo space that is not occupied by mission cargo.

**Comment by endless-sky** [comment]
Well, I think I agree with sodium70mg that you shouldn't be allowed to exceed your limit by taking on ordinary "jobs," because that is rather confusing. This feature was really just intended for special missions.

**Comment by endless-sky** [comment]
As of 11171f5 I have dis-allowed going over your cargo limit by taking on jobs from the job board. But, I will leave this open for now as a reminder that I should also add "blocked" messages to all the special missions.

**Comment by sodium70mg** [comment]
That fixed it. Thanks!

**Comment by endless-sky** [comment]
I've also gone through and added messages (in commit 3516bc9) to any of the missions in the main plot line that could be "blocked" due to the player not having enough bunks or cargo space free. So, I'm considering this fixed.
