### ISSUE TITLE
Crew on destroyed escorts do not incur death benefits

### ISSUE THREAD

**Issue by kyzentun** [endless-sky/endless-sky#163]
If crew die while capturing a ship, the player must pay death benefits to their families.  This is kinda cool and adds to the environment of the game.

After the ship is successfully captured, if it is blown up before the player can take it somewhere else to park, the player doesn't pay death benefits.  This seems inconsistent, and feels like a bug.

**Comment by endless-sky** [comment]
The real reason for "death benefits" is to make ship capture less over-powered as a way of making money. I think if you also had to pay death benefits for losing a ship, players would find that really annoying (because, it's bad enough that you lost the ship, without having to pay lots of extra money too).

**Comment by SolraBizna** [comment]
It makes sense if the contract they sign up for considers death in space due to the destruction of the ship they man as "an expected possibility", but death during an attempt to capture a ship as gratuitous, negligent, or otherwise unusual. Perhaps if the death benefits were called something slightly different... though I can't think of anything that is clear and not awkward.

**Comment by djae95** [comment]
You could call them Combat Fines, Combat Payments, At Arms Benefits, Boarding Loses, or some variant there of. Then you could just have some text about paying the families, but their is really not a word for oh you boarded a ship and lost you life because your captain is crazy so he is paying death benefits to your family.

**Comment by avivey** [comment]
Alternatively: Maybe replace the death benefits with some other way to lessen the power of capture - like a "re-registration fee/bribe", "airlock repairs"...

**Comment by endless-sky** [comment]
Since the real point of death benefits is just to keep capture from being too lucrative, I'm leaving this as-is.
