### ISSUE TITLE
Atrocity attribute for outfits to replace illegal < 0

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#1665]
Edit:
Outfits with an illegal value < 0 are able to trigger the atrocity mechanic, but will trigger the negative attributes dialog if no other illegal outfits are installed to give you a "positive" illegal value. 
Possibly create a separate attribute for outfits to avoid this problem.

Original:
I am attempting to install an outfit that has `illegal -1` and it is telling me that I do not have enough capacity in order to install it unless I have something else installed that has a positive illegal number.

**Comment by endless-sky** [comment]
Even if you could install it, it wouldn't make the illegal outfits any less illegal.

**Comment by Amazinite** [comment]
It's just annoying given that the purchase location of the outfit is far from any nerve gas in order to get a positive "illegal" stat.

**Comment by Pointedstick** [comment]
Yeah, me neither.

**Comment by LocalGod79** [comment]
logically, it triggers a negative attribute check, which;
provides loopholes to make un-installable outfits when desired
has no other effect on gameplay

(please close this issue)

**Comment by Jorbulous** [comment]
I thought outfits with Illegal -1 were supposed to count as an "atrocity" or is that just for special mission cargo?

**Comment by Amazinite** [comment]
@Jorbulous It does, but apparently you cant commit atrocities without having a little bit of fineable drugs or a few cans of nerve gas on board as well. 
@LocalGod79 Could an exception not be made where it logically should like in a case like this, where having the negative attribute doesn't break anything?

**Comment by MessyMix** [comment]
@LocalGod79 
>has no other effects on gameplay

@Amazinite is correct, negative illegal cargo does have an effect on gameplay, in the form of atrocities.

**Comment by LocalGod79** [comment]
this issue would be more concise if you had indicated "atrocity" early on, perhaps even in the title: "cannot create atrocious outfits - only mission cargo"

@Amazinite are you suggesting that you cannot accept atrocious cargo missions unless you're carrying illegal outfits?

from the wiki (Creating_Missions_)

> If the cargo is marked as "illegal," governments that care about such things will levy the given fine against you if you are caught carrying this cargo. If the fine is negative, being caught with this cargo while in flight is counted as an "atrocity" (the government that catches you immediately becomes your enemy, no matter how good your reputation was previously), and if you are caught in a spaceport with the cargo the result is a death sentence (game over).

creating exceptions to the negative attribute check was avoided when `shield energy` could not be made negative - i expect that this issue is secretly a request for an `atrocious` attribute (and that exceptions to N.A.C. will not be made).

**Comment by Amazinite** [comment]
Exactly. Outfits with a negative illegal value (I.e. atrocity outfits) are uninstallable without first installing non-atrocity illegals, as illegal is acting like a capacity; the prompt that it gives you when you attempt to buy it is not a "negative attribute" dialog, but a "this is ammo; install the weapon first" dialog. (Although that might be because the outfit was marked as being in the ammunition category).

**Comment by OmegaLokkes** [comment]
It confuses me a little as to why a meaningful stat would be made negative, wouldn't it make more sense to have it as illegal 2?

**Comment by KiLEdEnNis** [comment]
that would mean you''d have to pay 2 credits when they find it
if it was -1 you'd have to pay "-1" credit, but they become hostile (if I'm not mistaken)

**Comment by MessyMix** [comment]
And you die if they catch you on the ground.

@OmegaLokkes: a positive illegal value makes you pay the amount that is specified. A negative makes it an atrocity.

**Comment by LocalGod79** [comment]
"intended use" is key here: a negative fine for carrying **mission cargo** meant that you were carrying something considered an atrocity.

that's why the negative value is mentioned in the Creating Missions wiki page, and not in the Creating Outfits page (because a negative fine as an outfit attribute triggers the negative attribute check unless another illegal outfit is installed).

@Amazinite perhaps change the title of this issue to a request for the atrocious attribute so that the request is more apparent?

**Comment by endless-sky** [comment]
I've added a separate "atrocity" attribute to handle this (commit 12f32f6).

**Comment by KiLEdEnNis** [comment]
so illegal for example -1000 GIVES 1000 credits now? just wondering

**Comment by LocalGod79** [comment]
no, `illegal -1000` will trigger a negative attribute check when you try to install it...

**Comment by jafdy** [comment]
Or make your illegal outfits more legal . . .
