### ISSUE TITLE
fleet without hyperdrives disappears after combat

### ISSUE THREAD

**Issue by hasteech** [endless-sky/endless-sky#1675]
I was fighting pirates and a bounty at Shaula with a fleet without hyperdrives.  After the defeating the first set of ships in system, my fleet disappeared.  Adding hyperdrives to some ships sometimes fixes the problem (add a hyperdrive to the first ship only and things seem okay, but add a hyperdrive to the last ship and all the others disappear).  Save attached.

[disappearing fleet.zip](https://github.com/endless-sky/endless-sky/files/512924/disappearing.fleet.zip)

**Comment by KiLEdEnNis** [comment]
why don't they have hyperdrives anyway?

**Comment by hasteech** [comment]
It was just a temporary fleet to help out with the battle and didn't need to leave the system.

**Comment by KiLEdEnNis** [comment]
still, why take the drives out
this is a bug but it's kinda weird
and did you mean your own owned escort ships disappeared?

**Comment by hasteech** [comment]
I wanted the space for other outfits, and yes, my own owned escort ships disappeared.

**Comment by endless-sky** [comment]
OK, that was a really weird one. What's happening is that because your ships have no hyperdrive and are in a hostile system, they think they are "stranded." So, they want to ask another ship to help them, but they can't do that when there are any enemies in-system. Once the last enemy is destroyed, they all look for a ship that can help them, and the first ship they discover that is nearby and has fuel to offer is... themselves. So, they all "ask" themselves for help, then try to board themselves, which causes a divide by zero and sets their (x, y) positions to an invalid value. At which point they disappear.

In any case, commit bc6fc87 should fix that.

**Comment by Amazinite** [comment]
Lol, that is the most hilarious bug ever.

**Comment by MessyMix** [comment]
Not just hilarious. It's kinda freakin awesome.

**Comment by jafdy** [comment]
http://steamcommunity.com/app/404410/discussions/1/154645214960876817/?tscn=1483179522
This just came up on the steam forums. I think it is the same bug but it might be worth checking.

**Comment by KiLEdEnNis** [comment]
oh god the flashbacks

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
