### ISSUE TITLE
Please add an air brake for stopping immediately

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1706]
Planes have an air brake and one would be really useful for emergency stops or when you have ten reverse thrusters installed and you're going 41,000 MPH.

**Comment by toilethinges** [comment]
There's not air in space, but I don't know or care how air brakes work.

You could just hit the down arrow key and then go forward once you've turned around.

**Comment by Amazinite** [comment]
>air brake

You want to know why no one can hear you scream in space?

**Comment by Phil-Morley** [comment]
Reverse Thrusters do this.
If you implement air brakes then you would get signs 'please do not use air brakes near our planet'

**Comment by andyspurgeon** [comment]
[Hit the brakes and they'll fly right by!](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjTlpjAgtjPAhWHq1QKHQXXB2AQtwIIHDAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dhp4cy2NXblc&usg=AFQjCNEURhuygIAouynFPIudMEzHBeF8hg&sig2=xf-MGLB9Ss0H10aHBWhBKg)

**Comment by LocalGod79** [comment]
i think that @Admiral-Danforth really wants a "space brake", a way to bring the ship to a stop, without trying to maneuver the impossible task (and always just getting close to stopped).

it's been proposed in the past that an afterburner with a *tiny* afterburner thrust (like 0.001) would do the job, but the player would have to rotate their ship at an angle other than 0° or 180° (ideally > 90° to port or starboard) to their velocity vector to make it work properly.

**Comment by KiLEdEnNis** [comment]
some mechanic that can let your ship do the "hold position" thing like the escorts could be enough, so your ship can stay exactly still

**Comment by Admiral-Danforth** [comment]
i gave myself a afterburner with -.0000036 thrust and it works, it just take a few seconds and to don't have to turn at all

**Comment by johndh** [comment]
I think an "auto-stop" command makes more sense than having a dedicated outfit for it.  You can approximate it by reversing direction and applying thrust, but you can't quite get it perfect so you'll still be drifting one way or the other.

**Comment by KiLEdEnNis** [comment]
escorts can basically hold perfectly still with the Hold Position, maybe add Shift+H for the flagship to do that

**Comment by LocalGod79** [comment]
@johndh there have been several feature requests that require new key-bindings, and for the moment, adding more seems low on the priority list (especially if a solution can be implemented without adding more code, which may cause bugs).

that said, @Admiral-Danforth has confirmed that an outfit can be made (though incompatible with implemented afterburners, which can be explained in the outfit description) that accomplishes the desired effect.  if they create a pull request (or discussion in the Google Group), we can begin development (specs, sprite, etc.) of the outfit and its implementation.

**Comment by Admiral-Danforth** [comment]
Could someone please direct me towards the code for the "hold" command for escorts?

**Comment by LocalGod79** [comment]
@Admiral-Danforth line 1027 of ai.cpp

**Comment by Morcleon** [comment]
On the original topic of an air brake, would it work to have it provide a certain amount of reverse thrust while only functioning when the ship's forward speed is less than 0?

**Comment by LocalGod79** [comment]
@Morcleon i'm confused because, as near as i can tell, the issue is either resolved through a unique outfit, or some source coding that has yet to be accomplished (since the player is not privy to some ai behaviours without additional key bindings, and these are currently being avoided.)

@Admiral-Danforth a couple examples of additional-key-binding-pull-requests: #303 sits open from nearly a year ago, and #314 was abandoned.  please temper your expectations.

**Comment by Morcleon** [comment]
I was suggesting an alternative implementation of said unique outfit.

**Comment by LocalGod79** [comment]
i'm pretty sure that's what the original request was.

along with johndh's interpretation.

again (perhaps more concisely): additional key bindings (and source code) are less desired than immediately implementable solutions (that have been tested and shown to be adequate).

**Comment by retrue** [comment]
There are still problems with this.
It wouldn't be necessary to create new outfits because reverse afterburner function could be added to the current reverse thrusters (and in any case, a reverse afterburner should placed on the weapons section, it doesn't make sense it the engines section).
But we still have the problem of normal afterburners. If a ship has reverse and normal afterburners, what would work when pressing A? A new key binding would be necessary.
But if you add a new key binding the whole reverse afterburner outfit doesn't make sense, because scort ships can hold position perfectly without using any outfit.

**Comment by LocalGod79** [comment]
the "space brake" does not have significant reverse thrust: you cannot use it to fly backwards - only stop.  it employs the drag mechanic to reduce speed, rather than thrust.  it's a negative figure because drag does not apply when thrust (no matter how small) has the same vector as velocity.

the outfit description could be written such that said outfit didn't require any engine/weapons space at all: graviton engines are on all ships, and require the presence of a gravity well.  sounds like all they need is some sort of booster (and a replacement button for "afterburner" that says "brakes").

want to use them at the same time as afterburners?  i want to fire Javelins and Torpedoes at the same time, but i have to choose while i'm in combat - life is full of little decisions like these...

the a.i. does a great deal for the player, all with key bindings (or toggles in the preferences) - but, as i've said (multiple times): new key bindings appear *very low* on the priority list - reference: open p.r., almost a year old, was popularly requested, as yet unimplemented.
