### ISSUE TITLE
sound when all fleet ships are ready to jump

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#1713]
(steam link will be copied later)

A feature request in the steam forum suggests the addition of a sound, once, if you hold the jump button and all ships are ready to jump, a small sound is played.

**Comment by jafdy** [comment]
http://steamcommunity.com/app/404410/discussions/2/348293161790698611/

**Comment by spiral03** [comment]
Like this?
https://www.dropbox.com/s/tstqqjr1lj5kdxl/ship%20bell.wav?dl=0

**Comment by quyykk** [comment]
Do we still need/want this now that we have Shift+J for fleet jumps?

**Comment by cryo-es** [comment]
> Do we still need/want this now that we have Shift+J for fleet jumps?

I think it'd still be a good quality of life improvement.

**Comment by Amazinite** [comment]
I think the problem with introducing a sound for when all your ships are ready to jump is that it introduces a question of where else we could add sounds for statuses. We don't want the game to be a cacophony of different sounds indicating status updates.

We already have the visual indicator of all your ships being ready to jump, as all your escort icons in the bottom left will turn green. (I'm not sure if that was a thing when this issue was opened.) And as quyykk has noted, we've also since added a command that causes your fleet to jump the instant it is ready. So I think we can do without also adding a sound effect when you fleet is ready to jump.
