### ISSUE TITLE
AI ships destroying disabled pirate ships

### ISSUE THREAD

**Issue by TheEvilness** [endless-sky/endless-sky#172]
I jump to a system, half a billion pirates are waiting (not really) and I disable most of them.
I press b in order to try and board one of them, a Republic ship flies into the system, destroys the disabled ship RIGHT infront of me, and continues to fly around destroying the rest, and then jumps away.

Is this supposed to happen? It's preeeeeetty annoying, considering I'm just about to board a Leviathan, and then a random Navy ship flies in, destroying it for seemingly no reason.. Merchant ships doesn't do this, so I'm not entirely sure if it's supposed to.

**Comment by eflyon** [comment]
I do think it's intentional, because (setting aside the fact that it's pretty easy to justify in-universe) it would otherwise be very easy to make a lot of money by following fleets and stealing expensive ship components from the pirates they disabled.

Warships don't seem to go around blowing up enemy ships that were already totally disabled when they arrived in the system, though.

**Comment by TheEvilness** [comment]
Oh well, good points.

**Comment by TheEvilness** [comment]
But it's just that I do around 90% to 100% of the total damage, yet the Navy decides to be a total dick and destroy my work and effort. Would be nice if they would stop destroying the disabled ships if you have done the most damage to said ships. Up to the developer I guess.

**Comment by endless-sky** [comment]
A ship will never select as its target a ship that someone else has already disabled. But, ships will take shots at any enemy ship that happens to pass within range of them, even if that ship is disabled. And, they can destroy disabled ships in the process of trying to hit a different ship that is not disabled.

**Comment by TheEvilness** [comment]
I realize this, but the Navy ships seems to literally select them as their targets, as they deliberately fly towards the ships I disabled and then destroys them..

**Comment by TheEvilness** [comment]
But if you deem this not being an issue, and just me being wrong, go ahead and close the issue, I won't mind.

**Comment by omagasohe** [comment]
I'll second that this is real, after a big space battle(not really =P) no ships in system, 3 disabled pirate fighters left. A little navy ship pops in and blows the darn thing out from under my ship, takes out the other 2 and leaves. It's annoying. I do think that then should destroy it if attacked, but not if it's disabled.

**Comment by Phezzan** [comment]
As a partial solution - I've added a 'boarder' to ships.  The AI checks whether their target has a friendly boarder and chooses a different target.  I've found boarding much less frustrating... once I managed to figure out C++ 2011 pointers...

**Comment by TheEvilness** [comment]
Perhaps this should be implemented then?

**Comment by omagasohe** [comment]
Phezzan, You should do a pull request and see if it makes it in to the mainline code, It's more likely to be included if it's complete. Though follow the style guide on the wiki page. I'm sure it'll be rejected if there is a lot of work just to make it functional. 

I think whats happening is the "inspection" ships go and look at ship in the system, so it goes to ship A, see's that it's a pirate and boom, blows it up, then moves to the next ship, that's good, then so on and so forth. 

I think maybe adding a check in the govenment to see if it's ships are agressive, passive towards enemies, and if they will destroy disabled ships.

**Comment by endless-sky** [comment]
The latest code keeps merchants from traveling more than 1000 pixels out of their way to attack disabled targets. I'm not going to do more than that, though, because it totally makes sense that if a merchant is flying right by a pirate they'll take a few shots at it, or that a merchant seeing a fellow merchant in an ongoing battle will come over to help.

**Comment by thenerdfreak** [comment]
Endless, Navy ships go after pirates regardless of if they're disabled or not

**Comment by brendanjones** [comment]
Pretty sure it's as omagasohe said - it's because navy ships inspect (fly past) other ships, disabled or not. Then when the ship they're inspecting turns out to be a pirate, they fire on it as they fly past it. Whether the ship they're firing on is disabled or not doesn't come into the equation.
Is this right, endless-sky?

**Comment by thenerdfreak** [comment]
No. As soon as a Navy ship enters a system, if the disabled pirate is within a certain distance it goes straight to it and immediately destroys it. Free Worlds/ Syndicate, Militia, etc. don't do it, only Navy (I'm on Steam beta because of my lack of compiling skills, so if that was fixed in github version let me know lol)

**Comment by brendanjones** [comment]
Yeh I'm only commenting based on observed behaviour - I've got no idea what's in the code. I'm going to let someone who knows better comment :)

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
