### ISSUE TITLE
 mouse select-able secondary weapons

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#1724]
allow the player to activate secondary weapons by clicking on the secondary weapon's icon on the lower right corner of the screen. would be nice if the player could chose to activate some secondary weapons and not others in this way.

**Comment by KiLEdEnNis** [comment]
side thing
maybe allow several secondary weapons to be used at once (maybe you have meteor & sidewinders & wanna use them both at once)

**Comment by andyspurgeon** [comment]
Some other games permit the player to assign groups of weapons to hotkeys for quick selection and use...

**Comment by KiLEdEnNis** [comment]
AI ships can do it, seems stupid the player can't

**Comment by gunqqer** [comment]
Secondaries? Bah. The only secondary worth using is nukes, but even shield beetles can only use 8.

**Comment by Bladewood** [comment]
early-game.

**Comment by Lineth** [comment]
@gunqqer It does highlight that secondary weapons (besides flamethrowers and nukes) are underpowered.

**Comment by DingusShingleton** [comment]
I played a fighter pilot once entirely focusing on missile boats. Maximum gun ports. They are really quite powerful all things considered, if you play them right. Maximum speed and agility and as many launchers as possible will enable you to punch significantly higher than your weight class, simple because you can dish out damage while taking none.

My $0.02

**Comment by Lineth** [comment]
Maybe there could be a greater variety of missiles then. They feel a little wimpy to me. (okay okay i'll admit it i want my EV Nova hellhounds dammit)

**Comment by Pointedstick** [comment]
It's well known that human fighters are worthless unless you turn them into missile boats, and that missile weapons in general are not as effective as they should be given the cost of ammo and the prevalence of anti-missile defenses. On paper fighters and missiles seem like they should be fine due to their damage-to-weight-energy-and-heat ratios, but in practice most of the human ones are disappointing. The only human missiles that I find worthwhile are torpedoes when fired from medium and heavy warships; 50 tons for two launchers is usually a better trade than filling that space with two plasma cannons or one particle cannon. Still, it gets expensive--an even bigger concern as the too-easy moneymaking routes get fixed.

And yes, I want Hellhounds too. 🙂 Something with some PUNCH!

**Comment by Bladewood** [comment]
On the topic of fighters using missiles:
Capture a Tek Far 109 and fill it with Far Lek 14s and Far Osk 27s.
Give those fighters and drones nukes.
Find a Quarg ship.
LAUNCH FIGHTERS (and drones too).
Sit back and eat popcorn.

**Comment by Lineth** [comment]
An idea for a possible QoL adjustment for missiles:

Have missiles ignore asteroids so long as their tracking still works. As so far it seems a primary reason missiles seem to do so little damage is the asteroids. Maybe have there be a chance of a missile accidentally locking onto an asteroid.

**Comment by gunqqer** [comment]
Making missiles lock on to asteroids would just make them even less powerful. The only ammo consuming weapon that is worth using is an EMP mine layer that also kills shields from a plugin. With so many asteroids in almost every systems missiles are useless

**Comment by KiLEdEnNis** [comment]
adding a way for missiles to dodge is barely possible & they can't really go through asteroids either :/

**Comment by Pointedstick** [comment]
I find that the only missile weapons really worth using are Wanderer Thunderheads, which have an extremely high DPS value and can be expected to mostly hit their targets due to their speed, lifespan, and MIRV capabilities. Shooting four or five at once can cripple large faraway capital ships in a flash.

But yeah, most of the human missile weapons kind of suck. Only the torpedo-class weapons are worth it.

**Comment by KiLEdEnNis** [comment]
maybe for a start give them a "speed boost" at launch, as if they are actually launched with high speed

**Comment by tehhowch** [comment]
Disabling asteroid collisions while the target lock is active would be neat, but also hard to explain to the player, as there is no real visual indicator that a missile has or does not have a lock that can be observed in only a handful of frames. Instead, the player will just see that sometimes asteroids block missiles, but usually not, and especially not if they are "good" missiles (but the player might not even notice this last distinction).

This would heavily buff "jamming" techniques of missile defense as valid uses of space, since existing human a/m systems generally need help from asteroid collisions to protect the player in a significant manner. Spending space on a radar jammer could actually result in a load decrease on the anti missile system, as could extra cooling to const infrared tracking.

**Comment by warp-core** [comment]
Has anyone done any work on selecting/deselecting secondary weapons with the mouse?
