### ISSUE TITLE
"Nemesis" ships completely ignore out-of-range player, even if there are no other ships in system

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1731]
Took on an escort mission.
Dealt with the first set of pirates at the start system, then jumped to the end system.
A lone fury, the Spectre of Hell, was waiting.
It fired up its engines and began its assault.
But apparently, I was so far away from it (or maybe it was just discouraged from attacking me because I was flying a 27 million credit heavy warship), that it changed its mind and went back to analyzing planets out of boredom.

Later, a merchant jumped into the system, and the Spectre attacked it.

And it continued to ignore me.
Until I got in range.
Then it attacked me, and was obliterated (obviously).

**Comment by retrue** [comment]
This has reminded me of something that has been bothering me for a time.
Why the heck puny small pirate ships attack my fleet when it is composed by several heavy warships? Their behaviour is suicidal. They should jump away from the system as soon as they see me instead of attacking and being obviously obliterated.

**Comment by KiLEdEnNis** [comment]
@retrue even if you had like 500 Quarg outfitted ships most pirates would attack

**Comment by tehhowch** [comment]
I'm not sure there is an issue here - as you state yourself, you are flying a rather large and strong ship, and it is completely alone, and you are far away from it.
AI::FindTarget
```
 (looping over ships in the system)
			// Unless this ship is heroic, it will not chase much stronger ships
			// unless it has strong allies nearby.
			if(maxStrength && range > 1000. && !it->IsDisabled())
			{
				auto otherStrengthIt = shipStrength.find(it.get());
				if(otherStrengthIt != shipStrength.end() && otherStrengthIt->second > maxStrength)
					continue;
			}
```
The strength of a ship is measured essentially as "How much does it cost", and is compared across governments.
`maxStrength` evaluates to true only if the ship is not heroic (the fury was not heroic). Your flagship is the `it`. You are more than twice as "strong" as the Fury, so this block tells the ship to look for other targets close by.

We could update this to make nemesis try to chase you down no matter how far you get:
`if(otherStrengthIt != shipStrength.end() && otherStrengthIt->second > maxStrength && !isPotentialNemesis)`
(e.g. if you are on my nemesis list, I'll always at least consider you)

or

`if(maxStrength && range > (isPotentialNemesis ? maxRange * 1.5 : 1000.) && !it->IsDisabled())`
(e.g. if you are on my nemesis list, you have to be well beyond my engagement range for me to ignore you)

I have an open pull #2653 that is adjusting nemesis targeting, but currently would not affect this issue (but could easily do so)

**Comment by Jeremy-E-Johnson** [comment]
From a realism perspective I agree that it makes sense for the pirates to just turn tail an run vs a stronger force. However, I feel that, that leaves something to be desired from the perspective of game play. It could feel a bit silly if escort missions were never attacked. (though maybe the pirate fleets could scale so that they remain relevant, at least within reason)

My preference would probably be towards the first solution that tehhowch suggested, where the nemesis is always considered. I don't see much reason for a pirate that really wants to attack you to just sit idle with no other targets when they could attempt to close distance.

**Comment by hubbyist** [comment]
Another option may be to make pirates run away to meet with the next pirate force in the mission or make next attack stronger if first attackers have to turn tail and run. If they attack and lost next pirate force will not be altered.

**Comment by tehhowch** [comment]
Also regarding suicidal pirates - if they are mission NPCs they were probably given `heroic`, in which case being suicidal is the behavior they mission creator asked for.

**Comment by UnorderedSigh** [comment]
This problem has been solved by the new `hunting` trait. You can give `nemesis` ships `hunting` and they'll fly any distance to attack you, so long as it doesn't pass the invisible fence. Give it `unconstrained` and it'll ignore the invisible fence too.

**Comment by Hecter94** [comment]
Agreed with @UnorderedSigh
The issue here, as stated, seems to be resolved with the addition of the `hunting` trait from #8117 

I'm going to go ahead and close this issue, if you feel this isn't resolved, feel free to open a new issue with the specifics of what changes you'd like to see.
