### ISSUE TITLE
Instructions for the "Board a  surveillance drone" mission are not clear enough

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#175]
I'm doing the mission where you have to board a surveillance drone to steal its sensors and I'm trying to avoid pissing off the Republic. So I go to the Rasalhague system, wait until there's a big Pirates vs Republic battle, and then board one of the surveillance drones that inevitably gets disabled during the battle. Problem is, doing this simply repairs it. I can't steal the sensors. I only seem to be able to steal the sensors if I board a drone that I personally disabled, which instantly turns the entire republic hostile even if there are no Republic ships nearby. I don't wanna do this but I seem to have no choice.

**Comment by Trainbrain16** [comment]
I've been having the exact same problem.  I still haven't managed to pass this mission because every time I try I get stomped into the ground by the entire Republic Navy.  I think that it should be a lot easier to get surveillance drones to be the only Republic ships in a system, and if they are then attacking them doesn't aggro the entire Republic like it does right now.

**Comment by endless-sky** [comment]
If you attack a drone, the Republic will be mad at you for one day, but it has no permanent effect on your reputation because the drone has no crew. (That's what Kaya was trying to explain with the talk about the "Dereliction and Salvage Act," but without breaking the fourth wall by coming right out and saying, "attacking an unmanned ship has no permanent effect on your reputation.")

**Comment by Pointedstick** [comment]
Thanks! That's not exactly the behavior that I would have expected though. The legal wording given in the mission implies that exploiting this loophole will avoiding making them angry at all. I might recommend changing the mission text to indicate that the Republic might be angry and that you'll have to skedaddle out of the system ASAP, or either make it so that the Republic doesn't get mad at you in the first place.

**Comment by endless-sky** [comment]
I added some clarifying text both in the conversation and in the mission description: f4499a7.

**Comment by Pointedstick** [comment]
That's much better!
