### ISSUE TITLE
Request: add missions of massive transport of passengers.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky#1752]
Imho passengers space is infraused in the game. You get lots of missions to transport cargo on different planets, and even if there are not, you can buy all the commodities you want, without limit, in the Trading panel. However, there are very few missions of transport of passengers and most times you are transporting very small groups when you have ships like bactrians that can carry up to 175 passengers (Dreadnoughs can carry 63, Star Queens 69).
So, missions on the Job Board like "Carry 250 passengers to planet X" or 300 passengers or even more should be available.

**Comment by Bladewood** [comment]
We call those "colonies".

**Comment by Pointedstick** [comment]
There are already jobs to carry like 70 people…

**Comment by retrue** [comment]
That is, 70 people, and very few missions of those.
Right now, the only usefulness for ships with a large capacity for passengers is to be used as flagships with hired crew to capture ships.
You can have a fleet with thousands of tons of cargo space and you can use the whole of it, while at the same time you have hundreds of passengers space and you will transport most of the time no more than a half a dozen passengers, except on the rare occasions you transport 70 passengers for a colony.
Passenger space is clearly underused in the game.

**Comment by endless-sky** [comment]
In Coalition space, there are quite a few large passenger missions. It makes sense for missions for a higher-tier species to have larger payloads, so I don't see much need to increase the number of passengers on missions in human space.

**Comment by DingusShingleton** [comment]
I think i agree with your logic, but having played a specifically transport based captain the largest capacity ship is largely irrelevant because of the scarcity of missions that utilize it.

 I think it could be something as simple as a couple very long-distance transports that pay the same ratio as any other. There isn't really an economic benefit but it gives purpose to having such a big ship. 

Low hanging fruit on the player satisfaction scale. Actually that might be something that even I can complete

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
