### ISSUE TITLE
Escort jobs should always originate or terminate in a dangerous region of space

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1773]
It's always seemed weird that you could get an escort job where both the source and destination are peaceful and safe regions of the galaxy, yet magically pirate fleets show up as soon as you take the job! As a gameplay matter, this often makes the jobs very easy since the heavy Navy presence assists with the pirates, or even does your job for you. Realism-wise, in such regions of space, hiring private protection is a waste of money when your taxes (there are those missing space taxes again…😉) are paying for a government military force to do the same thing.

If you agree, I would be happy to make this change, but I though I'd run it by folks first before submitting a pull request.

**Comment by DingusShingleton** [comment]
Could also really help to mitigate the profit margin of sparrow escorts missions in the super-early game. I strongly concur!

**Comment by Admiral-Danforth** [comment]
Paranoid people would probaly still pay

**Comment by Nightmareman** [comment]
By that same logic every corporate building and warehouse that has tons of security in the real world shouldn't because they are in the middle of a safe area. The escort is there for the same reason such buildings have such high security. Besides who is to say all those "pirates" are actually normal pirates and not people who have been payed off by a rival to get rid of some of the competition. Think about it if your rivals lose ships more often then you do then not only do the suffer the costs of losing the ships and cargo but also the trust of anyone they were doing a runs for so now all those people come to you. Since everyone would probably be playing the same game to try and get on top you also have to invest in defense against all your opponents.

**Comment by Pointedstick** [comment]
Implemented in https://github.com/endless-sky/endless-sky/pull/1777.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
