### ISSUE TITLE
Why are Neutral planets still "Neutral" after the war has ended.

### ISSUE THREAD

**Issue by Admiral-Danforth** [endless-sky/endless-sky#1782]
Change them to independent or something. Another option would be to have more backstory surrounding this.

**Comment by jafdy** [comment]
Deneb should stay neutral but Tarazed and surrounding systems should change to FW and Poisonwood should change to Republic.

**Comment by Bladewood** [comment]
And Girtab stays neutral?

**Comment by toilethinges** [comment]
Girtab independent?

**Comment by jafdy** [comment]
I bundled Girtab with the near Tarazed systems. The assumption was that it was made neutral so that the player (and any NPCs) didn't have to be able to make 4 jumps.

**Comment by tehhowch** [comment]
#2541 attempted to address this, I think.

**Comment by Amazinite** [comment]
This has been covered in 9804d6c.
Poisonwood now shows as part of the Republic once the Free Worlds and Republic are friendly.
Harmony now joins the FW doing the eastern expansion instead of remaining neutral.
Tarazed either joins the FW or shows as part of the Republic again depending on the branch you take.
