### ISSUE TITLE
Overkill deaths

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#1786]
http://steamcommunity.com/app/404410/discussions/2/312265327168406077/?tscn=1477664598

If a ship is overkilled then have them blow up instantly. 
Could reduce load in large fights.

**Comment by gunqqer** [comment]
I agree with this! 
I've lost major DPS due to a small ship being in the way. 10 bactrians with 4 skylances on it should annihilate almost anything (of human origin). Realistically it would just punch a hole through the ship. A huge huge UUUGE hole.

**Comment by solardawning** [comment]
Rather than getting into weird complexity with damage per frame, how about this:

- When a ship's hull reaches 0, it begins the explosion sequence, as current behavior.
- The ship can continue to take damage from incoming fire.
- If the ship takes additional damage equal to 50% of maximum hull (a.k.a. reaches -50%), it skips immediately to the final explosion.

That way exploding ships can continue to soak damage and act as cover, but there's a sane limit to it before the derelict is immediately destroyed.

**Comment by Bladewood** [comment]
hmm... how about taking additional damage just speeds up the explosion process? do we have to make it instantly happen after we reach -50%?

**Comment by KiLEdEnNis** [comment]
maybe dealing a certain percentage of the ship's max hull on an exploding ship skips a percentage of total explosions?
& dang 8 thumbs

**Comment by DingusShingleton** [comment]
Perhaps split the difference between a fixed point and tracking damage per frame, and set it to make a random check to instantly explode when it reaches -30%, -50%, and -70%? Could be the same chance or increasingly likely. That combined with the variance in how much DPS you are dealing/how much hull different ships have should make it seem fairly natural and not just a preplanned event every time.

**Comment by Aq32** [comment]
There are already weapons that can pierce. How about make beam weapons always pierce through wrecked ships with reduced (but increasing/scalable) damage until it explodes? As for projectile weaponry (missiles, mines, energy blasters etc) the wreck should remain an obstacle but has a low % chance of piercing whilst doing full damage.

I like the idea that the "destroyed" ship can still block damage but wrecked ships are as immortal as certain asteroids until they explode. Logically however, "destroyed" ships have had enough damage already applied to pierce it's hull at least once. Since the game isn't that complicated (battle damage from any direction pierces the hull at least once), we should stick with the idea that weapons can pierce without having to deal a whole 100% ship's hull armour again. Perhaps scale pierce damage and pierce chance based on "Hull remaining the moment ship disabled".

**Comment by endless-sky** [comment]
In the midst of a pitched battle, hiding behind dying allied ships is one of the ways you can turn it into a skill game instead of relying on pure firepower. So, I'd prefer not to make a change that makes it so you're not able to do that.

**Comment by KiLEdEnNis** [comment]
if you have enough firepower you don't need to hide behind ships :P

**Comment by EndrosG** [comment]
Alternative suggestion :
Reduce the chance that enemy fire hits a death ship to (100% - overkill).
- A ship with just 0% hull is still a 100% obstacle to enemy fire. You can hide behind it with 100% safety.
- A ship with -25% hull (i.e. 25% overkill) still gets hit in 75% of the cases, the other 25% behave like if the ship would have already exploded (or as if it were cloaked).
- A ship with -50% hull is only hit every 2nd shot (on average).
- Hiding behind a -90% ship is pretty much useless.

Optionally, the ships hull could be reduced during the explosion process too, but I think I would not do that.

This way you can punch holes through the death ship, but at an acceptable cost.
And, since the chance to hit the death ship is getting lower and lower over time, it is harder to drop a death ship from -50% to -60% compared to -10% to -20%. I.e. from the point of view of the allies of the death ship, the rate of protection loss drops over time. Assuming the enemy does not insta-blast that ship to -100% (because it was just a drone or a fighter, not a carrier)

**Comment by MessyMix** [comment]
@EndrosG I really _really_ like the sound of that idea, but I'm afraid that it will add uneccessary complexity to the game + make it harder for people to learn exactly what is going on. Still, that is an awesome idea—I can just imagine skylances flickering through the hulls of wrecked ships!
