### ISSUE TITLE
Why are there no missile turrets? Would be good for Free World Missions (missile frigate/missile cruiser)

### ISSUE THREAD

**Issue by Johny-Cash** [endless-sky/endless-sky#1790]

**Comment by Pointedstick** [comment]
Missiles are mostly guided and have a long range, so they aren't as sensitive to a ship's orientation as guns are. Therefore most engineers would probably reach the obvious conclusion that turret space, being at a premium, is more efficiently devoted to turreted guns or anti-missile systems.

The only missiles turret that would really make sense to fire from a turret would be unguided munitions like Javelins or Heavy Rockets. Why don't you make some and put 'em in a mod?

**Comment by Amazinite** [comment]
>Why don't you make some and put 'em in a mod?

Tfw you already have

**Comment by toilethinges** [comment]
> a quad Javelin turret

We're doomed.

**Comment by Johny-Cash** [comment]
How the heck do you make a pull request!!???

**Comment by retrue** [comment]
You fork endless-sky, creating that way your own copy of the game, then you edit the files on your fork and submit the pull request to endless-sky/endless-sky.

**Comment by Elyssaen** [comment]
You still working on this, @Johny-Cash? I definitely like the idea of a Quad Javelin Turret, and a Heavy Rocket Turret gives me nostalgia for EVO's Voinians. I could see both appearing in Small/Large Southern Pirates, probably on a variant Modified Argosy and Falcon (Javelin) and Bastion (Heavy Rocket). If I remember rightly, both these projectiles are manufactured and sold mainly in the South, and Javelins are preferred by pirates.

**Comment by Bladewood** [comment]
I can't see a quad javelin turret appearing, unfortunately.
The javelin launcher is 12 tons.
The beam laser is 8 tons.
We only have a dual beam laser turret, no quad turret.

**Comment by Elyssaen** [comment]
Doesn't mean someone couldn't have made one. If it scaled as the Quad Blaster, it'd be 60 sp. It's not unfeasible, and wouldn't break a record. It's also worth considering the Javelin Pod/Launcher isn't _12_ tons, but _4_ tons, and the ammunition visibly loaded is 5x3. Consider another 5x3 behind, at most (I wouldn't expect a back row at all), and the whole launcher contraption that we'd be putting on a turret is only 5.2 tons. The remaining 6.8 tons are Javelins, presumably in a magazine whose ammunition is fed in.

A Quad Javelin Turret would need a mechanism for pushing Javelins up into the four Javelin 'launch pods', one that didn't interfere with the turret, but it'd pretty close to a Quad Blaster Turret in mass _on the turret_. The rest would be magazine space internal to the ship.

It certainly wouldn't contradict the Free Worlds comment that the player hasn't seen a turret as big as a Plasma Turret, because even if both took 60 sp, the Plasma Turret could well be a much larger turret.

**Comment by jafdy** [comment]
@Elyssaen They are just pictures. Also when we talk about launcher mass we are talking about a fully loaded launcher.

**Comment by Elyssaen** [comment]
Sure, we're talking about a fully loaded launcher, but would they realistically mount the entire magazine on the turret mechanism? That's tripling the weight of the turret for very little reason. A 60 sp Quad Javelin Turret isn't equivalent to a hypothetical Quad Laser Turret. The Javelin Turret is a much smaller turret mechanism with an extended magazine: the Quad Laser Turret is, apparently, four full laser weapons, the entire mass of each, all on a turret.

_(We're ignoring, for these purposes, that the **right** way to construct a series of laser turrets involves a single laser in the heart of your ship, and a bunch of mirrors... not to mention a phased array rather than a moving turret.)_

**Comment by jafdy** [comment]
So your saying that if it's not shown in the picture it doesn't exist. If yes then you would mount everything on the turret. If no then you can have most of the weapon away from the turret regardless of weather you are using missiles or lasers.

**Comment by KiLEdEnNis** [comment]
if the ammo wouldn't be in the launchers, then why can't you use those torpedoes you looted, the javelins you have left in your cargo capturing a pirate ship etc.?
balance purposes, and a launcher probably isn't only the launcher, but also like an ammo storage etc. next to it

**Comment by Isaacssv552** [comment]
I've made a javelin turret and added it to the most recent version of my [BAM](https://groups.google.com/forum/#!category-topic/endless-sky/content-creation/qoBwc77VLoA) plugin. No thumbnail for the outfit because I can't draw.

**Comment by KiLEdEnNis** [comment]
it's not really necessary to draw, just make the outfit in Blender, color it, render it & add it
