### ISSUE TITLE
[Mechanics] Random values in text files

### ISSUE THREAD

**Issue by Mavleg** [endless-sky/endless-sky#1810]
I think it would be neat to be able to set normally static values (such as outfit cost, weapon damage/reload, etc...) to a random value within defined parameters.
e.g. outfit price: 300k-400k -or- weapon reload: 10-12

An idea to play around with. any feedback is appreciated.

**Comment by KiLEdEnNis** [comment]
can you please start using the google group @Amazinite pasted on another of your issues that doesn't belong on Github?
& about the question; I doubt there's a feature for that yet

**Comment by Amazinite** [comment]
@KiLEdEnNis I left this one be because it doesn't exist yet or hasn't been asked before (that I know of) like the other two, making it more of a feature request. 

On the request itself, I think that random outfit space doesn't make any sense at all, but random reload and damage seem interesting, albeit probably difficult to convey in the stats of the weapon (unless it shows the minimum value like range does).

**Comment by retrue** [comment]
Random outfit cost inside of some range makes sense. Same like random price of commodities.
It is not a feature that is in this game, and the way the game itself works should be changed to accomodate this. Not that I think it would be implemented in the main game, but in a plugin could work.
And random damage is very typical of rpg.

**Comment by Mavleg** [comment]
@KiLEdEnNis @Amazinite My apologies to the both of you, I did not realize that I was breaking the guidelines. I will do better in the future.

**Comment by jafdy** [comment]
This would be an enhancement.

I can see why you would want it but it seems like it may be too much effort. And in the far future I would expect things to be quite reliable. That said if a weapon is supposed to be a bit unpredictable (Gatling gun) then it may fit.

**Comment by KiLEdEnNis** [comment]
@Mavleg I don't really mind, just helping :P
