### ISSUE TITLE
Really long hails go off the screen

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1825]
![screenshot 2016-11-15 17 28 10](https://cloud.githubusercontent.com/assets/16506683/20326937/0777f058-ab59-11e6-9f60-e792f5805917.png)
On an unrelated note, typo in the song name.

**Comment by KiLEdEnNis** [comment]
I feel like these kinda hails become too long, anyone else?
in case people wonder about the typo: wont should be won't or will not

**Comment by Pointedstick** [comment]
If MZ would accept my pull request to clean up the music-related hails (https://github.com/endless-sky/endless-sky/pull/1754), this would go away. 🙂

**Comment by tehhowch** [comment]
While the OP image is no longer possible due to #1754, there's nothing preventing a future hail from going off-screen. Seems like maybe the messages should be drawn within the "message box" with the help of WrappedText rather than just simply drawn.
Relevant:
https://github.com/endless-sky/endless-sky/blob/c6c5d149262e74662c0c82f076af35f130dfdfbc/source/Engine.cpp#L782-L800

**Comment by tehhowch** [comment]
Setting the wrap width to an absurdly small value just for demonstration:
![image](https://user-images.githubusercontent.com/20871346/33348573-81c2b712-d45c-11e7-9b44-5e825c66c34a.png)

**Comment by Pointedstick** [comment]
Should be fixed with https://github.com/endless-sky/endless-sky/pull/3313 being merged.
