### ISSUE TITLE
Choosing laser weapons over blaster weapons seems like a no-brainer

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#183]
I've gravitated towards laser weapons because they seems to be straight-up better than blaster weapons. They're easier to hit with, deal higher DPS, use less energy, and generate less heat. The only disadvantages are their greater cost and weight and lower range, but after a while money becomes no impediment, and the lighter weight of blaster weapons is easily offset by the need for bigger generators, batteries, and heat dissipation systems. As for range, that is indeed a bit of a disadvantage, but only a *bit;* the heavy lasers have nearly as much range as the blasters anyway, so it barely feels like a loss.

**Comment by endless-sky** [comment]
Blasters are intended to be the cheapest, weakest weapon. But, note that they do 20% more damage per second per ton than lasers, and for quad blaster turrets, that ratio increases to 32% more. In some situations (for example, on a ship where heat dissipation is not a problem), that makes blasters useful.

**Comment by Frozen-byte** [comment]
Indeed they do more DMG per needed space, but their lack of accuracy ships are not worth the trade.
I would suggest to give Lasers lesser Shield damage and even more Hull Damage, so you have to Mix them to be efficient.

**Comment by djae95** [comment]
Here is a PDF comparison of the two weapons and the beam does seem to be more cost and space effective than the blaster, but while the per tone 20% damage is their it is just not comparable to the benefits the beam gets compared to the negatives it gets. I think the best way to fix the balance issue is to give the beam a negative trait of some sort, the best way I could see to do it is increase the heat output of the beam weapon or fiddle with the attack damage to shields and hull plus some other modifications, all that the PDF is doing is showing that the balance between the 2 weapons seems off at the moment and needs to be fixed.

[Blaster and Beam Changes.pdf](https://github.com/endless-sky/endless-sky/files/33079/Blaster.and.Beam.Changes.pdf)

p.s some of the changes I did are extreme and they are just ideas and are probably not the best thing to do for the over all game but the beam needs some changes to not be so much better than it counter part blaster.

**Comment by Pointedstick** [comment]
I think the damage-per-second-per-ton advantage of blasters would be more pronounced if ships--particularly larger ones--had more weapon hardpoints available so that you really could cram in a lot more blaster weapons than laser weapons. The small number of turret hardpoints in particular seems to be encouraging me to optimize around smaller numbers of heavier weapons.

For example: if I have a three turret ship with 110 tons of weapon capacity, I can install two heavy laser turrets and a heavy anti-missile turret. Compared to the alternative of three quad blaster turrets, I get good anti-missile capacity, 100% un-dodgeable accuracy, nearly as good shield DPS (432 vs 540), much better hull DPS (888 vs 540), much lower energy usage per second (240 vs 600), and much lower heat output (548 vs 2,100). The 35 tons of outfit space I lose compared to the three quad blaster turret scenario would easily be taken up with more powerful generators, batteries, and heat dissipation equipment, which is all very bulky.  And I wouldn't have any anti-missile capability at all. With the laser turrets I can probably get away with a medium-size generator and a supercapacitor or two and probably forget the cooling equipment entirely, saving a lot of space that I can use for other things.

**Comment by endless-sky** [comment]
The whole point of blasters is to be the smallest, weakest weapon in the game, for use on tiny ships that don't have room for anything bigger. So, it's much fairer to compare them to ordinary beam lasers than to heavy lasers, since heavy lasers are really competing against pulse cannons in their weight bracket:

Energy Blaster: 5 T, 45 DPS, 9 DPS/T, 50 EPS, 175 HPS, 420 range, projectile
Modified Blaster: 6 T, 60 DPS, 10 DPS/T, 80 EPS, 275 HPS, 450 range, projectile
Beam Laser: 8 T, 60 DPS, 7.5 DPS/T, 30 EPS, 72 HPS, 300 range, beam
Pulse Cannon: 13 T, 135 DPS, 10.4 DPS/T, 72 EPS, 210 HPS, 450 range, projectile
Heavy Laser: 15 T, 108 DPS, 7.2 DPS/T, 60 EPS, 132 HPS, 400 range, beam
Plasma Cannon: 25 T, 210 DPS, 8.4 DPS/T, 100 EPS, 600 HPS, 480 range, projectile
Proton Gun: 28 T, 180 DPS, 6.4 DPS/T, 112.5 EPS, 450 HPS, 528 range, projectile
Particle Cannon: 30 T, 162 DPS, 5.4 DPS/T, 105 EPS, 360 HPS, 750 range, projectile

Within the "tiny gun" weight class, energy blasters have the advantage of a much longer range than lasers. To me that seems like enough of an advantage for them. Plus, keeping normal blasters weak leaves enough headroom for modified blasters to be an improvement without being overpowered.

**Comment by PhoenixRiver** [comment]
The weight difference makes a huge difference when trying to wedge weapons in mid sized freighters - particularly turrets... the choice for the 1.5M credit freighter is two heavy laser turrets or a heavy anti-missile and two quad-blasters... the choice for a trader is obvious... blasters dissuade attacks and anti-missle means running is an option without taking too much damage.
Worth remembering that weapons are used for defence as well as offence and that choices do not necessarily remain the same :)
