### ISSUE TITLE
Argosy turret hardpoints

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1835]
>turret 0 -8
turret 0 12

is a bit off. It should be
>turret 0 -12
turret 0 8

instead.

edit: also, is
>engine -16 82
engine 16 82

correct? Would something like
>engine -20 87
engine 20 87

be better?
(not sure about that one, because the Argosy's [exhaust systems?] in the sprite are already weird, but in-game, the flares seem to be at weird positions)

**Comment by endless-sky** [comment]
Fixed in 5cad0fa. It's possible those hardpoints were left over from the original Argosy graphic, which we must not speak of because it was...

![argosy-old](https://cloud.githubusercontent.com/assets/11450262/20604701/bf67a36a-b235-11e6-9312-7ec09757ad6b.jpg)

...embarrassing. (That's from before I started using Blender models for all the ships, when I was still drawing them by hand.)
