### ISSUE TITLE
Hand to Hand Enhancements

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1859]
Could you add tags to the Hand to Hand category for weapons and body armor so the values stack?
Also one for special training for boarding operations or add a Marines section to the hire crew where the marines have extra value in boarding operations and can man turrets but cannot be used as ships crew.

**Comment by KiLEdEnNis** [comment]
the offense value is used when using attack, the defense value is used when using defend, unless both sides defend
there isn't body armor, not sure where you got the idea
crew with higher boarding stats would make the game a bit unbalanced, as hand-to-hand outfits already give enough boosts

and you asked to add tags, any of these enhancements aren't made through tags as far as I know

**Comment by Bladewood** [comment]
He must be using mods of sorts.
I faintly remember a certain modpack that added in lots and lots of OP hand-to-hand outfits, including "crew training" and "body armor."

**Comment by Elyssaen** [comment]
By tags, I think he means he'd like to see this as a front-end option:

```
outfit "Fragmentation Grenades"
	category "Hand to Hand: X"
...

outfit "Fragmentation Grenades"
	category "Hand to Hand: Y"
...
```

and then have different sub-types of Hand to Hand stack.

It... doesn't seem like a good idea to me though. It just doesn't feel like an enhancement that makes Endless Sky more like Endless Sky: the game isn't really _about_ boarding. What we have now is a fairly simple trade-off system between Laser Rifles, Fragmentation Grenades, Security Stations and Nerve Gas. The only enhancement I'd ask for any time soon is for AI ships to randomly carry them. 

I think a key question to this 'stacking' idea is: does it actually add depth, or simply mean you're _always_ going to want the best possible stacking combination all the time? If so, the gameplay's no different, you just have more outfits you need.

Specialised crew _could_ be really interesting, but for me my first priority in that would be how specialised crew affect flying my ship. But later down the line, Marines/[espatiers](http://www.projectrho.com/public_html/rocket/astromilitary.php) aren't a bad idea.

**Comment by KiLEdEnNis** [comment]
> The only enhancement I'd ask for any time soon is for AI ships to randomly carry them.

instead of having a ship's outfit with "Fragmentatgion Grenades" 10, have it like "Fragmentation Grenades" 8-12 (between the values)
that's simple to add and could add a little bit more

but the boarding stuff doesn't get more fun with these enhancements, only easier, probably OP (make boarding the best way to get money again by far) and maybe slightly more realistic

**Comment by Admiral-Danforth** [comment]
Finally a way to capture a world ship

Maybe.....

**Comment by toilethinges** [comment]
@Admiral-Danforth, you already can (although very hard).

**Comment by retrue** [comment]
@Admiral-Danforth and you cannot do anything once you have captured the world ship. They don't have jump drives and there is not way to install one there.

**Comment by Bladewood** [comment]
@retrue after 0.9.4 happened, you can capture a world-ship in Kor Efreti space and bring it through the opened Eye...

**Comment by TheEmeraldRanger** [comment]
I think there should be more hand to hand outfits, but after all. Doesn't matter, adding more hand to hand outfits is good enough to me. But yeah, this game isn't about boarding, it would be preferable to just add a few more hand to hand outfits. All I would prefer, after all.

**Comment by KiLEdEnNis** [comment]
more hand-to-hand outfits; people would just buy the best offense one (& maybe also the defense one)
it's not needed at all

**Comment by Elyssaen** [comment]
I mostly agree with you, @KiLEdEnNis, though there's probably some space for it here and there. If the power creep of the game (all but confirmed as intended for the future) reaches the point that it's okay to capture Wardragons, a T2/T3 Nerve Gas would be fine as a power-up. I also have a mission I'm making that's going to give you a very limited number of something outright better than Nerve Gas (and legal), the idea being it won't shift the balance very much as you'll get about 10 ever.

**Comment by DingusShingleton** [comment]
I don't know if I would qualify that as power creep, so much as a natural progression through content.

That is, every game starts out at the same level and your power level as a pilot only increases as you make money and unlock new tech/discover new alien civs. I think what @KiLEdEnNis was saying is that if you add more H2H outfits at the starting level, there will be no real reason to take anything but the best.

Something like @Elyssaen's  idea for an extremely limited H2H outfit that you get from a quest chain is a great one, and a really cool way to give some serious boarding clout to smaller vessels so that they punch at a much higher weight class (Think interceptor capturing light warship) This is something that can be hard to do with stock outfits without allowing bigger ships to become that much more overpowered as well.

**Comment by KiLEdEnNis** [comment]
I never said hand-to-hand stuff shouldn't be made for other species; Intrusion Countermeasures, Pug Biodefenses & then similar items could be made
and a species having better hand-to-hand stuff could be a thing, but it would be hard to balance

**Comment by Admiral-Danforth** [comment]
Mind Manipulation could be a T3 outfit
No Killing=No Loss of Life

**Comment by SonEasterZombie** [comment]
At the current moment the balance between the defensive items and the offensive items is way tilted towards defense. there needs to be new offensive items for the different races, like a new rifle from the exiled korath, or Pug Bio-defense grenades. at this point in the game it is unreasonably difficult to board ships like the world ships and have any chance of success without building a ship entirely designed to board the world ships and then its only a tiny chance of victory and you then can't make it back before dying because both the ships will have like 2 pilots maybe.

**Comment by jafdy** [comment]
@SonEasterZombie Have you ever played a KWYK (keep what you kill) playsile? Capturing ships is completely OP.

**Comment by Elyssaen** [comment]
I think the balance should probably always tilt to defence in the way you say, @SonEasterZombie. It only really applies to ships that are supposed to be just about unobtainable, or far more difficult for the player to capture than the ship's crew size. The majority of ships don't even stock Fragmentation Grenades.

For the unobtainables (World-Ship, Quarg), it's a somewhat nicer way to achieve it than `uncapturable`, `never disabled` or `self-destruct 1`. And I guess at least some of these _will_ be obtainable in the future, with a higher tier of Capture Attack item finally unlocked... but the ability to capture, say, Quarg ships is a big deal and shouldn't come lightly.

For the harder-than-their-size, imagine this. If Pug Biodefences weren't overpowered, Pug ships – not supposed to be easy to capture – would probably need a self-destruct instead. Anyone who's farmed the Kor automata will attest that's not better.
