### ISSUE TITLE
Outfit Changes

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1861]
Not sure if this is mechanics or enhancement.
I'm working on an added armor outfit that will add hull but would be destroyed if it takes damage.  Is there any way to do this currently?  if not would it be too much trouble to add an armor attribute to ships and remove the armor outfit when it takes more damage than it provides armor? 

How about adding an outfit tag "requires" to indicate that one outfit requires another to be installed.  Such as a normal launcher that can have a magazine extension like a Sidewinder Missile Launcher and a box launcher that will fire Sidewinders but cannot use a magazine extension.  The magazine extension would have requires "Sidewinder Missile Launcher".

A destroyed on use tag which would make possible such things as drop tanks?

**Comment by KiLEdEnNis** [comment]
no, there is no way to do this, and as far as I know there aren't any plans to add it
and outfits that would have a requirement for another outfit would be very annoying, and it wouldn't make sense; if an outfit requires another outfit, it should be made as 1 outfit
and in the case for ammo boxes; you don't require a launcher to have an ammo box installed, the ammo box would just be useless
and what do you mean by drop tanks?

**Comment by Elyssaen** [comment]
**Outfit destroyed on taking hull damage** – don't think there's any way to do this in .txt files. I also don't think this is a trivial code enhancement, though probably not enormously difficult either. But you'd have a hell of a time convincing anyone it's a good idea, let alone a priority. I get what you're trying to do and why, but it doesn't fit existing design philosophy very well (which says 'no' to any +Hull outfit, for starters).

If you want something mechanically similar but with a different theme, you could set up an outfit as follows:

1. Launches a null munition (velocity 0, lifetime 1) that decays into a single submunition. _[This bit's only needed if the AI is going to fire it, I think I remember it will avoid firing a weapon that will hit itself with the parent munition.]_
2. Submunition also has lifetime 1, and a blast radius of 10-15 which is only likely to hit you.
3. Submunition does _negative_ shield/hull damage.
4. The weapon uses "Shield Cell" ammunition.
5. If you want the AI to use it, your best shot is: a) have a second submunition which is invisible and has a range of at least 600: the AI will need to feel it's going to target someone; b) rely on negative shield damage, not negative hull, and c) set any AI that has this with the "frugal" personality, so it's not too likely to burn through Shield Cells when it's at 100% (it will often only start using them when Shields < 50%).

It's something I'm playing with myself, but it's just a little too clumsy. You could try burning ammo that itself provides +Hull, but I don't know if this will even work and I can't think of a good implementation of it.

**Outfit tag: "requires"**  – think it's possible in .txt files already. Give the Sidewinder Missile Launcher "rack support" 10 (definitely a good amount more than 1), and the Sidewinder Missile Rack "rack support" -1. It's the same principle as ammunition, but you're not going to tell anything to use your Sidewinder Missile Racks as ammo. Try it out and let me know if it does work.

**Destroyed on use / drop tank**  – so, destroying something is supported through the "ammo" attribute on a weapon, but the real problem here is "on use". A drop tank (for @KiLEdEnNis) is a fuel tank you'd jettison when it's empty. Then we're talking about hull plating that destroys itself when the hull it provides is burned through. Those are pretty different "on use" conditions to one another, so I can't easily imagine a simple "destroyed on use" attribute that knows what it means to use an outfit. It's a cool idea, but is probably a non-starter in ES.

**Comment by KiLEdEnNis** [comment]
jettisoning an empty fuel pod doesn't make much sense to me, just refill it

**Comment by jafdy** [comment]
MZ has noed having outfits that boost shield/hull.
