### ISSUE TITLE
Selling items on uninhabited planets

### ISSUE THREAD

**Issue by Phil-Morley** [endless-sky/endless-sky#1870]
another minor one but if you change flagship and park the one you had been using, the items in your old ships cargo change to your new main ship (not sure if this has changed as I had thought you could leave freighters full of stuff parked, but maybe not). Anyway before taking off you get you must sell x amount of goods before taking off. This happens on uninhabited worlds too :)

**Comment by endless-sky** [comment]
That's intentional, mainly to handle the case where you buy or sell ships - you wouldn't usually want the cargo to be sold along with the ship. The way it actually works is that when you land on a planet, all your cargo on the ships that are landed there gets "unloaded," and then it gets loaded up again as efficiently as possible (prioritizing mission cargo) when you take off again.

**Comment by Phil-Morley** [comment]
Cool, just amusing on an uninhabited planet :)

**Comment by nickshanks** [comment]
This should be re-opened. Dumping lowest-value cargo when overloaded on take-off from uninhabuted worlds makes sense. On ships with an outfitter, outfits are stored on take-off. On planets with a trade centre, you are told to sell them yourself. It's only when neither of those are an option that we should dump cargo.

**Comment by Amazinite** [comment]
Let's just refer to the newer issue.
