### ISSUE TITLE
Map Crash: Uninstalling a Plugin with Active Missions

### ISSUE THREAD

**Issue by comnom** [endless-sky/endless-sky#1874]
After uninstalling a plugin while you have missions from the plugin active, the destination can become an empty string causing a CTD upon opening the map. Presumably because the source/destination is a now non-existent planet.

An offending save. Not mine but from [this steam help thread](http://steamcommunity.com/app/404410/discussions/0/154642321538602283/):
[Charles Broadsword.txt](https://github.com/endless-sky/endless-sky/files/628850/Charles.Broadsword.txt)

**Comment by Admiral-Danforth** [comment]
Plugin uninstalling needs to be smoother in general.

**Comment by tehhowch** [comment]
#3994 has made it so that the save is not modified until you actually "Enter" into the game (or pick a different pilot and Load Game). So it's no longer an instant shredded save if you launch the game after removing a plugin. Granted, mostly this will only be noticed for players who run from a terminal, as the warnings about undefined references are otherwise tucked out of sight.

That said, the behavior documented here is still going to happen if you *do* enter the game with a pilot and a missing plugin for that pilot, so this will stay open until we can work out a good mechanism to handle missing knowledge.
