### ISSUE TITLE
Mining Cannons

### ISSUE THREAD

**Issue by egony** [endless-sky/endless-sky#1886]
I've been working on a damage type for mining (asteroids). Do you think having separate cannons for mining is too much trouble, or is this a good mechanic?

**Comment by Wrzlprnft** [comment]
we made improvised asteroid mining before it was embedded in the source code. there we chose to make extra mining lasers by making the asteroids extreme low health and the mining laser extreme low damage....

MZ did choose not to keep mining damage and normal damage seperared. i guess to keep it simple.
i'd wait for his response,though.

**Comment by KiLEdEnNis** [comment]
btw, it's mining, not minning :P

**Comment by jafdy** [comment]
https://github.com/endless-sky/endless-sky/projects/1

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/issues/992#issuecomment-215289485
> Mineable asteroids can be destroyed by any weapon that does hull damage.

**Comment by BorkBorkGoesTheCode** [comment]
It would be interesting if the quantity of materials recovered decreased with damage dealt to the asteroid; then you could have a low-damage mining weapon which was useless for fighting but provided more materials.

**Comment by DingusShingleton** [comment]
That's a beautifully elegant way to have mining specific weapons imo. Perhaps shooting an asteroid generates a certain ore/second based on what ore is inside the asteroid. The longer you shoot, the more minerals pop out, thus, higher damage = less time = less reward.

**Comment by BorkBorkGoesTheCode** [comment]
I cannot claim originality here; the idea is used in Cataclysm: DDA corpse drop mechanics; a form of it is present in Freelancer; and it's common hunter's wisdom that using high-power weapons on small animals ruins the meat.

**Comment by endless-sky** [comment]
The advantage of the current system is that a small, weak ship mines at a slower rate than a ship with more powerful weapons. That is, you can start the game with a Sparrow and make a good living mining, but it's time consuming. If things were reversed and the weakest weapons produced the most resources, the only incentive to upgrade ships would be to get more cargo space.

It doesn't really make sense to me to have a different damage type, either, because I want all weapons to be able to destroy minable asteroids, and mining is a small enough part of the game that it doesn't make sense to have to specify a separate mining damage type for every weapon.

**Comment by egony** [comment]
Well in the case of having a different damage type is you can assign weapon a mine damage separately than the hull damage  Ex. the energy blaster has a hull damage of 6 but with the mine damage you can have it as like 12 or something like that. Also it doesn't add too much complexity to the code, just need to add a mine damage to each gun you want to break asteroids.

**Comment by LocalGod79** [comment]
@egony you have not addressed the concern that M.Z. raised about mining weapons: that it basically kills much of the player's incentive to get a better ship, explore the galaxy, make profits from all the available streams...

beyond this, M.Z. has expressed that he wants *all* weapons to be able to mine asteroids.
(let that sink in)

your proposal involves adding an extra line to every weapon (already/ever-to-be published) - seems like a lot of work for a (n intended) *very* minor feature of this game...

**Comment by DingusShingleton** [comment]
Ok, different idea. Give asteroids a large amount of shields but low hull, and set mining weapons to have piercing 100% but low damage. Regular weapons will be far less effective against asteroids, mining weapons are less effective against ships, and the player is rewarded for having multiple mining guns. It's a win win win. 

Though I think it would warrant some obfuscation of the actual mechanics from the player to really make sense ie, calling it mining damage or something in the stats and then explaining in the description how it works from a fluff perspective.

As an added bonus, mining weapons would be perfect for independent/fringe worlds outfitters.

**Comment by jafdy** [comment]
I am so sorry.

Tactical officer: Sir, the asteroid has raised it's shields!
Captain: Fire the mining laser!

**Comment by Elyssaen** [comment]
It's a pretty neat idea, Dingus, but doesn't it feel like a bit of a hack? : ) I'm not sure that mining's every going to be a big enough part of the game for it to be worth it... 'it' really being anything that involves the Outfitters having mining-specific weapons.

What about a new weapon modelled after EV Nova's Thunderhead Lance? A beam with a range of only 100-200, but extremely strong damage (esp. to hull). Give it a description describing how it was designed as a mining laser by Deep Sky, but has become popular amongst some pirates who prioritise immense firepower and don't mind damn near ramming their enemies.

**Comment by KiLEdEnNis** [comment]
> What about a new weapon modelled after EV Nova's Thunderhead Lance? A beam with a range of only 100-200, but extremely strong damage (esp. to hull).

was an idea for my project (I paused); a super strong close-range "arc weapon" (that only the small ships can have)

but I'm going off-topic, I'll be in my dungeon

**Comment by DingusShingleton** [comment]
Honestly i was about to go to sleep last night when i came up with that idea so w/e lol. And yes, it's a bit of a hack, but it achieves the desired results without requiring drastic changes to existing mechanics. All it needs is a little hiding-the-man-behind-the-curtain, and I think it would operate in a pretty flawless way. Is there a way to modify the stats of asteroids easily with a mod? Perhaps I'll try to make this into a mod and see how it feels if so.

**Comment by LocalGod79** [comment]
i like it when you think laterally @DingusShingleton , but this one seems pretty out there - disruption weapons would become overpowered mining tools, under your system, Hai Rail Guns would finally have a niche...i think you might run into a lot of little unintended consequences, though...

i'm pretty sure that mineable asteroids are coded as a part of the "minable.cpp" and "minable.h", and modding it through traditional methods is not possible...

i do like @Elyssaen's idea of a new weapon with extremely short range.  things to watch out for: especially on larger ships with spaced-apart hard points, short range will cause some interesting/disruptive convergence point calculations.  a weapon like this would pretty much be for small ships only, given that many asteroids are moving around quite quickly anyway...

**Comment by DingusShingleton** [comment]
Dang. Well leave it to you local to bring my lateral thinking back onto the rails lol. As usual there are numerous unintended consequences I didn't think of. But! I also think the thunder head lance style weapon is a great idea. And still perfect for those independent outfitters! Maybe there could even be a mini quest chain to mount them to a turret. Super short range turret sounds fun!

In my half-asleep stupor last night i also had an idea for a gun that shoots sticky IFF tags so that you could target asteroids with turrets/missiles and also identify what minerals it contains, to prioritize more valuable ones. Adds an upkeep aspect to mining (spending money on ammo, having to land to reload) but increases efficiency (and fun imo). So much for working with existing mechanics O.O

**Comment by tzargoth** [comment]
How about instead of blasting asteroids to bits, you should "board" them to mine them with some sort of drill (crew operated?)?  More/stronger drills makes mining faster.  Smaller ships move faster (usually) and can match velocity with more asteroids.  Obliterated asteroids using ship weapons may release a small amount of collectable ore, whereas mining yields a much higher amount.

**Comment by tzargoth** [comment]
Also, rather than having infinite, ore-filled asteroids everywhere, it would make sense to me that most asteroids in the more inhabited systems would already be mined, and provide much lower yields (mining does not destroy the asteroid).  There would still be unmined asteroids (amount to be determined), but going out to the rim and other uninhabited systems would have the most available resources.  A scanner (perhaps all existing types?) automatically indicates which asteroids have been mined.

**Comment by Amazinite** [comment]
>How about instead of blasting asteroids to bits, you should "board" them to mine them with some sort of drill

That was what the original iteration of asteroid mining was, but @endless-sky said that he'd rather have it be the current system.
