### ISSUE TITLE
Fedora RPM package

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#1891]
It would be great if less-technical Fedora users could install Endless Sky without having to build it from source.

**Comment by endless-sky** [comment]
I see some packages on rpmfind.net, but I have no idea if that's a legitimate site or not.

For now even the "stable" releases have usually turned out to have a bug or two in them, so I haven't been pushing too hard to get them into any official repositories (except for 0.8.11, which was the end of a long cycle of bug-fix releases, and which is in Debian). Maybe that will change as we get closer to a 1.0 release.

**Comment by Pointedstick** [comment]
Fedora's official repo should be good: https://admin.fedoraproject.org/pkgdb/

**Comment by Pointedstick** [comment]
I guess someone packaged it!

https://fedoramagazine.org/endless-sky-now-available-fedora/
