### ISSUE TITLE
awkward line in a new Wanderer mission

### ISSUE THREAD

**Issue by KiLEdEnNis** [endless-sky/endless-sky#1913]
Wanderers: Rek To Kor Efret

> 	Rek still remembers her way around a human ship, and gets settled in to one of your bunk rooms while you prepare for...

who says the player is using a human ship, or ever did in the Wanderer storyline? I'm flying a Wanderer ship

**Comment by Wrzlprnft** [comment]
unless you are a wanderer, the interior of your ship will be built to fit human needs.

**Comment by KiLEdEnNis** [comment]
it should be stated like that then

**Comment by Lineth** [comment]
It could be an (entirely reasonable) assumption that the player is flying a Bactrian.

**Comment by MessyMix** [comment]
@Lineth of course, but it's not an assumption that applies to all players, so it ruins immersion if the player isn't flying a Bac.

**Comment by KiLEdEnNis** [comment]
@Lineth more reasonable to fly a Derecho to be honest (I prefer the Dreadnought/Cruiser over the Bactrian anyway; they're symmetrical)

**Comment by Elyssaen** [comment]
...yeah, I really wouldn't assume every player's in a Bactrian, I _never_ fly one. Kestrel or Tempest for me, if I can't get over 700 speed I'm not interested.

Really, the easy answer is probably the best, and that's @Wrzlprnft's. Maybe if it read "a **human's** ship", it'd be a little clearer that the key distinction for Rek is the internal layout/configuration.

Otherwise I did just make a branch on my fork, TechConditions, that would let you give every human ship the attribute "tech: human", and so on, and it then turns the "tech" tags into conditions that missions can use. It could be used to branch this conversation, having it read "a human ship" only if you're flying a human ship.

But let's be honest: I'm only mentioning this because TechConditions is cool and useful (for multi-outfit checking and such), not because it's a good idea _here_. Seems like a lot of make-work here.

**Comment by KiLEdEnNis** [comment]
> Maybe if it read "a human's ship", it'd be a little clearer that the key distinction for Rek is the internal layout/configuration.

it should somehow state that the interior is changed for humans, because if for example a Hai flies the exact same ship as you, "a human's ship" wouldn't make sense, as a human can fly alien ships & aliens can fly human ships

**Comment by Elyssaen** [comment]
But even if a Hai flies the exact same ship as you, yours is a "human's ship" and theirs is a "Hai's ship", because one is possessed by a human and the other is possessed by a Hai.

**Comment by KiLEdEnNis** [comment]
yes, but they are the same ship, if someone else owns it it doesn't automatically change
then again, explaining that the inside of ships get modified based on species could solve it

**Comment by Elyssaen** [comment]
That'd be more explicit, certainly. Me, I'd be confused by "human ship" (I'm flying an Autumn Leaf, dammit!), but not by "human's ship" (I'd think it was just about who owned it, and from that I'd figure the internal configuration was probably changed). It'd be clearer still if it did outright say what you're suggesting... for me, I wouldn't think to do it: I'd feel it'd be unnecessary. But perhaps you're right.

**Comment by Bladewood** [comment]
demonyms are so confusing

**Comment by KiLEdEnNis** [comment]
I guess I'm the perfectionist then, since a human's ship can still be an alien ship & you can have a totally different ship since last time you saw him/her

**Comment by endless-sky** [comment]
Addressed in 12354a0.

**Comment by KiLEdEnNis** [comment]
that feels much better
