### ISSUE TITLE
[bug/mechanics/enhancement] Job requiring a Jump Drive jump sets payment to base

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#1918]
Screenshot of it on job board showing the jump route: http://prntscr.com/dlvo8t

Culprit missions (both look like this, almost exactly the same, one just has higher multiplier and a lot more cargo):

`	_source`
`		_ _government "Adamas"`
`	_destination`
`		_ _government "Adamas"`
`_on complete`
`	_ _payment 10 180`

My established theory is that when a job with a random payment requires a jump, it will set the payment automatically to the base.
Edit: Github's "code" tag doesn't work as well as I hoped... just putting the payment line and the source/destination.

**Comment by Elyssaen** [comment]
I was looking at the distance mapping a bit ago, and while it can deal with Jump Drives if the ship in question has them... the mission has no 'ship in question', so it goes off hyperlink routefinding only. (**DistanceMap.cpp**, lines 143-149.)  The relevant variable, `jumps `in **Mission.cpp**, is initialised to 0, and with no route found it's staying at 0.

Someone had a different problem with the same root cause on Google Groups:

https://groups.google.com/forum/#!category-topic/endless-sky/content-creation/MztQ1x49LIE

I guess this is because no missions yet in the game really depend on Jump Drives. If @endless-sky would like this implemented by someone who isn't busy on the core game, I'd love to help. I'll need some guidance on how we want to implement it though, because I don't want to do too much work that won't get used.

My first thought: content creators should be able to _tell_ a mission that it's a Jump Drive mission. I don't think it's appropriate to go off the capabilities of the ship you're currently, as it could create some awkward scenarios where you can trick the mission by coming under-equipped.

**Comment by toilethinges** [comment]
@Elyssaen thanks for that link and the idea.

> My first thought: content creators should be able to tell a mission that it's a Jump Drive mission. I don't think it's appropriate to go off the capabilities of the ship you're currently in, as it could create some awkward scenarios where you can trick the mission by coming under-equipped.

**Comment by endless-sky** [comment]
Job payments are based on how many hyperspace jumps it takes to get between systems. If you're creating a job that requires jump drive travel, you should just use a fixed payment instead.

**Comment by KiLEdEnNis** [comment]
I'd say jobs like these should have a jump drive variant
apart from jobs going beyond a wormhole, hyperdrive & jump drive are the only types of transport

**Comment by Wrzlprnft** [comment]
you forgot ringworlds

**Comment by KiLEdEnNis** [comment]
that's not added yet & that counts a bit like wormholes

**Comment by Elyssaen** [comment]
Well, I went and had a look anyway. 

1. Adding the functionality into **DistanceMap.cpp** is fairly straightforward in itself, asking for a boolean fourth argument to be passed to the 'defining a system only'-type instantiation (not the one used by NPC routefinding or the player's Map: first one in the file). It's then pretty clear Init has to set hasJump based on what's been passed if it wasn't passed a ship with a jump drive. Only arguable bit is I'd rename hasHyper and hasJump to doHyper and doJump at that point, since they don't necessarily reflect what a ship _has_ but what kind of jump the function is going to use.
2. DistanceMaps are created in four places. Two we can ignore: they're the NPC routefinding and player Map types. The third is through **LocationFilter.cpp** and specifically Distance() to check if a system is in range. The fourth is directly in **Mission.cpp**, doing a greedy algorithm to estimate the total mission jumps to get the variable cost. Or to put another way, third place = issue on Google Groups, fourth place = @toilethinges's issue.
3. The key question is if the mission characteristic, let's call it "jumping", is 'top-level' (like infiltrating) or is contained inside the filter specification. If the latter, a mission could have a random destination that uses jump-routing but random stopover destinations that don't. It's a pretty unusual scenario though, and requires writing "jumping" for each filter. My inclination is top-level is better: a mission is either expecting a Jump Drive or it isn't.
4. If "jumping" is defined top-level, the call in **Mission.cpp** is easy to get working. The LocationFilters then pose another question: the simplest way to do it involves the Mission::Load function passing "jumping" to each filter, and means "jumping" won't work for any filter defined _before_ it in order in the Data file. I _almost_ like this, as it means you could still do the 'unusual scenario' above by tweaking the order. But it would mean content creators would see it not work at all if they placed "jumping" last, and the order has never mattered before.
5. Otherwise... I do something a bit better to make it order-agnostic. Also a bit more impactful: it might have to involve a separate FinishLoading function, like how ships are loaded.
6. If "jumping" is defined by filter, not top-level, the LocationFilter stuff is trivial, but the greedy algorithm in **Mission.cpp** becomes troublesome. At that point we're in the messy situation that the Mission class has no idea if a mission requires a jump drive, and it's stopped using the LocationFilter objects that know. I don't fancy an elegant way of rewriting that, but I might just be biased in favour of 4-5.

Aside: @Wrzlprnft / @KiLEdEnNis, do I take it there's a hint somewhere of ringworld-to-ringworld teleportation? Where am I not reading that I could discover such wonders?!

**Comment by Amazinite** [comment]
> Aside: @Wrzlprnft / @KiLEdEnNis, do I take it there's a hint somewhere of ringworld-to-ringworld teleportation? Where am I not reading that I could discover such wonders?!

It was something that MZ mentioned a while back when he first teased the Coalition that he is currently adding, but as of right now there is no ringworld-to-ringworld teleportation in game.

**Comment by Elyssaen** [comment]
> It was something that MZ mentioned a while back when he first teased the Coalition that he is currently adding, but as of right now there is no ringworld-to-ringworld teleportation in game.

Ah, I think I never saw that specific post. MZ's updates lately have been kind of a Christmas surprise for me. Ringworld teleportation would be _really_ interesting, and explains a lot about the Quarg. Really hope it's implemented as generic teleportation, as that could allow some other interesting things...

To be a bit clearer on my code summary up there, here are the three options I can see:

**Option 1**
```
mission "Give Wanderers a Tour of Human Space"
job
jumping
source
   government "Wanderer"
destination
   government "Republic"
stopover
   attributes core factory textile urban rich
```

Here, jumping is top-level, but it _must_ appear before destination and stopover at least, as those filters need to know the mission will involve jumping. If it was below destination but before stopover, only stopover would use it.

**Option 2**
As Option 1, but order agnostic. Just... might need a FinishLoading function, and so might feel a bit over-engineered.

**Option 3**
```
mission "Give Wanderers a Tour of Human Space"
job
source
   government "Wanderer"
destination
   government "Republic"
   jumping
stopover
   attributes core factory textile urban rich
   jumping

```
jumping has to appear for each filter. I... don't like this, personally, and I don't like the mess it'd create in **Mission.cpp** when it tries to estimate the number of jumps, unless I just haven't found a tidy way to do that yet.

**Comment by Amazinite** [comment]
It would at least be helpful to have job distances track through wormholes that have visible links on the map. I'm currently working on making Hai jobs and some of the jobs involve either escorting or transporting cargo between the wormhole that connects Hai and Human space, so I have to have them all use set pays (currently set at 1 million each) which is kind of bland.

**Comment by jafdy** [comment]
Most trips between Hai space and Human space will likely be between Allhome and Prime as that is the (joint) shortest distance.

**Comment by Amazinite** [comment]
This is what I'm using for the destination and source so far.
```
source
	government "Hai"
	near "Heia Due" 0 2 # Either from Allhome or up to two systems from Allhome
destination
	attributes north # From what I can tell, at most 12 jumps. At least 8.
```

**Comment by Elyssaen** [comment]
Yeah, missions don't use wormholes. I'm not sure why: it's explicitly set not to, so there must have been some version at least initially. It'd be easy to change it but I'd like to have some idea of why it is the way it is.

**Comment by Amazinite** [comment]
I believe it's so that missions that you pick up in the north don't end up leading you to Hai space when they shouldn't.

**Comment by Elyssaen** [comment]
So, I'm still sitting on this. I have a feature branch in progress but need some input still on whether to proceed, and with which option (1-3). I can incorporate a parallel mission characteristic to allow wormhole travel easily enough.

@toilethinges, @Amazinite, can I have your views on the above options 1-3? Option 2 is probably best, right?

**Comment by Amazinite** [comment]
I like the way 1 looks, but I'm not sure what you mean by 2. If you think it's a better option though then go ahead with that.

**Comment by Elyssaen** [comment]
2 looks the same, but still works if you wrote "jumping" at the very _end_. 1 will only work if jumping is written before anything that needs it.

It's much easier to do it by 1, but I don't think the order you write mission characteristics has ever mattered before, so perhaps it's not a good idea to change that now.

**Comment by Amazinite** [comment]
> It's much easier to do it by 1, but I don't think the order you write mission characteristics has ever mattered before, so perhaps it's not a good idea to change that now.

Yeah, I'd agree.
