### ISSUE TITLE
Problem with Combat Rating

### ISSUE THREAD

**Issue by manitscold123** [endless-sky/endless-sky#1943]
So, my combat rating is 0 ( harmless ), and that's a real problem, b/c I can no longer dominate planets, or take bounty missions, and I know that it should be above 0 b/c I have dominated Earth, Mars, Luna, Prime, Betelgeuse, Valhalla, and Hephaestus. But it is at 0 and that's a real problem. Ripping apart Korath and Republic fleets does not help, even if I do disable tons of ships. 

I can't take some missions ( even if I don't need them ) and being harmless makes me feel bad.

Can fix pls.

**Comment by manitscold123** [comment]
So let me clear this up. My combat rating is 0. It should not be 0. I have finished every campaign ( Free World and Wanderer ) and I have even dominated many planets. ( my tribute is 100,000 ). But recently, my combat rating was set to 0, which I do not like, because I have not dominated most of Syndicate or the Deep.

Also, I took time to watch, and Kor Mereti is much more powerful that Kor Sestor.

And when will 0.9.5 come out?

**Comment by endless-sky** [comment]
Can you post your saved game?

**Comment by Elyssaen** [comment]
@manitscold123, could you attach your .txt save game file? You'll find it in one of these places:

Linux: ~/.local/share/endless-sky/saves/
Windows: C:\Users\yourusername\AppData\Roaming\endless-sky\saves\
Mac OS X: ~/Library/ApplicationSupport/endless-sky/saves/ 

Not sure what's happened but I'll take a look. If it turns out to be something that can't be explained/replicated, it will be something that can be fixed very quickly directly in your save game.

Kor Mereti _might_ outperform Kor Sestor a little, but if so I don't think it's by much.

**Comment by Pointedstick** [comment]
Perhaps the combat rating needs to be an unsigned long long. 😆

**Comment by endless-sky** [comment]
It'd take quite a bit of time to kill 2 billion people, I think. Or to kill 1 quadrillion credits worth of ships. Unless the OP was doing some save game editing or using plugins with absurd ship prices.

**Comment by KiLEdEnNis** [comment]
still, for the people I'd say switch to 64-bit, to please the ones that enjoy massacre

**Comment by manitscold123** [comment]
Uh... You might be right, b/c in the game, I'm using a Hurricane, which, by the way, looks badass, like an upgraded strong wind. And I also increased the size of fleets, like giant republic and free world fleets, and also have 24 antimatter cannons on the Hurricane, b/c the Hurricane has been modded, and ah... I probably killed 1,000,000,000,000,000 credits worth of ships. 

I am the God of Death. Worship my Drak Antimatter Cannons. :)

**Comment by Amazinite** [comment]
>24 antimatter cannons on the Hurricane

Saw something like that coming.

**Comment by Bladewood** [comment]
@manitscold123 what if I told you I had a thousand ships' worth of gridfire turrets?

**Comment by KiLEdEnNis** [comment]
if you cheat to the point where you have a Hurricane with 24 Antimatter Cannons, it's your own fault
it's like giving yourself 1 million ships and say the game crashes when you have a big fleet

**Comment by Bladewood** [comment]
@KiLEdEnNis It must be noted, though, that Michael has resolved issues like this before.
For example, we have a certain issue where he upped the limit of something (that I forgot) to... 2^64? (I don't know, I forgot that too.)
Or where he fixed an issue where a player's game kept crashing because of his use of nanobots in a fleet.

**Comment by Pointedstick** [comment]
For some reason games like this seem to attract genocidal megalomaniacs who just need to murder everyone in the universe for kicks and giggles, at least once. In a sense it's nice since these endeavors can be seen as stress tests for things you and me might not think do do ("what happens if I murder everyone in the universe? Does the game break?")

**Comment by Bladewood** [comment]
@Pointedstick what if multiverse?

**Comment by endless-sky** [comment]
Way back in the day, credits were overflowing at 2B, which was indeed too low. But to overflow combat rating you would need to kill 40 million of the largest Republic capital ships, which isn't going to happen unless you either modded the game, or left it running for a month while camping a busy Republic system.

**Comment by Bladewood** [comment]
*slow applaud*

**Comment by Elyssaen** [comment]
@endless-sky, I don't think the cap will work. Aren't you taking the minimum of your maximum and an undefined, overflowing signed int?  In practice the value will end up like this

`	"combat rating" -2147483648`

and the cap won't touch it.

**Comment by endless-sky** [comment]
Closing this because 0.9.5 is released now.
