### ISSUE TITLE
New fleet order, Interval

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1954]
Be able to set minimum and maximum distance a fleet ship tries to keep from the flagship and separately the farthest ship from it in the fleet.

**Comment by jafdy** [comment]
This sounds like a lot of micro.

**Comment by VonZorch** [comment]
The intent was for the ships to support each other instead of scattering out across the system in one case and to have damaged ships keep clear when boarding a ship that might self destruct.

**Comment by KiLEdEnNis** [comment]
maybe adding a 2nd "gather" command, and being able to set the max distance in the preferences tab
so ships don't wander off more than you want

**Comment by MessyMix** [comment]
I think adding a second "gather" will increase the number of key inputs, making the game non-controller-playable. However, I do support the idea of being able to set max and min distance in preferences, but probably not under "gather". The whole point of gather is to rally your fleet around your ship. There is never going to be a wandering ship on a "gather" command unless you are moving and your ships aren't fast enough to catch up. On the other hand, if the fleet was just hanging around, then maybe a max and min option would be in order. Sounds like a good idea.

On that note, why not make pressing "g" or whatever key is bound to "gather" un-gather the fleet? This is true of hold: pressing the key twice un-holds the fleet. But I think this would be useful too on "gather", undoing the command.

**Comment by KiLEdEnNis** [comment]
maybe just change that if you have no order active you CAN set a max distance

**Comment by MessyMix** [comment]
@KiLEdEnNis exactly my point, but a lot more well articulated xDD

I was also proposing that pressing "gather" when already "gathering" cancels the imperative.

**Comment by KiLEdEnNis** [comment]
if you were smart you'd just silently delete the fail, I was too lazy to read it anyway

**Comment by tehhowch** [comment]
Minimum/maximum distance between escorts is something that would need an AI touchup
As it is, with no hostiles present your escorts will (unless ordered otherwise) perform a "KeepStation" routine, in which they match your speed and heading as best they can, while not piling up on each other.
If there is a hostile present, they each use the MoveIndependent routine until you leave the system. MoveIndependent - as you might guess - means the ship assumes it has no partners or parent ship, and that it should make its own decisions about how to move. This is not a bad assumption, as there is no guarantee that its allies have similar weapons, shields, personality, etc as it does. It's also hard to say whether it makes sense that your escorts should worry about overlap when there is someone attacking them - e.g. if i turn to separate, i take weapons off my target. Is that ok? or is it better for me to just keep firing?

Certain NPC personalities have other behaviors beyond MoveEscort and MoveIndependent (Swarming and Mining, for example), so it is a matter of developing the AI logic for other coordinated movements, without making that coordinated movement so expensive that 5 game minutes in Mesukent takes much longer than 5 minutes of wall time. This is something that is wanted for improved fighter AI, almost certainly. But as it is a large mechanics change, it's something that needs doing very carefully.
