### ISSUE TITLE
New fleet order, retreat when damaged

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1955]
Be able to set a percentage of shield and/or hull damage that an escort ship will take before trying to disengage from battle, landing if possible.

**Comment by VonZorch** [comment]
This looks dead.

**Comment by tehhowch** [comment]
As it is, landing before the parent does does not result in recharging the shield or hull of the ship in question. I asked if it should in #2667 and have no response yet.
If it should, then we can develop a `retreating` (or otherwise named) personality that makes use of this behavior, including a preference to have the player's ships obey it, or choose to ignore it and always protect the player (unless ordered to land by the player, for example).

**Comment by VonZorch** [comment]
I wasn't thinking of having repairs done to the damaged ship until after the flagship landed, just having a heavily damaged ship getting away from danger.

**Comment by tehhowch** [comment]
Moving damaged ships out of danger easily is something that is also made possible by 2 of my open PRs regarding movement orders:
#2678 (open the map panel and right click the system map for a different system, selected escorts will go there)
#2679 (Right click on the radar display and send your selected escorts there)

I'd love to have those merge, and it's a natural extension of the land-to-accelerate-healing ability to have an "escort, go land" command, which would further help with moving heavily damaged ships.

**Comment by Amazinite** [comment]
It is currently a default behavior of your escorts to try to stay near your flagship while damaged. (This isn't necessarily retreating if your flagship is also in combat, but it is a potential way to get out of danger.) You are also now able to select escorts and tell them to move to specific locations in the system by right clicking on empty space, meaning you can manually command escorts to retreat.
