### ISSUE TITLE
Additional talk option, Planet

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1956]
An option between bribery and demanding tribute when trying to land on a hostile planet.  When you are denied landing you can point out you have a large powerful fleet in orbit and if you can't land peacefully you'll pound their stinking planet flat.

**Comment by DingusShingleton** [comment]
If you have such a massive fleet, paying a bribe shouldn't really mean much to you.

Though I have a feeling I know what your response will be, which is that you want to be able to do it anyway for roleplaying reasons.

**Comment by jafdy** [comment]
Or demanding tribute . . .

**Comment by DingusShingleton** [comment]
> between bribery and demanding tribute

**Comment by Amazinite** [comment]
What's the point of threatening planets with a large fleet to allow you to land when you can just demand tribute if you have such a large fleet and then land whenever you want?

**Comment by DingusShingleton** [comment]
Because rolling intimidate to get what you want isn't the same as murdering hundreds of innocent pilots

**Comment by KiLEdEnNis** [comment]
hey, only like 1-2 pilots a ship, the rest is regular crew :3

**Comment by endless-sky** [comment]
I generally don't add new game mechanics unless they make the game more interesting in some way, or open up new game play options that wouldn't be available otherwise. What you're suggesting is to add an option to not pay a bribe, but only in the case where you're so rich that a bribe wouldn't matter to you anyway. So, it doesn't seem like that would add much to the game.

**Comment by VonZorch** [comment]
Ok.
