### ISSUE TITLE
Crippled Ships

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#1959]
Since the beginning of recorded history, navies have considered destroying a crippled ship without first taking off survivors an atrocity.  Ship Captains who have done so to enemy vessels have been executed by their own governments.  Pirates have an economic reason for refraining from such practices, you can't loot an expanding cloud of metal vapor and fragments.
Given this there should be an option to call for surrender.  Military crews when faced with the option of being in a PoW camp out of the war or dead out of the war would surely choose surrender.  similarly pirate crews, which I gather from in game, are virtually slaves and could hope for a fair trial and clemency.  Of course the pirate Captain, after a fair trial, will get the bum's rush out the nearest airlock.

**Comment by Bladewood** [comment]
Duplicate.

> Military crews when faced with the option of being in a PoW camp out of the war or dead out of the war would surely choose surrender.

...I'm pretty sure surrendering is considered dishonorable in quite a few nations.

**Comment by endless-sky** [comment]
Pirates already refrain from destroying any ship they haven't plundered. But as @Bladewood said, the real issue is that if the Navy, etc. were leaving lots of disabled ships scattered about, it would be way too easy for the player to go around plundering or capturing those ships without doing any actual fighting. Game play and balance always take precedence over realism.

**Comment by Pointedstick** [comment]
Perhaps boarding and plundering could itself be made a Very Not Acceptable Thing in civilized society, and only barely tolerated when the target is a pirate ship (i.e. still a reputation drain, just not a large one).

**Comment by Bladewood** [comment]
The pirate faction was added so that players could plunder and capture ships without having to deal with law enforcement and stuff.

**Comment by Wrzlprnft** [comment]
i saw on the project around the topic of mining that ships breaking into parts is on the roadmap. maybe it can be used to regulate plundering.

**Comment by DingusShingleton** [comment]
I came up with an (imo) elegant way to balance plundering, just needs someone willing to take a crack at coding it. #1650

**Comment by VonZorch** [comment]
The Navy wouldn't be leaving derelicts around, they would be putting prize crews on and taking them to port.  Part of this is the annoying habit the Republic Navy has of coming up while I'm lining up to board and literally shooting the ship out from under me after a battle they haven't participated in.

**Comment by jafdy** [comment]
The navy capturing ships and "arresting" the crew would feel better than the current option and have a some effect.

**Comment by KiLEdEnNis** [comment]
what MZ said; just stay in Free Worlds space, they disable ships (intended towards the Republic)

**Comment by EndrosG** [comment]
May be the escape pod concept will provide a lore-solution to the original topic?
The Navy will still destroy those ships before the user can capture them, but when hull reaches zero, the crew escapes via escape pods.

**Comment by MessyMix** [comment]
I like the idea of the Navy capping their ships and then putting in prize crews to pilot it back to port.

**Comment by KiLEdEnNis** [comment]
energy chains on the pirate ship, dragging it back to port lol

**Comment by Tadrix** [comment]
Tractor beams at last?

About OP:
> Since the beginning of recorded history, navies have considered destroying a crippled ship without first taking off survivors an atrocity.

Submarines? They torpedo ships and don't take any survivors. Pretty sure that's their normal MO.

Pirate crews can't hope for clemency. They still caused many deaths (after pirate ship is done looting you, it will blow you up; also, overkill), remember Nuremberg trials. What we know from _escape from Smuggler's Den_ missions, some of the crew even actively helped to enforce pirate captain's will on these ships (most likely, in return counting as his lieutenants and being next candidates for boarded ships), so no clemency for them also. _And_, no pirate who survived to become a captain would allow their crew to even think that they have any chances to be spared; he needs them motivated to fight, and he controls all communications to be sure no one does anything behind his back. It's just a common sense for someone as paranoid as they have to be.

That being said, I totally support the idea that Navy (and perhaps militia too) should board pirate ships instead of destroying them and polluting their planet's orbit with debris (and perhaps selling these used ships at a discount to help fund their operations — after removing everything illegal), or at least tow them to the nearest planet or Navy outpost, if tractor beams get implemented.

**Comment by Pointedstick** [comment]
@Tadrix: it's the same logic used for self-defense situations: It's okay to shoot someone (possibly killing them) in a self-defense situation, but if they're no longer attacking you, it's not okay to finish them off/shoot them in the back/execute them/etc.

**Comment by VonZorch** [comment]
@Tadrix About submarines, yes that's their current MO.  The reason is that back in WWII a German submarine torpedoed a British liner then hove to to assist with taking off survivors, then took the lifeboats in tow to the nearest neutral port while also carrying some on deck.  During this trip it was attacked by an RAF bomber, after that the Kriegsmarine ordered that no survivors were to be rescued.
And no need for tractor beams, every warship should have extra crew for taking prizes and to offset deaths in combat as well as watch reliefs.

Or is the Republic Navy, despite what is said about their strict honor, supposed to be a pack of bloodthirsty murders no better than the pirates they seem to have little interest in fighting?
