### ISSUE TITLE
Raise Quarg ships' base hull price to 100M credits

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#1982]
This would bring them up to just below their original price (that is, with the antimatter cores) of 223.9M. (It would actually be 218M in this case.) This would make more sense when comparing them to ships like [this decked-out Heliarch Punisher](http://pastebin.com/xXfgCg5Q), which is slightly more valuable, at 220.63M (and also a bit more likely to win in a duel against a Quarg ship, simple calculations have shown).

**Comment by Elyssaen** [comment]
Quarg ships are _definitely_ too cheap right now, with a hull cost well less than a Summer Leaf, and I hope that's addressed as part of what I expect is a larger Quarg rebalance that's coming. I just get the impression that there wasn't really a good sense of what Quarg level should _look like_ when the Quarg were first introduced.

I don't think +100 M is necessarily going to end up being the way to go, as much as you're on point about the Antimatter Core. It's just... going to be part of a much bigger job, I imagine.

**Comment by Bladewood** [comment]
Probably.

**Comment by Lineth** [comment]
Speaking of Antimatter cores, will they be re-implemented with the Quarg overhaul and re-balance? Or will there be more of the integrated hull stats? I'll admit I prefer the former.

**Comment by KiLEdEnNis** [comment]
if the Antimatter Core gets re-added, a player can have 4800 energy generation, only 1200 heat, and that for only 80 outfit space
it's straight unbalanced by far; basically x3 generation of a blue sun reactor, half the heat and half as big

**Comment by Amazinite** [comment]
>Unplunderable

**Comment by KiLEdEnNis** [comment]
apparently people can capture world ships with a chance of 0,0001%
if anyone gets 1 they can farm those cores

**Comment by jafdy** [comment]
If you get a world ship you can farm more or less anything.

**Comment by Amazinite** [comment]
Well if you capture a World-Ship, I would think that you deserve to get Antimatter Cores.

**Comment by Elyssaen** [comment]
You can get up to a 10% chance of capturing a minimum crew Skylark, which'd probably be the easiest way to get those Antimatter Cores.

My [Trin](https://groups.google.com/forum/#!category-topic/endless-sky/iO4Dc1h45xc) (test version expected to be on GitHub in a week) have reactors that are Quarg-level and obtainable, ranging from the tiny Strangelet Cell to the enormous Strangelet Core. They're balanced because:

1. They can only normally be installed on Trin ships because they require `strangelet compatibility` that's found on Trin ships;
2. The only source of `strangelet compatibility` in an outfit is the Strangelet Adapter, obtainable as a mission reward, which takes up space and reduces the energy generation to the point that 'adapted' Strangelet reactors are only Korath/Wanderer level. (It actually uses [operational energy](https://github.com/endless-sky/endless-sky/pull/1896) instead of reducing energy generation, as otherwise you couldn't install Adapters without reactors and vice versa.)

The Quarg could work a similar way: their Antimatter Cores could require `antimatter containment` only found on Quarg ships, but perhaps the Heliarch would be interested in developing an antimatter containment outfit you could use.

**Comment by Bladewood** [comment]
Oh, also, we'll have to raise the price of the Arfecta and/or its outfits in this case~
