### ISSUE TITLE
Story line, where is it???

### ISSUE THREAD

**Issue by alugarius** [endless-sky/endless-sky#1994]
i love the game but i dont know what the storyline is, i always getting lost, trying to get every planets Spaceport and its hard to remember where i was with thousands of systems with one and more planets.
Missions of the storyline sudden ends, i end up with earning money and search the storyline 
(storylines ?).
Could we make this part better? I heard there is some kind of device to teleport between systems and i saw ships teleport in a purple cloud....

well .... i am a new, very lost player.
Please help. I want to know how big the universe in endless sky is.

**Comment by jafdy** [comment]
This is really not the place. GitHub is the development center for the game and we don't do the normal sort of pointers. I would advise you to try the Steam forums or the Google groups.
This sort of thing is being worked on but it will take time.

**Comment by alugarius** [comment]
I tried, the forums arnt helpful

**Comment by Amazinite** [comment]
Github is for feature requests and bug reports. If you're wanting to ask a question, you should do so over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky), or see if the answer is on the [wiki.](https://github.com/endless-sky/endless-sky/wiki)

**Comment by alugarius** [comment]
Doesnt that count as testing?

"Play-test the missions to find any confusing or broken parts."
I am very confused right now.

**Comment by KiLEdEnNis** [comment]
if you read all missions properly it's not confusing (there is a part where you're temporarily left alone twice)

**Comment by DingusShingleton** [comment]
It is pretty well known that a lost story arc is hard to rediscover... there has been talk of a pilot's log that would save the conversations and mission details. But like jafdy said, that takes time. In the meantime, this issue doesn't offer anything new or constructive. 

When I first played through the story there were a couple times where I lost my head of steam and needed a reminder. Those times I simply went to the mission files and read through until I found the spot I left off at. It's not the best method but for now it works. 

https://github.com/endless-sky/endless-sky/blob/3ffd6468201873b5ad669f2e89413f7f6086515c/data/free%20worlds%20intro.txt

**Comment by Elyssaen** [comment]
The main storyline is the Free Worlds campaign. You'll pick it up fairly easily at any Free Worlds spaceport. If you've started it but lost where you are, and want help, I can take a look at your save file (attach the .txt save file in a reply) and give you pointers. @DingusShingleton is otherwise right.

If you want a hint for some things to try exploring otherwise, click below:

<details><summary>hints</summary>
Try exploring the north of human space, particularly uninhabited dead ends.
And hang out in the centre-east of human Syndicate space: Sheratan and Polaris. Something will show up there which will present opportunities to massively open up the world.
</details>

**Comment by alugarius** [comment]
@Elyssaen @jafdy 
I already created an topic there, but noone replys.

**Comment by Elyssaen** [comment]
@alugarius, let's you and I pick up there then. I'm writing a post back to you now, but mostly just to point to my response here. So feel free to respond to me there right now. : )

**Comment by alugarius** [comment]
Thank you, if you reply i will close this one ok?

**Comment by Bladewood** [comment]
@Elyssaen off-topic, but could you teach me how to make something like that "hints" section in your post?

**Comment by Elyssaen** [comment]
@Bladewood, some basic HTML tags are supported. It's like this, spaces removed:

<details><summary>hints</summary>
first line<br />
second line
</details><br />

< details >< summary >hints</ summary >
first line< br / >
second line
< /details >< br / >

Just < br > instead of  < br / > is also fine.
