### ISSUE TITLE
No second chance after failing a mission in a main quest

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#20]
I've been playing around in the Free Worlds and doing the first missions, but then I failed the second mission where a bunch of freighters have to be escorted to a distant world, because one freighter was shot down by pirates just before I landed on a planet (and thus saved the game with the mission failed).

I was hoping the Free Worlds guys would propose me to retry this mission after a while, but it looks like I'm out of the Free Worlds quests due to this failure.

It would be nice if the mission was proposed again after a little while, or at least if this very mission could be made slightly easier by allowing losing one freighter (the reward could then drop substantially if it's not too hard to implement).

**Comment by akien-mga** [comment]
As a workaround I guess I can probably edit my save file and remove ```"FW Escort 2: offered"``` so that it's proposed again.

**Comment by endless-sky** [comment]
I'll add a second chance mission for this one, but it'll involve you receiving a very stern lecture about how letting people die when you had promised to protect them is a very serious failure.

In general, the player ought to save a snapshot before taking on a risky mission. Would it make sense for some missions to cause a snapshot to be auto-saved when they are accepted? Rather than auto-generating many different snapshots, I could add a special snapshot called "autosave" that is updated at points where it is certain that you have not failed a main story line mission.

**Comment by akien-mga** [comment]
I guess an autosave snapshot after having accepting a main story line mission would be very useful, and probably sufficient; from a player's point of view, it makes sense after failing a critical mission that you can't continue the story line – but then being able to load a snapshot to try again would be very appreciated :)

**Comment by endless-sky** [comment]
I've added a second chance mission (2f4d4be) and support for an "autosave" mission parameter (31732e1). Only missions in the main plot line (plus the intro escort missions) will autosave, so that the game can ensure that an autosave is only created when the game is in a state that would be "safe" to revert to.

**Comment by endless-sky** [comment]
Also, the "second chance" mission won't trigger for your pilot unless you add `"fw intro escort failed"` to your player's list of conditions. Another option, as you suggested, is to just remove the "offered" condition for that mission so that it will be offered again.

**Comment by endless-sky** [comment]
The second chance mission, plus the new autosave feature, should be enough to address this issue.
