### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by bamboowind** [endless-sky/endless-sky#201]
Hey, I can help on translating to Chinese.

**Comment by endless-sky** [comment]
I'll need to add support for non-ASCII text, first. But I can contact you once that support is added.

**Comment by bamboowind** [comment]
great, thanks

**Comment by angstsmurf** [comment]
I would just like to point out that unlike Escape Velocity and its sequels, this game won't let me use my real name for my starship captain.

**Comment by jafdy** [comment]
New issue. If your real name contains non ASCII letters then you can't use it.

**Comment by Wrzlprnft** [comment]
It's actually not new. MZ talked about that in another ASCII issue i believe.

**Comment by angstsmurf** [comment]
Yeah, it is not a new issue or a regression for Endless Sky, and perhaps it should have been a separate issue rather than a comment on this one. But I expect the cause is the same as the reason why there are no translations: only ASCII support. I mostly wanted to point out that this can be annoying even if you prefer to play in English. I'm pretty used to not being able to use _Sjölund_ as a name in games, and it was a nice surprise that Escape Velocity allowed me to do that.

**Comment by alugarius** [comment]
German, 
Could help there.

i think ÄÖÜäöüß are ascii chars

**Comment by zwparchman** [comment]
They are not

https://en.wikipedia.org/wiki/ASCII

**Comment by alugarius** [comment]
its not 7-bit ?

**Comment by zwparchman** [comment]
ASCII is 7 bit. If you look at the link I provided the only "letter like" characters are "A to Z" and "a to z". No characters with accent marks are included. What you may be thinking of are the extra characters that can come out when the top bit is set in some encodings. These are not ASCII characters.

**Comment by SeaLiteral** [comment]
I could translate the text into Danish, although I don't know how long that would take me. I see there's also an issue #558 and even a translatable fork. However, I also notice it says setting one language and loading a save from a different language might cause some text to show in the wrong language. I guess I'll try and see if I can get a Danish translation working in that.

**Comment by Amazinite** [comment]
Moved tracking of this issue to #558.
