### ISSUE TITLE
Extend depreciation time

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2034]
Rather unsurprisingly, depreciation hasn't been the most popular among the Steamies. Suggested increasing the time it takes for a brand new ship or outfit to fully depreciate as to make it less punishing when you want to try and experiment with new ships (maybe no depreciation for the first month too), as well as shifting depreciation from being a straight up economy nerf to something that more only effects capturing and plundering.

I feel like this would fix the main issue that some are having that it changes the once experimental/sandbox nature of being able to buy a new ship or outfit, fly it around for a bit to test it, and sell it back for full value if you don't like it.

**Comment by Lineth** [comment]
I support this.

**Comment by DingusShingleton** [comment]
Yeah I think a simple grace period would be the simplest and most effective way. Make it a few days, or even a week, but I think that would nip 95% of those complaints in the bud

**Comment by KiLEdEnNis** [comment]
what if every 10 days items lose a portion of their value? would also fix it, but is more rough

**Comment by zwparchman** [comment]
That feels rather arbitrary. Maybe depreciation should be tied directly to hull damage taken. Something like:

day 1: take 5% hull damage, your ship is now worth 95% of base cost.  
day 4: take 10% hull damage, your ship is now worth 85% of base cost. 

This would allow players that are peaceful to slowly climb the later into better ships without getting punished by depreciation  too hard. while still making combat oriented actions wear the ship out.

Maybe even give shield damage a smaller factor in depreciation so that a combat ship can never come out unscathed.

**Comment by Amazinite** [comment]
Well even when you aren't a combat oriented player, you still occasionally take hull damage. And how would that even make sense to tie depreciation to hull damage when hull damage can be repaired but depreciation can't?

**Comment by zwparchman** [comment]
You have the right idea though. Hull damage will happen to almost every ship so they will all depreciate, but combat ships are likely to take damage more often and thus depreciate faster. As to the hull damage remark, in real life cars lose value from damage, even if it is repaired. 

What does bothers me about the current system is how rough it makes trading. Trading makes far less per day than capturing ships until you have a large trading fleet. I don't have numbers to back it up, but capturing and trading seem to have comparable earnings for the player per real-world minute, but spending minutes in a system for a payday versus running a few trade routes cost vastly different amounts of credits, and I don't think they should.

Selling cargo ship to buy an upgrade is also discouraged by age based depreciation. By the time you have earned enough to cover the cost of your current ship and saved enough to buy a bigger one your original investment is nearly worthless. The only real advantage large cargo ships have over their small brothers is that they are tougher and are less likely to cause you to lose your investment. With the current system you have already lost most of it before the ship dies.

**Comment by Amazinite** [comment]
An important thing to note is that selling cargo leads to exponential gains. If you double your number of freighters then you double your profits, unlike capturing where only your flagship matters for making money.

**Comment by DingusShingleton** [comment]
Combine that with the fact that pirate attacks scale with cargo net worth, and those tougher freighters quickly become a necessity. 80 behemoths is a heckuva fighting force, even stock

**Comment by Isaacssv552** [comment]
I agree that the sandbox nature of being able to freely swap ships and outfits has been lost with depreciation. Maybe have ships depreciate when disabled? This would make it both a punishmnet for allowing escorts to be disabled and a mitigation on the value of looted outfits.

**Comment by geojak** [comment]
If depreciation ticked ~0,5% per day it would take somewhere around 4years to reach 25% for a new ship
Players would not be punished for trying different things out and it would probably also fix the issue with people not able to get loans anymore because of negative profits because of the too high depreciation.

The purpose of deprivation, to nerf looting, would be maintained.

It would be nice if looted/boarded ships/equipment would not always start out with full depreciation but rather with a random number (25%-100%) with the density focused on the lower values. 
This way players would have to make new choices: e.g. Do I loot that almost new gun or the really old core.

**Comment by onnikyla** [comment]
Another way to nerf depreciation would be to cap age based depreciation at around 50%, but keep the looting deprecion the same. This would help make ship upgrading less anoying, but still complete the task depreciation was added to do.

**Comment by endless-sky** [comment]
Once you acquire a ship, the game doesn't distinguish where it came from (plunder or not). So having plunder depreciate more fully than non-plunder would make things way too complicated.

I think the best approach will be to triple the depreciation timeline (from 360 days to around 1000 days). That will substantially cut down on your day-to-day depreciation losses, while still retaining the full balancing effect for plunder and capture.

**Comment by Tadrix** [comment]
Oh, seems that I missed this one and made new instead. I'll just close it and copy my suggestion here.

As it is now, trying to get wealthy would get a bit too tedious. My proposition would be this:
We assume that player looks after his fleet with good craftsmanship and care. Costs degrade over 10 years to 50% (in reality, amortization is counted for 5 years, but naval fleets tend to use their ships much longer). Spaceships aren't computers. However, others could ignore maintenance, so captured ship's worth could be randomly anywhere between 20% and 80% its initial cost (I imagine most pirates would be 20%–50%), and, if above 50%, it would degrade normally from this point onward (by 5%/year). It would be nice (and atmospheric) if the game gave an indication of ship's usage level just after capturing, for example:
65%–80%: looked after
35%–65%: average
20%–35%: ignored

Also, as for suggestions I read here, for hardcore gamers it could be a good idea to make value drop by 20% of remaining price (so, if the ship is at 80%, then it drops by 16%) for every time it is disabled, but not lower than 45%.

**Comment by Lineth** [comment]
Depreciation definitely seems to be a bit of an overnerf, as plundering outfits is pretty much pointless as mining is better in every way. The ships are fine, but I'd raise minimum depreciation to about 50% for outfits IMO. Maybe leave it at 25% for reactors or implement @Tadrix 's proposal.

**Comment by Tadrix** [comment]
Hi,
Since what I proposed earlier  could come across as not enough for M.Z. and some other hardcore community members, I'm proposing something much more moderate while still functional:

`double FULL_DEPRECIATION = 0.5;
int MAX_AGE = 730;`

This could alleviate these problems: #2223#issuecomment-284885545 #1848

**Comment by KiLEdEnNis** [comment]
if I could fix it I'd cap it at 33%, the intie start is bad now
but it's fine as is
