### ISSUE TITLE
Feature/Enhancement request: Divorce banking from depreciation

### ISSUE THREAD

**Issue by Waladil** [endless-sky/endless-sky#2049]
I'm sure a number of people here have seen the thread I started on depreciation breaking bank loans. For those who haven't, if a new ship's depreciation outruns a player's daily profit, they're considered to be losing net worth and will have small or no loans offered to them by the bank. This is odd behavior to me, since when it happened to me, I was making a healthy amount of money on a fresh save -- bought a Mule for 7 million credits (loan-free), made 3 million credits while the Mule's value dropped to 3.5 million credits, and wasn't offered any loans, despite clearly being in the black. Because my net worth went from 7.2 million (ish) to 6.5 million (ish). 

Anyway, I spoke to a real-life, American banker. Any arguments of "but realism" need to trump an actual banker.  He's not a gamer, so I posed the question to him in different terms:

Imagine there's a person of moderate income, with good credit and a net worth of a few tens of thousands (USD). And that person received a fantastically valuable gift that is worth much more than his regular income, like a Lamborghini. Because the car is depreciating faster than his regular income gains him wealth, he is now technically losing money. Would you give him a loan if he asked for it?

His response was that (unless the Lamborghini is used as collateral) the loan offer would be based on that person's regular, liquid income, not the value of the car. The max loan offered (collateral-free) would be one that brings his total debt payments (including any pre-existing loans or credit card debt) up to one-half of his regular income: If he was making $50,000 per year, no bank would loan him money that raised his annual payments over $25,000 per year.

Therefore, applying that real-world banker's opinion to the game, bank loans should track the player's income and be based on that, NOT depreciation. 

I propose that the game begin tracking the player's income rate -- primarily trade profit and mission payouts -- to determine how many credits that player makes per day, then only offer loans that would have a daily payment of 1/2 that average daily profit. If it didn't include sale (or purchase) of ships and outfits, it would remove depreciation from the bank loan system entirely. It would also make it harder for pirate/bounty hunter players to acquire loans from sale of plundered ships and outfits, which likely matches a real bank's hesitance to loan to a person engaged in highly dangerous and erratically-profitting work.

**Comment by comnom** [comment]
I think it's networth itself that has to be re-evaluated in a post-depreciation ES. Not only do we have the above where mortgage pre-qualification appears erratic to the player, but also testing the condition for mission availability. I'm not sure if anything does currently, but it could. Does the player have a brand new fleet worth 10 mil, or a much larger fleet worth 40 mil?

**Comment by Waladil** [comment]
I think having the net worth calculated the way it is is useful -- it still represents the amount of money you could muster right now if you sold all assets. It does that okay, we just need to acknowledge that it's less useful for other things than it was before.

**Comment by comnom** [comment]
> I think having the net worth calculated the way it is is useful -- it still represents the amount of money you could muster right now if you sold all assets. It does that okay, we just need to acknowledge that it's less useful for other things than it was before.

I get you, but as a mission condition it's now useless (ie, I want a super tough mission to spawn if the player's networth hits 100mil). And if it gets reworked somehow, then the absolute value of a ship could be considered in mortgages as well.

**Comment by Amazinite** [comment]
Well if that's what you're using the net worth condition for, then maybe a separate "fleet power" condition should exist that calculates the total undepreciated value of your fleet and uses that instead.

**Comment by comnom** [comment]
> Well if that's what you're using the net worth condition for, then maybe a separate "fleet power" condition should exist that calculates the total undepreciated value of your fleet and uses that instead.

Nothing wrong with that, but then why have a networth condition at all?

**Comment by Amazinite** [comment]
>Nothing wrong with that, but then why have a networth condition at all?

Because that's what the loans are still based off of...

**Comment by comnom** [comment]
They're based off of the networth in the code. Which is also what the condition is based of off. Why have the condition if it's useless?(ie theres plenty of things that aren't available as a testable condition, but that the code checks for, like history) Why add a condition when reworking networth for pre-qualification and as a condition kills two birds with one stone?

**Comment by Amazinite** [comment]
Well for one thing, you'd want to keep the `"net worth"` condition for the sake of reverse compatibility with other missions, and another is that `"net worth"` can be used differently than `"fleet power"`. Maybe the mod creator wants to check how much money the player could have in total in order to create a mission that they can only be given if they are rich, or if they need to spend money in the mission. `"fleet power"` on the other hand would better assess how powerful a player is in the moment, unlike something like `"combat rating"` which seems to be used to gauge a player's power, and `"net worth"` is more a measure of potential power than actual power in the moment.

**Comment by comnom** [comment]
@Amazinite I dig that, but then our buddy @Waladil still has his loans decreasing via depreciation. We could divorce them entirely as he suggests, or just alter networth. Just my two cents ;)

**Comment by Amazinite** [comment]
>but then our buddy @Waladil still has his loans decreasing via depreciation.

Yup, this is what betas are for. :)

**Comment by Waladil** [comment]
Even if it becomes unused in any game formula, as I mentioned the net worth is still worth tracking, because it tells the player how much money they can access without going into loans. It's also useful as a progress metric, to determine how far players are into the game when discussing strategies. 

By the way, I just ran a quick test to 100% confirm the loan value is based on losing money to depreciation. First, I modded the basic delivery job to pay 5 million credits per run. Then I started a new pilot, and ran those delivery runs until I had over 20 million credits after buying an Arrow (wanted the speed for convenient time-passing).

With those credits and the Arrow, I measured my loan-offering day by day by taking off and re-landing. Each day, I was offered about 4,000-5,000 less credits on the loan -- 6.595 million, 6.590m, 6.586m, et cetera. Then, I spent all those credits on Haulers and continued taking off and landing. Now, my offered loan dropped by 50,000 per day -- 6.338m, 6.288m. Re-sold the Haulers and the rate of loan offerage returned to 4,000 per day. As more time passed taking off and re-landing, the rate reduced over time as the Arrow got closer to its floor -- it was only going down about 3,000 per day after the Arrow was under 50% value.

**Comment by jafdy** [comment]
@Waladil That was a well argued OP.

I can get behind having "net worth" and "fleet power" as separate attributes with loans being based off trading income, but would you use mission payments as well. I think you have to because they can be the major source of income but they might be "too erratic" a source of income.

**Comment by Waladil** [comment]
I don't see a reason to ignore job payouts. Most of them are just high-pay trading anyway, with payouts calculated based on the distance between your starting and destination systems. I don't know the actual calculation but it's something like 300 credits per ton per jump, with extra multipliers if it's rush job or particularly large of a load. Chaining missions together provides very stable income, especially if paired with standard commodity trading.

**Comment by Isaacssv552** [comment]
The real issue is that depreciation has no effect on the profitability of the ship. Normally, the depreciation of key equipment would make sense to factor into loan offers because it will need to be replaced when the value hits 0. However, in game depreciation is limited and replacement will never be required. In effect, it merely increases the cost to upgrade your ship, not the everyday cost of operation.

**Comment by Architect-Luke** [comment]
Wow, I had to get a new account because I can't find my old information. That's a bad sign for how long I've been absent.

@isaacssv552 actually, that's all wrong. For one, assets don't depreciate to zero value. Second, you're completely making the rest of it up too.

For the purposes of credit, you are never, ever losing money due to depreciation.  Depreciation refers to sale value, not utility.  A $2 million CNC machine from 1988 is for sale on eBay right now for $6000.  It still functions exactly as it did when it was new. The problem is that technology has moved on, and it is no longer desirable at the industrial level that used to be.

 Income calculations cannot, and never should, including potential sale value of assets. If you want to include assets, then they must be calculated as collateral only.

 You could, however, argue that the company purchasing 1 million credits if equipment has lost money until they have earned an equivalent amount. This is not done in modern loans, because it is absurd. The lender will look at outgoing payments and incoming revenue and calculate a difference, potentially concluding that the borrower cannot support further loans.

 Honestly, there is another real problem: depreciation  has a floor that is way, way too low. The price value of used industrial equipment is 70 to 85% of the original purchase price, if working properly and not superseded by newer tech.  These advancements happen in ES at a rate of decades or centuries, meaning that equipment almost never becomes obsolete.

 Ships and outfits should never depreciate below 70%, or more realistically, 85% if the ship has not been in combat. I think captured ships should still be set at 20 or 25%, for game balance and to demonstrate the difficulty of selling a ship that has been completely disabled and filled with dead people.

**Comment by Architect-Luke** [comment]
How to delete a comment when you misunderstood what someone was saying?

**Comment by Architect-Luke** [comment]
Well, an absence of being able to correct a statement,  I will just say that Isaac appears to be discussing outfits, not ships or loans.  I misunderstood his post, and I actually agree with him on some parts.

**Comment by jafdy** [comment]
@Architect-Luke there is a cross in the corner. Right next to the edit button.

**Comment by Wrzlprnft** [comment]
except on mobile

**Comment by Ealb** [comment]
Thinking about what Architect-Luke is saying, rather than flooring dep at 70% or so for bought ships and 20-25% for captures, deprecation could be highest-damage-ever-taken with the current floor remaining in place. Disabled-and-captured ships would still be 25% due to how much abuse capturing would entail, but if you flew a freighter around for years w/o damage ever getting through its shield you could still get full price (or a bit less maybe)...

**Comment by jafdy** [comment]
And you would get to try stuff for a few days and then sell back for full price.

**Comment by Tadrix** [comment]
@Architect-Luke This could be related: #2100 I too was of opinion that 25% was too low, and that deprecation should occur during much longer time, about 10 years. Important bits:
> (in reality, amortization is counted for 5 years, but naval fleets tend to use their ships much longer)
and then sell them for scrap, of course.
> We assume that player looks after his fleet with good craftsmanship and care.
> However, others could ignore maintenance, so captured ship's worth could be randomly anywhere between 20% and 80% its initial cost, and, if above 50%, it would degrade normally from this point onward (by 5%/year). It would be nice (and atmospheric) if the game gave an indication of ship's usage level just after capturing, for example:
> 65%–80%: looked after
> 35%–65%: average
> 20%–35%: ignored
> A pirate ship should never have above 70%.
Of course, there are concerns about balance.

@Ealb Sounds like great idea. Would there be an option to refurbish a ship at a discount? (New Boston starport's description says that they sell refurbished ships, which are as good as brand new, and indeed they cost full price.)

**Comment by Ealb** [comment]
Thinking about what I said above (deprecation via max damage taken) a little more, I'd probably do something like deprecate new ships and installed outfits to 90% as soon as you took off, which would keep you from "renting ships for free" and also allow you to take superficial (i.e., up to 10%) damage w/o losing resale value (because that 10% was a sunk cost you immediately lost as seller's profit/restocking fee/refurbishing fee/whatever). It wouldn't be a perfect system (damage is not taken uniformly across a ship's structure, but all outfits and the hull would be deteriorated by it uniformly), but it would give a more organic feel to deprecation than the overly-aggressive current system.

**Comment by KiLEdEnNis** [comment]
that way you can't take off, test something and then sell whatever ya test because you'd lose money

**Comment by DingusShingleton** [comment]
Just take off, test it, and save scum like the rest of us

**Comment by KiLEdEnNis** [comment]
I do that, but not everyone does

**Comment by Tadrix** [comment]
@Ealb Wasn't this game supposed to be of sandbox-type, with possibility to experiment?

Seems to me that old players who finished and accomplished everything are pushing to make game harder, from which the beginners (who are starting from scratch) will suffer.

**Comment by Ealb** [comment]
The idea is to make gameplay more balanced. If that means eliminating some cheesy mechanics, then yes, it is "making it harder". But even so, what I'm suggesting isn't really doing that; indeed, it'd probably make it easier since you'd be able to sell back your ship for more than the current floor of 25% of what you paid most of the time - and if you use a given ship for any reasonable amount of time now, you'll be hitting that 25% floor and getting peanuts for trade-in.

**Comment by jafdy** [comment]
Easy->trading
Hard->capping
Trading is also a bit boring. I'm just saying that there is always an easier way.

**Comment by Startome** [comment]
I work for a commercial transport business, and have had exposure to the banking and loan side of things.
Where I don't know or can't get into the nitty gritty details, I do have associates that can. So if I can help at all please let me know.

Also, based on my post on steam and experience mentioned there. I suggest a new equation something like:
((assetvalue/2)-outstanding loans) + average100dayincome = Available Loan

The reason behind this:
When a commercial company requests a working capital (cash) loan from a bank (which is what the one I work for is doing right now), the bank requires double the collateral to be available based on the cash they offer. That covers their risk.
Hence the dividing the asset value (Ships and outfits) by 2, to reflect the actions of actual banks.

That being said, banks also will not offer you a loan unless they consider you D/I (Debt to Income) Ratio to be low enough. So If you have too many debts compared to the risk they want to take on giving you a loan, they simply won't offer you one.

Now some banks, if you can find a good one, will take your past company trends into account, though many of them are pretty much straight collateral and D/I. This is why I think the average 100 day income has a pretty solid place in this equation. It would allow someone to still get themselves too deep in loans, which obviously really happens, but also allow the banks some level of realism and "protection" from loss.

If the equation yields a negative result, then obviously the bank would consider you too high risk and not offer you a loan.

**Comment by endless-sky** [comment]
Prior to depreciation being added, it was *way* too easy to qualify for huge loans, which made it possible to buy a capital ship on credit after just capturing a handful of mid-range ships. A major goal in the balance of depreciation was to make the mid-game (the time when you've got a decent ship, but not the strongest one possible) last a bit longer, because previously it only took about half an hour to go from a Blackbird to a Bactrian.

So, the increased difficulty of getting loans is intentional.
