### ISSUE TITLE
Some way to disown fleet ships

### ISSUE THREAD

**Issue by kkuchta** [endless-sky/endless-sky#205]
I've had a few times where I've wanted to relinquish control of some ships in my fleet in order to declutter my in-flight fleet list:

1. Occasionally ships will get stuck in a system.  This seems to happen when I leave my fleet waaay behind (usually while doing missions).  When I return the the system, I can't seem to get them to jump away with me (despite telling them to gather around my flagship).  This could either be a bug, or a misunderstanding on my part about how fuel works with fleets.  Either way, it'd be nice to be able to just ditch those ships (if it's just a couple of cheap small ships or something).
2. Disabled ships on the other side of the galaxy that aren't worth going back to repair.
3. The two ships I accidentally left Over The Rainbow during the Pug missions and can't get back to now.

I seem to recall EV having a 'release ship' option somewhere– that'd be quite handy.

**Comment by LocalGod79** [comment]
make this a red 'destroy ship' button in the player info screen, next to park/unpark, please.

**Comment by endless-sky** [comment]
Added this option (finally) in commit 76b3471. It only works when you're landed on a planet, and bulk disowning (selecting ships in the fleet listing) isn't allowed, but for such a seldom-used and risky feature I think making it possible to disown ships one by one is good enough.

**Comment by interllect** [comment]
Really they need a "All ships warp to my current location" button.... save the hassle....

And maybe a "destroy disabled ship"  and "salvage dis able ship" option on the player info list....

Thats would make more sense... it's so frigging long waiting for your fleet to regroup back to you and it's annoying having to find where broken down ships are located...

**Comment by jafdy** [comment]
So you want a "teleport" button? Nope, that wouldn't be overpowered at all.

This has the same effect as destroying a ship. Salvaging has been suggested elsewhere.

The faster (and more agile) the ship is the faster it will get to you. The fleet moves at the speed of the slowest ship so if that's to slow make the ship faster.

You want to make the AI respond faster than once per frame. That won't happen. 
Have you tried pressing (F) yet?

**Comment by interllect** [comment]
@jafdy 

Q1: "So you want a "teleport" button? Nope, that wouldn't be overpowered at all."

A1: a teleport button only if the ship isn't following the flag ship anymore is what i meant to say (i.e. stuck ships)

Q2: "This has the same effect as destroying a ship. Salvaging has been suggested elsewhere."

A2: just to reiterate I said "make a destroy/salvage button for ships that are not in your current sector" ... i.e not ships right next to you 

Q3: "The faster (and more agile) the ship is the faster it will get to you. The fleet moves at the speed of the slowest ship so if that's to slow make the ship faster."

A3: ok well I currently have 40+ shield beetles (my flag ship being one of course), +20  ravens, +20 firebirds and a few other random smaller fast ships like hawks, furys and wasps all given the fastest engines they can possible be given...  as you should know the shield beetle is notoriously slow (no matter how you upgrade the engines)... but they are the strongest purchasable ships in the game (besides the Quarg ships obviously)... so you're in essence telling me to sell all my shield beetles for what exactly??? lightning beetles..... or maybe more hawks just for the speed???? lool no way those ships cost way too much money to just be sold like that for obsolete models.. you're basically telling me to change my  personal preference of play style (e.g relinquish my Slower Tank/Cargo based ships for fast light weight ships) in order to accommodate the poor gaming design.... wow ... that is kind of like saying: 

"When you are playing mario kart don't bother using anyone else but yoshi.... he is the fastest... therefore forget the rest of the characters and any personal preference to play style you may have..... everyone must choose yoshi in order to play and enjoy mario kart, its all about speed forget the other attributes, those other racers were just put in the game for fun, they were never intended to be used... so don't use them.... yoshi only ok?" ... come on dude :8ball:

Q4: "You want to make the AI respond faster than once per frame. That won't happen. 
Have you tried pressing (F) yet?"

A4: No I don't the AI respond faster than once per frame, I want my fleet's AI capable of instantly discerning when to go into hyperdrive/warp with me, not lagging behind me, then failing to appear in the new destination after a long journey and ultimately getting lost in deep space drifting around as targets for pirates.... it makes no sense (i literally sometimes need to warp back and forth from sector to sector (wasting time and valuable hyperdrive meter) in order for them to regroup, baring in mind the lost ships I am having the regroup with are much much faster ships than my flag ship... so what you said previously about "The fleet moving at the speed of the slowest ship" makes no sense... because as aforementioned my ship is the slowest... so they should be at least matching me for speed lol).... that is why i suggested  "maybe make a new outfitter's device that you can purchase to link the ships together like a "communications array", "hive mind system" or "ship network" to stop them from moving out of sync, making the fleet hyper-drive warp together instantly with no fall behind and help them form formations to fight in unison".... 

because right now they are all out of sync....  its like they are just fighting around me and not actually fighting/moving/defending/attacking..etc.. with me (that is even when pressing "F" lol) ... tbh "G" is about as close as it gets in this game to actually forming a cohesive formation.... and that sucks because they are not even facing in the same direction you want them to shoot in.... they have to slowly turn out of this huge bunched circle before they can actually shoot.... its totally impractical...... again I am spending more time fighting with managing my fleets formations and location... than fighting factions and pirates.... when i really shouldn't be... it ruins game-play

**Comment by jafdy** [comment]
Are we playing the same game?

If you want a slow fleet then don't be surprised when it's slow. Playstyle choice, it can come with disadvantages as well as advantages. 

Formations has also been asked for. The rest of that paragraph sounds like a bug. Do you hold (J) when you jump? If you do you can get your whole fleet jumping together.

**Comment by Wrzlprnft** [comment]
Um. I think you are talking about 2 different things here: 
A) more fleet control while fighting etc. Since this is somewhat on the roadmap as MZ stated elsewhere, i would not make that much a drama out of it, since, even if it takes a while MZs solutions are mostly worth the waiting time.
B) your ships not following you while you are waiting at the destination.
Well, ... They do follow you. They start preparing for jump once you start preparing for jump. They do not fight, and if they get stuck, they do try to refuel where possible or just slowly ramscoop their way to you. But they always follow you unless on hold position or parked.
I'd suggest you reinstall the game, since you seem to have some problem that should not be occuring, maybe corrupted files resulting in data loss and therefore the game "forgetting" about your ships.

Meanwhile, hold the Jump key until every ship in your fleet is ready to jump so you will always have all ships in one system, whivh seems to "just" reduce it to the missing fleet control rather than ships not following the programmed code.


Also, shield beetles are quite fast, relative to other tier 1 heavy warships.

**Comment by interllect** [comment]
holding (J) doesn't work for me.... sure it makes my entire fleet all point in the same direction initially..... but they do not jump at the same time and still end up getting stuck in the previous sector. Even if it is a fleet full of shield beetles (with the exact same specs as my flag ship btw) they lag behind and will not jump with me (even though they are animated as jumping with me upon releasing (J)... and when I do reach my destination only a few (like 10%-15% of the original fleet) appear, the rest are stuck in the previous sector) ... so there is no excuse.... 

furthermore my installation of endless sky is constantly updated by steam (ergo I'm tentatively sure I would have been forewarned by steam itself (if not my PC), If steam had of encountered any underlying error(s) and/or corrupted file(s) during the initial installation ... steam is petty thorough in that department after all... (tbh you can't even open a steam game without a steam performing a game update check and error check)... so I'm fairly certain it has nothing to do with my installation ....

**Comment by Wrzlprnft** [comment]
Since you are the only one, maybe it is a combination of steam, the game, and your machine, that is so very unique that noone encountered the error yet.

What version of the game are you running?

As well as do turn all your ships in the bottom left green?

What OS do you have?
Let's search for the actual issue and the look for "whom to blame"

**Comment by interllect** [comment]
Dell OptiPlex
Windows 7 Ultimate (SP1) 32bit
Intel Core2 Duo CPU E8400 @ 3.00GHz
8.00GB (RAM)
1x 1TB internal HDD
1x 1TB external HDD
DVD/CD ..yada yada yada

(basically one of these: https://www.amazon.com/Dell-OptiPlex-E8400-DVD-RW-WINDOWS/dp/B00NBRGQIE )

and yes all of the ships in my fleet turn towards the direction my flag ship is facing before I release (J), they all do that part just fine.... but not all of them jump with me, so when i end up in my flag ships final destination as stated before around 10%-15% will appear and the rest will stay in behind in the initial sector even with (G) turned on to group them.....

**Comment by Wrzlprnft** [comment]
Can you post your savefile(via google drive dropbox or whatever) please?

**Comment by interllect** [comment]
https://www.dropbox.com/s/0q3ff6flaw032co/adawg%20dawg.txt?dl=0

**Comment by Wrzlprnft** [comment]
As far as i can see almost all of your ships ran out of fuel on the way out of hai space, and since there are lots of uninhabited systems, they can't refuel there by landing, they are just stuck due to you not looking if they can make the whole distance. Install fuel pods and ramscoops, for further trips to hai space, or park ships you do not need there. In this case, you have to wait for the built in ramscooping ability to refuel them to make all the jumps, or refuel them manually.

 Further, Energy generarion might be a bit low on some of your ships, but it is there.

**Comment by interllect** [comment]
I see, well I guess I stand corrected (tbh I never really paid much notice to the "fuel" column until you mentioned it... because as you mentioned I only started getting this issue since I left Hai sector of space.... so I never once needed to consider it as ever being a future problem (mainly because I always docked off somewhere in the Human sector of space)...... 

but then that begs the question why isn't there a "refuel all ships in fleet" feature once you dock your flag ship on a planet with a shipyard?? (obviously at a price... I wouldn't expect a refueling of that magnitude to be free after all lol)... or does the "park all" feature also refuel ships stuck in sectors with no planets to dock on???.. because that could prove a major flaw in the game design.... your fleet runs out of fuel in a sector of space with no planets about... what do they do?

**Comment by Wrzlprnft** [comment]
They refuel slowly over time. I'd go to a system without a major sourcr of danger, and the let my computer just run while hanging in the orbit. Might just take 20 minutes, may take 2 hours. Since the game is not that resource intensive, i think you can do that for now, until we have a better solution.

I don't recall if they refuel each other, like they repair each other. Might be worth a try.

**Comment by LocalGod79** [comment]
@interllect all of the escorts that are in the same system as the flagship
will refuel when you land - for free.

@Wrzlprnft escorts will refuel each other as long as they're in the same
system as the flagship, have enough fuel to do so, there are no hostiles in
the system, and they have no orders to hold position/gather/focus.  it's a
pretty long list of conditions ahead of refueling/repairing escorts, but
they will do it...

**Comment by jafdy** [comment]
They can refuel each other but they need fuel in the first place. If none of them have a ramscoop equipped then they will all get to 100 fuel about the same time.

**Comment by Wrzlprnft** [comment]
He has a few ships with fuel. And it would stack up pretty quickly
