### ISSUE TITLE
NVIDIA's driver release (378.49) breaks basic OpenGL functions

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#2067]
http://steamcommunity.com/app/404410/discussions/1/143388511231569856/

i assume it is just right if i drop this information here.
My main source which brought me to what can cause those new crashes: https://starmadedock.net/threads/nvidia-driver-378-49-released-jan-24-2017-may-cause-crash-on-startup.28277/
i looked around a bit, but did not find anything more official from nvidia themselves.

**Comment by TJesionowski** [comment]
Ohhh, thought it was just me.

...On a totally unrelated note, this also affects minecraft.

**Comment by Pointedstick** [comment]
This would be NVIDIA's bug to fix, no? What's the game supposed to do--tell you to roll back your graphics driver?

**Comment by Wrzlprnft** [comment]
"NVIDIA's driver release (378.49) breaks basic OpenGL functions

Apparently, there are some problems with Nvidias driver update to 378.49 of 24th of January. if you experience crashes due to this, please revert to an older state until they have fixed the issue. We, as in the developing community around our main developer Michael Zahniser are unable to adress this issue ourselves."

that's what i posted. since i consider it somewhat official information, i linked it up here for people who are not on steam and want to know what's going on. it's not on endless sky to react.

**Comment by whismerhill** [comment]
hi @TJesionowski 
I am doubting the conclusion that it is nvidia 378.49 driver issue, due to my own testing (obviously limited to a single entity, e.g. myself. Even though I'm a helpdesk, therefore have some technical knowledge, it still only goes so far.)
if you wouldn't mind, I'd like to ask a few things to you. Still trying to diagnose the issue at hand: cause here are what I found out so far : 
-rolled back to 0.9.4 => no issue
-with 0.9.5 => TDR crashes with 3 different driver revisions

so if we could chat a bit, through any means of your choosing (example : friend me here : http://steamcommunity.com/id/whispershill/ )

**Comment by Wrzlprnft** [comment]
in the worstcase, it's a combination of both (0.9.5 as well as the driver update)

**Comment by whismerhill** [comment]
sorry I really really don't mean to be an annoyance but could you explain to me how you get to that conclusion given these facts  in chronological order: 
- I got the problem with 0.9.5 & 376.33 WHQL
- I got the problem with 0.9.5 & 378.49 WHQL
- I got the problem with 0.9.5 & 368.81 WHQL

**Comment by endless-sky** [comment]
I don't have access to an Nvidia machine, so I'm not sure how to go about testing this. There weren't any OpenGL-specific changes introduced in 0.9.5, so I'm a bit dubious about it being a new bug in 0.9.5.

**Comment by whismerhill** [comment]
If you want to use me for testing, go ahead.

**Comment by comnom** [comment]
> I don't have access to an Nvidia machine, so I'm not sure how to go about testing this. There weren't any OpenGL-specific changes introduced in 0.9.5, so I'm a bit dubious about it being a new bug in 0.9.5.

I can't add much as I'm on a radeon now, but I had a single TDR crash in .8.8, and then another in .8.9, for a grand total of 2 in ~30 hours on my 650TI. Made a bug report about it, though steam seems to have killed the thread somewhere, it was another user's thread. [This steam thread](https://steamcommunity.com/app/404410/discussions/1/458604254458077583/) has two users from .8.9 and one from .8.11 going by the dates.

I can also add that ES wasn't the only OpenGL application I had issues with at the time, leading me to point the finger at Nvidia, which is why I never pressed the issue.

**Comment by whismerhill** [comment]
@comnom 
thanks for your input, may I ask which other OpenGL apps you were having TDR issues with ?
currently ES is the only one for me, however most games use DirectX...

**Comment by whismerhill** [comment]
@endless-sky 
which OGL version is endless sky using ?
pardon my ignorance if that's a dumb question.

**Comment by comnom** [comment]
> may I ask which other OpenGL apps you were having TDR issues with ?

Looks like blender, epsxe, and pcsx2 going by my old logs.

> however most games use DirectX

Most _windows_ games do indeed use dx. Opengl see's heavy use in FOSS applications however.

**Comment by endless-sky** [comment]
@whismerhill, the game will run with anything above OpenGL 3.0, but it targets 3.3.

Are you able to compile the game and run it in a debugger? Without knowing what part of the code causes the TDR it'd be very hard to debug.

**Comment by whismerhill** [comment]
I have yet to try to compile endless sky yet, reading the build instructions for win7x64 right now.
I suppose I should get x86_64-posix-sjlj for mingw ?

**Comment by comnom** [comment]
> EDIT2: codeblocks window hangs upon exit after opening endless sky project

The version linked in the build instructions (13.12) hung constantly for me as well. Updated to 16.01 and it works fine.

**Comment by whismerhill** [comment]
Thanks comnom
since this is all new to me, I didn't think about verifying this.
there's also a codeblocks 16.01 with mingw included, didn't try it, but I wonder if it couldn't advantageously replace both.

so.... after all that:
Should I just run endless sky & wait for a crash ? I know that "debug" is selected in the build options. Is there any other step ? Also it seems to limit the amount of processing power given to endless sky when ran that way ?? (through codeblocks) which results in funny slow motion battles, sometimes (it's completely 100% fluid, just slowed down as if using bullet time.)

**Comment by CH-de** [comment]
I had the same problems with C::B and the libstdc++-6.dll. I figured out, that the MinGW download page tricked me to download a newer version instead of the a one (v4.8.5) the link points to. Since I use the linked one `x86_64-4.8.5-release-posix-seh-rt_v4-rev0.7z` the problems are gone.

![https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.8.5/threads-posix/seh/](https://cloud.githubusercontent.com/assets/25132101/22489572/755842d4-e818-11e6-8c47-4e112a206fa1.png)
To download just click on the file name under "Parent Folder".

**Comment by comnom** [comment]
> Should I just run endless sky & wait for a crash ? I know that "debug" is selected in the build options. Is there any other step ?

First make sure Settings -> Debugger -> GDB -> Executable Path is pointed at the debugger's executable. (gdb.exe in your mingw/bin). Then you have to run it with the debugger (the red play button next to the build target). When/if it crashes, you should get some output in the debugger console.

> Also it seems to limit the amount of processing power given to endless sky when ran that way

That's normal.

**Comment by whismerhill** [comment]
ok, it is working so I don't feel the need to reinstall that version of mingw. tell me if I'm wrong though.
the version I installed is up in this thread already.

Nevertheless I followed your procedure comnom & got my first "crash". I'm not 100% sure but it seems that stealing outfits from korath raiders for a long time do tend to increase the likelihood to get a crash (the way I do it, I have 20 bulk freighters that I bunch up with the guard command then send away from system center & hold that position. this allows me to then jettison my cargo inside those and the cargo is sure to be caught, therefore allowing me to stay for lenghty period of time).
so.... by "crash" I meant "TDR". And this time I got .... zero debug information:
the debugger log shows that it started, and that's all...
the endless sky process is sitting here doing nothing, (probably gonna kill it, don't see what else I could do)

As a sidenote, I have already had to kill the endless sky process before trying to debug it, though sometimes it would crash. gonna keep trying, maybe I'll get something workable. though if this trend continues I suppose nothing will be able to be done from this side  ????

**Comment by comnom** [comment]
@whismerhill The TDR should kill the application, which will give you the debug output. Pretty weird that the process still runs. 

From my old logs I got (ignore the missing description bs):
```
The description for Event ID 1 from source NVIDIA OpenGL Driver cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

A TDR has been detected.
The application must close.
```
And within two seconds:
```
Faulting application name: EndlessSky.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: nvoglv64.DLL, version: 10.18.13.5582, time stamp: 0x55dc6d58
Exception code: 0x40000015
Fault offset: 0x0000000000eaee56
Faulting process id: 0xcd8
Faulting application start time: 0x01d11fc065b15492
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Endless Sky\EndlessSky.exe
Faulting module path: C:\Windows\system32\nvoglv64.DLL
Report Id: c899d935-8bf2-11e5-aa78-6c626d4ca002
```

Breakpoints just pause execution so you can step through functions and fiddle with variables and the like. Not sure what's going on bud, but it's been almost ten years since I've done anything with compiled languages, so I'll have to leave the rest to someone more knowledgable.

**Comment by whismerhill** [comment]
Yeah I pretty much knew that, I just meant that the process was still alive but it wasn't kicking butt : e.g. it was actually not responding. still testing & waiting for another crash.
Other crashes before I tried this debug mode varied : sometimes the exe would be instantly terminated, sometimes it lingered around forever & ever until I killed it.

**Comment by comnom** [comment]
> Other crashes before I tried this debug mode varied : sometimes the exe would be instantly terminated, sometimes it lingered around forever & ever until I killed it.

That's the part I found weird, not that the debugger kept it around. Sorry should have clarified. From the little I understand, if the application doesn't handle the gpu reset, it should crash. Good luck regardless man.

**Comment by whismerhill** [comment]
Thanks comnom for all the help & support as well as all others who contributed so far.
Got another, still no application crash, just the TDR alone (& the gfx reset) It doesn't help much :(
Though one good thing came out of this (at least for me), it seems running an app in the debugger isolates it better from the rest of the system.

Found a hotfix driver 378.57 on nvidia forums (non-WHQL), gonna try it, nothing to lose at this point.
https://forums.geforce.com/default/topic/991248/geforce-drivers/announcing-geforce-hotfix-driver-378-57/
it says it fixes minecraft bug, and someone said this error was the same as the minecraft one so maybe it'll help.

**Comment by whismerhill** [comment]
well well well, if that isn't interesting xD
turns out there is a high probability that endless sky TDRs are unrelated to minecraft's TDRs ^^
driver hotfix 378.57 specifically designed to fix the minecraft bug do not change anything, I got two crashes with 378.57 in 20 minutes of play, didn't even have time to capture a single korath raider & go back to planet ! (got a bit unlucky with the spawning.)
Which is logical in the end, since it was apparently a java related issue !

**Comment by whismerhill** [comment]
a little update : 
-I have NOT given up completely on this
-I have however given up in trying to get a debug log, whenever endless sky is started through the "debug" red "play" arrow it always hangs & never crash on a TDR. Whenever endless sky is started through the green "play" arrow the process will terminate on a TDR.
-I tried endless sky 0.9.5 on another computer (my wife's) with my savegame. I let it battle/idle by itself for hours : http://steamcommunity.com/sharedfiles/filedetails/?id=857691832 . and got no TDR
it's also an nvidia card, though a GTX470 superclocked (so not the same model)

-I'm going through this :  https://forums.geforce.com/default/topic/389688/geforce-drivers/nvidia-statement-on-tdr-errors-display-driver-nvlddmkm-stopped-/
trying stuff as time allows. so far, no luck with realtek drivers updates.
