### ISSUE TITLE
Ability to set payment for killed NPC ships

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2092]
Example: Making an escort job where the payment is lower than normal, but for each mission NPC pirate killed that was trying to kill the escort you gain extra payment based off of the payment set on the NPC. 
```
npc
	personality nemesis staying
	system destination
	government Pirate
	bounty 5000 # An extra 5,000 credits gets paid to the player for killing this pirate
	fleet
		names "pirate"
		variant
			"Sparrow"
		variant
			"Wasp"
		variant
			"Berserker"
```

**Comment by warp-core** [comment]
Would this be addressed by allowing NPCs to have MissionActions that execute on various ShipEvents happening to that NPC? I think there's a separate issue for that?

**Comment by Hurleveur** [comment]
Well here it only happens when you kill it, meaning it is different from the objective of the NPC, allowing optional ones that are not required but still give you money.

That said I think its not that essential to have that distinction, as CC should be able to hack it to do what they want, like just despawn the ship if it isnt a true npc kill

**Comment by warp-core** [comment]
That's what I meant by 'various' events, not just the objective being met.
At minimum, I think we'd support an event on any of the possible completion conditions (even if that isn't the requirement for this NPC).

**Comment by warp-core** [comment]
#7113 (when it's done).
