### ISSUE TITLE
Feature Request: Get rid of drag parameter

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2098]
It just isn't needed. In space all that matters is acceleration, which is made up of inertia (mass), which for large ships is considerable, and engine power. So, even if large engine is more powerful, it wouldn't accelerate the larger ship as fast — and there's always the need to stop. To avoid player frustration, I'd recommend to still cap maximum speed (to something big, for example, to speed which is attained by thrusting continuously from the center of the system to farthest AI boundary), but there's no need for drag parameter, as the mass would do just fine.

Also, when the ship is moving erratically because of low crew, it wouldn't sporadically stop turning because of it if it's already turning. It would sporadically fail to stop to turn (because momentum).

**Comment by KiLEdEnNis** [comment]
mass isn't used for speed to make for example a Skein turn at an ok rate while barely moving, have a big freighter turn slow when it's still ok at speed etc.

and about the erratically part: it's meant to be a considerable disadvantage for boarding

**Comment by Tadrix** [comment]
Yes, an additional parameter which isn't really needed, because that's what mass is for. Also, do not confuse turning thrusters (ship rotates around its center mass, the effect should be there, but less pronounced) and main thrusters (ship's center mass is moved, the effect should be apparent).

Consider this situation in reality. You have similar engines on a heavy object and on a light object. To get from A to B, you need to accelerate, and then turn around and decelerate. While light object will be long there, the heavy one will barely start to move. You would need a more powerful engine for the heavy object to keep up.

At one time I read what Michael wrote about "drag" being to prevent bigger ships from being faster than small ships. If mass is factored in (as in thinking in space realities, not Earth realities) instead of drag, anything falls in place and is more intuitive for the players. Lighter ship — less inertia — engines more effective at moving that mass. Any more parameters are redundant.

**Comment by Amazinite** [comment]
I don't see why drag should be removed. As I recall, the only reason it's even called drag is because MZ couldn't think of any better name for it that would still convey that it's a max speed modifier without literally calling it "max speed modifier," which is pretty long compared to other attributes. Tying top speed to mass or some maximum speed limit just seems like changing something for little return. And as I understand it, "drag" ties in to a bunch of other speed related things, like hit force and firing force, so the removal of drag would probably be a difficult process that in the end wouldn't be worth it.

**Comment by Wrzlprnft** [comment]
i actually prefer a ship individual modifier rather than the hard coded speed limit the engine can and wants to handle. a speed limit is needed because computers.

**Comment by Tadrix** [comment]
As I said, IMHO speed limit isn't needed at all. A heavy ship with an engine of a fighter couldn't attain any considerable speed before it would need to "brake" using same engines. The distances between bodies in systems aren't really that big. As for AI's, they would calculate their max speed for themselves.

I feel that "drag" which never changes based on how heavy the ship in question is would be kinda artificial. Why not let elementary physics handle the problem? Besides, there's no need to tweak engine space of all ships, just the one of empty hull (if it isn't fine tuned already, which I'm pretty sure isn't the case).

I'm curious if Michael has something to say on this.

**Comment by jafdy** [comment]
Drag is simply the best name for an attribute that is used as a balancing factor. This is a case of gameplay over realism. If you don't like drag you can remove it in a plugin. [Here's one I made last time it came up.](https://drive.google.com/open?id=0B0mWx-Fhhhz7c21EYWZtbnpNUUk)

To use mass as the limiter then the mass of outfits/cargo would become meaning less to large ships or too important to small ships.

MZ leaves us to it for the most part as we have heard much of this before.

**Comment by Amazinite** [comment]
I feel like that if anything, this would remove a feature from the game. Right now, different ships having different drags adds more strategy to combat and to the ships you buy. Without drag, two ships with the same engine space would get the same max speed. Take the Corvette for example. The corvette is unique in being the fastest medium warship. But without a drag mechanic, most of the other medium warships would be faster because they have more engine space

**Comment by Tadrix** [comment]
Well, the corvette's hull could be lighter then the one of those other ships. Problem solved?

**Comment by Wrzlprnft** [comment]
Speed limit is needed, otherwise the game would break, even besides an Integer_Overflow.
Games are not continous, they are seperated in frames. people could dash through fights and skip over every damage instance. like, a nuke flying directly your way? no problem, in frame 1 you are directly in front of it, in the next frame you moved more pixels than the nuke has hitbox, and succesfully flied through a missle.

Using mass to regulate speed is a bit troubled, since mass also regulates heat.

**Comment by KiLEdEnNis** [comment]
> Yes, an additional parameter which isn't really needed, because that's what mass is for.

> mass isn't used for speed to make for example a Skein turn at an ok rate while barely moving, have a big freighter turn slow when it's still ok at speed etc.

did you even read what I said though?

the only thing I can see happening is if mass had a slight impact on drag (like drag calculates, gives max speed, then the results minus (mass / 100) or so)
but that's not even really necessary

**Comment by MessyMix** [comment]
I am fine with the engine the way it currently is; I don't see a reason to use mass/inertia as a determinant for the handling of a ship.

I think that the moving erratically suggestion would be great, albeit insignificant. I feel like it wouldn't be trouble to have a undercrewed ship retain player inputs sporadically instead of terminating the player inputs sporadically. e.g. player turns ship, crew attends to something else, so when the player wants to stop turning there is no-one there to stop it.

@KiLEdEnNis
> [moving erratically] is meant to be a considerable disadvantage while boarding

Well, I don't see how reversing the erratic movement to _oversteer_ instead of _understeer_ makes it less of a disadvantage. If I want to board a ship, but keep spinning too much, it would be equally disadvantageous.


>did you even read what I said though?

I know that comment isn't directed at me, but I think I'll weigh in for a bit. Your first post is incoherent, and I don't really understand what it means. I'm not sure the OP would understand either. What are you trying to say? Ship handling _isn't_ dependent on mass, or ship handling _shouldn't_ be dependent on mass? I can't tell what your argument is.

**Comment by SonEasterZombie** [comment]
@MessyMix Don't Worry, no one understands KiLEdEnNis.

to see why this wouldn't work balance-wise just look at the Archon Turrets or the Heliarch attractor. while it would be a little bit more realistic for the "drag" attribute to not exist, not only would it hurt balance and possibly harm game-play, but it would also, as Wrzlprnft said, break the game.

**Comment by KiLEdEnNis** [comment]
> Don't Worry, no one understands KiLEdEnNis.

no one gets me ( ͡°, _ʖ ͡°,)

**Comment by Tadrix** [comment]
Thanks for clarifying, OP indeed didn't wholly understand. ><

@SonEasterZombie I'm yet to encounter Archon Turrets of Heliarchs, because for now I'm just wandering around not doing missions for Free Worlds. So I would need another explanation.

> Well, I don't see how reversing the erratic movement to _oversteer_ instead of _understeer_ makes it less of a disadvantage. If I want to board a ship, but keep spinning too much, it would be equally disadvantageous.
Exactly. Game already treats erratical movement by sporadically shutting off engines (which means overshooting one's target and not stopping dead for a moment, which would be highly illogical, but possibly would penalize the player less, which obviously isn't what we're after), so it's inconsistent, when ships suddenly stops spinning for a moment, and then continues. The only explanation would be that, without input from pilot ship automatically tries to stabilize itself. I could argue that oversteering is even worse. As in, when ship stops spinning, we just need to wait. If it oversteers, then it turns the other way, than again, then again, then again… Ofc it could get too bad (unending cycles or realigning), so probably some small margin of "aligned good enough" would be necessary.

@Wrzlprnft Thanks on clarification on speed limits. I'm not wholly against them, they just shouldn't be so obvious. Especially if there's risk of player flying through something he's not supposed to. I'm just arguing that in space-themed game acceleration should play much larger role than speed. As in reality any engine is capable of attaining tremendous speeds, but often it isn't feasible to wait that long (months or longer).

**Comment by pjwerneck** [comment]
Sorry for replying on a closed issue, but I was also thinking about this. A realistic solution that wouldn't hurt gameplay is to replace drag with limited fuel/propellant, i.e., limited delta-v, as in reality. That would still impose a cap on maximum speed, but without drag in space and magical thrusters that require no propellant.

**Comment by MessyMix** [comment]
Sorry, I think that a delicate balance exists between realism and gameplay, and limited propellant is one that infringes way too much on gameplay. Yes, limited delta-V is a thing in real life, but if you came for such mechanics then perhaps Kerbal Space Program is your thing, but Endless Sky is not KSP. In a world 1000 years into the future where FTL is so prolific, I doubt delta-V will even be a problem now. The engines don't run on fuel; instead, they run on "power" generated by your reactors. I feel like a propellant element will introduce too many stray factors, and—while realistic—should not be implemented for ease of gameplay.

**Comment by pjwerneck** [comment]
@MessyMix Propellant is reaction mass thrown in the opposite direction of the one you want to move. Fuel -- or "power" -- is whatever is used to generate the energy to throw reaction mass in the opposite direction. You need both. Power alone won't get you anywhere, no matter how advanced your technology is, unless you're handwaving Newton's 3rd law.

I don't see how it would be detrimental to gameplay. It would simply impose a cap on velocity in a more realistic way, but there's no point in discussing if there's no interest in doing that.

**Comment by MessyMix** [comment]
@pjwerneck I am well-versed in the mechanics of spaceflight, but since Endless Sky does not currently have a mechanism to distinguish remass / propellant from fuel, I used the two terms interchangeably (in fact, chemical rockets today use fuel that is also propellant). I'll try to illustrate why it'll detract from overall game experience. We can surely have a discussion about it, because it is worth discussing. It's not like I'm the developer; it is simply my opinion that it will infringe on gameplay.

- Immersion breaking.
It's 1000 years into the future. We have FTL travel. Repulsor engines are used for gravity wells. I think it would be unbecoming of such a world to still require remass for engines.

- Annoying.
Yes, I won't be able to accelerate infinitely with limited propellant. But I won't be able to travel infinitely. What happens if I run out of propellant when I'm zooming away? There is a radius beyond which NPCs will not follow you. If you run out of remass, how are you going to get help, especially if you're travelling faster than other ships are? (They'll have to expend all their remass to get to you, and by then you'll both be stranded and no-one will have enough fuel).

- Needs severe balancing.
What engines will have what amount of propellant? How much is adequate? Will it be customizable? What if I customize the number of jumps I can make? In that case, will I get more remass to adequately navigate around more systems?

- Too complex.
If this were implemented—and it certainly _is_ a solution to the top-speed problem—it would require a lot of source code changes that aren't made easily. It's a solution alright, but it's clunky and cumbersome. I think that drag, while not particularly realistic, is a simpler and more straightforward solution.

I hope this answers some of what you're unclear about in my earlier post. I'm happy to keep discussing.

**Comment by endless-sky** [comment]
If you really want to, you can play around with ships with no drag and limited fuel in-game: just give the ship a "drag" value very close to zero, and only install afterburners in it instead of ordinary thrusters. What you'll find, though, is that it's incredibly annoying to pilot such a ship, particularly in combat (and, I already get enough complaints as it is from players who find navigating a ship that has inertia to be too difficult). This is a case where making the game fun trumps making the game realistic.

**Comment by Tadrix** [comment]
Interesting idea. I'll try.

@MessyMix There's a possibility to cap uninterrupted acceleration, something like power bar with non-instantaneous power generation just for engines. In-game explanation would be that part of reactor power is dedicated to engines and the other part to weapons to avoid systems interfering with each other. So it wouldn't be possible to accelerate infinitely, and it wouldn't be possible to get stranded — just wait for engine power to recharge and head back. Also, this should apply only to thrusters and not steering.
