### ISSUE TITLE
Ability to jettison cargo

### ISSUE THREAD

**Issue by naehc** [endless-sky/endless-sky#213]
One thing I currently miss (from the EV games) in Endless Sky is the ability to jettison generic cargo/outfits when in space; e.g. when I find myself just a few tons short of the necessary free space to loot a high value reactor. Not sure if this has already been considered, just thought I'd mention it.

**Comment by Pointedstick** [comment]
Oh yes, I've been in this situation too! Much better to toss those 130 tons of food so you can fit an Armageddon Core in the hold. :)

**Comment by endless-sky** [comment]
This is kind of the same as #29 - there probably would not be a reason to jettison cargo any time other than when you are boarding a ship, so adding support in the boarding panel for jettisoning cargo ought to be sufficient.

Eventually, I may redo the boarding panel so that it shows a list of your cargo and the other ship's cargo and outfits, and lets you transfer items back and forth freely (and transfer controlled amounts of fuel, too). I've been putting off doing that, though, because it would make the interface so much more complicated and possibly harder to understand and use.

**Comment by egilburg** [comment]
@endless-sky would this involve transferring outfits or just cargo?

Because if outfits, it would finally allow stealing the Korath World-Ships :)

**Comment by Phezzan** [comment]
As a tangential feature - I'd love the ability to buy outfits as cargo.  I tend to keep most of my fleet parked.

**Comment by endless-sky** [comment]
This is (finally) possible: 519c5cd. When you are viewing ship info in the info panel, and you are not landed, it now has a "Dump Cargo" button.You can select a particular commodity to dump, or click the button with no commodities selected to dump all regular commodities in the ship. It does not allow you to dump mission cargo or plundered outfits, although maybe I should add support for the latter.

Pressing the "INFO" key while in the boarding panel will bring up the ship info page for your flagship, allowing you to dump cargo if you want.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
