### ISSUE TITLE
Better bounty hunting payment?

### ISSUE THREAD

**Issue by ph2000bis** [endless-sky/endless-sky#2131]
By using the `on fail` and `npc save`, I could get the payment for bounty-hunting to happen whenever you land anywhere. The catch is, is there a way to display the dialogue when you kill the ship?

And is this a good change in the first place?

**Comment by Bladewood** [comment]
Display dialogue? [Yes.](https://github.com/endless-sky/endless-sky/blob/master/data/wanderers%20middle.txt#L1040) Place `dialogue "[insert text here]"` within (as in, below with an indent) an npc line.
Or at least it should.

**Comment by ph2000bis** [comment]
I tried it, payment happens on landing
From what I understood, the `dialogue` only happens when conditions are met.
The point is that conditions are failed, so that payment happens whatever planet you land on.

**Comment by jafdy** [comment]
@ph2000bis have a look at my hired mecs pull. That way I ran it there may also work for you.

**Comment by endless-sky** [comment]
The problem is that the "on fail" action is also triggered if you abort the mission.

I think the "right" solution would be a code change that allows missions to specify that they can complete on any planet once all other conditions are met. That would be really easy to do (adding about 6 new lines of code) but it's something I'll probably put off until 0.9.7 because 0.9.6 is focused on safe changes and bug fixes.

**Comment by toilethinges** [comment]
destination any?

**Comment by tehhowch** [comment]
Combining this "complete anywhere" mission behavior with the NPC behaviors in #2990 would be fantastic, especially if they can complete in flight (e.g. escort to planet job shows dialog as soon as the NPC lands on the target planet rather than when the player lands on a planet).

**Comment by Pointedstick** [comment]
> The problem is that the "on fail" action is also triggered if you abort the mission.

See https://github.com/endless-sky/endless-sky/issues/4018

**Comment by Amazinite** [comment]
Piggybacking off of this issue, perhaps instead of a simple and brute force "complete anywhere" mechanic, it could be expanded to instead have multiple valid destination planets at the same time. Using #4396 as an example, the Pug Arfecta mission could complete on any Wanderer planet instead of just a single planet and instead of on any planet (as it wouldn't make sense to get a message from the Wanderers if you jumped to human space).
