### ISSUE TITLE
Incorrect Capitalization

### ISSUE THREAD

**Issue by DrDankMLG** [endless-sky/endless-sky#2162]
The Lightning Bug's description doesn't capitalize 'Ion Cannon', instead saying 'ion cannon'.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/641756341f65b5a0d545109edfb18dfd5adfe2af
All of these were changes from upper-case words to lower-case words, and they were accepted by Michael, so I think "ion cannon" is correct.

**Comment by Amazinite** [comment]
It depends on if the name of the weapon is generic or specific. For example, particle cannon, blaster, or anti-missile turret are pretty generic, but then we have Meteor Missile, Sidewinder Missile, Hai Tracker Pod, LP036a Battery Pack, Chipmunk Plasma Thruster.

Ion cannon is one of those generic ones. It's a cannon that does ion damage. It's in the name. 
Those upper-case to lower-case changes I did were fixing generic names that should have been lower cased.

**Comment by MessyMix** [comment]
^^
Capitalization suggests a proper noun, i.e. the name of the weapon. Otherwise, a non-capitalized name indicates a standard noun, so a weapon or a weapon type. For example—and this is one that I fixed—a dreadnought is a real noun, so it needs no capitalization, but the name of the ship model, "Dreadnought," needs capitalization.
