### ISSUE TITLE
Make escorts refuel in the last available (and friendly) inhabited system

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2163]
Would be awesome if those escorts which are going to run out of fuel in uninhabited or hostile systems would try to refuel at the last possible place before it, if not already full. Or at least give the player option to command them to refuel now.

(Another thought, although perhaps warranting another issue, would be to put a tanker/resupply ship in the game with practically no cargo capacity but huuuge fuel hold. Differences between that and converted ship with fuel pods? Efficiency, appearance and AI behavior (also, good shields+hull, but crappy weapons capacity, some small self-defense turrets, but no guns — no missiles either). Namely, escorts are trying to help each other by boarding other escorts and giving them enough for another jump, and do it only when no hostiles are around. To resupply, other ships (interceptors, other small ships) would themselves dock and get a full tank, or at least half-full, if others are in need and fuel is running low. This fits nicely in the narrative of far expeditions and better ramscoops. But I guess such thing isn't something that would become a priority, so just spoke my mind.)

**Comment by Amazinite** [comment]
Currently, they actually will do this if they have 1 jump left and the next syst they are going into is uninhabited while the current is inhabited, but not beyond that.

**Comment by Rakete1111** [comment]
They will also refuel if there are no friendly planets in the next system.

**Comment by Amazinite** [comment]
Related to the second point, I would like to see the AI be smarter in how they ask for fuel and get it. The faster ship should always fly to the slower ship, not the requesting ship waiting for the offering ship.

**Comment by jafdy** [comment]
What counts as "faster"? What if one ship could turn faster and one could travel faster in a strait line.

**Comment by Tadrix** [comment]
@jafdy @Amazinite probably meant it as "which ship can faster make it to the other, performing all necessary turns in the process". And it's probably possible for the game to take this into account, seeing as it manager to calculate unparked fleets getting to the player. It's an awesome idea.

**Comment by tehhowch** [comment]
It's possible that a simple Ship::MaxVelocity comparison could be used for non-Player Flagship requestors. For example: If the hailed ship has twice the speed of the requestor, the requestor issues itself a MOVE_TO order for a point that is 1/3 of the way to to the other ship. No change in behavior of the hailed ship would be needed, as it sets a rendezvous target with the hailing ship rather than the position of the hailing ship at the time of the request.
This would be a simple quality of life improvement in AI-to-AI refueling operations, but note that this is the only time such a comparison would be used - the requestor can't move at all if it's disabled.

**Comment by tehhowch** [comment]
Between #2997 (consider more than just the next system) and #2861 (prefer faster helpers) I think this issue is resolved.

A while back I played around with getting the two ships to "agree" on a place to meet but couldn't get a solution I was happy with - from a code perspective it is much simpler and less error-prone to have one party simply stop moving.
