### ISSUE TITLE
webhook for discord server

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#2194]
hey MZ, you probably know we have this discord server, and it would be neat if a update alert was automatically pushed to our announcement channel. more information is in the e-mail i sent you a while back, but since i figured that that one month vacation is just a vacation from heavy tasks, i decided to bring this up.it's a rather lightweight thing.

**Comment by endless-sky** [comment]
My vacation hasn't quite started yet. I'm just trying to get some of the long-standing pulls that I put off (because 0.9.6 was a stable release) merged in, but I'm leaving for the airport in a few minutes and will be away from home for the next three weeks. So starting tomorrow, I *really* won't be on GitHub.

**Comment by Wrzlprnft** [comment]
... that's my timing as i know and love it!
have a good time!

**Comment by KiLEdEnNis** [comment]
we'll miss you ( ͡°, _ʖ ͡°,)

**Comment by endless-sky** [comment]
I'm not on Discord, but I've set up the webhook. Let me know if it doesn't seem to be working.

**Comment by endless-sky** [comment]
Can anyone confirm whether the webhook is working?

**Comment by tehhowch** [comment]
Yes, when releases are pushed, a message is sent out.
