### ISSUE TITLE
[Engine] Performence Issue ?

### ISSUE THREAD

**Issue by Nightshades1** [endless-sky/endless-sky#2196]
Hello everyone and the creator :P i have notice that this game got serious performence issue, i'm playing with 8GB, an old i7-2600k and an old gtx 580 but come on, why do i have FPS "spike" (drop) when my fleet of 8 Archon is firing, too much projectiles or something ?

By the way it's a great game and i believe you should ADD 2D Support, don't know if it's possible to create an entire ship using 2D Sprite, you know if i wanted to make a Giant plugin re-creating the whole Vell'Os storyline of EV Nova in your engine =P I have all sounds/graphics/Mission text/coord, off course everyone can do that but the time it would take holy crap.

Ps: Does this game got Hypergate as well ?

**Comment by Wrzlprnft** [comment]
well, first of, archons do have with a reason the “never disabled“ tag, and it might be just the amount of targets you're hitting.

all the games graphical assets are 2D sprites, check the wiki page here on github for how to create content ;)

not yet. but quarg ringworlds are handled as a hot candidate for such a functinality.

further, @endless-sky is on a one+- month vacation since today.

**Comment by Nightshades1** [comment]
Okay thanks for the info :+1:
