### ISSUE TITLE
When buying multiple ships and using the random name function it should work for all ships bought

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#2198]
When you buy say five ships with a random name it gives you <random name> 1, <random name> 2, etc instead of <random name one>, <random name 45>, <random name six>, etc.

Edit: This may not have been clear, so I shall say in better terms. If I buy multiple ships and use the random name function I get the same name multiple times. I would rather get multiple names for multiple ships, all different (if possbile. You can buy like 50k ships at once and idk how many combonations of names we have)

**Comment by KiLEdEnNis** [comment]
not sure if that can be fixed w/o having it that if ya buy 5 ships & name 1 the others get random names

**Comment by Bladewood** [comment]
That's exactly what he's asking for.

I can see his point, but if we want that, we can already just buy the ships separately, with randomized names.

**Comment by KiLEdEnNis** [comment]
but currently if you buy like 5 ships & give them a name, all of them get that name & a number, what if people want that instead

**Comment by jafdy** [comment]
For when you want to buy say 20 ships. That's 60 button presses to randomize it. I would like this.

**Comment by KiLEdEnNis** [comment]
I guess I can't really judge anyway, I never mass buy ships

**Comment by TJesionowski** [comment]
As someone who regularly mass buys ships, this would be really cool, and also a neat addition lorewise. (Adds some character to large fleets)

**Comment by Bladewood** [comment]
Lorewise, mass-purchase of ships doesn't make any sense at all.

**Comment by whismerhill** [comment]
@Bladewood 
I don't understand why the player couldn't order say ... 20 ships in lore ?

**Comment by Bladewood** [comment]
Hold on, let me pull up one of those ancient GitHub issues... Or maybe Steam threads...

**Comment by whismerhill** [comment]
nevermind then, thanks for trying  :)

**Comment by endless-sky** [comment]
I can't think of a good way for the player to make it clear whether they want to use the standard naming mechanics (add a number) using one random name that they selected, vs. using a different random name for each ship, without adding yet another button to the interface.

But, what would you all think of the idea of having random names get assigned if you leave the name field blank, rather than having it default to "<name>'s <ship model>"? That is:

  * If you leave the name blank, each ship gets a different random name.
  * If you enter a name (either manually typing one in, or pressing "random" until you get one you like) the old behavior of appending numbers is used.

**Comment by Wrzlprnft** [comment]
that suggestion sounds good, but needs documentation.

**Comment by gunqqer** [comment]
How naming works was changed in 0.9.7 that gets rid of numbering ships.

Closed.
