### ISSUE TITLE
Enemy ship destruction post move order to board

### ISSUE THREAD

**Issue by SamKeightley** [endless-sky/endless-sky#2215]
I find it pointlessly frustrating when NPC ships destroy a ship that you intend to board after you have clicked on it. This problem gets even worse when your piloting a slower transport full of crew and the NPC's are flying fighters which will always beat you to it. 

I think NPC's backing off after you have specified that you are boarding it would be good thing. This isn't to say that you can exploit this by immediately clicking on one about to die in the middle of a clump of ships, but to prevent ships beating you to a ship you are just about to board and destroying it just before you get there. 

Pros: Way less frustration!
Cons: Will have to think of some rules for when and when not to prevent NPC ships destroying disabled ships that the player has clicked on to board in order to prevent exploitation.

**Comment by MessyMix** [comment]
There are ships that don't go out of their way to finish off disabled ships. In fact, only certain ships actively seek out disabled ships to kill; they're tagged with "vindicative".

So unfortunately for you it seems that this is an intended feature. If you're salty at the Republic, head south. The Free Worlds do not shoot at disabled ships they aren't facing.

**Comment by SamKeightley** [comment]
I'm aware that it's intended and I'm not suggesting to remove the vindictive behavior entirely so am confused about how you think that is what I meant. I'm actually happy with it, but it would be much better if vindictive ships stopped being vindictive towards a ship if the player intends to board it.

**Comment by KiLEdEnNis** [comment]
@MessyMix *Vindictive and I think Heroic & Nemesis do that too (although the Heroics are the Navy, maybe their missiles just finish them off)

when I started I was around the Far North but the Navy kept destroying pirates so I emigrated to FW space (Kornephoros as my "home" planet)

**Comment by jafdy** [comment]
There are a lot of threads all over the place about this.

**Comment by Bladewood** [comment]
@MessyMix `vindictive` causes them to continue to fire on a ship after it has already started exploding. https://github.com/endless-sky/endless-sky/wiki/ShipPersonalities

**Comment by SamKeightley** [comment]
So instead of vindictive, the ships are just exerting normal behaviour.

**Comment by MessyMix** [comment]
@Bladewood thanks for the correction. It seems that `disables` is now the opposite tag, which prevents ships from firing at disabled ships.

@SamKeightley The thing is, it might be a lore-based explanation for this. You see, the FW are probably more sympathetic to the Pirates than the Republic are. You get people in the storyline that realize that perhaps a diplomatic solution with the pirates is less cruel and more effective than a militaristic solution. After all, they are only teenagers trying to make a living. And the fledgling FW government understands this, and is in a similar (although not identical) position against the Republic.

The Republic, on the other hand, comes off as, well, _vindicative_ of their superiority over pirates, by killing them even as they are disabled. They view the pirates as being anarchists who seek the downfall of the Republic. Because they evidently seem to think in such black-and-white, heroic, valiant, noble terms, they see the pirates as being despicable and evil. They lose sight of the humans behind the ship in their "honorable" and "glorious" crusade to crush these rebels. It justifies their killing of disabled pirates.

Note here, @SamKeightley, that I am not arguing against your suggestion at all, I'm just exploring what's currently implemented. _Why_ should the Republic allow boarding of pirate vessels? It will endanger merchant crew, and will also risk the pirate crew overpowering the merchant ship and taking it over. What happens, then, if the Merchant ship fails to board and then leaves? These are all questions we must consider when thinking about implementing something here. TBH, I think that the current system adds a layer of depth and flavor to the game. If you can implement a solution that retains this flavor, adheres to the game's lore, and  improves gameplay, I'll be happy to support it.

**Comment by SamKeightley** [comment]
Because it's a game, and the player should be able to reasonably board a vessel they choose unhindered by NPC's.

At this stage, there is nothing more frustrating than to see millions of credits lost because some NPC destroy an enemy ship as you are about to board it. It's even worse when it's a ship that you have disabled yourself too.

**Comment by endless-sky** [comment]
If you're in a region of space where other ships are helping you to disable pirates, they'll also "help" you to destroy them.

Most players learn rather quickly to either lure the pirates away from the heavily-trafficked part of the system before disabling them, or to just fight pirates in pirate systems where the Navy seldom appears.
