### ISSUE TITLE
Overhaul freighter raider system

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#2223]
Searched for it in issues, didn't find. (I'm notoriously bad at searching.) So I'm making a new issue.

There are alternatives to avoid freighter raiders. Any Berserker or Bounder can be disarmed and modded to be better at hauling cargo than a Star Barge — yet, they will not attract pirate raiders. So, instead of exponential Star Barge problem we can have exponential Bounder problem. Or cargo Bactrian problem.

Also, if there are many freighters, but even more heavy warships guarding them, then suicidal pirates don't make much sense.

My proposition is to replace fixation on amount of freighters to evaluating fleet's total cargo space to total firepower (number of weapons and total dps capability). Then no matter what ship category, better guarded convoys will be left alone in preference to poorly guarded ones, which is what real pirates would do, and which would resolve these balance problems nicely.

**Comment by Amazinite** [comment]
This was talked about a while back, but never on GitHub. Good change. 👍

**Comment by jafdy** [comment]
I see a problem at the start where you fly an unarmed ship around but this can be fixed by doing (maxcargo-abit)/firepower.

**Comment by Tadrix** [comment]
@jafdy As an example, this system could be turned on if any of the following are true:
1. Player has more than 7 ships (incl. flagship);
2. Player's total cargo capacity exceeds 760 t;
3. Player's net worth is at least 25M.
So, the player could have relatively untroubled start of the game, only to make things interesting later.

**Comment by Amazinite** [comment]
`(<fleet cargo>/(<fleet firepower> + 1))/1000 = raid spawn chance`?
This would make it so that an unarmed Star Barge has a (50/1)/10000 = 0.5% chance of spawning a raid.

**Comment by Tadrix** [comment]
Number of guns seems to me as poor choice. Then savvy players would outfit their ships with ordinary blasters.
I'd say total firepower is fleets total dps vs. shields.

**Comment by MessyMix** [comment]
I agree with this, and this is something I supported when it was first brought up.

But just to nitpick with you :P
>Any Berserker or Bounder can be disarmed and modded to be better at hauling cargo than a Star Barge

hmmmm...... not sure about that one ;)

**Comment by Tadrix** [comment]
Challenge accepted.

Reductio ad absurdum proof — remove anything, put a fuel cell and smallest engines available, fill rest with cargo expansions.

Normal proof — I'll assume we want to have same or better functionality (speed, turn rate) as stock Star Barge and we will have same shields as stock Star Barge, to keep things fair. Also, we use human technology available to someone not completing missions.

Stock Star Barge
cargo space: 65 = 50+15 (20 free outfit space gets converted by cargo expansion)
fuel: 300; speed: 240; acc: 138,24/186,81; turn 61,44/83,027

Cargo Berserker
cargo space: 70
fuel: 500; speed: 420; acc: 173,75/221,76; turn 73,5/94,08
outfits: hyperdrive, fuel Pod, 4 cargo expansions, cooling ducts, D14-RN shield gen., 2 supercapacitors, nGVF-BB fuel cell, A120 atomic thruster, A125 atomic steering.
Cooling ducts can be replaced with further 2 supercapacitors, according to preferences.

Cargo Bounder
cargo space: 115 (and 16 passenger spaces for missions)
fuel: 900; speed; 249,73; acc: 142,52/202,34; turn 60,463/85,839
outfits: hyperdrive, 5 cargo expansions, water coolant system, D14-RN shield gen., Dwarf core, A120 atomic thruster, A125 atomic steering.
Cheaper alternative: replace water coolant system and Dwarf core with 3 supercapacitors and nGVF-BB fuel cell.
This ship is the best cargo transport I can imagine which doesn't attract pirate attention and is better than Star Barge.

**Comment by gunqqer** [comment]
@Tadrix You aren't using any alien outfit. I Feel like alien outfits would possibly change the outcome of this.

**Comment by Tadrix** [comment]
@gunqqer As I said,
> Also, we use human technology available to someone who didn't complete story missions.

These are available from the start.

Want to use alien outfits? Install Korath generators (Candle class) as power sources together with Korath small heat shunts, use Hai Chasm batteries instead of supercapacitors and S-270 Regenerator instead of D14-RN shield generator. I'm sure you'll be able to squeeze some more cargo expansions. Here you go (no Coalition outfits):

Cargo Berserker
cargo space: 85
fuel: 400; speed: 420; acc: 173,25/235,91; turn 73,5/100,09
outfits: hyperdrive, 5 cargo expansions, small heat shunt, S-270 regenerator, generator (Candle class), A120 atomic thruster, A125 atomic steering.

Cargo Bounder
cargo space: 130 (and 16 passenger spaces for missions)
fuel: 900; speed; 249,73; acc: 142,15/213,23; turn 60,308/90,462
outfits: hyperdrive, 6 cargo expansions, small heat shunt, S-270 regenerator, generator (Candle class), A120 atomic thruster, A125 atomic steering.

If we were to sacrifice shield generation, some speed, or not trying to stay low on heat, these could be optimized for cargo hauling even further. Also, I'm not really even trying, I'm sure there are much better ship builds then these. But this is more than enough for proof of concept. Also, I intentionally constrained myself from using alien outfits previously.

**Comment by jafdy** [comment]
@Tadrix I think you made your point.

**Comment by zwparchman** [comment]
Ship type should never make it into code decisions. I've been messing around on a playthrough with masses of freighters only (current Coalition freighters)  and it gets annoying to have 15-20 Sparrows attack every single system only to be blown away in 1 to 2 seconds. Having >300 heavy lasers should be enough to stop petty pirate spawns.

**Comment by whismerhill** [comment]
I disagree with having fully automatic pirates disappearance based on fleet DPS

THAT SAID, what would be nice imho, is to see them retreat when faced with overwhelming odds ?
example IF your fleet DPS is overwhelmingly high enough, change the personnality of the pirates to something that will flee soonish .... (particularly fleets of small ships which don't stand a single chance)

IMHO, this would be nice.
thoughts ?

**Comment by LocalGod79** [comment]
@Tadrix, you appear to have omitted a key variable in your calculations: cost.

a star barge is cheap, and you can quickly make enough to borrow enough to buy another, and exponentially so from there.

freighter raiders are present solely to prevent this mathematical abuse of the star barge in the early game.

**Comment by Tadrix** [comment]
@LocalGod79 I disagree.

Cost isn't a factor even with depreciation, since player is unlikely to sell such a ship. A cargo bounder can transport 115+ cargo _and_ 16 passengers, which (if 1 passenger = 10 t of cargo) is 275 usefulness for just 1 crew member (and 100 cr,/d). None of other ships give so much for such little daily cost, and since such a ship doesn't provoke pirates, there's relatively little risk associated with operating it too.

Exponential Star Barges remain problem even in post-early game as there is nothing preventing player to have infinity+1 ships. Except there were pirates. With Bounders this problem doesn't exist either.

As a matter of fact, when I started game anew, at one point I had four cargo/passenger Bounders tagging along with rest of the fleet (a freighter and three normal Bounders — I tend to carry a lot of passengers in the beginning), and also I had a large debt. That debt cleared after about a month, because the whole point was to be able do bulk deliveries and colonists/strike breakers without being harassed.

**Comment by KiLEdEnNis** [comment]
> since player is unlikely to sell such a ship

using likeliness as an argument isn't right in my opinion; the game shouldn't assume things about the player
and I think you messed up your statement about a "cargo(?) Bounder": it has 40 cargo space, and it has 3 required crew, it lacks outfit space to refit it as a good transport and it's 1,6M
you can't really make that much profits with these Bounders, at least not so much as with freighters and bigger transports, and freighters are generally better because you can sell commodities from planet to planet, a transport requires jobs to be useful

and about the last part, you meant you had a Freighter and 7 Bounders? of course your debt clears after like a month, mid-game debts are way easier to clear due to the money-making ability, and late game debts aren't needed

so I don't really get your point besides adding occasional pirate raids on transports as well

**Comment by Tadrix** [comment]
Mid game? I really had 3 Bounders and a Freighter. However, I saw a good job opportunity and risked burying myself in 4,8 million debt. Soon afterwards I sold extra Bounders and cleared my debt. And it is beginning of the game, since at the start I tended to explore and just now terrorist nukes went boom.

Did you read my post two days ago here, right after @MessyMix wrote
> hmmmm...... not sure about that one ;)

Throw out turrets for starters — crew count goes to 1 and you have 16 passenger places. At the start I always do this to my Bounders, and perhaps install some AMs instead. But if you don't do it, you can downgrade your engines and fill all that extra space with cargo expansions. Boom, your Bounder already is much better than Star Barge could ever be, transporting 16 passengers and more cargo, but you still meed only one crew for such a wonder. AND it doesn't attract pirates. I mean, for purely cargo/passenger carrying this is the best you can have, seconded by underappreciated Hauler III's (which DO attract pirates, are slow and have less passenger space per crew). No need for Bactrians, you can always just have more Bounders.

**Comment by MessyMix** [comment]
>your Bounder already is much better than Star Barge could ever be

Don't even get started on this. The Star Barge is by far the best cargo ship in the game when min-maxxed, followed by the Freighter. There have been way too many Steam discussions on this, it's resolved, the Star Barge is the best for carrying cargo. Period. A min-maxed star barge WILL best your Bounder in terms of cargo per crew. That's not even a question. The question right now is that good cargo ships (i.e. retrofitted Bounder) won't attract PIRATES, whereas the Barge will.

tbh I feel you're trying to argue the wrong thing here. You're saying, "other ships should have pirate raids too; it has to be based on cargo capacity and armament". CORRECT. I AGREE. Right now, you're trying to argue that the Bounder is better than the Star Barge. Sorry, it is not. But that's besides the point, and yet you keep trying to assert it.

The point is that Barges attract pirates, whereas a retrofitted Bounder will not. This needs fixing. End of story. Don't make it into an argument about customizing ships, because that is one you will lose. Just trawl through the Steam threads because there are many on the Star Barge alone.

**Comment by Tadrix** [comment]
Yeah, I read them, and they are wrong if we don't take into account cost effectiveness. If you truly minmax (sacrifice everything for space, meaning, sell every outfit, buy nGVF-AA fuel cell and X1050 ion engines), and fill it all with cargo expansions, you'll end up with 110 cargo space in Star Barge and 175 cargo space in Bounder. Check for yourself in game. This is so obvious I don't even see the point to discuss it here, in Steam discussions or somewhere else. If you still choose to object, I'm fine with it, since I'm not really interested in convincing anyone.

Now, to the point. I see a lot of support for my proposition. I can't do this myself since my programming skills aren't sufficient (no experience in C++). How can we make this happen?

**Comment by kikotheexile** [comment]
I did the math, straight up, for Sinsling once. Straight up min-maxxed, one jump capable star barge vs min-maxxed, one jump capable <other ships> in order to state, straight up, flat out, that the star barge is a fraction of a percent better than the Freighter. A fraction of a percent. 

The bounder, however, is no where near close.  Having pirate raids depend upon cargo cap rather than ship class is a good idea, this is true, but the refitted bounder is not better than the barge or freighter. There is no argument for the bounder being better when it comes to cost effective refits, because it really, really isn't.   There is your answer.

**Comment by Bladewood** [comment]
The star barge is better. End of that discussion.
Forget about it.

Just come back on topic.

**Comment by MessyMix** [comment]
@Bladewood thank you that's what I'm trying to get at.

**Comment by Tadrix** [comment]
@kikotheexile 
> when it comes to cost effective refits

This. As I said, I never argued about cost effectiveness. Ofc what I described would be very expensive, compared to beginner ships. So it seems we were all this time arguing about two different topics.

@Bladewood You didn't participate, and, it seems, you missed the point entirely either.

Ok, I'll clear the misunderstanding: I never stated that for the same money one could buy better cargo space in Bounders than Star Barges. That would be ridiculous, as Bounders aren't nowhere near definition of cheap, and Star Barges are cheap as dirt.

I stated that if the aim would be to avoid pirates while having low crew per cargo / passenger spaces for any cost, then my setup was better than Star Barges. That's not cost effectiveness I talked about.

Which further proves the point in my OP. If pirates attack Star Barges and do not attack unarmed, retrofitted expensive ships (which is so absurd the owner oughtta have something valuable), then something is very wrong.

**Comment by KiLEdEnNis** [comment]
dps vs shields?
ships w/ high hull, fleets w/ a lot of utility weapons or flamethrowers etc.

**Comment by kikotheexile** [comment]
just base it on net worth, with a net-worth cap of a hundred thousand. Problemo solved. Pirates would, in lore, attack people worth a lot of money, because they would make money by ransoming them, or robbing them.

**Comment by Amazinite** [comment]
I just think that number of guns would be more realistic, because the "lore" behind pirate raids is that they hear that there is a big fleet of freighters nearby that could be attacked, but it should be "hey, there's a big fleet of freighters nearby, but they're also all armed with a bunch of guns." The pirates would never know your DPS, only how many guns you're packing.

**Comment by LocalGod79** [comment]
@Tadrix - you have not addressed why freighter raiders need to be present in the first place.

the "exponential star barge start", if not for freighter raiders, would be the de-facto early game strategy, as players would have little incentive to take any other, much slower, pursuit to wealth.

that depreciation is now a thing would actually exacerbate the problem, as the player is encouraged to retain their ships forever under the current system (or basically "burn" 75% of whatever they spent on their asset).

since the only time freighter raiders are a real problem for the player is if they're using ridiculous numbers of star barges, i really don't understand what you're requesting...

in any case: "freighter raiders" are not disappearing unless another solution can be found to prevent "exponential star barge start" (which you have not put forth), and your "min/max"ing of various ships (without accounting for key variables) discussion belongs in the Google Group, or on Steam.

please close this issue.

**Comment by whismerhill** [comment]
well, maybe it's another issue entirely, but I wouldn't mind the stopage of idiotic fleets of pirates interceptors almost everywhere I go
simply because this run I have about 40+ bulk freighters in my fleet (and also at least 30 war ships )
heck even a single of those bulk freighters can't be harmed by those fleets of pirates, even if not moving.

Just saying that after a while they are annoying buzzing insects I wanna step on.

**Comment by kikotheexile** [comment]
then people would get harassed more at lower levels, traveling unarmed... 

Net worth, sounds best to me. The more you're worth, the more pirates come at you. "Hey, we hear theres a rich fleet near by, lets go see if we cant grab any of their stuff!" "What about their guns?" "It will be like robbing a bank, i have the perfect plan..."

**Comment by Tadrix** [comment]
I see a major problem with net worth. Mainly, giant fleets of warships. Why pirates attacking these is a sanity crash, think Somali pirates. Also, if most of the fleet is currently parked, it makes no sense.

(Total number of guns + turrets) / fleet cargo? If pirates have no way to know which weapons are equipped, but can know if weapons are equipped, I'm starting to think that approach @Amazinite suggests is actually good idea.

> in any case: "freighter raiders" are not disappearing

@LocalGod79  I didn't ask for them to disappear. Please, read the OP before posting. I'm certainly not closing this.

**Comment by KiLEdEnNis** [comment]
@kikotheexile 2B net worth, T3 technology, flies by human space, 1 week later the Endless' Daily newspaper: Piracy disappeared in human space

**Comment by karkatic** [comment]
https://github.com/endless-sky/endless-sky/pull/2200

i'm a f'n noob to git, i wanted to do a 2nd pull request with my additional changes, but regardless...

in this commit i included logic for altering how pirates value ships.  previously it was a vlaue of 1 for light freighter and 2 for heavy.

now it's parameterized in parameters.text in data folder:
	"pirate attraction"
		"min outfit space" 200
		"damage per second factor" -1000
		"hull repair rate factor" -1
		"shield generation factor" -1
		"outfit value factor" 4000000
		"cargo tonnage factor" 100

using these values, the following (default from shipyard but fully-loaded with cargo) ships have the following values for comparison:

star barge: .34
star barge w/ blaster: .216
freighter: 1.174
hauler: .23
hauler ii: 1.5
bounder: .01
manta: -1.4
splinter: -.8
behemoth: 3
star queen: -1
leviathan: -.65

**Comment by endless-sky** [comment]
I'd prefer to keep things simple, ideally just using cargo capacity for a measure of how attractive a ship is, and damage per second as a measure of how much of a deterrent it provides. After playing around with a variety of formulas, I've settled on one that ranks the ships in what feels like a logical order:

```0.4 * sqrt(cargo) - 0.002 * dps - 1.8```

Below are the attractiveness scores for all the human and Hai ships, sorted by how attractive a fleet of a given value would be if it were made up entirely of those ships. (For example, for the price of one Freighter you could buy four Star Barges, which will be more attractive to pirates than the one Freighter.) Using this scoring method:

* A Star Barge has a value of 1, the same value it had before.
* A Sparrow or Fury is enough to guard one Star Barge, and a Quicksilver is enough to guard two of them.
* Aside from Boxwings (which can't form a fleet without a carrier), the most attractive thing to pirates is a fleet of Star Barges, followed by Freighters.

model | attractiveness
---- | ----
Boxwing | 1.78
Star Barge | 1.03
Freighter | 2.50
Heavy Shuttle | 0.57
Hauler III | 3.85
Scout | 0.87
Hauler II | 2.40
Bulk Freighter | 5.32
Argosy | 0.63
Behemoth | 3.02
Hauler | 0.51
Lightning Bug | 1.16
Water Bug | 1.43
Mule | 0.73
Bounder | 0.13
Clipper | 0.11
Skein | 0.33
Aphid | 0.11
Bactrian | 0.56
Headhunter | 0.02
Star Queen | -0.23
Shuttle | -0.01
Shield Beetle | -1.74
Roost | -0.47
Pond Strider | -1.12
Splinter | -0.55
Class C Freighter | -2.03
Leviathan | -3.17
Blackbird | -0.72
Falcon | -3.38
Marauder Splinter | -2.46
Carrier | -5.47
Gunboat | -0.99
Bastion | -1.24
Marauder Falcon | -5.75
Vanguard | -3.57
Cruiser | -5.29
Kestrel | -5.79
Dreadnought | -5.77
Osprey | -2.82
Nest | -1.52
Protector | -4.37
Aerie | -2.00
Marauder Leviathan | -7.56
Marauder Firebird | -5.15
Marauder Quicksilver | -1.91
Frigate | -3.41
Corvette | -3.30
Arrow | -1.56
Firebird | -3.00
Hawk | -0.62
Raven | -1.63
Marauder Manta | -4.73
Marauder Raven | -4.82
Manta | -3.61
Modified Argosy | -2.73
Marauder Arrow | -2.51
Quicksilver | -1.81
Marauder Bounder | -3.64
Marauder Fury | -3.79
Fury | -0.85
Rainmaker | -2.20
Violin Spider | -2.52
Sparrow | -0.80
Berserker | -1.64
Wasp | -1.28
Flivver | -1.96
Flea | -1.96
Finch | -2.35
Dagger | -2.35
Barb | -2.25
Lance | -2.35
Combat Drone | -2.08
Surveillance Drone | -1.80

**Comment by endless-sky** [comment]
And, here's the commit that implements that: 7715677.

**Comment by Tadrix** [comment]
Nice!

> A Sparrow or Fury is enough to guard one Star Barge, and a Quicksilver is enough to guard two of them.

No need for Quickslivers though, seems like a pair of Flivvers are a better deterrent while being cheaper and having less crew. Seriously, you'd think Pirates love to ransom rich customers in Flivvers…

**Comment by KiLEdEnNis** [comment]
1 Surveillance Drone mitigates 3 Haulers :I 
you do need a Cruiser but it seems weird that drones in general can do this

**Comment by Tadrix** [comment]
Makes sense. Imagine an aircraft carrier. Without its planes it's just a fat target. With them, however…

I thought Surveillance Drones were unarmed?

**Comment by KiLEdEnNis** [comment]
ye but they have no cargo
if 1 Surveillance Drone repels the pirates from 3 Haulers, then I guess pirates are afraid of them

**Comment by Tadrix** [comment]
Ok, so then −1,8 is intentional baseline for every ship, so by default pirates start uninterested.

Maybe they think it's a Navy drone and fear that a pirate-hunting fleet could jump here any minute now, with Cruisers and everything. xD

I'm still intrigued by Flivvers repelling pirates though. Flivver is basically a rich man's toy, like a sports car or a private plane. I bet people traveling on them look like a ransom money on a platter floating just there to a pirate.

**Comment by jafdy** [comment]
This is by a formula. Formulas are not well know if taking "character" into account, in fact they are used for precisely that reason.

A surveillance drones won't counter a Hauler as the formula if for the entire fleet cargo mass and weapon mass.

**Comment by EndrosG** [comment]
@Tadrix:
my maxed out mods for the mentioned ships, still using human tech only, were:
- Barge 95 tons, 2 free bunks
- Berserker 100 tons, 1 free bunk
- Bounder 145 tons cargo space, plus having these 16 free bunks for passengers

If you know you dont attract pirates, you can save on engines and thus again on power.

other ships:
- Blackbird (crew: 3) 240 tons + 25 bunks
- Freighter (crew: 2) 255 tons + 5 bunks
- Hauler III (crew: 3) 525 tons + 9 bunks or 495/510 with better steering and AM Turret

Both, the Bounder and the Blackbird, come with a high fuel capacity.
When playing with vanilla human technology, I really liked the BlackBird and used it as flag as well as escort. Keeping salary low, it was (and still is) a nice ship for capturing others. No surprise, one of my first modded ships was a somewhat scaled up Blackbird.

outfits:
Barge: nGVF-AA, X1200, X1700, Hyperdrive, 3x Cargo Expansion ; 412k cr
Berserker: nGVF-AA, X1200, X1700, Hyperdrive, 6x Cargo Expansion ; 812k cr
Bounder: nGVF-AA, X1700, X2200, Hyperdrive, 7x Cargo Expansion ; 1.473m cr

-----

Regarding the surveilllance drone: ships / fleets using them are still stronger than ships without them.
First, they can take at least some (minimal) damage, i.e. they partly attract enemy fire. This way, they protect their carrier.
Third, a swarm of fast moving ships is always freightening. Who knows if those drones wont self destruct next to you?
Second, lore-wise, a carrier with surv drones can better pick the "perfect" target to shoot on than one without scanners. Detecting illegal cargo, passengers to rescue, dangerous weapons / outfits, ...

**Comment by KiLEdEnNis** [comment]
I'm sorry I really don't see how that comment is relevant in any way

**Comment by EndrosG** [comment]
It refers to comments 8 and 10 of Tadrix from 5th march.
I'd like to point out that once you are "sure" you dont attract pirates - because of switching ship class away from freighters - which was his original argument - you can cut down speed and shield charging as well.
All you need is a "fast" (maneurable) flag ship which jumps from source to destination and avoids any battles inbetween. The escors will arrive, regardless of how many pirates try to block the intermediate systems.
If talking about maximum cargo storage, that is a point.
Back in feb/march 2016 I used to fly such a fleet.
