### ISSUE TITLE
More than 3 landable planets in a system pushes UI off screen

### ISSUE THREAD

**Issue by Lorantine** [endless-sky/endless-sky#2230]
long title short:
![overlap ui](https://cloud.githubusercontent.com/assets/10348657/23653672/aa94b95c-032d-11e7-9c1f-02506dc9294d.png)
my laptop has a 1600x900 screen and the left bottom stuff gets cluttered
checked for duplicates but didn't find any about this (but didn't click every single issue)

**Comment by MessyMix** [comment]
I've 100% seen this issue before.

**Comment by KiLEdEnNis** [comment]
I did see other ones about the UI, but the closest one I found is 1 that asked to widen the sector name things (where MZ said Gamma Cassiopeiae is the max)
#2085 I think
imma re-search for duplicates for a sec as well

**Comment by VonZorch** [comment]
Making the boxes collapsible and/or dragable would fix this.

**Comment by asl97** [comment]
@KiLEdEnNis FYI, you aren't really playing at 1600x900, it's more like 1600x837, it shouldn't overlap if you play in Fullscreen mode with the full height of 900 px.

Anyway, I did submit a patch that did that but decided to close it due to lack of comment and interest from the owner.

It's at https://github.com/endless-sky/endless-sky/pull/650#issuecomment-172016078 along with a screenshot, the modified xcf and generated png and now an svg*.

[endless-sky said](https://github.com/endless-sky/endless-sky/pull/650#issuecomment-172003123) that for it to be merged, it need to be an improvement and the original vector graphics has to be edited.

To which I pointed out that having the trade price shown at the same spot is an improvement.
Compare to it 'jumping about' when looking through systems with different amount of Commodity.


\* I finally notice the 'map trade texture' was in 'map ui.svg' and decided to redo the texture and reopen due to this issue.

**Comment by endless-sky** [comment]
Addressed this by moving the orbits widget to the top right and the key directly below it, in 746bc21. That addresses both this issue and the rather awkward-looking placement of the orbits widget:

![map details](https://user-images.githubusercontent.com/11450262/31365569-009f3c4e-ad3a-11e7-8a1b-0d08b0acbfca.jpg)

**Comment by litrevan** [comment]
Resolution 1920*1080. Five or more  landable objects takes up all the room for the trade window below on the left.  Trade prices still show up  with colors and numbers on the right, but not which one it is. Haven't found an example with four. What do we do if we have fifteen or more?
![Screenshot (20)](https://user-images.githubusercontent.com/68170965/90767534-3c272880-e2a2-11ea-80be-30f16cc00ed2.png)

**Comment by Amazinite** [comment]
What's your main zoom level? That UI is tighter than my screen, and I also have 1920x1080.

**Comment by Amazinite** [comment]
1920x1080 windowed (1920 by about 1000), normal main zoom factor. 
![image](https://user-images.githubusercontent.com/17688683/90769237-e6607980-e2bd-11ea-8722-2abc55bd221a.png)
![image](https://user-images.githubusercontent.com/17688683/90769305-02fcb180-e2be-11ea-9d55-690216df690d.png)

**Comment by beccabunny** [comment]
Unless we implement scrolling there, which might have seem like a weird behavior since the map also zooms in and out and the vast majority of the systems doesn't have 3+ landables, a possible fix could be to only show at most 3 planets in that section of the UI, as probably it isn't essential to have them all in there

**Comment by Amazinite** [comment]
We can cheat some space out by just not showing the "spaceport, outfitter, shipyard" lines if they aren't present and shrinking the UI boxes accordingly, instead of showing that text but greyed out.

**Comment by beccabunny** [comment]
If Amazinite's suggestion is implemented, then instead of having a fixed number of max planets the we could have the trading section UI calculated first and show only enough planets to have its borders not go off screen. In that case, we could also have ES show a planet with shipyard+outfitter instead of one that only has a spaceport, since that would be more important

**Comment by Zitchas** [comment]
I definitely like the idea of not showing outfitter or spaceport lines when they aren't present. Likewise, another space-saving possibility would be grouping planets together. To me, the three obvious groupings might be:
- Inhabited but unvisited
- Uninhabited and unvisited
- Uninhabited and visisted

All of three of these have no need for showing shipyard or outfitter mentions as a general rule, and could be listed together as a group.

**Comment by tehhowch** [comment]
The full fix is (unfortunately) to refactor the entirety of the map panels from their current procedural layout to one that is fully defined by the corresponding interface definitions. The parts of the map that aren't the systems & links themselves are basically the oldest graphics code in the game, so there is a lot of tech debt to wade through to achieve this refactor as well.

**Comment by Zitchas** [comment]
Ah. Sounds like a lot of work, although it could be beneficial.

I know there is talk about expanding Sol to include more of the solar system, too. And there is a lot of demand from people wanting more gas giants to land on...

Alternatively, could we have uninhabited planets simply left off that list entirely? We can still select planets via the mini map of the system, we don't really need to have a list of planets with nothing on them on the left hand side. Might be better to reserve that for inhabited planets.

**Comment by MasterOfGrey** [comment]
![image](https://user-images.githubusercontent.com/60949828/97819664-f81cbf00-1cf9-11eb-83d2-66ac22d0ac56.png)
Since no one else is appending this to the issue; this was in discord on the matter.

Additionally, I’m inclined to say that having the planet boxes collapsed using the legend should be the default view, click to expand a specific planet to the current view.

**Comment by Zitchas** [comment]
I definitely like the idea of having icons instead of listing off "Spaceport, shipyard, outfitter" all the time.

**Comment by Plip-Plop** [comment]
Maybe the planet list could be a dropdown menu. Something like this: 

Hidden: ![Down Planet Screen](https://user-images.githubusercontent.com/69060286/108157397-d7f1ef80-709f-11eb-86ce-566b6d391538.png)
Revealed: ![Up Planet Screen](https://user-images.githubusercontent.com/69060286/108157459-05d73400-70a0-11eb-9f19-d2302a17cac2.png)

**Comment by Hurleveur** [comment]
![screen_endless-sky](https://user-images.githubusercontent.com/94366726/142264698-b825a2cb-24ad-4049-8c74-460d59f449b2.png)
fixed it on https://github.com/Hurleveur/endless-sky/tree/unlimited-planets-supported-by-UI
but it doesn't look that good does it ? I'm open to suggestions (for now the upper and lower arrows only show when you can scroll to hint that is a possibility)
it would be possible to do it like in a outfitter/shipyard manner but then it would be easiest to move trade goods to right and would be required to give some planetary images and maybe other things ? I can't just put grey under the planet view and pretend it looks okay and I'm not confident I can do all of those changes properly. Also I want to know what you guys think would look best

**Comment by MasterOfGrey** [comment]
>  I'm open to suggestions  

Honestly I liked the collapsible layout with icons suggestion from above.
Maybe if above X planet boxes all were collapsed by default?

**Comment by Zitchas** [comment]
I like the idea of having multiple mechanisms here:

Having the collapsible layout with or without icons would be great, but I do think that the whole list of planets should scroll. I view having the scroll as something of a safety/compatibility mechanism, as it ensures the game continues to handle two situations without problem: Firstly, when someone stuffs a *lot* of planets into a system. (no matter how good the other mechanisms, there will always be a limit where it overflows). Second, when someone plays on a smaller screen. 

Ideally, the scrolling would just be done via mouse wheel, but having up and down arrows as you show there would work nicely. I know a few people have been doing UI graphics to make stuff that matches the current aesthetic. Maybe they could make arrows that fit?

**Comment by Hurleveur** [comment]
![screen_endless-sky](https://user-images.githubusercontent.com/94366726/142380257-764d985c-e15e-4ce2-86ef-2367b705f7b6.png) - updated image
Some true image for those arrows sure would look better tough if we keep this idea, for now I made them less aggressive (not bold text anymore) maybe I should make a tooltip message to notify the player of the fact it is scrollable the first time they have a too big system ?

The scrolling is done by mouse wheel the arrows are just to show when you can scroll, they aren't clickable. I can easily make it so you can click on them too to move the planets displayed that was my first idea actually (what I mean is on top of the scrolling which already works) if you want me to.

Also there is no use collapsing-decollapsing planets to show there is nothing so I propose just saying uninhabited instead of spaceport+outfitter+shipyard missing. 
Do you want the collapsing option for normal worlds on top of this ? (would be less optimised because I would have to check if the planets in the system all fit before starting to draw them, every time and also needs one more vector of bools, a more complicated loop each time you click so I don't wanna do it but I can)
