### ISSUE TITLE
Need a gun/turret offset angle

### ISSUE THREAD

**Issue by 0mothership0** [endless-sky/endless-sky#2237]
For some reason not every gun/turret need to point at exactly at what it aims, or just shooting forward.
Not saying it needs to be inaccurate. It will just be exciting if ships can fire at multiple directions. Adding a gun/turret offset angle may simply work out.

Okay, I'm saying like adding an "offset angle" attribute in the weapon definition which allows us to make the gun point at a specific direction instead of shooting forward, but still fixed.

**Comment by Amazinite** [comment]
Related: #579

**Comment by Bladewood** [comment]
https://github.com/Elyssaen/endless-sky/commits/feature/TurretFiringArc from Elyssaen

**Comment by jafdy** [comment]
I think he is asking for a gun that fires at a set angle instead of directly forward. 
So 90 degrees would be firing left, -90 would be right and 180 would behind you.

I have no idea what the turret thing is about.

**Comment by KiLEdEnNis** [comment]
maybe independent targetting or when ya have no target some turrets may fire just outwards
if/when weapon arcs get added, I hope guns can have at least a (-)90 degrees offset & then have a small arc, although just using turrets as broadside weapon works too

**Comment by 0mothership0** [comment]
Yeah, broadside weapons, sounds fun.

**Comment by gunqqer** [comment]
Broadside waepons sound like a really good idea. Giant, hulking ships taking passes at each other like in star wars (the... *shudders* prequels).

**Comment by 0mothership0** [comment]
Meanwhile an arc is still important for guns to "focus fire" on the target at mid or short range, instead of only focused at maximum range. An arc means they can change the focus point, sounds natural.

**Comment by Elyssaen** [comment]
Hey, my feature (re: @Bladewood ref.) is just about being able to swivel so many degrees _about_ the 'forward' point. I did think about adding the ability to define the 'forward' point as something different, which would allow rear weapons and broadsides, but it'd need a lot of work on the AI.

**Comment by Bladewood** [comment]
ohey Elyssaen's back

**Comment by endless-sky** [comment]
This would be pretty difficult for the AI to handle, especially if a ship has a mix of broadside and forward guns - how does it decide whether to strafe or do broadsides? And how would the player ship's "auto-aiming" work in that situation?

**Comment by KiLEdEnNis** [comment]
highest DPS side?
there's a lot of variables that decide which is optimal so it does seem very hard to add

**Comment by 1010todd** [comment]
_Posting from #3148_ 
From my idea the turret that are limited in firing angle would be like
`turret [x] [y] [first angle] [second angle]`
So typing in like this
`turret 2 8 0 90`
would result in turret that can only fire at this degree
![90degree](https://user-images.githubusercontent.com/19187937/31861981-8b3eb3fe-b760-11e7-8760-19bb03449d6a.png)
Here some example what it would be like using my idea of angle limiting.
![degree](https://user-images.githubusercontent.com/19187937/31861982-93663c5a-b760-11e7-8755-2368f77f9cc6.png)
So in the picture above I've also demonstrated what if only one number is defined after turret position numbers, it could be either any angle other than 0 to that number or from that number to 360/359.
So each ship would have their own firing angle defined, the ones that aren't limited don't have to define those numbers.

From this, firing angle would be limited if the specific turret hardpoint has the angle defined and if you move the turret to another mount it won't be limited anymore, so with this idea I think it won't need to change the engine as much as what people said in issue #3053 right?

For the AI as Kile said could work, facing the angle with the highest DPS at the enemy instead of facing the front at the enemy as this game AI are either forward against the enemy or run away spamming missiles.

**Comment by KiLEdEnNis** [comment]
to be honest, DPS is a mix between hull and shield
there are utility weapons too with lower DPS, which you may want to use, the AI doesn't take that into account then
how does the AI even calculate the highest DPS side

I don't think a proper AI can take all this into account, the best solution I can think of is make a more simplified AI, and don't make too complex ships with arcs all over it
I kinda want the turret arc thing too, but if the AI can't use them, it'll just ruin the game for players

**Comment by Pointedstick** [comment]
The only practical application of this that I can see would be to make broadside guns, but those would virtually useless. There's a very good reason why nearly every warship has dropped fixed broadside guns in favor of turrets since they were invented in the 1860s.

**Comment by Amazinite** [comment]
I have had ideas for large weapons specific to certain alien ships that can only fire in a cone in the front of the ship, but we’ll cross that road when we get to it in about... *checks watch*... eventually.
