### ISSUE TITLE
0.8.7: Fighters disappear if carrier is parked

### ISSUE THREAD

**Issue by ItsNickBarry** [endless-sky/endless-sky#224]
If a carrier is parked and the fighters it contains are not, the fighters disappear.  They should probably be automatically parked as well.

**Comment by endless-sky** [comment]
Fighters don't actually get assigned to a particular carrier until you take off. But, perhaps I could change it so that "extra" fighters get parked rather than sold when you leave a planet. Or, I could have a dialog that asks what you want to do with them, although that would be a bit more complicated.

**Comment by ItsNickBarry** [comment]
I didn't realize that they had been sold.  That's probably fine, but some sort of notification would be helpful.  Of course, a dialog with options would be even more so.

**Comment by endless-sky** [comment]
A note will appear in the messages at the bottom of the screen telling you that fighters have been sold, but I know people don't usually read those messages.
