### ISSUE TITLE
Fleet Command Bug

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2246]
There seems to be a problem with the fleet commands associated with ship capture, or possibly ship repair. I observed this when entering a pirate system with two ships. Becoming overwhelmed, I began retreating to the edge of the system. Once there I disabled and captured a pursuing Marauder Quicksilver. The captured ship was quickly disabled again by a Marauder Firebird. After disabling and capturing the Marauder Firebird, and another normal Firebird, I docked with and repaired the Marauder Quicksilver. At this point fleet commands ceased to work with any of the ships in my fleet, apart from the Marauder Quicksilver.

**Comment by wambat1** [comment]
Further testing has shown that this bug does not manifest if you have one of your fleet, but not the flagship, repair the damaged ship, given the above scenario.

**Comment by KiLEdEnNis** [comment]
look on the left, was the Marauder Quicksilver outlined green instead of white? that's a feature from the new zooming tactical fleet orders commit
if it was outlined in green, that means your fleet orders were only being sent to the Quicksilver, clicking it on the left again deselects it and lets you send orders to all ships again

**Comment by wambat1** [comment]
Thank you. I guess this one can be closed out then.

**Comment by KiLEdEnNis** [comment]
you can do so yourself ;)
