### ISSUE TITLE
Frozen NPC Ships

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2251]
I am finding npc ships frozen and unresponsive. They do not appear to have been damaged.

**Comment by Tadrix** [comment]
Could you be more specific? At which point they started to appear? Also, which version of ES you play?

**Comment by wambat1** [comment]
[love myron.txt](https://github.com/endless-sky/endless-sky/files/836474/love.myron.txt)

Sit in the system for some length of time. Eventually you will find them.

**Comment by Tadrix** [comment]
Can't confirm. Not on 0.9.6, neither on 0.9.4, nothing out of the ordinary, just endless militia vs. pirate battles in really large numbers. Could you provide more details?

**Comment by KiLEdEnNis** [comment]
what version ya playing on & what version ya started the save file
and which ships are freezing: just the random ships? and freeze in what way?

**Comment by wambat1** [comment]
I have been farming disabled pirates, so I have been in the system for as much as an hour at a time. I come across militia and merchant ships just sitting frozen in space. I have noticed their missile turrets firing, but otherwise non-responsive. I think you would just have to wait long enough.

**Comment by Tadrix** [comment]
Are some of them headed in the same direction? If yes, it could be arrival to or departure from the system, waiting for someone. But I'm pulling this out of my ass right now, never saw it myself.

**Comment by KiLEdEnNis** [comment]
are they completely frozen or do they drift aimlessly?

**Comment by wambat1** [comment]
No drifting and they do not all face the same direction. I am inclined to think these are ships that are departing from planets/stations. Thus far I do not think I have seen any targeted by pirates, and I seem to remember that departing ships could no longer be targeted until the departing animation was complete.

**Comment by KiLEdEnNis** [comment]
do you think you can record it and post a link?

**Comment by wambat1** [comment]
Conceivable. It may be some days before I get round to it, and I doubt very much I will be able to catch them in the act of freezing; I always find them after the fact.

**Comment by KiLEdEnNis** [comment]
seeing it start is extra, but seeing what they do in general is what I want
and take your time, MZ still gone

**Comment by wambat1** [comment]
It doesn't look like I will be able to produce a video. The game freezes every time I tab out to start recording. I don't have the kind of computer where I can just leave the recording program running for hours waiting for a ship to freeze.

#2267 is not very clearly worded, but I would guess he is talking about ships in his fleet, and the quick resolution would suggest to me that the player was having trouble understanding the fleet control system; I had a similar embarrassment when I returned to the game from several months absence; but figured it out on his own. I don't think this is the same issue; this thread concerns NPC ships freezing.

**Comment by Bladewood** [comment]
consider recording it with an external camera or something.
as in, one of these. https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Olympus_E-420.jpg/193px-Olympus_E-420.jpg

**Comment by ph2000bis** [comment]
I have experienced this as well on Navy NPCs. I do not know if they are targeted, but I saw a stuck Rainmaker firing its missiles. I think it had gone beyond the invisible line around the system (I was farming pirates far out).

**Comment by wambat1** [comment]
[Videos.zip](https://github.com/endless-sky/endless-sky/files/853259/Videos.zip)

**Comment by tehhowch** [comment]
@wambat1 do you still encounter this issue? 
Please share some of your system information as well (e.g. operating system and version/build number, processor/gpu, and where you get Endless Sky from (steam, github+self-compile, github-distributed binary))

**Comment by wambat1** [comment]
I haven't played in a few months. I should be getting a new computer this month, which, I hope, will allow me to record extensive footage.
Current computer:
Windows 10
intel core i7-4700mq 2.40ghz
ram 16gb
64bit OS, x64-base processor
intel HD graphics 4600
;

**Comment by tehhowch** [comment]
I think I've found a similar problem: if an NPC enters a system with no landable planets, cannot jump (yet), cannot request fuel from anyone (eg. only player ships or carryables present), and has nothing to fight, it will go to the star's location in the system due to c33b6f6cf. However, most NPCs will also try to land on it (except `skybound` and `staying` types, or ships without fuel capacity). This creates a stuck ship which does the "landing dance" on the star, and never gets to clear its target (because you can't land on stars). Because it always has a stellar target, it will never reenter the "decide what to do" phase of MoveIndependent, where it would find out that it is now able to jump away.

To reproduce:
1 . Go to Kor Ak'Mari
2. Cloak.
3. Wait.

Eventually a Raider will jump into the system and begin circling the star. After a bit, it will occaisionally go to refuel Raiders which jump into the system. It will not leave this system, even if you decloak for a bit to pester it, and then hide again - because it still has its TargetStellar.
Hypothesized cause of a Raider in Kor Ak'Mari that cannot jump: raider started elsewhere, jumped to it, jumped away, and then jumped back. Because of the Jump Drive, this can be done without taking so long that its internal `forget` timer is triggered while it is out-of-system.
This isn't quite the same as the issue here (which OP indicates happens in systems where the NPC can actually land and refuel), but is quite similar. The fix for it won't solve the issue in question, but between it and other updates to MoveEscort and MoveIndependent since this issue was posted, it's possible the corner cases that cause the behavior will have been resolved.

**Comment by tehhowch** [comment]
@wambat1 @ph2000bis please see if you can reproduce this in the latest official release

**Comment by Amazinite** [comment]
We're a ways out from v0.9.9 now. Any news on this?

**Comment by Amazinite** [comment]
With v0.9.11 being released soon and no response from OP (or anyone else) on this issue reemerging, I think we're safe to close this.
