### ISSUE TITLE
"Overkill" ship death

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#2276]
When the husks of dead ships are slowly exploding they can take an infinite amount of damage. This isn't that fun when say tributing earth where they pile up and make you waste energy (When using a lot of skylances energy is very valuable) and ammo that could have otherwise been used to blast ships out of the sky. 

What I am suggesting is that when a ship hits the negative of the value they are disabled at the ship instantly explodes.

**Comment by Amazinite** [comment]
#1786

**Comment by jafdy** [comment]
You even commented on that one.

**Comment by w0ntoan** [comment]
Maybe an exception can be made for massive nuclear bombs and other Tier 3 WMDs that would immediately disintegrate ships a la Terminator nuclear scene?

I've been trying to develop a reliable blackhole bomb that grows stronger as time passes, but the effect is diminished when exploding ships just drift through event horizon instead of just disappearing. Just imagine the horror when you get to a level of power that war ships that normally take ages to explode just immediately disappear instead.

**Comment by LocalGod79** [comment]
@gunqqer use a banisher with your skylances.  problem solved.

**Comment by gunqqer** [comment]
@LocalGod79 few problems with that.

Banishers take up space. A lot of space. That space could be used for better things. I only have a limited amount of 349s and for consistency I only use them. What you suggest is a temp fix that imo isn't that good. Also there's the problem if I use them that I would have to position them so they don't cancel each other out.

**Comment by LocalGod79** [comment]
you're complaining about wasted space, apparently at the same time as asking for a nerf to some of the counterbalance of beam weapons...

and how is it a temporary fix?  you're complaining that dead hulks are getting in the way of your hit-force-less beams - put some weapons with hit force, and push those hulks out of the way...

**Comment by gunqqer** [comment]
Not worth arguing about, closing issue
