### ISSUE TITLE
Quarg ships getting stuck in uninhabited Meteri systems

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2312]
I get groups of Quarg ships that will hang out in an uninhabited Meteri systems. They never jump out; they don't seem to need fuel, and I have to assume they have jump drives, as, otherwise, how did they get here.

**Comment by Bladewood** [comment]
The Quarg ships have 10 integrated ramscoop power (in the latest source build), so they should be regenerating fuel.

**Comment by wambat1** [comment]
Negative. I have tried docking with them to give them fuel, and they dock themselves with other Quarg ships passing through to refuel them. These guys will hang out in the system for hours until they are destroyed.

**Comment by jafdy** [comment]
Could you post a save file with this happening.

**Comment by wambat1** [comment]
They do disappear when you land, so a save game will not work. Your can observe the phenomenon by sitting in a system like Fornarep.

**Comment by endless-sky** [comment]
I tried sitting in Fornarep for half an hour and was unable to duplicate this. Are you running with any plugins?

**Comment by wambat1** [comment]
negative. i was farming the system for hours at a time. they disappear when you land so a save game will not help. if you can just leave the game running for a few hours while you do something else you will almost certainly have some hanging out when you get back. just make sure your fleet is strong enough take care of any hostiles that warp in so the Quarg do not get killed. 

    On Saturday, April 15, 2017 2:05 PM, Endless Sky <notifications@github.com> wrote:
 

 I tried sitting in Fornarep for half an hour and was unable to duplicate this. Are you running with any plugins?—

**Comment by tehhowch** [comment]
I've seen a fair number of some instances of AI ships that get "stuck" as well. I happened to be running a debug compile through gdb, so when I saw a hostile pirate "Berserker (Afterburner)" stop interacting, so I had to inspect it.
1) It was kicked into this no-op loop after getting hit with 6 Banishers
2) Its parent may have been disabled before it was sent careening away
3) It is currently hurtling away from my fleet and because drag won't kick in until it tries to turn, I can't catch it (its current velocity is 14.69)
4) It occasionally sends hostile hail messages
5) It will happily offer to leave me alone for a pretty penny if I hail it


Gdb discoveries:
1) It has a parent ship (another "Berserker (Afterburner)"), which I believe it spawned with (Fleet Large Northern Pirates, variant weight 2, "Berserker (Afterburner) 2"). I had previously thought only escorts and mission NPCs received parents, but according to [Fleet::Place](https://github.com/endless-sky/endless-sky/blob/52f5ac0469add79559778ef9070d121dc6d9993b/source/Fleet.cpp#L286), the first ship of a variant that gets placed becomes the parent ship of that variant.
2) Its maxRange (from AI::FindTarget()) is 4000, so my escorts are all too far away for it to consider them as targets, since its Position().Length() is 637851.6884782702 and growing.
3) It has no orders
4) It has sufficient fuel for a jump
5) Because it has no target, a non-dead parent, fuel, and is not the player's escort, MoveIndependent[AI.cpp L#919](https://github.com/endless-sky/endless-sky/blob/52f5ac0469add79559778ef9070d121dc6d9993b/source/Fleet.cpp#L286) traps it while also telling it to do nothing.

For reference, until I found it had a parent, its parent was disabled. After I learned it had a parent, I captured that parent. No change in the behavior of the poor Berserker. It also still bears a reference to its parent, despite the parent having changed ownership.

Takeaways:
1) Only AI ships that have a targeted ship will obey the "fence" and try to return to the system center (AI:868)
2) Government changes of the parent do not reset the parent-child relationship from the child's perspective.
3) I will test the impact of destroying the parent ship the next time I observe this behavior (the game crashed from too much time paused in the debugger before I could verify in this instance :(
4) Changing Fleet::Place `flagship` to `fleetLeader`  may improve readability - the large majority of references to `flagship` correspond to the player-controlled ship and not a possibly hostile NPC.*
5) This no-op loop bug affects both hostile and friendly NPCs, but is not exceedingly rare. It is difficult to reproduce on command, however.

**Comment by endless-sky** [comment]
Thanks for the detailed info, @tehhowch! The fact that the stuck ship was getting trapped in that particular line of the AI was exactly the missing piece I needed to figure this out.

I've addressed the parent not getting reset on capture in e8a629e.

Based on analysis of the code, I think a ship could end up in that line 919 condition in the following ways:
*  Its parent is disabled or dying (but still exists).
* Or, possibly, its "parent" is hostile (i.e. it's an enemy NPC following you) but is too far away to target it.

I've tried to address all those cases in c162a34:
* If its parent is dying, reset the parent.
* If its parent is disabled, fight enemies if present, then repair the parent.
* If its parent is hostile but too far away to target, move toward it.

**Comment by tehhowch** [comment]
I believe this issue of Quarg getting stuck in a system and not jumping away was caused by the lack of fuel to jump away, plus the previous bug where a ship would try to land on a stellarobject even if it was unlandable, and not clear its landing target (and thus never jump away).
The similar issue: #2251 (comment at bottom)
The PR'd fix: #2750 
In addition, the behavior update in PR #2967 will help speed up the refueling of any of them, whether they are the parent or escort in the fleet.
So IMO this can be closed with milestone 0.9.8 or 0.9.9.
