### ISSUE TITLE
A new button to enhance the gameplay label:enhancement

### ISSUE THREAD

**Issue by Oeleo** [endless-sky/endless-sky#232]
I got an idea yerstaday, if you want to have a big fleet with you but want to be able to "steal" the others ships you need to put only lasers in your ships or they will burst everything on their way. That's a little sad because it reduce the gameplay, so if a button could enable/disable the utilisation of secondary weapons, when there is a big battle, your ships could be at full power, and when you just fight several ships your fleet would only use her primary weapon. Furthermore, you will no more waste missiles for nothing. (and seriously how do i make a tag ?...)

**Comment by endless-sky** [comment]
Part of the long-term development goals is to have a more powerful fleet control interface. (Essentially, a way to zoom out and control your fleet like you would in a RTS, instead of just focusing on your flagship.) So, when I get around to doing that, I'll definitely add more ways to customize the escort AI.

In the meantime, I've added a new personality type, "frugal," that has ships only expend ammunition if they are outnumbered or taking heavy damage. That's probably the desired behavior in about 95% of cases.

**Comment by Oeleo** [comment]
Yes, it's really good because at one time the flagship is less important in the big battle.

**Comment by endless-sky** [comment]
This is fixed in 0.8.9 - escort use of weapons that take ammunition can be enabled or disabled in the preferences.

**Comment by Oeleo** [comment]
Yes I saw that, I think that it's really better like that, thank you.

**Comment by Gkramme** [comment]
Only endless-sky can add labels. I like this idea, but that would be a far off topic.
