### ISSUE TITLE
Anti Missile not working

### ISSUE THREAD

**Issue by egony** [endless-sky/endless-sky#2323]
I'm trying to make an anti missile using the Gatling gun but its not firing... Here's the code:

outfit "SP Anti-Missile"
	category "Secondary Weapons"
	cost 20000
	thumbnail "outfit/gat"
	"mass" 2
	"outfit space" -8
	"weapon capacity" -8
	"turret mounts" -1
	weapon
		sprite "projectile/tinyflare"
			"random start frame"
		sound "explosion tiny"
		"inaccuracy" 3
		"velocity" 16
		"lifetime" 1
		"reload" 3
		"burst count" 180
		"burst reload" 1
		"firing energy" .03
		"firing heat" 2.5
		"anti-missile" 2
		"cluster"
		"hit effect" "bullet impact"

**Comment by toilethinges** [comment]
https://groups.google.com/forum/#!categories/endless-sky

**Comment by Bladewood** [comment]
What @toilethinges is saying is that this is not the place for stuff like developing mods. The GitHub issue system is for reporting, tracking and addressing issues in the game itself.

**Comment by Amazinite** [comment]
>(Please close this issue.)

**Comment by endless-sky** [comment]
An outfit can be either an anti-missile or a weapon; it can't be both.

**Comment by EndrosG** [comment]
I know this has been closed, but...
I would like to fully answer to the OPs problem and also comment on the final comment of @endless-sky - Though the comment itself is correct it does not apply to the OPs issue/problem.

@egony:
**1.**
If you really want to use the gatling gun, then ensure that you allow your escorts to use ammo.
And be sure to have enough ammo loaded.
Your outfit "SP Anti-Missile" does not use ammo. :-1: Your attempt didnt fail for that reason (but for a different one, see below), but it makes it less realistic.

**2.**
The gatling gun uses submunition. While you would have instantly succeeded using the sidewinder launcher, you failed with the Gatling because of some specifics in its definition.

I will first show you how it will work and then explain you some complications (in terms of mechanics) when using submunition and what you cant achieve with it.

```
outfit "Gatling AM"
	category "Secondary Weapons"
	cost 20000
	thumbnail "outfit/gat"
	"mass" 2
	"outfit space" -1
	"weapon capacity" -1
#	"gun ports" -1
	"turret mounts" -1
	"gatling round capacity" 30000
	weapon
		sprite "projectile/tinyflare"
			"random start frame"
		sound "explosion tiny"
		ammo "Gatling Gun Ammo"
		icon "icon/gat"
#		"inaccuracy" 2
		"velocity" 1600
		"lifetime" 1
		"reload" 3
		"burst count" 180
		"burst reload" 1
		"firing energy" .03
		"firing heat" 2.5
#		"submunition" "gbullet"
		"anti-missile" 2
		"cluster"
		"hit effect" "bullet impact"
	description `A gatling gun mounted on a turret mount and redesigned to work as anti-missile.`
```

Changes to the original Gatling, despite the text stuff:

- replaced `gun port` by `turret mount` ---> you did that as well, :+1: 
- `outfit space`, `weapon capacity`, `gatling round capacity` changed to TESTING values, not necessary!
- removed `inaccuracy` because currently no anti-missile system uses inaccurancy. Removed it initially for TESTING purposes to avoid a source of error. Not sure if that would work. Some others may test. ;-)
- replaced `submunition` by `anti-missile` ---> you did that as well, :+1: 
- adjusted `velocity` ---> you forgot / overlooked that, :-1: 
- my `velocity` is a TESTING value, I wanted easy testing.
You would have to insert 336 here, or adjust the lifetime. Look at the `range` of the original Gatling in any outfitter having it. It is officially 336. Your "SP Anti-Missile" has a range of 16. That is, because the submunition has its own velocity and lifetime.
This thing WORKS. This turret fires, using ammo, using bursts and having cooldowns. And most importantly, it really fires only on enemy missiles / ammo and succeeds in eliminating them :+1:  (I did not test what happens when the pirate uses a regular Gatling... bad idea)

Check out how ammo and submunition is used in different weapons.
Most secondary weapons use only ammo, no submunition.
The Gatling uses a 1:1 mapping.
The Hai Railgun does as well (here the 1 is explicitely defined).
The Wanderer Thunderhead launcher uses `"submunition" "Thunderhead" 5`, i.e. 5 warheads per piece of ammo.

Conceptual things to have in mind in terms of game mechanics:
- The anti-missile attribute needs to be part of the turret/gun, not of the ammo or submunition. (you did that in this case :+1:). Because the turret/gun needs the triggering mechanism for firing. If the turret does not know that it fires anti-missile ammo, it would fire them always on the enemy ships and not on incoming missiles. :-1:
- The ammo / submunition should probably not have any damage values. For regular secondary weapons, the smallest piece of ammo/subammo hitting the enemy has the damage values since each small piece hitting the target inflicts the damage. Each Thunderhead deals damage or misses, not the carrying missile itself.
- So... what you (probably) cant achieve this way is firing one Thunderhead AM missile towards a cluster of incoming enemy missiles and have e.g. 3 of the 5 subheads eliminate 3 enemy missiles.
- All current anti-missile weapons (which I am aware of) use a lifetime of 1 (i.e. velocity == range). In theory it might work to have AM systems which dont instantly hit but instead use slow blaster shots (e.g. like the energy blaster) or ammo like trying to shoot down a slow typhoon torpedo or nuclear missile with a fast sidewinder. (1) It might sound charming but involves the question when the game decides if that sidewinder will succeed or not - this decision is relevant for deciding whether to continue shooting on that incoming missile or not. If it is certain that it will be destroyed there is no need to fire more sidewinders, otherwise fire until the first one hits. And the homing questions also arises once you use a sidewinder as anti-missile. (2) If using ammo (and not regular shots from a energy blaster), will that ammo (e.g. the sidewinder) again be subject to enemy AM systems and will this result in an anti-anti-missile effect? Example: The syndicate ship firing the nuke protects the nuke against sidewinders but taking them out as if the sidewinders would target the ship itself. :-1: 

Bear these things in mind and you can go on with your anti-missile gatling or other secondary weapon
