### ISSUE TITLE
Mistake in Deep Archaeology 3?

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2325]
John, after getting the results from the sample, says that "the second sample is between fifteen hundred (1500) and twenty-five hundred (2500) years old. Which means it predates the discovery of the hyperdrive by, at minimum, five centuries (500)."

Those numbers don't quite add up. 
Per the historical timeline, the all-powerful Plot Device was created in 2210. If the sample predates the hyperdrive by at minimum five centuries than that would put the church's build date at around 1710. But he says that the sample is between 1500 and 2500 years old, so that puts it anywhere from 513 to 1513 (assuming from the game start). So either he meant to say at minimum seven centuries or he meant thirteen hundred to twenty-three hundred years.

**Comment by Tadrix** [comment]
Are you sure this wasn't intended? After all, there are medieval tales about people abducted by elvenfolk who were then returned some three centuries later…

**Comment by endless-sky** [comment]
He's speaking in round number because the dating is somewhat uncertain.

Plus, assuming that "1500 to 2500" is the 95% confidence interval on the date, there would still be about a 0.1% chance that it's really only 1300 years old. So he's saying, even if the dating is way off, there's still no way this sample is from after the development of the Plot Device.

**Comment by Amazinite** [comment]
Well if he really is looking at it at a 5% siginficance level then why mention the .1% chance that it's younger? I think it would make more sense to say the minimum is something in the interval.
