### ISSUE TITLE
Coalition engine ordering

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2327]
I recently had a thought, and after discussing it with @Wrzlprnft, I have come to opening this issue.
https://github.com/endless-sky/endless-sky/issues/1887#issuecomment-266936827
Coalition engine modules stand out among engines, because instead of the expected smallest-to-largest ordering, they have the reverse: the large modules come first, and the small modules last.

**Comment by MessyMix** [comment]
>It's okay if they are out of order, right? They are alien engines, and therefore do not have to follow the same naming and ordering schemes as our own regular human engines.

I would agree with this issue, but then why not just have everything go the same way? Why not just standardise the Korath and the Pug engines while we're at it?

Also, it would be a pain to find a suitable word replacement for "small", simply because all coalition outfits are named "small" or "large", and alphabetically "s" comes after "l". For the naming of Korath engines, if we had "Stellar class thrusters" and "Stellar class steering", it already would be sorted the way everything else was, and that's a much simpler solution than the one that this issue calls for. ;)

**Comment by gunqqer** [comment]
I don't know if the issue is still open but there was a suggestion about reworking how outfitters are sorted entirely with subsections. The suggestions would solve this current issue

**Comment by MessyMix** [comment]
I don't find the outfitter subsection suggestion to be particularly useful or helpful. Filtering outfits _might_ be a good idea, but then again it's a lot of work for very little reward, and given that there aren't a _tremendous_ number of outfits in the entire game, I doubt it'll see prolific use. Can't hurt to have that option lying around, but to implement it to solve this one issue isn't an elegant solution imo.

**Comment by Amazinite** [comment]
> Why not just 

get over it?

**Comment by MessyMix** [comment]
no? :3

**Comment by Tadrix** [comment]
@gunqqer You are talking about #2166 . Under that proposal, engines would be subgrouped by type (afterburner, graviton, ion, Wanderer, plasma, atomic, Korath, Coalition), and inside those subgroups by increasing mass (outfit/engine space occupied). Subgroups wouldn't be visible by themselves, they would just place outfits in order (just like operation "sort by … and then by …" would).

**Comment by gunqqer** [comment]
And with them in an order you could order those subcategories and everything in them. Yeah it would take a lot of work but this game is not near completion an *many* outfits will be added. If you look at current plugins just having Shields Up will fill World Forge up to the bursting point.

**Comment by MessyMix** [comment]
I retract all my prior statements on this thread.

Here's how I see the current problem:
Each race has it's own engine nomenclature, which incorporates it's size, type, and function. The most common is size, type, function in that order, but each race is different. Here are several examples:

- Humans: `<size> <type> <function>` i.e. A120 Atomic Thruster, Greyhound Plasma Steering, X1050 Ion Engines
- Hai: `"<size>" <type> <function>` e.g. "Barsem" Atomic Thruster
- Quarg: `<size> <type> <function>` e.g. Medium Graviton Steering
- Pug: `Pug <size> <function>` e.g. Pug Akfar Thruster
- Korath: `<function> (<size>-class)` e.g. Steering (Stellar-class)
- Wanderer: `<size> <type> <function>` e.g. Type 1 Radiant Thruster
- Coalition: `<size> <function> Module` e.g. Small Steering Module

Okay. Why should we not standardize everything? Because we lose this uniqueness to each race. The reason MZ didn't allow for even the smallest of changes—to make the Korath engines <size>-class <function>, e.g. Stellar-class Steering, was to preserve this variation. It's not that he was too _lazy_ to allow me to PR it, but because he had reasons not to.

Okay. The Coalition outfits are strictly modular in the sense that they're always categorized small and large outfits. If you wish to rename the Coalition outfits to a) keep the current nomenclature style, i.e. modular outfitting, then you're going to have to find a word that replaces "small" and "large", but in alphabetical order, and apply it to the rest of the outfits, too. Yet, there are _no_ generic words that serve the purpose that "large" and "small" do. Check all the thesauruses, there are no substitutes for these words; since the modular Coalition nomenclature requires exactly the words "large" and "small", there is really nothing that you can do to preserve the unique style as well as order them small to large.

Let me also point out that Quarg engines, once Large and Small versions are introduced in future storylines, will also be ordered large to small alphabetically.

In my opinion, it will require way too many changes to order them small to large to be worth compromising the unique style of the Coalition outfits.

I thus stand by the current ordering of the Coalition.

**Comment by Bladewood** [comment]
Your argument is that it *can't* be changed, simply because there are no suitable replacements.
Very well then.

Do we even know if the Quarg will expand on their engine lineup?
I believe that they have a completely standardized engine design, like Coalition engines taken to an extreme. The Archons use it too. Which is why in my mod the "medium" graviton engines are absent, replaced with generic graviton engines.
