### ISSUE TITLE
Charge fighter shields in parallel?

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2333]
Currently, as far as I can tell, fighters that are being carried have their shields charged one by one, i.e. the shields of a second fighter don't start getting charged until the first is completely done. I think it would be more helpful to distribute the shield-charging capacity evenly across all the fighters once the carrier's shields are fully charged rather than charging them sequentially. Any thoughts?

**Comment by gunqqer** [comment]
Would this go all get the same amount or lowest get regened firsted then when they're all even it is distributed?

**Comment by KiLEdEnNis** [comment]
if ya have a lot of carriers regening fighters w/ different amounts of shields & all carriers have different amounts of fighter bays & shield regen, won't it be a lot harder for the CPU?

**Comment by jafdy** [comment]
Most of the time it is so fast charging that it doesn't matter. This would only become useful if fighters that are low on shields auto dock to regenerate as this would cause them to re launch in groups.

**Comment by endless-sky** [comment]
If fighters eventually get smart enough to stop at their motherships to repair and then launch again when ready, repairing the fighters one by one will presumably be a better strategy than repairing them in parallel.

Since it takes the same amount of time to repair all of them anyway, the only option that would make more sense would be to prioritize the most damaged fighter (which would automatically mean recharging them in parallel once they're at the same amount of damage).

**Comment by EndrosG** [comment]
If talking about prioritizing [staying with the sequential recharge/repair] I would prefer to prioritize the least damaged fighter. The faster any (single) fighter can return to battle the better is. I rather recharge 3 fighters from 75% to 100% (3x 25% = 75% of charging) instead of recharging the most damaged fighter which is down to 10% (i.e. 90% charging).

**Comment by tehhowch** [comment]
To address @endrosg 's comment, it could be a preference to choose the sort behavior of the BayOrder method in #3182, eg most vs least damaged

**Comment by endless-sky** [comment]
Commit 24cab84 makes it so that fighters will retreat to the mothership if badly damaged, and only launch again if they are mostly repaired.

Given those new mechanics, the optimum strategy with fighters is to maximize how many are out fighting at a given time. That means that repairing the *least* damaged one first (in order to get one more fighter out on the field as quickly as possible) is the optimum strategy.

**Comment by lheckemann** [comment]
Not necessarily — that's only assuming effectiveness grows linearly with the number of fighters, which I'd say is usually not the case (since more deployed fighters = more targets for the enemies to fight = less damage per fighter). So optimising for deploying fighters in "waves" might be better than optimising for the highest average number of fighters deployed over time. Basically, it's complicated…
