### ISSUE TITLE
Mechanics: Fleet disabled ship repair priority

### ISSUE THREAD

**Issue by wambat1** [endless-sky/endless-sky#2334]
When a fleet ship starts docking with disabled ships in the fleet, it seems to first choose the nearest disabled ship, but then proceeds to select other disabled ships in a nonsensical order. I assume it must be following the order in which those ships appear in the player info window. They should, instead, choose the next nearest disabled ship each time.

**Comment by themightygrunt** [comment]
If it did, it's kinda sorta make sense, right?
Like think about it, most people organize their ships from most valuable to least, so it's make sense for them to default to the I page listing

**Comment by endless-sky** [comment]
It's actually happening the other way around: disabled ships are requesting help (the same way you can) rather than active ships deciding to help disabled ships.

When requesting help, they ask the closest ally who is not already en route to repair another disabled ship. If there are more disabled ships than active ones, when each ship finishes repairing an ally it is now the only active ship that's not assisting someone, and that means that it is the "nearest" candidate for every single disabled ship.

If a disabled ship were able to see that an ally was repairing someone else but could say, "No, repair me first, I'm closer," it would be possible to get into an endless tug-of-war where two disabled ships keep asking the same ship for help and it never reaches either of them.

**Comment by wambat1** [comment]
Is it then random which disabled ship gets the attention of the repairing ship?
