### ISSUE TITLE
Merchant ships may dump their cargo immediately after being repaired

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2348]
A merchant star barge was disabled by a pirate ship. My ships engaged the pirate, and it flew fairly far away. Meanwhile, I repaired the star barge, only for it to dump all its cargo immediately. Surely this shouldn't happen if the pirates they were getting attacked by pose practically no danger anymore?

**Comment by KiLEdEnNis** [comment]
I think it's because it was low health but it got disabled before it could do it then
making it so that it only does that if enemies are in a certain range won't work either: pirates can have ranged weapons
maybe only making them dump cargo if they are under a health threshold AND if they are an active target of an enemy ship would fix this
you'd still have them dump cargo if a huge Navy fleet is around them & only a pirate Sparrow is some distance away, but a 100% fix isn't possible here

**Comment by VonZorch** [comment]
One simple fix would be to clear the dump decision on repair.  Then it could dump later if needed.

**Comment by KiLEdEnNis** [comment]
what if ya repair it & there's like 10 enemy ships right around ya then

**Comment by VonZorch** [comment]
It can always decide to dump cargo again.
Getting hit, dump cargo.
Just been repaired, don't need to dump now.
Bad guys still here, dump cargo NOW!

**Comment by KiLEdEnNis** [comment]
but what'd make it decide it then?
if pirates are near; what radius? what about ranged weapons like missiles where the pirate ship is out of the radius?
the issue would be "what decides that a ship should dump cargo"

**Comment by VonZorch** [comment]
It would use the same process that it used to decide to dump in the first place.  I don't know the in game mechanics, and not being a C++ programmer looking at the source would be no help to me.

**Comment by endless-sky** [comment]
This should be fixed by 12c650f.
