### ISSUE TITLE
Depreciation Rates

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2352]
Current depreciation rates are both too slow and too fast.
When you take your shiny new whatever out of the outfitter/shipyard it should have an immediate drop to about 80%.  After that it should take 3 to 4 years to drop to a floor value of about 25%.
This is of course my opinion and while my style is a bit brusque I mean no disrespect.

**Comment by KiLEdEnNis** [comment]
others could buy a ship, test it, maybe not like it & sell it a few days after purchase, they'd get punished too much for trying out ships & not loading game

**Comment by Tadrix** [comment]
@VonZorch If anything, you would want to follow actual economics rules of thumb about cars:
A new car loses 15% of its value a week after purchase; in total 50% of its value are lost after 3 years.
(I'd say 25% would be hit after about 5 years after its purchase, but this I made up.)

**Comment by KiLEdEnNis** [comment]
depreciation is balance, not realism
adding that's it's 1000 years in the future & not cars, we can't really compare it

**Comment by MessyMix** [comment]
@KiLEdEnNis, 1000 years is not enough for the human genome to change enough such that we _think_ differently. IMO human behavior + behavioral economics won't change drastically. So even if the scale might be a little different—perhaps now 15% becomes 5%—the rate of depreciation, i.e. the pattern which we perceive something to lose value, wouldn't change imo. For realism, it would be drastic depreciation after 1st week, and then less and less moving onwards.

HAVING SAID THAT. I completely agree with your statement that depreciation is balance and not realism. And for balance, I completely agree with the fact that depreciation shouldn't be severe for the initial period of time, because it gives players a chance to playtest without being too punishing.

**Comment by Tadrix** [comment]
OP proposed instant −20%, and this would neither be good for gameplay, nor realism. And I too think that initial drop in value is bad for this game as it prevents player from experimenting.

However, I agree that after this ships depreciate too fast. 50% at 3 years would be much better.

**Comment by VonZorch** [comment]
The initial drop was a number pulled out of the air any initial drop would do.  The 25% floor was taken from my current game, that was what my Star barge was worth just before Remembrance Day when I had enough wealth to look at a bigger ship.

**Comment by KiLEdEnNis** [comment]
I don't really experience any trouble w/ the 25% in 3 years, if others may want it to become less I'm fine with that, but personally I don't really need it to happen

**Comment by guillochon** [comment]
My question is why are the ships depreciating when they are losing no capabilities? A car loses value because it's more likely to break down when it's old, or has parts of it that no longer work as well. Perhaps the ships should require regular repair, losing capability (speed, turning, weapon firing speed/accuracy) if they are not repaired?

**Comment by KiLEdEnNis** [comment]
so capturing stuff isn't a brain dead OP way to get money & ya can't sell a ship to "tier up" in ships & immediately get like 60% of the new ship's costs back from selling your old ship
in short: to balance money making
