### ISSUE TITLE
Feature Request: Mission Sorting

### ISSUE THREAD

**Issue by Highrs** [endless-sky/endless-sky#236]
I would like a way to filter out my missions on the job board, by things such as: Reward, passenger or cargo, nearness and weather there is a time limit.

**Comment by natangold** [comment]
Dear lord, yes. Filtering and sorting would be great for either/both 'current missions' and 'available missions'. Alpha by type, alpha by <planet>, numeric by <payment>, numeric by <cargo> / <bunks>, and most importantly numeric by profit (i.e., <payment> divided by <cargo> / <bunks>.

**Comment by tehhowch** [comment]
Seems like this will require an additional "wide" sprite, as one column of the sorted table will have to hold the name of the mission, and the remaining numeric columns only have to be as wide as their names. For the names, offering every numeric component of a mission for sorting isn't sensible, and creating "complex" sorting criteria such as payment/ton/jump tends strongly towards handholding.

I'd lean towards sort options of
 - Payment (could be total, e.g. accept + stopover + complete, or just complete)
 - Due In (deadline - today)
 - Distance (would be the same distance used for auto payment calculation)
 - Used Space (cargo + outfits received - outfits given)
 - Used Bunks

The wide panel could remember that it is open, and the sort used last, so that it does not reset each time the panel is opened or returned to.

For graphics, much like choosing the map color, an indicator would show which sort is being used, and the choice of indicator would indicate ascending vs descending. Simplest would be to scale the collapse indicator used in the Shipyard and outfitter for categories.

This sort process would be restricted to missions that have the JOB category - story and spaceport missions would not be sortable. This limitation seems sensible since non-job missions are often composed from many parts.

**Comment by warp-core** [comment]
#6915?

**Comment by quyykk** [comment]
yes
