### ISSUE TITLE
With Caps Lock enabled, symbols are typed in numerical prompts

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#2377]
For instance, when I try to pay off a loan, numbers will type as symbols instead of numbers (this is not even the usual caps lock behavior). Example, "12345" will type as "!@#$%".

**Comment by tehhowch** [comment]
some possibilities:
 - Something in [Dialog::KeyDown](https://github.com/endless-sky/endless-sky/blob/2f5bb7878b3ae09b8ecb4a02a54c574325d3a8ad/source/Dialog.cpp#L186) needs changing

 - The bank screen isn't correctly asking for an integer input [passing](https://github.com/endless-sky/endless-sky/blob/ffb52706172eb32db03b686d975f62d297667ea1/source/BankPanel.h#L44) to Dialog that it expects a stringFun instead of intFun. BankPanel collects the input as a string rather than an int, and then after collecting, [casts it to an int](https://github.com/endless-sky/endless-sky/blob/ffb52706172eb32db03b686d975f62d297667ea1/source/BankPanel.cpp#L305).

 - the [shift](https://github.com/endless-sky/endless-sky/blob/f655f242a72041a547dd43d52112bba2688fae1c/source/shift.h#L19) array needs to consider if caps lock is the source of the shift.

I think it's the BankPanel, as you can happily type characters and not just numbers into the 'pay extra' and 'apply' Dialogs, and from my understanding of Dialog:KeyDown, for an intFun you can only add characters that are in 0-9.

**Comment by endless-sky** [comment]
Fixed in ea156e6 / 47c8885.

@tehhowch, the reason it's a string input is so you can type something like "400k" or "5M" (in other words, the same format that the game uses for displaying amounts of credits) instead of having to type out "5000000" and make sure you have the right number of zeros.

**Comment by tehhowch** [comment]
@endless-sky  I hadn't tried using suffixes on numbers until I saw the the comment about it in Format::Parse. Can't tell you how many 0's I entered, or how often I would alternate numbers just to be able to recognize what I was typing. :laughing:

**Comment by guillochon** [comment]
I've tested this in the new build and it appears to be fixed. Closing, thanks!
