### ISSUE TITLE
Escorts move to selected position regardless of system

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2382]
If I right click somewhere (telling the escorts to go there), and then jump out of the system, the escorts jump as well, and then move to the same corresponding spot in the next system. The command should disengage when we move to another system, or make the escorts hold in the current system (so they do not jump), because it isn't useful to have everyone park in the corresponding spot in the next system.

**Comment by tehhowch** [comment]
It's rather useful behavior when you find the disengage limit and `move to` your fleet there in one system, and then jump into a hostile system. Your fleet will beeline to that limit and wait for you to bring victims out to them, rather than flit about the system center and (perhaps) be obliterated by superior numbers, or require you to lead them there first (rather than soak up enemy fire so they can escape).

The fixed 'disengage' radius from system center is likely behavior in need of modification anyway... it becomes trivial to cheese opponents that are much stronger than you.

I do agree that I was caught off guard by the behavior when it first happened to me, but I wouldn't want all `escort do this` orders to be cleared on system change though: if I designate a ship to follow another, that is behavior I'd like to have persist when moving about the galaxy.

**Comment by MessyMix** [comment]
I agree with not making all escort orders clear on system change, so imo best solution: make escorts truly hold on your right-click command, so they don't jump with you. That's what I was expecting the first time, and I'm sure that's what many others were, too. It also solves the issue at hand.

**Comment by endless-sky** [comment]
Fixed in fb175d6.
