### ISSUE TITLE
Cannot refuel F.S. Shackleton

### ISSUE THREAD

**Issue by mokawi** [endless-sky/endless-sky#2385]
I'm playing with 0.9.6 (compiled on my debian machine). One of the Free Worlds missions involves salvaging a transport in Lesath, but when I board it, I can't manage to refuel it.

I do have more than enough fuel. I tried this with a Clipper and a Bounder. I also tried staying on top of the transport for while to see if it would refuel after repairs were done, to no avail.

**Comment by EndrosG** [comment]
- Is the ship lacking fuel at all?
- Did you set a course to Longjump (on the map) | Is any course set for your fleet?
- Try if you can refuel it after repairing it, if you change your own course on the map.
If nothing works, could you please attach a savegame?

**Comment by jafdy** [comment]
The ship should have ample fuel.

**Comment by mokawi** [comment]
Endros: 
- The ship I have to rescue (the FS Shackleton) lacks fuel. My ship, however, doesn't.
- I set the course to Trinket after "rescuing" (boarding) the FS Shackleton.
- Refueling (e.g. in Trinket) will refuel the ships that followed me there, but not the Shackleton, which is stuck in Lesath.
- Here's the save file:
[Josette Legrand.txt](https://github.com/endless-sky/endless-sky/files/908528/Josette.Legrand.txt)

**Comment by EndrosG** [comment]
in your save file, the ship is fully fueled.
Line 562 : fuel 600
I loaded your savegame, departed. The ship was shown as fully fueled while I was still in Sabik. Screenshot.

![endless_sky_v0_9_6__20170409__shackleton_fully_fueled_josette_legrand](https://cloud.githubusercontent.com/assets/26883037/24840846/d6e85cea-1d75-11e7-8c49-fa8439594756.jpg)
Fuel is the yellow line (the bottom line).
From top to bottom:
- (wide) blue is shields - they slowly restore
- (wide) yellow is hull - will not restore (no self-repair in space)
- white is energy (was restored right after repair)
- red is heat
- yellow is fuel

After arriving in the Lesath system, I pressed "b", to board the first available ship. It got repaired. Immediately after that I jumped out of the system - together with the Shackleton - because some enemies were ariving and this is a rescue mission.

**Comment by mokawi** [comment]
Ok, this is weird. So, in my case, it's the energy that doesn't get restored (I assumed it was fuel). And shield also isn't restoring itself either.
I can probably fix it by altering the save file.

**Comment by EndrosG** [comment]
Okay, I replayed your save again, just to take you another 2 screenshots. I put them together into 1 picture.

![endless_sky_v0_9_6__20170409__shackleton_fully_fueled_josette_legrand_2nd_screenshot](https://cloud.githubusercontent.com/assets/26883037/24841134/adbb1e78-1d7c-11e7-8964-4e5ccc972c41.jpg)

The main shot was taken 2 seconds after repairing the Shackleton. The ship is still the "target" of your flag ship, as you can see in the upper left. In both sections the ship is marked green, making it easy to identify.
A very small part of the shields has been already recharged in those 2 seconds. Energy storage / supplies is at approx. 60%, being higher than those of your Bounder escort ships which are engaged into some combat.
All of your ships have "lost" some fuell on the way to Lesath system, only the Shackleton is fully fueled.

On the right side, may be half a minute later (??):
Shields are still charging, one of your Bounders was lost during battle... I didnt bother since I wanted only the screenshots.

**Comment by EndrosG** [comment]
And you cant alter too much in your savegame file, because the ship starts as derelict. I.e. it should definetively have 0 shields, 0 energy and low hull. Changing those values before launch should not really help.

**Comment by EndrosG** [comment]
You did not board / assist that ship yet. At least not successfully. It is still disabled, as far as I would judge.
I have a build based on a latest fetch from master.
And that stuff worked very well with the 0.9.6 build from Steam as well.

Are you able to board other ships? Friendly (if they get disabled, happened to me in your savegame in that system with some Republic Drones) and/or hostile ones (disabled pirates which you could plunder or capture).

**Comment by mokawi** [comment]
You'll notice the hull indicator is slightly higher. That's all that happens when I board the Shackleton: the hull gets repaired to a certain degree, and the outline in the target description and arrows around the ship becomes green. So there is some kind of boarding happening, it's just not replenishing the energy.

Actually, I was just playing another game a few minutes ago, and one of my ships got disabled, and I had the same problem as with the Shackleton. However, there was no problem capturing or plundering enemy ships.

**Comment by Nechochwen-D** [comment]
What if you just remove the derelict tag? The game does not track whether or not it is derelict merely whether or not it lands with you.

**Comment by MessyMix** [comment]
"I had the same problem as with the Shackleton" sounds like a game error, then. Have you tried recompiling? If you play through Steam, what about verifying the game's integrity? That might help.

**Comment by KiLEdEnNis** [comment]
I play it on the latest Steam beta version & I have no issues, so it seems like some compiling issue

**Comment by mokawi** [comment]
I installed it on steam (v.0.9.6). It did not solve the problem. I really don't know what to do at this point...

**Comment by Nechochwen-D** [comment]
[Josette.Legrand.txt](https://github.com/endless-sky/endless-sky/files/911189/Josette.Legrand.txt)

Use this one. I have credited you the amount you would be paid and incremented the "assisted free worlds" condition. You should be able to continue the game as though you had completed the mission normally.

**Comment by endless-sky** [comment]
I tested the original saved game, and it works fine for me as well, so I'm really not sure what could be going on.

Note that the freighter will "keep station" with you when it is repaired, so it will not actually start moving until you move away from it. If, during that time, a pirate shoots it, you'll need to repair it all over again.

**Comment by EndrosG** [comment]
While your comment is good, the screenshot provided by the user shows zero shields and zero energy despite the ship being "green" in the upper left of the HUD. That's what confuses a bit. That and that it happens to him/her with the steam build as well.
I wonder if he/she has some testing libaries instead of stable version, resulting in the proper computations to fail. Being not a problem of the game itself but of the surrounding system.
Could that be?

**Comment by mokawi** [comment]
Nechochwen-D: Thanks! I haven't had the next assignment yet, but I'll keep playing

EndrosG: It's actually very likely. I'm having problems with other games as well. And there's this weird thing that sometimes, after I use google chrome, Endless sky will be super slow. I probably should wipe it clean and reinstall debian.

**Comment by Bladewood** [comment]
kill any browser processes before playing resource-heavy games.

**Comment by mokawi** [comment]
Bladewood: killing chrome process doesn't do anything. Besides it's *way* slower. The opening animation will take ~15 minutes to complete. Only restarting the computer solves it.

**Comment by endless-sky** [comment]
The "opening animation" is actually just a progress bar for loading the
image files, so if it's going very slowly you may have an issue with your
hard drive. (Or, conceivably, with transferring the images into your video
card's memory.)

**Comment by mokawi** [comment]
I don't think it's the hard drive; otherwise other things would get slowed down. Honestly, I think there is something with whatever is handling my graphic card. There has been problems with it ever since I installed it, and I've never been able to fix it.
