### ISSUE TITLE
imbalance Nest -> Roost -> Skein vs Haulers

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2396]
I've search for balance threads related to Nest or Roost ship classes.
I've read through the issues and PRs I found and none of them sees to adress what I want to post, so I can go ahead with a new issue.

*Summary*

I propose the following changes:
- required crew: Roost -> 6
- cost: Roost +1 million ; Skein +2 milllion
- mass: +20 / +40 / +60 tons
- drag: +0.15 / +0.3 / +0.45

-----

In my opinion the price tags for the hulls of the three Hauler: Type-F classes should be adjusted.
```
virtual Hauler Zero		530.000		-900.000
Hauler				1.430.000
Hauler II			2.340.000		+910.000
Hauler III			3.260.000		+920.000
Nest				2.500.000
Roost				3.000.000		+500.000
Skein				3.500.000		+500.000
```

I really like the modular approach of ship designs (when creating ship definitions) and when I first created an excel file with the (at that time) available ships (back in early 2016), I was happy to see that the Hauler series was really following its lore (except for a typo at that time with the Hauler III having only 360 tons cargo space, not 390 tons - got fixed later). The development to each bigger ship was very consistent.
*It even allowed for a clear definition of a Hauler based ship without cargo space. I didnt even come up with that idea until just now. Simply remove that 900k $ module. Compare the result with a Freighter or other civilian ship, and with a Raven / Corvette / Manta. The Hauler Zero is a slow but maneuverable ship with plenty of weapon mounts and outfit space... Can be classified either as transport or as light warship.*

Now, having the Type F ships still being Haulers, just with different modules, made me check them last night.

The cargo modules of the original series, costing some 900k each, deliver: 400 shields, 1500 hull, 110 mass, 1.0 drag, 130 cargo space.

The type F modules deliver: the same base stats of 400 shields, 1500 hull, 110 mass and 1.0 drag, but they add: 2 bunks (= small bunk room, 12 virtual outfit space), 100 fuel (= 1 pod, 8 virtual outfit space), 40 cargo space, 50 outfit space and two exterior ("under") hardpoints for fighters ("bays").
So... -90 cargo space, +70 (virtual) outfit space and two brackets seems "okay" - not overpowered. With standard mass/outfits expansion, 100 cargo space is converted into 75 outfit space. But these are newly designed modules, and not just old type C modules with mass expansion. So it's all fine here: Perfect in terms of space.
Surprisingly, they dont come at an additional mass. I would increase the mass by 10 to 20 tons. Those fighter brackets should have some mass, may be even some drag? (0.1-0.2)

One of the obvious mistakes is the required crew of these ships.
- Type C series: 3 crew for all ship variants. No crew required for the pure cargo modules.
- Type F series: 5, 7, 7 crew men. I guess it should be 5, 6, 7.

What made me really wonder was the pricing of the new Type F series. +500k for each additional module seems why too cheap for me. Compared to the 900k+ for the pure cargo module, 500k look like a joke considering electrical wiring (bunks, outfit space) and docking systems etc.. The type F modules are definetively more complex than the type C modules and thus should be more expensive.
The first type F module, i.e. the one forming the Nest, costs a rough 2 million.
Argueing, that some modifications had to be made to the cockpit module -- including one crew men on the bridge (+1 per each type F module), some additional software etc. -- one could say that may be 500k of those 2 mill were put into the cockpit module, and 1.5 mill should be the price for each type F module.

*Conclusion*

That is, I propose the following changes:
- required crew: Roost -> 6
- cost: Roost +1 million ; Skein +2 milllion
- mass: +20 / +40 / +60 tons
- drag: +0.15 / +0.3 / +0.45

-----
Appendix:
A two minutes GIMP strip of the "hauler i" sprite resulted in a (not perfect) "hauler 0" sprite.
No blender, just gimp - cutting out the module without too much effort.
![hauler 0](https://cloud.githubusercontent.com/assets/26883037/24905874/cd7e1230-1eb5-11e7-8e1f-a7f90e39b6c9.png)

**Comment by Bladewood** [comment]
"Hauler Zero" sounds pretty nice.

**Comment by KiLEdEnNis** [comment]
a hauler 0 would have no cargo space and thus hardly any use, it wouldn't even be that much faster if ya look at the other 3 ships

plus, your idea is to make the costs look synchronised, not actually balancing the ships, as none of them are very weak or strong, they are fine as is

**Comment by EndrosG** [comment]
I made a Pull for the Hauler Z, giving it a full lore. The lore story does not explicitely focus on the 0 cargo space but this just fits to the ships designation. The Quicksilver has 10 cargo space, not that much either.

Regarding the initial issue:
I think that the Roost and the Skein are too cheap.

Please compare the Aerie and the Skein, for example.
Aerie:
basics: 5.719m - 5700 shields + 1900 hull - 12/28 crew - 500 fuel - 2100 max heat
spaces: 50 cargo, 390 outfit, 150 weapon, 95 engine
armament: 2 guns, 3 turrets, 2 fighter bays

Skein:
basics: 5.859m - 3300 shields + 6700 hull - 9/18 crew - 700 fuel - 4100 max heat
spaces: 120 cargo, 500 outfit, 140 weapon, 80 engine
armament: 2 guns, 4 turrets, 6 fighter bays

The Skein is IMHO too cheap for it's capabilities. Same applies to the Roost. The ships are not overpowered, just too cheapt.

**Comment by SirStigII** [comment]
The Skein has extra costs in the form of 4 more fighters, add to that its low mobility and it's fine.

**Comment by DingusShingleton** [comment]
What you are forgetting is that the aerie has a hull mass of 130 and the skein has a hull mass of 470. That's a yuuuge difference and it means that the aerie (also with a 15 ton engine advantage) will be a sprightly platform that compliments its fighters while the skein will be a lumbering behemoth that has to leave its fighters to themselves in many more situations (which as we all know, equals destroyed fighters).

**Comment by EndrosG** [comment]
We had, before the Hauler Type F series came up, 3 carriers outside the Navy:
Mule (1 fighter)
Aerie (2 fighters)
Bactrian (3 fighters) - will soon require a license.

Mule: 6.9 mill credits, 9.8 mill hitpoints, 30.6 shield charging.
Aerie: 5.7 mill credits, 7.6 mill hitpoints, 30.6 shield charging.

Roost: 5.1 mill credits, 8.1 mill hitpoints, 122.4 shield charging (4x), and *4* fighters
Skein: 5.9 mill credits, 10.0 mill hitpoints, 196.8 shield charging (6x), and *6* fighters - requires licence

Bactrian: 25.8 mill credits, 26.1 mill hitpoints, 78.6 shield charging (2.5x of Mule/Aerie)

I honestly see the Mule and the Roost at a similar level in some points.
Both share 600 fuel (who cares, I know), 9 require crew men, 2 gun ports, 4 turret mounts, 450 outfit space, similar acceleration. Empty mass (without cargo and fighters) varies by less than 10%. The Mule is faster, but the Roost far more maneuvable by default.
The Mule comes with 270 cargo space, the Roost with 80. Lore-wise, those 3 additional fighter bays (despite being external for the Roost) match the 190 cargo space difference.
The difference in weapon capacity (210 Mule, 140 Roost) is matched out through the 3 additional fighters to, which have their own weapon space.
The difference in hitpoints is compensated by shield charging.

So... I still think, increasing the price of the Roost by 1 million and of the Skein by 2 million is reasonable.

**Comment by DingusShingleton** [comment]
..............Drag/Engine
Skein . . 12.5/80
Roost . .11.5/80
Mule . . . 5.7/110
Aerie . . . 4.1/95

You have to look at the whole picture. Using the hauler type Fs is limiting. They are painfully slow, and they don't really feel like warships, because they aren't. They are converted freighters, and they feel like it. Even with atomic engines, the skein is regrettably slow. All three type F haulers, due to to their speed, are far more reliant on their fighters than the other carriers, thus they will have to deploy them in more situations, and therefore, their complement will die and need replaced far more often.

That's why I think the price is fine.

**Comment by Amazinite** [comment]
It's also important to note that the Mule and the Bactrian aren't dedicated carriers, they just so happen to include fighter bays. The Aerie and the Hauler Fs are the only truly dedicated carriers that a non-Navy player can buy.

**Comment by EndrosG** [comment]
@Amazinite : Originally, I didnt compare with the Mule, I just added it in the lst comment for sake of completeness.

I did, @DingusShingleton 
> The Mule is faster, but the Roost far more maneuvable by default.

**They all have their pro's and con's.**
(The Hauler Zero has it's unique USP too, strengths and weaknesses)

I know that all Hauler ships lack end speed. I am fully aware of that. What is more relevant, when comparing with the Aerie is the ultra low weight of the Aerie, making it maneuverable and accelerating quicker. That is, it comes faster to a stop and can faster turn movement direction (not only ship orientation).
What do you mean by "they dont feel like, because they arent". I know they are slow, we had that argument.
That those type F ships depend on their escorts is not totally unique in the game. The Tek Far 109 medium warship of the Kor Sestor, being currently the largest carrier I know from vanilla game, has the same vulnerability.
>	description "The TF109 is designed almost solely for the purpose of carrying a fleet of Kor Sestor fighters and drones. Without them to serve as a protective screen, the ship itself is relatively helpless."

And a Class C Syndicate Freighter is even slower and less maneuverable than the entire Hauler series.
Shall we compare Syndicate Class C with Skein?
Hauler Skein:
- 5.9 mill cr, 10k hp, 196.8 charging
- 9 crew men control 6 fighters and 140 weapon capacity (2+4 hardpoints)
- lack of power for continous fire and shield charing, even when not moving
- better maneuverability, +100 tons outfit space, +100 tons cargo space
Synd. CCF:
- 14.3 mill cr, 21.1k hp, 78.6 charging
- 20 crew men control 12 drones and 140 weapon capacity (0+4 hardpoints)
- enough power for continous fire and shield charing, when not moving

I know that the Class C is not yet assigned to any shipyard or fleet or NPC (mission). But it is in the game as of v0.9.6 and as of current master repository.
Raising the cost of Skein by 2 mill to 7.9 mill would not harm in that comparison either.

![endless_sky_v0_9_6__20170411__comparison_of_aerie_skein_classc](https://cloud.githubusercontent.com/assets/26883037/24916550/c06f942c-1eda-11e7-93f5-32ad9d3fd78e.png)

**Comment by Wrzlprnft** [comment]
i want to point out that the hauler f types are made as a cheap fighter carrying ...thing during the fw storyline rather than a carefully designed carrier design perfectioned over years.

**Comment by EndrosG** [comment]
Agreed. A carefully designed ship would not come with 300 power supply and 200 + 600 + 200 = 1.000 power demand. ;-)
This ship needs to have it's con's and it has them in it's default configuration. - As always, the user can address some of them easily (e.g. swapping out one of the 4 D67-TMs and the S3 Thermionic for a Breeder Reactor, delivering 768 power, and an LP144a instead of the LP072a).

Interpreting all your comments as rejects, I wonder if you are completely against an adjustment or if, may be, -500k for the Nest and +500k for the Skein were thinkable. Plus the nerfs if mass, drag and crew.
(?????)

**Comment by Wrzlprnft** [comment]
it's not like i am against it, it just feels like it's a change for the sake of numbers, i'd at least wait until the ones who put the numbers up initially can say why those were chosen, and then we decide. hardly a number is randomly generated, i just want to hear the other side

**Comment by EndrosG** [comment]
That's what I want too. If I would not have wanted a "hearing" first, I would have created a Pull in the first place.

**Comment by Elyssaen** [comment]
#### Required crew
Yep, I can agree with the Roost requiring 6 instead of 7. A 5/6/7 pattern makes more sense than the 5/7/7, and it helps make the Roost less expensive to run than the Skein. It's a tiny tweak, but I'm all for it, realism-wise and gameplay-wise.

#### Aside: virtual outfit space: 

> 2 bunks (= small bunk room, 12 virtual outfit space)

I really, really think you need to be careful with this kind of 'virtual outfit space' number. It'd work if the only consideration in ship design was fitting to modular rules, but that takes a backseat (in this setting) to balance and playability. This is really obvious with bunks, which are worth (in space) far more as an outfit than when they're built into the ship.

The balance and playabiliy questions don't fit into formulae easily, as they range over questions like "How much money can this ship make hauling passengers?" and "What's the strongest ship this ship can capture?"

Also, I can think of a _realism_ argument for why your virtual outfit space number might not be very good. Most ships have to have life support, which will probably be rated for a particular crew count and volume of air. Adding a Small Bunk Room goes beyond that limit, so the 12 space has to include an integrated life support system. That isn't going to be anywhere _near_ as efficient as a ship built from the ground up to support two more crew.

#### Cost

I definitely agree that a F-class modules seem to be worth more than the normal freight modules. However, one _crucial_ piece is missing from your analysis.

List price and manufacturing cost aren't the same.

Manufacturers _charge_ 900,000 for each additional freight module, but that doesn't mean it cost 900,000 to manufacture. What it says is, consumers are willing to pay a 0.9M premium for the next grade up of Hauler.

The F-class modules might cost significantly more to manufacture, but consumers might not be willing to spend 0.9M extra for the next Hauler Type F up. Particularly, since they're sold only to FW militia, they might not even be trying to get the same kind of profit margin.

All that said, the Roost and Skein have always _felt_ too cheap to me, but adding +1M/+2M would feel like overkill to me. Balance-wise, I'd support +0.5M/+1M at most.

#### Mass

So if you equate the two 'upgrade modules', for them both to add +110 tons of mass you're looking at that coming from:

**Freight Module:** 400 Shields, 1500 Hull, 130 Cargo Space
**Carrier Module:** 400 Shields, 1500 Hull, 40 Cargo Space, 50 Outfit Space, 2 Fighter Bays, 2 Bunks, 100 Fuel

What we don't know is the mass needed to support 1 unit of cargo space, or outfit space. Presumably in the former you're looking at not just interior walling, but also all the mechanisms needed to actually move cargo crates around. For the latter, you're skip the latter but add in wiring and cooling. If we stick in the 'mass needed for one of this' as an unknown, we get:

90c = 50o + 2fb + 2b + 100f

We can _probably_ use your virtual outfit space (well, virtual outfit _mass_ ) for the Fuel Tank, so that's 8. A Small Bunk Room only masses in at 3, and that's probably far more than it has to be if it's better integrated. But taking 3...

90c = 50o + 2fb + 13

So... what *is* the amount of supporting mass per unit of cargo/outfit space? The best guess we can take is that fitting a Cargo/Outfit Expansion will give you 15 of that space, but add +5 mass. If we assume then that both c and o are 1/3:

30 = 17 + 2fb + 13
2fb = 0

so yes, I have to agree that the fighter bay mass might not be considered.

_However_, we could come back to a simulation vs gameplay question, because if increasing the mass of these carriers doesn't make the game better-balanced and/or more fun, there's really no reason to do it. And it bothers me in this case that these ships are slow enough as it is. I think gameplay vs realism is the fundamental sticking point here.

And besides, you can make those above numbers work out and give fb = 10 or 20 if you plug in some assumption that Hauler cargo modules (maybe esp. in the I/II/III line modules) are mass-inefficient because of highly sophisticated fast loading/unloading machinery. This is the biggest vulnerability with the sort of modelling you're trying to do: you don't have visibility of everything that isn't statted in-game.

**Comment by EndrosG** [comment]
@Elyssaen :
Regarding required crew: there is also a chance that the Skein was meant to require 9 people, i.e. 5/7/9, but we will never know without feedback from some people which were involved into that content creation

Regarding virtual outfit space my base statement was, that the Type F modules are not overpowered compared to the Type C modules

Regarding mass:
Indeed, my excel sheet has a "virtual mass" formula integrated, but I didnt write about that one.
I always found that the mass added with each cargo module was a bit high while the drag was a bit low. Most clearly seen at the Hauler Zero with a very high base drag and and an average base mass (comparing with a gunboat, for example).
*But changing the mass was not my primary concern. I just added it to complete the issue.*

Regarding pricing:
If we apply your +0.5M/+1M, then at least we would have +1M for each additional module beyond the first one. That would be slightly above the additional cargo module, which would be a minimum consens :-)

**Still, I hope for more feedback before creating any PR**

**Comment by LocalGod79** [comment]
i think crew complement was supposed to be 5/7/9 (to have two docking arm operators per type F pod).  not sure what happened there (that was some time ago).  could have been that 9 crew was just too much for the amount of warship one gets out of the Skein...

initially, the Skein and Roost *were* more expensive (and in higher Warship categories), but when i placed them in simulations (with a fighter complement), they did not balance against the existing content at that price point (which, at the time was, and i believe continues to be, the truest balance metric).

as @DingusShingleton (a giant contributor in that content addition) pointed out, the F-type Haulers are painfully slow, and are only really "warships" by virtue of the gun ports that their fighters could provide (which carries its own costs in combat, especially with a excruciatingly slow carrier).

personally, i found swapping the hyperdrive for a scram' was the single biggest upgrade for these ships in their role as force multiplier carriers, but as you've said - there's plenty of room for improvement (and the stock outfits are generally "locally sourced" - already commonly available in southern outfitters).

that the type-F pods have completely different effects on the ship (did you look at the heat dissipation, too?) reinforces M.Z.'s proposition that different ship hulls should have their own "personalities", that a cargo pod could have a mass similar to a type-F pod, but have completely different attributes because of materials and design.
