### ISSUE TITLE
SConstruct: Add support for DESTDIR parameter

### ISSUE THREAD

**Issue by akien-mga** [endless-sky/endless-sky#24]
When packaging RPMs, files are installed in a temporary directory called buildroot (similar to Debian's debian/tmp), and it's pretty usual to rely on the DESTDIR parameter to achieve that.

Currently to install in a tmp directory one should use ```PREFIX=${mytmpdir}/usr```, but that's not really the "proper" way of doing it. It would be more accurate to be able to install Endless Sky with:
```scons install DESTDIR=${mytmpdir} PREFIX=/usr```,
i.e. you should edit the install script so that it puts stuff in ${DESTDIR}${PREFIX}, with DESTDIR potentially being undefined.

In your case adding support for DESTDIR would be mostly an added convenience for packagers (many distros have macros that include this DESTDIR, e.g. on Mageia we have ```%scons_install``` that does the same as the above command without the PREFIX part.

If in the future you need to pass installation parameters as constants during the build time (e.g. to tell the game where the data will be installed), the usual way would be to define the PREFIX (and potentially data installation directory) at build time, and only add the DESTDIR at install time to be able to generate a package.

**Comment by endless-sky** [comment]
Give 25f33f8 a try - that should support DESTDIR while remaining backward compatible with only using PREFIX, because DESTDIR defaults to empty.

However, that will still require both PREFIX and DESTDIR to be set at install time. So, that's still a bit different than the autotools methods where you have three separate steps, configure / make / make install, and where the prefix can be set in the configure step.

**Comment by endless-sky** [comment]
I'm hoping to have a stable 0.8.0 release by the end of July. @akien-mga, if you get a chance in the next few weeks, could you test and see whether everything is working smoothly for building an RPM package? That way if it turns out I need to make changes to the build system, I can make them in time to incorporate them in the stable release. Thanks!

**Comment by akien-mga** [comment]
> @akien-mga, if you get a chance in the next few weeks, could you test and see whether everything is working smoothly for building an RPM package? 

I've imported endless-sky in Mageia's current development version, and it works great: http://svnweb.mageia.org/packages/cauldron/endless-sky/current/SPECS/endless-sky.spec?view=markup
As you can see on the spec script, I didn't have to use anything fishy to get it to compile:
```%scons``` just corresponds to ```scons -j<nb of CPU nodes>``` and ```%scons_install``` is ```scons install DESTDIR=%{buildroot}```, so it all works great.

Closing as fixed :)
