### ISSUE TITLE
Feature Request: Comparing

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#240]
Please add a feature where the player can compare outfits (weapon-weapon, engine-engine, ship-ship). Likely in the map menu, so that the worst of the two stats is red and the better is green. I have been confronted many times with the issue of comparing ships by switching between them in the map menu and trying to remember the stats.

**Comment by endless-sky** [comment]
I've added a comparison feature in commit c6b1d63. No color coding (which would be difficult because small is good for some attributes but bad for others, plus in many cases two outfits have very few attributes in common), but it at least makes it easier to compare:

![compare](https://cloud.githubusercontent.com/assets/11450262/11580715/238c3988-9a08-11e5-8512-b74dcab1fc01.jpg)

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
