### ISSUE TITLE
Lock player files?

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2401]
A while back, I accidentally ran two copies of ES at the same time, playing as the same pilot. I noticed once my laptop got rather warm and my fans started spinning angrily, but it would probably be good to lock player files so only one copy of ES can play as any given pilot at the same time to avoid accidentally overwriting one of the timelines followed. Thoughts?

**Comment by Bladewood** [comment]
Would this prevent players from opening the relevant save file at the same time that they are playing?

**Comment by tehhowch** [comment]
yep it would prevent that too

**Comment by Rakete1111** [comment]
Doesn't have to be, it all depends on how the lock is implemented.

Pacman (a package manager) for example, does this by creating a temporary `.lock` file (it has another name). So, if you try to run it while another instance is running, it will abort.

The same would work for ES: Create a hidden temporary file when a pilot is loaded, and when the pilot is saved, delete it. So that when a pilot is opened and the temporary exists, if means that another instance of ES is winning with the selected pilot.

**Comment by tboby** [comment]
How do you cope with a crash? You can't guarantee the lockfile will be deleted right?

**Comment by Rakete1111** [comment]
@tboby It's possible. It really depends on the crash:  If it is an exception, then RAII will delete it (if the file and exception handling were implemented properly). If a fatal error occurs, from which I one can't recover (e.g `assert`, `std::abort`), a SIGABRT signal is sent, which you can catch and then delete the file. Same for any other abnormal exits, like SIGKILL and the like.

**Comment by lheckemann** [comment]
No, SIGKILL can't be caught.

Potentially an appropriate solution would be a file lock on a temporary lock file. That would be released by the operating system on any abnormal exit, and not prevent editors from opening the file.

**Comment by zwparchman** [comment]
Can this happen if you use steam to launch the game?

**Comment by lheckemann** [comment]
Yeah, it shouldn't be possible in steam. I don't know any player base stats though.

**Comment by Rakete1111** [comment]
@Iheckemann jup, you're right. Is that a problem though? SIGKILL doesn't happen often, right?

**Comment by zwparchman** [comment]
Maybe instead of trying to lock the file the game could check to make sure the file hasn't changed since the last time it was read or written. That would solve all of the issues of unexpected overwrites without opening up weird error conditions from the game unexpectedly closing. Adding a "The file has changed. Do you want to overwrite it" prompt would make it clear to the player what is about to happen.

**Comment by endless-sky** [comment]
This really doesn't seem worth fixing. First of all, handling the lock files on all different operating systems (putting them in the particular OS's "temporary files" folder, for example) would be way too much of a hassle. And secondly, most computer users will know that if you open the same file in two different instances of a program, you risk having changes made by one instance overwrite the other.
