### ISSUE TITLE
NPC->Ship->customized stats : unexpected behaviour

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2418]
_tags: create NPCs, derelict NPC ships, derelict ship, capture mission, no crew_

In the past I had a few times problems with setting up NPC ships with the stats I wanted them to have.
Mostly resulting in the steam version (v0.9.6) to crash upon start.

Since I really want to allow a player to capture a certain ship without major casualities or requiring excessive boarding crew ("friendly takeover"), I was looking for solutions on how to set a derelict NPC with low crew, i.e. with 1 or 0 crew.

```
	npc board
		government "Test Dummy"
		personality derelict staying uninterested
		ship "Freighter" "Jackpot"
			crew 1
```
This failed over and over again for me. The freighter is disabled with 50% of the MinimumHull(), yes, but with a full crew of 4.
I also noticed that the ship did not have the name I assigned, but just an empty name.

I tested what happens if I change it to `crew 6`. It worked. The derelict ship had a crew of 6 instead of 4.
**So, while it works to increase the crew, it seemed impossible to lower the crew.**
-> first unexpected behaviour

I then created a full testsuite for me, analyzing the behaviour of the game since I did not fully understand why happened what happened and if [NPC::Load(const , Line 108](https://github.com/endless-sky/endless-sky/blob/master/source/NPC.cpp#L108) is the place to search or not.
In the end, I currently think, it is [Ship::FinishLoading() , Line 366](https://github.com/endless-sky/endless-sky/blob/master/source/Ship.cpp#L366) which caused my problems. Because the only solution I found out by trial and error was to assign a hull value too. Assigning a shields or fuel value did not help, while hull helped.
-> second unexpected behavour

Testsuite:
[testing_mission_capture_derelict_freighter.txt](https://github.com/endless-sky/endless-sky/files/925229/testing_mission_capture_derelict_freighter.txt)

**The smallest / minimum ship definition which I found out to achieve the desired instantiated ship, is:**
```
	npc
		government "Test Dummy"
		personality derelict
		ship "Freighter" "Jackpot"
			name "Jackpot"
			crew 1
			hull 100
```
- You need `ship` with 2 parameters like above, i.e. `ship "Freighter" "Jackpot"`. If you use only `"Freighter"` you create an empty/unknown ship without any attributes (no sprite, no attributes, no outfits, nothing...)
- You need to specify the name separately whenever/**IF** you use child nodes. Otherwise your ship will have an empty name.
- If you want to lower the crew below the regular crew size, you must also use `hull`.
- If you use hull, you can use any hull value. If you set a very low hull value, it will be taken, if you set a rather high hull value, it will be capped by the `IsDerelict()` condition in the `Ship::SetPersonality(const` function, which also sets shields to zero.
- If you use hull and do not specify fuel, the ship will have zero fuel.

I hope to at least help the ones who write missions, if this will not be changed.
This issue is not covered by #1763 , totally different from #2121. I did not find anything really related.

It helps me a lot since I now have finally found my way how to create delayed shipyard deliveries. I dont need delayed shipyard deliveries in my new plugin / plot I started 2 days ago, but always wanted it in my first plugin / plot.

**Comment by Tadrix** [comment]
Seems like a total mess… this should be fixed.

**Comment by KiLEdEnNis** [comment]
also, can you try to make future posts slightly less long? it's not an essay lol

**Comment by Elyssaen** [comment]
@KiLEdEnNis, I think the issue was mostly as long as it needed to be. And tl;dr warning: you're not going to like this response either!

_______________

@EndrosG, running your test suite I don't get crew 0 or 1 under these circumstances:

```
	ship "Freighter" "Jackpot"
			name "Jackpot"
			crew 1
			hull 100
```

<details>
<summary>Screenshots
</summary>

![empty_freighter1](https://cloud.githubusercontent.com/assets/23544894/25582031/00b40b3c-2e83-11e7-8bf7-765234445e4f.PNG)

![empty_freighter2](https://cloud.githubusercontent.com/assets/23544894/25581932/88b1e244-2e82-11e7-9f77-4bfbece3860e.PNG)
</details>
<br />

Think something might have changed? Does it still work for you in the latest build? I'll explain a bit below, but I don't think this should have worked in any build after 28 Oct 2016, specifically commit 2f6301910a9b2396f158e435996bcb218c741277.

Here's what I've been able to figure out. This is written up a little more straightforwardly than you need, but hopefully it will be a useful resource.

_______________

### Ship model, name and setting up as a variant
1. If you want a ship that **is stock**, there must be no indented lines (called 'child nodes') after the ship. The first term after the word `ship` has to be an existing ship model in the game, e.g., `"Autumn Leaf"`. If you include a second term after the word `ship`, it will become the ship name, e.g., `"Mistral Breeze"`. Everything about the ship will be stock, including the stock crew calculation.

2. If you want a ship that **isn't** stock, you must have at least one indented line after the word `ship`. If at least one indented line is found, the entire NPC load process changes.

a) By default now, you need to entire a _full_ ship specification in the indented lines. Anything you miss, like sprite, the ship won't have.
b) The first term after the word `ship` is the model of the ship. You can actually make this entirely custom, e.g., "Endrosinator". But if you want to base this ship on an existing one, give the name of an existing ship model: "Freighter", and follow along to c).
c) If there is a second term after the word `ship`, it will **not** be read in as the name of that particular ship. All the game does is this: if there is a second term, it recognises that you are specifying a _variant_, and will look up the model name and set up default specifications. The second term itself doesn't appear: it's an internal flag, like `Hurricane (Tough)`. In your case, rather than writing `ship "Freighter" "Jackpot"`, it's clearer if you write `ship "Freighter" "Freighter (Mission Variant)"`.

_______________

### Lowering the crew of a variant

Your crew value is being read in, but it's hitting two different problems.

#### Ships without a saved hull state are recharged in Ship::FinishLoading.
```
	// Recharge, but don't recharge crew or fuel if not in the parent's system.
	// Do not recharge if this ship's starting state was saved.
	if(!hull)
	{
		shared_ptr<const Ship> parent = GetParent();
		Recharge(!parent || currentSystem == parent->currentSystem);
	}
```

Were it just for this, setting a hull value would fix it, but that's not sufficient on my build and I think it's because of an exploit patched in 2f6301910a9b2396f158e435996bcb218c741277, which adds an extra step in Engine::Place:

```
// Avoid the exploit where the player can wear down an NPC's
// crew by attrition over the course of many days.
ship->AddCrew(max(0, ship->RequiredCrew() - ship->Crew()));
```

You can escape this by changing the required crew of your ship, but a player that captures that ship will enjoy the lower required crew, and if you set it to 0 the player won't be able to fly it as it will be classified as an automaton<sup>[unverified]</sup>.

Since this isn't ideal, I've put up a proposed fix here: [fix/DerelictCrewFix](https://github.com/Elyssaen/endless-sky/tree/fix/DerelictCrewFix) and made a PR #2469.

**Comment by MessyMix** [comment]
I would have to agree with Kile, but not because there's too much information. Instead, they are confusing and hard to follow. Long posts like these, especially with unhelpful titles and no overview / introduction to the problem, make it unclear about what the issue really is.

Here's how I would structure this issue: I would split it into 2 issues, since there are 2 issues at hand.
Title 1: Cannot set derelict npc crew below minimum requirements
Intro: I tried setting a freighter's crew to 1 person, but the game loads with the entire minimum crew complement of 4 members.
[insert details now]

Title 2: Unnecessary information must be specified in npc definition
Intro: To make an npc ship spawn, you need to specify the crew and the hull of the ship... etc. etc.
[insert details now]

That's how I would have structured the two issues if I were writing them.

**Comment by EndrosG** [comment]
Short reply on the first part (will read the rest for sure):
It happend to me only with 2017 builds as I upgraded to v0.9.6 before playing again, and this issue happened to me with v0.9.6+ (self compiled).
I will test it again with a latest build soon, but for that I at least have to grab those again and either kick some of my plugins which use not-yet-merged features, or do something else.

Important: For me, a derelict ship did not automatically replenish it's crew.

I dont know if any of the changes of the last 3 days changed something, but I encountered this 14 days ago with a recent build of that time.

**Comment by Elyssaen** [comment]
@EndrosG, I wonder if something you were doing was escaping Engine::Place, but I can't think how.

Running a circles a little on my last point, finding a way to _not_ require a specified hull to have your crew spec stick. The problems are:

1. NPC::Load runs ship->FinishLoading before it runs ship->SetPersonality, so FinishLoading doesn't know the ship's personality.
2. SetPersonality does manually set the hull of a derelict ship, so it _would_ play nice with the if(!hull) condition so long as it was run before FinishLoading (we _have_ a saved 'starting state', you just haven't read it yet!), however...
3. If we just switch the order, SetPersonality will throw another problem: it enforces `hull = min(hull, .5 * MinimumHull())`, but `hull` is still the initial value of 0 before FinishLoading runs Recharge... so SetPersonality won't work before Recharge, and Recharge won't work before SetPersonality.

There are a _lot_ of ways around this, but no clear 'best' has come to me yet... not without intimate knowledge of the entire code base. I'd be hesitant to muck with Recharge as it's used elsewhere, passing the `personality` object into FinishLoading so it can use it before SetPersonality is run is bad coding, combining FinishLoading and GetPersonality could have all manner of consequences... yep, this is going to need some more thought.

**Comment by EndrosG** [comment]
Okay, I have to admit that I obviously missed to test something. That's really ashaming now.

I remember that intensively checked the save game files of the instantiated mission but it looks like I didnt really capture those ships then, otherwise I would have noticed the `AddCrew` effect.
In the save's, the ship becomes instantiated with 1 crew... but than that AddCrew-upon-takeoff comes in place... :-(

I know that I have another solution content-wise to address that, but I didnt want to go that way because it's not that "nice".
Instead of changing crew assets (and I will definetively not change the required crew, since the player is meant to keep the ship!) there is the option to define a Hand-to-Hand weapon with negative stats. Since most ships dont have any H2H outfits, the crew will take the "negative" H2H outfit, because it is still the "best" available one.
The bad thing is, I will need to specify a full outfits list for the ship in that case, since there is no `add outfits` syntax for variants.

And yes, you're right, it reads better if I change the 2nd phrase after `ship` to a "real variant name".
When I wrote this issue, I somehow didnt have in mind that this would/could define a variant with that name.

--------------------------------

**So, my short term solution is:**
1. define a negative H2H outfit (-0.999 attack, -1.999 defense)
2. add a proper number of H2H outfits to the ship in question

**My long term solution is:**
+ Add a `surrender-on-capture` personality -- not: surrender-when-boarded - the player still has to click `attempt capture` and eventually (not sure yet) also `attack`.
+ This `surrender-on-capture` personality will involve that the crew stays alive and the players flagship does not need to transfer any crew.

Note @Elyssaen : You might want to consider the latter one when you implement the ship->tag->captured feature, making a difference between bloody capture and capture-by-surrender.

**Comment by Elyssaen** [comment]
Oh, _of course_. Some way of escaping Engine::Place... yep, looking at the save files rather than launching the game would do it! I'm glad that mystery is solved, and no shame to be felt. You were completely logical, you just didn't know about the exploit patch.

As to a negative hand-to-hand outfit, I admire the cunning, but you're right that it's not "nice". Right now I think the state is:

1. If my PR is accepted, your solution (hard-coding a hull) will work.
2. If we can work out a second PR, we can make it so you don't need to hard-code a hull to get it to work, so long as the ship is derelict.

A `surrendering `personality (probably the more consistent way of writing it in the data files) would be interesting. I have some ideas about that, but let's save that for another topic?
