### ISSUE TITLE
'Beta' sounds like a bad joke

### ISSUE THREAD

**Issue by xiamaz** [endless-sky/endless-sky#2419]
Currently as part of the wanderer mission, as part of the Wanderer Start mission line, Elias affiliation as a 'Beta' will be assumed in a dialogue.

Somehow... this seemed very clunky in comparison to the rest of the current storyline. Since 'Alpha' and 'Beta' are generally used in some contexts to describe dominant and submissive behavior, this seems like a fitting naming convention. But mostly through the more colloquial usage of these terms, this can seem like a bad attempt at a joke.

1. Add an incredulous player response 
2. Remove any naming references to 'Beta', which seems fine for the general development of the story afterwards

This is an incredibly petty issue, but it somehow breaks a lot of immersion at least for me.

**Comment by KiLEdEnNis** [comment]
I really don't see an issue: Alpha is dominant and wants to control humanity etc. while Beta is "submissive" to the humans and serves them

**Comment by SirStigII** [comment]
Eh I kinda like it, alpha's being a-holes seems to be a constant throughout time and space.

Not to mention experiment A and experiment B would naturally use greek letters, as all human science uses that standard.

**Comment by Tadrix** [comment]
Actually, omega is submissive to everyone. Beta's an alpha's sidekick.
https://en.wikipedia.org/wiki/Alpha_(ethology)

**Comment by MessyMix** [comment]
@Tadrix while that is true, an in-game Beta shouldn't be called an Omega, because they are not just submissive, nor are they polar opposites of an Alpha. They are simply a modified Alpha which do not have tendencies to "master all". I think the name "Beta" is more fitting than Omega.

**Comment by endless-sky** [comment]
The names were chosen quite intentionally. In sociological terms, "alpha" means the dominant animal in a pack, which is how the Alphas view themselves. But in technological terms, an "alpha" is a flawed and incomplete early implementation of a new idea, and a "beta" is what comes after the alpha version once you've had time to work out some of the bugs.

The Alphas were designed to be strong and self-sufficient warriors. But the characteristics that make humanity so successful in evolutionary terms are traits like empathy and altruism that make individuals "weaker" but enable stronger communities. Ever since the development of language, agriculture, simple machines, domestication of animals, etc., cultural evolution has played a much more dominant role for us than biological evolution. So a species that is incapable of forming communities cannot hope to compete with us regardless of how powerful or intelligent individual members of that species are. The Betas were created by someone who realized that.

(Incidentally, in case you haven't learned this yet, you should never trust what NPCs in the game tell you, because most of them have no clue what they're talking about, and the ones that do generally have strong incentives to lie to you. So what the officers say about Elias should be taken with a grain of salt.)

**Comment by KiLEdEnNis** [comment]
> Actually, omega is submissive to everyone. Beta's an alpha's sidekick.

don't spoil future content please :)
