### ISSUE TITLE
Converting EVN to an Endless Sky plugin

### ISSUE THREAD

**Issue by eli-lumos** [endless-sky/endless-sky#242]
Hi. Not sure if there's a better place to put this. Is there?

I started writing a bunch of node.js scripts to convert all the EVN data into Endless Sky plugin data. So far I only have outfits done and weapons partially done. But, I have all the data exported and dumped into useable files and a massive 250k line JSON file. So it should be easy for anyone to jump in to help. 

Would be cool if collaborators would join in.

https://github.com/eli-lumos/EVNToEndlessSky

**Comment by endless-sky** [comment]
So, obviously I'm a fan of EV, and I think it would be awesome if the EV games became available in an open format like this, for a new generation to explore and enjoy.

But, the text and images in the game are copyrighted by Ambrosia. You *might* be able to argue that providing the means to extract those resources from a free download that Ambrosia provides is not copyright infringement. But, posting that actual text and images on Github for other people to download almost certainly infringes their copyright and goes beyond what "fair use" law allows.

Ambrosia still sells EVN, so unless they decide to open source the game (which they have done in the past, e.g. with Maelstrom), you should really buy it from them if you want to play it. I hate to say that because it's clear you've done a lot of work on this and it'd be cool if EVN *were* an ES plugin. But, think about what's fair to the folks at Ambrosia who put so much work into the EV series.

**Comment by eli-lumos** [comment]
I'm actually in agreement with you. Currently the data dumps are in my Github repo for convenience, but I plan on removing them whenever everything is done. Then I'll leave the repo so that it has a single script you can run on EVNova.app to have your very own Endless Sky plugin. Basically an avenue for people like me who enjoy the modernity of ES and want to run EVN in it. And then maybe some person will post the plugin on a torrent or something, but I wouldn't have anything to do with that.

For now, I'm certainly in a legal gray (or maybe black) area by having the data dumps inside the repo, but it's the only real way to get collaborators to join me, so I've done it. If someone from Ambrosia contacts me I'll remove them and just keep updating the scripts.

I really wonder how much money EVN can be making now. They seem to not care about it, given that it has been on sale for $30 since 2002 with no sales, isn't on steam or iOS, or anything else that could translate to a giant payday. In the absence of their movement, people like me are going to do stuff like this.

**Comment by Pointedstick** [comment]
EV Nova also doesn't work at all on OS X 10.11. Crashes on launch.

**Comment by eli-lumos** [comment]
Then you should contribute to this project! The more people working on it, the faster you can run a script on EVN.app and have everything going in Endless Sky.

**Comment by naehc** [comment]
Pointedstick: a fix for that issue is available, https://dl.dropboxusercontent.com/u/522679/ev/index.html (El Capitan fix, at the top). Nova works fine in 10.11 after it's applied.

**Comment by Pointedstick** [comment]
Holy moly, that's awesome! Also, The Frozen Heart for Nova?! Whoa!

**Comment by schrauger** [comment]
Would the script work for user-created EV/EVO/EVN plugins? Those wouldn't be owned by Ambrosia, and they are free. Being able to use those plugins in this game would instantly make the project more attractive. Many plugins have awesome stories.

**Comment by eli-lumos** [comment]
Yes, it SHOULD. And that's part of the goal. Porting Frozen Heart or something would be great. Right now it's necessary to create some JSON with manual data... theoretically you could eliminate those with more effort.
