### ISSUE TITLE
feature: a new preference where escorts kill enemies

### ISSUE THREAD

**Issue by Lorantine** [endless-sky/endless-sky#2424]
searched a few times for a duplicate & didn't see one
basically: escorts always try to disable ships, and personally I want my enemies dead, so I always have to press B for nearby disabled enemies, then press F for my escorts to kill them as soon as they disabled it
should have asked several weeks before but got around to do it now

it could be a preference just like ammo usage: toggle between "disable" and "destroy", and maybe even add a key where you can toggle it mid-flight

**Comment by EndrosG** [comment]
2nd thought: This could be a nice feature when you decide to join the pirates.

1st thought (not speaking against it): Why do you want them killed in the first place? No capture, no plunder? Is it because of large scale battles where those disabled ships become just obstacles?

In the early months of gameplay I am very happy about every disabled ship. Having the Republic Navy often kill the ships I just disabled and almost boarded can frustrate.

**Comment by gunqqer** [comment]
There are a lot of missions that require the ships to be killed. Case and point the Automata invasion of human space. I had to go through each system twice to get them all. First time was easy. The next time it wasn't because all the markers vanished. If my escorts had just killed them all it would have been less of a problem

**Comment by KiLEdEnNis** [comment]
plus for example you are doing a tribute & ya wanna finish off all those annoying drones & fighters

**Comment by EndrosG** [comment]
Captains question: if my orders [as captain of an escort ship] were to kill the enemies and not just disabling them, what would you expect from me?
1. Disable all first, and one all are disabled, kill them
2. Immediately kill them before picking up the next target

@gunqqer : capturing counts as killing too. I prefer to try to capture first ;-)

**Comment by KiLEdEnNis** [comment]
immediately killing them
why would you disable them to kill them later

**Comment by MessyMix** [comment]
because it takes precious time, and there can be other enemies shooting at you while you try and kill a disabled ship, which is useless anyways, which makes this feature a massive timewasting detriment?
