### ISSUE TITLE
possible net worth calculation error

### ISSUE THREAD

**Issue by lordofruin** [endless-sky/endless-sky#2437]
My fleet consists of 6xBounder valued at 1.474m and 2xScout valued at 516,397. My Cash balance is 10.417M

By my calculations, this makes me worth 20.293(794)M credits.

However the Player info screen (accessed via 'i') shows net worth to be 17.330M credits.

This may be a legacy issue - I never bothered to check pre-depreciation (which, imho, works well, although looting is now pointless with the death of death taxes). 

System/Release - Ubuntu 16.04 fully updated and dist-upgraded - ES is from ppa and on latest stable release - last update/dist-upgrade performed on 20/04/2017

**Comment by EndrosG** [comment]
Are you *sure* that each of your Bounders is equally worth 1.474m ?
To me it looks like:
1 Bounder is valued 1.474m and the others have lower value due to different depreciation rations.

You can go to a shipyard and select either your two scouts and selling them, or do the same for all six bounders together.  The shipyard will display a confirm dialog before you finally sell, so this is a safe thing as long as you dont confirm in the end.

The story is simple: In 6 weeks, you buy 1 Bounder on every monday. On Friday you check the values and you get displayed the value of the newest Bounder only. Because if you would sell any Bounder, the game would sell (pricing-wise) your newest Bounder. The 2nd newest has already a lower worth... But that one you will not see in the game before you finally sell the first one.

**Comment by KiLEdEnNis** [comment]
I think I know the issue
you select whatever for example Bounder, but it shows the price you'd sell it for, grabbing the least deprecated outfits from possible other ships
this means that all Bounders are displayed as 1.474m, but if you'd sell one, all other Bounders would be shown as being worth less, and if you'd sell all Bounders, you'd get les than ~8,8m

**Comment by lordofruin** [comment]
@EndrosG, @KilEdEnNis - that makes perfect sense - whichever ship I select it uses the highest value relevant loadout items from my fleet. Closing issue. Thanks.
