### ISSUE TITLE
Shipyard/Outfitter GPU usage

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#2442]
I have some 150-odd ships. This is fine most of the time (e.g. in space, including in big battles), but causes a huge amount of GPU usage and heat when I enter the shipyard or outfitter panels with the ships present, to the extent that it crashed my whole system the first time I encountered it.

**Comment by Bladewood** [comment]
what the hell kind of computer are you using

**Comment by lheckemann** [comment]
Intel integrated graphics, on a "Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz"

The crash is presumably a driver issue, but the performance problems shouldn't be.

**Comment by jafdy** [comment]
Try updating the drivers. I know it seems obvious but it's a good idea to start with the obvious.

**Comment by EndrosG** [comment]
I would think it's the driver or so...
I have some 400 ships parked on a planet and I have no problems in neither shipyard nor outitter.
Memory consumption of the game is low too (no changes at all).
And my system is rather "weak". A low budget Asrock Q1900M mainboard ("Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz").
On my netbook I dont have any issues with the shipyard or outiftter either.
But I can't really bother to fly with that many ships since all those engine sprites require a lot of computation on

**Comment by lheckemann** [comment]
>Try updating the drivers

I'm on linux and already running the latest kernel available in my distro.

**Comment by lheckemann** [comment]
Tested on linux 4.9.22 and linux 4.10.10, both with ES 0.9.4 and latest master, could reproduce issue on all 4 combinations. Interestingly, it only occurs when the panel with the ship outlines is visible: if I make the window smaller vertically and scroll to the bottom so only the selected ship's stats are visible, GPU usage drops to normal levels.

**Comment by gunqqer** [comment]
400 ships? Wtf guys do you never sell any of your old ships?

**Comment by EndrosG** [comment]
> cat /proc/version 
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03)

No issues here. Using Steam version 0.9.6 as well as latest master.
@gunqqer : I sell ships, of course. But during operation freedom (FW campain, war FW vs. Rep.) I captured hundreds of their ships, including 100+ cruisers and a ton of carriers. I dont want to sell these capital ships... I rather park them (to save the salaries).
When I was playing the FW campaign 1 year ago, I was playing the safe way. Since I did not know what fleet I might need in the future, I kept the strongest ships. I even harmonized their outfits, lol...
I didnt even use them against the Sestor or Mereti :-/

**Comment by KiLEdEnNis** [comment]
the game isn't meant to have several hundreds of ships active so ofc ya lag a bit

**Comment by lheckemann** [comment]
It seems odd though that rendering the ship's static outlines should blow stuff up while rendering the ship's actual sprites, running their AI, and rendering projectiles fired by them doesn't.

**Comment by KiLEdEnNis** [comment]
I think because ships are more than a projectile anyway: a projectile just has a small sprite and outline to check if it collides at all
ships are way bigger, have hardpoints, more stats, actual hull and shield strength etc.

**Comment by Alkallid** [comment]
Projectiles can also have drag, lifetime, effects, homing, and submunitions to add.

**Comment by KiLEdEnNis** [comment]
still, ships are bigger and have more stats, they would take up more GPU
I think MZ planned to make a more efficient AI system though

**Comment by Alkallid** [comment]
One ship to around a dozen projectiles spawned every few seconds, or more.

**Comment by KiLEdEnNis** [comment]
should be about equal depending on the ship size, since projectiles only track a bit, ships have the AI too

**Comment by endless-sky** [comment]
Drawing the ship outlines is much more computationally expensive than drawing their sprites, because the outline shader is performing a [sobel filter](https://en.wikipedia.org/wiki/Sobel_operator) on them, as well as a 3x3 subsampling operation. It's also the only shader in the game that performs a square root, which might be slow if your driver or your iGPU doesn't support it natively.

Note that I'm doing my development work on an i3-2100 on Linux, and I don't see any issues like this.

If you're compiling from source, try changing line 79 of OutlineShader.cpp from this:

```C
        "  finalColor = color * sqrt(sum / 144);\n"
```

to this:

```C
        "  sum = 1 - sum / 144;\n"
        "  finalColor = color * (1 - sum * sum);\n"
```

If that fixes the slowdown, it would be a sign that the square root was the issue.

**Comment by lheckemann** [comment]
>Note that I'm doing my development work on an i3-2100 on Linux, and I don't see any issues like this.

That's odd, given that they're from the same generation but mine is supposedly more powerful...

That change didn't fix the slowdown, and it managed to crash everything again :/

I also tried removing the calls to `OutlineShader::draw` in `ShopPanel.cpp`. That did fix the issue (at the cost of the ship outlines in the outfitter and ship panels of course), so it is clearly still the outline drawing that's causing the problems.

**Comment by tehhowch** [comment]
Did some profiling on this as I noticed different behavior when trying to test #3569 compared to my past experience (I had purchased a number of Bulk Freighters so I could generate an interesting screenshots for the System::Danger color PR and the Show Escort locations PR).
As of 432b9a9b94fe44e47f42951038d17e298bba39b1, after 5 minutes of wall-clock idling in the Shaula outfitter with the all-content plugin (launch game, open outfitter, tab away):
<details><summary>1 single Osprey:</summary>

[1Osprey.txt](https://github.com/endless-sky/endless-sky/files/1640987/1Osprey.txt)
![1osprey](https://user-images.githubusercontent.com/20871346/35073127-2e7cf004-fbad-11e7-9c75-b0453de0081e.png)
</details>
<details><summary>164 Osprey</summary>

[ManyOsprey.txt](https://github.com/endless-sky/endless-sky/files/1640989/ManyOsprey.txt)
![manyosprey](https://user-images.githubusercontent.com/20871346/35073140-3b8ebd90-fbad-11e7-8edd-7d542b5afe69.png)
</details>
The call frequency shows a huge slowdown in stepped frames, from 18149 (~60 fps) to just 4962 (~16 fps). While tabbed away in the large-ship test case, I noticed significant UI delay in the active application.
Following @lheckemann 's lead, I disabled the two calls to OutlineShader and repeated the test:
<details><summary>164 Osprey, no outlines</summary>

[164Osprey_NoOutline.txt](https://github.com/endless-sky/endless-sky/files/1641035/164Osprey_NoOutline.txt)
![164osprey_nooutline](https://user-images.githubusercontent.com/20871346/35073619-6a577548-fbaf-11e7-8339-191ecf5fc604.png)
</details>
The fan was still running in the no-outline case, but unlike the case when using outlines, was not running at maximum speed (and was back up to 60 fps). No graphical hiccups were observed in other applications while the 5 minute test was running, unlike the case with outlines.

I then went and made the suggested changes to OutlineShader, removing the square root from line 106, and repeated the test. Graphical hiccups returned in the active application while the test was running, though it did seem the fan was not quite as active. Framerate again dropped to ~16-18.
<details><summary>164 Ospreys, outlines, no sqrt</summary>

[164Osprey_NoSqrt.txt](https://github.com/endless-sky/endless-sky/files/1641057/164Osprey_NoSqrt.txt)
![164osprey_nosqrt](https://user-images.githubusercontent.com/20871346/35073946-135c8c0e-fbb1-11e7-9d95-0580922545ce.png)
</details>

**Comment by MCOfficer** [comment]
![icon_scalable_simpler](https://user-images.githubusercontent.com/22377202/52523672-23dd5300-2c94-11e9-8a3a-79ad818d6ed7.png)

I tried to convert the current icon to svg, and it's better than i expected. (Ironically, this is a png version of it, because github doesn't like svgs.) It looks a bit goofy at full size, but holds up well until ~512MB. Thoughts?

**Comment by rymeilema** [comment]
bump, please fix this

**Comment by Amazinite** [comment]
I've provided a workaround with https://github.com/endless-sky/endless-sky/pull/5179, allowing you to either choose to use the sobel filter outlines, or switch to only using the normal sprites of the ships. Choosing the normal sprites should yield a boost in performance over the sobel filter outlines for large fleets.

**Comment by tux2603** [comment]
If nothing else, you could just add a "thumbnail" type pre-rendered image that shows the outline of the ship. It should be pretty simple to generate a cached texture though--I remember doing something like that when I took a computer graphics class a few years back
