### ISSUE TITLE
enhancement for missions: allow `require` in `to *` 

### ISSUE THREAD

**Issue by EndrosG** [endless-sky/endless-sky#2494]
As of now, the `require <outfit>` special condition can only be used in any `on` mission action.
During a longer conversation outside of this Git, it became clear that:
- `require <outfit>` should be available in the `to` sections of a mission. `to offer` and `to fail` are the most relevant ones.
  - `to offer` is the place where it would usually (logic wise) belong to instead of `on offer`.
  - `to fail` will allow a mission to fail if the player acquiers an outfit after the mission was accepted (i.e. while it is active)

Furthermore, it would be desirable, to allow the `require` construct to accept a number. This is not possible with the current implementation though. For numbers greater than zero, this would mean, that the player should have *at least* `<n>` units. For `<n> <= 0` it would require the player to *not have* any units (ideally accross all ships) - thinking of something "illegal" or "not liked on planet xy" here.

Furthermore, it might be desirable, to extend this from outfits to cargo in general.

**Comment by Elyssaen** [comment]
Just to explain the latter two – `require cargo` and `require <outfit> <count>`:

#### Requiring cargo

A development along these lines could start to open up the possibility for source-and-return missions. Particularly, since custom cargo types can be defined inside a mission spec, you could do things like create a mission to recover some war plans from a disabled ally... where you could betray your side and give them to the enemy instead. Doing this, as long as those war plans are cargo, is going to need some way for missions to check if you have particular cargo on you.

#### Require any number

So, my OutfitTags to some extent manages this need, but it's not identical. Particularly useful to me at the moment would be `require <outfit> 0`, i.e., requiring you _don't_ have any of a particular outfit. But `require <outfit> 2` (you have at least 2) would be useful too.

**Comment by EndrosG** [comment]
And your OutfitTags probably wont handle the case when the outfit is not "installed" but "in cargo".

**Comment by Elyssaen** [comment]
Yep, it won't. Tags are like attributes, and you don't get the attributes of an outfit that's in your cargo.

**Comment by endless-sky** [comment]
The "<mission>: active" condition can already be used to implement your "require cargo" request, because special cargo is always tied to an active mission. (For example, that's how the mission works where you are searched while carrying Katya's cargo.)

**Comment by tehhowch** [comment]
Is the first part of this (checking `require` in a `to offer`) as simple as running a CanBeDone on the MissionAction?

**Comment by tehhowch** [comment]
Given the restrictions imposed by the ConditionSet class, even with the enhancements of #3128, allowing `require` in the `to *` seems to either require changing the toOffer, toFail, toComplete variables from pure ConditionSets into a new class, extending ConditionSets beyond testing conditions, or as @Elyssaen mentions, use some other enhancements that allow storing outfit attributes in the player's conditions.

**Comment by endless-sky** [comment]
Addressed by merging #2496.

**Comment by tehhowch** [comment]
`require` and `outfit` are still only usable from the `MissionAction`s "on ______" and not the blocks created by "to ______"

**Comment by Zitchas** [comment]
This lack of being able to use `require` and `outfit` in `to fail` and `to complete` are continuing to be obstacles for missions.

Worth noting that as best I can tell, players can currently have a luxury accommodations, take a bunch of luxury jobs, then sell the luxury accommodations and the passengers don't complain that they just got downgraded to economy class. (haven't tested it, but that's the way things look).

The luxury jobs are one category of jobs that should have a `to fail` clause that if the player doesn't have any luxury accommodations, the job fails. Because rich people paying for luxury transport aren't going to tolerate being dumped in economy class for a chunk of their trip.

On the other hand, the Astral investigation mission (from Remnant Expanded Horizons Astral) shouldn't *fail* if the player doesn't have the research lab, but they shouldn't be able to trigger the waypoint, nor complete the mission, if they don't have one.

I initially wrote those missions with
```
	to complete
		require "Research Laboratory" >= 1
	to fail
		has "Research Laboratory" == 0
```
But Amazinite has informed me that this isn't a thing, yet.

**Comment by Amazinite** [comment]
Being honest, we could brute force this (and similar issues) pretty easily. For Player::UpdateAutoConditions, just throw more stuff in the conditions. We wouldn't only create conditions for the ship categories that the player has, but also the outfits on each ship. The condition could then be `"outfit: <outfit name>"`. (Similarly, we could create conditions for the visited planets and systems.) While this would get us the desired effect, the downside here is the duplication of information. The outfits on your ship are already saved in your ship definitions, and the visited systems and planets are already saved elsewhere in the file, so creating actual conditions for these means that this information is effectively saved in two spots in your save file. 

On one hand, we could say that this isn't the best solution and we should instead have ConditionSet have some way of accessing this information from where it already exists.

On the other hand, we actually already do this. The player's reputation is duplicated. The player's credits and credit score are duplicated. The year, month, and day are duplicated. The player's planet and system are duplicated. The only difference between those instances of duplicating information into the conditions and the suggestion I've made to "brute forcing" this is the scale; saving each individual outfit (or visited planet/system) is a lot more information than those conditions that are already duplicate information.

**Comment by petervdmeer** [comment]
> Being honest, we could brute force this (and similar issues) pretty easily. For Player::UpdateAutoConditions, just throw more stuff in the conditions. We wouldn't only create conditions for the ship categories that the player has, but also the outfits on each ship.

I would prefer to completely remove Player::UpdateAutoConditions(), remove all duplicates, and extend the Conditions-retrieval code to also access non-condition data indirectly by using the right keywords (and I filed #5017 with exactly this goal in mind).

> The condition could then be `"outfit: <outfit name>"`. (Similarly, we could create conditions for the visited planets and systems.)

I already mentioned access to the visited planets and systems as option in #5017, access to owned Outfits (and Outfits locally for sale) is also a nice option to be added there.

> While this would get us the desired effect, the downside here is the duplication of information.

#5017 is created aiming at the same desired effect, but without any data duplication (and with the information always being up-to-date). Note that auto-generated conditions will require the keywords for accessing the data to be well-structured (for performance reasons).

> The outfits on your ship are already saved in your ship definitions, and the visited systems and planets are already saved elsewhere in the file, so creating actual conditions for these means that this information is effectively saved in two spots in your save file.

The idea behind #5017 does not care about save-files, it takes the data directly from the relevant data-structures. And the idea of #5017 is to not save the auto-generated conditions as conditions, but to only save the auto-generated data in their original data-structures (as they are saved today) and only save the manually set conditions as actual conditions.

> On one hand, we could say that this isn't the best solution and we should instead have ConditionSet have some way of accessing this information from where it already exists.

Yes, some implementation ideas for #5017 are in #5244 and in #5384. Tehhowch asked me to implement a custom Iterator to get this going further. Please feel free to contribute to it if you want.

> On the other hand, we actually already do this. The player's reputation is duplicated. The player's credits and credit score are duplicated. The year, month, and day are duplicated. The player's planet and system are duplicated.

I plan to have all this duplication removed when #5017 is done.

> The only difference between those instances of duplicating information into the conditions and the suggestion I've made to "brute forcing" this is the scale; saving each individual outfit (or visited planet/system) is a lot more information than those conditions that are already duplicate information.

There are two scaling reasons of why I didn't want to go for more duplication:
- The amount of data itself can become quite large.
- Some calculations will be relatively expensive (like summarizing Outfits over fleets). I would prefer to only perform those calculations when they are actually needed.

Another reason that I didn't want to duplicate is that the duplicate data can be outdated if Player::UpdateAutoConditions() is not called often enough.
