### ISSUE TITLE
Tie the date conditions to the actual in game date

### ISSUE THREAD

**Issue by TheUnfetteredOne** [endless-sky/endless-sky#2511]
That is, editting day, month, or year in a mission with something like day += 7 would advance the game 7 days (or even allow you to set time back).

**Comment by Elyssaen** [comment]
Missions doing time jumps could be really useful. It'd need to run IncrementDate, probably a multi-day version so it wouldn't report your salary over and over.

Not sure what setting time back would/should do to events.

**Comment by Amazinite** [comment]
If this is going to happen then we would probably have to have each event (and even each mission) record the game date it was added to your save file. If you go back in time before the date of an event then that event either has its effects on the game deactivated or just completely removed from your save.

**Comment by Elyssaen** [comment]
@Amazinite, kind of a nightmare, isn't it? I'm not sure going back in time would ever be a good idea.

But adding the game date to each event might be really useful anyway.

**Comment by tehhowch** [comment]
Logging the game date should be done, at a minimum, such that entries in the yet-to-come "Captain's Log" are dated.

**Comment by tehhowch** [comment]
I think forward time travel is the only feasible part of this... Backward travel would (logically) require the game to remember where your original you was, what missions you had active then, what NPCs were active (and get them to follow original you instead of real you), the outfits and fleet associated with original you (and what about real you's fleet? Did they come with or just everyone in the flagship?)
Or is hypothetical backward travel more like "everyone gets back into their body, wherever that was on the date we traveled to"?

Backward travel is really complicated and the desired implementation varies with personal preference. Forward travel could simply be addressed in the "on *" blocks, and call increment/set date as needed. Those functions would need to consider their arguments to determine if any fleet placement should occur or if just the player/mission items.

Forward=doable
Backward=nightmare

**Comment by Elyssaen** [comment]
Someone on Discord was working on this, last I heard. Not sure if he still is.

**Comment by endless-sky** [comment]
Given all the things that would have to be updated (mission deadlines, events, salaries, etc.) and the limited usefulness, this just doesn't seem worthwhile.
