### ISSUE TITLE
Endless Sky not running on Windows 10 v1073 ("Creator's Update")

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#2520]
I got the update at midnight. The next day, I tried to run Endless Sky.
It didn't work.

Some other users share my predicament.

- http://steamcommunity.com/app/404410/discussions/0/1319962514592049375/
> After Windows updated to 1703, Endless Sky would silently crash every time I tried to start it. Checking the event logs revealed a fault in the 32-bit ntdll.dll

- http://steamcommunity.com/app/404410/discussions/1/2741975115067400334/
I am not using an Nvidia card, I have Intel integrated graphics.

- http://steamcommunity.com/app/404410/discussions/1/1319961618834604503/
This user seems to have the same problem, though it does not have as much detail to confirm it. I will note something that was said, which applies to me as well:
> The game would still occasionally launch, but still won't launch on the first try.

It does appear in Task Manager, but closes about ten seconds later.

The only workaround, it seems, is to enable compatibility mode, but I fear for the Common User.

**Comment by endless-sky** [comment]
Have you tried both the 32-bit version and the 64-bit version?

I don't have a Windows 10 machine, so I have no easy way to debug this.

**Comment by Bladewood** [comment]
It took a while for me to download a copy of the 32-bit 0.9.6 executable (my compiler does not support 32-bit for some reason). I accidentally downloaded the 64-bit version the first time, and I can confirm that that does not work.
Interestingly, the 32-bit version seems to work every time.

**Comment by Amazinite** [comment]
It's running fine for me, and I did update my Windows verion. Could it be only a problem with the current stable version?

**Comment by Bladewood** [comment]
This is a source build I'm running.

**Comment by utoxin** [comment]
Running the Steam version, and having this issue as well.

**Comment by tehhowch** [comment]
On a machine which just got upgraded to Win10 v1703, I am able to run the precompiled 64-bit binary with a text-only plugin. I don't have Steam available to test if that binary works as expected.

I have **not** enabled any compability mode settings.
CPU: i7-3770 4x @ 3.40 GHz
RAM: 16 gb
OptiPlex 7010
Win10x64 Pro version 10.0.15063
AMD Radeon HD 7500

So I'm curious if this and #2605  still persist, or if they've been silently fixed by MS through updates to other parts of the OS

**Comment by Marsfan** [comment]
Running 0.9.6 on Win 10 1703 in 64 bit works fine for me

**Comment by tehhowch** [comment]
@Marsfan if you open the properties menu for the executable, does it show any enabled compatibility modes? Also, I'm assuming you are running the binary that is distributed by Steam - is that correct?

**Comment by Marsfan** [comment]
EndlessSky.exe in my `steamapps/common/Endless Sky` folder shows no compatibility mode options enabled. Windows Resource monitor reports it is running as a 64bit platform. I cannot comment on any plugins/mods though, I installed it post Creators update, as I had to wipe my computer because I screwed up some settings. Could be only for people who downloaded it before the update.

**Comment by tehhowch** [comment]
plugins/mods do not change the binary - they are text only 👍 

Can you test if following the 1st post in #2605 changes your ability to play the game?

**Comment by Marsfan** [comment]
I will download the High DPI mod from steam, and report back.

**Comment by Marsfan** [comment]
It runs fine with the High DPI DLC downloaded from steam. I got in a ship and flew around.

**Comment by MCOfficer** [comment]
is this still a thing? i for my part never had problems on the latest windows.

**Comment by utoxin** [comment]
I'll check mine tonight when I get home.
