### ISSUE TITLE
Should hitForce and blast damage scale with distance from the blast origin?

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2529]
This topic was brought up in Discord today among @EndrosG , @Elyssaen , and myself.
If implemented, only ships which are close to the source of the push / blast  will take the full amount of damage. Others will take a scaled amount of the damage. Scaling would apply to any blast, and any damage type (e.g. ion damage taken from an EMP weapon would decrease with distance from the blast).

Refs #1630 

I am seeking feedback on the multiplicative constant used to normalize the damage: it will use the scaling approach [MZ offered](https://github.com/endless-sky/endless-sky/issues/1630#issuecomment-250055568), but will include a multiplicative constant to alter where the post-scaling damage is equal to the current damage values. A constant k = 1 means the specified weapon damage is only true at the blast center, while k = 2 means the specified weapon damage is only true when you are 1 blast radius away. K = 1.0625 means the specified weapon damage is true at 25% of the blast radius, and k = 1.25 moves it to 50%. Currently, the received damage is the specified weapon damage for all positions within the blast radius.
Possible damage scaling profiles:
<details>
  <summary>dealt = k * damage / (1+r²)</summary>

  ![image](https://cloud.githubusercontent.com/assets/20871346/26264499/aadeacc0-3ca2-11e7-8bb3-19370b055e5a.png)
</details>

<details>
  <summary>dealt = k * damage / (1+r²)²</summary>

  ![image](https://cloud.githubusercontent.com/assets/20871346/26264904/28118234-3ca4-11e7-9582-7cdb4d28a64e.png)
</details>

It is also possible to increase the effective blast radius of explosions and the like by modifying [Engine.cpp](https://github.com/endless-sky/endless-sky/blob/d92fc7e506b4e66d33674f27bed49beb5ebd4c6d/source/Engine.cpp#L1342). I would prefer not to increase this value (as that rapidly increases the area spent checking for collisions). In other words, the implemented damage profiles would be as above, from 0..1, and not extending to 1.5. I show that extra bit to indicate what the damage profile could look like if we choose to give a bit of extra distance to the blast radius to compensate for making the explosions weaker.

**Comment by Elyssaen** [comment]
Nice graphing. : ) I'm not sure how obvious it is what you're saying to someone just coming into this, especially if they haven't read #1630.

So to confirm:

1. The topic is having damage (and hit force) from a blast fall off with distance.
2. MZ has suggested a curve that would work, and you're looking to implement it.
3. Your main question is: should the damage values of existing weapons be what you get at zero range, maximum range, or something inbetween?

Is that right?

**Comment by Elyssaen** [comment]
The geek in me says you want the specified weapon damage at 70.7% (100%/√2) of the blast radius, which is _k_ = 1.5. If you're as likely to be anywhere in the blast radius, this is a ship's average distance from a blast, I think. This would keep ship explosions on average the same, though a 'ground zero' ship explosion will do 50% more damage and one right at the cusp will do 25% less.

The advantage here is that of 135 blast radius values in the game, 128 of them are ships. Skip the Drak Antimatter Cannon actually appearing twice, and that leaves:

1. Drak Antimatter Cannon – no trigger, direct target will take 'ground zero' damage.
2. Korath Detainer – ditto.
3. Pug Gridfire Turret – ditto.
4. Timer Weapon – ditto.
5. Heavy Rocket – trigger at 30, blast out to 50, so 60% range.
6. Nuclear Missile – trigger at 30, blast out to 150, so 20% range.

You then just need to tweak 1-4 to scale their damage down by 33%, Heavy Rockets by 10%, and Nuclear Missiles by 30%, and the average damage at most-likely-range will retained across the board.

**Comment by EndrosG** [comment]
Just a few small comments:
Having the same damages as of now (status quo) at 25% of the blast radius in the new setting is what my first guess would be too, if we were to apply any correction factor. I will, in the end, provide arguments why we should stay at `k = 1`.

Now, for all people who are not that good at maths, we probably should say the implications of that at some other distances. Most importantly, the maximum damage received, i.e. directly at the blast origin, and the minimum damage received, i.e. at a distance equal to the blast radius. And then, probably, also provide the data for 50% and 75% for the sake of completeness.

referring to the orignal post:
damage profile 1: `dealt = k * damage / (1+r²)`
damage profile 2: `dealt = k * damage / (1+r²)²`

k's of interest:
1.0 for both damage profiles, i.e. no damage modification
1.0625 for damage profile 1
1.0625² = 1,12890625 for damage profile 2

distance | profile 1, k = 1 | profile 1, k = 1.0625 | profile 2, k = 1 | profile 2, k = 1.0625²
----------|-----------|-----------|---------------|------------------
0% | 100.00% | 106.25% | 100.00% | 112.89%
25% | 94.12% | 100.00% | 88.58% | 100.00%
50% | 80.00% | 85.00% | 64.00% | 72.25%
75% | 64.00% | 68.00% | 40.96% | 46.24%
100% | 50.00% | 53.125% | 25.00% | 28.22%

While these numbers are already shown in the graph, I feel like reading it in plain numbers might help some of us. The numbers given are again relative numbers, relative to the defined nominal damage value.
Personally, I would be totally happy with damage profile 2 and k = 1, i.e. no modifications. A damage of 25% at the blast radius' limit is a good reasoning to not expand calculations beyond that, because of the relevance.

@Elyssaen : if you define a modifier which says: deal +50% at the center and -25% on the very edge, this does sound -- in the first moment -- like dealing more on average. I know what you mean and I understand the maths behind your thoughts, but please have in mind that not all of us attained calculus with the same interest. ;-)

Scaling down the damage of weapons does not sound too charming to me.
First: Players love big numbers.
Second: Players chose weapons according to a) favors or b) nominal data. And there they compete with weapons with no blast radius...
Third: A damage dealing 150% of its nominal damage under certain conditions (ground zero) needs lots of explanation which cant be provided ingame easily.

**Finally**: Why should the damage be not modified, i.e. `k = 1`?
Any given weapon should not behave too different whether it has a blast radius of zero, i.e. no blast radius (almost all weapons) or a tiny blast radius (e.g. of two, five, or ten).
Having `k = 1.5` as written by @Elyssaen in his last comment would dramatically alter a weapons damage only (at ground zero) only because the content creator added `blast radius 2` to the weapon definition without knowing the severe implications of that.

**My vote:** damage profile 2, k = 1.

**Comment by Elyssaen** [comment]
I see your point (second/third) about weapons. The strongest argument seems to be that we don't want it to be really hard to work out the damage of weapons with blast radius – we want to number on paper to be meaningful.

But it's not clear to me how this is _possible_ with any static value of _k_. With _k_ = 1 and no change to the data files, your Heavy Rocket will claim to do 700 damage but in fact it will do just 514 to the direct target.

I think:

1. Whatever we do, we don't want to rebalance every ship explosion in the game. That's 128 values, plus every plug-in that added a ship.
2. A key decision, then, is if the on-paper ship damage should now become the maximum you get (_k_ = 1, means on average it's less painful), the average (_k_ = 1.5), or even the minimum (_k_ = 2).
3. Whichever we choose, it _will_ have an effect on the balance of existing blast weapons. Some will usually hit their target directly, another at 20% through the blast, another at 60% through. Without tweaking the underlying numbers we're going to end up with weak Heavy Rockets / stronger Detainers, etc.

(I'm hesitant to mention that a dynamic value of _k_ is possible. But if _k_ was 1 + (TriggerRadius/BlastRadius)<sup>2</sup>, ship explosions would be as @EndrosG says, on-paper value only at centre, while weapons would automatically do their on-paper damage at the most likely range of hit.)

**Comment by Elyssaen** [comment]
[Here's a Google Sheets](https://docs.google.com/spreadsheets/d/1ThX-2du_t2jC_iKDEwd6C78ZtF8hKYIcmM7nqX-aMM4/edit#gid=1599021553) for playing about with the numbers.

**Comment by EndrosG** [comment]
With your dynamic `k = 1 + (TriggerRadius/BlastRadius)²`, I am still very fine for the ship explosion weapons.
I dont see any reason why, if we introduce damage dropoffs, we should rebalance ships blast radius or alike just because we eventually rebalance trigger radius based weapons.
Your argument of "most likely range of hit" only applies to the primary target, but not to secondary targets (being within the blast radius).
The ship explosion weapon does not have a primary target but only hits secondary targets. And thus its behaviour is consistent with other blast radius weapons with respect to secondary targets.

There is one thing with your dymanic k though which I didnt mention yet.
If you have own escorts, e.g. fighters, close to the primary target of your projectile, and if these are closer to the projectile than the target itself, your own escorts will suffer more damage than the target itself. Just because they accidently were heading the samy way towards that target...

**Comment by Elyssaen** [comment]
> I dont see any reason why, if we introduce damage dropoffs, we should rebalance ships blast radius or alike just because we eventually rebalance trigger radius based weapons.

Ideally the idea would be to rebalance as little as possible in the Data files, right? That's my position, and is why I don't think we should do anything that requires changing all the ships in Data files.

> Your argument of "most likely range of hit" only applies to the primary target, but not to secondary targets (being within the blast radius).

> If you have own escorts, e.g. fighters, close to the primary target of your projectile, and if these are closer to the projectile than the target itself, your own escorts will suffer more damage than the target itself. Just because they accidently were heading the samy way towards that target...

True, but what's the alternative? You can't add damage scaling to a Heavy Rocket without... scaling the damage. And without making a bystander potentially take more damage than the main target. If we don't want that, then we don't want blast damage scaling _at all_.

As to primary vs. secondary target, the reason I'm talking primary target is because I think that if the Heavy Rocket is nerfed from 700 shield damage against the target down to 515, this is a problem. It's not balanced out by it still doing up to 700 against an accidental bystander. A better state of affairs is it still does 700 to a primary target, but an unlucky bystander might take up to 952. If we don't want that, again, it's an argument not to have damage scaling at all.

**Comment by EndrosG** [comment]
I agree with you, @Elyssaen. It was important for me that we wrote those arguments down and had a look at both sides and point out the pros and cons. And I want the damage scaling.

**Comment by tehhowch** [comment]
Given that many secondary weapons which use explosion effects are actually single-target effects without a blast radius (i.e. **every** "missile" except Nuclear Missile and Heavy Rocket), `k = 1 + f(trigger & blast radii)` seems appropriate. This enables Heavy Rockets and Nuclear Missiles to deal near nominal damage to the primary target, despite being activating while the target is not positioned to take maximum damage.

<details>
  <summary>By tweaking the exponents in the denominator, we can arbitrarily flatten the damage profile to limit "damage peaking" for targets inside the trigger radius:</summary>

For example:
`k = 1 + (trigger/(2 * blast))^2` 
`d = k / (1 + r^4)^2`
This dependence results in k = 1.01 for the Nuclear Missile, and 1.09 for the Heavy Rocket, and a distance dependence that doesn't kick in rapidly.

 - At the NM trigger of 20% blast radius, it would deal `1.006 * 9000 = 9060` damage, while at the center it would deal `1.01 * 9000 = 9090`.
 - At the HR trigger of 60% blast radius, it would deal `0.854 * 700 = 597` damage, while at the center it would deal `1.09 * 700 = 763` damage.
 - At the edge of their blast radius, the damage is `25% * k` of the original value.

![image](https://cloud.githubusercontent.com/assets/20871346/26418673/b9579760-4082-11e7-8036-ed4c4abec457.png)
</details>
_________

The combined use of trigger radius and blast radius makes this overall issue (how to implement damage scaling?) hard to solve: the damage scaling method used will influence the desired ratio of trigger radius and blast radius, and the specified paper damage. In all cases, the minimum damage will be `paper * k / (2^(scaling denominator exponent)`, where k can be from 1 to 2 depending the scaling implementation.

Balanced/"good" outfits simply require the content creator to know that the scaling exists (and understand the formula). If the content creator does not know scaling exists, they will not make weapons that behave in expected manners. This is true in general though - if a content creator does not understand game mechanics, then they cannot create "good" content.
<details>
<summary>For example</summary>

Damage scaling could be used to offer multiple revisions of a mine where the differentiation is in its trigger mechanism instead of its specified damage: 
 - Mk0: very unstable, explodes as soon as it senses an opponent (`tr = br`)
 - Mk1: more stable, explodes when the hostile has approached somewhat (`tr = br / 2`)
 - Mk2: very stable, explodes when the hostile is very close (`tr = br / 4`) 

All of these mines could have the same paper damage, but achieve greatly improved effectiveness solely by altering the trigger radius and thus the damage the hostile will experience. They would thus have the same lethality to friendly ships (as the damage profile is essentially equal), but would be increasingly damaging to opponents due to the closer proximity trigger.
</details>
_________


footnote: I am pretty sure I'm not the only one who mistakenly thought that any weapon resulting in an explosion hit effect dealt splash damage. A PR to introduce appropriate small `blast radius` values to the existing missile outfits (e.g. 5-20 & no trigger radius) would be welcomed by me.

**Comment by tehhowch** [comment]
With the recent addition of "safe" to the content creation toolkit, our considerations about damage scaling can be updated:
1. Human tech in es-master (NM, Heavy Rocket) is not likely to get "safe" (lore / tech level reasoning)
2. Alien tech in development that uses trigger radius can also use safe to prevent the bystander-takes-more-damage-than-target effect

What this means to me is that if we add blast damage scaling via a dynamic k calculation and flattened-center blast damage scaling equation, the only immediate content adjustment needed will be a small boost to the Heavy Rocket damage (to 700/.85). A second adjustment may be needed to the Gridfire Turret/Arfecta, as a reduction in damage to secondary targets will reduce its ability to take on entire fleets by itself (yet simultaneously improve its ability to play nice with  allies).

**Comment by tehhowch** [comment]
Doing some testing shows one missed issue:

Collision detection is done using the mask of the affected ship, but positions are measured relative to the center of the mask. This means that small ship explosions, would do zero damage to large ships unless the ship is essentially concentric with it (e.g. just got boarded and destroyed).

I've fixed this by calling a check to the hit ship's sprite mask, but a perhaps-faster way is to alter / augment CollisionSet::Circle in order to output either vector<pair<body, double>>, or to be a map<body, double>.
This change would eliminate the need to compute the distance from the ships that have been flagged as being within the blast radius within the Ship::TakeDamage method, but the cost may be larger than any potential savings. Currently, CollisionSet::Circle does not bother to find the minimum distance, only if any part of the sprite overlaps with the circle having the expressed radius and offset by the separation distance, and thus an extra quantity would be computed, even for weapons which have the proposed `no damage scaling` attribute such that they can avoid the scaling behavior.

**Comment by endless-sky** [comment]
Addressed by merging #3276.
