### ISSUE TITLE
Volume (projectiles too loud, perhaps a mixer?)

### ISSUE THREAD

**Issue by Elyssaen** [endless-sky/endless-sky#2537]
Does everyone play ES like this?

![volume](https://cloud.githubusercontent.com/assets/23544894/26286608/52579ce0-3e61-11e7-88e1-07307e3986be.JPG)
_(actually, that's super loud for me)_

I've never really minded until just now, when I tried to use the system music feature to add a battle theme to a plug-in mission. But while it plays, projectile noises tend to drown any music.

I know Triple-A games would have a mixer, letting you choose different slider positions for different types of sound. But obviously, music isn't a big part of ES, so that might set false expectations and it's a fair bit of work.

But is there something else that could be done? An automatic, behind-the-scenes mixer (to just make projectiles/explosions a lot quieter) seems like it'd help.

**Comment by KiLEdEnNis** [comment]
the game is ridiculously loud by default so ye I have it very low too

**Comment by Bladewood** [comment]
I have the in-game setting at max volume.

My Windows volume mixer, on the other hand, is set to 25%.

**Comment by comnom** [comment]
I had the exact same problem when doing sound effects/music for mine. A volume mixer would be nice, I'm all for it, but I really think the audio just needs another pass.

I had attempted to balance the sounds a bit (they were all made louder as once upon a time they were too quiet), but I was unable to work with most of the current sounds due to clipping. 

From the Audacity manual:
>Clipping: Distortion to sound, usually due to the audio being too loud. Unless the original audio is 32-bit sample format, waveforms louder than 0 dB will have their tops lopped off (flattened) at 0 dB, rather than showing smooth curves.

Meaning when I went to edit them, I could make them quieter but not get rid of the flat spots. If there is a way, I was unable to find it. The red overlay in the following shows all the spots that are clipped:
![jumpdriveclipping](https://cloud.githubusercontent.com/assets/22107649/26315260/8b860f38-3ede-11e7-93ae-02e04a6b91c4.png)

I'd still be willing to give it a shot, (I'm no pro but willing to try), but I'd need the originals(before they were made louder), or a list of sources to have any real chance at doing a decent job.

**Comment by jafdy** [comment]
https://github.com/endless-sky/endless-sky/tree/84a580db197fddcbd9fc2c6c8944f0ea9b7e50f4
You can look at the files in the repros history by finding an appropriate commit and clicking Browse Files.

**Comment by comnom** [comment]
@jafdy Ah, thanks man, that'll help. Do you know if there's some github magic to check if any were replaced along the way without checking the history of each file individually?

**Comment by tehhowch** [comment]
from the command line:
`git log --follow filename`
e.g.
`git log --follow sounds/afterburner~.wav` returns 1 entry, 62876020
`git log --follow sounds/rocket.wav` returns 3 entries: 597fda2097, ecebf4ceb, and 4721b598cc

**Comment by comnom** [comment]
@tehhowch Thanks man, I was hoping to avoid checking individually but I'll just write a little script to grab it all before I start. No big deal. Hopefully I'll have some luck in finding a nice middle ground for all of them.

**Comment by endless-sky** [comment]
This seems to be strangely dependent on the operating system. The volume is currently set up so that if ES's volume is at 50%, sounds are roughly as loud as any music I play at full volume in the background on my own computer (which is running Linux). But apparently on other computers the sound ends up either much louder or much softer than everything else.

**Comment by Elyssaen** [comment]
Odd. What do you suggest?

**Comment by endless-sky** [comment]
Reduced the volume in 006238e.
