### ISSUE TITLE
Typo in Rim Archaeology 1?

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2540]
https://github.com/endless-sky/endless-sky/blob/master/data/transport%20missions.txt#L997
> We've heard rumors from the Quarg that an alien civilization used to exist in the Rim, a hundred of thousand years ago.

Shouldn't it be "hundreds of thousands of years ago" or "a hundred thousand years ago," because "a hundred of thousand years ago" doesn't appear to be right.

**Comment by MessyMix** [comment]
Seems like a typo to me.

**Comment by endless-sky** [comment]
Good catch. Fixed in 1abd93d.

The Sheragi discovered spaceflight around 100,000 years ago, about the time of the peak of the Hai empire, around the same time that the ancestors of modern humans began "banging rocks together." The Sheragi civilization survived less than a millennium after that.

The Hai discovered spaceflight about 120,000 years ago, and their civil wars stretched from about 95,000 to 90,000 years ago. 90,000 years ago, the Hai pulled back from "human" space and from the ruined worlds to the north of them, and 80,000 years ago the Wanderers moved into that northern territory.

The Korath, Saryds, Kimek, Arachi, and finally the humans, discovered spaceflight 40, 17, 14, 10, and 1 thousand years ago, respectively. Note that that means that new spacefaring species have been appearing more and more frequently in recent history, which is part of why the Archons have been having so much trouble holding things together lately.

**Comment by Amazinite** [comment]
Holy lore.

**Comment by Amazinite** [comment]
So the Unfettered are chill with telling us they discovered space flight 10 times earlier than they actually did? (One says over a million years now gone in "First Contact: Unfettered.") Aight, that's another lie detected.

**Comment by Amazinite** [comment]
>80,000 years ago the Wanderers moved into that northern territory.

Let it be known that 1 Wanderer cycle = 8 years, as in "Wanderers Conversation" they say they've been at their current location for 10,000 cycles.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/commit/ff8315834429f12e891db5358e50339adfcf78aa nope

**Comment by Amazinite** [comment]
Lol, time to change my own time line.

**Comment by Amazinite** [comment]
I think it might be worth putting somewhere since most of those dates can't be found via the game itself, namely when the Hai, Korath, Saryd, and Kimek discovered space travel (my dates for the latter two were off by 1000 years since the planet and ship descriptions I got them from didn't account for the 1000 year Coalition-Quarg war).

**Comment by Amazinite** [comment]
Now that I have all the important dates when the civilizations invented space travel I need population numbers...

**Comment by endless-sky** [comment]
Very roughly, I'd say:

* Humanity: 100 B
* Hai: 40 B
* Wanderers: 1 B
* Korath: 1 B (mostly the Kor Efret)
* Saryds: 30 B
* Kimek: 200 B
* Arachi: 50 B
* Pug: unknown; at least 1 B in our galaxy.
* Quarg: unknown; > 1,000 B per complete ringworld.

**Comment by Amazinite** [comment]
Thanks.

**Comment by Amazinite** [comment]
Remnant? :)

**Comment by EndrosG** [comment]
I think these information should be added to the wiki - mostly for reading by content creators.
