### ISSUE TITLE
Mortgage payment amounts won't go down

### ISSUE THREAD

**Issue by StokedIndustries** [endless-sky/endless-sky#2547]
So I just returned from buying a Beetle and started doing a few cargo runs.. and unfortunately took me a while to notice that my mortgage payments weren't going down at all and it was eating quite an amount every day.

Has anybody had this issue too?

Details...
Mortgage 1: 8.678M @ 0.200, 38,629 payment
Mortgage 2: 434,357 @ 0.200, 1,932 payment
Crew: 4,600
FW Income: -800
Total: 44,361

I noticed that it switches between 44,361 and 44,362 every day.

I had a little over 1.5M after the purchase and only started getting worried when I hit 300k pretty fast. Now I'm afraid to leave the planet and put myself another 44k in the hole.

**Comment by tehhowch** [comment]
Right, paying back only the minimum won't make your automatic payments go down, since that's how the minimum was decided.

Worst that will happen is your credit score will go down, and you won't qualify for new loans (and they'll be expensive). Crew salaries will pile up, so you may be best off in a nimble light/medium warship with 50+ cargo space. If you find the right stuff, mining asteroids can bring in >2000 per ton of profit, so you can pay down your loans pretty quick without any missions or jobs.

Unless MZ added the galactic repoman...

**Comment by Lineth** [comment]
Mine Uranium in Ascella. 5000/ton with titanium at ~2000/ton. Will pay back money troubles fairly easily. Gold and platinum are the most valuable at 8000 and **10000** a ton respectively, but they're very, very rare.

**Comment by gunqqer** [comment]
Capping pirates/Korath are also a good way of making money

**Comment by StokedIndustries** [comment]
Ahh my bad, wasn't thinking about that. Thanks everyone!
