### ISSUE TITLE
Destructible and mineable asteroids

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#257]
Adding mechanics for asteroid destruction and mining of their contents, like in EVN, would be a welcome change. Asteroids would blow up if caught in the crossfire during battles, and mining metal from certain asteroids would let you sell the metal for a profit or make your own missiles even more cheaply in conjunction with the proposed Missile Factory outfit.

**Comment by endless-sky** [comment]
In EV, the asteroids cease to exist once they are off-screen, which was rather unrealistic - it meant, for example, that missiles never struck an asteroid until they got close enough to you to be inside your own personal asteroid field.

I fixed that by having the asteroids "tile" - that is, each asteroid appears an infinite number of times in the system, in a big square grid. The disadvantage of that, though, it that if one instance of an asteroid were removed or split (say, because a ship off-screen hit it with a missile) you would see an asteroid in your field of view explode for no reason. So, right now asteroids are non-destructible to prevent that.

I suppose I could add a small number of "destructible asteroids" for mining, or something like that, but I always found mining in EVN to be tedious and pointless compared to other ways of earning a living.

**Comment by Pointedstick** [comment]
Some people liked mining; I had a friend who was nuts about it. Even besides that, making them destructible was cool for battles in asteroid belts; debris would start scattering everywhere, really making it look like a big deal.

**Comment by gchapyzh** [comment]
Asteroids you can build on? Have a little laser platform with a shield gen and a missile launcher. You could build these for systems for money from the planet you build it around on. For example:

Mission: Asteroid Base - Setup a <laser turret/blaster turret /missile launcher> and a level <level> shield on an asteroid orbiting <planet> in the <system>.

or,

Mission: Remove asteroid - Destroy a large asteroid in the <system>.

Asteroids would also act as great source of profit. Mining turrets and mining drones will give fighter bays another purpose: hosting mining drones. They would be like surveillance drones but with a turret and a mining laser. (or you could have the drones board/land on the asteroid and fill up their cargo bays.)
