### ISSUE TITLE
Fleets do not refuel at subjugated pirate planets

### ISSUE THREAD

**Issue by sigmareaver** [endless-sky/endless-sky#2575]
Possibly related to #2163.

I'm sitting in a pirate system that I've conquered and holding down J does not cause my fleet to go refuel. I have to land myself to get the fleet refueled.

**Comment by endless-sky** [comment]
Your ships only stop to refuel if they do not have enough fuel to make it to the next system (or, if the next system is uninhabited and they don't have two jumps worth of fuel).

**Comment by sigmareaver** [comment]
I will conduct additional testing, but I am pretty certain that the ships appeared as red in the fleet list, while I was holding down J.

**Comment by sigmareaver** [comment]
So, if you're in say, a Republic system, and you hold down J, any ships needing to refuel, will land, refuel, and launch.

In the subjugated pirate system, this does not occur. However, if you jump anyways, the ships will then go refuel and follow you. I'm not sure if this is an oversight, or intentional, but I was thinking it may be that your fleet prioritizes attacking pirates over refueling.

**Comment by jafdy** [comment]
They always prioritize combat over just about anything else baring getting ready for jump.

**Comment by tehhowch** [comment]
As jafdy says, if there is a target nearby, and you are in the system, your escorts will choose to defend you instead of prepare to evacuate.

It is possible that we could create a new fleet order (e.g. `Orders::LAND_ON`) in which we tell our fleet to land on a certain planet by right-clicking it (right now this executes a move-to). See #2667 for why we might introduce this order. Then you would be able to override this instruction for your escorts to defend you, and ensure they are ready to fight in the next system.
