### ISSUE TITLE
Banks should let you invest the money or put it in a savings account to generate a recurring income stream

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#258]
Right now all the bank can do is loan you money. You should be able to loan the bank money too! Why not allow the player to purchase CDs or otherwise invest their money, tying up the money but earning a recurring income stream? This would make it more palatable in the early game to buy a ship with a large crew or that relies on missile weapons before the point where you can easily defray the running cost with a salary from one faction or other.

**Comment by endless-sky** [comment]
I suppose this could just be done by having *all* your money in the bank earn interest. I considered that in the past, but decided against it because it's already hard enough for players to understand why they are *losing* money to mortgage payments.

Besides, maybe the Republic's Federal Reserve is just keeping the funds rate at 0% to try to stimulate the galactic economy. That would certainly fit with the plot of the game...

**Comment by Pointedstick** [comment]
Making you purchase galactic CDs or something would seem to alleviate that problem, because it would have to be a deliberate purchase rather than yet another thing that happens automatically that you have to figure out at the start of the game. And we still have 2-3% CDs in a ZIRP climate.

**Comment by wkoot** [comment]
What about war bonds? There are plenty of events that could play in to this :-)

**Comment by endless-sky** [comment]
I don't think it makes sense to add new features that add complexity to the game, unless they also make the game play more interesting. Mortgages work because they provide financial stress early on as well as a temptation to take on more debt than you can afford. But CDs or something similar would not provide much game play value.

Also, I'd like to know where in the world you're finding 2-3% CDs being offered by a reputable bank...

**Comment by Pointedstick** [comment]
https://savings.eloan.com/savings

Although maybe that doesn't quite meet the definition of "reputable…" But you can find 2.25% 5 year CDs from banks that would probably fit the definition.
