### ISSUE TITLE
Hirable specialist crew members

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#259]
Right now you can only hire generic crew members. It would be awesome if you could pay more to hire superior crew members who could improve the performance of your ship. For example, for 400 credits per day instead of 100, you could hire a pilot who would improve your ship's turning and speed, a tactical officer who would increase the damage or firing rate of your guns, a security chief who doubled your your boarding attack and defense, a chief engineer who would increase energy generation and heat dissipation, etc.

**Comment by thenerdfreak** [comment]
doubling ship's attack or defense no, that would be ridiculously op, but everything else seems fine

**Comment by Oeleo** [comment]
And fighters crew, more efficient that the others (1.25/1.5), it will be good for those who play pirates or to take alien ships

**Comment by endless-sky** [comment]
I'm hesitant to add something like this because it would make hiring crew an order of magnitude more complex and harder for players to understand.

Also, note that it would be relatively easy to simulate this by using outfits. For example, you could add a "navigation station" outfit that increases your required crew by 1, but also gives you a tiny boost to thrust and turning. (But, this could get broken pretty quickly with large ships that have lots of bunks, unless the number of stations is limited in some way.)

**Comment by Pointedstick** [comment]
I was considering doing it as an outfit, but then the extra required crew member would only cost you an additional 100 credits per day. To make them cost 400, you'd have to require 4 extra crew, which would limit such outfits to large ships.

Then again, as an outfit, I could make it require space or power, reducing the "no-brainer" effect. So I guess I'll do that.
