### ISSUE TITLE
Pirate Gatling guns are infuriating

### ISSUE THREAD

**Issue by CJL48** [endless-sky/endless-sky#2624]
Okay, I don't know for sure that these are Gatling guns, but I keep running into pirates with rapid fire yellow-projectile weapons that have substantial knock-back.

...and almost immediately and unavoidably dying, because in addition to the knock-back, these weapons deal heavy shield and hull damage, and the pirates never stop firing them. I essentially get stun-locked to death, meaning that I might as well reload if I see yellow projectiles.

I don't know why the pirates don't have to reload if these are gatling guns, but this needs to be fixed.

**Comment by Amazinite** [comment]
Those are particle cannons.

**Comment by CJL48** [comment]
Alright, sorry. I'm just a little irritated that I keep running into pirates who can stunlock me to death, when I'm in a medium warship and they're in light ones.

**Comment by tehhowch** [comment]
Note that it is totally OK for a medium warship to be beaten when swarmed with a handful of light warships. If you are playing single-ship and expecting to fight pirates, you will need to arm yourself heavily while also being rather maneuverable, in order to escape those instances where you can determine you will be fatally swarmed. It is almost certainly a death knell to be slow (< 500), lumbering ( < 80 turn), and poorly kitted (shield gen < 100) unless you can destroy a light warship in less than a second or two.

You can probably get a lot of good ideas for improving by posting a question on the [steam forums](steamcommunity.com/app/404410/discussions/0/) or the [Endless Sky subreddit](https://reddit.com/r/endlesssky) (as Github is more for bug reports and feature request implementation discussion)

**Comment by Bladewood** [comment]
I still hate the *real* gatling gun.

**Comment by CJL48** [comment]
Thanks. Looks like I either need to swap over to something more maneuverable, or upgrade my thrusters.

**Comment by MessyMix** [comment]
It makes ES all the more fun.

You could, alternatively, invest in a couple more ships, or maybe try going for more shielding, or even a Heavy Warship.

**Comment by Amazinite** [comment]
This should be closed.

**Comment by KiLEdEnNis** [comment]
a good counter is a high speed ship with good firepower, or at least a ship that can outrun them; get to a safe distance and jump away, or get a scram drive

**Comment by Pointedstick** [comment]
Or use torpedoes. A few salvoes will obliterate light pirate ships.
