### ISSUE TITLE
File Organization

### ISSUE THREAD

**Issue by TurkeyMcMac** [endless-sky/endless-sky#2630]
I noticed that the weapons of some governments are stored in a special `weapons.txt` file, while for other governments, it is stored in their `outfits.txt`. Perhaps this should be reorganized in some way to be more consistent. Hopefully this is the right place to bring this up.

**Comment by Bladewood** [comment]
https://github.com/endless-sky/endless-sky/pull/2579 They're working on it.

**Comment by TurkeyMcMac** [comment]
I'm not saying that the files must be reorganized into folders, necessarily. I just think that either every government should have separate `weapons.txt` and `outfits.txt`, or they should all have just `outfits.txt`, which would contain the contents of both files.

**Comment by Bladewood** [comment]
I understand what you mean now.

In the case of a species like the Wanderers, the reason their weapons are part of their `outfits.txt` is simply because there are so few of them. The weapons, I mean. (At least, I think that's the reason.)

**Comment by Amazinite** [comment]
>there are so few of them. 

That's what I would say. The main reason for the humans having ALL their outfits split into different files (a file for just weapons, just power, just engines, then "outfits" for systems and other misc stuff) is because there is so much of it, but other species like the Hai (who only have 6 weapons compared to humanity's 26 or 11 engines compared to humanity's 34) don't have enough outfits of any one type to warrant splitting the files up. 

(Although, the 21 outfits, 6 of which weapons, of the Coalition are split into multiple files while the Hai have 24 outfits all in the same file.)

**Comment by TurkeyMcMac** [comment]
Maybe governments that separate weapons from other outfits should call the `outfits.txt` file something else to indicate that it does not contain weapon outfits.

**Comment by MessyMix** [comment]
@TurkeyMcMac imo we can talk about this once we get folder structure organization. Otherwise, it just becomes a clustertruck of files and that becomes unnecessarily hard to navigate.

**Comment by endless-sky** [comment]
Closing this as a duplicate.
