### ISSUE TITLE
Feature Request: There should be a setting/toggle for fleet jumps.

### ISSUE THREAD

**Issue by Jeremy-E-Johnson** [endless-sky/endless-sky#2638]
When jumping with a large fleet, it is safer to keep every ship together. There should be a setting or toggle that enables some sort of "Fleet Autopilot" which will not jump until every non-disabled ship in the system is ready. This is already possible by holding down the jump key but can become tedious when making routine jumps.

I see this being implemented in one of two ways:
1) A new preference in the settings window that toggles between the standard auto pilot and the fleet version.
2) Some sort of keybinding (shift + 'jump key' possibly?) that triggers a toggle between the two modes and which is confirmed in the messages.

**Comment by tehhowch** [comment]
>it is safer to keep every ship together

Really depends on your game situation. If your flagship is a heavy warship with overpowered gear, no, it's safer for your fleet for you to go ahead. If your flagship is unarmed and your escorts have the firepower, then sure. 

As it is right now, you can always guarantee the ability of your flagship to flee its current system, and your escorts will join you when they can (unless you told them to do something else). If you make a preference toggle such that your fleet only jumps when everyone can jump, your whole fleet will be trapped when any single ship is prevented from hyperspace lock - this sounds like a poor user experience.

Should such a toggle be implemented... what are you doing while you wait for your fleet to get ready to jump? You can't move your ship or you will cancel the jump order, and your turrets will still engage hostiles while you hold J.
Or is this basically a request to press J once, go brew some tea, and return to a fleet in your destination system of choice, intact?  Because this is already possible with the current system.

**Comment by Jeremy-E-Johnson** [comment]
> Really depends on your game situation.
That's fair, but there are situations where keeping the fleet together is the preferred outcome.

As for making sure your flagship can leave, perhaps on a second press of the jump key, the flagship and all ready ships jump no matter the state of the rest of the fleet.

> Because this is already possible with the current system.
And yes, that is basically what it is, but there are some users for whom holding down a key for long periods of time can be uncomfortable and or painful. 
In case you are concerned that this is not worth the time, I was planning on implementing this, but I wanted to consider the best possible designs.

**Comment by SirStigII** [comment]
Could a shift=J trigger the jump as one behaviour until player input, similar to how it works now but with the group jump behaviour? It already seems to happen in AI convoys, so I would imagine the logic is already there.

**Comment by jafdy** [comment]
I think (to stop people just wandering off) shift-J could have the same effect as holding J but require you to press J once more to actually do the jump.

**Comment by Jeremy-E-Johnson** [comment]
> I think (to stop people just wandering off) shift-J could have the same effect as holding J but require you to press J once more to actually do the jump.

I think that this makes a lot of sense. It removes the need to hold down "jump key" without compromising the player's ability to go when they decide is best. It should also be easy to implement as it seems to me like it would involve adding a command that looks a lot like jump without the actual jump bit. 

The biggest downside that I see is the possible non-intuitive behavior where a player hits jump key of some sort and the ships never actually go. I think that this is a fairly benign problem especially if the shift+"jump key" press puts out a helpful message. I am going to start working in this direction for now.
