### ISSUE TITLE
Economics Issues with humanitarian missions to pirate planets

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2652]
When i did 2 humanitarian missions (food shortage on a northern pirate planet, needs medicine on an eastern), and then went to the market on the respective planets, the prices for the good was 'very low'.  Which makes no logical sense.  those missions should force the price to 'very high'.

**Comment by Amazinite** [comment]
The economy of goods doesn't fluctuate at all based off of story events.

**Comment by MessyMix** [comment]
@Amazinite I think he knows that, but he says that those events "should force" the price up.

**Comment by Amazinite** [comment]
He only mentioned the two humanitarian missions so I'm making it clear that it's all missions that this can have a problem with.

**Comment by Forlarren** [comment]
Is it possible story events can alter prices? Someone just needs to do the work?

**Comment by tehhowch** [comment]
Yes, you can use an event to redefine the properties of a system. No, there is no code work needed.

There is an entire wiki section devoted to changing the game's data.
https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins#creating-or-overriding-data-elements
Note the keyword `trade`
To make an event happen, you need a mission. Luckily, there is an entire Wiki section devoted to this topic
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions

If you still are unsure how to set things up, you also have an entire library of existing data to inspect! Of specific relevance will be `data/map.txt` and `data/events.txt`

Again, please read the wiki: https://github.com/endless-sky/endless-sky/wiki
There are many sections which you will find helpful.

**Comment by Forlarren** [comment]
Counter argument would be pirates aren't rational market actors. The problem is nobody can convince them buying medicine and food is better than stealing it even if they had much money.

There are other economic reasons as well. Like in Africa where medicine is sold at whatever the market can bear but it's so little it has to be cheap. The counterfeit problem is also so bad the locals won't pay any extra without extreme evidence of the quality, a catch 22 problem. The market is just too ignorant and chaotic to operate rationally. Like getting pirates to buy medicine instead of moar guns.

**Comment by endless-sky** [comment]
The humanitarian missions have random destinations, so there's no way to hard-code an event to change prices (or to change them back after). And, it really doesn't seem worth it to do so for such a minor increase in realism.

**Comment by marphod** [comment]
I would think that passing a variable to an event could be useful; this might be a low-priority issue in itself, but the general case would be powerful.

No idea at a usable syntax, though.
