### ISSUE TITLE
Unfettered intro assumes you've met normal Hai

### ISSUE THREAD

**Issue by jlnxr** [endless-sky/endless-sky#2664]
On a new save decided to do some things differently to see what would happen, and ended up visiting unfettered space before normal Hai space after passing through Wanderer space from the North. Despite never having met any normal Hai before, the text seems to assume you know what the unfettered are and aren't surprised to see Hai. It says "The Hai here appear to be at war with the rest of their species" but if you visit unfettered space first, for all you know all Hai are like them, and you haven't seen their war.

**Comment by arkhne** [comment]
As discussed during Derpy's stream yesterday, I've agreed to work on this, and have started, I just need to find someone willing to walk me through using github so I can make the changes (and somebody to make sure I don't make a complete fool of myself).

**Comment by neevok-eu** [comment]
What I missed is some sort of warning from the unfettered not to trust the other Hai or some question to spy on them or something like that. It still felt like the issue was solved by adding something to literally two dialogue boxes (one unfettered which I don't recall being really different from the reversed scenario and one for the regular Hai, which was a different intro.) Should they not be surprised/suspicious you came from up north? Also a change to the route for meeting the Hai through there-might-be-riots-band would be illogical (peaceful squirrels)
