### ISSUE TITLE
Pos/Neg credit difference between comodities should be color coded

### ISSUE THREAD

**Issue by gunqqer** [endless-sky/endless-sky#2671]
Something to indicate which is + and which is -. I get exited when I see -410 then I notice it's *minus* 410, not plus. On this note maybe highlightning the higest positive difference.

edit: see MZs fix below (increasing text size for the plus)

**Comment by Amazinite** [comment]
Similar to #1118

**Comment by Festerdam** [comment]
I think that color highlighting is a bad idea. When you play this game, you feel like some futuristic stuff is going on and that you're touching steel when pressing buttons(it is used a lot of gray, white and black). But that look and feel would be destroyed if we put somewhere a color like red(which is a really aggressive color(blood pressure becomes higher and is great for warnings)).

But I think we could add an option in the settings called something like "dynamic commodity order", so that if this option is enabled, it would on the panel that we see on the map at the ports section display the commodities according to the absolute value of the profit(not the value of the profit, because people are normally looking not just for big positive changes, but also for big negative changes(useful if you are planning to go from one point to another and vice-versa.))

To make the distinction between negative values and positive values easier, maybe we could make the font-size bigger on the entire game, that way even color-blind people could still play. But I am not sure that would still look pretty, that would be a reason to only make the font-size bigger of the plus and minus that are displayed on the panels with the profit and not of the entire game.

**Comment by tehhowch** [comment]
Numerical comparison may be better suited to using a font that has monospaced digits, as this would remove the left-right jumping one's eyes need to do when parsing the displayed relative prices. Alternately, removing or otherwise spacing the parentheses from the sign indicator could help as well.

Of these, the spacing can be done immediately, while the monospaced digit font would require obtaining a new font to use, and then using it only in tables of numbers (of which there are few).

current behavior:
![prespacing](https://user-images.githubusercontent.com/20871346/27557159-23f2a3b6-5a7e-11e7-94ce-81a3bee0c132.png)

space before + or -:
![post-spacing](https://user-images.githubusercontent.com/20871346/27557167-2e8b8f40-5a7e-11e7-9b79-f030e4a80af8.png)

space before + or -, and after number:
![double-spacing](https://user-images.githubusercontent.com/20871346/27557188-3ee2a702-5a7e-11e7-9df9-2632ebff2ab3.png)

removing parentheses entirely:
![no-parentheses](https://user-images.githubusercontent.com/20871346/27557202-4a8e0182-5a7e-11e7-9492-4bcd25faba74.png)

**Comment by gunqqer** [comment]
I really just want to be able to see +/- more easily. Maybe have the +/- on all the same collum. I don't need which one is going to be worth the most, just which have a gain or a loss.

**Comment by endless-sky** [comment]
Part of the problem might be the '+' sign itself - the right branch was way too short due to unfortunate auto-hinting when I rendered the font. Commit 02ed0ec makes the '+' sign a little bigger and easier to differentiate from the '-' sign:

![prices](https://user-images.githubusercontent.com/11450262/27718392-aaaab388-5d19-11e7-9aec-b425a6188821.png)

In general I've tried to avoid colored text because in the game's nearly-all-monochrome UI it would look really tacky.

**Comment by gunqqer** [comment]
oh wow, ok that upsized... size looks so much better. Ok, I think that is good. 

I'm going to leave this issue open until the next update when this goes into effect.
