### ISSUE TITLE
My additions for endless sky(please consider)

### ISSUE THREAD

**Issue by mhoekstra132** [endless-sky/endless-sky#2676]
Additions for endless sky

1. After destroying the extremists(syndicate):
After destroying the extremists, one of the Oathkeepers find a map to a secret syndicate development centre which has been captured by the Extremists. There they’ve developed a new ship, with equal strength as a Korath Raider, but with something extreme! They’ve developed Particle Turrets. But one of the ships has escaped to the base and warned the other extremists that the republic has discovered their secret, and now they are threatening to destroy the syndicate capital. The main character is send by the Free Worlds to assist the Syndicate. The main character is to infiltrate the base, and scan the Extremists Capital Ships, because those are expected to carry the ‘Weapon’ to destroy the Syndicate capital. When the player has scanned all the Capital Ships(the syndicate has discovered a way to scan while cloaked, is to be taken after this mission) the player returns to Hephaestus to report back. After that, the player is to start a hyperspace link with the base, in order for the Navy to sweep in(covered by Free World Dreadnoughts). After thats done, the Navy invades, and a giant space battle emits. After the battle, the Navy captures the base for one year, and then returning it to the Syndicate. The Syndicate captures some of the tech(Particle turret etc, can make own tech) and then selling it for reasonable prices.
2. After the pug war(through the wormhole)
After the pug war, a garrison of scientists and Navy Oathkeepers is stationed on pugglemug. The scientists discover the Wormhole, but before they can tell anyone, the pug come through and recapture Deneb. The main character is to be together with some representatives from Syndicate, Republic and Free Worlds, they are too travel to Deneb to discuss a truce, since a new war would be costly. According to what the player says, the Pugs decide to either restore the old border, or, if said wrong, the Pug will decide to capture all of the systems surrounding them. Again, the player can decide to use the diplomatic way(for people without a suitable ship) or the warmongering way. In the diplomatic way, the Pug become friendly, reachable and willing to trade. In the warmongering way, the Pugs will accept peace, but are turned to themselves, not willing to help when needed, but not hostile.

**Comment by tehhowch** [comment]
These look like things that you can turn into missions + content already. Take a look at the [wiki](https://github.com/endless-sky/endless-sky/wiki) to get started on creating missions. If you join the [Discord server](https://discordapp.com/invite/5H4UbfP), there is a chatroom devoted entirely to helping with mission and outfit creation.

Based on your 2nd suggestion, you still have some content to explore in your game.

**Comment by jafdy** [comment]
I think the main issue with your ideas is that they go contrary to the existing lore.

1. Hyperspace links can't be created quickly. At the end of the story the relinking only worked because there was some residue of the link still there and the Pug where kind enough to leave the right bits of kit there to do it. This leads on nicely to;
2. The Pug "invaded" to prevent a nuclear genocide as well as to give humans some new tech to backwards engineer. They where not fighting to win, but to lose in a certain way. If they wanted to win they would have won. This means that they are unlikely to just start to invade again. 
Also the wormhole is _really_ obvious.

All that being said, the idea of a science expedition through the wormhole is not such a bad idea.
If you want to contribute a mission string you can learn easily enough, but _please_ use a more laid back idea then those.

**Comment by endless-sky** [comment]
Of course, technically speaking, no one actually knows how those hyperspace links were created or destroyed. It's possible for example, that a cloaked Pug ship carrying the *actual* technology for re-opening hyperspace links was hovering over the planet waiting for Freya to flip the switch on what she thought was a machine controlling the links, in order to make it look like she had accomplished something.

**Comment by gunqqer** [comment]
well, one person knows. Or, there is only one person who *could* know. Yeah, he'd have to be smart to know. Yeah he is. Hopfuly he'll tell us soon how they are *truely* made.

**Comment by VonZorch** [comment]
@mhoekstra132 
It's just flat out impossible to scan and remain undetected.
Scanning requires sending energy to a target.  That energy can and will be detected and at least the direction can be determined,  By having detectors on different parts of the ship distance can also be determined and make even a cloaked ship targetable.
