### ISSUE TITLE
Heroic ships clustering around the system center

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#2704]
If there is a ship with the heroic personality whos only target is outside of the boundry of the system, then that ship will wait at the system center for the target to enter back into the boundry of the system. 
![screenshot_1](https://user-images.githubusercontent.com/17688683/27811386-d4e54aec-6033-11e7-9b86-e91f167efd61.png)
My ships are currently holding position far from the system center, meaning that these Wanderer ships would stay here for as long as my ships remain where they are.
This was brought up [on Steam](http://steamcommunity.com/app/404410/discussions/1/2592234299570997332/), and I'm wondering if it's intended behavior or not for heroic ships to wait indefinitely for their target to become viable. 
The same behavior is not experienced when all hostile ships in the system are cloaked (i.e. if my flagship is the only one in the system and is cloaked).

**Comment by tehhowch** [comment]
This is from AI::MoveIndependent
```
	if(target && !ship.IsYours() && !ship.GetPersonality().IsUnconstrained())
	{
		Point extrapolated = target->Position() + 120. * (target->Velocity() - ship.Velocity());
		if(extrapolated.Length() >= MAX_DISTANCE_FROM_CENTER)
		{
			MoveTo(ship, command, Point(), Point(), 40., .8);
			if(ship.Velocity().Dot(ship.Position()) > 0.)
				command |= Command::FORWARD;
			return;
		}
	}
```
which does the movement, and AI::FindTarget()
```
// Find the closest enemy ship (if there is one). If this ship is "heroic,"
	// it will attack any ship in system. Otherwise, if all its weapons have a
	// range higher than 2000, it will engage ships up to 50% beyond its range.
	// If a ship has short range weapons and is not heroic, it will engage any
	// ship that is within 3000 of it.
	double closest = person.IsHeroic() ? numeric_limits<double>::infinity() :
		(minRange > 1000.) ? maxRange * 1.5 : 4000.;
```
There are two ways to fix this... make `heroic` equivalent to `heroic unconstrained` by changing `!ship.GetPersonality().IsUnconstrained()` to `!(ship.GetPersonality.IsUnconstrained() || ship.GetPersonality().IsHeroic()`,
or make heroic only target ships within the max_distance_from_center range, rather than infinite range.
The second option is less than ideal, as when the heroic ship is not in the center of the system, it will select targets beyond the constrained edge, and then fly back to the center, where it would then lose the target and jump away or land or patrol, depending on other personalities.

**Comment by tehhowch** [comment]
I have an idea about actually making the heroic personality do what is claimed on the NPC personality page, and will PR it soon

**Comment by endless-sky** [comment]
I think I've got a better solution to this. In commit 89091e1 I made it so that if a ship has been outside the "invisible fence" for more than 10 seconds, no ship will target it. The ten second delay should be enough that players can't game the system by moving back and forth across the border, while still being fast enough to keep large clumps of ships from gathering.

**Comment by tehhowch** [comment]
Should the fenceCount check be incorporated in turret aiming? I can understand why we wouldn't care to check if the ship is beyond the fence when determining if a hardpoint that can fire and hit it, but choosing to aim a turret at a ship beyond the fence vs. one in system is maybe a situation to consider.

Other than that, 89091e1 does look like it will solve this issue and make #2713 unnecessary

**Comment by KiLEdEnNis** [comment]
feelsbadman rip Earth tribute
