### ISSUE TITLE
Pirates attacking Escorts without becoming hostile

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2711]
For some reason, Pirates do not remember that I'm hostile no matter how many I kill after a day change (which might be another bug, unless a high enough combat rating can cause that). 

This seems to mean that when a pirate attacks an escorted merchant, they are not considered hostile -- that is, other ships in my fleet ignore the pirate and hitting the hotkey for selecting the nearest enemy ignores them.  This makes targeting them back  hard, as i need to scroll through list of ships to find them (or select the pirate with my terrible laptop trackpad).

**Comment by Amazinite** [comment]
Could you drop your save file here?

**Comment by MessyMix** [comment]
From what it sounds like, your reputation with pirates is too high, and they are friendly. If you attack a pirate, the faction becomes temporarily hostile, as with all other factions. However, upon day change, if your reputation with them is still positive, they revert to being friendly. This sounds like what you are experiencing, and this is intended behavior.

What happens is the pirates are hostile to the Merchant government, and since the ships you are escorting are merchants, they are targeting the merchants, but not you or your owned escorts. Yes, it is hard to select the pirates, but I can't think of a solution without complicating the game mechanics.

**Comment by endless-sky** [comment]
You've probably either been farming Korath, or fighting the Syndicate. In commit 962cf2d I've changed it so the only way pirates become friendly is if you prove you're a *real* pirate by attacking merchants.

**Comment by marphod** [comment]
Farming Korath.  

The issue of concern isn't the pirates being overly friendly; its that when they attack a member of my fleet/a merchant under my escort, they aren't temporarily considered hostile.

**Comment by tehhowch** [comment]
Looks like we need an update to AI::UpdateEvents() to handle cases where the event.Target() is an escort.
This could be extended to handle cases where the escort is hostile to the natives and attacks them, resulting in provocation against the player for leading the escorts to the natives.

That would shut down reputation loopholes too (e.g. Heliarch would attack the player if the player acquires Quarg escorts and brings them to Coalition space)

**Comment by Amazinite** [comment]
A thought on pirate attitudes now, why is it that they only have an attitude toward merchants of -0.1 when other governments have an attitude of -0.4 or -0.3 toward pirates and 0.3 or 0.25 toawrd merchants. Kind of seems like pirates don't really care than much if you kill merchants along side them while other governments REALLY care about pirates and merchants when compared to how pirates care about merchants. Raise (or lower, depending on how you look at it) that value to something like -0.4 or -0.5?

**Comment by tehhowch** [comment]
This is perhaps not entirely resolved -- the Provoke event is not propagated to the player when the AI attacks NPC escorts, or when NPC escorts attack AI ships.
