### ISSUE TITLE
Solifuge Blend file is broken/empty

### ISSUE THREAD

**Issue by Rob59er** [endless-sky/endless-sky#2727]
loaded the Solifuge blend file into blender and all I got was a grey square. I got the file from the google drive folder: https://drive.google.com/drive/folders/0B9aK8dG39P29fmhaWE04RUdtSTM3ZElUeUhCT0xOSm5tajM5OVduaHFHSGZ3Z2ZxN0x2WnM

**Comment by KiLEdEnNis** [comment]
I see the problem
the shapes ARE there but it's messed up: keypad arrows zoom in & out, escape key shows the blender files etc. even though the render button shows it
maybe it's worth re-uploading it?

**Comment by KiLEdEnNis** [comment]
on the bright side: I did find the 3D view

![1](https://user-images.githubusercontent.com/10348657/27958594-325029de-6324-11e7-875e-688c424479af.png)
![2](https://user-images.githubusercontent.com/10348657/27958597-353de514-6324-11e7-8e00-58d81ef8dd21.png)

**Comment by toilethinges** [comment]
You see the gray square because the main area is set to "Render Result(?)." All I had to do to get it to work was set it to 3D view. 
![glx3fxpushg_0f2o4nw_na](https://user-images.githubusercontent.com/16909765/27959380-cd691134-62ec-11e7-8a5e-8af45dd8f8eb.png)

Apologies if I'm misunderstanding, but all the blend files come up with a gray square on the render result for me.

**Comment by Rob59er** [comment]
Only this one does this for me (of the ones I've looked at) clicking f12 fixed it, so I guess I'll close this.
