### ISSUE TITLE
Non-storyline Wanderer missions never extend through the eye.

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2730]
Given the culture is active on both sides, one would expect active trade both ways.

**Comment by tehhowch** [comment]
The default missionset could use extending - normal distance-based location filters do not route through wormholes.

**Comment by jafdy** [comment]
I feel like this is a duplicate . . .
Derpy/@Amazinite would be the person to ask about this as he (/she/they) created the wanderer jobs in the first place.

**Comment by Rob59er** [comment]
was mentioned in steam/discord, might explain the deja vu

**Comment by Amazinite** [comment]
#2046 
>I specify generic because I plan to later do story-specific jobs that are available between certain parts of the story, like special jobs to transport Wanderers through the Eye or assist the Mereti in building their Greenhouses by giving them materials that they don't have.

Waiting for the Wanderer storyline to be done so that I can look where I need to place jobs. Probably only going to do a few which involve traveling through the Eye sicne 1) all jobs that travel through wormholes require fixed payments (see Hai jobs where you transport a small amount of cargo into Human space) and 2) such jobs would be short-lived because of how the Wanderers will eventually leave their northern space.

**Comment by Amazinite** [comment]
We added a few jobs that can move across the wormhole in #5219.
