### ISSUE TITLE
Marauder Arrow (Engines) can't keep up with its own engines

### ISSUE THREAD

**Issue by SolraBizna** [endless-sky/endless-sky#2734]
As hilarious as it is to watch Marauder Arrows overheat themselves in circles around me, either they need smaller engines or *any* cooling outfits.

**Comment by endless-sky** [comment]
It looks to me like they actually run out of energy long before they start overheating.

Plus, they have no outfit space free for cooling. The only way I can see to give them a workable loadout is to forego the shield generator:

```
"Particle Cannon"
"Anti-Missile Turret"
"Dwarf Core"
"LP036a Battery Pack"
"Laser Rifle" 5
"Greyhound Plasma Thruster"
"A120 Atomic Thruster"
"A255 Atomic Steering"
"Afterburner"
"Hyperdrive"
```

**Comment by SolraBizna** [comment]
What I saw is probably more consistent with running out of energy than overheating. The new flashing "soft disabled" display has taken some getting used to, especially combined with the flashing "mission target" display.

Doesn't the proposed loadout leave it with less maneuverability than the regular variant? It's only the Engines variant that I've actually observed "running crippled".

**Comment by endless-sky** [comment]
The real problem is that:

1. an Arrow is *not* a ship designed for combat, and
2. the stock Arrow has such a high engines to outfit space ratio that it's basically impossible to make use of all the engine space on the "more engines" variant.

The best solution might be for the stats of all three Marauder Arrow variants to be adjusted to have less engine space and more combat ability.

**Comment by KiLEdEnNis** [comment]
Arrow not designed for combat
*cough Bow mod*
![bow earth 2 won](https://user-images.githubusercontent.com/10348657/28995403-a78dc956-79e8-11e7-87c4-e6b6c29cf688.jpg)
