### ISSUE TITLE
How do you create a timed mission that involves picking something/someone up and then taking them somewhere else?

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#274]
I'm working on a mission that is is randomly given at the current planet X and involves picking up a passenger at random planet Y, and then bringing them back to planet X, all within a specified amount of time. I don't see any way to easily accomplish this. If I make random planet Y the destination, then I don't have any text replacements to print the name of the current planet and system. I can omit the destination filter to make the current planet the final destination, but then I can't get it to choose a random nearby planet to pick up the cargo and passenger. A waypoint would seem to be the right approach but then I can't make the player actually land on the system, and waypoints don't seem to be able to be randomly chosen. If I make the pickup and return journeys into separate missions, this prevents the use of a continuous timer to ensure that the time taken for both legs of the trip doesn't exceed some limit.

**Comment by endless-sky** [comment]
You can create a second, invisible mission that controls the timer. Or, if this is a one-time mission, the timer can be handled by an event.

Or, you can make the place where you pick up the passenger a "waypoint" instead of the destination of the mission, and add a second mission that pops up when you land on the waypoint planet, and tells you that you picked up the passenger. Then, you can make it so that the first mission succeeds only if the first one is "active."

So, it's doable, but a bit convoluted at present.

**Comment by Pointedstick** [comment]
Can I get it to choose a random waypoint? Or have a second mission that originates on a random planet that's the same random planet mentioned in the first?

**Comment by Pointedstick** [comment]
This is almost possible. The last issue: #523

**Comment by Pointedstick** [comment]
Aaaand that actually works. This is now possible. Thanks!
