### ISSUE TITLE
Version Disagreement

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2744]
I just compiled the latest version, as of Jul 11, the version shown in game is 0.9.6 but the change log has 0.9.7.  The releases page has 0.9.6 as the latest version.
What's happening here?

**Comment by tehhowch** [comment]
Change log is getting ready for release. There was a lot of stuff added and updated since the last version tag was added, and rather than wait until the last minute MZ did a little catching up on the 350ish commits.
We could easily hit 500 since .9.6 before .9.7 is created.

If you compile from source, the version number is never correct unless you first run `git checkout (version number)`

**Comment by VonZorch** [comment]
Thanks.
