### ISSUE TITLE
Use volume instead of mass.

### ISSUE THREAD

**Issue by Festerdam** [endless-sky/endless-sky#2745]
Yes, I know people already talked about something similar in [this](https://github.com/endless-sky/endless-sky/issues/1177) issue, but I think there are some more things that are worth mentioning.

If we count everything in mass, then buying bigger ships wouldn't always mean higher profit. What would mean higher profit would be buying a ship that has stronger engines and resistant cargo room to allow your ship to survive the launch and landing and to be able to launch at all.

Counting the mass instead of the volume gives us the idea that current space ships have enough space, but lack resistance, which like said in the paragraph above, would make the idea hat buying bigger ships is better invalid.

I propose adding some imaginary unit that should represent a specific volume or  m³ or some other unit that tells you how big something is to the game.

I don't think that using  volume instead of mass will confuse players and make the game more complicated. I am more confused that my ship has enough space for 10 tons of feathers, but I am not able to load 11 tons of iron, even if the volume of it would be much lower.

**Comment by SirStigII** [comment]
Not sure why you have a problem with this. Vehicles are limited by weight ratings, not space limitations. Your suggestion would add even more problems. I can carry the same weight of iron or feathers, given the same handholds. The same would stand for spaceships, you need a certain amount of bracing to support the mass, the volume is irrelevant.

**Comment by Festerdam** [comment]
Through the game we say that we are buying bigger ships. We are not saying that we are buying ships with enough engine power to take off and land safely with a higher mass of cargo.

Sure, mass is important. We won't survive a landing on earth with a ship with some extra portion of mercury as cargo whose engines were only designed to allow the take-off of that empty ship on planets with a gravitation close to earth. And we can't put 10 tons of lead in a cargo holder that can only hold 9 tones before breaking, even if we have enough space free.

But I think that volume also is important. We can't fit the amount of substance1 which would weight 3 tons in a space where 3 tons substance2 would fit perfectly, if substance1 has a lower density.

(After summarizing this. I got the idea of not removing mass completely, but also add volume. Using them both would make the game extremely complicated only for some details, therefore I thought creating a Unit that unifies them both, or something similar.)

**Comment by Amazinite** [comment]
Using volume instead of mass would mean that the calculations of acceleration (thrust/mass) and turn rate (turn/mass) would make no sense, and using both would just add complexity to the matter (e.g. this 10 tons of feathers takes up 20 m^3 of space, you can carry the weight but not fit the volume). 

To add volume alongside mass means that we would need to create some way to give each commodity in [this file](https://github.com/endless-sky/endless-sky/blob/master/data/commodities.txt) a volume or mass, then decide whether volume or mass is used in a bunch of scenarios (e.g. what exactly does a cargo mission base its decision off of when giving a certain amount of cargo? Is the payments based off of mass or volume, and if you say both then we need to change how payments are calculated. What about non-job trade commodities? Do they have a set volume or randomized volume since you're just picking up general items?). 

Then we'd need to go through all 146 ships and determine how much volume each can carry alongside its mass. Then all 279 outfits would need to be changed up because it doesn't make sense under this system that they would all have the same mass as they do outfit space (secondary weapons excluded, which only match mass and outfit space when full on ammo), and outfit space would be akin to the volume of an outfit under this system.

**Comment by Festerdam** [comment]
Now I think that this issue should also be closed, given  the number of changes needed and the over-complication of things, if it would be added. It simply isn't worth it for such a detail.
