### ISSUE TITLE
Who pays all these space taxes that are repeatedly mentioned?

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#275]
The whole human part of the galaxy is covered with governments, and taxation is prominently mentioned and discussed in various storylines. The Navy is funded with taxes; the Paradise planets pay ten times more taxes than the Dirt Belt planets; the Free Worlds' taxation model is weird and cool, etc. But we as the player never feel the impact of any taxes at all. There's no income tax, no sales tax, no personal property tax, no landing fees, no nothing! Say, who's paying for all those huge Republic ships and the sprawling Republic government, anyway? Are we really to believe that all starship-related activity is tax-free throughout the galaxy? The fact that taxes are repeatedly discussed but the player feels no impact from them weakens the concept and makes it feel slightly surreal. If you can get out of your tax burden 100% simply by living on a spaceship, well gosh, who wouldn't want that!?

Obviously taxes are no fun, but I think adding them in some form could strengthen the game's presentation of the storyline and provide interesting gameplay elements. For example, sales taxes applied to outfits could nudge players to shop on planets with lower tax rates, mimicking a real-world phenomenon. An income tax levied on missions completed in certain systems would do the same. Maybe the paradise planets levy a 15% income tax on any deliveries or commodity profits, but the Dirt Belt planets only levy a 5% tax. That would be interesting and really viscerally bring that element of the game world to life.

This could also provide a damper on the tendency of player net worth to snowball quickly. Taxes could be run through a multiplier determined by your net worth. Once you have 20 million credits, maybe you're paying like a 50% income tax. This could open the door to tax-related missions, where you smuggle untaxed goods onto high-tax planets, or work to lobby some government for lower tax rates.

**Comment by Oeleo** [comment]
I totally agree, like that it will become harder to make money when you begin to become rich, and "it's getting harder and harder to avoid going into debt" will finally be true !

**Comment by endless-sky** [comment]
In earlier versions there were a bunch of different ship licenses you 
had to buy (freighter license, transport license, capital ship license, 
etc.) but I took those out because people found them so annoying.

It's hard sometimes to balance realism with actually enjoyable game play.

**Comment by Oeleo** [comment]
Sorry but are you sure that you posted in the good issue ? I don't understand. But yes for the last sentence that's one of the biggest challenge...

**Comment by airtroop392** [comment]
Sorry, but what real purpose does this serve? Realism is cool (just look at ARMA), but there is a line which has to be drawn. Games are meant to be fun- simulators are accurate, and games which are simulators are normally both, but as with all things, you must have a reason for doing things. The death benefits are an incentive for the player to improve his boarding equipment and to hire more crew, so as not to incur the wrath of their fallen crewmen's families, or perhaps even to look towards another prospective enterprise, one with less risk and an equal reward. What purpose does a landing or a personal property tax have, other than to annoy the player? Sorry if I'm coming off a bit harsh here, that's not my intention. OK, sure, you do make some good points- taxes <b>are</b> repeatedly mentioned in the story, but are they really that important, to the plot or otherwise? I would argue that the battle between the Republic and the Free Worlds is not that of a tax difference, but a political and socioeconomic one, in addition to a feeling of mutual mistrust, and, on the Free Worlds side, a strong feeling of unimportance and oppression. <i>Dune</i>, by Frank Herbert, paints a narrative of a young man who becomes a god and attains a cult of personality, even though it is evident to everyone around that he is no such individual. For obvious reasons, Mr. Herbert did not include address or explain every single thing- he often used leading names and vague descriptions to paint a thousand words on subjects like science. Pseudoscience is used in Star Trek: TNG and TOS in the form of technobabble and multiple attempts to explain the development of society and culture through vague timelines and events. I realize that I'm rambling here, but at no point was there a scene in which Jean-Luc Picard goes to the grocery store and gets his groceries in order to explain the phenomena of Star Trek: TNG's moneyless society- there was no reason, and instead, the issue was explained in under five lines of dialog in one of the TNG movies.

**Comment by Oeleo** [comment]
Maybe that it's bothering you, but I think that most of the player find this game too easy at this time, that's why that in addition to make the game more realistic, it will slightly enhance the game play. I don't know if you are at the begining of the game, but when you have ~3 bactrian and you can farm reactors with a price beetween 5 and 14.000.000, the game become too easy and you will quickly have 1.000.000.000 money, so a tax could resolve that. The tax shouldn't be for those who have a little ship but for those who have at least one good ship, and it will be little at the beginning and big at the end. At one point of the game you have money for several years with only the pay of your crew, even if you didn't particulary tried to make a lot of money.

**Comment by airtroop392** [comment]
Money has its use throughout the entire game- you need ships to take tribute, you need ships to take Korath ships, so forth. I've spent the last fifty hours of gameplay or so doing nothing but collecting money and adding more ships to my fleet, and I still don't have enough to take tribute from most planets. I don't find the game especially easy, and I don't see the point in a tax simply because I doubt it could add anything to the game except a slight annoyance to the player. Unless the tax is going to come in the form of the government taking away a portion of my earnings each time I complete a mission or deliver a load of cargo above X tons, I don't really see how it could affect me or anyone else for that matter, in any way.

**Comment by Pointedstick** [comment]
Haha, big shocker: nobody likes taxes :p

I think that's kind of the point, though. Taxes modify behavior. As a gameplay element, it can do the very same with player behavior, as well as drive some interesting plot points and bring home the narrative a bit more. I mean, the introduction of the galactic civil war involves the future Free Worlds planets refusing to pay their taxes!

**Comment by airtroop392** [comment]
I think I'm beginning to see where you're getting off with this- taxes as a way to prompt the player to pick sides is actually a pretty genius idea, and I now believe that would justify the implementation of such a system.

**Comment by Oeleo** [comment]
Tribute will not really add you money, the better way of winning money is the reactor farming. Before than I discovered this way, I farmed pirate system, but it was long and hard to make money, because pirates always tried to disabled ships that I just took. But as I said when you have several bactrians, you can have 100 millions by hour by taking reactors of 5-10 or 14 millions (especially on the republic biggest ships, and after Korath's ships), seriously money become no more a problem. Now after 100 hours I have 1.400.000.000 of money, just by making a few of hours of reactor farming. And as I said in an other issue, when you will have ~8 Bactrians you can farm Quarg ship, and with **118 millions** (I just calculated) on each ship I let you calculated what you can make in one hour...

**Comment by endless-sky** [comment]
I think the only thing taxes would do is to add even more complexity. Because (unlike mortgages) you can't make any choices that would increase or decrease your taxes, all they would be is a constant drain on your income, and existing things like crew salaries already do that.
