### ISSUE TITLE
Folding Ship Lists... Maybe

### ISSUE THREAD

**Issue by tick10** [endless-sky/endless-sky#2769]
This is the first time i've made one of these, I just think that it would be helpful for later in the game if you wanted lots of carriers in your fleet and probably not that hard to implement (emphasis on think)... 

But anyway I did search for this and can't find anyone mentioning this in the steam threads here or the google group... I might be using the wrong word to describe it. 

But basically if i have 30 (or many, many more) barbs in my fleet when i open the player info pane i think it would be nice if i could "group" them all together and close the set of barbs and it just leave the name blank and have the little arrow/triangle in its place showing you you can open it up to show my crap load of barbs instead of scrolling through all of those freaking fighters or whatever to get to the ship i'm looking for. I think this would be helpful for people that like to collect different kinds of ships and as i mentioned before people with more than one carrier and want to fill them as in my example. 

Note: I'm pretty sure folding is the correct term, I can't remember what it is called exactly but i believe thats what a similar feature in vim is called. ha

**Comment by tick10** [comment]
I just wanted to add that a search feature might also be nice for someone with many ships...

**Comment by tehhowch** [comment]
These would be nice features indeed. I don't think MZ will work on this himself, as large fleet management is low priority, but there are others who may take a crack at it though.


Some thoughts for an implementation:
 - perhaps automatically reorder ships by their number key binding status, placing the second and onward ships immediately after the first ship in the control group
   - issue: players may want a different order, where some non-bound ships come before some bound ships, and this will override their preference
 - addition of a folding graphic element in front of the members of command groups will require changing the column widths to accommodate the new column
 - folding a command group should not remove that groups ships from walking through each ship individually, on the ship detail pane
 - folding could simply result in not drawing that command group's second and onward ships, with the row for the first one replaced by "Command group $number"


Re: search. What should get searched? Ship name? Ship model? Should a successful search open that ships info pane, or just highlight it's entry?

**Comment by ghoulavenger** [comment]
Honestly the way I order my ships is by squadron. So if I wanted to fold ships, I would prefer custom groups for my squadrons. Usually my squadrons are the same ship type, so I'd be fine with this limitation if it was necessary for some reason -- but for carriers with fighters I could see this also being beneficial, the carrier being the leader of the group. But that doesn't mean that I expect these ships to be on the individual carrier that can still be determined by the code in other ways, since when you deploy fighters you deploy all of them instead of individual ships (so they're all out in the field anyway, which means the groupping is just for organizational purposes and not practical ones). Similarly I think this would be great if you could move entire groups at a time instead of individual ship re-ordering (the ship list is currently only drag and drop one ship, not multiple).

Ideally what I would like is a marker that I could use to mark ships as part of a group, this can be by color (visually pleasing but very limited since the colors need to be legible on the viewing pane and sufficiently different to be easy to differentiate, basically ship names display in this color or have the color in a column next to them) or numeric (less pleasing but much more open to large and varied fleet management). A final option could be groupping by name, but that doesn't add very much functionality over numbers or colors, so it seems a bit excessive to me (but maybe somebody wants to call their fleet Rogue Squadron or something).  Then this group could be folded.

On searching the ship list, I really don't think a search should open the info pane but rather highlight all matching entries. As far as search modalities, I can see a few being particularly useful:

- Model -- Useful if you want to modify multiple ships at once at the outfitter, especially if it can sort
- System -- Especially useful if you're parking ships, hard to implement well though, other than perhaps selecting the system of a ship on the list and highlighting all ships at that system.
- Outfit -- Without the lack of storage capacity for outfits I find myself stuffing outfits on ships that I have parked somewhere else, if I can highlight all ships with an ionic afterthruster or electron beam etc. it would be useful. This is the only one where you would absolutely need a text search field, since highlighting model and location can be done by clicking on the model/location fields of a similar ship.

**Comment by tick10** [comment]
Yeah that all seems great to me. Sorry, i'm no code guru myself. I have fiddled with stuff here and there but i basically just know enough to be dangerous... ha This project has definitely peaked my interest though so far i'm loving it and the community seems great also. I might try to take a crack at it if i can find some time to sit and figure it out... If not this, i would be happy to help with some stuff thats higher priority. Is there a list somewhere of things that need to get done besides just cruising around here and finding stuff people suggested like my op? 

But as for your question i was just imagining a simple way to search for either ship name or ship model or even the current system would be useful, similar to the map search feature. I would think just highlighting the correct ship or ships if there is multiple with that name or multiple with that model in the list, just to help you find that random leviathan or whatever it may be. 

And honestly it could be very helpful FOR grouping in the way we were talking about. Type in dagger to select all your daggers instantly and move them into a group or smaller groups as you see fit depending on how you want to organize. Then double clicking on it or clicking the tab itself once its selected to enter the Ship Info pane i think would be fine.

**Comment by tick10** [comment]
As for ghoulavenger's comment i hadn't thought about that yet but that also makes sense. I haven't really organized my ships like that much but i can see why that makes just as much sense as keeping them all together, esp when your trying to figure out how many fighters and drones you can have active and max out your carriers...

PS in the current master moving entire groups of ships that are selected is now possible. I don't know when it was added but that would have been something id mentioned also if it wasn't already fixed. :)

**Comment by AdamMil** [comment]
The game AI Wars lets you command thousands of varied ships on screen at once, and manages to organize them in a reasonably useful way. It may be useful to use a similar design.

They organize enemy and allied ships in a similar way on the opposite side of the screen so you can also attack certain enemies as easily as you can select certain of your own ships.

**Comment by VonZorch** [comment]
It would also be helpful to be able to assign group numbers from the info pane.

**Comment by endless-sky** [comment]
Since this is an Escape Velocity clone, the game is mostly designed around single ships and small fleets. It supports people who want to amass enormous fleets, but UI changes that are only to make things easier for those folks are low priority.
