### ISSUE TITLE
Ship Weapon Idea: long range, slow firing sniper weapon

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#277]

**Comment by thenerdfreak** [comment]
Long-range weapon that generates a ton of heat, uses a ton of energy, fire extremely slow, has a firing delay (charge up) of a few seconds, and takes up a lot of outfit space (double the particle cannon) but is extremely accurate and temporarily overheats the ship it hits regardless of size (think EMP sniper)
or better yet, how about an unlockable particle cannon turret (like how the plasma turret is eventually unlocked)

**Comment by gchapyzh** [comment]
Always wanted to to see Navy Gunboats have their one turret emplacement have something like that.

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!
