### ISSUE TITLE
RNG state not saved in save file

### ISSUE THREAD

**Issue by AdamMil** [endless-sky/endless-sky#2770]
Since the RNG state isn't saved with the save file, it's all too easy to fly around with a big fleet of defenseless Star Barges (best price to cargo ratio of any ship), never taking any losses. You just reload if you run into trouble. What do you think of this?

I plan to fix it myself in my own game in any case, to force myself to plan more for defense. I only ask about it here to see if the author thinks it should be changed. If not, I'll just hack it in locally. If so, maybe I can do it as part of an iron/bronze-man mode and do the work to integrate it into the opening dialog text with an in-game reward/penalty...

**Comment by Hadron1776** [comment]
> Since the RNG state isn't saved with the save file

RNG is just re-rolled every time you land or jump into another system.

**Comment by tehhowch** [comment]
Even if the state were saved in the save file, what's to stop someone from altering it in their save file? Even in "iron man/hardcore" mode? One cannot simply disable the users access to their hard drive...

**Comment by Hadron1776** [comment]
Theoretically, the game could be saved as a binary...

**Comment by XHawk87** [comment]
This is a single-player game, so attempting to actually prevent players from cheating would be a waste of everyone's time. 

However, if what we're talking about is actually just enabling players to play a more difficult variant of the game, than that is adding value to the game by keeping players at a higher skill level entertained for longer. 

It is also worth considering that even a mechanic to 'prevent' cheating that can be easily subverted is still useful as a guide for players who wish to play the game the way the developers intended. 

In this case, I am not sure whether this would be an improvement in gameplay or not. For one thing, saving the RNG state would only produce the same results if the player takes the same set of actions. They could vary what they did slightly in order to produce wildly different results, in order to get around whatever caused the undesirable outcome that caused them to savescum. It might have to be done in a clever manner to ensure that the same outcome occurs on reload.

Even if the same outcome were to occur each time the player reloaded, it will just be like playing the same level of a game with static content over and over until you learn how to beat it. One of the selling points of Endless Sky is the dynamic generation of its encounters, so unless you're following a scripted mission, you never quite know what is coming next. 

I think if we're looking for a more challenging variant to the game, it would be better to add a hardcore mode (#362), where if a player chooses to play that mode, they will have to face consequences for their errors, rather than automatically reloading an earlier save whenever their flagship is destroyed.

**Comment by AdamMil** [comment]
The RNG isn't only "rerolled" when jumping or landing. If you take off, reload the autosave, and take off again, you'll see a different composition of ships outside.

The save file doesn't need to be saved in binary to prevent most save file tampering. It would be fairly simple to detect most tampering. (What the game does upon detecting it, if anything, is a separate question.)

AFAIK there is no randomness once you've landed on a planet - at least there's no need for there to be - so there's no issue of the player being able to take a different set of actions to change the outcome. 99% of saves are made on planets because that's when it autosaves. (I've never even tried to save in space.)

As for the dynamic nature of the game's encounters, that wouldn't change; it's just that the player couldn't reroll the current situation on demand. As it is, the player can always know what's coming next because they can reload until they get what they want (either a safe takeoff, or a fight, or whatever), so this would actually enhance the "you don't know what you'll have to deal with next" aspect.

It's useful to make 'cheating' harder for players (like me!) who don't want to use lame tactics but have insufficient will power to hold themselves accountable all the time. Even if it's possible to circumvent with a memory editor or by tweaking and rehashing the save file, that would be too much work. But if I can just press Escape and click Load, then that's very easy and I'll be tempted to do it all too often.

-----------

Anyway, I think storing the RNG state and hardcore mode are separate things:
* Storing the RNG state in the save file just prevents players from rerolling to prevent all pirate attacks. You could always reload an earlier save if it turns out that sending your defenseless Star Barges through pirate territory was a bad idea, but you couldn't save scum your way through.
* Hardcore mode might limit your saving by giving you only 1 or 3 autosaves or even by disabling reloading entirely, but it doesn't have to store the RNG state.

I'm personally interested in both, but this question is mostly about saving the RNG state.

**Comment by endless-sky** [comment]
Unfortunately, early on in the game it's entirely possible to take off from a planet and have a powerful pirate sitting close enough that there's literally no way you can escape.

**Comment by AdamMil** [comment]
Ideally that would be fixed because it's not a good experience even if you _can_ reload, but I realize it may not be a simple thing to do. (I think realistically a pirate wouldn't be able to get deep into Republican space and/or wouldn't be foolish enough to attempt it, but I do see a lot of pirates committing suicide attempting to rob freighters right under the nose of big navy patrols... But without those guys around the safe area might be too safe to provide excitement for the player.) Of course the player could reload the previous autosave; they'd only lose a few jumps, but that's not nice either.

**Comment by VonZorch** [comment]
@endless-sky Yeah, had that happen too many times to count.  But it's only a minor annoyance, just reload and try again, eventually you'll get your tiny boat launched without that heavy pirate ship smoke testing you in under a second.
