### ISSUE TITLE
limit reputation gain for a time frame rather than removing it completely

### ISSUE THREAD

**Issue by Kryes-Omega** [endless-sky/endless-sky#2771]
One big reason for using `-0.01` for government relationships, was that it made (for example) Gov A hostile to Gov B, while preventing the player from farming Gov B for reputation for Gov A. This helps keep the story running properly, and prevents the player from farming a government too much, but takes away from the original intent of the more dynamic government relations system. So, for governments like the Quarg where farming them for technology then farming pirates to gain back reputation was more of an issue than story,

My idea: Rather than completely removing the ability to gain back reputation with governments, add a system wherein you can only gain a certain amount of reputation with a government per a certain amount of time. say, 100 reputation per week in game. That would cut down on the farming issue, and keep the governments relations more dynamic.

**Comment by tehhowch** [comment]
Seems like something that could be handled in a manner akin to how depreciation is tracked.

The simplest logged value could just be (current rep) - (previous day's rep).
At the start of each "day" we would need to pop the oldest logged entry in that government's rep list, sum the rep list, and then when processing ShipEvents, tally the rep change per day per govt and make sure it doesn't exceed the value of `cap-summed_list`

**Comment by Hadron1776** [comment]
The limit should be customizable, though

**Comment by Amazinite** [comment]
I don't really see how this fixes anything. This just reverts the current system of things back to the old system of grinding reputation back to positive but adds an extra barrier of having to actually be at your computer in order to jump systems every so often instead of being able to hold position over a pirate planet. The grind of the old system would still exist in this new system, but just be worse.

**Comment by solardawning** [comment]
Yeah, I'd place this squarely under "not fun".

**Comment by AdamMil** [comment]
I think a better idea is the concept of a grudge. If you do something really bad to someone, you can't always make up for it by doing something nice next week. People weight bad actions more heavily than good actions. So if you just act negatively against both, maybe it works a little bit in the beginning but eventually they both end up hating you.

**Comment by Bladewood** [comment]
"If it has stats, we can kill it."

**Comment by ghoulavenger** [comment]
I'm honestly not sure how to feel about this. On the one hand, I'd like to be able to farm the quarg, then do missions involving the quarg without save file editing (because those skylances completely break the game, even just two of them are better than a full complement of just about any other weapon), but on the other hand, theres a reason why the game tries to make you do meaningful decisions (if you want to be the good guy, you can't act like a pirate). If you want to be a pirate, people won't like you it is just that simple.

But if you insist on being able to force redemption, then redemption missions for these "specific" governments might be the better option. But this has the potential of being much more grindy than simply killing government enemies, and expensive since you'll likely have to bribe the governments to land on their worlds, and possibly want to bribe ships not to attack you. But it does eliminate the trivial nature of just killing pirates for favor while offering a path for redemption.

**Comment by Elyssaen** [comment]
I don't like this particular idea (as @Amazinite says, it doesn't seem to solve anything), but I do think the `-.01` system is far from ideal.

Reputation – and tribute – both seem like systems MZ used to parallel Escape Velocity, rather than really liking. He's totally right to then notice the problem it poses with, for example, Quarg farming, but `-.01` attitude toward never felt like a good fix to me. It essentially just bypasses a reputation system that a) we all admit doesn't work, and b) isn't really used for much. I mean, look at every instance of the word 'reputation' in the Data files:

1. The +30 you can get with the Coalition/Heliarch from various missions, relevant because there's no other way to gain reputation with them.
2. Required values to land, no higher than 100, when our save files often have five figure reputation values.
3. Setting negative or positive to represent war/friendly states.

We can easily have 50,000 reputation with the Syndicate, and the only reason we'd want 49,900+ of that is to be able to kill every defence fleet they have without upsetting them. So the only real use for the reputation values we realistically build up is to break realism in half.

A very different way to do it might be:

1. Jobs/missions regularly gain you reputation, so we're not only really getting it from destroying enemy ships.
2. ES becomes a little _more_ like EV in having reputation 'rankings' (e.g. Pillar of Society) and perhaps even both local and faction-wide reputations (faction-wide might be an average of every local spaceport rep), to encourage player engagement a bit more.
3. Higher reputation makes more jobs available, is used to unlock access to some outfits and ships, and is required for missions to a much greater extent. (So you might read, "Make a name for yourself around here and we might have more work for you" at the pause of a campaign.)
4. Revise atrocities into felonies, and have a felony min your reputation not just to 0, but to -100 or -1000. Make that a threshold that _cannot_ be passed from below normally. Then make murder a felony.
5. Create some redemption missions as @ghoulavenger suggested. Different factions would be different: the Quarg might give no second chances (yet), the Hai and Syndicate might give quite a few redemption opportunities (for different reasons), and the Republic might only give you one second chance.

**Comment by Bladewood** [comment]
I agree with (1), though there are probably going to be a few small problems around that.
I have no idea what (2) means.
Agree with (3).
(4) is an interesting idea, though again I see some problems, such as with the Deep Archeology missions. I'm also kind of worried that it will make the game too unforgiving to players.
(5) sounds pretty nice.

**Comment by KiLEdEnNis** [comment]
what if reputation just caps at say 50 for governments like the Quarg, and make it very hard for the player to gain rep for those govs

**Comment by Elyssaen** [comment]
@Bladewood: To (1), I think there's only a problem with jobs giving reputation as long as there's a problem farming reputation to get a free pass for hostilities. 

To (2), by reputation rankings I mean like combat ratings. Just like fearsome scrapper or dread warrior, you'd have upstanding citizen or pillar of society. It's just part of making it a little more engaging. Right now there are three shades of blue, but they go by very quickly. Then, by local reputation vs faction-wide, I mean like Elite does. Both the Republic, and Sirius (well, the planet Relic) would have reputation values for you. The Republic reputation might be an average of all your local reputations, or just loosely based on it. Then, if local reputation mattered for jobs and some missions, the player would be engaged to build it up.

To (4), you might be right that it's a bit unforgiving. I think there are ways that could be tweaked, while still trying to maintain a general sense that killing a faction's people isn't something meaningless you just trade your 'reputation coupons' in for.

**Comment by marphod** [comment]
There's a few issues with Reputation, all of them bundled up here.

-  Reputation effects seem to based around a 3-4 figure value, where real game values are significantly larger
-  Reputation gains and loses don't take into account current relationships and are purely linear increases/decreases (as opposed to the stronger the reputation, the harder to change)
-  Reputation is way too based around how many people you kill rather than all your actions.

Proposal:
To address how to make reputation more generalized:
-  Add a concept of named (and possibly hierarchical) sins and virtues (called Virtues hereon)
-  Let missions and/or events specify if they trigger a Virtue, on behalf of a Government and the magnitude of the virtue (a numeric value)
-  Let the magnitude be a simple number, or a value based on the current mission or action (I know that [number sentients  involved], [seized/contraband equipment/goods value], and [mission reward] will be needed, maybe others)
-  Let the Virtue definition specify a means to normalize the magnitude (Murder's normalization is 1, every death is significant, whereas the Contraband normalization may be 0.0001, as the penalty is per 10,000 credits of value.) 
-  Let governments specify how much they care about each Virtue independently from how it views other Governments (for instance, Pirates know they might die, so they don't care as much about the Murder Virtue, but care a lot more about the Stealing Virtue; the Republic doesn't care as much about the 'Attacking (drone)' Virtue (child of the Attacking Virtue) but really dislikes the 'Murder (civilian)' Virtue, the Coalition really cares about the 'Transport Mission (heliarch)' Virtue but less about other Transport Missions; the Hai care a lot about violence so the Attacking Virtue is a big deal for them)
-  When a Virtue is triggered, calculate the Reputation Modifier by Government(Relationship)* Government(Virtue Importance) * magnitude * Virtue normalization factor
-  Some governments might need to be able to specify if a Virtue should have a positive or negative impact, regardless of the relationship they have with the affected government.  (Naval Humanitarian Corp might approve of the Assist Ship virtue regardless of ownership of the ship)


Proposal:
To address the unbounded nature of reputation values and existing relationships impacting reputation changes:
-  When changing a reputation, use a Scaled Reputation Modifier of the log(Reputation Modifier) (base 10? natural log? some experimentation will be required) rather than Reputation Modifier to represent that the reputation impact of grandiose actions aren't linear with the size of the action
-  further, consider dividing the Scaled Reputation Modifier by the log(abs(Current Reputation)) (base 10) if this value is greater than 1; this represents that it is harder to change a strong impression of a person than a weak one.
-  Governments might need a Atrocity Threshold for certain acts, where if a specific negative Virtue's magnitude is large enough, reputation gets set to a large negative value if the normal modification process would leave it too high.  


Well, that took way longer than I expected to write.
