### ISSUE TITLE
Invisible Escort

### ISSUE THREAD

**Issue by TurkeyMcMac** [endless-sky/endless-sky#2777]
![screenshot from 2017-07-18 06-46-08](https://user-images.githubusercontent.com/28828704/28364532-cea475e2-6c52-11e7-8a95-3a727a857206.png)
As you can see, this screenshot was taken in Durax. This showed up as part of my fleet when I pressed 'i', but when I selected it, I found that it was invisible. It was also completely inactive and, as shown here, insubstantial:
![screenshot from 2017-07-18 06-46-31](https://user-images.githubusercontent.com/28828704/28365278-e184d654-6c55-11e7-86fc-b051eb4f7abb.png)
A while ago, I accidentally left my fighters in Durax when I exited the system. I suspect that this fighter somehow bugged out while I was gone.

None of my fighters, including the one pictured, show up in the on-screen fleet list. This seems like it is probably also a bug.

Unfortunately, I have no other information on this phenomenon, so I am sorry of this is unhelpful.

**Comment by tehhowch** [comment]
Looks like it lost its sprite definition in your game save.

Regarding why it is just sitting there, what commit are you playing on?

**Comment by TurkeyMcMac** [comment]
I just updated, but I think that the commit was `1812b34` at the time the screenshots were taken.

**Comment by tehhowch** [comment]
The lack of fighter display is due to insufficient space for the escort display panel. It ranks ships based on their cost, from highest (bottom of the display) to lowest (top or not shown). 

Was that ship's definition (in your save file) missing the line "sprite ________"? If it's there, it would come right after the name line.

**Comment by TurkeyMcMac** [comment]
I just checked, and the line is there. It reads, "sprite ship/chaser."

**Comment by tehhowch** [comment]
can you post the whole ship definition, inside triple backticks? Or your save.
(if the issue persists after a restart)

**Comment by TurkeyMcMac** [comment]
```
ship "Korath Chaser"
	name "Sesk Perwasi"
	sprite ship/chaser
	attributes
		category Fighter
		cost 671000
		bunks 1
		drag 0.9
		"engine capacity" 30
		"gun ports" 1
		"heat dissipation" 0.9
		hull 900
		mass 40
		"outfit space" 92
		"required crew" 1
		shields 2300
		"weapon capacity" 25
	outfits
		"Korath Fire-Lance"
		"Small Heat Shunt"
		"Generator (Furnace Class)"
		"Thruster (Asteroid Class)"
		"Steering (Asteroid Class)"
	crew 1
	fuel 0
	shields 1315.3
	hull 900
	position -42.724951 18.688899
	engine -7 23 1
	engine 7 23 1
	gun 0 -28 "Korath Fire-Lance"
	explode "tiny explosion" 20
	system Durax
	parked
```
Upon inspecting the save file, I realized that it was parked (although I probably should have noticed that before.) When I unparked it then entered the system, it was there, flying around normally. When I parked it again, it disappeared, but was nowhere on the map that time, having seemingly parked properly in a system containing no planets on which one can land. This save is from before these experiments.

**Comment by tehhowch** [comment]
This issue is then not about an escort being invisible, but about parking ships in systems without planets and then going there. 

This can be fixed by not allowing the player to park ships in systems that have no landable planets.
Anyone who choses to then edit their save file to park ships manually will then have this same thing happen - it doesn't impact gameplay, but certainly seems strange if one investigates.

**Comment by AdamMil** [comment]
Perhaps we can ignore attempts to select parked ships, then.
