### ISSUE TITLE
macOS Sierra: reorganizing ships in info panel crashes game

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2796]
Title says it all. I'm landed, and using the info panel to reorganize my flagship. It crashes the game. Savefile attached.

[Roscoe Skylar.txt](https://github.com/endless-sky/endless-sky/files/1166795/Roscoe.Skylar.txt)

**Comment by Rob59er** [comment]
I can confirm, but it doesn't happen 100% of the time

**Comment by gunqqer** [comment]
ANOTHER MAC USER HERE, CAN CONFIRM THIS DOES CRASH THE GAME

**Comment by MessyMix** [comment]
Oops looks like I broke the game.

![image](https://user-images.githubusercontent.com/20450076/28483273-01966f20-6e9f-11e7-9d21-5c66f67857f3.png)

switched flagship in outfitter, can't depart now. buttons are messed up.

to replicate: take my save, jump to the remnant system directly north, land, shipyards, switch flagship to Bactrian (parked), and sell the gascraft. lol rip

**Comment by Bladewood** [comment]
The same thing happens if you end up without a flagship in any way.
It even happens at the start of the game, if you refuse to purchase a ship.

**Comment by gunqqer** [comment]
When launching from Terminal after the game crashes all it says is "Segmentation fault: 11"

Just thought I may as well put that here

**Comment by tehhowch** [comment]
@gunqqer can you build from source? if so, compile with debugging symbols, and then start endless sky via the debugger. I think for Mac this is still `gdb`, so (for example) if you normally type `./endless-sky` to launch from terminal, you would type `gdb endless-sky`.

Then when it fails you can type `bt` and copy the printout that it gives (bt is gdb shorthand for backtrace). That printout will indicate functions being called, and the lines within those functions that were active when the segfault occurred.

If not, oh well. MZ has a mac so in theory he can obtain this information firsthand.

**Comment by gunqqer** [comment]
I'm launching through terminal using the steam build. Using

 ~/Library/Application Support/Steam/SteamApps/common/Endless Sky/EndlessSky.app/Contents/MacOS/EndlessSky 

and just plopping that in terminal. I would be compiling but idk how and it requires downloading xcode whch is just a pain. If you want to tell me how exactly do to so I could maybe.

**Comment by tehhowch** [comment]
No mac, and the wiki on building for mac is a bit rougher around the edges than it is for linux :innocent: 

If perhaps a video can be posted of the behaviors which have a high tendency to cause this error (vs drag behaviors that don't seem to trigger it nearly as often) that can help.

**Comment by gunqqer** [comment]
I won't be able to do video, my computer is incredibly shitty and doing anything and trying to record itself would kill it. I am upgrading later this summer hopfuly but for now... I can't help with video.

And is it worth compiling the game from source vs just using steam?

**Comment by tehhowch** [comment]
steam means stuck with steam release and no new code behaviors, or new data that needs code support (you can drop in data-only updates that don't need code changes)
compile means freeeeeedooooooooommmmmmm
your choice :rocket: :rocket: :rocket:

**Comment by gunqqer** [comment]
well how hard is it to compile on OS X? Is it 10 minutes and download time or an hour and download time.

**Comment by tehhowch** [comment]
I suspect for someone who has not compiled on OS X that it is in the hour+ window, since you will need to download XCode, download the 4 libraries, build one, adjust paths, and then build Endless Sky - in addition to solving / figuring out any kinks along the way.
Here's your TODO: https://github.com/endless-sky/endless-sky/wiki/BuildInstructions#mac-os-x

**Comment by gunqqer** [comment]
well is that hour just working on it? Because downloads are stuff I will have to do overnight, I get 2.21MB down (For all my downloads that about what I get).

**Comment by tehhowch** [comment]
You'll need to also set up a Git repository of endless sky (to download the code that you plan to build, and any future updates to that code).
1. set up your Git repo (you probably have git, but you might not - if the terminal doesn't show a help page when you type `git --help` you'll have to install it too) by running 
`git clone https://github.com/endless-sky/endless-sky.git .`
from whatever directory you want to contain the game (I have mine in `~/projects/endless-sky`)
2. follow the stuff on that wiki page section
    - download XCode + the 4 libraries
    - build SDL2
    - etc

That's all the detail and help I can give you, since I have no mac to work on, and have not used XCode, or built SDL2.
I think you'll need an hour of fiddle-about time at minimum to get oriented within XCode and solve any errors that come from wrong paths to files, in addition to however long SDL2 takes to compile

**Comment by gunqqer** [comment]
compiling? xkcd.com/303 

Well, I already have git, cloning endless sky right now and downloading xcode. Annoyingly I can't limit downloads from the app store (that I know of) so i can't watch youtube on my ipad... shitty internet... 

Thanks for the help, though

**Comment by gunqqer** [comment]
@tehhowch I know you don't know much about OS X. but... I'm stuck. Other than a few semantic issues (Overrides not marked as such) I have one problem I can't figurte out: 'mad.h' file not found. I could have fucked up one of the libraries but I can't find out what.

**Comment by tehhowch** [comment]
That sounds like libmad - you need the `-dev` version of it

**Comment by gunqqer** [comment]
@tehhowch so in my libmad folder I have a file called mad.h, is this the right file? Do I need to put it somewhere else (It's in ~/ )? Do I need to download a different version and do something different?

**Comment by tehhowch** [comment]
In XCode there should be a way to specify where various "Include" files are located (these are the header files that tell the program you are building how to interface with the external libraries it needs). You should be able to add the folder containing `mad.h` to this include path, or move it to wherever the path is already. For sanity in your build environment, I recommend moving your `I downloaded this to build ES` libraries into something like `~/es/libraries`, while the actual endless sky git repo is in something like `~/es/endless-sky`

**Comment by gunqqer** [comment]
ok, so, I did [this](https://forum.juce.com/t/xcode-link-binary-with-libraries-and-introducer-external-libraries-to-link/14739) and linked it to  -/es/libraries. It didn't like that. I linked directly to mad.h which it then didn't like it using <mad.h> instead of "mad.h" so I changed that and now... ```ld: library not found for -lmad.0.2.1
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by tehhowch** [comment]
You may need to upgrade your library version from 0.2.1 to the version that you downloaded

**Comment by gunqqer** [comment]
@tehhowch Ok so I may not be installing libmad correctly, I can't find ```libmad.0.15.1b``` and the build instructions say stuff idk what it means. How do I edit the script (I can find the script) to edit the configure script to not default to "i486" for x86 architectures?

**Comment by tehhowch** [comment]
:man_shrugging: 

In the endless-sky repo there is a folder `EndlessSky.xcodeproj`, containing the file `project.pbxproj`... You may be able to achieve what you need by editing this file.
You should be able to accomplish the same by changing the project options (targets?) from its menus. Which menu, I can't say.

I will add that (when building on linux) the library version numbers are omitted during the linker step:
![image](https://user-images.githubusercontent.com/20871346/28653537-af7b1d2c-7253-11e7-98e8-43eb4ac84199.png)
e.g. `-lmad` instead of `-lmad123456789`

**Comment by gunqqer** [comment]
@endless-sky I hate pining you, but I am at a pretty big loss here and... I nor tehhowch can find it out. Can you help me fix all of this please?

**Comment by MessyMix** [comment]
Please, take this to another thread. :)

The original issue still stands. dragging to rearrange flagship crashes the game on macOS Sierra.

**Comment by Rob59er** [comment]
so apparently this wasn't fixed...

**Comment by gunqqer** [comment]
I just tested this myself on the latest steam release (I'll test my compiled version when I get around to it) and it still crashes for me

**Comment by MuhammadNCheema** [comment]
MacOS Sierra , issue confirmed

**Comment by endless-sky** [comment]
This should be fixed by 92d0e35.

**Comment by MessyMix** [comment]
Can anyone confirm the fix?

**Comment by gunqqer** [comment]
Just tested it, it works! No crashing on ship reorder on OS X. 

MacOS X El Capitan, issue resolved

**Comment by MessyMix** [comment]
Alright. Solved and locked, my dudes.
