### ISSUE TITLE
Simple Math in Mission Conditions

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#2799]
It would make mission creation much more flexible to be able to do simple operations such as multiplication and division in missions.
Something like this.
    FleetStrength = "ships: Large Warship" * 5

**Comment by VonZorch** [comment]
And that requires being able to use conditions as variables.

**Comment by tehhowch** [comment]
Isn't this something that was made possible by https://github.com/endless-sky/endless-sky/pull/2383#issuecomment-292752140 ?

I use some similar constructs here: https://github.com/endless-sky/endless-sky/pull/3076/files#diff-2bac732e91cc1eca7e71ca841a06dc9cR165

Looks like the `*=` operator was added initially, but then removed during a cleanup commit by @EndrosG prior to it merging. Not sure if that was intentional or not.

Even without it, you can currently do this (no errors generated when parsing):
```
to offer
    FleetStrength = "ships: Large Warship"
    FleetStrength += "ships: Large Warship"
    FleetStrength += "ships: Large Warship"
    FleetStrength += "ships: Large Warship"
    FleetStrength += "ships: Large Warship"
    FleetStrength < random
on offer
    ...
```

**Comment by VonZorch** [comment]
That works.

**Comment by VonZorch** [comment]
And since it's now a milestone, the thread can be closed.

**Comment by tehhowch** [comment]
Actually, this isn't done yet - or if it is, it's not complete.
I'm adding "competition"  to #3076 with this set:
```
	to offer
		"mining_competitors" = "Human Mining Competition [0]: active"
		"mining_competitors" += "Human Mining Competition [1]: active"
		"mining_competitors" < 10
```
and it never offers, because ConditionSet::Test does not differentiate between conditions that can be tested, and conditions that should be created and then tested.
https://github.com/endless-sky/endless-sky/blob/349229c2583e8e8cd84418976720f9c16088a235/source/ConditionSet.cpp#L187-L209
As soon as the first line of the to offer is parsed, it returns false and none of the other conditions are tested, because the number of currently active human mining competition missions is 0.
Either I'm using this feature incorrectly (quite possible, since it is essentially only documented (and very sparsely) by #2383 ), or it's only partially implemented.
If I wrap things in an or:
```
	to offer
		or
			"mining_competitors" = "Human Mining Competition [0]: active"
			"mining_competitors" += "Human Mining Competition [1]: active"
			"mining_competitors" < 10
```
the value loaded in the second line, for the +=, is not the value from the 1st line, but instead is a default value of 0 because "mining_competitors" is not a condition found in the player's save.

I think this can be resolved by cloning the condition map inside ConditionSet::Test and then modifying the clone when the function is not a comparison function, and only testing `result == isOr` if it was a comparison function.

**Comment by EndrosG** [comment]
just to help you a bit, @tehhowch : please read #2514 ... it exactly explains where you fail.

> because in to offer you can't do such apply conditions

hope that helps since it IMHO & AFAIK exactly addresses that particular issue, just 5 months ago ;-)

**Comment by tehhowch** [comment]
I've gone and extended the Test and Apply methods to solve the issue :+1:

**Comment by tehhowch** [comment]
This is 100% achieved in #3128 now 👍

**Comment by VonZorch** [comment]
Good to hear.
