### ISSUE TITLE
Slightly too many jobs in new Wanderer system

### ISSUE THREAD

**Issue by lifeyouristhis** [endless-sky/endless-sky#2800]
![image](https://user-images.githubusercontent.com/30373861/28492715-73fade34-6f08-11e7-8f33-666b45454004.png)

I thought it might be worth mentioning.

**Comment by MessyMix** [comment]
Holy millions of credits right there. Good catch, probably because there are only, like, 3 systems in wanderer space beyond the eye. 😆

**Comment by solardawning** [comment]
And they all together give fewer credits than swiping a single Triple Plasma Core from a raider.

**Comment by ghoulavenger** [comment]
Considering they don't compete with looting triple plasma cores (which is the most efficient combat method of making money that I know of) and the trading in these systems is mediocre at best (if you've got a big fleet and do trading these systems are trash even with all the missions, for reference my fleet has 100 deep rivers that are all jump drive enabled -- I make over 25 million in profit per jump when I do trading) I don't see this as a problem but more of an obscurity. Perhaps lower frequency but higher payout would be better if trying to make a smaller fleet or single ship money making more accessible rather than a multitude of lower paying jobs (even though these are pretty good for jobs especially compared to human space).

**Comment by Amazinite** [comment]
>Perhaps lower frequency but higher payout would be better if trying to make a smaller fleet or single ship money making more accessible

MZ has stated that jobs of higher tiers should generally increase in size and not in payment per ton. That is, most of the jobs in Human, Hai, Coalition, and Wanderer space all pay the same per jump per ton or per jump per passenger, but more advanced factions provide bigger jobs and thus bigger payouts for a single job. 

Also, all Wanderer planets share the same job, so anything done to affect the jobs that offer on new Wanderer planets also affects the jobs on old Wanderer planets.

**Comment by ghoulavenger** [comment]
Well that leaves two options then, make jobs that can go through the Eye or separate the jobs for Wanderer space and Korathi space.

**Comment by tehhowch** [comment]
There are a couple of event conditions that can be checked to control the job availability windows. We can also use the `near ` keyword to gate job origins/destinations to specific sides of the wormhole.

This distinction can be improved if we get @Hadron17776 's PR #2626 merged (e.g.  `attributes !korath`) as that will help distinguish wanderer worlds which have significant Korath influence/presence as well.

**Comment by endless-sky** [comment]
Addressed in 2de4024.

I made some jobs phase out when their territory shrinks (to account for the smaller number of destinations) and others continue but not be offered beyond the Eye.
