### ISSUE TITLE
Consistency: "show outfits for sale" --> "show outfits in stock"

### ISSUE THREAD

**Issue by MessyMix** [endless-sky/endless-sky#2802]
For sake of consistency, I suggest changing the box in the outfitter, which reas `show outfits for sale`, to `show outfits in stock`, since the game language in the outfitter is either in stock / in cargo, so it should be reflected here.

![image](https://user-images.githubusercontent.com/20450076/28493074-2af58a60-6f42-11e7-9394-c055b7cb6b34.png)

**Comment by MessyMix** [comment]
lol whoops

**Comment by endless-sky** [comment]
The trouble is, when an outfit is labeled as "in stock," what that really means is that it's *not* for sale here but a few of them are available. So switching this to "in stock" might actually make it more confusing. (It might also be confusing to new players, because "for sale" pretty clearly means it's something the outfitter sells, whereas they might not understand that "in stock" means "in stock at the outfitter" rather than "in stock in your cargo" or something like that.

**Comment by MessyMix** [comment]
Understandable. Closing for now, then.
