### ISSUE TITLE
Turrets suddenly try to rotate as ship emerges from jump

### ISSUE THREAD

**Issue by Vilhelm16** [endless-sky/endless-sky#2805]
Immediately as the ship emerges from another system, the turrets on it suddenly try to rotate. Upon further observations, I noticed that the turrets will rotate different amounts when this happens - I have had them rotate just 20 or so degrees and even 360. I noticed this when using a protector, as the high amount of turrets caused more motion. I further tried with a Bounder and confirmed that this happens with more than one ship.

**Comment by tehhowch** [comment]
Turrets are supposed to rotate independently.

Are you instead saying that the turrets are not remembering their previous aiming angle? This is likely because only the ships in the player's system invoke the turret aiming routines. (Eg. they do not have those angles)

**Comment by Vilhelm16** [comment]
If you watch the turrets closely, when the ship jumps you will notice that the turrets suddenly rotate partway, then go back to their forward facing position.
![turret_bug](https://user-images.githubusercontent.com/27139210/28500370-c7c01eda-6fe4-11e7-8c21-07147a9dc8b2.gif)

**Comment by tehhowch** [comment]
Did you set the preference for opportunistic turrets, or keep the default
focused turrets?
If focused, they will aim forward until an enemy is nearby. If
opportunistic, they sweep the sky about their "natural angle"

On Jul 23, 2017 9:54 AM, "Vilhelm16" <notifications@github.com> wrote:

If you watch the turrets closely, when the ship jumps you will notice that
the turrets suddenly rotate partway, then go back to their forward facing
position.
[image: turret_bug]
<https://user-images.githubusercontent.com/27139210/28500370-c7c01eda-6fe4-11e7-8c21-07147a9dc8b2.gif>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/endless-sky/endless-sky/issues/2805#issuecomment-317258508>,
or mute the thread

**Comment by Vilhelm16** [comment]
https://youtu.be/cbyvqQmU5

This video shows it nicely:

just notice the turrets when I enter the next system. This has happened in multiple systems, even when no enemy is nearby.

**Comment by tehhowch** [comment]
>https://youtu.be/cbyvqQmU5

Your video doesn't exist

**Comment by Vilhelm16** [comment]
I don't know what's up with that. I'll try to fix it tomorrow; it is hard to explain without showing.

**Comment by Bladewood** [comment]
Okay, I see what he is talking about.
When you jump, the turrets instantly reset to a particular orientation - in particular, the facing consistent with the sweeping motions of opportunistic firing.

Enable focused firing, then attempt a jump. Closely observe your turrets.

**Comment by Vilhelm16** [comment]
I’m not certain this is what I saw, but it sounds fairly close, so I’ll go
with this for now.

**Comment by endless-sky** [comment]
Fixed in fa92d76. What was happening is that when a day passes in-game (e.g. when you jump), all your weapons get reset to clear the reload counters on any that take a very long time to reload. But, the reset was also resetting their angles.
