### ISSUE TITLE
Make shield charging more efficient on small ships than large ones

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#281]
Fighter shields charge too slowly and disappear quick- on the other hand, heavy warships can charge at a relatively fast rate (depending on the amount of shield generators) and due to their shielding matrices, can withstand an attack from a dozen fighters and win. (Bactrian- I'm looking at you here). To even out the playing field- I think there should be a charging rate based on the size of a ship (type). OK, I realize I'm not explaining very well. Fighters, due to their smaller and compact frames, should be able to charge their shields faster- maybe in the form of a factor applied to their shielding ability, say, if they had one shield generator, they would operate at 1.5 or 2x the efficiency, as opposed to the standard charging rate, with 2 shield generators outputting 4x the charge rate. Larger ships, like the Bactrian, would have a slower shielding rate, maybe like .7 or .5, because of their much larger size.

**Comment by minecraft2048** [comment]
The sad thing is that the longer you play this game, the more you realize that this: http://www.projectrho.com/public_html/rocket/spacegunexotic.php#fighters is true.

**Comment by Pointedstick** [comment]
Yeah the launched fighters are pretty pathetic and not worth much.

Interceptor class ships can be useful en masse, though. Half a dozen Furies and Hawks can take down a lone heavy warship.

This is another reason why missiles need to be beefed up: then fighters can basically become mobile missile launch platforms (kind of like today's warplanes), and if the missiles are actually any good, then such ships will be effective because they don't have to close to such a short distance that they get turned into space debris in the blink of an eye.

**Comment by Oeleo** [comment]
I agree ! That's  a big problem in endless sky, and I didn't understand why I was only use warships, but that's because they need they need the same minimum in all though they have much more space, that's why unfortunately other classes are useless. Of course you can use it for fun or for roleplay, but for efficacity they are better in all the domain. So i'm totally for ir, because other ships will become usefull when you are rich as well, so I think that we need it too.

**Comment by endless-sky** [comment]
One problem this might cause is that large ships would suddenly be taking forever to recharge shields (or small ships would recharge in an absurdly short time). And, small ships are *supposed* to be weaker and unable to take as much damage.
