### ISSUE TITLE
No "blocked <message>" in Remnant missions.

### ISSUE THREAD

**Issue by lifeyouristhis** [endless-sky/endless-sky#2813]
Could you add "blocked <message>" for them?

mission "Remnant: Defense 3"
mission "Remnant: Void Sprites 1"
mission "Remnant: Void Sprites 3"

Also, some kind of hint for "mission "Remnant: Key Stones"" for players from [0.9.6] who are unaware of existence of Hai quantum keystones would be nice.

**Comment by ghoulavenger** [comment]
Heh, can agree with the hint bit. Trolled around remnant space for awhile before I decided I wasn't going to get any more missions from them (I honestly wasn't expecting much, since the coalition didn't have much either but I didn't have access to buying their tech other than the gascraft), checked their file to discover the key stone mission, and said "I didn't even know the Hai sold them, well, off to buy some key stones". And since I spoiled the mission for myself, I just brought the extra key stones with me on my way back.

**Comment by endless-sky** [comment]
I try to avoid too much hand-holding in the missions. The player will get a lot less enjoyment out of discovering the Key Stones if there's some sort of awkward hint given to them that they exist somewhere.

**Comment by endless-sky** [comment]
I added a message for Void Sprites 3 in 05300c0. Blocked messages are only for continuation missions; it doesn't make sense to have them for missions that start a completely new mission thread.

**Comment by tehhowch** [comment]
Perhaps a solution for the keystones is to make all Remnant space wormholes require their use. This would reduce the likelihood of players having only Jump Drives when exploring Remnant space, as the northern path is considerably more dangerous, and considerably more hidden than the path from near Tarazed.

**Comment by Lineth** [comment]
I honestly thought that not all red wormholes needing keystones was a bug.

**Comment by endless-sky** [comment]
The Waste is designed so you need *either* a jump drive *or* a keystone to explore all of it. The idea was to add one more section of space that a pre-jump player can discover. (Note that once the map gets filled in, presumably it'll be possible to fly around the Waste anyway and the wormholes will no longer be the only route between certain systems.)
