### ISSUE TITLE
Should the Science Drone Really say Uninhabited?

### ISSUE THREAD

**Issue by Rob59er** [endless-sky/endless-sky#2816]
Wouldn't it be better to make something akin to the opposite of "never disabled"? Make a "never fixed/reenabled", so it doesn't have that uninhabited bit. It just looks odd.
Edit: I have been informed it is derelict and not set up as a planet, but it still looks weird.
(This may be impossible I don't know)

**Comment by Rob59er** [comment]
![screen shot 2017-07-24 at 6 21 50 pm](https://user-images.githubusercontent.com/29336153/28549276-99711740-709e-11e7-9f29-13d1c7650c14.png)

**Comment by tehhowch** [comment]
https://github.com/endless-sky/endless-sky/blob/86d219b63e07fae49cd43e852c27d49e3320dcf9/data/transport%20missions.txt#L1910
That's why it says `Uninhabited`
(The player can not have angered the `Uninhabited` government in any way, while they could discover this mission while at war with the Republic)

**Comment by endless-sky** [comment]
I just didn't want to have to add a whole new government just for that mission. (Although "Derelict" would probably make more sense than "Uninhabited.")

**Comment by Amazinite** [comment]
I added a whole new government just for this mission. c39ba35
