### ISSUE TITLE
Proposal for Drak Draining Field

### ISSUE THREAD

**Issue by ReimeiSky** [endless-sky/endless-sky#2847]
So after a discussion, I came up with an idea for the Drak Draining Field: give it

- 0 velocity (so we don't have something like the Antimatter Cannon);

- 400 blast radius (since that is the existing range of the Draining Field); and

- the `safe` attribute (to prevent the Archon from harming itself, obviously).

I believe that this would best recreate the effect of an actual ion field that only damages enemies.

**Comment by tehhowch** [comment]
Does it make sense for the draining field to drain more energy the closer to the Archon one gets? That'd be another argument in favor of blast damage scaling ( #2529 ) if so.

**Comment by jafdy** [comment]
MZ wants to add field weapons properly at some point.

**Comment by tehhowch** [comment]
Hadron and I have the start of a  class for something similar. It works for what it needs to, and has marginal extension ability, but for use as a hostile item would need to be moved to a standalone class so that both engine and ai have access to it at the right times without crazy argument-passing code:
https://github.com/endless-sky/endless-sky/compare/master...Hadron1776:jump-interdiction

**Comment by KiLEdEnNis** [comment]
(please add aura weapons asap, I got a heat aura to implement in my mod)

**Comment by tehhowch** [comment]
Aura weapon or field weapon? Or both and make one friendly only  and the other hostile only?

**Comment by Amazinite** [comment]
Both would solve old issues like #861, allowing aura weapons to act as support/logistics weapons that have been asked for on more than one occasion.
Maybe instead of having two different types of weapons, we have an attribute similar to `safe` which causes the weapon to only impact friendlies instead of only impacting hostiles.

**Comment by gunqqer** [comment]
Aura weapons would be nice, right now for my plugin I just have something shooting constantly with 360º inaccuracy. (This was before we had ```safe``` so I couldn't use explotions). I do like this idea for the Drak draining field, but if explotions decrese over distance we should get a tag for them that means it wouldn't have decresing damage

**Comment by KiLEdEnNis** [comment]
what if for explosions;
you have the base damage & range, but there was a new tag, whatever the name, that defines how much damage the border wouuld do?
say it does 1000 damage w/ a range of 200, you set this tag to 0.2, the outer edge would do 0.2x the initial damage (200), and in between it calculates the distance and then the damage
sounds very confusing but not really a better way to explain it

**Comment by tehhowch** [comment]
That sounds like a detail that belongs in that other issue :)

**Comment by endless-sky** [comment]
The AI would never choose to fire that weapon, because right now it doesn't take blast radius into account when deciding if a weapon will hit something.

But, giving the weapon its usual velocity *plus* a blast radius and making it "safe" would probably work. The "safe" keyword didn't exist yet when I created the Archons.

**Comment by Bladewood** [comment]
Huh. Nicetoknow.

**Comment by KyroFirehammer** [comment]
If this were to be implemented an "actual" drak "ship" (as the archon is technically a organism)

**Comment by Bladewood** [comment]
> He [Erukt Isi'ithi] says, "They are partly [living, biological], partly [constructed, technological], and partly..." Whatever the third part is, the words for it are so far removed from human language that your translation device doesn't even attempt a guess at how to express them.

**Comment by KyroFirehammer** [comment]
Ahhh but still it would be interesting to have an actual drak colony (potentially near worlds end *starts winking and nudging)

**Comment by Bladewood** [comment]
If you want to discuss or suggest potential storylines, don't do it on the GitHub. Do it somewhere else, like the [Steam forum](http://steamcommunity.com/app/404410/discussions/) or the [Google Groups forum](https://groups.google.com/forum/#!forum/endless-sky) or the [subreddit](https://www.reddit.com/r/endlesssky/new/).

Like I've asked before.

**Comment by Zitchas** [comment]
This issue could probably be closed, as the main request has been completed.

Or do we want to keep it open for the subsequent idea/suggestion of having actual aura/field effects instead of just using blasts all the time?

**Comment by Amazinite** [comment]
Considering this completed by #7239. We can consider aura weapons a separate issue.
