### ISSUE TITLE
Smuggling issues- landing clearance and rep 

### ISSUE THREAD

**Issue by jlnxr** [endless-sky/endless-sky#2862]
First of all, I love the new changes to pirate reputation where you have to attack merchants to increase your rep as a 'real pirate'. Also love the new pirate smuggling jobs- finally a use for interference plating other than boarding. 

However, the combination of these two cause a bit of a catch 22 when it comes to smuggling. The increased profitability over legal jobs evaporates if you have to pay every single time you want to want on a pirate world, and the only way to solve this is to attack merchants- pretty much the opposite of the discreet low-profile behavior that would make smuggling successful. 

My solution would be to give the player landing clearance for a planet after completing a smuggling job that originated there. This wouldn't change pirate rep- they would still attack you, but it would allow players to land and pick up more smuggling jobs without either paying such a fee that they aren't profitable or attacking merchants. 

I've also noticed the bigger payout smuggling jobs of 'highly illegal' cargo require a higher pirate rep than the smaller once, albeit still negative, along with a higher combat rating. If the only way to raise your pirate rep is to attack merchants, once again smugglers would need to attack merchants to get a shot at these jobs. 

The higher combat rating is also funny too, because really a smuggler would probably want to avoid fighting both merchants and pirates, and therefore probably wouldn't have a high combat rating. 

My solution to this would simply be to offer those bigger payout jobs after having completed a number of a smaller jobs, rather than having it based on pirate rep and combat rating. 

Have I somehow missed the mark/point on this or does anyone feel the same way?

**Comment by Amazinite** [comment]
The reasoning behind the combat rating requirement was because no pirate is going to trust their cargo with someone who's never fought before. They need to make sure that you're at least able to handle yourself in the event of being attacked.

As for the pirate rep thing, that change was done after pirate jobs were added, so I couldn't account for it when making the pirate jobs. As of right now there's no mathematical way of making both pirates and merchants friendly to the player, let alone having all human factions be friendly to the player. You're either a pirate to everyone (maybe excluding the Syndicate) or on the side of the law with everyone else.

Whether this is intended, I'm not sure, but it certainly does make gaining profit from pirate jobs tougher. If we wanted to change it so that you can make pirates and merchants friendly at the same time, then we'd want to increase (or decrease, depending on how you look at it) the pirate attitude toward merchants from the current -0.1 to -0.3, or even -0.5 (which would allow us to get law enforcement and pirates friendly). We could also make it so that completing pirate jobs gives you a slight pirate rep boost every time, so eventually you won't have to pay or worry about killing merchants.

**Comment by jlnxr** [comment]
I wasn't suggesting that there be someway to make both pirates and merchants friendly- I was suggesting that the player simply have landing clearance on pirate worlds they've completed jobs for in the past. The problem is caused by the rep, but the solution doesn't have to be change the way pirate rep works. We could just let players who've done smuggling jobs land on planets they smuggled for. Or maybe after having done a few smuggling jobs. Just someway to **land** without attacking merchants. 

Otherwise, as you point out making a profit is pretty hard so there's really no reason for someone to take these illegal jobs. I thought the point of making them illegal was the higher risk/reward.

As for combat rating... I guess that makes sense. I was picturing the possibility of making dedicated smuggling ships, i.e. stripping out weapons for interference plating in a fast ship. Personally, I'd prefer to maybe make those highly illegal jobs require you to have interference plating installed or something rather than combat rating, but that's pretty minor compared to the landing problem.

**Comment by Amazinite** [comment]
>I was suggesting that the player simply have landing clearance on pirate worlds they've completed jobs for in the past. 

Not possible to do currently.

**Comment by gunqqer** [comment]
could you not have a mission that always gives clearance to a planet? yeah it would not be a very effecuiant way of doing it but it is a way

**Comment by jlnxr** [comment]
It's possible in actual missions to give landing clearance for a planet controlled by a hostile faction... (ex. land on Thule in Free Worlds campaigns) ... What is the barrier to doing this for normal game play? Would a hidden mission work?

**Comment by gunqqer** [comment]
oh wow we both had the same idea at the same time. 

Only reason why it wouldn't work is it'd be terribly effeciant with code- requiring awhole mission

**Comment by Amazinite** [comment]
@jlnxr There's no way for the game to know what planet you're always taking jobs from then give you an invisible mission which provides clearance to that planet after a certain number of jobs have been completed from that planet.

**Comment by jafdy** [comment]
You can give clearance for the destination planet but there is no way to allow the player to always be able to land on a planet without setting each route as a different mission.

**Comment by gunqqer** [comment]
So, while technicaly possible it isn't optimal or even worth it

**Comment by jlnxr** [comment]
Hmm, disappointing, really takes the interest out of the pirate jobs. Hopefully, whether it's some change to rep or some way to give clearance, some solution becomes possible at some point in the future. That, or increase the value of the smuggling pirate jobs so it's worth bribing your way to land. 

Although, anyone else notice that you're clear to land on Albatross? Is that a bug or intentional?

**Comment by Bladewood** [comment]
I'm guessing it's to give you an easier start with the pirates.

Albatross isn't just a pirate world - it also has a lot of regular people.
Until you anger the Pirates to a sufficient extent, you're free to land on it.

**Comment by Amazinite** [comment]
Some pirate worlds have a negative required reputation to land.

**Comment by jlnxr** [comment]
Interesting. Anyways, hopefully a solution to the pirate jobs becomes possible at some point in the future, otherwise it's hardly worth it, with the exception of Albatross.

**Comment by ghoulavenger** [comment]
I noticed something funny, I have the pirate worlds dominated, and I'm pretty sure they hate my guts, but when I landed on alcyone I had a whole lot of jobs available to me, and since they are dominated I can land freely. This seems like an odd way to make friends with pirates. Or is that intentional? Dominating pirates is a lot easier than befriending them by attacking merchants.

**Comment by Amazinite** [comment]
Some lower-end pirate jobs will offer under two occasions. 1) you're friendly with pirates or 2) you have a high combat rating.

**Comment by endless-sky** [comment]
Having the pirate jobs boost your pirate rep a tiny bit might make sense. But, ideally there would be a downside, too - like, every once in a while when you get caught doing a pirate job it decreases your Republic rep. (It wouldn't make sense to decrease Republic rep *every* time you do a job, because then you could transition to being at war with the Republic without even realizing they knew what illegal stuff you were doing.)

**Comment by jlnxr** [comment]
And once again @endless-sky comes up with the perfect idea for solving a balance issue. This here is why this game is so good- because of ideas like this. The solution allows dedicated smuggling ships without attacking merchants while still carrying the element of risk that should be inherent in these illegal jobs. It also totally makes sense- of course being caught doing illegal stuff should lower your Republic rep and not just be a fine. It's a perfect solution.

**Comment by Amazinite** [comment]
#3984 added rare pirate jobs that boost the player's reputation with pirates at the cost of hurting their reputation with a certain law enforcement faction. This notably requires combat, so it isn't the best for someone only interested in smuggling jobs, but the issue right now with @endless-sky's idea is that a mission can't decrease your rep based off of who scanned you, which is ideally what would occur if that idea was implemented. 

There are certain smuggling jobs that only offer regionally, so we could make it so that getting scanned during those missions hurts your rep with the regional law enforcement, but one could still take a job, leave the region they got the job from, and be fined in another region while not actually losing rep with who scanned them. But that seems like an edge case that can be ignored for now if you ask me.

**Comment by Amazinite** [comment]
@jlnxr does #4287 look like it'll fix this issue for you?

**Comment by jlnxr** [comment]
That about solves it yes

**Comment by Amazinite** [comment]
Well I guess this is complete, then.
