### ISSUE TITLE
Feature request: pause button + ability to "detach" camera view

### ISSUE THREAD

**Issue by ReimeiSky** [endless-sky/endless-sky#2865]
I have a feeling that someone's asked for this before, but I can't find it, so I'm making this issue here.

**Comment by Amazinite** [comment]
Reference: http://steamcommunity.com/app/404410/discussions/2/1471966894880432300/

**Comment by jafdy** [comment]
I asked for a pause/slow button on the commit where the fast time button was added.

**Comment by tehhowch** [comment]
Pan n scan for ES... 

The easiest way to do this might be an invisible (or lightly bordered) overlay, as panels already have the ability to pause the game. The system scene (orbits and planets map) could be rendered in a corner. It would need to use the radar colorations, along with a "viewing rectangle", and all the ship information that gets drawn on radar. (This is a nice tie in to #2678 for move-to orders via the system map, where other improvements to the map were discussed). Drag actions on the map would need to be reinterpreted to move the origin rather than draw a rectangle, or perhaps a mod key to provide both behaviors (shift to select or shift to move... Pick a control scheme from moving the blender camera).

Some way to indicate feedback from ship interactions would also need to be added, as the functions handling left and right click on ships run during engine::calcstep or ai::step - without this there would be no "your fleet is targeting...." messages.

I say doable but difficult.

**Comment by lifeyouristhis** [comment]
How about slowing the game and excluding certain animations from that?

**Comment by tehhowch** [comment]
Slow the game would be done with "slow everything proportionally". Which effects are you thinking should not be slowed down?

**Comment by lifeyouristhis** [comment]
Zooming speed, selection rectangle and game menu (for both slowing and speeding).
It would be nice if you could change slowing and speeding values in game preferences or data files.

**Comment by lifeyouristhis** [comment]
I did some testing. In 30 frames per second game still looks good and is slow enough to grasp the situation and give orders to your escorts. Unless game become more strategic in future that will be enough.
`		if(zoom < zoomTarget)
			zoom = min(zoomTarget, zoom * (1 + 0.01 / gameSpeed));
		else if(zoom > zoomTarget)
			zoom = max(zoomTarget, zoom * (1 - 0.01 / gameSpeed));`
`		gameSpeed = frameRate / min(frameRate + 5, 60)`
Rough idea that should fix the zoom speed problem.
Side note: current zoom speed is, in my opinion, way too slow. I wanted to speed this up ever since I started playing. How about adding "Zoom speed" to settings (with numbers like x1, x1.5, x2)?

As for detachable camera, I suggested this because of not being able to target properly those missile Furies running away from my flagship, so I could send my escorts after them. Solution to this problem I suggested in #2897.

**Comment by Amazinite** [comment]
[Quoting MZ](https://github.com/endless-sky/endless-sky/issues/1408#issuecomment-238399248):

> This is a classic example of "feature creep." If you want to play XCom, play XCom. If you want to play FTL, play FTL. If you want to play a 4x game, play a 4x game. But all those are well beyond the scope of a space trading and combat game, which is all ES is intended to be.

Features like this would creep the game into being a strategy game and overemphasize the need for a fleet.
