### ISSUE TITLE
Enhancement Request: change when hostility is set vis-a-vis Void Sprites 3

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2876]
Unless the guardian Archon is psychic or omniscient/clairvoyant (in which case, it probably shouldn't be hostile at all), it doesn't make much sense for the Archon to be hostile until you bring the Gascraft into Nenia.

The exact same ships were there on the previous missions, and could come and go as they pleased.  Being hostile just because you accepted the mission seems odd. 

Ideally, your rep with " Drak " would be 1 until you entered the system with the gascraft, at which point it would drop to -1000.  I don't know if it is possible to have an event trigger off of the presence of a model of ship, which is what would be required to do this, though.

**Comment by tehhowch** [comment]
The `" Drak "` Archon does not exist in Nenia until the mission is accepted.

**Comment by marphod** [comment]
Yes, and?

Story-wise, what is it about accepting the mission that makes there be a hostile archon?  The missions up to that point were non-threatening.
What should make the Archon hostile is approaching the gas giants and/or having a known hostile ship in your fleet.

If you forget to put a jump drive in your gascraft and try to see if you just need it in your fleet, rather than having it as your flagship, you warp into Nenia, looking just like you did last week, except there is now an inexplicably hostile Archon.

For what it is worth, I fully expect this to be marked unlikely or won't fix, as I apparently have an odd play style and this is a weird edge case.

**Comment by MessyMix** [comment]
I actually have been thinking about ways to do this for a long time, and imo it's a legitimate idea, whether or not it gets implemented. I was trying to do this for a blockade running mission, where you have a mission that you have to sneak past a blockade looking for your cargo. I was thinking that if you get scanned, your rep instantly drops because they're trying to get the cargo. I haven't tested this, but I thought having a `stealth` mission that happened secretly alongside your delivery mission, and `on fail` have the rep drop, but I'm not sure if it'll work out yet.

But yeah, it's an edge case, but I like the idea. :P

**Comment by Amazinite** [comment]
Or just make the cargo `illegal -1` so it drops your rep anyways, but have an event `on fail` which raises your reputation back up to positive after say a week.

**Comment by endless-sky** [comment]
It seems perfectly reasonable to me to say that just the fact of you nosing around the system for the past few weeks has attracted a hostile Archon.

Plus, Archons are mind readers, so they know you've taken on a mission to try to land on the gas giants even before you do anything. :)

**Comment by tehhowch** [comment]
We can look at it as a warning from the Archons to the Remnant who keep sending you there... They knew what would have been asked of you next if you didn't get "warned" on this mission, and chose to not have the Remnant put that idea in your head 👍
