### ISSUE TITLE
Feature request: color key for locations on map

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#288]
The map very nicely color codes each system depending upon what item is selected in the left-hand list. For factions, the color-coding is obvious, but for other pieces of information the coding is not so clear. For instance, I could eventually figure out that "blue" means "low prices" and "orange" means "high prices" when a particular resource is highlighted, but what the heck do blue and orange (or the colors in between) mean when "outfits" or "shipyards" is highlighted? How can a system have half a shipyard, for instance?

I think to reduce all this confusion, it would make sense to have a "key" for the system color-coding scheme in the lower-left of the map screen.

**Comment by gchapyzh** [comment]
Sure, a map key would help.

**Comment by airtroop392** [comment]
Yeah, I agree 100%. When I first tried to use the catalog, I was confused because I thought orange meant that the particular item I was interested in definitely WASN'T there. And it's not just like there's only two colors- there are a few and I don't even understand why there are more than 2 (yes, we have it here, or no, we don't have it here) unless the shades inbetween are supposed to represent a sector that possibly has it or something.

**Comment by jafdy** [comment]
Key:
Dark blue: No outfitter/shipyard here 
Light blue: Outfitter/shipyard but not with selected outfit/ship
Orange: Selected outfit/ship sold here
I don't dare fiddle with the UI myself but I hope this helps.

**Comment by guillochon** [comment]
This has largely been addressed by @endless-sky's latest commits, so I'm closing this.
