### ISSUE TITLE
Mines an piercers should be purchaseable 

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#2887]
So tehhowch said I should open a issue on this so I did... my reasoning,
The Efreti sell the storage racks for the mines and piercers. It makes sense not to sell the actual secondary weapons to give a bit of challenge to unlock them. My second reasoning to this is that as it stands the minelayers especially are very impractical because of the way the kor automata work and how they blow up most of the time when boarded. They also have usually shot off most or all of the mines and piercers before you even get there rendering them too rare to get a decent amount of them and too easy to avoid unless in mass group for them

**Comment by KyroFirehammer** [comment]
Too be useful (it accidentally subed without the end of the sentence)

**Comment by Pointedstick** [comment]
You can and should edit your posts instead of posting another comment with a correction.

**Comment by tehhowch** [comment]
(if you change to desktop mode you can edit your previous posts, and delete unnecessary self-replies)

There has not been much development of the Korath race beyond defining factions and their respective fleets. Only 2 commits out of the 4k+ have dealt with Korath outfitters:
1) The initial definition: ff6da7c5df9d113d44cfc04ac2e1369849c2b581
2) The addition of ammo storage to the game as a whole: 8d0455dab2e868151b2ace1393de6c77ebd4e5f0

The perhaps better solution is to define outfitters unique to the factions (Efreti, Sestor, Mereti, and the exiles).

**Comment by KyroFirehammer** [comment]
But how would you get the peircers it is my understanding that in the wanderer misdions you only befrend mereti and you wipe out sestor ( I personally haven't finished them yet because if how seriously outgunned I am with my carrier, but that's another story). Unless they add missions that reprogram the sestor factories and ships (which would be great because I like sestor better
model wise)

**Comment by tehhowch** [comment]
The same way one gets Finisher torpedoes currently: attack the relevant ships, board them, and plunder the outfit. If they explode before you can plunder them, thanks to a previous PR they have a small chance to jettison ammunition during the explosion.

Piercers are very potent weapons, and being hard to obtain (but not impossible) is part of the balance against them. You are welcome to create a story arc / mod in which the player character sides with the Alphas and thus has easy access to Piercers, but obviously such a character will have a rather difficult time obtaining things that are commonly available in the current game.
If you want to have everything with no compromises, you'll have to use a mod to do that. The game is more interesting when you have to make choices about things.

**Comment by MessyMix** [comment]
they're still around. although I feel like your comment detracted from your
intial post, which was worth considering.

**Comment by KyroFirehammer** [comment]
Siding with the alphas seems a bit unlikely because of the syndicate nukes mission was also the alphas and you fight them in another FW mission. I was thinking more along the lines of after taking out their control hub the wanderers/you could then hijack their systems and control them to be the defence fleet along with the mereti for the wanderers and Efreti thus rebooting the factories and the outfitters/spaceport(?) Of the sestor planets similar to what happens to mereti

**Comment by KyroFirehammer** [comment]
Or if they would ever so alien tribute fights that would also work

**Comment by Amazinite** [comment]
The reason that the Kor Efreti sell storage outfits for piercers and mines is because they encounter automaton fleets that attack their planets from time to time. Although we don't see any, the command center suggests that the Kor Efret have captured some automata. Given that automata are more likely to explode than be captured, the Kor Efret, having to deal with the automata for over 100 years now, certainly have a stockpile of piercers and mines somewhere, more so than they have weapons which can fire them. As such, they build the storage outfits to be able to pack more ammo on any captured automaton that they have.

The thing is, the Kor Efret do not produce their own piercers or mines. This is the reason that they don't sell the ones they probably have, because eventually they'd run out as aliens like the player show up and ask to buy ammunition.

If you're wanting to buy mines or piercers, I'd say just wait for the end of the Wanderer story to be finished where I'm sure we'll be rewarded with being able to purchase Mereti and/or Sestor tech (and I'll laugh if it turns out that the final decision that we make which determines the branch we take will also determine whether it is Mereti or Sestor tech that we get to purchase).

**Comment by KyroFirehammer** [comment]
You destroy pretty much all of sestor with mereti so a decision seems unlikely however it would be nice to get an item along the way or a upgrade to the hai translator that allows you to talk to the korath ships and planets to demand tribute and takeover the places that would sell them. This would open up another can of worms that would end up expanding the end game goals to include taking over a quarg ringworld

**Comment by MessyMix** [comment]
No, sestor ships are still around. :)

**Comment by tehhowch** [comment]
@KyroFirehammer note that I said you would need to write an entire plot arc (perhaps more) in order to side with the Alphas: in the current game's plots it would not be sensible to have the player side with the Alphas.

Regarding direct communication with friendly drones - we can only wait and see where the Wanderer story goes.
Regarding tribute - this is a "bonus" mechanic in Endless Sky, so it won't happen. Install mods like Tribute+ if you want more of this.
Regarding capture of a Quarg ringworld - good luck. You can write a mission string to do this, but note that it would require spawning so many Quarg fleets (due to the lore about population size) that the game would be unplayable. Your hypothetical mission would also need to address the retaliation to such a grievous action by extragalactic entities. By all means though, go ahead and create one - all the machinery needed is present in the game today.

**Comment by endless-sky** [comment]
My plan for the Alpha story line is that it would cover tiers 1 *and* 2, i.e. doing the Alpha story line would take you through all the events of the Free Worlds and Wanderers stories combined, but from a very different perspective. Taking control of the Sestor fleets and factories would be part of the Alpha story line, naturally.

I also plan to have a Wanderers side story line where you help out the Kor Mereti in various ways and get access to purchase their tech (and maybe eventually even to the Kor Sestor weapons and ships).

**Comment by ghoulavenger** [comment]
@tehhowch I imagine a fleet that would defend a ringworld would be what, one fleet per planet on the ring? Assuming 12 planets (I haven't counted lately) at 3 ships per fleet, thats 36 ships, most of them probably wardragons. I can't imagine anybody capable of defeating that few quarg ships without having a gambebreakingly large fleet, or quarg ships themselves. And they'll probably take heavy casualties regardless because of the extremely OP nature of skylances. I don't think it'd break the game, but I do think it'd be a hard fight to win.

**Comment by tehhowch** [comment]
per https://github.com/endless-sky/endless-sky/issues/2540#issuecomment-302986796, there are 1 T quarg on that ringworld. I think they're going to fight back, and I don't think you're going to survive.

**Comment by Lineth** [comment]
Given also that it's not unreasonable for the ringworld itself to have defenses (and I think MZ said that they even have a sort of giant built-in jump-drive-like device to teleport entire fleets from ring to ring), the idea of conquering a Quarg ringworld just simply is not gonna happen (Unless you're the Pug, becase Pug).

**Comment by gunqqer** [comment]
Yeah taking on a ringworld, even one not finished is suicide and would take a full armada to even hope to defeat. If you want to capture it you're going to lose many, many people and you still wouldn't take out the quarg: they'd jump ship (ship as in the ring world) before it was taken if they have no chance.

**Comment by KyroFirehammer** [comment]
She'll I don't think atm my 9000+ quicksilver at my would work I personally am just at the part where I'm fighting the "giftbringer" bit the way I play is I like to cap most ships that I can't easily "buy". I think a alpha line would be interesting where it would make a sparrow start more likeable because you could attack the merchants right off the bat. I also think a kor mereti/effreti side story would be nice abd give access to potentially purchaseable automata or even just simply the korath chasers and a few of the weapons. In my opinion the reasoning of they (the kor effreti) can't make them could be solved with the wanderers who could show them how to produce things more environmentally friendly and could lead to some more peaceful korath ships such as a ship for running peace delegations with various other races via jump drive and lead to a steady return to prosperity for the race. This would also most likely lead to mines and piercers available on open market along with some of their systems such as thier generators and heat shunts.

**Comment by gunqqer** [comment]
No offence but please proof read what you post

**Comment by Pointedstick** [comment]
@KyroFirehammer 

http://www.talkenglish.com/grammar/grammar.aspx

**Comment by KyroFirehammer** [comment]
Eh that's fair. regardless you still have to win 2 dice rolls and not be instantly vaporized to even think about getting any of the ammo the most of the time there all ready shot it all off. It makes two of the most interesting weapons in the game practically useless and needs an alternative way to get them.

**Comment by gunqqer** [comment]
The punisher missiles from the coalition are very interesting (and incredibly powerful) but we can't buy those. Hell, we can buy any of their weapons or ships and because they're storyline isn't finished attacking them to a neg reputation isn't really an option.

**Comment by KiLEdEnNis** [comment]
one of the ways the Wanderer end storyline CAN be is that they for some reason (peace or whatever) acquire both Mereti & Sestor ships in their space, which will be the Efreti's new defense fleets, they would of course offer their ammo, other outfits(?) and even ships (???) to the player

and I think there are quite some other scenarios where the player will be able to at the very least purchase ammo (but be real; simply adding the ammo to the Efreti worlds may not make much sense; they don't know how to properly make them as far as we know, even the mine/piercer racks seem a bit weird)

**Comment by KyroFirehammer** [comment]
I very much agree the wanderers should find the sestor control hub and hijack it thus ending the korath civil war and their outfits and ships(PLEASE) would then be purchasable and would solve the ammo problem

**Comment by jafdy** [comment]
Umm . . . you are told that the Efreti don't know how to stop the automatons . . .

**Comment by Lineth** [comment]
It's actually a plot point that the Kor Efret don't know how to stop them. When you visit them with Rek they get offended at the idea that the Wanderers can offhandedly achieve what they've been attempting for what's implied to be a very long time.

**Comment by KiLEdEnNis** [comment]
plus we know the control bunker where the Alphas were controlling them got breached and they escaped, after that Zenith thing you destroy the hub either way (if I remember; if ya kill the giant-ass fleet & don't bomb Zenith they blow the base up after?), so the new controller for the Sestor in exile Korath space is somewhere there; guarded by those fleets

besides; the Efreti can't make Mines and Piercers without some sort of blueprint and the means to manufacture them (equipment/resources), either MZ says "hey, the Efreti sell this shit now" and adds it or he lets the player unlock them through the story

**Comment by KyroFirehammer** [comment]
The Efreti could possibly disassemble and make a blueprint from some ammo they would have salvaged from some of the automata that wold be developed through the storyline ( sestor through after the Alpha base raid Mereti after the wanderer integration of their system)

**Comment by KiLEdEnNis** [comment]
I don't think disassembling live explosives is your best idea

**Comment by Lineth** [comment]
I would be okay with the Kor Efret selling the ammo for mines and piercers. Neither are really gamebreakingly powerful enough to really be worth the trouble otherwise; and it'd gel with them building the racks (i know building a glorified closet with a rack stuffed in it is easier then a bomb hush).

**Comment by KyroFirehammer** [comment]
It would also be nice for lore reasons to have a short mini quest whrer you have to steal one of each and they will then research them and after a short time span ( I was thinking a week or two in game time) and it would give you a message that the Efret have offered to sell them to you because you helped them to be able to make them,

**Comment by gunqqer** [comment]
That seems like a simple enough mission, so, go code it yourself, make a pull request and we can discuss it better with a real, solid proposal.

**Comment by Pointedstick** [comment]
Seems like this will eventually be done as part of a future storyline. No need to keep the issue open for now.
