### ISSUE TITLE
Syndicate Target Practice missions should probably have a failure consequence

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2890]
Currently, boarding and capturing the target ship (or simply boarding and stripping) pays better, by a significant amount, than just doing the mission.  There probably should be a rep drop on failure to discourage the practice. Alternately, the value of the ship and its outfits could be set to 0, if possible.
(related to #2268)

**Comment by Amazinite** [comment]
Or just make it `uncapturable`.

**Comment by marphod** [comment]
Given the mission is to disable the ship, `never disabled `would make the mission impossible.

Does `uncapturable `prevent looting?

**Comment by Hadron1776** [comment]
> Does uncapturableprevent looting?

I don't believe so. It just makes the boarding panel say `This is not a ship you can capture`.

**Comment by marphod** [comment]
Making it self-destruct would also work, but that likewise should probably result in a rep loss (as should destroying the ship).  But stealing from or destroying the ship should piss off your employers.

**Comment by Pointedstick** [comment]
Good catch, will fix shortly: blowing it up (in any way) imposes a financial penalty and reputation hit.

**Comment by Pointedstick** [comment]
One issue with adding a significant failure penalty is that, as @lifeyouristhis pointed out in https://github.com/endless-sky/endless-sky/issues/2900, the "on fail" condition is applied if you deliberately abort the mission. Not sure what to do about this, since I agree that a failure penalty is appropriate if you destroy or attempt to board the ship, but it's entirely inappropriate if you just chicken out of the job.

**Comment by marphod** [comment]
That seems to mean we might need an `on abort` block added to missions.

**Comment by Pointedstick** [comment]
This was resolved by https://github.com/endless-sky/endless-sky/pull/2902. Let's track the bug in https://github.com/endless-sky/endless-sky/issues/4018
