### ISSUE TITLE
Improvements to targeting options

### ISSUE THREAD

**Issue by lifeyouristhis** [endless-sky/endless-sky#2897]
http://steamcommunity.com/app/404410/discussions/2/1471966894880432300/
In this thread I talked about tactical pause & detachable camera (#2865) and possible improvements to targeting system. I suggested:

> Toggle through hostile ships [R]
> Toggle through neutral and friendly ships [N]
> Toggle through disabled ships [some other key]
> [Shift] -> Changes toggling into selecting nearest ship of that kind. Remove that part about escorts from menu.
> Bonus: toggle through escorts.

That's the general idea. I think there are better key bindings than that, like [CTRL] + [R] to toggle through disabled hostile ships. 
I believe such a change would greatly improve the game.

**Comment by IsocratesGrey** [comment]
This seems like a strong choice for improvement. Especially toggling through hostile ships. The main concern I'm having with the expansion of drones is the difficulty in targeting the main carrier. In 0.10.0 the key binding is

R Select nearest hostile ship
Shift-R Select nearest ship
N Select next ship
Shift-N Select next escort
B Board selected ship (auto selects closest ship if no disabled ship selected)
Shift-B Board disabled escort

That means the ones not in the game yet are toggle through hostile and toggle through disabled.

Unused keybinding so far: EYOP K ZXV

Because this is for cycling through ships where there is already a key for selecting the closest, the key bound should probably be something close to it.

**Recommendation 1:**
Minor change to add two new keybindings
E Select next hostile ship
V Select next disabled ship

**Recommendation 2:**
Major change to revamp combat keybindings

E Select nearest escort
Shift-E Select next escort
R Select nearest hostile ship
Shift-R Select next hostile ship

V Select nearest disabled ship
Shift-V Select next disabled ship
B Board selected ship (auto selects closest ship if no disabled ship selected)
Shift-B Board disabled escort
N Select nearest ship
Shift-N Select next ship

This uses the same method for each key, where nearest is default and next is shift. Alternatively it could be next is default and shift is nearest. Keeping them the same makes keyboard use easier. 

Additional note, keeping the keybindings as either just the key or Shift-key will simplify the control binding.

**Comment by Amazinite** [comment]
> Toggle through disabled ships [some other key]

As of #6346, the boarding key now cycles through disabled ships.

> Unused keybinding so far: EYOP K ZXV

We don't think we should be saturating the keyboard with keys for different targeting types. If there's a targeting type that we want, we should look to how we can add it to the existing keybinds, or if it's even necessary to add.

In the interest of keeping requests separate, I've opened the two issues linked above for adding specific commands to select different types of ships that aren't covered by the current commands.
