### ISSUE TITLE
Allow ship descriptions in missions to add or override specific children of parent nodes without having to copy-and-paste the entire parent node + all children

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#2901]
I'm making the Syndicate target ships into self-destructing automata to resolve https://github.com/endless-sky/endless-sky/issues/2268

It would be really nice if I could just do this:

```
	npc save disable "scan cargo"
		personality staying heroic target
		government "Test Dummy"
		ship "Vanguard" "Syndicate Test Vessel"
+			attributes
+				"automaton" 1
+				"self destruct" 1
```

That doesn't work, and instead I need to copy-and-paste the entire `attributes` node in order to add or change any of its children:

```
	npc save disable "scan cargo"
		personality staying heroic target
		government "Test Dummy"
		ship "Vanguard" "Syndicate Test Vessel"
+			attributes
+				category "Heavy Warship"
+				"cost" 7200000
+				"shields" 9800
+				"hull" 6000
+				"automaton" 1
+				"self destruct" 1
+				"bunks" 45
+				"mass" 500
+				"drag" 8
+				"heat dissipation" .6
+				"fuel capacity" 400
+				"cargo space" 50
+				"outfit space" 560
+				"weapon capacity" 220
+				"engine capacity" 120
+				weapon
+					"blast radius" 160
+					"shield damage" 1600
+					"hull damage" 800
+					"hit force" 2400
```

**Comment by lifeyouristhis** [comment]
`ship "Vanguard" "Vanguard Test Vessel"`
`	attributes`
`		"self destruct" 1`
Define a variant before mission. Adding "automaton" attribute doesn't matter because ship's gonna blow up anyway.

**Comment by Pointedstick** [comment]
"automaton" is just to reduce the crew to zero, which I know won't matter if it always blows up, but it seems appropriate anyway.

**Comment by lifeyouristhis** [comment]
```
ship "Vanguard" "Vanguard Test Vessel"
	attributes
		category "Heavy Warship"
		"cost" 7200000
		"shields" 9800
		"hull" 6000
		"bunks" 45
		"mass" 500
		"drag" 8
		"heat dissipation" .6
		"fuel capacity" 400
		"cargo space" 50
		"outfit space" 560
		"weapon capacity" 220
		"engine capacity" 120
		"self destruct" 1
		"automaton" 1
		weapon
			"blast radius" 160
			"shield damage" 1600
			"hull damage" 800
			"hit force" 2400
```
This works. You can remove some parts, I think.

**Comment by Pointedstick** [comment]
You're right, that works! Looks like you can overtire only entire top-level nodes (including all of their children), but not their individual child nodes. Updating the request and title

**Comment by tehhowch** [comment]
Extending the "add/remove ____" functionality to ship `attributes` is possible.

The reason for the behavior you experience (have to fully spec the attributes, not just the "new" ones) is because the attributes of a variant are not pulled in from the base model if the variant has some attributes initially: https://github.com/endless-sky/endless-sky/blob/785bb501f353e13498b146a19341394fdb7be10d/source/Ship.cpp#L261-L268
The process of reading the data from the mission description calls Ship::Load, which is where your variant's specified attributes are read (and stored as its `baseAttributes`).

One method would be to import the contents of an "add attributes" node into `attributes` in Ship::Load(),  then use a `+=` operation equivalent instead of `=` here: https://github.com/endless-sky/endless-sky/blob/785bb501f353e13498b146a19341394fdb7be10d/source/Ship.cpp#L333

**Comment by tehhowch** [comment]
#2959 should resolve this nicely. There isn't really a need for a `+=` operator, as the `attributes` variables are just outfits and the Outfit class has Outfit::Add, which does what you would expect.

The syntax used by 2959 is
```
ship <base model name> <variant name>
    add attributes
        <attribute> <value>
        ...
```
which is consistent with other "add ____" uses (e.g. planets, systems, etc).
