### ISSUE TITLE
Content Request: More T2 Carriers/Drone Carriers, T2 Interceptors

### ISSUE THREAD

**Issue by marphod** [endless-sky/endless-sky#2904]
There aren't many T2 ships that are carriers, and the ones that do exist have issues.

- Solifuge(Hai unfettered): Really T1.5 (low hull and shields)
- Korath Raider: Ridiculously high crew requirements & only carries 2 fighters
- Tek Far 78 - Osk (Sestor): the self-destruct rate doesn't help.  Inaccessible currently after the middle of the wanderer plot (You can capture them in Exile space, but as there are no outfitters there, the ships are stuck there)
- Tek Far 109 (Sestor): Same as the 78. With less hull and shields it is less likely to survive to be captured.

The state of drone carriers is even worse:
- Pond Strider (hai): not currently used in the game, really T1.5
- Tek Far 71 - Lek (Sestor): Same as the 78 above.
- Tek Far 109 (Sestor): Same as above.

The Model 8 (Mereti) is the only existing T2 Interceptor.  It is rather rare, self destructs frequently, requires attacking a friendly government (after wanderer middle), and doesn't fulfill the interceptor role very well.

**Comment by tehhowch** [comment]
In the next 6 months we should see further developments to the availability of the Solifuge, Pond Strider, and the Sestor carriers, as the Wanderer story is worked on by MZ.

Regarding the rarity of the Model 8 - it is not rare if one goes to the Mereti systems in which mining is done. It is exceedingly rare (nonexistent) if one attempts to find it in a Sestor vs Mereti contested system, as it does not have a presence in combat fleets.

**Comment by Amazinite** [comment]
>requires attacking a friendly government (after wanderer middle)

Said friendly government won't change its reputation given that it has no crew (you have to attack the Wanderers to change your Kor Mereti crew), and will probably have its ships and outfits sold by the end of the Wanderer storyline. We'll probably also get to buy Sestor ships by the end of the Wanderer campaign.

**Comment by Rob59er** [comment]
https://steamcommunity.com/app/404410/discussions/2/1457328392112238682/

**Comment by jlnxr** [comment]
I think there are enough tier 2 drone/fighter carriers available with the Sestor (farming them just takes patience and cloaking, not even money or a boarding party, so I don't think this 'discounts' them as usable carriers). Also, the Navy Carrier and Solifuge are still pretty solid in this regard, and while tier 1 both are top t1 ships and the Solifuge's sheilds are actually similar to t2 medium war ship level, so it can take a beating. 

However, I agree with the knock on interceptors. I guess there's little demand for it from players because a human heavy warship could still murder one no problem, but it seems odd this whole category is seriously lacking. The Model 8 is basically it.

**Comment by tehhowch** [comment]
Who knows the developments the Wanderers have in store... a drone carrier, protective interceptors, and a 26-space hull-based beam could be in their archives just waiting to be unearthed..

**Comment by Amazinite** [comment]
>Who knows the developments the Wanderers have in store... a drone carrier, protective interceptors, and a 26-space hull-based beam could be in their archives just waiting to be unearthed..

How specific an idea. It's be crazy if you were right.

**Comment by tehhowch** [comment]
I forgot to mention `turreted`... unless the Flycatcher's cousin drone has a gun port ;)
It'd probably be 27 space, because then there would be 1 left over and it would irk people 😇

**Comment by warp-core** [comment]
I feel like you know something we don't...

**Comment by solardawning** [comment]
The problem with drones isn't a lack of carriers as much as it is a lack of easy to outfit, replace, and combat-ready drones. 
You can't really use Flycatchers out of the box, you have to go equip them with laser or blaster turrets first. And then they all die in a battle and need to be replaced.

(That problem, of course, needs to be tacked elsewhere- like by making smaller ships avoid exploding ships.)

**Comment by marphod** [comment]
> Said friendly government won't change its reputation given that it has no crew (you have to attack the Wanderers to change your Kor Mereti crew), and will probably have its ships and outfits sold by the end of the Wanderer storyline. 

Quite frankly, I consider the reputation change due to disabling/destroying/looting being based on population alone thing a bug (which I commented on elsewhere).  And the Kor Mereti don't have carriers.

> We'll probably also get to buy Sestor ships by the end of the Wanderer campaign.

I don't know MZ's plans, but I can't fathom why. The Sestor ships currently balance their lack of crew by being hard to capture.  Buying them would make that factor irrelevant.

> I think there are enough tier 2 drone/fighter carriers available with the Sestor (farming them just takes patience and cloaking, not even money or a boarding party, so I don't think this 'discounts' them as usable carriers).

1) The cloaking device is only available for one of the main Free World story branches
2) Advance your Wanderer plot further.  The Sestor stop being available in any area where you have access to an Outfitter and lacking the ability to install a jump drive, cannot be effectively farmed

> Also, the Navy Carrier and Solifuge are still pretty solid in this regard, and while tier 1 both are top t1 ships and the Solifuge's sheilds are actually similar to t2 medium war ship level, so it can take a beating.

Can't get a Carrier after the resolution to the free world plot without attacking a friendly government. And at under 30k shield+hull, terrible drag, and high crew requirements, it isn't a great choice.

The Solifuge is a stop-gap at best.  High drag and weight makes them slow and gives them poor maneuverability compared to other warships of its class.  It is better than the other options, but realistically, that's the korath raider, and ... nothing.  (Admittedly, It is an utter beast with up to 5 skylances -- I go with 4, 2 disruptors, and an antimissle (usually, the warder -- but i have to assume the eventual quarg rebalancing will make that less viable as an option. )

> I feel like you know something we don't...

Only that the flycatcher has a potential as an offensive drone that the wanderers can't currently use as they don't have appropriate massed weapons

> You can't really use Flycatchers out of the box, you have to go equip them with laser or blaster turrets first.  

You can't/don't want to use almost any ship out-of-the-box.  I don't see that as a problem.

**Comment by jlnxr** [comment]
1.- Talking about Mereti because they have interceptors. I definitely agree though, as a sentient species, even with a hive mind, they should probably be pissed if you attack them for at least some length of time 

2.- With the Starling cloaking is now easily available in atleast limited form regardless of branch taken in FW campaign. They are excellent at what they are designed for- scout ships- and can easily harvest Sestor drones due to cloaking.

3.- Human carriers still pack one of the largest fleets of drones and fighters at 4 fighers and 6 drones. As a carrier, it's still pretty damn useful, and there's always the option of capturing the Giftbringer after the FW campaign. Of course, hopefully they will be buyable in Republic storyline, whenever on earth that actually happens (please don't consider that a question, I don't want it set back another week ;) ). Solifuge Carriers are slow, yes, but it's a carrier- you'd expecting to to be slower than non-carrier ships of its class. I don't really consider that a problem, nor do I think we need a super-fast T2 or high T1 carrier ASAP

3.- Flycatchers are also 2 freaking million dollars last I checked, making them pretty damn cost prohibitive as offensive drones. In defense, they atleast aren't targeted directly by your enemies. Also, sure, most ships you wouldn't want to use out of the box, but if you really want to use Flycatchers are offensive drones you shouldn't have to head all the way back into human space first. Also, IMO fighters and drones are more important to be decently outfitted out of the box because they're so expendable in battle compared to larger ships.

**Comment by Bladewood** [comment]
on the note of kor mereti reputation: https://github.com/endless-sky/endless-sky/issues/1964

**Comment by KiLEdEnNis** [comment]
side note; simply adding random ships for aliens requires some backstory; why would they have them
and every species using carriers is boring imo

**Comment by KyroFirehammer** [comment]
In my opinion to solve the drone problem it would be cool to have a purchaseable upgraded combat drone that would be available on Farpoint after completing the Alpha raid on host that could be a merge of sestors drones and the navy's that was in essence a better armored combat front with a heavy laser or electron beam (but would be very expensive in comparison to the standard drones available elsewhere)

**Comment by KiLEdEnNis** [comment]
well I'd say that would require some upgraded Navy ships (because they got Sestor tech) & then of course a general tech increase to human tech if you going realism, and that'd kinda mess w/ the game way too much
