### ISSUE TITLE
Possible typo--Quantum Keystone or Key Stone?

### ISSUE THREAD

**Issue by ldsgsm** [endless-sky/endless-sky#2922]
![image](https://user-images.githubusercontent.com/24484477/29236933-c77af49a-7ed0-11e7-99bc-8d7651293b90.png)

While exploring the ember wastes after purchasing a quantum keystone from the Hai, I discovered that the remnants also have quantum keystones, but there the artifact is spelled slightly differently (Key Stone vs. Keystone). Is this deliberate so they can have different descriptions, or is it an accident? If it is deliberate, is it possible to use a space after the name or some other invisible marker to distinguish them?

**Comment by Amazinite** [comment]
Deliberate: #2620

**Comment by marphod** [comment]
I understand the in-story reason, but the distinction feels like it is a UX failure/programming limitation rather than an important in-game distinction.  This is especially true, as the items remain distinct, rather than collapsing into a single stack.

It would be surmountable if:
outfitters could override prices on a item by item basis
outfitters could override item descriptions (or events/invisible missions were used to do so)

It would be unnecessary if there was a clear, important distinction between the items, or if the items didn't have so similar names.  Given that the Hai language, the 'ancient tongue', and the Remanent sign-language have few, if any, linguistic ties to each other, the single space difference in the name is off-putting.  If the Hai item were a Lucky Lodestone, a Probability Field Generator, a Schreodinger's Spyglass, Pet Rock or similar, and was manufactured into something you would suction-cup to the main viewscreen or dangle from the rear-view mirror, having the items be distinct would make more sense.

More seriously, given that it is a piece of a ships outfit, it would make more sense if the Hai instance was used as part of a sensor package, or something else that would be connected to your on-board systems.  Maybe an outfit scanner named a 'quantum field detector' that is described as a crystalline tuning fork. The description could clue players by describing it with 'According to Hai legends, a ship with this scanner will always have "the key to open the doorway home"'.  That would also give a reason for the 2 outfits to remain distinct, even after discovering the Remnant Quantum Keystones.

**Comment by endlesssteve** [comment]
I also thought it was a bit odd that the two objects are dealt with separately. The mission to bring 50 stones from Hai space shows they are the same thing. it stops you bringing more and selling them privately. However it was not such a big deal that I thought of raising it myself.
