### ISSUE TITLE
[Low Priority] Add message when getting cloaking device while in starling

### ISSUE THREAD

**Issue by Rob59er** [endless-sky/endless-sky#2928]
A message similar to the one when you have a JD already.

**Comment by Amazinite** [comment]
Well a Starling's cloak is integrated, so it's questionable if it would even by something that the Syndicate engineers can see.

**Comment by Bladewood** [comment]
The engineers can't see the regular Cloaking Device, that's for sure. But, presumably, the Starling engineers would have had to make the Cloaking Device visible so that they could actually install it into the ship.

I think the separate Cloaking Device itself is valuable enough to be given anyway, even if a player is flying a Starling or an Arfecta.

**Comment by Amazinite** [comment]
>But, presumably, the Starling engineers would have had to make the Cloaking Device visible so that they could actually install it into the ship.

Making it visible for the sake of installing it implying that it could be removed. It seems like it would be more a feature of the hull itself to cloak and not a singular part of the ship you can point to, as otherwise one could uninstall it.

**Comment by KyroFirehammer** [comment]
It also would be nice to be able to remove the cloaking device out of a starling 


Also,
WHAT THE ARFECTA CLOAKS TOO!!!!!
*mind blown

**Comment by gunqqer** [comment]
If we can remove the cloaking from a starling that makes cloaking devices almost worthless. There are a maximum of 4 cloaking devices you can get and install on any ship. If we make it so you can just buy another one it makes them something that just requires money instead of something that must be heavily rationed to only the ships that need it.

**Comment by KyroFirehammer** [comment]
True but the checkmate branch seems kinda pointless seeing as how the ravens sent that good and the ionic afterburners are obtainable by harvesting marauder ships

**Comment by KiLEdEnNis** [comment]
1. the Starling cloak is intergrated in the ship's stats; being able to acquire a theoretical infinite amount of cloaking devices would arguably be the most horribly unbalanced thing this game would have seen (above the Mass Expansion stacking and probably even AM Cores)

2. yes the Arfecta cloaks, those kind of comments serve no actual purpose on GitHub though; you didn't even discuss the matter, (didn't even make a funny joke,) it's an entirely irrelevant post more suitable for the subreddit or Steam

3. both branches in the FW storyline are meant to give the player some way to influence the outcome of the story, technically the Reconcilation is better because it gives you a Cloaking Device, but none of us have any idea what your last comment was even supposed to mean, as it contradicts itself in a way

**Comment by KyroFirehammer** [comment]
OK so first off I will as it it might be unbalanced , however it could easily be a much more inefficient version of the cloaking currently in game thus being balanced.(similarly to the Ionic afterburner vs afterburner) this would also make it less of a horrible mistake to choose checkmate branch ,because instead of a good cloaking device you get a good afterburner. Also marauder ships (Bounty hunters) will sometimes have the checkmate branch outfits and ionic afterburner (ionic afterburner are commonly found on the marauder leviathon) so it would make sense to be able to obtain more than 4 cloaking devices but have them be less effective than the regular (Possibly call it "Remnant cloaking node")

**Comment by KiLEdEnNis** [comment]
inefficient cloaking devices will still be OP
you can eco on stuff to keep yourself in cloak, the mere concept of getting out of combat for even just 5 seconds w/ cloaking is OP, less efficient cloaking devices won't change it, so it shouldn't happen

**Comment by KyroFirehammer** [comment]
True.. as a side thought would it be to OP to add a possibility to get a cloak on an albatross via a storyline (Aside from the other four) this wouldn't be removable though

**Comment by gunqqer** [comment]
IMO cloaking devices (universal ones able to be transfered between ships) should be very very very limited in supply. Ships that have built in cloaks should be either limited in supply like transferable devices, or weaker than other ships on the same tier.

**Comment by KyroFirehammer** [comment]
I was thinking more of something like the barbs but only avalable through a quest line where one has hull regen and the other has cloaking

**Comment by gunqqer** [comment]
some fighters or drone with cloaking devices built in would be interesting, especialy if they auto cloaked when low on shield/hp.

**Comment by endless-sky** [comment]
There's no easy way for a mission to check that you're flying a Starling, and it's enough of a rare case that it doesn't seem worth including.
