### ISSUE TITLE
Make Hai hostile toward Pirates

### ISSUE THREAD

**Issue by lifeyouristhis** [endless-sky/endless-sky#2931]
It's possible for Pirates to enter Hai space through escort jobs. Perhaps make Hai hostile toward Pirates?

**Comment by KyroFirehammer** [comment]
Wow I'm surprised there not all ready

**Comment by tehhowch** [comment]
If you lived right next to a massive population of aliens and had limited, if any, formal relationship with their governments, would you want to just blow some of their ships up? Talk about a PR nightmare..

Mods which add Pirate-based activities in Hai space can amend the relationship if they so desire

**Comment by MessyMix** [comment]
My initial impression was that the Hai should be hostile to pirates, and
although it is not explicitly stated in the text, it is implied from their
being a "peaceful" society that they would be opposed to pirates—although,
admittedly, I don't think an implication can 100% justify Hai blowing up
Pirates. IMO the decision is down to MZ, but I would favor it.

However, I don't think teh's argument about blowing up alien species' ships
really holds—the Syndicate blow up Korath on a regular basis, and we have 0
formal connections to the Efret. To be honest, since the Republic are
killing Pirates mercilessly anyways, I don't see why it would be a PR
nightmare for the Hai—and even if there aren't any "formal" relationships,
there are certainly backchannel comms between the two races.

IMO, it's down to MZ, but if the Hai purposely hold their fire, it's almost
certainly *not* because of their relationship with human governments, but
rather some innate compulsion as a peaceful species that keeps them from
killing aliens.

**Comment by tehhowch** [comment]
A simpler change may be to the Pirate government, giving them a negative attitude towards the Hai (and possibly positive towards the Unfettered). This would make the Hai *respond* to being attacked, but never initiate the attack. `Nemesis` pirates will not engage non-player ships if given the choice between player and non-player...

**Comment by lifeyouristhis** [comment]
Oh well. I always thought Hai enforce peace in their space. Turns out they don't care if humans fight with each other. I was wrong, sigh.

It still looks pretty ridiculous when their whole war fleet is manoeuvring next to you while you're fighting for your life with pirates and they just ignore you and jump away.

Case closed.

**Comment by MessyMix** [comment]
@lifeyouristhis don't close this! there should definitely be a fix. I actually agree with at least the Hai reacting to Pirates, although maybe not actively blowing them up. Keep this open.

**Comment by jafdy** [comment]
Make Hai friendly to merchants and make pirates unfriendly to Hai. The Pirates will initiate attacks on Hai and the Hai will intervene on attacks on merchants.

**Comment by tehhowch** [comment]
I looked into this a bit more and my earlier supposition was incorrect - the IsEnemy check is directionally independent, so even if Hai don't care about Pirates, if Pirates view the Hai as opponents, the Hai will happily go Han and shoot first. If the Pirates don't care about the Hai, the Hai don't care about the Pirates, but the Hai care about Merchants, nothing happens between the Pirates and the Hai - there is no "government A provokes government C by attacking government B on this day" equivalent.

**Comment by MessyMix** [comment]
Hmm. That's interesting. Do we think it should be this way, or should the
AI targeting check be directionally aware? I personally think changing it
to the latter makes more sense, although I'm not familiar about how much
codework this would entail.

**Comment by tehhowch** [comment]
If the IsEnemy check is directionally dependent, then some kind of provoke
action is needed for ai government (otherwise they will not attack back,
and not attacking back is already possible via the pacifist personality).

I do think a provoke action is a good improvement as it makes a true
"police" government possible - one that does not attack faction a or
faction b individually, but if faction b is present and attacks faction a,
which the "police" have a positive attitudeToward, then they ally with
faction a against faction b.

**Comment by Lineth** [comment]
How would this 'police' government react to two factions it's friendly to attacking each other? Ignoring it? Siding with the side with higher relations?

Sorry if stupid question. Not good at codery.

**Comment by Bladewood** [comment]
I think it just ignores them both.

**Comment by lifeyouristhis** [comment]
> Without additional changes to the generation of provoke events, it would ally itself with the faction that is first hurt: ship::takedamage returns the provoke event

That's actually realistic.
By the way, I've noticed I could attack merchant ships in Hai space without them reacting.
```
	"attitude toward"
		"Hai (Unfettered)" -.5
```
It means Hai's space is basically pirates paradise, am I right?

**Comment by tehhowch** [comment]
Yep, the Hai do not currently care about piracy, unless it is of their own ships.
