### ISSUE TITLE
AI navigation fails with too low propulsion

### ISSUE THREAD

**Issue by Musaran2** [endless-sky/endless-sky#2939]
Escorts with very low propulsion often get stuck behind for no apparent reason, especially on wormholes.

It seems that when the AI fires both engines (intended to get faster to destination on a curve rather than straight), it does not account for the time it takes to turn, and so if turn/thrust is too low it ends up overshooting destination and circling it.

This prevents landing, thus refueling and wormholes.
Sometimes it also messes getting steady for Hyperdrive of Jump Drive.
Oddly enough, boarding & holding position work, probably because they have some terminal brake.

[Save to reproduce](https://github.com/endless-sky/endless-sky/files/1227516/Test.Test.txt)
Depart, ask escorts to gather.
_BCT 2_ will circle. (158 max speed, 4.7 turning)
_BCT 3_ will run in "8". (82 max peed, 9 turning)

Halting escorts first does not workaround, as they don't change heading first when asked to move again.
Revers thruster does not workaround.

**Comment by tehhowch** [comment]
FYI: a figure 8 and a circle are both acceptable flight patterns for escorts that have been asked to gather (the Gather command triggers AI::CircleAround movement logic).

AI movement logic generally falls apart at extreme thrust:turn ratios due to the use of simple (read: fast) movement approximations - drag is ignored.

(Generally, those designing freighter fleets will choose low thrust:turn ratios so that their fleet is able to jump quickly, rather than move away from pursuing ships / projectiles)

**Comment by endless-sky** [comment]
Commit ba06025 (having ships prioritize turning over thrust) should help with this.
