### ISSUE TITLE
Ship idea: ship carrier

### ISSUE THREAD

**Issue by KyroFirehammer** [endless-sky/endless-sky#2940]
The idea behind this ship is that it would allow you to attach to a friendly ship and jump away with it attached to it (for non jump drive ships) this would be ubtainable by the unfettered after completing enough storyline that they get solifuge

Now before we say this would be OP keep in mind these balances

When attached movement is slowed to a crawl (picture pushing a world ship with the syndicates tiny engines in their barbs)

Has little outfit space 
No gun/turret ports
Low shields and hull (picture the eqivalant of a t1 interceptor or transport
Low fuel for what it's used for (400 stock)

Used to transporting non jump drive capable shipsshort distances without hyperspace lanes or
Towing a ship that doesn't have enough crew to a planet

**Comment by gunqqer** [comment]
Doesn't seem very useful. It'd take a lot of time to code it, and there wouldn't be very much use. Even I, the power gamer would say the space that could be saved on warships isn't worth waiting for something to catch up that has inferior movement

**Comment by KyroFirehammer** [comment]
Ok so have you never even looked at a world ship or a hielarch punisher before. Have you ever been that that guy that steals the jump out of a ship but then cap it over a pka2net with no outfitter (Ok so possibly not the second but hey I like drives even if I can't cap the ship but the end up miraculously doing so) 
This would be HUGE it would open up a lot of those "impossible to cap unless in this very specific event " ships into "insanely hard to cap but when you do ,you can actually have a chance at using it"

**Comment by Bladewood** [comment]
OP, given your intentions. We're not doing that.

**Comment by gunqqer** [comment]
Yeah, this seems like a "I want to get more powerful but I want it to be coding in the game for me" type of thing. You can always mod your own game to make ships be fighters and create your own carrier

**Comment by KyroFirehammer** [comment]
Sort of fair but, it just seems to be in get any type of moderately good ship past hai space in most cases(besides wanderers) is only obtainable through timing of getting it (examples navy carrier/cruiser ,korath world ship ,sestor/mereti [Ok so it sorta possible but you have to have soon many ships it's not worth it unless you have cloaking [Also it woldnt be solved by this it was sorta with the starling] hielarch warships, quarg wardragon, rainmaker/gunboats, all t1 drones in human space [are you seeing the problem yet...] Pug Arfecta, sestor ships in exile space, and even more that I'm not writing in.) I would be willing to figure out how that would work code wise and make the sprites ,and it really wouldn't be that OP because you also have to consider how fast you would die due to no weapons slow speed and low armor, those factors would make obtaining those ships after the event times extremely hard but not impossible to obtain legitimately (Also I consider mods to be sorta cheery and I'm a 100% legit kinda player)

**Comment by Hadron1776** [comment]
> Slow speed

Jumping out of system counts on you moving slowly

**Comment by tehhowch** [comment]
You want to make boarding and capping more powerful for **everyone** because **you** feel it is "cheery" [sic] to make them more powerful for only **yourself**? Seriously?

There is *nothing* stopping the player from capturing ships that belong to the Navy, Sestor, Mereti, or Quarg in their natural territory except the player's willingness to provoke said governments. Through some reputation exploits, Heliarch warships can currently be obtained with 0 save file edits / mods. At least 1 World-Ship can be captured (albeit with immense improbability), and this 1 can be captured without angering any normally-friendly faction.

Some method of ship-towing may be eventually possible, but I don't think it is sensible in the game lore that a ramshackle ship-to-ship coupling could survive the accelerations of entering and exiting hyperspace - that is, tow-to-planet only. Such an action would be helpful only for a captured ship which has no engines or power, and even then if the planet has no Outfitter, you have gained nothing useful.

**Comment by KyroFirehammer** [comment]
Umm did you not read the little part on sestor/mereti. Also it is next to i.possible to steal a carrier or cruiser after FW because you anger all human governments. Second off yes jumping require a you to be slow but think about getting to said ship. Thirdly if a link made with the same material as the ship wold be inadequate for jumping than explain how they can jump at all. Fourth jump drives don't have velocity. Fithly[ is that even a word (answer: is now)] it isn't only about ticking off goverments it's also the fact you can't get back to a place to put a jump drive on it (for world ships, coalition, and sestor post wanderer missions). Also it would totally fit into lore in more than one way, for the hai it's putting ships in wanderer space, for korath it explains the only currently capable world ship ,and for humans it's the AAA of space.  And by he way i meant cheaty not "cheery". Along with all this it would encourage players who know how to cheat files not to because more or less the stuff that they would want would be obtainable (But still very challenging to acquire)

**Comment by Hadron1776** [comment]
> Also it is next to impossible to steal a carrier or cruiser after FW because you anger all human governments.

This does not actually make it impossible

> AND if you want to say useless in most situations take a good hard look at the gascraft and think again

You found a single use case!

> Fithly[ is that even a word (answer: is now)] it isn't only about ticking off goverments it's also the fact you can't get back to a place to put a jump drive on it (for world ships, coalition, and sestor post wanderer missions).

1) Fifthly*
2) Want to put a jump drive on it? Plugins are great (hint hint)

**Comment by jafdy** [comment]
As a rule a temporary link is always weaker than permanent link.

**Comment by KyroFirehammer** [comment]
But still no velocity and it's bound to be a strong link because even the weaker parts of the ships like the doors to the outside still are strong enough not to kill everyone onboard when you jump.

**Comment by Rob59er** [comment]
The doors are integrated into the ship...
A tow cable isn't

**Comment by tehhowch** [comment]
<details><summary>response</summary>

 - My comment about capturability referenced the ships in their native systems (Sestor & Mereti in the exiles' systems does not meet this criteria). 
 - Note that angering governments does not preclude your ship from boarding ships of that government (actually, it is currently a requirement that your government and the ship's government are hostile if you wish to capture it), nor does this hostility prevent you from defending your captured ship from hostile opponents. 
If you are unable to defend your prize, I suggest capturing it in a less-defended system, or only attempting such a feat when you are able to adequately protect it.
 - As jafdy mentions, a ship-to-ship bond made in space is by definition going to be a temporary one, and one that is made without access to the "comforts" afforded by a drydock facility. Hurtling through space amid all its perils (which may include hostile ships firing on you) is not going to be very conducive to proper metallurgical bonding.
 - I confess, I am not aware of how a Jump Drive works. I am rather certain that the player and other humans are similarly unaware. Thus it is quite plausible that a temporary ship-to-ship connection is severed during the process of instantaneously disappearing and reappearing in a different area of space-time.
 - The World-Ship I spoke of can be taken to a planet with an outfitter. Heliarch warships and Coalition vessels can be captured and taken to a Coalition planet that has an outfitter if you have not permanently angered their government - this is why I mentioned reputation.
 - Korath World-Ships do not use Jump Drives because *they do not need to*. Korath World-Ships are not meant to invade other species' territories and attempt to plunder their resources. Korath World-Ships are habitats for their species first, and warships second.
 - No level of game content will satisfy everyone, and thus no level of game content, ease, difficulty, etc. will stop save file editing. 
</details>
----

Implementing something like this in the game code requires a lot of changes, even thought it is conceptually as simple as "dock this ship with that ship." For this reason, in addition to those outlined above and in previous posts, this is not something that is going to be on MZ's priority list.
*You are welcome to learn the code needed to make your request possible, and submit a Pull Request for review. No one else is likely to do this for you.*

**Comment by KyroFirehammer** [comment]
OK so it isn't a towcable it's the she tech used on the fist and those types of ships an AIRLOCK AND ELECTROMAGNET
*Returns to calm state

**Comment by KiLEdEnNis** [comment]
simply said way too much work for some dumb useless feature but if ya wanna try go ahead I don't mind

**Comment by jafdy** [comment]
In case you hadn't noticed no one here _wants_ this. If you want to do it your basically on your own.

**Comment by Hadron1776** [comment]
> You are welcome to learn the code needed to make your request possible,

C++ to be exact. 
> Implementing something like this in the game code requires a lot of changes, even thought it is conceptually as simple as "dock this ship with that ship."

It's more a matter of "make sure the game doesn't die a horrible death when something happens that the game doesn't expect": about 70% or so of code is catching error cases.

(Also: 66.2% of statistics are made up on the spot)

**Comment by KyroFirehammer** [comment]
I see many uses and I will I just want a cool name and I'll close this and open a PR

**Comment by jafdy** [comment]
I only see risk.

**Comment by Rob59er** [comment]
I await this PR
*Eats Popcorn*

**Comment by solardawning** [comment]
This would not add an enjoyable element to gameplay. It has a very specific purpose, and that purpose is to counter intentional design elements and placement of worlds/fleets.

So, uh... if you just want a cheat mod, make it for yourself.

**Comment by gunqqer** [comment]
Remember, when you make a sugestion if you make a PR with all of stuff ready to be used it's much more likely to be considered. Especialy with something like this that will take real programing not just coding in content it would be better if you do it. Then we can also have a bigger and better discution on the features

**Comment by KyroFirehammer** [comment]
Olive also been thinking of s more dynamic way to use it that way it's less if a only used to cap and possible little misdions to go with it and it to be more of a well rounded addition to the games content

**Comment by gunqqer** [comment]
@KyroFirehammer http://www.scoalastefancelmarefocsani.ro/engleza/teacher_s_room/Complete%20Idiot%27s%20Guide%20to%20Grammar%20&%20Style,%202nd%20Ed%20(2003).pdf

**Comment by KiLEdEnNis** [comment]
not to be rude but you tend to make irrelevant comments and your grammar makes it extremely hard for us to comprehend half the things you say, gunq is hinting to that in a more... rude way

**Comment by KyroFirehammer** [comment]
Thanks but that's not hing to help my autocorrect I do proofread but hey I'm trying here

**Comment by gunqqer** [comment]
"But that's not hing [sic] to help my autocorrect"

In the same comment you say you proof read, you fail to proof read

**Comment by KiLEdEnNis** [comment]
before this escalates

try & turn autocorrect off?

**Comment by kingmooselord** [comment]
I think the idea is somewhat cool. I'm not really sure about how you are going to justify towing through hyperspace jumps but eh. Certainly sounds... human though! "Just strap some rope roun' that alien ship"

Plus it kinda sounds like the ship you are proposing is almost worse than the flagship required to cap stuff if its useless at everything else. If you were building a true Super Carrier ala EV:N then sure...

Realistically, I'm amazed ships even have crew (besides the obvious dev decision and balance reasons). With the level of tech humans have an AI should easily be able to pilot the ship at a basic level or completely.

Perhaps an outfit module which can remotely hack a ship under your control? I imagine you'd disable a ship then run the attack program which would take several seconds or so to complete (but not a static time, "harder" ships would have longer times to capture). Meanwhile enemy reinforcements should be unleashing the welcome party to interrupt said attempt. 

But that's just me. I don't particularly care for the whole "need a flagship to capture" play style myself.

**Comment by gunqqer** [comment]
Amazed ships even have crew? see the depricated androids or something... well they were OP and so were depricated

**Comment by ghoulavenger** [comment]
Honestly, I don't care that much about the idea, since it makes sense but serves very little practical purpose (only fighters go without hyperdrives and they already have carriers and pirates don't loot outfits anymore so you're not going to get stranded very often, if ever). But if the OPs intention is to just make it possible to capture higher level ships, wouldn't it be easier to just lower minimum crew capacities on said ships (drop the worldships required crew by half and you'll have a significantly higher probability of capturing one without actually making worldships less desirable for crew capabilities, along the same vein you can put a jump drive on them too), or remove defenses such as self destruct (I actually debated doing this since I find that the efret/sestor aren't worth the effort with their high self destruct rates)? Or even just raise the strength of hand to hand weapons (make nerve gas twice as strong and you'll cap just about everything pretty easily)? So many easier solutions, granted none of them will make it to the main game unless MZ decides those things should be easier to cap, which I feel is the crux of your argument.

**Comment by KyroFirehammer** [comment]
I've come up with the other uses for it and I have an idea for a description(no name yet but IMO that comes last) here's so far what I have. "After the Unfettered created the Solifuge they sought to have even more efficient use of their Jump Drives, the result was a multipurpose ,mining and industrial use ,non combat ship capable of carrying  any ship using an electromagnetic locking system far more advanced than anything in human space." I'm also going to create a small quest to get the ship similar to the kestrel, where you escort one to wanderer space ,and report back to the unfettered to gain purchasing access. For a name I'm thinking the "thylacinus" after the extinct marsupial. 

Hull 1250
Shields 1800
Mass 250
Drag 1.9
Outfit space 100
Cost 60,000,000
Cargo space 50
Weapon space 38
Crew 25
Fuel capacity 400
Heat dissipation .7
Bunks 40
Turrets 0
Gun ports 1

How's this for stats (ships attached to it will add mass )
Keep in mind this will be classified as a "light freighter" ( although I have half a mind to make it a transport)

**Comment by Bladewood** [comment]
@ghoulavenger
> But if the OPs intention is to just make it possible to capture higher level ships, wouldn't it be easier to just lower minimum crew capacities on said ships (drop the worldships required crew by half and you'll have a significantly higher probability of capturing one without actually making worldships less desirable for crew capabilities, along the same vein you can put a jump drive on them too), or remove defenses such as self destruct (I actually debated doing this since I find that the efret/sestor aren't worth the effort with their high self destruct rates)? Or even just raise the strength of hand to hand weapons (make nerve gas twice as strong and you'll cap just about everything pretty easily)? So many easier solutions, granted none of them will make it to the main game unless MZ decides those things should be easier to cap, which I feel is the crux of your argument.

Up until this point, it had always been assumed that world-ships were made absurdly difficult to capture because of how they would allow players to possibly capture Quarg ships, [but apparently that's going to change.](https://github.com/endless-sky/endless-sky/issues/2838#issuecomment-318541966)
> I actually don't think the androids are all that OP. At best they make it easier to maintain a fleet, but considering you can just run freighters to pay for your fleet or park ships you don't need at the time it is at best a management tool. And if you're patient enough to capture the sestor/efret, you don't even need a captain.

The primary problem with androids was that they allowed players to easily get away with the below-crew requirement status after attempting to capture a ship.

A more modern problem with androids, which I had only realized a few weeks ago, is that for using a Korath automaton as your flagship, the Command Center and the Bunk Room requirements are acting as a balancing mechanic. If we had androids, this requirement would be mostly negated, up to the Command Center.
Incidentally, a similar mechanic does not exist for escorts. (It's a good thing it doesn't, because that would be hell to deal with...)

**Comment by KyroFirehammer** [comment]
I agree with Bladewood with androids ,but I'm not sure why you mentioned my previous article. Also I feel like a recurring theme is we shouldn't have world ships because quarg would be accessible but honestly I think the bigger issue is the quarg are a incomplete and OP species, if we were to fix the quarg and buff the coalition (to make their story more believable [The publishers are fine as is but the sojorner and others that we're "used to fight the quarg" to make it more realistic that a realistically sized fleet of them could take a few quarg ships on and actually not get creamed] personally I also think a nice quarg transport a few light ships and a couple of freighters wold be a fantastic addition to the need they clearly are going to get (hopefully with a story arc to get access to some of their ships). A world ship is a very nice T2 ship that is fairly well rounded but hard to obtain ,it is not a horribly unbalanced ship because a few shield beetles can easily kill one (and IMO not deserving to be unobtainable other than 1 random one in remnant space)

**Comment by jafdy** [comment]
A. "publishers"?
B. we're = we are
C. It's OP for the same reason the Bact is OP.

**Comment by gunqqer** [comment]
And please for the love of grammar, the space goes after the comma, not before.

**Comment by KyroFirehammer** [comment]
Please for the love of are Emalis making posts that are irrelevant to the topic it's annoying and churlish 

BAM FANCY WORS IN YO FACE :P

**Comment by ghoulavenger** [comment]
> The primary problem with androids was that they allowed players to easily get away with the below-crew requirement status after attempting to capture a ship.

I don't think this is nearly as big of a deal as you're making it out to be. The hardest ship to capture that I'm aware you can, is the Korath Raider. The minimum crew of this makes it very difficult if not impossible to capture two of them at a time. I could capture them reliably without androids, and usually still have a full complement of crew left on my Bactrian. So there is absolutely zero increase in actual capturing capability. You might be able to capture one or two more pirate vessels, but those are twice as likely to get destroyed on the return trip. So yeah, while I see the potential, I don't see the actual practical use for that.

> A more modern problem with androids, which I had only realized a few weeks ago, is that for using a Korath automaton as your flagship, the Command Center and the Bunk Room requirements are acting as a balancing mechanic. If we had androids, this requirement would be mostly negated, up to the Command Center.

Isn't the balancing mechanic on the automata the fact that they self destruct constantly? I don't find them worth the effort.

**Comment by Hadron1776** [comment]
>Hull 1250
Shields 1800
Mass 250
Drag 1.9
Outfit space 100
Cost 60,000,000
Cargo space 50
Weapon space 38
Crew 25
Fuel capacity 400
Heat dissipation .7
Bunks 40
Turrets 0
Gun ports 1

1) You didn't add _any_ engine capacity
2) I'm curious what would happen if the tugboat is destroyed while carrying another ship. Would both ships be destroyed, or would the carried ship be released to be carried by another tugboat (After taking damage from the original tugboat's explosion, of course)?

**Comment by KyroFirehammer** [comment]
Whoops  good eye, now u gotta rework outfit space... When destroyed A you'd have to reset ( magnet only usable if it's the flagship) B the ship below would deploy ( similar to fighters in a carrier)

**Comment by jafdy** [comment]
And you want to tow Heavy Warships with this thing? That is going to look odd.

**Comment by KyroFirehammer** [comment]
It's very wide that's it's length 
 Picture about the width of a 512
Should I do the lowest or second lowest hai atomic for this Ship? 
Ether way it's going to be slower than a protector while carrying

**Comment by KyroFirehammer** [comment]
Ok so here's the stats of it and the stock build:
Category: light freighter
Hull 1250
Sheilds:1800
Mass 250 *note that the mass of the attached ship is added to this number
Drag 1.9
Rewired crew 28
Bunks 40
outfit space 150
Weapon space 40
Engine space 60
Fuel capacity 400
Heat dissipation .9
Turrets 0
Gun ports 1

Stock build * the unfettered will have a missile boat variant using tracker pods as well as the stick varyant 
Pulse cannon ( 13 outfit/weapon space )
Corundum regenerator (16 outfit space)
Pebble core ( 32 outfit space)
Benga atomic thruster (28 outfit space)
Biroo atomic steering (32 outfit space)
Hyper drive (If bought) jump drive (in Unfetterd fleets)

**Comment by KiLEdEnNis** [comment]
we encourage you to get involved in the game and try to make your own content but please don't do this on GitHub here
do it in the google group https://groups.google.com/forum/#!categories/endless-sky/content-creation or even Steam or Reddit

**Comment by jafdy** [comment]
>Rewired crew 28

Oh dear, I don't think they will like being rewired. In fact I find most living creatures don't muck like being rewired.

Why are you giving this thing a weapon? It's going to be a bit useless at any kind of combat, it is only a bit tougher than a star barge.

Have you got any coding yet or do you think this will magically work if you write some stats.

**Comment by KyroFirehammer** [comment]
HAHA totally missed that when I revised it 
The points to make it more versitire and giving it the ability to mine
I forgot to put this in but
Cargo 85 tons
I am working on it currently I'm creating a sprite for it (what program should I use to actually [I'm currently in using paint but I feel that may not be the best to use)(coding I'm sorta list so any tips on what programs to use would be appreciated, but I have started in Notepad ) also when I have competed it how would I upload the files [should Ok up my whole files for the game of just the additions I made to them]
Any content creation tips and advice is always very much appreciated.

**Comment by tehhowch** [comment]
This ship will not do what you want it to do without changes to the game's source code.

Changing the source code will require you to be able to compile and execute it (see the Wiki on Build Instructions). You will then also need to understand it, and identify the required changes needed to support your desired use. Be sure you follow the style guide, linked in the wiki.

As for content creation, there are several pages in the Wiki that discuss this, including recommended, freely available programs. There is also an entire Discord channel devoted to this topic.

Contributing your changes back to the community will require the use of a Pull Request. Use the search engine of your choice to learn all about this. There are **extensive** resources available to you for free so that you can learn how to do this.

**Comment by KyroFirehammer** [comment]
Ok sweet I will start research and work on that. Also how can I join that discord I have an account but the discord in in also used patreon. Other than the discord info consider this closed for the time being (I will post that the PR is open when I finish the ship )

Also I have got a mountain of new ideas that I came up with while researching for this so expect some of my favs in the future * SPOILER ALERT war is approaching.....)

**Comment by gunqqer** [comment]
I'm pretty sure on the subreddit's side bar there's a link for the Discord server (Warning: It is a wretched hive of scum and villeny and I sugest sticking to the Endless Sky and content creation rooms while steering clear of the off topic)

**Comment by MessyMix** [comment]
>Warning: It is a wretched hive of scum and villeny

Well. Someone's salty.

Anyways, almost all of our leading contributors are on the Discord.
But, before you begin, I suggest looking at the wiki over here: https://github.com/endless-sky/endless-sky/wiki. It'll help a lot.

**Comment by gunqqer** [comment]
Messy, that discord literal had a porn room and a weeb room. And also, *whoosh*

**Comment by MessyMix** [comment]
...no, it doesn't? can you please fact-check yourself before slandering? everything nsfw has been moved off server...

**Comment by gunqqer** [comment]
>had
>had
Can you not read?

**Comment by Amazinite** [comment]
You're banned from the Discord for a reason, Gunq.

The nsfw room has been gone for over half a year now (I deleted it once the Discord started to gain more traction), so given that a majority of the current members joined after the deletion of the room, I'd say you can't really consider the current members part of a "hive of scum" based off of the idea that the server at one time had a nsfw room.

**Comment by KyroFirehammer** [comment]
This may be stepping  out of my bounds,  but why don't we just make a endless sky discord specifically only for the game and it's content creation (in essence one place for all the ideas issues and forum type discussions that way we wouldn't have to deal with the "scum" ) if MZ is ok with it of course.

**Comment by Kryes-Omega** [comment]
Thats what the discord is, with the addition of an off-topic room for other discussions.

**Comment by MessyMix** [comment]
Lol "if MZ is ok with it"

he wouldn't be ok with it if he were on the existing discord, lmao. (/s)

The entire discord (exception of 2 rooms) is entirely focused on Endless Sky, so I don't see the problem...

Perhaps you should try joining before commenting!?

**Comment by KiLEdEnNis** [comment]
> that discord literal had a porn room and a weeb room

if MZ ain't joining the Discord now I don't know

**Comment by KyroFirehammer** [comment]
I was saying it in quotes referencing gunqqer o haven't joined yet but I am intending to also check out my intergalactic war discussion on steam (I'm looking for feedback)

**Comment by Pointedstick** [comment]
@KyroFirehammer, can you close this and submit your Pull Request when ready? It's pretty clear that this isn't gonna get done unless you do it. 🙂
