### ISSUE TITLE
Documentation: no information on how to buy outfits to cargo 

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#2946]
In issue #2944 I learned that I could buy outfits to cargo by deselecting all ships. After experimenting I found that I could deselect a ship by ctrl+clicking it, which showed me simple "cargo space: x/y" details.

I did not intuitively guess how to deselect ships and I would not guess that I could buy to cargo with that text (unless I already knew it was possible to buy to cargo).

The in-game first-time help should mention how to buy outfits to cargo. Maybe also mention I'm buying to cargo it in those details?

**Comment by Bladewood** [comment]
Nitpick: this is not a bug, nor is it a glitch, just a mistake in documentation.

**Comment by gunqqer** [comment]
wiki needs a big update but I'm pretty sure you can't make a PR to do it, only MZ can

**Comment by jafdy** [comment]
It's the same as the way widows handles its files. I think not enough people spend enough time in windows explorer to know all these little things.

**Comment by endlesssteve** [comment]
Put it the other way around.  The outfitter has become so complex it needs documentation to be understood. This should not be the case. Extra functions have been tacked on rather than changing the whole feature. A buy to cargo button and "in stock"/"in cargo" tags all on one standard page would be easy and obvious.

**Comment by gunqqer** [comment]
Not everyone uses windows explorer, jafdy. Some uf us use good things, like finder... ;)

But the in game tutorial should be extended a bit (Not the old man, the 10 things that pop up that can be reset) to include more things.

**Comment by endless-sky** [comment]
I've updated the player's manual to describe how the "for sale" and "in cargo" checkboxes work. Also, since the latest stable release includes those checkboxes, figuring out that that option exists should be a lot easier for people than it was back when you had to deselect all ships to buy into cargo.
