### ISSUE TITLE
Bug: window size/full screen status not remembered on OS X

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#295]
It appears that no window size information is maintained between sessions on the OS X (10.11) version of the game (0.8.8), the game neither remembers the new size/position of the window if it was resized, nor remembers if the user went into full-screen mode before quitting their last play session.

**Comment by endless-sky** [comment]
Can you post a copy of your preferences.txt file? (One directory up from the saved games.)

To avoid creating the window too large, if you are in windowed mode the window size is limited to 100 pixels less than the width and height of the screen. But, if you are in full screen mode (not just maximized, but full screen) it should remember that.

**Comment by guillochon** [comment]
A copy of my preferences.txt is available here: http://pastebin.com/raw.php?i=B5pgwPx2

**Comment by endless-sky** [comment]
If you make the game fullscreen (Alt+Enter or F11) rather than just maximizing the window, does it remember that?

**Comment by guillochon** [comment]
It does! I guess it's just the green zoom button and the "full screen" menu item that doesn't work.

**Comment by endless-sky** [comment]
Well, the real question is whether it makes sense to remove the code that limits your window size (to make sure it won't extend beyond the edges of the screen). Either way some people are going to be confused sometimes, but it seems like the number of people who want to play in almost-fullscreen instead of real fullscreen is rather small.

**Comment by guillochon** [comment]
It seems to me that both the full screen menu item and the green zoom button should work too, even if you remove that code it still won't be truly full screen (the menu bar, title bar, and dock will still be visible).

**Comment by endless-sky** [comment]
I've experimented with ways to change this, but if the window size is nearly-fullscreen there's no way to guarantee it will be placed exactly as you want it, anyways. SDL support for creating a "maximized" but not fullscreen window seems a bit patchy. And given how few people seem to want almost-fullscreen windows rather than entirely-fullscreen, I'm not sure if any change to this would be worth the inconvenience it would cause for other people who would end up with windows too big for the screen as a result.

**Comment by guillochon** [comment]
I guess you didn't quite understand the issue, the green button currently fullscreens the window appropriately, I am not talking about the "zoom" menu item, which is the "maximized" view. When you quit Endless Sky and reopen it, the window is no longer full screen. The same with the "full screen" menu item. The only way to have Endless Sky remember that you want full screen when the game first opens is to use "F11", which is not the standard OS X way of fullscreening an application.
