### ISSUE TITLE
NPC success condition does not consider actor of actions

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#2968]
For example, if the success criteria is `disable "scan cargo"` and you disable the ship, but Cap'n Pester hops into the system and scans the Syndicate Test Vessel, you're done, all set, mission complete - no need for you to scan it.

**Comment by MessyMix** [comment]
If this is fixed at all, it would probably be to consider the actor of scans, and not disables, because if a target ship is disabled by another faction, you won't be able to complete the mission (?). Besides, it doesn't really matter—the target ship is disabled anyways. But it's pretty hilarious that you can have Cap'n Pester scanning your mission ships for you.

**Comment by tehhowch** [comment]
Yes, only certain actions make sense to consider the actor, and really only the scanning criteria.
That said, having a new NPC success condition that requires the player to be the actor (playerkill, playerdisable?) would allow some creative missions and [more realistic Bounty Hunting missions (e.g. regular Pirate government, and if you don't get the kill shot, you don't get the payment)](https://groups.google.com/d/msg/endless-sky/DKaCv6PN3-c/z_Aikko9AQAJ)

**Comment by endless-sky** [comment]
Fixed in d3fd026.
