### ISSUE TITLE
Balance: Plundering and Capturing overpowered

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#2978]
I'm playing version 0.9.8. First I started by mining and capturing/plundering disabled pirates with my initial Shuttle. Then, with a Mule, I continued mining and capturing/plundering pirates and bounties, and built a permanent fleet of Headhunters (half for defense, half for offense). Now I'm plundering/capturing pirates and plundering Korath ships in Almach, have 7 pirate systems dominated, and have enough ships ready to go explore Jump Drive systems and kick ass.

Before exploring those systems I decided to advance in the Free Worlds storyline and that's when it hit me... the Free Worlds haven't come out yet!!! Need to wait another month of game time... I have a net worth of 200M credits, plenty of good outfits and hulls, and can go to Jump Drive systems. ~~This is mostly **thanks to capturing and plundering**, which means they are **overpowered**.~~ _(EDIT)_  Since the game is balanced based on real-word time then I guess it's balanced.

### Analysis

Mining was a good way to pay for crew salaries, pay back my loan and a nice supplement to buy my next ship. It was also very game-time effective since (after finding a good system) I could fill my whole cargo and return with any captured ships in 1 day of game-time. (I wouldn't mind being able to buy an outfit to scan asteroids that showed me the location and/or orbit of the asteroid in the minimap, but that's too much work for little gain)

Capturing ships was very profitable. The crew salaries to capture them is covered just by selling their cargo, but the most useful result is getting outfits to improve your ships for "free". The rest can be sold off when you need the money to buy your next ship or it can be used to build your fleet (reuse hulls or temporarily store outfits). I only had to buy a Mule ship, bunk rooms, laser rifles, fragmentation grenades and local maps. The rest was obtained from capturing ships (or plundering the Korath).

Plundering is also very profitable. The advantage over capturing is that it can be sold on more systems. The disadvantage is the limited cargo space, so I only use it to hunt for specific outfits. (I would prefer to have some way of boarding my fleet to transfer cargo around, but positioning myself well enough and jettisoning cargo is a good enough)

### Proposals

Messing with the value of things would do nothing about the hulls and outfits you obtain, which is the main benefit, so instead I propose other costs:

1. After the boarding panel closes, both ships will **stay "paused" an amount of time proportional to the amount of tons plundered and the amount of rounds the crew fought**, which introduces a cost of vulnerable play time.
   Lore: your crew is busy transferring stuff and fighting.
   TODO: what happens when multiple ships want to board the same ship at the same time?
   TODO: should the amount of crew affect the time you are "paused" while transferring stuff?
   _(EDIT)_ Scales well when you transition to bigger ships, but only because the vulnerable time is at the end. You also get more time to attack plundering npcs (assuming they follow the same rules).

2. **Require a cargo scan to plunder specific cargo**, which introduces a cost to outfit space, ship mass and play time. You could also scan from the boarding panel and spend the corresponding time "paused" after closing it.
   Lore: each cargo box only shows an identifier on the outside and the scanner results tell you what's inside, so it makes sense to be able to **plunder random cargo without the scan**.
   _(EDIT)_ Not affected by scaling, the player is paying a permanent (outfit space+mass) and temporary (play time or vulnerable time) price to have the convenience of choice. Pirates don't need the scanner because they only take cargo in an almost indiscriminate way (CargoHold::TransferAll gets outfits before commodities), which is a good enough way to get "random cargo". Only matters when you want to optimize your limited cargo space.

3. **Require an outfit scan to plunder specific outfits**, which introduces a cost to outfit space, ship mass and play time. You could also scan from the boarding panel and spend the corresponding time "paused" after closing it.
   Lore: the scanner results tell you how and where each outfit is installed, which means being able to take a random outfit doesn't make sense.
   _(EDIT)_ Not affected by scaling, the player is paying a permanent (outfit space+mass) and temporary (play time or vulnerable time) price to enable plundering of installed outfits. It matters when you want to plunder outfits from a ship you can't capture.

4. **Plundering an outfit might damage it**, which introduces a cost of wasted cargo space and play time. Damaged outfits can't be installed, and you would only know about the damage by entering the the Outfitter. (damaged outfits are probably a lot of work but also open up more gameplay possibilities)
   Lore: you need trained workers and specific tools to avoid the risk of damage when you change ship outfits and when you put cargo in cargo boxes. You don't have trained workers, specific tools or empty cargo boxes, so your efforts to remove the outfit and secure it in your cargo hold might damage the outfit.
   TODO: maybe "selling" a damaged outfit would cost you money? (fee to transport junk and/or safely recycle it)
   _(EDIT)_ It hurts beginners more than big players, so it doesn't scale well.

I also thought of the possibility of loosing crew while transferring stuff, but I don't have a specific proposal for how that would work.

**Comment by tehhowch** [comment]
1) Right now you are already paused for 2s after any boarding action
2 & 3) Neat, but i think most would agree that you can simply crack open the cargo crate after boarding a ship, or cut an outfit out of the hull. It shouldn't be too hard to convince a crewmember on the ship that telling you what's in the crate is in their best interest
4) Damaged outfits has been brought up before

I think the first step is to simply make the boarding panel non-modal. Yes, players with large fleets aren't really hurt by this since they can park their fleet in a protective circle, but this absolutely making plundering / capping in the early to mid game more difficult - either you or your target are at risk at every moment. Combine with a time-to-transfer that is dependent on outfit size, and you've got risk vs reward vs "take it all!"

**Comment by Amazinite** [comment]
>This is mostly thanks to capturing and plundering, which means they are overpowered.

I'd say that it's more because you know how to play well than just capturing itself; i.e. you're what's overpowered in the situation. Most players aren't going to go capture crazy right out the gate, so for most players this isn't exactly something they'll come across. Might I ask how many times you've played the game before this run?

Honestly, after capturing and plundering became 1/4th as lucrative as it use to be thanks to depreciation (yes, at one time you'd be sitting at 800 million credits if you did the same thing), I honestly think that capturing and plundering is fine as is. If we wanted to go any further, the above mentioned taking time to plunder outfits is all I'd say we need. As of right now, capturing does good as the combat-oriented way of earning money. The three non-combat oriented ways involve mining (a solo ship endeavor) doing jobs (can use one or many ships), and trading goods (requires many ships to be lucrative), the latter of which is the only way to exponentially increase your income.

**Comment by ghoulavenger** [comment]
You know, people claim that depreciation was a way to nerf plundering and capturing but I'm not so certain I agree with that assessment. It also kind of threw out the idea of incremental upgrades. It is not only more cost efficient to just buy a new ship and run a fleet, but selling old ships is always a net loss. That being said, I still think depreciation is a much better mechanic than death benefits, which was already a significant penalty to capping ships just not plundering them.

As far as startups go, my new strat for power gaming is literally to buy the starbarge, install a bunk room, install laser rifles, and go up north to leech from republic kills, capturing sparrows and the like until I can capture a firebird (which sometimes requires buying a bounder, capping a raven is not as easy as it sounds with a star barge). After you get a firebird, you've got enough firepower to go down south where the militia is less likely to kill steal. I had a bactrian and a fleet of falcons before war broke out. So yeah, capping is definitely a big strat if you're trying to shave off game time, but I also invested a heck of a lot more real time than a simple mass freighter method, and didn't have a lot to show for it other than an early game date -- falcons don't make money on their own and depreciation will discourage you from hot swapping ships and outfits to change your fleet structure (which is actually my largest complaint with depreciation, still better than death benefits though).

>I think the first step is to simply make the boarding panel non-modal. Yes, players with large fleets aren't really hurt by this since they can park their fleet in a protective circle, but this absolutely makes plundering / capping in the early to mid game more difficult - either you or your target are at risk at every moment. Combine with a time-to-transfer that is dependent on outfit size, and you've got risk vs reward vs "take it all!"

The problem with making it non-modal is not the defense of the flagship, but rather the ease of cross fire (allies will hit all enemies in the line of fire) or missiles destroying what you've already boarded (anti-missiles don't destroy what is targetted at enemies) while you're trying to perform actions. I think that would add a lot more frustration than anything else.

**Comment by flaviojs** [comment]
@Amazinite

> I'd say that it's more because you know how to play well than just capturing itself; i.e. you're what's overpowered in the situation. Most players aren't going to go capture crazy right out the gate, so for most players this isn't exactly something they'll come across. Might I ask how many times you've played the game before this run?

This is quite off topic, but here it goes... I only played once before this run (my first time). I was trying to get a feel of the game and see how I really wanted to play. I tried legal missions, trading commodities, fighting, capturing (got lucky and captured a fast Corvette but didn't build a fleet), storyline (helped Katya Reynolds up to leaving her undercover in Clink) and mining. I felt a good enough grasp of the game to know how I wanted to play and so deleted my first pilot and created a new one.

I decided I wanted to focus on avoiding battles, transporting people, mining, capturing ships and storyline. This time my choice for the second ship was a Mule outfitted to be faster than most pirates, with a respectable turn rate (to slingshot faster pirates), maximum amount of bunks and minimal weapons (anti-missile and mining laser). It became enough to capture any disabled pirate ship and could hold lots of cargo (for plunder or mining). The headhunters were initially just meant to be extra flotsam catchers, but I found them quite effective in battle too. Bounty hunting provided very nice outfits. Dominating pirate systems was time-consuming on some (run around and disable the fastest chasers first) and cheatty on others (wait for an author ship to come destroy the chasers, or wait for them to die while idling over the "cowardice range" where they wont chase you).

> Honestly, after capturing and plundering became 1/4th as lucrative as it use to be thanks to depreciation (yes, at one time you'd be sitting at 800 million credits if you did the same thing), I honestly think that capturing and plundering is fine as is. If we wanted to go any further, the above mentioned taking time to plunder outfits is all I'd say we need. As of right now, capturing does good as the combat-oriented way of earning money. The three non-combat oriented ways involve mining (a solo ship endeavor) doing jobs (can use one or many ships), and trading goods (requires many ships to be lucrative), the latter of which is the only way to exponentially increase your income.

Back on topic, after getting the Mule I was finally able to plunder the outfits I wanted and capture big ships. This made a huge difference. From systems with "large" pirate fleets I can net up to around 5M per game day. While plundering the Korath in Almach I can almost double that.

Heck, even if the captured and plundered stuff sold for 0 credits it would still be a profit as soon as I reused an outfit or a hull because I didn't have to pay for it! Also note that I got rich fast while avoiding  combat, only latter did I start fighting too (causing minor improvements in profitability).

Think about it, capturing means I don't really need to spend money and I can get a constant stream of money coming in. Trading commodities may be exponential, but you need to spend money to make more money.

**Comment by ghoulavenger** [comment]
>Think about it, capturing means I don't really need to spend money and I can get a constant stream of money coming in. Trading commodities may be exponential, but you need to spend money to make more money.

Doing missions doesn't seem to cost money either, and you're not complaining about the efficacy of missions. I don't think that this really is being applied correctly for your argument. Trading commodities *is* the most extensible way to make money, not necessarily the *best*. That really depends on the size of your fleet and cargo hauling capability (capping ships and plundering tends to be better for combat fleets, there is no real endgame for passenger haulers -- I count them as free missions since either haulers or combat fleets can do them effectively and there is no way to capitalize on fleet crew capacity, and cargo fleets are best at freight). So to put it more correctly, it requires *investment*.  

By the way I'm not saying you're wrong about early game tactics, capturing is pretty powerful especially since you don't even need to fight to do it. But it too has a significant risk element, pirate raids are often dangerous (until your tech/ships just outmatch them to the point of absurdity), and staying in the same system to wait for random pirates eats up time (it is merely coincidental that it went along with your mining expedition). It also isn't predictable. I've spent days capping ships from pirate systems (where I could pull in 30m in a single game day but I almost never did, 15-20 is much more realistic assuming good RNG) to only have all of my captured ships destroyed.

**Comment by tehhowch** [comment]
Spawning a government's raid fleet in response to capturing a ship could be an answer, but it too will increase the frustration, and only for players with insufficient fleet strength to defeat the raid fleet. Those with the strength would probably celebrate the increase in spawn rate, as it means they can exhaust their available crew more quickly.

A more aggressive fix is to switch from our current "fixed time" system into one in which crew costs will be assessed periodically in-flight, and not only when entering a system. This boosts the competitiveness of mission and trade careers, as they are still largely focused on number of jumps and not combat, while decreasing the profitability of combat-focused earnings, due to both increased bribe requirements (bribes will expire on each day, as they do now), and repeatedy levied crew salaries while waiting for ships to become available for plunder / capping.
I'd think a good initial "one day" timeframe would be 3-5 minutes of wall time (60 * 60 * 3 frames).
Paired with a non-modal BoardingPanel, or at least one which requires a handful of seconds to transfer each item, adds an actual cost to every decision.

**Comment by ghoulavenger** [comment]
>A more aggressive fix is to switch from our current "fixed time" system into one in which crew costs will be assessed periodically in-flight, and not only when entering a system. This boosts the competitiveness of mission and trade careers, as they are still largely focused on number of jumps and not combat, while decreasing the profitability of combat-focused earnings, due to both increased bribe requirements (bribes will expire on each day, as they do now), and repeatedy levied crew salaries while waiting for ships to become available for plunder / capping.

Mission based careers work in T1 content, but I don't think they extend well into T2 content because they do not scale with large fleet sizes (sure they're larger missions, but still based around only a few freighters or warships tops, and you can buy several warships/freighters pretty easily) so I do not think this will encourage mission based careers. People that want to do mission based careers will do so largely because they enjoy the content, I certainly have fun reading some of the mission messages, but I only do them when they're going my way. Honestly I think trading is actually better than combat already as well. It just doesn't have an early game at all. The shifting of trade good prices as you run them makes it less preferable to just go back and forth, which makes the most profitable areas significantly less so in a hurry, similarly it increases the odds of pirate raids, which in the early game is lethal (after you have a decent fleet going, pirates are only a concern if you're not armed or are using small craft). The density of missions in human space also doesn't really help a trading based careers start, unless you don't know where to trade and the mission helps you explore.

On the other hand, even the lowly sparrow is a full quarter of your initial loan, so it doesn't take much to get exponentially ahead of the other methods. Your suggestion to make in game days pass as you wait could address this because you're talking about (10k a day versus 50k+), but not only might it overreach (making combat horrible to make money in game days, and taking more real time than the other methods), but it might also destroy asteroid mining (but maybe I'm just that bad at it, it takes me several minutes to find a single asteroid that I can actually destroy).

**Comment by Lineth** [comment]
'stroid mining in Ascella (3 jumps southeast of start) is hands-down the fastest and most efficient way to get a quick start. It's fairly easy to do, as well, because the asteroids you're interested in are blue as opposed to grey-brown and stand out pretty well.

I honestly think capturing is balanced fairly well as-is. But I grant I am probably just really bad at it. It's the most lucrative, but really it should be considering the inherent risk and mid-to-late-game nature of it. (And I never could easily capture any ship in Republic space, the kill-crazy tools. Also, I'm terribad at getting rich in late game.)

**Comment by tehhowch** [comment]
Harvested mineral value would indeed need to be raised in a system that uses continuous time.

**Comment by KiLEdEnNis** [comment]
I've been playing for (if I remember) over 1,5 years, and have near 10 playthroughs, so I know capping is hard and very rewarding early, and only experienced players can do so properly early game, if you nerf this you make it nearly impossible for new players to get any profit if they succeed, and experienced players aren't really affected as much as newer players

**Comment by endlesssteve** [comment]
I think everybody is getting too worked up about the money thing. It"s not really the point of the game.
So you get a mega fleet and billions of credits and .....completely spoil your own game.

However one point I have with the caping or plundering is the lack of any consequence of getting large numbers of your own crew killed. It doesn't feel right and that doesn't fit in with the atmosphere you get from the stories.

**Comment by KiLEdEnNis** [comment]
death benefits were removed to make it actually worthwhile to cap big ships
the more crew dies the more control ya lose over your ship if you go below required crew

**Comment by tehhowch** [comment]
Which is hardly much of a punishment with speedup and a large fleet to protect you

**Comment by endlesssteve** [comment]
I deliberately didn't say bring back death benefits.
I didn't mean just the crew killed off capturing one ship. If you capture ships as a means of making lots of money you capture dozens of ships and lose hundreds of crew. With no penalty of any sort.
Another idea is that the whole surviving crew share the loot as in earlier times at sea.

**Comment by flaviojs** [comment]
Let me clarify... by overpowered I mean you can prepare a jump drive fleet too fast when you look at the game date. And it looks like none of my proposals actually fix that... not a good start. -.-'

Capturing isn't really hard to do, just look at the odds and refrain from capturing what is too risky. There are plenty opportunities to capture when there is an ally faction fighting an enemy faction. My guess is that seeing a disabled ship you can't capture makes you feel like it's hard (wasted opportunity).

@KiLEdEnNis

> I've been playing for (if I remember) over 1,5 years, and have near 10 playthroughs, so I know capping is hard and very rewarding early, and only experienced players can do so properly early game, if you nerf this you make it nearly impossible for new players to get any profit if they succeed, and experienced players aren't really affected as much as newer players

Wasn't considering how it would scale as you progressed.

Proposal 1 scales well when you transition to bigger ships, but only because the vulnerable time is at the end. You also get more time to attack plundering npcs (assuming they follow the same rules).

Proposals 2&3 are about paying a permanent (outfit space+mass) and temporary (play time or vulnerable time) price to have the convenience of choice. Pirates don't need them because they only take cargo in an almost indiscriminate way (CargoHold::TransferAll gets outfits before commodities), which is a good enough way to get "random cargo". It seems to encourage capturing ships over of plundering, so I guess it only truly matters when you want to plunder a ship you can't capture.

Proposal 4 hurts beginners more that big players, so it doesn't scale well. But it sure is tempting for potentially opening up more gameplay possibilities.

**Comment by ghoulavenger** [comment]
>Let me clarify... by overpowered I mean you can prepare a jump drive fleet too fast when you look at the game date. And it looks like none of my proposals actually fix that... not a good start. -.-'

Does the game date actually matter? I think time investment is a much more serious concern. For example compare the two fleets:

1. My combat fleet can capture between 15-20M of ships reliably, but it takes me at least 3 minutes with fast forward, and sometimes the ships can be destroyed wasting valuable time. Said fleet has a bactrian flagship (to maximize capturing potential) and 12 heavy warship escorts (to make this exceptionally safe).

2. A fleet of 12 deep rivers (at 1140 cargo capacity a pop with jump drives) can make 300 credits per ton on a single jump trip (not everywhere, and with some fluctuation higher and lower, 300 for arguments sake). So basically 4 million a jump. 

In the time it takes me to do one game day on the capture fleet, I will have done 8 jumps if not more, grossing 32,832,000 in the same amount of time that combat fleet will pull in 15-20m. Sure, the cargo fleet will take 16 game days (1 day for each jump and another for landing) to make that money, but game days usually aren't important. They're only important at the very beginning when you're under time pressure to pay back your first loan (since it hinders your growth potential, although loans actually are a great way to expand your fleet if you're a cargo hauler), or for rush jobs if you're picking up missions.

**Comment by MessyMix** [comment]
Game date matters because there's a date on the Geminus bombing, and you
can amass a way too OP fleet before the storyline could possibly start.

**Comment by ghoulavenger** [comment]
If you say so but the window for starting the war can be anytime you want after that point. Still no time pressure.

**Comment by MessyMix** [comment]
Yeah, I agree. Honestly, I don't see a problem, as you have to already KNOW
where to look to be able to make money fast early-game; it's not (normally)
something you can do accidentally right off the bat. I, like many others,
spent my first month in serious debt because of poor fund management
and—well, just general inexperience. But, if there is a easy fix to this
problem, I'd have no problem going with it.

**Comment by endless-sky** [comment]
The game is balanced based on how much real-world time things take, not how much in-game time they take. Mining and plundering allow you to have a strong fleet at a much earlier in-game date, but you'll need to spend a significant amount of real-world time to do so (especially if you're in a shuttle trying to get lucky and plunder a pirate ship that someone else disabled).

**Comment by flaviojs** [comment]
If it's real-world time then it's not overpowered. It takes almost no extra time if you do it while mining and don't discriminate what you capture (irregular income) but takes a lot of time if you're hunting for specific ships (high income).

**Comment by kaylara** [comment]
Sorry I'm late to the party.

As someone who played a lot of Escape Velocity and played through Endless Sky three times now, I agree the current system of capture is too lucrative mid-late game. Early game I find very difficult to win combat/capture regularly.

Once I obtain a capital ship on the order of the Falcon or Leviathan as an escort with some continuous weapons, however, I can easily capture pirate fighters and make ~$100-500k very rapidly.

From there, I build a capital fleet. Capturing pirates then Hai Unfettered is too much money, too quickly. I have tried all kinds of mission strategies (best seem to be Wanderer or Coalition) and trading routes (usually within human space) with reasonable (~10k tons?) cargo space. However, nothing seems to beat capping 2-3 Unfettered Hai in Wah Ki for $20-30M using some large crew capacity ship, and I can use my combat fleet for the task -- I don't need to switch out, retool, or use other ships for the task (as I would for the missions or cargo).

With death benefits, really well-defended and big ships required a lot of money to capture and keep in addition to the difficult of the fight. With depreciation, capturing ships becomes lucrative and an inexpensive way to upgrade compared to purchasing.

I support the 4th proposal.

Additionally, perhaps you need to "share the bounty" with your surviving crew (including escorts), so you have to pay something similar to death benefits... maybe this kicks in slowly and scales with crew size... something like:

BountyShare = max(0,(crewSize-500)/(2*crewSize))

Below 500 crew members, you don't have to share. At the same time, with large crews, you never have to pay more than some maximum percentage (50% in my example) of the bounty. Nevertheless, increasing crew makes capturing ships less lucrative.

**Comment by Pointedstick** [comment]
Another suggestion: mark "internal" outfits as unplunderable and require you to cap the ship to get them, which is more dangerous and can't be done in a tiny ship with an unarmed skeleton crew.

https://github.com/endless-sky/endless-sky/issues/3346

**Comment by Tadrix** [comment]
> Another idea is that the whole surviving crew share the loot as in earlier times at sea.

Bad idea. This entices to try and win the fight with largest casualties possible. Because less survivors = larger shares.
Besides: https://en.wikipedia.org/wiki/Prize_money#Distribution
So 3/8 to the captain, rounded up (because in the game player is also a pilot). Added complexity, no real benefit.

**Comment by endless-sky** [comment]
The mechanics for plunder and capture have gone through a lot of variations in an attempt to balance them. The first version was indeed that all crew members got a bonus that was some fraction of the plunder, and the bonus had to be paid back over time. Among other things, that caused the problem that if you captured a ship and it was destroyed before you could sell it, you could end up deeply in debt.

The next balancing mechanism was death benefits, where you owed a share only to the crew members who died while capturing a ship. But that created a heavy incentive to only attack and capture the smallest ships, which is a whole lot less fun than going head-to-head with a single strong ship and defeating it. And it had the same problem as before if a ship was destroyed before you sold it.

Capturing or plundering ships takes less in-game time, because you can capture a dozen ships in one system, but in terms of the time it actually takes the player to earn that money, it's now on par with other less interesting strategies like shipping tons of commodities with a fleet of star barges. If plunder were made even less profitable, the easiest ways to make money would be the most boring and grind-y ones.
