### ISSUE TITLE
Illegal outfits?

### ISSUE THREAD

**Issue by ph2000bis** [endless-sky/endless-sky#2998]
The description of the outfit scanner currently says 

> The Republic Navy uses these scanners to detect when ships are equipped with illegal weaponry.

 Does refer to Nerve Gas Grenades, and should other weapons qualify as illegal weaponry, such as nukes or modified blasters? It does not seem that anything else uses the `"illegal" x` attribute

**Comment by Bladewood** [comment]
Nerve gas and illegal cargo, like drugs.

There is no reason for modified blasters to be called illegal. They definitely void the Syndicate warranty, sure, but that doesn't make them illegal.

On the topic of nukes, the Republic has bigger problems than illegal objects.

**Comment by PlanetLP** [comment]
as bladewood said… if somebody got nukes and leaves you alone, better don't change it.

**Comment by ph2000bis** [comment]
Illegal cargo is covered by the cargo scanner.
But does it mean that the republic has developed an outfit scanner just for nerve gas? Perhaps this could be used as a balancing factor for other outfits or future outfits. Could it also link to having a ship (or outfit) that the player doesn't have a license for?

**Comment by Bladewood** [comment]
Just some secret illegal stuff. We're not told what it is.

**Comment by MessyMix** [comment]
Modifying an Energy Blaster isn't illegal. It just voids your warranty. ;)

**Comment by endlesssteve** [comment]
Obviously this is just the excuse used by the Republic to scan your outfits. Just like real governments read all your mail looking for terrorists.

**Comment by ghoulavenger** [comment]
@endlesssteve The government doesn't have the manpower to read everybody's mail (although they certainly could be reading an individual's mail). They do collect a lot of data over wireless devices and such though, and that data can be analyzed by a computer. Still not very likely to find much but eh, a little conspiracy heavy for my taste. 

On topic though, I thought the illegal modifier was more of a proof of concept than anything else. Yeah it sees some use but it's pretty light considering just how large the development space for it is. Would be nice to see more illegal outfits developed (although admittedly I hate the mechanic -- I never really liked how effective interference plating was and the republic scans ships religiously which really harms the fun for me, I actually just turned the fines off for carrying around nerve gas because of it).

**Comment by endlesssteve** [comment]
@ghoulavenger  The syndicate secretly nuke two planets and the Pug are up to who knows what and you think it"s conspiracy heavy. God, wake up man and smell the coffee!!!!!

**Comment by ghoulavenger** [comment]
@endlesssteve No outfit the pug have will be considered illegal, since it is beyond the realm of what humanity can even conceive of (like how the pug shattered a quarg ringworld). On the nature of the nukes, I think those go beyond just illegal, aren't they considered an atrocity?

**Comment by tehhowch** [comment]
nukes aren't illegal. immoral, perhaps.

**Comment by MessyMix** [comment]
Nukes used in space probably wouldn't be immoral, but it might not be within ROE (i.e. a war crime to use nukes). They're just a different kind of weapon that happens to be extraordinarily powerful, and it's ban is probably just some kind of relic from ancient laws. (Plus, no-one seems to need nukes. Pirates want to keep their enemies alive.) In space, radiation from nuclear weapons—unless you're in the blast radius—is insignificant compared to space radiation.

**Comment by KyroFirehammer** [comment]
However I would love to see multiple things

A pirate varyant of the marauder ships with built in interference plating 

A way to refuse to pay fines at the cost of angering that govt 

Multiple pirate weapons such as a upgraded quad baster turret or upgraded meteor missiles 

A way for if you have a special licence with the government that would fine you to "turn a blind eye" (like dominated planets or the planets of the side you chose during the FW campaign )

AND if we really was go an extra mile a revamp to the tributary system it's really odd that you have forced these planets under your control yet( let's say your like me and ruin any government with a cloaking fleet and a flagship of a legit world ship and you said "eh screw it" and literally took over every human government) they will still refuse to sell you ships because you don't have the licence, but your basically holding the whole government at gunpoint

**Comment by MessyMix** [comment]
I wouldn't mind having a smuggling marauder ship (Engines variant, maybe?) come with built-in (like into the hull, you mean?) interference plating, if that's possible. That would be a nice touch, albeit not terribly important.

Refusing the fines but angering the government is a legitimate idea, but I think that would be overly complex to implement and lore out, so I'd leave that one alone for now.

Upgraded pirate weapons probably aren't going to happen, though.

I'm not sure if the pirate jobs that @Amazinite did had a reputation-restoring license (like a fake ID). I seemed to remember it, but I might be mixing things up, and I can't really check on that one right now.

The tribute system currently is just a post-endgame kind of thing. It's not meant to be a real in-game feature, and if MZ intends it to be then he will rework it.

By the way, good job on that post. That was very legible. Makes all of our lives a lot easier.

**Comment by Amazinite** [comment]
>I'm not sure if the pirate jobs that @Amazinite did had a reputation-restoring license (like a fake ID). I seemed to remember it, but I might be mixing things up, and I can't really check on that one right now.

Didn't make the final cut; I cut down the size of the PR for the sake of simplicity and actually getting something merged.

**Comment by MessyMix** [comment]
Good for flavor, I guess. Maybe @endless-sky could chime in a little here, although he does have a penchant for reticence....

**Comment by KyroFirehammer** [comment]
Hey @MessyMix Good to hear it's appreciated

Also it would be cool to have those sold on pirate planets and not only obtainable by capture (for a large price of course)

**Comment by endless-sky** [comment]
Originally I planned to have a lot more slightly-illegal outfits, but getting fined all the time is rather annoying.

**Comment by tehhowch** [comment]
Turns out the Free Worlds have a point :grinning:
