### ISSUE TITLE
Re-allow taking mission cargo with lesser cargo full

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#30]
There's an usability regression: in 0.7.9, the missions screen considered space taken by lesser cargo to be available for missions.  The overage, if any, was automatically sold when you departed.  This is no longer the case in 0.7.10: if you're travelling with a full hold (ie, most of the time), all cargo missions will be shown in dark brown and you can't take them unless you empty the hold first.  This requires you to make an additional step, of first selling all cargo, then viewing missions, and then finally re-buying the cargo.  This is merely an usability problem as there's no penalty for re-buying cargo back and forth.

Related: if your hold is overfull (due to a mission you took from a random event rather than the missions screen), even passenger missions are darked out until you sell the overage.

**Comment by akien-mga** [comment]
Yeah, that's due to fixing #16. I was also an advocate of keeping the "feature", as it makes it easier to play as a freighter with full cargo and still accept the missions you want to focus on. On the other hand, players who never knew the previous feature should not be bothered by the change :)

**Comment by endless-sky** [comment]
That change was in response to a different tester complaining that allowing "negative" cargo space was really confusing to them as a new player. I decided that avoiding confusing new players seemed more important, but I'm open to changing it back the way it used to be if you really think that's an important feature.

I guess the best option would be to let you accept the mission, but when you click accept it would pop up a dialog saying, "Sell <n> tons of cargo to make space for this mission?" and sell that cargo immediately, rather than showing negative cargo space.

**Comment by kilobyte** [comment]
Negative cargo space also happens whenever a random event mission gives you something (like, 2 for package, etc).  This includes story missions as well.

I guess, perhaps it'd be easiest to instead display negative values as "2 over"?

**Comment by endless-sky** [comment]
In commit 0c0a634 I've restored the ability to accept jobs that require you to sell ordinary cargo or fire extra crew to make room for them. But, it will now pop up a dialog confirming that that's really what you want to do. To me that seems like a reasonable compromise, providing most of the convenience while also making it much less confusing to beginning players. Let me know if you think this is a good enough solution.
