### ISSUE TITLE
Quantum Keystones

### ISSUE THREAD

**Issue by anyoldname8** [endless-sky/endless-sky#3010]
When given the Remanent mission to get 50 quantum keystones, if purchasing from Hai space the keystones are added to outfit space, not cargo space which doesn't trigger the end of the mission when returning to Viminal in Remanent space.

**Comment by endlesssteve** [comment]
Did you specifically try to buy into cargo or did you just buy them. The outfits are installed as default.
I had a similar problem with this mission but also had problems with the new outfitter screens which have since been fixed.
I got around the problem by selling in Viminal then buying back into cargo which then triggers the end of the mission.
If you have a save before you buy the stones run through it again. use ctrl to deselect your ship and try buying into cargo.

**Comment by anyoldname8** [comment]
Yes you are correct. First you need to deselect all your ships before purchase. It is confusing as when in the outfitters it says buy, not install. I too sold my keystones in Viminal then bought them back with my ships deselected. I then repeated the process returning to Hai space by deselecting my ship and buying into cargo before selling them back in Hai space. It is more confusing rather than a bug.

**Comment by Lineth** [comment]
This seems to be a good example why I think the Remnant missions could do with being rebalanced a fair bit. But this in particular just needs the buy-into-cargo explained better.

**Comment by endlesssteve** [comment]
I'm not completely sure there isn't an issue here. I"m at the point where I could try this mission again with a recent build and see it it works as expected.

**Comment by endless-sky** [comment]
Is it possible you installed the keystones on an escort, rather than on your flagship? By design, missions that remove an outfit from your ship / cargo do not take it from escorts, because that could create really confusing results (especially for the FW missions that branch based on the type of hyperdrive you have).

**Comment by jafdy** [comment]
What about making it a mission with 50 tonnes of cargo and you pay the cost of the keystones when you start that mission. Although people would complain that they should be able to do it the other way so you would need to leave the old mission in.

**Comment by endlesssteve** [comment]
In 9.7 the mission would only complete if the keystones were cargo. This seems sensible other wise your ship would be like a flying Xmas tree!
I just want to be sure this is just the usual outfitter confusion and not something else.
If I find anything I'll open a new more specific issue.

**Comment by endlesssteve** [comment]
I've just got to the mission and the stones could be bought straight to cargo without problems.

It's easy when you know how.

**Comment by endlesssteve** [comment]
...and mission completed without problems or delay. The keystone should be in cargo.
