### ISSUE TITLE
ships with zero max speed have backverds momentum after exiting hyperspace

### ISSUE THREAD

**Issue by abenkovskii** [endless-sky/endless-sky#3023]
v0.9.8 (built from source), Linux

Is this intended that flagships with 0 maximum speed move backwards after exiting hyperspace if you use normal hyperdrive?

To reproduce:
1. Buy scout
2. Sell engines
3. Buy afterburner
4. [D]epart
5. [J]ump to any neighbouring star system

Expected:
Ship exits hyperspace with zero momentum

Got:
Ship is moving backward after exiting hyperspace

Not tested yet:
Does the same apply to escort ships?

**Comment by MCOfficer** [comment]
i not quite sure how i should imagine this, so for clarification: by backwards, do you mean that

- the ship moves in reverse to the jump direction, i.e. when you jump to a system to your left it moves to the right, or
- the ship accelerates against it's own momentum (it seems to break)
- or something completely different.

in the best case, drop a Video or GIF here showing the issue. maybe i'm just dumb, people tell me that happens.

also: any plugins, any modifications?

thanks in advance.

**Comment by lifeyouristhis** [comment]
I've tried it. It works just as he described. After the jump ship suddenly, um, bounces back (that's how it looks like).

**Comment by Disiuze** [comment]
I quickly made [a video](https://www.youtube.com/watch?v=iKFA0Q8swQY) demonstrating this.
Note that the escort is unable to jump at all.

**Comment by jafdy** [comment]
If I had to guess, the exit speed is `maxspeed - abit` or `presetmax` whichever is smaller.

**Comment by tehhowch** [comment]
The exit speed is indeed `maxspeed - abit`:
https://github.com/endless-sky/endless-sky/blob/3a1af5dab6027d2a08198ade0ca9ffc85e3bae78/source/Ship.cpp#L977

Each step while the ship is decelerating, it loses 2 (`HYPER_A`) velocity units in the direction it was hyperspacing. Because the likelihood that the ship started with exactly 0 velocity is essentially 0, this is essentially impossible to meet for ships without thrust:
https://github.com/endless-sky/endless-sky/blob/3a1af5dab6027d2a08198ade0ca9ffc85e3bae78/source/Ship.cpp#L987-L991

which means that the ship will continue to lose 2 velocity units until the `hyperspaceCount` variable is 0. However, these "lost" units are in a direction, which at some point cause `velocity.Length()` to begin increasing again, but now the ship's velocity is in the direction it hyperspaced from.

This could be fixed by 
`double exitV = max(HYPER_A, MaxVelocity())`

**Comment by endless-sky** [comment]
Fixed by merging #3026, although ships with no ordinary thrusters are going to cause you plenty of other problems too...
