### ISSUE TITLE
pirates give double bunks!!!

### ISSUE THREAD

**Issue by endlesssteve** [endless-sky/endless-sky#3055]
Standard 9.8 version from the Ubuntu PPP.
In the early game before FW I'm running a shuttle. I have several transport missions active.
I'm disables by pirates and they board me. They seem to have stolen my passengers as all my bunks are free but I still have the missions and can complete them plus I have all my bunks free for new missions.
They don't take my mission cargo. I'm not sure if I had other cargo.
Only after a quit and restart later do I get negative bunks.

**Comment by toilethinges** [comment]
So the pirates are taking your passengers but not failing the mission?

**Comment by endlesssteve** [comment]
Yes.  and not taking cargo. Rather funny pirates. May be they were short of crew and wanted to press gang them.  Still the missions should fail to be consistent. I don't actually know what the pirates are supposed to do if they board but what happened is not logical or consistent. I expected they would take cargo and mission cargo.
I think most people hit the reload button if they get disabled but I don't want to if my character isn't actually killed. I just hailed a passing merchant for help.

**Comment by tehhowch** [comment]
Looks like the Ship::Board and/or CargoHold::TransferAll methods needs a tuneup. Currently, for `autoplunder` situations (someone other than the player does the boarding), `cargo.TransferAll` is used, and the first step done there is Cargo::TransferPassengers, then outfit transfer, and lastly commodity transfer.
https://github.com/endless-sky/endless-sky/blob/93979842e1bdaa023fe52dd530b8b2dee0a3ad1b/source/Ship.cpp#L1383-L1395
https://github.com/endless-sky/endless-sky/blob/93979842e1bdaa023fe52dd530b8b2dee0a3ad1b/source/CargoHold.cpp#L463-L496

There is an event generated for boarding actions:
https://github.com/endless-sky/endless-sky/blob/93979842e1bdaa023fe52dd530b8b2dee0a3ad1b/source/Engine.cpp#L1015-L1021
These events get handed to AI::UpdateEvents, so that AI ships know if they have previously boarded someone.
These events also get handed to MainPanel, which sends them to PlayerInfo::HandleEvent, where each of the player's missions run Mission::Do on the event:
https://github.com/endless-sky/endless-sky/blob/93979842e1bdaa023fe52dd530b8b2dee0a3ad1b/source/Mission.cpp#L752-L767

As can be seen above, the cases for a player's ship being boarded and losing passengers or mission cargo have not been addressed - only the ship's destruction.

I'll submit a PR to remedy the missing event processing later, if someone hasn't beaten me to it by then.
As I see it, once the missions fail due to event processing, the transfer of passengers and mission cargo isn't an issue - pirates stole your passengers to sell them into slavery, and your mission cargo was extra useful in their quest to please their current warlord.

**Comment by tehhowch** [comment]
An alternate solution would be to flag the ship that stole your mission cargo as `personality marked target escort` and only fail the missions whose cargo/passengers it stole from your fleet if that ship is destroyed. This is a more realistic (and likely, fun) solution than failing the missions when the cargo gets stolen, as the player has a new quest to steal back the cargo, but is considerably harder to implement (requires flagging the boarding ship as special, modifying its personality, and possibly instantiating a mission around that ship, with it as the NPC (success criteria = board), and also sharing the mission cargo / passengers with those missions that would otherwise fail - something that is currently not possible).

**Comment by endlesssteve** [comment]
To fit in with the other mechanics I would think the order should be  commodities-outfits-passengers.
With player mechanics you can easily steal commodities and outfits from the outside of the ship but crew/passenger affecting action need an attack. No need to go into that in detail as the player will die anyway. However if the pirates are interrupted during boarding ( I assume this is what happened to me) it makes more sense to be left with the passengers but no commodities.
The getting back the passengers does sound like an interesting idea unless like me you were flying a shuttle. if done that way there should be some time limit so your not stuck with impossible missions.

Thanks for reading the issue and taking it seriously. After I wrote it I regretted using such a light hearted title. It just seemed like fun at the time.

**Comment by tehhowch** [comment]
The order is done in this manner because that is the item importance to the player, and this function (CargoHold::TransferAll) is used when you land and depart to pool all your cargo together, or distribute it out to your ships, respectively.

Rather than merge #3059, MZ may choose to write some conditions into the TransferAll function that exclude transference of mission cargo and passengers during a plunder operation.

**Comment by endlesssteve** [comment]
The main thing at this point is to correct the mission failure point. the game is then consistent. If you follow up on the idea of some plot lines involving getting back lost passengers or cargo I think the logic should match that used for player boarding. i.e cargo and outfits are on the outside of the ship and easy to steal. the crew and passengers are inside and the ship needs to be attacked to be plundered This might make some of the defensive outfits have some sort of use.  Not a big deal just my penny worth.

**Comment by endless-sky** [comment]
Fixed by merging #3059.

Pirates stealing your passengers was unintentional, so I'll think about whether that ought to be allowed or not.
