### ISSUE TITLE
Package links not avalailbe ?

### ISSUE THREAD

**Issue by sbeden** [endless-sky/endless-sky#3057]
Hello there,

Came looking some time later and found that the link for the package version is no longer available ?

Since it do not seem to be an alternate option as to get the game (its on version 9.4 over opensuse repository, since it is not operated by someone from here (?) there is probably nothing to do, still, any insight would be appreciated.

Its fine to delete this message once read.

Regards, thanks in advance.

**Comment by tehhowch** [comment]
https://github.com/endless-sky/endless-sky/releases

If that link doesn't have what you are looking for, please reiterate the intent of your post. I understand your post to be asking for the updated version of the game, since your host OS's packaged version of it is still 0.9.4, according to this page: https://software.opensuse.org/package/endless-sky

**Comment by endlesssteve** [comment]
Possibly you could compile the game yourself. There are Linux build instructions in the wiki. Note there is an error and package libmad0-dev is needed not libmad-dev. This will save you a bit of googling.
If your using opensuse I assume you have some idea with this sort of thing.
