### ISSUE TITLE
Clarify cooling inefficiency's effect

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3074]
So we're getting a lot of confusion over outfits expansions.
I'm guessing this is because cooling inefficiency's tooltip is not exactly helpful in explaining how it works:
> Interferes with your ship's ability to cool itself.

We've gotten a few suggestions:
* add a graph, instead of just text

While a graph would be extremely helpful, I'm not sure if it's actually possible to put one under a tooltip. In addition, it'll probably take up too much space, at least in comparison to other tooltips.
* provide the exact formula

This provides clear and exact accuracy, but it'll probably be a pain to ordinary players for obvious reasons.

Besides that, I propose this description instead:
> Your cooling systems will degrade in performance quickly the more of this attribute you have.

I also propose that we put some raw stats, or at least relative information(?), giving us an example of just how quickly or slowly it grows. Consider the ramscoop attribute's tooltip:
> If you add more than one ramscoop, each additional one is less effective: you need four ramscoops to achieve double the recharge rate that one ramscoop provides.

A user named @Janaszar gave this as an example (though I cannot confirm if it is actually accurate):
> Changes Cargo Space to Outfit Space.  These expanders decrease the efficiency of cooling modules non-linearly; 1 unit sees almost no change, 3 units see ~8% reduction in efficiency and 7 units reduce cooling module efficency by ~47%

**Comment by gunqqer** [comment]
A graph of it would be cool, even if not put in game

**Comment by Janaszar** [comment]
Janaszar here; just made the account.  The actual values I have for those are:
Cooling Inefficiency Units | Impact on modules
------------ | -------------
1 | 0.38%
3 | 8.16%
4 | 16.26%
7 | 46.64%
8 | 55.92%

I picked 3 & 7 as I would expect the 10% and 50% marks to be of interest to users.

Graph as made by MZ can be found in the Creating Outfit page: https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits
Based on that, I think these values fit.

**Comment by Amazinite** [comment]
@gunqqer A graph already exists on the creating outfits page.
![image](https://user-images.githubusercontent.com/17688683/30779036-451e63de-a0b2-11e7-81a8-1f1a03f5113f.png)

**Comment by ghoulavenger** [comment]
@Amazinite now put it in game. I think thats what he meant.

The general rule of thumb I discovered is, if you're using 4 or fewer outfits expansions, it probably doesn't change any builds previous to mass expansions. It really affects putting the heavier outfits on bactrians (which I know some people wanted, but I didn't really see the problem since T2 ships already outclass bactrians, unless you're putting skylances on them, but skylances are broken in and of themselves, just 2 of them are better than 4 of any other current turret mounted weapon). It was probably necessary increasing the cargo capacity of freighters though just to prevent invincible freighters.

Personally I think the effect of outfits expansions are pretty obviously illustrated when you just start adding outfits expansions to your ship, and your cooling literally starts doing nothing. Don't even need any outfits other than your reactor and any piece of cooling equipment to see the drastic effect. If you wanted to make it more obvious it should probably say something like "Using an outfits expansion will most likely require additional cooling". Which is largely a true statement, unless you keep under 4 outfits expansions, but if you're using that many outfits expansions you're probably already running hot equipment and are almost certainly using passive cooling, and maybe active cooling (I'm still not sold on active cooling since it might require a higher power generation threshold, which in turn needs more cooling).

**Comment by Bladewood** [comment]
gunqqer had assumed that such a graph did not already exists (but it does), and asked for someone to make one, even if it weren't going to be put ingame.

**Comment by endless-sky** [comment]
I've added a bit more detail to the tooltip in 091acd4.
