### ISSUE TITLE
Feature request: a couple more buttons

### ISSUE THREAD

**Issue by ReimeiSky** [endless-sky/endless-sky#3079]
http://steamcommunity.com/app/404410/discussions/2/1474221865199984718/
# In-game button to open save file folder
Like in Minecraft.
![save folder](http://i.imgur.com/BF2m174.png)
We could also, instead, add a button that links to the plugins folder, or just to the general save directory (on Windows, `C:\Users\[REDACTED]\AppData\Roaming\endless-sky`, rather than to `~\Roaming\endless-sky\plugins` or to `~\Roaming\endless-sky\saves`; you get the point).
# Player Manual button
this_is_your_life:
> While we on subject of adding buttons, I'd suggest adding one leading to the github's [Player Manual](https://github.com/endless-sky/endless-sky/wiki/PlayersManual) page (the one where many hidden key bindings and functions are explained).

**Comment by warp-core** [comment]
Two of these things are done: #6768 and #9588.
Adding a button that opens the player's manual is also requested in #8057 and #7938 is also related.
#3663 proposes making the information from the player's manual available within the game (which I think I'd prefer, rather than having a button that opens a webpage.)
