### ISSUE TITLE
Feature request: Block flagship destruction.

### ISSUE THREAD

**Issue by endlesssteve** [endless-sky/endless-sky#3080]
While thinking about the many balance/instant death problems I have this idea.

If the flagship can be disabled and have cargo stolen but not destroyed the player can choose to continue the game and not be forced to reload. This could then make 3077 obsolete.

This would still be a big set back for the player as they could lose their fleet, fail missions etc.

I can see this could be implemented in a couple of different ways:

1   Global for the whole game.
2   An option the player can switch on/off.
3   An even that just stops the player being killed in random non storyline incidents.
4   An event that allows the player to be killed in important storyline incidents.

I'm also open to other suggestions from those who understand the game mechanics better than I do.

**Comment by ghoulavenger** [comment]
I don't think this could be a global option. The game can be played entirely with a single ship, so if it was implemented globally there wouldn't really be a failure condition. Switching it on and off for the same reason feels like toggling god mode. I don't see people that are interested in an iron man mode particularly wanting this option either, since the point of an iron man mode is to increase difficulty not lower it. 

The reason I supported the other issue (#3077) for the sake of an iron man mode was entirely because it was a *random unavoidable death* versus something that could be handled by preparation or skillful play.

**Comment by Amazinite** [comment]
Essentially a duplicate of #906, except for the flagship instead of fighters.

**Comment by endlesssteve** [comment]
@Amazinite   The mechanics may be similar to 906 but the impact on the game is completely different. 906 was rejected because of it's impact on the game ( fighers lying all over the map ). The intent is to stop unavoidable instant death in the early game.

@ghoulavenger  God mode would be where you take no damage. This is get out alive with only your underpants mode. Saved by fate for the storyline missions.

The principle aim is also not to implement an Iron man mode, it's to improve the feel of the early game. With the switch option you would have the choice to switch it on or not. There would also still be the option of reloading if that's what you wanted.

You have personal preferences and like 307 better, that's fine.

**Comment by Amazinite** [comment]
>The intent is to stop unavoidable instant death in the early game.

Well this mechanic would stop *any* deaths in the game *at all*. If you never die then all combat in the game becomes trivial and you just have to wait for enough allies to warp into the system to take care of your enemies before asking for repairs.

**Comment by KiLEdEnNis** [comment]
you're basically asking for an ultimate "pussy" mode, and if you want to play the game in this way ya might as well edit your save for OP hull stats or uninstall since what's the point in this game

"code all this shit so no one can die ever so there's 0 challenge involved in the game, so we don't have to press "reload" once and try again"

not gonna happen, close this issue, there's not a single argument that'll make any of us change our minds, unless ya change your entire idea to be the same as 3077 which would make this a duplicate issue in which case ALSO close this issue

**Comment by endlesssteve** [comment]
Current game. 
bump into enemy several times more powerful than you. Get vaporized. reload. try again.

Proposal. ( If you don't like the above you get the choice to instead..)
bump into enemy several times more powerful than you. Get disabled. lose cargo. lose escorts. get rescued. keep playing.

I don't like the reload and try again option as the only way of progressing through the game and I've seen many comments from others users that don't either.

This is no duplicate of 3077. The requested function is completely different.

@KiLEdEnNis . Can't say I'm very happy with the tone of your comment. there is no need to call my idea shit or try to force me to close the issue before others have a chance to view it and give their opinion.
So far I have been very impressed with the openness and tolerance around Endless Sky. This is a nasty surprise.

**Comment by tehhowch** [comment]
This is actually more a duplicate of https://github.com/endless-sky/endless-sky/issues/362

Escape pods -> problem solved.

**Comment by endlesssteve** [comment]
@tehhowch . I have to disagree. It's not a duplicate, one minor part of 362 has vaguely the same point.

It's also not an iron man option. As mentioned above it's a pussy option.

I see a problem with the new player friendliness of the game. You need new players to keep this alive.

However with such a hostile response I don't see any point taking this any further.

**Comment by KiLEdEnNis** [comment]
as a last comment here
thing is this idea IS bad, the good parts of the idea are based on those duplicates stated

and as far as I know the escape pod idea will happen sometime, so I guess patience

**Comment by tehhowch** [comment]
Should #362 be fully addressed I readily doubt that escape pods would be limited to the hardcore/iron man mode. As you mention here, they greatly enhance the immersion in the game since the player does not automatically "have" to reload a save if things go south if they want to keep playing - the player has an outfit they can install on their ship that will give them a second chance.
In fact, of #362's desired additions, escape pods are the most likely to be done first due to the global frustration level reduction.

**Comment by endlesssteve** [comment]
The escape pod idea is cool but so much work new storyline content will always get priority. The idea is at least 2 years old. May be my idea was bad. Have you got a better one for dealing with the admitted frustration?

**Comment by sivael** [comment]
Immersion suffers when you reload.
This basically encourages "undock, wait for hai beetles to die, board, win" by undocking, dying, undocking, dying etc...
I would like the "escape pod" approach as that would mean you simply continue onwards. Would need to rebalance the cost of new ships vs players balance, maybe introduce some kind of insurance payout in case of ship destruction?

What I would not like is to force a player to one way of playing. Escape pods could make the whole game more streamlined and immersive, and they could as well make people quit. BUT. With the three last saves this rarely is an issue since if someone *wants* to respawn by loading, they can.

Thus, escape pod idea is great and would love to have it in game.
Problem is in places where you jump to and there's no friendly planets anywhere. Then You'd die.
Or You could get rescued by some race with jump drives once and they tell you you should not venture there if you aren't sure you'll return. Next time you die.
