### ISSUE TITLE
Suggestion: once one ship of a government scans you, others in the same system leave you alone

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#310]
Repost of thread I made on the Steam discussion boards;
As the game is ATM, the Republic will scan your ship nonstop. I like to carry nerve gas because it helps me take out heavy warships, and because I carry illegal goods, I also have to buy interference plating. At the moment, I have 100 units of interference plating which, in theory, allows me to barely get fined at all, but the plating only increases the probability that a scan will not detect my goods, which does not secure me invulnerability, regardless of the amount of plating I have. Case in point- if there are 10 or 20 republic ships, or 2 carriers in the sector I'm in, they'll constantly scan me, and every 2-3 sectors, I get fined 1 million, pay it off, and in another 2-3 sectors, get fined again.

EDIT: Now that I think about it, why would they scan me more than once every couple of minutes/jumps? If it takes 1 day to jump to another sector, and it takes 1 day to land and take off from a planet, why is the Republic scanning me every couple of seconds, which is probably one scan every couple of minutes in game time? Isn't there some sort of information net where scan records are kept? If they scan me twenty times in two minutes, and all twenty scans show no illegal cargo, and every single Republic ship can see this, I think it's a little contradictory for them to be scanning me over and over and over when the information and results of the scans are available to them just like that. 

EDIT 2: Removed references of the FW. Not sure why I said FW as well, as it's the Republic Navy that scans nonstop.

**Comment by Pointedstick** [comment]
100 units of Interference Plating should theoretically give you a 98% chance to avoid any given scan. If you're still regularly getting fined, then the frequency of scans should definitely be lowered.

**Comment by fcfort** [comment]
Also see related issue https://github.com/endless-sky/endless-sky/issues/261. 

Currently, I don't even bother with any nerve gas except if I'm in the Northern Pirates area way up at the top of the map. I'd say either lower the fine or decrease the frequency of scans, or perhaps make it so that a single faction will only scan you once per day or something along those lines.

To @Pointedstick's comment, yes that's true for a single scan, but if you jump into a system with a single carrier, they release all of their surveillance drones and they all scan you, the chance of at least one successful scan is ~11.4%. This type of scenario is pretty frequent and it makes the interference plating sound better/more effective than it really is.

**Comment by endless-sky** [comment]
Here's a compromise: 9b34b45. Governments will now only scan a ship once per day, so if one gunboat scans you, all the others will leave you alone. But, any ship with the "surveillance" personality will not leave you alone until it has personally scanned you. So, scans will be greatly reduced in most Republic systems but not in systems with a Navy surveillance fleet.

**Comment by endless-sky** [comment]
Included in release 0.8.10.
