### ISSUE TITLE
Best order for weapon attributes?

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#3108]
Currently weapon attributes are listed in the following order:
* ammo
* range
&nbsp;
* shield damage / second
* hull damage / second
* heat damage / second
* ion damage / second
* slowing damage / second
* disruption damage / second
* firing energy / second
* firing heat / second
* firing fuel / second
&nbsp;
* shots / second
* turret turn rate
* homing
* tracking
* optical tracking
* infrared tracking
* radar tracking
* piercing
&nbsp;
* shield damage / shot
* hull damage / shot
* heat damage / shot
* ion damage / shot
* slowing damage / shot
* disruption damage / shot
* firing energy / shot
* firing heat / shot
* firing fuel / shot
&nbsp;
* inaccuracy
* blast radius
* missile strength
* anti-missile

That's not necessarily the most logical order for the attributes, as mentioned in PR #1654. The goal was to put the most important attributes (range and damage / second) first, but the order of the other attributes is somewhat random.

**Comment by KiLEdEnNis** [comment]
in advance: not sure what to do with the /second and /shot, I put /shot below /second for now
and this could be "fine tuned" a bit, but I think this would be generally better

damage / second:
- shield damage / second
- hull damage / second
- ion damage / second
- heat damage / second
- disruption damage / second
- slowing damage / second
- anti-missile (only present if there is no other damage, unless a later update)

damage / shot
- shield damage / shot
- hull damage / shot
- heat damage / shot
- ion damage / shot
- slowing damage / shot
- disruption damage / shot
- firing energy / shot
- firing heat / shot
- firing fuel / shot

fire "requirement" / second:
- firing energy / second
- firing heat / second
- firing fuel / second

fire "requirement" / shot:
- firing energy / shot
- firing heat / shot
- firing fuel / shot

important non-damage stats:
- turret turn rate(?)
- range
- shots / second (not sure about this placement, it could be in the damage tab too)
- ammo (paired with shots / second on purpose)
- inaccuracy

secondary weapon stats:
- homing
- tracking
- optical tracking
- infrared tracking
- radar tracking
- piercing (not sure about this placement, it may be used on other weapons later)
- missile strength
- blast radius

**Comment by tehhowch** [comment]
My thought is that, no matter the order, per shot and per second values need to be in the same row, as this cuts down on the vertical requirements, which means the outfitter does not have to scroll as much. Forced scrolling is jarring and IMO, bad UX.

Building on that, since we know that anything that has per shot and per second has to be in one table, the rest have to be in another table (perhaps 2, depending on the vertical dimension relative to the per shot/second table).

Perhaps something like this:

Attribute | Value |   | Generic Operation |   |   | Activated |  |
-- | -- | -- | -- | -- | -- | -- | --
Cost | cost |   | Attribute | Value |   | Attribute | Per Second (/shot)
weapon space | int |   | Ammo | thing |   | Firing Energy | double (int)
outfit space | int |   | Range | distance |   | Firing Heat | double (int)
mass | int |   | Fire Rate | rate |   | Firing Fuel | double (int)
turret/gun | int |   | Inaccuracy | degrees |   | Shield D | double (int)
required crew | int |   | Turret Turn | degrees |   | Hull D | double (int)
  |   |   | Piercing | % |   | Heat D | double (int)
Description | d |   | Homing Level | int |   | Ion D | double (int)
Description | d |   | Tracking | int |   | Slow D | double (int)
Description | d |   | Infrared, Optical, Radar | % , % , % |   |   |   |  
Description | d |   | Blast Radius | distance |   |   |   |  
Description | d |   | Missile Strength | int |   |   |   |  
Description | d |   | Anti-Missile Strength | int |   |   |   |  

The markdown merge columns and size limits kinda failed me here, but I think the gist is there. In theory you would want to make the description squat enough to fit within the limits of whatever non-zero attributes you had (vs. the current stay-in-column format), but yet not so wide that it looks poor.

**Comment by KiLEdEnNis** [comment]
per shot and per second should indeed be together, I just wasn't sure what needs to happen to do so
the rest looks fine to me

**Comment by Amazinite** [comment]
If we are to keep the singular column set up (ignoring the descriptions column), then I would say that the attributes should probably go

General attributes:
* ammo
* range
* inaccuracy
* turret turn rate
* piercing

Missile-related attributes:
* blast radius
* missile strength
* homing
* tracking + tracking types
* anti-missile

Per-second attributes:
* shots / second
* [damage attribute] / second
* [fire requirement attribute] / second

Per-shot attributes:
* [attribute] / shot
* [fire requirement attribute] / shot

Adding a new column where /second and /shot attribute parallel each other would be nice, but I worry about that causing trouble on smaller screens. (Shrinking my window size slightly already pushes the current attributes column into the right-hand ship display.) A possible fix for this could be (pseudo-code):
```
if(enough window room) {
create second attributes column
} else {
put everything in a single column
}
```

**Comment by tehhowch** [comment]
At the minimum conceivably playable resolution (1024 x 768):
![image](https://user-images.githubusercontent.com/20871346/31454362-d197e7a6-ae7a-11e7-9169-90b9a2d733b5.png)

At the minimum reasonable resolution (the "Abort" button doesn't overlap the "Done" button in MissionPanel), 1117 x 768: 
![image](https://user-images.githubusercontent.com/20871346/31454413-fb44e43c-ae7a-11e7-9887-f0bbace2f602.png)

With some rethinking of some of the text (e.g. dropping `needed`) the middle column won't need to be so wide, and it can shrink enough to support the inline per-shot + per-second rows, even on tiny game sizes. There's also clearly room to shrink the description's column to achieve a similar effect, and still also achieve a net reduction in area needed for display.

**Comment by endless-sky** [comment]
Would the damage table make sense if it was abbreviated like this?

![damage table](https://user-images.githubusercontent.com/11450262/31568706-ecc30e50-b043-11e7-96d4-0d5c0fae4ce5.png)

(That's 250 pixels wide, the same column size used by the item info display right now.)

**Comment by tehhowch** [comment]
Is reasonable to anyone who understands tables :+1: 
But, it does require displaying only damage in that table (e.g. not energy consumption or heat production or fuel usage)

**Comment by endless-sky** [comment]
Yes, there would have to be a separate table for "firing cost" or something like that.

damage | per second | per shot
---- | ---- | ----
shields | ### | ###
hull | ### | ###
fuel | ### | ###
heat | ### | ###
ion | ### | ###
slowing | ### | ###
disruption | ### | ###

firing | per second | per shot
---- | ---- | ----
energy used | ### | ###
fuel used | ### | ###
heat generated | ### | ###
ammunition | &nbsp; | &lt;name&gt;

There would still be lots of single attributes on top of that, of course.

**Comment by MessyMix** [comment]
I know it may seem redundant, but IMO it is better than having 2 separate tables for it: just add `dmg` after the damage types, and then condense into 1 table.

**Comment by tehhowch** [comment]
Use of two tables can allow them to flexibly position themselves based on available space - e.g. with a lot of available space, they should probably fill horizontally, while if there is not a lot of horizontal space, they should align vertically.
It's possible that updating the table layout will coincide with changes to the outfitter layout (e.g. #500 )

**Comment by Nescio0** [comment]
Instead of inserting an additional column, how about:
* projectile velocity / range
* inaccuracy
* shots per second
* shield damage per shot / second
* hull damage per shot / second
* ion damage per shot / second
* heat damage per shot / second
* slowing damage per shot / second
* disruption damage per shot / second
* anti-missile per shot / second
* firing energy per shot / second
* firing heat per shot / second
* firing fuel per shot / second
* *all other stats*

**Comment by Tadrix** [comment]
It'd be good if rate of fire would be displayed somewhere near the "requirements", and unified tables would have "per shot" as a first column, and "per second" as a second column, not the other way round as it's proposed now.
