### ISSUE TITLE
Question: fleeing ships sometimes coming back is intended behavior?

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3111]
When an NPC flees to another system, it sometimes comes back to the system almost without recovering. Is this behavior intended? They are "easy pickings" in that state and it makes capturing ships significantly easier.

How I noticed:
I was trying a playthrough where I flew a single ship and mostly followed missions, which ended up with me in a Splinter just before the Pug invasion in the "checkmate" storyline.
The Pug always dominated me, so I decided to gauge how stronger my ship had to be by retrying after plundering some alien tech (from the Korath, an then from the Unfettered Hai).
As I waited in Sheratan for a disabled Korath Raider, I noticed that sometimes new arrivals didn't launch Korath Chasers. By not switching targets until they disappeared on their own, I found that they were actually ships that had fled to a different system and come back, easily being disabled or destroyed. I then started noticing the same behavior in other npcs (pirates, merchants).

**Comment by tehhowch** [comment]
Regularly spawned ships make decisions randomly, so the likelihood their next jump takes them back to your system is proportional to the number of options they have available.
If they are mission NPCs, if they are not `staying` or `uninterested` this is expected behavior - they are told to route to your system (at least until #2990 .. :smile: ) and so even if they choose to flee from it (e.g. damaged enough and not also `heroic`, they are required to return to it.

There was a request recently to have ships not decide to land on the planet they just took off from, and I would classify this in the same category of enhancements to travel.
Adding a Danger(const Ship &) method to the AI class and calling that when the ship's target system is the player's would be one way to reduce the likelihood of ships that flee from the player/combat, returning to the player/combat.

**Comment by flaviojs** [comment]
I see, it's not intended but probably a consequence of trying to keep behaviors simple and with the same code for all ships.

-----

Instead of adding to the hard-to-understand AI code, I believe it would be better to bring some order to it.
Something like an ordered list of objectives/behaviors, where each one would:
- decide if it should delegate control to the next one in the list;
- control the ship according to their specific AI logic;
- contain any needed "memory" variables;
- load from and save to txt files their specific node.

I'm not sure if it should replace the current personalities or work with them, but conceptually it would make controlling behavior much simpler.
It can be equivalent to one of the current personalities.
It can be a mini-mission (ex: scan ships, patrol/visit systems, haul cargo to planet, plunder cargo).
It can be just adding another objetive/behavior when certain conditions are met (ex: stayalive adding a flee or land with the highest priority).
I can envision lots of possibilities...
