### ISSUE TITLE
Two minor issues

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3115]
# Energy flight check warning sometimes appearing in shipyard
Move the mouse around in the shipyard. Occasionally, this happens:
![whyflightcheckwhy](https://user-images.githubusercontent.com/16506683/31476906-f2036cb6-aed6-11e7-9062-a9ab4828e9aa.png)
It seems to only happen at most, what, once every game start? And it disappears as soon as the cursor moves away (excluding scrolling actions).
Happens with or without ships in your fleet.
# Pressing number key in the outfitter while a ship with outfits is selected
So I have a punisher.
I select the dual sunbeam turrets installed, and press the `1` key.
This deselects the punisher (for whatever reason, I don't know). But its outfits' names are still highlighted:
![whyoutfitterwhy1](https://user-images.githubusercontent.com/16506683/31477050-d09a2d48-aed7-11e7-937b-81a7358b285e.png)
![whyoutfitterwhy2](https://user-images.githubusercontent.com/16506683/31477052-d2c50aa2-aed7-11e7-8901-1098be830455.png)
(No Pug anti-missiles are installed, I just manually selected them.)

**Comment by tehhowch** [comment]
number keys are selecting those ships that have that command grouping... probably some issue with them not being available or defined anymore.
Haven't spent time in the shipyard to see that error yet.

**Comment by tehhowch** [comment]
2nd one is actually not a minor issue:
It triggers ShopPanel::KeyDown: line 553
https://github.com/endless-sky/endless-sky/blob/4c2396d209a636c11eb182abc311b60d44e809f4/source/ShopPanel.cpp#L532-L554
which calls PlayerInfo::GetGroup()
https://github.com/endless-sky/endless-sky/blob/4c2396d209a636c11eb182abc311b60d44e809f4/source/PlayerInfo.cpp#L2019-L2031

Thus we see that 0-9 would select these ships regardless of their system and status.
Fixed in #3119

**Comment by tehhowch** [comment]
Regarding the first issue:
https://github.com/endless-sky/endless-sky/blob/4c2396d209a636c11eb182abc311b60d44e809f4/source/ShopPanel.cpp#L687-L697

So i'm really not sure what's happening for you. Is it the same ship, every time?

**Comment by Bladewood** [comment]
It is not.

**Comment by endless-sky** [comment]
The first issues should be fixed by 5d6d579, and the second by #3119.
