### ISSUE TITLE
Mission `to fail` is evaluated twice when being offered

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3131]
A new mission's `to fail` criteria is evaluated twice when the player lands
1st, in Mission::CanOffer:
2nd, in PlayerInfo::CreateMissions, after the mission has successfully offered

This means that if the `to fail` criteria contain `"random"` values, these checks must pass twice in order for the mission to successfully appear as an active mission.
The second check was added in https://github.com/endless-sky/endless-sky/commit/79e09a589918deac71e63b9d820df849cf4223f8#diff-bb0adb43cf141cd2202dd3555492800aR963
At that time, Mission::CanOffer did not have a failure check (or even a `to fail` node!).
Later, when the `to fail` condition was added, the HasFailed check was kept in PlayerInfo::CreateMissions: 9bc372927cb274544620b5cd0ca83331587df1e8

I think this 2nd check should be removed, otherwise:
```
to offer
    random > -1
to fail
    random < 50
```
has only an 25% chance of appearing instead of the presumed 50%, as it has to pass the check once to offer, and again to stay offered.

**Comment by tehhowch** [comment]
Should be resolved by #3132

**Comment by endless-sky** [comment]
The "to fail" condition is checked every time you land on a planet. So, if the mission has a random "to fail" condition, it is likely to fail on some random planet before being completed. Conceivably there are uses for that, but it'd be much cleaner to just create a separate mission that occasionally gets "offered" while the first mission is active, and causes it to fail. In other words, using "random" in a "to fail" condition is a mistake in the first place.

Note that the second HasFailed() check is necessary, because marking a mission as failed is how Instantiate() signals the fact that it was unable to find a destination, etc. that satisfied the filters.

**Comment by tehhowch** [comment]
This is inside of PlayerInfo::CreateMissions - this is separate from the check for failed missions when a player lands.
The check you mention is here, and the check I mention is inside the function called at the end of this block:
https://github.com/endless-sky/endless-sky/blob/048ac19e260b18179101f6a36ae285a7fb8a3c7b/source/PlayerInfo.cpp#L1006-L1031

**Comment by tehhowch** [comment]
Ah, misread your second paragraph.
