### ISSUE TITLE
Performance in fights with minelayer ships.

### ISSUE THREAD

**Issue by flaviojs** [endless-sky/endless-sky#3146]
While exploring outer edge systems and their planets with 2 Mules, I jumped (with Jump Drive) Sepetrosk -> Sayaiban -> Faronektu. As I waited for fuel to refill in Faronektu I noticed the battles were producing a constant stream of capturable ships. I decided to remain there capturing, aiming to get at least a ship of each kind. ^^

As I spent time there I noticed the game speed had big fluctuations, I even saw the cpu stat go over 1000%. After some time I narrowed down the cause to the mines that were being deployed by Kor Mereti ships. To confirm this I reloaded the game in Sepetrok to get a mine field deployed and see the difference.

A Model 64 and 2 other ships started chasing me. The Model 64 deployed a mine field, which caused the cpu stat to jump to 42%. After all the mines exploded the cpu stat went down to 15% (they were still chasing me).

**I know my cpu is weak but a jump from 42% to 15% over a single mine field is too much.**
Clearly something should be improved so I recompiled with ```scons mode=profile```, fired up the game with callgrind, reduced the size of the game window, and left the game running in Faronektu for a few hours (with caps lock on).

Callgrind made everything around 30 times slower, the biggest cpu stat I saw was 40099% (~1300% without callgrind?). It looked like a small battle followed by a big battle from the times I peaked into the window.

Within the +4h of run time ```Engine::CalculateStep()``` was called 13783 times. After inspecting with kcachegrind, these appear to be the critical calls:

```
mcount  [49.81% total, libc]
0x000000000004bf10  [19.46% total, libopenal1]
75.65%  Engine::ThreadEntryPoint()
  75.65%  Engine::CalculateStep()
     7.58%  [other code?]
     5.93%  AI::Step(PlayerInfo const&)
    62.14%  AsteroidField::Collide(Projectile const&, int, double, Point*)
       0.53%  [other code?]
       3.31%  Minable::Collide(Projectile const&, int)
      58.30%  AsteroidField::Asteroid::Collide(Projectile const&, int) const
        15.32%  [other code?]
         5.48%  drem  [libm]
         2.96%  Point::operator=(Point const&)  [3.96% total]
         3.01%  operator*(double, Point const &)  [3.06% total]
         5.00%  Point::operator-(Point const&) const  [6.69% total]
         5.12%  Body::Velocity() const  [5.49% total]
        10.75%  Body::GetMask(int) const  [11.86% total]
        10.66%  Mask::Collide(Point, Point, Angle) const [14.12% total]
```

I'm running Linux Mint 18 Sarah (64-bit) and my cpu is an Intel Core 2 Duo P7550  @ 2.26GHz, limited to 1.6GHz to prevent the fan from going into hyperdrive.
This was with master at commit 048ac19e260b18179101f6a36ae285a7fb8a3c7b.

**Comment by flaviojs** [comment]
To me this just looks like a lot of projectiles being called, which is normal since they are short lived and fired often... How do I do time-based profiling in linux?

**Comment by tehhowch** [comment]
The only profiling I've done is with `gprof` and the `scons mode=profile` build. The gmon.out file has time information in it.

**Comment by Wrzlprnft** [comment]
are those the checks from mineable asteroids testing collision with the mines, which then bloats the collision code?

**Comment by tehhowch** [comment]
I ran to Faronektu and idled for a bit, engaging with the local Mereti for a bit, running master:
I then ran the gmon.out file through gprof2dot and trimmed to just the Engine::ThreadEntryPoint() tree, with default node/edge trimming on total % time (.5 node, .1 edge):
![faronektu](https://user-images.githubusercontent.com/20871346/31864208-271a0c5c-b71f-11e7-8807-bb8fddc4e9f0.png)
(format is "function, total% (self%), calls" for nodes, "total%, calls" for edges)

And the converted gmon.out text: 
[Faronektu.txt](https://github.com/endless-sky/endless-sky/files/1405123/Faronektu.txt)
As expected from the dot graph, the components of AsteroidField::Asteroid::Collide are right up there for total time used.

@Wrzlprnft this is mostly because of the high asteroid density. There's nothing particularly unique about the mines except they have a long life and very low velocity - they make this especially noticeable because each one generates multiple additional projectiles.

**Comment by flaviojs** [comment]
Wait... are mines long lived projectiles?

**Comment by Amazinite** [comment]
Yes. They're really just missiles that slow to a stop after firing.

**Comment by tehhowch** [comment]
Everything that is fired is a projectile, even lasers and blaster shots.

**Comment by flaviojs** [comment]
Then that explains it, during big battles the map had tons of them and ```AsteroidField::Collide``` tests each projectile against each asteroid during each step.

Adding some kind of spatial map to asteroids should improve this, I'll give it a try. :)

**Comment by flaviojs** [comment]
After introducing a spatial map for asteroids (in a quick&dirty way) the cpu stat never reached 200%, even in the biggest battle I saw in Faronektu with 4 independent clusters fighting at the same time. Very good!

I'll test a few alternatives and then make a PR.

**Comment by Amazinite** [comment]
Sounds awesome; I get massive slowdown for even small battles in asteroid-dense systems as well, so anything to reduce that would be great.

**Comment by flaviojs** [comment]
With 14d70baf86932d887de41e3b1aedebd3c6e24633:

* I'm getting at most 260% in big battles in Faronektu
* a single minefield in Sepetrosk is indistinguishable from the usual cpu stat fluctuations, so I guess it's somewhere from 0% to 2%

I consider this issue resolved. :)

**Comment by tehhowch** [comment]
Repeated the above profiling:
I'd say there's a definite improvement :tada: :confetti_ball: 
![9c1f20ade3](https://user-images.githubusercontent.com/20871346/32000988-0564f46e-b95e-11e7-8700-a4d8e33a727c.png)

**Comment by Joeppie** [comment]
Hello, I was just curious and  ran a performance analysis on my computer using valgrind , using
`valgrind --tool=callgrind ./endless-sky ` as run from the endless-sky repo (after cloning); kcachegrind can then visualize diagram results and order functions by cost.

Without raising a seperate issue immediately,  I just wanted to bring to your attention that with a decently powerful PC, you can instrument it using Valgrind; which does not necessitate adding instrumentation (possibly skewing results) of any kind to the release code (unlike gprof) This means that at 50x reduced CPU speed (and single thread), you can see where time is being consumed. Stunningly, the game still runs well enough to play on my Linux Mint, i7, Quadro laptop.

While I do not see major performance problems, one thing that stands out is that Dictionary::Get() accounts for 1.9% of all execution time, and is called directly and indirectly from things such as Ship::Move() which I presume execute every frame. 

This is a 3x difference from the above diagram I see pasted, so in the future it may be worthwhile to consider using Valgrind to profile, or compare profiling results with release+valgrind versus gprof+instrumented binary.


I presume that it would be possible to eliminate string-based get lookups for every frame. Would you like me to create a seperate issue?

Perhaps if I find time in the Christmas Holiday, I could take a look and see if it is feasible to reduce the number of lookups by caching them. :smiley:

**Comment by Joeppie** [comment]
@tehhowch Thanks, I was looking into Endless Sky yesterday, and managed to compile it with Cmake under Linux, so that I can modify the code and monitor what happens.

I see that a lot of attributes get read before they ever get initialized.

In the end I gave up on easily 'caching' or rather- building references (i.e. pointers but with nicer syntax) to the underlying values.

For example instead of `double hull = outfit::Get("hull")` in ship within the DoGeneration() method, it might be possible to add a double& hull = outfit::["hull"] and effectively turn this often-queried attribute into a pointer to the actual value. 

But I ran into two distinct problems there:

1. It should be a const double& or (double* const ), to keep the read-only semantics.
2. The value of a Dictionary gets initialized with the [] operator.

So, without precise knowledge of what I am doing, I could not safely alter that code.

While only ~2-3% of the vanilla execution time is spent doing Dictionary::Get executions, these occur when generating frames; this therefore puts a cap on the maximum frame-rate that could be achieved.


As I said, overall I am quite impressed with the lack of performance bottlenecks, and the fact you dared write your own Dictionary :bowing_man: !

**Comment by endless-sky** [comment]
For a long time the game was just using a `map<string, double>` for the dictionary lookups. The custom Dictionary class makes those lookups several times faster. At this point, I think we've already got a good balance between flexibility and efficiency for the ship attributes - if it's only taking a few percent of the execution time, there's not going to be much payoff from further optimization.
