### ISSUE TITLE
Crew payout

### ISSUE THREAD

**Issue by CMSgtCodeFox** [endless-sky/endless-sky#3159]
Can you make it so that the crew is payed every month instead of everyday

**Comment by Amazinite** [comment]
Why? You'd still be paying the same amount.

**Comment by Hadron1776** [comment]
I'd guess the idea is you could run low on cash for a time, without going deeply in debt to your crew...

**Comment by Amazinite** [comment]
Whether you pay 100 credits per day or 3,000 credits after 30 days, the amount of debt you accrue after the end of the month would be the same. The only difference is that one is a tiny bit of credits daily while the other is a huge chunk of credits once every so often.

**Comment by tehhowch** [comment]
Daily is much simpler. A monthly or weekly payout means that the game has to pay salaries to parked ships that were not parked when you landed, every day, plus to any crew of ships that you might have sold when you landed. To do that requires implementing checks to compare the ships you're using on takeoff with those you were using on landing.

If those checks and pay-on-dismissal aren't done, people are 100% going to be confused why they are paying 60k in crew salaries when they've been solo-piloting a Sparrow for 28 of the last 31 days.

So, sure, we could implement a switchable pay scale (preferences->crew payroll length = {1, 7, 14, 28}, but doing so means we have to add a bunch of extra methods. I'm not going to write them, but someone else certainly could. If they're done well, maybe there's a chance their PR gets added. But, I really doubt it, because paying daily means no extra tracking needs to be done.

**Comment by ghoulavenger** [comment]
You actually don't need all those checks to make it work. You just need to track it on a daily basis even if it isn't being paid. Think of it like running a debt. Your debt increases every day just as if you were paying them now with a paid event, probably on the first or fifteenth of the month.

The question is why it is preferable to track your debt like a mortgage to just paying daily? I don't see the merit in it. You pay for your mortgage everyday, so what makes paying for crew special?

**Comment by Wrzlprnft** [comment]
The only thing that comes to my mind is that it would act like a free mortgage. you can save up 29 days, buy a better ship next day, then not being able to pay. Different Outcome? not really, except you were making konstant - with the salaries. Such a change probably would force rethinking of prices in the game, which i'd prefer to avoid

**Comment by tehhowch** [comment]
Good thing is back pay is tracked so if you miss a crew payment you'll pay it back asap
