### ISSUE TITLE
Republic + Oathkeeper escorts in Escape The Syndicate mission are not hostile to the Syndicate

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3171]
[Zeta Reticuli.txt](https://github.com/endless-sky/endless-sky/files/1424666/Zeta.Reticuli.txt)

**Comment by tehhowch** [comment]
Indeed, they are only hostile to the `Syndicate (Extremist)` government - they have never been hostile to the Syndicate, because the Syndicate has not declared war on the Republic or the Navy. The very next mission has the Syndicate amassing a fleet in Sol, but not attacking Sol.

A fix would be to label the hostile npcs as part of the extremist faction, or make the navy & republic escorts use pseudo governments (e.g. `" Navy (Oathkeeper) "`) which do have hostility.
The mission in question: https://github.com/endless-sky/endless-sky/blob/9c1f20ade3dd8e4e3151fe8021def5a0ed8d11ae/data/free%20worlds%20reconciliation.txt#L684

**Comment by endless-sky** [comment]
This is addressed in 82057b7 by making the Syndicate hostile to your escorts for just the duration of that mission. (I also added a "Deep Security" government so I wouldn't have to make the Syndicate hostile to the Republic.)
