### ISSUE TITLE
Suggestion: When taking tribute, planet hails you once it wishes to surrender

### ISSUE THREAD

**Issue by airtroop392** [endless-sky/endless-sky#319]
Instead of the current method, which, in the heavily defended Republic and Free Worlds sectors, entails of hailing the planet every few seconds due to the fact that the player has no idea how many ships are left that actually belong to the planet's defense fleet (and therefore must be eliminated in order for the planet to surrender), the planet would notify the player's ship, much in the same way that the game notifies the player to pick up their reward when he/she destroys a pirate ship which has a bounty on it.

**Comment by Oeleo** [comment]
I agree, furthermore that's a little weird that they ask you a bribe again while when you ask them a tribute a second time they will surrender.

**Comment by GoldenDalek** [comment]
Well, a suggestion for the implementation, that wouldn't change that much, would be to rewrite the tribute system as a mission, so when you get that tribute you get a non-visible mission that is failed automatically if you leave the system or quit the game. That way, it would be easy to implement the notification rather than just checking every frame.

**Comment by endless-sky** [comment]
This would significantly increase the complexity of the tribute code, because the status of the tribute fleet would need to be checked every time a ship is destroyed rather than only when you hail the planet. That doesn't seem worth it just for convenience for a player engaged in what is, after all, not supposed to be an easy or common task.
