### ISSUE TITLE
Small list of fixes for Jump Drives, and Outfit Spaces

### ISSUE THREAD

**Issue by manitscold123** [endless-sky/endless-sky#3199]
I have about 215 hours on this game so I feel like I have the right to give some suggestions or bugs.

First, the jump drive: the jump drive (hinted at an antimatter core lol) shouldn't use the same amount of time to jump as the hyperdrive yes? Plus the animation for the jump drive makes it look like it takes no time at all. I haven't looked in the actual XCode folder yet, but I assume that the time ticks forward exactly by one day every time the map changes, so all that's required is to add an if else (or whatever the C++ version of that is). This isn't just for realism, but also b/c it'll be harder to catch Korath Raiders when they're running away.

Second, I've found that if you add like, 5 scram drives on one ship, the speed at which you can jump increases every time. I'm not sure if this is intentional, or if it's a bug. The good thing is that it doesn't consume 5x the fuel, so I'm not sure if it's intentional or not. But still, stacking scram drives is pretty much OP, as it ensure that no one will ever be able to catch up to you.

Third, (and this is just a question) I've always wondered where Archon ships go when they run away. Perhaps you need to make the Archon ships NOT run away, b/c y'know... they're ARCHON. (20 Pug Arfectas do the trick) Archon ships are pretty OP, but maybe an increase in Hull or just an upgrade to their AI will help. (Or make the antimatter cannons do more dps)

Fourth, I've found that it's possible to have -spaces for weapon slots, so perhaps an extra attempted launch failure should be added, perhaps like 

> You take off, but remember that the extra weapons you bought are still in a pile on the ground. Maybe you should probably do something about them before you leave and someone can take them

Fifth, Regarding the combat rating and capturing planets, it may be better if combat rating is calculated a bit differently, such as increasing the rating based on your net worth.

Sixth (added afterwards), I noticed that there is a mission in Remnant Space that involves killing a Korath World Ship Class B, which, may I point out does not have a Jump Drive, so HOW DID IT EVEN GET THERE IN THE FIRST PLACE LOL. Perhaps this needs to be fixed because I was really really confused.

P.S. I'm too lazy to create different issues for each bug/suggestion so live with it. ;) 
Also, I've checked the [long] list of issues, and I don't believe that any of these are duplicates, but if they are, don't be a prick and make a jape of it, just tell me and I'll delete it. K?

**Comment by Amazinite** [comment]
>First

I'm not sure what you're talking about here.

>Second

No one may be able to catch you, but you're wasting 150 outfit space just to do that. It's a trade off situation, as with all things.

>Third

Archons already have the staying personality so they never leave their system. If you're attacking the one in the Ember Waste, that guy can cloak.

>Fourth

Is this possible in vanilla though?

>Fifth

Why?

**Comment by ghoulavenger** [comment]
>> First

> I'm not sure what you're talking about here.

The couple things I picked apart from hist post are that jump drives probably take longer than scram drives to perform a hyperjump, which has to do with scrams not requiring slowing down, while all other hyperdrives do -- also the fact that each hyperjump transition takes a full day regardless of *how* you jump. To the former, try using reverse thrusters, they speed up jump drives significantly. To the latter, you can save plenty of days using jump drives if you're skipping systems entirely (which is most useful in human space). 

Oddly enough, just as well, transitions only occur when YOU jump and not when NPCs or escorts jump. So it's quite possible to amass your entire fleet in one spot just by launching and then waiting for all of your escorts to arrive etc, assuming they can get to where you are without getting stranded.

**Comment by jafdy** [comment]
>Fifth

You could so you think combat rating should be affected by the amount of credits in the bank and not by the number (and power) of the ships you beat.

>Fourth

Strange things can happen when you start editing saves or game files.

>Second

If you want to jump quicker then you can waste as much space as you like on Scram Drive. They are not broken because most people would laugh at you for putting 5 of one kind of drive in a ship.

>First

No. And are you saying that time should not advance when you use a jump drive? (You can check the date in the upper right corner.)

**Comment by manitscold123** [comment]
I'm going to pretend I didn't see that rude cyanide and happiness guy. Like, haven't you heard or manners?

> First

It's not that scram drives can jump immediately, but more importantly is the fact that Jump Drives tick the days forward by one. And let me give you an example.

Let's say that it takes me 10 jumps via Jump Drive (10 days) to get from Sol to Ruticulus, but it takes me 20 jumps (20 days) to get there via Hyperdrive or Scram Drive. If I install a Jump Drive, I'll get there in 10 jumps, and the rest of my fleet will get there as well, even though it takes twice as much time.

> Second

It's not just for scram drive, it's for jump drive and hyperdrive as well

> Fifth

Not the credits in the bank, but the total price of the ships in your fleet or the strength of your ship + it's outfits.

I find that having to increase the combat rating via killing pirates is rather bothersome. Perhaps the Combat Rating should be based on the rating of the ship currently being piloted.

**Comment by jafdy** [comment]
>First

Gameplay over realism. If that didn't happen we would get some very upset players.

>Second

We know, we still don't think you have a point.

>Fifth

That's not what you said, but never mind.
How are you calculating "combat rating of a ship"? Just on cost or something more complex?

**Comment by manitscold123** [comment]
In the description of the Pug Arfecta it says "Tier 3 Warship". This game has a pretty well community defined tier system, so you can base it on that.

**Comment by ghoulavenger** [comment]
>Let's say that it takes me 10 jumps via Jump Drive (10 days) to get from Sol to Ruticulus, but it takes me 20 jumps (20 days) to get there via Hyperdrive or Scram Drive. If I install a Jump Drive, I'll get there in 10 jumps, and the rest of my fleet will get there as well, even though it takes twice as much time. 

Day transitions only happen when YOU jump, not when your fleet jumps. So if you have jump drives and your fleet has to catch up to you, it still takes the same ten jumps it would have taken you to get to your destination, so only ten days. You just have to wait for your fleet to catch up. This is indeed, in my opinion a bug, but not one with a very easy fix -- the only *good* solution here is to have it so that you always do *fleet* jumping, but then you'd need your entire fleet to have jump drives, or be forced to path through systems all of your ships can travel through. Having jump drives take no time however, doesn't seem to fix this issue but make it worse (since then the only game day transitions would be on launching if your flagship had a jump drive). I don't think it is much of an issue though since game days aren't that valuable anyway. They only gate when the free worlds storyline opens up (which happens around 6 months in I think), and in determining when rush jobs are due (and they rush jobs always give you enough time to make it to your target destination without jump drives assuming you have enough fuel to make a 3 jump leg or so).

>It's not just for scram drive, it's for jump drive and hyperdrive as well

The reason why people aren't caring so much, is that stacking drives to speed up the jump transition wastes valuable outfit space that might otherwise be put to use in making your ships well guarded (120 extra outfit space on scram drives could house an extra large systems core and have space left over), or more capable of hauling cargo and passengers (bunk rooms and cargo expansions). If quick escapes are your priority, people are not only okay with that but encouraging you to follow it.

> In the description of the Pug Arfecta it says "Tier 3 Warship". This game has a pretty well community defined tier system, so you can base it on that.

Not really. To really consider your threat assessment like that you'd need something more direct. Such as comparing your fleet to their defense fleet. If you're laughable compared to their defense fleet they might ignore you, comparable they might engage you etc. I don't like the system in its entirety since I think all threats should be taken seriously and the game should just kill off the plebs that don't know what they're doing. Not like the game has perma death so they can just reload and laugh it off.

The only reason why combat rating makes any semblence of sense is because of your perceived notoriety. People *know* who you are (Nobody would surrender their ship to the Dread Pirate Wesley, but they will to the Dread Pirate Roberts -- Princess Bride ref). In this sense though it might be better if there was a notoriety attribute being tracked instead, or a fame attribute. But seeing as there isn't really a strong need for either one, combat rating will do. 

If I were to redefine the system I'd probably go with requiring a bad reputation, not just giving you one for doing it. Basically, you need to start attacking them first so they're hostile, makes your threats seem more plausible. But as I understand it, the entire feature is a throwback and nobody seems to want to do anything with it -- which is why it only works in human space.

**Comment by kikotheexile** [comment]
Its stated that something must be wrong with its jump drive or that it broke. So now its just frantically trying to get out of remnant space but cant.

These type of discussions are best held on the discord or steam forums. We aren't trying to be mean, we are just generally super blunt on the github because this is not the place for rants and threads, but rather proposals as to specifically address issues. 
https://discord.gg/9Qsfv2x

**Comment by endless-sky** [comment]
None of these things are actual bugs, and "issues" that don't focus on one particular suggested change or fix aren't helpful. (This is a bug tracker, not a forum.)
