### ISSUE TITLE
Test: gonna idle all night

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#320]
Gonna go to an empty system with my best fleet, upgraded with full quarg outfits, and idle all night and see if my combat rating goes up very much. Starting combat rating: 11

**Comment by fcfort** [comment]
If you look to see what the titles correspond to, the "Rank" is the natural logarithm of the minimum crew required on each ship that you have at least disabled (see https://github.com/endless-sky/endless-sky/blob/master/source/InfoPanel.cpp#L380). So here is a quick table showing the rank, min. crew to kill and also handily converted into the number of Korath World Ships you would have to destroy to get that rank. I chose Korath World Ships since they have a very high min. req. crew (543).

Title | Rank | Min. crew killed | # of Korath World Ships destroyed
---- | ------ | -------- | ---------
"harmless" | 0 | 1.00 | 0.001841620626
"mostly harmless" | 1 | 2.72 | 0.005006043883
"not entirely helpless" | 2 | 7.39 | 0.01360783812
"borderline competent" | 3 | 20.09 | 0.03698993909
"almost dangerous" | 4 | 54.60 | 0.1005490793
"moderately intimidating" | 5 | 148.41 | 0.273320735
"not to be trifled with" | 6 | 403.43 | 0.7429627873
"seasoned fighter" | 7 | 1,096.63 | 2.019582244
"respected foe" | 8 | 2,980.96 | 5.489793715
"force to be reckoned with" | 9 | 8,103.08 | 14.9228065
"fearsome scrapper" | 10 | 22,026.47 | 40.56439373
"formidable adversary" | 11 | 59,874.14 | 110.2654544
"dread warrior" | 12 | 162,754.79 | 299.7325809
"veteran battle-lord" | 13 | 442,413.39 | 814.757628
"terror of the galaxy" | 14 | 1,202,604.28 | 2214.740855

**Comment by thenerdfreak** [comment]
I went from 11 to 12, however This leads me to a new suggestion: Battering down. When i awoke this morning my flagship was literally a 30 minute ride at full speed with afterburners from where I was to the cluster of uninhabited planets. apparently i had gotten hit by a single pirate missile and it had thrown me, very slowly, miles away from where I started. Maybe You would take more damage from being battered down, but it would lock you into the space you're in

**Comment by gchapyzh** [comment]
@thenerdfreak Ah, yes. So that particular feature, the do-your-best-to-move-at-all feature, is definitely needed to some degree.

**Comment by thenerdfreak** [comment]
zero, they were all outfitted with quarg stuff :p pirates and the occasional cruiser/frigate (the republic hates me since i took a syndicated space station full of them) were no match for my might. I have literally destroyed Sol's defense fleet three times just for the fun of it

**Comment by endless-sky** [comment]
This conversation should probably be moved to the [forum](https://groups.google.com/forum/#!forum/endless-sky); I'm trying to keep the issues list small by limiting it to bug reports and feature requests, rather than using it as a general discussion board.
