### ISSUE TITLE
Phasing weapons blocked by disabled enemy ships if a ship is not selected

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#3232]
![whygridfirewhy](https://user-images.githubusercontent.com/16506683/32974592-6ec8233c-cbcd-11e7-85a9-2814fb7c25a2.png)

**Comment by tehhowch** [comment]
And? Phasing weapons with targets only hit that target. Phasing weapons with no target hit the first target in their path.

**Comment by Bladewood** [comment]
I had assumed that phasing weapons were supposed to auto-target active ships.

They pass through asteroids, so why not disabled ships?

**Comment by tehhowch** [comment]
They pass through asteroids while you have a target ship, same as they pass through non-targeted ships.
When you have no target ship, they can hit ships. They just also happen to pass through asteroids when you have no target ship too:
Compare
https://github.com/endless-sky/endless-sky/blob/c74ca06dd41f3d3ca6305f856ce63985db028fe9/source/Engine.cpp#L1532-L1535
with
https://github.com/endless-sky/endless-sky/blob/c74ca06dd41f3d3ca6305f856ce63985db028fe9/source/Engine.cpp#L1572-L1578

It's possible that the bottom phasing check should have a `&& projectile.Target()` check as well.

**Comment by Bladewood** [comment]
If they're not supposed to ignore asteroids without targets, either, then changing that is also a solution, I guess.

**Comment by tehhowch** [comment]
I'm gonna let MZ control the behavior of weapon keywords, so I won't consider the absolute ignorance of asteroids by phasing weapons to be a bug until he does. He did write `can` in the leading comment, but at the same time he also says `for all other projectiles`, so the intent is a tad ambiguous.

**Comment by endless-sky** [comment]
The current behavior is intended. If the player is dumb-firing weapons, there's no way for the game to know whether, in this particular case, the player is intentionally firing at a disabled ship to destroy it versus firing at another ship and the disabled one got in their way. So, dumb-firing phasing projectiles will hit any ship that is hostile to you, the same as any other projectile.

On the other hand, when dumb-firing a phasing weapon and an asteroid is in the way the question is whether the player is trying to mine or trying to shoot an enemy ship. Again, the game can't figure out your intentions, so it does the thing that is more likely to be useful: ignore asteroids and only hit ships. (The only downside of this is that phasing weapons can't be used to mine, but if you have an Arfecta you probably have better ways to earn money.)

**Comment by Bladewood** [comment]
Oops. I should have mentioned that the neutralizer in the screenshot was in the process of exploding, not just disabled.

But I did mention it was auto-targeting and firing.

**Comment by tehhowch** [comment]
Destroyed ships meet the criteria for `disabled` 😋

**Comment by accursedCursive** [comment]
I'm going to make an odd suggestion: Phasing weapons should pass through _everything_.
They should only be usable by setting a trigger radius.
This would make the "phasing" tag more versatile.

**Comment by Amazinite** [comment]
>They should only be usable by setting a trigger radius.
This would make the "phasing" tag more versatile.

>only be usable by
>more versatile

Does not compute

**Comment by accursedCursive** [comment]
It's more versatile because you can use a trigger radius to keep current behaviour of phasing weapons, but you can also not set a trigger radius at all if you're making a weapon with a projectile that is intended to pass through even your target.

**Comment by tehhowch** [comment]
As implemented in the base game, `phasing` signifies a weapon so advanced it can only hit what it is aiming at. You are trying to redefine it to mean "never hits anything" and I don't think your effort will be successful.

**Comment by accursedCursive** [comment]
For a game that puts an emphasis on modding, giving tags very specific and poorly documented behaviours is a bad idea.
Even if nothing in the vanilla game would need the phasing tag to pass through absolutely everything, a mod might need it.
I've got one mod weapon that would work better with a more generalised phasing tag, and one that necessitates it.

The vanilla game can work with almost no difference by changing the phasing tag to never be able to hit anything without a trigger radius or submunitions.

Alternatively, the "phasing" tag could be changed to mean "continues after hitting something and can't hit that thing again", then "uncollidable" is added to mean that "can't collide with anything".
This gives "phasing" a more predictable behaviour, and opens up new modding possibilities.

**Comment by MCOfficer** [comment]
that seems like an arbitrary change solely for your own projects to work. nothing against that, but i don't see anyone but you making an effort for it.

**Comment by Tadrix** [comment]
> there's no way for the game to know whether, in this particular case, the player is intentionally firing at a disabled ship to destroy it versus firing at another ship and the disabled one got in their way.

> so it does the thing that is more likely to be useful

@endless-sky Wouldn't it be more useful to ignore inactive (disabled) threats for a possibility that there's an active threat further along? If there isn't one, player would have time to click and target ship (s)he wants to destroy.

**Comment by accursedCursive** [comment]
@MCOfficer 
It's actually reducing the arbitrariness.
The current behaviour of "phasing" is programmed specifically for Gridfire, which makes it pretty useless for anything else.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/afc4df90fa24a77c36afa95e3501b8222e8dd9bd `"phasing," meaning the projectile is not blocked by asteroids or other ships.`
This is what the attribute is programmed to do. It is intended to be an attribute that ensures that the target ship will be hit if it is in range, without fail. The Gridfire utilizes this ability, but it is by no means specifically for the Gridfire. If you are attempting to do something else with phasing, then you are not using it for its intended purpose.
>This gives "phasing" a more predictable behaviour

I fail to see how phasing is unpredictable currently. If targeting a ship and the ship is in range, you will hit your target, as the projectile will pass through anything else it could collide with (i.e. `not blocked by asteroids or other ships`). If not targeting anything, the projectile acts like normal (as shown by this issue). That's all there is to it.

>Even if nothing in the vanilla game would need the phasing tag to pass through absolutely everything, a mod might need it.
>Alternatively, the "phasing" tag could be changed to mean "continues after hitting something and can't hit that thing again", then "uncollidable" is added to mean "can't collide with anything".

If you're looking for an attribute that does something different than what phasing currently does, then you should make a feature request asking for a new attribute instead of demanding that phasing be changed.

**Comment by tehhowch** [comment]
I think `phasing` is quite useful for any weapon which should hit what the ship that fires it is targeting and not anything else. I can imagine some alien civilization that lives in asteroid-heavy regions of space have learned how to manipulate the space fabric such that they are able to effectively defend their space from a distance, while invading parties first have to approach through a dense field, unable to deal significant damage until very close to the target -- having been picked off the whole way.
Or alternately, by strategic commanders that use their phasing weapons to target a very powerful ship that is hiding behind a "cloak" of cheap and numerous fightercraft.

**Comment by accursedCursive** [comment]
@Amazinite , @tehhowch 
In that case, "continues after hitting something and can't hit that thing again" works excellently.
It hits through obstacles, which is what the vanilla game and existing mods need.
It doesn't allow projectiles to be stopped even by the target, which is what I need.
It hits multiple targets, which is what future mods might need.

The only downside to this is that it's no longer possible to make a weapon that can phase through enemy ships but is only able to damage one ship at a time.
I can't really see anyone preferring the old behaviour though, given that phasing is meant to make a weapon better against groups of ships, and my new behaviour emphasises that.

**Comment by jafdy** [comment]
I would consider that a fairly large downside, seeing as the weapon that uses phasing now is only meant to hit one ship at a time.

**Comment by Amazinite** [comment]
@accursedCursive I'll repeat myself

>If you're looking for an attribute that does something different than what phasing currently does, then you should make a feature request asking for a new attribute instead of demanding that phasing be changed

**Comment by accursedCursive** [comment]
The reason I think phasing should be changed as opposed to a new tag being added isn't a technicality, it's because it better fits in with how ES is developed and maintained.

Plus, it should also be considered that the current behaviour of the phasing tag is not necessarily the ideal behaviour of the phasing tag.
There's three possible versions of how the Gridfire turret was developed:
-A weapon was imagined with sci-fi reasoning (e.g. "projectiles that curve in the fourth dimension"), then the phasing tag was made to fit it
-A generic piercing weapon was desired, but the more obvious kind of phasing behaviour was harder to program, so the current kind was made out of laziness
-With no sci-fi reasoning, someone decided "I want a piercing weapon that has almost none of the benefits of a piercing weapon"

It's not the first one, because the description of the Gridfire turret sucks.
The third one is unlikely, but possible.
I'm almost certain it was the second one.

**Comment by KiLEdEnNis** [comment]
> The reason I think phasing should be changed as opposed to a new tag being added isn't a technicality, it's because it better fits in with how ES is developed and maintained.

[citation needed]

basically what you've been doing from the start, and now again: "this must happen because I think it's better this way" and ya never give any solid argument, ya just claim it's better for the game for no reason and hope to get your way
this isn't how the world works, and the sooner ya accept that the sooner we'll actually consider your opinion (we stopped valuing yours because you've been claiming bs all over and lost all credibility due to a lack of arguments)

**Comment by Amazinite** [comment]
@accursedCursive I'll repeat myself.

># If you're looking for an attribute that does something different than what phasing currently does, then you should make a feature request asking for a new attribute instead of demanding that phasing be changed

**Comment by Bladewood** [comment]
*leave me alone already*

**Comment by jafdy** [comment]
Gridfire is named and modeled after the Culture weapon of the same name from novels by Ian M Banks. Consider Phlebas is a good example.

**Comment by jafdy** [comment]
Gridfire is named and modeled after the Culture weapon of the same name from novels by Ian M Banks. Consider Phlebas is a good example.
