### ISSUE TITLE
Request: add more reverse engines

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3252]
Currently there exists just one reverse engine, the "AR120 Reverse Thruster" of the A atomic engine set. It would be nice if all other engine sets (animal plasma, X Ionic, Hai B Atomic) would also have a reverse engine each. Even if they're not for sale anywhere, at least having them would be nice for variant ships.

**Comment by tehhowch** [comment]
Reverse engines in the main game indeed are underdeveloped. Put together the appropriate content (sprites & balanced attributes) and you can probably get it merged. Help can be found on the Wiki regarding resources, art styles, etc. Existing .blend files for the games models are in a Google Drive around here somewhere.

More content of course doesn't do anything to improve how NPCs utilize reverse thrust in close-quarters combat. One reason content hasn't developed around reverse thrust is that the movement decisions being made currently prefer simple (and fast) decisions, and improving other parts of the game have taken priority / been more interesting. If you're able to improve the AI logic, go right ahead and PR the changes.

**Comment by endless-sky** [comment]
Reverse thrusters are really a niche item - aside from making jumps a little faster, they're useless for any player who has actually learned how to fly their ship. So, I don't see any reason to add more of them.

**Comment by gunqqer** [comment]
Yeah reverse thrusters aren't very useful. It's better to just have better turning and forward thrusting if you need better jump times. Although, if someone does make more I would support them being added. Would I use them? Eh probably not, but I don't oppose them

**Comment by ghoulavenger** [comment]
They are niche, but you'll never see me strip them from my Deep River jump drive fleet. It speeds up jumps considerably for those, way faster than any steering I've come across, and for significantly less outfit space. If you're not using jump drives though, I suppose just using a scram with good steering is better. 

While I'd like to see more reverse thrusters I get the feeling that the wide variety of them isn't as necessary as you might think. The remnant might have a variant just because they're scroungers (if they can make it work they might sell it), if the Korath had a fast attack ship, it might make sense on that too (a really powerful plasma reverse thruster, be even better if it doubles as a heat weapon). Other than that, you're essentially just talking about a less space efficient reverse thruster -- it isn't even like the AR120 isn't strong enough for your piloting needs, unless you really want to drive backwards (using them as brakes I understand, but not piloting backwards).

**Comment by KiLEdEnNis** [comment]
big slow low-turn ships could have reverse thrusters to "make up" for that
maybe some alien species could be more focused on this than actual turning

**Comment by Nescio0** [comment]
Yes, reverse thrusters are not very useful; simply turning around your ship with side thrusters is faster and more efficient. 

> Reverse thrusters are really a niche item - aside  from making jumps a little faster, they're useless for any player who  has actually learned how to fly their ship.

Exactly! However, for an inexperienced pilot such as me my ship tends to drift away when my fleet takes care of attacking ships, because I'm too slow to turn around; as a result other ships tend to blow up the enemies before I could capture them. With harvesting meteorites my lack of piloting skills is also a problem, therefore I'm potentially a niche customer, interested in a reversed thruster.

Having a Deepspace A Atomic reverse thruster in combination with my Hai B Atomic engines looks aestethically unpleasing. Therefore I'd appreciate it if there was one for every engine set (even though I realize they're inefficient).

**Comment by KiLEdEnNis** [comment]
an excuse to limit HUMAN reverse thrusters could be that it was a test concept that didn't prove useful
but I'd really like to see big-ass ships that turn so slow they need reverse thrusters

furthermore:
reverse thrust could give a combat advantage (together with hit force to keep a distance), which is good
it disables pressing the backwards key to turn exactly the opposite side of where you're going, which is bad

**Comment by ghoulavenger** [comment]
If reverse thrusters could help you turn faster, that would be an interesting reason to use them assuming you didn't need forward momentum. Doesn't really fit the current reverse thrusters though which are the basic opposites of traditional thrusters. I feel like you're suggesting forward mounted steering instead, which could work (rear fires on the left, forward fires on the right when you turn left etc) -- the only problem is that such a ship would need massive weapon space for it to be worth it. The current reverse thrusters, if applied as steering are far too weak to make a substantial difference in turning speed on all but the smallest craft.

**Comment by tehhowch** [comment]
Ship designers would be silly to not utilise steering pairs. Arguably they all do already, as ES ships clearly rotate around their center-of-sprite. If the steering mechanisms are only located in the rear section, then the ships would (should) display very different rotational behavior.

From a physics perspective, reverse thrusters are a poor complement to a ship's main thrusters if the goal is to induce controlled rotation - they are located extremely close to the ships centerline, and thrust along this direction. This results in a very small torque moment arm, especially compared to that created by turning the thrusters to act normal to the ships centerline.

**Comment by ghoulavenger** [comment]
> Ship designers would be silly to not utilise steering pairs. Arguably they all do already, as ES ships clearly rotate around their center-of-sprite. If the steering mechanisms are only located in the rear section, then the ships would (should) display very different rotational behavior.

The breakdown of the engine system to allow for either thrusters or steering or both, assumes the tonnage is concentrated, unless component systems are far more dynamic than they are allowing for (like sticking some parts in the center of the ship and some on the side, which feels more like globalized outfit space rather than designated outfit space). Not to mention you kind of broke that idea when reverse thrusters did not use engine space but rather weapon space. As far as I'm concerned, no ships in the game have forward steering, they're all rear wheel drive.

**Comment by Amazinite** [comment]
Remnant engines have been given in-built reverse thrust, and #5792 seeks to add ion and plasma reverse thrusters. After that, I think it'd be fair to close this issue, as we'd have far more reverse thrusters than the one that existed when this issue was opened.
