### ISSUE TITLE
Few Human ships have enough gun or turret mounts to take advantage of Energy Blasters' small size

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3264]
I've [brought](https://github.com/endless-sky/endless-sky/issues/194) [this](https://github.com/endless-sky/endless-sky/issues/316) [up](https://github.com/endless-sky/endless-sky/issues/668) [before](https://github.com/endless-sky/endless-sky/issues/1533), but I wanted to take the opportunity to do so once more in an integrated manner, reflecting years of gameplay and observation of player trends.

## The issue ###
Energy blasters are reasonably efficient on a damage-per-ton basis, but most human ships don't have enough gun or turret mounts to actually take advantage of this, so their effective maximum DPS is capped. If you only have four gun or turret  mounts, then it makes more sense to fill them with better weapons because you don't get the option to achieve a similar or higher DPS by instead using a larger number of less efficient worse ones weapons.

## The proposal ##
Without increasing any ships' weapon or outfit capacities at all or changing their default loadouts, raise the number of gun ports and turret mounts on human ships across the board--and especially on fighter-sized craft. I mean, the Sparrow already _looks_ like it has four gun ports. Give the sparrow four gun ports, the Berserker 6, the Hawk and Fury 8, and give every turret-armed ship another turret or two (you can imagine that they're on the underside of the ship, so no sprite changes would be necessary).

## Why it would be a gameplay improvement ##
This would improve the humble Energy Blaster's competitiveness during Tier 1 play without actually needing to change the weapon at all. Instead, you'd have the option to fit more of them to achieve higher DPS compared to using Lasers. A reasonable player might actually decide to favor Energy Blasters over Laser weapons, whereas at present time nobody would make that decision; Heavy Lasers are just a straight-up better option if your gun and turret mounts are limited to 3 or 4 each (which is almost always).

This would also make gun-armed fighter craft more useful at low numbers (we all know that a swarm of 40 status-quo fighters with Gatling Guns or Pulse Cannons is deadly, but that's not actually seen in most play). This would also allow fighter-sized craft to feasibly be armed with missiles and also an effective number of guns which would vastly improve their missile-firing behavior: instead of annoyingly running away while spamming missiles, they would fire their missiles while they close to use their guns, which is more more fun to observe and fight against, and more reflective of how contemporary military aircraft operate.

This would not require any default ship loadout changes--and therefore no balance testing, either. You'd just have another practical option for how to arm your Tier 1 Human ships.

**Comment by Amazinite** [comment]
So your suggestions are:
* Increase the number of gun ports on interceptors and fighters (and drones?)
* +1 turret mounts on all ships with turrets

but only for human ships?

Personally, I'm 100% on board with increasing the gun ports on interceptors.
The following is a chart showing all the interceptors in the game (excluding the Marauder Arrow and Bounder). On the left is their weapon space, on the right is their gun ports, and in the middle is the number of weapons of a certain type they could hold given no restriction on gun ports. I chose to only look at early game weapons between 5 and 15 tons.
![screenshot_1](https://user-images.githubusercontent.com/17688683/33193759-c113caf4-d098-11e7-8a8e-db51913480b5.png)

* Sparrow: this ship has the potential to carry 4 normal blasters or 3 modified blasters. If the number of gun ports on the Sparrow was raised from 2 to 4 then this would only allow for more blasters to be equipped, as all other weapons are too large for the Sparrow to fit any more than 1 or 2 already.
* Wasp: same story as the Sparrow; from 3 to 5 gun ports would allow the Wasp to equip 5 blasters or 4 modified blasters, and no other weapon would be able to be equipped more.
* Fury: could carry 8 normal blasters or 6 modified blasters. Increasing the gun port space any more would also allow a Fury to equip an additional Gatling gun or beam laser. From 4 to 8 gun ports would make sense if we want to be able to saturate a Fury's weapon space with blasters, but I think that raising it to only 6 so that it can equip as many modified blasters as possible is more reasonable.
* Marauder Fury: this is a special ship with lots of weapon space, but I included for the sake of comparison with the normal Fury. Either the M Fury should remain unchanged or have its gun port space be increased from 6 to 8 (so it either ties with the Fury or still has 2 extra gun ports).
* Berserker: same story as the Wasp and Sparrow; an increase in gun port space only allows more blasters, but other weapons are already able to saturate the gun space.
* Hawk: this ship has the same exact weapon space as the Fury, but instead of currently having 4 gun ports it only has 2. The Hawk normally spawns with two heavy lasers installed, meaning that it's generally a heavy hitting interceptor. Because of this, I think that instead of focusing on being able to have the Hawk be saturated with blasters, raising its gun ports from 2 to 4 so that it can be saturated with meteor missiles is more reasonable.
* Model 8: Included in the picture for the sake of seeing how the only T2 interceptor in the game would look. If the Model 8 changed at all, then from 2 to 4 gun ports would make sense to me, as that would allow it to cap out on Korath Repeaters (for the likely occasion that the player is able to purchase Korath tech).

So looking at those numbers, this is my proposal

Ship | Current ports | Proposed ports
---|--------|-----|
Sparrow | 2 | 4
Wasp | 3 | 5
Fury | 4 | 6, in order to allow the Fury to saturate its weapon space with modified blasters but not normal blasters for the sake of keeping normal interceptor gun port numbers at or below 6.
Marauder Fury | 6 | 6 or 8, depending on if we desire the M Fury to retain its upgrade in gun ports over the normal Fury
Berserker | 4 | 5, in order to allow the Berserker to saturate its weapon space with modified blasters but not normal blasters for the sake of keeping normal interceptor gun port numbers at or below 6.
Hawk | 2 | 4
Model 8 | 2 | 4

The keeping interceptor gun port numbers at or below 6 is just a personal preference thing (some part of me just doesn't want to go higher), but if we wanted to have the Berserker and Fury saturate their gun ports with normal blasters then they'd need 7 and 8 gun ports respectively.

In the end, these changes would allow interceptors to take better advantage of small weaponry, especially blasters. I don't see light warships needing a change as they have high enough weapon space that blasters becomes entirely useless on them anyways. Blasters (in their gun form) are suppose to be very *very* early game guns, and once you get to a light warship your guns should probably be filled with missiles, cannons, or lasers.

**Comment by Pointedstick** [comment]
Basically yeah. The exact numbers of additional gun ports isn't particularly important to me; I just think more is better because it yields more flexibility. In particular allowing interceptors to mount a pair of missile launchers alongside 2 heavy guns or 4+ light ones would be ideal. They might actually be useful!

I wouldn't be averse to doing the same for alien ships too, but maybe a little less so, to distinguish them from Human ships. Human ships would be known for their many weaker guns, while alien ships would be known for fewer stronger ones. But that's a judgment call that I'm pretty neutral on.

**Comment by Bladewood** [comment]
I think the way it works should be like this:

Humans are the most balanced overall (though at the same time relatively boring among races): a reasonable number of reasonably powerful guns. Or, a mix of small, weak guns, and large, strong guns.

But once we move past them into the alien game, this balance goes way out of wack, taken to lots of extremes. Some races will be biased towards having a lot of weak guns (Korath repeaters, Heliarch bombardment cannons); others will have a small number of strong guns (Wanderer sunbeams).

**Comment by KiLEdEnNis** [comment]
more gun ports on interceptors enables the use of small guns you'd never get on a big warship, so I'm in on that

**Comment by jafdy** [comment]
Humans need to provide an entire ecosystem of choices on their own. Once you add a collection of aliens they can each have a particular style without needing to force the play towards a particular playstyle.

**Comment by KiLEdEnNis** [comment]
> Once you add a collection of aliens they can each have a particular style without needing to force the play towards a particular playstyle.

I'm a little confused, could ya explain what ya mean please?

**Comment by jafdy** [comment]
I was commenting on Bladewood's last paragraph.

**Comment by endless-sky** [comment]
In general, the ship sprites are designed to have something that looks like a gun or turret mount wherever there are weapon hardpoints. So, increasing the hardpoints might require re-doing graphics.

Also note that even if you could put 8 Energy Blasters on a Fury, there would be no way to provide enough energy for them unless you install a reactor that's worth several times more than the chassis of your ship. (And even then, heat would be an issue.)

**Comment by Pointedstick** [comment]
But if Missile launchers were half their size and had internal magazines 1/10 the size, each fighter could easily fit at least two missile launchers to complement their gun armament, and fire those few missiles on the way in to use their primary gun weapons once out of missiles.

**Comment by Amazinite** [comment]
>So, increasing the hardpoints might require re-doing graphics.

Some ships, like the Argosy, Modified Argosy, Bastion, Frigate, Carrier, and probably more already have 2 gun ports placed over top of the same visual gun port, so redoing graphics might not be necessary.

**Comment by Pointedstick** [comment]
In fact, if you take a look at the Blender model for the Vanguard, it already does have stacked guns.

**Comment by Amazinite** [comment]
I've increased the gun ports on most human interceptors in #3350, as well as decreased the firing energy and heat of blasters by roughly 33% in order to make a Sparrow with 4 blasters more feasible.

**Comment by Pointedstick** [comment]
I approve of the PR, but it's not only fighters that would benefit. Plenty of mid-sized and larger human ships need more turret mounts in particular. If you've only got 2 or 3, it makes far more sense to fill them with Heavy Laser or now Proton turrets (or Pulse or Thrasher turrets if you've discovered the Hai and Remnant) than it does Quad Blaster turrets. This is even more true if you're going to use one hardpoint for an anti-missile turret of some kind--the remaining turret hardpoints need to work harder on a DPS basis as long as you have the weapon space to spare.

Basically the balance of turret mounts to weapon space seems off when we're talking about Tier 1 human ships and weapons. Most human ships with small numbers of turret hardpoints have enough weapon space to mount a Heavy Anti-Missile turret and saturate the remaining 1-3 turret slots with really good turrets, rather than having to meaningfully choose between saturating them with quad blaster turrets or leaving a few empty.

Especially if we give the fighters more gun hardpoints, I think most human ships with turret hardpoints could benefit from at least one more. Especially the capital ships, which often have the same number of turret hardpoints as low-end freighters (see also https://github.com/endless-sky/endless-sky/issues/194). If we add more turret hardpoints without increasing anyone's weapon space, that automatically buffs the Quad Blaster turret a bit because it becomes more of an option with its high DPS/ton rating.

**Comment by KiLEdEnNis** [comment]
I agree with Pointed: try outfitting a Frigate, you'll have more hardpoints than ya can really fill, so ya may pick a blaster turret, while if ya look at the Firebird, Osprey, Splinter, Corvette etc. ya can usually fill the hardpoints nicely
for now I'd say merge this to make Interceptors a bit more viable, then add some hardpoints to a few Light & Medium warships to encourage smaller turrets on them as well

**Comment by AlbertNewton** [comment]
Perhaps quad blasters could be added as fixed weapons, not just turrets. With 4 times the DPS, but 4 times the outfit space, 4 times the power and 5 times the heat, a quad blaster could be a reasonable weapon on a medium warship, or even a heavy warship with a small range buff.

**Comment by Amazinite** [comment]
I'm interested in resurrecting #3350, but there has also been chatter of potentially adding a dual-blaster fixed gun. A quad blaster fixed gun seems a bit excessive though. Could be something straight out of Kraz.

**Comment by Quantumshark** [comment]
I think this has been adequately resolved by #8469
