### ISSUE TITLE
Consider improving smaller and projectile-firing turrets to make them more attractive compared to large beam-firing turrets

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3265]
This has been brought up before, but I wanted to take the opportunity to do so once more in an integrated manner, reflecting years of gameplay and observation of player trends.

## The issue ##
- Beam-firing turrets (human and alien alike) are virtually no-brainers because they have perfect aim and auto-hit, which gives them a higher effective DPS than projectile-firing turrets whose projectiles can miss 10-50% of the time (depending on both ships' vectors and the guns' inaccuracies).
- Larger turrets in general (including most of the beam turrets) are just a better option than smaller turrets due to a lack of enough turret mounts on most ships to instead use a greater number of weaker turrets (see also https://github.com/endless-sky/endless-sky/issues/3264).

Giving larger turrets a more limited turn rate helped a bit, but IMHO it's not aggressive enough: massive Dual Sunbeam and Plasma turrets still track fast enough to waste incoming fighter-sized craft and out-range almost every other common weapon.

## The proposal ##
- Rebalance small projectile-firing turrets (like the Quad Blaster Turret) as necessary to make them more attractive vs beam turrets
- Further reduce turn rates for large turrets like Dual Sunbeams and Plasma Turrets
- Create turret versions of the largest projectile guns (Proton turret, Particle turret, etc.; single-gun versions would be fine).

## Why it would be a gameplay improvement ##
Making projectile-firing turrets more numerous and competitive would increase the practical options available to players. And with slower turn rates, large turrets would become anti-capital-ship weapons--like the 16-inch guns on the battleships of yore--and requiring a secondary armament of more nimble turrets capable of hitting fast-moving targets--like the 40mm AA guns on those battleships. You'd need to mount a mix of weaponry to be maximally effective against all kinds of ships. This would make the game more interesting and open up new tactical possibilities and ship loadouts, and discourage players from following the current obvious approach of getting the biggest ships and stuffing them full of the biggest turrets. That gets boring! Players with large capital ships might rationally consider replacing some of their Sunbeam and Plasma turrets with Heavy Laser, Electron or Pulse turrets for anti-fighter defense. They might consider using anti-fighter picket ships. If there were Particle turrets, their range might make them competitive even into Tier 2. There would be more practical options rather than as clear a linear progression in favor of bigger weapons in all circumstances.

**Comment by Amazinite** [comment]
>Further reduce turn rates for large turrets like Dual Sunbeams and Plasma Turrets

Personally, I never found the current turret turn rates low enough to be noticeable in most cases. As you said, even the slowest of turrets are substantially fast enough to take down fighters and drones. A bigger difference between the turn rates of small and large turrets would be welcomed in my eyes.

You say this:
>Rebalance small projectile-firing turrets (like the Quad Blaster Turret) as necessary to make them more attractive vs beam turrets

but don't elaborate beyond "as necessary". The only thing I can think of to make projectile weapons more attractive compared to laser weapons is if lasers were intended for closer combat while projectile weapons were able to reach out to farther ranges. Even if the inaccuracy made hitting things at those ranges difficult, it would still be some damage compared to the no damage that a laser would get at that range. And since slightly inaccurate weapons will almost always hit up close, they can still be competitive when against lasers at that range, but the generally higher damage output of lasers will make up for the fact that they have to get closer to begin damaging.

>Create turret versions of the largest projectile guns (Proton turret, Particle turret, etc.; single-gun versions would be fine).

For what reason? Simply to make turreted projectile weapons more prevalent in human space? The plasma turret comes from the FW story, so I imagine that a proton or particle turret might as well, but that seems way too bland to me. A single proton turret might make sense to be sold at the start of the game though; just another way for the Syndicate to have an edge against its competitors, being the only weapons producer to build a large projectile turret. It's an untapped market at the beginning of the game right now, so I'm surprised the Syndicate haven't jumped on it years before we even start.

**Comment by Pointedstick** [comment]
I agree with everytihng you say. As for specific changes,I deliberately left it vague, mostly as an entry point to a larger discussion. There are many ways that Blasters and their turrets could be improved to the point that you would actually want to use them, but personally I would go with slightly longer range and faster projectile speed.

**Comment by endless-sky** [comment]
I definitely agree that the turret turn rates could be tweaked to further differentiate between them. The turn rates I gave them were chosen somewhat arbitrarily, and in general I think they ought to cover a much wider range (e.g. from 0.5 to 10 or so, instead of the current range from 2 to 6 degrees per frame). It would take a lot of experimentation to figure out what values best achieve the goal of making different turrets useful in different situations, though.

As for adding even more human weapons (e.g. more turrets) I feel like human space already provides a player with way too many choices as it is.

Note that the Hai Pulse Cannon / Turret is a projectile weapon that already gives a very good alternative to human weapons. My go-to ship loadout for the FW campaign is generally a Shield Beetle with nothing but Pulse weapons; the DPS is far better than Heavy Lasers.

**Comment by KiLEdEnNis** [comment]
for me plasma cannons & pulse turrets on a... Falcon? was the way to go, mostly because half the weapons in human space felt straight-up worse than the rest
we shouldn't add new human weapons, but changing some so that they're all decent options to buy would increase variety

**Comment by SirStigII** [comment]
A single proton turret combined with the ability to have an escort "gather" around other escorts could potentially make protectors actually useful as convoy muscle, the description for proton guns even suggests that they are highly effective against fighter sized ships, it only seems logical to stick them on a turret monster like the protector and use it to "block" fighters from being able to get in close and cause damage to convoys. I am definitely in support of a proton turret. Particle cannons would be interesting also, but the niche might be too small. In universe I find it hard to believe that their respective manufacturers haven't slapped them onto turrets. It could even help differentiate the different weapons into "good for fighter defence/offence", "good for capital warfare" ie a 70 ton particle turret that turns like molasses in january, and good all arounders like the electron beam. I know I would get a blast out of using a dreadnaught with 5 proton turrets bouncing fighters and gunboats around.

**Comment by KiLEdEnNis** [comment]
again, I'm not sure if we should add any new human weapons
although I did get an idea for the Proton Gun: what if its main strength is high fire rate and velocity? or at least buff the damage a little & the range a bit

**Comment by Pointedstick** [comment]
I like the Proton Turret idea, especially if we reduce the gun version to 15 tons and make it a little worse to compensate. That would make Proton weapons useful options. You could even stick two Proton Guns and a Meteor Missile Launcher on a Fury!

**Comment by Amazinite** [comment]
(From #3271)
How about this? (Only showing turrets I'd change)

Turret | Current | Proposed | Purpose 
-----|------|-------|-------
Blaster | 5 | 6 | Anti-fighter
Laser | 6 | 5 | Anti-fighter
Heavy Laser | 3.5 | 3 | Balanced
Electron | 2.5 | 1.5 | Anti-capital
Plasma | 2 | 1 | Anti-capital
Pulse | 4 | 3 | Balanced
Pug Zapper | 3 | 2 | Balanced
Thrasher | 3 | 2.5 | Balanced
Repeater | 4 | 3 | Balanced
Slicer | 3 | 2.5 | Balanced/anti-capital (needs to be fast enough to deal with Sestor fighters)
Sunbeam | 3 | 2.5 | Balanced
Moonbeam | 4.5 | 4 | Anti-fighter
Dual Sunbeam | 2 | 1 | Anti-capital
Bombardment | 6 | 3 | Balanced

The numbers I'm working off of:
Anti-fighter: 3 to 6
Balanced: 1.5 to 3
Anti-capital: 0.5 to 1.5

I'm only working off of easy numbers (whole or x.5), but turn rates can be shifted a few tenths for the purpose of differentiating turn rates if necessary. Excluding the Blaster Turret, I reduced the turn rate of everything shown.

Remaining turrets:

Turret | Turn Rate | Purpose
-----|------|-------|
Mod Blaster | 4 | Anti-fighter |
Quad Blaster | 3 | Balanced |
Banisher | 6 | Supportive |
Grab-strike | 4 | Supportive |
Disruptor | 4 | Supportive |
Attractor | 3.5 | Supportive |
Repulsor | 2.5 | Supportive |
Skylance | 4 | Balanced? | 

I left the supportive type turrets untouched since they're more based on applying an affect than dealing damage themselves. The Skylance I left untouched because there's really no way to know if it's simply a Quarg version of an anti-fighter weapon or if it's one of the heaviest weapons they have.

**Comment by Amazinite** [comment]
>As for adding even more human weapons (e.g. more turrets) I feel like human space already provides a player with way too many choices as it is.

Personally, I'm going to have to disagree on this front. Yes, human space does provide a large number of choices in many areas, but in terms of offensive turrets pre-campaign, human space only has 5 turrets available to buy, and the Heavy Laser Turret is really the only viable choice among those, as it's a straight upgrade from the Laser Turret and blaster weapons are a joke right now if you can afford lasers, which isn't hard to do. Post-campaign, the two viable offensive human turrets become the Plasma Turret and Electron Turret. A Proton Turret could serve as the long range projectile turret that competes with the Heavy Laser Turret pre-campaign, and still hold viability post-campaign being the longest range human turret.

In contrast with other species, I'd say that all 5 Korath non-AM turrets (Repeater, Disruptor, Slicer, Banisher, Grab-strike) are all viable choices, as are all 3 Heliarch turrets (Bombardment, Repulsor and Attractor, assuming we had access to them) and all 3 Wanderer turrets (including the Moonbeam, and the single Sunbeam is still viable once the Dual Sunbeam comes out because of its ease of use on smaller ships).

>Note that the Hai Pulse Cannon / Turret is a projectile weapon that already gives a very good alternative to human weapons.

An alternative that not everyone will know about before starting the campaign on their first playthrough. I feel that providing a reasonable alternative in human space is preferable to placing the only alternative outside of human space.

**Comment by Pointedstick** [comment]
At least in tier 1 human space/play, I would consider that https://github.com/endless-sky/endless-sky/pull/3316 and https://github.com/endless-sky/endless-sky/pull/3319 go a long way toward resolving this. Some small improvement to all Blaster weapons would seal the deal.

**Comment by Pointedstick** [comment]
I gotta say, I'm reeeeeeeeeally enjoying the new Proton Turret. It's a super fun weapon, competitive with the Heavy Laser turret and totally satisfying to use. Protectors with 6 are hilarious to watch--and deadly effective. So IMHO we've effectively tackled the issue from the Heavy Laser Turret perspective. Now onto blasters: the Proton Turret blows the Quad Blaster Turret out of the water in nearly every way--including heat output and energy use, which especially seems a bit silly, and Proton weaponry's new higher range makes the choice even easier.

**Comment by endless-sky** [comment]
In commit 6da2d50 I've reduced most of the turret turn rates. I tested each one against large ships and interceptors to get a sense for how it performs. A turn rate of 1 (60 degrees per second) seems like about the lowest it can go without getting really annoying, because the turret ends up chasing the target around but never being pointed at it closely enough to fire.

It might help if the turret aiming AI were modified to take a target's current "angular velocity" (rate of change in heading) into account when deciding which direction to turn in to intercept the target.

**Comment by endless-sky** [comment]
I think the Quad Blaster with the recent range upgrade is reasonably able to compete with the Proton Turret. It does the same amount of damage but takes up 30% less space, and has only a 20% shorter range.

**Comment by Knightroad** [comment]
The Quad Blaster is by far my least favorite human turret. While it doesn't take up much space, and is one of the fastest firing (non-laser) turrets in the game, it's very low projectile speed makes it so that you are putting a bunch of crud in the sky and hoping something runs into most of the shots. I would welcome one or two new projectile turret.

**Comment by Pointedstick** [comment]
I feel like as a meta-task this is resolved now. Individual issues should be raised against niggling issues (such as blaster turrets' projectile speed being too low, about which I would agree).

**Comment by Pointedstick** [comment]
I think this is generally accomplished now with the current state of the game with git master.
