### ISSUE TITLE
Outfits in cargo should not depreciate (that fast)

### ISSUE THREAD

**Issue by postscripter8** [endless-sky/endless-sky#3267]
Freshly after doing something stupid... I checked the issue list - looks like I'm first to have done this and complain.

### My story
I have and use 3 different fleets depending on goals. I wanted to buy 700 remnant capacitor crystals for my deep river haulers. Used my jumping beetles fleet to go to remnant space to fetch them and transit as cargo. There by mistake I bought 700 anti-missile turrets (~1M each). Back in Wanderers capital (and 4 mid-landings later) I discovered my mistake. Selling the turrets for ~70% of nominal price. Just lost ~210M CR on transporting brand new high-end outfits across the galaxy... Turns out the galaxy indeed is a dangerous place.

### Conclusion
Wouldn't it maybe be better (more fair) to only depreciate outfits that are actually in use? I thought outfits on parked ships don't depreciate, do they? They shouldn't in cargo either. Or at least outfits held in cargo should depreciate at a tenth the usual rate.

**Comment by ghoulavenger** [comment]
I've often thought that depreciation wasn't a particularly fair mechanic period. This is because it discourages you from trying out new outfit configurations. But you can get around something like this IF you get some way to store outfits in an armory so you could just swap between outfits you have collected without penalty -- storing it in your ships works if you're willing to install the outfits (because you can't park cargo afaik), but thats a very rough way to store outfits for future use and completely locks up the frame which has a value of its own. 

But the reason depreciation was added was *not* to penalize you for hauling outfits from one end of the galaxy to the other. It was to make boarding and looting outfits less profitable, while making capturing ships more viable (by removing death benefits). 

As far as your conclusion goes, depreciation happens on a car the second you drive it off the lot. Whether you drive it or not, it still depreciates. Granted, one of the biggest causes for depreciation in reality is damage to the vehicle where you would need to repair it to restore some value, where in game the repairs are free. So I don't really agree with your conclusion even though I don't really think the depreciation mechanic is fair.

**Comment by Amazinite** [comment]
>Wouldn't it maybe be better (more fair) to only depreciate outfits that are actually in use? I thought outfits on parked ships don't depreciate, do they? 

Parked ships and their outfits will depreciate. It's all a matter of simplicity over complexity in the code. It's easier if everything depreciates based off of the day it was purchased and depreciation isn't put on pause if the item in question isn't in use. The added complexity in the code that would be required to have items not in use put depreciation on pause has been considered too much for the gain in gameplay.

I know that this discussion has been had in the past, but I can't find the exact issue. If anyone else can find it, go ahead and post it.

**Comment by KiLEdEnNis** [comment]
in real life ya have a trial period where ya can return a product for the full price within the first few weeks
so Amazinite's solution is quite good and realistic

**Comment by Nescio0** [comment]
Incidently, how to purchase outfits as cargo? I couldn't find it in the manual.
Apparently it's possible, because a remnant mission asks for a cargo of 50 remnant crystals, and ignores me when I return with a ship with over 50 equipped.

> My solution for this in #2034 was to have a one month grace period where no depreciation occurred, but that hasn't happened.

A one month grace period would be nice. Having different deprecation times for outfits equipped, in cargo, or on parked ships sounds like a bad idea. Furthermore, I'd also favour lowering the minimum value (you can rapidly make hundreds of millions from seizing ships), but I suppose I'm in the minority on this.

**Comment by jafdy** [comment]
You deselect all ships then buy the outfits.

**Comment by tehhowch** [comment]
Or use the view-altering checkboxes in the bottom left.

**Comment by VonZorch** [comment]
Also ammunition should not depreciate, it isn't deteriorating while in the magazine.
Alternately have outfits in cargo and ammo depreciate to 75% not 25%

**Comment by Amazinite** [comment]
Since this issue was opened, depreciation was given a short grace period before kicking in and was greatly extended in how long it takes for items to reach max depreciation, so accidentally buying the wrong item then having it depreciate by a massive amount by the time you reach your destination and realize your error shouldn't be a problem now.
