### ISSUE TITLE
Consider making missile weapons more dangerous and less numerous

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3268]
## The issue ##
Endless Sky's missiles (particularly Human ones) have the following characteristics:
- Individual missiles don't do much damage relative to most ships' shields and hull (e.g. it takes three shots from what's called a **torpedo** to destroy a **shuttle**)
- Because of the above, missiles are spammed, which makes fights against missile-armed adversaries merely annoying rather than nerve-racking. Each individual missile doesn't really do much damage so it's not that big of a deal if you get hit with 10 or 20. The missile spam is particularly ridiculous in Hai-on-Hai fights, where there will be like 200 missiles in flight at any one point in time. It's just silly.
- Because of the above, missiles are extremely expensive damage-for-damage when compared to guns, but don't generally make up for it in effectiveness. Using them becomes a huge money drain, and after nearly every battle, you'll be nearly out of missiles and have to refill for tens or hundreds of thousands of credits.
- Missile Jammers are nearly useless when weighed against their tonnage requirement.

Overall, missiles weapons are annoying to fight against and annoying to use. I think this needs to be remedied.

## The proposal ##
- Make missiles do much, much more damage. Like, factor-of-4 more damage. Prices should also rise a bit.
- Make missile launchers fire much more slowly, have much smaller magazines, and weigh less (this would also increase the utility of the missile box outfits).
- Make the large heavy anti-capital-ship missiles [much more clumsy](https://github.com/endless-sky/endless-sky/issues/1599#issuecomment-256526764) so that they're nearly useless against small and medium sized ships. This would increase the utility of Sidewinders and even humble Meteors, because right now Torpedo-class weapons are practically the only worthwhile guided Human missile weapons.

## Why it would be a gameplay improvement ##
Primary reason: Missiles would actually be fun to use and defend against.

Secondary reasons: by increasing the danger of each individual missile, the player's missile defense strategy would be something to actually consider much of the time. Dodging them would become a more useful skill. Jammers, anti-missile defenses, and cool-running ships would become appropriately more important rather than afterthoughts. And with missiles' increased damage and dangerousness, they would become actually worth using against the AI. Also, with smaller launchers that don't have as much capacity, it would be worth putting missile launchers on fighters, since this would make them actually punch above their weight class like real fighters do--but they wouldn't be able to spam missiles with their low capacity.

**Comment by Amazinite** [comment]
😆 
![screenshot_1](https://user-images.githubusercontent.com/17688683/33195806-b628c878-d0a8-11e7-8065-99e543466480.png)

**Comment by Amazinite** [comment]
I have spreadsheets and free time in December, so I might try to tackle this, along with the other three issues you posted today, assuming they aren't handled by MZ before then. That means they probably won't be in v0.9.9 though.

**Comment by endlesssteve** [comment]
I have to agree with these observations. I never have missiles on my flagship and the first thing I do when I capture a ship is sell any missiles weapons it has. The only drawback I can think of is status of nukes in the storyline. The new missiles should be significantly less powerful. otherwise why bother with nukes?

**Comment by KiLEdEnNis** [comment]
my problem with missiles isn't as much the fact that you have to restock them frequently, it's the limited areas you can but them
human space is mostly central; you can still restock them reasonably easy, but say ya have thunderheads while in Remnant or Coalition space, no way you're gonna travel ALL the way back to restock
and while ya can limit how much ya use on the flagship, the escorts are limited to always, frugal and never
making missiles "more dangerous but less numerous" may not entirely fix it, but it should at least make spamming less of a factor

**Comment by hellminister** [comment]
military class freighter might help with supply.

military class freighter would be a freighter with good defensive capability (high hull, high shield, lots of small turrets for missile defense, low (or no) gun ports, high cargo, ...) and bad offensive capability

you simply need to buy a large amount of your missile in cargo and then you can resupply you fighters when you find an outfitter

I know normal heavy freighters would work, but i never find them strong enough to take in combat zones...

**Comment by Pointedstick** [comment]
So I've been playing a new game with the following changes to missiles:
- Quadrupled damage
- Doubled launcher reload time
- Halved launcher outfit and weapon space requirement
- Launchers only hold 1/10 the ammo in their internal magazines, so you need to buy the missile boxes/racks to actually have a decent number
- Torpedo weapons are even slower
- Meteors have worse tracking but faster turning

The effect is dramatic. Missiles are actually fun to use, and a challenge to avoid. Anti-missile, radar jamming, and cool-running ships are much more important. Fighters can mount missile weapons, but with very limited ammunition, and exhaust their missile stores on their way in to use their gun weapons. It's, actually fun! Like, really really fun! Needs a lot of tweaking and playtesting but I think it holds promise.

**Comment by Amazinite** [comment]
Just out of curiosity, you say that
>Endless Sky's missiles **(particularly Human ones)** have the following characteristics:

and have only been mentioning human missiles, so would these changes only occur to human missiles or would it be an across the board change? Personally I find most of the alien missiles already pretty great.

**Comment by Pointedstick** [comment]
I think most of the proposed changes apply equally well to the alien missiles, especially Hai Trackers. Hai-on-Hai battles quickly result in like 500 missiles in flight at once, which is an absolute visual mess, and becomes impossible to really react to. IMHO the change of increasing missiles' damage and reducing their number works well for them too. maybe less so for Korath mines or Wanderer Thunderheads which are indeed excellent as-is.

**Comment by endless-sky** [comment]
Human missiles already have significantly higher DPS / ton than non-missile weapons. For example, when facing a difficult FW campaign combat like the Pug battles I'll often switch over to heavy rockets to make it easier. I do agree that halving the firing rate and doubling the damage for long-range missiles would make sense, but I might leave the dumb-fire missiles as they are.

Also note that anti-missiles (or, the anti-missile resistance of the missiles) would have to be re-tuned if missiles are less numerous and more deadly.

**Comment by Pointedstick** [comment]
I'm not really talking about mechanistic quantitative measurements like DPS/ton. I'm talking about tone, feel, and _fun._ Most guided missiles simply aren't fun when the only way to use them properly is to spam huge numbers. 

I also only ever use Heavy Rockets as a secondary weapon choice, which probably shows that their damage is more reasonable as-is. But Torpedoes, Sidewinders, and Meteors really need some improvement in the fun department.

**Comment by Amazinite** [comment]
The DPS/ton of secondaries is high, but their chance to hit their target can be the lowest of any weapon given the asteroid density of many systems and the existence of anti-missile turrets, so in practice the DPS isn't as high as on paper.

**Comment by Pointedstick** [comment]
Precisely.

**Comment by KiLEdEnNis** [comment]
while these ideas should of course be fine-tuned, I think the concept would make missiles more fun to use, and it could actually be worth to use them over some steady DPS lasers thay ya never have to restock

**Comment by SirStigII** [comment]
I would definitely support this change, when trying to do small ship playthroughs missiles are a necessity, and the only ones that are worth a damn are thunderheads. There will definitely need to be balancing, but overall I feel fewer but stronger missiles would be an improvement both in gameplay and in visual feel. I also think most asteroid-heavy systems could use a decluttering, but that is a different discussion.

**Comment by Pointedstick** [comment]
So in playtesting the changeset I'm working on, quadrupling the damage and doubling the reload time doubles the _apparent_ DPS, but with anti-missile and jamming, it really just brings the _realized_ DPS in range with what it should have been all along.

Meteors are deadly to large slow hot ships without anti-missile defenses, just like they should have been--but their lower number makes them all but useless against ships with any kind of missile defense . Sidewinders fare better but they do less damage and are much less available outside of Republic space, which becomes an issue during the campaign. Torpedoes are devastating if they can score a hit, but they're really slow and awkward, and there's now an art to delivering them with small fighters.

Overall it feels much more fun. I'm going to submit it as a PR after more playtesting and would welcome others' feedback at that time.

**Comment by Nescio0** [comment]
Advantages of missile launchers:
* great range
* typically smaller in size (mass, outfit capacity) than heavy guns
Disadvantages:
* having to reload your ammo
* anti-missile turrets

Currently, missiles are rather ineffective, mostly because of the effectiveness of anti-missile turrets. A Chameleon anti-missile turret can destroy 4 hai trackers per second, whereas a single pod fires only one tracker per second. However, I think that is a fair trade-off, since anti-missile turrets can't destroy enemy ships, so you sacrifice firepower, which can result in being destroyed by enemies which use guns instead of missiles.

What I would suggest to try out:
* halve the shots/second for all anti-missile turrets
* halve the shots/second for all secondary weapons (including the gatling gun)
  * this means you can do twice as long without refilling
  * because you can fire in salvos, this means anti-missile turrets become slightly less effective
* treble the damage per shot for all secondary weapons (increasing their damage per second, on paper, by 50%); quadrupling sounds a bit too much for now
  * as a result each missile is thrice as cost-effective
* keep masses, sizes, capacities, and prices of launchers, pods, and ammunition unchanged for no

**Comment by SirStigII** [comment]
I would definitely be interested in playtesting your PR.

**Comment by KiLEdEnNis** [comment]
> So in playtesting the changeset I'm working on, quadrupling the damage and doubling the reload time doubles the apparent DPS, but with anti-missile and jamming, it really just brings the realized DPS in range with what it should have been all along.

beam & projectile weapons don't really have a counter, missiles do; they can be jammed and AM works against them
this would make missiles a good choice to buy, and make jammers & AM more important to deal with them, which in return makes the missiles less effective
it basically adds more strategy to ship design too; instead of just getting as much damage onboard as ya can, ya can pick an AM and/or a jammer to keep the ship safe (real-life military ships have that too)

I'm not sure about lowering the ammo capacity that much in the launchers if that's gonna be in the PR too, although ammunition boxes would make this less of an issue

**Comment by Pointedstick** [comment]
> I'm not sure about lowering the ammo capacity that much in the launchers if that's gonna be in the PR too, although ammunition boxes would make this less of an issue

It works well. Fighter-sized ships can fit launchers but not the storage boxes/racks, and will be limited to 2-5 shots. Missile-wise, larger ships are distinguished by their ability to have many launchers and lots of ammo.

Also, diminished ammo capacity in general is less of an issue because because missiles no longer need to be spammed. They're used strategically.

PR in progress...

**Comment by comnom** [comment]
I don't usually chime in on balance, but I'm really against this one.

If we take a step back, the issue seems to be that a missile isnt a guaranteed hit because of asteroid heavy systems, other targets, and anti missile can stop the hit.

Maybe I'm not getting it, but I fail to see how halving fire rates and lowering capacities makes more missiles get through. It seems to me that youre creating a balance where a skilled player will simply abuse the now obscene damage by shooting point blank. (or near enough to not die)

These balance changes only take into account the "worst case" scenario, and completely ignore how strong these weapons will be in open space vs a target with no AM.

Further, I don't even agree that there's anything wrong with missiles in the first place.

An anecdote:
I ran a test a little ways back to see the strength of the capacity outfits wherein I took a stock sparrow, stripped the shields and used a lighter generator, then loaded it up with meteors and meteor racks. I had no trouble at all taking down any ship in my class that didn't have missiles of it's own, and I could clean up most light warships as well assuming no AM or missiles. All without any shield regen, and little to no damage taken because of the range.

On fighters and missiles:
Missiles are incredibly strong on fighters. Each fighter is an extra two hardpoints, with the same capacity as anything else, and theyre quick enough to never get hit. The only time I use fighters is when I have them equipped with missiles, and they put out a ton of damage and rarely die.

**Comment by Pointedstick** [comment]
There are two issues:
- Current missile mechanics **aren't fun** (mostly/especially human missile weapons). They don't feel like they do enough damage, so the only way to use missiles is to spam them, which feels unrealistic and wasteful. And their characteristics are all wrong: Torpedoes can turn on a dime to hit fighters, and mass meteor fire overwhelms capital ships. It's ridiculous, and completely counter to the way real-world missile-style weapons operate.
- Effective DPS is far lower than beam or projectile weapons because of asteroids, anti-missile turrets, and jammers, so you're better off ditching them completely and just using Heavy Lasers or other beam weapons.

All of this is wrong and needs to be fixed.

> I ran a test a little ways back to see the strength of the capacity outfits wherein I took a stock sparrow, stripped the shields and used a lighter generator, then loaded it up with meteors and meteor racks. I had no trouble at all taking down any ship in my class that didn't have missiles of it's own, and I could clean up most light warships as well assuming no AM or missiles. All without any shield regen, and little to no damage taken because of the range.

This is exactly one of the problems I'm trying to address. Missiles are currently too strong on fighters because their capacity is far too high, and there's a lack of AM on many ships. We solve that by lowering launcher capacity, making up the missing capacity with boxes/storage racks that fighters can't fit, and boosting the AM defenses on most larger ships. But perhaps with all this extra AM, missile strengths should be boosted a bit as well.

**Comment by comnom** [comment]
>Current missile mechanics aren't fun

I had plenty of fun terrorizing the galaxy in my sparrow of doom.

>Effective DPS is far lower than beam or projectile weapons because of asteroids, anti-missile turrets, and jammers, so you're better off ditching them completely and just using Heavy Lasers or other beam weapons.

True, but only under those conditions. How will you reconcile the additional power in open space and no AM?

>boosting the AM defenses on most larger ships.

This one confuses me. Do missiles hit enough, or do they not?

**Comment by Pointedstick** [comment]
It seems paradoxical, but missiles are simultaneously not powerful enough and also too powerful--in different situations, and for different reasons. But the basic problem is that the mechanics are all wrong, as I mentioned above. A lone sparrow shouldn't be able to take out multiple capital ships. That's ridiculous. It runs totally contrary to the way the game universe is set up.

> This one confuses me. Do missiles hit enough, or do they not?

They should hit less, but when they do, the hits should deal far more damage. Why? 1. to make missiles more scary, and therefore more interesting, and 2. to better mimic how missiles work in real life.

Both of these will encourage players to use them more.

Did you ever play old-skool EV or EV Override? The missiles in those game did serious damage. They were fun to use, fun to outrun, evade, and jam, and. In EV Nova the only similarly fun missiles were the Hellhound and EMP missiles (because most were really puny and just amounted to annoying pinpricks, which felt all wrong). The only missiles in Endless Sky that offer the same degree of fun as the aforementioned deadly missiles are maybe Wanderer Thunderheads. But for all of the human missiles, I always feel like I'm shooting spitballs, and that the only way to use them would be to fire like 8 at once, which just seems all wrong.

**Comment by comnom** [comment]
>It seems paradoxical, but missiles are simultaneously not powerful enough and also too powerful--in different situations, and for different reasons.

The definition of a specialized weapon. We have a fundamental difference here that'll I doubt we'll get through; I think it's fine, and enjoy the playstyle and you don't.

So rather than debate that I'll just say that I think your PR's are premature. You're tinkering pretty low level in what's become a fairly complex system, so I'll put the argument aside, and instead just list some concerns.


* You'll need to take into account:
	* lower skilled players who have trouble with the current system.
	* low HP starter ships and non warships.
	* the "best case" scenario: no AM, no asteroids
	* large ships (namely, Im already wondering how many super missiles I can pack into a shield beetle or bactrian)
	* all forms of AM
	* all the prices of both ammo, and the weapons and racks
	* default loadouts of all random fleets
	* default loadouts of all the story mission ships
	* if you take missiles away from fighters, you nerf something people already dont like
	* if you make them so damaging, you're going to pidgeon-hole people into using AM
	
It's a pretty big job. I'm not going to argue that you wont have more fun with the system you create, but I don't think realism should be your guiding factor. It's a game. Good luck man.

**Comment by Pointedstick** [comment]
I agree that we have different play styles that likely won't converge, and that I'm proposing changing some pretty basic parts of the game. I don't really expect my PRs to actually get merged; my aim was more to start a conversation, because the subject of missiles just not feeling right comes up a _lot._ It's not just me. I appreciate your points; there's definitely a lot to consider there.

If @endless-sky winds up implementing the more limited version that he proposed yesterday--1/2x missile fire speed, 2x damage, and 1/2x AM strength--I'd be over the moon compared to what we have today.

**Comment by Amazinite** [comment]
I think you're trying to brute force your way into having missiles be better. If should be about making small, fine changes, not making these huge drastic sweeping changes like 4x damage, 1/10th ammo capacity, and half the launcher size.

Here is the main problem with missiles as far as I can see that has been brought up:
* Missiles in general, while having a higher DPS/ton than guns and turrets, will in practice yield less DPS due to asteroids
  * By extension, missiles must be spammed in order to be effective and are therefore expensive.

There's the fact that we are questioning how to make missiles fun/effective in practice, not how to make them realistic, so I'd completely ignore any mass or outfit changes, and capacity changes, and any changes to capacity upgraders. I'd also avoid the fine tuning of any specific missile into a different role than it currently has (e.g. #3277 and #3278).

So in an attempt to ONLY address the above mentioned problem, I think that the following would be reasonable changes:
* Half fire rates and double damages (and possibly half capacities + double ammo weight + double ammo cost in order to retain potential damage output of each launcher).
  * This makes missiles less spammy weapons and more about hitting your shots and making them matter. There is also no net change in DPS, meaning that this is a VERY easy change to work off of should it occur.
* Increase velocities (and perhaps decrease lifetimes to keep the ranges the same) but decrease turn rates. (Exact numbers can be weapon dependent.)
  * These changes help to alleviate the problem of hitting asteroids, and may also be a boost to players with missiles and a negative to NPCs; since NPCs generally turn tail and run while firing, the reduced turn rate will hurt them, but a player looking to aim their shots through asteroids will be helped by the increased velocity.
  * The decrease in turn rate is a trade off for the increased velocity, and may make dodging easier, as one doesn't need to move as far out the path of a missile in order for it to miss them, and a missile that misses will likely not be able to make a return trip.
* Alternatively to the above changes, instead of making each missile more likely to hit, make the ones that do hit more powerful.
  * Based on current numbers, I think a roughly 20% to 25% boost in damage and no other changes would help to mitigate the fact that a majority of missiles will not reach their target due to asteroids.
  * If the reload numbers are halved, this translates to a 2.5x damage boost.
* I would NOT touch anti-missile turrets while changing missiles until the missiles have been changed and we can see how effective they are against current AM turrets.

In all honesty, if we went through with any changes at all, I'd only go one-by-one with each change. "Does this change help, yes or no. If no, remove it and try a different change or tweak the current change slightly. If yes, consider if missiles are now fine. If no, implement another change on top of the first change while considering what the first change has done." I don't know about your thought or testing process when making your changes, but to me it looks like you threw a bunch of changes at a wall and now you're seeing what sticks.

**Comment by Pointedstick** [comment]
Like I said, I don't really expect any of my PRs to be merged and won't feel disappointed if they don't--the goal was to start a conversation about ways to make missiles more realistic and fun. If anything positive comes out of it, all the better. :+1: 

While many of the numbers are off, I think there are real problems that need to be solved:

- Missiles need to be made **fun**, not only through much-needed DPS upgrades in asteroid-laden systems and when facing heavy anti-missile fire, but also in how they **feel and play**. If their DPS is high but they still don't feel right, people like me and my wife who play for mood and story will still avoid them.
- Torpedo-sized weapons shouldn't be easily usable against fighter-sized craft. That's just silly.
- Fighters should be able to mount missile weapons without becoming incredibly overpowered.
- Missiles should _sound_ more impressive!
- Starting ships need to be made less vulnerable to missiles without nerfing missiles for the remainder the game.

If you think you can do a better job (highly likely), please, go ahead!

**Comment by Amazinite** [comment]
Just something to mention: #1537
This needs done still. \:)

**Comment by tehhowch** [comment]
One of the issues new players have with missiles is they can't dodge enough of them for it to make a difference. I think reducing the speed/maneuverability and also the number of them should help newbies with this task, even as the damage from any one missile increases.

**Comment by Nescio0** [comment]
Although I agree missiles are usually not really useful, I don't like all of your ideas, although some could be interesting. In your own words:

> It seems paradoxical, but missiles are simultaneously not powerful enough and also too powerful--in different situations, and for different reasons. 

Quadrupling their damage makes this only worse, as does changing missile launchers without taking anti-missile turrets into account (). Right now missiles are not perfect, but at least they're balanced to each other, to anti-missile turrets, and to non-missile weapons.

A balanced overhaul is not implemented overnight. Please take time to do it in careful, reasonably small steps, while looking both at individual weapons and at the larger picture.

It is also important to keep in mind what works for your playing style might not work for players who do not fully understand the game (e.g. the AI, new players, me, etc).

**Comment by Pointedstick** [comment]
I'm closing this in favor of a new issue I've just filed without any specific recommendations that will inevitably prove controversial and distract from the underlying issue.

https://github.com/endless-sky/endless-sky/issues/3288
