### ISSUE TITLE
Feature Request: Collaborative Multiplayer

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#327]
There's a lot of discussion in #149 about multiplayer, but it's all focused on the idea of giving each player their own ship.

I'd like to propose a collaborative mode, where all players are controlling the same ship, in the style of games like [Artemis](http://artemis.eochu.com/).

This removes the complexity of having to synchronize galactic time between multiple players, and would allow for significantly more complex ship models to be playable by having each player control different aspects.

Some examples of roles that could be made with multiple players include:
 * **Communications officer**: Actions like hailing or consulting the hyperspace map could be done without pausing if a second player were in charge of it. This could also lend itself to more detailed communications screens (e.g., a view showing all ships in the system and letting you choose one instead of having to scroll through them one at a time).
 * **Weapons officer**: Imagine turreted weapons that are actually directed by a player, or a mobile extra shield that could be rotated around the ship to wherever it's most needed - a single player couldn't possibly pilot the ship while operating these systems, but it'd be easy if a second player controlled them.
 * **Chief Engineer**: We could support e.g. diverting power from weapons to shields or steering, or directing repair crews to make minor hull repairs in the middle of combat.
 * **Fleet coordinator**: You could have more fine-grained control over your escorts if someone else had a full fleet coordination panel - they could e.g. assign escorts to groups and issue different commands to these groups, or assign "personality traits" to each group (e.g. "heroic", "timid", "disables").

**Comment by gchapyzh** [comment]
A lot of remodeling for ships will be required to turn this FTL or Pulsar style.

**Comment by airtroop392** [comment]
This sounds really, really, cool. I just want to say a few words:
<ol>
<li> ES is a very fast paced game. From what I've seen of Artemis, it's more leisurely and slow, but gets terse at moments- its slow pacing also allows for more coordination, as teams can predict what is going to happen and create plans around those predictions. In ES, teamwork might be harder and maybe even detrimental (talking to people takes time), due to the high unpredictability of events. </li>
<li>People are going to want to play with a different amount of teammates- some people will want to bring only 2, others will want 3, so forth- there should be a way to assign one person more than one station.</li>
<li>This seems heavily in line with piracy, bounty hunting, or other combat related activities, but it doesn't seem like it would work with trading, which is one of the essential elements of this game. I'm not sure if that's a good thing or not- no one thinks trading is fun anyways, and trading with other people is sure to be even more boring.</li>
</ol>
I thought about adding in some more points, but I felt like if I did, it would come off as nitpicking instead of constructive criticism, so I guess that's all I have to say.

**Comment by dplepage** [comment]
Scaling the player count could be solved by having the AI take care of some of these functions. For example, a manually-operated turret could fall back to a normal "point at your target" turret when nobody was operating it. Ideally any player could claim any station that wasn't currently occupied, so e.g. if you only have two players your co-pilot could stop tinkering with the engine and run to the gun turret when enemies approached (the time needed to switch stations could even be part of the challenge - if you don't plan ahead, you'll be a sitting duck while your crew scrambles to get back to their battle stations).

You're right that this wouldn't be a lot of fun when running trading missions or playing with a small ship - at best, you could benefit in a kind of boring way from a second player who's searching the map for trade routes and handling dialogs. So maybe this would have to be an optional mode that only applies when you have a larger ship? Or maybe this would be a way to scale up from the co-op mode proposed in #149 to larger ships - you and your friends start out as two Sparrows and a Star Barge, but later in the game you're all operating different stations on a single Corvette?

Regarding the pace of Artemis vs ES, I think the biggest difference between Artemis's world and ES's is the level design.

The complexity in ES comes from the network of systems and the missions between them - individual systems are identical except for asteroid density and the specific ships and planets in them, and apart from the planets (which are all right in the middle of the system) every point within a system is the same as every other point.

In Artemis, however, the map is all one continuous block of space, with a wide variety of things scattered throughout it - you can have e.g. a cloud of gas that you can hide in so enemy ships can't detect you, or a weird spatial anomaly that interferes with your ship's movement while you're nearby.

Some of these things could be added to ES - it wouldn't be that difficult to have stellar gravity affect your flight, for example, or to add other in-system objects that interfere with your sensors or combat (or that you can run into), but it'd be a pretty major shift in emphasis - suddenly instead of being a game about multi-jump hyperspace voyages punctuated by large space battles it'd be game primarily about in-system maneuvering and combat.

Possibly if this is implemented it should be an entirely separate play mode, using the same core engine and resources but with a completely different map comprised of a smaller number of much larger systems with diverse navigational hazards etc. in each system.

**Comment by airtroop392** [comment]
Having the AI take over unoccupied stations seems like a good way to solve the problem of crew scaling. As to your second point- remember that one of the major things that came up in #149 was time synchronization- if there are three different ships that are taking different hyperspace routes at same time, the passage of time is broken. An easy way, but maybe not the most effective one, is to simply have the game require all players to be holding down the jump key in order for any one ship to jump (obviously, this has its limitations- what about people who are doing stuff, what about people who have no fuel, so on). This brings me to my next point- having a team pilot two or more ships is not possible <i>unless</li> in this new game mode, the passage of time is changed so that time passes in real time (as opposed to time passing when the hyperdrive is used or when the player lands/takes off), with travel via hyperspace taking a certain amount of seconds (maybe 5 or more, depending on the increments) per jump. This obviously isn't ideal, and it too has its own limitations, which is why I'm proposing something else: players start with choosing a cargo ship, or perhaps a light warship to begin with, instead of the standard assortment. They would, of course, still need to take out a loan and pay their debts- but this way, they at least are able to share the same ship from the start, and are able to work as a team more effectively.

**Comment by gchapyzh** [comment]
I am not shure I want to micro-manage a single ship. Endless sky is all about fleet management, and I see no logical way where multiple layers can manage a single ship. A more realistic scenario is multiple players managing different parts of a fleet, or even better, different players commanding their own fleets.

**Comment by dplepage** [comment]
@gchapyzh Yes, this play mode would definitely change the emphasis - you'd do more single-ship micromanaging, but your ship would be a lot more powerful by itself.

That said, you could also easily use this model for fleet-level multiplayer: one player pilots the flagship while all the others are controlling different subgroups of the main fleet.

@airtroop392 Yeah, in addition to larger and fewer systems, the collaborative play mode would have to have you start with a ship large enough to justify collaborative play (and forbid you from downgrading your flagship to a tiny ship).

**Comment by johndh** [comment]
While this sounds fun(?), it sounds to me like an entirely different game.

**Comment by airtroop392** [comment]
@johndh at this point, it pretty much is- there's no possible way this could fit in the normal game, so at the very least an entirely different game mode would have to be sectioned off and created for this to work. IMHO, would still be worth it.
