### ISSUE TITLE
Random names for ships you buy

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#328]
Since NPC ship names are randomly generated, I'd like this to be available for the player for when I don't feel like being creative.  Maybe next to the okay button, there could be "generate", which would put something random in the text field and the player can accept it, change it, or generate another random name.

**Comment by airtroop392** [comment]
I would argue that you can just as easily go to the internet and simply google for such a generator, and if you were to make the counter argument of name generation for large fleets (50-100+), then I could argue back that once you have a large enough fleet, you tend not to care about what your ships are named simply because there are so many.

**Comment by luiges90** [comment]
In fact all the names are in `data/names.txt`. I think you can simply pick one there :stuck_out_tongue:

**Comment by luiges90** [comment]
And when I am too lazy, I just name it with a number lol :stuck_out_tongue_closed_eyes:  (btw Syndicate do this :laughing: )

**Comment by airtroop392** [comment]
Same here. If I buy ships in bulk, I use the purchase multipliers, put in a simple, generic name, and then let the game affix numbers to my ships.
![image](https://cloud.githubusercontent.com/assets/16041937/11461839/f3a02a5e-96d8-11e5-8bf7-d5cb92ffb5c5.png)

**Comment by frameworld** [comment]
Usually I want a fighter in "SolaEvoluion" be called "SolaEvolution-F0"
But the automatic naming adds a space-character + I want it to count from 0 onward! ;(

I dislike many different ships because it is difficult to setup outfits for many different.
Also they tend to spread apart even further when using scram-drives and improved ramscopes excessively.

**Comment by endless-sky** [comment]
@frameworld, are you aware that you can use shift+click or control+click to select many ships at once and outfit all of them at the same time?

**Comment by frameworld** [comment]
@endless-sky, yes, but that has issues.
With different I meant different ship-types (Light and Heavy shuttle for example - or L and H fighter)

Also you can't sell reactors if only 1 is installed after using shift-click and trying to sell them at once.

Items that are installed on some but not the last ship you clicked sometimes are hidden while multiple are selected, especially when they are not sold at this outfitter.

Sometimes you have an outfit just once and another outfit just once and it gets messy to track which ship has the better versions installed.
I can't store them up until I have 1 for every ship because when I leave the planet they are lost.

Items that are not for sale, but which the outfitter holds (used sell-all in the trade window) are not highlighted - it is easy to forget them accidentally.

Resulting from ships having different outfits installed and only 1 -not the lowest- outfit-space attribute is shown, it can get quite messy.

**Comment by endless-sky** [comment]
For now I've just changed it to give unnamed ships the name "`<first>'s <model name>`", e.g. "Michael's Kestrel."

**Comment by endless-sky** [comment]
I think the solution I mentioned above is probably good enough for this, and it's included in the latest release, so I'm closing this.
