### ISSUE TITLE
The Proton Gun needs a little something

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3287]
It's just a fairly lackluster weapon. It doesn't have the Particle Cannon's extreme range or pushback, nor is it small enough that you can fit it on anything smaller than a warship or very large multipurpose ship and have much room left.

Ideas for improvement:
- Reduce the size to 20 tons
- Increase the damage
- Increase the range
- Inflict special damage(heat, ion, disruption, something else?)
- Something else?

**Comment by KiLEdEnNis** [comment]
tbh just increasing the RoF and range would make it a fun long-range "bombardment" type weapon, and the humans don't really have that yet
what does the rest think about this?

**Comment by Amazinite** [comment]
* Increase damage: Yes
   * The Particle Cannon should get this too
* Increased range: questionable. I think increasing the range on the Proton Gun warrants also changing the other cannon, blaster, and laser ranges (i.e. fully fleshing out #3266).
* Increased fire rate: the Proton Gun already fires super fast.
* Special damage type: No.
* Reduced size: unnecessary in my eyes.

>tbh just increasing the RoF and range would make it a fun long-range "bombardment" type weapon, and the humans don't really have that yet

Humans don't need everything.

**Comment by Lineth** [comment]
T1 I near-exclusively use plasma weapons so anything to make particle and proton guns more attractive would be lovely.

**Comment by KiLEdEnNis** [comment]
> Humans don't need everything.

true, but something as simple as this wouldn't hurt
if the range got buffed, it'd still be more effective up close due to the inaccuracy, but a damage+range buff would make it good

**Comment by Amazinite** [comment]
>true, but something as simple as this wouldn't hurt
if the range got buffed, it'd still be more effective up close due to the inaccuracy, but a damage+range buff would make it good

By lore, the Proton Gun is suppose to be a crappier Particle Cannon, so pretty much anything we do to the Proton Gun means we also need to look over the Particle Cannon. i.e. a range buff to the Proton Gun means a range buff to the Particle Cannon, which I don't think the Particle Cannon needs.

**Comment by KiLEdEnNis** [comment]
fair enough, as long as both options actually do some damage I'm fine with it

**Comment by Pointedstick** [comment]
I'd be fine with it just being a crappier Particle Cannon if it weighed a lot less so I could stuff two of 'em onto a Hawk. :slightly_smiling_face:  KISS

**Comment by Amazinite** [comment]
Well, I guess a size reduction could make sense. MZ has said that he wants the human cannons to work like this: Particle > Plasma > Proton, but the size right now is Particle > Proton > Plasma.

**Comment by Amazinite** [comment]
How about this?
* Mass: 28 -> 20
* Hull damage (total): 24 -> 22
* Shield damage (total): 19.8 -> 17.6
* Hit force (total): 18 -> 13
* Firing force: 2 -> 1.5
* Energy/shot: 15 -> 13
* Heat/shot: 60 -> 54

Changes in balance from this:
* DPS/ton: 11.73 -> 14.85 (~26.5% better per ton)
* Energy and heat per damage is very similar
* Shield/hull ratio changes very slightly (1.21 -> 1.25)

**Comment by Pointedstick** [comment]
I'd take it. :+1: 

The Vanguard might need some changes to go along with that, or else it will have a huge amount of free space. Maybe another gun port and another gun? It was basically built around cramming 7 Proton Guns into an otherwise almost empty hull.

**Comment by KiLEdEnNis** [comment]
shouldn't be needed, we can upgrade the AM for a heavy AM, maybe get another small reactor, and put a better shield generator in

**Comment by MessyMix** [comment]
I don't know how this'll turn out; I'm just throwing this out there: why don't we make the particle cannon feel a lot more powerful and sniper-y by increasing it's damage  and decreasing the ROF? Gives it an air of authority, separates it further from niche of the Proton Gun, and maintains the balance. It can be the gun you find in games that's, you know, hard hitting, a somewhat hefty load time, but delivers a meaty punch.

I might test this out and see how it goes. Even if it performs similarly to before, it'll give the player a different feel.

**Comment by Nescio0** [comment]
Although they are not great, they are actually quite balanced right now:
* Proton Gun: highest fire rate, highest average damage per second
* Plasma Cannon: nice heat damage, high firing heat, highest shield, poor hull damage per second
* Particle Cannon: pushes back target, highest range, high accuracy, shield to hull damage nearly 1:1, highest hull damage per second
* Lowering their mass or size is a bad idea; these are supposed to be heavy weapons, not something to fit into the smallest fighter

I like them as they are right now, and would prefer to leave them unchanged. I actually use Particle cannons exclusively (because 8 Particle cannons plus 4 Chameleon turrets fit into a Shield Beetle; 8 Ion cannons and 0 turrets don't). I've considered replacing them with Inhibitor cannons (higher range, lower damage, slows down target) or Electron beams (lower range, higher damage, continuous fire), which are significantly smaller. However, neither is unlocked in the early game, thus they make an unfair comparison.

PS The Proton gun is a Syndicate weapon, therefore not supposed to be the best option.

**Comment by Amazinite** [comment]
>Although they are not great, they are actually quite balanced right now:
>PS The Proton gun is a Syndicate weapon, therefore not supposed to be the best option.

Yes, the Proton Gun is meant to be the worst among the three cannons, but the cannons themselves are not particularly good, save for the Plasma Cannon and its heat damage. 
Here are the human guns and their DPS/ton ratios along with their drains (energy + heat required per DPS)

Weapon | DPS/Ton | Drain
---------|----------|--------
Electron Beam | 19.43 | 0.60
Heavy Laser | 17.25 | 0.74
Beam Laser | 16.80 | 0.76
Modified Blaster | 16.67 | 3.55
Blaster | 15.00 | 3.00
Plasma Cannon | 11.73 | 2.39
Proton Gun | 11.73 | 1.71
Particle Cannon | 10.60 | 1.46

As you can see, the cannon weapons bottom out in terms of DPS/ton and are only moderately good in terms of their drains on your ship systems. The human lasers, on the other hand, have the highest DPS/ton of the human weapons AND the lowest drains (i.e. lowest requirements to use). This massive disparity among the effectiveness of human cannons and human lasers is by no means balanced; an Electron Beam is practically four times as good as a Particle Cannon, as it has almost double the DPS/Ton and less than half the drain.

**Comment by tehhowch** [comment]
Compare DPS/ton-px, as range of the weapon surely matters in practice.

**Comment by Pointedstick** [comment]
Accuracy matters too, which is one of the reasons why beam weapons are so good: 100% auto-hit accuracy.

**Comment by Pointedstick** [comment]
Also DPS/ton isn't a measurement that's as applicable as it could be because of the limited number of gun and turret slots on most ships (see https://github.com/endless-sky/endless-sky/issues/3264). If you know you're going to saturate your weapon slots, you look for absolute max DPS, not DPS/ton.

**Comment by Amazinite** [comment]
>Compare DPS * px/ton, as range of the weapon surely matters in practice.

>Accuracy matters too

Accuracy isn't exactly easy to take into account in theory (or at least I haven't found a way to reliably take it into account), but if we want to take range into account by doing (DPS * Range) / ( Mass * 100) [the *100 on the bottom is for the sake of keeping numbers small] we get these numbers:

Weapon | DPS/Ton
---------|----------
Electron Beam | 87.43
Particle Cannon | 79.50
Modified Blaster | 75.00
Heavy Laser | 67.20
Energy Blaster | 63.00
Proton Gun | 61.95
Plasma Cannon | 56.32
Beam Laser | 51.75

The Particle Cannon's massive range redeems itself, but the Proton Gun (and to an extent the Plasma Cannon if we ignore heat damage) is still pitiful. And range is only important as long as the Particle Cannon can fire and the Electron Beam can not. Inside the range of the Electron Beam it's no contest.

>Also DPS/ton isn't a measurement that's as applicable as it could be because of the limited number of gun and turret slots on most ships

In which case we get these numbers for DPS (shield + hull DPS)

Weapon | Mass | DPS
---------|-------|-------
Electron Beam | 21 | 408.00
Particle Cannon | 30 | 328.50
Proton Gun | 28 | 318.00
Plasma Cannon | 25 | 293.33
Heavy Laser | 15 | 252.00
Beam Laser | 8 | 138.00
Modified Blaster | 6 | 100.00
Blaster | 5 | 75.00

No matter how many gun ports you have, the Electron Beam still out damages everything. Two Heavy Lasers also out damages as single Particle Cannon, and 3 Beam Lasers at only 24 tons total does the same. So if gun ports are limited (they usually are) and Electron Beams aren't available and the weapon space is high enough to take it (ship dependent), all Particle Cannons becomes the best choice for DPS.

The sheer number of variables at play does make this difficult to truly show, but a slight buff to the Proton Gun (and for goodness sake, reducing the drain on the blasters as well so they at least have SOME viability early game instead of switching right to lasers) makes sense in my eyes.

**Comment by Nescio0** [comment]
Yes, the electron beam beats everything, but that one is not normally available, and has to be unlocked by a quite long campaign; from game start to electron beam takes much longer than from electron beam to Wanderer sun beam; furthermore, the Hai pulse and ion cannons are readily available, and Remnant weapons can be quickly unlocked; therefore I'd recommend to leave the electron beam out of the comparison and only focus on the default human guns.

> The sheer number of variables at play [...] does make this difficult

Exactly. Every one has its own flavour, characteristics, strengths, and weaknesses; there is no overall best choice, which is why I believe the situation, although not great, is balanced. For each one it could simultaneously be argued it's the best or the worst.
Yes, blasters are worse than lasers, but also smaller and nearly half as cheap; the three Ps are best in damage per slot and worst in damage per mass; they also outrange all blasters, lasers, and turrets, which is important to take into account. Etc.

**Comment by Lineth** [comment]
"remnant weapons can be quickly unlocked"

Not really, no. Not for a new player, certainly.

**Comment by endlesssteve** [comment]
My personal opinion (not that anybody needs to take any notice) is that balancing can be taken too far.
There should be good weapons and bad weapons other wise they're essentially the same and the game gets boring. I would leave the proton gun as a bad weapon, maybe drop the price to reflect this.

**Comment by KiLEdEnNis** [comment]
if ya make a few weapons strong & a few weak players basically get punished if they don't use the strongest ones
what we mean by balancing isn't making them the exact same, it's about making them all viable choices while keeping them unique

**Comment by jafdy** [comment]
@endlesssteve That would be like saying two equally good weapons (a shotgun and a sniper rifle) in an FPS are the same. Being equally good is not the same as being essentially the same.

**Comment by endlesssteve** [comment]
@jafdy  There are way more than 2 weapons here so I don't feel your comparison is valid.
Are all cars produced today equally good? No. In game terms equally good is the same as the same.

but as I said it's my personal opinion. Why do people here always want to argue?

**Comment by Nescio0** [comment]
> "remnant weapons can be quickly unlocked" Not really, no. Not for a new player, certainly.

Well, I might be an exception, but I actually had Hai ships, Remnant technology, and Korath outfits before I discovered the Free Worlds campaign. Anyway, my point was merely to exclude the electron beam from the comparison, and instead focus only on the default human guns.

**Comment by KiLEdEnNis** [comment]
> @jafdy My opinion is my opinion you can have your own and it doesn't have to be the same as mine.
Are all cars produced today equally good?

to explain jafdy's example with your cars: a truck & a racecar; both are good at 1 thing & bad at another

and "Are all cars produced today equally good?" is a real-life thing anyway; in real life we want things to be as good as we can, in games we don't want to make 10% of the weapons clearly the best & 70% trash: in a GAME we want all weapons to be viable choices so players can get anything they like

**Comment by KiLEdEnNis** [comment]
also @Nescio0 new players might not discover the Hai until they finish the FW campaign, then they need to get a key stone & try that wormhole
you might as well say "it's easy to get Coalition tech early; just get a tanky ship, bribe pirates & loot a Raider to get its jump drive"

both things are possible and not that hard for experienced players that know what they're doing, but both are very hard & unknown to new players

**Comment by endless-sky** [comment]
Reducing the size of the Proton Gun isn't reasonable because so many ship load-outs are already based on its current size.

The most interesting option, I think, would be to increase the Proton Gun's range by 100 pixels or more. Because of its inaccuracy, it'd still feel like a completely different weapon than the Particle Cannon - something like a shotgun that does high damage at close quarters but only hits you with part of the spray at its full range.

**Comment by Amazinite** [comment]
* Submunition lifetime: 20 -> 24
  * Range: 528 -> 624 (96 increase)

If anyone's still up for that damage buff... how about we only do a 5.5% increase?
* Submunition hull damage: 8 -> 8.4
  * Hull DPS: 180 -> 189
* Submunition shield damage: 6.6 -> 7
  * Shield DPS: 148.5 -> 157.5

**Comment by Pointedstick** [comment]
>The most interesting option, I think, would be to increase the Proton Gun's range by 100 pixels or more. Because of its inaccuracy, it'd still feel like a completely different weapon than the Particle Cannon - something like a shotgun that does high damage at close quarters but only hits you with part of the spray at its full range.

It's like the Syndicate tried to reverse-engineer the space sniper rifle and accidentally created the space shotgun.

**Comment by Amazinite** [comment]
Is #3315 the "little something" the Proton Gun needs? :)

**Comment by Pointedstick** [comment]
I'd take it!

**Comment by Pointedstick** [comment]
Another something: [a turret version!](https://github.com/endless-sky/endless-sky/pull/3316)

**Comment by Pointedstick** [comment]
I think it's got its little something now.
