### ISSUE TITLE
Missile weapons (most notably human ones) need some tweaking

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3288]
Right now most players don't favor human missile weapons, for a variety of reasons relating to them not being good enough:
- Low _effective_ DPS/ton when taking into consideration asteroids, anti-missile turrets, jamming, missed shots, etc
- Must spam them to be effective; low cost-effectiveness
- Lack of realism and satisfying-ness of individual missile damage profiles (with the exception of Heavy Rockets and some alien missiles); un-fun play style for many
- Near uselessness against alien anti-missile tech; even Hai turrets wreck them (Tier 1.5 human Electron Beam weapons remain competitive for quite a while by contrast)

But in other cases, missiles are actually **too** good:
- Fighters crammed with missiles (especially Wanderer Thunderheads) punch inappropriately above their weight due to the number of missiles they can carry
- Novice players are easily destroyed by missile-armed pirates in the early game, which can be very frustrating
- Torpedoes are inappropriately maneuverable and capable against fast-moving craft, which looks and feels really weird and can frustratingly ruin small ships (see above)

It's a tough nut to crack, but somehow we need to find a way to address both sets of issues.

**Comment by Lineth** [comment]
I agree 100% with almost all your changes. Missiles just **feel** wrong. They should be few, and quite dangerous (and I'm a crap player), not glorified spitballs. My rough-and-tumble guess was double damage, halve capacity and reload (double capacity on racks to make heavy ships appropriately missile-y), and have guided missiles and especially torpedoes ignore asteroids entirely until they lose their lock, at which point anything goes. I'd also reduce the weight of jammers, but possibly also give them an energy cost to make them more appealing as a light-weight alternative to AM turrets.

Just a few thoughts off the top of my head. Missiles absolutely need to be be less spammy and overall lacking in oomph.

**Comment by ghoulavenger** [comment]
My largest complaint with missiles is and will probably remain that they are expended on use, which causes you to restock them that costs money and time. Even if missiles were more boomy, this wouldn't address that complaint. I might be willing to ignore this complaint if there were less options to deal with enemy fleets though -- missiles don't need to be stronger for this to be the case. 

Simple things like capped fleets, or enemy fleets that scale with yours could do this just as easily (which is basically an adaptive difficulty, making your loadouts and strategy the most important things, rather than letting large fleets handle most problems with relative ease). The problem is that this way of design might force players into specific playstyles to adapt to the difficulty, meaning there are a lot more wrong choices than right ones.

**Comment by KiLEdEnNis** [comment]
I'll make a bold proposal that in one way would make missiles more attractive
instead of having to restock in an outfitter, ya get free full reloads on any inhabited planet if said species own said ammo and allow you to have such ammo
for example, any Wanderer world would restock Thunderheads (no other missiles), but only if I'm allowed to purchase its launcher (so not like ya steal a Finisher Pod & get free torpedoes)
pair that with lower ammo capacity in general, and maybe a longer reload

it's quite a big mechanical change (since for example the buying ammo balance factor is gone, ammo gets removed from the outfitter etc.) but I'd really use missiles this way

**Comment by gunqqer** [comment]
Yeah one big reason why I don't use missiles is because the only one I'd ever use is wanderer missiles and the downsides are just too big, I don't want to have to return to wanderer space every time I fight or worry about running out. They just don't have enough consistancy for me to use. Also with escorts, if I set them to frugal they rarely fire, and if I set it to fire they spam them wasting many of them especialy if I have a lot of escorts with missiles. All of the aim for the same target using 10x as many missiles that are needed to compleatly kill the target

**Comment by Pointedstick** [comment]
Re-stocking is probably always going to be an expensive annoyance. The trick is in making missile weapons tactically important and fun enough to use anyway. I bet y'all would keep using Plasma and Sunbeam turrets even if they required ammo. :slightly_smiling_face: 

Here's an idea for Meteors: make then much faster (like, `velocity 14` and `acceleration 2`) in conjunction with reducing `homing` to 2. Higher speed and worse homing make them even worse at turning to track fast-moving targets (such as a new player's small vulnerable ship) and recovering when they miss, but lets them through large ships' anti-missile defenses more often. With that change, it wouldn't be insane to increase the damage and reduce the firing rate, and the slower Sidewinder would become the maneuverable anti-fighter missile of choice that it wants to be deep down inside (if only its mother had encouraged it as a baby missile).

**Comment by KiLEdEnNis** [comment]
> I bet y'all would keep using Plasma and Sunbeam turrets even if they required ammo. :slightly_smiling_face:

nah, I really dislike limited ammo, (even w/ generators, I want as much energy generation as I can so I never really run out)

missiles being expensive ok, but restocking ruins them for players to the point I'd prefer gameplay over realism: restocking any missile weapon at any planet

**Comment by ghoulavenger** [comment]
> I bet y'all would keep using Plasma and Sunbeam turrets even if they required ammo.

Not if there was a reasonable alternative that didn't. I never use plasma turrets either by the way, sunbeams I do.

**Comment by Pointedstick** [comment]
If having to buy missiles is a sticking point, folks might be interested in this idea I opened exactly two years ago: https://github.com/endless-sky/endless-sky/issues/255

**Comment by SirStigII** [comment]
Honestly for gameplay it would be better to restock ammo at any outfitter, even if that breaks realism a bit. I would be way more into missiles on ship if I didn't have to scramble to restock after every big fight.

**Comment by KiLEdEnNis** [comment]
I'm not sure how 255 should be implemented at all, it'd require quite some coding, and how will ya even apply that feature? does it happen automatically? manually? if so, where?
despite that, I find the idea of creating ammo (mid-flight???) in whatever way quite good, maybe somewhere in the I-screen ya have an ammo creation menu, the ammo itself could automatically go into the cargo hold after

**Comment by MessyMix** [comment]
Here's a suggestion I threw out to the Discord, and they seemed to like it:

Missiles give the impression that they aren't powerful, since they pretty much just swim around in space.
Why don't we give them acceleration, so that their velocity when fired is very low, and the missiles accelerated towards their target, increasing their final velocity? This would really give the player the impression that missiles are fast and dangerous.

This would serve to buff missiles, since they are exposed to AM for a shorter time—at least once they are up to speed; i.e. when fired from an optimal range.
It would also counter spamming missiles at short range, since they are travelling very slowly and have lots of time for AM to get shot down.

I think that a change like this will make missiles feel a lot more like missiles: you release, and they propel themselves to high speeds. Dodging should remain mostly the same; although the missiles are travelling faster, their turning radius will be much larger, and if you move out of the way fast enough, they'll have trouble hitting you.

For this change, I'm mostly talking about Meteors and Sidewinders, since that's how normal human missiles behave, and how they _should_ behave. [https://www.youtube.com/watch?v=yMkr_3_CZO4]
I think it might also work for Korath Piercers and Thunderheads.

I don't know how this change will turn out, but missiles will seem a lot more substantial afterwards, I think.

**Comment by Pointedstick** [comment]
I've been experimenting with the same thing and like the outcome. It both makes missiles feel more missile-like and also helps them get through anti-missile fire a bit better.

The breakdown I like is making the meteor accelerate to a much higher speed than today (in line with its name!) but reducing maneuverability. That makes it better against capital ships, but worse against fast-moving targets, against which the sidewinder becomes preferred.

I've also tried drastically increasing the `hit force`, which has a really satisfying outcome. With that, missiles push back small targets on impact, visually reducing the "insignificant pinprick" effect. There's no change to the damage or speed... they just _look_ like they hit with some punch. It works really well with the better sounds IMHO. I've submitted a PR for it: https://github.com/endless-sky/endless-sky/pull/3294

**Comment by MessyMix** [comment]
Nice!! Are you planning to do an acceleration / velocity PR as well?

**Comment by jafdy** [comment]
Pirates don't use sidewinders so this won't harm new players once they stop flying strait at the pirates.

**Comment by Pointedstick** [comment]
> Nice!! Are you planning to do an acceleration / velocity PR as well?

Yeah, I changed Meteor acceleration in https://github.com/endless-sky/endless-sky/pull/3278

I thought that only Meteors needed the change, and it now makes them feel very distinct, and not just worse Sidewinders.

**Comment by Pointedstick** [comment]
Took another crack at this in https://github.com/endless-sky/endless-sky/pull/3866/

**Comment by Pointedstick** [comment]
From my perspective, this is done. I think human missiles are now just about right! There's always room for more tweaking of course but I don't think any major changes are needed anymore.
