### ISSUE TITLE
We got 99 problems but money ain't one

### ISSUE THREAD

**Issue by Oeleo** [endless-sky/endless-sky#329]
Hello,
We talked since a few time about the ease to make money in this wonderful game, but I think that *"a picture is worth a thousand word"* so I'll give you an equivalent of 2000 words :
![capture d ecran 11](https://cloud.githubusercontent.com/assets/15967612/11461829/12ca632c-970b-11e5-9aa5-00ab4902c996.png)
![capture d ecran 12](https://cloud.githubusercontent.com/assets/15967612/11461830/13fa6e18-970b-11e5-92bf-3aff54f05d97.png)
I show you that because some people who don't know strategy to make money fastly could be hesitant for enhancement that will make harder the fact of making money. But I hope that I showed you that making money is **really** easy in the current state of the game, and that we need to do something about that, to debate and find a solution together. I let you several saves as proof.

[How Much.txt](https://github.com/endless-sky/endless-sky/files/46841/How.Much.txt)
[How Much~3013-11-16.txt](https://github.com/endless-sky/endless-sky/files/46842/How.Much.3013-11-16.txt)
[How Much~3013-12-02.txt](https://github.com/endless-sky/endless-sky/files/46843/How.Much.3013-12-02.txt)
[How Much~3014-01-12.txt](https://github.com/endless-sky/endless-sky/files/46844/How.Much.3014-01-12.txt)
[How Much~3014-01-24.txt](https://github.com/endless-sky/endless-sky/files/46845/How.Much.3014-01-24.txt)
[How Much~3014-03-13.txt](https://github.com/endless-sky/endless-sky/files/46846/How.Much.3014-03-13.txt)
[How Much~3014-04-16.txt](https://github.com/endless-sky/endless-sky/files/46847/How.Much.3014-04-16.txt)
[How Much~3014-05-19.txt](https://github.com/endless-sky/endless-sky/files/46848/How.Much.3014-05-19.txt)
[How Much~3014-06-30.txt](https://github.com/endless-sky/endless-sky/files/46849/How.Much.3014-06-30.txt)
[How Much~3014-07-07.txt](https://github.com/endless-sky/endless-sky/files/46850/How.Much.3014-07-07.txt)
[How Much~3014-07-17.txt](https://github.com/endless-sky/endless-sky/files/46851/How.Much.3014-07-17.txt)

**Comment by Pointedstick** [comment]
Escort jobs are one offender. They are ridiculously easy ways to get a lot of money very quickly in the early game. You never have to travel far and once you fight off the initial pirate ship or two, it's smooth sailing.

**Comment by endless-sky** [comment]
This is pretty clear evidence that plundering is overpowered; the suggestion to not allow plundering power sources could help with that, although once you can disable Quarg ships you can basically get infinite money quite quickly.

Another option would be to add a risk that an item you try to plunder will be damaged as you try to yank it out, and have the chance of damaging it be proportional to its price per ton. Neither of those solutions would keep you from just capturing the ship outright, but I'm guessing most of your earnings here were from plunder, not capture.

**Comment by Pointedstick** [comment]
I like the idea of having to fight the crew for "internal" outfits like reactors.

**Comment by airtroop392** [comment]
"Damaged" salvage, among other additions or revamps of the salvage system, was mentioned heavily in #325. A lot of people on the Steam forums often point to Quarg ships as a way to make a billion credits in under an hour, and, in stark contrast to the escort missions, which are all under 1 million per job, I feel like Quarg technology should not be able to be sold at all (due to its complexity and alien origins, or simply because most people wouldn't ever need one, and no merchant would ever take it).

**Comment by thenerdfreak** [comment]
I like the idea of not being able to sell quarg outfits. It makes since with the "intrusion countermeasures" item that states that no person would want to buy stolen quarg technology

**Comment by Oeleo** [comment]
Yes but there is always a problem which is that the Quarg's stuff is about 8x more powerful (skylance 3000 dps, for 60 tons, Plasma turret 420 dps for 60 tons), with one ship with Quarg stuff you can fight a small fleet, so even if Quarg outfit couldn't be sellable, when you will begin to equiped your ships with it, you will instantly kill all the ships on your way in several seconds. That's why I proposed to reduce their power, and to do something more like the other Alien, better than human technology but you can still be outnumbered. #267

In this save I plundered almost only the Quarg, when I had ~40M (with ~25 ships captured and sold) I took a credit of 80M, bought 20 Firebirds and took my first Quarg's stuff. After that I took >100 Clippers and farmed the Quarg.
But if we forgot the plundering, capture of ship seem to me already easy. I hate to say that because I know that a lot of people worked on that, but missions and playing like a merchant is useless right now (I don't remember where, but we already talked about that in several issues). I do them for fun but that's 0.1% of my earnings ... I think that when you reach a certain amount of money, making money have to be harder to extend the life of the game. That's why we talked about a system of tax, which would be for the richest only (or almost inexistant when you begin) #275. I understand that tax isn't fun, but maybe that it could give you something (reputation, any ideas ?)
Of course I find that games are often too easy that's why i'm not an example, but **to resume**, only to my opinion :
1-Transporting and missions need to be more lucrative, and therfore we could have missions for high level, with ~1M of benefit (or more if we pay tax)
2-Capturing ships is good as it is if ->1
3-Plundering outfit need to be harder and less lucrative, I like the idea of #325, especially the fact that outfit are destroy randomly, it seems realistic and a good game play enhancement.

**Comment by Man-animal** [comment]
By the time you can actually disable a Quarg ship you could also roll through the campaign.

**Comment by endless-sky** [comment]
Note that to make it impossible to sell Quarg outfits, it would also need to be impossible to sell a ship that has Quarg outfits in them. And, if you had a Quarg outfit in cargo, the only way to keep it from taking up cargo space would be to install it. So, I don't think that's a very practical solution.

**Comment by jafdy** [comment]
So you would need a dump type function. or make quarg outfits almost worthless.

**Comment by Oeleo** [comment]
@Man-animal That's what we said me but I disable the first Quarg ship in ~3 hours, so that's an other problem yes. By the way I remembered that, I found sad that it was not yet exploited maybe it could be use for the Quarg stuff : * "" If the cargo is marked as "illegal," governments that care about such things will levy the given fine against you if you are caught carrying this cargo. If the fine is negative, being caught with this cargo while in flight is counted as an "atrocity" (the government that catches you immediately becomes your enemy, no matter how good your reputation was previously), and if you are caught in a spaceport with the cargo the result is a death sentence (game over). "" *

**Comment by Tufton** [comment]
I guess we really need to be asking what the Quarg represent here.  Are
they just an end-game treat to get super powerful items or are they the
next level of progression in ship power post-campaign?  If there were a
large Quarg area opened, would we need Quarg gear to survive hostile/rogue
Quarg?  The Quarg appear to me to, right now, be inherently unbalanced by
design.  The Skylance, Anti-missile, shield generator, and battery (and the
anti-boarding outfit I guess but I'm not really counting that) are all best
in slot items by miles, regardless of the price point.  I can mount 4
skylances on a single kestrel, I mean come on.  The thrusters are all
garbage (like the korath!) and then we've seen jump drives before.

If we treat Quarg as an end-game easter egg, then the money isn't really an
issue because by that point you are probably filthy rich.  If we treat them
as being another level in power progression over the course of a
long-campaign, they need to be balanced or walled off.

Maybe add a license for Quarg items (selling or mounting) that can only be
unlocked through some long and difficult Quarg questline that appears after
the chapter 1 storyline has been resolved.  Second thought, add a unique
item that is required to board/loot a Quarg ship that you cannot get until
late game. (Quarg Anti-Boarding Nullification Array...whatever).

**Comment by egilburg** [comment]
I kinda think plundering should not be possible at all without first capturing the ship.

And if you then answer "whats the point of plundering then if you can just steal the ship itself for more cash", I'd answer that capturing the ship is only half the challenge - the other half is to tow it back safely to port, especially if you captured it in a hostile sector.

So I think it's quite balanced to require a capture before either plunder or tow - and then decide whether you want to bother towing it back, or just plunder it for components where it stands.

Perhaps this should be combined with a small chance of enemy ships dropping a component or two upon destruction - but that would be much rarer than a guaranteed steal on plunder - for obvious reasons of components being damaged when a ship is destroyed. So if you are unable to steal and plunder a ship, you can still try capturing components from destruction - but that would take much longer and be less profitable.

(P.S. as a separate point, repairing hull points should cost money, the exact price depending on how friendly the faction is to you. It's too easy to go for random looting knowing that you have nothing to lose. If you had to repair your ship and your captured ships for $$$, you'd be more careful picking your battles).

**Comment by thenerdfreak** [comment]
Not necessarily making it absolutely untradable, just making it worthless (like the intrusion countermeasures)

**Comment by Wrzlprnft** [comment]
I really like the ideas coming up here.
"... One of the fuel tanks has a human-style connector on it, but there are a dozen other connectors branching off from it as well...."
I would prefer a progress of Loot-able stuff with the story, like[Warning: Spoiler] when the syndicate tells the player about the jump drive, he/she/it/other could gain access to loot jumpdrives.

**Comment by Man-animal** [comment]
" like[Warning: Spoiler] when the syndicate tells the player about the jump drive, he/she/it/other could gain access to loot jumpdrives."

Why?  The player presumably knows about the existence of jump drives; their existence is no secret, and it's even implied that jump drives have been looted on previous occasions.  If a player can disable a Korath raider or Quarg ship, why shouldn't they get a jump drive out of it?

This seems like gating for no reason other than wanting to force the player into a linear progression.

**Comment by thenerdfreak** [comment]
Can you even get a jump drive before the mission in which it is given to you? i've waited int he northern areas near korath territory for ages and never seen one before finishing the mission, and quargs were almost impossible before i got a jumpdrive

**Comment by Man-animal** [comment]
Korath raiders are rare outside of their own systems but they do spawn on occasion, and you can get a jump drive from them.  You could get one before even starting the campaign.

**Comment by thenerdfreak** [comment]
@Man-animal  this is what I was looking for, thanks, plan on fully outfitting my fleet before starting campaign (for reasons)

**Comment by Wrzlprnft** [comment]
Well, it took me a while till i recognized, that jump drives even exist.
Since there is no jump-drive-loot-tourism amongst the npcs in the game, i wonder where the player's crew got the knowledge how to 
a) loot and
b) install and
c) use jumpdrives
since it's all alien technology, without a manual.
aaaand there is already some kind of gating... i mean... plasmas, dreadnoughts, (ok i do hardly use them), the cloaking device (i do like this thing, but since you can't buy it it doesn't count here). The Hai-equipment litterally hase a gate you have to find before you can buy it (yeah except with jumpdrives).

Of course, if it's not done right, it's only annoying, but look at the thought behind it: our problem is the plundering of endgame-stuff, like quarg-ships. It would prevent the player from doing so early on, but knowledge will come, and in the end, there is no difference. Besides, there would be space for more story (less railroad from a to b and back again).

And if you are still worried about early jump drives...
What could be a better way to proof yourself to be worthy to get a promotion within the syndicate ranks?
Maybe you are the one, if you choose syndicate, who looted the jumpdrives they have?
Or a syndicate manager bet his (modified) star queen that with money you can buy everything, and his counterpart said you couldn't buy jumpdrives. So the manager hires you, you have to carry a (bankrupt) specialist with you, and that's it.

if you don't want to play story, maybe we need, a "no-story-space-truck-simulation-mode" ;)

**Comment by Wrzlprnft** [comment]
@Tufton i just managed to mount 2 skylances on a kestrel before i had real energy/heat issues, and had no cargos space left.

**Comment by Tufton** [comment]
use mass expansions, drop your old shields for the quarg generator and you
will gain a lot of heat dispersion from ditching the hai shields (or outfit
space from ditching human shields) and get korath heat shunts if you have
heat issues. Liquid helium cooling is also fairly cost effective.  if you
have energy issues im running teknel and double teknel reactors on
bactrians and kestrels with the quarg battery (30000 energy storage for 50
outfit dear god) and can fire 3-4 skylances for extended periods of time.
I don't have to have them up constantly because of the insane dps.
Obviously you have to build your ship around them, but when they are as
powerful as they are it is pretty much always worth it.  Hell, I even run
an anti missile battery AND 3 skylances on my flagship (bactrian) and thats
with saving ~370 cargo for boarding plus a quarg shield gen and various
other knickknacks.  Switching to atomic engines will also give you a lot of
extra outfit space if you havent already.

**Comment by Wrzlprnft** [comment]
ah ok the batterys, forgot about them

**Comment by LeadProphet** [comment]
Licenses should need renewal fees.

**Comment by guillochon** [comment]
I also think that the removal of any outfit should require at least one round of fighting with the crew of the ship. That would give looting a cost, especially with the death benefits being as punitive as they are.

**Comment by LeadProphet** [comment]
Guillochon, I disagree that ANY item should require fighitng. There are definitely items like fuel pods which it seems likely you'd be able to strip without going inside the ship. What I think would be more interesting would be that components would be randomly damaged according to the fighting that took place. 

Really, the big reason it's so easy to make money in this game is because you don't have to pay for any kind of maintenance other than crew, which can be strategically mitigated. Fuel, repairs, licenses, etc are free.

**Comment by Pointedstick** [comment]
And outfits and ships can be sold for full market value, and there are no taxes, and escort jobs pay *really* well.

**Comment by guillochon** [comment]
@LeadProphet Couldn't the crew get into spacesuits and fight outside if they are being stripped of their systems? I also think treating the taking of all systems the same is better from a gameplay standpoint. 

The problem I have with damaging systems is that any disabled ship could be boarded and repaired to full functionality, implying the systems are repairable and should always be lootable. So it would require the outfit itself to have a "damaged" state.

**Comment by thenerdfreak** [comment]
Add a % damage repair to larger ships (starting at light warships) maybe like, if the warship costs 10 million, a full repair would cost 1-3 million

**Comment by Pointedstick** [comment]
Yeah, making hull damage cost money to repair seems like it would be a good way to impose a new cost on rich players but be relatively negligible for starting players.

**Comment by LeadProphet** [comment]
@guillochon you make good points. I mean, it's unreasonable to suppose anyone in their right mind would don a spacesuit and go outside when the ship that just disabled you has its massive ship-based guns trained on you, but the rest of what you say makes sense. I guess I'm just not sure that making it only possible to loot by fighting is a good idea. The problem with that approach is that you pretty well eradicate any money-making prospects for small fightercraft with low crew counts.

**Comment by Tufton** [comment]
I mean the end game death benefits are pretty steep when you have a nice
ship and you are trying to capture a nice ship.  Sometimes I see 10mil crew
death benefits on a 15mil ship.  Taking outfits is pretty profitable of
course but there is probably a better way to mitigate that issue.  Maybe
only make 1/2 the outfits available to loot without fighting the crew?  I'm
worried if we add too many ticky tacky costs and %s and interest it's going
to start feeling more like Accounting Simulator 2016 than Endless Sky.  The
mortgage system is already starting to get a little too real for me lol.
Sure money management is important, but unless we create a slick interface
for dealing with it all I think it may end up feeling like a chore.

**Comment by thenerdfreak** [comment]
In all, this is the way I see it: The universe is only 1/5th explored so far. 1 Billion may be child's pocketmoney to other alien races. There will, obviously, be races with weapons and ships that have triple the capabilities of the Quarg. Human money will only be able to get you so far once the whole game is released.

**Comment by egilburg** [comment]
Cost of repair and refuel
---

If we introduce costs which currently are free (repairs, refuel, etc) we could balance the game by reducing initial loan interest and death benefits. Spread out the costs rather than only make one aspect expensive. 

For slightly less brutal gameplay, we can make it so landing on any planet will auto repair and refuel you and your fleet for free to 25% health and 25% fuel, for any ships below that limit, to prevent you from being stranded. Anything above that, though, you need to pay for (and add quick "repair all" and "refuel all" buttons to reduce manual clicking - and/or add game preference "auto repair" and "auto refuel" if money permits).

Ship and outfit prices
---

I really like the fact ships and outfits are bought and sold at same price and without flux; this allows you to experiment with loadouts without worrying about losing money. I realize it's "less realistic" but I think it's more fun - buying and selling ships and outfits should not be used as a means of making (or losing) money. Leave the cargo trading for that.

What I do think needs to happen is that repairs should be proportional to the cost of the ship's hull (e.g. a 50% damaged ship sells for 50% of a 100% ship, not counting outfit cost), and this also factors into ship sale price. So if you disable and capture a ship, which involves damaging it to 25% health, you'd only be able to sell it for 25% of the full price. This way you can experiment with buying/selling ships for free (as you'd buy and sell them undamaged), but reduce how quickly you can make profit by capturing and selling enemy ships as those would be damaged.

**Comment by LeadProphet** [comment]
A lot of this sounds like something that should be integrated into various difficulty levels or game options. I'm sensing a lot of difference in skill level and playstyle here.

**Comment by egilburg** [comment]
If game has difficulty levels, they should adjust modifier % uniformly on various game aspects - e.g. reduce enemy damage, increase your damage, decrease loan%, etc.

But game difficulty shouldn't completely add or remove a mechanic - it makes it too hard to balance and would lead to different game experience independent of your skill level.

**Comment by LeadProphet** [comment]
@egilburg I don't really understand the impetus to have a unified game experience. It's not even a multiplayer game. There's no reason at all not to include mutators, difficulty levels, mods, skinpacks, etc.

One of the most popular things about the original Escape Velocity series was the ability to mod it to be like Star Wars, but not everyone wanted that. The two different camps did not lessen the popularity or effectiveness of the gameplay.

**Comment by egilburg** [comment]
Mods are different - if you mod the game you are free to make any and all changes you want.

But the base game should be the same for everyone, it's not the game author's responsibility to maintain mods.

**Comment by Oeleo** [comment]
@LeadProphet I think you are sadly true, I already think of something like an "hardcore mode"
@egilburg Yes that seem a nice idea too if the first is too hard, I think that we'll  need it. Like that the game could be still a challenge for "old players" and could be something like the actual game for new players.

**Comment by LeadProphet** [comment]
@edilburg how would difficulty levels make the game different for different people? Everyone would have access to the same difficulty levels. So what if some people play on easy and others on hard? That would hardly hurt the community - only make it more inclusive.

**Comment by egilburg** [comment]
@LeadProphet I'm not opposed to difficulty levels, only to when they cause different mechanics.

A difficulty level which is balanced to be easier than another - but still provide the same type of gameplay - is OK. A difficulty level which turns on or off an entire aspect of the game is best left to mods and not the base game.

**Comment by LeadProphet** [comment]
OK, at least now I see where you're coming from. I'm not sure I agree, but I understand. I'm very happy that this game is open source AND on steam, so a vibrant mod community is virtually guaranteed.

**Comment by egilburg** [comment]
I'll expand on my statement a bit - as I mentioned, it's OK to have "metagame" options like "hardcore" which is permadeath. It's also OK to have special "challenges" designed to be extra hard, as long as they are seen exactly as a "challenge" rather than a normal difficulty level.

Consider XCOM - it has "difficulty levels" which adjust the same gameplay, and then it has "second wave" challenges on top for those who want to go the extra mile - but it's clear those are special challenges and may not be as balanced or holistic as playing the base game, and it's clear players shouldn't complain they can't beat a "challenge" because it's not designed to be fair to begin with.

---

However, my concern is when players ask devs to provide option to turn on or off entire aspects of _base_ gameplay simply because they don't like them, with common argument "why don't you make it an option so everyone chooses for themselves?"

While this is a well-intentioned idea, trying to implement every such request as an option makes a game that's too fractured across multiple options, making base gameplay incoherent and hard to balance. And this is why I'm saying that custom stuff is best left to mods, on top of a coherent base game which makes modding itself easy.

Relevant xkcd comic: https://xkcd.com/1172/

**Comment by Man-animal** [comment]
Honestly this entire 'problem' comes down to going out of your way to break a single player game in a way most normal players never would do, and then claiming it's a balance issue that needs to be fixed.

I saw a video of someone completing Morrowind, start to finish, in three minutes.  Most people spend dozens if not hundreds of hours to do the same.  And both are completely acceptable ways to play.  This isn't an MMO, you don't need to ruthlessly hunt down every little imbalance and obscure advantage and stomp them into the dirt.

**Comment by thenerdfreak** [comment]
tbh the imbalance is one of the main reasons this game is what it is. Fun. Nobody likes grinding for hours to get the next ship.

**Comment by egilburg** [comment]
>tbh the imbalance is one of the main reasons this game is what it is. Fun. Nobody likes grinding for hours to get the next ship.

Wouldn't a game where you need to grind for hours mean it's unbalanecd rather than balanced?

**Comment by Tufton** [comment]
I think if we had to grind for hours for each upgrade we could add
micro-transactions and become a mobile game cash grab lol.  "Sorry, your
pilot license has expired today! Share this with a friend on Facebook to
get an extra license!  Spend 400 Skygems to boost your license regen!"

**Comment by Oeleo** [comment]
It depends of what you like. I like challenge in every games. This game is really great, especially for the story, but without challenge I find every game boring, but that's just a different point of view.
@Man-animal I'm sure that in morrowind the man use glitch to pass quests, and he wasn't invincible, level 50 etc... Here I played *without one glitch exploit* just like a normal player could play. I just take some ships, and after plundered the Quargs. I don't understand why some player can't understand that  a weapon which is 8x more powerful need to be unlootable. I know that I'm not representative of the majority of the player, but I know an other thing, if you let it like that, most of the player will complain because they are in Godmode after that they loot some Quarg's ship.
That's a question of opinion, I don't ask that the game become really hard, just not too easy. And yes if possible a way to change the global difficulty, like that everybody is happy, and play the game like he want. It's now in most of the game, a way to change it like in morrowind could be cool.

**Comment by thenerdfreak** [comment]
Oeleo the quargs won't be the strongest thing in the universe, and their weapons will be meager when all of the aliens are released, they are the stepping stone to alien tech imo

**Comment by Man-animal** [comment]
@Oeleo "That's a question of opinion, I don't ask that the game become really hard, just not too easy."

Then you're missing the forest for the trees, because if you have the resources to kill Quarg, *nothing else* in the current game is going to be a challenge... except for possibly capital system defense fleets, and frankly, the tribute system is tertiary at best.

I do think that income generation from looting is probably too high, but the idea that the Quarg weapons - used by the strongest NPCs in the game - present a balance issue is silly.  To use another analogy from other games, it's like how in some old Final Fantasy games you could kill optional superbosses for an overpowered weapon or item.  Does it make the rest of the game easier?  Yes.  But it's kind of irrelevant, because you already killed the strongest enemy in the game without it.

**Comment by Oeleo** [comment]
It depends of what the other species will have as stuff, but now I think that be able to kill the stronger enemies in the game in 3 hours is unbalanced. The tribute system isn't a fundamental aspect of the game but that's the only major difficulty of the game for now, and having Quarg weapons make it too easy too. I'm ok if they are like "optional superbosses" (by the way that would be a great idea) but in this case their ship need to be much more powerful (and since their ship aren't takable, we could do something really overpowered), like that the players could have the time to change human stuff, for Quarg/Hai/Pug stuff, become more powerful and after at least dozens of hours they might have access to this stuff and be able to fight the new species.

**Comment by thenerdfreak** [comment]
you CAN kill them in three hours, but it requires a speedrun. If you're just laidback playing the mission it'll take more along the lines of 10 hours to finish the story line and have enough Korath outfitted ships to do it. and their ships are able to be captured, it just takes way too much illegal nerve gas, a ship outfitted with the lightest thrusters, no weaponry, no shield, very little power generation, (barely enough to keep it moving with said tiny thrusters) and the ship itself isn't really worth capturing (its shields are really the only good thing about it, besides in-born energy generation)

**Comment by thenerdfreak** [comment]
OH and I forgot to mention. You have to pray to the RNG God that your capture will be the 1-150 or so chance that it'll actually work (this requires using the mega defense thing using a ton of korath Intrusion Countermeasures)

**Comment by frameworld** [comment]
I support the idea of damaged ships and outfits cost cr to repair before being sold.
* Maybe some can soon purchase cheap/heavy hull plating equipment that gets damaged before the real hull gets damaged.

But if you restore a starting-freighter to 25% fuel, that would be 75 fuel, less than 1 jump.
* 3 jumps are minimum. Maybe 25% above 3 jumps?
* Fuel doesn't cost anything if you can harvest it that easily with ram-scopes.

**Comment by LeadProphet** [comment]
If fuel is really so easy to come by, then we need to rewrite a substantial
amount of the flavor text.

**Comment by Oeleo** [comment]
@thenerdfreak Sorry that's because of my bad english I didn't want to mean "take" the ship but just plundered his outfit. No I actually can't take a Quarg ship, I even didn't know that it is possible in beta

**Comment by Impurethinker** [comment]
I haven't gotten this far into the game to worry about unlimited money, but if the alien Quarg tech is the problem, may I propose another solution?

Make is so that all (or some) the alien tech is "lo-jacked" and constantly phoning home to the original owners. Like some sort of subspace beacon thing. Undetectable and untraceable by Human technology. We have problems with this sort of thing today with smart phones and Google ads, can you possible image stolen future alien tech?

And you could do a lot with this premise. You could give different weights to different types of systems. The higher the more interested the Quarg would be in stepping in and doing something about it. Maybe they by come and simply blow you away. Maybe they'll offer you a trade first, like they repo the 'good' stuff and install some 'junk' (read slightly better then normal human tech) to replace it. Maybe if you have such a powerful fleet (somehow, given all the problems you'd have before hand with the aliens) they just bring in the 'Enforcement' fleet and you die in a blaze of glory.

There has to be a reason why no sane Human powers have stolen much Quarg technology before now, right? The player couldn't have been the first guy to be like "Hey why not steal the alien stuff and be invincible yo!"

**Comment by frameworld** [comment]
The jump drive you get given in the Free Worlds mission required the effort of a large fraction of known space.

It could require Hai-shielding tech and their guns (a bit better than human ones in some aspects). Few humans know Hai-space according to what you hear in the first-contact dialogue.

**Comment by johndh** [comment]
What about giving some ships self-destruct mechanisms?  When you try to board, they detonate a bomb for massive damage, ruining anything you might have looted from them.  Or maybe some aliens might kamikaze as soon as their shields go down.  These could work especially well if there's a lore-related reason why they might not value their own lives very highly (hive mind, robots, etc.).

As far as ideas that have already been mentioned, making the player pay for repairs seems like most direct way to limit the income from boarding.  It's also very adjustable, since you can change the damage rate or the cost pretty easily whenever necessary for balance.

**Comment by thenerdfreak** [comment]
That could work johndh, and you could also make it that things with the EMP effect disable that so that they're still lootable, just requires you to use a certain type of weapon to loot them (a type that may not be the best you can put on that ship)

**Comment by endless-sky** [comment]
Self-destruct is supported, but I haven't made use of it yet: e6e16db. I intended it for exactly that sort of situation: making a ship that cannot be boarded, but in a more evil way than the "never disabled" flag.

**Comment by thenerdfreak** [comment]
That is extremely evil D: all ships that exist, save your ship that taunts me occasionally, should be boardable xD

**Comment by zig158** [comment]
I feel that the price curve of ships/equipment is not steep enough. It is very easy to go from a Star Barge to a Freighter then to a Mule/Bulk Freighter/Bactrian. Once the player has put a few hours into the game, money is no longer a differentiator in ship selection.

On a side note, I think making repairs and fuel cost money is a step in the right direction. Making larger ships cost more to refuel would also help make small/medium sized ships useful.

**Comment by Impurethinker** [comment]
Making the game even more grindy for traders is probably not going to do any favors for it.

**Comment by thenerdfreak** [comment]
I went from a sparrow to a corvette in less than ten minutes. From a corvette to a leviathan in just ten minutes after that. Everything is easy to get money in, so it's fairly balanced.

**Comment by DingusShingleton** [comment]
@zig158 "Making larger ships cost more to refuel would also help make small/medium sized ships useful."

But then that begs the question why a 2000 ton bactrian uses the same amount of fuel as a 175 ton sparrow. Both ships consume 100 units of fuel using a hyperdrive, so clearly whatever mechanism the hyperdrive utilizes is irrespective of mass. Therefore charging different rates for different sizes makes little sense.

Although now that I think about it, the fact that by default a sparrow carries 300 units of fuel, while a bactrian carries 700, when the bactrian is 10 times the mass, also is interesting. If you did link stock fuel reserve to the size of the ship, you could also then have cost per jump scale with mass--- you know what, I think it's probably fine as it is.

**Comment by Oeleo** [comment]
I'm sorry, but I actually finished all the actual missions with 10 warships with various aliens technology, and sometimes I lost a ship or even a battle in aliens spaces since I drop all of my Quarg's outfit. The game are much, much more balanced without the Quarg's outfit, maybe that the Quarg's ship need to be impossible to disabled or something like that, but I maintain that the game is much more fun without them. Maybe that in several months there will be aliens as powerful, but before finishing the main story I think that they need to be impossible to plundered. And an other thing, without the Quarg's outfit the non-Bactrian warships become intersting again because the outfit space isn't the only thing that is intersting, while with the Quarg outfit you need to have 2 ~140 mass reactors and it's much more harder to put in the other warships.

**Comment by Xcelcio** [comment]
Endless Sky is an open ended sandbox, and if one took the time to grind and be almighty before starting the story simple just to cruise the main story, it is his choice, and that is what is wonderful about this type of game.

I do actually agree the whole plundering system is right now slightly overpowered, some good suggestions about plunder damage, self destruct, etc, and such are already mentioned above, I'm sure somewhere along the line, the game will be more polished and balanced.

BUT, please, please, please do not add artificial 'gatings';
"before finishing the main story I think that they need to be impossible to plundered"
This is just bad practice in gaming.
Remember THAT tree in Cerulean city? Or an npc that for no reason whatsoever blocks you from entering some dungeon?

Please don't do go down that road. It ruins the open ended spirit and enforces linearity.

-----

tl;dr
balancing is fine (make it harder/less rewarding plunder/etc,etc)
gating is not

**Comment by lehgogh** [comment]
One idea for balancing is to make ships depreciate 10-15% as soon as they leave the planet with it. (Buying and immediately selling a ship before you leave gives no penalty.) This would make the sale of entire ships slightly less profitable.

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.

**Comment by LeadProphet** [comment]
That was unwise.
