### ISSUE TITLE
Possible Wanderer mission balance issues

### ISSUE THREAD

**Issue by SirStigII** [endless-sky/endless-sky#3332]
Unless I'm mistaken, all missions should be able to be completed in a single (non-Arfecta) warship, but in the Sestor missions it seems like at least several player ships are required if using the current strongest ships accessable to the player (Hurricane or Derecho). The innitial battle goes okay, but there is a Sestor carrier fleet that jumps in and overwhelms the Wanderers, and the Wanderer fleet only has flycatcher reinforcments. Played two different pilots to double check that nothing was wrong with my pilot file. Using a Hurricane or Derecho the best I could do was get the Sestor down to 5 ships, at which point I couldn't take them straight up without dying, and I couldn't split them up any more. Could someone else double check my findings and/or confirm that it should  or shouldn't be possible?

**Comment by tehhowch** [comment]
(Share your build)

**Comment by SirStigII** [comment]
ship Hurricane
	name "Tears in Rain"
	sprite ship/hurricane
	attributes
		category "Heavy Warship"
		cost 39100000
		bunks 117
		"cargo space" 98
		drag 11.9
		"engine capacity" 140
		"fuel capacity" 500
		"gun ports" 6
		"heat dissipation" 0.55
		hull 46500
		mass 770
		"outfit space" 960
		"required crew" 76
		shields 72400
		"turret mounts" 5
		"weapon capacity" 428
	outfits
		"Cooling Module" 2
		"Outfits Expansion" 4
		"Jump Drive"
		"Cloaking Device"
		Flamethrower 2
		"Fuel Pod" 3
		"Korath Fire-Lance" 2
		"Large Heat Shunt"
		"Thruster (Planetary Class)"
		"Steering (Planetary Class)"
		"Systems Core (Large)"
		"Wanderer Ramscoop" 2
		"Point Defense Turret"
		"White Sun Reactor"
		"Dual Sunbeam Turret" 4
		"Blue Sun Reactor"
	crew 84
	fuel 800
	shields 72400
	hull 46500
	position 217.07858 -173.53808
	engine -23 181 1
	engine 23 181 1
	gun -68 5 "Korath Fire-Lance"
	gun 68 5 "Korath Fire-Lance"
	gun -85 21 Flamethrower
	gun 85 21 Flamethrower
	gun -62 32
	gun 62 32
	turret -27 -80 "Dual Sunbeam Turret"
	turret 27 -80 "Dual Sunbeam Turret"
	turret 0 -33 "Point Defense Turret"
	turret -39 140 "Dual Sunbeam Turret"
	turret 39 140 "Dual Sunbeam Turret"
	explode "small explosion" 20
	explode "large explosion" 70
	explode "medium explosion" 80
	explode "huge explosion" 30
	"final explode" "final explosion large" 1
	system Solifar
	planet "Desi Seledrak"
got real close with this build.

**Comment by tehhowch** [comment]
use \``` to wrap "code"
ship & outfits is all that's needed ;)

**Comment by SirStigII** [comment]
basically it comes down to me soloing the last 10-15 ships, and the detainers make it too easy to get mobbed

**Comment by jafdy** [comment]
I think the requirement is that it should be doable, if not easy. Because you always have the option of simply getting a fleet. 
In the future it is not unlikely that you will be able to get ships a tier or more above where you are at making the missions much easier.
I for one do think we need an easier mode for the story (your side will win most of the time without your intervention). It would let people new to the game experience the story without needing to be a good pilot of have mountains of cash (older players will have both), if it said something like "would you like to play easy mode, reducing the difficulty of story missions" then it would also let everyone know that there is a story (a thing lots of people miss).

**Comment by SirStigII** [comment]
That might be enough, I don't have a problem with the difficulty, more the change in difficulty from doing FW with tier 1 tech vs wanderer in tier 2 tech

**Comment by Amazinite** [comment]
Reference: #2054
>"The [initial] battle"

Mission names would be preferable.

**Comment by SirStigII** [comment]
"Wanderers: Sestor Attack"

**Comment by Amazinite** [comment]
Trying it now, but this mission does seem particularly hard in a single ship. The fact that your only backup is a stream of Flycatchers doesn't really help either.

**Comment by SirStigII** [comment]
I think that is the biggest problem, in the later missions there is a steady stream of republic ships to help you, but in the wanderer (and FW for that matter) planets there aren't any reinforcements to help you or assist you if you are disabled.

**Comment by endless-sky** [comment]
I've extensively play-tested every story-line battle in a single ship. Because so much of how the battle goes depends on the initial (random) locations of the ships, it's inevitable that sometimes you'll end up with an unwinnable fight and have to reload, and sometimes it'll be much easier. I generally try to balance the battles such that there's no chance of the player winning without doing anything (e.g. just cloaking and letting others fight) while also making sure that if the player plays strategically, a good fraction of the time the battle will be won without all the player's allies ending up dead.

Battles are designed so that the player needs to have good tactics in order to win them. The best two tactical options are:
  1. focusing your firepower on the same ships your allies are attacking, and taking out weak ships first, or
  2. trying to draw off a large portion of the attack force (leading it on a merry goose chase instead of engaging it) so your allies can mop up the rest.

There's a ton of skill involved in flying your ship in battles: dodging missiles, avoiding forward guns of the enemy, strafing effectively, etc. It still can't completely make up for the occasional awful luck, but if you're ending up solo at the end of every battle there are probably tricks you could learn to make the battles go much easier.

**Comment by KiLEdEnNis** [comment]
if a relatively "experienced" player faces a lot of trouble in this big battle, imagine the average Steam user in 1 ship

I do like one needs skills to win in 1 ship but if even the most experienced players have a lot of trouble I think we need to at least add 1 or 2 allied ships

**Comment by jafdy** [comment]
Yeah, but not everyone can afford a fleet or has the skill to fight effectively. We don't want to exclude the casual portion of the games population from the story line simply because a few of the most skillful among us can manage it in their position.

**Comment by endlesssteve** [comment]
Perhaps the random element in storyline battles could be reduced. I think the variations are more than the impact of the player in several battles.

**Comment by SirStigII** [comment]
@endless-sky not to toot my own horn but I consider myself a fairly skilled player, and up to this mission I was able to get by with only a single starling, through use of the tactics you describe. I think this difficulty might be a side effect of the turret turn rates, as the AI has a lot tougher time taking out the fighter swarm. Part of the issue is that the AI is very inconsistent in its clumping, sometimes they will group really well, and other times that will all split up and get wrecked. For the record this is the only mission that I had trouble with during the single ship playthrough, the moreti attack is  difficult but very doable if the player is in a serious warship.

**Comment by tehhowch** [comment]
As I mentioned in the "assistance" PR, the difficult battles may require revision due to the change in NPC parent behavior. This revision could be done in the form of NPC subdivision (creating more semiindependent groupings), or personality changes (heroic and/or timid usage, to control swarm size and the tendency of a ship to attack a lone target).

**Comment by KiLEdEnNis** [comment]
as Stig mentioned, not only the AI changes are making this difficult, but the turret turn rates too, and since the Wanderers only have slower Sunbeams they're at a disadvantage

**Comment by jafdy** [comment]
That is a big enough change that I imagine a balance pass on most of the combat missions is called for at some point soon.

**Comment by KiLEdEnNis** [comment]
I could do a speed playthrough in 1 test ship + loadout (like MZ did, not that I start in a Falcon or something) to see if there are any particularly difficult battles, I just need to know what ship to start in and when to switch to what ship (loadout is optional)
if anyone could hunt down MZ's old comments, or MZ himself gives me the list? @endless-sky

**Comment by KiLEdEnNis** [comment]
you're right, once the turrets are all rebalanced, I can playtest both stories, provided I get some sort of list of what ship to use (and maybe what tech) at what part in the stories so I know around what it should be balanced

**Comment by endless-sky** [comment]
The Wanderer missions are basically balanced assuming you are flying the best Wanderer ship available for sale at any given point, equipped with a good combination of Tier 2 technology.

**Comment by KiLEdEnNis** [comment]
does the human story need some retesting too?
in my playthrough I'm nearing the end of the FW campaign so I'd have to make a new save to test it
I can basically start on the Wanderer testing within a day though:
I plundered some Korath tech (automaton), I have some Remnant tech, Coalition tech & I'll have access to Wanderer tech, and I was planning on going in a Tempest once I get it anyway (then upgrade to Derecho etc.), which means I have that "good combination of Tier 2 technology"
all I have to do is stick to 1 ship & I can basically both test & play for fun at once

**Comment by tehhowch** [comment]
One current issue with the Wanderer content in v0.9.8 is that all Wanderer Flycatchers are broken - they don't properly swarm due to #2828 (this swarming issue is fixed in #3531 )
Without their swarming behavior, fighting missile-heavy Sestor packs will be considerably harder.

**Comment by FixItYondu** [comment]
I just ran into this issue with 2 different missions: the first being the one mentioned above and the second being "Wanderers: Sestor: Drones in Alnilam". The issues with the first mission have even larger effects on the second since you are facing a fleet of T2.5 ships with a few T1 allies (a Carrier, a Cruiser, and a couple of Gunboats, Rainmakers, and Frigates). One solution for the second mission is to reduce the number of Sestor ships, but that seems rather unintuitive and would end up reducing the difficulty of the mission overall. The second option, then, is to add more Navy ships. Maybe you could add in a mission chain where you go around to other Navy bases or potentially Free Worlds and Syndicate bases and ask them for ships for the attack? This seems like a better solution to me and would also add in a little more content.

**Comment by Amazinite** [comment]
> the second being "Wanderers: Sestor: Drones in Alnilam".

I just recently addressed this mission by removing some of the ships and reducing the number of detainers that the Sestor have in Alnilam. (The number of ships kinda needed to be reduced here because before you are even asked to destroy them, you need to fly past them to bomb Zenith.) #3804 https://github.com/endless-sky/endless-sky/commit/0436d657744d4c1e1355351a4c955fb178a91fc5

I'll take a look at Sestor Attack, though.

**Comment by Amazinite** [comment]
I believe that the *112 Sestor fighters* may be a big reason why this mission is quite the issue.
The Sestor ships become reinforced by a larger fleet shortly after the battle starts. How about some Mereti show up to help the Wanderers? It only makes sense that when under threat of the Sestor, the Wanderers would be assisted by their new allies literally designed to combat the Sestor.

**Comment by Amazinite** [comment]
In the latest commit, I've added a few Mereti ships that show up to the fight a little later. Just those few ships seems to greatly relieve the weight put on the player by this mission without completely trivializing the combat.
