### ISSUE TITLE
Navy Surveillance so frequent it overwhelms FW space

### ISSUE THREAD

**Issue by Lorantine** [endless-sky/endless-sky#3333]
I'm surprised I didn't find any issue related to the fact that Navy Surveillance are way too frequent, to the point they literally overwhelm the FW borders (even w/ me helping to defend in a partially-Korath tech Cruiser)

this is the part of the map
![surveillance map](https://user-images.githubusercontent.com/10348657/33517698-2825f9f0-d789-11e7-9c38-95d9c702d1e9.png)

after say 2 minutes of fighting, I saw this, ALL Surveillance (I've been killing several Cruisers before that)
![surveillance](https://user-images.githubusercontent.com/10348657/33517704-300c7ff4-d789-11e7-8f3a-057d07f7d50f.png)

reducing the Surveillance frequency to 1/4th (yes, that much, I'd even consider 1/8th tbh) would make it more realistic, and straight-up... better
(side note, maybe increase the frequency a little bit for the FW patrols?)

**Comment by tehhowch** [comment]
What point of the FW arc is this (i.e. what's your next mission).
You might also consider posting your save's `changes` list in a text file

**Comment by KiLEdEnNis** [comment]
scouting the sectors pre-attack because they want to defect, but this problem is basically from the start (mission "FW Southern Recon 1")
[changes.txt](https://github.com/endless-sky/endless-sky/files/1524031/changes.txt)

**Comment by SirStigII** [comment]
I would agree that patrols seem to come at an excessively high rate.

**Comment by KiLEdEnNis** [comment]
not only is it unrealistic ya see that much, it's actually hard to travel through the FW borders (in the mission where I had to escort the 3 Dreadnoughts & 5 Furies to Sargas for the next battle, 1 Fury got disabled & I landed to be safe, it took me 10 tries to lift off, repair & land because surveillance fucked him)

**Comment by KiLEdEnNis** [comment]
"FW Northern 2" is my current mission, and below is my map
Dschubba was getting spammed w/ Surveillance while the nearest Republic system is 4 jumps away, more proof those Surveillance fleets need a fix

![surveillance map 2](https://user-images.githubusercontent.com/10348657/33521740-e031d8e2-d7da-11e7-9f65-b856d1635cc0.png)

**Comment by Lineth** [comment]
This. So, so much. The Navy spam is ludicrous.

**Comment by ToxicFrog** [comment]
I ran into this as well; I actually started the FW storyline, played a few missions into it, and then had to reload an earlier save and grind up a much larger flagship and more capable fleet before trying again, because as soon as you enter the storyline FW space becomes completely overwhelmed with RN ships.

(More generally, the barrier to entry for the FW storyline is way lower than the barrier for "can survive the first few missions of FW", and once you enter the FW storyline you're cut off from most of the map, which makes it hard to get the necessary firepower if you don't have it already.)

**Comment by KiLEdEnNis** [comment]
I finished the human storyline again yesterday and I had less issues with the Surveillance after a couple of expansions; the main problem is early on (and Dschubba not updating as I said a week ago, but that's a bug)
end-game the Surveillance is less overwhelming as far as I saw, but when someone does the rebalancing, they should still make sure the Surveillance fleets warp in way less frequent than FW ships at any point in the campaign

**Comment by Pointedstick** [comment]
This seems pretty easy to fix; wanna submit a PR?

**Comment by KiLEdEnNis** [comment]
it's basically adding a few systems to some events, but I'm too busy w/ various other things, so someone else can do this
