### ISSUE TITLE
Trade interface displays cargo in parked ships

### ISSUE THREAD

**Issue by mootootwo** [endless-sky/endless-sky#3360]
This may be intended behavior, but it seems strange.

I was able to have cargo (50 food) remain inside a parked ship.  I am able to replicate this by filling a fleet with cargo, ordering a ship to hold position, and then remotely parking that ship.

The trade screen will then always display a price difference for the commodity inside the parked ship, even if your active fleet is empty.

As above, this may be intended.  I am not sure what the appropriate behavior would be if this is not indended, perhaps the Trade screen should somehow indicate that the commodity is warehoused and not available to be sold?  a (parenthetical) quantity, or shaded or colored value?

![es parked cargo](https://user-images.githubusercontent.com/25321484/33555031-ce091a0a-d8f6-11e7-9758-071ec28524fc.png)

Steps to reproduce:
- fill fleet with cargo
- launch
- order one ship to hold position
- move to new system
- land
- remotely order the holding ship to park
- sell all cargo
- observe profit/loss margin still displayed for cargo in parked ship
- observe ship details in 'i' screen lists the cargo onboard the parked ship

**Comment by endless-sky** [comment]
Commit 30bb81e will mostly fix this. There's still an issue where if you sell all your cargo of that commodity and then buy some back, a profit amount will be shown (because it's including the absent cargo in the cost basis), but there is no good way to avoid that because the cost basis treats all your stock of a commodity (even on absent ships) as fungible.
