### ISSUE TITLE
Mission failure by ship loss is very hard to spot

### ISSUE THREAD

**Issue by bluss** [endless-sky/endless-sky#3361]
Imagine you are in a big space battle. Hundreds of ships, thousands of projectiles :boom: :smile:. During all that, it may happen that a mission failure is announced, without sound, in white text at the bottom of the screen. You are going to miss that and later wonder huh, why did the mission fail?

It would be great to improve the visibility of the mission failure message from losing ships; and it should be available after after the fact too.

It's really an awesome game, so thanks a lot for making it.

**Comment by jafdy** [comment]
What about having the mission name in red (like disabled ships in the I menu) until the next takeoff.

**Comment by tehhowch** [comment]
My suggestion from https://github.com/endless-sky/endless-sky/issues/3354#issuecomment-348837136
>Regarding the mission failure info getting "drowned out" - please open as a separate issue and request something like an "Alert panel" in which "important" messages such as mission failed, ship captured, ship destroyed, etc are kept, and possibly viewable from the Player Info Panel, much like the logbook can be viewed.

Coloring the message could be done by extending the Messages class to have a flag (e.g. `isHighPriority`) that can be referenced in the message-drawing code when setting the color (which right now is just an alpha variation based on message age).
I would say coloring is a step in the right direction, with the end goal of what I mentioned in my comment (which requires sprite / UI updates).

**Comment by Laudrin** [comment]
Not only colouring the messages, I would further suggest specific **sounds** for events like ship is attacked, disabled or lost, mission failed etc.

**Comment by Zitchas** [comment]
Yes, this would be very helpful. Personally, I'd also like it to stick around a bit longer, so when the text fades it, it just leaves the mission failed notification floating there for another minute or two.

**Comment by temtemy** [comment]
I think all mission failures should be in dialogs instead (except the invisible "missions"), just like the FW missions. They definitely won't be missed out.

**Comment by Pointedstick** [comment]
The main problem here is that the failure message disappears. Even if it were rendered in flashing red text and sounded a warning klaxon, it would still disappear in a matter of seconds in a large battle.

Very important messages like these should probably be persistent somehow. Using dialogs for all of them seems quite reasonable to me.

**Comment by Zireael07** [comment]
redirecting from a duplicate:

Most games with many messages (RPGs, roguelikes) have a 'message/log history' screen where you can scroll back at your leisure. This often, but not always overlaps with storing the log in a file, as mentioned in #4794.

**Comment by 7eggert** [comment]
Moving over my feature request since it's deemed to be related:
---
While fighting, I don't usually have time to read the log. Important messages will get lost by scrolling and/or fading away. Especially if 10 ships scan my about 800 ships, I can't even read the steering feedback.

To change that, I'd like to have a log on the right half of my screen (if screen width permits) containing messages like "Escort xyz has been destroyed" rather than "drone 0815 scanned you" times 1001.

The navigation / landing box can be used to also show boarding commands, too. If there are different planets to land on, a dropdown there might help (it's hard to click on a planet if there is a fleet above). Fleet holding position / gathering might be indicated by a (G) or (H) icon there.

Scanning messages don't currently contain the name of the ship. I suppose it's important which ship would be scanned, otherwise future messages could be suppressed.

While scrolling, less important lines should be sacrificed in favor of more important ones. If a line says "Ship xyz is attempting to scan you", the "Ship xyz finished scanning you" line should replace it. If there is a chat line, a "scanned" line should not scroll from the screen.

Log Lines might be colored on the fight screen: "You sold … for a profit of …" might go green on the right side; "ship destroyed" red to the right, "scanned" blue to the left, chats to the left, too.

After landing, the complete log should be visible on demand.

**Comment by salqadri** [comment]
What is the status of this issue? Would love to see a resolution to this.
