### ISSUE TITLE
At >100% zoom levels, substitute scaled-down @2x assets

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3363]
I play the game with a 150% main UI zoom level on my 1920x1080 display, and at that zoom level, the raster sprites for ships and outfits start to look noticeably blurry around the edges. It would be really nice if the game substituted appropriately scaled down @2x graphics for >100% zoom levels when you have the hidpi package installed.

If this could create performance problem for in-game ships, then maybe just do it for the outfitter and shipyard, which is where it becomes really noticeable.

Edit: it just occurred to me that maybe the game already does this and I'm not getting it because I play with the game compiled from source and run out of the source checkout (can't check right now), in which case oops, egg on my face.  🍳😱

**Comment by tehhowch** [comment]
High DPI images should be used if they are available as soon as the UI zoom or 'main zoom' is higher than 100%.
If for example I am tracking down a bug and end up before the lighting switch, I can "recolor" my ships on the fly by zooming in because I have old lighting regular images, and the new lighting for the 2x images in my outside-of-git High DPI plugin.
You can check if this is happening by swapping a 1x image into the High DPI plugin (moving the 2x into a directory ES doesn't read), renaming it so the game will treat it as 2x, and then viewing it in game - it should be tiny compared to what you expect.

If you can, images would be nice

**Comment by Pointedstick** [comment]
Yup, user error. The symlink to the HiDPI assets into my user's plugin folder broke. Nuthin' to see here, move along...
