### ISSUE TITLE
"Linger" behaviors for NPC ships

### ISSUE THREAD

**Issue by tehhowch** [endless-sky/endless-sky#3381]
Figured I'd poll the community to see what, if any, consensus there is on what it should look like for an NPC to spend extra time in a system, outside of combat.

Currently, ships enter a system, decide if they want to land on a planet or jump, and then do that, immediately. There are a tiny handful of alternate behaviors:
 - surveillance (scan other ships, scan stellar objects, unload drones and jump away)
 - swarming (flit between any ships in the system)
 - mining (mine asteroids for a bit)

One issue brought up previously is that ES has a very high turnover on NPCs, and the lack of various behaviors is generally the root cause of this, as ships without one of those 3 behaviors have only one thing they can do: travel.

In #2990 @elyssaen and I introduce a "survey" behavior (which is exactly equivalent to the "scan stellar objects behavior" of surveillance ships), to increase the amount of time that our travelling NPCs spend in a system, but extending that specific behavior to all ships is probably not the greatest plan (it would look pretty weird to watch a bunch of Merchant Bulk Freighters traveling between the moons in a system).

If we reduce the turnover rate some, by requiring NPCs to do at least something in a system (i.e. we don't let them jump immediately), what kinds of things should NPCs do?
```
(please vote on suggestions you like)
```

**Comment by tehhowch** [comment]
One possibility is to have ships first decide to rendezvous at a randomly chosen point in a system. Ships with no parent would enter a system, pick a point randomly (equally probable to be anywhere within that system's habitable radius), and then only jump out after having traveled to that point. Ships with a parent would naturally follow their parent, and would get ready to jump when the parent had picked its position and arrived there.

**Comment by tehhowch** [comment]
Another possibility is to have some ships choose to spend some time circling a landable planet in the system (equally likely to circle counterclockwise as clockwise).

**Comment by solardawning** [comment]
Circle a landable planet/station makes a lot of sense: you'd expect ships do that while waiting for spaceport control to give landing clearance, or they've sent a landing craft down and leave the ship in orbit. I like it!

Here's another one: Meeting. Two fleets meet up at a picked point in the system, and one ship from a fleet boards a ship from the other, then they split and leave. (Are they friends? Bartering cargo? Who knows! But it looks like something is happening.)

**Comment by jafdy** [comment]
You could make landing ships slow down ahead of time and come in slowly instead of as fast as possible. If there was a fight going on then they would revert to as fast as possible.
This could be a safety thing where they decelerate below max thrust to avoid putting too much strain on the engines, or to allow landing with a partial failure.

**Comment by 1010todd** [comment]
Maybe some navy or any pirate hunters to wait in the system for a while to ambush pirate fleets and they'll leave after they waited for a certain amount of time and there're no pirates? (Like how pirate fleet ambush the players)

**Comment by ghoulavenger** [comment]
I'm a big fan of solardawnings meeting suggestion, from random merchant hails to actual trading, it just makes sense.

Another possible suggestion I could throw up is a tail personality. A ship just decides randomly to tail another, possibly even the player. Not quite like an escort since it doesn't belong to the same fleet, just someone that is snooping around basically.

That being said, I don't think that npc behavior is a very large concern, seeing as there isn't a lot of reason for players to stay in system either -- so the only times you really might notice are when you are mining or in combat. When you're mining you might run into other miners, and when you're in combat you're too busy to care.

**Comment by jafdy** [comment]
It's really for players the are lingering.

**Comment by endless-sky** [comment]
In Escape Velocity, this sort of happened automatically because ships had to fly out of the system center before jumping. But that also made traveling from place to place needlessly time-consuming, and putting a "gravity well" limitation on jumps would get complicated when each system has so many planets.

A better option, at least for ships in a fleet, might just be to require them to all gather in formation before jumping. The downside would be that it looks like a ship's behavior is "broken" when it is sitting stock still doing nothing just because it's waiting for its escorts to be ready to jump, but maybe if the escorts were actively moving close to the ship that would be alleviated.

**Comment by tehhowch** [comment]
As I mention in #3777 , an additional linger behavior is to seek out disabled ships and repair them. This is akin to the above suggestion for AI boarding other AI to do more than just plunder. A caveat is that it is not really very common for disabled ships to have enemies in system and no friendly ships pursuing said enemies - almost always if a ship is able to help, there are no enemies in system that prevent the disabled ship from asking for help.

If added, you'd really only see this linger behavior in systems where there is a lone missile Fury/Corvette in the great yon, or when you are the instigator and are cloaked in a hostile system / beyond the fence. However, if NPC factions ever deploy hostile, cloak-capable fleets into systems the player can monitor, then observing similar situations as to that in #3777 may become more commonplace.

**Comment by Zitchas** [comment]
I'm not sure about commonplace exactly, but I expect that as the Remnant missions progress they will get into situations that match this at least on occasion. Starlings should be using their cloak to flee and recover, and on the flip side could make great "medic" ships for assisting disabled ships.

**Comment by petervdmeer** [comment]
The linger behaviour would also be nice in combination with #4471 . My test with formations for NPC fleets didn't show any formations forming, and it looks like the NPCs just didn't hang around idle long enough to get in formation.

**Comment by chigau-kyuu** [comment]
My main problem with this issue is when you destroy ships, replacement ships appear too fast and in too great a number. For example, jumping into a pirate system and engaging any pirate ships present. You manage to destroy/disable them after a grueling fight, and then... more pirates jump in. You destroy them, and more pirates jump in. It's nearly impossible to just have a fight that begins and ends, because their allies keep appearing as fast as you can take care of the original targets.

I'm not sure what the solution is, but I don't recall ever having this issue in the Escape Velocity games. Perhaps it's because they were more okay with systems being relatively empty in terms of ships? It's a real big issue that detracts from the game, however. Perhaps there is a way to make it so that destroyed ships aren't replaced by new ship traffic, or there's a delay before the turnover. Also, perhaps more "neutral" ships should spawn in systems instead of pirate systems constantly spawning almost nothing but more pirate ships (ditto for systems with other governments and their respective ships, of course).

**Comment by tehhowch** [comment]
Note that if ships do more than just jump in/out/land, we can reduce fleet frequencies and still have the same level of "busyness" in a given system, as ships stay in it longer.

**Comment by Amazinite** [comment]
A lingering personality was added in #8125.

**Comment by warp-core** [comment]
Who merged #8125 and didn't close this?
