### ISSUE TITLE
Newly captured escorts are suicidal

### ISSUE THREAD

**Issue by ToxicFrog** [endless-sky/endless-sky#3387]
Any sort of battlefield capture of a ship is extremely dicey, not because you're vulnerable while docking with it, but because as soon as you capture it, it will immediately (with 5% hull and no shields) charge into battle and explode. The only way I've found to mitigate this is to *immediately* jump out as soon as you capture, at which point the ship you captured is safely "off screen".

Seriously damaged escorts should probably try to land and repair (if possible) or, failing that, disengage or at least try to keep other friendly ships between them and the enemy, rather than charging headlong into battle.

**Comment by jafdy** [comment]
We know, if you are going to post a new issue then please search for existing issues first.

**Comment by tehhowch** [comment]
You don't mention what platform you use to play on, but since this is a recent change I'm assuming a self compile.
This particular behavior would be abated somewhat by https://github.com/endless-sky/endless-sky/pull/3369

**Comment by KiLEdEnNis** [comment]
I'm currently at the start of the Wanderer story, and I use a Starlings' cloak to attempt to plunder/capture Korath Automatons in Mesuket
while it is obviously way easier to do so with cloak, I wait with decloaking until the battle moves a little bit away (so that once I may capture said ship, I'm safe for the next few seconds)
the base idea applies to non-cloaking: wait until the battle dies down around the ship you want to capture (the battlefield basically moves a bit away), THEN capture said escort, you can even have them gather using G, then fly to an edge and have the ship hold there so you can continue

simply said; your capturing chance goes up a lot if you have patience, the trick is WHEN to capture

**Comment by ToxicFrog** [comment]
> _YYou don't mention what platform you use to play on, but since this is a recent change I'm assuming a self compile._

Yep, amd64 linux built from d598858c9a444a5824e6c25dcfcafba9d426a815. I was running the Steam version, but then I went to report some issues and found out they were already fixed in master.

> _Additionally, since you have captured the escort, tell it to go somewhere else that isn't a combat zone. Select your escort and right click somewhere. If you've enabled radar interactivity, you can right click it and send them a fair bit away without leaving combat yourself._

I had no idea this was even possible -- I thought the only things you could do with escorts were the commands with associated keyboard hotkeys! This will help a lot, thanks.

**Comment by endless-sky** [comment]
I think most players who are farming ships quickly learn to lead them out of the center of the system before disabling them, to avoid having to capture ships right in the area where new ships are jumping in. It's so easy to do that that I don't think it's necessary for the game to make any special provision for players who choose not to.

**Comment by KiLEdEnNis** [comment]
the other scenario is capping ships on the egde of a battle, lead them away a bit, hold & continue, which isn't that hard (I do it w/ Automata in Mesuket, which should be even harder)
but I haven't had any ships storm in, they follow me when I move away (Steam build though), and ya can just press G to be safe
