### ISSUE TITLE
Suggestion: Faction-specific outfitters

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#339]
Some of the problems discussed in #329 and #267 would be mitigated if it were harder to use or sell looted alien technologies. Perhaps outfitters should have faction- or species-specific knowledge? E.g. if you just go to a normal outfitter in human space, the technicians there might have no idea how to attach a jump drive to your Bactrian - you'd have to go to Quarg space or to the few Syndicate shipyards where they've been studying this.

This would mitigate the problem where once you've overpowered a single Quarg warship you become nigh-invulnerable - you could only equip your ship with Quarg tech at an outfitter in one of the Quarg stations (which would now be hostile to you because you looted their tech).

It would also make sense if e.g. outfitters that only sell missiles and maps didn't have the tools to mount a new reactor in your ship - you'd have to go to a larger outfitter for that. Similarly, it'd make sense if e.g. the Syndicate arranged to make it illegal to install some of their outfits except via their own shipyards, though pirates and non-human species wouldn't care.

**Comment by endless-sky** [comment]
I think this could be a cool idea, but I'm also worried that there are already so many rules about what you can or cannot install in your ship, and adding another set of constraints would make it even more confusing for starting players.

**Comment by Oeleo** [comment]
That's not the first time that you said that, but it's normal that the players that played the game a long time wants to add things that complicated the game . Honestly the game is already a bit hard to be fully understand at the beginning, but adding new features will never simplify it. That's your game so that's your choice, of course that make the game the simplest possible will make the game more for "casual gamers" and less for "hardcore gamers", and the opposite is true too. But personally I think that the biggest difficulty of the game is that the wiki for beginners is rather empty. For example, Minecraft, project zomboid or don't starve are games that are 10x more complicated (you need to learn a lot of things), but there are a lot of casual gamers on this game, because they can find all the help they want on internet easily when they want to. I don't know for the others, but I find that a game with so many buttons to learn is what made me love the game, of course that you have to learn them for ~2 hours to be comfortable with them, but after you are free to do exactly what you want to do, and that's wonderful.

**Comment by brick96** [comment]
A problem may arise from these new constraints though. If you accidentally sell a reactor at one og these smaller outfitters, you're out a reactor and possibly a ship

**Comment by Pointedstick** [comment]
Personally I think the game is delightfully simple for beginners. You don't need to touch any of the complicated things like balancing power and heat until you're ready because most ships that you buy have that stuff already working fine. And the autopilot makes it easy to land on planets, board ships, and use un-turreted guns in combat. It's also way better documented than any of the EV games ever were. Most of those games never gave you any specific information about what ship outfits actually did, for example! You had no way of knowing how any of the weapons differed numerically except by using them and observing the effects, and of course if you decided you didn't want one anymore, you would have to sell it for less than half the price you bought it…

**Comment by dplepage** [comment]
@brick96 It would make sense if outfitters that didn't understand how or didn't have the facilities to install a component also couldn't uninstall it, so you couldn't sell your reactor at a place that couldn't put it back in. This would have one significant downside, though, which is that it'd be hard to swap out one race's outfit for another's, since you couldn't find a space station that knew both how to uninstall your old one and how to install the new one.

The other option would be that a place that doesn't know how to install something could nonetheless reinstall something they just disconnected - they wouldn't know why it works, and couldn't do it again if you brought them an uninstalled outfit, but they can at least reconnect the bits they just disconnected this one time.

**Comment by frameworld** [comment]
*joking* I am for a home-base where you can hire specialists :p

Or that you have to go to a outfitter on a planet with a shipyard that produces your ship if you want some fancy equipment on it.

**Comment by dplepage** [comment]
Three more related ideas:

1. What if you carry knowledge of your own systems with you?

That way, if you've ever had outfit X installed on your ship, then any outfitter can install or uninstall X for you, because you've got notes on how to do it, but if you've never had an X before, then you need to find an outfitter capable of figuring it out. This would, for example, make it impossible to install a jump drive before that point in the Free Worlds mission even if you successfully acquired one, unless perhaps there were a way could convince the Quarg to do it for you (or some other Syndicate mission chain triggered by landing on their worlds while possessing a Jump Drive). Possibly there could be similar missions for other useful technologies, or a few generic missions that could be applied to any alien technology (you pay a bunch of money and run around a lot between various systems, and eventually you get an outfitter capable of installing your alien outfit).

2. Unrecognizable outfits

Taking that one step further, what if you couldn't even *recognize* alien outfits until you found someone capable of working with them? E.g. if you disable a Korath Raider for the first time, you won't get a list telling you "This is a Tek'nel Reactor that you could sell for $14M, and this is a Shield Generator that you could sell for $1.7M", you'd just be told "There's a 140-ton outfit you don't recognize, and a 52-ton outfit you don't recognize". You might be able to sell them at some very low price as "unrecognized alien tech", but they wouldn't become valuable until you'd done whatever was needed to figure out what they actually *are*.

3. Penalties for mismatched systems

It might also be easier to keep things balanced if there were penalties for mixing systems from different manufacturers. For example, if you have a Lionheart ship, then Syndicate-specific weapons and systems might, say, take up 10% more space and generate 15% more heat (because of all the extra wiring you need to do to connect the Syndicate and Lionheart interfaces). These penalties could be stricter depending on how different the sources are, so e.g. mounting a Pug weapon on a Hai ship might carry more like a 60% space penalty.

This would also lessen the "I beat a Quarg and now am invincible" effect, because unless you actually captured the Quarg ship you'll need a lot more space and cooling to use their systems on your human ship.

**Comment by frameworld** [comment]
I like 3.

**Comment by endless-sky** [comment]
This would make outfitting a ship *way* too hard for beginning players to figure out, especially if there's something that causes the size or efficiency of an outfit to change depending on where it's installed. I don't think it would add anything to the game play aside from an extra layer of complexity, which will not appeal to most players.
