### ISSUE TITLE
Coolers would make a ship *more* vulnerables to IR-guided missiles, not less

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3390]
Where's all that heat going, anyway?

The description and visual design of Endless Sky's coolers makes them look like fans, heat pumps, and radiator coils--that is to say, rather than storing heat or transforming it into work, they move it around--presumably, radiating it into space. Lots of cooling would mean a huge amount of infrared heat radiating off of the ship. So a ship full of coolers would be lit up like a Christmas tree to a missile's infrared seeker, compared to a ship with equal heat but fewer coolers.

The only equipment that should make a hot ship less passively vulnerable to IR missiles should be things that prevent heat from being radiated into space: hull insulation, low-E hull coatings, or internal thermal mass heat storage systems. Any of these would actually have the effect of _increasing_ a ship's heat, not decreasing it! I think this would enable an especially interesting gameplay dynamic: since cooling outfits would increase vulnerability to IR missiles, players with really hot ships would have to choose between managing the heat or having better passive IR missile defense.

Right now, there's little disincentive to use better equipment that generates more heat. Coolers are widely available and most aren't _that_ big compared to the cooling they generate--and anyway, a lot of the outfits that generate a lot of heat are fairly compact compared to their larger but cooler alternatives, so you have more room for coolers anyway. In the late game, Korath coolers quickly render heat a non-issue. Players can have their cake and eat it too. Every ship can easily have a near-invisible IR signature to missiles. It's yet another way that missiles are less useful and effective than they could be.

**Comment by ghoulavenger** [comment]
I think that some cooling systems might make you more attractive to IR, but most of them I'm going to disagree with.

Fans on principle reduce heat by increasing the amount of surface area that the heat is applied to, unless the fans are blowing into space directly they should be okay (which theoretically means more ducts would only be good if there wasn't enough airflow to distribute the heat, and would generate heat thereafter). Water coolers use condensation as a natural cooling process (which you can bet they do inside of a radiator). Liquid helium/nitrogen coolers just straight up chemically reduce heat. Which means basically all of the human solutions wouldn't raise IR. The Wanderer heat sink should also be okay, since again, you're distributing the heat and increasing the surface area to which it applies.

But the heat shunts from Korath tech, they might, since they vent the heat directly into space. The Remnant's cooler is in the same boat since it does the same type of thing. 

I have no real opinion on the Coalition's cooler or Hai Williwaw cooling.

**Comment by jafdy** [comment]
So while it follows logically this is more about game play than anything else. If the mechanic was changed then it would need to be consistent across all coolers. Most likely some function that looks at the heat lost per frame and the cooling power at that frame to find the IR visibility.
I like the idea in principle but I worry that it will add complication to a system that can already overwhelm some people.

**Comment by ghoulavenger** [comment]
@jafdy I never even considered cooling as a defense against missiles so I wonder how much that is true. The obvious answer for anti-missile has always been the outfit specifically for that, the AM turret. The less obvious solution is a strong engine and knowing how to dodge missiles. I stand by my original statement though, most coolers shouldn't increase IR as an offset to their cooling.

**Comment by Wrzlprnft** [comment]
i agree with jafdy that this might just overcomplicate the heat-cooling-issue. at least with put current UI and information on the tracking.

**Comment by KiLEdEnNis** [comment]
to be honest it'd make customizing a bit more fun in that you have to decide "do I get cooling or do I stay hot and safe from some missiles", but it'd be too complicated indeed for just a small feature

**Comment by ghoulavenger** [comment]
You know, I might recommend a different solution if heat and cooling is truly a problem with the current way IR works. 

Givens:
Heat is generated and detected by IR.
Cooling reduces heat and therefore the effectiveness of IR.

Potentially wrong behavior:
Exterior outfits can be invisible to IR via internal cooling.

Basically there isn't really a problem with masking the heat a reactor generates because it's interior heat, and can be addressed with interior cooling. But most weapons, while they can be cooled with interior cooling, passively radiate heat into space while they are in use, which should show up to IR regardless of whether or not they are adequately cooled.

This fundamentally changes the problem into is the ship actually moving or firing. If the ship is doing both, theres a very large probability that IR will be able to track it. And a ship that doesn't move or fire is basically a sitting duck to missiles anyway. 

Honestly though I still think the AMs are the best defense against missiles so this isn't a very large issue to me, and might complicate things more than necessary.

**Comment by ToxicFrog** [comment]
> _Cooling reduces heat and therefore the effectiveness of IR._
> _Basically there isn't really a problem with masking the heat a reactor generates because it's interior heat, and can be addressed with interior cooling._

The thing is, all that heat has to _go somewhere_. It can't just build up inside the ship indefinitely; cooling systems don't magically eliminate the heat, they just move it around. In space you can't convect the heat away, so typically "move it around" means "to external radiators, where it gets shed as IR".

IMO, the best way to reconcile this with more cooling making ships harder to get IR locks on is to assume that everyone uses open-loop cooling in combat. The ship doesn't radiate heat; instead it concentrates as much heat into the coolant as possible and then vents the coolant to space. This means heavily-cooled warships are trailing a giant cloud of boiling coolant that's invisible to the naked eye but blinding in IR. The more cooling the ship has, the bigger and hotter the cloud and the more likely a missile is to lock onto that (or get confused and fail to acquire lock entirely) rather than getting a lucky glimpse of the ship's gunports or coolant vents and lock on to the ship itself.

Refilling the coolant is presumably part of the same free, automatic maintenance like hull repairs and refuelling you get every time you land.

**Comment by Pointedstick** [comment]
Hah, that's a great head-canon explanation.

**Comment by endless-sky** [comment]
The three tracking modes aren't about realism. They're about creating three different tracking modes that are as distinct from each other as possible: one that can only be defeated by special outfits, one that gives you an incentive to run cooler than the absolute limit, and one that penalizes you for flying a large ship and gives small ships a better chance.

If infrared tracking was switched so that you had to install special outfits whose only purpose is to defeat infrared tracking, that would erode the differences between the three tracking modes.

**Comment by Pointedstick** [comment]
Okay, fair enough.
