### ISSUE TITLE
Mission "FW Syndicate Capture 1B" requires too much luck

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#34]
I had to retry the mission after you capture a Syndicate guy over seventy times (not sure about the exact count).  All but 7-8 times I got destroyed in the first system, where a massive horde with particle cannons makes it impossible to jump (particle cannons and missiles give the ship some momentum, causing it to repeatedly try to stop).  The remaining times, I got destroyed by insta-kill missiles in the second system.  Only after that many tries somehow the missiles flew some other way (a heavy anti-missile turret was never enough).  This was with a Dreadnought with atomic engines, so most other ships would die sooner.

While many other missions are luck-based, odds that low are excessive.  Am I doing something wrong?  If not, I think the first welcome party should be reduced.

**Comment by endless-sky** [comment]
It was intended to be three separate battles: after capturing him, if you wait 5-10 seconds in the first system (Alpha Hydri) instead of jumping out immediately, the Syndicate fleet starts to arrive but you can pick them off individually as they jump in. Then there's the second fleet waiting for you in the next system (Ruchbah), and the nukes in a third system (Ankaa or Sheratan or Scheat).

But if you jump out immediately (which is the natural thing to do, after all!) you meet up with both fleets in the Ruchbah system and then, they are indeed far too powerful. So, I've changed it in commit 8c2c459 so that the Syndicate shows up in the initial system almost immediately, to make sure that it ends up being three separate, manageable fights instead of one big one.

The nukes are *supposed* to be really evil and annoying; I suspect I was testing in a faster ship or one with afterburners. But, it's essential to the plot that you *should* be mad at the Syndicate for using nukes against you. :)
