### ISSUE TITLE
Grace period for mortgages?

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3412]
When bank lends money to start business, they usually don't expect for it to start generating revenue instantly, so payments start after some negotiated time. Starship is such an investment (otherwise, if starting from scratch, you'd have to calculate initial payments and possibly salaries into the loan). Also, I've read that new players are struggling with repaying initial debt.

Perhaps some grace period (say, a month) could help? It likely wouldn't change much for experienced players.

**Comment by tehhowch** [comment]
I wasn't given or offered a grace period on a car loan, and a spaceship is just a bigger (and better) car.

**Comment by Pointedstick** [comment]
Of course, your car loan gave you a month between having to make the payments. 🙂

**Comment by tehhowch** [comment]
If I paid daily I expect I'd have to pay daily though, without days off on it.

From an implementation standpoint, we could implement some sort of grace period by decrementing a counter, and while it is positive, no payments are made but interest accrues. We'd use a new keyword to avoid giving grace periods for any loans beyond the starting loan (e.g. being able to cheese the system by just taking new loans to pay off old ones but never actually paying down a loan).

**Comment by ghoulavenger** [comment]
> We'd use a new keyword to avoid giving grace periods for any loans beyond the starting loan (e.g. being able to cheese the system by just taking new loans to pay off old ones but never actually paying down a loan).

Considering one of the best ways to pay off your loans as a merchantman is to take out a new loan (because of better interest rates) I'd rather have that ability than any sort of grace period. It isn't exactly hard to pay off the first loan as long as you're actually doing jobs (the hand holding method), trading (some exploration required), or know what you're doing (combat and optimal trading routes). The only way not to pay off the first loan is just to go around exploring aimlessly.

**Comment by tehhowch** [comment]
>Considering one of the best ways to pay off your loans as a merchantman is to take out a new loan (because of better interest rates) I'd rather have that ability than any sort of grace period. It isn't exactly hard to pay off the first loan as long as you're actually doing jobs (the hand holding method), trading (some exploration required), or know what you're doing (combat and optimal trading routes). The only way not to pay off the first loan is just to go around exploring aimlessly.

What's your point? I said no modification to existing loans, except the starting loan, should be done if we add a grace period. If you got a grace period with any loan you took, you could just use a new loan to pay off the old loan on the day before your grace period expires, and keep repeating this process - getting money (and yes, building a mountain of high-interest debt) without ever paying anything back to the bank from your own earnings - i.e. you'd never see "you paid $y in mortgage payments" because you'd always be in the grace period of a new loan.

**Comment by endless-sky** [comment]
Ships are much more comparable to houses than to cars. (Cars have a much smaller range of sizes, for example. And it's unreasonable to expect, even in the future, that an interstellar transport would cost as little as a road vehicle.)

Just think of one "year" of game time as equivalent to 30 years in real life. That is, the amount of economic growth you can experience in a "year" of game time would probably take 30 years in the real world. (And, your mortgage in-game has a 1-year term instead of a 30-year one.) By the same token, in-game mortgages get paid every day instead of every 30 days.

**Comment by Tadrix** [comment]
Ok, so let's take a real grace period banks grant to startups (which would have at least a workshop, a warehouse or at least an office) and divide it by 30. Because that's what player at the beginning really is.

A quick search turned up with no interest period during first 15 months. Half a month in-game then. If player takes tutorial missions and follows instructions precisely, then payments will start a few days after taking James to Hestia, on time to underline "You're on your own now, kid."

**Comment by endless-sky** [comment]
If someone's having trouble earning enough income to pay their mortgage, a "grace period" is only a bandaid solution; they really need to think more strategically about what missions to take, etc. And, the grace period would have to be another column of info displayed int he bank, which really doesn't have space for it, or else be invisible to the user, which would be confusing.

The fact that the starting loan is big enough that you have several weeks of zero income before you run out of starting money to pay it already builds in a sort of grace period.
