### ISSUE TITLE
"Wanderers: Sestor: Bomb Zenith 1" Can Skip out on Lots of Text

### ISSUE THREAD

**Issue by Alkallid** [endless-sky/endless-sky#3424]
If you bring the Quarg reinforcements back to Farpoint and land with a ship that lacks cargo space, you will get a blocked message for the following mission. When you take off, the fleet of Sestor drones will be in flight, and destroying them and landing will trigger "Wanderers: Sestor: Drones in Alnilam" and skip out on the introduction of the bomb and the drones elsewhere.

**Comment by endless-sky** [comment]
There's no easy way to fix this, because the two missions need to be generated at the same time. One option would be for the bomb to not take up cargo space, I suppose.

**Comment by SirStigII** [comment]
Ohh this explains some weirdness I had on my last playthrough, I thought I had messed something else up and went back a few saves. I must have just not picked up as much jetsam.

**Comment by tehhowch** [comment]
We could perhaps make the Quarg mission offer have the blocked message, or rather than as cargo, require the Zenith bomb to be installed on the player's flagship. Installing would also have the benefit that the player cannot fail the mission due to losing an escort in the fray that follows the launch.

**Comment by jafdy** [comment]
If it was a mass less bomb then that might work, but the player could still sell it.

**Comment by Amazinite** [comment]
>We could perhaps make the Quarg mission offer have the blocked message

Yeah, if both missions need to offer at once then the prior mission should check for cargo space. Maybe the Quarg not only assist you with warships but also give you X tons of medical supplies to help the Navy, X being equal to the mass of the bomb so that you're guaranteed to have enough space for the bomb.

**Comment by tehhowch** [comment]
In #3596, I have Elias offer some supplies. Being a rather empathetic person, that seemed more in character than having the Quarg do it.

**Comment by Amazinite** [comment]
Sounds like a good plan.
