### ISSUE TITLE
"Sestor: Kill Southern Remnant" way too hard in 1 ship

### ISSUE THREAD

**Issue by Lorantine** [endless-sky/endless-sky#3429]
when you bomb Zenith you have to kill all Sestor ships in human space, but there's up to 5, 6 Sestor ships in some systems, and Republic fleets hardly show up to help (mostly in the Northern areas around Betelgeuse)
to fix this we'd either need an event that makes the Republic way more frequent in those areas until the mission is over, or (less good) create some Republic NPC ships in those systems so there's always a battle going on upon jumping in
I have a cloaking device but as far as I know this is literally 100% impossible when picking the checkmate branch since you get slowed ridiculously much and swarmed w/ Sestor drones
I also have a backup save so the mission can be tested quickly if any rebalancing takes place

**Comment by Wrzlprnft** [comment]
then link said savefile here, and give a quick overview over the different strategies you already tested, please.

**Comment by KiLEdEnNis** [comment]
in the Southern areas there are plenty of Navy ships, so it's just a bit of patience
in the North I tried it without using my cloaking device as the checkmate branch doesn't give one, but usually once ya enter a system ya get swarmed & hit by Detainers; no escape
if I do use my cloaking device, I have to get to the edge of a system, first take care of the fighters, then keep hit-and-running to slowly take the rest of the fleets out
more Republic/Oathkeepers in the Kursa system, and Canopus+everything above it (until the mission is completed) would fix this, since in some systems like Mebsuta the Navy hardly appears at all

[Kill Southern Remnant balance test.txt](https://github.com/endless-sky/endless-sky/files/1565576/Kill.Southern.Remnant.balance.test.txt)

**Comment by tehhowch** [comment]
And is this using the latest self compile, or v0.9.8?

**Comment by KiLEdEnNis** [comment]
Steam version, but I haven't found any signs of a rebalance that's been done before, and I don't remember any either

**Comment by SirStigII** [comment]
Well I just did that playthrough just before the last turret speed change, and it was pretty easy I thought compared to the defence missions...

**Comment by KiLEdEnNis** [comment]
in this mission (Northern regions where ya hardly get friendlies to jump in) ya just get slowed until ya hardly move & can't even escape, and those systems have maybe 4-6 Sestor ships + fighters
did ya even use 1 ship or a fleet? because the balance is around 1 ship

**Comment by endless-sky** [comment]
Those missions are balanced under the assumption that you're flying a Hurricane with a well-considered set of outfits.

Unless you've skimped on engines, Detainers are pretty easy to dodge until you are at quite close range.

**Comment by endless-sky** [comment]
Well, after playtesting a bit more, I think the biggest issue is that the missions are way too easy (if tedious) to beat with a cloaking device, and way too hard without one.

**Comment by SirStigII** [comment]
I would agree that more balancing with the cloaking device is in order, the cloak, shoot, cloak, repeat tactic seems like the clear choice, the slowing is brutal to fight against.

**Comment by KiLEdEnNis** [comment]
with cloak about anything is a no-brainder due to hit-and-run, my max speed was a little below 300 but even <450 makes it too hard
I'll leave the cloaking rebalance to others, but I'll playtest the hardest defense missions & this mission after:
all the weapon rebalancing is done
of course this issue gets a fix (I'd say temporary frequent Navy patrols, I may get to that myself this evening (European time)

**Comment by KiLEdEnNis** [comment]
I'm not sure if the patrol fix was addressed, but was there anything else to do before I start playtesting all Wanderer post-Eye battles, or should I start doing it?
