### ISSUE TITLE
Add missile jamming

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#346]
Anti-missile turrets can destroy incoming missiles, but I notice that there's nothing that can jam them. This could be a useful addition and enable the creation of missile jammer outfits. Needless to say, this should only affect guided missiles.

**Comment by Tufton** [comment]
How could it be implemented though?  Like...you would need an outfit that
somehow affected the "homing" value on another ship's missile launcher
outfit (perhaps easier if the homing was on the missile itself but I think
that's another discussion).  I can't think of a current outfit that affects
the outfits on a ship that is attacking it.  Maybe an anti-missile turret
with super low anti-missile strength but impact force so it knocks the
incoming missiles off course?

**Comment by Pointedstick** [comment]
I'm thinking this would probably require code changes.

**Comment by endless-sky** [comment]
I think the best way to do this would be to add ship attributes like "infrared jamming" or "radar jamming". (Presumably, different missiles use different tracking methods, so a particular jammer might only work against some of them.) The missile AI would then be responsible for checking if its target jams its particular tracking method, and randomly simulating tracking problems if so.

The bigger problem would be balance: the jammer has to be really unreliable, or so big and power-hungry that it's not significantly better than the anti-missile turrets. Or, the jamming would need to be an intrinsic property of certain ships rather than an outfit you can buy.

**Comment by Pointedstick** [comment]
The way I see it, jamming and anti-missile defenses are used to defend against different threats. Jamming is used to address the threat of guided missiles, while point defense can project you against dumb unguided missiles as well as guided missiles. So an anti-missile turret would always be better than a jammer. And yeah, jammers could use energy and generate heat.

In fact, this gives me a balancing idea: guided missiles could have heat-seeking properties and be more strongly attracted to and more difficult to jam for huge ships that generate a lot of heat, so for those ships, jamming would be largely ineffective and they'd have to rely on point defense systems to destroy the incoming projectiles. So jamming systems would really be for small ships that don't have the room or turret hardpoints for anti-missile turrets.

**Comment by endless-sky** [comment]
@Pointedstick, I really like that heat idea. What about this:

A missile can have multiple tracking methods, each with some percent
accuracy. For example, a missile might have infrared tracking of 0.8 and
radar tracking of 0.4.

A ship's ability to evade infrared tracking is based on its heat
percentage. (So, adding enough coolers to keep your ship at zero heat would
allow you to evade IR tracking.) Evading radar tracking would require
jammers. There might be other tracking methods as well - e.g. optical
tracking, which might work better while the missile is pointed towards its
target, and might also work better on larger targets.

A missile would get "confused" if all its tracking methods fail. Once it
got confused, it would have some chance of regaining the lock but in the
meantime it would stop steering.

This would also allow the missile damage amounts to be increased (#251),
because they would be less likely to hit, especially if fired at long
range. It would also add an element of strategy, e.g. needing to fire
missiles from closer to the target, or letting your ship drift to cool it
off if you are trying to evade missiles. If optical tracking depends on
target size, it would also make fighters naturally more resistant to
missiles than capital ships.

**Comment by Pointedstick** [comment]
I like where you're going with this *a lot*. This would make missiles much more fun and interesting. Tracking methods could be IR (defeat with coolers), Radar (defeat with jammers), Optical (defeat with maneuverability), and Gravimetric (defeat with small mass). Better, more expensive missiles would have multiple tracking methods, while the cheapest might have only one.

Optical tracking could also be added to the currently unguided projectiles to give them a very limited mid-flight course-correction ability if they were generally pointed in the right direction but would miss slightly, would could help boost them a bit in this brave new world of more-defeatible missiles.

**Comment by Pointedstick** [comment]
This would also increase the importance of cooling and provide a counterbalance to outfits whose drawbacks include high heat output, like Atomic Engines (#271).

**Comment by thenerdfreak** [comment]
How about making a jammer in the form of a turret, that, instead of blowing up missiles, disables their steering so they still blow up just they don't follow you

**Comment by endless-sky** [comment]
This is implemented as of commit a0ed0fd.

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
