### ISSUE TITLE
Consequences for being in debt

### ISSUE THREAD

**Issue by Fzzr** [endless-sky/endless-sky#3469]
This came up thanks to starbridge in the discord. They suggested some sort of consequence for the player being in debt beyond the compounding payments. Suggestions that came up were:

1. Increasing bounty hunter/"Repo Man" attacks based on the size of the debt after some amount of time.
1a. If caught and boarded, your fleet assets are seized to pay the debt. If you have negative net worth, you get sent back home to start from the beginning (or probably they just kill you).
2. If you're in arrears on crew pay, not being able to hire any new crew until you're up to date on payroll.
2a. The player could be able to buy crew who don't require pay (slaves) on appropriate outlaw worlds, both in general and when defaulted on crew pay.
2b. At a certain combat reputation the player might still be able to get crew eg. for "prestige".

As an aside, @Bladewood and others suggested a bank robbery mission string. Interesting enough I decided I'd mention it here.

**Comment by Amazinite** [comment]
>They suggested some sort of consequence for the player being in debt beyond the compounding payments.

Why would anything else be needed? Being unable to purchase anything until you pay off your debt is punishment enough. To add even more consequences on top of that seems far too punishing. 

>1 and 1a

What if you aren't even in human space? Will aliens start coming after you? 

>If you're in arrears on crew pay, not being able to hire any new crew until you're up to date on payroll.

Gameplay > realism; such a scenario seems very counter intuitive to gameplay. You need ships with crew to make money, but if your crew leave then you can't make money to pay them, so you just end up with no crew and no money and have to start over. There are already enough people who complain about the existing mortgage system on Steam, saying they need to start over because they get stuck in a rut with only the current system. I don't think that adding any additional consequences like the two above would be beneficial in any way.

>The player could be able to buy crew who don't require pay (slaves) on appropriate outlaw worlds, both in general and when defaulted on crew pay.

I've had an idea in the past to create a "slave" outfit that acts just like the android outfits we use to be able to buy, except it's an atrocity to have. I haven't gone ahead on it though, since I feel that it would be something locked behind a story.

**Comment by ghoulavenger** [comment]
> I've had an idea in the past to create a "slave" outfit that acts just like the android outfits we use to be able to buy, except it's an atrocity to have. I haven't gone ahead on it though, since I feel that it would be something locked behind a story.

Why not just bring the androids back? Thanks to the automated ships, it doesn't seem like it'd make much of a difference. If you're worried about extra capturing potential, just eat up max bunks. That being said, a slave crew could be amusing, for the folks looking for something a little darker, particularly a pirate playthrough.

**Comment by Fzzr** [comment]
Another suggestion from starbridge, which I'm adding here so it's written down: A new type of bounty mission where a bank and/or pirate warlord sends the player after someone who didn't pay their debts. eg. `"The captain of the 'About To Get Rekt' left town without paying the last installment of their debt to a local warlord. Find them and make an example."`

**Comment by ghoulavenger** [comment]
>Regarding androids: Why were they removed in the first place? If having crew with no ongoing costs is a major balance issue, making slaves harder to get and keep might or might not help. 

All I know for certain is the amount of power held behind them. Theres a couple ways to tackle it:

1. Fleet size is managed by how many ships you can support.

But this doesn't really seem to be that much of a problem to me. Players can just run a cargo fleet. Alternatively we also can now have drone automata, which don't even have a single crew, but instead are balanced by their difficulty to obtain.

2. Capturing is balanced around the amount of crew you have remaining. 

This in and of itself does not directly challenge androids. But one of the ways capturing is balanced is remaining crew members, and the difficulty to pilot ships, which androids will negate entirely. The fix to this is to make androids eat up bunk rooms. This will actually make it more difficult to capture ships than without having androids though, since your offense is determined by total number of weapons wielded, and with a lower bunk count you're always going to have fewer crew holding weapons. But if your desire was to make it easier to manage a fleet then this isn't a problem. Just make sure your flag isn't running androids.

**Comment by KiLEdEnNis** [comment]
quite a big wall of words, I'll just state a fact in 1 sentence (which Amazinite said before too as far as I saw):
being in debt is already a penalty, no need to add more

**Comment by Fzzr** [comment]
After more thought, I feel like it is indeed the wrong time to add slaves/bring back androids. No crew will make clawing one's way back out of debt even more difficult, and the boarding thing is just too harsh (not to mention the extra work it would take).

I do like the new mission/job ideas that various people came up with. I'm working on one about making an example of a thief, and after that I'll give the bank robbery one a shot too.

Overall though, nothing else worth discussing here. Thanks for the input everyone.

**Comment by slchorne** [comment]
I know this issue is closed, but you can still upgrade by just plundering ships, you never need to purchase anything, and still run a crew racking up more debt each day.
see this [interesting thread](https://www.reddit.com/r/endlesssky/comments/znkagf/so_how_exactly_do_i_get_myself_out_of_this/). 

Eventually something needs to happen to your reputation, systems should classify you as a pirate, or perhaps the banks just sell your debt to the the Syndicate, your rep with them drops to -1000, and they come after you. If you're caught, your fleet assets are seized to pay the debt (add a random encounter mission that flips the right bits). And you start again, with a basic ship, starter mortgage and whatever you have parked and stored elsewhere. 

Perhaps the syndicate then offers (forces) missions to improve your rep and pay off your debt.

Being almost stranded on a planet is a reasonable interrupt to your game progress: declare bankrupcy. Your combat rating will still get you high paying bounties and you will be left with rebuilding a reputation in some places.
