### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#349]
There seems to be a growing need for ship and outfit textures. I myself know how to use blender to a degree, but every time I try I fail to create anything that looks like endless-sky style ships and outfits.

Perhaps a more realistic scenario is a one where Michael puts out textures (for example here) and then we code and balance the ships?

Michael would post a, say, outfit that looks like a block of wires, and someone turns it into a 'Targeting Computer' outfit. Same goes with ships. This, perhaps, would make item and ship creation much faster shot term, since trying to match E.S. style while making textures would no longer be our concern.

This also makes things easier on people who do not know how to use blender or any other 3D/ Photoshop program.

**Comment by endless-sky** [comment]
In other words, I do the hard part and you'll do the fun part? :) There are
actually a lot of people who are *much* better with Blender than I am - I'm
hoping a few of them will get involved eventually.

There are Blender templates here that will at least let you get the
lighting and perspective to match the existing renders, and also the raw
Blender and GIMP files for all the graphics:

https://drive.google.com/open?id=0B9aK8dG39P29fkdBeUJjSXJYVDdjMEpkOXh3T1NDekFYaTEtbkdTdzVwX2NTUWVVT3BUWVk

One of the reasons I'm encouraging modders to think about adding new alien
species, rather than just new human technology, is that if the ships and
outfits for each species are done by a different person, they will still
have a cohesive look even if that look is different from the human items.

**Comment by Tufton** [comment]
You know, I found it easiest to just take the existing sprites and chop
them up into pieces in photoshop.  Now I have a repository of a bunch of
ship parts (Cruiser wing, cargo bay, etc.) that I can mix and match to
create new ships that match the current theme of the game.  Obviously this
is just a workaround for someone with no 3D modeling experience, but I've
found it to be rather effective.  It also allows you to make small (or
large) adjustments while generally staying true to the existing art style,
which is difficult if you want to slap something together from scratch.

**Comment by gchapyzh** [comment]
​Yep :)

Honestly, however, I tried. Everything I create looks like it came out of a
parallel universe. I would if I could...
Just every time I try to make something, I realize I have no​ texture!

Tufton, you are a genius. You have practically solved my issue. Take what
we have now, and rebuild! Thank you!

Still, some original, dev-made textures would be nice :) perhaps out of the
dev scrap-box?

**Comment by wkoot** [comment]
Could you use some of these for wire block http://opengameart.org/textures/5646 ? I guess you could colour some of the wires differently for instance, or blend them atop of existing patterns.

**Comment by frameworld** [comment]
First, think about basic shapes.
* Rectangles vs ovals
* Circles vs Hexagons
* Right angles vs some odd shapes
+ For each part, define the number of edge-points visible from top.
+
