### ISSUE TITLE
In "FW Pug 3B", Geminus demands a massive bribe.

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#35]
In some earlier missions, hostile planets required a bribe even for doing something required -- this can make sense.  But not in a case where I'm trying to land on a friendly planet that's about to give me a fleet.  Also, a fully hostile Republic planet used to demand mere 40k from a "terrorist", while Geminus wants 478k from a friend.

**Comment by endless-sky** [comment]
Fixed in 8c2c459 (by giving you "clearance" to Geminus for that mission).

When the ceasefire with the Republic begins, most of the paradise planets still refuse to trust you, so they won't let you land at first. Helping the Oathkeepers vs. the pirates helps to restore your reputation with them, and I guess in my testing I had always garnered a good enough reputation by that point that Geminus would let me land with no trouble. But, I agree that even if you haven't built your reputation back up by that point int he story line, they should let you land without a bribe.

Bribes are based on the total value of the ships in your fleet, because I wanted them to scale as the player gets richer.
