### ISSUE TITLE
Runaway ships

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3507]
#2234 was supposed to be fixed. Apparently, it isn't (however, it's very rare now):

![outofbounds](https://user-images.githubusercontent.com/17566547/34644240-30ed0538-f33b-11e7-8e2e-47575e75b95f.png)

Playing v0.9.8
Using best Hai atomics, chased it for three minutes (and all this time it pointed away, accelerating, I assume). One can see in the radar how far everything else is.

**Update:** Still playing around. Now that I did catch up to her, this pirate boat behaves like my escort. It doesn't try to run away. It doesn't try to attack. It turns to face direction I'm facing, and accelerates along side when my flagship accelerates.

![faithful](https://user-images.githubusercontent.com/17566547/34645413-a183c2b8-f355-11e7-870c-9577b06b3492.png)

Still with me, my faithful friend.
And then, on our return trip, my real escorts managed to catch up and disable the boat. Snif.

**Update 2:** After reloading some thirty times got similar situation (these always spawn, because I have a merchant to escort) and this time confirmed that at one point far away Fury starts to behave like an escort. It runs further away because flagship is moving that way. If flagship turns around, Fury turns around. And it still had missiles, it just didn't fire them on me or my escorts, as evidenced by leading it back to the center of the system — pirate Fury immediately opened fire on Merchant ships. Well, it tried (launched missiles facing them). My flagship was closer, so missiles circled around and homed in on me. About the same time enemy contact warning sirens finally blared.

Here's the save if someone's interested:
[Test~RunawayFury.txt](https://github.com/endless-sky/endless-sky/files/1609429/Test.RunawayFury.txt)

I'm not a programmer, but I'm guessing this is very much an AI problem.

**Comment by Staferfield** [comment]
This happened to me as well, 3 times if I remember right.
I'm playing on steam build v0.9.8

The first time is just like what happened to @Tadrix, I was just chasing a random Fury equipped with missiles far away from the center. Then it suddenly stopped, I thought it's running out of misiles but when I got closer it somehow acted like an escort.

The second time is when I'm attacking pirates and then running far away the center because I got chased by a large number of pirates. But when I went closer to the center I noticed these two.
![20180105175841_1](https://user-images.githubusercontent.com/25031487/34667045-a710d6b6-f4aa-11e7-8e1c-5ab76f3e4399.jpg)
That Leviathan is equipped with missile and torpedo, but I don't know about that hawk (or was it berserker?). They just get stuck there without moving or attacking, . I'm not sure if they acted like escort if I get closer on it, I didn't care and just disable them at that time.

The third time is when I'm doing flamethrower mission, I was bored so I used korath banisher and pushed that poor Fury far far away from the center. Before it was disabled, it stopped moving and then acted like escort. I don't have any screenshot though. I tried to do the same thing for other Fury but I guess it's just a rare bug, they will just jump to other system.

**Comment by endless-sky** [comment]
The "invisible fence" boundary also keeps you from kiting slower ships. In Escape Velocity, you could use kiting to destroy pretty much any ship that had a shorter weapons range than you because they were too dumb to give up on following you. That made combat a lot less interesting because there was such an easy way to "cheat" and win any battle.

**Comment by jafdy** [comment]
What about having them ignore the boundary if they can hit you when you cross the boundary and have them return to the center if they can't.

**Comment by Tadrix** [comment]
**Update 3:** Fury ran away and then stopped. This time I didn't bother to chase it and lined up my ships to jump to the next system, but, out of curiosity, did target the Fury to see what it's doing. It lined up perfectly. When my fleet jumped, pirate Fury jumped with us, and then became aggressive.

**Comment by tehhowch** [comment]
Were you beyond the "fence"? if so, #3523 should address it.

**Comment by Tadrix** [comment]
The Fury was. I, on the other hand, never have been following it, was near the system's star.

**Comment by tehhowch** [comment]
The latest commit I added to #3523 should address it nevertheless, by making it return to the central region

**Comment by Tadrix** [comment]
Why is it that out of bounds enemies start to behave like friendly escorts?

**Comment by tehhowch** [comment]
They don't, unless they are from a mission. Hostile mission ships have the player as a parent, which is how they find you when they start in other systems.
These hostile escorts pick targets as normal, which is subject to a range and position check - if a target is too far away, it won't get selected (unless the ship searching is heroic), and if it is beyond the fence, it won't get picked either (unless the ship searching is unconstrained).

When it comes time to decide how to move, ships with a target move as though they take no orders. Otherwise, they rendezvous with their parent (and if they are a parent they would choose to land or jump).

**Comment by Tadrix** [comment]
Maybe give these hostile escorts _gather_ order? If it is escort mission, then gather around escortees, if not, then around player's flagship. Maintain this order while ship has no targets. When ship has active targets, it reverts to its usual behavior, and when there aren't targets anymore (because on its way to player it, for example, got involved in a fight with some merchants who were defeated or successfully jumped away), renew gather order. This will ensure that when hostile has nothing to to it will pursue its mark across the system.
