### ISSUE TITLE
Pause sound effects when bringing up certain UI panels

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#351]
If you go to the map while jumping, the gfx are interrupted but sfx are not.
A possible solution could be to simply restrict changing view while jumping (as opposed to simply pausing the sfx).

**Comment by Pointedstick** [comment]
I rather like being able to access the map while jumping.

**Comment by wkoot** [comment]
So do I, but every time I get back to the normal view its still stuck jumping.
Otherwise, perhaps let the gfx/state continue until actually entering the next system and then pausing ?

**Comment by endless-sky** [comment]
Basically, this would mean pausing the sound effects when certain dialogs are displayed, and then making sure they get unpaused when the dialog is closed. It's definitely doable, but it could get complicated if I ever want to add UI sound effects.

**Comment by wkoot** [comment]
Is the other option (not interrupting jump gfx) viable? Main reason to pop up map when jumping is because it's a waiting moment.
Note that in EV Nova you can simply not open the map when jumping (sadly you cannot even toggle the map overlay); I assume they had a similar dilemma

**Comment by AdamKauffman** [comment]
Hi, I'm new here. Both to this project and to C++. Please excuse any atrocities I have committed to the code. 

I have a patch that shows simple pause and resume of all game effects without limiting music and UI effect. Music and UI each have a dedicated ALuint source that is not a member of the main sources vector. In my brief testing I have seen some strange behaviors and it might just be due to the fact that I have no idea what is really going on here. I would guess that there is a race between my pausing and the Audio::Step thread. I believe much of the strangeness is due to fading sounds and looping sounds. Sometimes they pause and resume cleanly. Other times they don't. I'd like to get the code out here so that anyone else working on this issue can see that I've made good progress. 

I'm not sure this patch is "pull ready". What's the best way to get testing\opinions? Take a look at my fork. Let me know if I should create a PR, if that's easier.
