### ISSUE TITLE
Make basic aspects known in the tutorial

### ISSUE THREAD

**Issue by Brick63** [endless-sky/endless-sky#3513]
I recently got a friend of mine into the game and they said later that their main problem was that the tutorial wasn't very good so could this be a possible aspect that is in need of an update

**Comment by Bladewood** [comment]
It'd be more helpful if you list which particular aspects are confusing or unclear or left unstated.
Keep in mind that while we want the tutorial to actually be helpful and informative, some aspects are more useful than others, so some are omitted for brevity.

**Comment by Brick63** [comment]
I had to tell them where to find the controls and how missions and the map worked.

**Comment by mdsmestad** [comment]
This would be helpful fir new players. My brother in law tried the game, but got frustrated and stopped playing because he didn't realize you needed to jump to a new system. He tried to get there by flying his ship in that direction on the the map.

Poor guy tried to get there for an hour and then gave up. It was a funny but understandable mistake

**Comment by Brick63** [comment]
Yeah tried that for my first 15 minutes so I can understand the pain

**Comment by KiLEdEnNis** [comment]
> He tried to get there by flying his ship in that direction on the the map.

I did that for like 15 mins when I was new (I knew how to jump, but was out of fuel in an empty sector), so I can partially confirm this

the tutorial missions are more about how one should make money instead of base gameplay functions, and while the bottom left hail area shows "press J to make a jump" and the game does have a few pop-ups in on-planet areas, it still lacks quite a bit of information a new player should know

**Comment by Wrzlprnft** [comment]
1) People have to read in this game. This is one of the things the tutorial pop-ups teach them. They either read in there that you have to press J, or, if they ignore it, they read that there is the J key for Jumping in the keybindings. Someone not capable of finding out about this will almost never ever discover the pure beauty that lies beneath the  shallow buisness-fight-simulation.
2) Endless Sky, the game as well as the person, MZ, lies focus on not breaking immersion. i had a pull request for a personship once, that, even when i would overcome the failures it had, was very unlikely to be accepted, because it would aim to break immersion to remind the player to make a pause and only would be able to appear after 4 hours of continous playtime(which i wasn't able to code)). The player manual outside of the game is seemingly a concious choice.
3) As far as i see it, a extended tutorial just extends the inevitable “what shall i do now?“. this is one of the main things for me in the game: it doesn't tell you what to do. the faster this question is thrown at the players, the less time they will waste if they don't want to play such a game.

I think a link to the player manual. A shiny button in the main menu wouldn't hurt though.

**Comment by jafdy** [comment]
I still think the reason people don't know to use J to jump is because they first try to learn the game by trial and error and then when that fails they can't find that helpful pop up that told them how to do it. Going to the preferences are obvious enough but I think making it easier to get the instructions back would be a good thing.

**Comment by Nescio0** [comment]
Wait, is there a tutorial? 

> He tried to get there by flying his ship in that direction on the the map.

Yeah, I also tried that when I was new. I think I simply closed the game after a minute or two and relaunched then. If you don't know the keyboard shortcuts the game is quite difficult. Perhaps the preferences/controls menu could show up by default for new players?

**Comment by Amazinite** [comment]
>Perhaps the preferences/controls menu could show up by default for new players?

Something I've never understood is why people don't reflexively check the controls of a game they've never played before, especially if they don't know what they're doing once they start playing.

Aside from not knowing the controls because you don't read and don't look, there are a number of things in game that *never* get explained, and without help they can be difficult to understand. Here are a few things I have written down that could be added into the tutorial
* Explain the raid system (more freighters and less fire power leads to being attacked)
* Explain how being unarmed leads to pirates ignoring you more
* Explain how checking the spaceport can lead to missions (instead of just implying it through having the James missions continuing through the spaceport)

Those are three game mechanics that I'm sure could be explained in the tutorial and aren't immersion breaking, like describing how to do something like compare two outfits or ships while on the map, another mechanic/shortcut that isn't explained anywhere.

**Comment by Brick63** [comment]
ill say this 
1: how would new players know to check preferences for the controls especially if they are new to gaming
2: even reading everything the game makes obvious that you need to read it doesn't tell you how to jump unless you look in a certain part of the screen
3: simply telling the player the controls wouldn't break immersion much and it might help more players not drop the game before even completing the tutorial

**Comment by Brick63** [comment]
tutorials are supposed to lay bare the controls of the game and how it works and plenty of games have good immersion while also having good tutorials first example i can think of is skyrim which tells you how to move with popups on the screen and other controls without breaking the immersion of how you need to escape a burning city

**Comment by Amazinite** [comment]
>how would new players know to check preferences for the controls especially if they are new to gaming

Well if someone is new to gaming then I'd be surprised that Endless Sky is their first game.  As for how a player new to the game itself would know, I would hope they know that the universal pause/menu key is `esc` and to go to preferences from there if they don't understand the controls and care enough to look for them.

>even reading everything the game makes obvious that you need to read it doesn't tell you how to jump unless you look in a certain part of the screen

A help dialog pops up right on screen once you've launched for the first time and tells you how to jump, so I don't know what you mean by this.

**Comment by Brick63** [comment]
first point: it can happen 
second point: been so long since i did the tutorial i forgot and must have missed it while doing a screen-share with said friend
also as a realization on my part i don't mean tell them everything you can do but just a popup at first launch showing the controls and that you can change em in preferences just so we don't have the aforementioned flying towards the system to try to get there

**Comment by Nescio0** [comment]
> the universal pause/menu key is esc

Unfortunately, no. I've checked out the few games I've installed right now (0AD, ES, Mahjong, Mines, OpenTTD) and ES is the only one which uses `esc` in this capacity; `esc` is typically used to deselect your current selection and seldom has another function. The game menu/options/preferences can often be toggled with one of the function keys (e.g. F10). And a great variety of keys can be used to pause a game: Pause, Spacebar, a function key, P, Ctrl+P, etc.
More importantly, in many games the keyboard shortcuts are just that: keyboard shortcuts. Usually there is a button somewhere you can click on instead of pressing the relevant key. While this is occassionally the case in ES (you can either click on Spaceport or simply press P), there are no Jump or Map buttons when travelling in space, at least not as far as I'm aware of.
Even though it might seem obvious to us who're used to the game now that a new player ought to look up the controls beforehand, apparently not everyone does, therefore it doesn't hurt to automatically display the preferences for new players.

**Comment by Bladewood** [comment]
> universal pause/menu key

- Minecraft
- Terraria: esc
- \[pretty much any `Source` game, e.g. TF2\]: esc
- King Arthur's Gold: esc
- Space Engineers: esc
- Reassembly: esc

It's not universal, but it is extremely common.

**Comment by jafdy** [comment]
All biowere, paradox, stardock, most other EA, nearly every one-off game I've played (except one that helpfully tells you that the menu is on F10 whenever you press esc), Fraxis, 2k. Not forgetting Keen, Squad, valve, Zachtronics, Kerberos. It's not universal but it's fairly close.

**Comment by Amazinite** [comment]
Dare I invoke [wikipedia](https://en.wikipedia.org/wiki/Esc_key)?

>In most computer games, the escape key is used as a pause button and/or as a way to bring up the in-game menu, usually containing ways to exit the program.

**Comment by Brick63** [comment]
as i said players who are relatively new to gaming may not know these things and that's why most games still tell players the controls at the start cause it may be their first.

**Comment by Nescio0** [comment]
**universal** *adjective* relating to or done by all people or things in the world or in a particular group; applicable to all cases;

While many games use `esc` in this way, plenty of others don't. It's perfectly possible ES is actually one's first game.
The point is not all new players will behave as we might expect them to. This discussion shouldn't focus on how what they are doing wrong, but instead on how the tutorial could be improved.

**Comment by Amazinite** [comment]
>“universal adjective relating to or done by all people or things in the world or in a particular group; applicable to all cases;”

"**hyperbole** *noun* exaggerated statements or claims not meant to be taken literally."
(I couldn't resist.)

**Comment by endless-sky** [comment]
Okay, maybe 4f1c605 will help players who are confused and think that they can get to other systems without a hyperdrive.

I can still remember the feeling of playing Escape Velocity for the first time, and the shock when I realized that the game was not going to tell me what to do next or what direction to go in (open-world games were a less well-known concept back then). I want Endless Sky to capture some of that same feeling. For the players who are most likely to enjoy this game, being flung out into a strange universe and having to figure it all out from scratch will be enjoyable, not (just) frustrating.

**Comment by Brick63** [comment]
just had said friend look at the new additions and they said that those messages are really helpful so im going to be closing the issue

**Comment by Zireael07** [comment]
I looked at the commit, and I have to applaud the way those are handled - really neat way of showing the newbie what to do without handholding through a traditional tutorial!
