### ISSUE TITLE
Make radar view affected by heavy cooling and radar jammers just like missiles

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#352]
To go along with the missile jamming idea we have going on  (#346), we could extend the concept of multiple tracking methods to the player's radar view. Your "radar" could, by default, scan using IR and radar. This opens up the possibility that a ship with a radar jammer and no net heat generation would be invisible except while visible on the screen! This would produce a sort of "poor man's cloaking device" effect. The player could do the same thing to travel more easily in pirate systems, for example, because most pirate ships would probably not be equipped with extremely sophisticated scanning equipment and would ignore the player unless their ship got close enough to the pirate ships to see them on screen.

Once this concept is established, is would enable the creation of new outfits to give your ship better scanning capacity, like gravimetric scanners, omnidirectional cameras, sensor stations, and things like that, which would give a ship more methods to reveal these otherwise invisible ships.

**Comment by brick96** [comment]
Tracking drones :D

**Comment by dplepage** [comment]
EV also had various radar improvements as purchasable upgrades - without a Density Scanner your radar view wouldn't distinguish large ships from small, and without an IFF Decoder it wouldn't color-code ships based on hostility. Maybe outfits could allow you to tweak that, as well? E.g. with the right sort of scrambler you might be able to make your Bulk Freighter look like a much smaller ship on radar (and therefore attract fewer pirates).

**Comment by endless-sky** [comment]
It never made sense to me that in Escape Velocity, there were certain
outfits that you would always want to install in a ship, because they had
no disadvantage other than cost: in particular, the radar improvements and
the auto-refueler. I really don't see what that added to the game. If the
IFF decoder or density scanner had power or space requirements, so that you
might have an incentive to fly without it, that would be different. But
even then, those are such basic functions that I think any pilot would want
them.

**Comment by Tufton** [comment]
I agree on the auto-refueler, that was stupid, like...install this so you
don't have to click a button when you land.  OK....cool?  Now radar
upgrades that take outfit space might be something worth looking into.  As
long as it takes outfit space and has some other drawback (less weapon
capacity? high energy usage?) I think it would be an interesting option on
some ships, especially ones that rely on identifying and engaging targets
from outside visual range or that rely on being able to beat missile
jammers/cloaks/whatever with stronger radar or something.

**Comment by dplepage** [comment]
I agree about the auto-refueler, but the thing I liked about the radar upgrades was that at the beginning of the game you didn't know what you were missing them until you made enough money to buy one, and then suddenly you couldn't imagine how you ever survived without one. But yeah, after you save up enough to get them it just became another button you had to click every time you bought a ship.

Radar upgrades would make a lot more sense with @Pointedstick's suggestion, though - you have to choose whether you want to buy big bulky sensors that might let you detect tiny ships or cloaked ships, etc.

Another thing I liked in EV was that some systems had natural background interference where your radar screen would flicker with static, sometimes so severely that you couldn't use it all. Radar upgrades also make more sense if that's a possibility - you trade some outfit space for better sensors if you're going to be spending a lot of time in high-noise systems.

**Comment by Pointedstick** [comment]
Yes, that's a good point @dplepage. EV Nova even had a "murkiness" level that affected the main view screen itself in certain systems that were like in a nebula or something. I liked that too. Made the galaxy more interesting and less monotonous.

**Comment by frameworld** [comment]
@dplepage I agree.
Also: Scanners only need to be installed in one ship for a fleet. (combat: take out the scanner-ship?)

Holographic-projectors, extend-able hull parts and thrusters that are just slightly jammed but trick somebody into thinking it is a bigger version that is stronger jammed.
These equipments trick your enemy into thinking your fleet has a big escort.

Maybe some pirates even attack parts that are intentionally obscuring volume like lightweight paper and miss your ship's vulnerable core parts if they have not the right scanner equipment. Critical shots.

**Comment by dplepage** [comment]
There's also the potential for multiple kinds of noise in a given system. Basic murkiness would just add static to the radar, but other effects could include:
 * Distant ship dots appear offset from their actual positions
 * Ship dots are large and blurry, indicating uncertainty
 * Some fraction of the time, ship dots actually disappear (and homing weapons cease following them, etc.)
 * Some fraction of the time, ship dots appear in wildly wrong places (e.g. reflected across the axis of the observer, or rotated around the system center).

Strong sensor interference would force players to fight without homing weapons or auto-aiming (maybe even without turrets in extreme cases), adding considerably more variety to exploration and combat.

**Comment by Impurethinker** [comment]
I'm all for adding interesting systems, but 'hiding' in space is basically a space opera fairy tale. Without magical cloaking tech or active ECM even the smallest FTL capable ship will stick out like a blazing flare of energy to even the most basic sensors from a huge distance away. 

The fact that weapons can even miss is stretching credibility given that computers (thus targeting) should be way more advanced this far in the future.

Warfighting in this sort of hard sci-fi setting really ought to boil down to:
1) effective range of weapons
2) your ability to soak damage (shields or hull)
3) your ability to dish out damage (thus compensating for your target's #2)
3) your ability to quickly go FTL, to get the hell of out Dodge.
4) Possibly the ability to 'outrun' the fuel supply of any guided missile coming after you, but I'd propose that any useful missile in space is by design going to have to run faster than any ship possibly can in sub-light. Maybe if their fuel was limited and you were at extreme range could you outrun and dodge any missile.

**Comment by Tufton** [comment]
While those points are valid, I think that may be venturing too far into
the realm of hard science fiction and out of the world of sandbox video
games.  I guess the assumption is that with the missile upgrades, there
would be corresponding ECM via scrambling heat signatures/electrical
signatures/mass hiders(?).

You are of course right about the accuracy of weapons in a vacuum, but we
would have to completely overhaul combat to be more like EVE Online, which
if I recall correctly has a fairly "realistic" combat system taking into
account relative velocity, tracking, range, etc.  I think sci-fi realism
may have to suffer somewhat in favor of streamlined game design and
entertainment value.

**Comment by Pointedstick** [comment]
The entire physics model is wrong if we really want to get pedantic about realism; you should be able to infinitely accelerate for example. The most plausible extrapolation of space combat is that it would be 100% missile based and guns would be pointless because ships would be destroyed before they made it to gun range. But that wouldn't be very fun!

**Comment by johndh** [comment]
"The fact that weapons can even miss is stretching credibility given that computers (thus targeting) should be way more advanced this far in the future."

Given that real space battles, if they ever happen, will likely take place at astronomical distances, I think missing would be a huge problem to overcome.  If your target is 10 light-seconds away, then you're seeing where it was 10 seconds ago, so your targeting computer has to guess where it's going to be based on that data.  If your weapon acts at light speed, it takes another 10 seconds to reach the target.  If, in the last 20 seconds (10 seconds to see it, 10 seconds to reach it), the target has moved in a way your targeting computer didn't predict, you've missed.  A self-guided missile will obviously be slower, but better able to correct its mistakes.

While I think a hard sci-fi game would have a lot of potential, I don't think that's the kind of game ES is aiming to be.  With FTL travel, force fields, humanoid aliens, space cloaking, etc., it's pretty far toward the soft end of the spectrum.  It's high-seas sailing action in space and it's fun that way.

As far as hiding in space, I don't think anything short of a "black body" cloaking field (Star Trek style) would make any sense.  Even if you've got enough cooling to reduce your net heat to zero, your engines are still sending out a lot of energetic reaction mass, and all of your internal systems are radiating various electromagnetic radiation.  If all of your systems are shut down and the hull of your ship is at a temperature equal to the space around you, anybody with a telescope can still spot hundreds of tons of metal floating in space.

This applies to ships, at least.  A mine or stationary drone might be able to get away with a thick coating of absorbent paint like modern stealth aircraft, or disguising itself as an asteroid until a target gets close enough.

**Comment by Impurethinker** [comment]
Far enough points. I'm not arguing for a 100% accurate model of physics. Hell I haven't even done enough combat to take note of the miss chances really. I'm just saying I'd rather have highly accurate weapons and soak damage via shields vs 'space dodging'.

I was mostly counter pushing the idea this game needs to have more sensors to counter any sort of 'murkiness' or some kind of fog-of-war mechanic. By default you really out to see everything out there as long as some agent isn't screwing with your sensors.

Seeing non-cloaked ships (because those are magic you know), shouldn't be an issue at all. Identifying who and what they are would the the possible problems.

Deep cargo scanning, sure.
Active counter measures vs enemy sensors, sign me up.
Some kind of masquerading tech that lets you like like you are in a different kind of ship until they get close to you? That would be cool.
Possibly something like a pulsar that messing with your sensors would be cool too.

I have a pet peeve about nebula hiding though. You can be in the middle of a 'dense' nebula in space and you would literately not know the difference. Nebula are dense relative to the rest of space. They aren't like being in an airplane and flying through a thunderhead.

**Comment by Pointedstick** [comment]
> Some kind of masquerading tech that lets you look like you are in a different kind of ship until they get close to you? That would be cool.

That *would* be quite cool. I can imagine that merchant ships as well as pirates would be interested in such a thing.

**Comment by Impurethinker** [comment]
You would probably need to keep in in the same weight class for the masquerade thing.

**Comment by frameworld** [comment]
johndh> While I think a hard sci-fi game would have a lot of potential, I don't think that's the kind of game ES is aiming to be. With FTL travel, force fields, humanoid aliens, space cloaking, etc., it's pretty far toward the soft end of the spectrum.
At least the story could be.
Impurethinker> I'm just saying I'd rather have highly accurate weapons and soak damage via shields vs 'space dodging'.
Agree. Dodge-computers vs Targeting-computers.
But if a weapon makes more damage at short distance or against "static" targets (floating wrecks which are about to explode), you could also have navigation computers keeping yourself at a static distance to your target if your engines support it.

Which means that the faster target could choose the distance at which to engage, the formation would have more AI assistance and ... more things.

And then the question arises "How far should it go?"

**Comment by LocalGod79** [comment]
i have just read the discussion in its entirety (again), and missile jamming has been implemented, but we're unsure of how far that effect should be extended to the player's radar screen, and how that information should be represented on the radar.

as you can see, i've raised a new issue that this can tie into (and offers a baseline feature that proposed outfits could offer).

perhaps the cargo and outfit scanners get a buff?  or redo the scanners system entirely, and basically have a scale of outfits that accomplishes varying degrees of *added* cargo/outfit/heat/radar/"energy signature" scanning (with hulls containing a base attribute for some, tuned to their role/manufacturer)?

for example, it would make sense that the Hai hulls would have more energy signature scanning built into some of the hulls, and possibly even the Ion Cannon itself.

the Korath are engaged in a civil war with high-heat outfits, so it would make sense if their sensor technology revolved around i.r., and more of the "heat scanning" attribute was present baked into their hulls.

**Comment by endless-sky** [comment]
I'm a bit worried that ship radar jamming would be very annoying. Does it cause you to lose a target lock every time the target ship blinks out on radar? Can a ship still disappear from radar even if it's visible on the screen? And, how do beginning players know that the radar is not just buggy?

Missile jamming adds something to the game because it adds an incentive to fly a small ship, or a ship that runs very cool. And, it adds more variety in terms of which missile types are dangerous to which ships. But as for ship radar jamming, I'm just not sure what it would add.

If ship radar *were* made fallible, rather than having it blink in and out my preference would be for it to depend purely on range to the target, with radar jamming on a ship allowing it to fly closer before it is detected. That would add an interesting tactical effect of not knowing what is going on beyond your radar range. But even that may just end up being annoying.

**Comment by Hyratel** [comment]
"Only one person would give me the Raspberry."

**Comment by Alkallid** [comment]
what
