### ISSUE TITLE
Boarding counter attack event

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3520]
So as to make Defense actually useful
I suggest the following mechanic : 
**a low % of enemy ships (pirates ? marauders ?) would have huge offensive capabilities (grenades/ nerve gaz)**

On boarding the ship you're prompted with a sort of choice UI : 

- "Seeing their ship in poor shape the enemy crew was actually prepared to go on the offensive as soon as you docked. You already see them finishing to place explosives by your airlock. Captain, what are your orders ?"

Giving you several option : 
 
1. **emergency retreat**, _blow up "bridge"_ (lose 10% hull, lose 10% crew, unboarded, chance for enemy ship to blow himself up increased, can't board anymore until landed)
2. **emergency retreat**, _start engines breaking the bridge_ by sheer force in the process (can't board anymore until landed, lose 45% hull, crew 3% casualties)
3. **retreat ASAP**, _hold them off while you retract the "bridge"_ (get a bonus to resilience of your crew and a good debuff to killing off their crew)
4. **defend** (usual defend option except the  #surprise element makes your crew lose a bit more % in defensive rating 5%? or more ?  )
5. could even think of more options given by defensive/offensive outfits (say if you want more)

Also this behavior would be race/ship dependent, hence can be disabled for say ... reasonable races & thinkers (robot AIs, advanced races) ...

Finally suggest introducing **resilience**, or making _attack_ the rate of killing enemies & _defense_ how resilient your crew is:
the point being that an imaginary race with 0 attack & 1000000 defense/resilience could never lose a single man to the enemy, but couldn't kill anything either  (example : a "ghost", planar or "gaseous" race
Contrary to the current situation where a 1000000 defense ship would kill your crew if you attack.

**Comment by tehhowch** [comment]
in v0.9.9 governments can set their "crew attack" and "crew defense" attributes to arbitrary values, so i don't see any reason to add "resilience"
refs #2708 

Defense is useful for the player if they attempt to capture a ship and then the battle does not go in their favor. Unless of course that player feels it is not cheating to "try again" after death from their own mistakes and simply reloads (which is a perfectly valid mindset).

**Comment by whismerhill** [comment]
I'm not sure how it's all calculated. as I see it crew defense is basically a power value when you're attacked. while "attack" is a power value when attacking.
"resilience" on the other hand is more like : it'll take more turn to achieve the same number of death the end of the resilient race just a thought.
also reformatted is that clearer ?

**Comment by tehhowch** [comment]
- Regarding offensive H2H weaponry on some hostile ships: #3427 
 - Regarding "no boarding until you land again": This mechanic is unnecessary - losing crew is sufficient penalty to discourage further boarding:
   - loss of maneuverability makes boarding take much longer to initiate
   - once a ship has boarded a faction, that faction will target it if given the chance, even if it's unarmed
 - Regarding damage to the ship which is boarding the other: could be added

Your guess is correct, attack = power if opting to attack, defense = power if opting to defend. Combat then checks that at least one group chose to attack (it ends otherwise), then compares strengths (roll 0:A vs roll 0:B, whoever rolls the lower number loses 1 crewman). Changing this is unlikely.

At its core, you're basically asking for #3346 with a random chance of needing to fight just because you boarded. Which could be added.

**Comment by whismerhill** [comment]
the "can't board anymore" was more to reflect the fact that the bridge with which you board got destroyed, although realistically, a single ship (even small) could have several of those. Hence I'm fine with all of your observations.
