### ISSUE TITLE
Large passenger missions and escort missions pay waaaay too well

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#356]
I just transported 11 people 6 systems away and got paid 155,000 credits. That's a huge amount of money for practically no work. Then I escorted a ship 4 systems after defeating a couple of wimpy Furies and Headhunters and got paid 120,000 credits.

These rewards are seriously outsized compared to ordinary cargo transport missions. For example, at the same time I was offered a job to deliver 104 tons of goods 4 systems away for 78,000 credits. Any heavy cargo ship capable of taking that mission would easily be combat-worthy enough to fight off two or three interceptor-class pirates and make a lot more money doing the escort mission itself while fillings its cargo bay with enough goods to sell on the destination planet to make at least another 10 or 20k profit. The same can be done with the passenger missions which also do not fill up your cargo bay.

I'm willing to do the work make these changes; posting it here for discussion first.

**Comment by endless-sky** [comment]
For the purpose of payments, one passenger counts the same as 10 tons of cargo. That's intended to balance the usefulness of bunks and cargo space so that the Shuttle and the Star Barge have equal earning potential.

If that 104-ton mission were 6 jumps away instead of 4, it would have paid roughly the same as the passenger mission. It's possible that the fixed bonus amounts for the large passenger missions need to be reduced, but I don't really see a need to change the baseline payment formula.

As for escort missions, they're rush missions *and* they require waiting around for the ship you're escorting. The payment might be a *little* high, but the fact that escort missions are all rush jobs is a huge disadvantage because it means you often can't pile up a bunch of them at the same time.

**Comment by Pointedstick** [comment]
I find myself piling up escort jobs all the time. I frequently manage to get multiple escort jobs to the same planet or one planet away. And the timer is pretty lenient; you have more than twice the time you usually need, so it's rarely a big factor. Once you've killed the initial pirates, it's smooth sailing.

As for passenger missions, the reason why I think they're superior to cargo missions and therefore pay too much is as follows:
* Ships with passenger capacity still have a cargo bay, so passenger missions can always additionally include some commodity selling on the side to make extra money. This can amount to an extra 15k or more if you manage to get a good trade route and have a ship with even a moderately-sized cargo bay (40 tons).
* Carrying a lot of passengers doesn't reduce your ship's maneuverability the way loading up a cargo bay does.
* Focusing entirely on passenger capacity means you can transform your unneeded cargo capacity into extra outfit space; the same can't be done for unwanted passenger capacity.

**Comment by endless-sky** [comment]
I've checked in a change that reduces the bonuses somewhat for the jumbo missions (db2b0fd).

I'd also be open to reducing the escort payoffs a bit, maybe 50 / 75 / 100k rather than 60 / 90 / 120k. But for an early player, those escort missions may very well be challenging enough to warrant the higher payment, so I don't want to reduce it too much.

**Comment by Pointedstick** [comment]
I think those are better prices. I'm also experimenting with making the jobs more interesting by spawning more pirates than just those who are instantly there as soon as you take off from the source planet. At the moment, once you defeat the initial baddies, all the excitement of the job is pretty much finished.

**Comment by endless-sky** [comment]
Good idea. That would mean that weak players can try to outrun the pirates, but stronger players who stick around to destroy the initial fleet will have to fight off a few others, too.

Just be sure to test the "small" missions in a Sparrow to be sure they're not suddenly too difficult for an early player. I think it's reasonable for the "large" escort missions to expect at least a Hawk and the "extra large" ones to expect a light warship.

**Comment by Pointedstick** [comment]
For example, here are four escort missions to adjacent systems that I successfully completed, earning more than $400,000 credits in the space of about 5 minutes.

<img width="238" alt="screen shot 2015-12-02 at 8 13 55 pm" src="https://cloud.githubusercontent.com/assets/1097249/11580726/7577f7a2-99f7-11e5-9611-daae18a3e63c.png">

I got them all on Porrima. By batching up the missions, I had four escorted freighters worth of anti-missile turrets and supporting meteor missile fire to help me defeat all the pirates who showed up.

**Comment by dplepage** [comment]
Maybe stacked missions could merge the difficulties of their corresponding pirate fleets? E.g. three small escort missions wouldn't mean three times as many enemy Argosies, but rather that some of the Argosies got promoted to Leviathans.

**Comment by Tufton** [comment]
I feel like the real answer to this problem is just preventing the player
from speed jumping through all the systems then waiting at the destination
point.  That is absolutely the easiest way to complete this mission type in
my opinion, but it goes against the spirit of an "escort" mission because
you aren't really escorting anything, just playing catch me if you can.  If
we could code it where you actually had to wait and jump with your escort
ships, it would force the player to actually defend them and give pirates
time to engage.

**Comment by Pointedstick** [comment]
That is an excellent idea, @Tufton.

**Comment by frameworld** [comment]
* Ships with passenger capacity still have a cargo bay, so passenger missions can always additionally include some commodity selling on the side to make extra money.
But each landing on a planet costs a day and some game time. You also may not get as good trade routes.
* Carrying a lot of passengers doesn't reduce your ship's maneuverability the way loading up a cargo bay does.
Cargo mass is usually only 1/4 on a Warship and 1/3 on an armed freighter.
* Focusing entirely on passenger capacity means you can transform your unneeded cargo capacity into extra outfit space; the same can't be done for unwanted passenger capacity.
Has the disadvantage that you can't purchase and sell passengers as fluid as cargo.
Cargo is available everywhere and any route you can use the full space, but passengers are limited and stick around for longer if you stack them up (different locations).

I also agree with @Tutton 's idea to require to wait for escorted ships to jump-align in these missions.
Still, it is a bit annoying once you got scram-drive and the improved ramscope to effectively reduce the drive's drain.

I would really appreciate a better formation-AI.
* When I gather my escorts around the flag-ship, they tend to fly erratically around it
* When they are on hold position, after 1 jump they spread out of each others vision and weapon range.

BTW: I would like an option to convert passenger into cargo space, cargo into passenger space or passenger into equipment space.

**Comment by endless-sky** [comment]
0.8.9 is now released with rebalanced mission payments, so I'm closing this.
