### ISSUE TITLE
number of decimals (& outfit expansion)

### ISSUE THREAD

**Issue by whismerhill** [endless-sky/endless-sky#3565]
I think the number of decimals should be limited (maybe to 1 ???)

![ryjntpzjsaoz2k11bbm5kq](https://user-images.githubusercontent.com/17818248/35004357-11dd2abc-faf0-11e7-9aed-ee3e0ab73bdd.png)

reason is : 
 - player doesn't need ultra precision values
 - due to language differences commas & dots & such values get confusing
 - it's also small which adds to the confusion
 - in particular it's also because there's **3 numbers after the dot**
 - this happens because of outfits expansions
 - all this makes it be read as 47000 instead of 47

so that's why I suggest the precision to be limited to one or two decimals (or heck even 0 decimals is fine by me)

EDIT: of course I'm talking about rounding in display only

**Comment by Nescio0** [comment]
Most outfits do not require any decimals to be displayed.
The Emergency Ramscoop, Interference Plating, and hand-to-hand weapons require one decimal to be displayed.
The Outfits Expansion and Cloaking device require two decimals to be displayed.

Consistency is important. Even though limiting decimals might be sensible in specific instances, it might not be a good idea in general.

**Comment by accursedCursive** [comment]
There's a simple solution to this: Have it so that numbers can only be added past the decimal point if it does not bring the total number of digits (discounting leading 0s) up to 3.
12340 = 12340
1234 = 1234
123.4 = 123
12.34 = 12.3
1.234 = 1.23
0.1234 = 0.123
What this means is that the last digit after the decimal point represents about 1% of the value it's a part of, which I think is just the right level of precision.

**Comment by KiLEdEnNis** [comment]
I don't mind the digits, but maybe rounding up to whole numbers could be a (hidden) preference?
