### ISSUE TITLE
Sell all button never works anymore

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#357]

**Comment by thenerdfreak** [comment]
Using steam beta version

**Comment by endless-sky** [comment]
Are you sure that you're using an unmodified copy of the beta? It's working for me.

The keyboard shortcut for the "sell all" button changed when I added the "buy all" button, and because I use keyboard shortcuts to map mouse clicks to events, if you somehow were using the old executable with the new interface definition or vice versa, that would break the Sell All button.

**Comment by thenerdfreak** [comment]
revalidated steam copy and it works fine- dunno why it was different, didn't really change anything this time
