### ISSUE TITLE
PLEASE take out the little part of code that makes merchants murder the already-disabled pirate ships I'm in the process of boarding

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#358]

**Comment by Pointedstick** [comment]
Haha yeah, this drives me crazy too!

**Comment by endless-sky** [comment]
There's already code that has merchants ignore pirates that are not close to them, *and* that keeps them from engaging a target that is already disabled (but, not from stopping attacking a ship just because it's disabled). If you just take your fight out to the edge of the system like a civilized person instead of starting a brawl right where everyone is trying to get in and out of hyperspace, you'll find that everyone leaves your disabled enemies alone.

If I went further than that and made merchants stop shooting at pirates once they're disabled, they would basically be leaving disabled pirates lying around everywhere for the player to plunder for free.

**Comment by thenerdfreak** [comment]
I'm sorry that my lasers disable them near instantly before my slow ship can lure them ;D

**Comment by dplepage** [comment]
Maybe ships should have two levels of engagement - targeting (meaning they intend to attack it but haven't gotten close enough yet) and attacking (meaning they've actually fired at it), and ships that are merely targeting should disengage when the target is disabled?

It makes sense that a merchant convoy fighting a pirate won't stop firing until they've destroyed it, but when you disable a pirate on your own and then a merchant ship that wasn't close enough to join the fight earlier swoops in and blows it up right when you're about to finish boarding it, it just makes the merchant look like an asshole.

**Comment by Tufton** [comment]
Frankly I think it just adds another layer of difficulty to boarding and
looting ships, which if you consider that most people's complaint is that
it's too easy to get rich by boarding, I'm not sure it should be changed at
all. Wayward merchants and military blowing up your disabled ships was a
staple of the Escape Velocity series. Either get better at timing your
lasers, get a more maneuverable ship, drag/kite the targets further away,
or pick a system where other ships are less likely to interfere.  If I were
a merchant and a pirate ship was shooting me, I certainly wouldn't stop
firing until it was dead.  I'd consider it a blessing they don't just auto
attack all pirate vessels until death.

**Comment by thenerdfreak** [comment]
@dplepage this is what I'm talking about. Like I disabled it by my self, and the merchant swoops in and kill it, so i just disable and board the merchant (out of rage)

**Comment by dplepage** [comment]
@Tufton It's just a weird and confusing behavior. Why would a merchant fly out of their way to destroy an already-disabled pirate ship?

Even more confusingly, many times they won't - the only time they will is if they arrived in the system before you finished disabling the ship. This means that a tenth of a second difference in an event on the other side of the system can drastically alter their behavior, which is just bizarre.

**Comment by endless-sky** [comment]
How is that "bizarre"? If a merchant arrives and sees a disabled pirate, it
says, "Okay, looks like that situation is handled, I won't interfere." If
it arrives and sees an active firefight going on, it comes over to "help."

As far as the AI knows, your ships are no different than anyone else's
ships - it doesn't give you special treatment just because you're the
player. If it did, I think that would be more "bizarre" than anything else.

The AI also isn't remembering a history of everything that has happened
since it arrived in system, or looking at what other ships are doing to its
target - that would be way too complex, and the AI is already the most
CPU-intensive part of the game. So there's no way for the AI to distinguish
between the case where it has been fighting a pirate for a while and the
case where it only just decided to target that pirate. The AI doesn't know
who's done the most damage to that pirate. It doesn't even check whether it
was the one who disabled that pirate ship, or someone else. And even if it
did, it would look really odd if a bunch of merchants were ganging up on a
pirate, and then suddenly stopped firing because you came in and got "dibs"
on the pirate by firing a single shot.

**Comment by thenerdfreak** [comment]
what about a hail option that tells a  specific merchant/merchant convoy to "degress" or "flee"

**Comment by dplepage** [comment]
> How is that "bizarre"? If a merchant arrives and sees a disabled pirate, it
says, "Okay, looks like that situation is handled, I won't interfere." If
it arrives and sees an active firefight going on, it comes over to "help."

@endless-sky I agree with this behavior:
 1. A merchant who sees an ongoing fight should try to join, and 
 2. A merchant who sees that a fight is already over shouldn't.

The bizarre behavior is at the midpoint between these two extremes: a merchant arrives while a firefight is active, but the fight ends before the merchant can do anything about it. In this case, the merchant *should* treat this like case 2 - the fight was already over before they got there, so they don't need to interfere. Currently, though, they treat it like case 1, as though the fight were still happening.

The net result is that a merchant is willing to fly halfway across the system just to shoot up a bunch of disabled ships, even though the situation was clearly handled before they got close enough to "help".

I don't think fixing this requires giving AIs more memory, or treating the player ship differently from any other - the AI just needs one additional state, for "I haven't joined this firefight yet but I'm on my way to join it", and if they're in that state when they see that the fight has ended without them, they stop coming to help because they recognize that they aren't needed after all.

Or, alternatively, ships could automatically disengage from disabled ships *if they're out of weapons range*. This would still keep fights from leaving lots of disabled ships for you to board, because in most cases the disabled ships would be destroyed by the combatants that were closest to them when they got disabled. But in cases where a disabled ship was far away, the combatants wouldn't go out of their way to hunt it down and destroy it.

**Comment by endless-sky** [comment]
I checked in a change that makes "timid" ships (merchants, basically) stop targeting a ship if it is disabled and is more than 1000 pixels away (i.e. well beyond the range of non-missile weapons): b8c5e58.

**Comment by frameworld** [comment]
Sometimes I try to board, another pirate jumps in and my escorts shoot the wreck while trying to shoot that pirate.
In a realistic 3D-environment this would happen a lot less.

Instant-hit weapons could stop fire when they would hit a wreck.
There could be an option to have your own ships guard the target.

Or proper formation management to avoid your escorts over-killing the target.
Why are ships unable to use their steering thrusters as omni-directional light thrusters? Today some military fighters have thrust vectoring.

**Comment by thenerdfreak** [comment]
Sorry for the bump post but in reply to frameworld on 3d environments, I made a suggestion a little ago about making disabled ships shoot-through unless directly targeted. This would fix this case

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this. Plundering is already over-powered. Making merchants ignore disabled ships if they're far away was a reasonable change, but I'm not going to make plundering even easier than that.
