### ISSUE TITLE
Request for: Star Map Completion Percentage

### ISSUE THREAD

**Issue by HaraldusBluum** [endless-sky/endless-sky#3586]
Possible addition to the star map, number of visited systems.

"Star Map completion: ## in %"

**Comment by tehhowch** [comment]
There is a more interesting and useful metric already in game. Select a visited system and then click under the planet  info where it says `(has been visited)`.

I don't think adding a "competition percentage" does anything useful.

**Comment by mdsmestad** [comment]
@HaraldusBluum I don't think thats a good idea, the player should be left to explore with no clue how big the map is

**Comment by Amazinite** [comment]
Knowing how big the world is in my eyes would take away from the fun of the exploration. If you've only explored 4 systems but you see you're already 2% complete, then you know there are 200 systems in the game. I think it would be far more interesting if you didn't know the vastness of the galaxy, especially later down the road when the entire thing will be filled up, and when we might be able to travel to other galaxies.

**Comment by Amazinite** [comment]
The only way I can see this being exciting/useful is if we had multiple galaxies. Say someone explores the entire Milky Way and finishes all the content within it only to reach 20% systems visited. Now THAT would be exciting.

**Comment by jafdy** [comment]
They would also find out that human space is only about 4% of everything. Content shock?

**Comment by accursedCursive** [comment]
@Amazinite
You could achieve the same effect by making the current map take up a much smaller portion of the galaxy
No need to show how many systems have been visited, you can see how much of the galaxy you've explored, and you can see that it's a tiny portion.
I personally prefer big galaxies to numerous galaxies, because it feels like a challenge to explore the galaxy, and it's actually possible to put things in the galaxy that the player isn't going to quickly find such as a secret pirate outpost that's in a region of unoccupied space.
Spore implemented this perfectly: A galaxy had thousands of systems, most of them barren so that alien empires actually had some distance between them, and the sheer size of it made it possible to hide easter eggs that few players would find (A number of handmade planets, the Sol system, and a godlike being at the very centre of the galaxy).

**Comment by MCOfficer** [comment]
as much as i like realistically barren systems, i don't think it fits a game like, ES where a system without anything happening is of no interest at all. even if they are populated, systems can be boring as hell. for example, exploring coalition space was a pain to me, cause i know exactly that there's nothing waiting for me in the next system - not like korath space where the excitement is carried by the danger, or remnant space which is exciting cause it introduces new content.


that said, literally the only difference i can see between having all systems spread over multiple galaxies or clunked up in one is that the player can't anticipate that there's even more to discover - until he goes through a wormhole and is suddenly confronted with yet another blank map to discover.

one more difference: changing everything now would be an insane amount of work - and probably screw over all plugins in existance. i know that vaniall takes prioritiy over plugins, but given that there's actually a forum thread where mod authors can mark their territory, changing the entire map feels like a very destructive move that servers a goal which can be much more easily achieved by creating new galaxies.

**Comment by HaraldusBluum** [comment]
Ok I see and get the idea that showing the Percentage can be bad for the fun of exploring things.

On the other hand how about a simple Notification of let us say "You have explored all of Coalition Space" once you did (in story correlation as well). 

As much fun the sandbox part is, a little frame couldn't hurt IMO

**Comment by Amazinite** [comment]
At that point it sounds like you're getting into something like #301.

**Comment by tehhowch** [comment]
Further what says that the explored space won't get updated in a story later that adds new systems?

**Comment by jafdy** [comment]
That could be implemented by a mission and updated appropriately (by adding any added system to the mission requirements). Then it becomes a case of is it worth it.

**Comment by tehhowch** [comment]
>That could be implemented by a mission and updated appropriately (by adding any added system to the mission requirements). Then it becomes a case of is it worth it.

Absolutely, but it would certainly feel off if a game said you were at "100%," and then said "Psych! You're actually not done!" and reset the status on a number of systems that have been altered.
For this reason, I don't think adding any sort of completion mechanism / status will be useful - the player can't trust it to be accurate.

**Comment by KiLEdEnNis** [comment]
> "You have explored all of Coalition Space"

about this example, one would already SEE they explored all of Coalition space because there are no unexplored nearby systems, a notification would be redundant and not worth the effort except for a wormhole-heavy area, and even then it seems redundant and not worth the effort

**Comment by accursedCursive** [comment]
@MCOfficer Even in the current system, the player can't really anticipate there's more to discover.
You explore human space, keep exploring human space, and then suddenly you're in Hai/Korath space.
You keep exploring Korath space, then suddenly you're in Quarg space. Explore deeper, and without warning you're in a different kind of Korath space, then Archon space, etc.

There's never that crucial moment where the player realises that they are way outside known space, and could discover anything.
That's what barren systems are for, to space things out.
Also, barren systems leave future developers with room to add new content.
For example, some fun missions could be added by adding a pirate base to a hard-to-find region of human space, but due to a lack of barren systems and the galaxy being filled to the edges I can't do that.

**Comment by Wrzlprnft** [comment]
@accursedCursive i disagree, based on the feedback in the various forums like steam, and my personal experience: without a jumpdrive you're stuck. many not even discover Hai-Space.
there's no quarg-space (maybe except the 3 Systems around tarazed),  and no Archon-space. At least not in the way of their Drak-intended space-pockets.

I do agree thought that the recognition of player progress beyond human space and tech is a bit lacking.

**Comment by accursedCursive** [comment]
Isn't that only more reason to expand the galaxy and add more barren systems?
Currently, the only ways to reach alien space are:
-So happen to be exploring a dead-end barren system at the right time and realise the system is a source of jump drives (it's likely the player will only ever see this system once and immediately leave)
-Explore the barren systems in human space (a boring, nonsensical task) which, if the player doesn't know about the wormhole, would appear to be leading the player into getting stuck with no fuel which is only further incentive not to explore
And, as you say, without a jump drive you're stuck. Realising how to get a jump drive is pure luck.

The reason these sometimes-game-ruining barriers to reaching alien space exist is because there's no other way to make alien space hard to reach.
If there was tonnes of room for more systems, the space inbetween aliens could be packed with barren systems, and so stuff like this becomes possible:
![untitled](https://user-images.githubusercontent.com/9290794/35597161-fae053b4-0681-11e8-8cf9-c31094e23217.png)
This makes it less about luck, whether the player discovers Korath.
The player has two very plausible means of discovering Korath:
-Take an extremely dangerous shortcut that is infested with both Korath and pirates (something the player will probably do multiple times)
-Notice that every barren region they find in this area has a way leading further out of human space, and decide to load up with fuel and see how far out of human space they can go

**Comment by MCOfficer** [comment]
> Explore the barren systems in human space (a boring, nonsensical task)

>The reason these sometimes-game-ruining barriers to reaching alien space exist is because there's no other way to make alien space hard to reach.

isn't your point to _add more_ barren systems? which, according to you, are boring?

let's not even get into things like "getting a JD is pure luck"

**Comment by accursedCursive** [comment]
There's a big difference between exploring barren systems inside a known territory and outside a known territory.
Inside a known territory, you can't expect much if you don't know about wormholes (which is why some people never find Hai, I only found them thanks to a Jump Drive).
Outside a known territory, barren systems provide a buildup towards discovering something new.

**Comment by MCOfficer** [comment]
i confess, i had a brief mental breakdown here.

are you actually trying to tell me that, for a player that hasn't gone beyond human space, the existing barren systems are "Inside a known territory"? you need to explain this in some different way.

i fail to see any difference between the existing barren systems separating the hai from humans and the barren systems you suggest.  the only difference that i _can_ see is that the "good" systems are part of your suggestions, the "bad" systems are part of the game.

**Comment by jafdy** [comment]
Raiders appear in all the systems that border on the core, they are simply more common in Durax. I know there are enough first time players that get jump drives from the Korath on their first playthrough before doing the FW story.

**Comment by accursedCursive** [comment]
To a new player, the existing barren region doesn't represent the edge of known space.
It's a barren region strictly inside human territory, they couldn't possibly exit human space by delving into the region (except for the wormhole that they don't know about).

It builds no anticipation to discovering anything, and means discovering Hai without a Jump Drive relies on players obsessively checking out every single system.

The simple way of separating civilisations, just by putting empty space between them, is the best way.
It leaves room for new content, creates anticipation of discovery, and doesn't result in the player getting stuck if they don't do an arbitrary thing you expect them to do.

**Comment by KiLEdEnNis** [comment]
so even though one gets a Jump Drive by playing the human story, ya say new players are having trouble finding any aliens? and ya want new players that just started the game to be able to find various aliens before they even played the human story?

how about new players play the storyline and get a free Jump Drive? so they also have some minor knowledge about the game and a decent ship so they don't get blown up by new aliens

**Comment by Amazinite** [comment]
>There's a big difference between exploring barren systems inside a known territory and outside a known territory... Outside a known territory, barren systems provide a buildup towards discovering something new.

And those systems are only outside a known territory in so much as they are unknown. Once the player discovers them (i.e. there is no build-up anymore), those barren systems become nothing more than a nuisance when trying to get around fast.

**Comment by accursedCursive** [comment]
There's already a chain of barren systems between humans and Hai every single time you want to travel between them.
But because it's a chain of barren systems, rather than a complex network, you can't have a shortcut that the player can later discover to make the trip shorter.
So, adding more barren systems would actually make it faster to repeatedly travel between alien systems via hyperdrive since there wouldn't need to be hard-to-reach-with-no-shortcuts wormholes.

Jump Drive travel would hardly be hindered, this would only add one or two jumps to get from one territory to another.

**Comment by tehhowch** [comment]
I think we've deviated enough from the OP's topic requesting an "exploration %". To summarize, the counter couldn't be trusted to be useful even if added.

If people want to continue discussing the merits of surrounding (new) systems / territories with dozens of `government "Uninhabited"` systems, that should be done in a separate Issue devoted entirely to that topic.

**Comment by MCOfficer** [comment]
The request is to move to the discussion to a different issue. Also, note the parentheses around `new`.
