### ISSUE TITLE
More audio feedback

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#360]
* The new Plasma Cannon sound is *much* better.
* The laser sounds are much better, and much less annoying, but are much too soft compared to other weapons. When firing a laser as well as another weapon, you barely hear the laser noise at all.
* I prefer the old sounds for the Particle Cannon and blaster.

**Comment by endless-sky** [comment]
I'll wait for a few other people to weigh in on which sounds they like, but part of the change was to switch everything to public domain audio sources instead of the hodgepodge of different licenses that the old sounds were under.

I'll see if I can make a web form to make it easy for people to vote on which sounds they like.

**Comment by Pointedstick** [comment]
When you do that, it would be helpful to have both the old and new effects available for listening-to in the form you'd actually hear them in the game. So the blaster noise would be rapidly repeated 15 times, the laser sounds would be looped, etc.

**Comment by Pointedstick** [comment]
Closing in favor of #366
