### ISSUE TITLE
The graphics code is unmodular and inefficient

### ISSUE THREAD

**Issue by BellatrixOrionis** [endless-sky/endless-sky#3629]
Currently, each type of graphical object has its own class, and an associated shader program.
These classes all do the following things:
- Provide a shader program
- Create a set of vertices
- Bind their program, draw, then unbind (Doing this numerous times every frame is inefficient)

I suggest this restructuring to improve performance and allow new shaders to easily be used:
- Define shader programs in data files: A `shader` tag with `vertex` and `fragment` children, which in turn have a GLSL program as a child

- Create a class which has numerous constructors to create lines, sprites, rings, etc. with the one thing these constructors have in common being that a shader (an instance of the Shader class) is specified to draw the object.
Each set of vertices added with one of these constructors is added to a list, with which list it goes into depending on what shader those vertices use. This reduces the number of draw calls and bindings per frame to exactly the number of shaders being used in a scene, which should have a substantial impact on performance with scenes that have lots of objects (dense asteroid fields for example) as CPU graphics events force the GPU to wait for the CPU.
Since whatever list class will be used is probably an array that creates a new array of double the size then moves its contents when it gets full (a performance-costly operation), at the end of each rendering the sets are not replaced with empty sets, and instead they're just overwritten starting from the first index.

- Allow a shader to be specified as a child of a sprite tag, if a non-default shader is to be used. As the shader may make the sprite texture unnecessary (e.g. a star shader that creates a firey-looking circle), it should be possible to specify a width and height instead of a texture when defining a sprite, which will simply create a textureless box to be rendered with your chosen shader.

- Allow sprites to use attributes from whatever object they're drawing as input for their shader. This could have some pretty cool uses, such as having human ships show scorch marks or even fire as their hull gets low.

**Comment by jafdy** [comment]
Go on then.

**Comment by accursedCursive** [comment]
I have graphics programming experience, so I'm fine with designing a graphics engine, but actually programming it would tie framerate to my level of C++ knowledge.

**Comment by flaviojs** [comment]
Having a child vertex+fragment shader in sprite data raises a thorny issue: there is a multitude of things you might want to bind to shader uniform variables, and the data reader would have to support all of that (which quickly escalates to something close to a programming language).

From what I learned while researching alternate ways of doing outlines, the main bottleneck in OpenGL is usually something that causes synchronization.

Shaders are made to be bound and unbound often and their uniform variables are made to be changed at runtime, no performance issues come from drawing with shaders.

Texture binding, on the other hand, might cause an [implicit sync](https://www.khronos.org/opengl/wiki/Synchronization#Implicit_synchronization) in some cases ([example](http://outerra.blogspot.pt/2012/11/opengl-notes-2-texture-bind-performance.html)). A class that manages texture unit bindings could be done (no restructuring needed). The shaders would then query it to know where the target texture is bound (binding only if needed) and update their uniform variables.

**Comment by accursedCursive** [comment]
Uniforms could work something like this:
1. The shader class parses the GLSL code to find a list of inputs
2. The shader refers to a map that provides a function to acquire each input (e.g. `time` is acquired with `std:time()`, `hull` uses a function that checks if the object rendered has a `Hull()` function and if so uses it, anything not on the map is sought as an attribute of the object being rendered)
3. The rendering class renders one object at a time, getting the shader to acquire uniforms
The low number of binding events is retained since rendering is done shader-by-shader.
It does mean there's lots of glDrawArrays events, but that was already the case and my idea for avoiding that wouldn't have worked. I forgot uniforms were used to position objects.

A function map to allow shaders to get uniforms would be really useful, and could simplify the GLSL code: For example, instead of having scale, position, and transform all as separate uniforms with the math to use them to position a sprite being done inside the vertex shader, you could just write `uniform mat3 transform` and `transform * vec2 position = (u_matrix * vec3(vertexPosition, 1.0)).xy;`, and the shader class would have a function for figuring out `transform` based on the properties of what it's rendering.
