### ISSUE TITLE
When you hail a disabled pirate ship, they still demand a bribe to stop attacking you

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#364]
Instead, they should beg for mercy and try to bribe you to repair them (at which point they will presumably run away immediately)!

**Comment by endless-sky** [comment]
This would probably require changing the bribe mechanic so that instead of
applying to all ships of a given government, it only applies to one
particular ship - i.e. this particular pirate would suddenly consider
itself your friend but all the other pirates would not. And because the
friend-or-foe test is one of the most frequently called functions in the
game engine, it might be hard to implement that in a way that wouldn't
significantly increase the CPU load. (Doable, but certainly not trivial.)

**Comment by thenerdfreak** [comment]
Maybe just once you've disabled/destroyed a certain # crew requirement, pirates hail you and offer tribute? (wouldn't require changing bribe mechanic, but would go along with another request (that other ships and planets 'especially during conquests' would hail you instead of you having to hail them)

**Comment by endless-sky** [comment]
To avoid having the player take the bribe and then just attack the ship again, I suppose each ship would have to remember whether they've bribed the player already (and been betrayed). And, ideally the bribe would not get paid until you repair them (or maybe, until you repair them *and* they jump to safety).

**Comment by thenerdfreak** [comment]
true^ and maybe once they're out of the system, since the pirates bribed you, maybe no more will even show up

**Comment by brick96** [comment]
Add a disable check to hails? That way if target is able the bribe/phrase will show. If disabled, the hostile will bribe for their lives.

**Comment by endless-sky** [comment]
Adding a game mechanic where individual ships will bribe you to leave them alone seems like it is likely to introduce new bugs I can't anticipate, so I'm putting that off until the 0.9 series of releases. But for now, I've switched to having disabled enemies respond in a [classic](http://www.pangloss.com/seidel/shake_rule.html) and appropriate way when you hail them rather than pretending they're still in a position to demand a bribe from you (e9ecdfa):

![insult](https://cloud.githubusercontent.com/assets/11450262/11595274/915b7040-9a7c-11e5-918c-b7eaabe91a3b.jpg)

**Comment by Pointedstick** [comment]
Hah, that's great!

**Comment by frameworld** [comment]
Each entity could have it's trust-rating -information-centre (TRIC)  to which you can get reported for taking a bribe and attacking or to which you can report a pirate if it offers a bribe after jumping out and betraying you as a player (automatically?).
The betrayer could get a bounty on his head if the betrayed offers it until either somebody collects the bounty or the wanted one pays as much as the bounty is.
The bounty would than only be active while you are inside that governments or TRIC's region, but if it gets too high, pirates may chase you and you can capture their ships to pay the bounty off (works like a mortgage).

An entity only needs to check the relation-ship when it enters the system.
After that it has an enemy/friend-list.

I think currently endless-sky checks wether A's gov and B's gov are at war or friendly.
* For when the mini-map requests a colour, only the player sees the mini-map and it can have a cached value for the player-relationship. Refresh the whole cache if gov-gov changes for the player, or refresh the entities single cache-value if it's government changes.
* For NPC-NPC I don't think they need to bribe each other if it is too hard to implement.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this. Having pirates bribe you to leave them alone is on my long-term to-do list.
