### ISSUE TITLE
Missiles fired from rear of ship?

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#365]
I was playing around with the idea of EMP mines, which would basically be missiles with `drag=1` so that they don't move after you fire them, with really high shield and ionization damage but no hull damage.

It looks really weird that you drop them from the front of your ship, though. Is there a way to make a missile launch from a point on the back of the ship, even though the gun ports are in front?

**Comment by Pointedstick** [comment]
Maybe a turreted missile launcher?

**Comment by endless-sky** [comment]
Projectiles are always fired from whichever "hardpoint" they are installed in, and the hardpoints are fixed for each ship. So, aside from making a ship with a rear hardpoint just for mines, there's no real way to do that.

**Comment by Tufton** [comment]
I made a mine. Ion Mine. I posted it in the Google group in content
creation. I'll post it here when I'm off my phone.

**Comment by Tufton** [comment]
I won't put the plugin here because its in the google group, but this is
how I did it, I think it works pretty well.

relevant.txt:

outfit "Hedgehog Ion Mine Launcher"
category "Secondary Weapons"
cost 110000
thumbnail "outfit/torpedo launcher"
"mass" 50
"outfit space" -50
"weapon capacity" -50
"gun ports" -1
"torpedo capacity" 30
weapon
sprite "projectile/seeker"
"frame rate" 16
"random start frame"
sound "torpedo"
ammo "Hedgehog Ion Mine"
icon "icon/torpedo"
"fire effect" "torpedo fire"
"hit effect" "big explosion"
"die effect" "tiny explosion"
"inaccuracy" 4
"velocity" -10
"acceleration" 1
"lifetime" 800
"reload" 120
"firing energy" 2
"firing heat" 45
"drag" .2
"turn" 20
"homing" 2
"ion damage" 6
"shield damage" 280
"hull damage" 340
"hit force" 100
"missile strength" 25
description "Hedgehog Ion Mines are powerful tools to "dissuade" any
pursuers from continuing the chase."

**Comment by thenerdfreak** [comment]
I like that idea ^^ wouldn't really be over powered since they're still considered missiles,and can be simply blown up with anti missile turrets,(or coded to be avoided if possible)

**Comment by dplepage** [comment]
I did something similar, but a little more special-purpose; I'll clean it up and put it on the google group if I have time, but the essence is
```
	...
	"emp capacity" 3
	...
	weapon
		"velocity" 0
		"acceleration" 1
		"drag" 1
		"lifetime" 600
		"reload" 400
		"blast radius" 200
		"shield damage" 50000
		"hull damage" 0
		"ion damage" 1500
```

This gives you a weapon with the following properties:
 1. The blast completely de-shields and de-powers any ship for several seconds, but does no hull damage whatsoever.
 2. The blast radius is ENORMOUS, so you better be careful - if e.g. an asteroid hits it before you're out of range, you'll be stunned yourself for several seconds and will almost certainly die.
 3. You can't carry very many, and reloading takes a long time, so you better get this right on the first try.
 4. A light warship can take out a heavy warship if you drop one of these correctly and act fast, but if you screw it up you'll die.

I also had to tweak the code to cap the number of ionization effects that would be shown on a ship, otherwise it looks pretty ridiculous. I'll put up a PR for that later.

Another experiment was to make it more like a heavy missile - hard to aim, and you have to be facing your target. That makes it even easier to accidentally ionize yourself.

**Comment by Tufton** [comment]
Ya they actually don't move too fast because their lifetime runs out before
they can really get moving so the mine ends up popping out backwards then
slowly accelerating straight towards the target (i cant remember which
homing level it is but they end up not being that different at low
speeds/lifetimes).  The turn radius generally keeps it tracking properly,
but the low acceleration means if you dodge it on the first pass it's not
too hard to outrun it, especially for faster ships.  I think those traits
suit a mine.

**Comment by frameworld** [comment]
Is there no possibility for proximity-self-triggering mines?

IRL, an anti-tank missile launched by peoples activates itself after 9m and some digged-in mines even launch a pod into the air which fires an anti-tank-shell from itself (a single mine which is easy to clear after the war ends, but with a great radius).

When the real life is so advanced, why not add a little bit of that in a sci-fi-game?

**Comment by dplepage** [comment]
@endless-sky is there a way to control which weapons go at which hardpoints? I.e. if I put a hardpoint at the back of each ship, could I ensure that mine launchers go on those hardpoints and lasers don't? Or would that require actually adding an entire new type of hardpoint for rear-firing weapons?

That last one might actually be worthwhile - the Rear Laser was a pretty useful EV upgrade.

**Comment by thenerdfreak** [comment]
Yes @dplepage you can change them by dragging them in your I menu (where it tells your ship names and combat stats

**Comment by dplepage** [comment]
@thenerdfreak Oh, I saw that view but didn't realize I could actually move things around on it. Thanks!

What I was really asking, though, was whether it was possible to specify when creating a weapon that it should go in specific hardpoints, and having examined the code I'm pretty sure that's not possible except by adding a new, separate kind of hardpoint.

Since that answers my question, I'm going to go ahead and close this issue.
