### ISSUE TITLE
Gravity Wells

### ISSUE THREAD

**Issue by Seaton3310** [endless-sky/endless-sky#3661]
One small feature of EVN I enjoyed was the gravity wells around planets and how they restricted hyperspace jumps - you couldn't jump to an adjacent system immediately after taking off, you had to move away from the mass from which you took off (i.e. fly a screen's length away from New Boston before being able to jump).

I think this would force players to be more aware of their surroundings and add an element of surprise to the game.  See an enemy on your radar?  You can't jump right away to safety, so quickly find out where he is  and maneuver away, getting enough distance to allow you to safely jump.

Thoughts?

**Comment by Quantumshark** [comment]
I think the problem with this idea would be that unless the radius of the effect scaled with ship size and was much smaller for smaller ships, this would make it almost impossible to escape pirates early game.

Also, one entire screen length seems a bit excessive for a distance requirement given the size of the planets, it seems more reasonable to have a distance requirement of maybe 1-2 times the planet's diameter.

**Comment by Amazinite** [comment]
Minimum distance restrictions on how far you need to be from stellar objects in order to jump have been noed in the past. https://github.com/endless-sky/endless-sky/issues/1094

**Comment by Seaton3310** [comment]
#1 Sorry not a full screen length, I think EVN had it at like 75% of a screen away from the planet.
#2 Hmm ok, if it's been no'd by the community then that settles it.  But I liked it, found it challenging in a fun way, and I find it far too easy to just jump immediately upon take-off in ES.

But hey, guess it's a personal preference.

**Comment by nylki** [comment]
Perhaps a soft limit could be interesting to experiment with:
starting the hyperjump near the sun/system center to require more fuel or increases overheating.

**Comment by Zitchas** [comment]
The soft limit idea I think kind of misses the point: Which is namely that the gravity-well limit on hyperjumps constituted a sort of terrain that one had to deal with strategically. It meant that enemy fleets jumping in usually arrived farther out, so one had a bit more warning before combat started. It also meant that it wasn't as trivial to escape because one couldn't hyperjump instantaneously off the planet. 

Later on in the game, there were certain plot choices that led to getting outfits that reduced that radius by half. For some players, those were essential equipment, for others simply a convenience, some just ignored it. But they were definite luxuries and achievements that really felt like game-changing elements.

I would love to see no-jump radius-es exist in ES, but not having them isn't going to wreck the experience. (although the whole 'take off or hyperjump into the teeth of a fleet' element that this radius often helped prevent is rather nasty.)

**Comment by TheGiraffe3** [comment]
You can add hazards to each object in a system with negative hit force, but let me just say, defining a hazard for each sprite you want is a headache.

**Comment by Saugia** [comment]
This has been implemented for Ringworld systems using `departure` distances. After the limitations have been in game for a few patches, we feel that we don't want to do this for every system and gameplay in general feels better without them. As Amazinite mentions in an above comment, this kind of environment has been no'd by MZ before (and if not, it probably would have been part of the game in the beginning).

It existing for ringworld systems has a bit of use with lore implication and is generally workable for now. Otherwise, after getting the feel with the implementation for ringworld systems, we feel it better not to have this as a galactic standard. Regardless, the ability to mimic this behavior is now doable with arrival and departure distances, and would be good for plug-in use.
