### ISSUE TITLE
Button to make Escorts land, but not flagship

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#367]

**Comment by endless-sky** [comment]
Escorts will automatically land if they need to refuel (which is already sort of cheating, because landing takes a "day" for the player but only a few seconds for them). Is there another reason that you would want your escorts to land without your flagship?

**Comment by jafdy** [comment]
if the next system is uninhabited and they only have one jump of fuel left but you have more than one jump of fuel left.

**Comment by johndh** [comment]
I guess it would be useful for repairs, or if you've just captured a ship and don't want it to be destroyed before you can sell it.  I can see how it's "cheating", so maybe if you land an escort in this manner then they stay parked until you land your flagship?

**Comment by brendanjones** [comment]
I like this idea from the point of view of forcing your ships to refuel, but one major drawback is that you could use it to stay in space and capture/loot a bazillion ships without ever losing them because they're sitting around with 10% shields or something. Especially if they stayed parked until you landed. And pillaging is already OP in terms of financial reward.

**Comment by omagasohe** [comment]
I like this idea too for refueling. Ditto for balance issues, if I can make just certain escorts stay down. Park by a pirate planet, terrorize at will then take my toy and leave. it'd be worst if it's a pirate planet with a shipyard.

**Comment by thenerdfreak** [comment]
@omagasohe you can do that, just have the ship you're using as a flagship have at on of fuel addons (they're 8 outfit space each) and press b to refill your escort's fuel

**Comment by frameworld** [comment]
If you put a dozen fuel tanks into your flagship and your escorts have scram drives, it will be annoying without automatism.

Sometimes I just want a ship to land and deliver a missions cargo and the rest of my fleet to jump to the adjacent system for another landing operation.
Would you suggest a button for this too?

**Comment by thenerdfreak** [comment]
I meant this for circumstances where you're guiding a bunch of freighters, and there is nothing but uninhabited space ahead, with you having enough to get through it but your escorts wouldrjn out, and you're on a time-budget

**Comment by brendanjones** [comment]
"Make them popup immediately and don't heal them. balance issues solved."
That'll do it. Good thinking.

So to clarify:
- You can refuel an individual escort or all escorts. 
- They refuel, but don't heal, and they cannot be parked.
- To refuel an individual escort, select that ship and hit shift+L
- To refuel all escorts, hit (not sure about this) control/command+shift+L

Anyone see any balance issues with this?

**Comment by endless-sky** [comment]
It's already "cheating" for an escort to be able to land and take off without it taking a day. The only reason they're able to do that is to make stranded escorts less difficult to deal with.

**Comment by brendanjones** [comment]
Hmmm...so you're saying it's cheating enough that escorts can auto-refuel, and this shouldn't be implemented? I understand...

What about if it took more real-world time? So if you forced your escorts to refuel you'd save a day in-game, but it takes 10-20 seconds, or so (yawn). I'd always land, because I'm impatient, unless I was really stuck for time in-game.

Of course, if ships took 10-20 seconds to refuel, you could use (abuse) force-refuelling them as a way to make them out-last a battle when they're only on 10% shields. There's always a downside...

**Comment by frameworld** [comment]
> The only reason they're able to do that is to make stranded escorts less difficult to deal with.
Select an escort, press u and it gets refuelled?
The only problem I see is that the fleet is unable to share fuel automatically.

**Comment by endless-sky** [comment]
The new release (0.8.9) at least fixes the bug where escorts fail to refuel even if they know they're about to jump into a system where they will be stranded. Adding even more ability to cheat the clock doesn't make sense to me.
