### ISSUE TITLE
Ships won't respond

### ISSUE THREAD

**Issue by MikeDred** [endless-sky/endless-sky#3698]
Version 0.9.8 playing with (your) files on my computer, (not through Steam) windows 10.

I am in the Edusa system (and area)... Some of my ships have grouped up and stopped taking orders. 
usually 5 at a time. they either play ring-around-the-rosie or pace back and forth over a line maybe 7 ships long. They refuse to HOLD or GATHER to my flagship or GOTO. 
I have quit and come back in game but they remain blissfully mutinous. 
I leave the system, no change. Come back ... you get the idea. I lost them to insanity. 
There are now groups of them in Segesta too.

**Comment by tehhowch** [comment]
It is recommended practice when filing a bug report on GitHub to first verify that your issue is not resolved when using the latest build from source.

It is also a good idea to include your save file when discussing issues that affect your fleet even when you relaunch the game. In this case, your issue was caused by having a Travel Plan, the relative speed of your flagship and your escorts, and use of a wormhole. You can resolve this by editing your save file (located in `%appdata% -> endless sky -> saves`) and removing the `"destination system" line from each of your escort's ship definitions.

Likely related issues: https://github.com/endless-sky/endless-sky/issues/2830 https://github.com/endless-sky/endless-sky/issues/2829 https://github.com/endless-sky/endless-sky/issues/3012 https://github.com/endless-sky/endless-sky/issues/3608

**Comment by MikeDred** [comment]
Didn't even know I could attach save files, thanks.
And I wish that was the case. I thought of it. I was in the same system... I was beside them, flying away, toward, jumped in and out in each direction.. they just flew around one another.
In the Segesta system they flew to a far away (away from planets and sun) bit of space and clustered there. I sped the game up and told them to gather on flagship. All of the ships made a loop from that random spot and back to me, over and over again. 
Eventually they did follow me out of system. 

But yes, I had the latest build and did realize the travel issues. I gather all my ships before jumping. I don't jump ahead often and when I do they sometimes get stuck in various systems. For known reasons. That's part of the game I can live with. 
I'll have a look at the other related issues too, thanks.
