### ISSUE TITLE
The Bactrian has too much weapon capacity

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#370]
That coupled with its 6 turret hardpoints and 4 gun hardpoints makes it sort of a no-brainer for players wanting the best heavy warship. You can fit five plasma turrets and a heavy anti-missile turret, and with that you can pretty much blow anything out of the sky at close range. Lowering its weapon capacity would limit it to lighter weapons if you wanted to fill up all the hardpoints, which might make it less desirable vs the Dreadnought and other super-heavy warships. It seems like powergamey players are strongly attracted to the Bactrian right now, which is a sign that it's too abusable.

**Comment by endless-sky** [comment]
Sounds reasonable. How's this: 0450664? (-30 weapon space)

**Comment by omagasohe** [comment]
I roll with 12, but because that allows for 6000+ cargo, and enough ommph to keep them safe. But it's supose to be a city ship. It needs a but of nerfing, but I'd go with manuverability and a higher price tag.

**Comment by Pointedstick** [comment]
Ah, nice.

**Comment by Man-animal** [comment]
The thing with the Bactrian is that you can convert most of its cavernous cargo hold into outfit space and still have enough room to loot reactors.  The popularity of the Bactrian is not due so much to the firepower - good as that is - as the fact that you can easily pull off things that no other ship can do without major sacrifices.

**Comment by Pointedstick** [comment]
Yes, and the advantage of a huge cargo bay would be much less noticeable if you couldn't loot reactors, or if any of the other suggestions to tone down the power of looting were implemented.

**Comment by Man-animal** [comment]
It would still be superior for warfare because of its high crew capacity and effective outfit space advantage - a 200+ advantage over the other top tier human warships.

**Comment by frameworld** [comment]
There should be good flagships and good ships for escorts.
The flagship should have high crew requirements and be it's own class "World/City ships".

Additional ships neither need the crew space nor the enormous cargo in a single entity nor the whole lot of turrets/weapons on a single entity and thus not as much outfit space.

Still, even though Bactrian is op, it, together with a dozen shield beetles from Hai space, full of Hai's advanced shield technology merged with Korath cooling systems will eventually lose in some campaign's mission.

**Comment by egilburg** [comment]
I think Bactrian's mass should be significantly increased. Just look at it's size in the UI - it's twice as large as other ships, yet similar massed.

Increasing it's mass by 50-75% would still make it useful at specific roles - looting/raiding mothership, heavily armed freighter, backrow artillery for other ships in your fleet. But make it too slow for front-line dreadnought combat or general-purpose adventuring.

**Comment by egilburg** [comment]
Weapons - not all are problems, just Laser turrets
---

When it comes to weapons, I think Bactrian just exposes how OP laser turrets are. Guns are OK because they require turning the ship and thus are naturally nerfed by turn rate. Turrets turn instantly and that makes the any ship (but especially Bactrian) carrying a ton of turrets (and especially laser turrets) incredibly OP. 

I think turrets should have their own turn rate equal to the turn rate of the ship, so while they can turn independently from the ship and auto-aim, they shouldn't be able to instantly switch direction. Such a change would weaken all turrets compared to guns, and further weaken laser turrets compared to other turrets (as their no-lead time is especially OP when combined with no-turn time too), and would make bigger ships like the Bactrians much more vulnerable to several smaller agile attackers, as they should be.

**Comment by frameworld** [comment]
@egilburg Bactrian is perfect for boarding. If you take away speed, it can neither board nor loot effectively. I feel like this is too much of a nerf at once.

* Laser turrets make the Bactrian near-invulnerable to almost all attackers.

Wrong. World-ships outrange them and pushes your Bactrian away. Some missiles do that very effectively too.

I'd like turrets to not be 360° but covering an angle. In turn they could get equal firepower as guns - because you can't focus a single target.

Guns: anti-heavy. Turret: anti-swarm.
If you can't equip both fully it would be balanced.

**Comment by endless-sky** [comment]
@egilburg, capital ships already are quite vulnerable to "swarms of agile fighters." Take any capital ship in the game and have it face off against however many Sparrows you could buy for the cost of that one capital ship, and I guarantee it will lose. (For example, a Bactrian against 50 Sparrows.) In fact, most capital ships could easily be brought down by a fleet of interceptors worth less than half the capital ship's value.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
