### ISSUE TITLE
Stuck with the FW campaign

### ISSUE THREAD

**Issue by bergentroll** [endless-sky/endless-sky#3701]
I am on Endless Sky 0.9.8. I already got mission to hunt down some pirate with an alien weapon. I captured his ship, but some enemy blasted it over. I decide, that mission is accomplished and went to do some money. But it seems, the camaign is stuck. It is no more missions on spacepots of Free World, also no eny messages on the Bourne's spacepot.
My last logbook record is:
"Earned a good reputation with the Free World militia by taking on missions to hunt down some dangerous pirats"

**Comment by Janaszar** [comment]
The FW campaign needs you to do some other work for them; Escorting freighters, doing some Recon, and helping determine what happened with the nukes.
Go around to Free World planets and spam Spaceport to pick the missions up.

**Comment by Amazinite** [comment]
The ES Github is for feature requests and bug reports. If you're wanting to ask a question, you should do so over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky). Please close this issue.

**Comment by bergentroll** [comment]
@Janaszar, I have done all but nukes. I visited spacepots over 50 times and envelop almost every FW planets and stations, but nothing happens.

**Comment by jafdy** [comment]
You rejected the required mission at some point. 
Please close the issue.

**Comment by bergentroll** [comment]
[There is my savegame also.](https://grotten.ru/index.php/s/RjRBJEwG6nfXSTg)

**Comment by Wrzlprnft** [comment]
the thing is: this is less a personal issue tracker, more a general issue tracker. so, many people get notifications about this, expecting a bug report or feature suggestion. someone has to adress or close it at some point.
that is why our community is structured in a way where, if you prefer a forum, the steam forum or google group serve as platforms to ask and answer questions or refine ideas until they are ready for this here, or the discord in a more conversation based way of questions and answers.
it's.... more of a task list for those interested in improving and advancing the game. your personal savegames problems do not matter, as harsh as it sounds, unless you can refine it to a proper issue. in this case it would probably be the question “is the campaign too easy to break?“ which then would be discussed, adressed and closed once done.

The Answer to said issue would probably be: yes, it currently is rather easy to break, given how it assumes there are alternative paths you can take, which are not there yet (syndicate story, republic story, fallback solutions and proper consequences). so, it will be fixed once there is more content to the game. why not earlier? it's the removal of a single plain text line in a savefile which reenables it. and the choice is worded in a way that it is normally very clear that thus is a no.

i hope you can understand the reactions, especially since this kind of issues arises more frequently lately. that said, feel free to join the discord (i recommend mute-ing the entire off topic category, though), because the most know how is there, fast answers, and there is any question to the game welcome, and get help there. steam forum gives the second fastest answers, though occasionally there is a wrong one in between, and google group takes the longest, but normally has only high quality answers.

**Comment by bergentroll** [comment]
@Wrzlprnft, OK. Sorry for trouble and thanks for all!
