### ISSUE TITLE
Shaders are too slow on integrated graphics

### ISSUE THREAD

**Issue by CyberShadow** [endless-sky/endless-sky#3714]
Hi and thanks for the amazing game!

I'm playing this game on a laptop with Intel integrated graphics, and noticed that my laptop gets pretty hot (and the fans get pretty loud) in certain situations while playing the game. Specifically, this seems to occur on the map screen, and when there is a lot of text on the screen (such as during dialog).

Building the game from source and profiling it reveals that the culprits are:
- Font::DrawAliased
- RingShader::Draw
- LineShader::Draw

All three seem to make use of shaders, so I'm inclined to believe that the shaders create a performance bottleneck on machines like mine.

As these primitives look like they could be implemented in other ways, what do you think about having an alternative implementation of them that doesn't make use of shaders?

**Comment by KiLEdEnNis** [comment]
if you know how to do it, feel free to try, better game performance is greatly appreciated
and if you don't know how, thanks for bringing it up anyway, and hope someone finds a way to improve it

**Comment by tehhowch** [comment]
Map code is the oldest code. If you are able to write GPU code or develop a less resource intensive equivalent of the existing map, please do

**Comment by CyberShadow** [comment]
PRs: https://github.com/endless-sky/endless-sky/pull/3720 https://github.com/endless-sky/endless-sky/pull/3721 https://github.com/endless-sky/endless-sky/pull/3724

With these three, there is a significant reduction in heat and fan noise.

**Comment by endless-sky** [comment]
I've checked in a change (7d74467) that takes a different approach than those PRs: rather than trying to optimize the map access functions, I just cache the map layout itself and only update the cache when the coloring changes.

With that change, on my computer, map drawing uses significantly less CPU. Rather than data lookups being the bottleneck, the biggest remaining bottleneck after the change is the text drawing code itself.

Optimizing text rendering is a separate issue. Once the game switches to full Unicode support, lines of text will need to pre-rendered and cached. In the meantime, there might be other ways to optimize (like using vertex buffers to draw a whole line of text with one draw call, instead of drawing one character at a time).

**Comment by CyberShadow** [comment]
Thank you, that does seem to make a noticeable difference on my laptop!
