### ISSUE TITLE
How to capture this ship

### ISSUE THREAD

**Issue by dark-wind** [endless-sky/endless-sky#3722]
![image](https://user-images.githubusercontent.com/15257951/39405780-33aec24c-4bde-11e8-82dd-289c3fdb4688.png)
![image](https://user-images.githubusercontent.com/15257951/39405781-365b7d28-4bde-11e8-953c-bab2ec58940f.png)

There are two many people.

**Comment by MCOfficer** [comment]
yes, this is by design. a worldship is supposed to be (almost) uncapturable).

something you should know:
this is an issue tracker, not a support forum. if you have questions or need help, please ask in the google groups forum, the stream forum or on the discord server. github issues are for tracking bugs and feature requests.

please close this issue.

**Comment by dark-wind** [comment]
Thank you very much
