### ISSUE TITLE
Shouldn't nerve gas canisters be confiscated too?

### ISSUE THREAD

**Issue by temtemy** [endless-sky/endless-sky#3754]
When I landed in a Kor Efret planet with my flagship crew equipped with nerve gas, I get fined (and I am not sure if this is normal). I wondered if they have confiscated my nerve gas canisters, and I found out they do not. Shouldn't the canisters be confiscated too, just like when some gunboat scans you and founds out you're smuggling illegal cargo, and confiscates it?

**Comment by KiLEdEnNis** [comment]
first, aliens fining you too has been brought up, some people want it so that only certain governments find something illegal (and maybe that each government has custom fines), and that fines are based on (base value + value * amount)
but confiscating? imagine you have 200 Nerve Gas, you get fined 1M, AND you lose 15M Nerve Gas
it'd be extremely annoying, and discourage anyone to buy anything illegal, so that's not worth it

**Comment by robot-rover** [comment]
KiLEdEnNis’s point is especially true when you consider some of the Easter egg ships (eg. Capt Pester). Imagine getting your cap ship all geared up and losing all your nerve gas’s right before you arrive because pester shows up. The fact that it is random and completely unavoidable would almost completely discourage the use of nerve gas.

**Comment by temtemy** [comment]
Okay, your points makes perfect sense to me.
