### ISSUE TITLE
Mission disappearing from the Mission selection and mission field

### ISSUE THREAD

**Issue by FireWolf74** [endless-sky/endless-sky#3762]
Also everytime I go to accept a new mission I click it but the mission never shows in my mission field. But it is removed from the mission selection.

**Comment by jafdy** [comment]
Can you explain what you mean, this isn't a potential bug we have met before so without screenshots and/or reproduction instructions there is nothing that can be done.

**Comment by FireWolf74** [comment]
ok here we go

I have grabbed many different missions while i was running the FW mission track to stay in the south to pay off loans.  I would grab the missions I wanted click "Accept Mission" set my travel the location which would my the I think light blue arrow and start my mission, only to find out after I get to to receive the credits that it was not in my mission field.  Now upto landing on the planet or Station it was in my Mission Field, but after landing it was not there at all.

I have lost over 6 Million Credits because of this.  I doubt I can get reimbursed I'll take it at a loss.

**Comment by tehhowch** [comment]
Your opening post makes it sound like you click accept while landed, the job disappears from the left-hand menu, but does not appear in the right-hand menu.

Your next post indicates that what is actually happening is that you accept a mission, it does move from the left-hand menu to the right-hand menu, but after you depart, travel to your destination, and then land, it is no longer available and you do not get paid for it.

Is that last paragraph a proper understanding of your issue? If so, I must say it does not sound like a bug, it sounds like you failed a mission in flight, either due to losing a ship carrying mission cargo or mission passengers, or due to taking too long to each the destination (deadline expiration), or because the ship you were escorting was destroyed. Those are not bugs. Please pay attention to the ticket, as mission failures can be hard to spot in a busy systems.

If you think I have an incorrect understanding, please provide a save file and reproduction steps. Alternately, a video clearly demonstrating the issue occurring.

**Comment by FireWolf74** [comment]
I have an OH SHIT Moment here I don't have a saves folder :(
![screenshot from 2018-06-09 20-44-19](https://user-images.githubusercontent.com/33334258/41197274-fd3f9548-6c25-11e8-8717-795e1bc88452.png)

**Comment by KiLEdEnNis** [comment]
on W10 the saves folder is in User > AppData > Roaming > endless-sky
on Linux it should be something similar
are you sure you're looking in the right place?

**Comment by tehhowch** [comment]
As mentioned before, in linux distros the saves and other files which are expected to be written to by the user are located in `/usr/share/....` or `~/.local/share/endless-sky/`. It is not surprising at all that the folder in which steam does whatever it wants does not contain files you are expected to freely configure - you would lose your configurations with every steam update.

The mechanic you mention - free bunks and free cargo space decreasing when you accept a mission from the Mission Panel - is not a bug at all. It is normal behavior for all missions that you have active.

**Comment by FireWolf74** [comment]
Tehhowch the one I have for linux is the same way

**Comment by Wrzlprnft** [comment]
that doesn't look like .local/share . that looks like the installation directory for non steam. which is not what we're talking about?

**Comment by FireWolf74** [comment]
Wrzlprnft, .local

**Comment by Wrzlprnft** [comment]
eh, sorry, i did not specify: we're not looking for the install directory for plugins and saves, but the plugins and save directory. the save files are there, and not the install directory.

anyway, back to the issue: when you depart from a planet after accepting missions, does any pop up or the bottom left chatzery show any messages about not enough cargo?

**Comment by tehhowch** [comment]
If your system does not use `~/.local/share` to store user preferences data, it still stores them somewhere. The game uses the SDL library to obtain the base path for the user data folder (`SDL_GetPrefPath`), adds one named `endless-sky`, and uses that location to store `/saves`, `preferences.txt`, `errors.txt`, and `/plugins`, and whatever else.

Consider reviewing how to find directories on your filesystem - it will not be difficult to find where user data is stored since you know the names of the directories you are trying to find, and files within those directories (your pilot's save is `<first> <last>.txt`).

Again, please clarify the actual issue you are having with missions, per the posts above.

**Comment by FireWolf74** [comment]
No

**Comment by MCOfficer** [comment]
you progress is being saved, ergo the save folder does exist. try `find / -name "endless-sky`

And once again, please provide some clarification as to what the issue actually is.

**Comment by FireWolf74** [comment]
MCOfficer,
I did a complete and total search from (/) root directory and the two screenshots I provided are the only two folders other than sbin that has folders that have anything in them.   The first screenshoot is from the Steam version of Endless Sky and the Second one is the Linux Fedora 28 GNOME 3.28.2.

**Comment by MCOfficer** [comment]
i can only reiterate - if the folder didn't exist the game would error on trying to save. alternatively, you can search for `YOURPILOTNAME.txt`.

**Comment by FireWolf74** [comment]
MCOfficer if what I'm looking for is within steam I maybe unable to find it.

**Comment by MCOfficer** [comment]
it is in your local filesystem, that's all you need to be able to find it.

instead of posting your savefile, you can still record a video showcasing the issue.

**Comment by FireWolf74** [comment]
I will be closing this Because again People are not understanding.

I was looking for the Steam saves which I can not find. (Don't hee telling that the game can not Play without), Which is where I am having the majority of the issues.

The two attached files are not what I'm looking for.  Notice the date on it.  Over a week Old.
![screenshot from 2018-06-10 18-46-33](https://user-images.githubusercontent.com/33334258/41207156-a96f07b4-6cde-11e8-9f1e-c2124a848eb6.png)
![screenshot from 2018-06-10 18-46-22](https://user-images.githubusercontent.com/33334258/41207157-a987cab0-6cde-11e8-8cda-3b42155fdf92.png)

I feel like I'm trying to beat a dead horse when I say I am looking for the Steam Version not Linux Version.

And with that this is closed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by MCOfficer** [comment]
the steam version stores the savefiles on the disk, afaik even in the same folder as the linux version. the steam cloud is not being used.

**Comment by FireWolf74** [comment]
Sorry MCOfficer but you are 1000% incorrect and I did not change anything.

I want  you to really look at those two images and this one and then tell me what is Different (this is the current one I'm playing on Steam)
![screenshot from 2018-06-10 19-13-40](https://user-images.githubusercontent.com/33334258/41207333-1ff9cc0e-6ce2-11e8-81ce-3242222cc820.png)

Notice the Different Name of the Ship Pilot? 
Does it say Jeff Howard or Jeffery Howard?
Now you tell me that I'm blind as a bat.

**Comment by MCOfficer** [comment]
i told you what i am 100% certain of, that's the best i can do. if your pilot is called Jeff Howard 2, then there is **most definitely** a file called `Jeff Howard 2.txt` on your system.

btw, your screenshot from earlier shows that there are save files in `~/.local/share/endless-sky/saves/`, just like it's supposed to be.

you can still record a video, because posting a save file apparently isn't an option.

**Comment by jafdy** [comment]
MCO is entirely correct, you will have more success if you avoid insulting the most of the community. 
Also, those screen shots are of the same save as far as I can tell, the pilot and ship names are the same.
