### ISSUE TITLE
Cannot "gather" when whole fleet is in other system

### ISSUE THREAD

**Issue by lheckemann** [endless-sky/endless-sky#3774]
I used to use the gather command to get my fleet to follow me when they were holding position in another system. Now, pressing G does nothing unless I already have at least one escort in the system, and I have to right-click to send them to a specific location in the current system, then wait for them to arrive before I can issue the gather command.

**Comment by temtemy** [comment]
Alternatively, you can press H again so that your escorts no longer hold position and follow you. Or is this no longer the case in the git version?

**Comment by lheckemann** [comment]
It seems that none of the key-based fleet commands work when the escorts are all in a different system. Additionally, H can only be used to cancel a "hold position" initiated with H, not a "go to position".

**Comment by temtemy** [comment]
Sorry, not the case for me. I divided my fleet into two groups, which are in two different systems. I told each group to hold position then park. Then I go to another system and cancel my order to hold position, and they go to my system. Escorts always follow you, unless you ordered them to hold position, or are busy fighting a hostile.

**Comment by lheckemann** [comment]
OK, checked again to make sure:

1. Give "go to position" order to fleet
2. Jump to another system
3. Press G (nothing happens)
4. Press H (fleet is "now" holding position)
5. Press H again (fleet is now on its way)

I also had some odd issues which I don't fully understand, which may be caused by some combination of <kbd>H</kbd> orders and landing, where I pressed <kbd>H</kbd> about 5 times, each time resulting in the message "Your fleet is holding position.", until the 6th (estimate) time where the fleet started moving again.

This is on 5d06aff7e59ba5ba46b19d9c6c82f0a2e0a600f7 (master from a few days ago), not 0.9.8, FWIW.

**Comment by tehhowch** [comment]
Depending on how mixed your fleet's maneuverability is, the changes in #2591 can cause the repeated pressing of H not toggling orders - basically, part of your fleet is in a hold order, and part is in a move order. Because the ships you instruct have mixed orders, issuing a new hold order doesn't toggle the command off as it would if they were all on a move order:
https://github.com/endless-sky/endless-sky/blob/04b99dc89a40b584151202abab2379d52c7bf0b9/source/AI.cpp#L3403-L3455

There are a few ways to prevent the conversion - one possibility would be to change the hard-coded `20.` units to reference the stopping distance, which is dependent on characteristics of the ship. I.e., if the ship is far from the stopping point, but that's because it is a slow ship, don't switch the order.

**Comment by temtemy** [comment]
@lheckemann It seems you're right. On 04b99dc89a40b584151202abab2379d52c7bf0b9 (master 3 days ago), I can't gather my fleet when I am in another system. It used to work in 0.9.8. Pressing H to cancel holding position still works, except in situations like tehhowch mentioned.

**Comment by jostephd** [comment]
Bisected to c8540a6d5f7f25cb6d80cac80592ff01eed6bbc6 (#2984).

**Comment by VonZorch** [comment]
@lheckemann  I'm experiencing the H command problem.
Details
1. Hold entire fleet with H.
2. Select Scout group with 1.
3. Un-hold scouts with H, may take 4 tries.
4. Un-select scouts and jump.  Secure the system.
5. Hold fleet with H.
6. Un-hold fleet with H, sometimes works first time but usually takes many tries.  If it does not un-hold gives a "Fleet is holding position." message.
