### ISSUE TITLE
Korath exiles not repairing their disabled ships even if the player is cloaked or very far from the system center

### ISSUE THREAD

**Issue by temtemy** [endless-sky/endless-sky#3777]
While enjoying the sight of disabling lots of Korath exiles, I noticed while cloaking that the ships jumping into the system and taking off from their station aren't helping their disabled allies. Even when I am very far from the system center, they don't care about the disabled. They only care if they disabled my ship. It doesn't make sense, especially if I am very far from the system center, since they are given the chance to save their own ships.

**Comment by tehhowch** [comment]
AI doesn't call for help unless all in-system hostile ships are disabled. They don't care how far away or untargetable you are.
https://github.com/endless-sky/endless-sky/blob/04b99dc89a40b584151202abab2379d52c7bf0b9/source/AI.cpp#L767-L774
The source of that code is PRS https://github.com/endless-sky/endless-sky/pull/3025 and https://github.com/endless-sky/endless-sky/pull/2861

In the code before those 2 PRs, they wouldn't have asked each other for help even after you were disabled - you'd need to have been destroyed.

The shortcut is to simply add an `IsTargetable()` check in addition to the `IsDisabled()` check. But perhaps it would be more useful to approach from the opposite end - rather than forcing the disabled ship to always ask for help, a parentless ship should consider assisting fellow ships that are disabled if it finds it has not much else to do. This would be a tiny step towards #3381, and if done well (NPC leader chooses a squad action, whole squad achieves task) would be pretty neat to observe.
Note that if the lead ship of an NPC group gets disabled, but at least one non-carried escort is not, `escort` -> `parent` assistance is already performed:
https://github.com/endless-sky/endless-sky/blob/04b99dc89a40b584151202abab2379d52c7bf0b9/source/AI.cpp#L696-L706

So, I wouldn't call this a bug, just a missing feature :)

**Comment by Zitchas** [comment]
As far as this goes, how variable is assisting/not-assisting? The Korath always strike me as being rather brutal and unforgiving, so it suits them to not bother helping their own if there is *anything* else they could possibly be doing. (including trying to find a cloaked ship).

But I've noticed that the Hai and various other factions do the same thing: Don't help their own unless there is absolutely nothing else to do. And the Hai strike me as a group that might prioritize assisting their own ships.

I don't know how hard it is to implement, but having some kind of scale or series of options would be good for diversifying faction behaviours. The basic options I'd see would be: Never, sometimes, and always. 

 - With never being, well, never assisting; 
 - sometimes being assisting only when the disabled craft is closer than any hostile ships & no hostile ships are within 2x their longest range weapon; 
 - Always would be they prioritize assisting ships. 

(The sometimes option would be the default and more "logical" behaviour, as it would generally translate to "help unless there is an enemy within striking distance," which should also help avoid them being too dumb about ignoring enemies who are sitting on top of them, etc. The "Always" behaviour would probably be rare, mostly for when a mission needs specific behaviour (or ships with some kind of "medic" personality?))

**Comment by temtemy** [comment]
> As far as this goes, how variable is assisting/not-assisting? The Korath always strike me as being rather brutal and unforgiving, so it suits them to not bother helping their own if there is anything else they could possibly be doing. (including trying to find a cloaked ship).

I don't think the exiles are not like that. My understanding is that they raid other species because they are forced to be dying in lifeless star systems. Given that the Wanderer storyline is not yet complete, I believe there is hope for the exiles, and it was hinted when the Wanderers said that the exiles "betrayed" because they were afraid of the Wanderers. Also, resources are scarce and important for the exiles, so they can't afford not to repair ships if there is an opportunity to do it. I like your suggestion for them to find the cloaked ship though.

If there is a faction which is brutal and unforgiving, then that would be the Unfettered and pirates. The Unfettered loves war and strength, and it is right to make them ignore their disabled ships, since they think they are weak. The pirates are selfish people who loves lots of money, so they should ignore other disabled pirates too (maybe we can even make them plunder each other, but that's a separate issue). There is an old saying in my country: a thief is not always friends with another thief.

**Comment by Zitchas** [comment]
That's a rather valid point regarding the Korath. They are the last remainders of a brutal civilization, the ones who rejected the compromise of giving up their JD tech. I assume that some remnant of that personality is still in there. But yeah, at this point the resources each ship represents would almost certainly be extremely important. 

The Remnant's aggressive attempts to cultivate the greedy "need resources" side of their personality in order to keep a steady supply of ships coming to their systems in order to steal their tech puts an interesting dynamic on that, too. (as in, they kill ships that try to kill them, but they let any Korath ship that just goes for the cargo and loot floating around in space escape. So the Korath who survive are the ones who forgo combat to grab the easy prize. I wonder what that'll do to the Korath fleet mentality, given it has been going on for almost a century now...)

**Comment by tehhowch** [comment]
The "shortcut" i mentioned is added (using `IsTargetable()`), along with a check for overheated enemies. The more advanced behavior can be raised in the "Linger" issue, or a new one.
