### ISSUE TITLE
Drak Missions never done

### ISSUE THREAD

**Issue by FireWolf74** [endless-sky/endless-sky#3786]
When will these missions become available? Even though they show done.  I hope this clears up the confusion.

**Comment by temtemy** [comment]
Endless Sky is a FLOSS (free, libre, and open source) game. There is no precise time when a feature will be added.

**Comment by Amazinite** [comment]
The ES Github is for feature requests and bug reports. If you're wanting to ask a question about the story or other content in game, you should do so over on either the [Steam forums](http://steamcommunity.com/app/404410/discussions/0/) or [Google Group](https://groups.google.com/forum/#!forum/endless-sky). Please close this issue.

**Comment by FireWolf74** [comment]
Temtemy,
It is not FLOSS it is FOSS (Free Open Source Software). 
Amazinite,
You are correct if I was just asking it, but because these missions are showing as "# What you've done:" which as far as I can  remember I have not done these missions.  That would be consider to be an issue, am I not correct.
Now to let you know the entire pastebin there is as current as of 08:55 Monday June 18 2018 EST 
https://pastebin.com/wW7YUPKr

**Comment by jafdy** [comment]
That is the only way currently to ensure a single, non replacing entity remains in a singe system. "Fixing" this would require code changes that would have no effect to people not looking in their save, and very limited if any effect even on those.

**Comment by KiLEdEnNis** [comment]
so a summary
those missions say done basically to create lasting Archons in those systems, and because you know how look in your save but you have no actual clue how those things work, you basically created a problem that doesn't exist; it's intentional, these missions can't be completed as they are not meant to

if you have such questions, ask them on Steam, Discord, Google Groups idc but not here
there's a time and place for everything, but now

what you should do now: close this issue and save future questions for one of the platforms Amazinite posted

**Comment by temtemy** [comment]
@FireWolf74 Both "FOSS" and "FLOSS" have basically the same meaning, [it just the FSF prefers the latter because "free" in "FOSS" is unclear.](https://www.gnu.org/philosophy/floss-and-foss.html)

The Drak "missions" can actually be "done", you will need to kill the Archons in those missions to do that. You gotta steal a lot of Skylances and have a large fleet of Hurricanes, or else you get killed fast

**Comment by Bladewood** [comment]
The Drak missions are `invisible`, which means you're not supposed to have them on your mission list in-game.

OP is talking about the `# What you've done:` comment line in the save file, after the outfit and depreciation lines.
It can be misleading, but I think it gets the point across for the most part.

**Comment by temtemy** [comment]
Yeah, that "What you've done" part is confusing, I thought all of the storyline missions I've completed are there. I think that should be changed, but it is up to MZ whether he will change that or not

**Comment by Zitchas** [comment]
It might make more sense to players in general to change that to "Ongoing effects & What you are doing:"

After all, anything the player has actually *done* won't be there anymore, and instead will be in the "Conditions" section.

**Comment by MessyMix** [comment]
@Zitchas it shouldn't be something that the player sees in the first place, hence the `invisible` tag. So I don't quite see the point in separating missions from "effects" or anything to that effect. (Ba dum tss)

@FireWolf74 As jafdy said, the "mission" only exists to ensure that every time the player departs, there is a Archon that's present and staying in the assigned system. It just uses the "mission" mechanic to achieve this end. It's not really a mission that you should be completing, per se. All in all—don't worry about it.

**Comment by FireWolf74** [comment]
Ztichas,
You right those "Ongoing effects" should not be in the #What you have done.  I mean when you have rep mission I don't see those as "#What you have done", it is in a total different area.  Keeping things like the Archons and the Draks should be in the conditions or even in and event section.

**Comment by MessyMix** [comment]
@FireWolf74, I understand that you want to make it more clear to players reading their save file the difference between the two things, but ultimately whether it's actually a mission that you do or a "mission" that enables an effect or whatnot, they both use the same game engine mechanic. So there is no easy solution without going into the C++ to differentiate the two. If you are fluent in the language and the game data, have a crack—otherwise, I don't think it's worth the time for contributors to go in and make this change while they have other things on their hands. In the end, if you're reading your save file, you're already going above and beyond what the average player is supposed to see, so it's not worth changing something that the game isn't explicitly catering to.

**Comment by FireWolf74** [comment]
MessyMix,
Your right in that I'm going above and beyond.  C++ while it is hard to understand it there are great resources like pastebin that can help you writing C++.  To show this I'll use this message and then use pastebin to do the conversion into C++ and post the website results.

**Comment by KiLEdEnNis** [comment]
what even are you trying to accomplish? you've had your answer for the initial question that doesn't even belong on GitHub in the first place
so can you please close this issue so we can move on with our lives?

**Comment by temtemy** [comment]
Wow it seems it will take longer for this issue to be closed than I expected
