### ISSUE TITLE
Democratic process for pull requests?

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#379]
I've been spending my free time as a hobby to suggest various improvements to the game (as I loved the original EV and think this is the true successor) and submitting them as pull requests, and I don't mind very much if a particular PR isn't incorporated into the main game, so long as the reasons for not doing so are justified. I understand that @endless-sky doesn't want to include many of the suggested improvements just because he don't feel that they take the game in a direction he wants to go. However, I do think that part of this might just be not knowing whether a given proposed PR is desired by the community, especially given that there are only a few interested people commenting on any particular PR.

It's a shame that Github doesn't seem to have any sort of democratic process for pull requests, but I was wondering if perhaps there was a third-party solution for this. Perhaps for instance polls could be posted to Steam's community forums for feedback on any particular PR, if it's the case that @endless-sky is on the fence about a particular PR. I'm not sure on what the best solution is here, but it would be nice to have more community feedback. What do you all think?

**Comment by Wrzlprnft** [comment]
You do a great job!
but yeah, github isn't really designed for communicating with a large community..
The number of issues are quite big, and the pull requests... i personally think those threads are less for discussion and more for the real improving of the code or an idea. at least it feels that way.
http://www.forumotion.com/
Maybe that would be a solution to divide between the flood of ideas
and the work on the code
there could be links to github
and polls
and stuff

**Comment by Pointedstick** [comment]
If you like an unmerged pull request, post a positive comment!

**Comment by endless-sky** [comment]
My goal for the game is that someone who is just starting out can learn a small set of commands, etc. and then can gradually learn new features over time. If you present the user with too many controls and options up front, they will be overwhelmed. So, I worry that some feature requests will add something that is very useful for a small number of advanced players in limited circumstances, but

**Comment by guillochon** [comment]
Hence the appeal for a voting system or democratic process of some sort. It's just a couple of us debating back and forth about what's a good addition and what's too confusing. Let the broader community decide somehow.

**Comment by endless-sky** [comment]
(Sorry, clicked the wrong button.) Anyways, note that there are currently about 60-70 requests for new features. For example, there are currently ten different requests for either a new key command or a new preference. If all ten of those were added, I feel like the preferences page would be overwhelming for a new player, and many of those new commands would only be useful in a handful of situations.

**Comment by guillochon** [comment]
Of those 70 requests, wouldn't it make sense to prioritize somehow based upon outside input?

**Comment by Wrzlprnft** [comment]
if i got it right, @guillochon wants not that all the features the community comes up with to be added
he wants to have a overview about the opinion of the community about certain pull requests, to help @endless-sky to come to a decision.

Since github does not really provide a poll function, i myself suggested to open up a extra forum, so we do not depend on steam, an there we can sort things way better. we could even open up a forum-section for guest comments. Additionally we could divide "issues" into "feature requests", "bugs", "enhancements" and so on and so forth. More people could moderate stuff, but without being able to actually accept Pull requests and stuff.

**Comment by frameworld** [comment]
If this gets a forum, endless-sky needs to watch the steam-forum, these issues and the forum.
We all need to register 2-3 different accounts, It is not a particularly good idea.

But when creating an own forum, avoid the problems StarMade has.
* Give users a way to answer forum-posts with one click without disturbing the topic for everyone else.
* Like with chat-style 1 liners as feedback or indented posts hidden in a spoiler.

Everyone wants feedback.
* Most often 3 answers help and after that it is only useful to those which search for that topic because it is buried below newer threads.
* and it only helps if it doesn't contain outdated answers.

Give every questioner 3 answers and highlight the threads with are raised in importance.

**Comment by Wrzlprnft** [comment]
the point would be to redirect all posts into the new forum, but yeah, nevermind

**Comment by endless-sky** [comment]
There already is a forum:

https://groups.google.com/forum/#!forum/endless-sky

Maybe not the very best forum format out there, but it has the advantage of being free and not requiring a separate website to host it.

**Comment by guillochon** [comment]
I think a good solution here is http://poll.gitrun.com. I believe @endless-sky has to create the polls since he's the repository owner, but it does give a democratic means of judging PRs. Would be nice to see it used.

**Comment by guillochon** [comment]
Here's a solution I like better, simple polls on demand: http://poll.lab.io. Perhaps a best practice would be to add one of these poll links once a contributor feels that their PR is near-complete.

**Comment by frameworld** [comment]
http://poll.lab.io/ - bookmarked

**Comment by brendanjones** [comment]
Without trying to sound too snobby, half of the feature requests on the Steam forum aren't very good ideas. Mainly it's either because they're too new a player and simply not aware of everything that's going on in the game, or they're not an ex-EV player and are trying to take the game in a different direction (not that that's always a bad thing. Fresh ideas are good!). Also, people don't always know what's implementable, coding-wise (myself included :p ).
My point being, I'd only be polling the Git users, not the whole Steam community.

**Comment by Wrzlprnft** [comment]
Well, let's just try it :)

**Comment by frameworld** [comment]
>  My point being, I'd only be polling the Git users, not the whole Steam community.
Perhaps git users have the most knowledge because they are interested into mechanics rather than how to archive x in the game when I want it.
You always miss some users which miss a notification-email because of spam or don't open steam for some weeks.

**Comment by endless-sky** [comment]
It's fine for people who post pull requests to poll others for support, but no matter what the process won't be democratic: most of the pull requests I've received contain bugs of some sort, or conflict with other features that other people have requested, or need more polishing in one way or another.
