### ISSUE TITLE
Liberated Shiver has government: pug

### ISSUE THREAD

**Issue by kilobyte** [endless-sky/endless-sky#38]
In one of last Pug missions, the planet that you liberated and are defending still has its government set to "pug".  This means, it keeps demanding bribes (hmm... and why would Pugs even accept them?).  That's inconvenient especially as I found no other way to complete Pug missions other than massive land-scumming.

**Comment by endless-sky** [comment]
Note: the Pug missions are different from all the missions up until then
because the escorts that get assigned to you persist from one mission to
the next (including the Syndicate reinforcements you get halfway through.)
So, if you allow half of your fleet to die in the very first battle, all
the subsequent missions will be nearly impossible. But, if you take good
care of your fleet and repair any of the ships that get disabled, the later
missions are not too difficult.

I tried to include plenty of warnings of that in the mission text, but
maybe I should make those warnings even more explicit. For the first
mission, if you win the fight but lose *all* your escorts, when you land
you are told, "You've won the battle, but lost your whole fleet, so future
battles will be very difficult." I should probably add the same sort of
warning to the other Pug missions as well.

**Comment by kilobyte** [comment]
There's no real way to "repair" your fleet, other than abusing landing.  And by such abuse, I mean starting a new land right after launch, using the few seconds before your ship positions itself to shoot a bit.  As your entire fleet consists of capital ships, they won't get destroyed that fast and the landing will replenish their shields while Pugs, being small, will lose a few ships during those seconds.

I spent several days attempting the Pug missions, without much success until I learned the landing abuse.  For example, the very first battle is lost a vast majority of the time, I managed to survive it with four out of six ships in a repairable state only twice (once with a captured Zibruka as a bonus :) ).  As for the second battle, I did not manage to complete it even once without land-scumming, in a massive number of attempts.

Thus, either I'm missing something, or the missions are currently not doable without degenerate tactics.

As for the warning that you need to take care of your fleet, I think that's discoverable enough, especially after a few attempts.

(Note: this discussion strayed far from the initial bug report, about Shiver's government not changing after liberation.)

**Comment by endless-sky** [comment]
Now that I'm back at my development computer, I see that I'd actually designed that mission expecting you to travel directly to Earth with your fleet and fight the Pug there (along with the Navy reinforcements), rather than staying in the Altair system. I added some text to the mission conversation to reflect that.

Also, for the earlier missions were you using the trick where you hold the jump key (to get all your ships ready to jump simultaneously) so no one ship of yours gets ganged up on? I replayed those Pug missions, and they're definitely hard (this *is* the very end of the story line, after all), but they shouldn't be so hard that you have to use tricks like landing over and over again to heal.

(By "repairing," I just meant boarding disabled ships to reactivate them. If you don't do that, any ships that are still disabled are lost when you land.)

**Comment by endless-sky** [comment]
The text changes in 55f62cd should give the player a clearer idea of how they're expected to finish the final missions. I think more playtesting and balancing will still be needed, but I'm marking this particular issue closed.
