### ISSUE TITLE
Double Kor sestor fleet

### ISSUE THREAD

**Issue by TechnoNinja64** [endless-sky/endless-sky#3804]
If you drop the bomb or super nuke or whatever before killing the kor sestor fleet in Alnilam and return to far point, another kor sestor fleet will spawn in Alnilam that you need to eliminate before progressing, the fact that there is a 'double fleet' makes progressing very difficult unless you have a powerful fleet yourself. I think it would be much better if the second fleet is not added until the first fleet is destroyed making it much less hard. Other people have experienced this issue: https://groups.google.com/forum/#!category-topic/endless-sky/OPKMyvzfxr0

**Comment by KiLEdEnNis** [comment]
if that'd be true one could leave 1 ship alive and exploit is
I think the goal was to just escape without destroying the fleet though? later you can ask the Navy to send reinforcements to clean up

**Comment by TechnoNinja64** [comment]
I guess it could be exploited but the main reason why I wrote this is that it is difficult to destroy a single sestor fleet alone yet two together would be more than twice as difficult and to a player that doesn't have any more than one ship - near impossible.

**Comment by KiLEdEnNis** [comment]
I suppose having the 1st fleet always disappear & spawning the 2nd fleet could work
but this specific mission plus basically all the Kor Sestor vs humanity missions has been brought up in #3429 , which makes this a duplicate issue
right now I'm kinda waiting for (???) to start the balance test of the full Wanderer storyline, so it'll hopefully get fixed before next update

**Comment by Amazinite** [comment]
It looks like the first fleet in Alnilam spawns from "Wanderers: Sestor: Alnilam Fleet 1", which spawns after "Wanderers: Sestor Attack" is done, the mission where the Sestor attack the Wanderer planet in Korath space.

The fittingly named "Wanderers: Sestor: Alnilam Fleet 2" spawns after "Wanderers: Sestor: Quarg Help 2" is done, which is the point where you're told to bomb Zenith. So bombing Zenith isn't what's spawning another fleet, but there are two fleets there.

Instead of having the first fleet being defeated spawning the second fleet, I think it'd just be better to decrease the number of ships.

Fleet 1:
* 2 Heavies
* 1 Medium Carrier (16 fighters/drones)
* 3 Lights

Fleet 2:
* 1 Heavy
* 2 Medium Carriers (19 fighters/drones)

It is important to note that if you do bomb Zenith, the pirates become hostile to the Sestor ships, which you can use to your advantage to slowly widdle down the Sestor ships, but a combined strength of 3 heavy warships, 3 medium warships, 3 light warships, and 35 fighters and drones is a bit much.

**Comment by Amazinite** [comment]
I found that without a cloak, the most difficult thing about attempting to land on Zenith was the number of Detainers, massively slowing down your flagship and allowing you to be swarmed.
In 0436d65, I not only dropped the number of ships with Detainers from 7 to 1, but I also lowered the number of ships as to make fighting them later on easier.
