### ISSUE TITLE
Trading

### ISSUE THREAD

**Issue by UserPlayer** [endless-sky/endless-sky#3876]
At times the price of resources isn't displayed right. It shows profit :xxx instead of low or high without having any resources of that kind in cargo.

**Comment by Amazinite** [comment]
Is this a bug report? Can you describe how you get this bug to occur so that we can recreate it?

**Comment by Pointedstick** [comment]
And better yet, add a screenshot?

**Comment by tehhowch** [comment]
Pretty sure this is cargo in parked or out of system ships. A known issue.

**Comment by Pointedstick** [comment]
A known-non-issue? 😝

**Comment by RedLucidity** [comment]
The out of system ship that has that type of trade cargo is also what I figured out... Perhaps some dialog in game as part of a starter mission might help with understanding this mechanism.

**Comment by tehhowch** [comment]
@RedLucidity if you review the issue i linked, you will note that this issue is addressed.

Please verify you observe the behavior you take issue with on the current `master` branch. **If you cannot reproduce it, close this issue.** If you can, then you need to provide more detail about the behavior you are talking about.
