### ISSUE TITLE
random Republic planet sells ILLEGAL nerve gas. Trinket in Sargas system

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#388]

**Comment by endless-sky** [comment]
Trinket is described as a favorite vacation spot for pirates. The idea was that there are some shady markets there where you can get things that are usually only available on pirate worlds.

**Comment by eggels** [comment]
It's the only non-pirate system to sell Frags too, which is great for early game boarders and also really risky if you buy nerve gas without a lot of reserve funds to pay the inevitable fines.

**Comment by frameworld** [comment]
Interference plating... I thought each halves the chance to get detected with nerve gas.

But when I looked at the code file, I saw it uses a 1/ (1+ 0.5n) formula, which is 67% detection for the first, 50% for the second, 40% for the third, 33% for the forth plating... Approaching 0, never reaching it.

The issue is that the value ingame says 0.5 and you assume 50% for the first.
A more intuitive formula would be "f/ (f+ fn) with f=.5and f >0" => ".5/ (.5 +.5n)

How many interference platings are you supposed to buy? 4 already cost 16 outfit space - a tiny ion thruster.
