### ISSUE TITLE
Different disable rules

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#3882]
Currently there are rules that when ship's hull is at 50%–20% (depending on max value) the ship becomes disabled.

I'm proposing that the ship becomes disabled at 0, and begins exploding at either −20% (if striving to retain some semblance of status quo), or −100%. (Leave current ship stats in data files as they are.)

Gains:
More obvious hull amount balancing w/o additional obscure formulas;
Current small ships gain a little boost;
(−100%) *Hiding behind disabled ships* tactic more viable, or (−20%) while smaller ships become a bit more useful, there will not be a shit ton of them to capture after large fights.

**Comment by Amazinite** [comment]
#3448?

**Comment by Tadrix** [comment]
The referenced issue is a great idea on itself, but doesn't quite duplicate my proposition. This issue here would be satisfied with any fixed disable value as well, be it −20%, −25%, −100% or whatever.

The point is:

1. Have 0 be always the disable value, and some negative value be the value where explosions start. It makes for much easier combat/balancing calculations for humans (if I know that the value in data is the value till the ship is useless, I don't need to calculate at what percentage it's disabled).

2. Originally, this proposition suggested having the same disable percentage for all ships, which would either preventing interceptor snowball and making them more useful (in case it's low), or making hiding behind disabled ships a worthwhile tactic (in case it is high).

**Comment by endless-sky** [comment]
There are some situations in the game where you want to know how much more damage you need to do to a ship to disable it, but there are also situations where you want to know how much damage you must do to kill it.

There's no obvious way to show a negative hull value in the UI, and it would be annoying to have to keep pumping fire into a disabled ship without any idea of how much progress you're making toward disabling it.

Having a fixed disabled % cutoff wouldn't work for very small ships, because the line between disabled and destroyed could be a very small amount of damage.

If the point is just to make it so the player always knows at what point the ship will be disabled, a simpler solution would be to just display the disabled zone in the HUD:

![disabled indicator](https://user-images.githubusercontent.com/11450262/43670297-26050d5c-9758-11e8-9e80-c4f52a81f987.png)

(Of course, the current line-drawing code couldn't handle that properly, but it would be possible to change it.)

If the point is to buff small ships, that could just be done by increasing their hulls, but a lot of balancing has already gone into the current relative strengths of the ships.

**Comment by DingusShingleton** [comment]
That line looks sick. Very smooth. I would say the color could even be a bit more subtle, but it looks great as is too.

**Comment by endless-sky** [comment]
Well, it turns out adding the disabled zone to the UI was pretty easy (e2e8898). On the other hand, having it at exactly 50% looks weird - a new player might think it's a left / right split in the colors or something and not realize the red is marking a specific fraction of the distance around the circle. Maybe the max should be changed to 40% or so.
