### ISSUE TITLE
Fleet battles devolve into close-range brawls

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#3884]
Because of the way the AI currently works, large fleet battles almost inevitably devolve into huge brawls in the center of the system with like 50 ships practically on top of one another, all of them firing everything they have in any direction. Formations are lost, weapon range becomes unimportant, and missiles lose their advantages over guns. How combatants fare becomes largely a function of their shields and the raw damage output of their turrets, with a large element of pure random chance.

This seems to happen because of a combination of factors:
- Initial random fleet positions are too close to one another, and too close to the system center
- Reinforcements warp in really close to the system center
- AI fleets seem to have no conception of formation, and their ships make no effort to re-form once cohesion is lost
- AI ships seem to make little to no effort to escape from the giant deathball of firepower once they're inside it
- AI ships armed with both missiles and guns show no preference for range (not even a small one)

Thoughts?

**Comment by Variance-Moment** [comment]
I think the AI might need an improvement. It gets boring seeing fleets focused mainly towards the equivalent of a "gear carry" instead of tactics, when it should be a balance of both.

**Comment by tehhowch** [comment]
Changing the AI combat behavior gets tricky - right now the only (meaningful) choice a ship will make when fighting is to flee if its health and personality allow it. This behavior guarantees that ships will not make the decision to attempt to outmaneuver ships (possibly dying) when they could simply attack and emerge victorious.

Because of the simple combat movement AI (thrust and turn if possible, so the opponent needs to turn too and we can maybe outmaneuver them), we are guaranteed that attacking ships will damage each other consistently. Changing the combat AI to select strategies that make sense to a human viewing/participating in the battle, and also are not extremely frustrating (e.g. missile boats that jump away once their ammo is gone so you can't destroy them), is non-trivial, especially if we want to maintain performance in large battles. 

Note that making complex decisions involving maneuvering vs firing generally requires considering not just the position of the target and the ship, but of in-system enemies and allies as well (i.e. easy to implement as `O(n²)` code). This is especially "fun" if a ship has multiple attack vectors (i.e. fixed-angle / broadside hardpoints). #2788 could limit some of the impact of repeated in-system ship access, though there are probably good algorithms for spatially-related data that could prove useful (and which I currently know nothing about), since "ship combat" isn't exactly a concept unique to Endless Sky.

There's a lot of existing issues about altering combat ai. I don't claim these are all 100% relevant, or even that this is an exhaustive list of related material:  
#1537, https://github.com/endless-sky/endless-sky/issues/1932, https://github.com/endless-sky/endless-sky/issues/2220, #2313, https://github.com/endless-sky/endless-sky/issues/2748, https://github.com/endless-sky/endless-sky/issues/2916,  https://github.com/endless-sky/endless-sky/issues/3853

**Comment by Tadrix** [comment]
> also are not extremely frustrating (e.g. missile boats that jump away once their ammo is gone so you can't destroy them)

Let them jump out.
Then it should either count as killed for the mission purposes, or it would make a journey to the nearest outfitter that sells appropriate ammo and return to spam missiles once again. Which would open up an interesting choice for the player — either ignore missile boats at first, or chase them down to kill ASAP.

**Comment by Pointedstick** [comment]
> Let them jump out.
> Then it should either count as killed for the mission purposes, or it would make a journey to the nearest outfitter that sells appropriate ammo and return to spam missiles once again. Which would open up an interesting choice for the player — either ignore missile boats at first, or chase them down to kill ASAP.

+1, this sounds like a great idea. It certainly makes more sense then having them uselessly fly around you with no offensive abilities whatsoever once their missiles are gone.

**Comment by DingusShingleton** [comment]
There's a problem with that... A jump takes a day. If the ship jumps out, lands to repair, then jumps back, in theory three days have passed during one continuous battle. I'm not sure that it matters, but it did just occur to me, so I thought I'd point it out.

**Comment by Pointedstick** [comment]
FWIW the same thing happens when your escorts land to refuel: it happens instantaneously rather than taking a day.

**Comment by DingusShingleton** [comment]
Hmm... I suppose that's true. And I guess that's why I wasn't sure it mattered. Because clearly it already doesn't :P

**Comment by johndh** [comment]
Another contributing factor is that an infinite (AFAIK) number of ships can occupy the same space, so there's no requirement to spread out.  With space being 3D, there's no reason that an infinite number of ships couldn't occupy the same (x,y) coordinates in an infinite vertical stack, but why would they?  A group of ships centered on a point (like a planet or flagship) would form a sphere, not a stack.

As far as missile boats go, aren't they almost always small-to-medium pirate ships?  It seems like the most intuitive thing for them to do is fire their missiles, hope that somebody gets disabled, destroyed, or hurt badly enough to surrender, and if they fail they just cut their losses and jump away.  Even if they're able to land somewhere in the same system, like on a station, it should take some in-game time before they're ready to fight again.

**Comment by Pointedstick** [comment]
Basically a duplicate of https://github.com/endless-sky/endless-sky/issues/3853
