### ISSUE TITLE
Messages::Add causes immense slowdown when number of messages is in thousands

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#390]
Was testing a PR that happens to dump a lot of messages to the screen for testing purposes, and noticed that the game had slowed down by a factor of 5-10 after printing a few thousand messages, and remained slow even after the messages had faded from the screen. Not sure what exactly causes the slowdown, but the GPU fraction also spikes dramatically when the messages are displayed, ~200-300% usage! Perhaps it suggests a memory leak within the messages system?

Here's a screenshot when things are slow:

![image](https://cloud.githubusercontent.com/assets/4998058/11611518/3b21aa94-9ba0-11e5-82a0-70fe8c7ecf31.png)

**Edit**: The game does speed back up once the messages have *completely* faded, which takes a lot longer when the game has slowed down.

**Comment by endless-sky** [comment]
That probably just means that the font rendering engine is somewhat inefficient, which is not surprising because it draws each glyph individually. That means that much text could easily generate 100,000 draw calls.

I think the best solution would just be to limit the number of messages on screen at once, which I can do easily enough. (Or, I could just make it stop "drawing" them once they're above the top of the screen.)

**Comment by guillochon** [comment]
Limiting the number of messages to an amount that guarantees it doesn't go behind the UI seems reasonable to me.

**Comment by endless-sky** [comment]
Fixed in commit a3ff9ba.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
