### ISSUE TITLE
Missing program icons for Linux

### ISSUE THREAD

**Issue by grawlinson** [endless-sky/endless-sky#3913]
https://github.com/endless-sky/endless-sky/blob/ffd15a7453c7cc48b5c70ed7a8bbd3beb4f7e1cb/SConstruct#L68-L75

Just wondering why the Linux icons are missing the following sizes: 128, 512. These can be found alongside the Mac icons in `icons/endless-sky.iconset`

**Comment by Pointedstick** [comment]
Does this result in any visible problems for you?

**Comment by Pointedstick** [comment]
128 wouldn't help you for a HiDPI screen, but 512 would.

I'm pretty sure the icon isn't an SVG because it's simply an edited render of a 3D model, not something that was made in Inkscape. I know we have some artists here, so maybe someone could create one.

**Comment by MCOfficer** [comment]
![icon_scalable_simpler](https://user-images.githubusercontent.com/22377202/52523672-23dd5300-2c94-11e9-8a3a-79ad818d6ed7.png)

I tried to convert the current icon to svg, and it turned out better than i expected (thanks, vector magic). Ironically, this is a png version of it, because github doesn't like svgs. It looks a bit goofy at full size, but holds up well until ~512px, and weighs in at almost 1MB. Thoughts?

**Comment by Pointedstick** [comment]
That's pretty impressive for an SVG conversion, and I kind of like how "arty" it looks. However those shadows would need to be re-done by hand, probably.
