### ISSUE TITLE
Parole

### ISSUE THREAD

**Issue by tmbutterworth** [endless-sky/endless-sky#3932]
The section of the text that first initially discusses Parole is Typo/Confusing.

"The Council has decided," he continues, "that any of you who gives us your parole, swearing to take no further part in fighting the Free Worlds, will be returned to Republic space.

The navy is not giving parole the free worlds is offering parole.

It should be:
"The Council has decided," he continues, "that any of you who gives us your word, swearing to take no further part in fighting the Free Worlds, will be returned to Republic space.

**Comment by comnom** [comment]
See 1. It's common enough in literature that I don't see any point in changing it.

Definition of parole
1 : a promise made with or confirmed by a pledge of one's honor; especially : the promise of a prisoner of war to fulfill stated conditions in consideration of his release
2 : a watchword given only to officers of the guard and of the day
3 : a conditional release of a prisoner serving an indeterminate or unexpired sentence

**Comment by tmbutterworth** [comment]
I submitted a pull request to change it. The navy is not giving parol they are giving their word to receive parol.

**Comment by DingusShingleton** [comment]
1 : a promise made with or confirmed by a pledge of one's honor; especially : the promise **of a prisoner** of war **to fulfill stated conditions** in consideration of his release

In this definition of parole, it is indeed given by the prisoner. I didn't know that either, since by vast majority the most common use of parole I would say is for people in jail being released on it. But I don't think it matters much either way

**Comment by tmbutterworth** [comment]
In that definition of parole is what they are "receiving", parole is a state of being/condition, not what they are providing "Promise or pledge of ones honor". The Free Worlds are providing parole, the navy is accepting the conditions to receive it.

The dialogue is asking the navy to "Give Parole" when it should be asking them to accept parole.

It should be worded like this:
 "that any of you who gives us your word, swearing to take no further part in fighting the Free Worlds, will receive parole and be returned to Republic space.

**Comment by endless-sky** [comment]
As several people have pointed out to you already, the existing usage of "parole" is correct and does not need to be changed. The use of the archaic sense of the word "parole" rather than the modern sense is intentional. The Free Worlds have no legal authority to grant parole to the Navy officers in the modern sense (and no power to enforce it even if they did), but the Navy officers (because of how honor-bound they are) are capable of giving parole in the historical sense.

**Comment by DingusShingleton** [comment]
While that certainly makes sense, it recalls the scene in Avatar where they refer to the mineral unobtainium. Everyone thought that was the dumbest made up sci-fi word they'd ever heard... Only problem is, it's an actual word that refers to the hypothetical perfect solution for a given problem. 

But the fact that it was technically a word didn't matter to the millions of people who had never heard it; they thought it was a dumb made up word anyway. 

In this case, it's a minor part of one sentence (not a major plot device), but nevertheless, most people will think it's an error. Does that matter at all? Not really, but it is what it is.

**Comment by tmbutterworth** [comment]
I understand your usage now. There are over 20 dialects of English, and we consider your usage to be old English "I pledge my parole to thee" similar to "I pledge my fealty to thee" We treat parole as a condition/state of being/contractual agreement.
