### ISSUE TITLE
Gridfire and Tier 3 Anti-Missile images

### ISSUE THREAD

**Issue by Nescio0** [endless-sky/endless-sky#3967]
Currently most Pug outfits have images in a style similar to the Pug ships. However, the "Pug Gridfire Turret" and "Tier 3 Anti-Missile" don't have hardpoints nor outfit images yet. It would be nice if someone (@comnom?) could design them.
Quite a few players would be able to admire these, because capturing an Arfecta is not very hard.

**Comment by Nescio0** [comment]
Sprites for Korath outfits have been added about two years ago, sprites for Quarg outfits are proposed in #3536. Drak Archons cannot be disabled and therefore their outfits are unobtainable. That means these two Pug turrets would be the only two outfits with an "unknown" sprite. It is unclear if and when more Pug 3 content will be added; Arfectas are already present and capturable in game, therefore it would be nice to have sprites for these T3 Pug turrets sooner rather than later.

**Comment by KiLEdEnNis** [comment]
of course, but

> It's better to do these things as sets rather than one-off images that could be made with a large span of time in-between for better consistency/theming.

**Comment by comnom** [comment]
@Nescio0 I get where you're coming from. It would be nice in terms of completeness, but from a design standpoint it's premature. ex. The t3 anti missile doesn't even have a proper name.

When thinking about a future set of artwork, we have to keep in mind the consistency I mention above, but also the artist. The pug aren't my addition to the game, they're the dev's. Since he's more than capable of doing the artwork on his own, we should first defer to him to see if he has a certain design in mind, and also if he wants to do the artwork. For someone that enjoys CG, it's a fun project to mix in with other stuff that could be drudgery.

So I haven't even considered it before this issue, but if I did, I wouldn't start on it without knowing what his plans for the pug are.

**Comment by Amazinite** [comment]
#4196
