### ISSUE TITLE
High-DPI Plugin Inactive

### ISSUE THREAD

**Issue by Onion-S** [endless-sky/endless-sky#3973]
There seems to be a problem with the high resolution plugin

I'm running ES on a Dell Precision M3800 with a 3200 x 1800 pixel 15" display.
The High DPI plugin is installed, but the game will not use the high-resolution sprites unless it is zoomed in.

The `Main Zoom Factor` in the settings panel refuses to be changed, and claims that "your screen resolution is too low to support a zoom level above 100%"

(Version 0.9.8, with Steam on Windows 8)

**Comment by Philemon120** [comment]
You may get better feedback here: https://github.com/endless-sky/endless-sky-high-dpi

**Comment by jafdy** [comment]
Check what resolution windows is running at, ES uses the resolution from windows and not the native screen resolution. For 15" screens 720p or 1080p are the common resolution.

**Comment by Onion-S** [comment]
> 
> 
> Check what resolution windows is running at, ES uses the resolution from windows and not the native screen resolution. For 15" screens 720p or 1080p are the common resolution.

Windows is running at full resolution

**Comment by jafdy** [comment]
Well the game is running at something below 1080p.

**Comment by endless-sky** [comment]
I'm not sure if anyone has actually tested high-DPI on Windows; I only had access to a high-DPI Mac for testing it. In any case, the expected behavior is that the high-DPI graphics are only used if the effective zoom factor is at least 200%.

It's possible that [something special](https://nlguillemot.wordpress.com/2016/12/11/high-dpi-rendering/) needs to be done to tell Windows 10 that the program is capable of high-DPI rendering. That might be as simples as calling `SetProcessDpiAwareness(PROCESS_PER_MONITOR_DPI_AWARE);` at the start of the program when running on Windows; I just haven't made that change because I had no way to test it.

**Comment by Zitchas** [comment]
I would be happy to test, but I'm not really a programmer, so I'd need some fairly specific instructions of how to test it.

**Comment by quyykk** [comment]
High DPI now works correctly on Windows!
