### ISSUE TITLE
Drones/fighters Bay Enhacement

### ISSUE THREAD

**Issue by ThatAtom** [endless-sky/endless-sky#3997]
The fighters/drones could share their cargo with the flagship while it is in the bay. This will allow extra space for stealing outfits from a ship for example. The same thing can be applied for excess power/cooling, and crew.

**Comment by jostephd** [comment]
Sharing **power** is plausible and would open new tactical possibilities (tradeoff flagship mass for power generation). I suppose this also goes for **cargo**.

Sharing **crew** makes perfect sense. It would need some thought regarding how to distribute the surviving crew members among the flagship, the captured ship, and their combined fighters, should an attempted boarding result in fewer surviving crew members than required to operate all those ships. Or what should happen if the flagship's in flight with fewer than required minimal crew, and then a fighter docks in: will its crew be used to replenish its mothership's crew, and if so will it be able to launch again, etc. (Escorts can't replenish the flagship's crew because escorts always fly with minimum crew.)

I'm not sure if sharing **cooling** is realistic (of course, realism's not the only criterion). If a drone runs its cooling inside a closed bay, it's going to _heat_ the mothership, not cool it down. For cooling to be effective the drone would need to be mounted in an external bay ([like this](https://upload.wikimedia.org/wikipedia/commons/f/fe/Atlantis_on_Shuttle_Carrier_Aircraft.jpg)), which begs the question, should ships have different **`drag` or `heat dissipation` coefficients** while carrying fighters/drones?

**Comment by ThatAtom** [comment]
The cargo pretty much only applies to one fighter.

**Comment by Bladewood** [comment]
You'd have to be careful about how the cargo is shared, similar to how it's done with normal escorts, because your fighters are their own separate ships and not actually part of the flagship.
Suppose I have a flagship with 60 tons of cargo space and a fighter with 20 tons of space.
I shouldn't be able to steal a 70-ton outfit, because then I'd have to cut it up into 60- and 10-ton parts, which is impermissible.

I don't see this happening for the same reason that you can't order escorts to board ships: it is brokenly overpowered.

**Comment by ThatAtom** [comment]
The fighter carrier will always come first when it comes to lack of crew. Maybe the fighter won't launch when there is a lack of crew.

**Comment by ThatAtom** [comment]
The only fighter with a sizable cargo hold is the box wing at 80 cargo. Most outfits are smaller than 80 outfits space. If does not fit in the fighter carrier or box wing then you won't be able to pick it up.

**Comment by ThatAtom** [comment]
Some Drones also have a cargo hold.
