### ISSUE TITLE
Have ships "holding position" stay at one location instead of drifting

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#400]
Currently, the term "hold position" means turn off thrusters after half-heartedly trying to align yourself. Gets annoying when trying to keep a strong formation for attacking and defending when most of your ships float of into space. Maybe and installable air brake or something

**Comment by brendanjones** [comment]
Agreed. When I say hold position, I want my ships to stop as soon as their thrusters allow (if moving), and actually stay in that position, not cut some of their speed and keep drifting.

I'd like to add one more thing: a 'hold fire' button. As I understand it, there's no way to stop your escorts firing. Sometimes you just don't want your ships to fire on an incoming ship, but even if your escorts are holding position, they still fire. The 'hold fire' button should not be tied to 'hold position', because you might want your escorts to be flying along with you and not firing.

**Comment by thenerdfreak** [comment]
Anybody have any idea how this would be done? how to code in making the ship turn and thrust to a  complete stop?

**Comment by endless-sky** [comment]
This would require a ship to remember what position it is trying to "hold," and to actively fire up its thrusters and return to that position if it gets too far away. That sort of addition to the AI would allow other things as well - for example, right-clicking the screen to tell your escorts to move to a certain position, or adding a personality type that "camps" around a planet. So, it'll probably be added when I start to work on better tactical-level fleet controls.

**Comment by brendanjones** [comment]
Rather than always having the escort return to one specific position, wouldn't it be better if the hold position command meant that if they are moving, they stop moving as quickly as their thrusters allow, and then stay in that position? So if the escort was already holding position, and was set moving again by, say, a large ship exploding nearby, then the escort would (as quickly as possible) manoeuvre to face 180° against the direction of travel, and fire thrusters to come to a halt. Wherever they stopped is their new held position.
Returning the ship to one held position sounds like harder work than a command that says a ship should continuously stop itself moving whenever it is moving. Or not... I ain't a coder :)

**Comment by LocalGod79** [comment]
i played with this a little bit - the problem seems to be that it's not possible for ships to actually stop - if their acceleration for a single frame does not divide evenly into their current velocity (i.e. almost never), the remainder will be their drift rate.

quite simply, even the a.i. cannot manage the task, because the tools it has aren't capable.

so, if even you set a point in space that it's supposed to seek, it will forever be flying around trying to stop on that spot, in spite of its inability.  this would prevent our escorts from behaving as we all expect them to when 'holding position'.

until such time that one can apply an incrementation of those large thrust figures (which really only has this one application), this problem will remain unsolved...

**Comment by endless-sky** [comment]
Oops, I was working on a solution at the same time you were: 599cb35.

What I did was to add a "hidden" STOP command that the AI sets to tell the ship that if possible, it should apply fractional thrust less than its full capability, when doing so will make it possible to zero out its current velocity in the direction it is facing.

**Comment by LocalGod79** [comment]
:laughing: i like yours better.

**Comment by brendanjones** [comment]
"if their acceleration for a single frame does not divide evenly into their current velocity (i.e. almost never), the remainder will be their drift rate."

![i know some of these words](https://cloud.githubusercontent.com/assets/16049594/14342931/e2c3e01a-fc9d-11e5-8398-f6f2bdf7c064.jpg)

Yeh this makes me realise I can never be a developer, and I should stick to words (I used to be an editor).

**Comment by LocalGod79** [comment]
@brendanjones lol, literally (1).  basically it means that previously, a ship would virtually always end up drifting at a speed between 0 and their single-frame acceleration, so that when it tried to stop it would just add too much velocity in another direction.

we could use your help writing for the Republic storyline, if you're interested.

https://groups.google.com/forum/#!category-topic/endless-sky/OMC1MdSO9Ac

**Comment by brendanjones** [comment]
I'll take a look, and contribute when I can :) My work keeps me fairly busy so my efforts will always be a bit sporadic...

**Comment by LocalGod79** [comment]
(done) https://github.com/endless-sky/endless-sky/commit/599cb35f31ec66cbbbe940947b0e7569f381d1c5

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
