### ISSUE TITLE
French Trad

### ISSUE THREAD

**Issue by Skornflex** [endless-sky/endless-sky#4053]
Hi ! As you've see from title i'm French, i work in IT and english is not really a problem for me, but i would like, if possible, make a trad in French so i can make some friends play the game with me :)
Let me know if that can be interesting for you, i've often go free time in my work ;)

**Comment by jafdy** [comment]
The game's data files are all .txt based so as long as you don't need to use characters outside the normal English ones you will be able to translate just fine.

**Comment by Skornflex** [comment]
Hi, thanks for your reply, i'll try then, and come back when finish, i can take txt files from debian version and still can distribute files to windows for example ?

**Comment by jafdy** [comment]
.txt files are compatible across all versions.
No, you couldn't use "réparé" because it contains "é".

**Comment by MCOfficer** [comment]
Related: #3312

**Comment by Pointedstick** [comment]
Unfortunately there is no translation framework, so creating translated versions of the current files would be pointless since they're all intermingled with code, which can change.

Additionally, translating the Debian package versions of *anything* is a bad idea because Debian packages are ancient; your work would go to waste since many strings you translate will have changed in the meantime. You always want to be working with the current source code version when translating.

Once translation support is implemented, we'll be sure to reach out to all the people who volunteered. :)
