### ISSUE TITLE
Feature request: Variable turret crew (depending on the ship type)

### ISSUE THREAD

**Issue by Tadrix** [endless-sky/endless-sky#4054]
Currently, there's usually one gunner per turret, and it's understandable for ships like the Barb (one pilot, one gunner). However, on larger ships the crew usually operates in shifts (which is the reason for large crews), because people have to sleep sometimes, and warships are likely to staff their turrets all the time. Which is why I propose for the turret crew specified by outfits to be multiplied by a value determined by a ship type. Adjust (lower) nominal crew counts accordingly. Consider the default to be one.

Transports, light freighters, interceptors, light warships, fighters: 1 (the default);
Heavy freighters, medium warships: 2;
Heavy warships: 3.

Which means that a turret on a heavy freighter or a medium warship would require 2 crew (or 4, for Dual Sunbeam Turrets); a turret on a heavy warship would require 3 crew (or 6, for Dual Sunbeam Turrets).

**Comment by Pointedstick** [comment]
Actually in real life the real reason for large crews is generally damage control.

I'm not sure if this proposal makes sense. If we take your thought to its logical conclusion, when a small smaller ship operates the same turret with fewer people due to longer duty shifts, then that implies significantly reduced weapon performance due to crew fatigue. If instead the ship has less than 24/7 coverage due to the to the available crew being asleep some of the time, that means that sometimes the turret isn't available. I'm not sure this level of specificity gains anything, and would probably just be annoying.

The thing that does make sense is for larger turrets to have higher intrinsic crew requirements compared to smaller turrets, which is already possible and implemented. For example the WWII-era 5" DP gun turret had a crew requirement of 14, while a 16" gun turret had a crew requirement of 79. Obviously only the larger ships could even fit a 16" gun turret, so to a certain extent the manning requirements of the turret matched the size of the ship anyway.
