### ISSUE TITLE
Korath Worldship swears at me in the mission Remnant: Defense 2

### ISSUE THREAD

**Issue by AlbertNewton** [endless-sky/endless-sky#4078]
**Describe the bug**
During the mission Remnant: Defense 2 (spelling mistake intentional as that is what the mission is called - another issue here?) the ship can send hails reminiscent of 'Pirate' ships when disabled to the main screen. I have an example here(look at the bottom)
![image](https://user-images.githubusercontent.com/42004388/50111341-7a9a5380-0234-11e9-9741-909ab88fc699.png)

**To Reproduce**
1. Take the mission in a pilot
2. Disable the ship
3. Wait a little while
4. You should see insults thrown at you from the Worldship

**Expected behavior**
I expected to not receive English hails from a creature speaking an alien language.

**System (please complete the following information):**
 - OS: Windows 10 Home. I know no more except that I always do all updates.
 - Game Source: nightly, last updated yesterday
 - Version: 16 December's nightly

**Comment by Zitchas** [comment]
That is problematic. I'll test that later today.

**Comment by Zitchas** [comment]
Sorry, took me longer than expected to test this. Along the way I noticed that disabled Remnant ships also have the same problem.

In regards to the spelling of Defense, yeah, Fzzr nailed it: Due to the fact that the founding/primary developer for ES lives and works in the USA, he used American English spelling for everything, so that's the standard for ES.

**Comment by tehhowch** [comment]
For a government that does not define friendly or hostile disabled hails, they have default values:
https://github.com/endless-sky/endless-sky/blob/46713549172774bf5777f0319678365eed93b2c4/source/Government.cpp#L124-L128

While the Korath have a defined `language`, language checks are pretty sparse in the game currently, and one is not present in the standard `Engine::SendHails` logic:
https://github.com/endless-sky/endless-sky/blob/46713549172774bf5777f0319678365eed93b2c4/source/Engine.cpp#L1537-L1541

but one is present in the `Engine::DoGrudge` logic:
https://github.com/endless-sky/endless-sky/blob/46713549172774bf5777f0319678365eed93b2c4/source/Engine.cpp#L2023-L2030

(The only other use of a `Government::Language` check is performed when you open the hail panel with a ship or planet)

I am not quite sure why the disabled ship is able to send the hail at all, to be honest, since the `CanSendHail` function explicitly states that disabled ships cannot send a hail. I'd need to walk through the call stack to see exactly how / when these messages are popping up.

**Comment by tehhowch** [comment]
Perhaps also applies to random Raiders: https://discordapp.com/channels/251118043411775489/536900466655887360/683699943281524793

**Comment by SubstandardZeal** [comment]
I just saw a Ka'het Telis'het do the same
