### ISSUE TITLE
On the Navy and Syndicate campaigns: a question about the intros

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4089]
Just some quick info:
* Kiko posted the Navy intro in #3959, but he has unfortunately decided to not continue working on the Navy campaign.
* I'm currently working on a Syndicate intro and I'm almost done a rough draft of the string of missions that parallels FW Katya with all the other intro missions (Syndicate Commitment excluded) done.

<hr/>

Should we merge the intro missions to these two campaigns without having the entire things done?

Arguments for:
* More content in the game.
* Shows that these campaigns are being worked on, a taste of what's to come.

Arguments against:
* If like with #3959 the writer quits, then whoever picks the missions back up may end up scrapping what was already there.
* Having the intro missions without the rest of the campaign may be confusing seeing as how the Free Worlds would still be the only ones you can join.

👍 or 👎

**Comment by jafdy** [comment]
Having the intros there will lay out a clear step forward, even if they are then scraped that has no lasting effect because the player still won't have been asked to make the commitment yet. Notably, the FW commitment is done outside (and after) the last required intro mission is completed so although there will be a feeling of incompleteness I feel that it will be no greater than as it still is, with the intro missions not there at all.

**Comment by Brick63** [comment]
Every major content update will have fixes following it, as everyone misses something. I wouldn't call things inferior until you can produce something similar that is clearly to all present, Superior.

**Comment by Zitchas** [comment]
Well, just throwing the intro out there is basically what MZ did with the Remnant, and that was enough to spur me into writing everything in the Remnant Content PR. Having the intro to the Syndicate and Navy missions may provide a foundation upon which others can likewise build those stories. Even if a subsequent campaign completely erases and replaces all those missions, they can still provide valuable inspirational benefit in the meantime.

The only concern I have is that players may get stuck on it as they go down that route until it ends, and then have no way to continue on to the Wanderer campaign due to missing content. The only good solution I can think of is that at the end of whatever Syndicate and Navy missions we have should be some kind of "change sides" mission that moves the player over into the FW campaign at the appropriate point. 

I know veteran players will have no problem just hitting the end of the navy, realizing it, and restarting / save editing as necessary to continue. My main worry would be for new players who don't know the storylines and who get frustrated because they get stuck somewhere waiting for more missions to be made.

**Comment by Amazinite** [comment]
@Zitchas I specifically mentioned the intro missions because they wouldn’t have this issue. The player would be doing jobs for the Syndicate or the Navy, but simply never be given the chance to join in the same way that they are for the Free Worlds, therefore there’s no need for forced side switching or waiting around for more missions in the same way that people wait around for the Wanderer missions.

**Comment by Zitchas** [comment]
Ah, ok. In which I'm whole heartedly in favour of having the intro missions included. I see no downside to it, aside the fairly minor "may need to revise a few things when more content is added" which I personally think is a pretty small thing.

**Comment by TheMarksman-ES** [comment]
I'm in the Ayes camp for having the intro into the game. The reason being that it will, as you've said, give the players a taste of what's to come. It will also retain the people who may have thought that the game's development has stopped and keep them hyped for the incoming campaigns.

**Comment by 10010101001** [comment]
Introduce it to the point the player can still do the FW campaign. Just my 2 cents

**Comment by MessyMix** [comment]
Instead of the "offer" mission, there could be a little fourth-wall
breaking dialogue that would inform the player that the FW campaign is
already done.

By the way, I'm thinking that once the Navy and Syndicate intros are
introduced, we may have to expand the area that the FW intro missions are
offered in. Personally, I didn't find the FW missions until many, many
hours into the game, and there were countless people on the Steam forums
who had no clue there even was a storyline in the game. I expect most
players to end up Navy or Syndicate, because many don't venture South and
stay there. It might help FW adoption rates if we were to offer a wider
range of intro missions, or at least re-distribute the current offerings,
to cover slightly more space and give the campaign a fairer adoption chance
against the other 2. Just my 2 cents as well.

**Comment by tehhowch** [comment]
@messymix with the introduction of the `neighbor` filter we can create spaceport missions that "advertise" for the given campaigns. By making these spaceport missions, we also help ease new players into checking the spaceport when they land (since there are more chances for something to happen when they visit the spaceport).

**Comment by Janaszar** [comment]
Idea:
Put a "throw away" mission at the end of both chains, where "for some reason" , your commander/guidance person tells you to join the FW. ("We're set for now, so don't need your help. But, we think it would be nice to have someone on the inside of the FW.  I hear if you go to X, they may let you join after doing some work.")

Also, could the last mission (or that mission idea I mentioned) give the player access to the currently unavailable licenses?  In theory, it would mean players who did those missions and followed the FW would then be able to buy ships they couldn't, but given the options later on in the game for ships (or even at the same stages), I don't see much reason to prevent it.

**Comment by Amazinite** [comment]
To be fair, at least for me, the time since receiving collaborator access has been focused dealing with all these PRs that have been open for quite some time. 

While there have been a number of commits based around fixing errors in previous changes (there’s been 100 commits since any collaborator made a change, and it looks like 17 of those were fixing errors in newly added content), I’d say we’re FAR from doing little play testing and quality control. #3120? #3761? There’s clearly still a high level of scrutiny being put on PRs before they’re merged, even if small errors do get through; small errors have always gotten through, even in the past, but we’re just catching them very quickly, so it may be giving the illusion of a lack of quality control upon merging PRs simply because the quality control is actually now so high on stuff actually in the game. (i.e. errors on stuff in game are caught quickler than they otherwise would have been.)

As for a perceived lack of direction, I can see that very much being the case on a small scale (we don’t have any small scale projects right now that MZ has explicitly pointed community development toward), but we do have the direction on the large scale of getting the Syndicate and Navy campaigns done (to note, someone has picked up the Navy campaign development from Kiko) so that v1.0.0 can be a thing. That though shows exactly why stuff getting merged in the past months hasn’t brought us closer to v1.0.0; there are literally only two things that can be merged that would bring us closer to it, but they can only be merged in whole (or as being discusssed here, they may be merged in two parts, the intro vs the rest).

**Comment by comnom** [comment]
>To be fair, at least for me, the time since receiving collaborator access has been focused dealing with all these PRs that have been open for quite some time.

I get that. I really do. That wasn't the impetus for me calling out unfocused development. You know me. comnom isn't the guy that critiques your work. He's the guy that tells you to keep going. So understand that this is just what it seems. A guy who loves both sides of development. That doesn't change the fact that the project has been, and still is, unfocused. Which, in terms of backlogged PR's, isn't a bad thing. A lot of them needed more testing.



Real talk though, I think reffing 3120 and 3761 is disingenuous. They're monsters where no one seems to be content.

>....there are literally only two things that can be merged that would bring us closer to it...

Sorry to cherry pick, but you and I both know that there were far more people that wanted to contribute, but fell out of it due to poor direction.

>There’s clearly still a high level of scrutiny being put on PRs before they’re merged

I don't doubt that. I do doubt that it's the same level of scrutiny as before. I'm not the only one either.

But let's not devolve the thing into a development discussion. I said my piece (make this issue a case study in how to focus), and I appreciate the feedback.

**Comment by jafdy** [comment]
Expecting every merged PR to be error free is a fools errand, there have been typo fixes that I have delt with that have been in the game for anywhere between days and years. Although we are working at a higher pace and not with the same level of perfection we still can create good content that can then be improved over time. As MZ himself said, perfection is the enemy of good.

**Comment by comnom** [comment]
>  perfection is the enemy of good.

I see this thrown around often, so I'll just come right out and say it. A typo in a description or the like is fine. Syntactically incorrect content is not. It means that no one actually played it before merge.

https://github.com/endless-sky/endless-sky/commit/1d618b47695ad9bf2de9ffd7ea7f80da023c5770
https://github.com/endless-sky/endless-sky/commit/0c5fee0f347fbc209ed82a0437b52f2f95e21f82
https://github.com/endless-sky/endless-sky/commit/804cb9a914e46e0367f50be91247215ade04c40f
https://github.com/endless-sky/endless-sky/commit/13c505778bc0cd67bc54755bc2e0d7f18f826f28
https://github.com/endless-sky/endless-sky/commit/77a02559502775f0486b4d0074eb34b592fb171e
https://github.com/endless-sky/endless-sky/commit/162c646ac99dcf1e16ecf3715fa76172c684c196



@Zitchas Quickly merging content wont fix issues in reviews. Proper management, (ie, review guidelines) will. The review button in this project is broken. It's a "my opinion on this line is" button. That's entirely due to no direction on what constitutes a proper review on content.

I dream of a future where a review on code reads: I tested this code on WhateverOS. My test was X. Y occurred.

A mission review reads: I played through these missions in [ship]. X works fine. Y is broken due to [syntax].

This all plays into my suggestion above. Content does not need to be merged to be tested and built incrementally. We're on github. There's issues, projects, reviews, and branches. If kiko's work goes into a larger project it isn't lost. The next guy just pulls it into his copy and builds on it.

**Comment by Nescio0** [comment]
Exactly. A poorly choice of words in a text string or a typo in a description is not much of a problem, but syntax errors, misspelled fleet definitions, or improper formatting are. Ideally everyone proposing new content should offer it as a plug-in and include a zip in the opening post. And before any job or mission is committed, at least three different persons ought to have playtested and approved of it.

While more content can be nice, it is not really important. As for the lack of direction, what is really needed are code improvements, new features, and plug-in support. E.g.:
* allow defining a load order for plug-ins
* allow plug-ins to be selected, enabled, and deactivated
* add an in-game plug-in downloader
* de-hardcode user-facing text strings in the source code
* add unicode support
* add support for different writing directions (e.g. right-to-left instead of left-to-right)
* add support for selecting different languages and translations

**Comment by Zitchas** [comment]
@comnom I agree with that. Content should be played and tested. And stuff definitely shouldn't be merged quickly, especially on the code/mechanics side. I rather think it is a scale, though. On the one end is mechanics, where everything should be pretty close to perfect before merging. The other end is descriptive text. Which should be free of grammar and spelling mistakes and make sense, but should have a lot more leeway in terms of style and content.

A related problem, however, is that we want people to test and review this content. While admittedly having stuff merged shouldn't be a necessary prerequisite to it being tested, it basically is. There are a lot of people who would happily play test all the latest missions, but who either a) have trouble with or b) can't be bothered with, setting up an updating copy of the repo and regularly fetching the nightly build.

Personally, I'd suggest having three builds on Steam rather than two: The stable build, the unstable, and the beta. Leave the former two as they are, and have the third be effectively a user-friendly nightly build. And merge stuff to it fairly quickly (once it has passed the requisite "everything in this actually works and is good enough for us to think it worth including" stage). Then those people with an interest in testing and polishing could do so without needing to figure out repo cloning, library dls, and nightly downloading. (and yes, I know this would require MZ to do it, or additional permissions of some kind for one or more Dev, so not exactly something that that any of the new devs can do right now)

**Comment by KyroFirehammer** [comment]
I think adding them in would be fine to give a point to move forward with in the development of those storylines. With that being said, they probably should have a tenporary disclaimer attached that would let new players know that they are still WIPs

**Comment by Zitchas** [comment]
The entire Beta channel *should* have that disclaimer, but yeah. :)

**Comment by Fzzr** [comment]
@Amazinite:
>I specifically mentioned the intro missions because they wouldn’t have this issue. The player would be doing jobs for the Syndicate or the Navy, but simply never be given the chance to join in the same way that they are for the Free Worlds, therefore there’s no need for forced side switching or waiting around for more missions in the same way that people wait around for the Wanderer missions.

Now that I thought about it after a few days and reading the rest of the thread, I'm persuaded that this is worth it to show players outside Github that there really is significant progress happening in many parts of development, including content. Changed my votes here and on Discord. I like the idea of having a fourth-wall-breaking notice at the end of the intro content telling the user that this is just a preview, and directing them to the Free Worlds storyline.


@Nescio0:
> Exactly. A poorly choice of words in a text string or a typo in a description is not much of a problem, but syntax errors, misspelled fleet definitions, or improper formatting are. Ideally everyone proposing new content should offer it as a plug-in and include a zip in the opening post. And before any job or mission is committed, at least three different persons ought to have playtested and approved of it.

I apologize, since some of those have been from me.

**Comment by FixItYondu** [comment]
Are there still plans to add in the Navy and Syndicate intros?

**Comment by Amazinite** [comment]
I'm still 50/50 on it. I think that since the FW campaign is done, other main plot campaigns should be merged in full instead of in parts. But I'm more open to having stories be merged in parts if they're not the main plot, e.g. everything being worked on with the Remnant, #4800.
