### ISSUE TITLE
Ability to reliably transfer cargo between ships in fleet.

### ISSUE THREAD

**Issue by Joeppie** [endless-sky/endless-sky#4100]
As far as I can tell, It is not reliably possible to transfer cargo between vessels of your fleet.

For instance, if I am using my warship for mining iron, and my fleet has capacity to spare, I cannot properly get this transferred to another vessel in my fleet. This can help avoid making a landing necessary, which is an inefficient logistic operation that cuts into my profit margins.

What I can do is press [i] for ship info, then jettison a small amount of cargo, which can then be picked up by my other vessels. Sadly, however, this is not reliable, and there is a 50-50 chance your cargo is then lost to space, as you can no longer pick it up.

There are two possible options to resolve this, from my current understanding;

1. implement a button that lets you transfer cargo between fleet vessels, similar to drop cargo, but which then presents a panel to transfer the cargo to another vessel. (alternately, it could just try to cram as much of the cargo onto any other vessel and keep whatever flows over; this might be the most user-friendly implementation and save developer time)
2. somewhat less elegant; make jettisoned cargo not disappear as quickly, and reliably jettison in one direction, optionally making it possible to pick it up after a short duration by the vessel which dropped it.

A possible work around might be if it was possible to change flagships while in space; even if cargo was jettisoned in the most imbecilic manner, a skilled pilot would still be able to safely retrieve it from aboard another vessel. This gave me an idea: I will submit it as a feature request if no similar issues exist; escape pods for captains/crew (it might be fun if exploding ships jettisoned escape pods, yielding 'passengers' that would be okay with going to any (friendly?) port)

**Comment by Zitchas** [comment]
While option 1 would be good, I would really like to see 2 implemented anyway. I've always thought cargo disappears far too quickly.

**Comment by Bladewood** [comment]
Just fly directly over your escort and dump cargo there.

**Comment by Joeppie** [comment]
> Just fly directly over your escort and dump cargo there.

This is not a possibility; the cargo, when dumped, takes a random direction, and worse, if your escort misses it, it will likely disappear. Not even using [h] to order the fleet to  halt can stop that.

**Comment by tehhowch** [comment]
Unlikely. Improving the current system has been brought up before, and the inertia in changing it is that it is simply too easy to make money plundering if you can guarantee the use of your flagship and your fleet cargo space. If plundering has a different limit (cargo space is currently the only limit), a better transfer system is feasible.

Here's a related issue -- there may be others, and probably also some steam threads, too.
https://github.com/endless-sky/endless-sky/issues/2195

**Comment by DingusShingleton** [comment]
What if plundered cargo had a percentage chance of having contraband hidden in it and thus presented a risk of being scanned and fined? Could be pretty low, but enough that it would sting a bit once in a while if you were plundering your way across the galaxy.

**Comment by DingusShingleton** [comment]
Volume is a can of worms that may never be opened

**Comment by endless-sky** [comment]
If it were possible to reliably transfer cargo to your escorts in-flight, that would make outfit plundering way too lucrative - particularly in the story-line battles, where a player could just park a few freighters in the next system, call them in once the fighting was over, and steal everything that's not nailed down on the enemy ships.

**Comment by jostephd** [comment]
> If it were possible to reliably transfer cargo to your escorts in-flight, that would make outfit plundering way too lucrative - particularly in the story-line battles, where a player could just park a few freighters in the next system, call them in once the fighting was over, and steal everything that's not nailed down on the enemy ships.

What if pirate fleets were more likely to appear in systems that had disabled ships lying around? I don't doubt the larger pirate clans have sources of intelligence in systems close to their base. In fact, if there had just been a big storyline battle, I'd be surprised if there _weren't_ an outbreak of pirate activity in all the neighboring systems anyway, while all the FW/navy police ships are busy fighting, and even a strong contingent of pirates jumping into the battle's system after the battle is over to try and loot all the disabled capital ships and kill or kidnap their crews...

Secondly, looting disabled ships should have storyline consequences. In the navy campaign, looting disabled FW ships should get you court martialed; in the Syndicate campaign, looting disabled navy ships could gate some side quest that kicks you up the corporate ladder. (A captain who _doesn't_ loot disabled ships doesn't Get It, in the Syndicate.) In the FW campaign, I guess they'd be fine with you stripping navy hulls (that's exactly what the surveillance drone mission is about, after all) but not with you engaging in hand-to-hand combat to capture disabled navy ships?

Come to think of it, in the Battle of Kornephoros you could get an assignment, after the battle is over, to board disabled ships in order to capture their crews as prisoners of war, before their life support systems run out. (And Tomek would tell the player to kill the crew and report there had been no survivors...)

**Comment by samrocketman** [comment]
@Joeppie In pull request #6669 a fleet command for collecting flotsam has been added.  This issue will probably be resolved once it is merged.

**Comment by ThrawnCA** [comment]
> If it were possible to reliably transfer cargo to your escorts in-flight, that would make outfit plundering way too lucrative.

What if each attempt to plunder a critical outfit carried a risk of the crew deciding that they'd rather go out with a bang than wait to see whether they freeze before they starve, and rig their reactor to blow?

**Comment by Amazinite** [comment]
> somewhat less elegant; make jettisoned cargo not disappear as quickly, and reliably jettison in one direction, optionally making it possible to pick it up after a short duration by the vessel which dropped it.

We greatly increased the lifetime of flotsam back with #5689, and as @samrocketman has noted, you can now command your escorts to target ejected flotsam.

**Comment by mikeloeven** [comment]
@Amazinite I know this issue was closed but honestly this should be reopened since jettisoning and recollecting cargo is really a bad way to handle this we need a proper ui interface possible something in the pilot or ship info screen that lets you dock and directly move cargo between ships using an interface similar to trading where you select the type and qty of item to transfer and move it manually. Simply making floatsam last longer is still a bad way to transfer cargo esp since other ships can simply scoop it up if they get too close. The solution that marked this as complete seems less like a true implementation of the requested feature than a tweak to make a sub optimal workaround function a bit better. I posted here since I feel like it would be less productive to make another duplicate issue

**Comment by Hecter94** [comment]
Based on the [comment](https://github.com/endless-sky/endless-sky/issues/4100#issuecomment-450431487) from tehhowch on Dec 28, 2018

> Unlikely. Improving the current system has been brought up before, and the inertia in changing it is that it is simply too easy to make money plundering if you can guarantee the use of your flagship and your fleet cargo space. If plundering has a different limit (cargo space is currently the only limit), a better transfer system is feasible.

It seems like changing the system to make it any easier isn't something that we're looking to do as long as plundering remains in its current form. 

I'm curious what your reasoning is for wanting an easier way of transferring cargo. What are you hoping to accomplish by being able to move cargo between ships easily? 
Perhaps there's an underlying issue here that we could look at resolving.

**Comment by mikeloeven** [comment]
I dont see how this has anything to do with plundering More so than moving cargo between ships using an interface in pilot info maybe there is some exploit to plundering I am unaware of but primarially its to ensure mission cargo is not split between different ships in the fleet or having one mining ship be eaisly able to fill other cargo ships without risk of a random npc stealing ejected ore. If anything its a common sense issue more than anything since this is a basic function the average person discovering the game would expect to exist as cargo management is something every trading game has

**Comment by samrocketman** [comment]
At its core, fleet collecting floatsam is a mining mechanic rather than a cargo management mechanic.  It just so happened to pair okay-ish with this kind of issue but I agree it is not a complete solution.

I also don't think it makes much sense to reference tehhowch; as they no longer develop the project.  There are quality of life improvements that can be made in several areas.
