### ISSUE TITLE
Add per-ton summary of outfit stats to the tooltip shown for outfit mass

### ISSUE THREAD

**Issue by starcatter** [endless-sky/endless-sky#4106]
The idea is to provide a quick summary of how efficient a given outfit is in respect to its mass. 

While various other measures of efficiency may be relevant to some outfit types (eg. heat produced vs provided resource), trying to cover some or all such cases would result in a much more extensive and contentious change. All ships are ultimately limited by their outfit/weapon/engine space, making performance per ton a universally useful statistic. 

Placing this information in the mass tooltip keeps the feature from cluttering the UI, and is easy enough to remember.

![2018-12-29 22_00_44-window](https://user-images.githubusercontent.com/30572485/50605422-8d628880-0ec2-11e9-86eb-53b64de7ce8f.png)

![2018-12-29 22_07_00-window](https://user-images.githubusercontent.com/30572485/50605423-8d628880-0ec2-11e9-9884-ce7cdff86a81.png)

![2018-12-29 22_07_34-window](https://user-images.githubusercontent.com/30572485/50605427-8dfb1f00-0ec2-11e9-965b-0f661953524e.png)

![2018-12-29 22_08_30-window](https://user-images.githubusercontent.com/30572485/50605428-8dfb1f00-0ec2-11e9-9d87-6185272336fa.png)

I've been playing with this modification for a few months now and found it tremendously useful for quickly identifying strengths and weaknesses of various outfits.

**Comment by Zitchas** [comment]
I like it. It gives players a way to get more information without over-filling the main stat areas. It also means players can find and compare this info without using external sources.

**Comment by jafdy** [comment]
If you have this coded in already then can you create a Pull Request so we can review and consider merging this change.

**Comment by Amazinite** [comment]
>While various other measures of efficiency may be relevant to some outfit types (eg. heat produced vs provided resource), trying to cover some or all such cases would result in a much more extensive and contentious change.

For this reason, [insert stat here] per mass isn't always helpful. Why would I care that my System Core has 0.5 hull energy per ton or 0.7 hull heat per ton? It would be much more useful to know the relation of those stats to hull repair, but knowing them in relation to the mass isn't very helpful at all. 

Since this approach leads to just as much if not more useless info than it does helpful info, I don't see why it should be added to the game.

**Comment by jafdy** [comment]
It's not the ignoring useless stats that is the problem, it is the knowing what the useless stat is. New players already have a heck of a lot of numbers to contend with and I don't see adding more numbers will help with this.

**Comment by MessyMix** [comment]
Fantastic idea, but implementing it in a way that isn't gimmicky is the real issue.

**Comment by starcatter** [comment]
I went with my second idea in #4113

Since the extra tooltip content is generated and added all in one place, `OutfitInfoDisplay::getTooltipText()`, it could easily be disabled by some option, in case we want to keep all parts of the interface simple for new players. Then again, IIRC in order to keep the options screen simple for the newbies we're not adding any new options either...

**Comment by jostephd** [comment]
I'm guessing this was closed as it was superseded by / subsumed into #4215.

**Comment by Amazinite** [comment]
Not really. This one I closed moreso because I just don't like the idea of showing "x per y" values for arbitrary stats on all outfits, because as described, even in the case of just looking at "x per ton" for each attribute, that information isn't always helpful. So if you want to know the "x per y" of an outfit for any two attributes on it, I think you should be messing around in spreadsheets, not trying to add that information to the game.
