### ISSUE TITLE
Reloading save can cause the completion of mission in odd circumstances...

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4108]
**Describe the bug**
Reloading the last save can result in the unexpected completion for missions where
1. The source is the destination
2. The on offer conversation resulted in launching

**To Reproduce**
1. Get the missions from #3761 
2. Make first contact with the Remnant
3. Run to your ship and escape to refuse the blood test, causing you to launch
4. Refuse to take the blood test again, causing the Remnant to become hostile
5. Reload your save (which you may likely be forced to do at this point as the Remnant ships will tear you apart)
6. The mission completes and your reputation with the Remnant is now fine, as if you never refused the blood test in orbit

**Expected behavior**
Instead of the mission acting like it was already accepted and completing upon reloading the save, it is expected that reloading that save would result in the player immediately launching from the planet again and interacting with the `on enter` conversation.

**System (please complete the following information):**
 - OS: Windows 10 Home, Version 10.0.17134 Build 17134
 - Game Source: Self-compiled
 - Version: Most up to date as of this issue (https://github.com/endless-sky/endless-sky/commit/275795c005ce21cd9208dab4e5ebdf8566d4cc98)

**Comment by jafdy** [comment]
This is the mission being created before the save file but the conversation the force launches the player is skipped on reload (because the mission has already started according to the save file, because of the game not thinking it just created the mission (even though it would have done if the reload hadn't happened) allows it to complete. You could fix the unexpected completion by not allowing any mission to complete when a save is loaded but that would still have the unexpected not launch. Better would be for the game to remember it was supposed to launch with a line in the save somewhere.
If I am correct then this would suggest that any mission with the source as the destination and no other requirements could be completed this way.

**Comment by tehhowch** [comment]
I think this is an issue most easily addressed by mission logic. Most missions involve some sort of task (stopover, destroying npcs, etc) and these cannot be completed in advance by simply reloading the save. A mission which has no such tasks IMO needs fixing. The simplest fix would be to use a `to complete` node, e.g. (For that mission):

```
on enter
    conversation
        ...
        label accept
        apply
            set "remnant: received second chance"
        ...

to complete
    has "remnant: received second chance"
```
Note that missions already properly serialize the "you need to launch" status (e.g. Danforth & the "Bomb")

**Comment by Amazinite** [comment]
Perhaps that is a fix, but even though I know that
>missions already properly serialize the "you need to launch" status (e.g. Danforth & the "Bomb")

it isn't doing so in this case when one would expect it to.

**Comment by Amazinite** [comment]
@tehhowch Even with that addition, reloading the save still completes the mission despite refusing the second chance.
