### ISSUE TITLE
Lore friendly way to keep a few Pug ships spawning in the galaxy

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#411]
Basically, as far as I can tell, after the storyline is over, nothing remains of the Pug. Maybe like a single galaxy that they jump into infrequently, just some way of still getting pug ships/equipment after the storyline

**Comment by frameworld** [comment]
Agree.
You also don't know that before completing the mission which forces you to travel with a huge number of escorts which may kill a pug ship instead of disabling it.

**Comment by endless-sky** [comment]
Once the whole galaxy is populated, there could be other parts of the galaxy where they are also interfering, or perhaps even a way to travel to their home galaxy.

Or, maybe Pug ships should occasionally appear in the galaxy that you can get to through the Pug wormhole?

**Comment by brendanjones** [comment]
mmm yup, it was a bit disappointing that with my first pilot I whipped through the storyline and then the Pug were gone altogether. That pilot now has a stupid number of Bacs with all the possible Korath/Quarg outfits, but it'd be nice to be able to play around with fitting some Pug gear in there. With any new characters, I'l take the time to take out some Korath Raiders in Syndicate space and then use the jump drive to go over to Pug space and have some fun.

I like the idea of the Pug interfering in another part of the galaxy, or finding their actual planets (which should be insanely hard to capture - the ships you fight atm in the storyline are supposedly matched to human ships, as part of the Pugs' galactic game. But they'd surely defend their home worlds with everything they had, so that would mean ships/weapons better than the Quarg, right?)

In the mean time, maybe once the current storyline is complete, Pug could spawn at VERY rare rates in human space, simply labelled as a 'Watcher'. Keep them extremely rare, as a bit of an easter egg.

**Comment by Wrzlprnft** [comment]
Since they love to support the deep, as it seems, the would be somewhere there if they appear eastereggly, i guess

**Comment by guillochon** [comment]
I agree, they should continue to spawn at a rare rate throughout the galaxy.

**Comment by frameworld** [comment]
But it is still a bit hard to compare pug equipment.
Outfitting is a real pain if you have a limited amount of supply for a fleet of optimized ships.

There needs to be at least a ship that can carry outfits "unequipped" and dps/mass rather than just damage/second displays.
Also the cost of cooling and power supply should be shown in the outfits cost based on what cooling systems you install on a ship that size.

**Comment by endless-sky** [comment]
A new Pug system is added in commit 4c152fb, and eventually there will be further story involving them, too...

**Comment by thenerdfreak** [comment]
YAY new systems are always exciting

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
