### ISSUE TITLE
System Hazards

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4116]
Ref: #3729, https://github.com/endless-sky/endless-sky/pull/3729#issuecomment-439544894, #1553, https://github.com/endless-sky/endless-sky/issues/1552#issuecomment-246232974, http://prntscr.com/m4l25g

System hazards would be akin to the Korath nanobots, applying some sort of damage to ships within the system over time, only this would be applied to all ships equally instead of certain ships taking the brunt of the force and some ships taking no damage at all while the nanobots/any invisible ships are not attacking them.

Hazards would be able to apply any form and combination of damage to ships within the system. This damage could be constant, or it could fluctuate to give the effect of the hazard being like weather, where sometimes things are calm and sometimes they are rough.

Any hazard should ideally have some sort of visual effect within the system and/or to affected ships to convey to the player that the hazard is present. If hazards are able to fluctuate like weather, this effect should change to reflect the severity of the hazard at that time.

**Comment by Pointedstick** [comment]
Even non-destructive hazards like haze would be great. EV Nova had that and it always added a really spooky atmosphere to certain systems.

**Comment by Zitchas** [comment]
Does that haze apply overtop of ships, or just over the background? Also, does it increase over distance?

**Comment by Amazinite** [comment]
Haze right now is just the blue gas (or red gas for the Ember Waste) that you see in the background.

**Comment by Pointedstick** [comment]
Right, I'm thinking about about EVN-style haze that actually obscures things rather than just being visual differentiation for different areas of space.

**Comment by Zitchas** [comment]
I'm not the one writing code, but from my point view the ideal would be having seven attributes that could be assigned to a system:

1) Damage type: (shield, hull, heat, ionization, slow... basically everything that we have)

2) Frequency of hit: none, continuous, or a hit every so many frames.

3) Damage amount: how much damage per "hit" (or damage per frame if frequency is set to continuous)

4) Haze intensity (and this would be haze over top of ships) how much it obscures

5) View distance (how far one can see in through it. Basically, creating a "fade out" distance

6) Tracking interference type(s)

7) Tracking interference intensity.

All that being said, the first three are the original "system hazards" idea, the remainder are things that we could use to make systems much more interesting and varied.

**Comment by Zitchas** [comment]
Yes, exactly! There were a number of systems that had a "fog of war" effect with varying levels of obscurity. Some of them one could only see another ship up to about halfway to the edge of the screen (and that game couldn't even zoom out, either)

**Comment by jafdy** [comment]
Frequency of hit needs a random element so you don't get a lightning bolt every exactly 3.5 seconds.

**Comment by tehhowch** [comment]
Whatever timer class controls the proc rate could inherit familiar distribution specifications (e.g. mission cargo and passengers). What is more useful is
1) artwork that would use this feature
2) thoughts on how system-wide (fog-of-war) vs localized hazards (ion discharge / CME) could be specified, or if they should instead be tiled like asteroids
3) syntax for the interface

Following the discussion shown in the screenshot I did an iota of planning here: https://github.com/tehhowch/endless-sky/commits/system-hazards but have obviously not developed it further. Better to define the interface and utility before jumping into excessive (wasted) detail.

**Comment by Ferociousfeind** [comment]
If I may add my two cents, the system I'd imagine would work visually similarly to current "fleet" values, ergo something like:

`fleet "Korath Nanobots" 400`
`hazard "Electromagnetic Storm" 6000`

The frequency for hazards would be identical to the frequency for fleets. That is, 400 is very frequent, 400,000 is very, very infrequent.
Somewhere else in the game, the "hazard" would be defined, as something like:

`hazard "Electromagnetic Storm`
`"lifetime" 600`
`"random lifetime" 60`
`weapon`
`"reload" 10`
`"random reload" 20`
`"shield damage" 3`
`"hull damage" .4`
`"ion damage" 4`
(I'm not sure how to make indentations, so you'll have to imagine proper indentation instead, sorry.)

In any case, `lifetime` and `random lifetime` would tell the hazard how many frames it persists, while `reload` and `random reload` tell the hazard how often to inflict its effect. I don't know how visual hazards like fog would be implemented, I would leave that up to someone else if they wanted to do that.
(I also don't know how much ion is too much ion.)

This effect could also be per-ship, as in hazards are attached to the singular ship it is affecting, so that lightning bolts wouldn't hit every ship in a system in a pulsating manner every 210 frames.
(Of course, if you wanted relatively global lightning bolts, you could still use a fleet, with a weapon of a large blast radius.)

I, of course, have no idea how I would even go about creating the functionality for hazards in this way, so someone else would definitely have to do the major heavy lifting first.

**Comment by comnom** [comment]
Im with @Ferociousfeind on syntax, that looks reasonable enough. Implementation wise it may be simplest to just spawn hazards as projectiles with a blast radius. So they'd spawn periodically using the same sort of randomized distrubution that haze does but you'd still have to physically hit the projectile. (which allows manual dodging and such).

As for fog of war, im meh. I wouldn't really be a fan if half my enemies disappeared. (especially missile boats)

**Comment by NomadicVolcano** [comment]
I suspect the easiest way to implement this would be to have some special personalities for ships, and use fleets to implement scenery:

* untargetable = nobody can target the ship
* above = ship is drawn above all other sprites
* scary = enemies of this ship will try to avoid flying within its weapon range
* "random movement" = ships moves in random directions
* "cyclonic movement" = ships moves approximately in a circle around the center of the fleet
* "orbital movement" = ships orbit the center of the system
* "random targeting" = ship chooses targets at random

Scenery would be fleets with "untargetable staying above scary," and some target or movement personality, in a government that is hostile to everyone. (Possibly you would exclude the Drak, Author, and Parrot governments.) Everyone would have to be hostile to the scenery too, otherwise it could land on planets or go through wormholes.

If it is implemented that way, you can spawn scenery the same way you spawn fleets now. You can even have scenery NPCs. "Planet X in system Y is caught in an ion storm and urgently needs medical supplies."

**Comment by NomadicVolcano** [comment]
On second thought, the "scary" and "above" personalities are probably not necessary. I suspect it is enough to implement alternative movement and targeting options, and make the fleet untargetable.

**Comment by Amazinite** [comment]
That seems like a very hacky solution akin to the approach taken for mineable asteroids in #992. 
Could we get something like what is desired using existing mechanics? Perhaps. Would it be far better to just implement source code changes instead as to allow for better results? Yes.

**Comment by Zitchas** [comment]
As a content creator, I can see a lot of fun possibilities with the addition of those personalities. That being said, implementing them will take game engine changes just as surely as the kind that FerociousFiend proposed, and I feel that FF's proposal serves the purposes of system hazards better.

**Comment by NomadicVolcano** [comment]
His solution can be implemented as a wrapper around what I proposed. In the game engine, the hazards would be handled as ships with odd personalities. There would be a Hazard subclass of Fleet that converts your "hazard" blocks internally into ships with the necessary personalities. That Hazard subclass is what would be read in from the missions.

The effect would be precisely the same from the point of view of content creators, but the code changes would be much simpler. It does add the extra step of having to make a "Hazard" subclass though. That might be on the order of a thousand lines due to the overcomplicated way in which mission text is implemented, but it will be mundane code that is easy to debug.

For the damage done by the hazards, you are better off using outfits. Call them something else if you want, but the outfit implementation is powerful and well-tested.

**Comment by Zitchas** [comment]
While that does have some potential, and graphics are usually nice to have, they aren't really necessary.

Being able to simply have the code that FerociousFiend suggested attached to a system definition, and thus have ships randomly start taking damage while they remain in the system, is more than good enough for me.

As far as that goes, I'd actually like something even simpler:

```
hazard "Electromagnetic Storm"
  weapon
    "reload" 10
    "random reload" 20
    "shield damage" 3
    "hull damage" .4
    "ion damage" 4
```
Specifically, a constant damage effect that applies its effect on a regular basis based on the reload and random reload timers. Basically uses identical parameters as weapons, except without lifetime, velocity, and inaccuracy. No graphics needed, no fake "ships" needed, and very straight forward to understand. Also no need for the game do all the workload for tracking a bunch of fake ships and weapons and stuff. 

It could be expanded later as needed; but this right here is what I need for my purposes. (and, of course, being accessible to events so they can be changed. But I think that is to be expected by being part of the system definition)

**Comment by NomadicVolcano** [comment]
If there are no graphics, the player has no visual indication that anything is wrong. Also, we can already do what you suggest. You just need fleets of black-spite ships that move quickly and have effectively infinite repair.

The point of this ticket, in my opinion, is to add something more substantive.

**Comment by Zitchas** [comment]
Yes. The point of this ticket is to add a substantive mechanic. There are frequent issues with the timer ship because it acts wonky in all sorts of circumstances. I don't want that.

Besides which, the player *will* have indicators: Their heat meter rising, ionization graphical effects, etc. For my purposes (in the Ember Waste) the whole area glows red, which *should* be a warning sign for most people.

**Comment by NomadicVolcano** [comment]
Receiving damage for no obvious reason would be extremely confusing.

**Comment by NomadicVolcano** [comment]
To put it more succinctly: a proper implementation of hazards would be worth the extra effort.

**Comment by Zitchas** [comment]
For a lot of the hazards I envision, the most I'd want in terms of a visual effect is a small pulsing "danger" icon in the GUI somewhere. Which, admitedly, would be a really good idea to have.

I'm not fond of the idea of having an animated electro-storm floating around. That sort of thing is really hard to get looking good, I'd imagine. And gimicky.

If someone wants to implement that too, sure, but What I described above is the sort of implementation I'm hoping for.

Radiation doesn't have a visible effect to show people they are being irradiated. Heat doesn't really either. For that matter, neither does electricity or ionization. They all show some effect when applied in large amounts to other substances, but just floating along in space? Nope.

**Comment by NomadicVolcano** [comment]
What you describe is a proper subset of what I describe. It can be implemented as a first step with the "full solution" coming later.

Many games have visible hazards you have to dodge. They're able to make it look good and incorporate it well. I'm sure we can do the same.

One way to handle the hazard warning is a "critical message" log separate from the scrolling console to the lower-left. When a "critical message" is available, an angry-looking button appears to the lower-right. Press it and a window pops up with log messages.

**Comment by Zitchas** [comment]
Sure, and I think we actually agree on this. I'd like the part that I want to use now implemented as soon as someone can make that part work, and if someone wants to continue on to make the full thing with flying clouds of danger later on, then that's great too. 

As far as that goes, a plug-in for EVN actually implemented your suggestion. It had "ships" that were hazards, with "weapons" that had various effects. And it was initially really cool. But then all the hazards started chasing you down, and that.... lost its coolness really quickly. Because having an ion storm (or meteor cluster, or whatever) chase me down from across the system just doesn't make sense.

Another plug-in got around that by giving all the hazard spaceships thrust and speed, but no turning. (or conversely, gave them turning with no thrust). That way, none of the hazards could chase anything down, and just went careening around the system and off into the great beyond. Or sat there spinning around, but not moving. This looked a little better, but usually ended up causing the game to run into its limit of "numbers of ships per system".

So part of the larger process will be making an actual "random AI" that is hostile to the player, but also ignores them and just flies around randomly and just happens to take opportunistic shots at them whenever they are in range.
