### ISSUE TITLE
Crew salary non-payment message overlaps system entry message when at zero credits

### ISSUE THREAD

**Issue by Fzzr** [endless-sky/endless-sky#4132]
When the player has zero credits and owes crew salaries, the alert about that overlaps the message for entering a new system.

**To Reproduce**
1. Hire crew
2. Reduce credits to 0 (doing it due to running out of money in space works)
3. Launch from a planet or jump to another system
4. Observe alert area at bottom of the screen - the messages for being unable to pay salary and for entering a system on X day stack on top of each other. This persists as other messages are added.

**Expected behavior**
Alert messages should not overlap.

**Screenshots**
Stacked messages as they first appear:
<img width="389" alt="screen shot 2019-01-20 at 12 15 56 am" src="https://user-images.githubusercontent.com/1037883/51436804-f4b16400-1c48-11e9-8bae-2089820abc7e.png">
Stacked messages as they fade out:
<img width="764" alt="screen shot 2019-01-20 at 12 18 06 am" src="https://user-images.githubusercontent.com/1037883/51436805-f67b2780-1c48-11e9-9dc0-e0c6a6072ea2.png">

**System**
 - OS: macOS Mojave 10.14.2
 - Game Source: Self-compiled
 - Version: commit hash 9eed145c

**Link to save file**
Save File: https://pastebin.com/QcKpt1yN

**Comment by Fzzr** [comment]
Update: I've figured out that this happens when the message has a trailing space. Investigating further.

**Comment by Fzzr** [comment]
Additional update: This appears to be caused by WrappedText lacking a case to check if a newline is needed when a space character is also the end of a line. https://github.com/endless-sky/endless-sky/blob/master/source/WrappedText.cpp#L261-L262

Thanks to @sbweber for debugging assistance.

**Comment by sbweber** [comment]
Hello, I'm here with some details.

There are three situations that could be the final text printed in wrapped text
1) Non-whitespace text, aka a word. In this situation, `hasWord` is `true` and the code goes through the `if` block at https://github.com/endless-sky/endless-sky/blob/master/source/WrappedText.cpp#L271-L290 , ultimately advancing vertically `lineHeight + paragraphBreak` on line 286 after printing the final word.
2) Newline. In this situation, height is again advanced vertically by `lineHeight + paragraphBreak` on line 254, as is always done when a newline is encountered. Since it's not on a word, the hasWord block is skipped.
3) Whitespace that isn't a newline. In this situation, the newline-specific code is not called, and the handle the final word block is not called.

The bug is caused by situation 3. Two ways to address this immediately come to mind.
1) Move the 'advance one line vertically plus a paragraph break' logic on line 286 outside of the final word if block, so that it always happens at the end of wrapping text (say, putting it right before line 294). This is probably not desired behavior -- while I was doing this writeup, @Fzzr found https://github.com/endless-sky/endless-sky/blob/master/source/Conversation.cpp#L122 where what appears to be intended behavior depends on a newline not being visually inserted at the end of all text.
2) specifically address the edge case of 'trailing non-newline whitespace at end of wrapped text'. Maybe an else block off the handle final word block where it adds the `lineHeight + paragraphBreak` if the final character isn't a `'\n'`?

**Comment by Fzzr** [comment]
Additional note: This does not occur in #4123. If option 1 above turns out to be too high-impact, it may be better to go with the less-intrusive option 2 and leave a permanent fix to 4123 or another font-rendering refactor.

**Comment by tehhowch** [comment]
A temporary fix is to fix the relevant strings in `Account::Step`:
![image](https://user-images.githubusercontent.com/20871346/51782297-c077f080-20eb-11e9-9e10-94fd5109cd05.png)
