### ISSUE TITLE
Concerns over the changes to missiles from v0.9.8 to now

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4149]
Just an issue to discuss the balance changes made to missiles. I think we're in a far better place now than we were before, but there are some issues with the new balance system that need ironed out.

Ref: #3866 (missiles buffed), #3922 (missiles made more numerous), #3845 (buffed Javelin fire rate), #4162 (reduced frequency of missile usage in pirate fleets and made small tweaks to various missiles)
#4077 (similar issue)
<hr/>

<details><summary>Initial concerns</summary>
List of concerns:

* Missiles are now too numerous.
   * The solution to this may be to simply revert many of the changes done in #3922. (Not revert it fully, though.)
* Missiles are now too powerful.
   * #3866 gave missiles a roughly 20% DPS buff. Perhaps lower this to a 10% buff, of even down to 0% (slight changes only being due to wanting round numbers).
* Look at usage of Sidewinders vs effectiveness/cost of jamming.
   * Sidewinder missiles are very difficult for small ships without jamming to dodge. That's exactly the kind of ship a player flies early game. Either revert to pirates only having meteor missiles, or look at the effectiveness and/or cost of jamming such that it's easier to use early game.
* Heavy rockets are now too powerful in terms of single shot damage. Early game, interceptor-sized ships are too easily disabled or outright destroyed. 
   * Solutions that I can think of would be to either keep the DPS similar by reducuing the single shot damage while increasing the fire rate such that a player is able to survive a single shot, or reduce the trigger radius of heavy rockets to make them more precision weapons when fighting smaller ships, but still be very capable of attacking larger ships.
* Look at Javelin balance.
   * Not something I've looked into since the changes, but I've received reports that the Javelin may be a bit too powerful now.
</details>
<hr/>
Concerns post-#4162:

* Look at Javelin balance
  * Are Javelins too weak? Do they need a further DPS buff above 33% but below the 68% that they had?
  * Or do Meteors and Sidewinders need to be brought down to "make room" for the Javelin as a viable weapon?
* Are missiles in general, or at least just the small ones, too strong?
  * Strong missiles allow smaller ships to compete against larger ships, but is it too much? Should the smaller missiles (Javelin, Meteor, Sidewinder) be able to directly compete with the three P cannons (Particle, Proton, Plasma), or should they be just under them?

Reference any other issues below that have changes missile balance that I've missed, and add your own concerns as well.

**Comment by Pointedstick** [comment]
In general, I think game mechanics are more fun when they're bold but have hard counters than when they're wishy-washy and indistinct.

From my perspective the game feels pretty good now vis-a-vis missiles. In particular, the fact that heavy missiles like rockets and torpedoes are so powerful in terms of single-shot damage has been pretty crucial to my ability to enjoy using them. Before, they just felt too weak. The fact that a salvo of two heavy rockets will destroy most interceptors seems to me like a feature, not a bug. Reducing the triggering radius could work, but I wouldn't like to see the per-missile damage reduced.

I would agree with you that jamming being mostly worthless makes Sidewinders slightly too powerful. But I think that's something that should be addressed by improving jamming, not by reducing the utility of Sidewinders. I could probably accept a slight reduction in ships' missile armament too.

The biggest issue I see with the current state of affairs is that Meteor missiles have no ideal target: they lack the maneuverability to hit small fast ships (by design, because we wanted to make it easier for new pilots to evade Pirates' missiles), but they're too easily destroyed by anti-missile fire to be very useful against warships or even most freighters. They are a jack-of-no-trades missile.

**Comment by Pointedstick** [comment]
Sounds sane to me. I could get behind reducing the frequency of heavy rocket armament among southern ships. Just reducing the number of launchers from 2 to 1 on a few of those interceptors could help, or reducing the spawn frequency of the dual-rocket-armed interceptors.

I'm also in favor of making jamming a realistic alternative to anti-missile turrets. This was one of the reasons why I proposed IR jamming too in https://github.com/endless-sky/endless-sky/issues/3323.

The thing about Javelins is that since they're missiles, a ship armed with even one anti-missile turret is pretty safe from a ship armed exclusively with them. One HAMT = Javelins do practically no damage. But I can see how it's a problem for ships with no anti-missile turrets. But then again, isn't this to be expected? I do understand that it's important that low-skill starting players not get frustrated and give up, but they'll pretty quickly turn into medium skill non-starting players and will learn strategies for dealing with those challenges. I think that's one of the things that makes the game fun.

**Comment by Nescio0** [comment]
There's nothing wrong with javelins; if anything, they're still quite useless now most ships have anti-missile turrets. A javelin pod (size 12) could theoretically inflict slightly more damage than the meteor launcher (size 10), but it has no homing and significantly less range:
![screenshot from 2019-01-28 19-58-07](https://user-images.githubusercontent.com/21634324/51859520-9b77bd80-2337-11e9-8354-12350767ed83.png)

**Comment by Amazinite** [comment]
We can't just balance missiles under the assumption that the opponent will always have anti-missile turrets, though. The complaints I've gotten in relation the the javelin and heavy rocket (and missiles in general now) have been that they can make it painful early game, at which point the player has no or little AM to defend against such weapons.

**Comment by Amazinite** [comment]
I'd rather things be too weak than too strong, as things too weak can be slightly buffed over time until the sweet spot is found while things too strong break the game and warrant being nerfed too hard. Do note that feedback so far has only been from the small population of people who are both on the Discord and play up-to-date versions of the game. I think it'd be safe to reign missiles in now with that feedback before the changes hit a wider audience, and then we can make tweaks from there.

Suggested changes at this time:

Weapon | Shield Damage | Hull Damage | Other changes/notes
---------|----------------|-----------|-------
Javelin Pod | 57 -> 48 | 36 -> 28 | This change fully reverts the damage buff that Javelins got, which was roughly +26%. That stacked on top of the +33% fire rate was far too much. <br/>The 68% DPS buff since v0.9.8 becomes 33%
Meteor Missile | 260 -> 240 | 160 -> 145 | The 20% DPS buff from #3866 becomes 10%
Sidewinder Missile | 180 -> 165 | 125 -> 115 | The 20% DPS buff from #3866 becomes 10%
Heavy Rocket | N/A | N/A | The changes to the Heavy Rocket haven't change its DPS, so I'm tempted to say completely revert them for the sake of not having the Heavy Rocket be too obnoxious, although I do love the true heavy hitter that it feels like it's become. <br/>For now, I'd say nerf the trigger radius from 30 to 20 or even 15 and see where that gets us.

Feedback on torpedoes has been good, or at the very least not negative in that they're too powerful. Other changes to missiles, such as changes to turn radii and velocities, seem fine. Damage and frequency is mainly what I'm getting negative feedback on.

**Comment by Amazinite** [comment]
And looking at jamming as well.

Outfit | Cost | Weight | Cost/ton
-----|-----|-----|-----
Small Jammer | 70k | 4 | 17,500
Large Jammer | 490k | 14 | 35,000
Small AM | 60k | 16 | 3,750
Heavy AM | 150k | 30 | 5,000

I'd say that keeping the AM turrets at the same cost, the small jammer should be 24k and the large jammer should be 138k (just picking numbers out of the air, really). Jammers are a more limited form of missile defense that shouldn't cost so much considerably more than AM turrets.

**Comment by Pointedstick** [comment]
Tweaking the cost/ton of jamming is pretty pointless as long as the mechanic itself has little effect due to https://github.com/endless-sky/endless-sky/issues/3912 and the lack of https://github.com/endless-sky/endless-sky/issues/1865.

Your suggestions for Javelins make sense, especially in light of the fact that they got a 68% DPS buff, which is huge. I like the idea of making them faster to help against AM fire too.

But I don't think the proposed DPS reduction for Meteors and Sidewinders makes sense in the same way. Going from +20% DPS down to +10% seems insignificant. Will this really move the needle? Is the current DPS really the cause of any problems? I'm not sure it is, especially for Meteors, which the AI is now pretty bad at using properly. It's almost trivial to dodge Meteors in a small ship, even for relatively skill-less players.

Reducing the Heavy Rocket's trigger radius to 20 seems reasonable enough.

**Comment by Amazinite** [comment]
>Tweaking the cost/ton of jamming is pretty pointless as long as the mechanic itself has little effect due to #3912 and the lack of #1865.

I think whether jamming works or not is less important than the fact that jamming outfits are so expensive, especially when compared to their only alternative, AM turrets. Like come on, the large jammer right now is more expensive than any of the starter ships!

>But I don't think the proposed DPS reduction for Meteors and Sidewinders makes sense in the same way. Going from +20% DPS down to +10% seems insignificant. Will this really move the needle? Is the current DPS really the cause of any problems? I'm not sure it is, especially for Meteors, which the AI is now pretty bad at using properly. It's almost trivial to dodge Meteors in a small ship, even for relatively skill-less players.

Like I said, the feedback I'm getting includes that missiles have become too powerful with their +20% damage buff. There's general agreement that before all this in v0.9.8 and prior, human missiles were essentially worthless, so dropping back down to a 0% buff seems like we'd just be back at square one, so going to +10% seems like the reasonable middle ground to see how things turn out. Like I said before though, it could be that the frequency of missiles needs changed. Players may be able to dodge missiles from a single ship, but when more ships have missiles, it may be becoming difficult if not impossible to dodge the missiles from various ships at once.

**Comment by Pointedstick** [comment]
> I think whether jamming works or not is less important than the fact that jamming outfits are so expensive, especially when compared to their only alternative, AM turrets. Like come on, the large jammer right now is more expensive than any of the starter ships!

The problem with radar jammers is not really their cost or size (though those are a part of it). It's that the service their provide is nearly worthless, so the only way a rational player would buy one is when the cost and size are negligible. Solve the usefulness issue and you solve the cost and size issues automatically.

> Like I said, the feedback I'm getting includes that missiles have become too powerful with their +20% damage buff. There's general agreement that before all this in v0.9.8 and prior, human missiles were essentially worthless, so dropping back down to a 0% buff seems like we'd just be back at square one, so going to +10% seems like the reasonable middle ground to see how things turn out. (Although given how the heavy rocket feels better even without a DPS change, it wouldn't be unreasonable to assume that a +0% DPS buff with only the fire rate and damage per shot changes may be all we've needed.)
>
> Like I said before though, it could be that the frequency of missiles needs changed. Players may be able to dodge missiles from a single ship, but when more ships have missiles, it may be becoming difficult if not impossible to dodge the missiles from various ships at once, especially when #3922 gave ships both missiles and normal guns to force them to get up close where the player has less time to dodge. I'm just looking at weapon stats right now because it's easier to compare and suggest changes for than changing fleets.

There's a lot of daylight between "essentially worthless" and "too powerful". I want to make sure we're adequately  quantifying the problem space first. Is it the DPS boost? Is it the frequency? Is it something else? I think you're onto something about the frequency, but this is important because if it's the frequency, then if we solve that issue, we won't need to change the damage, or if we do, we can do it in conjunction with rate-of-fire reductions to hold DPS constant.

**Comment by Amazinite** [comment]
>Solve the usefulness issue and you solve the cost and size issues automatically.

Not really, because jamming is still only an alternative to AM turrets that only works against a limited number of missiles (only Sidewinders in human space), so the effectiveness of jamming would need to be at godly levels, say preventing being hit by a vast majority of Sidewinders no matter how many there are, in order to be a viable alternative with its current cost.

>I want to make sure we're adequately quantifying the problem space first. Is it the DPS boost? Is it the frequency?

I don't know, because the people giving me these concerns aren't the ones arguing here right now. I think the frequency boost is more the problem than the DPS boost though.

>we won't need to change the damage, or if we do, we can do it in conjunction with rate-of-fire reductions to hold DPS constant.

I wouldn't touch the rate of fire at all. One of the side effects of reducing the rate of fire on missiles is that players now need to rearm less, and the need to rearm secondary weapons was one of the major gripes with them before.

**Comment by Pointedstick** [comment]
What I'm proposing is further //reducing// the rare of fire while holding DPS constant (by increasing damage a commensurately), which would further reduce the need to re-arm while making missiles less numerous.

**Comment by Amazinite** [comment]
Well doing that same thing on the heavy rocket is what caused concerns with it. If you reduce the rate of fire and increase the DPS too much, you end up with a scenario where *all* missiles must be dodged, as otherwise you take unsustainable amounts of damage.

**Comment by Amazinite** [comment]
Fleet | Chance of any single spawn containing a ship with missiles
-----|-----
Small Southern Pirate | 89.80%
Large South | 59.38%
Small Core | 43.24%
Large Core  |51.02%
Small North | 72.97%
Large North | 77.97%

**Comment by Amazinite** [comment]
At a glance, a large portion of the missiles used in small southern fleets are heavy rockets.
I spoke with some people on the Discord about the current numbers, and we think it'd be sensible to aim for having fleets only have missiles at most roughly 50% of the time. It doesn't necessarily need to be 50% exactly; the rate could differ between small and large fleets and between regions however we see fit, as long as the numbers aren't as high as now.

**Comment by Amazinite** [comment]
Any changes to the % of missiles line (chance of any spawn containing missiles) were me catching errors in my counting. I think I only had to change the southern fleets slightly.

Fleet | Small South | Large South | Small Core | Large Core | Small North | Large North
-- | -- | -- | -- | -- | -- | --
% of missiles | 87.76% | 60.94% | 43.24% | 51.02% | 72.97% | 77.97%
Meteor | 67.35% | 39.06% | 24.32% | 32.65% | 35.14% | 59.32%
Sidewinder | 0.00% | 0.00% | 0.00% | 0.00% | 13.51% | 16.95%
Javelin | 14.29% | 10.94% | 8.11% | 6.12% | 21.62% | 22.03%
Heavy | 32.65% | 31.25% | 13.51% | 20.41% | 18.92% | 8.47%
Torpedo | 0.00% | 15.63% | 0.00% | 16.33% | 5.41% | 30.51%

**Comment by Nescio0** [comment]
#3922 probably changed too many things at once and might have been merged prematurely; reverting parts of it might improve the situation.
How about removing missiles from fighters and interceptors, to make the game easier for starting players? (Gatlings are fine)

**Comment by Amazinite** [comment]
The standard Hawk definitely needs its heavy rocket removed.
The standard Sparrow could have its meteor missile removed; we don't necessarily need to force Sparrow start players into using missiles. Perhaps just have James mentions something about possibly swapping out lasers for missiles to improve your odds in battle.
The standard Fury could have its meteor missiles removed, as it already has three variants that also use missiles.
The Wasp seems fine, as it's in the Core where missile usage is already the lowest.
The Beserker seems fine, as it comes with Javelins that don't seem to be as much of a problem as say heavy rockets or the heavy meteor spam, or at least shouldn't be after the suggested tweaks.
I'd be all for removing missiles from fighters. I was iffy on it in the first place, and it is important to note that the numbers I've posted don't include any changes to the pirate fleets, which means we need to think about the fact that pirate fleets end up gaining Roosts and Nests with squadrons of missile fighters.

**Comment by Zitchas** [comment]
I think wholesale removal of missiles from fighters and interceptors would be going much too far. 

From my perspective, fighters ought to have mostly dumb fire (or poor guidance) missiles, just a low number of them.

I don't know the numbers, but will a single starbarge attract pirate fleets? That might be worth bumping up a bit. I don't think regular pirates knocking out a starter ship is a problem, but it might be a tad cruel to have them actually attracting them.

**Comment by Amazinite** [comment]
Raid fleets are something completely different, and a single star barge will never attract a raid fleet.

**Comment by Nescio0** [comment]
How about the following?
* default interceptors use only blasters or lasers
* variant interceptors don't use torpedoes, but can have all other secondary weapons
* default fighters use only blasters or lasers
* pirate variant fighters use gatlings

**Comment by Pointedstick** [comment]
Very much -1 on removing missiles from fighter-sized ships' default armaments. Missiles (or Gatling guns) are basically the only weapons that makes them even remotely effective and worthwhile in the numbers with with they're typically fielded and encountered in the game. There may be something to the idea of using mostly dumb-fire missiles instead of guided missiles though. E.g the Sparrow could have a Javelin Pod instead of a Meteor Missile Launcher.

**Comment by Zitchas** [comment]
All this makes me wish we had disabling weapons. Pirates by their very nature should be avoiding mass missile spam since they want to loot ships, not blow them out of the sky (unless they are navy). But at the same time, it makes sense to have them use the most effective weapons that they can be reasonably assumed to be able to afford and access.

Having weapons in general (and some kind of missile in particular, say, a "Marauder Meteor" or something that had its targeting tweaked to specifically tweaked to hit vulnerable control system with a payload that includes damaging energy discharges) would fit the bill. In practice, it would have identical stats to the Meteor (or whatever missile is deemed a suitable base), but it has a "Disable" flag similar to what EVN had. 

In EVN, weapons with the disable flag functioned as per normal until a ship was actually disabled. Once a ship shutdown, disable weapons only dealt 10% of their normal damage. The lore was that something in the nature of the damage or payload of the weapon was just as effective as normal against shields and hull, but was focusing its damage somehow (perhaps due to it including part of its payload that specifically target control systems), so once a ship is disabled, hitting those critical systems was far less effective.

Such a weapon has some trade-offs. On the one hand, it gives the pirates more chances to loot. And the player too. It also would mean that big disabled ships (like cruisers and stuff with high hull) are going to be a much bigger obstacle in combat since they could absorb 10x as much damage from disabling weapons as normal, which puts pirates in an odd position of being good at looting but poor at taking on millitaries, since they'd have trouble finishing the kill in any battle that they don't completely win. (basically, raids where they just take out one or two ships before running away would have lower chances of actually killing things). So some pirates would love these things, others would avoid them, but probably skewed towards the former.

This would also mean that player ships would end up as disabled by pirates more, and destroyed by pirates less. If the pirate AI was tweaked so that it would NOT destroy a ship after looting, along with a "on boarded" mission starting condition that triggers when someone boards the player instead, it could actually turn a negative event into a gateway to missions and more interesting RP experience. It could also serve as the basis for making the boarding defence and security stations more meaningful.

(Imagine being boarded by pirates and captured, and the captain gives you the choice to jump out the airlock or join his fleet. Joining would reset the player's rep with pirates, and start a mission sequence where they'd get the chance to either work their way up a pirate organization, or figure out how to get out from under their control. Sounds like fun to me.)

That's starting to go off topic, but the point is that having a disable attribute would have immediate applications for allowing pirate fighters/interceptors in particular to be equipped more realistically and dangerously (as per PointedStick's comments), while decreasing the incidence of player death. It also means that the penalty for failing to defeat some pirates becomes an in-game "lose some of your stuff as they take your cargo and maybe some stuff" instead of an immersion breaking "go reload."

**Comment by ChamEV** [comment]
I very much believe there are too many missiles in general floating around.  Another possibility is to reduce the capacity of missile launchers in most cases, sidewinder and meteor missile capacities down to 4 and 6 per launcher.  Bigger ships can buy racks with autoloaders to store more.  But fighters should have access to these types of armaments, each one ready to fire, but no loading mechanism for more as the rack outfit is too big for them.

This lets the player experience them in smaller numbers too when they run up against a fighter with them, they get used, then they run out.

> In EVN, weapons with the disable flag functioned as per normal until a ship was actually disabled. Once a ship shutdown, disable weapons only dealt 10% of their normal damage.

Ships already stop firing at targets when they're disabled.  It's usually the shots already in transit that kill a ship instead of disabling it.  Perhaps when a shot would disable a ship, all damage past that threshold is reduced by 50% for 1-2 seconds.  Example: a heavy rocket does 720 hull damage, first 400 disables the ship, remaining 320 is halved to 160.  Rationale could be as you suggested, shots at already destroyed control systems/engines.  Making it too easy for the player to plunder later in the game can be addressed by small chances of tripping a self destruct on any vehicle or with the rumored boarding overhaul.

**Comment by Amazinite** [comment]
Closing this issue because it seems that missiles are largely in a good place now. Will look into reducing their frequency for v0.9.11, though.
![image](https://user-images.githubusercontent.com/17688683/60059351-38a60a80-96ba-11e9-9bbe-c379e03a6258.png)

**Comment by Pointedstick** [comment]
> Another possibility is to reduce the capacity of missile launchers in most cases, sidewinder and meteor missile capacities down to 4 and 6 per launcher. Bigger ships can buy racks with autoloaders to store more. But fighters should have access to these types of armaments, each one ready to fire, but no loading mechanism for more as the rack outfit is too big for them.
> 
> This lets the player experience them in smaller numbers too when they run up against a fighter with them, they get used, then they run out.

This was in fact my original proposal, and I still feel that it was the best approach, because it would allow fighters have a small amount of missiles, and big ships can have a large amount of missiles. This way, fighters can be dangerous, but have a limited combat endurance and not contribute so much to missile spam.

**Comment by Zitchas** [comment]
I recall in ES how the corvette had something like 4 heavy missiles, 6 regular missiles, and twenty odd javelins. Taking it on in a clipper, I always felt really rewarded when I carefully dodged missiles and lured it into wasting the heavy rockets and javelines until I could close in for the kill, confident that it had wasted all its heavy DPS. I've never really had that rewarding feeling in ES. I think @Pointedstick's suggestion would potentially bring that back.

**Comment by SirStigII** [comment]
I'd go as far as to say I'd like missiles to not take up a gun port, I find them useful but not something I'd want to rely on, and on most smaller ships you only have 2 ports. I'd like to see missiles used more as a support weapon instead of a main weapon. If I'm honest I feel like launchers should be limeted to the amount of missiles shown in the picture (with weight changed to reflect it) and racks required if you want more. It would take a more realistic approach while still being something you could balance.

**Comment by Zitchas** [comment]
I fully agree with that. (And, as an added bonus, it takes it back to how EV worked. Gun ports were for guns. Turret hardpoints for turrets, and all the rest of the outfit space (or weapon space, in this case) was for sticking missiles or whatever else into.

**Comment by Amazinite** [comment]
I'm not too keen on the above suggestions given that they completely deviates from the current system, where as the changes that came with v0.9.9 only altered the existing system. Seeing as how feedback is relatively positive with regards to the strength of missiles and only their frequency is in question, I don't see why it would make sense to completely overturn missile balance again by making such massive changes instead of simply reducing the number of fleets that can spawn with missiles.

With regards to the conversation about fighters though, with #4392 we could give fighters and drones built-in missile launchers, effectively allowing some of the above ideas without changing the balance of missiles for everything else. The built-in weapon system would also to an extent allow the idea of missiles not taking up gun ports, simply without the same level of customization as right now. That seems like something for plugin territory, though.

**Comment by Zitchas** [comment]
Well, getting missiles (at least in fighters) out of the gun ports is a good start. I look forward to getting missiles in general out of the ports, but starting small is fine by me.

**Comment by Pointedstick** [comment]
I'm also not super keen on making missile launchers not take up gun hardpoints. I think the current approach works well enough; the problem (such that it even still exists) is launchers that are too big and can't be stuffed into fighters in adequate numbers. Built-in launchers would solve that problem, and I think it could make a lot of sense.

**Comment by Zitchas** [comment]
That's fair, but I think we at least need to get the engine to *handle* having missile launchers that don't take up hardpoints. Once we have that, we can experiment with various configurations and setups, and see how things work. 

Something that comes to mind is that it would be interesting to have dual configurations where there is a missile launcher that takes up a gun port, then have another version that has significantly more space requirements, since it has to include all that support machinery itself.
