### ISSUE TITLE
Suggestion: Shift should reverse target select, not select different kinds of targets

### ISSUE THREAD

**Issue by guillochon** [endless-sky/endless-sky#418]
Holding down shift while cycling through items on a computer almost always reverses the cycle order. In Endless Sky the shift key is instead used to modify the selection (e.g. select escorts instead of just ships). As an example holding shift while pressing command + tab on a Mac (or Alt + tab on Windows) will reverse the order that applications are cycled.

I suggest the following: Change the modifier from "shift" to "option/Alt," then re-assign the shift key to reverse target selection duty. This would make it more consistent with how list item selection is generally done on computers.

**Comment by Pointedstick** [comment]
This is consistent with general desktop OS conventions, but it would require making the shift key unbindable in the preferences. Imagine if you had shift bound to "fire secondary weapon" and you accidentally fired a missile at the ship you were trying to un-target!

**Comment by egilburg** [comment]
In most games shift is treated like a continuous modifier - e.g. shift+w to walk if just w means run. As opposed to a single-use button like fire a missile. 

IMO it should be this way in Endless Space too. You should be able to bind any key to shift+<that key> for an alternative action, at the cost of being able to bind shift independently.

**Comment by thenerdfreak** [comment]
if this were made then we would need an independent button for hailing a target planet :p because shift T is the only way I can do it

**Comment by egilburg** [comment]
@thenerdfreak why? shift+tab cycles, shift+t hails, that's the whole point of modifier key.

**Comment by thenerdfreak** [comment]
No. Shift plus tab opens the steam menu :p GG

**Comment by frameworld** [comment]
I generally hate the ALT-tabbing out issue. You can't freely use these keys reliably.
Or you press the key between shift+tab and are stuck in UPPERCASE. When you regularly play games where chat matters, that's why I moved my hotkeys to SDFG+surrounding keys.

Unfortunately keyboards listen to only 3-4 keys at once (shift+alt+crtl+space excluded), even a 50€ expensive gaming-keyboard can do that.
* So you are sometimes required to use these keys.

Sometimes I wish I could design my own keyboard. Perhaps the game should not rely on (while key-pressed) but on (key-down → key-up) events and the order.
* Because even if I would have my own keyboard design, games that would have no support for it just makes me sad.

As for special keys, I don't care (because of the reason I stated above).
But I would like 2-key combo-hotkeys.

**Comment by anonybosch** [comment]
Y,U,K,Z,X, and V are still available. Why not use one of those?

**Comment by frameworld** [comment]
> Y,U,K,Z,X, and V are still available. Why not use one of those?

If you squish every bit out of all keys, there is no room for customization per player.

**Comment by DingusShingleton** [comment]
The targeting system while it certainly gets the job done, still has toom for improvement. And this is one thing that would help IMO. since there is no way to target in the previous direction, when there are lots of ships in the system, it leads to constant "DANGIT i missed it" and having to go through the entire list again, whereas a simple shift+n/Shift+r would solve that beautifully. As for friendlies, giving "target next friendly ship" a hotkey (e, for example) seems simple enough. Better to have n/r/e for "next" and shift+n/shift+r/shift+e for "previous" rather than needing 6 different buttons for those 6 tasks
