### ISSUE TITLE
Pirates constantly targeting weakest ship, often a new capture.

### ISSUE THREAD

**Issue by amtgeography** [endless-sky/endless-sky#4220]
Pirates very often target the weakest ship in the system (or possibly my fleet). They also spawn in a lot of systems about every sixty seconds.

This is creating a regular situation where I capture a ship, only to see it immediately disabled (usually destroyed) unless I'm at the edge of the AI fence and I jump out of the system right away.

Capturing and plundering is overpowered. But it is still extremely frustrating to go through the process of capturing a ship like a Leviathan, then have a pirate fleet jump in a couple seconds later and focus-fire on the already half-dead ship. It is especially annoying when it happens between the time I hit j and my ship exits the system.

I'm running vanilla 0.9.8, so maybe some of the work that's been done will address this, but I didn't see it searching through the recent issues here. 

Probably could be merged with any existing pirate behavior thread that aims to make them less ridiculously suicidal.

To replicate, pick a pirate-heavy system where there's enough neutrals that they're not always targeting you or your escorts then pick off somebody and capture them out away from the center. Usually only takes a couple tries before I've got a horde of pirates charging in. Are there just a bunch of pirates spawning with the nemesis tag, or?

**Comment by jafdy** [comment]
Ships focus the threat they can take down the fastest, recently repaired ships often fit this category.
As for large numbers of pirates . . . are you flying a fleet with lots of cargo and not a lot of weapons?

**Comment by Fzzr** [comment]
Try removing the weapons from the ships before capping it, that might make it a non-target.

**Comment by m4v** [comment]
I find this really annoying when my ship is disabled. If a friendly fixes it, then is immediately disabled again because a pirate decided to momentary ignore whatever is fighting and take a few shots at me.

If the one fixing me is an unarmed escort then it gets into a fixed, disabled, fixed, disabled, fixed, disabled loop until one ship is destroyed.

**Comment by tehhowch** [comment]
- You can often bribe the attackers for safety.
 - You can ask multiple non-hostile ships to help you, thus increasing the number of ships that will engage your attacker.
 - You can jettison some cargo to serve as a distraction

The tendency of AI ships to pick targets that will reduce the number of ships that can fire at them is a behavior that won't vanish. No one seems to complain that their AI-controlled escorts attack & disable heavily damaged pirate ships instead of changing targets to attack full-health ships ;)

I've mentioned in a similar issue that the specific prioritization constant affecting this behavior could be tweaked but I think at this point 0.9.9 will be released before we make additional balance changes.

**Comment by Zitchas** [comment]
This behaviour is just the pirates demonstrating good tactical decision making. If a disabled ship just got repaired and is in the process of building back up to full strength, it is very much worth their time and effort to divert from their current target to take it out, since, as you point out, it is easier to take out a still heavily damaged ship before it has a chance to repair. Also, being pirates, that disabled ship is literally their loot. They don't want it just flying away.

Annoying behaviour? Yes. Intelligent decisions making and sound tactics? Definitely yes. (usually)

**Comment by m4v** [comment]
> No one seems to complain that their AI-controlled escorts attack & disable heavily damaged pirate ships instead of changing targets to attack full-health ships ;)

Would they? would players complain that their escorts aren't picking targets with machine-like efficiency? could they even realise that with the information the game provides?

Some concessions has to be made for the sake of _fun_, I have seen issues where some aspect of the game was changed for make it less annoying, I don't think this case is any different.

> This behaviour is just the pirates demonstrating good tactical decision making. 

This is just the AI having _full_ knowledge of _every_ ship at _any_ time and reacting _instantly_ as the situation changes, lets not call it anything special like "good tactical decision making". This isn't anything like the human pilots the game is trying to portray to the player, much less the teenagers forced to fight that the lore talks about.

**Comment by jafdy** [comment]
So what better approach could be implemented? Clearly you don't like the "shoot the weakest" approach, however sensible that may be. And a "tunnel vision" approach would be extremely frustrating for new players and extremely exploitable by experienced players.

Just to be clear, I am asking for an algorithm, not a vague notion that can be summed up as "make it better".

**Comment by Zitchas** [comment]
That's a good point.

How about some kind of delay? 

If a ship is repaired right in front of them (say, within a 45degree arc and less than 800 distance) it is considered something they could immediately recognize as a threat and switch targets. 

If a ship is repaired within only one of those two criteria (so, either 45 degree arc centered on their front OR 800 distance), they realize it is a threat after a few seconds. Say, 5 seconds for the purposes of discussion.

If a ship is repaired outside of both their forward field of view AND is beyond 800 distance, then they don't include it in their target-seeking / attack behaviors for 10 seconds.

And since there always has to be exceptions:
If the newly repaired ship is the *only* hostile ship visible to them OR if every other hostile ship is at least twice as far away from them, then they immediately include it in their target list. (So, situations like the newly repaired ship is 1000 distance from them off to the side, and the next nearest hostile ship is 2000 away).

The second adjustment would be that the instant the repaired ship fires at the ship in question, it immediately ends whatever delays might have been happening. 

That would need adjustments, and probably extra categories. And might add enough calculations to not be worth it. But how's that for a general concept?

Bonus points if the values could be adjusted based on faction or fleet values. perhaps simply using the `inaccuracy` value as a modifier, since that is basically reflecting the degree of training and skill at combat. Highly accurate (aka very skilled) naval ships would understandably react faster to changing combat environments than an untrained or unskilled crew.

The flip side of all this (thinking about the "untrained teenagers" comment): Currently, some of the best video game players in the world are teenagers, and historically they tend to have the advantage over adults in terms of high-speed reactions to varied data input. While as a group they may lack long-term strategic thought, they do seem to be able to outperform adults (especially much older ones) in short term tactical decisions. (thinking on the seconds to minutes timescales of combat and games like starcraft).

**Comment by m4v** [comment]
> Clearly you don't like the "shoot the weakest" approach

I didn't say that in my comment, I don't mind the AI targeting the weakest ship (I wouldn't mind if they stopped attacking a ship they have no chance of beating either, but I disgress). What I do mind is my ship begin disabled because they instantly know I got repaired and go "lets ignore my target for half a second so I can drop some shots on this guy in _particular_". It's bad if it becomes a fix-disable loop, it's worse if I end destroyed because the AI casually switching targets happens to have a big guns and doesn't know restraint.

>Just to be clear, I am asking for an algorithm, not a vague notion that can be summed up as "make it better".

Just say [patches welcome](https://www.google.com/search?q=patches+welcome) so I know that I should better do something else with my time. 

Users are good at pointing problems but not at solving them. I'm not familiar with the source code, If I had an algorithm in mind it would come in the form of a pull request and not a critique. 
Maybe it would be best for escorts to not fix my ship unless requested or until combat is over, maybe it would be best to limit how often can the AI switch targets; for OP's user case maybe It would be best to reduce the rate of new enemy ships entering the system, maybe pirates could use some of their "good tactical decision making" and not accidentally destroy a half dead ship they would want to board later.

I wouldn't know.

> The flip side of all this (thinking about the "untrained teenagers" comment): Currently, some of the best video game players in the world are teenagers

That's only because video game players doesn't have the inconvenience of _death_ the first time they fail, the best video game players are _highly_ trained by their own experience.

**Comment by MCOfficer** [comment]
> Just say patches welcome so I know that I should do something else with my time.

A good chunk of people here do not contribute to the source code, but to the datafiles, so i doubt that was no intentional "PR it". Your suggestion is indeed a bit... vague, to say the least. You can say that something simply isn't fun, and we can hardly deny it unless we all disagree, but to actually fix it we need some ideas how, hence the question for something akin to an algorithm.

> I wouldn't know.
+1 for honesty. i don't know either, but zitchas' suggestion sounds promising.

**Comment by m4v** [comment]
>To be fair: A good chunk of people here do not contribute to the source code but to the datafiles, and might not know the code either. I doubt that was an intentional "PR it".

I was asked for an algorithm, that's code as far as I know, pseudocode or a flowchart even.

>Your suggestion is indeed a bit... vague, to say the least. You can say that something simply isn't fun, and we can hardly deny it unless we all disagree, but to actually fix it we need some ideas how, hence the question for something akin to an algorithm.

I gave several ideas in my last comment, I don't know what about them is vague without having to resort to describe them in pseudocode, evidently we don't agree in what an "algorithm" is.

**Comment by jafdy** [comment]
Algorithm: a process or set of rules to be followed in calculations or other problem-solving operations.
Zitchas gave an example of a suitable answer to my request.
On the subject of that example it seems a bit arbitrary, I also think it would depend on weapons. It makes sense for front facing to matter if the ship has front facing guns but there is already a precedence for ship direction to not matter for most applications.

**Comment by tehhowch** [comment]
For those unsure of the current methodology: 
https://github.com/endless-sky/endless-sky/blob/938f68dec84d8e9f0f9bbb97299ed7c0e2c3cba4/source/AI.cpp#L547-L557

https://github.com/endless-sky/endless-sky/blob/938f68dec84d8e9f0f9bbb97299ed7c0e2c3cba4/source/AI.cpp#L1042-L1098

The easiest changes to make are to reduce the frequency of ship inspection from twice / second or loss-of-current, and adding more uncertainty in the AI's assessment of the other ships. Extending the target selection procedure to information gleaned over multiple frames will add considerable complexity (which is not the same as "won't happen" or "will reduce performance").

**Comment by Amazinite** [comment]
>Would they? would players complain that their escorts aren't picking targets with machine-like efficiency? could they even realise that with the information the game provides?
>...
>This is just the AI having full knowledge of every ship at any time

The status overlay is a thing that can be turned on in the preferences, allowing the player to see the status (hull and shield strength) of all ships on screen. A quick glance would allow one to notice those ships which are close to death, making those ships the best targets to focus on. So yes, players could realize that the weakest ships aren't being targeted, and the AI is using the same "full knowledge" that the player has.

**Comment by Wrzlprnft** [comment]
the player can only see what's on their screen, so zoom and reaction times indeed could be artificially added to the AI.

**Comment by ThrawnCA** [comment]
I know this is closed, but the simple solution that kept occurring to me is, Don't bother capturing ships in the middle of active combat. It is, as discussed, an invitation to get them shot.

If a particular system is _constantly_ in active combat, then that's just one more factor to weigh up in deciding whether or not to capture something. Capturing in a location like that is high-risk high-return. You can still plunder relatively safely if you like.

(Plundering all the guns, as suggested by Fzzr, could also work, yes.)

**Comment by amtgeography** [comment]
Does ES still even get attention? I gave up on it years ago. Tried to 
get off this thread, but it. Won't. Die.

On 2022-10-31 10:19, ThrawnCA wrote:

> I know this is closed, but the simple solution that kept occurring to 
> me is, Don't bother capturing ships in the middle of active combat. It 
> is, as discussed, an invitation to get them shot.
> 
> If a particular system is _constantly_ in active combat, then that's 
> just one more factor to weigh up in deciding whether or not to capture 
> something. Capturing in a location like that is high-risk high-return. 
> You can still plunder relatively safely if you like.
> 
> (Plundering all the guns, as suggested by Fzzr, could also work, yes.)
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you modified the open/close 
> state.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/endless-sky/endless-sky/issues/4220#issuecomment-1297415087
[2]

**Comment by ThrawnCA** [comment]
> Does ES still even get attention?

Yes, version 0.9.16 was released quite recently.

> I gave up on it years ago. Tried to get off this thread, but it. Won't. Die.

Well, you can disable all notifications for the GitHub repository. Top of the page, there's a Watch button that gives you options. Good luck!
