### ISSUE TITLE
Smarter escort refueling

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#425]
Currently, escorts will automatically land and refuel when they don't have enough to make the next jump.  However, this often gets them stranded in unoccupied systems because they won't refuel when they have 100 fuel and are about to jump.  I think it would be nice if escorts knew that they were about to jump to somewhere that didn't have fuel, so they would go ahead and top off their tank if the next jump would leave them stranded.  I call this the "you'd better pee now, because we're not stopping later" approach.

**Comment by thenerdfreak** [comment]
+1 I had a different idea but this works a lot better and isn't as borked (op)
Game would know that they don't have the fuel to finish the line and make them refuel

**Comment by brick96** [comment]
they do this when you leave them behind, i belive. leave planet, hold, reach destination, unhold

**Comment by Wrzlprnft** [comment]
if you start checking at 200, you might need to check for 300 too
if you start chekcing at 300, you might need to check for 400 too
...
i think there need a few things to be thought about additionally, but the idea itself is good

**Comment by endless-sky** [comment]
This should be fixed in 5e83ae3 (but with only one jump of look-ahead, which is enough to fix most of the times this happens).

**Comment by anonybosch** [comment]
@johndh My escorts don't <b>automatically</b> do anything. If your escorts get stranded it's because you're not paying attention. It's already pretty clear who can go how far and who can go a bit farther just by looking at the route colors of the jump path.

Say you plot an 8 jump route but it's farther than your fleet can go. Everybody gets to 6 is in green, some get to 7 is in yellow, and nobody gets to 8 is in red. So you land the fleet at 6 or risk stranding the ones who can't make it to 7 without refueling. How much simpler does that have to be?

**Comment by omagasohe** [comment]
I think one jump is fine, but people should watch out for there ships. All mine have ram scoops though =P

**Comment by anonybosch** [comment]
@johndh Where do I get some of these escorts that land themselves and refuel automatically? Because, currently, the only thing my escorts can do automatically is shoot at everything in sight.

Are you jumping through hyperspace without checking the map or plotting a route?
Currently, plotted routes clearly show who can go how far, who can't go as far as the rest, and if the jumps are plotted far enough apart, who can't get there at all without refueling. 

This one-jump warning thing. How would that work? A moronometer that looks like a gas gauge? Or an imbecilloscope that sounds sharp pings? Or a text box that opens and says, "Yo, numbnuts, you forgot to refuel!"?

One time I was hauling a load of framulators out to the end of The Rim and I ran into an old spacehand I hadn't seen in a long time. We chewed the fat for a while and I still remember something he said. "These kids today... I keep telling them, 'traipsing the void without a ramscoop is like hoverboarding with a spare battery.' But do they listen? Nooooo..." Then I remembered the framulators were a rush job and we said our goodbyes and went on our separate ways.

**Comment by anonybosch** [comment]
@thenerdfreak 
<i>Game would know that they don't have the fuel to finish the line and make them refuel</i>

Isn't that supposed to be your job and why you're getting the big credits while the rest of the slobs get a measly 100 credits per diem?

**Comment by Tufton** [comment]
Right but I mean, If I hire someone to fly my 30+ million credit ship
around, you better believe he knows how to read a fuel gauge.

**Comment by Wrzlprnft** [comment]
You might not have the newest version @anonybosch 
it works that if you travel along a route, your escort ships just land automatically and refuel, it doesn't matter what you do or where you are in the space

**Comment by anonybosch** [comment]
There's a version newer than 0.8.8? Well I'll be damned. I've been J-holding all this time.

**Comment by endless-sky** [comment]
In 0.8.8, escorts automatically refuel if they run out of fuel completely
(and are in an inhabited system). They also automatically refuel if you are
*not* in the same system as them and they are trying to catch up with you,
but know that the next jump will strand them in an uninhabited system. The
new change in the code (that will be in release 0.8.9) is that they will
also refuel if they *are* in the same system as you, and you are about to
lead them into a system where they will be stranded.

**Comment by anonybosch** [comment]
@endless-sky  Well, that solves that mystery. I noticed it but thought it was a bug. <i>Mayhaps a mention in the manual for the innocenti?</i>

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.

**Comment by lheckemann** [comment]
I still find it rather frustrating that ships will fly through uninhabited territory without having enough fuel if the AI is left to its own devices. Are you opposed to having them refuel/reroute as necessary as a matter of principle, or is it purely about the effort of implementing it, i.e. would it be worth submitting a PR to improve the behaviour?
