### ISSUE TITLE
Guns without ports firing issue

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#4251]
**Describe the bug**
1) When guns are purchased that do not have `"gun ports" -1` as an attribute, they still take up the gun slots in the ship diagram, but do not prevent other guns that do use those slots from being purchased afterwards. When fired, the guns that don't use slots will fire, but the guns purchased afterwards will not.

2) When purchasing guns that don't use slots after having already filled up all gun slots with normal guns, the normal guns will fire and the guns that don't use slots will not.

**To Reproduce**
1. Modify a gun so that it does not use up a port
2. remove all guns from the test ship
3. purchase enough guns of the type that don't use ports as there are slots
4. purchase additional guns of a type that do use the slot.
5. test, and notice that whichever set of guns that were purchased first are the ones that fire. 

**Expected behavior**
- That all other guns function normally, regardless of whether they were purchased before or after the guns that do not use ports;
- that the guns that don't use ports aren't assigned a weapon spot on the ship diagram.
- That guns that don't use ports fire normally from a location determined by one of the following two methods (or both in sequence)

1) guns purchased that do not use slots will default to using the locations indicated in the ship diagram for guns, but are not listed in those spots and don't interfere with normal guns that would use those slots. (this would result in stacking where a gunport would visually have both a regular gun and a gun-that-doesn't-use-ports stacked on top of each other.
2) guns purchased that do not use slots will default to the most-forward point of the ship's hitbox along the centerline as the firing location. (so 0 on the left/right axis, and whatever the forward-most point of the hitbox is on the aft/stern axis) This would be the fallback solution for situations where the ship does not have a gun port.
3) turrets would default to 0,0 or center of mass as their firing point.

**System (please complete the following information):**
 - nightly as of https://ci.mcofficer.me/job/endless-sky-win64/143/

**Additional context**
The current behaviour of guns suggests that -even without the `"gun ports" -1` attribute, the game still recognizes them as guns and puts them into the correct ship diagram slot and associated position. It simply needs to be modified so that this behaviour does not interfere with normal guns that *do* utilize those slots.

While guns or turrets that do not take up the relevant port probably shouldn't be a common thing in vanilla, it is a perfectly valid thing that plug-in creators or mission writers should be able to do, and that the game should be able to handle mechanically without glitching. (at least up to the already existing 32 guns/turrets limit).

Three examples I could see this being used for:
A) creating weapons, such as a bomb dispenser or the minelayer, that are technically weapons but should definitely not be launched forward from a spacecraft. These shouldn't be using gun ports at all, as they are merely dispensing things out of the craft with the intent that they go backwards, not forwards. 
B) creating weapons that are designed to provide their own superstructure. For example, missile racks that take up twice as much space because they include all the support structure & connections instead of using a gunport. 
C) giving the player unique story weapons that have story reasons for being attached to the ship in ways that don't involve being slotted into standard gun or turret ports.

**Comment by tehhowch** [comment]
This automatic allocation of guns to ports occurs because `Armament` currently only tests for the presence of `"turret mounts"` to determine if an added outfit uses a turret mount or a gun port.

I don't consider it an issue that the ship is only able to fire as many weapons as the ship chassis was designed to handle (# gun ports + # turret mounts = # hardpoints = # max supported weapons). It's possible new syntax could be developed to help obey this ship design decision (hardpoint count) while allowing for creatively positioned weapons.

That is, I believe it is a content definition error to create a weapon that does not use a hardpoint, as only hardpoints are designed for carrying external/internal loads.

**Comment by Zitchas** [comment]
OK. So currently it is a bug that the weapons without ports aren't flagged as an error. 

Should I resubmit this as a feature request, then? Because I would like to have this functionality.

**Comment by tehhowch** [comment]
I've addressed the erroneous equipping of an outfit that specifies a `weapon` node without specifying how the hardpoint(s) it consumes.

I have not added a method for specifying "no hardpoint needed" or "multiple types of hardpoints" as these are not cases for which we ever had true support. I have not improved support for outfits that consume multiple of the same type of hardpoint.

I considered adding a check in `Outfit::Load` to supply a load-time warning for the outfit, but such a check will flag any weapon outfit that is not intended for use as a ship-fired weapon (such as a ship's death explosion, or submunitions). Instead, I have settled for a run-time warning message that is logged in the console, and avoiding adding the outfit to the ship's `Armament`. The outfit is still installed in the ship (e.g. it may have other non-weapon utility), but cannot be fired (because it is not in the ship's `Armament`).
