### ISSUE TITLE
Afterburner effect is offset from engine flare point at certain times

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#4260]
**Describe the bug**
When the ship is pointed in a direction perpendicular to the path of travel, the afterburner effects are created at a point that is ahead of the engine flare point in the path of travel.

Which is to say, when the ship is rotated relative to the path of travel, the afterburner flare appears to be coming from where the engine will be in the future, instead of where the engine is now.

**To Reproduce**
1. Outfit a ship to have an afterburner
2. Go fly in space.
3. Accelerate in a straight line
4. cease acceleration.
5. rotate 90 degrees to the path of travel. (either direction works)
6. accelerate and use afterburners.
7. Notice that the afterburner effect occurs to one side of the engine flare (the side that is ahead of the ship in the direction of travel)
8. Watch as the afterburner flare slowly comes into alignment with the engine flares. This seems to correlate directly with how close the ship is to being fully aligned with the path of travel. Fully aligned to path of travel = afterburner fully aligned with engine flares.

**Expected behavior**
I expect to have afterburner effects remain perfectly centered on the engine flare. They are, after all, a modification installed directly on the engine port.

The effect trail could be expected to *trail* the engine flare if it is a smoke effect that isn't moving as fast as the engine flare itself, but in no circumstance should it be *leading* the engine flare. In other words, the default behaviour for an afterburner flare should be that its point of origin should always be the engine point unless otherwise determined by an offset in the effect definition.

**Screenshots**
https://www.youtube.com/watch?v=kQMeGOVa9Tk
This video shows a starling with a standard afterburner installed. It starts out accelerating in a straight line, then rotates 90 degrees and accelerates while using the afterburner. One can see how the afterburner leads the engine flare, with the lead distance steadily decreasing until they match after the ship has fully changed direction.

**System (please complete the following information):**
 - OS: Windows 10 Pro, version 1803 build 17134.648]
 - Game Source: Github as of 2019-APR-18
 - Version: [MCO nightly build 144](https://ci.mcofficer.me/job/endless-sky-win64/144/)

**Comment by Zitchas** [comment]
I have observed a second behaviour of the afterburner flare which I suspect is probably related. The afterburner effect position shifts forwards and backwards (relative to the ship orientation) based on how fast the ship is moving relative to its maximum speed: If the ship is pointed the opposite direction from its path of travel, the effect starts behind the engine flare's start point. That is to say, it starts farther along in the direction of the path of travel from the ship.

As the ship applies thrust, which brings it to a stop and then accelerates it in the opposite direction from where it was initially pointed, the start point for the afterburner flare moves forward along the ship's longitudinal axis until it is preceding the engine flare start point, in this case by being practically on top of the ship sprite.

*Video of bug in action*
[Afterburner bug 180degree to path of travel](https://youtu.be/KBKBVblIP8Y)

*Expected Behaviour*
Due to the fact that this is taking place in space and is not subject to aerodynamic flows, I expect the afterburner flare to be consistently matching the start point for the engine flare.

**Comment by djlad** [comment]
Quick fix here: #4261 

The afterburner effect is a Visual. The visual for the afterburner is created before the visuals and flagship has moved:

![image](https://user-images.githubusercontent.com/7683633/56464024-189e5600-63ae-11e9-819e-4730c00e26c1.png)

It places the afterburner at pos + velocity because the ship hasn't moved yet, so it's putting the effect where the engine point will be after the ship moves.

This produces approximately the right point, but something else is moving the visual forward .5 velocity after this spot. I am not sure where that is happening since the visual velocity would move it backwards.

The quick fix is to only move the visual forward .5 velocity:
![image](https://user-images.githubusercontent.com/7683633/56464054-de818400-63ae-11e9-85b5-5668218ec1a9.png)

Otherwise we can try to track down whats moving the visual, or we can move the afterburner effect out of the Ship.move function. Then we can put it after all functions that move visuals or ships. The game state hasn't been calculated yet, so we would otherwise be spawning the object using old game state.

The engine flare works fine, because we use it after the move function finishes calculating state.

**Comment by Zitchas** [comment]
Interesting. Thanks for tracking down what's going on!

**Comment by tehhowch** [comment]
This was caused by the [switch to BatchDrawList](https://github.com/endless-sky/endless-sky/commit/8a13777ad8ca580e34e01e8129ba61232fcaafbf), which unified the draw code route between Projectiles and Visuals. Projectiles [have always had a somewhat hacky drawing calculation requirement](https://github.com/endless-sky/endless-sky/blob/cab74fd31f1984d2e9010b93849c2db2a09bc468/Engine.cpp#L520-L525) that stems from the lack of a custom sprite anchor point: given that "lasers" and "missiles" are both Body objects that are created at a ship hardpoint position, and given that a Body's sprite is centered about its origin, you end up with wacky things like this if you don't compensate by something:
![image](https://user-images.githubusercontent.com/20871346/79698982-0ae60f80-8252-11ea-8330-3280b10c55c3.png)
Note that this is basically the same reason that #4814 was filed: effects do not have a significant velocity of their own, and thus the compensation that works for Projectiles fails to work to create "laser effects" and the creator must instead manually pad the sprite dimensions so that 0, 0 is a sensible position for the effect.

Without adding new functionality for sprite anchor locations (and then breaking every mod that doesn't specify this location for its laser sprites), the simplest fix is to restore the separate code paths. We can still keep the graphical savings from the batched draw commands, though: https://github.com/endless-sky/endless-sky/commit/d4e4bb26b1d022bfa44d5392c87b37e387d18e54
