### ISSUE TITLE
Adding fuel damage to forbearing 

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#4264]
Currently, the forebearing attribute is related to damage taken; the quarg lore specifies that they care about their fuel, but with the current mechanics fuel damage could decrease their fuel to less than 200 without angering them
There would be 2 ways of implementing this:
1: simply, if the player reduces the fuel of like the 20% then the ship with the forebearing attribute becomes an enemy;
2:  if the fuel is below 400 or so, then do not ignore the damage anymore even if the shields are above 90%

**Comment by Amazinite** [comment]
Something important to note about the forbearing personality is that it causes the ship/government to become hostile if you hit them directly, deal damage, and their shields or hull are below 90%. That is not the same as hitting the ship and having that hit put their shields or hull below 90%; if you were to join in on a fight against some Quarg, if you deal even 1 damage to a Quarg ship and their shields or hull are already below 90%, that will turn them hostile.

The reason I bring that up is because if we were to add fuel to the equation, I imagine it'd be a similar "become hostile if took direct damage and fuel <x%," but the problem with that is that a ship could have below a certain fuel level by having used its own fuel through normal means, meaning that becoming hostile off of the current fuel level could give a false positive on when we want the ship to become hostile.
