### ISSUE TITLE
Timer Ship is disabled soon in "Sad Archie."

### ISSUE THREAD

**Issue by oo13** [endless-sky/endless-sky#4271]
**Describe the bug**
Entering Ildaria, you fall asleep in several seconds.

**To Reproduce**
1. Finish the mission "There Might Be Riots part 3B."
2. Go to Ildaria.

**Expected behavior**
You meditate deeply.

**System**
 - OS: Debian GNU/Linux testing
 - Game Source: Github
 - Version: commit hash 37f6d1238c19bc8947393a4272d4a42d2c73623d

**Additional context**
In v0.9.8, I had to wait for a few minutes.
In c6dd97e3497c757fc7cf569b672c7b7129afe8b9, I could not cause "Sad Archie."
c73e3a47406741e63783e6fa3556023da65805d5 was the same as current behavior.

**Comment by tehhowch** [comment]
The Timer Ship "mechanic" of firing a short range weapon with a larger blast radius no longer reliably works since the ship AI now considers if it will be hurting itself. Thus, before blast strength falloff was implemented, the Timer Ship couldn't put out enough DPS to kill itself. After the blast strength falloff was implemented, it was able to put out enough DPS because of the trigger range compensation:

With a base damage of 0.1, trigger range of 200, and blast radius of 20, the calculation of scaling coefficient yields [*26*](https://github.com/endless-sky/endless-sky/blob/b14b2b666f48a61b06e3956214f50a0e2f2ffacb/source/Ship.cpp#L2616-L2618) (expected normal values are < `1.25`). So with a damage output of 2.6 and total health of just 3, it only took 2 or 3 shots for the NPC to disable itself.

Without the damage scaling, the ship's hull repair rate (boosted 3x by https://github.com/endless-sky/endless-sky/commit/cbdc163c6e15b76b327d3b7bdf6337b1eac237d0), coupled with the increased range when firing, meant that the ship was drastically outhealing its DPS.

I've abstracted the self-damage into a submunition to ensure a short-range firing solution, and added a `split range` to help make sure the submunition is able to deal damage. I kept the higher hull repair rate and tweaked the base damage output slightly to account for the increased hull repair rate. (Reverting the damage increase and the hull repair rate increase would mean that those who currently have the mission would not be able to complete it.)
