### ISSUE TITLE
Free Worlds Defends Republic Systems (Free worlds storyline bug)

### ISSUE THREAD

**Issue by Jojobees** [endless-sky/endless-sky#4276]
I was in the free worlds storyline and I decided to increase my cash flow by going to a republic system and demanding tribute, but when I came back to free worlds, they were hostile towards me, because it was the militia who were defending the republic systems.

**To Reproduce**
Join the free worlds storyline until you're at war with the Republic, then go to Zeta Aquilae, Rasalhague, Ascella, or Peacock (confirmed bugged) and demand tribute. The defense fleets will be militia, even though these systems are republic, and after defeating them, you will become hostile towards free worlds.

**Expected behavior**
These systems were under republic control, so I expected to fight the republic defense fleet when demanding tribute. Even if they are defended by 'local militia' as suggested in a previous closed bug report, it should not make me hostile towards free worlds after defeating them.

**System (please complete the following information):**
 - OS: win 10
 - Game Source: steam
 - Version: 9.8

**Link to save file**
I already restarted from the last hard save, losing a few hours of progress.

**Additional context**
I did see this reported and closed in another thread, and the explanation given was that the systems were defended by local militia rather than the Navy, but this shouldn't make me hostile towards free worlds if that's the case.

**Comment by tehhowch** [comment]
The Free Worlds is made up of a militia. Why wouldn't attacking a militia -- not the Navy -- anger other militias?

**Comment by MCOfficer** [comment]
#1289 and #2428 have good reasoning on this question. also #1642

**Comment by Jojobees** [comment]
At least show us in the map somehow that they are defended by militia. I was told that I could attack any Navy I saw along the way, so I assumed that they'd be fine with me taking tribute. But when I attack the systems, suprise! The system is defended by a local militia (which is coded as the same as FW) and when I kill them, the FW get mad at me.

Bottom line is, it's a republic controlled system, and the code says it's defended by free worlds. I don't care how you logic it out, it's a bug.

**Comment by MCOfficer** [comment]
you are apparently oblivious of the fact that milita are not necessarily FW, despite being told so multiple times. if you don't listen to us, why should we listen to you?

**Comment by kikotheexile** [comment]
If you open the games data files and check for bugs from there, you'll notice something really interesting.

The militia is totally disconnected from the free worlds. 
The free worlds is not *the* militia.

They share colors thanks to the mutual defense pact having been a militia before the formation of the free worlds

If you check the planets in question in map.txt, you'll see that the planets are defended by the militia - their own planetary militia - not the free worlds

You will also see that the Militia is kinda beloved by everyone, excluding pirates. They are volunteers who go into combat to defend their planets. Everyone has respect for them. 

So, I absolutely get why MCO is frustrated about this, and also understand your confusion. But, the planets aren't defended by the Free Worlds, they are defended by someone the Free Worlds really, really likes.

**Comment by Jojobees** [comment]
That's weird, because in my map.txt, 'free worlds' doesn't even exist.

**Comment by beccabunny** [comment]
That's because the free worlds declare their indipendence only after that a pilot is started

**Comment by kikotheexile** [comment]
We really do appreciate how exited you are for this game, and appreciate that you would like to contribute to this game by finding minor errors and bug reports. 

And frankly, that's absolutely great and to a degree you should keep at it. 

In this event, however, what you are reporting as a bug is an intended feature.

`government "Militia"
	swizzle 2
	color .06 .68 0
	
	"player reputation" 0
	"attitude toward"
		"Merchant" .3
		"Pirate" -.4
	"bribe" .1
	"friendly hail" "friendly militia"
	"hostile hail" "hostile militia"

government "Free Worlds"
	swizzle 2
	color .06 .68 0
	
	"player reputation" 1
	"attitude toward"
		"Merchant" .3
		"Militia" .3
		"Pirate" -.4
		"Neutral" .1
	"bribe" .1
	"friendly hail" "friendly free worlds"
	"hostile hail" "hostile free worlds"
	raid "pirate raid"

government "Republic"
	swizzle 0
	color .91 .42 .09
	
	"player reputation" 2
	"attitude toward"
		"Alpha" -.3
		"Merchant" .25
		"Militia" .1
		"Pirate" -.3
		"Navy Intelligence" 1
		"Navy (Oathkeeper)" 1
		"Neutral" .1
	"friendly hail" "friendly navy"
	"hostile hail" "hostile navy"
	raid "pirate raid"
`

You'll notice specific attitudes are directly tied together, and that both the Republic and Free Worlds love the militia. 

The militia is a """government""" of small, independent, planetary volunteers that defend merchants and planets from pirates. 

Demanding tribute from a world controlled by the militia and then killing the militia is very much so a big no-no to both these factions. They really don't want you killing innocent people. So the free worlds will indeed get mad at you over it.

**Comment by Zitchas** [comment]
One of the big motivators for the Free Worlds is the fact that the Republic won't allocate enough Navy to defend them against pirates, leaving the job for the local militias. As a result, the majority of the Free World's military is made up of former militia. Just because some worlds who share their cause didn't rebel with them doesn't make them enemies. 

Perhaps a better way to look at it is that the Free Worlds are simply the stronger, braver, or more aggressive version of the militia: They share the same aims, and their overall purpose (defend their worlds against pirates) is the same. The only real difference is that the Free Worlds decided to lump the Republic government into the same category as pirates (profiting off them without providing any benefit) whereas the militia's from non-Free Worlds did not.

You'll probably note in the story that the Free World doesn't even hate the Navy. They will fight them, of course, but the only ones they actually hate is the Republic government itself.

Also, by demanding tribute from a planet, you are actively acting like a pirate, and destroying a large portion of the fleets that would normally protect said planet from pirates. Given that the Republic providng insufficient forces to protect planets from pirates was a catalyst for the whole thing getting started, it ought to be fairly obvious that this is a course of action the Free Worlds aren't going to be very happy about.
