### ISSUE TITLE
Automatic Universe Trader "AI" for your ships

### ISSUE THREAD

**Issue by Noxmiles** [endless-sky/endless-sky#4277]
**Is your feature request related to a problem? Please describe.**
Endless Sky is nice - but you have to do everything on your own. Similar to X1-4 there should be an (expensive) Outfit for your ships for automatic universe trading.

**Describe the solution you'd like**
The Universe Trader Option in the X Games was a quite expensive outfit, but enables a ship to buy and sell products in stations. So you don't have to fly and buy everytime yourself, but the ships autopilot / crew is trading on their own while the player can do missions or fight pirates.

Actually ships not in your own sector don't have to be 100% simulated, just add a time for jumping through sectors, buying or selling stuff and maybe a random offset. Of course Pirates could destroy the automatic ships - could be implemented by a chance in each sector.

**Describe alternatives you've considered**
The fleet should get basic intelligence instead of just fly behind the player or wait in a sector.

**Comment by jafdy** [comment]
Please see any previous auto trading requests. TLDS: ES isn't a sim and automating everything isn't what we try to do. Ultimately ES is a story telling game and the feature set is built that way.

**Comment by Zitchas** [comment]
While it would be interesting to be able to command fleets to do different stuff behind the scenes (such as trading, protecting a specific system, ferrying outfits from one place to another, etc), it likely won't be a priority for the developers due to the fact that Endless Sky is primarily a spaceship based RPG or story telling game. As such, their efforts are focused on those elements of the game that will directly benefit the story telling and character-immersive elements of the game. 

At its core, Endless Sky focuses on exceptionalism and how one person *can* change the galaxy in unforeseen ways, and enabling players to build up vast wealth and power without actually doing anything runs counter to that.

While it wouldn't achieve the automated trading you have asked for, a more likely improvement might be the ability to assign specific behavioral patterns to the ships in your fleet. Ex. Snipe, close & melee, pack, solo, evade, stay as far away as possible, etc.

**Comment by jostephd** [comment]
I'd love to have a very simple change: once a destination is selected in the map screen, auto-sell all commodities and minerals and auto-buy whichever commodity makes the highest profit per ton for the selected destination. That's it. Nothing else. Doesn't even have to be an outfit; I'd be happy if it were a new button/hotkey on the map screen.

Why? Because during early game, it's not fun to have to check every time what commodity to buy.

The algorithm is deliberately simple, to make sure the player still has to do something. The algorithm doesn't check if there are enough funds to pay salaries and loans until the next landing; the player will need to do that. When traveling towards the Paradise Wolrds the algorithm will buy Luxury Goods almost every time, even if that runs out of funds before running out of cargo space and buying Heavy Metals or Food would yield a larger profit for the run.

**Comment by Amazinite** [comment]
Ref other "auto do-something" issues, which included auto-buy-sell: #3620 #1504

**Comment by jostephd** [comment]
Thanks for the refs. In terms of MZ's https://github.com/endless-sky/endless-sky/issues/1504#issuecomment-243287632, I'd say auto-buy of commodities has no effect on Star Trek mode, is useful in Star Wars mode, and only partly helps Firefly mode, since the player is still going to have to babysit the automation and overrule its decisions from time to time.

**Comment by Pointedstick** [comment]
I personally think it's fun to fly all over the galaxy outfitting your ships in exactly the way you like. On the way, interesting things can happen. If you automate that away, you're reducing the game to a less serendipitous and more mechanical exercise of pure numbers, which isn't really what the game is about.

So I'm gonna have to say that we won't do this. Features that amount to automating away core elements of the game's gameplay don't make much sense; if you don't like this kind of "Space Trucker" game, don't play it. :)
