### ISSUE TITLE
Feature Request: Crew Numbers as Condition

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#4286]
Have the flagships required crew and current crew exposed to condition statements in missions.
This implies being able to modify current crew inside missions too.

**Comment by Zitchas** [comment]
Definitely a good idea. As a mission writer, this would be a very useful variable to have for branching dialogue. Up until now it has basically been verbotten (forbidden) to reference the player's crew in descriptive text, because there is no way to know if they are flying a ship with 1 crew or a ship with a crew in the hundreds. This will probably still be the norm, but it would open up a lot of potential descriptions, scenes, and descriptive variety.

**Comment by Fzzr** [comment]
I would say that checking flagship crew and modifying it from within a mission are distinct features. There's no upfront cost to hiring crew, so it's not a reward. All that can do is involuntarily change the player's recurring costs or damage their ship's handling without interactive combat. The only reason I can think of to modify player crew would be like the current firing of crew to fit passengers, rather than doing it manually during a mission. Checking for mission offers or conversation conditions makes sense, though.

**Comment by Fzzr** [comment]
See https://github.com/endless-sky/endless-sky/pull/4294 for a quick implementation of just the condition check part.

**Comment by tehhowch** [comment]
As of 7fe1e52 there are read-only conditions for the flagship crew. Allowing mission conversations or actions to explicitly modify the crew complement is not a priority.
