### ISSUE TITLE
Shipyards need a way to show the top-down view of a ship

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4312]
Ref: #3682, https://github.com/endless-sky/endless-sky/issues/3682#issuecomment-379564103, #3816 

Feedback has been generally positive with regards to the shipyard thumbnails, but the one complaint with them has been the fact that this now means that you can not see the top-down view of a ship until after you've bought it. One of the issues with this is that the shipyard thumbnails don't show scale as well as top-down views, such as how the Carrier and Cruiser thumbnails are the same size despite the Carrier being a larger ship.

Suggested having some way to view both the thumbnail of a ship and its top down view. 

<details><summary>Mock-up of a possible solution</summary>

When a ship is selected, a panel pops up either to the right or left of the image showing the ship's top-down view, scaled to how it was in v0.9.8. 
I'm using the "shipyard selected+" image rotated 90 degrees to the right or left in these images, but I did have to erase a bit of the bottom of the image in order for it to look good.
![Screenshot_1](https://user-images.githubusercontent.com/17688683/58649361-e8fe3a00-82d9-11e9-9ba3-7d55e335d6c7.png)
![Screenshot_2](https://user-images.githubusercontent.com/17688683/58649363-e8fe3a00-82d9-11e9-8846-435cfa2f4b1d.png)

The easily seen downside of this suggestion is that it covers up whichever ship may be to the right or left. A solution to that perhaps might be to have a button that one can press that shows the top-down view, similar in nature to Comnom's mock-up of an advanced stats button seen [here](https://github.com/endless-sky/endless-sky/issues/4215#issuecomment-469756467).
</details>

**Comment by Pointedstick** [comment]
Maybe the 3D view could be badged in the corner with a small version of the top-down view.

**Comment by jafdy** [comment]
Have it change from one to the other when selected?

**Comment by tehhowch** [comment]
Complex new UI elements would be something that doesn't make it to 0.9.10. The simplest would be a toggle checkbox in the shipyard, changing between the two.

**Comment by MCOfficer** [comment]
Either that, or something simpler, like holding down the alt or the ctrl key. that spares us from creating yet another setting.

**Comment by Amazinite** [comment]
>The simplest would be a toggle checkbox in the shipyard, changing between the two.

Could just copy from the outfitter. 
![image](https://user-images.githubusercontent.com/17688683/58716142-60919f00-8396-11e9-8bc9-d3d301596459.png)

Just a single `Show top-down images` checkbox would do.

**Comment by endless-sky** [comment]
Because the selected ship's info is only 750 pixels wide and the sidebar is 250 pixels, on nearly any monitor there's going to be extra space to the left or right of the ship info. Why not put the overhead view there? At 1280×720, which is probably the smallest resolution we need to worry about, that looks like this:

![beetle](https://user-images.githubusercontent.com/11450262/58717610-9a17d980-8399-11e9-84e3-699d41e38c3f.jpg)
![clipper](https://user-images.githubusercontent.com/11450262/58717620-9d12ca00-8399-11e9-9149-614d9c3d7d51.jpg)
![star barge](https://user-images.githubusercontent.com/11450262/58717624-a13ee780-8399-11e9-88bf-2d86134766a9.jpg)
![starling](https://user-images.githubusercontent.com/11450262/58717628-a3a14180-8399-11e9-9c4c-6911d0841836.jpg)
![albatross](https://user-images.githubusercontent.com/11450262/58717634-a7cd5f00-8399-11e9-8902-615721968748.jpg)

On a small screen, a ship like the Albatross with a very wide wingspan would need to be scaled down to fit. `ShipyardPanel::DrawDetails()` would just need to figure out how wide the sprite should be and update the centering / X offset to include the width of the sprite in the total width of that block of information.

**Comment by jafdy** [comment]
What about doing it the other way around, the default is the top down view and the extra displayed image is the 3D view from there. It seems that the size of the ships and other things about how the ship plays is better represented by the overhead view while the nice to look at but mostly unimportant view is the 3D one.

**Comment by Pointedstick** [comment]
The top-down view doesn't give a better sense of size unless all the sprites share the same scale--which is something that could be done with the 3D version too. The main reason to show the 3D version is basically just aesthetics. And I do think they're very pretty. :)

**Comment by Amazinite** [comment]
>Because the selected ship's info is only 750 pixels wide and the sidebar is 250 pixels, on nearly any monitor there's going to be extra space to the left or right of the ship info. Why not put the overhead view there?

It feels a little... empty, to me. If we do put the images there, I don't think that the image should move based off of its own width/height. That is to say that all ships should be centered at the same point, meaning that if you flip between two ships of different sizes you'd still be able to easily compare their size since their center points are the same. 

Then on top of that, perhaps have some sort of light gray border to show the edges of where the ships can show.

<details><summary>Example, using the Star Barge and Albatross images from above.</summary>

The box surrounding the image is probably off, but the idea of having ships be centered in the same spot is there.
![star barge](https://user-images.githubusercontent.com/17688683/58739523-a53e2a00-83d8-11e9-83d9-d9fd94a1951c.png)
![Albatross](https://user-images.githubusercontent.com/17688683/58739524-a5d6c080-83d8-11e9-9072-e7a88a4df2a2.png)
</details>

**Comment by LocalGod79** [comment]
would it be possible to use the tool-tip's code to pop-up a top-down on hover?
