### ISSUE TITLE
[suggestion] Cargo as separate space objects, targetable/lootable/destroyable

### ISSUE THREAD

**Issue by egilburg** [endless-sky/endless-sky#432]
Evolve commit https://github.com/endless-sky/endless-sky/commit/a8a9bf49e267e445f2166532c8f7ea1b03c50bc6 into lootable cargo containers which you could discover in space and loot (or alternatively destroy)

Possibilities:

- Discover ancient artifacts or hidden stashes, possibly after eavesdropping on conversations.
- Allow new quests to recover valuable cargo, or alternatively destroy guarded enemy supplies.
- Open up new piracy avenues - hail a ship, demand it to drop cargo, loot the cargo if it complies. Some civilan ships could automatically drop cargo if attacked, in the hope you go for the cargo and leave them alone.

**Comment by thenerdfreak** [comment]
This does have great quest implications, as well as implications for piracy. +1

**Comment by frameworld** [comment]
Sometimes I'd like to dump items that I have accidentally looted to make space for others more worthwhile :palm_tree:

Cargo will not get auto-attacked by anyone or shot if in-between because you only shoot enemy that way - cargo has no friendly/enemy status.

As a loot-able-ship-captain I would not drop all at once, maybe just a bunch here and there in the hope I get marked as "unattractive target" for not giving any loot.

**Comment by TaramaSlaughter** [comment]
Gets a thumbs up from me =)

**Comment by egilburg** [comment]
>Cargo will not get auto-attacked by anyone or shot if in-between because you only shoot enemy that way - cargo has no friendly/enemy status.

Right. But cargo left unattended could be stolen by pirates. Also, if cargo contains contraband then (once scanned) it could be shot and destroyed by Navy.

**Comment by endless-sky** [comment]
As of 0.9.1 there is "flotsam" left behind by exploding ships, which you can pick up.
