### ISSUE TITLE
Ship Class: Heavy Transport 

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#433]
the specific goal of this ship would be, as the name implies, to carry HUNDREDS of people(troops >:D) quickly and efficiently throughout the galaxy. If there was ever a planetary invasion scenario, this ship would be boss

**Comment by Wrzlprnft** [comment]
Good idea :) i would ask @tufton, he made some impressive work in the google group

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!
