### ISSUE TITLE
Another Alien Idea:

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#434]
An alien species that doesn't use spaceships... an alien species that is as BIG as a space ship!

Think "kraken of space" Giant creature, large as a Bactrian or even larger!

Would go along with another species of alien, maybe as a protector to their planet

**Comment by Wrzlprnft** [comment]
Reminds me of this:

![StarCraft2 Leviathan](http://vignette1.wikia.nocookie.net/starcraft/images/2/2a/LeviathanBattlecruiser_SC2-HotS_Art1.jpg/revision/latest?cb=20140124115132)

In code they would probably count as normal ships

**Comment by thenerdfreak** [comment]
yes, only they would have explode set to 0 and anti-disable (AND WHAT IS THAT)

**Comment by Wrzlprnft** [comment]
well i would add a special explode animation i guess... like a green-red-splash or something
there is already an anti-disable attribute in the game :)

**Comment by thenerdfreak** [comment]
I know, i was saying it would need that because it'd be weird to capture a ship like that xD
and zero explodes means it instantly dies

**Comment by Wrzlprnft** [comment]
"that ship has a real heart as a core... don't even try to loot it"
but should it instantly die? well that's something which needs to be tested

**Comment by tankhunterking** [comment]
another option off a 'spaceship' that is actually an alien, would be that they are similar to the whales of Earth, in that they produce something similar to ambergris, which is highly valued. can only be collected from boarding a disabled/dead.
And tying in to the above idea would be they are extremely rare found in the least traveled sectors, which could lead to an option for some quest lines
e.g scientists wanting to place trackers and take samples or a mad captain with out a ship hires you and your crew to help him catch one has been hunting for years (based on Moby Dick)

**Comment by thenerdfreak** [comment]
XD yes ^

**Comment by Tufton** [comment]
i think the polaris in EVN had organically grown ships.  Having an organism
as a ship doesn't really work with the idea of a human player, so even if
we did add it it would have to be alien only (strictly), which nothing is
right now

**Comment by frameworld** [comment]
Space Wales !!! :dancer: 

I don't know EVN and would like to read through the reasons why it didn't worked out.
https://en.wikipedia.org/wiki/DarkStar_One has an organic player ship exclusively and it works out.

DarkStar_One is quite similar to this game, except for it having just 1 ship.
The diversion we have in Hyper&Jump-drives, DSo has it with different ranges on jump-drives.
The interesting part is that you can find artefacts within hollow asteroids to upgrade your ship.

Perhaps it's worth a look for lets-play-videos.

**Comment by jafdy** [comment]
The risk is that if its just one ship then it players will just think that it is just a very strangely shaped ship. It would probably be better to have an alien race with territory that is known growing there own ships.

**Comment by omagasohe** [comment]
Reminds me of farscape.

**Comment by thenerdfreak** [comment]
Maybe instead of just one, every planet that this certain alien inhabits has a chance that some will come off of the planet (in a way akin to a shop taking off) and go around the planet, patrolling

**Comment by brendanjones** [comment]
> It would probably be better to have an alien race with territory that is known for growing there own ships.

Sooooo... shall we just make this easy and import the data files for the Polaris from Nova? I'd love to pit my fleet of Bactrians against a fleet of Ravens :'D

**Comment by tankhunterking** [comment]
another option keeping in line with my earlier comment would be that they are only found VERY rarely and that due to this if one is in an inhibited sector the planet will hail you the second you try to attack and warn you that they will send a defense fleet to intercept. secondly the idea of a species that grows its own ships is amazing, and that a player cant fly one with out finishing a quest line for that species, that allows you to become symbiotic with the ships .

**Comment by jafdy** [comment]
We will still need some explanation of what these strange looking ships are. Maybe in a dialog when you first land on a planet it an area where you may find them.

**Comment by thenerdfreak** [comment]
Yes, the species that the creature protects would have to tell you something about them :p

**Comment by masterpierround** [comment]
Maybe an associated "Stun Gun" weapon (Hai Ion Cannon could do something as well) that simply disables these creatures. If they existed in only a certain area of space, there could be an associated species of "whalers" that warn you not to kill any of them, and then turn hostile if you do.

**Comment by tankhunterking** [comment]
a dialog in which you learn about these creatures could be when you enter the space port a group off old pilots are talking about their past, in which one says that he saw one of these magnificent creatures, and is mocked by his fellow pilots for taking an old fairy tale a bit to seriously and says that since you don't believe me i find real proof  where you get an option to give him a ride to the systems where he saw them.
also on looks 
i would say that it would be cool if they look like massively up sized whales (larger then most ships) with hard exoskeleton like plates running along its back and sides. also to fight back they could have like parasites that live on the come off and act like missiles or shots from particle cannons.

**Comment by thenerdfreak** [comment]
I like the armored whale idea and storyline . Will sketch something like that on paint tomorrow when it isn't 23:30

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!
