### ISSUE TITLE
able to add fighter through outfit

### ISSUE THREAD

**Issue by hellminister** [endless-sky/endless-sky#4358]
**Is your feature request related to a problem? Please describe.**
There is a clear lack of carrier -especially drones- that are easily available

**Related Issue Links**
#978
#692

I know this has been discussed before but please listen me out

**Describe the solution you'd like**
I was thinking of creating outfits that would let us convert freighters (ie big cargo space) into carrier

here are the outfit stats i was thinking about : 

Fighter bay :
   cargo -130  \\ i think the biggest fighter is about 120 outfit space, some a little room to move around
  outfit -5 \\ representing the modification to the ship for the hangar doors etc.
  fighter 1 \\ how many fighter that the bay would accept 

Drone bay :
   cargo -70  \\ since drones are smaller
  outfit -5 \\ representing the modification to the ship for the hangar doors etc.
  drone 1 \\ how many drone that the bay would accept

**Comment by Zitchas** [comment]
Not a bad idea. I'd like to see more large scale outfits that change the fundamental nature of a ship, like this one.

**Comment by jafdy** [comment]
The issue that would have is that currently bays are defined by the ship definition with a placement point, this would require us to define a number of extra bays that could be used up to the maximum number of bays, and that could be a lot on some ships.

**Comment by SirStigII** [comment]
I think you would also need to classify something as a bay vs a docking point. Most (all?) the carriers in ES don't actually have a bay that houses multiple fighters. Perhaps it's due to the ships not being incredibly large, but it would make sense to have a ship that has a stereotypical fighter bay that houses multiple fighters. It has always seemed odd to me that both drones and fighters are housed on the outside of ships.

**Comment by hellminister** [comment]
if you look at the carrier, the bactrian and the mule, the fighters they have are not visible on the sprite but they do have attachment? docking? coordinates.

i know that this feature would require some modification in the code, but could simplify the definition of ships that have internal hangar versus external docking points

**Comment by Zitchas** [comment]
I think that problem could be resolved quite easily: have a default launch point built into ES so that any drones & fighters that don't correspond to a predetermined point on a ship default to the center of the ship These bays that don't correspond to pre-determined points would also be labeled as internal storage (so they aren't visible on the ship sprite) and launch underneath the ship (which eliminates the issue of why we can't see where the bay entrances are.)

**Comment by SirStigII** [comment]
As far as bay size, we could either do weapon space style bays (ie Bay can hold up to 200tons of fighters, mix and match whatever fits) or you could do specific bays per type/size of fighter.

**Comment by ChamEV** [comment]
A default bay launch point could be the underside in the center.  An additional version could convert a turret slot and use that as a docking port, though it may need some code changes.

**Comment by jafdy** [comment]
All of this would need code changes.

**Comment by hellminister** [comment]
Personnally, i prefer having outfit that gives space to a specific number of fighter or drone, going with weight or size, we could wonder why a sparrow couldnt fit in a bay that can hold 2 finch...

Ive looked at the code, unfortunetly i have no idea exactly where to put the change even with the default bay launch point (i havent coded in c++ in 20 years, being a java programmer)

**Comment by Zitchas** [comment]
While the turret and the "fighters take up space instead of bays" options sound interesting, I agree that they might cause some problems for the moment, not to mention a lot of reconfiguring of the mechanics. And adding interceptors to the list of things that can be carried in bays would block them from being flown by the player (seriously, the code stipulates that nothing that can be carried in a bay can be flown by the player - at least as I understand it).

Anyway, I would suggest that for now the most reasonable and straight forward option to implement is having bays add a fixed number of slots, and implement a default launch point.

One question to ask in regards to the outfit space requirements for the bay itself: Is this a hole in the ship that a fighter parks in, or is it a box attached to the hull that the fighter parks in? Or is it some halfway case where it sticks out of the ship but is at least partially within it?

For the former, your calculations for how big the outfit is are reasonable. Such a bay would probably take up at least that much outfit space, but it would add very little mass, since it is mostly hollowing out an area, not filling it with something.

For the second option, we could expect the bay to take up significantly less outfit space, maybe as little as a quarter of your figures, but it would add quite a bit more mass since it has to build out that bay.

The last option would be a balance between the two: Somewhat reduced outfit space requirements from what you calculated, since about half of it is sticking out of the ship, but also reasonably significant mass, since the outfit does need to build out that space and isn't simply hollowing things out.

**Comment by comnom** [comment]
>have a default launch point built into ES so that any drones & fighters that don't correspond to a predetermined point on a ship default to the center of the ship

>A default bay launch point could be the underside in the center.

There isn't any point that can be a default for all ships. See: Model 128, Model 256, and Model 512 for why the center default won't work.

The reason this was turned down in the past still stands. It's an intentional design decision that hulls be as unique as possible, and fixed numbers of fighters/drones are one of the stats that achieves that.

As for the "problem" of not enough carriers, the simplest solution is just to make more carriers ;)

**Comment by Zitchas** [comment]
It might be easier to specify that certain ships have a "no bay" attribute that blocks bays from being added.

As far as adding new ships goes, that also runs up against the design decision that "No new ships should be added to human space." There's a caveat that new ships will be considered if they're really good quality and have a specific (preferably mission) purpose, but the default answer is "no".

As for the uniqueness of ships, that gives rise to an opportunity to three problems with one fix: Fighters being useless, ship uniqueness, and usability of fighters.

Firstly, let's reduce the cost of fighters by a significant margin, enough so that people using them are going to be bankrupted by the possibility of losing several fighters per carrier type ship per engagement. That might not make them more useful outright, but it does make it much less painful to use them.

Secondly, let's up the quantity of fighters that dedicated carriers can carry. The Republic Carrier itself, as being THE predominant carrier in human space, should be able to carry something more along the lines of 8 fighters and a dozen drones. It may have to be a bit rarer as a result, but it'll be a lot more impressive disgorging a wing of fighters at something than it is currently. 

Along the same lines, the Type C Freighter, Nest, Aerie, and Bactrian should all get a few additional built in bays of the appropriate type. All of these ships include being a carrier as an essential element of their purpose. (In the Bactrian's case, I'd suggest this as part of nerfing their outright combat abilities. Extra fighter bays makes a lot more sense for a city ship than do cannons, for instance)

If all the "carrier" type ships carried twice-ish as many fighters and/or drones, that would mean these ships would much closer to being able to deploy enough fighters/drones to swarm targets, and I think it is generally agreed that swarms are really about the only time fighters are currently useful. 

Thirdly, add in these bays. Preferably, a variety of them. Chances are, most people will only be able to fit  one or two on a ship. In other words, enough to provide covering distractions while they escape, or to provide supporting fire if they're fighting. Almost certainly not enough to form an effective swarm. 

The net impact of these three changes will be:
- Increase customizeability for people to adjust their own loadout (which is a core feature of this game)
- Increase the value, power, and uniqueness of the carrier ships
- Increase the ability of fighters to have a significant impact on battle.

And it will do all that without requiring the addition of new ships to an area of space that has already been deemed effectively off-limits to new ships in general.

**Comment by SirStigII** [comment]
Kestrel with a dagger bay ❤️

**Comment by comnom** [comment]
I wasn't aware that we were only talking about human space. 

I really don't follow the logic going on here. We have a problem (which I don't even think is a problem), that is: not enough carriers. It makes no sense to me that we would fundamentally alter design decisions and go wildly impacting balance when you can just solve it by adding more carriers.

**Comment by Zitchas** [comment]
That would be awesome and appropriate. The original Kestrel had bays for a pair of lightnings, which were top end civilian fighters in that game.

Sorry for the confusion. My impression from the steam forums and the like is that 75% of players spend close to 90% of their gametime in human space. Likewise, adding, say, a Wanderer carrier does nothing to change the dynamics of fighter combat, utility, and carrier balance in human space where fighters are so prevalent. Especially during the FW campaign before the pilot knows about jump drives or has access to them. Between those two things, I'm inclined to try to fix the feel and utility of fighters in human space before getting into alien territory. If a player learns to dislike fighters for being useless and discount carriers as "just another warship" in human space, they are unlikely to change their mind later on. First impressions make a big impact, after all.

I'm not sure it is a design decision, actually. Hull capacity and shield capacity have clear statements about why they aren't in the game. Bays, I haven't seen anything on, so to me they fall into the realm of "development hasn't reached them yet." But I'm comparatively new here, so it is possible I missed something. And, it should be noted, we are still pre 1.0.0. The game clearly has a fair bit of development to go before it reaches that, although progress is happening.

(I'd also like to point out that the EV series *did* have bays that were available as general outfits, and at about half (or less) the sizes proposed here. I don't think they did anything to making carrier ships feel any less important. They did make it so that we could build our own personal versions of the class C freighter, though. And that was a lot of fun. And at the end of the day, isn't fun what we are aiming for here?)

**Comment by comnom** [comment]
>I'm not sure it is a design decision, actually.

https://github.com/endless-sky/endless-sky/issues/978#issuecomment-212653239

>I'm inclined to try to fix the feel and utility of fighters in human space before getting into alien territory. 

That's fair. I still hold the opinion that fighters/drones are only useful with missiles, so I agree that they need work. But making any ship with the space for it a carrier doesn't do that. There's plenty of fighter balance threads that are more appropriate for ideas on that subject.

**Comment by Amazinite** [comment]
>Related Issue Links
>#978
>#692
>I know this has been discussed before but please listen me out

A duplicate is a duplicate is a duplicate.

Referencing this and #4334, I don't see an issue with adding mechanics like this solely for the purpose of being used by plugins without using them in vanilla, but don't expect content like that to be focused on any time soon given that it's time spent on something that isn't enhancing the vanilla experience.

**Comment by Zitchas** [comment]
I don't know about implementation in human space, but if the mechanics for this are implemented, I fully intended to bring forward at least one fighter bay and one drone bay outfit for the Remnant as possible inclusion in vanilla content. Whether or not it gets merged or we can agree on stats or whatever can wait until we have the mechanics and the graphics to do it. I just want to put it out there that I would like to at least take a shot at having some such outfits available in vanilla Remnant space. In short: Potential for this mechanic to enhance the vanilla experience.

**Comment by ChamEV** [comment]
To make fighters really work in this game, there needs to be some form of fighter/escort replacement, and move the game away from constant save scumming.  I think the best version for ES would be insurance and repurchase when at a shipyard.  Pay 0.1% of value per day per ship insurance is activated on, when ship is destroyed, return to a shipyard and pay 25%, 50% or 100% of it's total cost to restore it (all numbers subject to balance).  Since credits are already a magical sort of player tool, as aliens who've never met use the same currency.

The only other version of replacement I've seen is regenerating fighters, which at least with the current races doesn't make much sense.  However eventually it should be implemented as something story writers may use (biologically regenerating ships) and to match the behavior of EV if that's ever allowed to be ported and preserved,

Secondly, fighters die too easily.  Turrets were adjusted to be more slow to make them live longer, but the number 1 killer of fighters is simply large ships exploding.  Given the damage model, it does not really make sense for small ships to take as much damage as large ships.  A hit anywhere on a large ship does the exact same damage as on the small ship, which makes perfect sense with shields, on the hull, less so, but that's how it is and it won't change.  So, big explosions send out lots of debris pieces, and the bigger ship will get hit by more of them than a smaller ship, so bigger ships should take more damage than the smaller ships from ship explosions.

Zitchas wrote:
> It might be easier to specify that certain ships have a "no bay" attribute that blocks bays from being added.

Again with code changes, maybe the best option is ship specific upgrade/alteration options that are apart of the ship definition.  Call them conversions, one conversion would be a carrier conversion.  For the kestrel it would take some cargo/outfit space and give you 2 fighter docking ports, and would tell the game where they went.

This would allow you to have 1 outfit associated with "Carrier conversion", and any ship the story authors feel would qualify would have a conversion section in the ship definition.  New types of conversions could be added without further code changes.

**Comment by Amazinite** [comment]
Ref: #4034
