### ISSUE TITLE
In-game music

### ISSUE THREAD

**Issue by apathy-dude** [endless-sky/endless-sky#44]
Not sure if you're interested, but there's someone on reddit offering free game music: http://www.reddit.com/r/gamedev/comments/39q6vi/hey_gamedevs_im_an_awardwinning_composer_for_tv/

**Comment by endless-sky** [comment]
That does sound like a great offer! But right now in-game music seems like a low priority to me - it'd have to be *really* high quality music in order to convince the player to not just disable it and provide their own music via an MP3 player in the background instead. :)

The only thing that would make in-game music better than that would be if it could somehow respond to what is going on in the game (e.g. play more exciting music when the player is under attack, or play different themes for different regions of space). That's something I've thought about doing in the long term (i.e. for an eventual "1.0.0" release) but right now I'm really focused on trying to make a "0.8.0" stable release in the next month or so.
