### ISSUE TITLE
Shield hardness / piercing mitigation proposal and request for comment (RFC), v0.9.11+

### ISSUE THREAD

**Issue by ChamEV** [endless-sky/endless-sky#4406]
## Shield Hardness ##
**Shield hardness** directly counteracts piercing and disruption.  If a ship has a shield hardness of 1.15, then korath piercers with 0.2 piercing will instead have 5% of damage skip through shields.  1.15 - 0.2 = .05  Typical values of shield hardness would be between 0 and 2, with 1 being default.

Two outfit attributes would need to be associated with this.  (Names need work.)
**Shield hardness increase.** how much this outfit increases the ship's shield hardness.
**Shield hardness cap.** the maximum this outfit can increase the ship's shield hardness.

Piercing is currently capped to between [0,1], uncapping this and shield hardness would enable specialized encounters where a very special gun with 1000 piercing is needed to kill a very special baddy with 1 million shields and regen and 999 shield hardness.  Hopefully if someone does this, they have a good story for it.

In vanilla, we might see some future or existing alien ships like Quarg, Drak, pug, with shield hardness values between 1.2 and 2.  Keep in mind shield hardness does not mitigate regular shield damage in any way, just prevents skipping it.

An example with disruption.  First recall that disruption makes any weapon damage pierce.

> `"disruption damage"`: works like ionization, adding a "shield disruption" effect that fades by 1% each frame. When disrupted, your shields only block 1 / (1 + .01 * disruption) of weapon damage, and the rest pierces through your shields and damages your hull. For example, if a ship has accumulated 10 disruption, about 9% of damage will leak through to the hull. (v. 0.9.0) 

With shield hardness, a ship will need to acquire enough disruption before any damage can pierce.  While the separate existing stat disruption resistance still removes disruption faster.

Required D disruption to achieve B blocking with H hardness.  Piercing is 1 - B.
D = 100*(H/B - 1)

Effective Piercing | Required Disrution 1.2 hardness | Required Disrution 1.0 hardness (default)
-------|----------|------------
0% | 20 | 0
10% | 33.3 | 11.11
20%|50 | 25
40%|100 | 66.66
50%|140 | 100
75%| 380 | 300
99%|11900 |9900

---

## Shield and Hull generation after delay ##
Moved to: https://github.com/endless-sky/endless-sky/issues/4408

## Shield and Hull Recharge multiplier ##
Moved to https://github.com/endless-sky/endless-sky/issues/4407

**Comment by ghoulavenger** [comment]
My take on shield hardness is that enemies are not likely to develop shield hardness unless faced by weapons that can disrupt or pierce shields. So, that leaves mostly the Korath and Quarg that might develop it at this point. Perhaps I could see it as part of the last Wanderer chain as an innovation to deal with the drone fleet, although deployed too late to make a difference. So I'm not against it, but it should not be a common thing in any stretch of the imagination. At least not with the current campaigns.

On the shield regeneration front, it kind of feels awkward to make shield generators weaker as they stack, only as individual units. If you wanted to make shield generators operate like this globally, I could see it something akin to the change to outfit expansions -- penalizing people for stacking shields. But that begs the question, do people that stack shields need to be penalized -- that kind of pushes people away from customization that the outfit system allows. I guess I'm on the fence about this one, because I do see the practical application with small ships specifically, although a small generator that fits the current balance scheme might be the best approach (like a wanderer shield thats scaled down specifically for fighters/drones).

**Comment by ChamEV** [comment]
>My take on shield hardness is that enemies are not likely to develop shield hardness unless faced by weapons that can disrupt or pierce shields. So, that leaves mostly the Korath and Quarg that might develop it at this point. Perhaps I could see it as part of the last Wanderer chain as an innovation to deal with the drone fleet, although deployed too late to make a difference. So I'm not against it, but it should not be a common thing in any stretch of the imagination. At least not with the current campaigns.

My goal is to create greater diversity in the things story tellers and designers can do.  So coming up with story reasons isn't something I'm really trying to do, that's for others, and maybe the vanilla game won't even need it, but that's not to say plug in developers can't use them either.

> that kind of pushes people away from customization that the outfit system allows.

This only happens if imbalanced outfits are introduced which will likely not happen in vanilla.  Simply having the option there for designers just gives them another tool to use.

**Comment by Amazinite** [comment]
Re: "shield hardness." Resistance attributes are already a thing. https://github.com/endless-sky/endless-sky/commit/2bf7c0f089d72aef14a301bbdd09b9639f17c1e0 https://github.com/endless-sky/endless-sky/commit/ab5fd68e635da11550082f70e12f60345099eda5 How about instead of having only this one type of "shield hardness" that basically rolls two types of resistance in one but only when the shield is up, resistance attributes be expanded to 1) include piercing (and heat) and 2) be able to be specified for only the shields or the hull.

**Comment by ChamEV** [comment]
> Resistance attributes are already a thing.

I was trying to demonstrate that shield hardness would have little effect on the existing disruption resistance attribute.  Hardness is primarily a counterweight to piercing.  If it works on disruption as well, it's effect would be very small due to how disruption works.  But if that's unwanted, disruption could easily be entirely separate.

> 2719 (comment)

Thanks for this thread.  It seems the only mitigation stat not in the game currently is for heat damage and piercing.

For reference this is how disruption resistance works and is described currently. https://github.com/endless-sky/endless-sky/blob/0415035cecab6228ee765ecad0c1581d6ab5c2b4/data/tooltips.txt#L71-L72

The thread also suggests other methods of piercing mitigation which could be implemented.  
* On a scale from 0 to 100% with 40% giving piercing 60% effectiveness, and 100% completely ignoring any piercing.

This is almost identical to what I suggested, but with a key difference.  Any piercing weapon can always do some hull damage if the target does not have 100% resistance.  If you think of hardness like armor thickness, a small gun won't penetrate heavy armor, but a big gun will.
* A piercing buffer, as it takes damage that is piercing, the buffer absorbs it until it's gone.

This is basically how heat and ion damage already work, there is a buffer of excess heat or extra energy your ship has, once it's depleted bad things happen.  This works well for these effects as it's logical, not so much for piercing as piercing modifies where damage is received, but does not actually do damage.

All of these have the damage that would normally pierce affect the shields instead.

**Comment by tehhowch** [comment]
This should be split into multiple issues (piercing resistance, regen delay, regen effectiveness).

**Comment by Zitchas** [comment]
I think piercing resistance would be a useful attribute to have.

As for usage in game, it might be interesting to have each of the T3+ races (Pug, Drak, Quarg have a different resistance (Perhaps Pug against Piercing, Quarg against disruption, Drak against ionization) to differentiate the three from each other and make them stand out a bit). Other races (perhaps the Wanderers) might develop it after significant exposure.

**Comment by Amazinite** [comment]
Although the implementation isn't the same, #4519 does seek to add a form of piercing mitigation. I can see an argument for adding this though, as it would effectively become piercing's resistance attribute, as it has the same "you must be this tall to ride" effect. (i.e. piercing must reach a certain point before taking effect, similar to shield regen vs shield damage, ion resistance vs ion damage, etc.)

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/6359a2c7ec73c6d169618d1bbd7a8db24ea93871
