### ISSUE TITLE
Shield and Hull generation after a delay proposal and RFC v0.9.11+

### ISSUE THREAD

**Issue by ChamEV** [endless-sky/endless-sky#4408]
## Shield and Hull generation after delay ##
**Shield recharge delay after taking shield damage.**
**Shield recharge delay after shields go down.**
**Hull repair delay after hull damage.**

Minimum and default: 0 (all values in frames)
Outfits can alter each directly.  positive value increases delay, negative decreases delay.  Stacks additively.

Allows for more diverse ship and outfit design.

**Comment by SolraBizna** [comment]
I was just thinking about this the other day. This would, IMO, provide a really interesting way to break up the current strata of shield system desirability.

I would say that the delays should be an attribute of individual generators, so that different generators might kick in at different times. For example, if basic shield generators worked on zero delay, but shield regenerators had a three-second delay, then a ship that had one of each would have a low level of constant recharge that sharply increased after three seconds of not being hit.

**Comment by Amazinite** [comment]
Do you have shorter names for these? :)

**Comment by SolraBizna** [comment]
Could even be `"repair delay" x y` to allow delayed recovery from being disabled, like EVN's repair bots...

**Comment by Amazinite** [comment]
Inb4 a super strong shield generator with a shield delay of 1 so only continuous damage will actually do anything.

**Comment by SolraBizna** [comment]
You mean like the "Systems Core (Large)" we already have? :)

**Comment by Amazinite** [comment]
Shield generation and hull repair don't have a delay right now. They'll still repair even when taking damage. That's why you can't take a beam laser to an Archon and do any damage; you first have to get over the 4000 shield generation/second threshold. 
A shield delay of 1 (frame) would mean that if damage happens on that frame, generation doesn't begin until the next frame, but if on the next frame damage happens again (such as with a laser), then the generation gets delayed again.

**Comment by SolraBizna** [comment]
Aha. My mental simulation had an off-by-one.
