### ISSUE TITLE
Show the orange "available job" tag when active mission list is large

### ISSUE THREAD

**Issue by alextd** [endless-sky/endless-sky#4436]
**Is your feature request related to a problem? Please describe.**
There are a max of 12 mission tags per system on the map.

When you have 12+ active missions for a system, only 12 tags are shown.

When I am looking for new missions, I would prefer to add new missions in that system.

But that system doesn't show any orange tags because the 12/12 tags are blue and I don't see a mission to start, but there is one in the list to do.

**Describe the solution you'd like**
Simply show the available mission tags first, taking preference over active missions.

**Describe alternatives you've considered**
One blue tag + number of active missions, one orange tab + number of available missions. More consideration for blinking tags and dark blue tags needed for that.

**Additional context**
[Example image](https://user-images.githubusercontent.com/101399/61390571-e2b72380-a86f-11e9-8040-60f9e162addc.png)

^Note, the available mission is not shown in the map as an orange tag.

**Comment by petervdmeer** [comment]
Attached is a savegame that can be used for testing this feature (it has a destination with more than 12 jobs, and a spaceport job that also goes to this destination):
[Busy Tester.txt](https://github.com/endless-sky/endless-sky/files/8403382/Busy.Tester.txt)

Note, the player/tester needs to buy more shuttles and/or starbarges in order to be able to accept all jobs to the crowded destination.
