### ISSUE TITLE
More than possible outfit space

### ISSUE THREAD

**Issue by tmoftdead** [endless-sky/endless-sky#4445]
![21](https://user-images.githubusercontent.com/52049166/61968936-f0904580-afe1-11e9-8981-3ce576d13bcf.PNG)
[Taylor Stuart.txt](https://github.com/endless-sky/endless-sky/files/3436780/Taylor.Stuart.txt)
As you see, the ship "Jump Tank" has made 630/510, therefore having more than possible outfit space
Is this left in intentionally or is it a not?

**Comment by jafdy** [comment]
The "out of" section refers to the base amount for that hull, so when you install outfit expansions you will reduce the used outfit space. This is because the game has normal outfits reduce outfit space while outfit expansions increase it, but there is currently no way of tracking the maximum possible outfit space given your number of outfit expansions.

**Comment by Amazinite** [comment]
Given that cargo updates with adding an outfits expansion, it does seem like it would be sensible for the max outfit space number to update as well.
