### ISSUE TITLE
Killing oxyrynchus?

### ISSUE THREAD

**Issue by tmoftdead** [endless-sky/endless-sky#4449]
While playing the new deep missions, I realized that the government of the oxyrynchus is independent(which doesn't exist pre fw). It is a fast marauder ship so some people may kill it to get rid of it. This may cause them trouble in the fw campaign after the government Independent gets the same government. So the player can't go to the planet and land.
The same thing happens in project hawking where other independent marauder ships follow you  
Changing the govenment of them to " Independent " could be a solution.
A warning to the player might be a solution.
Leaving it alone may also be a good way to go assuming the player can already demand tribute from both the planet and the station at the stage where they can kill a marauder.

**Comment by Darcman99** [comment]
Something similar to the `Indigenous` government might work, how there is no lasting penalty for the players actions. Since they truly are independent I don't think they should 'have each others backs' when they likely wouldn't interact with each other.

**Comment by Amazinite** [comment]
I recall talk of the nature of the independent government being mentioned elsewhere; even though there are various planets that may become independent that are far away from each other, they should still care if you attack any given independent planet because attacking one makes it likely in their eyes that you'll attack another. 
In this situation, Oxyrynchus is basically just a merchant, and the player killing them is an unprovoked act of aggression that has consequences to it. The use of the independent government just allows the player to destroy them without making anyone around them angry.

**Comment by tmoftdead** [comment]
I remember he worked with the black market(he is no good samaritan) .  That's why I proposed " Independent " to be included instead of "Independent" in that mission as well as the ones that follow you in project hawking(which cause an earthquake and destroying of material in interest of the deep).

**Comment by Amazinite** [comment]
The ships in Project Hawking being there or not has no bearing on the outcome, at least not right now, so there's no point in making them " Independent ".
