### ISSUE TITLE
Optimal range attribute that overrides calculated range

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4478]
**Is your feature request related to a problem? Please describe.**
As noted by #1826, the current range calculation isn't always perfect. It doesn't take into account drag, acceleration, random lifetime, and random velocity. As I noted as well, the range calculation ignores the inaccuracy of the weapon being used, meaning that the range that the weapon will be fired at by the AI may be too far for the weapon to reliably hit. In this way, the current way that range is calculated makes the creation of more novel weaponry difficult.

**Related Issue Links**
#1826 The issue where I first brought this idea up (but the issue itself was not asking for this change).
#1894 A PR that attempted to add this mechanic, but also attempted to change how the current range is calculated. I suggest that the current range calculations remain the same, as the optimal range attribute allows the creator to set whatever range they want.

**Describe the solution you'd like**
Suggested that we have an "optimal range" attribute that overrides the calculated range of a weapon. This optimal range is what would be used by the AI and by auto-fire when determining when to fire the weapon. In game, this optimal range would simply show where the current range stat is, as the player does not need to know if the range of the weapon is being overrided. 

**Describe alternatives you've considered**
As mentioned in #1826, it's somewhat possible to manually override the range calculation by using "fake" submunitions, but, akin to the creation of various timer ships mentioned in #4475, this is a rather messy solution that requires the creation of new "fake" submunitions with every new weapon.
The other solution would be to make the range calculation be more accurate by taking drag, acceleration, random velocity and lifetime, and inaccuracy into account, but as highlighted in #1894, the inaccuracy of the current calculation has its uses and is used in game already. The creation of an optimal range attribute would allow the creation of weapons that require a more accurate range number while not ruining the existing weapons that benefit from the range calculation being "wrong."

**Comment by Amazinite** [comment]
Also, minimum range attribute, anyone?

**Comment by Bladewood** [comment]
As an example, this is the kind of weapon I'm looking for:
![prismaticlaser](https://user-images.githubusercontent.com/16506683/63027142-6584cb80-be7a-11e9-9cf9-ee70cc84ddbe.png)
I've tried to implement this in the current game many times. However, no amount of submunition trickery will make this weapon work without it horribly breaking in some way. (With projectile weapons it can be much easier to disguise the effect, but the uniquely "instantaneous" quirks of beam weapons are insurmountable.)
One effect of an unsuccessful implementation is that the AI doesn't actually know when to fire the beam (as it is displayed as having "0 range" in-game); the other part is that the weapon doesn't aim toward the nose of the ship like most guns, instead just firing straight forward.

As an addition, I'd like it to be possible to specify not only `"optimal range"` (invisible range that the combat AI usually performs at), but also the true maximum `range` (displayed range that the auto-fire AI will fire at), in part because it'll allow the weapon to correctly arc inward.

**Comment by Amazinite** [comment]
It might be the case that we also need some sort of "fake velocity" to go alongside the optimal range so that the AI knows by how much to lead the target.

**Comment by jafdy** [comment]
So this is a request to be able to tell the AI how to think of the weapon even if that isn't how the weapon actually works.

**Comment by Amazinite** [comment]
In effect, yes.

**Comment by petervdmeer** [comment]
Did you also consider a fix to the range calculation itself? So let the system automatically calculate an optimal range based on drag, acceleration, random lifetime, and random velocity?

I don't mind a manual override if it really is required, but if the calculation is wrong, then I prefer fixing the calculation itself if possible.

**Comment by Amazinite** [comment]
That's what #1894 tried to do, but as mentioned there, the quirks of the current range calculation are actually useful for certain weapons. So even if the current calculation is made more accurate, we'd still need a manual override for those weapons that currently exist that depend on the current calculation being "wrong."

**Comment by Amazinite** [comment]
I'd say that the range calculation should be changed to take into account the velocity of the submunitions (as right now it assumes that the submunitions don't add or subtract any velocity and it only looks at submunition lifetime), but random velocity/lifetime and drag/acceleration should be left out still, with the optimal range attribute catching the slack.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/4ccfbd91910bd46e2de95f34ceb36b517eaf59cd
