### ISSUE TITLE
Republic still fines you after you've defected

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#45]
As a Free Worlds rebel, when I visit Republic space during a cease-fire, probes and gunboats still fine me for having an unlicensed ship or illegal nerve gas.  It seems to me that if I'm a rebel, I should not not willingly surrender my money.

**Comment by endless-sky** [comment]
Right now the player's "reputation" with each government is just a single value: positive means "law-abiding citizen" and negative means "attack on sight." The trouble with that, of course, is that it can't differentiate between a player under a ceasefire and a player at peace with the Republic. (The ceasefire is implemented by adding a large value to your reputation, then subtracting it a few days later.)

I think the best solution for this is to just disable fines for owning an unlicensed ship, so I've done that in commit 5c49b73. The ship licenses will still limit what you can buy, but not what you can capture. The other option would be to add some way to distinguish a ceasefire from peace, and disable fines during a ceasefire, but then you'd start being hit with those fines the moment the Free Worlds work out a permanent peace agreement.

Do the Free Worlds *not* fine you for using nerve gas? Because if so, that's a bug - that outfit ought to be illegal everywhere but on the Pirate worlds (although, most worlds in Free space will only rarely search your ship to check for illegal stuff).

**Comment by johndh** [comment]
I've been fined on Free Worlds for having nerve gas.  It's not as common, since they don't have probes and gunboats scanning me all the time, but I've been fined a few times when landing.

**Comment by endless-sky** [comment]
This issue has been addressed by making it so that ship licenses only control what you can buy, and do not cause you to be fined for an unlicensed ship. Those fines were just an annoyance and don't really add much to the game play (unlike the fines for illegal cargo / outfits, which add the interesting dimension of needing to avoid patrols and land on less secure planets when carrying illegal cargo).

**Comment by speeder** [comment]
I have a suggestion for this: instead of illegal ships being fined, they should attract more scanners, like the game Starsector when you shield your smuggling cargo (in Starsector patrollers may randomly scan you, if you install a special cargo hold to smuggle cargo, although the chance of detection of illegal cargo decrease, the amount of times they scan you increase, because your modified ship is suspicious, but they can't fine you if they can't prove you are an actual criminal)
