### ISSUE TITLE
Hails for alien governments

### ISSUE THREAD

**Issue by Janaszar** [endless-sky/endless-sky#4549]
**Is your feature request related to a problem? Please describe.**
Alien governments don't always have hails defined, resulting in them using the default human hails.  See: https://github.com/endless-sky/endless-sky/blob/c80111f5011b45d38468384873ee2b00bf3a0780/data/governments.txt

**Related Issue Links**
Has been discussed previously ( https://github.com/endless-sky/endless-sky/issues/2526 ) but I haven't seen anything comprehensive developed.

**Describe the solution you'd like**
The insertion of a default "unknown alien hail" for all alien governments in Governments.txt , or part of governments.cpp around line 124 ( https://github.com/endless-sky/endless-sky/blob/ffd15a7453c7cc48b5c70ed7a8bbd3beb4f7e1cb/source/Government.cpp#L124-L128 ), which will act as a catchall for these cases.  The hails themselves should be something generic and not specific to any alien group, such as "your communicator overheats while trying to figure out the connection protocols", or "you hear something, but can't tell if it's an alien language, random noise, or some opera that was transmitted into space ages ago"

**Describe alternatives you've considered**
Custom hails for each government.  Takes a lot of extra work, but would be nice to see.

**Comment by Amazinite** [comment]
I'd think it more sensible to simply create hostile disabled hails for alien factions that can communicate with the player whenever they're added. When #2526 was posted, changing the hostile disabled hails of a government wasn't possible, so now there's really no excuse to have a generic set of hails. Since I think that the Heliarch are the only alien faction that could use hostile disabled hails right now, it seems to me that any work would be better put toward simply giving them their own hostile disabled hails after the 2+ years that it's been since #2526 was posted.

**Comment by tehhowch** [comment]
How should the game know which governments are alien and which are human?

**Comment by Pointedstick** [comment]
Implement now, thanks a lot @Amazinite. I'll add some more later.
