### ISSUE TITLE
When accepting a job, always present the next acceptable job on that planet if any are available

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#455]
It's good to batch up jobs to the same planet. Right now, when you accept a job, the map sometimes jumps to a job on a different planet. I'd prefer if it always cycled to the next acceptable job on the currently-selected planet, if any are available. It *sometimes* does this right now, but I have been unable to figure out the logic behind when it doesn't.

**Comment by johndh** [comment]
This is something I'd noticed and been mildly bothered by.  It seems to just go down the list in alphabetical order.  Maybe they should be grouped geographically instead.

**Comment by brick96** [comment]
Agreed I also so think that there should be a different pointer for rush jobs, maybe flashing orange?

**Comment by anonybosch** [comment]
@Pointedstick The jobs pay you credits. All the jobs ask for in return is that you pay attention.
@johndh The missions list is not in alphabetical order. It's completely random.
@brick96 There is already a color for rush jobs - flashing blue, and rapidly-flashing blue for jobs about to expire.

**Comment by brick96** [comment]
@anonybosch flashing blue is for taken jobs but available rush missions are just orange like every other mission.

**Comment by johndh** [comment]
@anonybosch It seems you're right.  I looked at a job board to verify, and at the time they were in alphabetical order, and for the most part they normally are -- bulk delivery, delivery, escort, large rush, passenger, rush, transport... There are some oddballs, though, like colonists coming between delivery and escort.

**Comment by frameworld** [comment]
I did many times accept a job on a different planet because it jumped from one planet to a different one even tough I just accepted 1/2 jobs available for that one.

I like the alphabetical sorting, but more I would like a sorting of categories: cargo, passengers and rush-missions (later bounty-missions as a category).

However, it should switch to another job on the same planet before jumping to the next on another.
Internally (rather than visually) sort by categorical order of first job on a planet

**Comment by anonybosch** [comment]
I suppose it all depends on how you play the game. I plot routes that maximize returns by looking at the map, and if there are acceptable jobs en route, I take them. I don't read the list and decide, "Oh, here's a juicy one. I'll take it." only to realize afterwards it's all the way across the galaxy.

If I see multiple flags on a system, I click on them in turn to see if I want them. If I've accepted one and click on it again there's an "Abort?" message. So, how much more hand-holding does the player need?

**Comment by frameworld** [comment]
If you abort a mission now because it's not on your way, does it limit you later in what missions are offered?

There are 2 ways to accept good jobs:
* Accept a juicy one and plan your other tasks around it.
* Plan your tasks and accept jobs along the way.

It also depends a bit on whether a mission requires cargo or bunk space. You have infinite chances with commodities, but only limited with peoples.

**Comment by brick96** [comment]
I dont think there is any punishment for aborting but you did forget  anther way to accept jobs
Take all of them then plan a route

**Comment by frameworld** [comment]
> Take all of them then plan a route

This is inefficient. While executing 4 missions your cargo room is blocked by another 8-10 and can not be used to trade commodities.
After you finished your 4 missions, 500cr for each ton are missing, while missions only give around 1000 per ton when completed (which you haven't for 8-10).

**Comment by endless-sky** [comment]
The original issue is fixed in commit c80bbc0, although I widened the criteria to include any job that has the same system as a destination (even if it is not the same planet).

**Comment by endless-sky** [comment]
And, in commit 2c3104c I changed it so that if there are jobs with the exact same destination planet as well as the same system, it will always select one of those.

**Comment by Pointedstick** [comment]
Excellent!

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
