### ISSUE TITLE
There Might Be Riots 2 has unneeded depends on Deep Archaelogy 5

### ISSUE THREAD

**Issue by anon119** [endless-sky/endless-sky#4559]
In 0.9.9 (and unchanged in the 0.9.10 data files, now that I see the release recently happened), the mission:
"There Might Be Riots part 2"

Has this condition on "to offer":
has "Deep Archaeology 5: done"

in transport missions.txt.

I cannot work out why that condition exists.  If the player declines the Deep Archaelogy mission line, the entire set of There Might Be Riots missions is also blocked after the first mission.  But having worked through all the mission files, I cannot see why the Deep Archaelogy missions have anything at all to do with the There Might Be Riots missions.  There is no other cross-dependency with Deep missions that requires the Deep Archaelogy to have been completed.  And given the new Deep missions leading to the Bactrian license, a player could reasonably be expected to decline Deep Archaelogy rather than risk offending the Deep (although I realize that in reality it does not matter, the story text strongly suggests it might).

**Comment by Amazinite** [comment]
Deep Archaeology is required to finish TMBR for the sake of narrative flow.

TMBR leads into the Sad Archie mission, which leads into Rim Archaeology. Rim Archaeology requires that Deep Archaeology be done since it involves Foster from Deep Archaeology. If it wasn't required that Deep Archaeology be done before finishing the TMBR missions, then the player might end up traveling to Ildaria after finishing TMBR without being able to contact Foster about the Archon. At that point the narrative would break down, as the player would need to complete Deep Archaeology first, then suddenly they'd be told to meet Foster again about the Archon that they interacted with before ever meeting Foster.

Changes could be done to make TMBR not have to require Deep Archaeology and still maintain a good narrative flow for Rim Archaeology, but it would require some work.

**Comment by anon119** [comment]
Okay, I see that point.  I propose two possible partial solutions that do not require rewriting story:
1. Block on Deep Archaelogy on TMBR.  There is no reason to block the other story line prior to that.
2. Make Deep Archaelogy 1 repeat offer, so that the player has a clue that maybe it needs to be done for some purpose.  This would still lead to potential issues if Deep Archaelogy is declined midway.

But honestly I do not see it as a big deal even if the two Foster mission sets are back-to-back (which would probably require solution 2 above anyway, because chances are someone declined the first long ago by the time TMBR comes up).  There are numerous other slightly disjointed bits like that due to the overall complexity of the number of stories happening, and there is no way to practically resolve all of them.

**Comment by jafdy** [comment]
It is not vital for every mission to be done, eventually we should have enough things that most people won't see all of them even if they aren't mutually exclusive.
