### ISSUE TITLE
Phrase generation algorithm favors some results over others

### ISSUE THREAD

**Issue by Thunderforge** [endless-sky/endless-sky#4570]
## Background

A phrase in Endless Sky is a combination of phrases and words. For instance consider the following set of phrases:

```
phrase "civilian name"
	phrase
		"male names"
		"female names"
	word
		" the Great"

phrase "male names"
	word
		"Alexander"
		"Bob"

phrase "female names"
	word
		"Alice"
		"Beatrice"
		"Charlotte"
		"Denise"
```

Thus the phrase "civilian name" will generate `Alexander the Great`, `Bob the Great`, `Alice the Great`, etc.

The [algorithm to generate certain phrases](https://github.com/endless-sky/endless-sky/blob/94346d8905ec516b9a5fad2683f9ca0e5ab5f11f/source/Phrase.cpp#L68) works like this:

1. Take an input phrase (which will contain subsequent phrases or words)
1. Create a new string `result`
1. For each phrase or word within the phrase:
    - If it's a phrase, pick a random value, go to 1. with that phrase value as input, and append the result returned to `result`
    - If it's a word, pick a random value and append it to `result`
1. Return `result`

## Problem

The problem is that by having each step be a discrete random event, the outcomes are uneven. Consider that in the above example, there is a 1/2 chance for either "male names" or "female names" to be selected. Also, there is a 1/2 change for either "Alexander" or "Bob" to be selected. But there is a 1/4 chance for any of "Alice", "Beatrice", "Charlotte", or "Denise" to be selected. Thus the odds of a particular name to be chosen would be:

- Alexander the Great: 1/2 * 1/2 = 1/4
- Bob the Great: 1/2 * 1/2 = 1/4
- Alice the Great: 1/2 * 1/4 = 1/8
- Beatrice the Great: 1/2 * 1/4 = 1/8
- Charlotte the Great: 1/2 * 1/4 = 1/8
- Denise the Great: 1/2 * 1/4 = 1/8

Or to put it another way, if you parsed the phrase "civilian" eight times, the expected probability outcome would be some combination of:

- Alexander the Great
- Alexander the Great
- Bob the Great
- Bob the Great
- Alice the Great
- Beatrice the Great
- Charlotte the Great
- Denise the Great

Thus `Alexander the Great` and `Bob the Great` appear more often than any other names.

This is especially relevant with [names](https://github.com/endless-sky/endless-sky/blob/master/data/names.txt) and [hails](https://github.com/endless-sky/endless-sky/blob/master/data/hails.txt). Thus with [this phrase](https://github.com/endless-sky/endless-sky/blob/31fe88b980a1ccef243190ef4f4cbe70bcdb412f/data/names.txt#L3314) for generating Pirate ship names, "Fortress of Doom" (with the first word selected from 26 "pirate nouns that work after bad outcomes") is more likely to be chosen than "Spectre of Doom" (with the first word selected from 116 "pirate nouns"). Anecdotally, I've seen this happen in-game with some ship names being repeated, despite such a wide range to choose from.

## Desired Outcome

I would like to see the algorithm changed such that all possible outcomes are equally likely to appear. So in the above example, there is a 1/6 chance for each of the following to appear:

- Alexander the Great
- Bob the Great
- Alice the Great
- Beatrice the Great
- Charlotte the Great
- Denise the Great

I'm not sure what the best way to fix this is. The implementation that comes to mind is to generate all outcomes ahead of time and store them in memory, but that has some obvious downsides in terms of processing time and memory consumption. I'm hoping that a better algorithm that allows for equal randomness, while not being taxing on the system, can be implemented.

**Comment by tehhowch** [comment]
I'm gonna just say no to generating all possible phrase outcomes and picking one from that. Storing them sounds also bad.

I see this as only a content issue: because there are twice as many results in a phrase node, any one path through that node will be half as likely. Collectively though, they have the same likelihood as appearing as those choices from the other path.

**Comment by Thunderforge** [comment]
@tehhowch After some reflection, I've come to agree that generating all outcomes ahead of time has too many downsides, and have adjusted my PR to not request that solution specifically.

> I see this as only a content issue: because there are twice as many results in a phrase node, any one path through that node will be half as likely. Collectively though, they have the same likelihood as appearing as those choices from the other path.

It's true that collectively, the "male names" and the "female names" in the example collectively appear an equal amount of time (1 out of 2 times), but my concern is that the individual outcomes are less likely. In the game, this means that some ship names and hails happen more often than expected, meaning that users are more likely to see duplicates and not the rich amount of content the game has to offer. Does that clarify my concern? Or am I misunderstanding what you are saying?

**Comment by tehhowch** [comment]
We could indeed weight the path selection somewhat. Probably this would be just a simple first-level count of possible outcomes.

**Comment by Pointedstick** [comment]
I noticed this a long time ago but came to the conclusion that the best solution was to just add more content. :)

**Comment by Thunderforge** [comment]
> I noticed this a long time ago but came to the conclusion that the best solution was to just add more content. :)

Adding more content is great, but unless you add that new content evenly, it doesn't really solve the problem. If we have this:

```
phrase
     "a million possible items"
     "two possible items"
```

...then that all that time and effort put into adding a million items is going to waste because nobody will ever see it; they're only going to be seeing the two items in the second group.

**Comment by Pointedstick** [comment]
Yeah, that's true. You can work around it by adding duplicate definitions (e.g. in the ship names), but I agree that the current situation isn't ideal.

**Comment by jafdy** [comment]
Could we add a weighting, in the same way the fleet definitions have weightings. Then we could manually fix any particularly bad cases (or make some things vary rare on purpose).

**Comment by tehhowch** [comment]
> Adding more content is great, but unless you add that new content evenly, it doesn't really solve the problem. If we have this:
> 
> ```
> phrase
>      "a million possible items"
>      "two possible items"
> ```
> 
> ...then all that time and effort put into adding a million items is going to waste because nobody will ever see it; they're only going to be seeing the two items in the second group.

That's disingenuous, since if it was
```bash
phrase
    phrase "a million different possibilities"
    phrase "a million other possibilities"
```
It's **still** a 50% chance to see one of the first million possibilities, i.e. no time was wasted on coming up with them. The only thing that is different upon expanding the other branch is that the end user doesn't see the same two choices 50% of the time.

It sounds to me like the most appropriate thing to do would be to have a tool that samples the current phrases and identifies the phrases or words that get used a lot in comparison to a sibling, but have less diversity.

Then we can focus on where to add new content, and also provide plugin authors with a tool for their own content. 

The design and development of that tool should go to the endless-sky-tools repository, and not this one. (A contribution is welcomed, I won't be focusing on creating one for quite some time.)

**Comment by Amazinite** [comment]
I think an easy course of action to solving this would be to have phrases be able to use weights similar to how fleet variants do. For example, take the following example. Lets say these two phrases here are our only pirate phrases. For reference, "bad outcomes" contains 50 words, "pirate adjectives that work as titles" contains 50 words, "pirate adjectives that don't work as titles" contains 66 words, and "pirate nouns that work after bad outcomes" has 27 words.
```
phrase "pirate"
	phrase
		"bad outcomes"
		"pirate adjectives that work as titles"
		"pirate adjectives that don't work as titles"
	word
		" "
	phrase
		"pirate nouns that work after bad outcomes"

phrase "pirate"
	word
		"Three Skeleton Key"
		"Ampoliros"
		"Demeter"
		"Antonia Graza"
		"Mortzestus"
```
As it stands right now, "Three Skeleton Key" has a 1/10 chance of being chosen. (1/2 for one of two pirate phrases, 1/5 for one of the five names within that phrase.) A name like "Doom Ogre" though has a 1/8100 chance of being chosen. (1/2 for one of two pirate phrases, 1/3 from "bad outcomes" being chosen among the first three phrases, 1/50 from choosing one word among the "bad outcomes" phrase, and 1/27 from choosing one word among the "pirate nouns that work after bad outcomes" phrase.)

If we weighted each phrase though, it would look like the following.
```
phrase "pirate"
	phrase
		"pirate set 1" 4482 # 4482 possible names can come from this set
		"pirate set 2" 5 # 5 possible names can come from this set

phrase "pirate set 1"
	phrase
		"bad outcomes" 50 # 50 words in this phrase
		"pirate adjectives that work as titles" 50 # etc.
		"pirate adjectives that don't work as titles" 66
	word
		" "
	phrase
		"pirate nouns that work after bad outcomes" 27

phrase "pirate set 2"
	word
		"Three Skeleton Key"
		"Ampoliros"
		"Demeter"
		"Antonia Graza"
		"Mortzestus"
```
In this way, we then get an equal chance of each of the two mentioned names coming up.
"Three Skeleton Key" now has a 1/4487 chance of showing up due to the 5/4487 chance that "pirate set 2" is chosen, then a 1/5 chance that it is chosen from its set.
"Doom Orge" now has a 1/4487 chance of showing up due to the 4482/4487 chance that "pirate set 1" is chosen, then a 50/166 chance that "bad outcomes" is chosen, then a 1/50 chance that "Doom" is chosen, then a 1/27 chance that "Ogre" is chosen.

**Comment by SubstandardZeal** [comment]
Just to make it explicit, whatever system we use should allow *not* weighing things by their length. For example, choosing between male and female names should be a coin flip regardless of length (as it currently is).
This might introduce the same issue if one list is significantly smaller than another "equally likely" list. Hopefully this isn't too common and we can just adjust the size of the affected lists.

**Comment by Thunderforge** [comment]
[This comment](https://github.com/endless-sky/endless-sky/issues/5024#issuecomment-621016060) gives a concrete example of this problem: when generating pirate names, there is a 1/90 chance for the ship to be named "Three Skeleton Key" versus 1/498,960 for "Shadow Lucifer".

We could certainly try "rebalancing" the phrase groups, but that's kicking the problem down the road and means a new group of names may unbalance them in the future as well; at some point it's better to find a solution that more evenly distributes them.
