### ISSUE TITLE
Allies are merciless toward disabled ships

### ISSUE THREAD

**Issue by johndh** [endless-sky/endless-sky#46]
This is especially jarring when I'm specifically instructed to disable ships rather than kill them, like the early Free Worlds battles.  The gameplay and the story seem to contradict one another, since the text talks about how reluctant everyone is to go to battle and how every death is regrettable on both sides, but in actual gameplay they will go out of their way to slaughter any disabled enemy on the map (even ones I'm currently boarding).

**Comment by endless-sky** [comment]
I think the issue is not the mission-related allies, but the ordinary, non-mission-relates Free Worlds ships that are flying around in the same system. For the time being, I've switched all Free Worlds ships to disable their targets instead of destroying them (2ee50a9).

A better long-term solution would be if they somehow disable Navy ships but destroy pirates outright, or destroy non-mission-related Navy ships but disable mission-related ones, or something like that, but that would introduce a lot more complexity in the AI.

**Comment by johndh** [comment]
I understand that it would probably add a lot of complexity too, but I wonder if the best (eventual) solution would be taking prisoners?  Suppose there's a chance the crew of a disabled ship will just surrender instead of fighting to the death when being boarded (assuming there is enough bunk space somewhere in the winning fleet) and be offloaded the next time they land on an allied world.  That way you don't have indiscriminate slaughter, nor do you have a bunch of derelicts floating around unattended.

Navy captures FW for bargaining purposes, FW captures navy to make Oathkeepers, pirates capture merchants for the slave trade, and everybody(?) kills pirates.

**Comment by endless-sky** [comment]
You're right, that does sound like the best long-term solution. Otherwise there would be way too many derelicts floating around for the player to plunder for free. :) Maybe the way it works should be that they will capture enemy ships if they can, and if not they will "scuttle" them - remove key outfits so the ship cannot move, essentially turning it into a floating prison until reinforcements can arrive with enough force to capture the prisoners.

If I have a free weekend some time in the next few weeks, maybe I'll try to implement that.

**Comment by speeder** [comment]
By the way, I came here also because of this... I don't figured how to start the storyline... So I decided to become a pirate-ship stealer (I started with the shuttle and all my flagships are shuttles, so lots of crew), I noticed that everyone is extremely murderous toward pirates, sometimes I and my already looted ships disable somene, but before I can board it, some capital ship jumps in in the system, and fire from the other side of the system, and explode the pirate while I am trying to board it, a couple times this also killed me (with the explosion killing my shuttle).

It is extremely annoying how out of their way AI ships go to kill everyone else.

**Comment by akien-mga** [comment]
> It is extremely annoying how out of their way AI ships go to kill everyone else.

Though that's true, it also needs careful balancing, as if the AI ships did not destroy everything in their way, you would gain so much loot in a little time that any other career than pirate-ship plunderer would become 20 times less attractive.

**Comment by speeder** [comment]
I noticed that too, but it is really annoying when I even decided to strike a pirate system, I went in the pirate system with my shuttle and 4 silverblades.

Then a pirate ship showed up, I pounded it, then when I was about to see the board screen (my ship was already aligned wit hit), some AI ship jump in the system, and launch 20 rockets at the thing and explode it and myself with it.

Seriously, I went out of my way to capture ships, I wandered into pirate space (with a tiny shuttle, most ships can one-shot it if I don't stay behind my silverblades) and sometimes crazy whole armies show up with multiple capital ships, and then they promptly kill everything on sight, even stuff you painfully disabled with your little small ships.

It is very tempting to just cheat, find the save file and put the ships I want there (I don't did that, yet... but I reaload saves every time the AI kill a ship I disabled)

**Comment by endless-sky** [comment]
Here's a change that might strike the right balance: c695080. With that change, if an AI ship is fighting a pirate, it will finish the fight and destroy the pirate, as always. But,when it goes to look for a new target, it will not choose to attack a disabled ship that it was not already fighting. This will need some testing, but hopefully the effect will be that the militia don't leave disabled pirates around for the player to plunder for free, but if the player has disabled a pirate without their help, they won't go out of their way to swoop in and destroy it.

As for the story, right now the only story line that is implemented involves the "Free Worlds," so you'll pick it up if you visit enough worlds in their territory (the "southern" part of the map, particularly the "Rim").

**Comment by jackg4** [comment]
If a ship has been targeted for boarding by the Player, maybe we could prevent any fire on that target.
