### ISSUE TITLE
Selected system X jumps away should calculate planned instead of optimal route

### ISSUE THREAD

**Issue by wkoot** [endless-sky/endless-sky#460]
I planned a route of 5 jumps that escort ships without jump drive can follow.
However, the calculation for selected system says 4 jumps instead:

![2015-12-14_200253](https://cloud.githubusercontent.com/assets/3715211/11790865/58913bf8-a29e-11e5-87f6-b601fb9f729d.png)

**Comment by brick96** [comment]
I want this

**Comment by endless-sky** [comment]
Right now the distance shown is always the minimum amount of jump fuel, not the length of the path you have currently planned out. (The distance shown is the distance to the mission that is selected, not the distance to the end of the player's current travel plan.)

**Comment by frameworld** [comment]
"Selected system: Nihal (4 jumps away)" is miss-leading if "(… jumps away)" show the distance to Markab (from mission).

Suggestions:
* 4 jumps to: Markab (mission goal)
* 3 jumps to: Nihal (minimum jumps required)
* 5 jumps to: Nihal (selected system)

**Comment by wkoot** [comment]
I always see the X jumps away (being minimum distance) in the map>missions screen, even if I don't have an active mission. This is on 0.8.9 btw (I love the map additions zoom and legend btw)

**Comment by endless-sky** [comment]
I've changed this in commit 71e807e so that:

* Jump drive jumps get counted as one jump instead of two (i.e. the "jumps" number now always reflects how many days it will take to get there with no stopovers).
* If the selected system is along your current travel plan, the "jumps" number is how far along the travel plan it is, rather than the minimum distance.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
