### ISSUE TITLE
Reputation maintainer / communication jammer

### ISSUE THREAD

**Issue by DynV** [endless-sky/endless-sky#4629]
**Is your feature request related to a problem? Please describe.**
I occasionally want to capture a ship from faction I have a good reputation with, and am not doing so to keep the reputation.

**Describe the solution you'd like**
An outfit preventing the reputation from changing would be added. I'm thinking the reputation change is due to the  attack being communicated; so a communication jammer would prevent that, provided no other ship of the same faction show up during the attack.

If you think it would be a good idea, perhaps there would be a chance of failure, so multiple ones would be necessary to drop the failure rate to something the attacker is willing to take. Perhaps also the fleet members around that area would experience problems (like when there's crew below minimum) due to that added outfit.

**Comment by Zitchas** [comment]
I'm not sure this is a good idea. On the surface it looks reasonable, and adds some fun reasonableness. But such a device would mean that suddenly every ship in the game is basically available for free without penalty. So, things like capturing Arfectas, Heliarch warships, Wanderer warships. (Perhaps trying to capture a Derecho or Hurricane when they first appear instead of waiting until they are available for sale?)

Such a device would have to have some serious drawbacks. For instance, being illegal and subject to stiff fines while simultaneously being fairly big with decent energy drain & heat production. 

More likely, if such a thing could be considered likely, would be having said device be a single use device granted by a mission (something in the oft-discussed pirate campaign, for instance). Have it be some kind of ammunition like a nuclear missile that could be used, and if it connects with its target, anything the player does subsequently (like attack, disable, and capture) doesn't have any karma consequences. So long as the ship is alone and doesn't have any allies to witness what is going on, at least.

If this was a  one-off thing where the player got to - once - capture a ship from anyone without karma damage... That could be fun, interesting, and not OP. But in the form of a permanent outfit that lets a person do it on a regular basis.... No, I don't think that could ever be considered for vanilla. That being said, I'm curious as to what it would take in terms of coding to support such a thing.

**Comment by Pointedstick** [comment]
> I occasionally want to capture a ship from faction I have a good reputation with, and am not doing so to keep the reputation.

Translation: I'd like to break the law and hurt innocent people with no consequences. :)

Since this is a video game set in a fantasy universe, there's already a perfectly good solution: cap the ship and then edit your save file to restore the reputation hit, or just edit the save file to give yourself the ship.
