### ISSUE TITLE
Permit dialog boxes with "on accept" conditions for jobs

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#463]
Currently, if you create a mission that is offered via the job board and has a dialog attached to the "on accept" condition, it is ignored. This should work as intended, and you should be able to display a dialog box (for additional flavor text) for jobs accepted via the job board.

**Comment by endless-sky** [comment]
As of commit 962db5c I've added support for "on accept" dialogs / conversations for jobs.

Any "on offer" dialog or conversation for jobs will still be ignored. Otherwise you could decline a job after accepting it, which would make very little sense and would significantly complicate the code for accepting jobs.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
