### ISSUE TITLE
Idea: Modder facility

### ISSUE THREAD

**Issue by sanjayatio** [endless-sky/endless-sky#466]
What do you think about a modder facility?
As the name suggests, it allows a player to modify his/her existing ship/outfit into something else.
Obviously, a planet without a shipyard would have no capability to modify a ship.

My ideas:
- have a "difficulty" parameter for modified ship/outfit.
- all modder will start with 0 knowledge about how to modify; except for those designated places.
- the modder can only initiate a modification attempt after a player arrives with an original and a modified sample, 
- depending on "difficulty" parameter (and perhaps local proficiency parameter) the result could range between:
   - successful modification
   - ruined original
   - ruining both the original and the modified sample; to add more spice, player reputation might be reduced based on the maximum damage of these items combined
- once the modder has 100% modification knowledge, the ship/outfit can be offered in the shipyard/outfitter.

In the core we have:
- Argosy to "Modified Argosy"
- "Energy Blaster" to "Modified Blaster"
- "Blaster Turret" to "Modified Blaster Turret"

Logically ancient models should be the prime targets for tinkerer; like turning Star Queen into a boarding ship (converting from a luxury liner, one should be able to squeeze a lot of people in).

Attached are my attempts to turn a berserker into a light freighter. 
[ships.txt](https://github.com/endless-sky/endless-sky/files/62589/ships.txt)
![reformed brute](https://cloud.githubusercontent.com/assets/8486873/11813531/947701a8-a374-11e5-9c7a-9da310b834b3.png)
![full throttle](https://cloud.githubusercontent.com/assets/8486873/11813551/ab4ff920-a374-11e5-886b-52618d2a28ae.png)

**Comment by Wrzlprnft** [comment]
That's ans interesting idea, but basically we would need every ship model in every variation?

**Comment by Pointedstick** [comment]
This seems like it would reduce the distinction between ships and introduce an enormous vector for abuse by powergamers. Instead of turning your Berzerker into a light freighter, just get a Headhunter. It has 50 tons of cargo space.

**Comment by brick96** [comment]
Maybe instead of having models for each ship have "glue on parts". Take minecraft banners for example, there isnt a model for every banner combination, but code to remember up to 4 mods to it, in the same order they were applied

**Comment by sanjayatio** [comment]
@Wrzlprnft: not necessarily, just that w/o visual differentiation, some might press "S" more often?

@brick96: if i read yours correctly, you're suggesting color code(s), just like the one used to differentiate factions.
imho this requires some code change, and further limits graphics artists choice of color.
perhaps modifyable ship can have a 2nd sprite simply for the color code(s)? 3 codes for up to 9 possible modifications per ship?

@Pointedstick: abuse?
this game gives a lot of freedom for personal modifications, but only a few got merged into the core.
my points are not about turning berserker into a freighter, but:
- look around, one hit and there'll be lots of copycats / modifications. 
- pirates are not the only faction that has interest in modification.

To take the idea to the next level:
- each planet should have a prosperity value.
- prosperity dictates some demands (e.g: it doesn't make sense for a poor planet to have unlimited demands for luxury goods).
- by requesting a mod, planet;s prosperity can be raised.
- the warehouse idea in #330 should increase prosperity as well.

**Comment by bobafetthotmail** [comment]
Cool idea, redundant mechanics.
We can already fit whatever on a ship by using "outfits--> cargo" or "cargo--> outfits" modules, with sane limits on engines and weapons so people can't just buy a cargo ship then turn it into a FAST warship with this trick.

But these changes in stats aren't shown in-game which is a pity. A no-weapon full-cargo berserker looks like any other berserker. I can buy a cargo ship, turn all its cargo into passenger space, and it will still look the same.

I'd just make what brick96 said, base ship image remains the same.

Then place hardpoints on the ship image (these are just coordinates on where to place stuff, not anything physical, they can go in the ship stat file), and depending on what outfits you place, stuff is loaded on these hardpoints and shown, or not.
IF a condition is met, an image of the right module is shown OVER the original ship image (or under, depending on where the module is, over or under the ship), at the coordinates you wrote down in your "hardpoint" entries.

So for your berserker freighter, the cargo modules are shown in the hardpoints when you buy more than X "outfits--> cargo" internal modules, or when the internal cargo raises above X.

X has to be chosen high enough to not have conflicts on same-class-size ships. (that is, Interceptors have their own X, Light warships have their own X, and so on)

With this system you can even get hybrid modules, like say showing a big cargo module on the right to show that you have bought say 10 cargo space, and showing a big passenger module on the left to show that you have bought say 10 crew bunks on your berserker. (purely random numbers to make an example)

You will probably need one set of (cargo/passenger/shield/dunno) module images per ship class (due to sizes), and maybe a set of special modules for special purposes/races/ships/whatever.
Can of course have more than one set, like one per faction, so that a syndacate interceptor does not use the same modules than a repubblic one.

Some ships can have a "default modules shown" configuration too, that is, for example the Behemoth (but many cargo ships), it has a bunch of cargo containers in its ship image. If those were simply its "default module configuration" and they were in fact modules loaded by default, you could see them change into passenger or shield generator modules when you change the ship stats.

It's annoying do do and mostly cosmetic since the core mechanic is already there, but it is doable and would look pretty damn cool.

**Comment by endless-sky** [comment]
As other have said, this would erode the current differences between ships, and it's already doable to some degree using cargo and mass expansions. The only improvement would be to allow ships to show they have been modified, but that would also put a much higher burden on people designing ship sprites. So, I think it's better to handle this via hard-coded ships in the same "family" (e.g. Argosy vs. Modified Argosy) rather than having generic modding capabilities built into the game itself.
