### ISSUE TITLE
Generally increase weapon inaccuracies to improve the chances of smaller ships to dodge

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4697]
**Is your feature request related to a problem? Please describe.**
Weapon inaccuracies are currently generally very low, which means that even at max range the cone of fire is small enough that the inaccuracy doesn't even come into play, even for small ships. That is, even at the maximum range, nearly every shot will still connect due to the size of ships versus the cone of fire.

**Related Issue Links**
#4034

**Describe the solution you'd like**
Increase weapon inaccuracies across the board, except for on homing weapons and lasers. This will make it so that the cone of fire comes more into play at longer ranges, meaning that it may be possible for smaller ships to actually dodge shots because of the inaccuracy of the enemy.

**Comment by jafdy** [comment]
I don't think this really does "doge", more "miss".

**Comment by Zitchas** [comment]
I like this, although on the flip side if the shots are more randomly spread out across a cone, they become harder to dodge. 

Given that the AI doesn't really dodge, this seems like something that will make life easier for the AI, new players, and those who don't dodge; and make things harder for those who do dodge.

**Comment by Pointedstick** [comment]
I generally agree.

**Comment by ravenshining** [comment]
I'm sceptical about this idea.  Inaccuracy in a projectile weapon may well make it *harder* to dodge, since you have to avoid a larger area of the battlefield.  And, if projectile weapons are allowed to spray wildly, it makes much less sense for certain projectiles such as the Gatling to be relegated to short range - my headcanon about why a ballistic slug vanishes after a very short range is that the gun is firing very inaccurately, so the low range is acting as a proxy for lack of focus.

I rather think lowering turret turn rates would be a more meaningful boon to smaller ships, while being able to be applied to both projectiles and beams.

**Comment by Zitchas** [comment]
That reminds me, that there's at least a few weapons that should probably have significantly increased lifetime, but with a "range override" at their current max range, to represent that they continue to be dangerous for much farther out, even if it is impossible to consistently hit anything at those ranges.

On the flip side of this idea, I think I might be leaning more towards keeping accuracy as-is for the most part, with only specific weapons that are noted for having poor accuracy being bumped up. Then have the general inaccuracy of governments increased. 

So a blaster on a navy ship might have not-great-but-not-terrible accuracy, while a blaster on a merchant ship might be basically an inacurate cone of fire.


Overall, though, the more I play with Revamp (in which almost all weapons are twice the inaccuracy of vanilla), the more I am of the opinion that generic inaccuracy isn't the solution to enabling small ships to dodge shots. While it does make more shots miss small ships, that's not dodging, that's just the shooter missing. I think what we really need is some sort of engine change wherein the AI has an enforced "lag" time of some sort, so that they can't react instantly to every move the player makes. Even something as small as limiting the AI to using the position and vector information for their target from 1/10th of a second ago would probably result in a noticeable decrease in their laser accuracy and a more human-like levels of targeting.

Ideally, perhaps a baseline/range of timings. Maybe the baseline is .2 to .3 sec lag time (randomly assigned to NPCs when spawned), with the governments, persons, and/or NPCs having a modifier that is applied to that. For instance, the Navy might have a .1 modifier, so it's lag time is actually .1 to .2 sec, representing their professional training so they instinctively track and lead targets better.

**Comment by Amazinite** [comment]
Not taking this route of balancing.
