### ISSUE TITLE
Damage dropoff/decay with range mechanic

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#4698]
**Is your feature request related to a problem? Please describe.**
In relation to #4697, inaccuracy can't be increased on beams as a way to make them worse at their maximum range, as high inaccuracy on lasers looks very weird. Lasers should still have some way to be less effective at range, though.

**Related Issue Links**
#4697

**Describe the solution you'd like**
Add some sort of mechanic that causes a weapon's damage to decay with range, similar to how damage scaling works with blast radius. This could make it so that lasers for example are at their most powerful up close, but at the very edge of their range they do reduced damage, say 75% of their maximum.

**Comment by jafdy** [comment]
Could we make damage formulaic, so that we can make the damage the weapon does a function of the distance travelled, and possibly some other stuff. Or just make a new damage type/modifier to the existing type that decays to 0 at maximum range (with a second damage line adding a constant to that).
This would need to be conveyed to the player some how as well.

**Comment by Amazinite** [comment]
>Could we make damage formulaic

How do you imagine the syntax for that would look?

**Comment by Amazinite** [comment]
Syntax wise for this, I'm thinking having some attribute `"damage dropoff" <a> <b>` where `a` is when damage dropoff starts and `b` is when it ends. If `b` isn't specified, then the end is just when the projectile dies. Then `"damage decay" <x>` where `x` is a number from 0 to 1 representing the % damage at `b`, and with the damage decaying linearly from 100% at `a` to `x/100`% at `b`.

Mechanically, I imagine that a projectile would be given the knowledge of the position it was fired from by its armament and the position it impacted by Engine::DoCollisions, then just figure out the distance to know the range the projectile was at when it impacted to be used for the damage decay.

**Comment by jafdy** [comment]
`damage 10/(distance+1)` would be 10 damage next to the weapon 1 at distance 9 ect.

**Comment by Amazinite** [comment]
Sounds like a situation begging for someone to create a divide-by-zero.
That would also require weapon to be able to read a conditionSet, or something like it.

**Comment by jafdy** [comment]
Yes, but we don't need to protect content creators from themselves.

**Comment by NomadicVolcano** [comment]
It would also be useful to increase with distance, or have an optimal distance (increase and then decrease).  I see a straightforward way of implementing this:

    velocity 25
    lifetime 20
    "center point distance"  300
    "ranged damage percent"  50 100 80

The weapon does 50% damage at point-blank range, 100% damage at a range of 300, and 80% damage at maximum range.

You avoid strangeness by clipping percentages to 0--100 and center point distance between 0 and maximum range.

The AI would try to stay at the optimal range when firing instead of maximum range.  If the weapon is multi-stage, the AI would pick the maximum damage across all stages.  When someone has more time, they can update it to optimize self damage vs. target damage.  That would be complicated when several weapons are shooting, each with different damage curves.

Graphics would be scaled by the damage percentage.

You can achieve a linear drop-off to zero with:

    "center point distance" 0
    "ranged damage percent" 100 100 0

or a linear increase from zero with:

    velocity 25
    lifetime 20
    "center point distance" 500
    "ranged damage percent" 0 100 100

quadratic drop-off with 75% damage at half-range:

    velocity 25
    lifetime 20
    "center point distance" 250
    "ranged damage percent" 100 75 0

constant damage (the default) would be:

    "center point distance" 0
    "ranged damage percent" 100 100 100

**Comment by Amazinite** [comment]
I don't think there's a need to get too complex with it. #4703 does allow for weapons to increase in damage over range instead of only decreasing, and using submunitions would be an easy way to have a weapon increase in damage then decrease in damage after a certain point. (Parent projectile increases in damage, then the submunition is spawned and decreases in damage.)

**Comment by NomadicVolcano** [comment]
I concede your point.  Simpler changes are better changes.
