### ISSUE TITLE
wanderer outfits license is Installed before being offered

### ISSUE THREAD

**Issue by undepressor** [endless-sky/endless-sky#4702]
Description:
In the First Contact mission chain with the wanderers, the player receives the Wanderers Outfits License at the exact same time as the player receives the Hai translation device. The License is visible at every outfitter even before the player returns to the Wanderer home world to make contact and receive it.

1. Follow the Wanderer storyline up to the point where the Hai gives the translation device.
2. Check your installed outfits at the Outfitter
3. Observe that the Wanderer outfits license is already installed

Expected behavior:
The License should get installed after the player visits the home world with the translator.

Link to my save file where the bug just began:
[wanderer-outfits-bug-Erik_Hess.txt](https://github.com/endless-sky/endless-sky/files/3924326/wanderer-outfits-bug-Erik_Hess.txt)

**Comment by Amazinite** [comment]
Fixed this in the latest commit by pushing the license back a mission..
Notably, this makes it so that pilots who finished these missions prior to v0.9.7 but haven't been been launched since won't be able to purchase Wanderer outfits (as the license is no longer in any patch mission), but that was nearly 3 years ago now so I think we're in the clear.
