### ISSUE TITLE
steering imbalance?

### ISSUE THREAD

**Issue by Listerdave** [endless-sky/endless-sky#4713]
Observation: While experimenting, I outfitted a ship with insufficient energy to run its engines and fire its weapons at the same time.  When using both weapons and main thrusters, the port thrusters worked, but the starboard thrusters didn't, so the ship was able to turn left but not right.  It's not really a problem, but it seems odd, so I thought someone should know about it.

**Comment by Amazinite** [comment]
What are the keys for your fire, thrust, and steer left/right?
At a first glance, sounds like an issue with your keyboard, not the game. I know my keyboard can't do certain combinations, which required me to change up my key bindings in order to be able to do certain things. (In this case, it sounds to me like you had your fire on tab, then your thrust on W and your steering on A/D, because I had that issue myself where I could thrust, fire, and only turn in a certain direction. By changing fire to space, I'm now able to fire, thrust, and turn in both directions.)
I say it's your keyboard and not the game because the inability to use certain key combos holds true across games for me. (Not being able to do Shift+W+3 is one I consistently run into for sprinting and trying to select my 3rd weapon in FPS games.)

**Comment by Zireael07** [comment]
It's known as "keyboard ghosting", and unfortunately it's a known issue with many keyboards.

**Comment by Pointedstick** [comment]
Yep, I have the same issue with my keyboard. It's keyboard ghosting, which is a hardware problem that we can't work around in the game, sorry.
