### ISSUE TITLE
XML Conversion

### ISSUE THREAD

**Issue by shitwolfymakes** [endless-sky/endless-sky#4721]
**Is your feature request related to a problem? Please describe.**
Currently, the game engine uses a custom data format to store all game data. It was a decent format, and makes it fairly easy for people to jump in and start writing missions. However, automated tools like ESMB can easily surpass this in terms of making it easy for anyone to jump in and start making content for the game. The problem is that the current data format lacks closing tags, and cannot be easily ingested and parsed due to a lack of closing tags.

I'm not going to rehash why the conversion should be to XML, but that's what we settled on. It is worth noting that this project is already in motion on the Endless Sky Civil War project, the relevant issue post is [here](https://github.com/kikotheexile/Endless-Sky-Civil-War/issues/6).

**Describe the solution you'd like**
Switching to xml will decrease time to implement features in tools created to generate content for the game, like ESMB or the ship builder. I'm writing the schema for the new format while working on new features for ESMB

The real question is, if ESCW successfully implements this, will you guys be willing to port it Endless Sky? It would be great for me if you did, as I could ditch the rather ugly parser I've written so far for just walking an xml tree

**Comment by Amazinite** [comment]
1) Why can't any 3rd party tools just emulate the behavior of the game's data parsing, looking at [DataFile](https://github.com/endless-sky/endless-sky/blob/master/source/DataFile.cpp), [DataNode](https://github.com/endless-sky/endless-sky/blob/master/source/DataNode.cpp), and [DataWriter](https://github.com/endless-sky/endless-sky/blob/master/source/DataWriter.cpp) (a collective ~600 lines of code) for how the game handles the custom data format? In terms of converting the entire game over to a different format or instead creating a 3rd party tool that parses the data the same way the game does (which could then be used by other tools for specific purposes, e.g. creating ships or missions), I feel like the latter would be easier.

2) Would this be a total conversion or be an addition to parsing the custom format in text files? It's unlikely that we'll go fully into a different data format as one of the principles of new updates is backwards compatibility, but such a change as converting to an entirely different data format would go against that. (Not only would all old plugins become useless, but all old saves would become useless too since they're in the old format, so throwing the old format out is out of the picture.)

3) Should both formats be supported, do we still go through with converting all vanilla data to the new format? And going forward, do we enforce which format will be used for vanilla content even though both are possible? Or do we simply accept both formats, meaning you'd have a set of .txt files and a set of .xml files for the same things.

4) What exactly would such a conversion entail? What would need to change source-code wise?

If the only purpose of changing the data format is for the sake of 3rd party tools, I feel that there has to be simpler solutions.

**Comment by comnom** [comment]
#551

>The problem is that the current data format lacks closing tags, and cannot be easily ingested and parsed due to a lack of closing tags.

A newline ends a datanode. A space or quote ends a token.

**Comment by shitwolfymakes** [comment]
1. The current data format is already basically xml, but worse. It has now way to write a schema you can validate against, and it has no closing tags. He reinvented the wheel, and I can understand why, but xml is *vastly* easier for a program to parse than the current data format. When I saw 3rd party tools, I mean things like ESMB or the ship/planet editors, that generate the data that is then added into ES, not anything ES source code needs to see or use.

2. This would be a total conversion. Once the schema documents are written, then all game data can be converted to xml, and validated against the schema docs. Furthermore, all of that could be scripted, and I'd be happy to halt work on ESMB to help convert mods, work on a save file converter, and the like. I'll need to update ESMB anyway to handle the new format. Please don't let this part be what changes your mind, it will be more like updating mods from Skyrim to Skyrim SE than some herculean task.

3. It will be XML only from here on out, with a suite of tools for converting plugins and save files. Otherwise the engine has to handle two different formats, and that's no bueno. None of the art data or folder structures will change though. I will be one of the people working on converting everything. After the conversion, the ES source should not accept .txt files as valid data.

4. In terms of source: as I understand it now, when the game creates almost any object, is passes the parent DataNode to the object's constructor, and it parses the data inside that node to create the object. This is almost exactly the same, due to how the DataFormat is already basically xml. The things that will change are that instead of looking for tokens, the constructors or factory methods will check the tags. 

When saving and loading the game, the source would be pretty much the same as it is now, except leveraging the new XML library. I do not know how the game stores the data during play, and I don't know enough C++ to suss it out myself.

5. I imagine it was to cut down on the need for non-standard libraries, as well as to make it easy to read and write for people of all skill levels. The major downsides are that it makes automating that work very difficult, there's no way to check for errors without going line by line.


@comnom I am aware of the current data format. I have been working around that constraint for a year now. Thank you for pointing me to #551! Although it it's almost 2020. The arguments of "difficulty matching up tags" and "people would make more mistakes writing XML/YAML/Cuneiform" no longer hold water, if indeed they ever did. Any half decent text editor will give an error on tag mismatches. 

The knee-jerk reaction is to assume that people will be writing this by hand, which is understandable because until January, there was no way to write a mission other than by hand. But the tools to create content with out writing a line of code in any language are here, and are being used. All of @dplepage's arguments for switching to an actual data language are still there.

**Comment by comnom** [comment]
> I have been working around that constraint for a year now.

I fail to see how parsing for a closing brace (or in the case of xml, </> ) is somehow easier than parsing for /n.

Since the whole issue is predicated on that, I also fail to see how a whole new data format helps anything. 

There's three open source parsers in three different languages, all for es's data format, and none of them have trouble finding the end of a node or token.

**Comment by beccabunny** [comment]
>     2\. This would be a total conversion. Once the schema documents are written, then all game data can be converted to xml, and validated against the schema docs. Furthermore, all of that could be scripted, and I'd be happy to halt work on ESMB to help convert mods, work on a save file converter, and the like. I'll need to update ESMB anyway to handle the new format. Please don't let this part be what changes your mind, it will be more like updating mods from Skyrim to Skyrim SE than some herculean task.

Still, if that would mean losing backward compatibility at all, I highly doubt it will be added; I can see why CW wants it, since there is nothing to be backward compatible to, but completely losing the backward compatibility in a game as old as ES doesn't seem a good thing to me. Similarly, one of the best part about ES is that you can easily write almost everything using only a basic text editor, and having to rely on a third party tool all of a sudden doesn't seem a good change as well

**Comment by Amazinite** [comment]
>The knee-jerk reaction is to assume that people will be writing this by hand, which is understandable because until January, there was no way to write a mission other than by hand. But the tools to create content without writing a line of code in any language are here, and are being used.

So at that point aren't we just creating a problem to sell the solution? (i.e. converting the game data to XML so that tools like ESMB can be used.)

**Comment by shitwolfymakes** [comment]
Converting the game data isn't much of a hassle, same goes for mod content. I've been working on the schema for a couple days now. The point is that the content creators shouldn't have to write a single line in the text files, all they should be asked to do is fill out a form in an app and press compile

**Comment by beccabunny** [comment]
But the current format is already simple enough, most people never had problems using it. They can also already use the errors.txt, which is almost always enough. Also, note that in the current state there are mods from 2017 that are still working and supported, even if its modder has abandoned it. Last, about the save files: most of the downloads come from there, and asking everyone with an old save to visit the forums, eventually find a third party converter, use it and hope a bug doesn't occur. That seems a very messy way to me, which will only make the game get worse reviews from users who didn't pay enough attention

**Comment by jafdy** [comment]
While there is always an argument for using tools to create the data it does increase the barrier to entry and require those tools to continue being supported. In a professional studio this may not be an issue as they develop and maintain the tool alongside the game, but for us it is not so simple. 
This begs the question; What happens if you stop support? Does this require us to take over support of your tool? We can't just let it sit, no new features could be added that way. 
You will not be the first nor the last person to leave this project.

**Comment by jafdy** [comment]
```
<ship ="Aerie">
	<sprite ="ship/aerie">
	<thumbnail ="thumbnail/aerie">
	<attributes>
		<category ="Medium Warship">
		<"cost" =3500000>
		<"shields" =5700>
		...
		<weapon>
			<"blast radius" =80>
			...
		</weapon> #These are the end tags he wants.
	</attributes>
	<outfits>
		<"Sidewinder Missile Launcher" =2>
		...
	</outfits>
		
	... #Not sure how these would convert 
	<description> 
		"The Lionheart Aerie ... weapon technology."
	</description> 
```

**Comment by comnom** [comment]
>The point is that the content creators shouldn't have to write a single line in the text files, all they should be asked to do is fill out a form in an app and press compile

Sounds neat. Fortunately, nothing about the current datanode format would stop someone making such a tool.

If you're having trouble parsing the data files and validating the data for a tool, I'd recommend looking in this very repo, since the game already does this.

**Comment by shitwolfymakes** [comment]
@jafdy Your point about me not always being around is a good one, but right now is actually the least time I have to work on this, seeing as I'm in my last year of university. Once that's done I start working full time, and my position is barred from overtime work. Furthermore, ESMB is being built as a major part of my resume going forward, so it behooves me to complete it.

@comnom I'm not saying it's stopping me from making such a tool, as I already have, it just makes it harder for me.

Again, my question is: If the conversion is successfully implemented for ESCW, will you accept the conversion as a pull request to ES? I need to know before any source overhauls begin, because I don't have the time support two different data formats

**Comment by tehhowch** [comment]
There's no plan to change the data format of the text files.

**Comment by shitwolfymakes** [comment]
Due to the overwhelming lack of support for this, I'm closing this pull request for both ES and ESCW

**Comment by ThrawnCA** [comment]
> But the current format is already simple enough, most people never had problems using it. 

The current format is very nearly [YAML](https://en.wikipedia.org/wiki/YAML). To me it would make much more sense to convert to - or add support for - that, instead of XML.

Put colons after key names (eg `goto label` becomes `goto: label`) and hyphens at the start of list items (instead of wrapping conversation lines in back-quotes) and you're almost there.
