### ISSUE TITLE
 #4715 seems to change the behavior of the jump button and arrow keys

### ISSUE THREAD

**Issue by pouar** [endless-sky/endless-sky#4744]
**Describe the bug**
before 96e2b53b5c83ca5715411fb7d9d8b22fe4f16454, you could use the arrow keys while holding down the jump button, which allowed you to move back and forth without "disengaging autopilot". After the change, pressing any of the arrow keys "disengages autopilot" even while still holding the jump button, so you have to let go of the jump button and press it again. This also causes any escorts to stop waiting for you to release the jump button and start moving around again. Cancelling a jump before 96e2b53b5c83ca5715411fb7d9d8b22fe4f16454 worked by releasing the jump button while holding down the arrow keys, and not by simply pressing the arrow keys even while holding down the jump button.

**To Reproduce**
1. Press one of the arrow keys while holding down J
2. The Jump gets cancelled even though J is still held down.

**Expected behavior**
The jump should've only been cancelled if you let go of J while pressing the arrow keys.

**System (please complete the following information):**
 - OS: Arch Linux
 - Game Source: self-compiled
 - Version: 96e2b53b5c83ca5715411fb7d9d8b22fe4f16454

**Link to save file**
[Pouar Dragon 2.txt](https://github.com/endless-sky/endless-sky/files/4066698/Pouar.Dragon.2.txt)

**Comment by petervdmeer** [comment]
Thanks for taking the time to file an issue, the behaviour change described here indeed happens with 96e2b53b5c83ca5715411fb7d9d8b22fe4f16454.

I tested the scenario described in this issue (on 49a387d848e88dc734c93b34013af81f873e70c1, just before the commit above) with the savegame provided (and with a gaming keyboard that supports multiple keypresses at once);
The only control that still did something on my laptop while pressing JUMP was FORWARD. All other LEFT/RIGHT/BACK turning signals appeared to be fully countered/overruled by the autopilot. Pressing FORWARD in this scenario also just caused the ship to immediately start turning to re-aligin for the jump.

I need some more information on why the behaviour change is undesired in order to decide on a proper follow-up; Can you explain a bit more on why and when you were using JUMP together with FORWARD (or other controls)?
- Was this while waiting for slow ships to align for jumps?
- Or was this in crowded battles?
- Or at some other time/game-event?

**Comment by pouar** [comment]
Mainly because I have a modded hyperdrive that sets `"jump speed"` to a high amount and I end up moving far away from escorts I'm guarding while waiting for them to align themselves before jumping. I usually used the back button to slow my ship down without cancelling autopilot so I don't lose track of them. Although ideally there should be a button to make autopilot bring your ship to a complete stop regardless of whether you're jumping to another system or not, but this was working good enough.

**Comment by petervdmeer** [comment]
Do I understand correctly that if we implement a solution for #4135 (allowing the flagship to do a full stop), then you would also consider this issue to be solved?

**Comment by pouar** [comment]
probably, assuming I can trigger it without disengaging the autopilot when jumping to another system

**Comment by petervdmeer** [comment]
No, the full-stop command and the jump command would still cancel each-others autopilot actions.
One of the major design guidelines that makes this game successful is that the game should be easily accessible for new players; A new player that starts a jump and then gives a full-stop command would expect the flagship to stop, not to stop and then jump from stand-still.

The game does have quite a few areas where the player needs to make choices. Choosing to have a drive with a high `jump speed` is great when you need jumping at high speed, but it works less nicely when you have a need to stay close to escorted ships. If a player is going to do a lot of escort missions in sequence, then the player might want to choose to temporary install a drive with a lower jump-speed equal to the most common escort ships.

My impression is that your use-case can be handled (after #4745 gets merged) by first giving the "full stop command" and then giving the "jump now command" after your flagship fully stopped.
Is it possible for you to run a test with #4745 and tell us if it indeed solves this issue for you?

**Comment by NomadicVolcano** [comment]
Does pull request #4756  resolve your problem?  It resumes the jump, board, or land commands after movement keys are released, if the relevant keys are still pressed.

**Comment by NomadicVolcano** [comment]
A bug fix is in the master to solve this problem.  It also restores the handling of the launch and board commands.

**Comment by pouar** [comment]
seems to work yes

**Comment by pouar** [comment]
Actually works better than it used to because now the AI in all the escorts obey it
