### ISSUE TITLE
Which colors does the game take and make them to fraction colors?

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#476]
I've made a ship design which includes blue elements, but the game unfortunately takes the blue and converts it into fraction colors :/
![big aqua](https://cloud.githubusercontent.com/assets/15857993/11856583/3f7041cc-a452-11e5-96ac-a999a6d93787.png)

**Comment by endless-sky** [comment]
The ship coloring works by swapping ("swizzling") different color channels of the image, so all colors are affected. For example, the Merchant colors work by swapping the red and blue channels.

**Comment by Wrzlprnft** [comment]
So i'll just adjust the colors of my alien government and the player has to live with green or red or whatever octopus-eyes. Could be worse.

**Comment by endless-sky** [comment]
The best option would be to make the ship sprites still use a red and yellow color scheme, but set the "swizzle" for your alien species so that they are turned blue and cyan. That way, if the player buys one of the alien ships, the color will shift to match the player's government color.

(You could render the images in blue if you want, but swap the blue and red channels in GIMP before exporting the sprites.)

**Comment by Wrzlprnft** [comment]
Oh and thx.
