### ISSUE TITLE
Hai story idea needs a big plot hole filled: Why are the Hai so friendly?

### ISSUE THREAD

**Issue by NomadicVolcano** [endless-sky/endless-sky#4790]
I have a long Hai side-story that is about half implemented, but there is one major plot hole in Endless Sky that has to be resolved before I can finish it: the reason for the friendliness of the Hai.

I'm trying to summarize a discussion I had with Amazinite here, in the context of a Github issue.

### The Story Idea

My side-story involves the player meeting a group of Hai dissidents that want to be browbeaten and faux elated like their kin, but don't want to join the Unfettered either.  The player can ignore them, or help them organize, and can choose how far to go with organization: just connect multiple dissidents, start smuggling banned literature or other items, or form a military resistance. The farther down the path you go, the more it changes Hai space.

The nature of this side-story depends on why the Hai are so friendly and how society enforces that behavior.

### The Plot Hole

The Unfettered Hai tell us that the Drak modified the regular Hai 100,000 years ago, but that explanation is inconsistent with other facts. Had this been through biological modifications, it would have been eliminated through migration or inter-breeding in that time. If it was through some other method of long-term, inter-generational, mind control, why haven't the regular Hai broken their conditioning? Are the Drak maintaining the conditioning? Or are the Hai maintaining it through some genetic manipulation or brainwashing of their own? Or do Hai occasionally break it but get removed from society somehow (such as jail)?

In any society, there are crimes of passion and the occasional sociopath, so violations will occur.  What happens to Hai when they violate those rules?  In hails, the Hai tell you that you are welcome in their space if you are empathetic, friendly, and the like; when you attack them, they say they're kicking you out because you violated those rules.  Are the Hai thrown out of Hai space if they misbehave? Are they jailed? Exiled to Unfettered space? Is there some other fate?

### Possible Solutions

My suggestion was for the Hai to apply some form of mental conditioning to Hai criminals to make them friendly and compliant.  Literature that would risk damaging society is banned, like how Germany bans literature that encourages hate.  In other words, what the Unfettered accuse the Drak of doing, is what the Hai are actually doing to themselves. (Though, perhaps, the Drak started the idea 100,000 years ago.)

Amazinite thought the idea was too generic and too 1984 and seemed to prefer the Drak method.  His suggestion was that Drak have made a mimetic change to the Hai; some sort of conditioning that survives multiple generations but isn't biological. The Unfettered have figured out how to break that conditioning, but the regular Hai haven't.

That doesn't explain why the regular Hai can never break their conditioning, or if they do break it, what happens to them.  For my side-story, that plot hole has to be filled in.  The Drak explanation would either need to be supplemented, revised, or replaced (ie.: the Unfettered were wrong).

Suggestions?

**Comment by Zitchas** [comment]
I was under the impression that the unfettered weren't so much Hai who had "figured out" how to break the conditioning (be in genetic or mental), but rather ones who it didn't work on to begin with and/or had some other kind of circumstances that contributed to excessively rebellious and adventurous behaviour.

Personally, I like the sounds of what you outline. Having the Hai adopt some kind of pervasive self-control of what they think is their own doing is neat. Orwellian and 1984, yes, but still interesting. That being said, what if some of them knew full well what they were doing? Maybe the Drak simply got things started with some kind of "pacifier" that temporarily dulled the Hai's imperialistic instincts into quiessence, and a faction within the Hai decided that this was how they preferred things, and took steps to ensure that it persisted. Basically, the Drak said "Time out" rather forcefully, and a pacifistic internal faction took control and figured out their own way of doing it.

(There's a *lot* of science fiction that talks about humans using genetic engineering to form the perfect society, including at least one series where they used it to eliminate aggression and violence from human society. Those who slipped through the genetic cracks were identified and put on a very heavy dose of medications to deal with it chemically instead.)

**Comment by NomadicVolcano** [comment]
An extremely long  discussion on Discord amounted to this:

1. The Hai are friendly due to their upbringing and education.
2. They achieved a utopia by giving up ambition
3. Unfettered Hai are drunk on ambition
4. Ambitious Hai that are fettered either rise to power in their field and become leaders until they lose ambition, or do something criminal, or join the Unfettered
5. Hai society has stagnated for millennia due to fearing ambition.
6. Any side-story that modifies Hai society would need to be based on restoring ambition.
7. There should at least two endings: peaceful, warlike
8. This would eliminate a bastion of peace for the player, so it should happen late in the game
9. Merging the Hai with the Unfettered would screw up other story arcs, so those two must stay separate.

**Comment by Amazinite** [comment]
Quoting from Discord.
> My original feedback on the idea was to have this be a look at the "dark side" or "underbelly" of Hai society outside of the Unfettered. Basically, the answer to the question "Why are the Hai so friendly?" would be "Well maybe they aren't all as friendly as you're led to believe." e.g. an investigation of the criminals of Hai society that aren't also Unfettered.

**Comment by NomadicVolcano** [comment]
The ideas aren't mutually exclusive: the Hai are brought up to be really nice, and most of them are, but a sizable fraction are not.  The appearance of the utopia is just an illusion the player can see through once they dig deep enough.

The question that remains then is whether the Hai in control of the government are the nice kind, or if there are some non-utopian Hai mixed in.  Even if this is a democracy where the bulk of the people prefer nice leaders, that may not be an option if the only people running for office are the not-nice Hai.

The fact that the leaders prefer not to be aggressive towards violent abusers (pirates and Unfettered) suggests that the leadership is dominated by the utopian Hai.  If that is so, then any group desiring to act non-utopian would encounter resistance from the government.

**Comment by jafdy** [comment]
You make it sound in some way bad. Regardless what happens or you think you need to make sure that you are keeping an open mind about the matter. Who is to say that Hai society isn't as it appears. 
A few years ago Iceland was having a youth crime problem, by simple effort of the government and adult population the focus of the youth was shifted to sport instead, this change does still persist. 
It could well be that any Hai that don't fit in enough are less welcome in polite society (thus not normally seen) but are otherwise free to leave. Assuming otherwise is at risk of assuming a government that is at least somewhat authoritarian. 
While it would make the Hai more interesting I do think that having an area of space where the inhabitants are genuinely nice.
A more interesting place to explore this idea may be a more advanced race where every individual has more power so the player could either work with the government to separate the dissident individuals or with the dissident individuals to (covertly) find other dissidents.

**Comment by NomadicVolcano** [comment]
The feeling I'm getting from a lot of people is that Hai space should be left as an area of stability for the player. Any major conflict inside Hai space, like I wanted to do, would ruin that. I'll leave this Issue open a little longer for further comments, but I don't see myself attempting this story.

**Comment by downRightCoder256** [comment]
i will have to agree with @Amazinite : such a story arc is far too 1984, for a couple of reasons; it states that the hai government is malicious without any particular reason. we also do know that unfettered hai have only really existed as a organisation since the korath raids started, and mainly because some hai couldn't let go of the thrill of the battle. i would presume they are just anarchists who demanded less intervention from government in terms of issues such as gun control (you never know then attacks such as the ones by korath might happen again), and, at first, they were probably granted such rights. we know, afterall, that they have only begun raiding regular hai, and when they obtained jump drives, the wanderers, when their worlds started running out of resources. we also do know that they, just like the korath, hold highly to their pride: they require their donations be called "tributes". they also send player straight to the jaws of death, just for fun, so they definitively don't have a moral high ground.

**Comment by NomadicVolcano** [comment]
Yes, I've come to the conclusion that this route won't work.  If the Hai are to be made more nuanced, and not pure black-and-white morality, it needs to be at the level of individual Hai rather than the society as a whole.

**Comment by NomadicVolcano** [comment]
Also, I think the question of the Hai origin story should be left until the details of Wanderers Act 3 are decided.  I'm concerned that any choice on such a matter may restrict options for the grand finale.
