### ISSUE TITLE
Alien Idea: The Tor

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#482]
The Tor are an alien race that use weapon systems that appear to be lightning, and their engines roar like thunder. Their basic ships' shapes would be a Hammer

**Comment by thenerdfreak** [comment]
![bee fighter - copy](https://cloud.githubusercontent.com/assets/15973422/11886769/65b31fde-a4f3-11e5-8392-857c1d005a35.PNG)

**Comment by Wrzlprnft** [comment]
mnah, i wouldn't really shape it like a hammer, i would turn the aspect on the electricity

**Comment by thenerdfreak** [comment]
true^ and maybe instead of their engines sounding like thunder, their jumpdrives sound like thunder

**Comment by Thunderforge** [comment]
In space, nobody can hear the jumpdrives thunder. But I suppose those on board would, as would those hearing it lift off from a spaceport.

**Comment by thenerdfreak** [comment]
If in space, nobody can hear jumpdrive's thunder, then why (also in space) can I hear my enemies' weapons and engines?

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!
