### ISSUE TITLE
Harder penalty for not paying crew salaries

### ISSUE THREAD

**Issue by DmitrySukhv** [endless-sky/endless-sky#4839]
**Is your feature request related to a problem? Please describe.**
As of now, not paying crew salaries (and mortgage) doesn't lead to any problems for the player (except for credit score becoming lower). I suggest that not paying crew salaries must lead to more severe consequences, namely:
- player can't hire crew anymore
- the crew start leaving the ships at ports, at a rate of [total necessary crew]/30 per day, leaving the ships crew-less in a month.

It will make piloting ships more complicated and will motivate player to gain money ASAP

**Related Issue Links**
I didn't find anything

**Comment by Zitchas** [comment]
1. For escorts, sure, this could be good, but with a few caveats. A: They don't lose crew in space or on uninhabited planets. B: they auto-park when crew hits 50% required crew. (the player can still un-park them at whatever the crew level is at, but the point is to make having the fleet degrade to complete uselessness be an active choice, not something that just happens through aggressive inattention.) I'd have the ships auto-park again at 25%, and at that point ships can't be launched. Of course, there should be warnings about this. Probably in the form of a crew chief informing the player when they can't pay the crew that people are going to start deserting. And then every time a ship hits 75, 50, and 25% there should be appropriate notifications so that the player *knows* what is happening.

2. For the flagship, though, I'm not so sure. It'll get really hard to make money really fast if the flagship goes below required crew. The Flagship's crew might ditch extra crew fairly fast (everyone knows extra crew is just there to be cannon fodder on boarding operations. They're not going to stick around if they aren't being paid), but essential crew should drop very slowly, and probably with a several day delay. Something like 1 crew every 5th day sort of thing.

2. The flagship should have a cap at 75% required crew, below which it doesn't drop. (through crew desertions, at least) That's enough to be a crippling in terms of combat,  but still flyable. Someone's who can't afford crew salaries is already down, effectively. We don't need to kick them too.

**Comment by Amazinite** [comment]
This falls into the same category as the idea of aborting jobs having a penalty; it's unnecessarily punishing, and only leads to harming those who are likely already in a bad position. Even worse is the fact that this could lead to a fail state; what happens when you reach no crew but you're on a planet without any 1 crew ships? Or if selling your current flagship doesn't even give you enough for a 1 crew ship to avoid the crew payments?

**Comment by geeknik** [comment]
If I don't get paid, I am going to quit my job and go find one that will pay me. Same goes for a hired crew onboard any vessel. If you're not paying them, they are going to get upset. Maybe they'll quit and leave at the next port. Maybe they'll sabotage the ship. Maybe they'll mutiny and take over the ship and eject the captain out of the airlock. I don't see a problem with punishing players who have made poor life choices and are now marooned on an uninhabited planet because they couldn't pay their bills. LOL

**Comment by Zitchas** [comment]
I get that it seems very realistic, but on the other hand, for a lot of human history the idea of being paid daily/regularly has been uncommon, to say the least. During the heyday of big sailing ships it was rare for sailors to be paid until they got back to their home port. Not at the end of that cargo run, not at the end of the job, no: Not until they got back to wherever their home base is. And that was often several months away. Even today there are plenty of people who stick with jobs on the promise that "some day, down the road, the company is going to make money and pay them off." A lot of start-up companies do this, for instance.

**Comment by Amazinite** [comment]
> If I don't get paid, I am going to quit my job and go find one that will pay me.

Gameplay > realism.

**Comment by geeknik** [comment]
> Gameplay > realism.

Yes and thankfully this game is open source and I can bend it to my will.

**Comment by Zitchas** [comment]
Yes, yes it is. And if you feel like putting in the work to add a "Hard mode" (which is where I think something like this belongs), I'm sure there will be people who enjoy and appreciate having it. I suspect, however, that it will require a decent amount of game engine changes to do it.

**Comment by geojak** [comment]
I like suggestion 3. That crew leaves on landing until 75% left.

The player is crippled in ship control and can't board but he also got lower salary costs.
