### ISSUE TITLE
World-Ship misused; need a "battleship Raider" to replace it

### ISSUE THREAD

**Issue by NomadicVolcano** [endless-sky/endless-sky#4841]
The Korath World-Ship is a major population center, holding the few remaining Korath Exiles, so it doesn't make sense that they would send it into ordinary raids. We must misuse the ship in that way in the game because we don't have a "bigger raider." There is an effort underway now to add:

1. A "Battleship Raider." Compared to a Raider, it has more turrets, a lot more weapon and engine space, more cargo space, but only a small increase in total outfit space. That means it can be a powerful gunship, or be extremely maneuverable, but not both.  In terms of durability: it has only slightly more shield strength, and a lot more hull strength.

2. A "Mining/Factory Raider." This will show up in systems with a lot of asteroids. It will mainly mine asteroids, but it will respond to any attacks. Compared to a Raider, it will have more hull, lower shield strength, innate hull repair, fewer turrets, and more fighters.

3. New weapons for the new Raiders. We may add an afterburner and a reverse thruster too, but that depends on what comes up during testing.

As of this writing, graphics are about 60% complete, and we're planning stats for the ships and outfits.

**Comment by beccabunny** [comment]
I'm not too sure about the mining raider, but perhaps it is something that could be added post wanderer 2d act; namely, an Exile automated ship that can do what you suggested and has a good cargo space. I made a model a while ago that could fit that role, which back then I called "Far Ek Tek 243":
![far ek tek 243@2x](https://user-images.githubusercontent.com/45330165/75105023-80e24780-5610-11ea-9580-66d5f3a195a7.png)
![far ek tek 243 thumb@2x](https://user-images.githubusercontent.com/45330165/75105024-82ac0b00-5610-11ea-8392-c0ab95bd9e2b.png)

**Comment by Zitchas** [comment]
I really like that ship, BeccaBunny,  but I don't think it is quite what we need here. As you say, that looks like it would fit something from late in the Wanderer Act 2 or Act 3 story. Actually, I'd suggest PRing the whole thing with a ping to Endless Sky and a message along the lines of "We don't know what you are doing for the Wanderers and Exiles, but here's a ship that might work nicely for them."

Although that being said, it occurs to me that it could serve this role - after all, the Korath Exiles did develope the base technology behind both Sestor and Mereti - might they not have at least one or two ships in their exile fleet that look like these automata ships? I suppose it more or less depends on when the automata developped their characteristic appearance - whether it was before or after the Korath lost control of them.

**Comment by NomadicVolcano** [comment]
The mining ship is critical since the Korath have no other source of materials. Their systems don't have an overly large amount of asteroids, so they'll mine nearby systems, especially Remnant. 

The world-ship(s) will be dealt with in a separate pull request. For this issue, I'd rather focus on the world-ship combat replacement. We won't really know what we need to do for the world-ship until after we have the new raiders. Also, it should be redone to look like a population center. The current one, and the new one you just showed, look like big warships.

**Comment by downRightCoder256** [comment]
well if that is so, we only need to find a ship suitable as a kor sestor mining drone, since model 8 already serves as a mining drone for mereti.since exiles are scavengers, and kor efret are surviving on ground, there is no real need for a mining ship until exiles recover automata manufacturing technology.

**Comment by NomadicVolcano** [comment]
The Korath Exiles do need to make ships, chairs, and chess boards. They can't steal fully-built world-ships and raiders from the Humans; it has to be built from something.  They cannot produce that out of the cold vacuum of space. To manufacture anything, they must leave their system to mine ores.

**Comment by geojak** [comment]
It's a game and fighting a world ship sounds epic and cool. We don't need perfect realism everywhere. Let the game be a game.

**Comment by Zitchas** [comment]
Don't worry. The world-ship will still be in the game, and you will still be able to find it and attack it if you really want to. (both the current 0.9.12 world-ship; as well as the new replacement world-ship)

Having a "Battleship Raider" to replace the current world-ship in combat situations is intended to make the game more fun, not less. My reasoning is two-fold:
1) Right now, the World-Ship is used anywhere the Korath Exiles need a capital ship to serve as opposition in a combat mission. Given that the player is usually flying at least a medium warship and probably a heavy warship by the time they really start fighting them; that means almost immediately.  This means that World-Ships, despite sounding epic and cool, are being used as common opponents. Being common opponents is pretty much the opposite of being epic and cool.
2) Right now the Korath Exiles basically have three ships: The Chaser, the Raider, and the World-Ship. This is an incredibly low diversity of ships, and it gets *really* old, really fast, if every time you face them you go up against just different combinations of these three ships. 

Having a "battleship raider" (and, more importantly, a larger array of ships that fill different use scenarios, many of which include combat support roles) results in two key changes to gameplay:
A) There is more variety in combat, because there are more ships that will turn up in a larger variety of capacities. This makes for more interesting fights, more challenges, and a much more dynamic environment.
B) It also means that when you do go up against a World-Ship, it is actually an Epic fight. Because the World-Ship isn't just the Korath's only capital ship that you fight all the time - it is basically the Boss Fight. They're big, they are tough, they are a challenge worthy of the name "World Ship." Taking down what amounts to a mobile space station that houses a significant portion of the Korath population is not something that should be an every day occurrence. But when/if it does happen, it should *feel* Epic, not just "ho humm, another world-ship looted."

For reference, see the "[Korath Exiles Expansion](https://github.com/endless-sky/endless-sky/pull/4987)". It adds a variety of beautiful ships that nicely expand the various roles that would be found in an exile/vagabond fleet, and provides a massive boost to the variety and challenges that a player will face when going up against the Exiles.

Just to expand on that, I continue to hope that the "Far Ek Tek 243 that Becca posted will end up as a new Korath Exile ship for the Wanderer Chapter 3 campaign.

**Comment by NomadicVolcano** [comment]
Closing all issues related to this account.

**Comment by Zitchas** [comment]
I would like to request that this issue be re-opened, as the issue continues to exist in-game.

**Comment by Bardagh** [comment]
Is this project up and running again? I strongly believe it should be finished & implemented.

**Comment by Zitchas** [comment]
It is currently on hold. We have copies of most of Nomadic Volcano's work (they provided .blend files and stuff for us to work with), but are currently holding off at Amazinite's request so that he could focus on getting a bunch of other stuff done for 0.9.13, and possibly get a bunch of one of the main human storylines done too. We definitely will be be continuing and resolving this issue.

If nothing else, the Remnant need more varied opposing ships because just chasers, raiders, and world-ships makes for boring combat. :)

**Comment by Amazinite** [comment]
The World-Ship has been replaced by the Dredger in any combat situations in Remnant missions.
