### ISSUE TITLE
human s-970 better than hai diamond regenerator

### ISSUE THREAD

**Issue by starmlerp** [endless-sky/endless-sky#4849]
question: as of now, human s-970 regenerator technology is more advanced by raw numbers than the hai diamond regenerator, even though humans are supposed to be technologicaly inferior to hai. why is that? is there an explicit reason humans would make a better regenerator than hai, or is it a bug?

**Comment by MasterOfGrey** [comment]
I posted this on Reddit, but they're actually quite a lot better. You can combine one each of the S series for significantly better results:

S-270+970 --------- Hai Diamond

Mass: 49 ------------ Mass: 49
Shield Gen: 174 ---- Shield Gen: 150
Energy Gen: -72 ---- Energy Gen: -54
Heat: 480 ----------- Heat: 540 (when recharging)

**Comment by Amazinite** [comment]
> I posted this on Reddit, but they're actually quite a lot better. You can combine one each of the S series for significantly better results:
> 
> S-270+970 --------- Hai Diamond
> 
> Mass: 49 ------------ Mass: 49
> Shield Gen: 174 ---- Shield Gen: 150
> Energy Gen: -72 ---- Energy Gen: -54
> Heat: 480 ----------- Heat: 540 (when recharging)

I wouldn’t exactly consider 16% more Shield generation at the cost of 33% more energy usage and a constant heat production instead of only producing heat when in use to be “significantly better.”

**Comment by DmitrySukhv** [comment]
The Hai so far are most militant race, making _constant war_ with their Unfettered siblings. I would ecpect great advances in shield-making and weaponry from them. It's a shame that their shields and weapons suck like that...

**Comment by Arachi-Lover** [comment]
> The Hai so far are most militant race

bruh

main Hai are one of the most peaceful factions in the game, they aren't *making constant war*, they are constantly having to defend and hold a chokepoint from attacks.

**Comment by DmitrySukhv** [comment]
@Arachi-Lover I know that the Hai are trying hard to be peaceful, but the fact is that they are the only species that have constant, intense warfare on their own territory. I supposed they must learn something from it... I did not count Kors and late Wanderers here - their war technologies are good enough for this very reason.

It looks like 'fettered' Hai have lost their ability to further evolve their war technologies, after Drak interference. *sigh*

**Comment by Arachi-Lover** [comment]
I see, misinterpreted what you said, sorry.

fair point, but I feel like the exact intention was to have the Hai be seen as stagnant. I always figured that since they always managed to keep the Unfettered at bay, and their current ships/tech were working for that purpose, they never felt the need to make something stronger.

a nicer generator being developed could be neat, though.

**Comment by MasterOfGrey** [comment]
> > I posted this on Reddit, but they're actually quite a lot better. You can combine one each of the S series for significantly better results:
> > S-270+970 --------- Hai Diamond
> > Mass: 49 ------------ Mass: 49
> > Shield Gen: 174 ---- Shield Gen: 150
> > Energy Gen: -72 ---- Energy Gen: -54
> > Heat: 480 ----------- Heat: 540 (when recharging)
> 
> I wouldn’t exactly consider 16% more Shield generation at the cost of 33% more constant energy drain and a constant heat production instead of only producing heat when in use to be “significantly better.”

I would argue that the heat produced only really matters under circumstances when they're likely to be recharging shields, ergo, the lack of heat when not charging is hardly much of a plus, and while it's 33% more energy it's not a large amount of energy in total actual numbers, so it's very unlikely to affect your generator space requirements.

It is better shield per mass and even better shield per mass-heat. The decrease in energy efficiency from 3.06 to 2.42 may not be negligible, but I think it's more than well paid for by the rest of it.

**Comment by waterhouse** [comment]
It helps to know the conversions from energy and cooling into outfit space.  I know things are discrete and you can't install half of a reactor, but it's still worth the rule of thumb.

Liquid helium cooling: 4140 in 40 tons = 103.5 cooling per ton
Korath small heat shunt: 810 in 7 tons = 115 cooling per ton
Korath large heat shunt: 3240 in 24 tons = 135 cooling per ton

Next, for energy, assuming

**Comment by waterhouse** [comment]
It helps to know the conversions from energy and cooling into outfit space. I know things are discrete and you can't install half of a reactor, but it's still worth the rule of thumb.

Liquid helium cooling: 4140 in 40 tons = 103.5 cooling per ton
Korath small heat shunt: 810 in 7 tons = 115 cooling per ton
Korath large heat shunt: 3240 in 24 tons = 135 cooling per ton

Cooling efficiency is reduced by mass expansions.  5 expansions gives 73% efficiency, for example.  We'll remember that in a bit.

Next, for energy, assuming you have to fully offset the heating that a reactor provides:
Boulder reactor: 1038 energy, 2040 heat, 90 tons.
- Boulder with (idealized) helium cooling: 19.7 tons of helium cooling to cancel the heat, so total 119.7 tons, which is 9.46 energy per ton.  With 73% cooling efficiency, that would be 8.87 energy per ton.
- Boulder with (idealized) large heat shunts: 15.1 tons to cancel heat, leads to 9.87 energy per ton.  With 73% cooling efficiency, you get 9.37 energy per ton.

Blue Sun reactors with large heat shunts yield 11.09 energy/ton, 10.68 energy/ton with 5 mass expansions, but those are less relevant to Hai / Marauder shields; I just mention them for reference.

Anyway, let's consider helium-cooled boulder reactors and imagine a little cooling inefficiency.  We'll call it about 9 energy/ton, and 100 cooling/ton.  In that case:
- S-970's effective mass may be increased by 360/100 = 3.6 for its extra heat, and by 54/9 = 6 for its energy drain.  If we imagine that it's constantly running—which I think is reasonable, since if you're not recharging shields, you're probably not in combat, and you probably have plenty of energy—then that's +138/9 = +15.3.  So we get 37+3.6+6+15.3 = 61.9 tons for 138 shield generation, or 2.229 shield gen per ton.
- Applying the same calculation to the hai diamond regenerator, the main wrinkle is whether we count the shield heat the same as heat.  Arguably,   Well, let's do it both ways.  49 (raw size) + 6 (energy drain) + 16.6 (shield energy) + 0 or 5.4 (shield heat) = 71.6 or 77 total tons.  Compare this to the shield gen of 150 and you get 2.09 or 1.95 shield gen per ton.

So the S-970 seems clearly superior to the diamond regenerator, even when I completely ignore the shield heat of the latter.  This is on top of being smaller, which makes it more flexible.
If I do a similar calculation with the corundum regenerator vs the S-270 (and just assume it's running full blast at all times), I get:
- corundum: 24.47 effective tons, 42 gen -> 1.72 gen/ton
- S-270: 19.2 effective tons, 36 gen -> 1.875 gen/ton

I don't think it's necessarily _wrong_ that the S regenerators are better than the Hai—one could imagine the Alphas captured some Hai generators, improved them, and gave them to the Syndicate in exchange for something else—but that they _are_ better, I wish to leave no doubt.
