### ISSUE TITLE
Please tag unstable releases as pre-release

### ISSUE THREAD

**Issue by ryantm** [endless-sky/endless-sky#4874]
I run a bot that automatically updates software for the Nixpkgs package repository and it uses GitHub releases information to decide to update. It would be helpful to us if you could mark your unstable releases as pre-release in GitHub, so we can filter them out.

https://github.com/endless-sky/endless-sky/releases

https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by MCOfficer** [comment]
Despite its a name, an unstable release is still a full release. All software packages except steam are being updated, including the Ubuntu PPA. I see no reason why Nix should reject it.

In case you're OK with a special switch for ES, you can rely on the fact that unstable releases always have uneven PATCH versions numbers (0.9.9, 0.9.11 etc).

**Comment by tehhowch** [comment]
Even the Steam release is updated, albeit only for the beta channel, for "unstable" releases.

**Comment by Synthetica9** [comment]
> Even the Steam release is updated, albeit only for the beta channel, for "unstable" releases.

Only the beta channel being updated sounds like an indication that this _is_ a pre-release?

**Comment by MCOfficer** [comment]
> > Even the Steam release is updated, albeit only for the beta channel, for "unstable" releases.
> 
> Only the beta channel being updated sounds like an indication that this _is_ a pre-release?

Depends... On steam, it is something akin to a pre-release. For all other packages (the ubuntu PPA, unofficial windows packages and debian (see #4630) ) it is a regular release. To me, Nix packages would fall into the latter category, rather than the special case steam.

**Comment by Zitchas** [comment]
Tech-savy people that are using something like nixpkgs are probably the sort of people that prefer to have the most up to date content instead of being stuck on whatever the current "official" steam build. I can't speak from experience, but that's what it seems like to me. 

It is also worth noting that the "beta" / unstable release isn't an experimental side-branch or anything, it is the "soon-to-be-official" release for those who want it a bit faster than they would otherwise get it. It typically has a lot of fixes and improvements over the stable release that preceded it, so I would say it is a clear step up. 

And for the technically inclined, it is worth noting that *all* of these are beta releases: We haven't hit version 1.0.0 yet.
