### ISSUE TITLE
Korath Space too small?

### ISSUE THREAD

**Issue by starmlerp** [endless-sky/endless-sky#4893]
**Is your feature request related to a problem? Please describe.**

Currently, the biggest species in game by sole number of star systems they possess are humans. By my understanding, this is because they are a species in development, and most changing: only half a millennium ago, they underwent a war (or a series of wars) 
that almost wiped them out in its entirety, and only recently underwent a conflict severe enough to have a third party engaged.

knowing this, it is surprising to see the Korath, an equally, if not more turbulent species take up so much less planetary space. 

keep in mind that Humans and Korath are the only two species in development;

Hai, despite unfettered and Korath raids, are more-or-less stagnant. they relied on 2 ship designs for centuries, developed two ships to stand the Korath raids, another two when they were introduced to humans, and will have developed four(?) more ships by the end of players storyline. nothing compared to the spaceship arsenal in human space.

Coalition, consisting of three species, has too been pretty stagnant ever since they defeated the quarg some years now (6000, I think?). after humans, they are probably the largest by planet space.

Remnant have separated from humans half a millennium ago, and have been too small as a community to develop consistently. as such, the only reason they are on the current tech level is mostly because of their salvaging and reverse engineering. 

Wanderers are, just like the Pug, extragalactical, meaning they are not native to the galaxy, meaning that their home world could have been just as big as humanity's. this is obvious due to the fact that they have probably the most advanced outfits players can acquire legally. 

my point is, how much space a species might need is determined by their development rate, which in turn affects how politically stable they will be (aka. how much will they war)

although one might argue that Korath have spiraled down into civil war exactly because they didn't have enough space, I don't find that quite convincing: the space Korath currently inhabit is on par with Hai, which we know have once inhabited space somewhat smaller than the one occupied by humans. it is quite obvious that the Korath have far too little space to properly develop in the first place, yet they managed to create weapons and technology powerful enough to alert the Drak. 

**Describe the solution you'd like**
1: reduce the human space
if the human space were smaller, it would be able to explain a lot of things clearly: the Hai would have had a lot less space to develop initially (they probably shared it with Sheragi at the time), the coalition would have had more space to prosper and Korath would only be short in space by a small factor. However, knowing how much content has been added to human space so far, and how the factions are positioned along it, I would consider this solution unlikely, since it may eventually require rewriting FW campaign entirely.

2: increase Korath space
looking at the background image of the starmap galaxy, it is easily noticeable to see that most of the systems in game are leaning to the left, meaning that there is a plenty of space on the right side of the starmap for Korath to possess.  Since korath campaign so far isn't so tightly tied to specific systems, and the Korath are on the edge of known space, expanding their territory should be easy enough.

3. add empty star systems beyond core
after some discussion with @Amazinite below, some empty star systems could be added to the right side of the galaxy. this would require the least amount of changes to be made to the game, and it would fit into the personalty of Achorns.

**Comment by downRightCoder256** [comment]
is @endless-sky responsible for Korath campaign? if the is, I would like to hear his opinion on my suggestion.

**Comment by Amazinite** [comment]
When various species discovered the Hyperdrive in years prior to game start:
* 120k - Hai
* 100k - Sheragi
* 73k - Builders
* 40k - Korath
* 17k - Saryd
* 14k - Kimek
* 10k - Arach
* <1k - Humans

The Korath are older than the Coalition. Much of their history is unknown to us. It is in all likelihood that they once had more space than they do now. 
Part of the reason that humanity has so many systems is due to the extinction of the Sheragi. If the Sheragi hadn't gone extinct when they did, it's likely that they would still be around just like the Hai are. If that were the case, then the Free Worlds would never have existed because the region of space that start out as the Free Worlds would actually be Sheragi territory, as the Rim was their home region of space and they likely had system in what humanity calls the South region.

**Comment by downRightCoder256** [comment]
> It is in all likelihood that they once had more space than they do now.

where is that space? we do know that Hai, despite being three times as long in space, have "once inhabited many worlds beyond wormhole". we do know that in all likelihood, they have inhabited at least the far north, and probably the current wanderer space, giving them about as much space as a third of coalition, or rim. and even without the rim, human space is quite sizable. we do know that the Korath didn't have the territory that the exiles are currently in, because the of the description of Far'en Lai.

> They have been told by the Drak to not drain this planet of it's resources like they did in their old territory or they will be destroyed

"Old territory" implies that this is new territory, and since the Dark banished them after their civil war, it is that point in time that we are looking in.

>  It is in all likelihood that they once had more space than they do now.

unless it is human space, it must be in the rest of the galaxy, which could just be uninhabited systems.

> When various species discovered the Hyperdrive in years prior to game start:
120k - Hai
100k - Sheragi
40k - Korath
17k - Saryd
14k - Kimek
10k - Arach
<1k - Humans

I could find any information on anything like this. the game's wiki only talks about human space. there is nothing about any other aliens (except Quarg) even mentioned in there. Why isn't this knowledge easily available, especially since the game is open-source? it could greatly reduce mishaps like these.

> If the Sheragi hadn't gone extinct when they did, it's likely that they would still be around just like the Hai are

...What?

**Comment by Amazinite** [comment]
> where is that space?

Does that information matter? 

> I couldn't find any information on anything like this

Much of this information is spread around in game, but the exact numbers on when those factions discovered the Hyperdrive come from this comment here. https://github.com/endless-sky/endless-sky/issues/2540#issuecomment-302976860
Not all of the game's lore is or even should be on the wiki. Nearly all of it is found within the game itself, and as per #3663, the goal is for all of the game's lore to be discoverable within the game itself.
It's also important to note that the wiki here on GitHub is largely intended to be used as a tool for creating new content, not as a place to document the entirety of the game's story and lore. If you're looking for that, you're better off looking to the [Fandom wikia](https://endless-sky.fandom.com/wiki/Endless_Sky_Wikia).

> ...What?

Speak with the Unfettered for the first time and finish Rim Archaeology to hear about the Sheragi.

The Sheragi were an alien race that use to inhabit the Rim. After only about 1,000 years, they went extinct as a result of a civil war. We learn from the Pug during the Wanderer campaign that this has had a great impact on the Drak/Archons, and it's likely that the extinction of the Sheragi has shaped much more of the galaxy as we know it today than one would expect.

**Comment by downRightCoder256** [comment]
well, its kinda odd that players and newbies like myself would only be able to find such information in a 3-year-old closed issue. couldn't such information be put in a wiki with a spoiler warning for the time being (at least until #3663 is implemented)?

> Speak with the Unfettered for the first time and finish Rim Archaeology to hear about the Sheragi.

yes, I have. I wouldn't even have known about the Sheragi if I haven't. it's just that your wording got me a bit confused (you basically said :"if Sheragi hadn't gone extinct, whey would still be around" which doesn't quite introduce any new information, just states the obvious). 

> We learn from the Pug during the Wanderer campaign that this has had a great impact on the Drak/Archons

The Pug will only mention Drak as protecting species from extinction, and having "failed, many times". in a different dialogue pattern, they will also describe them as "mopey", and too depressive to talk with. MZ also mentions in the same issue that the Achorns have had issues keeping things together lately, because new species have been appearing more and more often. If that is so, Achorns may have just not had enough time to separate rim from the rest of space to prevent humans from coming in there.

galaxy beyond the core could then be made as some some sort of "in case of emergency, place new species here" zone. stars could be named after human star names, because those are the ones that matter to the player.

**Comment by Amazinite** [comment]
> well, its kinda odd that players and newbies like myself would only be able to find such information in a 3-year-old closed issue.

Like I said, much of that information is already in game, e.g. the age of the Sheragi. I simply cited a comment that had all those numbers together. 

> it's just that your wording got me a bit confused (you basically said :"if Sheragi hadn't gone extinct, whey would still be around" which doesn't quite introduce any new information, just states the obvious).

Key words "when they did" in my statement. That is, if they had overcome the situation that actually did make them go extinct, it's unlikely that they'd have gone extinct otherwise.

**Comment by Zitchas** [comment]
Your dates are... not entirely accurate. Just to clarify one in particular, the Remnant separated from humanity during the Alpha Wars, which happened roughly four centuries prior to the start of the game. They took a few years to get established, but they have had close to 4 centuries of frantic development. (they are small, so they can't research everything, but they are basically a group of fanatics who believe they are humanity's last, best hope in surviving the Alphas and other threats out there. And this is reinforced by the fact they live in the Ember Waste - which they have studied long enough to have realized that it is the remnants of someone elses' war. A war that destroyed countless systems and changed countless more. That's the sort of threat they envision faces humanity, and they still believe that they are the only ones that can ensure humanity survives it. For most of their history the Remnant have been on a war footing, originally against un-named threats, and more recently against the Korath.

1) I don't think that anything is gained by reducing the number of human systems. There is a thousand fold more stars in this half of the galaxy than we currently have systems. I could see potentially increasing the density of human space (as in, shrinking the area that it currently covers) so that other areas (Korath in particular) can be expanded, but there should not be an actual reduction in the number of human systems.

2) When they talk about how they were kicked out of their old space, I always assumed that they were referring to the areas currently controlled by the automata ships. That being said, I think that increasing the density of korath space would probably be a good thing. In this case, it would be adding systems to bring it up to something comparable to at least half the number of systems in human space. Just to be clear, this is "the total of all korath systems - including all the different korath groups" being equal to about half of human space or slightly more. I have always found it amusing that getting across korath space is so much faster than crossing human space - although it takes about the same amount of fuel because the player is likely using a jump drive instead of hyperdrive.

3) Systems beyond the core are being worked on, I'm sure. I don't see the need for the community to intentionally just fill them up right now; but as we have new aliens and stuff to introduce, that's where they go. It'd be good to have another large group (as in humanity or coalition sized) to go over there, along with several smaller ones, but I don't think that'll be a problem. There are plenty of people working on large plug-ins and large races that could easily fit into it.

**Comment by downRightCoder256** [comment]
> Your dates are... not entirely accurate. Just to clarify one in particular, the Remnant separated from humanity during the Alpha Wars, which happened roughly four centuries prior to the start of the game. 

I wouldn’t quite agree with you. the game explicitly says they separated during 1st alpha war. wiki doesn’t state when did it end, but it clearly says it started in 2450 (game starts in 3013), meaning, for them to have left human space 400 years ago, that war ought to have lasted at the very least 163 years, a pretty unlikely number to assume for a duration of a modern war. Not to mention, you don’t really have to assume anything, because the game states it obvious that they left human space MORE that 500 years ago. once you land on remnant planet for the first time and get blood tested, they will sing to players, from which he concludes the following:

> As they continue to sing, you begin to piece together their story. They are the descendants of people who fled to this region of space through an unstable wormhole at the peak of the first Alpha War, which means they have been here for **more than half a millennium. **

> I don't think that anything is gained by reducing the number of human systems.

i didn’t quite mean reducing, but rather annexing. take the systems from humans and give them to other species, particularly the Korath. And, as i’ve stated in the end, it is unlikely for that change to be accepted, mostly because how FW campaign is hard tied to the current organization of the stars.

**Comment by Zitchas** [comment]
I was nitpicking the fact that the initial post says "half a century ago." Clearly, four centuries is much close to half a millennium than 50 years, but yes, you are correct. I mis-spoke.

For the later part, I continue to disagree. Annexing a bunch of human systems to have them instead be korath is just as bad. While The "main" story of ES is the human civil war, we want it to have room to have a lot more than "just" the civil war. And that means having space for a very wide range of human planets. If we reduced that number significantly, then we would lose out on that diversity, and the galaxy would be that much more compact and boring. 

If we want to make the systems more dense, sure. Let's reduce the distance between them and them add more systems onto those areas that need it (such as Hai, Korath, and Wanderer space, but probably Coalition space too). That'd work much better. (or alternatively, we can stretch up the galaxy map image and then proceed with adding new systems)

**Comment by downRightCoder256** [comment]
ah, so a century IS 100 years. my bad :(

in terms of planets, i have from the beginning been saying that annexing is bad, or, more specifically, unlikely to get in the game. i was just keeping it as a last resort option if densing up the korath space proved unviable, but no, i have never been actively promoting it. one trend i can see appearing is stars being closer together the shorter the distance to the center of galaxy (sagittaurus *). this is most notable in wanderer and coalition space.

**Comment by downRightCoder256** [comment]
will edit my question for accuracy

**Comment by MasterOfGrey** [comment]
Without dramatically changing the star map, mostly by just moving Oblate, Alcyone and Durax down a bit, I could see 19 systems being added to Korath space without seriously impacting things. You can already make the jump with a jump drive at all the nearby points anyway, so you don't lose any true isolation by pushing a few more systems into the void between Korath space and everyone else. Plus, they're in the more dense part of the galaxy, so a slightly higher star density makes sense.
