### ISSUE TITLE
AppImage fails to run on Ubuntu Xenial

### ISSUE THREAD

**Issue by probonopd** [endless-sky/endless-sky#4923]
**Describe the bug**

Fails to run on Ubuntu xenial:

```
/run/firejail/appimage/.appimage-9134/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /run/firejail/appimage/.appimage-9134/AppRun)

/run/firejail/appimage/.appimage-9134/AppRun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9134/usr/bin/../lib/libSDL2-2.0.so.0)

/run/firejail/appimage/.appimage-9134/AppRun: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /run/firejail/appimage/.appimage-9134/usr/bin/../lib/libpng16.so.16)

/run/firejail/appimage/.appimage-9134/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9134/usr/bin/../lib/libpulsecommon-11.1.so)

/run/firejail/appimage/.appimage-9134/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-9134/usr/bin/../lib/libbsd.so.0)

/run/firejail/appimage/.appimage-9134/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-9134/usr/bin/../lib/libsystemd.so.0)

/run/firejail/appimage/.appimage-9134/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9134/usr/bin/../lib/libsystemd.so.0)
```

**Additional context**
All additional information can be found at https://github.com/AppImage/appimage.github.io/pull/1937, including a log file of the test run.

**Comment by MCOfficer** [comment]
> works on my machine

i will take a look on a VM.

**Comment by MCOfficer** [comment]
I'm getting a segfault now on a stretch server, but that might be because it's headless. Can you give this a try? https://github.com/MCOfficer/endless-sky/actions/runs/56576245

**Comment by probonopd** [comment]
Thanks @MCOfficer, I have triggered a new run of the automated test.

**Comment by probonopd** [comment]
Getting

```
/run/firejail/appimage/.appimage-9276/AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /run/firejail/appimage/.appimage-9276/AppRun)

/run/firejail/appimage/.appimage-9276/AppRun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9276/usr/bin/../lib/libSDL2-2.0.so.0)

/run/firejail/appimage/.appimage-9276/AppRun: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /run/firejail/appimage/.appimage-9276/usr/bin/../lib/libpng16.so.16)

/run/firejail/appimage/.appimage-9276/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9276/usr/bin/../lib/libpulsecommon-11.1.so)

/run/firejail/appimage/.appimage-9276/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-9276/usr/bin/../lib/libbsd.so.0)

/run/firejail/appimage/.appimage-9276/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-9276/usr/bin/../lib/libsystemd.so.0)

/run/firejail/appimage/.appimage-9276/AppRun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9276/usr/bin/../lib/libsystemd.so.0)
```

Please make sure that no libraries newer than what comes with xenial get pulled in, e.g., from PPAs.

**Comment by MCOfficer** [comment]
That is weird, the AppImage is built on a [GitHub Actions runner](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1604-README.md). The only modification is an `apt install`, but the entire `sources.lists.d` directory is being pruned before that, so the only package source should be the official repos. (and yeah we do run `apt update`).

I'm pretty much at a loss here, any ideas?

**Comment by probonopd** [comment]
That image seems to have a _lot_ of additional software that does not come with xenial from Canonical by default. Specifically I would assume this to cause at least the libstdc++ issue:

* GNU C++ 7.4.0
* GNU C++ 8.3.0
* GNU C++ 9.2.1

**Comment by MCOfficer** [comment]
i'd have to test that... it would certainly simplify things since we've been having a number of issues with the action runners' specialties. The CD is a construction site anyways, so this might take a while.

**Comment by probonopd** [comment]
Thanks for considering.

**Comment by MCOfficer** [comment]
That came out way hackier than expected. Can you give this one a try?
https://github.com/MCOfficer/endless-sky/actions/runs/58116055

It's built in the official xenial container, with no PPAs whatsoever - this pretty much *has to* work.

**Comment by probonopd** [comment]
Thanks @MCOfficer. Triggered a new test run but it looks like Travis CI has a hiccup at the moment, please ping me again in case I forget.

**Comment by MCOfficer** [comment]
@probonopd FYI, travis is back and the build went through - same error. To be completely honest, i'm close to capitulating. There's hardly any way for me to debug this, and i have 0 idea why it's still happening.
[
Here's my last shot](https://mcofficer.me/download/Endless_Sky-ca96302-x86_64.AppImage): an AppImage built by hand inside the `ubuntu:xenial` image. No CI shenanigans this time. The only curveball is that the script extracts linuxdeploy, because there's no fuse inside the container:
https://github.com/MCOfficer/endless-sky/blob/cc51f0b222c91cfbefa750966570ece6bcc07ab6/utils/build_appimage.sh#L20-L26

If this doesn't work either, perhaps your CI is outdated? I cannot possibly imagine the build tool linking against anything other than the latest `g++` package from the xenial repos.

**Comment by probonopd** [comment]
Maybe you can run your AppImage on a Ubuntu xenial Live ISO for local testing?

**Comment by MCOfficer** [comment]
I just did - i had dreaded it because i've had... difficulties getting VirtualBoxes kernel modules to work in the past, but surprisingly it worked out immediately (thanks for making me try it again). 

As expected, the 0.9.11 AppImage built on bionic failed with the error you posted. But all the other images i posted in this issue work flawlessly.

The VM i used is a completely unmodified (apart form VBox guest additions) image from [osboxes](https://www.osboxes.org/ubuntu/), the one titled "Ubuntu 16.04.6 Xenial", 64bit.

**Comment by MCOfficer** [comment]
I did some more research, and the only alternative i see is to statically link against a musl-based cross-compiler. That's a rabbithole i'd rather not go down unless it's absolutely necessary.

Since 0.9.12 is around the corner, i'll PR my first fix (simply change the runner OS to xenial), until we have more clarity about the origin of this issue.

**Comment by probonopd** [comment]
Thank you. Will it be available at https://github.com/MCOfficer/endless-sky/releases soon? (I never find it in "the other place".)

**Comment by MCOfficer** [comment]
The PR has been merged, so it will be available at [the releases page](https://github.com/endless-sky/endless-sky/releases), not on my fork. You can already test with the latest CD build from the [actions page](https://github.com/endless-sky/endless-sky/actions?query=workflow%3ACD). It should be the same as [this one](https://github.com/endless-sky/endless-sky/issues/4923#issuecomment-599425380) though.

**Comment by MCOfficer** [comment]
@probonopd can you confirm this is still an issue? https://github.com/endless-sky/endless-sky/releases/tag/v0.9.12

**Comment by probonopd** [comment]
Thank you very much @MCOfficer it is working now :+1:
