### ISSUE TITLE
"Captain's Log" storing key story events to remind you where you are

### ISSUE THREAD

**Issue by anonybosch** [endless-sky/endless-sky#494]
Day after day the players who congregate at Steam post requests for help finding the next thread of the story. At various points in the story they reach a dead-end. They generally get some sort of hint or outright help for how to proceed to the next mission. Then they reach a fresh impasse. I've found myself in the same situation repeatedly.

Would it possible to "toss the player a bone" after the player has wandered aimlessly looking for the next mission? 

After a certain number (tbd) of days without finding the next mission the player would encounter an acquaintance who would tell the player "(character) was looking for you on (planet) a couple of days ago." (Or words to that effect.) The player could then have some idea about how to resume the story.

This would help relieve some of the frustrations expressed by way more than a few players.

**Comment by brick96** [comment]
Maybe an event set to happen about 1-2 months after each mission that is stopped if they take the next 1

**Comment by natangold** [comment]
So... something like the "missions" informing you "Hey, we got that [ship / weapon / whatever]? Or a comm message like those offering the pirate recon missions?

**Comment by Wrzlprnft** [comment]
Maybe just displaying the text of the mission of the map->job board. On several occasions i saw answers basically quoting those descriptions :)

**Comment by anonybosch** [comment]
@brick96 Some missions end naturally or just dead-end by themselves; the "Splinter", "Terraforming", "Kestrel testing", (no need for "helpers" for those), but bringing the war to an end seems to require chasing down very illusive characters. And they get more illusive as time goes on.

The early FW missions arrive in a fairly timely manner. There's some element of chance as to what or where the next mission will be, but they all happen in a moderately short time span. But then the story lags. Katya's been captured. Tomek's been placed under house arrest. The Wolf Pack assigns a few missions. Then they say they'll contact the player again. The player does the Winter missions. The player is then left to squander time trading up and down the Rim... waiting... looking in every spaceport in the hopes of resuming the story. 

After a protracted search of the Rim the player still has no idea how to resume the story. At that point, perhaps, a "chance encounter" type message, or a summons from the Council, or something...

**Comment by endless-sky** [comment]
If they say they'll contact you when more work is available, that's what
they do - you never have to visit spaceports to pick up the thread again. I
think when people get lost, though, it's usually because they failed a
mission without realizing it, or were told to go to the spaceport to get
the next mission but did not do so, or something like that.

The planned addition of a "logbook" with automatic entries whenever the
plot advances will help with that, but no matter what it's going to be
possible for the player's actions to interrupt the story. For those cases,
that's why there's an autosave to revert to.

**Comment by Thunderforge** [comment]
@endless-sky When you said that they "were told to go to the spaceport to get the next mission but did not do so", does that tend to be with missions that can only start from a specific planet's spaceport bar? If so, that could definitely be a problem. A logbook would be helpful, but I wonder if there is a bigger issue there. Are there some missions that the player would legitimately want to delay? 

If so, then spaceport bar "when you're ready" makes sense, and a reminder that they can go back there would be helpful. If they wouldn't really want to delay the mission, then why not have the next mission just start in the main area of the spaceport? That way, the mission ends, then they are given the next mission and there is no chance of them missing it because they didn't click on the "spaceport" button.

**Comment by Tadrix** [comment]
Having played a while and being something of a completionist, it occurred to me that a journal would be very handy for tracking information player's given and missions he's completed (note that it would be something different than missions screen in starmap, which is useful in its own right).

I imagine it as something having 5 tabs:
**Current missions**: Basically same info as active missions on the map, only without map, but arranged in a table: Name, Source, (Requirements,) Waypoints, Destination, and clicking on it, description in the bottom panel, nothing really new here.
**Completed missions**: Only visible and non-repeatable missions which are done listed. (This would be great when loading an old save.) Nice touch would be to list quest strings together as one, than, when selected, in the bottom or side panel show them all together, but it's probably not feasible as missions in data files currently aren't identified as belonging to a string — or maybe we could do it for missions with the same visible name.
**Failed missions**: As in active. Only visible and non-repeatable missions which are failed listed. (Also useful from time to time — and if someone complains that he's not offered a mission, this is a way to check if it's possible at all — just ask the player if something is listed under failed missions.)
**Information**: Here could go stuff from completed invisible missions, for example, "Ulrich told me of his meditation near a cloudy star along the Rim, about fallen civilization. To him it felt real, so There Might Be Riots started to speak against the war." Well, that's a crappy example, but I meant things that the player could read if (s)he took a break from the game, forgot some details and needed to immerse himself/herself in it again.
**Notes**: An empty page. Allow player write in it whatever desired.

**Comment by guillochon** [comment]
I also think this is pretty much a necessity for 1.0. People will drop the game for a bit and come back to it, it's nice for game longevity to give them a way to pick up where they left off without having to dig through data files.

**Comment by Wrzlprnft** [comment]
it's on the roadmap https://github.com/endless-sky/endless-sky/issues/907
