### ISSUE TITLE
Wrong number of non-hyperdrive ships departing

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#4949]
**Describe the bug**
It seems that the "If you take off now you will launch <x> ships that will not be able to leave the system" only takes into account the ships that have that warning displayed, so that if e.g. a non-hyperdrive ship is only powered by solar energy but doesn't have enough energy to power the thrusters at full speed that warning will be displayed instead, and the game will not count it in the message

**To Reproduce**
1. Buy a ship
2. Outfit it so that it has no hyperdrive, less solar generation than the energy required to move and no batteries
3. Depart and see the message not appearing at all
4. Now buy a normal ship and remove the hyperdrive
5. Depart with both ships and see the counter only showing that 1 ship with no means of leaving the system is departing

**Expected behavior**
The game should count all the ships that can't jump, even if a warning overrides the hyperdrive one in the shipyard/outfitter view
**Screenshots**
These four ships have no hyperdrive, and two make less solar energy than the thrusters:
![Screenshot (1487)](https://user-images.githubusercontent.com/45330165/77522458-943d3880-6e84-11ea-87f7-07bc2e994d1a.png)
Message when departing with the 4 ships:
![Screenshot (1488)](https://user-images.githubusercontent.com/45330165/77522577-bf278c80-6e84-11ea-9b53-4c017c4d555d.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: current nightly
 - Version: 0.9.11

**Comment by downRightCoder256** [comment]
Tested it on MacOS 10.15.3 "Catalina", happens there too. It is definitively a bug. It doesn't even display the warning if all the ships are insufficiently powered, and it appears when any other warning overlaps it.

**Comment by tehhowch** [comment]
I believe this is newly added in 0.9.11... mind verifying?

**Comment by Amazinite** [comment]
Would be the doing of 2ac2482, I imagine.

**Comment by tehhowch** [comment]
We had flightchecks and pre-launch warnings before that commit, too.

It shouldn't be too complex of a fix IIRC.

**Comment by Amazinite** [comment]
> These four ships have no hyperdrive, and two make less solar energy than the thrusters:

Looks like this is the cause of the issue. 

PlayerInfo::FlightCheck right now calls Ship::FlightCheck for all unparked, undisabled ships in-system. 
https://github.com/endless-sky/endless-sky/blob/3e64028836dcef817ee469c750756f6d7eca3be2/source/PlayerInfo.cpp#L781-L786

PlanetPanel::TakeOffIfReady then counts the check of each type that was returned and uses that in order to determine the number of ships to show as being unable to leave the system.

https://github.com/endless-sky/endless-sky/blob/3e64028836dcef817ee469c750756f6d7eca3be2/source/PlanetPanel.cpp#L273-L278

The issue though is that Ship::FlightCheck doesn't return every issue with a ship. It only returns a single warning, and whichever warning pops up first is the warning that is returned for that ship. In this case, the check for low energy is done before the check for no hyperdrive/jump drive.

https://github.com/endless-sky/endless-sky/blob/3e64028836dcef817ee469c750756f6d7eca3be2/source/Ship.cpp#L802-L812

It would appear to me that in PlanetPanel::TakeOffIfReady, the number of non-jump-ready-ships is the only time that the warnings are being counted. Therefore, an easy solution would be to simply have the check for a hyperdrive or jump drive be the first warning condition.

**Comment by beccabunny** [comment]
This probably doesn't make sense, but if we move the hyperdrive check to be first, could it perhaps happen that if you have a ship with no thrusters and no hyperdrive, but since only the hyperdrive is checked it shows the "you will launch x ships" dialog instead of the conversation that keeps you from departing?

**Comment by Amazinite** [comment]
No thrusters is an error, not a warning, and errors prevent you from leaving the outfitter. The only warning with a dialog on depart is the no hyperdrives one.

**Comment by downRightCoder256** [comment]
> If in the future we have multiple dialog pop-ups that reference the number of warnings for your ships, a better solution would be to return all the issues with a ship, not just the first issue.

I could imagine a solution using a bool array, where element at each index would represent a certain warning/error, although such a solution would be quite abstract, and would require quite a lot of documentation, in case someone else decides to fiddle with it, not to mention it wouldn't fit the currently clean and readable style of code present in game.

maybe have a bool function for each and every warning ?

**Comment by tehhowch** [comment]
I didn't modify the order of warnings, or allow displaying the tooltips from multiple warnings, but I did fix the issue of not reporting ships that can't leave the system when they have a different warning displayed.

For a future unstable release, we should evaluate the various flightcheck warnings and determine a valuable "reporting order". We can then update the `Ship::FlightCheck` logic to perform the checks in this order, and simultaneously verify that the `if` condition expressions still make sense now that they are always checked, or whether they need to be updated too.
