### ISSUE TITLE
A simple(ish?) fix to make the outfitter screen much easier to read

### ISSUE THREAD

**Issue by DingusShingleton** [endless-sky/endless-sky#500]
Simply move the details of the item you are inspecting to the right side next to your ship description, and leave the outfit icons where they are, rather than having them fly around as your selection changes. This also makes it WAY easier to compare outfits by alternating between them, as the relevant numbers stay in the same place.

 Also, increase the brightness of the outfit you have selected to make it easier to pick out at a glance. This will also differentiate it visually from an outfit you only have installed.

You lose a column or two of outfits, but the gains in visual feng shui far outweigh the loss IMO

stealth edit: Also for what it's worth, listing thrust and steering in two different sections would be a huge improvement to alternating thrust and steering units.

 To wit: 

![outfitter](https://cloud.githubusercontent.com/assets/16414093/11977650/ebce65a2-a984-11e5-82fb-59afef168982.jpg)

**Comment by brick96** [comment]
Yes please, and comparisons im the outfitter too

**Comment by endless-sky** [comment]
The outfitter is designed to be usable even on a relatively small screen, e.g. 1024x768 or 1280x720, less than a third of the dimensions of your screen. At that resolution, you might not even be able to fit three columns of outfits, and in addition, the data for the selected outfit would not all fit on the screen at once.

**Comment by DingusShingleton** [comment]
My screen is only 15", surely that's not that huge a screen. It is 4k, but it isn't some giant 27" behemoth... or bacrian for that matter.

**Comment by sanjayatio** [comment]
Mine is 14" at 1366*768 and I put the windows taskbar on the left side (rather than the bottom default).
With this configuration, currently I can see 5 columns --> implementing your idea will bring it down to 3 columns.
Further:
- as someone who carries a laptop around on daily basis, I actually prefer smaller laptop.
- I don't like to scroll too much.

I agree with you though, the dynamic flow is kind of annoying.
My idea would be tabs - alternating description on the right side between ours & shop's.

==============================================

> ... as the relevant numbers stay in the same place.

Not true, with different length of description and different kinds of attributes an outfit has, the scrolling wheel will need some oiling; however
> ... the data for the selected outfit would not all fit on the screen at once.

ignoring aesthetic factor and putting the description at the bottom would minimize the issue, imho.

**Comment by DingusShingleton** [comment]
Wanting to survey the situation firsthand, I busted out my old 13" macbook to do a side by side, and lo and behold, as @sanjayatio said, there are 5 columns. But those icons are huge!! way bigger than they need to be if you ask me. So I took my screenshot from above, lopped off the leftmost column (since 4k is a wider aspect than that of the macbook's 1200x800) and put it up fullscreen on the mac. It is still perfectly readable with the verticle data, 5 columns of icons, and pleny of room for all the stats and descriptions. And if there is a description too long, as @sanjayatio suggested, putting it after the stats with a small scroll bar would solve that nicely.

Here is the cropped 4k screenshot at fullscreen on 1200x800 (subway card for scale):
![12374747_10156344790335481_1466675403861655843_o](https://cloud.githubusercontent.com/assets/16414093/11988980/479e0178-a9c4-11e5-8fc2-8abf2029c5de.jpg)


And here is the actual game on the same screen:
![1292983_10156344793520481_7591884693399553445_o](https://cloud.githubusercontent.com/assets/16414093/11988982/52100016-a9c4-11e5-8416-07f1bec7e80e.jpg)

I don't think there is a huge difference in readability between the two. And if some people really do want the giant icons, perhaps there could be a toggle in the menu to go back to the current implementation? I don't know, maybe I'm crazy. I mean at 75 hours played I am *very* comfortable with the outfitter as is, and I get around in it just fine. But I remember my first hour or 5 of playing, it took a while to get the hang of. And if nothing else some sort of compare function in the actual outfitter would do wonders.

**Comment by jafdy** [comment]
How about letting everyone have there own way and make the zoom function zoom out as well as zoom in.

**Comment by bobafetthotmail** [comment]
I would add a tab bar on top with "weapons", "ammo", "stuff", "stuff2" and so on to clear up and make easy access.

If I need say Engines, rifles or maps, I need to scroll around lots. With a tab bar you just click and bam! it's there. Maybe even with a hotkey.

Then keep the system info bar at the bottom, IN A FIXED PLACE, if I scroll it should remain there at the bottom, not scroll up with the page. It's confusing and annoying.

Also, the system description text could really use the whole space, not half of it (as shown in the screenshot posted by DingusShingleton). 
Agree on fixed space with its own scrollbar if needed, makes no sense to waste space like that for a description that won't be read more than a few times by players. (not saying that it's not important to have good descriptions, just saying that a clear UI is more important).

**Comment by DingusShingleton** [comment]
The reason there is extra space is that not all descriptions are that length, some are longer. But I mocked up that in photoshop before @sanjayatio suggested putting the description on the bottom anyway, which overall is a better idea.

**Comment by bobafetthotmail** [comment]
No, I meant in the actual game there is extra space on the sides of the info panel, as shown in your "actual game with the same screen" screenshot. That's a wasted column's worth of space right there.

When you click on an item that is on the left, everything looks fine but there is a bunch of wasted space on the right side of the item info panel.
When you click on an item on the right, the description and other info columns are moved to the right, leaving wasted space to the left.

With a fixed bar that does not do this "move stuff around" trick, you can get more horizontal space for the description, which means you can get it to occupy less space, without having to place it inside its own scrollable box.

Although I'm suspecting that the current arrangement was done because the UI itself does not scale that well both in smaller and in bigger screens, and that's probably the true culprit. 
In my game (I run it windowed), when I resize the window and there is less space than the three columns needed for the description stuff, I get the rightmost one that overlaps the ship's stats (the gray column).

If you add a column on the side, this lack of flexibility is less apparent, as you will see less icons, but descriptions won't overlap anything.

So I'm changing my mind about the fixed bar on the bottom. Giving how the UI seems to behave, the easiest thing should be adding a bar to the side.

**Comment by frameworld** [comment]
It would be neat if the icon of selected item would also appear in the vertical description column, if it is possible with space.

I'd also like if there is a featured-line on top of the list which shows not purchased licenses or Star-maps (one-time purchasable) followed by rare items until the line of 5 is full.

For comparison of items, I'd like to compare DPS or "damage per outfit space" both.
Because "damage per outfit space" doesn't exist jet, there should be easy mod-support with +-*/ operations, variable=value inserts and use of existing variables.

There can be a config file which defines which stat=value pairs are shown.
"damage/outfit-space" = ("dps" / "outfit space") - the part in brackets is evaluated.

**Comment by jmhorjus** [comment]
Has anyone started work on this?  
Just a anecdote: My brother loved EVN, but said he'd stopped playing ES after about 30min. When I asked him why he said "the UI was just terrible, you couldn't see what you were buying in the outfitter. When I pressed him for more details about what was wrong with the UI he pointed out this precise issue. Then he made me renew my ENV license, load it up, and start a new game just so that he could show me how low the resolution of that game is compared to what we're used to on modern monitors and how they use exactly the layout being suggested here to save a lot of space in a low res environment. >_<

Personally I didn't care, but to people who are aware of these things apparently it's a big deal.

**Comment by jostephd** [comment]
Even if the new layout doesn't work on small resolutions, why not use the current layout on small resolutions and the new layout on large resolutions?

**Comment by TeoTwawki** [comment]
@ everyone busting out their low end displays: now try it on a1024 pixel width. When looking at columns and width, that's the dimension that matters.

I think tabbed UI multiple icon sizes/scale is the way to go.
