### ISSUE TITLE
Infinite Submunition weapons not working correctly

### ISSUE THREAD

**Issue by Janaszar** [endless-sky/endless-sky#5022]
When using looping submunitions, such as A dying and becoming B, which dies and becomes A and so forth, the game crashes at some point.
Errors.txt leaves nothing if it crashes on loading.
If the game loads, clicking on the weapon in the outfitter crashes the game, the only warning found in Errors.txt being `Warning: maximum projectile velocity is 450000`.

**To Reproduce**
The second error is hard to reproduce, as I've worked around it and cannot seem to get it to trigger again.  I was working on developing this weapon for several hours, and once I got it to work, left for several hours and now do not know what to change to get it back to not working.

As for the first error:
1) Create a weapon using a submunition spawn on death.
2) Have that submunition create another submunition on death, with the submunition being the same name as the current submunition.
3) Start the game
4) Game crashes at 90~95% loaded (2~3 ticks from completing the circle)

**Expected behavior**
Previously, going back several years, infinitely looping submunitions would work.  They would be usable weapons, with submunitions continuing to spawn, and the outfitter data would calculate up to ~500 iterations as damage.

**System (please complete the following information):**
Steam Beta

**Link to weapon file**
[AAA Square Laser.txt](https://github.com/endless-sky/endless-sky/files/4540372/AAA.Square.Laser.txt)
This is the completed weapon.  Remove the later parts of the submunitions and loop B into A for the infinite submunition error.

**Comment by tehhowch** [comment]
You can start the game from a terminal with `-d` as a command line parameter to enable it to print out which files it parses, to debug load crashes. This probably won't help much, as the game is likely crashing when creating the outfit in question.

Probably if you update to the latest nightly you will get better behavior on load-time crash as well, since I recently restored error messaging in that scenario.

As far as the actual issues, they sound like bugs but aren't higher priority than other ones out there. Thank you for filling a report; I'll investigate further when I can.

**Comment by Janaszar** [comment]
Took me a bit to do it from the command line (did you know you can just drag and drop the .exe into CMD and it will parse the location to run it?  I didn't...)

Used the "continuous" build, was given this result, where it just crashes on parsing the new gun.
![Untitled](https://user-images.githubusercontent.com/32232509/80400076-4a32e280-8888-11ea-88c9-6dc68431429d.png)

I looked for errors.txt, but the only one I saw was the same from the steam version, and that was (until overwritten by the -d command?) from ~12 hours ago.

**Comment by Amazinite** [comment]
It looks to me that this is simply because at no point are you reducing the velocity on the laser. Submunitions add their velocity to the velocity of their parent, so each time it reaches submunition A, it's adding 300 velocity to the projectile. If you change `"velocity" 0` to `"velocity" -300` on the turning submunitions, this should work.

**Comment by Janaszar** [comment]
I have had it use `"velocity" -300` before, and it still works, but not to the point where it's infinitely repeating properly.  
I only included that "Max velocity" error message as that's the only one I've seen when I was working on developing the laser.  My memory isn't perfect, but I think it happened when I used very high drag rates.  (Not to mention, due to the turns, while velocity seems like it is increasing, it's actually losing and gaining velocity in different directions that eventually pass the origin again)

**Comment by Amazinite** [comment]
@Janaszar Would you be able to retest your weapon now that #5079 has been merged? Looping submunitions should no longer crash the game for simply existing, and using the suggested `"velocity" -300` change on the off-submunition should avoid the velocity error.
