### ISSUE TITLE
Shield Capacitors

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#503]
Don't know if that is the proper terminology, but something that increases shield strength instead of just making it charge faster

**Comment by endless-sky** [comment]
The reason there are no outfits in the stock game data that increase your shields or hull, is that it would be very difficult to make those outfits balanced. The only way EV managed it was by limiting the number of shield capacitors you could install, but the result was that there was basically no reason not to install the maximum number on every ship you owned.

**Comment by Nightmareman** [comment]
I think its interesting that there is a lore reason for the shields being at a set strength the shield matrix being integrated into the hull so the modular generator is the only thing you can change which effects the recharge rate.

On the other hand as the game progresses and more advanced aliens are encountered with bigger and bigger HP pools on the shields you have no reason to keep flying human ships when you have ships like the Hai Shield Beatles but this could probably be rectified with instead of something like shield capacitors Mk II or Mk III versions of human ships could be created. Later in the story line new advances could happen in human shield tech because alien tech is stolen or perhaps given this would allow you to keep flying your favorite ship designs while not feeling under-powered compared to the races we will encounter in the future. Of course the newer versions would cost more since they are the newest improved versions.

**Comment by thenerdfreak** [comment]
maybe make them like a capital ship only thing? costing like 100+ outfit space

**Comment by DingusShingleton** [comment]
104 outfit space gives you 2x Korath Generators, which adds 288 shield regen/second. Over a twenty second battle, that's 5600 shields. So a shield capacitor would have be in that ballpark of effectiveness to even be viable, but at that point, why bother? Shield regen is the gift that keeps on giving, and the capital ships that have the space to spare for this outfit already have enough of a soak to make regen way more valuable in the long run. Not to mention that sacrificing shield regen for shield capacity just means that you will be flying around with no shields more often.

**Comment by Tufton** [comment]
I see where Michael is coming from, but I think they could be balanced a
number of ways.  Shield max at the expense of shield recharge, reduced
energy capacity, high outfit space, etc.  Only having shield regen as a
defensive stat makes burst damage weapons much stronger, but also limits
how strong they can get.  Basically, you can never have a ship below a
light warship that doesn't get instagibbed by a nuke or a ship exploding.

Not having "capacitors", as it were, also gives ships with high base shield
values a big and unchangeable advantage over lower shield value ships.
Even with two Quarg shield generators, enough enemies (or quarg) can blast
through a fully outfitted Bactrian's shields in seconds.  Take a Shield
Beetle though, and you will live twice as long (or more), despite it being
a generally inferior ship.  This also makes the other heavy warships even
more useless because you can never really make them tanky enough to not get
annihilated in seconds under focused fire.

An elegant solution may be to add shield capacitors that give a % amount of
your base shield per outfit, so it has diminishing returns as your base
shield values get lower (prevents "Super Interceptors") while still proving
cost-effective (but not OP) for larger ships.

The only other option I see for adding more defensive options (which are
currently limited to how much shield regen you can stack and how much
anti-missile you have [RIP if they have continuous fire weapons]) is
allowing hull/armor to be a buildable stat.  If you add armor plating
instead of shield capacitors, you can make a ship straight up tankier while
not allowing people to stack high shield with high shield regen to become
unkillable.  Of course they would also have to be balanced by outfit space
or mass or something, but I really don't think it would be game breaking.

As I recall, the issue with EV's shield capacitors and armor is that they
were massless (i think? maybe just negligibly so, frankly I don't remember
how EV balanced stuff exactly except money was harder to come by), so you
could just add the maximum amount you could afford.  If you make armor
plating and shield capacitors take outfit space (maybe even weapon
capacity, forcing the player to choose between more offense or more
defense), you can make it a meaningful choice to be made without either
necessarily being better than the other.

**Comment by DingusShingleton** [comment]
I think it's pointless to use quarg outfits when considering balance, as they are intentionally way out of proportion balance wise. And I mean, anything will get instagibbed if you have enough firepower. 

I think shield capacitors adding a percentage makes sense, but I would actually make it a progressive scale based on the size of the ship, which smaller ships getting a higher percentage. Adding 25% to a sparrow gives you 400 shields, a relative pittance, whereas a bactrian would get 4250. 

Perhaps you could further balance it by having shied matrix upgrades reduce allowed engine and/or weapon outfit space, to represent the truly comprehensive overhaul of that integrated system. Doesn't have to be a lot, but shaving 5 or ten tons off the engine capacity is a serious drawback to consider, and hurts alot more than just taking a lot of outfit space.

**Comment by LaPimpa** [comment]
That progression based on scale size of the ship could be made if we consider the capacitors like a shield matrix stabilizer, the smaller is your shield capacity the higher the bonus you will gain from it, at the cost of a gun port or turret mount. Giving a chance to smaller ships while for bigger ships you will need to install more than one in order to get a decent defensive bonus, renouncing to offensive capability.

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!
