### ISSUE TITLE
Clicking multiple times on friendly ships turns them hostile

### ISSUE THREAD

**Issue by bobafetthotmail** [endless-sky/endless-sky#506]
I'm on a bactrian with automated fire on.

If I (right or left) click multiple times on an already-selected friendly ship while fighting, it eventually turns red and I attack it.

I managed to get even the game dev's own ship (a special kestrel) to turn on me.

I think it is a bug because it is random and not stated in options panels.
Sometimes they turn red after 2 clicks, sometimes they need up to 10.

**Comment by endless-sky** [comment]
I think what's probably happening is that because you have targeted that ship, your weapons fire can hit it even though it is not hostile. (Otherwise, there would be no way to choose to attack a friendly ship, because your weapons fire would just pass through it.) So what's happening is that it is wandering into your crossfire and because you have targeted it, it is hit by your weapons.

**Comment by bobafetthotmail** [comment]
Hmmm, yes, but there is more. Parked my fleet, with my flagship alone it still happens.

My ship should not fire at the target because it is friendly, the rest of the fleet is parked so is not firing at it for sure.

But when the friendly target is more or less between me and an enemy or if there is an enemy more or less behind it, my ship opens fire on my friendly target. Which turns red and so on as normal.

Clicking or not clicking.

I think that while you are right (since I can indeed hit the friendly target with automatic fire on), the turret AI also has some issues (because someone on my ship is shooting at the friendly target, and it's not me).

It's easy to reproduce this, I've now angered everyone something like 20 times during my tests.

**Comment by endless-sky** [comment]
What's happening is that your ship is firing because an enemy is in range, but the ship you have targeted is getting in the way and getting hit. The same thing would happen if you were pressing the "fire" button. If you have a ship selected as your target, that means you're willing to fire on it.

The best approach is probably to use the R key to just select the nearest enemy, to avoid mis-clicking and attacking friendly ships by mistake. There's no easy way for the game to read your mind and figure out when you've targeted a ship because you actually want to shoot it, versus when you've targeted it by accident.

**Comment by bobafetthotmail** [comment]
No, I'm sure of what I see. When an enemy is in range and more or less on the same bearing of my target (either before or after it), my turrets decide that they can shoot ON MY FRIENDLY TARGET.

The question here is this: if I'm targeting a friendly ship why my turrets are shooting at all? 

Afaik turrets shoot only at the ship I'm aiming, and autofire shoots only at enemy ships.

There is ONLY my flagship there.

>"The best approach is probably to use the R key to just select the nearest enemy,"

Come on.... I'm not using mouse to select targets because I like being original.

With mouse I can select most important targets, like say stronger ships or stuff I need to see dead first, with R I target "whatever is close" which isn't terribly good at selecting best targets.

In pitched battles sometimes I click on the wrong target or (more commonly) I actually want to select an ally to see its status. 
At the moment this triggers this bug and if an enemy moves in the right place I shoot automatically, everyone turns red, and I have to revert a save.

**Comment by dplepage** [comment]
Autofire means "If there is an enemy in range, fire your weapons at the nearest enemy", and the target ship can always be hit be weapons fire. Consequently, if you target a neutral ship, but the nearest enemy is right behind them, you'll autofire at the enemy and hit your target instead.

If you're using lasers, this will only last for a single frame, because you'll hit the target ship instantly, they'll immediately turn hostile, and from that point forwards they'll be the closest enemy and all your weapons will be (correctly) targeting them.

Perhaps clicking shouldn't select non-hostile targets while your ship is autofiring? Or perhaps the autofire code should explicitly check to see if there's a non-hostile but targeted ship between you and the nearest enemy? Or maybe there should be a panel that pauses the game and displays the statuses of all the ships in your system, so that you can check on your allies without having to target them with your weapons?

**Comment by dplepage** [comment]
Side note: personally, I find the ability to shoot through friendly ships kind of weird already. I assume it's implemented that way because the AI would be a lot more complicated if every ship had to check all the other ships to make sure it wouldn't hit a friendly ship before firing, but I did like that if you weren't careful in EV you could ruin your own fighters with friendly fire.

**Comment by endless-sky** [comment]
Well, the only solution I can see is to disable automatic firing any time a non-hostile ship is selected (a146412). That will mean that if you select a hostile ship in the middle of battle, your guns will stop firing unless you actually press the fire key.

**Comment by bobafetthotmail** [comment]
"Autofire means "If there is an enemy in range, fire your weapons at the nearest enemy", "

it is like that for wingmen, but on autofire my flagship's turrets shoot only if I have selected someone OR if I haven't selected anyone and an enemy is in front of me (together with frontal guns). Which is also weird.

Then there is this behaviour described above.

Am I the only one noticing these things? Is it just my game that acts weird?

"Well, the only solution I can see is to disable automatic firing any time a non-hostile ship is selected"

Thanks. Does that apply to flagship only or to the whole fleet?

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
