### ISSUE TITLE
Minor grammar issue

### ISSUE THREAD

**Issue by Haadrak** [endless-sky/endless-sky#5087]
**Describe the bug**
In the the quarg.txt there are a couple of times where the quarg says 'Ware', either by selecting the prompt "What do you mean, 'thinking war machines'?" or "You mentioned 'thinking war machines.' What are those?", the context indictating that the Quarg are using the contraction of beware. Now unless we're speaking English from the 1500's then it should probably have an apostrophe before 'ware' to indicate that you mean the contraction of beware and not some sort of fine ware.

I should also point out this isn't really a bug but I wasn't sure where else to put this...

**To Reproduce**
1. Go to any other Quarg world first.
2. Go to Kuwaru Efreti.
3. Select either "What do you mean, 'thinking war machines'?" or "You mentioned 'thinking war machines.' What are those?" from the chat dialogue.

**Expected behavior**
'Ware

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Windows 10 Pro, version 1809
 - Game Source: Steam beta
 - Version: 0.9.12

**Link to save file**
N/A

**Additional context**
N/A

**Comment by MCOfficer** [comment]
Link for the lazy: https://github.com/endless-sky/endless-sky/blob/0997067beacd71042cb2f382cc460e58199dca97/data/quarg/quarg%20missions.txt#L88

> Robotic starships, and autonomous factories to create them. Though now directed by no living being, they yet reproduce and wage against each other senseless war. Ware their ships should you wander north and east of here, for they wield diverse weapons and strange, and bring you can we no succor within the bourne of their space.

imo, this is fine, it's a consequence of the quarg's generally more ancient tongue. Compare the second part of the statement:
> ... and bring you can we no succor within the bourne of their space.

**Comment by Zitchas** [comment]
According to the [style guide](https://github.com/endless-sky/endless-sky/wiki/StyleGoals), the Quarg speech patterns are described as:

> "The Quarg occasionally use archaic language constructs, to hint that they're an ancient species (who presumably learned to talk to humans thousands of years ago and haven't kept their grammar books up to date since then)."

So this is basically a case of "given ancient historical Earth languages (presumably English or whatever passes for human "Common"), is `ware` correct spelling, or should it actually be the contracted for of beware: `'ware`

Given the antiquity of Quarg statements, I'm inclined to say that it is the correct spelling; but I'm not a linguistic expert either.

**Comment by Haadrak** [comment]
According to the endless sky wiki: In 2320, the Quarg made first contact with humanity; by 2330, they were beginning to learn human languages. 

This is about 800 years after we stopped using 'ware'. Now you can keep it in if you want but if you want to keep things canon, it isn't correct.

**Comment by Amazinite** [comment]
> if you want to keep things canon, it isn't correct.

It's important to note that the historical timeline isn't exactly gospel. The timeline states that the Deep was first inhabited in the 2200s, but by playing the game you learn that this is not true. So just because the timeline says something that turns out to not be the case does not mean canon is broken; the timeline exists within the canon, not define it. As the wiki says:

> This is the history of the galaxy as it is known to the player in the year 3013; over the course of the game the player may discover that certain things they took for historical fact turn out to be untrue, and that the history books have left out key information about the forces at work behind other events...

**Comment by Zitchas** [comment]
Personally, I would reconcile the two by assuming that the "First Contact" listed in the wiki is indeed when the two species officially met each other and began the process of learning languages, exchanging diplomatic efforts, etc. 

Given the age of the Quarg and the expanse of territory they cross, it is ludicruous to assume that they haven't met the humans long before that. The Quarg are my leading contenders for being behind the alien abductions and contacts and what not that our human history is full of going back centuries (millennia, dependin on interpretations of hieroglyphics, conspiracy theories, and Nazca figures. The ones that are true, anyway. Isn't there a reference somewhere to them telling someone that Earth is offlimits? So they've been watching Earth since the time of the primates.

**Comment by LordInsane** [comment]
Why would it be assumed that the language spoken by the player character is exactly identical to modern English, not simply rendered as such to make things easy for writers and players given that ES starts nearly a millennium into the future, and by extension then that the Quarg using terms like ware evokes them using equally archaic language from the perspective of the player character as 1500 century English would sound to us?

**Comment by Amazinite** [comment]
> Why would it be assumed that the language spoken by the player character is exactly identical to modern English, not simply rendered as such to make things easy for writers and players given that ES starts nearly a millennium into the future,

I actually thought about this yesterday, and thought it would be funny to have someone like Albert Foster find something from the 21st century and complain about how archaic the English is.

**Comment by jostephd** [comment]
> Isn't there a reference somewhere to them telling someone that Earth is offlimits? So they've been watching Earth since the time of the primates.

There's such a reference in context of the Drak:

https://github.com/endless-sky/endless-sky/blob/76dc1a9f7d6c490718047daf43ae8fd1450e9815/data/hai/hai%20missions.txt#L117
