### ISSUE TITLE
Ship Cores

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#509]
Seen this on another game (or movie?) Certain ship cores give higher bonuses to specific stats, for example a civilian/merchant core would be about +5% everything, but:

Tank Core
+15% Shield Capacity
+10% Maximum Hull
-10% Weapon Capacity
-20% Engine Capacity

something like this^ or maybe

Attacker Core
-10% Shield Capacity
-5% Maximum Hull
+15% Weapon Capacity
+/- 0% Engine Capacity

of course different sized ships could fit different cores, maybe something like

Attacker Core(light) would fit on interceptors
-5% Shield Capacity
-1% Maximum Hull
+10% Weapon Capacity
+/- 0% Engine Capacity

but something like
Attacker Core(heavy) would fit on bactrians (or other heavy warships)
-15% Shield Capacity
-10% Maximum Hull
+20% Weapon Capacity
+/- 0% Engine Capacity

**Comment by DingusShingleton** [comment]
I like the idea of being able to modify the base stats of your favorite ship to fit your playstyle, but I think a more elegant way to do it would be more like the x wing miniatures game, where each ship is allowed to have one single modification that buffs a stat or gives an ability.

Each pilot gets one buff to represent your pilot's unique "special sauce" modification that he came up with and perfected himself. It can be applied for free to only one ship at a time, so when you change flagships it can come with you, but you can't apply it to your whole fleet. You could buff total shields, add a base amount of thrust to whatever engines you have, increased weapon damage, or additional energy production. Think han solo getting the millennium falcon to go .5, past lightspeed, you know, it's had a lot of "special modifications".

**Comment by Tufton** [comment]
Interesting idea, I like it

**Comment by LaPimpa** [comment]
Sounds good but i would prefer a weapon damage or engine power bonus instead of increasing weapon or engine capacity. That would mean less problems when changing outfit but on the other hand your outfit could be a lot more personalizable.

**Comment by bobafetthotmail** [comment]
"ship core" is a weird name, considering the kind of game here.

I would call this "ship tuning".

"Tank tuning", "Raider tuning", "whatever tuning" and so on.

**Comment by brick96** [comment]
I can mach up something like this, wont be percent like this but flat numbers will work yes?

**Comment by bobafetthotmail** [comment]
flat numbers would mean small ships will get a "bigger" bonus, while bigger ships will probably not notice it.

Unless you make a version per ship size/type.

**Comment by thenerdfreak** [comment]
That's the idea boba^

**Comment by thenerdfreak** [comment]
Please do try to make a small version, and, if you can, design another specific type of slot for it (like the Engine Capacity limit, etc) something like "Core Complecity Capacity"

**Comment by omagasohe** [comment]
This actually would be better as a plug in and a modification on the Outfits so that fields can be multiplied * ship mass. Kinda like the armor plate in Nova was. you pay more for a larger ship but get better gains. Smaller ships are cheaper but less gains. I'd imaging most fields would be applicable. 

A better would just have the flag that would multiply the hard numbers by an ammount. 

Say I could make a awesome engine, but to balance it I could have the Crew requirements multiplied by 1.25 to reflect the unique conditions =P Or a supercomputer mod that would reduce crew size by 75%.

**Comment by brick96** [comment]
^^ That would mean every ship will need to be modified with this attribute and balancing may be time consuming

**Comment by thenerdfreak** [comment]
well since there won't be an infinite number of different types of cores, wouldn't it be possible to copy/paste the size data from each ship to next?

**Comment by thenerdfreak** [comment]
If need be, pick a name for the specific name for this "core complexity" and give an example of the attribute's usage and I'll use my c/p skills in a datafile

**Comment by bobafetthotmail** [comment]
>"^^ That would mean every ship will need to be modified with this attribute and balancing may be time consuming"

Can't you make the outfit stat dependent on a ship stat somehow?

So that the outfit stat looks at the ship and calculates a static modifier that can then be added to the ship normally.

Say that engine could have a crew stat that is Crew: +MinCrew/100*25.
That way the stat would be calculated dynamically by looking at the min crew stat.

No need to alter ship stats.

>"That's the idea boba^ "

Then you need to make big ship cores not installable by smaller ships, which isn't as easy as it sounds, since I can swap cargo for outfits too so you cannot just make them relatively big (say 50-70 outfits), and at that size, I'd rather install moar power or shield gens or a better engine alltogether.

**Comment by thenerdfreak** [comment]
no, the idea is to make them take up 0  outfit space, but instead take up a specific "ship core" capacity that varies by ship size

**Comment by bobafetthotmail** [comment]
Meh, that way I could install two small cores in a big ship.

The elegant way is a single slot, and the core's stats are calculated from the ship's base stats.

**Comment by thenerdfreak** [comment]
true, like a "gun port" only named something different

**Comment by bobafetthotmail** [comment]
yeah, should work like a gun port. Can fit whatever, but ONLY one system per port.

The easiest way is making "light core port", "medium core port", "heavy core port", and so on.

Might get away with a (hidden since it's 1 for everyone) "core port" capacity to make sure that only ONE core is installed, and then you can have a "ship core" capacity like you wanted to do.

A bit like fixed guns and weapon outfit capacity. If you are out of gun ports you can't install more fixed guns even if you have 400 outfit capacity left.
If you are out of capacity, you cannot install guns even if you have 400 gun ports.

Although this would allow to install ONE light core in a big ship, which may or may not be what you want.

**Comment by endless-sky** [comment]
It's already hard enough with the current game mechanics, given how customizable ships are, to create ship types that have particular strengths and weaknesses that can't be removed. That means that all ships in a given price range are almost interchangeable, aside from differences in engine and weapon space. This change would make that an even bigger problem - you could take basically any ship and make it super fast or super well-armed.
