### ISSUE TITLE
Storyline rework, no random fails.

### ISSUE THREAD

**Issue by Eljee** [endless-sky/endless-sky#514]
After playing 7 hours to find a (the?) story line I got a 50% chance of getting the answer right and failing a test. I uninstalled the game since ferrying passengers for 7 more hours before getting a second chance is not how a game should work in my opinion.

I know that similar things tended to happen in Escape Velocity. However, I feel that this is something that can be improved upon, since that was just as infuriating in EV as is has been in Endless Sky.

A proposed change is maybe a conversation where you either agree with the separation of Free Worlds or oppose. You could be thrown from the planet and you could be overheard by someone working for the Republic. A least that means you wont waste hours flying around waiting for more to happen.

**Comment by thenerdfreak** [comment]
Erm no. That was just an optional thing xDDDDDD You'll still get the story-line quest

**Comment by Nightmareman** [comment]
Use your head before making a decision doing a karate move you saw on T.V. is obviously a very stupid move.

**Comment by endless-sky** [comment]
The Free Worlds story line offers you numerous second chances - you can do the karate chop *and* have the freighters you're escorting get blown up *and* refuse the scanning mission, and you'll still be offered second chances. The only way to completely wreck your chances at joining them is if you consistently refuse to work with them over and over again.

**Comment by Nightmareman** [comment]
@endless-sky 
Wow knew you could get away with the karate chop and the freighters as well as I've done several playthroughs now but didn't think you could get away with that much before completely wrecking your chances. Will it always be this way since its the only story line available or will it be changed once the other story line options are added? On another note is there any way to private contact you regarding ideas for story line related material or for more a more in-depth story?

**Comment by endless-sky** [comment]
Most of the discussion of story development is going on in the [forum](https://groups.google.com/forum/#!forum/endless-sky), in order to keep this issues list just focused on bug fixes and feature requests.
