### ISSUE TITLE
Mass and Cargo Expansions have nonsensical speed effects

### ISSUE THREAD

**Issue by Waladil** [endless-sky/endless-sky#516]
In the current Steam version (0.8.9), according to the speed pane of my ships, installing Mass Expansions reduces the effective mass of my ships by 20 tons, and installing Cargo Expansions increases the effective mass by 20 tons. 

Mass Expansions actually appear to increase the displayed mass by 5 tons (as expected, the equip is clearly listed as having 5 tons of mass) but decrease the ships "actual" mass used in the speed calculations by 20 -- ignoring the +5 from the equip itself.

it took a lot of fidding with equips to get these data. A lot of times of me staring at two ships with hugely dissimilar masses and identical speeds from identical engines.

**Comment by Nightmareman** [comment]
The current movement appears to display the ship when fully loaded with cargo so with the cargo expansions it presents the speed you would have with a full cargo load. When you add Mass expansions it wont present the speed penalty because it is now free space for outfits so unless you add outfits to fill up the newly created space your ship will essentially have a big empty area which is why the movement looks the way it does. So it is working correctly its just kind of weird to look at unless you understand the reasoning behind it. I totally understand your confusion.

**Comment by Waladil** [comment]
Then that issue still needs to be fixed. If that is the case then the "mass" attribute should assume that all cargo holds are filled at all times, and installing a Mass Expansion should show the ship's mass reducing by 15 instead of increasing by 5. The mass attribute's main functionality is to indicate how large of thrusters are needed to maintain a certain speed. Higher mass value means you need bigger engines. Having the cargo space as a hidden speed penalty is literally nonsensical.

Personally, I think it's oversimplified bullocks and preferred it when it displayed values for empty and fully loaded cargo holds. I don't know if just the display was changed or the actual speed calculations.

**Comment by endless-sky** [comment]
Yes, this is a semi-bug: the display calculations are assuming you have a full cargo bay. In commit 4c3e87d I changed that so that when you are landed, it will show your empty / fully loaded speed, the same as in the shipyard when you first buy the ship.

**Comment by endless-sky** [comment]
Fixed and released in 0.8.10.
