### ISSUE TITLE
Typo when landing on Relic

### ISSUE THREAD

**Issue by roadrunner56** [endless-sky/endless-sky#5175]
### Bug
In the Relic description of the planet and spaceport, 'it's' should be 'its', as it is a possessive and not a contraction of 'it is'. 
### To Reproduce
1. Land on the planet Relic
2. Read planet and spaceport description
3. Find typos
### System 
OS: Kubuntu 20.04
Game Source: Github
Version: Continuous Build, 2020-07-23
### Additional Context
I have previously filed a similar bug (#5069) that was a duplicate, but this time I am on the latest build and still see this typo. I searched issues and pull requests, but found nothing. I'm really sorry if it turns out that this issue has already been fixed, and I made the same mistake twice.

**Comment by Amazinite** [comment]
Fixed in https://github.com/endless-sky/endless-sky/commit/671607c38eea3c066a31e8d577d8fbd17d587e8e. The previous issue mentioned a bunch of other typos that had been fixed, hence why it was missed then. I will note that with both the linked issue and this one, neither said *where* exactly the typo was. Took me a minute to catch it since there were actually multiple uses of "it's" for Relic. In the future, saying something like "The 'it's' in 'despite it's low gravity' is wrong," so that we know exactly where it is. :)

**Comment by roadrunner56** [comment]
Okay, thanks for the advice. The issue was fixed after I opened it, right?
Also, it seems that in the spaceport description, an improper use of 'it's' is still there, in the phrase "and **it's** only designed to handle". This should also be corrected to 'its'. Thanks for being patient with me :)

**Comment by Amazinite** [comment]
No, that one is correct. “The spaceport here is located in the only recognized city on Relic, and **it is** only designed to handle the occasional merchant or Navy ship...”

**Comment by roadrunner56** [comment]
Sorry, you're right, I was really tired when I wrote that. Thanks again. :)
