### ISSUE TITLE
'Search for the Korath' mission bug

### ISSUE THREAD

**Issue by roadrunner56** [endless-sky/endless-sky#5246]
**Describe the bug**
After completing `Remnant: Cognizance 4`, Chilia's dialog triggers on any planet, even uninhabited ones or ones outside of Remnant space. In addition, the 'Mission failed' message comes on the bottom of the screen in the middle of the mission, even if the player's flagship has not been lost. There seems to be no way to perform 'Search for the Korath' without failing it. This could be confusing to players.

**To Reproduce**
1. Accept `Remnant: Cognizance 4` and complete it. Observe 'Mission Failed' text at the bottom of the screen. 
2. Land on any planet. 
3. Dialog triggers, no matter the planet characteristics.

**Expected behavior**
I expect the dialog to trigger only when landing on Caelian after the mission is complete. In addition, I expect the 'Mission failed' message to appear only when the player dies.

**Screenshots**
![BUG](https://user-images.githubusercontent.com/65418682/90837933-a70f4880-e310-11ea-93e5-9cb443f6ad61.png)
Landing on an uninhabited planet after completing the mission.
![Screenshot_20200820_180532](https://user-images.githubusercontent.com/65418682/90838114-361c6080-e311-11ea-82a7-6611af51435a.png)
Landing on Tarazed, a non-Remnant planet, after completing the mission.
![Screenshot_20200820_180411](https://user-images.githubusercontent.com/65418682/90838069-11c08400-e311-11ea-9691-06c3763321e3.png)
'Mission failed' message even when the flagship is still intact.

**System (please complete the following information):**
 - OS: Kubuntu 20.04
 - Game Source: Continuous, appimage
 - Version: commit f3edfc4

**Comment by waterhouse** [comment]
So it seems to me that, if we want to do it with one mission (as opposed to using a second invisible mission), then the ideal approach would be...

Well, we want something to trigger when the ships die.  Failing the mission is not the best because of the "wherever you next land" thing (as well as the player-visible failure message).  Setting a flag seems ideal.

Next, as for how it gets triggered... It seems "npc kill" clauses can trigger dialog inflight, so at least syntactically it looks like you could make them trigger `set "fleet killed"` (I haven't tested this).  However, the "npc kill" thing would then become a required objective for the mission, when we want it to be optional.  The ideal thing would seem to be an "npc" clause, with an "on kill" subclause, which would trigger `set "fleet killed"`.  Unfortunately, such a subclause doesn't seem to exist.

Still, if we are in the business of asking for new features to the game engine, an "on kill" trigger for fleets (or for ships), which can be used to set flags, seems a good fit.  Could be used in lots of places, really (e.g. one could refactor the Cosmic Devil missions, or add custom text like this mission's to any "find an enemy but don't necessarily fight them" mission).  @Zitchas mentions a planned change to despawn mechanics; this seems related though not necessarily the same.

**Comment by Amazinite** [comment]
I outlined a method that could solve this back when this issue was posted.
![image](https://user-images.githubusercontent.com/17688683/116474401-4b954300-a82d-11eb-985c-d4c04766c018.png)

Due to a bug with `to despawn` though it didn't work at the time, but has since been fixed.
![image](https://user-images.githubusercontent.com/17688683/116474455-623b9a00-a82d-11eb-8778-535b3341e0dc.png)

So pester Zitchas to get around to that.
