### ISSUE TITLE
Bug: Can't continue to Remnant Cognizance 10

### ISSUE THREAD

**Issue by RicCakes** [endless-sky/endless-sky#5262]
**Describe the bug**
I _can_ complete "Remnant: Cognizance 9" but I can't continue it due to the next mission's source is in the Esquiline planet. The gist of it is that it leads me to Aventine (the source) instead of Esquiline. The ship I had used is the Penguin, also used the Puffin (both has gaslining). The only gas giants I can land on is at the system Nenia. Seeing that there's no other reports of this, am I the only one experiencing this? I already looked at the map.txt of the instance I downloaded and it seems up-to-date.

**To Reproduce**
1. Complete "Remnant: Cognizance 8"
2. Spaceport
3. Gavriil says Aventine is a gas planet
4. Land on Aventine again

**Expected behavior**
Waypoint should've led me to Esquiline.

**Screenshots**
**

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Continuous, ESlauncher2
 - Version: built 2020-08-25

**Link to save file**
**

**Additional context**
The pilot I used is new, the one I made in the Continuous build.

**Comment by Zitchas** [comment]
If the only gas giants you can land on are in Nenia, then there is indeed a problem. In the current continuous build, using a Penguin or a Puffin,  you should be able to land on virtually every planet in the Pantica or Cinxia systems, and all-but-one in Arculus. Within those three systems, there are a handful of gas planets. (not all of them are gas *giants*).

When not flying something with gaslining, there should still be a number of uninhabited planets you can land - uninhabited moons, and other planets like that. Are these present?

Likewise, for Cognizance 9, the data files specifically state "Aventine" as the source, and "Esquiline" as the destination. It should *not* be completing on Aventine.

Does your error.txt file have anything in it?
Are you using any plugins or otherwise have changed any of the data files?

**Comment by RicCakes** [comment]
> As it might be relevant, how did you verify the map.txt file?

Going through the data files and just opening it. And it does, indeed match the one you just shown. I can't land on the moons either.

The only plugin I am using that could change the map is Animated Stars from last year ago. I'll remove that.

**Comment by RicCakes** [comment]
... yeah it was that plugin. Outdated plugins are complicated.

**Comment by Zitchas** [comment]
No problem. I'm glad you were able to work it out. And it is useful to know that the Animated Stars plug-in breaks some of the Cognizance missions.

**Comment by Amazinite** [comment]
In order to work, the Animated Stars plugin has to redefine all the objects of every system. This means that Animated Stars will only include the landable planets that existed when it was created/last updated. Cognizance added new planets to existing systems, meaning that Animated Stars will overwrite those planets.
