### ISSUE TITLE
There is a lack of progression in speed related to ship sizes

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5271]
**Is your feature request related to a problem? Please describe.**
Currently in game there is a progression as you increase the size of your ship. Generally, the bigger the ship within a tier, the more HP it has, the more DPS it can output, and the more outfit/weapon/engine space it has. One would also think though that the bigger your ship, the slower it goes. While it is roughly the case that larger ships are slower than smaller ships, it is very easy to equip a larger ship with engines that make it as fast as or faster than a much smaller ship. Therefore, there is currently no real progression in speed related to ship size. Increasing the size of your ship yields no downsides, as the one expected downside of lower speed does not exist.

**Related Issue Links**
Other issues that either speak directly to or are related to the balance between large and small ships:
#1932 was closed because turrets were given turn rates. While this helped to give smaller ships a chance, the issue of speed still exists.
#4034 The issue with smaller ships vs larger ships is related to the issue of fighters being underwhelming at the moment.
#4407 suggested using multipliers to make generators that are more attractive to smaller ships, but I suggested that we instead simply make smaller ships regenerate faster. (This is also something mentioned in #1932.)
#4697 discusses ways to make smaller ships have more of a chance against larger ships. 

**Describe the solution you'd like**
Rebalance the mass and drag of ships to have a much more drastic jump between categories of ships.

For example, right now the difference in the average mass of a human interceptor versus a human light warship is only +80%. From light to medium warship it's +87%, and from medium to heavy warship it's +126%.
In terms of drag, the progression is +127% from interceptor to light warship, +86% from light warship to medium warship, and +57% from medium warship to heavy warship.

By increasing the jump in mass and drag as you go up a ship category, we'd make it so that larger ships handle noticeably slower than smaller ships, being the trade off for more HP and DPS.

**Describe alternatives you've considered**
Another point of concern might be the progression in power between various types of engines. A ship with atomic engines will be going MUCH faster than a ship with ion engines of the same size. Perhaps we want to reduce the difference between the slowest and fastest engines. Currently, a tiny atomic thruster has nearly double the thrust per ton as a tiny ion thruster. (87% more to be exact.) This difference in power continues all the way up the size progression of engines. (The huge atomic thruster has 81% more thrust per ton than the huge ion thruster.)

And in terms of progression of power as you increase in engine size, at the same time that the average human heavy warship has 565% more drag and 661% more mass than a human interceptor, huge thrusters have about 1260% more thrust in the case of ion and plasma thrusters, and 807% more thrust in the case of atomic engines when compared to the tiny thruster of the same engine category. 

This is to point out that on average, **the power of human engines as you increase in size currently outpaces the increase in drag and mass.** Therefore, we either need to reduce the power of engines with size or increase the drag and mass more with size.

**Additional context**
Should we go the route of increasing the mass of ships, we need to remember that hit force and optical tracking are currently balanced assuming the average mass of ships of certain categories.

**Comment by Amazinite** [comment]
Just a thought to keep in mind.
![image](https://user-images.githubusercontent.com/17688683/91874221-f4ac7f00-ec47-11ea-8d97-cbaf8fee0efa.png)

**Comment by vitalchip** [comment]
The way the formula is written for hit force ( I think there's been a mistake ) means it's very skewed at higher mass, I doubt there would be any noticible change to larger ships anyway.

If it's a mass solution you go for, consider adding 'people mass' something that doesn't really seem to have been taken into account. Most medium/larger ships are very much on the light side for 'dry' weight. 

For example, the Centipede has a 'dry' mass of 187 tons. This is not a hull big enough for 131 bunks. 

I'd suggest adding a mass per 'built in bunk'. Very little effect for small ships but more pronounced for larger ones. Not a complete solution but it would at least address the current 'underweight' situation as regards people capacity.

2 tons per bunk would be in line with the bunk room outfit.

**Comment by Zitchas** [comment]
As I understand physics, (which is rudimentary), a larger ship theoretically could have more energy to devote to thrust, and thus be able to attain greater speeds. But that is in a universe where the amount of force required for each increase in speed goes up significantly. At low speeds, smaller ships have the advantage of low mass, and thus can accelerate faster. So there is basically the situation where over the short term (and low end of the speed spectrum) small craft have the advantage, and larger craft have the advantage on the long term and high end of the speed spectrum. (and by long term, I mean days, weeks, or even years of constant acceleration)

In ES, we don't use real world physics for that, so it probably doesn't apply. I just wanted to put it out there.

Inside ES,  some things come to mind:
A) In the predecessor games speed was a relatively static attribute: Each ship was assigned a max speed, acceleration, and turning speed. Some outfits could give a one-time boost to each of those, and afterburners could boost them temporarily, but overall they were static. In the EV/O/N games, there were significant variations in speed. Things like the bulk freighter, confederate cruiser, and other really big, heavy things, had max speeds that in ES terms were in the range of ~100, and turns speeds of <45/sec. Given that ships actually had to leave the inner system before they could hyperjump, traveling using these ships was incredibly slow. (just found some numbers: Bulk freighter had a top speed of 80. Confederate cruiser was 150, Rebel cruiser was 200. Bulk freighter had an acceleration of 125, Confed Cruiser of 290, and Rebel Cruiser was 280. And let me tell you, the Rebel cruiser could dance circles around the Confed cruiser. Kestrel had a top speed of 225 with an acceleration of 375, hence its reputation as being the favourite combat ship. (stats from http://allenthar.50megs.com/EV.html)

B. Rule of Fun: Slow ships aren't fun, generally speaking. Everyone wants their preferred ship to be not-slow, preferably actually fast. Personally, ships that have a max speed below 400 just feel too slow to me, and I rarely spend time in ships that have a speed less than 500.

C. Something related that I have noticed with ES: Effectively, speed and agility are intertwined. Thanks to the engine system, a degree of ship versatility is gone compared to the other games. In the other games, there were some ships that weren't particularly fast, but had good turning. Or conversely, were really fast, but only mediocre turning. Scoutship, for instance, wasn't great at dodging, but wonderful for outrunning things. We could aproximate such things with something like drag for turning, which would be nice, but I'm not sure how obvious it'd be as a ship feature.

D. I agree with the need for more variety in speeds, and I think I also agree with how the really wide range of possible speeds in the current engine set make things a little ridiculous. While I definitely feel that there should be a few fast big ships, they should be the exception, not the rule. For example, the blockade runner that princess Leia uses in Star Wars. That's an example of a larger ship that is designed for speed. Note the comparatively large engines compared to the total size of the ship. 

![BlockadeRunner-TCGEoD](https://user-images.githubusercontent.com/32169904/91873853-c5d9dd00-ec36-11ea-80fd-5298c594b46e.png)

For ships that are *not* designed for speed, the general trend of small ships are faster than bigger ships should hold true. Likewise, while I fully support the idea that customizing and upgrading your ship and tweaking things should be able to change that up a lot; it shouldn't be able to completely upset everything. Example: Marauder (Engine Variants) ships. These are ships that should clearly go faster than normal for their size. Swapping out engines and stuff should allow people to buck the mold a bit, but not completely.


Ideas:
1) Reduce the effectiveness gap between engines: For instance, instead of the comparable atomic to ion being 87%, maybe let's drop that down to 50% and see how things feel then. At the same time, let's increase the price on engines so that going up a category is a real investment, not an automatic "of course I swapped out the engines for atomics" thing. That way, taking a ship that starts with ionic and upgrades to a plasma or atomics is an actual investment that people plan for, and feels more like the big change that it is. After all, ripping out your engines and putting in new ones should *not* be a casual change.

2) Carriers are another issue. Currently, the mass difference between a carrier and fighter is sufficiently small that a carrier can go from feeling like a slower-than-average cruiser to being a rocket boat just by launching a couple fighters. I'm not a fan of this. I'd like to see the difference in mass between fighters and carriers increased sufficiently that launching fighters isn't suddenly making carriers handle like a frigate. Increasing the mass of all carriers by 10-15% would probably be a good starting point, especially in conjunction with idea 3.

3) A straight up mass reduction of about 10-15% across the board on all drones fighters, and interceptors might be a really good place to start. No change to any other stat - just their actual mass value. This will probably, for an immediate result, lead to drones, fighters, and interceptors actually being able to outrun almost everything. Within the ES world of smaller=faster, this helps establish the paradigm and fits nicely into it. Yes, it also makes them a lot more vulnerable to weapons that have force effects, but I don't see that as a problem either. A fighter getting hit by a heavy rocket or something designed to push around warships *should* get destroyed and/or blown across the system.

4) tightening up engine space on most ships, but add in a "marauderfication". Basically, make it harder to uber-engine a standard ship, but introduce a way for ships to have some *real* intense engineering work done on them to open it up again. Something like Lake's system of hull slots and what not would be great for this: It allows people more flexibility in customizing how their ship works, and lets people optimize their ships in different ways, but still keeps a limit on it so things have trade-offs.

**Comment by vitalchip** [comment]
For me, top speed isn't really important. The issue is with acceleration ( and turning ). If a really large ship has a high top speed then as long as it takes a while reach that speed and to slow down / change course there's no problem. What it shouldn't be able to do is get to that speed quickly or turn on a dime. Therefore mass and/or thrust is the key. Drag is just a sanity check for the game really, to stop crazy speeds happening.

**Comment by Zitchas** [comment]
I agree. I'm perfectly fine with anything being able to reach crazy top speeds. But fighters should be able to get there *long* before the heavier ships do. A very long time before.

**Comment by Kaatapohlt** [comment]
Just posting in here, as the other party to the conversation that spawned this, I'll be taking a look into this. I really want ships to feel different, so there's more reason to maybe use another ship type in your fleet.

My intention is to work off an intial basis on the assumption of people using plasma thrusters to get how a ship should feel with the "middle ground" engines, focusinging on tinkering with mass and drag. I don't want to focus too much on rebalancing the engines right off the bat and see what can be achieved with just tinkering with the ships first.  My personal suspicion is it'll be a little of both to get things to a nice middle ground.

**Comment by Red-57** [comment]
One thing that I have noticed is that in some of the larger free worlds battles the navy cruisers and carriers are zooming around much faster then they ought too, while their drones and fighters are slightly faster there is no clear difference. Also star wars when the star destroyers jump out of hyperspace they don't then go rocketing around blasting everything to bits, they launch their fighters and let them get in close and do the damage while they bombard from far away

**Comment by vitalchip** [comment]
Kaatapohlt, something to consider when you're tinkering.. change the mass of the engines. Right now they're all mapped 1:1 with their outfit space. Not only is there no need for this to be the case it's actually vanishingly unlikely that all engines have equal density.  So where Orca Plasma gives 244,440 thrust for 98 tons and Bufaer atomic gives 432,360 for 104 tons.. you could make a plasma engine less dense and atomic more dense, this would narrow the gap by giving you more thrust but at the same time more mass to shift..  It would has the benefits of carrying over to any saved ships and not affecting which engine combinations currently fit in a given ship.

**Comment by Kaatapohlt** [comment]
Generally, most outfits are 1:1 with space to mass, so I'd not really want to break that,

**Comment by ira210** [comment]
For big ships to be slower than small ships whilst still moving at a reasonable speed so not being boring would it be possible to add a time compression thing for bigger ships so that for example piloting a heavy warship would feel the same as piloting an interceptor for the player but all the interceptors to look much faster when you are in a heavy compared to when you are flying one yourself. See Naev for an example implementation. This could probably be done the same way as fast forward but I don’t know enough code to say this with confidence.( this is not my idea, I saw it in naev and thought it was a good one)

**Comment by Zitchas** [comment]
That's definitely a possible idea; although we'd want it to be implemented as an option. Some people (such as myself) don't really want the rest of the galaxy changing around us.

**Comment by Amazinite** [comment]
The fast forward mechanic should be sufficient enough.

**Comment by ira210** [comment]
As a way of implementing my suggestion or as a way of making it unnecessary?

**Comment by ira210** [comment]
> That's definitely a possible idea; although we'd want it to be implemented as an option. Some people (such as myself) don't really want the rest of the galaxy changing around us.


In my view it wouldn’t be changing, only your perspective would be I.E it take longer to do things in a bigger ships so time seems to pass faster

**Comment by vitalchip** [comment]
Some food for thought. As I mentioned above, a lot of ships are simply not large enough / heavy enough for what they are supposed to be. I've attached a quick table. For these ships I've taken added the cargo space, outfit space and a considered bunk space, calculated by taking the number od standard bunks and assigning a cu/m volume to each, depending on the type of ship.

2 for a shuttle (very basic, bed and a shared table probably) 8 for Riptide ( still small, that's only 2m x 2m x 2m per person to include sleeping and a share of communal facilities, for a ship with an 8 day range..) and 16 for Bactrian ( people would live on it for months..). All of these are still, very much, on the small side.

I've used these things to calculate the minimum internal volume required. Then I've worked out the hull thickness if the ship were a cube ( they're not a cube, in fact internal space / hull volume will be far less efficient than a cube ), factored in a hull thickness based on hull strength (sqrt relationship) and finally a material density. 4.5 is Titanium. I'll assume the Wanderers have something better, so 3 for them.

The result shows the shuttle frame mass to be a little high and the others to be considerably too low.

I'm not suggesting these exact figures should be used or even that they are 'right' simply that when you put a bit of thought into what a ship is supposed to be and what sort of size/mass it would need to be to achieve that, current numbers look more than a bit suspect.

![image001](https://user-images.githubusercontent.com/65342577/91976243-969b9c80-ed18-11ea-8185-c2659cbaa89f.png)

**Comment by Zitchas** [comment]
Could you explain the colums in  your table a bit more? (specifically, which column corresponds to w hat value in your explanation?)

@ira210 In regards to my not wanting the galaxy changing around me, I'm referring to my personal learned behaviours. If I get used to fighting pirate clippers, for instance. I know how they move, how they shoot, how to kite them, etc. Then I move to a bigger (slower) ship, and then suddenly the clippers are moving twice as fast, spinning around me with greater (comparative) agility, etc. 

It would basically feel like every ship I fly has roughly the same performance, but every time I change ships the every other ship in the game changes performance. Which flattens out the learning curve as far as how to handle *my* ship, but makes the curve much steeper for learning how to predict enemy ship movements and where they will be.

**Comment by vitalchip** [comment]
Frame is the base mass of the ship, as defined. Cargo V is the cargo space (I'm treating it as a volume) Bunks is how many bunks are defined for the ship, as standard. Bunk Mult is a multiplier, how many cubic metres per bunk. Bunk V is the derived volume needed, per person (bunks x bunk mult). Outfit V is whatever outfit space the ship has. Hull is the hull strength from the definition.

Hull Mult is a multiplier, it's a broad stroke attempt to gauge a hull thickness, based on a stronger hull being thicker. I've used a square root relationship as I doubt you'd need 2x as thick to get 2x strength.

The reference size I used was 5cm thick Titanium for a 400 strength hull.  I din't go into the probability that there would be 2 hulls, an outer to absorb damage and an inner pressure hull.

Inner L and Outer L are the sides of a cube with volume 'Frame Vol'. Worked from the volume needed and the calculated hull thickness.  

Hull Vol is the volume of material needed for the hull. Hull Mat is the density of the material.

Hull Mass is the mass of the material needed to construct a cube, internal volume of "Frame Vol" of the specified material density, given the calculated thickness.

**Comment by Zitchas** [comment]
Thanks for the annotations. That helps things make more sense.

**Comment by vitalchip** [comment]
For info. Bactrians with added mass as above table. Two variants, original engines and what everyone goes for, Hai Atomic.

Both screenshots, original mass on the right.  Approx 30% less agile in either case with the added mass but not all bad, extra heat capacity gained.

I'm probably towards the extreme end on this one, to me a "city ship" should be enormous and have all the agility of a laden oil tanker but I appreciate not everyone thinks this way. 

<img width="617" alt="Screenshot 2020-09-02 at 14 50 08" src="https://user-images.githubusercontent.com/65342577/91993813-bb4e3f00-ed2d-11ea-8598-e8ed54cf182e.png">
<img width="617" alt="Screenshot 2020-09-02 at 14 54 01" src="https://user-images.githubusercontent.com/65342577/91993819-bee1c600-ed2d-11ea-8131-3191b5254e2c.png">

**Comment by Zitchas** [comment]
To be honest, I completely agree with that sentiment. The Bactrian is a city ship that was designed to go in straight lines over long distances (perhaps for weeks or even months at a time through sparsely settled space between colonies. This should be the definition of an endurance ship, not an agility one. I also find the idea of it having 4 gun ports that it uses in combat to be kind of ludicrous because it should not have anywhere near the agility to make guns even remotely useful. But that is a longstanding issue. If a speed rebalance happens to make it more in line with what it should be, then all the better, though.

I really like the way the speeds with atomics turns out. That's almost exactly what I'd imagine for a city-ship: Reasonably high max speed, but not great acceleration. I'd personally thinking the turning should be lower, but it is a solid shift in the right direction.

**Comment by Kaatapohlt** [comment]
I'd like to not map out ships in isolation, I'm a tad busy so I've not had chance to compile a set but I feel we need to try and work on adjusting across the board and not just working with an extreme edge case to begin with, (The baccy should, by a fair margin be the slowest human ship by virtue of being the most massive)  Heavy warships should feel pretty heavy, and the ones that are not so sluggish, like a kestral or falcon should handle notably lighter,

**Comment by vitalchip** [comment]
Totally agree on the method, I'd do the same. I just wanted to show 1 worked example and how it would affect that ship. The Bactrian I play is actually much slower and heavier even than that, it's a proper pig to fly and I only roll it out when I really need the capabilities, I think that's the right way though.

**Comment by Amazinite** [comment]
If we do what I mentioned and bring all the engines closer together, we should leave afterburners alone. That way afterburners are comparatively stronger than they are now, meaning that could see some actual use. (Because I don't know about you guys, but I never use afterburners right now.)

**Comment by vitalchip** [comment]
I'd agree on both counts and I do use afterburners. In fact the main reason I have them is my ship was built using the formulas I mentioned above and it's 4100 tons. Every now and then I need a kick to get it somewhere a bit faster ( and stop it when it gets there ).

**Comment by Zitchas** [comment]
Actually, I like using afterburners - they give enough of a boost, but only kind of. The problem I run into is that I usually don't have enough space for them. So basically, they work well, and feel good, just aren't worth it enough to overcome many of the other demands on my space, like ramscoops or extra fuel or whatnot. Not to mention, running up against the engine space limit.

**Comment by Kaatapohlt** [comment]
So, for a rough sort of ballpark of what some basic broad tweaks can do, I've compiled a spreadsheet with some basic ideas on tweaks. The first tab is currant as is, to give a basic picture. Second is bringing the increase in power from 1.9x the previous tier, to 1.8, the third is with LWs massing 1.1x the amount, MWs 1.25 & HWs 1.5, The fourth has both tweaks applied, and the fifth is after I went over and tweaked the values a little for even numbers/give a little boost/smack to ships that are meant to be fast/slow. Yellow highlight is reduced, Green is increased. 
[Endless Sky Eyeballing.xlsx](https://github.com/endless-sky/endless-sky/files/5198442/Endless.Sky.Eyeballing.xlsx)
Thoughts?

**Comment by Zitchas** [comment]
I'd just like to re-iterate that I think one thing that could add a bit of sanity would be to have a value similar to drag for turning. For the sake of discussion, let's call it inertia. As in, inertia resists turning movement.

So, turning would become something like (Turn force / Inertia) / Mass = Turning speed

Thus, we could start dividing ships into five categories:
- Ships that are good for speed and agility
- Ships that are good for speed but have poor agility
- Ships that are bad for speed but have good agility
- Ships that are bad for speed and have bad agility
- Ships that have average speed and agility.

For example, the arrow. It is designed to be an executive transport that outraces threats, but it isn't really built for agility. So it'd fall into the category of "good speed but poor agility."

Then there are things like the Bactrian and the Bulk Freighter. Both of these are ships that should have terrible turning, but the former should have decent (but not great) speed, and the later would be poor speed too.

That being said, I think that both drag and inertia should be visible in-game, on some kind of a "more info" screen. Especially if they have a larger impact on ship performance, the player should be able to find out what they are without looking at data files or checking a wiki. But, they should reflect what the player can see on the image: The Bactrian looks like a really heavy, unbalanced and unwieldy ship. This should be reflected in the inertia stat.

**Comment by Vrok-Kronos** [comment]
Would the data in the included spreadsheet be of any help in this issue? (work in progress) https://github.com/Vrok-Kronos/endless-sky-ship-mass-balance.git

I have tried to adjust the mass of each ship based off its stats. For each bunk, fuel, outfit space, shield point, and hull point said ship gains x mass. Higher tier ships gain a discount for 'advanced materials' so they don't become impossible to fly. The numbers are editable to whatever(in green), and ships are grouped by class. 

Note 1: In my formulas/plugin I deviate from vanilla human fighters by swaping some shield hp for hull so they are more likely to be recoverable after being disabled.

Note 2: 'Hit force' and 'firing force' are out of control on heavier ships. Is there a way to apply "force protection" to the hulls of each ship? It would make a roundabout way of making larger ships feel like they can take a punch, apart from adding a module to every ship in the game that would have the same affect.

**Comment by Amazinite** [comment]
Well we already have two separate takes on mass changes with #5772 and #5779, so not so sure how helpful another take will be.

As far as hit force/firing force goes, I've outlined potential changes that could be made here: https://github.com/endless-sky/endless-sky/pull/5779#discussion_r645028497
Either we remove the fixed mass weighting of hit force or we shift the fixed mass from 30% of 400 to 20% of 2000.

**Comment by mike-f1** [comment]
I would suggest another way to handle ship sizes, speed, masses and all these thing in a different way: with some physics.

**Take on [max speed](https://github.com/endless-sky/endless-sky/blob/02a280c1c1c0e7dc83f54e42a4954637579d3ca4/source/Ship.cpp#L3462)**
the model used scale linearly with thrust and in inverse proportion with drag. Quite simple.
But what about drag? Drag is [an attribute](https://github.com/endless-sky/endless-sky/blob/02a280c1c1c0e7dc83f54e42a4954637579d3ca4/source/Ship.cpp#L3392-L3395), then here you can put anything. And indeed, sorting stats I see there's a lot of variance... Probably because that value is simply used to cap the max speed to the wanted value.

But in 'real-atmospheric-model' drag is proportional to a "coefficient of form" multiplied by the cross section area, which is not _linear_ with mass, and two simple example can help:
* assuming a thin spherical shell, the mass is proportional to the external surface of the shell, and cross section is proportional to the radius squared. So we have:
`TopSpeed = Thrust / Drag`, but `Drag = K * CrossSection`, `CrossSection = radius^2`. But `Mass = radius^2` and so `Mass = CrossSection` ('=' means proportional) .
Thus `Drag = K * CrossSection = K * Mass`, which means that Drag should increase linearly with the mass of the ship.

* The result for a sphere will end having `Mass = radius^3`, meaning that `CrossSection = radius^2 = radius^3 / radius = Mass / radius = Mass / pow(Mass, 1 / 3) = pow(Mass, 2/3)`. So CrossSection increase less than linearly with the mass of the ship.

Then, if you would that your model fit with a behavior similar to that of the real world, you should apply one of the above (or a linear blend of those) and try to make the `attributes.Get("drag")` to behave as 'K'... Then the model will become more usable.

**Take on [turn rate](https://github.com/endless-sky/endless-sky/blob/02a280c1c1c0e7dc83f54e42a4954637579d3ca4/source/Ship.cpp#L3447-L3450)**
that's 'physically' wrong, the turn rate in general is not scaling with the 'InertialMass', but with the _moment of inertia_ and the moment of inertia of a thin shell and of a sphere increase [waaaay more rapidly](https://en.wikipedia.org/wiki/List_of_moments_of_inertia) than Mass.

**Take on [acceleration](https://github.com/endless-sky/endless-sky/blob/02a280c1c1c0e7dc83f54e42a4954637579d3ca4/source/Ship.cpp#L3454-L3458)**
well, this is 'physically' right :wink: 


Concluding, the general approach I took here is to abandon the 'linear' rules you used and find a way to integrate the above rules.

Using them (with some correction coefficient, of course...) should lead automatically to a better simulation.

Couple of examples using that approach:
* turn rate is decreasing a lot when you double mass, so it's easy to do what @Zitchas [do here](https://github.com/endless-sky/endless-sky/issues/5271#issuecomment-689965274)
* fighters gain a lot because they have less cross-section, and thus max speed is a lot more.

If the idea and the underneath reasoning is well received, I can provide some formula and spreadsheet in order to keep gameplay the same.

**Comment by brendanjones** [comment]
I think this is still valid. Nerfing the acceleration and turn ( i.e. increasing the inertia) of heavier ships gives more variety between ship classes, and introduces more potential play styles. At the moment, a larger ship is always better, because (as mentioned above) there's no attribute penalty for using a larger ship. This lack of variety actually makes the game less fun, IMO.

I think the solution is fairly simple: lower the acceleration and turn rate of larger ships. Top speed can stay the same because it's realistic that a large ship can accelerate to high speeds, given enough time. This should be done as a constant value relative to ship mass, not worked out per-ship.

Doing this adds the following question to the game: Do I go for a larger ship that is stronger (can fit more weapons/shields/other outfits) but is slower to accelerate & turn, or go for a smaller, more maneuverable ship at the expense of ship strength? Same for escorts, do I keep some more maneuverable ships in my fleet or just have slower, more powerful ships?

A little example of a capital ship that's more maneuverable than most NPC fighters, from my current fleet:

<img width="773" alt="Screenshot 2023-03-31 at 10 49 22" src="https://user-images.githubusercontent.com/16049594/229074344-0c8329f3-d44c-47ea-b3c9-e170619b1ac1.png">

Versus:
<img width="629" alt="Screenshot 2023-03-31 at 10 59 06" src="https://user-images.githubusercontent.com/16049594/229075573-5c46d478-753f-4bb8-b27e-45feca83a8c9.png">

**Comment by brendanjones** [comment]
Another solution that could be added both separately or in addition to the increase in intertia values is separating engine capacity into Thruster and Steering capacity. 

This passes the 'realism check': different ships would be designed to be able to take more or less thrusters on different parts of the ship. As Zitchas mentioned, this change could bring variety in ES engine stats more in line with EV ships: you could alter ships to be fast in a straight line, or fast at turning, or with balanced thrust and turn. 

This solves some of the issue mentioned above: we could give cargo and city ships (hello, Bactrian) lower turn rates to reflect that they just travel from point A to B. You could give some fighters insane turn rates so they can dodge around larger ships and their weapons. You could give another fighter/interceptor a lower turn rate but super high speed, so that it can be used for ramming targets at high velocity before turrets have a chance to track them (hello [Thunderhead](https://evn.fandom.com/wiki/Thunderhead)). A larger ship could be given a low top speed but a high turn rate, so that it can mount powerful guns (not turrets). So many possibilities!

I can imagine this would be less popular than the intertia change, however: it does after all reduce the ability for the player to customise ships as they like. I like it, though: with too much customisation available every ship around the same mass is basically the same. Differentiation between ships and the play style they encourage is good!

**Comment by Quantumshark** [comment]
I'd just like to point out this, since no-one seems to have addressed it yet.

>And in terms of progression of power as you increase in engine size, at the same time that the average human heavy warship has 565% more drag and 661% more mass than a human interceptor, huge thrusters have about 1260% more thrust in the case of ion and plasma thrusters, and 807% more thrust in the case of atomic engines when compared to the tiny thruster of the same engine category.

Worth noting that with the specific exception of the Sparrow, interceptors don't use the tiny thrusters, they use the small ones. 
Similarly, most heavy warships use the large thrusters - or in many cases the medium ones - rather than the huge ones.

**Comment by dletai** [comment]
@vitalchip 

Shouldn't the hull multiplayer be variable according to tech level (e.g., using Yottrite instead of Titanium), so higher tech hull is thinner than equiv hp hull on lower tech (a.k.a human) and hull mass also derived from it, instead of from hull v alone? In essence, use hull mult * hull v to get hull mass?
That would allow "getting rid" of hull mat, as it's already factored in. Alternatively, use only Hull Mat directly, and get rid of the multiplier. IMO This is analogous to how if you have mass and density, you shouldn't add volume as an independent variable.

> 
> Hull Mult is a multiplier, it's a broad stroke attempt to gauge a hull thickness, based on a stronger hull being thicker. I've used a square root relationship as I doubt you'd need 2x as thick to get 2x strength.
> 
> The reference size I used was 5cm thick Titanium for a 400 strength hull. I din't go into the probability that there would be 2 hulls, an outer to absorb damage and an inner pressure hull.
>
... 
> 
> Hull Mass is the mass of the material needed to construct a cube, internal volume of "Frame Vol" of the specified material density, given the calculated thickness.

**Comment by dletai** [comment]
@mike-f1 
> 
> **Take on [turn rate](https://github.com/endless-sky/endless-sky/blob/02a280c1c1c0e7dc83f54e42a4954637579d3ca4/source/Ship.cpp#L3447-L3450)** that's 'physically' wrong, the turn rate in general is not scaling with the 'InertialMass', but with the _moment of inertia_ and the moment of inertia of a thin shell and of a sphere increase [waaaay more rapidly](https://en.wikipedia.org/wiki/List_of_moments_of_inertia) than Mass.
> 
I think there are 2 separate issues here - turn rate (which is actually spin rate) and shouldn't be affected by inertia if starting from 0, and making headway in the new direction (changing the vector of the ship).
I find it awkward that ships take so long to spin, but can move in the new direction almost immediately after starting to thrust in the new heading. Not sure how hard that would be to add to ES, so possibly not feasible, but inertia tied directly to mass of ships, making big ships have to turn much earlier and accelerate longer in the new direction in order to land or come to a complete stop would be more realistic than further nerfing the turn rate. With that in mind, forward guns make sense on capital ships (somewhat) as the ships can turn "quickly" (at least enough to hit a ship 2 tiers lower) but if they continue to accelerate (firing thrusters) while at it, they'll screw up completely their routes, and will have a much harder time re-engaging. This should lead to HW remaining slow of their own accord and using ranged weapons, to not move out of effective combat range. Just my 2 cents.
Fun tactic this could lead to - spinning top - HW starts spinning in place, can't really stop (due to moment of inertia physics) or control it's heading, but obliterate swarming fighters unless they're moving away in time.

**Comment by dletai** [comment]
@brendanjones I don't believe your kestrel example is valid. Superior tech should be magic. Getting quarg powersupply and battery should be next to impossible legitimately  and if you manage it without getting every quarg/drak/archon hostile on sight - kudos to you (Does the game enforce immediate -1000 rep and hostile to a player who attacks quarg? Because if it doesn't, it should).
This kind of tech should feel like magic, I don't see the problem with that.

**Comment by dletai** [comment]
I'm missing reference to heat from the current discussion - bigger engines are hotter than smaller one, better performing engines are hotter than slower engines, but one obvious (at least to me) way to enforce less performance of ships could be achieved by multiplying the heat coefficient rather than a simple sum - bigger atomic engines should be hot enough to require so much extra cooling as to make the resulting ship much less combat effective due  to much lower outfit space remaining.
