### ISSUE TITLE
Free Worlds Checkmate Only Outifts

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5287]
**Is your feature request related to a problem? Please describe.**
I would like the Ionic afterburners and regenerators to be removed from marauder ships, as this makes it so the player does not have to do the Checkmate branch to get them, making it less likely for them to do Checkmate.

**Related Issue Links**
Look at this page showing the Marauder Leviathans. They have outfits from the Checkmate Story line, and even electron beams that you can obtain before even starting the free worlds story line! https://endless-sky.fandom.com/wiki/Marauder_Leviathan
**Describe the solution you'd like**
I would like the marauder ships to have these Checkmate branch outfits removed.

**Describe alternatives you've considered**
An alternative is to just make them always self destruct when you board them.

**Additional context**
I want to make it so more people will do Checkmate, and I think this may help a bit.

**Comment by W1zrad** [comment]
It would seem the intent behind this request is more about improving Checkmate than it is removing the Checkmate-exclusive outfits from Marauders. If so, #4672 is likely to address your general concern about not as many people playing Checkmate (whenever it is finished, that is).

**Comment by Amazinite** [comment]
As far as the electron beams go, that's intentional. (See: #1929) Notably, the S-type shield generators use to be used by the Hai, meaning that the Marauders were intended to have Hai shields, and some of them do use Hai weapons, but given that the electron beam is used, I don't see why the S-type shield generators couldn't be used on Marauders as well.
