### ISSUE TITLE
Feature Request: Kor Mereti and Kor Sestor Faction Descirptions

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5307]
**Is your feature request related to a problem? Please describe.**
I noticed that almost every faction has a description, even sub-factions (Navy Oathkeepers and Intelligence) and extinct species! (Builders and Sheragri) So for that reason I think that the Kor Sestor and Kor Meteti should have faction descriptions as well.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think that these factions should get there own descriptions in the Logbook.

**Comment by W1zrad** [comment]
The Kor Mereti and Sestor are briefly explained in the Korath faction description (so are the exiles, as well). Splitting up all four factions (Efreti, Mereti, Sestor, and Exiles) into their own faction descriptions instead of a general "Korath" is certainly a possibility., but I don't think it would serve any substantial purpose that the current faction description doesn't, at least right now. Maybe if some more substantial lore is added to Korath space (i.e. Wanderers Act III), then it would be necessary, but for the time being it doesn't seem pressing.

**Comment by Luuiscool4567** [comment]
There's not really much we could say about them honestly. If we really wanted to expand on the faction descriptions, we might have to just describe design philosophy and how they communicate throughout the Wanderer campaign. Otherwise, we don't actually  "meet" the Kor Meterti near the end of the middle of the Wanderer campaign and never meet the Kor Sector.
