### ISSUE TITLE
Sargas Illegal Outfits

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5320]
**Is your feature request related to a problem? Please describe.**
I noticed that the outfitter on Trinket in the Sargas system is selling nerve gas. I don't know if this is intentional an error? 

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think that the no more illegal outfits should be sold on Trinket in the Sargas system.

**Additional context**
I think that the authorities would have figured out they are selling nerve gas seeing as its a republic/free worlds system.

**Comment by Anarchist2** [comment]
monkas

**Comment by Amazinite** [comment]
#388

**Comment by Amazinite** [comment]
Bro. Please search before you post. And maybe join the Discord server. Flooding us with all these issues where most of them end up closed because it's either a duplicate or already done or intentional isn't helping anyone. It would be far easier for everyone if you would just ask questions like this on the Discord server where you can immediately get a response from a bunch of people telling you why things are the way they are.

**Comment by starmlerp** [comment]
Man, can't wait for another person that has never used github before to come in here and open the same issue, and start this unending cycle over again.
