### ISSUE TITLE
More City Ships

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5337]
**Is your feature request related to a problem? Please describe.**
By the time you realize the deep has mission chains of its own, you will have ships far more powerful then the Bactrian available to purchase. Yes, I am aware that the deep missions are being nerfed, but we need to make them more attractive to players. The Bactrian is just one of the city ships, there are probably tons of powerful ships (like the one on the license), Carriers, Interceptors  (Mostly for mining) and freighters to carry cargo. Also, maybe throw in some drones, as human space has almost no drones at all. In fact, the entire game has almost no drones at all (As mentioned in another issue.)

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think that maybe some of the old city ships should be brought into the game, to add more flavor to the game. There have to be city ship designs worth selling, right?

**Describe alternatives you've considered**

**Additional context**
I really want to know what the city ship on the license is. Maybe a post Bactrian mission chain which makes it purchasable? Thank you for reading, feedback is appreciated. (By the way, I don’t really like discord. I think it’s a waste of my time.)

**Comment by Zitchas** [comment]
> I think that maybe some of the old city ships should be brought into the game, to add more flavor to the game. There have to be city ship designs worth selling, right?

It is worth noting that city ships are antiques. They date to a time period of human history when humanity had very few planets, and large expanses of empty space between them, and *lots* of unexplored space beyond them. It is also implied that hyperjumps may have taken longer back then, or had other factors that slowed down travel. In any case, these ships had to travel for weeks between systems, and thus had to be capable of making multi-week or even month long voyages between planets. These ships were also the primary means of settling new systems, and thus had to be capable of travelling weeks to get to the new world, deposit their passengers and cargo, and then return, all without the benefit of being able to refuel or resupply. 

This has a lot of design impacts compared to present day ships:
- Few-to-no threats: 
    - Low hull and minimal shielding. All they need to handle is asteroids and radiation. Practically by definition, if there is nothing to plunder, there are no pirates.
    - By the same token, minimal-to-no weaponry. A basic defense turret to shoot the occasional asteroid is really all they'd need. And they wouldn't waste resources on hardpoints, either.
- Massive life support systems: Hydroponics, air tanks, water tanks, recreational space, etc. None of these really have an equivalent statistic in ES, and in mechanic terms translates to "stuff that increases the mass of the ship but doesn't provide any combat or mercantile benefit."
- Large fuel tanks: larger than normal fuel reserves. 

So basically, all these city-ships would be basically transports or freighters that have significantly less hull & shield than present day ships; even fewer gun & turret hardpoints, massively more mass; and more fuel. In short, they'd be weaker and slower, but longer range.

So yes, these would be different ships from what we have access to now, but they don't make economic sense to be mass produced or fielded in the current economic reality of Endless Sky. Pirates are a constant threat almost everywhere in human space. (They even raid into Sol and paradise worlds if the target is tempting enough!), and there are so few gaps of uninhabited planets that having an extra long range doesn't provide that much of a benefit.

At the end of the day, while I would love to see  a bunch of old city-ships flying around as collector's items or relics of a bygone era (it has been probably over 5 centuries since any city ship other than the Bactrian has actually been manufactured), they don't make sense to have for sale as a commonly available ship.

**Comment by Plip-Plop** [comment]
There are lots of alien city ships. If you want more **human** city ships, you will need to make a plugin for them yourself.

**Comment by McloughlinGuy** [comment]
why were all my ideas last year so terrible?
