### ISSUE TITLE
Wanderer Carrier

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5341]
**Is your feature request related to a problem? Please describe.**
The wanders have a drone, but not ship capable of carrying it!

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
The wanderers need a carrier for the Flycatcher. Also, it wouldn’t hurt to give them a fighter.

**Describe alternatives you've considered**
Another way to go about this would be to have the carrier be available later in the storyline, becoming available at the same time as the drone.

**Additional context**
The flycatcher needs something to transport it between worlds. Otherwise, it can’t be used to defend worlds that don’t produce it and will become a dead weight in the economy, seeing as no one will buy something they can’t use.

**Comment by beccabunny** [comment]
#3676
#1730
#2309

**Comment by Amazinite** [comment]
> Related Issue Links
> Has anyone else had this issue or idea? Share some links to those Issues, Google Group threads, or Steam forum posts

This section of the template is for *you* to fill out, by the way, not to leave as is and let others do the work for you.

**Comment by tehhowch** [comment]
@McloughlinGuy From another thread:

>  (By the way, I don’t really like discord. I think it’s a waste of my time.)

The recommendation of more real-time avenues for answering your many questions is not just a consideration of _your_ time.

Everyone is expected to follow the contribution guidelines, which means filling out the issue templates or using the most appropriate means for resolving questions, because everyone else's time is valuable, too. **If the issue templates seem laborious for what you are trying to ask, let that be a sign that perhaps your question is not serious enough for this forum, and should be directed elsewhere.**
