### ISSUE TITLE
Logbook flaw?

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5344]
**Is your feature request related to a problem? Please describe.**
In the logbook it says that the pug could beat the drak if they really wanted too. But that isn't mentioned anywhere in the game other than the logbook

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think the logbook should be changed so it doesn't say that.

**Additional context**
We don't know the true power of the Pug, and the logbook shouldn't just assume.

**Comment by Arachi-Lover** [comment]
to provide further context, the log entry is this:

`		log "Factions" "Pug" `The Quarg claim that the Pug are powerful enough that they could defeat the Quarg, or even the Drak, if they chose to. But the Pug treat warfare like a game. When battling another species, the Pug will limit themselves to ships and weapons that are weak enough that the other species has a chance of defeating them.`

which is added by the optional mission where the player asks the Quarg about the Pug. during that mission, the Quarg never claim the Pug could beat the Drak (one could argue they never say they could beat the Quarg either), in fact the only mentions they make of the Drak is that the Pug posess wormhole technology, saying that that is a technology the Drak don't posess:
`The Quarg is silent for a long moment. "The Pug have meddled with the affairs of many species in this galaxy," it says, "but they are not native to it. They came here through artificial wormholes: a technology that not even the Drak possess.`

and that the Drak will not help humans fight the Pug, for they only interfere when their rules are broken, and that either way it'd only make it harder on the humans since the Pug adjust their tech level to their opponents (which doesn't necessarily mean the Pug have something to beat or even match the Drak, for even if we assume Arfectas are their strongest ship, them bringing those in would already make the situation of humanity a lot harder, which is what I believe the Quarg is saying in the quote):

`"No," it says. "The Drak do not interfere in a war unless their rules are broken. And, it would not help you anyway; the Pug always adjust the strength of their fleet to give their opponent what they consider to be fair odds."`

**Comment by tehhowch** [comment]
The logbook is another worldbuilding tool and doesn't need to be a strict rehash of directly stated things.
