### ISSUE TITLE
Hand To Hand Outfits

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5354]
**Is your feature request related to a problem? Please describe.**
I noticed that there are only 3 hand to hand outfits in human space! I would imagine that there are more weapons that people use then just Grenada’s and laser rifles to defend and attack ships.

**Related Issue Links**
Has anyone else had this issue or idea? Share some links to those [Issues](https://github.com/endless-sky/endless-sky/issues), [Google Group threads](https://groups.google.com/forum/#!categories/endless-sky), or [Steam forum posts](https://steamcommunity.com/app/404410/discussions/)

**Describe the solution you'd like**
I think more hand-to-hand outfits should be added to the game.

**Describe alternatives you've considered**
I don’t have alternatives.

**Additional context**
I think a few extra hand to hand weapons would be a nice addition to the game.

**Comment by tehhowch** [comment]
Duplicate of your previous post https://github.com/endless-sky/endless-sky/issues/5353, which was closed because you didn't fill out the issue template in full. You need to search for existing related issues, and share the results of that search and what distinguishes your request from any existing requests.
