### ISSUE TITLE
Tributes are woefully low

### ISSUE THREAD

**Issue by mohmad-null** [endless-sky/endless-sky#5371]
0.9.12
Yes, I know that "over time" they build up, but consider this pirate planet I just conquered. I went in with the following (stock except the Dreadnaught which was customised with bits from around the galaxy):

6* leviathan, 4* falcon, 5* osprey + 1* dreadnaught (me)

And I lost the following:
3* OSPREYS, 1* FALCON

The lost ships have a combined sale price of 10 million (all are 25% depreciated).

For that, I get a tribute of 1300 per day. Or 474,500 per year. Put another way:
* It will take 1 entire year just to pay for the fleet to travel there
* It will take another 20+ game years to pay for the losses.

I'm now at 10 game years and am at end-game. I've completed the main story and various side stories. There's no way that planet is going to pay for itself in the remaining play time I'm going to be playing and I went in with an overwhelming fleet which even had I taken no losses would have taken an entire year to pay off just the crew costs to get there.

(And lets not even get into the economics of the lost opportunity cost from those ships\money over the next 20 years! :-) )
---

Put another way:
* If tribute is only collected end game when you have massive fleets, then trickling it in long term is pointless because the player won't be around to use the winnings.
* If tribute is collected early game - you're going to have a smaller fleet and lose more ships so still not going to pay it off.

There's no scenario I can see where the current tribute system pays off.

**Comment by tehhowch** [comment]
Don't ignore the templates. Your background research would have led you to discover the tribute system is not meant to be meaningful

**Comment by mohmad-null** [comment]
> 
> 
> Don't ignore the templates. Your background research would have led you to discover the tribute system is not meant to be meaningful. One such existing issue you are expected to have found is #4278

I searched for open tickets with the word "tribute" in and none seemed apt; hence opening this.

**Comment by Zitchas** [comment]
The point that Tehhowch is probably making is that if a similar issue has been raised, and closed; it probably means that the subject has been discussed and is considered decided, one way or another. If you used the template, and listed the various closed issues that are relevant to tribute, and then presented your arguments as to why the reason for closing those other issues is wrong, then you are provoking new discussion, and that is useful.

Also, it is worth noting that a moderately significant proportion of the community (including some Devs) view tributes as a meaningless element of the game that should actually be simply removed outright. If you think the pirates pay is inadequate compared to the fleet you need to conquer them, wait until you meet the Remnant... the pain to benefit ratio is significantly worse.

At the end of the day, though; the forces you have to defeat are based on how many ships are likely present at that place and how likely they are to fight against paying tribute. How much money the place pays is based on how good their economy is, how much money they have available, and how easily the primary authority could get its hands on said money in order to pay you. Pirates have a strong tendency to oppose anyone taxing them (which is what you basicallly want to do) and tend to have very informal economic systems, which leads to low cash flows, hence the low pay.
