### ISSUE TITLE
disabled ship attackers

### ISSUE THREAD

**Issue by neevok-eu** [endless-sky/endless-sky#5446]
**Describe the bug**
In a battle with multiple ships the AI-ships keep firing on a disabled ship to destroy it while other enemy ships are still a bigger threat.
This makes it needlessly difficult to board and take over enemy ships.

**To Reproduce**
1. Go to any system with several friendly and enemy ships
2. Disable 1 enemy ship
3. Friendly ships (often navy or local militia) keep firing on the ship you disabled (and are possibly trying to board) while active enemy ships are still flying around and attacking other ships.

**Expected behavior**
Defenders should focus on active ships and ignore disabled ones. Why do they want to destroy the disabled enemy ships at all? At least give more time for boarding. (Possibly detect that the board key has been pressed and change the behavior.)

**Comment by Zitchas** [comment]
I agree that it seems odd that the AI will sometimes prioritize disabled ships, but in most cases they are simply taking shots of opportunity on their way to another ship. Unless the government actually likes to disable ships, most ships in ES take the view of "better to finish the kill than to risk an enemy getting repaired and re-entering the fray."

And the AI does, in fact, repair ships; although doing so is a pretty low priority.

There is no reason that the game should detect that the board key has been pressed and change behaviour. Other than the Remnant (which explicitly aim to disable ships instead of destroying them), no faction explicitly *wants* you to board ships for them. And non-allied but not-hostile ships shouldn't care at all.

Note, some fleets (especially NPCs) have the vindictive personality, which explicitly specifies that they will blow up disabled ships.

**Comment by Amazinite** [comment]
#591
If a ship that doesn't have the disable personality is targeting an enemy, it will attack that enemy until it is destroyed, not simply disabled, even if that enemy becomes disabled before the ship gets to it. A disabled ship can be brought back into the fight, but a destroyed ship can't, hence why one would finish off disabled ships. If you disable a ship without anyone else targeting it though, other ships will only take pot shots at it if they just so happen to be in range instead of intentionally targeting and destroying it, hence why dragging enemy ships away from the system center is a useful strategy for capping so that other ships won't target and potentially destroy it.
Pirate and Free Worlds ships have the disable personality, so if you're attempting to cap, being in systems with those ships is useful.

**Comment by InfiniteDonuts** [comment]
As @Amazinite said, Merchants and the Navy destroy ships instead of leaving them disabled is due to the fact that they don't have the `disables` personality. Also, it helps to balance ship capping: I can't tell you how many times I've descended upon a disabled Bastion or Osprey with the intent to cap it and then a merchant ship just blows it away with missiles. If they just disabled, you would be able to cap a huge fleet in a very short amount of time.
