### ISSUE TITLE
Strange landing behavior with reverse thrusters

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#5520]
**Describe the bug**
When attempting to land with the Penguin, which has reverse thrusters built in, the reverse thrusters will fire while the ship is close to the planet, causing you to take longer to land.

**To Reproduce**
Try to land with a Penguin.

**Expected behavior**
The ship shouldn't be fighting itself to land.

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: self-compiled
 - Version: latest commit as of posting (https://github.com/endless-sky/endless-sky/commit/5364605634ff0eabbd3b500c6e3ef53f6554abdb)

**Link to save file**
N/A

**Additional context**
AI use of reverse thrusters was recently updated by #5352.

**Comment by vitalchip** [comment]
What seems to be happening is that on a normal approach the ship reaches the calculated stopping point, cuts thrust and passes the point. This makes the ship turn to face the point and then it decelerates using main engines. When there are reverse thrusters they fire, and instead of smoothly passing the stopping point it gets recalculated due to a decrease in velocity, putting it out in front again. The ship moves forward again to intercept and depending on the magnitude of the reverse thrust they may or may not fire again. This behaviour can also happen right before landing causing the ship to 'slide' sideways under reverse thrust, because its (say) pointing left to intercept the stopping point but firing reverse thrusters will cause it to slow but move right.

**Comment by vitalchip** [comment]
Reverse landings can be improved a bit with a quick code change but they're still slower than a regular landing under most circumstances as the only way I've been able to keep the landing reliable is where forward and reverse thrusters alternate. Anything else I tried just ended up off target at the end and 'circling the drain' to land.

Here's an example, it's what I refer to as the 'shaking your tail feathers' approach.

https://vimeo.com/484002443

**Comment by vitalchip** [comment]
Far less noticable with a small ship like a Penguin.

https://vimeo.com/484006527

I suspect reverse landing could be made faster by lowering the calculated stopping distance for a reverse landing, as it stands it seems to be much longer than required (if I press and hold reverse at the moment the AI first applies reverse thrust I stop long before reaching the planet)  This would require testing over a range of values to be certain of a reliable landing.

**Comment by vitalchip** [comment]
This is the change I made, it just points the ship at its own velocity when reversing, countering drift and stopping the turn around.

<img width="924" alt="Screenshot 2020-11-26 at 11 15 34" src="https://user-images.githubusercontent.com/65342577/100346087-32b50700-2fdb-11eb-93d9-ad8109172995.png">

**Comment by InfiniteDonuts** [comment]
Yes, THANK YOU DERPY! Trying to land my Arfie takes FOREVER. Please fix this!

**Comment by Terin** [comment]
Implementing that fix is a definite improvement in many cases, but not nearly big enough compared to the new worst-case scenario, in the case of an Emerald Sword. This can double the travel time when trying to go to a close location while not facing it. Either a special case needs to account for this, or we'll need another approach entirely.

https://user-images.githubusercontent.com/4471575/103113093-acfa9a80-461e-11eb-8986-63274c664c26.mp4

**Comment by Terin** [comment]
Testing with a new patch Vitalchip made (tightening the Move() angle to 95% instead of 80%) improves the worst case scenario to quicker than current (4.25s vs. ~5.33s). Going to re-open the original PR now.

https://user-images.githubusercontent.com/4471575/103193296-a92a7a80-48a1-11eb-9bd4-6327836cdff0.mp4

**Comment by vitalchip** [comment]
The latest change helps in situations where a short distance is travelled to a small target by not firing forward thrust until the ship has turned further in line with the target. I'm still able to create situations (heavy ships, low drag) where the ship approaches the planet with enough side drift to require stopping just outside the target radius and re-aligning for the final 'leg'. Without an entirely new approach method I think there will always be cases where extra correction time is needed but those should be relatively few.
