### ISSUE TITLE
Make Drone/Fighter Distinction (WRT Mothership Capability) Clearer

### ISSUE THREAD

**Issue by cathalgarvey** [endless-sky/endless-sky#5549]
**Describe the bug**
I just learned the hard way that Drones cannot be carried by regular carrier motherships, for example the Skein - I just bought a trio of Flycatchers, and found that I could not dock them and carry them to another system.

This is unexpected behaviour to be honest - I assumed that Drones and Fighters were in most ways equivalent.

Resolutions I would suggest to make things clearer:

* Remove the distinction and let Drones dock in carrier ships of any kind.
* OR: Have a warning notice on Drones that they can only be carried by specific ships.
* (± to the above) Have a special outfit for "regular" fighter carriers that lets them control and dock Drones.

Just my 2c.. I had really been looking forward to a little fleet of Flycatchers armed with turret beam weapons. :)
Related question: Aside from capturing Navy ships, are there currently any ways to get a Drone-capable ship?

**Comment by Zitchas** [comment]
That's not a bad idea, actually. Drones fitting into fighter slots wouldn't cause balance issues (drones are universally less powerful than fighters from the same tier). But fighters should never fit into drone slots. 

The Remnant have a medium warship-carrier that can carry 4 drones and 2 fighters. (and the Remnant have a very good drone & fighter pair to use with it, too.

**Comment by cathalgarvey** [comment]
Thanks for the heads up about the Remnant: Their ships look like a nice step up from a regular (civilian) human carrier, and it's good motivation to follow their quest line for a while. :)

It does make sense for Drone bays to be not necessarily capable of handling fighters, unless there were some converse outfit for fighter craft to allow "remote control" from the mothership - e.g., a drone-bay-enabling outfit for fighters, and a drone-controlling outfit for motherships, to allow cross-over without waiving the distinction completely?

**Comment by Zitchas** [comment]
Well, it is also a matter of size. Drones are considered to be smaller ships than fighters. While there are pretty small fighters, for simplicity we are currently going with the logic of "drones are smaller ships than fighters, so fighters cannot fit in drone bays."

There has been talk about making bays with size limits instead of type limits; but I don't know if anyone's gone very far with those. General consensus that I've heard is that people think they'd be confusing. "What do you mean, my 99 ton drone can fit in this bay, but my 100 ton fighter can't?" Just having it be drone bays and fighter bays and not mixing them is simpler.

There's no concrete lore surrounding it, but generally speaking:
Drones:
- Are smaller than fighters
- Have special AI related requirements (power, etc)

Fighters:
- Are larger than drones
- Require life support hook ups
- Require pressurized bays or docking connections so the pilot can board the fighter.

**Comment by Amazinite** [comment]
I'm not sure what more distinction there needs to be beyond "drones go in drone bays and fighters go in fighter bays."

**Comment by cathalgarvey** [comment]
If nothing in the game were mechanically changed, then at the least it would be good to get some clarity in the UI and the descriptions.

Consider for example, that outside Remnant space, there are no options to purchase ships that have drone bays, so it's very easy to miss the fact that _drone bays and fighter bays are different things_.

I had completely assumed that Drones were just cheaper, smaller Fighters without pilots, and that Drones go in Fighter bays. Nothing in the UI was present to make it clear that a Fighter Bay could not house a Drone.

I had to buy drones to get a warning, and even then my first guess was that there was some bug failing to assign the drones to the available bays.

Since learning of my mistake I've been able to pursue more appropriate routes for Drone management and I'm happy again (I have a fleet of 10 Flycatchers with blaster turrets and the results are amusing and fun), but my first experience with drones (cool little ships you can buy but not fly) was baffling.

**Comment by vitalchip** [comment]
One problem with having more than one type of carried ship in a bay is that it could lead to a situation where a drone takes up a fighter bay because it is allowed but then a fighter arrives back and can't fit in the drone bay that's vacant. You may answer that issue by only having combined bays but then there is no way to create a drone only carrier.. so you need another solution to that. Not to mention aesthetic concerns where the carried ships are external and have 'sized' bays, such as the Ibis.

**Comment by samrocketman** [comment]
I think this will be less of an issue when I open a PR for drone and fighter bays as outfits.  A player could install drone bays and store weapons in their cargo temporarily to take drones or fighters with them.

**Comment by Amazinite** [comment]
I've gone ahead and added a bit to the end of the description of every drone and fighter describing how such ships lack hyperdrives and need a specific bay in order to be carried: bbfeaa0
