### ISSUE TITLE
Hitting Alt+Key in windowed mode causes error beep on Windows

### ISSUE THREAD

**Issue by Terin** [endless-sky/endless-sky#5589]
**Describe the bug**
When hitting Alt, and some kind of alphanumeric key while in windowed mode on Windows, the OS will play an error beep as if you've entered an invalid command. This is particularly trouble when using WASD for movement keys, and you want to use alt for a useful keybind.

**To Reproduce**
1. Enter windowed mode
2. Hit Alt+Some Alphanumeric character (Alt+B, Alt+5, etc.)
3. Hear Windows play an error beep

**Expected behavior**
The game will remain silent when pressing that button combination.

**System (please complete the following information):**
 - OS: Windows 10 Pro, version 1909 build
 - Game Source: Self-compiled
 - Version: commit hash c5588f9

**Comment by tehhowch** [comment]
Basically, `Alt` triggers windows menus, we don't have one, so combining Alt with a "shortcut key" throws an invalid shortcut alert. First order of business is probably to verify if this is still an issue in SDL v2.0.14--since we use it to create our game window and handle key input--and if so, investigate remediation.

**Comment by Terin** [comment]
This hasn't been an issue for a while, likely fixed from one of the various SDL or other library updates.
