### ISSUE TITLE
Mission information

### ISSUE THREAD

**Issue by adegans** [endless-sky/endless-sky#5605]
**Is your feature request related to a problem? Please describe.**
Kinda, but not really - Can't see for which faction a mission is done and how it affects relations/standings.

**Related Issue Links**
n/a

**Describe the solution you'd like**
When selecting a mission show which faction it's for - pirate, free world, blabla. - and show how it affects the factions.
+1 standing with pirates, -5 with this and that other faction.

**Describe alternatives you've considered**
Looked for plugin, there is none that I could find.

**Additional context**
As a whole, factions seem wholly under represented and very hard to work with.
To make this more transparant and part of the game certain actions should impact standings/relations AND that should be visible. I didn't find out there were factions that mattered and that I could upset them until after a week of playing...

To make the universe more immersive this should be more visible and matter more in the game.

Do too many missions for one faction, loose standing with another and perhaps get paid less with them, or get offered 'cheaper' missions with them. Get high enough standing with one, and you can get away with smuggling or illegal stuff more easily (less fines, no fine, etc.)

(Kinda like Eve Online has it, but then in a appropriate way for Endless Sky)

**Comment by adegans** [comment]
The relations also could affected trading... High standing gets a X% price boost and lost a loss of Y%. 
And it could affect response times from navy when asking for help. Higher = slightly quicker.

**Comment by Zitchas** [comment]
Reputations are currently very binary: For the  most part, either you have positive relations, in which case they are neutral to you, or negative, in which case they are hostile. There are a few places where you need to have a certain amount of reputation in order to land or qualify for missions, but not that many.

There are a lot of mission (probably even most missions) that don't actually affect your reputation at all. Unlike the EV trilogy (where doing generic jobs would build up your reputation), in ES you pretty much only build up your reputation by repairing ships of that faction or killing their enemies.

**Comment by Terin** [comment]
As it stands with the general plot of the story, human space is relatively united until the Free Worlds break off from the Republic, and even then, they have a tenuous peace. You make your way into the story missions for the Free Worlds (or eventually the Navy or Syndicate) by doing authored story missions at their spaceports, at which point you'll be more set in until the war ends. Doing jobs for the Syndicate would have no reason to piss off the Republic or Free Worlds for most of the game.

The world of Endless Sky isn't really built with these monolithic, disparate factions in mind you'd have to slowly pledge your loyalty to by grinding reputation with jobs. Pirates are a notable exception, but mostly due to them being underdeveloped. A theoretical pirate campaign would probably act similar to the Free Worlds, where various pirate missions would open their ports to you, eventually resulting in you more fully putting on pirate colors and becoming hostile to the Republic.

> I didn't find out there were factions that mattered and that I could upset them until after a week of playing...

How did this happen, exactly? Outside of story beats, the only way to negatively alter your reputation with a friendly faction is to manually target and attack them.

**Comment by adegans** [comment]
@Terin I took a mission that went into pirate space and couldn't complete it because I wasn't allowed to land.
In a separate event, I accidentally attacked some navy ships (targeting the wrong ships) and it upset them all.

--

@Zitchas Even if relations aren't really a thing in a nuanced way, there IS a hostile/friendly relation in the game. But we as players can't see it. There is a whole section about it in the saves file though... So clearly it's a game mechanic, just not visible to us.

Adding a line in the mission description "This mission is for Syndicate, delivering to Free Worlds (standing: poor)".
Players will then be able to make a more educated decision on whether to do the mission or not.
As a risk indicator if nothing else.
Just the 'high piracy' warning in some missions is a risk indicator too.

--

As for missions/actions affecting relations - Factions that are neutral to one-another won't negative or positively impact relations of-course or very very slightly depending on the mission type. But it may increase the rep you get for the mission giver. 
Similarly, doing missions for pirates will please them, but may upset the syndicate and republic for example...
And if as you say, Free worlds is a kind of split-off faction from others, doing missions for them may slightly impact the relation you have with the faction the free worlds split off from and vice versa.
Generic trade/delivery missions much less so than the espionage stuff.

I think it'll make the missions more interesting or a bigger consideration other than raising your wallet balance if a reputation system exists. Same way that market prices fluctuate. It affects how you trade.

I'm not sure how much or on what scale (-1000 to +1000) or whatever this should work, nor what thresholds should exist for being allowed to dock or being attacked by navy or something like that. Or how much missions one should grind to raise standings. It could be very small so that for casual play it doesn't matter much unless you do really bad stuff like killing navies or endlessly hunting pirates. But a basic system like this would add to the game and if done right it won't overcomplicate things at all. It simply adds a consideration on how people may take missions or not. Same as how you decide what to trade between systems.

Lastly, I can't imagine this being very hard to implement at all. Since most of the mechanics seem to exist already. Just a bunch of if/else on the docking and +/-1 on missions completions/failures and certain actions that alter the numbers that are already there.

**Comment by Terin** [comment]
> @Terin I took a mission that went into pirate space and couldn't complete it because I wasn't allowed to land.

Pirates are hostile by default, but you can bribe your way onto their planets by hailing them. Some of the Free Worlds missions will describe that in more detail.

> In a separate event, I accidentally attacked some navy ships (targeting the wrong ships) and it upset them all.

As long as you didn't do permanent damage to them, they'll forgive you after you jump away. It's just them being temporarily hostile in response to your attack, but you need to disable/board and kill crew/destroy them for permanent reputation loss.

> @Zitchas Even if relations aren't really a thing in a nuanced way, there IS a hostile/friendly relation in the game. But we as players can't see it. There is a whole section about it in the saves file though... So clearly it's a game mechanic, just not visible to us.

Something may be a game mechanic in the backend, but iterating on it and surfacing it more wouldn't necessarily fit with or add to the game positively.

> Adding a line in the mission description "This mission is for Syndicate, delivering to Free Worlds (standing: poor)".
> Players will then be able to make a more educated decision on whether to do the mission or not.
> As a risk indicator if nothing else.
> Just the 'high piracy' warning in some missions is a risk indicator too.

The randomly generated jobs will never ask you to deliver places to a hostile location, so that information would always be the same.

> As for missions/actions affecting relations - Factions that are neutral to one-another won't negative or positively impact relations of-course or very very slightly depending on the mission type. But it may increase the rep you get for the mission giver.
> Similarly, doing missions for pirates will please them, but may upset the syndicate and republic for example...
> And if as you say, Free worlds is a kind of split-off faction from others, doing missions for them may slightly impact the relation you have with the faction the free worlds split off from and vice versa.
> Generic trade/delivery missions much less so than the espionage stuff.

That's the thing, by the time the Free Worlds are in open conflict with enemy factions, they're 100% hostile. The Republic going from -1000 reputation to -1010 reputation because you did generic jobs for the Free Worlds wouldn't impact the game at all.

> I think it'll make the missions more interesting or a bigger consideration other than raising your wallet balance if a reputation system exists. Same way that market prices fluctuate. It affects how you trade.

On paper, sure, it could be an interesting system, but like I said, the world of Endless Sky isn't built on balancing these reputations. At most it would just be a WoW-style "Grind your rep to exalted to a 20% discount", which isn't very interesting on its own.

> I'm not sure how much or on what scale (-1000 to +1000) or whatever this should work, nor what thresholds should exist for being allowed to dock or being attacked by navy or something like that. Or how much missions one should grind to raise standings. It could be very small so that for casual play it doesn't matter much unless you do really bad stuff like killing navies or endlessly hunting pirates. But a basic system like this would add to the game and if done right it won't overcomplicate things at all. It simply adds a consideration on how people may take missions or not. Same as how you decide what to trade between systems.
>
> Lastly, I can't imagine this being very hard to implement at all. Since most of the mechanics seem to exist already. Just a bunch of if/else on the docking and +/-1 on missions completions/failures and certain actions that alter the numbers that are already there.

You said it right there yourself, "Just a bunch" of things. Implementing some UI/text to establish a reputation change might not be too hard, but the only jobs in the game that do that right now are Pirate jobs, mostly as a workaround to let the player be an impromptu pirate before a more full experience is considered.

We could add a bunch of +1 rep to Syndicate missions, but it wouldn't do anything in the game right now. We'd have to consider a system that rewards higher rep, but that's still labor figuring out if we even want a system like that, or how to balance the reputation and discount caps, and trading is already fairly complicated that adding more modifiers onto it could cause problems. You mentioned how it could "affect response times when asking for help", and that'd be a pretty significant change in AI. All this adds up to something that could very well be hard to implement, on top of being something that just wouldn't fit with the game as-is.

There may be more specific, actionable things you could bring up that get more to the core of issues you've had. #218 mentions reputation titles, which could better communicate how much you damaged your reputation if you accidentally fired on someone. Or, when you fired on those Republic ships, did you open up your map and see the entire galaxy be hostile? That happened to me, and that could be a more specific issue to bring up.

**Comment by tehhowch** [comment]
This level of granular detail isn't something that fits with the design or intended ui experience. IMO, seeing how much something will change your reputation with X takes away from the roleplaying / character-building aspect of the game, biasing your choices to be based on numbers rather than who you'd like your pilot to be. To me, this info would _reduce_ immersion, not strengthen it.

On a more technical note, there's no guarantee competing a mission will give a given amount of rep, even if the mission completion state says so, because the mission may utilize branching or other conditional actions based on the player's current state--any numbers presented ahead of time would just be estimates.

Tying jobs & other missions to faction rep is already 100% possible. So is basing additional universe changes on the kinds of jobs you do - just need thought-out content that makes use of it.

**Comment by adegans** [comment]
Then why is there a reputation thing at all in the game if nobody cares for it or won't use it?
Why not just make pirates hostile then and everybody else friendly/neutral and remove the thing from the game...

If you're all so hell-bent on keeping it "dumb" or simple.

Never mind for making the suggestion, clearly a waste of time.
