### ISSUE TITLE
Dragons be here...

### ISSUE THREAD

**Issue by CaptKrevor** [endless-sky/endless-sky#5612]
**Is your feature request related to a problem? Please describe.**
A small side quest where you encounter an archaeologist in a spaceport (somewhere).  Similar to Train a Novice or helping that little Hai getting started, he asks for you to take him to some systems for 'research'.  Once you've traveled to all of them, you learn that the archaeologist has been "triangulating" a star system that doesn't appear on the map (yet) and isn't accessible via hyperlink (like Deneb pre-FW storyline).  Once he's done with his research (or you abort), he locates where the system is, but laments that there is no way to get there.

Post FW-Campaign/Acquisition of Jumpdrive:
Archaeologist seeks you out.
If you did the first mission, then he asks if you remember him.  If not, short introduction.  He asks if you can take him to <system X, planet Y> located at <these coordinates>.  IF you accept (why wouldn't you?), upon arrival, you do indeed a habitable planet that has a 'dying race' of what turns out to be dragons.  In their past, they had the ability to break hyperlinks which they used to isolate themselves, but this leads to their downfall over the eons.  They currently don't even know how they did it before, the knowledge was lost through the years.

Post Finding Dragons:

You can either help them (a trade port with not very lucrative prices for commodities), or plunder them (where you get a load of commodities for free, but then they want to eat you, so you can't come back).

**Related Issue Links**
I am unaware of any.

**Describe the solution you'd like**
New quests.

**Describe alternatives you've considered**
Do nothing. :(

**Additional context**
Ultimately, it's just a little flavoring of whether you are "Altruistic" or "Opportunistic"

**Comment by Zitchas** [comment]
This sounds like a great mini-mission set for a plug-in.

**Comment by CaptKrevor** [comment]
Thank you.  Question is:  How? :)  I'm only recently arrived at playing Endless Sky.  Did the main quest and several others, and even did the 4th wall ending suggesting "making more content", and seen some other suggestions for the same.  How would I get this added/made into a plug-in?

**Comment by Zitchas** [comment]
Creating plug-ins starts here:
https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins
With info specifically on missions here:
https://github.com/endless-sky/endless-sky/wiki/CreatingMissions

A lot of different missions exist in the game - one good place to start is to find a mission that does the same thing as your idea does, then change the conversations to be *your* story instead. Oh, and of course, put all that in the plug-in file. 

I'd recommend visiting the discord channel for more advice and guidance. There are also tools available to help with the plug-in creation process. GitHub here is better suited for requests and bug reports rather than plug-in making walkthroughs.

**Comment by CaptKrevor** [comment]
Thanks again.

**Comment by roadrunner56** [comment]
Sounds like an interesting idea! However, I would personally change the aliens from dragons into something else, due to the in-game Sheragi being established as a dragon-like species. A second dragon species would be confusing and unrealistic. 
Also, adding a new species, even if it is small and isolated, has pretty serious lore implications. I would highly recommend doing what Zitchas said and running your ideas through the Discord channel.
That being said, I personally think that ES could use some more alien species, especially in the base game.

**Comment by Zitchas** [comment]
That's part of the reason I suggested a plug-in. While we might have to be pretty strict about things like not doubling up on dragon-like species or having factions that are too-similar to others or things like that in vanilla content, there is no such problem with plug-ins. A plug-in simply needs a good/cool/fun story; it doesn't have to have the burden of being 100% lore compatible, which can be a major chore.

Keep the learning fun in a plug-in context; and if it turns out to be something people want in-game, well, that can be done later just as easily.

**Comment by Amazinite** [comment]
GitHub issues are mainly for "I want X new mechanic" or "I think X mechanic should be changed" or "I found a bug with X," not "I have X idea for story." If you have some sort of story idea then that is better suited for discussion on Steam or the Discord server, not for being tracked on the GitHub issues.
