### ISSUE TITLE
Ka'het Nacelles work without power

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#5660]
**Describe the bug**
Because of how energy consumption works, running out of power won't deactivate Ka'het engines, due to them lacking turning or thrusting energy.

**To Reproduce**
1. Install Ka'het engines on a ship without power.
2. Take off.

**Expected behavior**
The Ka'het engines should not function.

**Proposed Solution**
Add a tiny amount of thrusting and turning energy to Ka'het engines.

**Comment by Amazinite** [comment]
Well the attributes used are all working as intended, so really it's a question of whether this is something that @beccabunny wants to change given that they're his aliens.

**Comment by Amazinite** [comment]
A ship that is in the scenario of having no energy but functional engines and shields isn't able to do anything else, as weapons still have an energy requirement. Given that, I don't really have an issue with the fact that these outfits are able to function without energy, since it's not as though they make a ship overpowered.

I've changed the descriptions of some of the Ka'het engines to highlight this unique behavior. https://github.com/endless-sky/endless-sky/commit/045897af6a3c64afb76acdd925300768c8be48d0
