### ISSUE TITLE
Amending Early Access To Jump Drives via Border Syndicate Space

### ISSUE THREAD

**Issue by Vedvod** [endless-sky/endless-sky#5672]
**Is your feature request related to a problem? Please describe.**
It is very easy to obtain a Jump Drive shortly after starting the game by jumping to one of the border Syndicate worlds and waiting for a Korath Raider to jump in and be disabled, so that you can board it and loot the jump drive. This severely breaks the story progression, as it allows you to complete the wanderer quests before even initiating the Free Worlds story.

**Related Issue Links**
Unsure, could not find anything.

**Describe the solution you'd like**
I think it would resolve this to add a requirement for jump drives where you have to have a component installed in your ship (not physically, only lore-wise) (which would be installed in any ships you own in the future as well) when you receive the jump drive in the story, which would prevent players using the jump drive to access other races before completing the human storyline. There's probably better solutions than that :<)

**Describe alternatives you've considered**
Allowing the player to skip story progression completely

**Additional context**
I do not have any.

**Comment by MCOfficer** [comment]
I think we can agree that it's highly unlikely that a new player will come across this and obtain a JD accidentally.

BTW, there is a soft requirement on the wanderer story: you can play the intro at any time, but everything after require you to have completed the FW story.

**Comment by Zitchas** [comment]
Is this particularly a problem? As MCOfficer mentioned, the actual Wanderer story (beyond the intro) is locked to the completion of the FW story, so there's no possibility of messing up the story. Likewise, this is what I'd call an "advanced technique" since most players won't know to do this.

All this change would really do is restrict the player's freedom of movement and compartmentalize the galaxy into "before pug section of the story" and "post pug section." 

This would probably also make veteran players feel more "channelled" into a confined path through the game.

Given that a fair number of people enjoy the more sandboxy feel of just exploring the galaxy and finding new stuff without bothering to do the main story, I feel that this change would be a detriment to the game.

Also worth noting that the Remnant campaign does not require completion of the FW campaign for the core storyline; and it definitely provides access to JD. Likewise, I suspect that the Coalition campaign has no reason to be tied to the core human stories either, but it would be impossible to access them without getting a JD somehow.

**Comment by Amazinite** [comment]
This is largely an exploration and sandbox game, so I see no reason why we would gate simply exploring the galaxy behind story. And if anything, I feel like in any way restricting your access to jump drives without the story actually runs counter to the story we’re told. If the Syndicate can steal a few jump drives and start exploring the galaxy with them, which we don’t find out until the end of FW Reconciliation, why couldn’t the player?

If the story is somehow broken anywhere as a result of the player owning a jump drive prior to completing the main story, we should account for that in the story instead of preventing the player from getting the jump drive in the first place. See #989 for one such situation.
