### ISSUE TITLE
Testing source code

### ISSUE THREAD

**Issue by ph2000bis** [endless-sky/endless-sky#571]
Is there a way to test modifications to the source code ? I have (finally) found the file I was looking for and I need to know how to test the modifications.

**Comment by thenerdfreak** [comment]
You have to compile it (don't as me how, I can't even figure it out and I've been trying for weeks)

**Comment by bobafetthotmail** [comment]
You must compile it. C++ must be compiled before you can run it.
Will be useful to read the "building instructions" page of Endless Sky's wiki. https://github.com/endless-sky/endless-sky/wiki/BuildInstructions

**Comment by ph2000bis** [comment]
Thanks

**Comment by ph2000bis** [comment]
when it says "pthread", does it mean "posix thread" instead?

**Comment by bobafetthotmail** [comment]
yes, "pthread" is short form of "posix thread", I THINK that the one linked in the wiki is already the right one, as it comes with c++ compiler (called g++ because it's GNU c compiler) at a later version than 4.8 (it is version 4.8.5)
But I'm on linux (Debian) so I can't confirm.

From Codeblocks it either detects it on its own and opens a popup to ask you if you want to use it, or you need to click on "Settings", then on "Compiler", in the "selected compiler" field select the "GNU GCC compiler".

Then click on "toolchain executables" tab to make sure that Codeblocks knows where the compiler is, Autodetect should work, otherwise browse and select the mingw64 folder and other stuff like shown in the screenshot in the wiki.

Then if you want to start compiling you click on the yellow gear icon ("build"), the binary is generated in a new folder inside the source folder, "bin" or somesuch

To the right of it there is a green arrow which is "execute what was compiled already" and an icon with both gear and arrow to compile and execute it when ready.

Build times depend from how decent is your CPU but should be fast.
