### ISSUE TITLE
Add non-directional weapon hazard/projectile "impact effect".

### ISSUE THREAD

**Issue by petervdmeer** [endless-sky/endless-sky#5751]
**Is your feature request related to a problem? Please describe.**
The `"hit effect"` for projectile based weapons creates visual effects at the position where a projectile hits/touches a ship.
The `"hit effect"` for hazard based weapons creates visual effects (CreateSparks) all over a ship when hitting/touching.

**Related Issue Links**
I was looking at #3878 when I noticed this difference.
PR #4931 introduced Hazards, so it also seems related.

**Describe the solution you'd like**
This request is to change the hazard type `"hit effect"` to `"impact effect"` to allow both projectile weapons and hazards to specify both effects.
This could for example be used by towing weapons to create some sort of grid over the ship that is being towed.

**Describe alternatives you've considered**
I'm not sure about the name `"impact effect"`, but couldn't come up with a better name (maybe `"effect on impacted target"`, but that is a bit long).

**Additional context**
Ship::TakeDamage() is used both for projectile weapons as for impact from ship explosions. If we remove some more differences between hazards and projectiles, then we might be able to also use Ship::TakeDamage() for hazards (and no longer need Ship::TakeHazardDamage()).

**Comment by Amazinite** [comment]
`"spark effect"`?

**Comment by petervdmeer** [comment]
`"spark effect"` sounds okay. `"spark hit effect"` might then even be better if we also want to add `"spark live effect"` and `"spark fire effect"`  someday.

**Comment by tehhowch** [comment]
I think "target effect" is easier to reason about than "spark effect".

Possibly "affected target effect," or similar.

I believe there will be some visual discontinuities without extended code support, since there is currently no coupling of the visuals generated by effects to whatever caused the effect to be triggered. That is, if getting hit with a weapon with this new effect type creates a multi-frame visual, only the first frame is guaranteed to be drawn correctly. On all subsequent frames, the visual and the "source" of the visual, the ship or asteroid, can move with differing velocities.

I've noted (offline) that we can refactor the current hardcoded effect generation (disruption, slowing, etc) into generalized "effect emitters" that store particular effects to spawn and also the rate with which to spawn their respective visuals. A weapon would then be able to transfer an effect source to targets when they are hit, allowing e.g. the slowing caused by a system hazard to be differentiated from the slowing caused by a Detainer, or the aforementioned "towing grid" to always draw over the ship it affects.

**Comment by petervdmeer** [comment]
I expect that eventually we might even want to have both:
- Effects that stay with the ship / animate on top of the ship (like the towing grid).
- Effects that immediately detach (like the nano-sparks, they seem to work better that way and the bay launch clouds (those clouds disperse where they appear, they don't travel with the ship).

**Comment by petervdmeer** [comment]
Closing this ticket; PRs #5753 and #6098 seem to implement the requested feature completely. The "effect emitters" as discussed here also seem valuable, but I feel they are better served by their own ticket.
