### ISSUE TITLE
(Major Feature Request) Ingame Shipbuilding

### ISSUE THREAD

**Issue by Plip-Plop** [endless-sky/endless-sky#5767]
# Premise:
There are many ships that appear to be modular, but can only be bought as pre-built ships like any other ship. I want to make it possible for players to build their own ships with modular ship parts (Hauler, Star Barge, some Arach ships, etc) *without* learning how to make plugins and ruining the balance of their game in the process. This post will explore as many of the things that must be implemented to allow modular ship building that I can think of. 

# Items To Complete:
- [ ] **Tabs in the Shipyard and Outfitter (unless I am wildly mistaken, the Map tabs would not work for this purpose)**[Figure 1]
- [ ] **Construct Tab**[Figure 3]
- [ ] **Section Sprites**[Figure 2]
- [ ] **Permanently Docked 'Drones'**
Add the ability to have drones that cannot be deployed. This could allow the player to switch between the Arach Hulk and the Arach Spindle like Arach merchant captains do all the time.

Please tell me if I missed anything, as I most definitively have!
# Mockups
### Figure 1:
![Shipyard with Tabs](https://user-images.githubusercontent.com/69060286/109743957-c411b780-7b8e-11eb-9d4e-7d42592bd618.png)
--
### Figure 2:
![Cut Hauler](https://user-images.githubusercontent.com/69060286/109750229-4901ce80-7b99-11eb-9d2e-d1dcfc43fd39.png)
--
### Figure 3:
![Construct Tab](https://user-images.githubusercontent.com/69060286/109815213-9e1b0000-7bec-11eb-8e20-3e98eb734d56.png)

**Comment by tehhowch** [comment]
Not gonna happen, sorry. This requires a completely different data model and also requires we create a 3D rendering engine (thumbnails) _and_ then also requires all content authors to include conformant 3D assets to support thumbnail rendering of said modular chassis components. All of said assets then need to ship with the game and associated plugins.

Ignoring the shipyard thumbnail rabbit hole, this functionality doesn't align with the game in general. This is a text-based story engine that happens to be strapped onto a space shooter. 

(As far as "not ruining the balance of their game" goes, I believe "let the player create their own designs" is rather susceptible, too.)

**Comment by Zitchas** [comment]
While definitely a very cool idea, I think the closest we are likely to get is more along the lines of being able to buy an almost completely empty hull that just has "expansion slots" that we then fill with appropriate modules that give cargo, outfit space, fuel, etc. So the outer limits of the hull (and the entirety of its appearance, as well as all the hardpoints) will remain fixed - but everything on the inside could then be modified.

**Comment by Plip-Plop** [comment]
I understand why this would not work using image modification like I first thought, but could fighters that cannot be deployed work?

**Comment by Zavindur** [comment]
If the the ship models were pre-created; you could have missions that let the player pick how to improve a ship- and it would actually just update the shipyard with that variant instead- like the kestrel mission.

A mod I tweak from time to time kinda allow this, not the appearance, but it lets you purchase more outfit space which can be used for engine/weapon; but you have to purchase more stuff to handle the increased mass and such; ends up sinking alot of credits into it but pretty fun idea to spend more credits on upgrade ship instead of getting different model.

**Comment by movingpictures** [comment]
I'm a thinking there's some pretty liberal ways of equipping ships already. In my quest to break the game - all in the name of contributing to the effort - I've flown Mereti vessels with Hai reactors, Korath fuel systems, Ka'Het turrets and Remnant crystals. I think that's enough flexibility. 
(Heck, just for grins and giggles, I tried to turn a Korath fighter into a starship. Didn't work.)

**Comment by arkhne** [comment]
Since this is an Issue, and not a PR, I'd like to propose an alternative, one that actually requires very minimal work on the core engine (and what work it *does* need is work that is wanted in other areas, anyway).

If we had the ability to remove ships, we could create missions requiring the player's flagship to be one of the modular style ships (IE: Hauler series), that had the destination as some shipyard where the ship (and credits) was removed, and the other model of it added. It would be fairly trivial at that point to buy a Hauler, do some space truckin' and then upgrade your rig with an extra cargo pod. Or even decide that the extra cargo pods slow you down too much and attract too much pirate attention, so you downscale to better combat piracy.

Things this needs:
Giving ships to the player (already a thing, I believe).
Removing ships from the player (not a thing, but wanted, I believe).

Optional things:
'Outfit' configuration saving, letting you keep your outfits when switching ships, although this runs into the issue of either being too specific a case (only for these missions), or too broard in scope and impacting too many things. Thankfully, this (like the elsewhere discussed Penguin evolution) can be avoided by having the mission text tell you to not have anything special on the ship, and just swap to a basic loadout of the 'new' ship.
Tracking whether or no the player owns any spare 'pods'. When buying a pod, and uninstalling it (or buying a bigger ship and uninstalling a pod), it would be nice if this could be stored like outfits on a planet and used to configure future versions of the mission, although this also runs into the problem of probably being too specific a case.


I most definitely do not propose a generalized configurable ship system, nor am I even convinced that we need it for these ships, this is just what I see as the best way to make this a reality, with the least amount of non-content work, should it be decided to be feasible (as it is often requested).

**Comment by starmlerp** [comment]
a similar feature I would be thrilled to see added in game, kind of stemming from similar tech shooter games, like War Thunder, is a "tech tree": ships in the game could each have a "parent"(ship they are preceded technologically by), and "children/siblings"(ships that stem from it). players could them "upgrade" their current ship (replace it by one of the children ships), with smaller upfront cost, but greater overall cost (aka. since used ships and modules are valued less, upgrading my ship to hauler II from hauler I is cheaper for me now than buy-in a new hauler II, but I would've spent less money overall had I bought hauler II to begin with).

here is an example of how hauler tech tree might look like (and, arguably, the most complex tech tree should this feature be implemented): 
![hauler-tech-tree](https://user-images.githubusercontent.com/45012410/111351712-c04c5d80-8683-11eb-9284-eb0a9a639779.jpg)
