### ISSUE TITLE
More specific issue tags

### ISSUE THREAD

**Issue by bobafetthotmail** [endless-sky/endless-sky#578]
Because for example "enhancement" is a bit generic and if we keep the current pace of issue generation, within a few months it's not going to be much better than "no tag".

I think that adding to the main tag (like "enhancement") other tags like "ships" or "weapons" or "aliens" or "missions" or whatever would help greatly anyone that will look through the issues looking for ideas or searching for something.

**Comment by cool833** [comment]
i agree

**Comment by endless-sky** [comment]
The main point of the tags is to prioritize issues, with bugs being the highest priority, support requests being the lowest (because they belong in the forum, not here), and feature requests being the next lowest priority.

Also, it would be difficult to come up with a small set of categories that would cover all the issues currently in the "enhancement" category.

**Comment by bobafetthotmail** [comment]
thanks for the honest answer, closing then.
