### ISSUE TITLE
Mission to ??? on Meblumem can't be finished?

### ISSUE THREAD

**Issue by pepoluan** [endless-sky/endless-sky#5788]
**Describe the bug**
I got a mission in Coalition space, delivering Longcow Antibiotics to "???" on Meblumem.

I can't land on "???". Is this by design?

**To Reproduce**
1. Go to 'Coalistion Space'
2. Randomly visit Spaceports until one gets the mission
3. Pick up antibiotics
4. Try to deliver to Meblumem system, "???" planet

**System (please complete the following information):**
 - OS: Windows 10 Pro
 - Game Source: Nightly
 - Version: "commit hash f91398a"

**Link to save file**
[Pepo Langit~3019-09-25.txt](https://github.com/endless-sky/endless-sky/files/6134882/Pepo.Langit.3019-09-25.txt)

**Additional context**

**Comment by Terin** [comment]
The mission is supposed to go to the Corral of Meblumem in that system. As always, do you have any plugins that would interfere with it?

**Comment by pepoluan** [comment]
> 
> 
> The mission is supposed to go to the Corral of Meblumem in that system. As always, do you have any plugins that would interfere with it?

Maybe? I'll try disabling some plugins I already have.

That said, since posting, everytime I reloaded the game after quitting, it will warn of "Longcow Antibiotics rely on plugins that are missing" or something to that effect, so yeah probably a plugin conflict of sorts.

**Comment by arkhne** [comment]
Since the mission has already been accepted and shows ??? as a destination, it's likely unfixable. Your best bet is to remove it from your save file and try taking it again.

It *could* be an artefact of #5328 , but I doubt it. This would require the mission having been accepted prior to that merge, and 'completed' afterwards, and even then, it should've been fine because the 'destination' didn't change (neither in the mission, nor did the planet change).

**Comment by pepoluan** [comment]
> Since the mission has already been accepted and shows ??? as a destination, it's likely unfixable. Your best bet is to remove it from your save file and try taking it again.

Ah okay. Thanks for the tips!
