### ISSUE TITLE
"gun port"'s should have small frontal arc

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#579]
Currently, "front facing guns" fire directly ahead regardless of targeting, but what if they had a small arc that they could turn in? Maybe something like a 45 degree angle of arc.
Of course, the "auto target" feature would still try to directly align with the target regardless of arc, but it would be nice to have a small area of hittage (lol) Currently guns slightly turn towars the center of the ship, kinda how the small angle offset on Fighter Jets cause the bullets to converge and increase accuracy, but that isn't really what I'm meaning

Current:  
![capture](https://cloud.githubusercontent.com/assets/15973422/12075668/6abc7a38-b14c-11e5-9b97-e95d134c1361.PNG)
Proposed: 
![capture2](https://cloud.githubusercontent.com/assets/15973422/12075669/6abee2dc-b14c-11e5-9782-ef72ced31537.png)

**Comment by endless-sky** [comment]
This doesn't make sense to me. If the arc is as small as in your drawing, your ship can just correct by steering slightly. If it's as big as 45 degrees, that would totally change the balance between guns and turrets. Either way, I'm not sure what it would add to the game, especially since the tradeoff between powerful forward-facing guns and versatile turrets is a big strategy element.

**Comment by thenerdfreak** [comment]
The drawing was just an illustration of the idea, i didn't measure the arc. But in ships where turning is ridiculous, a little lee-way with front facing guns couldn't do much harm. and the most powerful weapons in the game are turrets in general, they have the power and versatility (Electron turret, Plasma turret, etc.) The only two decent guns in human space I see that don't have turrets are the Proton and Particle cannons, I don't really thing either of those are very favorable over turrets

**Comment by Pointedstick** [comment]
This change would have the effect of slightly improving the performance of fixed guns mounted on slow-turning ships. I'm not sure that's a use case that's underpowered. If anything it's small fighter-type ships that are need of improvement, as they generally get evaporated by large ships unless they're present in huge swarms.

**Comment by cool833** [comment]
yes sparrows get immediately blown to smithereens by anything bigger than a mule.
unsure about how this would be fixed though.

**Comment by bobafetthotmail** [comment]
bah, it makes more sense to have gun ports facing right or left of the ship (to shoot broadside barrages) than giving a fire arc to the frontal guns.

**Comment by frameworld** [comment]
It makes sense from a technical standpoint (why try to align 1000 tons of ship when you could just align a 5 ton weapon with small servos).

It also allows more seem-less target switching.

Sometimes it could be useful to have half-turrets, covering a half of a sphere around your ship.
 * Example : anti missiles at the rear only guarding your retreat.
 * Vector thrusters
 * …

**Comment by omagasohe** [comment]
I can see the use for a fire control capable forward gun, Most current Naval ships guns has something similar where they self stabilize for accuracy, since even calm waters move the ship around a bit. most naval guns are synced up with gyros to compensate for movement and rotation on 3 axis. They even compensate for the rotation of the earth =P

**Comment by luiges90** [comment]
Talking about "half-turrets", we should actually consider giving weapons a "firing arc" attribute which replaces all the Gun/Turret distinction. But that isn't anything happening in short term I guess
