### ISSUE TITLE
Caelian Planet Description States Remnant Knows Alpha Wars Ended

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5825]
**Is your feature request related to a problem? Please describe.**
The description of the remnant planet Caelian in the Cinxia system states that the remnant know the alpha wars are over, despite them acting like they have no clue the alpha wars ended centuries ago, especially during the tech retrieval mission.

**Related Issue Links**
None. I cannot believe nobody else noticed this.

**Describe the solution you'd like**
Change the description of the planet, removing the part which states they know the alpha wars are over.

**Describe alternatives you've considered**
You could change the missions so that they say that the remnant know the alpha wars are over, but that would be hard.

**Additional context**
If anybody wants me to, I can modify the text file containing the description to remove the part which states they know that the alpha wars are over.

**Comment by Zitchas** [comment]
Believe me, the Remnant know the Alpha Wars are over. 

Either we change the mission, or the we assume that the Remnant are "playing dumb" because they don't want to reveal how aware they are of the outer universe. I lean towards the latter.

**Comment by McloughlinGuy** [comment]
Why wouldn't they want to reveal how aware they are?

**Comment by Zitchas** [comment]
Knowledge is power. If your potential enemies think you are so out of touch that you aren't aware of a war ending centuries ago, then they probably won't invest much effort in  hiding stuff out there, right? No need to hide from someone if the people you are hiding from haven't been outside the Ember Waste since the time they entered it.

**Comment by McloughlinGuy** [comment]
Yes, but that may could lead their enemies to believe they are an easy target.

**Comment by Zitchas** [comment]
That is why the Remnant's first and foremost line of defense is to be not known at all. They never leave the Ember Waste except in cloaked ships. And even in the extremes of the Ember Waste they prefer cloaked ships.

So ideally, enemies never know they are there. But if they *are* going to have enemy's show up, better to have them show up expecting a weak target than prepped for a tough fight.

**Comment by McloughlinGuy** [comment]
This might still be confusing to players, we should maybe brainstorm a way to make the player understand this better.

**Comment by jerith** [comment]
There's a big difference between "the Alpha Wars are over" and "the Alphas are no longer a threat". The Remnant know there hasn't been active warfare for a while, but they also believe (correctly, as it turns out) that the Alphas are still out there and are still extremely dangerous. All my interactions with the Remnant are pretty consistent about this, but I haven't read through the data files thoroughly to check. Can you perhaps point out some specific instances of the Remnant thinking the war is still ongoing?

**Comment by McloughlinGuy** [comment]
In the remnant Quarg missions it states something about you not knowing if the remnant have been holding back from you. Therefore, this is no longer a valid issue.
