### ISSUE TITLE
Quarg Wardragon Classification Issue

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#5830]
**Is your feature request related to a problem? Please describe.**
The Quarg Wardragon is classified as a heavy warship, despite it's description saying otherwise.

**Related Issue Links**
 #756 is similar, surprising they didn't notice this while correcting the previous error.

**Describe the solution you'd like**
Change it's classification to light warship.

**Describe alternatives you've considered**
Or you could change the description to say heavy warship.

**Additional context**
I had a text file which remedied the issue, but it wouldn't load.

**Comment by McloughlinGuy** [comment]
I am addressing this in a pull request (I don’t know how to link them) so I am closing it.

**Comment by MCOfficer** [comment]
You already have

![image](https://user-images.githubusercontent.com/22377202/115955358-41560a80-a4f6-11eb-9fde-413cf633875f.png)


![image](https://user-images.githubusercontent.com/22377202/115955356-3d29ed00-a4f6-11eb-9bc2-232ad99c4ed6.png)

Ideally you'd want to keep the issue open until the fix is merged, because in theory your fix could be rejected and the issue could go back to being on hold.

**Comment by McloughlinGuy** [comment]
Ok.
