### ISSUE TITLE
Endless Sky Beta Modding

### ISSUE THREAD

**Issue by admiralTANK** [endless-sky/endless-sky#5867]
IMPORTANT UPDATE: While I am still experiencing the issues mentioned below, there has been a development. I will place it at the bottom for chronological convenience.

I do not understand why my modded outfits and ships will not show up in the Beta.

I copy and pasted the sections I modified into the new files. I double-checked that there's no new code format. Perhaps I missed something.

Left is the Steam set of files, in the box on the right is the Win64 Beta.
![image](https://user-images.githubusercontent.com/82894877/115466711-71539400-a1fe-11eb-8e8e-7e0f434ca051.png)

This is the beginning of my mods. I consolidated all of my outfit modifications (power, engine, weapon, alien) into the human "outfits" file. This is the screenshot of the first outfit. They are all together at the top of folders for ease of access and quick identification. The Steam files still work as they're supposed to.
![image](https://user-images.githubusercontent.com/82894877/115468420-11122180-a201-11eb-99dd-79152ce30510.png)

This is the new outfits file. My old saves on Steam have the new images, but old formatting (no sidebar for descriptions and no timer). The new files don't seem to have a user folder. They take the data from the Steam folders.
![image](https://user-images.githubusercontent.com/82894877/115468504-2d15c300-a201-11eb-9172-f7d65886baa3.png)

 - OS: Windows 10
 - Game Source: Github stable release.
 - Version: win64-0.9.13

IMPORTANT UPDATE (cont.): I tried double-checking the file location. I re-opened the files to see they were modded by me. Then I went back and opened the game straight from the file explorer instead of a pinned desktop shortcut. This opened the game with everything in-tact except for the images. Some of the mods which used a new image were not carried over. While explained above all images were present, but replaced by new images as applicable. The file explorer version opened with only 2 images I carried over. The icon is also a top-down Berserker instead of the flyby Berserker that I'm used to. When pinned it transforms into the flyby version. A number of times opened also appears when I right-click the pinned icon. I am still curious as to what could cause these inconveniences, even though it is pleasantly functioning now.

**Comment by Zitchas** [comment]
OK, several things here.
1) does the errors.txt file give you any errors? (it should be located in the same folder that houses your saves and plug-ins folder)
2) Did you add your outfit to an outfitter? (Since you are editing the regular data files, that would be the sales.txt file. Outfits don't show up for sale if they aren't listed in an outfitter. )
3) You have a `"heat dissipation" 1.5` listed as part of the outfit. That may cause problems, as the game really isn't designed to have that value outside the 0.1-1.0 range. It's basically representing a percentage 0.01 = 1% and 1.0 = 100%, aka, how efficient is the ship at dissipating heat naturally. I don't know the code, but having a ship boosted up to somewhere over 150% efficient may cause problems.

**Comment by tehhowch** [comment]
This discussion belongs in a different forum, such as Steam, Google Groups, or Discord.
