### ISSUE TITLE
Strider 1 quest requires you to depart then enter the planet again.

### ISSUE THREAD

**Issue by binaryspica** [endless-sky/endless-sky#5895]
**Describe the bug**
Strider 1 mission on the Hai-home requires you to depart the planet then enter Hai-home again, instead of go for spaceport.

**To Reproduce**
1. Enter Hai-home with the trigger to activate 'solifuge conversation'
2. End it and get Strider 1 mission.

**Expected behavior**
Strider 1 should be continue with tap the spaceport like as many other missions that talks with the person on landing then call the captain to the spaceport.

**Comment by Amazinite** [comment]
Weird. I'm pretty certain I had this working before, but I may have broken it when I rearranged the missions one last time. Not entirely sure why this doesn't work, though.

Strider 1 sets a condition during its conversation, which occurs on landing, in order to determine which mission should offer next in the spaceport. On landing missions should be able to affect which mission offers when you visit the spaceport. 

So it looks like the culprit though is that when you land, Strider 1 is added to the available missions list, while Strider Coalition and Remnant aren't. Then when you finish the Strider 1 conversation, while you now meet the to offer conditions of Strider Coalition and Remnant, the available missions list hasn't been updated to actually make them offer, hence the need to reland to cause the available missions list to update and make the next mission available.

Seems like a similar predicament to #1938. In that case mission failure isn't updated immediately, in this case mission offering/availability isn't updated immediately. Sounds like an issue to fix, I'm not entirely sure at the moment how I could rearrange these missions to get around this for the time being. We'll probably need an intermediate mission of some sort between the two. Perhaps you pick up the delegation on Allhome instead of the Hai-home spaceport.

As far as fixing the underlying issue goes, I know @tehhowch has expressed interest in refactoring the landing sequence to be able to fix #1938 (and perhaps also #3746 at the same time), and such a refactoring should also be capable of fixing this. When that refactoring will be done is a question for him, though.

**Comment by Amazinite** [comment]
Opened an issue so that we can track making this line of missions work and allowing landing missions to cause spaceport missions to offer separately.

**Comment by Amazinite** [comment]
Changed it so that Strider 1 now accepts and tells you to meet the delegation on Allhome instead of declining and telling you to head to the spaceport.
