### ISSUE TITLE
ShipInfoDisplay: slow reload and burst reload

### ISSUE THREAD

**Issue by jostephd** [endless-sky/endless-sky#5923]
**Describe the bug**
The ShipInfoDisplay `firing:` line doesn't account for burst reload.

**To Reproduce**
Read the source: https://github.com/endless-sky/endless-sky/blob/142fa61b72f7d543431ca0cf8de3bf29c347deb8/source/ShipInfoDisplay.cpp#L297-L307

**Expected behavior**
https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits says

> The fraction of time that a burst weapon spends firing is `"burst reload" / reload`

so I expect burst weapons to use `BurstReload() / Reload()` where non-burst weapons use `1. / Reload()`. This way, the computed values would be the average heat/energy per second while firing for both burst and non-burst weapons (they're already so for the latter).

So, should `FiringEnergy() / Reload()` be changed to `FiringEnergy() * (BurstReload() ? BurstReload() : 1.) / Reload()`?

**System (please complete the following information):**
 - Version: current master (142fa61b72f7d543431ca0cf8de3bf29c347deb8)

**Additional context**
Related issues listed in #4215.

While we're looking at that loop anyway, I remember there was an issue involving projectile weapons: the table shows the average per-second energy draw, but projectile weapons require all energy to be available in a single frame, so a weapon that has a reload time of more than a second could end up unable to fire, despite the table showing otherwise. If that's still an issue, perhaps the loop should show the heat/energy consumption at the time of actual firing, rather than amortized values? I think that would be `FiringEnergy() / min(Reload(), 60.)`. This would need to be combined with the BurstReload() use, so I suppose the end result would be something like `FiringEnergy() * max((BurstReload() ? BurstReload() : 1.) / Reload(), 1./60.)`? I'm sure I overlooked something (and even if not, it would be nice to avoid dividing by `60.` and multiplying it back).

**Comment by Amazinite** [comment]
Say you have two weapons. Both have a reload of 10 frames, but one has a burst reload of 3 frames and a burst count of 2.
A normal weapons fires when its reload is 0.
A burst weapon fires when its burst reload is 0 and burst count is >0, and the burst count is refreshed when reload = 0.
Every frame, reload and burst reload are decremented. Burst reload is decremented immediately after firing. Burst count is decremented after firing.

The following table shows one second of firing from both weapons as described above, showing the values of the relevant variables for the Hardpoint as well as whether the weapon fires or reloads on that frame, and if it fires it includes a cumulative count for how many times it fired.

<details><summary>61 row table.</summary>

Frame | Normal Weapon | Reload |  | Burst Weapon | Reload | Burst Reload | Burst Count
-|-|-|-|-|-|-|-
1 | Fire (1) | 0 |  | Fire (1) | 0 | 0 | 2
2 | Reloading | 9 |  | Reloading | 9 | 2 | 1
3 | Reloading | 8 |  | Reloading | 8 | 1 | 1
4 | Reloading | 7 |  | Fire (2) | 7 | 0 | 1
5 | Reloading | 6 |  | Reloading | 16 | 2 | 0
6 | Reloading | 5 |  | Reloading | 15 | 1 | 0
7 | Reloading | 4 |  | Reloading | 14 | 0 | 0
8 | Reloading | 3 |  | Reloading | 13 | 0 | 0
9 | Reloading | 2 |  | Reloading | 12 | 0 | 0
10 | Reloading | 1 |  | Reloading | 11 | 0 | 0
11 | Fire (2) | 0 |  | Reloading | 10 | 0 | 0
12 | Reloading | 9 |  | Reloading | 9 | 0 | 0
13 | Reloading | 8 |  | Reloading | 8 | 0 | 0
14 | Reloading | 7 |  | Reloading | 7 | 0 | 0
15 | Reloading | 6 |  | Reloading | 6 | 0 | 0
16 | Reloading | 5 |  | Reloading | 5 | 0 | 0
17 | Reloading | 4 |  | Reloading | 4 | 0 | 0
18 | Reloading | 3 |  | Reloading | 3 | 0 | 0
19 | Reloading | 2 |  | Reloading | 2 | 0 | 0
20 | Reloading | 1 |  | Reloading | 1 | 0 | 0
21 | Fire (3) | 0 |  | Fire (3) | 0 | 0 | 2
22 | Reloading | 9 |  | Reloading | 9 | 2 | 1
23 | Reloading | 8 |  | Reloading | 8 | 1 | 1
24 | Reloading | 7 |  | Fire (4) | 7 | 0 | 1
25 | Reloading | 6 |  | Reloading | 16 | 2 | 0
26 | Reloading | 5 |  | Reloading | 15 | 1 | 0
27 | Reloading | 4 |  | Reloading | 14 | 0 | 0
28 | Reloading | 3 |  | Reloading | 13 | 0 | 0
29 | Reloading | 2 |  | Reloading | 12 | 0 | 0
30 | Reloading | 1 |  | Reloading | 11 | 0 | 0
31 | Fire (4) | 0 |  | Reloading | 10 | 0 | 0
32 | Reloading | 9 |  | Reloading | 9 | 0 | 0
33 | Reloading | 8 |  | Reloading | 8 | 0 | 0
34 | Reloading | 7 |  | Reloading | 7 | 0 | 0
35 | Reloading | 6 |  | Reloading | 6 | 0 | 0
36 | Reloading | 5 |  | Reloading | 5 | 0 | 0
37 | Reloading | 4 |  | Reloading | 4 | 0 | 0
38 | Reloading | 3 |  | Reloading | 3 | 0 | 0
39 | Reloading | 2 |  | Reloading | 2 | 0 | 0
40 | Reloading | 1 |  | Reloading | 1 | 0 | 0
41 | Fire (5) | 0 |  | Fire (5) | 0 | 0 | 2
42 | Reloading | 9 |  | Reloading | 9 | 2 | 1
43 | Reloading | 8 |  | Reloading | 8 | 1 | 1
44 | Reloading | 7 |  | Fire (6) | 7 | 0 | 1
45 | Reloading | 6 |  | Reloading | 16 | 2 | 0
46 | Reloading | 5 |  | Reloading | 15 | 1 | 0
47 | Reloading | 4 |  | Reloading | 14 | 0 | 0
48 | Reloading | 3 |  | Reloading | 13 | 0 | 0
49 | Reloading | 2 |  | Reloading | 12 | 0 | 0
50 | Reloading | 1 |  | Reloading | 11 | 0 | 0
51 | Fire (5) | 0 |  | Reloading | 10 | 0 | 0
52 | Reloading | 9 |  | Reloading | 9 | 0 | 0
53 | Reloading | 8 |  | Reloading | 8 | 0 | 0
54 | Reloading | 7 |  | Reloading | 7 | 0 | 0
55 | Reloading | 6 |  | Reloading | 6 | 0 | 0
56 | Reloading | 5 |  | Reloading | 5 | 0 | 0
57 | Reloading | 4 |  | Reloading | 4 | 0 | 0
58 | Reloading | 3 |  | Reloading | 3 | 0 | 0
59 | Reloading | 2 |  | Reloading | 2 | 0 | 0
60 | Reloading | 1 |  | Reloading | 1 | 0 | 0

Then on the very next frame both weapons would fire and you're just wrapping back up to frame 1 in this row.

</details>

As you can see, within a second, both weapons fire 6 times regardless of the burst count or reload. This is because ultimately it is the weapon's reload value that determines the RPM over time. The burst mechanic does not increase or decrease the overall RPS of a weapon, only altering how it fires to have periods of rapid firing followed by longer periods of reloading, but ultimately the RPS, and therefore the firing energy or hull damage or any other value per second, is the same.

**Comment by jostephd** [comment]
> So as demonstrated, the info display doesn't account for burst reload mechanics because it doesn't need to. The per second values are the same for two weapons where the only difference is one having the burst mechanic while the other does not.

Understood, and thanks a lot for the extraordinarily detailed answer!

> A burst weapon is considered to be firing if burst reload is non-zero or the weapon fired that frame.

Ah! I thought "the fraction of time that a burst weapon spends firing" only counted frames in which the weapon fired.

Here is a shot at a wiki diff to clarify these points:

<details>

<summary>
patch for CreatingOutfits on the wiki
</summary>

```diff
diff --git a/CreatingOutfits.md b/CreatingOutfits.md
index bd73775..1e79d3a 100644
--- a/CreatingOutfits.md
+++ b/CreatingOutfits.md
@@ -474,9 +474,9 @@ Ordinary weapon attributes (those that take a number as an argument) include:
 
 * `reload`: how many frames this weapon takes to reload: 1 means it fires every turn (e.g. most beam weapons), and 60 means it fires once per second.
 
-* `"burst count"`: how many projectiles this weapon can fire in a row at a higher reload rate (`"burst reload"`). The burst will reload fully after `reload * # of shots fired`, making the reload time for a full burst `reload * "burst count"`. Reloading for a burst weapon starts immediately after the burst has started, so the number of frames between full bursts is `"burst count" * (reload - "burst reload")`. **(v. 0.9.0)**
+* `"burst count"`: how many projectiles this weapon can fire in a row at a higher reload rate (`"burst reload"`). The burst will reload fully after `reload * # of shots fired` frames from the first shot of the burst, making the reload time for a full burst `reload * "burst count"` frames, same as for a non-burst weapon. The number of frames between the end of a full burst and the start of the next burst is `"burst count" * (reload - "burst reload")`. **(v. 0.9.0)**
 
-* `"burst reload"`: how fast the weapon reloads when firing projectiles in a burst. This value must be less than the full `reload` value. The fraction of time that a burst weapon spends firing is `"burst reload" / reload`. **(v. 0.9.0)**
+* `"burst reload"`: how many frames this weapon takes to reload between projectiles in a burst. This value must be less than the full `reload` value. For instance, a weapon with a `reload` of `100`, `"burst count"` of `2` and `"burst reload"` of `5` will fire on the 1st and 6th frames, then on the 101st and 106th frames, and so on. **(v. 0.9.0)**
 
 * `homing`: How good this weapon is at seeking its target:
 
```

</details>

> If you have a weapon that doesn't fire because of low energy capacity, you should be looking at the energy capacity section of the table to ensure that it is greater than what any off your weapons use each time they fire, not looking at the firing energy and energy generation sections of the table to see if the firing energy per second is less than the energy generation per second.

Why? Aren't the per-second values the better statistic to look at, if prolonged battles are expected? When possible, I prefer generators to batteries because then I don't have to worry about running out of stored energy in the middle of a battle. (At least in human space. Giant squirrels call for different builds :))

> Perhaps a "energy spent on first frame of firing" type stat would be appropriate for an advanced stats page, though. `Max energy requirement`?

Well, not to bikeshed, but for an advanced stats page we could perhaps get a bit more technical and precise in the terminology? For instance, `Max instantaneous energy requirement`?

**Comment by Amazinite** [comment]
> Why? Aren't the per-second values the better statistic to look at, if prolonged battles are expected?

Well yes, but when we're talking about the amount of energy needed to fire a single weapon once, we're not really talking about prolonged battles. So I suppose that staying within the bounds of the per-second values, a sensible change would be to not include the firing energy/second of weapons which you don't even have the energy capacity for, therefore if you only have one weapon that you can't fire the table will show 0 for firing energy/second.

**Comment by jostephd** [comment]
> Well yes, but when we're talking about the amount of energy needed to fire a single weapon once, we're not really talking about prolonged battles. So I suppose that staying within the bounds of the per-second values, a sensible change would be to not include the firing energy/second of weapons which you don't even have the energy capacity for, therefore if you only have one weapon that you can't fire the table will show 0 for firing energy/second.

If the weapon's energy requirements exceed energy capacity (+ generation, etc), the `This ship has insufficient energy storage to fire an installed weapon` pre-flight check would trigger, so I guess such builds aren't going to be too common. I more often run into the situation where I can fire the weapon while engines are idle, but not while thrusting and steering.

Could a mission increase the energy capacity in-flight? For instance, by instructing the player to hold position and let an NPC board them and install new batteries in their outfit storage? This sort of "reverse plundering" (from the boarder's cargo hold to the boardee's outfit space) seems like it ought to be possible in-world, since plundering batteries is possible, but I don't think it's possible to write such a mission right now. If it were possible, there would be an argument to not exclude weapons from the total just because they can't be fired at take-off.

Have you seen the wiki patch in the spoiler in my previous comment?

**Comment by jostephd** [comment]
> Have you seen the wiki patch in the spoiler in my previous comment?

Bump? See the spoiler in https://github.com/endless-sky/endless-sky/issues/5923#issuecomment-832929689.

**Comment by jostephd** [comment]
@Amazinite Sorry, but bump again? You labeled this "question" but there's an actual documentation patch up there, I think it might be getting lost.

**Comment by Pointedstick** [comment]
LGTM
