### ISSUE TITLE
Atomic and Alien Afterburners?

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#597]
We have a Ionic afterburner, a protonic (the original), so why not have a atomic? Of course, this would be expensive as a Fury interceptor, use a TON of energy; but it would boost ships extremley fast and use almost no fuel and outfit space. Also, it could be possible that the Wanderers and maybe the Quarg and the Korath have some too? (Although the Quarg and the Korath have large ships, so it wouldn't be very pratical) What do you think? Is it possible?

**Comment by frameworld** [comment]
Haven't used ionic yet, but it might be a good idea with the improved ram-scopes.

The normal afterburners however require so much fuel that the only ship that really benefits from it is a scout-shuttle.

Big ships do not benefit from the standard afterburner at all because large atomic thrusters are more efficient per ton.

**Comment by endless-sky** [comment]
Cleaning up the issues list to focus on feature requests that are more likely to get implemented.
