### ISSUE TITLE
I need a ship model!

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#598]
I am working on a new ship for Lionheart, and it will be MASSIVE. However, I am terrible at making ship models, so can a pro make me one? What I do NOT want is a ship scraped together in five minutes from other ship models in photoshop. I would like this ship to be implemented into the main game, so quality matters. Some qualites to note:
Gun ports: 6
Fighter bays: 6
Turret mounts: 12
Very long.
With 1/3 of the length
Has the main tower at the back of the ship
Has a small pair of wings at the front
I hope to see some cool results!

**Comment by bobafetthotmail** [comment]
I think you might get more/better answers if you post in 3D artist forums or somesuch.

**Comment by natangold** [comment]
At a glance, that ship looks like it would easily curb-stomp both the Carrier and the Dreadnought, so please make sure it has some pretty significant [hull, shielding, and/or maneuverability] deficiencies to offset.

**Comment by lor1113** [comment]
This ship looks like a continuation of the 'City Ship' line, and so it makes sense for it to be that huge.
I guess speed and maneuverability should be reduced, but there is no reason not to give the ships high shields and hull when it's huge

**Comment by Pointedstick** [comment]
Not sure such a ship would be accepted into the main game. Seems totally overpowered if it's available for civilian purchase, since it would basically be a better Bactrian--already the no-brainer overpowered choice of power gamers. I'd say work on your 3D skills and implement it as an optional plug-in if you don't choose to re-work it into something that fits better into the game.

**Comment by lor1113** [comment]
It could work if the price was set to something astronomical - could be a solution to the whole 'too mush money' problem

**Comment by Gkramme** [comment]
Yes, the price is around 350 Mil, so only the richest of the rich can buy it. Also, the shield recharge rate is very slow, heat dissipation is bad, and the amount of crew it needs is CRAZY. It's kind of like a Quarg ship. Endgame. I'm actually considering bumping up the price to 500 mil, and only make it possible to buy one. Also, due to it's gigantic size, anti-missiles cover it badly. I may also make it buyable if you have a navy lisence.

**Comment by Pointedstick** [comment]
So who would buy this ship, then? What's the player use case?

**Comment by endless-sky** [comment]
Please use the [forum](https://groups.google.com/forum/#!forum/endless-sky) for seeking collaborators for content creation, rather than the issue tracker. If people keep using the issue tracker as a general discussion forum, it will make it much harder to sort out the things that actually are bug reports or actionable feature requests.

**Comment by Gkramme** [comment]
Ok thanks
