### ISSUE TITLE
Sort out Remnant: Face to Maw ("Talk to Plume about the void sprites")

### ISSUE THREAD

**Issue by 2phunkey4u** [endless-sky/endless-sky#5990]
using 0.9.14 (replaced Steam installation)

Traveling back from Nenia after the first mission that involves an encounter with Korath meddling in this system, the mission
"Talk to Plume about the void sprites" sticks around even after landing on the destination planet and at the same time "Remnant: Cognizance 1" / "Follow-up Observations" starts (which involves talking to Plume)

Apparently, this mission will only complete after the entire Remnant: Cognizance branch? This looks irritating, and seems unnecessary.

**Comment by Zitchas** [comment]
Just to clarify, do you mean that the mission stays in your mission list? That's definitely not intended behavior.

Could you share your pilot file please?

**Comment by 2phunkey4u** [comment]
Yes, that is what I mean. It also stays in the mission list upon completing "Follow-up Observations" for Plume.
There was also no prompt for the mission upon completing the visits to both planets in Nenia, which I would have expected.
[github-5990.txt](https://github.com/endless-sky/endless-sky/files/6526464/github-5990.txt)

For now, is it safe to abort the mission, or would that break the progression of the Remnant arc?

**Comment by Zitchas** [comment]
Aborting that mission would be bad for story progression.

What *should* happen in "Follow-up Observations" is that you visit each of the two planets in Nenia, and after the second one you get a dialog  box that says you got some recordings; after which you can go back to Aventine to talk to Plume again.

**Comment by Zitchas** [comment]
Also, I'm not sure about your game installation - the pilot file lists you as flying a gascraft, but those were renamed to "puffin" quite a while ago... (almost a year ago, in June). So any 0.9.13 or (not yet released 0.9.14) should no longer be called the gascraft, with the exception being if this pilot purchased the gascraft while you were still playing on 0.9.12.

**Comment by 2phunkey4u** [comment]
Hi @Zitchas ,
landing on Aventine completes "Follow-up Observations" and the subsequent visit to the bar offers "Eliminate Korath Ship" (in Nenia, again), but "Talk to Plume about the void sprites" stays in the Missions list, even after completing "Eliminate Korath Ship" and some more subsequent missions. Thus, I'd guess "Talk to Plume about the void sprites" is redundant to "Follow-up Observations".

I hope "Talk to Plume about the void sprites" finally resolves upon getting to and completing "Remnant: Cognizance 1", if I read the Remant missions data file right.

About my installation and the Gascraft: Yes, I installed 0.9.12 via Steam and then overwrote the game files first with 0.9.13 from GitHub (which did not break my game, but just reset my game timer), and then again with yesterday's continuous build because the 0.9.14 revisions looked so juicy. I bought the Gascraft / Puffin while still being on 0.9.12

**Comment by Ornok** [comment]
"Remnant: Face to Maw 1"  has recently been changed so that it can't be offered during the Cognizance missions. But "Remnant: Face to Maw 1B" (what you see as "Talk to Plume about the void sprites" in your game) hasn't been changed and still offers during Cognizance. So the first part of the mission, "Remnant: Face to Maw 1", won't be offered until you complete Cognizance 19. And your current mission won't complete until that first part is done.

"Remnant: Face to Maw 1B" is supposed to have the exact same conditions as "Remnant: Face to Maw 1" so that they're both offered at the same time.

The best way to fix your game would be to remove "Remnant: Face to Maw 1B" from your save file once the mission has been fixed. This way you'll be able to play the mission correctly after completing Cognizance.

If you really want to complete it right now, just add "Remnant: Face to Maw 1: declined" in your save file under `conditions`. You'll then be able to continue the mission normally. However I wouldn't advise it, because you'd be missing the choice that the first part offers.

**Comment by Ornok** [comment]
In the PR mentioned above you'll find a fix for the mission. I also took the liberty of using your save file for testing. I just edited it to remove "Remnant: Face to Maw 1B", so you can use it to pick up where you left off once you update "remnant missions.txt".

**Comment by 2phunkey4u** [comment]
@Ornok 
Thanks a lot! But do I correctly understand that I could alternatively just play all the way through Cognizance and then I would eventually be able to complete Face to Maw without using the fix?

**Comment by Ornok** [comment]
Yes, you can do that. Once you finish Cognizance, return to one of the gas planet in Nenia to get "Remnant: Face to Maw 1". From there the mission should work normally.
