### ISSUE TITLE
HAI RAMSCOOP

### ISSUE THREAD

**Issue by unjown** [endless-sky/endless-sky#6002]
**Describe the solution you'd like**
Hai version of ramscoop... 

**Describe alternatives you've considered**

Coalition ramscoop

**Comment by 1010todd** [comment]
Can you please explain in detail about the reasons (Lore, gameplay, etc.) why we should have a unique ramscoop for the Hai?

**Comment by unjown** [comment]
first, it doesnt have to be "unique" , just an improved version of the human ramscoop.
hai engines are just like an improved atomic, their reactors also, why not ramscoop?

**Comment by Terin** [comment]
Engines are a pretty integral part of space flight. They have their own quirks, like engine flares, energy consumption, heat, and size varieties that can make them more unique. Ramscoops, on the other hand, are much simpler gameplay features. An "improved version of the human ramscoop" is basically the Wanderer ramscoop. On top of that, the Hai are in a dense, well-settled area with only a handful of uninhabited systems. They'd have no need for a ramscoop.

If you're going to post an issue, it should not be 6 words. You need to really consider what you're asking for, why it should added, and what it looks like.

**Comment by Amazinite** [comment]
Probably not happening. 

Ramscoops are indicative of factions that either currently or recently lived in regions of space with few opportunities to refuel. See humanity (their region of the galaxy was only relatively recently entirely inhabited, and there are still long stretches of uninhabited systems like in the north where ramscoops become somewhat necessary) and the Korath (no home planets, nomadic in nature at the moment). Wanderers also have ramscoops out of necessity for when they begin exploring new regions of space to repair with no preexisting refuel capabilities. The Coalition and Hai on the other hand have both lived in completely inhabited regions for thousands of years, and in the case of the Hai for tens of thousands of years.

And from a gameplay perspective, we simply aren't going to give every possible outfit type to every possible faction. Outfits from different factions need to be sufficiently different from one another to be interesting, otherwise meeting new alien factions starts to get boring if they just have slightly altered versions of things you've already seen; each new faction you meet should have quirks with their outfits that you haven't seen before. This is why for a while we only have human and Wanderer ramscoops and just human fuel pods, then eventually gave the Korath a ramscoop/fuel pod hybrid outfit. So even if we were to add ramscoops to the Hai or Coalition, we'd need a sufficiently interesting quirk to give them.
