### ISSUE TITLE
Can't Back out of New Pilot

### ISSUE THREAD

**Issue by redcrate** [endless-sky/endless-sky#6056]
Unable to back out of new pilot process and return to the main menu if clicked on by accident.

**Comment by McloughlinGuy** [comment]
(Inset Tehhowch telling person to fill out template here)

**Comment by MCOfficer** [comment]
^this. You can find the template [here](https://raw.githubusercontent.com/endless-sky/endless-sky/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by aberhow** [comment]
What is the purpose of using this template if all the relevant information requested by the template is already contained within the issue?

---

**Describe the bug**
Unable to back out of new pilot process and return to the main menu if clicked on by accident.

**To Reproduce**
... back out of new pilot process ...

**Expected behavior**
...  to back out of new pilot process and return to the main menu if clicked on by accident. ....

**Screenshots**
Irrelevant 

**System (please complete the following information):**
Irrelevant 

**Link to save file**
Irrelevant

**Additional context**
Irrelevant

**Comment by Anarchist2** [comment]
I feel like #5512 solved this issue already.

**Comment by MCOfficer** [comment]
> 
> 
> I feel like #5512 solved this issue already.

It solved it for content creators. I get the feeling OP is a player that wants to return to the main menu, but i could be misinterpreting "back out".

**Comment by aberhow** [comment]
> > I feel like #5512 solved this issue already.
> 
> It solved it for content creators. I get the feeling OP is a player that wants to return to the main menu, but i could be misinterpreting "back out".

yes, that is correct

**Comment by tehhowch** [comment]
> What is the purpose of using this template if all the relevant information requested by the template is already contained within the issue?

Things you think relevant != things that maintainers think relevant.
Things you think are detailed enough != things that maintainers think are detailed enough.
The template is there to help remind you that there is a lot of room for context and interpretation. Your viewpoint and others' viewpoints are highly unlikely to be equivalent, so providing more context will help others understand you.

> **Describe the bug**
> Unable to back out of new pilot process and return to the main menu if clicked on by accident.

"Back out of" meaning...?
The screen after you click "Load/Save"? You can do that already.
The screen after you click "Load/Save," and then click "New Pilot"? You can do that already.
The screen after you click "Load/Save," and then "New Pilot," and then also click "Start Game"? You're right, at this point you're staring down a conversation panel that asks you to fill out your name, and you can't use the menu key to open the main menu. Your previously loaded pilot, if any, is now closed and any changes since the last time you saved are lost, because you went through _a lot_ of hoops to start a new game.


> **To Reproduce**
> ... back out of new pilot process ...
> **Expected behavior**
> ... to back out of new pilot process and return to the main menu if clicked on by accident. ....
> **Screenshots**
> Irrelevant

False. It's quite relevant and helps others understand what you consider "the new pilot process" that needs to be backed-out from.

> **System (please complete the following information):**
> Irrelevant
> 
> **Link to save file**
> Irrelevant
> 
> **Additional context**
> Irrelevant

Probably what you are actually wanting is us to fix the bug where, when a "name" prompt is being displayed, the menu panel can't be opened. This bug isn't unique to the "New Pilot" process, but is likely where most players will encounter those prompts.

**Comment by daveeater** [comment]
It is possible to "back out" if you've got yourself "stuck" in the new pilot conversation panel. It's not pretty, but you can simply Quit the game and then re-launch the game, and you're back at the main menu.  Yeah, it would be lovely if the Esc key kicked you out of the conversation panel, but it's not clear to me that such functionality wouldn't interfere with mission mechanics (e.g., if you can Esc out of conversation panels, you can Esc out of situations where the mission doesn't want you to have a choice). Moreover, if you've "accidentally" dug yourself three layers deep (Load/Save, New Pilot, Start Game), the extra mouse click to re-launch the game seems pretty trivial.

**Comment by Pointedstick** [comment]
After you click "New Pilot", you can "Back out" by clicking on the "Back to Menu" button. If instead you click the "Start Game" button, then, well, you've started the game. you can't back out until you've filled in your name and such. This is a required step, so I don't think there's a problem to be solved here.
