### ISSUE TITLE
[Feature Idea]: New Homing Type

### ISSUE THREAD

**Issue by onkel75** [endless-sky/endless-sky#6058]
**Is your feature request related to a problem? Please describe.**

I was thinking about missiles and that the homing systems seemed sort of boring since there aren't that many. So I thought about real missile guidance systems, and came up with my Idea.

![laser](https://user-images.githubusercontent.com/85624541/121366522-d8a5de80-c939-11eb-9bf1-509bc101e8ee.png)
(credit: https://thaimilitaryandasianregion.wordpress.com/2018/04/)

**Related Issue Links**
Has anyone else had this issue or idea?

**Describe the solution you'd like**

In real life lots of missiles are guided by a laser beam, projected by the launching vehicle, towards the target. This enables the missile to be lighter, carrying more explosives and engines, due to it not having to carry big large guidance systems, but still being sort-of intelligent because a human or a more intelligent computer than what would fit into the missile, shows the missile where to fly. The human/computer points the laser towards the target, and the missile does pretty much anything to reach the laser dot, like a cat chasing a laser.

So my Idea is that the projectile homes toward the selected ship and does so not mattering on size, radar jamming or heat of the enemy ship. The drawback I had in mind is that the missile homing loses efficiency with distance to the ship that launched it. This would be because the "laser" that the ship emits (not actually present but is the idea) can't be picked up by the missile the farther the launching ship is away. Maybe there would be a maximum range? This i just an idea I had recently and I don't know how it would be implemented, but I just wanted to share it.

**Describe alternatives you've considered**
I dunno, anyone else has other ideas?

**Additional context**
For example the AGM-114 "Hellfire" uses this system.

**Comment by Ferociousfeind** [comment]
Thoughts on the missiles chasing the launching ship's current active target, instead of sticking to their assigned target on being fired? Analogous to moving the laser to some other ship instead of keeping it on that one ship. This would make laser guidance exhibit a unique behavior. (I'd like for the others to perhaps exhibit unique behaviors too, not just different criteria to sometimes-if-you're-lucky swerve out of the way.)

**Comment by Pointedstick** [comment]
In real life, laser guidance exists for short-ranged missiles where it is advantageous for a human spotter to direct the missile to its final destination for maximum precision, or to change the target or abort the mission at the last minute. It is not used for long-range missiles.

In Endless Sky, none of these conditions apple:
1. maximum precision not requires because ships are big and you can't do things like target specific areas of ships
2. Aborting the missile strike at the last minute isn't a thing you do in this game
3. Missile ranges are generally pretty long.

So I don't think this guidance method would make sense, sorry.
