### ISSUE TITLE
Add ship hardpoints for reverse engines to fire from

### ISSUE THREAD

**Issue by bassgoonist** [endless-sky/endless-sky#610]
When coming out of hyperspace I've seen NPC ships use their reverse thrusters to slow down, as opposed to turning 180 and using the main thrusters, but if the flagship is equipped exactly the same it still turns 180 to slow down.

If the flagship used reverse thrusters when on 'autopilot' this could make landing on planets quicker, depending on how heavy the ship is/how fast it can turn

**Comment by Gkramme** [comment]
In many ocasions, my ships have used reverse thrusters to land and to jump. They are not very powerful, however, and they are only used if it offers a quicker alternitive than spinning around to stop or to orient your ship for landing. If you have a large ship with powerful engines, it will use the quicker way instead of the slow reverse thrusters. Get a small flagship with reverse thrusters. They will be used.

**Comment by bassgoonist** [comment]
Alright, I tested and it will use them to slow down if they're powerful enough, but if it's going for best efficiency you'd think it would fly around backwards all the time if you had 5 times as much reverse thrust as forward...but it doesn't.

**Comment by bobafetthotmail** [comment]
we need capital-class reverse thrusters, 'nuff said.

**Comment by guillochon** [comment]
The reverse thrusters really need some visual/aural indication that they are firing, that would I think make it obvious when they are being used.

**Comment by LocalGod79** [comment]
@endless-sky did you just want the centre front tip mapped for each ship?  labeled 'rengine'?

**Comment by Amazinite** [comment]
Implemented this in #4539 using a `"reverse engine"` keyword that works the same as `engine`, but for reverse thrusters.

**Comment by Amazinite** [comment]
https://github.com/endless-sky/endless-sky/commit/435ab5c32047d589b14bb73e380e3d1869410893
