### ISSUE TITLE
[Question/Documentation] Uncertain licensing policy?

### ISSUE THREAD

**Issue by oo13** [endless-sky/endless-sky#6104]
**Describe the bug**
README.md links "source code" to the whole repository, but it says the source code and all the artwork have the different licensing policy.
Which license will you publish the data files under? I'm not a native English speaker and not sure what means "artwork" exactly.

**Expected behavior**
README.md clearly says anything except visual images and sounds shall be published by GPLv3.

**Additional context**
CC-NC and ND restrict distribution and modification. If you might accept NC and ND, I would avoid distributing and modifying the data files.
I should notice it and ask you it five years ago...

**Comment by MCOfficer** [comment]
Exact copyright is documented in the `copyright` file. An Excerpt:

```

Files: images/*
Copyright: Michael Zahniser <mzahniser@gmail.com>
License: CC-BY-SA-4.0

[...]

Files:
 images/icon/gat*
Copyright: Jonathan Steck
License: CC-BY-SA-4.0
Comment: Derived from works by Maximilian Korber (under the same license).
```

Which means that all files in `images` are CC-BY-SA-4.0 by MZ, unless specified otherwise. One such exception is for all files that match `images/icon/gat*`, which are CC-BY-SA-4.0 by Jonathan.

**Comment by oo13** [comment]
I know about the copyright file.

README.md says "all the artwork is either public domain or released under a variety of Creative Commons licenses.", so you can post a PR under CC-NC or CC-ND and devs might accept it.

I wonder what licenses devs might accept for the data files.

**Comment by Amazinite** [comment]
> I wonder what licenses devs might accept for the data files.

All data files are currently under GNU GPLv3. From the copyright header in each data file:
> \# Endless Sky is free software: you can redistribute it and/or modify it under the
> \# terms of the GNU General Public License as published by the Free Software
> \# Foundation, *either version 3 of the License, or (at your option) any later version.*

So I'd only be accepting data files under these conditions of it being licensed under GNU GPLv3 or later versions.

> I'm not a native English speaker and not sure what means "artwork" exactly.

Artwork is any images and sounds, which is what the copyright file covers.

**Comment by tehhowch** [comment]
I would also include the text-based data files in the definition of "source code" for Endless Sky, as they are of a material format to the game and its directly associated content (such as map or ship editors), but are not widely useful in other contexts without extended processing.

That said, I doubt processing existing texts, such as a novel or excerpt thereof, into a format recognizable by the game, is sufficient to count as a new work and thus would be bound by the license(s) of the original. The same goes for e.g. compiling narratives from the game's missions or hails - the result is bound by the original license, which will be GPL v3 unless explicitly noted otherwise.

**Comment by oo13** [comment]
Thank you for answering my question!
