### ISSUE TITLE
Spacediving on Luna

### ISSUE THREAD

**Issue by paulusasol** [endless-sky/endless-sky#6146]
It does not appear to make sense to offer spacediving jobs for Luna due to its lack of an atmosphere. However this job is offered.

**Comment by petervdmeer** [comment]
Thanks for the bug report.
The missions already have attribute-filters ["not station" and "not research"](https://github.com/endless-sky/endless-sky/blob/aeb612f7c4cfa42729b83d64970ac69a63c8e8c7/data/human/transport%20missions.txt#L3297) to avoid non-atmospheric locations, but apparently that is not sufficient.

I see a number of ways to fix this:
- Either we add attributes to planets like "atmosphere" (and maybe also attributes like "mountains", "oceans", "landmasses" for if we add sports like skiing, water sports and missions that require large patches of land later) and require the "atmosphere attribute from the skydiving missions.
- Or we hard-code exceptions directly into the skydiving missions.

I would prefer the generic attributes for fixing this, because they are more re-usable for future missions.

**Comment by MCOfficer** [comment]
Is using moons as attribute an option? It would net us some false positives, but it pretty much filters out any non-atmosphere bodies.

**Comment by Anarchist2** [comment]
Should the quality of atmosphere be considered for destinations of the missions? Places like Helheim and Oblivion seem to have pretty nasty atmospheres, though you could also just lore it away as saying that the skydivers have the equipment to survive.

In terms of airless non-moons, the closest thing I could find was Trove, which only says it's too small to have a breathable atmosphere.

**Comment by petervdmeer** [comment]
I just created an update that filters out all moons (including Luna). But we should add relevant attributes as suggested by Anarchist2 (like the quality of the atmosphere) to solve this properly.

**Comment by Pointedstick** [comment]
Filtering out moons seems good enough to me, honestly.

Let's track the addition of additional attributes in a new issue, if needed.
