### ISSUE TITLE
Feat: Scroll bar on plugins list

### ISSUE THREAD

**Issue by kestrel1110** [endless-sky/endless-sky#6154]
**Is your feature request related to a problem? Please describe.**
I don't know if anyone else has this problem, but as someone who enjoys a ridiculous amount of plugins, sometimes they get a bit out of hand.
Pictured here are about two thirds of my plugins loaded and the rest off-screen.
![Screenshot from 2021-08-02 11-21-19](https://user-images.githubusercontent.com/64381519/127885087-85456a32-2fef-4cf8-8362-7100e6de609a.png)

**Describe the solution you'd like**
Solution: a scroll bar. Instead of plugins just going on the list until it exceeds the bounding box, a scroll bar would appear that enabled you to scroll through the list of plugins, instead of them looking terribly ugly as they move out of their dedicated box and even, as in my case, off the screen.

**Describe alternatives you've considered**
And alternative would be to increase the size of the plugin box or make it fit to the length of the list of plugins. But, that wouldn't be helpful for an amount of plugins that goes off the screen.

**Additional context**
N/A

**Comment by tehhowch** [comment]
The plugin UI is absolutely in need of some touch-ups (related issue: https://github.com/endless-sky/endless-sky/issues/2022).

Rather than just a simple touch-up to add scrolling, anyone wanting to work on this should convert the plugin menu to be driven solely from its interfaces.txt description. Guidance on that can be found by looking at the implementation of the newly added panel for start conditions.
