### ISSUE TITLE
0.9.14 Syndicate space Koroth Raider boarding impossible

### ISSUE THREAD

**Issue by neevok-eu** [endless-sky/endless-sky#6157]
Since the last version it seems impossible to board a koroth raider in Polaris or Sheratan. This was my usual way of obtaining a jump drive and hull repair technology while sticking to human space. In Polaris the Koroth raider is destroyed by other syndicate forces and in Sheratan it is usually shot by my own escorts even though I have given the hold command...

It is illogical for syndicate forces to destroy the alien craft as the story says (later) that they obtained jumpdrives from an alien species. They would board and loot any disabled ship an not destroy it,

My second,, but indirectly related point is the Hai introduction storyline. You have to transport the band three times before you are introduced to the Hai. In fact I have not been able to get that far. The third band mission simply does not come up.
This should be MUCH easier (in effect a higher chance). In my current playthrough I decided not to visit Hai space unless I am directed there. I also have not started the Free worlds campaign but am doing some deep missions.

**Comment by DeciduousBeard** [comment]
Regarding your second question, the third band transport mission will not appear until you have found the Hai. That is how the story works - in the story, it is only because you already know how to find the Hai that you can suggest to the band that you could take them there. So the job will not appear until you have had first contact with the Hai. This is by design.

If you want that job, visit the Hai, then hang out in the dirt belt / south / rim systems for a while.

**Comment by neevok-eu** [comment]
that is not true. The third option has a variant where they lead you to the hai. Look at the mission text (see the options)

**Comment by DeciduousBeard** [comment]
The "There Might Be Riots part 3A" job includes the following offer conditions:
```
	to offer
		has "There Might Be Riots part 2: done"
		has "First Contact: Hai: offered"
		random < 30
```
This means it will not ever be triggered until you have completed "First Contact: Hai".

There is a slight variation in the mission text depending on whether you had visited the Hai before or after doing TMBR mission 2. I believe this is the "variant" you are speaking of. But if you look more closely at the job you'll see that only affects the conversation text. The third mission itself will never be offered until you have already found the Hai.
https://github.com/endless-sky/endless-sky/blob/7338aacc474198f2d6caf92b424fa3fe98f4c981/data/human/transport%20missions.txt

**Comment by movingpictures** [comment]
> Since the last version it seems impossible to board a koroth raider in Polaris or Sheratan. This was my usual way of obtaining a jump drive and hull repair technology while sticking to human space. In Polaris the Koroth raider is destroyed by other syndicate forces and in Sheratan it is usually shot by my own escorts even though I have given the hold command...

Durax is your answer. Or, depending on your definition of "human," also Remnant space.

**Comment by neevok-eu** [comment]
@DeciduousBeard
You're right, I must have misread the text (or was it changed)
In that case it would be a very nice variant (3B or something like it) where the band tells you how to get to the Hai...

@movingpictures
Thanks I will try that system, but it is still illogical that the syndicate destroys the alien ship. More broadly: I wish in general that the chance a disabled ship gets destroyed would be MUCH lower. And if you are playing as the good guy a variant where you capture the crew instead of killing them.

**Comment by Zitchas** [comment]
The syndicate is a profit-centric entity, and are probably well aware of how valuable alien technology can be. Therefor two potential motivations for them destroying Korath ships could be involved:
a) They want to preserve Korath technology for themselves so that they are the only ones who have a chance to research & market something based on it.
b) They want to prevent anyone else from getting a combat edge on them, 
Both cases basically boil down to a "if there's a chance that someone else might get their hands on the alien tech, destroy it. We can't risk non-syndicate people getting their hands on it or realizing how special/advanced/valuable it is.

Keep in mind that the Korath are *not* public knowledge, despite regularly appearing in those systems. So far as humanity as a whole is concerned, the only aliens we know about are the Quarg. This implies that the Syndicate (who clearly have looted at least 7 Korath ships so far) is actively suppressing  knowledge of them, and probably has some kind of propaganda campaign in effect that depicts the Korath raiders as a new kind of pirate ship, Syndicate prototype, or some other innocuous explanation. There have been plenty of corporate R&D programs over the years that have had "destroy if there's a chance of someone external to the program discovering it" mandates.

**Comment by Zitchas** [comment]
Based on all the alien movies we have, this sounds emminently normal for humanity as an overall group: "It's strange and different, Kill it!"

**Comment by movingpictures** [comment]
FYI, I attempted to verify this claim - and managed to board two Korath Raiders in Syndicate space. Dec. 27 continuous build, fleet of Falcons and Ospreys.

**Comment by Zitchas** [comment]
As an additional thought: The syndicate (and pirates, and everyone else) destroying the ship instead of letting the player have their way with it is definitely annoying, and is clearly disadvantageous to humanity as a whole. (*WE* see the big picture and how having lots of JD and alien tech is good, and that there's no risk to doing so like plague or wild nanites, etc.) Local ships, however, aren't operating under "big picture" mentality. They're all operating under one of the following:

1. Syndicate directive: If we can't keep it entirely to ourselves, destroy it to keep it our own resource.
2. Pirates: It's a competitor that would take the stuff we're here to steal, kill it!
3. Civilians: It's a ship that raids us! Every one of it we kill means that many fewer to come back to kill us later!
4. Everyone who thinks it is alien: I've watched (insert sci-fi horror show here)! I know what I need to do to save humanity from this threat! Kill it!

Sadly, virtually none of the ships we see there are part of the tiny minority, which includes the player, who say: "It's a source of useful tech that humanity needs, save and loot it!"

**Comment by mrunderhill89** [comment]
I might be wrong on my development history, but I think ships actually _did_ stop to loot disabled enemies in early builds of the game. The behavior was taken out because it was annoying if an AI took all your loot before you got a chance to take it yourself. The Remnant still board disabled ships, IIRC, but they don't take anything (because again, it would be annoying), so maybe it would be possible to expand this behavior to select Syndicate ships as well?
