### ISSUE TITLE
Bug: Escorts can fly through uncharted systems

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#616]
I started exploring wanderer space, jumping from Ehma Ti to Prakacha'a, and then ordered my fleet (which was down in Alnitak) to come and meet me. Instead of going through Hai space, they took a route though Hatysa, even though I hadn't explored that area and did not yet know that those systems connected to where I was now.

I think this is a bug - escorts shouldn't path along hyperspace links you don't know about yourself.

**Comment by Gkramme** [comment]
I think they should discover those systems if they do it. It would be convienent

**Comment by Thunderforge** [comment]
I would be in favor of them being restricted to routes you have discovered because it provides the least amount of surprise to the player.

If they are somehow unable to get to you through known space (you got sucked through a wormhole or whatever), they would just tell you that they can't get to you right then.

**Comment by endless-sky** [comment]
It may be unrealistic, but it also means that escorts catch up to you more quickly if you leave them behind.

Also, limiting them to systems you know about would make the escort AI a lot more complicated, because right now in most cases the AI does not distinguish between an NPC that is escorting another ship, vs. one of your escorts.

**Comment by dplepage** [comment]
@endless-sky The user experience is confusing - my escorts ran out of fuel, and while I was waiting for their ramscoops to recharge them their icons were on the left of my screen listing a system that didn't appear anywhere on my map. At the time, I hadn't even noticed Aya'k'k (the "unexplored system" icon blends in really well with a star on the background image), so I had no idea where they could be until I explored further into wanderer space and discovered them.

I'd be happy to fix this and submit a patch; I can also fix #355 while I'm working on it.

**Comment by Thunderforge** [comment]
@dplepage If you are willing to tackle those, I would be in favor of seeing those changes implemented.

**Comment by endless-sky** [comment]
Closing this to focus the issues list on feature requests that are more likely to get implemented.
