### ISSUE TITLE
Check out this one simple trick to absolutely eat someone's storage with a single image file (again)

### ISSUE THREAD

**Issue by Anarchist2** [endless-sky/endless-sky#6206]
**Describe the bug**
A similar issue to #5879 has appeared, where giving an image file with an incredibly high frame number will flood the error file with thousands of lines of errors. Not only that, but the game will crash while attempting to load if the frame number is set high enough.

**To Reproduce**
1. Rename or create an image file with a name that denotes a very high frame number. i.e. (~X.png) where X is a very large number.
2. Launch the game.
3. Watch the game crash while loading.
4. Observe how your error file gets filled with line upon line of `Failed to read image data for "<path>" frame #x`

**Expected behavior**
Not that

**System (please complete the following information):**
 - OS: Windows 10
 - Game Source: Self-Compiled
 - Version: 1b3920874e70252fead4c9b06b2f0617bacee0f7

**Additional context**
From my limited research, it appears that the error file filling is caused by 2fd9f8883ccc4bcfcd62e9aa12194f0941572543. Not sure what causes the crash, though.

**Comment by tehhowch** [comment]
The crash is because the game tries to allocate enough memory for the required number of pixels. It can't, so the game assumes there are memory issues, and there is no recourse for "the operating system won't give you the memory you asked for" except to crash (because how can you reliably allocate memory for a string to tell the user what happened if the OS won't give you memory when you ask for it?).

As for the error message spam, we can log a little more intelligently, but we approach a point where the _content creator_ would like more information (tell me all the problems with my stuff) and the consumer wants only to know if the plugin should be uninstalled.

**Comment by Zitchas** [comment]
As a content-creator, if I am missing frames from an animation, I don't see a circumstance where I need to know about more than, say twenty frames for a particlar animation. So to me, if it is possible, I'd say it would be reasonable that any particular effect or animation is capped at 25 missing frame errors. Doesn't matter if it thinks there should be ten thousand frames. It only gets to log error messages for the first 25 of that animation.

**Comment by Ferociousfeind** [comment]
I'd want the game to find all images that are part of the apparent animation (so if it can find "typhoon~0.png", "typhoon~1.png", "typhoon~2.png", and "typhoon~30000000.png", it should only expect 4 images, not 30000000)

And then, use that acquired frame count (in the above case, 4, not 30000000) to allocate memory for processing and such, while reporting the apparent missing frames (in this case, the game is missing at least 30000000-4 or 29999996 frames)

In this way, the only way to generate the crash would be to have the data to be allocated in the first place, instead of only telling the game that you might have that much data to allocate.

**Comment by tehhowch** [comment]
As of 79ce0471b58bb81993affebbebbc5bd1c306964e the game will only keep valid frame sequences for images. Intentionally "frame-bombing" via a plugin will not cause memory allocation issues when collecting paths, or when allocating pixel data.

Every frame after a missing or discontinuous frame is intentionally dropped--if you encounter this scenario when creating your plugin, then you broke your animation, you get to fix it.
