### ISSUE TITLE
Possible (and extremely likely) to get stranded in wanderer space

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#626]

**Comment by Pointedstick** [comment]
If you get stuck, load your game from the last time you were on a planet, buy a ramscoop, and try again. This reads kind of like, "My car stops moving if I drive somewhere with no gas stations and I don't bring some gas along!" User error. 🙂

**Comment by thenerdfreak** [comment]
XD I was actually suggesting that, even though you can't talk to them, the wanderers refill your gas (they seem that kind of group)

**Comment by endless-sky** [comment]
So, the options are:

1. Have it impossible to communicate with the Wanderers, because you don't know their language (good for story, bad for getting stranded).

2. Make it somehow possible to tell them that you need fuel, even though you can't communicate in any other way (conflicts with the story, but more convenient).

Given how easy it is to just reload your game, and given that you shouldn't be exploring unknown space without a ramscoop anyway, I prefer option 1.

**Comment by egilburg** [comment]
@endless-sky it's plausible a stranted pilot would be able to indicate their predicament without knowing the language. E.g. point finger to a point in the sky, and then to their empty fuel tank.

**Comment by Thunderforge** [comment]
I remember in EVN that I got stuck with my first character because I was in a system with no ships at all (way off in the corners) and landed on a planet that didn't have fuel. 

So long as that is not possible in Endless Sky, I would rather that we just have the players reload if they don't have a ramscoop.

**Comment by omagasohe** [comment]
I think the perceived issue is that to get to wander space you have to go through several systems that are default hostile ( pirates or unfettered). So your down 3 or 4 jumps of fuel off the bat and a couple of more just to get to the wander homeworld.  from the direct human space there is a uninhabited system to go through and pirate infested ones and the system you jump into is off limits even if you can talk to them.

The solution is to be a better player and have fuelpods and a ramscoop.

I think contacting a ship you don't know the language to should have a chance of triggering hostilities, since there are words that can take on meaning depending on who says it and to whom. Gestures are the same way. that will also give people more things to complain about

"I ran out of fuel and hailed an unknown alien ship and it started to attack me for no reason" =P

**Comment by egilburg** [comment]
>"I ran out of fuel and hailed an unknown alien ship and it started to attack me for no reason" 

Speaking of this... If you ask for help you will get some fuel. But perhaps you could also take some fuel from a plundered ship? It'll allow *one* way out of being stuck in an unfriendly sector.

**Comment by IFailAtGaming** [comment]
I think refueling from plundered ships is a thing already, at least I remember getting all my fuel back after doing so, but maybe it was a bug

**Comment by frameworld** [comment]
> Speaking of this... If you ask for help you will get some fuel. But perhaps you could also take some fuel from a plundered ship? It'll allow one way out of being stuck in an unfriendly sector.

My preferred solution.

**Comment by Pointedstick** [comment]
You already take fuel from hostile disabled ships.

**Comment by thenerdfreak** [comment]
@Pointedstick you reiterated @egilburg 's statement. I don't want to attack the wanderer ships because I'm building my pre-quarg fleet based off of their FunBeams (as I like to call them) 

but Either way it really doesn't matter. I just reloaded 100+ times and gave up and went and bought at on of fuel pods
