### ISSUE TITLE
Allow the outfit mission keyword to report number of outfits on hand.

### ISSUE THREAD

**Issue by VonZorch** [endless-sky/endless-sky#6273]
### Problem Description

It's just absolutely impossible to get an exact count of the number of a specific outfit available.

### Related Issue Links

None

### Desired Solution

Modify the outfit keyword to return the number of outfits installed or in cargo.  Perhaps by using a ? in place of the quantity.
Like, WeGot = outfit "some outfit" ?
Or add the keyword outfits "some outfit", so WeGot = outfits "some outfit"

### Alternative Approaches

It may be possible to use a stack of require "some outfit" n where n is a specific number such as 1, 2, 3..., but I don't think so.  Unless you can use require in a manner similar to branch.
on offer
    require "some outfit" 1
        WeGot = 1
    require "some outfit" 2
        WeGot = 2
etc

**Comment by tehhowch** [comment]
The existing "on ____" block's `require` and `outfit` keywords will not ever return a value.

With dynamic auto-conditions, and an agreed property-access syntax, one will eventually be able to determine this. (Note that the question, "how many of outfit 'x' does the player have," is not at all specific enough for the answer to satisfy everyone who asked it, which is why both functionalities are required.)

There are related issues to this already, too.

**Comment by warp-core** [comment]
I think #7210 achieves the desired functionality.
