### ISSUE TITLE
Can we add this ship?

### ISSUE THREAD

**Issue by Mark11110** [endless-sky/endless-sky#6283]
### Problem Description

I found this sprite. It says free
https://www.pngkey.com/detail/u2e6w7a9w7t4u2i1_enemy-spaceship-png-nave-sprite/

This can be a good remnant ship too:
https://www.kindpng.com/imgv/wRJJih_space-ship-sprite-png-space-ship-sprite-transparent/

Can we add these?

### Related Issue Links

n/a

### Desired Solution

just thinking of a new ship that we could add

### Alternative Approaches

n/a

**Comment by Hyugat** [comment]
They don't really match the artstyle of the game, and would probably be a better fit for a plugin, which you can discuss on the [discord](https://discord.gg/ZeuASSxl).

**Comment by Zitchas** [comment]
There's two issues with these:
1. They don't match the artstyle of the ships already in game.
2. The license of the one is unclear, and the other one states "free for personal use only." It is unclear whether it would be legal to redistribute either one of them, or use in a project like ours.

If you would like to see them in-game, I would strongly recommend making a plug-in that adds them, as they are unlikely to be added to the base game for the above reasons.

**Comment by ixPost** [comment]
The second ship don't look nice to me, it look like oh well cartoony hyperevil si-fi, kiddish(maybe I should have said hobbitish?)? I can't describe it precisely, well silly looki'n.

The first ship is not realistic looking at all!

**Comment by Zitchas** [comment]
To expand on my previous comment a bit:

There's a variety of requirements for a ship to be added to the game. The more of these that can be satisfied, the more likely something is to be included:
1. A role: Generally speaking, we try to have just a single ship per faction that fills a specific role and type. Ex. If they already have a heavy warship that is designed to be a brawler (close quarters combat), why would they have a second heavy warship that is also a brawler? 
2. Lore: What is the story behind this ship? Why does it exist? How is it different from similar ships, especially within its ecosystem? There can be story reasons for it existing (perhaps it is a new ship unlocked over the course of story, with different capabilities from its predecessors, for instance.), but the closer it is to duplicating an already existing role in that faction, the better the lore has to be.
3. Supporting content: If a ship is added to the base set of ships available from the start of the game, then reasons 1 or 2 need to be strong. If it is a ship to be revealed later on in a storyline, then it needs to have missions and story that lead up to it. 

On the technical side:
4. A .blend file, and usually a .xcf file too: As a community project, it is important to enable the project to continue development by making all the assets used in the creation of the graphics available. As such, when ships and outfits are added to the game, we also add the 3d model (.blend) file to the asset repository. This means that, as capabilities improve, it is easy for them to be touched up, re-rendered, and improved over time; as well as enabling derivatives (such as "modified" or "marauder" versions).
5. All artwork has to be compatible with Endless Sky's copyright and licensing, as it will be distributed freely as part of the game and is freely accessible from the respository. While free artwork from elsewhere may meet this requirement, we generally prefer original artwork that is submitted by the artist as that is the easiest way to ensure that it is actually created under a compatible license. There are "free" artwork sites out there that list stuff as being free and open permissions, but have actually stolen their content from across the internet. We don't want to risk accidentally perpetuating the theft of someone's artwork just because it was listed on a freebie site.

And as a side note: The first image's name "enemy-spaceship-png-nave-sprite" suggests that it may, in fact, be a spaceship from the game NAEV, which is another game inspired by Escape Velocity. If this is the case, it would be inappropriate for us to use a ship image from a similar game. Special exceptions can be made, such as, for example, the Kestrel (which is deliberately an easter egg / tribute to the original Escape Velocity trilogy). But these need to be carefully thought out and implemented.

**Comment by ixPost** [comment]
>
>
>    1. role: Generally speaking, we try to have just a single ship per
>    faction that fills a specific role and type. Ex. If they already have a
>    heavy warship that is designed to be a brawler (close quarters combat), why
>    would they have a second heavy warship that is also a brawler?
>    2. Lore: What is the story behind this ship? Why does it exist? How is
>    it different from similar ships, especially within its ecosystem? There can
>    be story reasons for it existing (perhaps it is a new ship unlocked over
>    the course of story, with different capabilities from its predecessors, for
>    instance.), but the closer it is to duplicating an already existing role in
>    that faction, the better the lore has to be.
>    3. Supporting content: If a ship is added to the base set of ships
>    available from the start of the game, then reasons 1 or 2 need to be
>    strong. If it is a ship to be revealed later on in a storyline, then it
>    needs to have missions and story that lead up to it.
>
> On the technical side:
> 4. A .blend file, and usually a .xcf file too: As a community project, it
> is important to enable the project to continue development by making all
> the assets used in the creation of the graphics available. As such, when
> ships and outfits are added to the game, we also add the 3d model (.blend)
> file to the asset repository. This means that, as capabilities improve, it
> is easy for them to be touched up, re-rendered, and improved over time; as
> well as enabling derivatives (such as "modified" or "marauder" versions).
>
*???*
