### ISSUE TITLE
Paragraph formatting

### ISSUE THREAD

**Issue by seanfahey** [endless-sky/endless-sky#63]
I see in blocks of text with multiple paragraphs that the first paragraph begins with no indentation, but all of the following paragraphs do have indentation, using non-breaking spaces. An example is in Poisonwood's world description.

Is that done on purpose, or should the first paragraphs have indentation added, or should indentation from following paragraphs be removed?

PS, you have done some awesome work, it is a lot of fun!

**Comment by endless-sky** [comment]
Whether or not you indent the first paragraph turns out to be something that prompts [considerable discussion](http://ask.metafilter.com/18872/No-indentation-of-initial-paragraphs) among typography geeks. If you look at a random book or magazine, very often the first paragraph of each chapter or section or article is aligned flush rather than indented, and that seems to be considered more "professional." But, you can also find plenty of cases where all the paragraphs, even the first ones, are indented.

So yes, not indenting the first paragraph was intentional. That, along with justifying the text (stretching the spaces so both margins are a straight line) was meant to give the text a neater, more professional aesthetic. But you're right that in plenty of contexts (like, pretty much everything you find on the web, or in Word documents) the standard is usually to indent everything or nothing.

**Comment by seanfahey** [comment]
Sounds good. It is interesting to read up on the differences between style guides.

I have some PRs I am going to put in for typos that I come across, but I wanted to see if I should go crazy on these indents or leave them alone.  Thanks!

**Comment by endless-sky** [comment]
I'm thinking of doing a stable release within the next week. If you get a chance this weekend, could you do a pull request for your fixes to the hyperdrive and the anti-missile descriptions? (I could just change them myself, but I'd rather that you get credit for finding the typos.)
