### ISSUE TITLE
Suggested change to trade prices of Metal and Heavy Metal

### ISSUE THREAD

**Issue by Hector-of-the-Void** [endless-sky/endless-sky#6398]
### Problem Description

There is a large disparity between harvested astoid ore prices and Metal/Heavy Metal trading good prices. 

The only correlating prices are Silicon and Lead for Metal and Heavy Metal respectivly at or near Very Low prices. 
If it was the intention of the trade goods for Metal/Heavy Metal to be scrap then they should still be above the ore prices by a small amount. I was under the impresion that they were ingots ready for manufacturing or half procesed materials like sheet metal and coils of wire.

I know realism is not the goal, but some semblence of it increases immersion. I don't propose realistic price ratios because that would make the trade goods almost unreasonably expensive in early game, and in mid-late game keeping the same % variance would allow for very quickly snowballing fleets. I will mention an example as it adds some weight to the idea of changing them.

Producing 1 ton of aluminum takes 4 tons of ore.
Currently the cost of the ore amounts to about  1/32th of the total cost to produce a ton of aluminum
With a future society having almost negligable energy and labor costs, ore would still be about 1/9th the total cost.
This is without corperations like the syndicate tring to make an exorbant profit.

### Related Issue Links

[https://github.com/endless-sky/endless-sky/issues/1018]
the only issue I found related to trade prices, it dosen't really apply to this, neiter did any of the astroid mining issues I found relate to their prices at all.

### Desired Solution

 I propose that the adverage prices of Metal and Heavy Metal be increased to at least that of their average constituent ore prices, and the order of trade goods be changed to reflect the new values. 

I recomend metal be priced at 1200 to cover silicon, lead, aluminum, copper, and iron. Also that  heavy metal be priced at 3800 to cover neodymium, titanium, tungsten, and uranium. The precious metals and yottrite will just not be covered.

This is a minor issue and not likely to be noticed by the adverage player, however it is a real easy fix so I hope it gets implimented.

### Alternative Approaches

The easist fix is lowering ore prices but currently it feels balanced for the effort, changing Metal and Heavy Metal prices would not break the balance. Maybe Replace Metal with a new trade product and rename Heavy Metal to Metal.
For astetic purposes Luxury goods cost could be incressed to go between Metal and Heavy Metal.

### Additional Context

Currently I understand that job goods are a single unit with a defined mass/cargo space. In the future if jobs transporting outfits, astroid ores, or trade goods get implimented then it may be a more noticable disparity. 

In particular I had an idea for a series of jobs (framed as a multi part mission) where the player gathers ore and delivers it to a factory planet, then 20+ days later transports the metals to a diffrent factory planet to be combined into the needed alloy. then 20+ days later transports the unique metal to an outfit planet to be make into parts, and after some time can pick up an outfit. (not sold anyware, either new so will now be sold, like the electron turret mission, or because it requires some rare element like yottrite)

The request becomes relevent when my recovery misson (if you failed a part) asks for Heavy metal (more than the original transport amount) to turn into the special alloy (time rush reasons for not starting over). I want to keep the cargo size down but not let the player make a profit selling the ores and skipping to the recovery mission.

**Comment by Hecter94** [comment]
Looking into actually implementing this suggested change. Is what's listed in the desired solution, ie. 

> metal be priced at 1200 to cover silicon, lead, aluminum, copper, and iron. Also that heavy metal be priced at 3800 to cover neodymium, titanium, tungsten, and uranium.

What we're happy to go with? 

Looks like it would resolve the issue and I don't see it causing any extra issues since the absolute value of trade goods is rarely relevant outside of very early game. 

For values, I'm thinking of setting the new values to
Metal - Min: 890, Max:1420, Avg: 1155
Heavy Metals - Min: 3370, Max:4120, Avg: 3745

For reference, this is how those new values compare against the current ones:
| Commodity            | Min  | Max  | Range | Average |
|----------------------|------|------|-------|---------|
| **Heavy   Metals - New** | 3370 | 4120 | 750   | 3745    |
| Luxury Goods         | 920  | 1520 | 600   | 1220    |
| **Metal   - New**        | 890  | 1420 | 530   | 1155    |
| Heavy Metals         | 610  | 1310 | 700   | 960     |
| Electronics          | 590  | 890  | 300   | 740     |
| Industrial           | 520  | 920  | 400   | 720     |
| Medical              | 430  | 930  | 500   | 680     |
| Equipment            | 330  | 730  | 400   | 530     |
| Metal                | 190  | 590  | 400   | 390     |
| Plastic              | 240  | 540  | 300   | 390     |
| Food                 | 100  | 600  | 500   | 350     |
| Clothing             | 140  | 440  | 300   | 290     |

If you're curious, this is what the individual system values would change by with these new min, max and averages:
<details>
  <summary>Metal</summary>

| Old | New  |
|-----|------|
| 589 | 1409 |
| 588 | 1408 |
| 587 | 1407 |
| 580 | 1400 |
| 577 | 1397 |
| 575 | 1395 |
| 572 | 1392 |
| 566 | 1386 |
| 565 | 1385 |
| 560 | 1380 |
| 559 | 1379 |
| 554 | 1374 |
| 549 | 1369 |
| 548 | 1368 |
| 547 | 1367 |
| 546 | 1366 |
| 546 | 1366 |
| 543 | 1363 |
| 542 | 1362 |
| 542 | 1362 |
| 542 | 1362 |
| 541 | 1361 |
| 540 | 1360 |
| 540 | 1360 |
| 539 | 1359 |
| 538 | 1358 |
| 538 | 1358 |
| 537 | 1357 |
| 537 | 1357 |
| 536 | 1356 |
| 535 | 1355 |
| 535 | 1355 |
| 534 | 1354 |
| 533 | 1353 |
| 532 | 1352 |
| 531 | 1351 |
| 531 | 1351 |
| 528 | 1348 |
| 525 | 1345 |
| 524 | 1344 |
| 524 | 1344 |
| 523 | 1343 |
| 521 | 1341 |
| 520 | 1340 |
| 520 | 1340 |
| 520 | 1340 |
| 518 | 1338 |
| 518 | 1338 |
| 517 | 1337 |
| 517 | 1337 |
| 516 | 1336 |
| 516 | 1336 |
| 515 | 1335 |
| 514 | 1334 |
| 514 | 1334 |
| 514 | 1334 |
| 513 | 1333 |
| 513 | 1333 |
| 512 | 1332 |
| 511 | 1331 |
| 510 | 1330 |
| 510 | 1330 |
| 508 | 1328 |
| 508 | 1328 |
| 506 | 1326 |
| 502 | 1322 |
| 499 | 1319 |
| 498 | 1318 |
| 498 | 1318 |
| 497 | 1317 |
| 496 | 1316 |
| 495 | 1315 |
| 495 | 1315 |
| 495 | 1315 |
| 493 | 1313 |
| 490 | 1310 |
| 490 | 1310 |
| 489 | 1309 |
| 488 | 1308 |
| 486 | 1306 |
| 485 | 1305 |
| 484 | 1304 |
| 483 | 1303 |
| 483 | 1303 |
| 480 | 1300 |
| 480 | 1300 |
| 479 | 1299 |
| 478 | 1298 |
| 478 | 1298 |
| 478 | 1298 |
| 478 | 1298 |
| 476 | 1296 |
| 475 | 1295 |
| 475 | 1295 |
| 474 | 1294 |
| 473 | 1293 |
| 473 | 1293 |
| 473 | 1293 |
| 473 | 1293 |
| 470 | 1290 |
| 468 | 1288 |
| 468 | 1288 |
| 467 | 1287 |
| 466 | 1286 |
| 463 | 1283 |
| 462 | 1282 |
| 461 | 1281 |
| 460 | 1280 |
| 460 | 1280 |
| 459 | 1279 |
| 458 | 1278 |
| 458 | 1278 |
| 457 | 1277 |
| 457 | 1277 |
| 456 | 1276 |
| 455 | 1275 |
| 454 | 1274 |
| 451 | 1271 |
| 451 | 1271 |
| 450 | 1270 |
| 450 | 1270 |
| 448 | 1268 |
| 448 | 1268 |
| 448 | 1268 |
| 446 | 1266 |
| 446 | 1266 |
| 445 | 1265 |
| 445 | 1265 |
| 444 | 1264 |
| 444 | 1264 |
| 443 | 1263 |
| 442 | 1262 |
| 439 | 1259 |
| 438 | 1258 |
| 438 | 1258 |
| 438 | 1258 |
| 436 | 1256 |
| 435 | 1255 |
| 433 | 1253 |
| 432 | 1252 |
| 432 | 1252 |
| 429 | 1249 |
| 427 | 1247 |
| 426 | 1246 |
| 422 | 1242 |
| 421 | 1241 |
| 419 | 1239 |
| 417 | 1237 |
| 417 | 1237 |
| 417 | 1237 |
| 417 | 1237 |
| 416 | 1236 |
| 416 | 1236 |
| 415 | 1235 |
| 414 | 1234 |
| 414 | 1234 |
| 413 | 1233 |
| 413 | 1233 |
| 412 | 1232 |
| 410 | 1230 |
| 408 | 1228 |
| 408 | 1228 |
| 407 | 1227 |
| 407 | 1227 |
| 406 | 1226 |
| 406 | 1226 |
| 406 | 1226 |
| 404 | 1224 |
| 404 | 1224 |
| 404 | 1224 |
| 402 | 1222 |
| 398 | 1218 |
| 397 | 1217 |
| 396 | 1216 |
| 395 | 1215 |
| 393 | 1213 |
| 393 | 1213 |
| 392 | 1212 |
| 390 | 1210 |
| 389 | 1209 |
| 388 | 1208 |
| 388 | 1208 |
| 388 | 1208 |
| 385 | 1205 |
| 384 | 1204 |
| 383 | 1203 |
| 382 | 1202 |
| 378 | 1198 |
| 375 | 1195 |
| 372 | 1192 |
| 368 | 1188 |
| 368 | 1188 |
| 367 | 1187 |
| 367 | 1187 |
| 366 | 1186 |
| 366 | 1186 |
| 365 | 1185 |
| 365 | 1185 |
| 363 | 1183 |
| 362 | 1182 |
| 359 | 1179 |
| 358 | 1178 |
| 358 | 1178 |
| 357 | 1177 |
| 357 | 1177 |
| 356 | 1176 |
| 356 | 1176 |
| 354 | 1174 |
| 354 | 1174 |
| 354 | 1174 |
| 352 | 1172 |
| 351 | 1171 |
| 350 | 1170 |
| 349 | 1169 |
| 348 | 1168 |
| 348 | 1168 |
| 348 | 1168 |
| 348 | 1168 |
| 346 | 1166 |
| 346 | 1166 |
| 345 | 1165 |
| 344 | 1164 |
| 342 | 1162 |
| 341 | 1161 |
| 341 | 1161 |
| 340 | 1160 |
| 340 | 1160 |
| 339 | 1159 |
| 339 | 1159 |
| 338 | 1158 |
| 338 | 1158 |
| 338 | 1158 |
| 338 | 1158 |
| 338 | 1158 |
| 338 | 1158 |
| 336 | 1156 |
| 336 | 1156 |
| 335 | 1155 |
| 335 | 1155 |
| 335 | 1155 |
| 335 | 1155 |
| 334 | 1154 |
| 334 | 1154 |
| 334 | 1154 |
| 334 | 1154 |
| 333 | 1153 |
| 332 | 1152 |
| 331 | 1151 |
| 330 | 1150 |
| 329 | 1149 |
| 328 | 1148 |
| 328 | 1148 |
| 328 | 1148 |
| 327 | 1147 |
| 327 | 1147 |
| 326 | 1146 |
| 325 | 1145 |
| 325 | 1145 |
| 324 | 1144 |
| 324 | 1144 |
| 323 | 1143 |
| 323 | 1143 |
| 322 | 1142 |
| 322 | 1142 |
| 320 | 1140 |
| 320 | 1140 |
| 318 | 1138 |
| 318 | 1138 |
| 316 | 1136 |
| 315 | 1135 |
| 314 | 1134 |
| 313 | 1133 |
| 311 | 1131 |
| 311 | 1131 |
| 310 | 1130 |
| 309 | 1129 |
| 309 | 1129 |
| 308 | 1128 |
| 307 | 1127 |
| 307 | 1127 |
| 307 | 1127 |
| 307 | 1127 |
| 306 | 1126 |
| 306 | 1126 |
| 302 | 1122 |
| 300 | 1120 |
| 299 | 1119 |
| 299 | 1119 |
| 297 | 1117 |
| 297 | 1117 |
| 294 | 1114 |
| 293 | 1113 |
| 293 | 1113 |
| 293 | 1113 |
| 292 | 1112 |
| 291 | 1111 |
| 290 | 1110 |
| 290 | 1110 |
| 289 | 1109 |
| 288 | 1108 |
| 288 | 1108 |
| 285 | 1105 |
| 285 | 1105 |
| 285 | 1105 |
| 285 | 1105 |
| 285 | 1105 |
| 285 | 1105 |
| 285 | 1105 |
| 284 | 1104 |
| 284 | 1104 |
| 284 | 1104 |
| 283 | 1103 |
| 281 | 1101 |
| 280 | 1100 |
| 279 | 1099 |
| 279 | 1099 |
| 278 | 1098 |
| 278 | 1098 |
| 278 | 1098 |
| 278 | 1098 |
| 277 | 1097 |
| 276 | 1096 |
| 276 | 1096 |
| 275 | 1095 |
| 275 | 1095 |
| 275 | 1095 |
| 274 | 1094 |
| 274 | 1094 |
| 272 | 1092 |
| 272 | 1092 |
| 272 | 1092 |
| 272 | 1092 |
| 271 | 1091 |
| 271 | 1091 |
| 271 | 1091 |
| 270 | 1090 |
| 270 | 1090 |
| 269 | 1089 |
| 267 | 1087 |
| 266 | 1086 |
| 265 | 1085 |
| 265 | 1085 |
| 265 | 1085 |
| 264 | 1084 |
| 263 | 1083 |
| 263 | 1083 |
| 262 | 1082 |
| 262 | 1082 |
| 261 | 1081 |
| 260 | 1080 |
| 260 | 1080 |
| 259 | 1079 |
| 259 | 1079 |
| 259 | 1079 |
| 258 | 1078 |
| 258 | 1078 |
| 256 | 1076 |
| 255 | 1075 |
| 255 | 1075 |
| 252 | 1072 |
| 251 | 1071 |
| 251 | 1071 |
| 251 | 1071 |
| 249 | 1069 |
| 249 | 1069 |
| 248 | 1068 |
| 247 | 1067 |
| 246 | 1066 |
| 245 | 1065 |
| 244 | 1064 |
| 241 | 1061 |
| 241 | 1061 |
| 241 | 1061 |
| 240 | 1060 |
| 240 | 1060 |
| 238 | 1058 |
| 237 | 1057 |
| 237 | 1057 |
| 236 | 1056 |
| 232 | 1052 |
| 228 | 1048 |
| 224 | 1044 |
| 223 | 1043 |
| 222 | 1042 |
| 219 | 1039 |
| 217 | 1037 |
| 216 | 1036 |
| 216 | 1036 |
| 210 | 1030 |
| 209 | 1029 |
| 208 | 1028 |
| 198 | 1018 |
| 188 | 1008 |
| 175 | 995  |
| 138 | 958  |
  </details>

<details>
  <summary>Heavy Metal</summary>

  | Old  | New  |
|------|------|
| 1305 | 4105 |
| 1289 | 4089 |
| 1280 | 4080 |
| 1275 | 4075 |
| 1266 | 4066 |
| 1263 | 4063 |
| 1254 | 4054 |
| 1249 | 4049 |
| 1248 | 4048 |
| 1245 | 4045 |
| 1241 | 4041 |
| 1231 | 4031 |
| 1230 | 4030 |
| 1228 | 4028 |
| 1224 | 4024 |
| 1221 | 4021 |
| 1221 | 4021 |
| 1219 | 4019 |
| 1211 | 4011 |
| 1210 | 4010 |
| 1210 | 4010 |
| 1208 | 4008 |
| 1207 | 4007 |
| 1205 | 4005 |
| 1200 | 4000 |
| 1195 | 3995 |
| 1195 | 3995 |
| 1192 | 3992 |
| 1188 | 3988 |
| 1187 | 3987 |
| 1186 | 3986 |
| 1183 | 3983 |
| 1181 | 3981 |
| 1179 | 3979 |
| 1176 | 3976 |
| 1175 | 3975 |
| 1171 | 3971 |
| 1170 | 3970 |
| 1167 | 3967 |
| 1166 | 3966 |
| 1165 | 3965 |
| 1159 | 3959 |
| 1158 | 3958 |
| 1157 | 3957 |
| 1155 | 3955 |
| 1154 | 3954 |
| 1152 | 3952 |
| 1152 | 3952 |
| 1146 | 3946 |
| 1146 | 3946 |
| 1146 | 3946 |
| 1142 | 3942 |
| 1140 | 3940 |
| 1140 | 3940 |
| 1140 | 3940 |
| 1137 | 3937 |
| 1129 | 3929 |
| 1129 | 3929 |
| 1126 | 3926 |
| 1125 | 3925 |
| 1124 | 3924 |
| 1118 | 3918 |
| 1116 | 3916 |
| 1113 | 3913 |
| 1108 | 3908 |
| 1107 | 3907 |
| 1107 | 3907 |
| 1107 | 3907 |
| 1105 | 3905 |
| 1105 | 3905 |
| 1105 | 3905 |
| 1102 | 3902 |
| 1102 | 3902 |
| 1095 | 3895 |
| 1093 | 3893 |
| 1092 | 3892 |
| 1090 | 3890 |
| 1090 | 3890 |
| 1088 | 3888 |
| 1088 | 3888 |
| 1084 | 3884 |
| 1084 | 3884 |
| 1083 | 3883 |
| 1079 | 3879 |
| 1075 | 3875 |
| 1075 | 3875 |
| 1075 | 3875 |
| 1074 | 3874 |
| 1072 | 3872 |
| 1071 | 3871 |
| 1071 | 3871 |
| 1067 | 3867 |
| 1067 | 3867 |
| 1066 | 3866 |
| 1065 | 3865 |
| 1065 | 3865 |
| 1061 | 3861 |
| 1060 | 3860 |
| 1060 | 3860 |
| 1059 | 3859 |
| 1056 | 3856 |
| 1056 | 3856 |
| 1052 | 3852 |
| 1051 | 3851 |
| 1049 | 3849 |
| 1049 | 3849 |
| 1048 | 3848 |
| 1048 | 3848 |
| 1046 | 3846 |
| 1045 | 3845 |
| 1045 | 3845 |
| 1045 | 3845 |
| 1043 | 3843 |
| 1043 | 3843 |
| 1043 | 3843 |
| 1043 | 3843 |
| 1042 | 3842 |
| 1042 | 3842 |
| 1041 | 3841 |
| 1036 | 3836 |
| 1035 | 3835 |
| 1034 | 3834 |
| 1028 | 3828 |
| 1027 | 3827 |
| 1027 | 3827 |
| 1024 | 3824 |
| 1023 | 3823 |
| 1023 | 3823 |
| 1023 | 3823 |
| 1022 | 3822 |
| 1020 | 3820 |
| 1019 | 3819 |
| 1018 | 3818 |
| 1017 | 3817 |
| 1017 | 3817 |
| 1016 | 3816 |
| 1015 | 3815 |
| 1014 | 3814 |
| 1013 | 3813 |
| 1013 | 3813 |
| 1012 | 3812 |
| 1012 | 3812 |
| 1011 | 3811 |
| 1010 | 3810 |
| 1007 | 3807 |
| 1006 | 3806 |
| 1005 | 3805 |
| 1002 | 3802 |
| 999  | 3799 |
| 997  | 3797 |
| 996  | 3796 |
| 995  | 3795 |
| 992  | 3792 |
| 992  | 3792 |
| 991  | 3791 |
| 989  | 3789 |
| 989  | 3789 |
| 986  | 3786 |
| 986  | 3786 |
| 986  | 3786 |
| 986  | 3786 |
| 986  | 3786 |
| 985  | 3785 |
| 982  | 3782 |
| 982  | 3782 |
| 981  | 3781 |
| 978  | 3778 |
| 977  | 3777 |
| 977  | 3777 |
| 974  | 3774 |
| 974  | 3774 |
| 972  | 3772 |
| 972  | 3772 |
| 972  | 3772 |
| 971  | 3771 |
| 968  | 3768 |
| 968  | 3768 |
| 968  | 3768 |
| 967  | 3767 |
| 966  | 3766 |
| 965  | 3765 |
| 965  | 3765 |
| 964  | 3764 |
| 964  | 3764 |
| 963  | 3763 |
| 963  | 3763 |
| 962  | 3762 |
| 961  | 3761 |
| 960  | 3760 |
| 960  | 3760 |
| 959  | 3759 |
| 959  | 3759 |
| 958  | 3758 |
| 957  | 3757 |
| 956  | 3756 |
| 955  | 3755 |
| 955  | 3755 |
| 955  | 3755 |
| 954  | 3754 |
| 954  | 3754 |
| 953  | 3753 |
| 953  | 3753 |
| 947  | 3747 |
| 946  | 3746 |
| 945  | 3745 |
| 942  | 3742 |
| 942  | 3742 |
| 942  | 3742 |
| 941  | 3741 |
| 941  | 3741 |
| 941  | 3741 |
| 940  | 3740 |
| 940  | 3740 |
| 939  | 3739 |
| 938  | 3738 |
| 938  | 3738 |
| 938  | 3738 |
| 935  | 3735 |
| 935  | 3735 |
| 934  | 3734 |
| 933  | 3733 |
| 932  | 3732 |
| 931  | 3731 |
| 931  | 3731 |
| 929  | 3729 |
| 928  | 3728 |
| 927  | 3727 |
| 926  | 3726 |
| 925  | 3725 |
| 923  | 3723 |
| 923  | 3723 |
| 922  | 3722 |
| 921  | 3721 |
| 921  | 3721 |
| 920  | 3720 |
| 919  | 3719 |
| 919  | 3719 |
| 918  | 3718 |
| 917  | 3717 |
| 916  | 3716 |
| 916  | 3716 |
| 915  | 3715 |
| 914  | 3714 |
| 914  | 3714 |
| 911  | 3711 |
| 911  | 3711 |
| 911  | 3711 |
| 911  | 3711 |
| 908  | 3708 |
| 907  | 3707 |
| 907  | 3707 |
| 907  | 3707 |
| 904  | 3704 |
| 904  | 3704 |
| 903  | 3703 |
| 903  | 3703 |
| 895  | 3695 |
| 892  | 3692 |
| 892  | 3692 |
| 891  | 3691 |
| 889  | 3689 |
| 888  | 3688 |
| 888  | 3688 |
| 887  | 3687 |
| 887  | 3687 |
| 886  | 3686 |
| 885  | 3685 |
| 885  | 3685 |
| 883  | 3683 |
| 882  | 3682 |
| 882  | 3682 |
| 881  | 3681 |
| 880  | 3680 |
| 879  | 3679 |
| 879  | 3679 |
| 878  | 3678 |
| 878  | 3678 |
| 876  | 3676 |
| 876  | 3676 |
| 875  | 3675 |
| 875  | 3675 |
| 875  | 3675 |
| 874  | 3674 |
| 872  | 3672 |
| 868  | 3668 |
| 868  | 3668 |
| 868  | 3668 |
| 866  | 3666 |
| 866  | 3666 |
| 865  | 3665 |
| 865  | 3665 |
| 863  | 3663 |
| 863  | 3663 |
| 861  | 3661 |
| 860  | 3660 |
| 859  | 3659 |
| 859  | 3659 |
| 859  | 3659 |
| 858  | 3658 |
| 858  | 3658 |
| 856  | 3656 |
| 856  | 3656 |
| 856  | 3656 |
| 855  | 3655 |
| 854  | 3654 |
| 853  | 3653 |
| 849  | 3649 |
| 849  | 3649 |
| 848  | 3648 |
| 843  | 3643 |
| 839  | 3639 |
| 834  | 3634 |
| 829  | 3629 |
| 828  | 3628 |
| 824  | 3624 |
| 823  | 3623 |
| 821  | 3621 |
| 816  | 3616 |
| 815  | 3615 |
| 815  | 3615 |
| 812  | 3612 |
| 812  | 3612 |
| 811  | 3611 |
| 811  | 3611 |
| 810  | 3610 |
| 809  | 3609 |
| 806  | 3606 |
| 804  | 3604 |
| 802  | 3602 |
| 801  | 3601 |
| 801  | 3601 |
| 801  | 3601 |
| 800  | 3600 |
| 800  | 3600 |
| 799  | 3599 |
| 798  | 3598 |
| 795  | 3595 |
| 794  | 3594 |
| 792  | 3592 |
| 792  | 3592 |
| 791  | 3591 |
| 791  | 3591 |
| 790  | 3590 |
| 790  | 3590 |
| 786  | 3586 |
| 785  | 3585 |
| 785  | 3585 |
| 783  | 3583 |
| 782  | 3582 |
| 782  | 3582 |
| 782  | 3582 |
| 781  | 3581 |
| 780  | 3580 |
| 779  | 3579 |
| 775  | 3575 |
| 775  | 3575 |
| 772  | 3572 |
| 771  | 3571 |
| 770  | 3570 |
| 769  | 3569 |
| 768  | 3568 |
| 767  | 3567 |
| 765  | 3565 |
| 763  | 3563 |
| 761  | 3561 |
| 757  | 3557 |
| 755  | 3555 |
| 753  | 3553 |
| 753  | 3553 |
| 749  | 3549 |
| 743  | 3543 |
| 733  | 3533 |
| 722  | 3522 |
| 722  | 3522 |
| 721  | 3521 |
| 719  | 3519 |
| 718  | 3518 |
| 714  | 3514 |
| 713  | 3513 |
| 705  | 3505 |
| 702  | 3502 |
| 695  | 3495 |
| 694  | 3494 |
| 694  | 3494 |
| 689  | 3489 |
| 688  | 3488 |
| 675  | 3475 |
| 675  | 3475 |
| 674  | 3474 |
| 656  | 3456 |
| 650  | 3450 |
| 640  | 3440 |
| 615  | 3415 |
  </details>

If this all looks good, I'll go ahead and make the changes and PR it. 

My spreadsheet if anyone wants to play around with values themselves or see in more detail how I came up with these:
[commodities.xlsx](https://github.com/endless-sky/endless-sky/files/9039626/commodities.xlsx)

**Comment by Hecter94** [comment]
> I don't think we should necessarily tie commodity prices to minable prices, as that would mean that changing one would require us to change the other, and the balance of minables and the balance of commodities are two wildly different ecosystems. I also don't think that heavy metals should be so far and above the other commodities.

Okay, sounds reasonable to me. Should this issue be closed in that case?

**Comment by TheGiraffe3** [comment]
> Should this issue be closed in that case?

This question still stands.

**Comment by Hector-of-the-Void** [comment]
yes, please close the case.
