### ISSUE TITLE
Have mass expansions and cargo expansions remove each other

### ISSUE THREAD

**Issue by Bladewood** [endless-sky/endless-sky#642]
Minor nitpick (that doesn't really matter, since we're all rich and fast enough). Have 1 mass expansion installed, -50000 credits, +15 outfit space, -20 cargo space, +5 mass. Then, install 1 cargo expansion. -20000 credits, -15 outfit space, +20 cargo space, +5 mass. Totals at -70000 credits, 0 space, 0 space, 10 mass. I suggest that if you have a mass expansion and buy a cargo expansion, it uninstalls the mass expansion and there is no cargo expansion.
Or something.

**Comment by asl97** [comment]
your stat is wrong

Item | Credits | Outfit | Cargo | Mass
----- | --------- | ------- | -------- | -------
Mass Expansion | 50000 | 15 | -20 | 5
Cargo Expansion | 30000 | -20 | 15 | 5
Total | 70000 | -5 | -5 | 10

https://github.com/endless-sky/endless-sky/blob/1733ec00b7258d49e1dab218e1491f2eee162e8f/data/outfits.txt#L197

**Comment by endless-sky** [comment]
There's no other outfit that works this way (installing one uninstalls another), so I think doing this would just add confusion for most people, rather than simplifying things. (Plus, in the future there may be other mass expansions of other sizes; there's no guarantee they will always be exactly paired off with opposite effects.)

**Comment by frameworld** [comment]
Also, what if I'd like to keep some? Not all outfitters sell them.
