### ISSUE TITLE
Killing shot appears after NPC death dialogue

### ISSUE THREAD

**Issue by pilover100** [endless-sky/endless-sky#6475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using a weapon such as the dragonflame cannon to kill an NPC, the dialogue box appears before the shot is even made.

### Steps to Reproduce

* Accept a mission with a NPC to kill
* Damage the NPC enough so that you can 1-shot-kill it
* kill it using one shot (i.e. by using the dragonflame cannon)
* observe the dialogue box opening before the shot is fired

### Expected Behavior

the dialogue box appears after the shot is made (just wait a single frame even so it looks like it's happened?) which destroys the ship

### Screenshots

See video below:
[Video: https://1drv.ms/u/s!AhEogbCmotiYg5NMZhqqfxDjbcSKbQ?e=mGWTjk](https://1drv.ms/u/s!AhEogbCmotiYg5NMZhqqfxDjbcSKbQ?e=mGWTjk)

### Link to save file

Doesn't matter particularly which save file you use but here's mine:
[Save File: Elijha Letney.txt](https://github.com/endless-sky/endless-sky/files/7837516/Elijha.Letney.txt)

### Operating System

Windows 10 Home

### Game Source

GitHub Releases

### Game Version

Commit af34cc82e9e4c5eaaec96ff2bc5f6752f2d2fa32

### Additional Information

Was originally posted on discord: https://discord.com/channels/251118043411775489/536900466655887360/929769563770466335

**Comment by tehhowch** [comment]
The shot was fired and the NPC killed before the dialog opened -- you can clearly observe that the the target reticle shows the NPC has no shields and no hull. The NPC executed its movement instructions already that frame, in which it decided to thrust, which is why the flares are drawn for it (collisions are performed after all ships move; one could probably add a "is this destroyed? don't draw flares for it" check to handle this single-frame discrepancy but it's not critical IMO).

The reason for the visual delay is that this particular weapon has a lifetime of 1 and does not have a sprite _at all_; it uses the effects system to simulate having a sprite.

https://github.com/endless-sky/endless-sky/blob/1cf4239517bf645dd4dbf723ac392ea6ed02b2d1/data/sheragi/sheragi%20outfits.txt#L146-L173

The effect system has a slight delay in rendering relative to things like sprites because of how the game's computation & rendering is architected -- while determining what happened, we collect what new things should be added. We do this is in a background thread. When it is safe to do so, we push those things to the draw thread.

FWIW I think the dialog may be appearing a step early -- 1fb3549 added an additional "render added panel" instruction to the UI sequence that I meant to double-check:
https://github.com/endless-sky/endless-sky/blob/1cf4239517bf645dd4dbf723ac392ea6ed02b2d1/source/UI.cpp#L103-L104

It's possible removing those would fix the issue; I or someone else can recompile without those lines to verify.

**Comment by Zitchas** [comment]
Just an idea: I've always found it a little anti-climatic in big battles that I put all that work into killing my target, and then the dialog pops up the *instant* the ship reaches 0 and starts to explode. I'd be much more cinematic if the dialog didn't appear until the ship actually finished exploding.
(also, it'd feel better too, since then the dialog would appear when I have visual confirmation that the ship is, indeed, obliterated. This isn't the case when the ship is just on the very first frame of death.)

**Comment by Ben-Wise** [comment]
> The effect system has a slight delay

Ah... so that's what it is! Ok I see now (as simple as the shot has been made it's just not made it to the visual update yet).
But yes, I always find it interesting that as soon as you've depleted health to 0 the death dialogue comes up even when the ship is still around.

**Comment by tehhowch** [comment]
While one may be able to special-case the success condition for `npc kill` by watching some property on the ship model, conversations or dialogs that result from a disabling shot cannot be handled similarly.

**Comment by quyykk** [comment]
> It's possible removing those would fix the issue; I or someone else can recompile without those lines to verify.

I removed the lines and the issue persists.

At first I thought that the delay you mentioned was the `visual` `newVisuals` thing, but it appears that `newVisuals` are still drawn immediately so the effect should still appear. As far as I can understand the Step function of Engine waits for the computation thread so there shouldn't be a delay. Is this correct?

**Comment by Zitchas** [comment]
For a different but very similar visual discrepancy: Killing a target using a nuclear missile. I was just testing out the new visual effects on some raider bounties, and I noticed that the "you have killed your target" dialog pops up *before* the nuke's own explosion shows up. As best I can tell, the damage is done the instant the nuclear missile's explosion is triggered, and thus the ship is killed in that frame, then the dialog triggers, and the visual explosion starts in the frame afterwards. 

The more I play, the more I see this happen, and the more it bugs me. lol. And all these years I just never really noticed...

**Comment by Zitchas** [comment]
Definitely, the more I play, the more I see this happen.

Here's a case where I killed a Raider using a nuclear missile. Note that - at the time I get the dialog box - the Raider is still firing thrusters and shooting at me. The nuclear missile is also visible right near the Raider under the beam. Basically this dialog box appears to have triggered at the exact moment that the missile reached its proximity perimeter and decided it was time to blow up and inflict the damage. So from a player perspective here, it doesn't even appear to be waiting for the first frame of the explosion; but merely for the point when the game has decided that an explosion is going to happen and it has figured out that the Raider will be caught in said explosion.

![Raider not quite destroyed](https://user-images.githubusercontent.com/32169904/150796205-7a1dde36-c683-4b72-86da-ffee2c078fca.PNG)

**Comment by quyykk** [comment]
I fixed this bug by coincidence while working on another PR lol. Also seems to apply to the thrusters-still-firing case as well. Some screenshots. The second one is a nuke (the one that just got merged).

![dragonflame-dialog](https://user-images.githubusercontent.com/85879619/151096194-058f47fb-b61e-4069-8d6e-57cfa8981520.png)
![nuke-dialog](https://user-images.githubusercontent.com/85879619/151096208-2dd7136b-d50c-4ba4-bfba-25a94901eac4.png)
