### ISSUE TITLE
Give dramatically out-manned crew ability to jettison themselves

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#655]
So I have a fully supped up bactrian with almost or at 400 passenger space. I get bored and decide I want to take a ship with 50 crew. That crew must be made of the bravest men in the world. They fought me to the death and I still didn't lose a single man. Maybe let them jettison themselves for the sake of realism and non-brutality (after you have over 3x, 4x their crew, or there defense is measurably lower than your offense?)(Would only be an option if in a system with a habitable planet/station)

**Comment by lor1113** [comment]
Interesting idea, but makes capping only that more OP, which is not what we want

**Comment by Pointedstick** [comment]
If they have laser rifles and defense stations, maybe they're not the bravest folks in the galaxy. And maybe you'd fight to the death too if you were cornered and your home was threatened by violent invaders. I hope you would.

**Comment by erprice** [comment]
You could flee in escape pods, but those are most likely going to take up outfit space. And some min/maxing captain is bound to drop them in favor of getting an extra gun or a little bit bigger battery.

So failing that, you might choose to surrender and throw yourself on the mercy of your captors. Does the capturing ship have space for prisoners? Are they gonna take the time to drop you off on a hospitable planet? Maybe impress you into their own crew? Maybe sell you into slavery on some pirate world?

**Comment by bobafetthotmail** [comment]
Yeah, go cap Interceptors. 400 men boarding a ship that has 4 crew, outnumbered 100 to one!!!!! FIGHT!!!!!

Seriously, it makes more sense for them to scuttle the ship when you board it (killing off a good chunk of your boarders) than to fight to the death.

>"maybe you'd fight to the death too if you were cornered and your home was threatened by violent invaders. I hope you would."

If victory isn't possible at all, suicide is a better choice than dying in battle.
There is no honor in getting slaughtered anyway.

**Comment by Nightmareman** [comment]
@thenerdfreak 
Escape pods would be a fine idea but I also like the other ideas that have been posted regarding boarding in the many many other threads regarding boarding.
1)Enemy crew should be capturable and against vast numbers there should be a chance of them outright surrendering. You should be able to choose the fate of those you capture whether to hold them prisoner to later release or sell as slaves, impress them into your own crew, kill them ect. In many games where pirating is one of the main themes this is how it is done.
2)More types of boarding weapons would be nice with each one changing how likely members of enemy crew are to be captured, obviously things like nerve gas are going to have low chance of capture as they are probably going to be dead rather then just incapacitated from injury or whatever.

@bobafetthotmail 
I have had this conversation many times with you regarding the self-destruct but I am willing to have it again. Scuttling the ship is a silly idea and once again I will tell you why. 
1)The ship is crippled and the reactor is offline along with almost every other system hence why no energy production so in the short amount of time it would take to capture the ship they aren't going to be able to rig the ship to explode. The crew will likely be help up in the cic, bridge whatever you want to call it preparing for you actually boarding them while praying you ether leave them alone or just take some components/cargo ect. then leave so they can be picked up at a later time by someone else.
2)The instinct for self-preservation is one of the strongest impulses humans have even in properly trained spies and military you will have a hard time finding someone who will willingly commit suicide by their own hand, its not like in movies and books where every single ship captain is willing to kill themselves and crew at the first sign of capture. Even among highly trained spies they rarely commit suicide even though they are trained for that, they just can't bring themselves to do it. Most would choose surrender against overwhelming odds or fight as hard as they can to try and live and die in battle rather then suicide. Only types of people who would willingly kill themselves in this type of situation are the crazy zealot types, the clinically insane, and those who are just so spiteful about having lost because of their pride they rather everyone die. So unless they add a new faction in the game that is composed of 100% zealots following some religion or some other cause I see no reason for a self-destruct to be added.
3) It would just make the game worse to have ships you board self-destruct that alone would probably detract enough from the fun of the game I would stop playing or edit that feature out so its not something that should be added to the main game perhaps an optional plug-in.
4)The death benefits alone as they currently work are annoying enough when it comes to ship capture we don't need anything else that makes it less profitable or fun. Honestly I pray for the day when its changed so I can actually make a decent profit if I decide to capture a large ship.

**Comment by Pointedstick** [comment]
> If victory isn't possible at all, suicide is a better choice than dying in battle. There is no honor in getting slaughtered anyway.

It's always interesting to meet people with different views, because I feel like if a battle is inevitable but victory is impossible, dying in battle is a *vastly* preferable outcome to suicide.

**Comment by bobafetthotmail** [comment]
Thinking a bit more about it (while writing the answer to the quote below), I find VERY strange that ships in an universe where pirates/battles are so common don't have any kind of escape shuttles/pods/whatever to avoid such bad fate.
Are crewmen so desperate? Are captains so reckless?

Having "escape pods" (not as an outfit but as an integral part of the ship's hull) would allow jobs like this:
"go recover X escape pods from sector Y" (while avoiding pirates that try to nibble on you)

And allow getting hails from pods in systems saying "hey friendly traveler come pick us up!" (with or without payment for it)

And also a last-chance of survival for the player, that lives on in his escape pod until he finds someone that can carry him to the nearest shipyard.

Escape pods should be pretty damn small and fast, and should also be non-targetable for the first 5-10 seconds after being spawned (to avoid being destroyed by the same ships that are destroying the ship they came from while zipping away to escape from it)

>"It's always interesting to meet people with different views, because I feel like if a battle is inevitable but victory is impossible, dying in battle is a vastly preferable outcome to suicide."

Oh, I would love too to "die in battle", like shown in movies. With a clean shot to vitals causing near-instant death. Maybe even shouting something cool while looking at the eyes of the enemy with my best "macho man" face and planting some doubt in his mind with my last breath. 
Point is, that it is not how it goes.

Most of the times you get incapacitated by stuff you did not even see coming (usually shrapnel or stray bullets) while not in sight of anyone but your comrades (if they are still alive after the fact) and die after a long-ish painful agony, assuming the enemy does not find you and torture you while you are still agonizing.

Any hunter can also confirm this. Most times the animal must be "finished" after it has been incapacitated.

This of course applies firstly to "doing your damn best to avoid getting into that situation at all", because I'm not terribly attracted by death in general.
