### ISSUE TITLE
more shield types

### ISSUE THREAD

**Issue by unjown** [endless-sky/endless-sky#6554]
### Problem Description

More variety of shield type.

### Related Issue Links

none found

### Desired Solution

some shield will take less damage(more resistant) to missile or lasers, etc.

### Alternative Approaches

N/A

**Comment by Zitchas** [comment]
While we don't have any ability to differentiate between general damage types currently, we do have both protection and resistance attributes for every damage type (thanks to Amazinite's efforts). So while we can't currently make a shield that is better against lasers than against blasters; we *can* make a shield that is better against heat damage, or one that resists force. So that's a possibility. Plug-in creators could (and in some cases are) making use of these to create wider variety of ships.

**Comment by tehhowch** [comment]
Please ensure you devote as much time and sincerity to filling out the template as you'd like others to devote when considering your request.

**Comment by unjown** [comment]
> Please ensure you devote as much time and sincerity to filling out the template as you'd like others to devote when considering your request.

ok noted thx

**Comment by unjown** [comment]
> While we don't have any ability to differentiate between general damage types currently, we do have both protection and resistance attributes for every damage type (thanks to Amazinite's efforts). So while we can't currently make a shield that is better against lasers than against blasters; we _can_ make a shield that is better against heat damage, or one that resists force. So that's a possibility. Plug-in creators could (and in some cases are) making use of these to create wider variety of ships.

ah okok 

would a heat shield or a "usable special coating"(an usable item) that could lessen the effect of heat damage be possible?

**Comment by petervdmeer** [comment]
> would a heat shield or a "usable special coating"(an usable item) that could lessen the effect of heat damage be possible?

Yes, I believe that this is already possible with the current code-base.

**Comment by petervdmeer** [comment]
Closing this issue; we recently had a lot of PRs that added new damage and resistance types, so I consider this PR done.
(If you have more explicit ideas for new damage types, then please mention them explicitly in a PR.)
