### ISSUE TITLE
Suggestion: Killing enough unfettered hai causes them to let you buy their ships (I'm assuming this makes you more friendly with the wanderers)

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#658]
So I tried killing a bunch of unfettered hai to see if it affected the wanderer's landing requirements (still in the process of doing this) and wondered if this would be an effective way to introduce the wanderer's ships to the player (since you literally can't capture one and put a jump drive on it, as capturing a single ship makes all of wanderer space hostile)

**Comment by endless-sky** [comment]
I've already got an outline of the beginning of a Wanderer story arc (at least, enough to get you to the point where most of their ships are for sale). It's just a matter of me finding time to write it.

Killing the Unfettered does not alter your reputation with the Wanderers. In terms of story, the implication is that the Wanderers fight back through self-defense, but are not actually too thrilled at the thought of Unfettered Hai losing their lives.

**Comment by thenerdfreak** [comment]
I can understand that. They seem the type

**Comment by jamaican117** [comment]
I captured a Deep Sky relatively easy. I have a single Bactrian with the cloaking device and plenty of hyperspace fuel/catalytic ramscoops. Basically when the Unfettered are fighting in one of the Wanderer Systems select the ship you want, take it down, board, and cap before getting blown to bits. Soon as you cap it cloak and jump. Jump back to the ship and land on the planet in the system. Put a spare jump drive in the ship and you are done!

**Comment by thenerdfreak** [comment]
The issue is as soon as I take any ships of theirs, they're hostile and I can't land on any of their planets

**Comment by frameworld** [comment]
I think there is a REAL problem with peoples not understanding or being able to translate correctly the word "unfettered". It might be obvious to native speakers, but … this game may need a bit more manual pages ingame, link-showcase triggered by words.

http://tvtropes.org/pmwiki/pmwiki.php/Main/TheUnfettered tells clearly that "unfettered" means they have 1 single goal and sacrifice anything for this single goal.
With the sole exception that a sacrifice of something else reduces the chances of archiving it (by drawing attention, losing allies which are considered required, etc). They might also appear dumb because they think most of their time about archiving this single goal, not about how others or other things might help to archive it (except this hint is obvious).

**Comment by johndh** [comment]
The word "unfettered" means free from restraints, bonds, inhibitions, etc.  Some good synonyms include unchained and liberated.  It's pretty clear to me that they view their neighbors' civility as a crippling weakness that they themselves are not subjected to.  In their eyes, they've thrown off their shackles and are free to choose their own destiny, while the other Hai see them as misguided children who earn their pity.  When you do the tribute missions, the regular Hai say things like "this is so much better than letting our brethren starve".

**Comment by endless-sky** [comment]
There's now a way to earn access to most Wanderer ships by completing missions. (ab449c0)

**Comment by jamaican117** [comment]
I can assume that means we are continuing the Wanderer storyline?

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
