### ISSUE TITLE
Remnant: Arriving in spaceport with broken jump drive does not trigger a mission

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#6606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was doing some testing with a new pilot in remnant space. I fought several raiders and carried broken jump drives in cargo. The normal mission for prompting to on broken jump drives did not trigger for me. I tried all three space ports and at one point had 3 broken drives in cargo. I had recently updated my continuous build. I refreshed again from the launcher and got the same results.

### Steps to Reproduce

Land on any space port with the attached save file. Jump drives are in cargo.

### Expected Behavior

I expected a mission prompt to ask me if I wanted to talk to someone about the drive which would then direct me to the information desk.

### Link to save file

[Fred Flintstone.txt](https://github.com/endless-sky/endless-sky/files/8248192/Fred.Flintstone.txt)

### Operating System

Linux EmberWastrel-8088i 5.16.14-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:18 UTC 2022 x86_64 GNU/Linux

### Game Source

ESLauncher2

### Game Version

ndless Sky commit a0c92ee2d52c719c5edab429d5d6905fc5a8a3f6

**Comment by waterhouse** [comment]
I've hit the same thing, in commit 2380cdfd9b4aae12ef9976dbab0f15b0a2649b6a (March 19).  My own savefile:

[Deepak Chopra broken jump drive test.txt](https://github.com/endless-sky/endless-sky/files/8347027/Deepak.Chopra.broken.jump.drive.test.txt)

I looked into the mission in question:
```
mission "Remnant: Broken Jump Drive 1"
        repeat
        minor
        landing
        name "Broken Jump Drive Delivery"
        description "You have been asked to deliver a broken jump drive to the researchers on <planet>."
        to offer
                has "remnant: blood test pure"
                not "Remnant: Broken Jump Drive 1: active"
                not "Remnant: Broken Jump Drive 1: done"
        source
                government "Remnant"
                attributes outfitter
        destination
                government "Remnant"
                attributes outfitter
                not distance 0
        on offer
                require "Jump Drive (Broken)"
                conversation
                        branch repeated
                                has "Remnant: Broken Jump Drive 1: offered"
                        `As the <ship> settles onto its designated landing pad, you see someone emerge from the nearby outfitter and quickly make their way to you. The man waits a safe distance before approaching once you cycle the hatch and disembark. "Greetings, Captain <last>," trills the Remnant, "we saw the news that the newcomer among us was tracking down an erratic Korath ship. When you came in to land, we saw on the scans that you salvaged its malfunctioning jump drive. Could we take it to study?"`
...
```
I tried removing various of the conditions to see if that let me trigger the mission.

Ultimately, I found that removing the "minor" attribute was the key.  When I edit the data file to remove it, then, the next time I leave and land, I get offered the mission.  When I put "minor" back and reload a copy of the old pilot, then leaving and landing leads to no missions being offered.

Using git blame, I found that the "minor" attribute had been added in this commit:
```
commit b70e1afc031503f88d632968adae5d70245234d9
Author: Amazinite <jsteck2000@gmail.com>
Date:   Sat Feb 12 18:09:29 2022 -0500

    revert: Don't warn about missions that are both landing and minor
    
    This commit reverts part of 36cc1d9.
```
That probably explains the chronology of the bug.

The thing is... The "minor" attribute is documented thus:
```
        // Check if this mission is a "minor" mission. Minor missions will only be
        // offered if no other missions (minor or otherwise) are being offered.
```
Yet I'm being offered _zero_ missions when I land.  There should be nothing that interferes with the jump drive mission.  I don't think the mission data file should be causing this behavior.  Yet it is.

The "minor" property seems to be used in exactly one place in the codebase (minus it being copied around):
```
        else if(availableMissions.size() > 1)
        {
                // Minor missions only get offered if no other missions (including other
                // minor missions) are competing with them. This is to avoid having two
                // or three missions pop up as soon as you enter the spaceport.
                auto it = availableMissions.begin();
                while(it != availableMissions.end())
                {
                        if(it->IsMinor())
                        {
                                it = availableMissions.erase(it);
                                if(availableMissions.size() <= 1)
                                        break;
                        }
                        else
                                ++it;
                }
        }
```
Which seems like it fits the documented description... assuming that "availableMissions" consists of missions that actually get offered to you.  My hypothesis is that there is some "available mission" that ends up being silent.

Time for some printf debugging...
```
@@ -2712,6 +2712,9 @@ void PlayerInfo::CreateMissions()
                {
                        if(it->IsMinor())
                        {
+                         printf("IGNORING %s WHEN %s IS AT FRONT\n",
+                     it->Name().c_str(),
+                     availableMissions.front().Name().c_str());
                                it = availableMissions.erase(it);
                                if(availableMissions.size() <= 1)
                                        break;
@@ -2719,6 +2722,8 @@ void PlayerInfo::CreateMissions()
                        else
                                ++it;
                }
+        printf("LEFT WITH %s\n",
+               availableMissions.front().Name().c_str());
        }
```
And we see:
```
IGNORING Broken Jump Drive Delivery WHEN Broken Jump Drive Delivery IS AT FRONT
IGNORING Investigate Ivan WHEN Investigate Ivan IS AT FRONT
IGNORING Learn Remnant Sign WHEN Learn Remnant Sign IS AT FRONT
LEFT WITH z Spaceport Reminder Resetter
```
Ok, what's that?
```
# Use of "z" at the start of the mission name is to make it offer only if no other missions have.
mission "z Spaceport Reminder Resetter"
        minor
        invisible
        repeat
        to offer
                not "chosen sides"
                not "Spaceport Reminder: offered"
        on offer
                "spaceport reminder year" = "year"
                "spaceport reminder month" = "month"
                fail
```
Added Mar 12:
```
commit eb864d5f841b2971d35211564c8d5c7da04f9143
Author: Anarchist2 <60202690+Anarchist2@users.noreply.github.com>
Date:   Sat Mar 12 09:14:31 2022 +1000

    feat(content): Add a mission that reminds new pilots to check the spaceport (#6595)
```
And ... then we see this on Mar 21:
```
commit 044aa83263fe73679fb597a49fbb972e0bda303d
Author: Anarchist2 <60202690+Anarchist2@users.noreply.github.com>
Date:   Mon Mar 21 01:20:08 2022 +1000

    fix(content): Correct spaceport reminder resetter evaluation order (#6636)
```
Dammit, did I pick the wrong 9-day period to choose a git revision?
Cherry-picking that commit and re-running... I leave and land several times, and I get, in order, (a) nothing, (b) the "Learn Remnant Sign" mission, (c) the "Investigate Ivan" mission, and (d) the "Broken Jump Drive Delivery" mission.

Ok, looks like this issue is likely fixed by #6636 .  @williaji , try again on a version containing 044aa83263fe73679fb597a49fbb972e0bda303d and see if it's fixed?

**Comment by Zitchas** [comment]
So the spaceport reminder mission is silently blocking minor missions? That's problematic.

**Comment by quyykk** [comment]
Not anymore since #6636 was merged.
