### ISSUE TITLE
Mission to meet Ivan in Valhalla disappears after landing.

### ISSUE THREAD

**Issue by Galabar001** [endless-sky/endless-sky#6637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When landing on Valhalla, the following mission disappears (there is no dialog shown when landing):

mission "Deep: Remnant: Continue Research"
	name "Travel to Valhalla"
	uuid 20000000-0100-0000-0000-000001000000
	description "Meet up with Ivan on Valhalla in the Epsilon Leonis system to continue helping with research on the Ember Waste."
	to offer
		"event: deep: remnant: rest period" != 0
		"deep: did reveal remnant" != 0
	destination Valhalla
	on offer
		conversation
			label 0
			`You receive a message from Ivan, the Deep scientist who you helped to discover the Remnant in the Ember Waste. "Captain <last>, it's been so long. The Deep has finally finished reviewing our research in the Ember Waste, and we've been approved for further funding! Please meet us on Valhalla in the Epsilon Leonis system if you wish to assist us again. Your help would be appreciated, but we will make progress even if you're unable to help."`
				goto 1
			label 1
			choice
				"	(Accept.)"
					accept
				"	(Decline.)"
					decline

### Steps to Reproduce

Pick up the above mission (I've included the save file so that you can travel to Valhalla).

### Expected Behavior

I'm assuming some sort of dialog should take place when landing on Valhalla.

### Link to save file

[Galabar Gilleo.txt](https://github.com/endless-sky/endless-sky/files/8313824/Galabar.Gilleo.txt)

### Operating System

MacOS

### Game Source

GitHub Releases

### Game Version

2022-03-20 18:52 UTC

**Comment by Eboy147** [comment]
Hello there, I am having the same issue on this mission. When I land on Valhalla, the mission disappears without dialogue. I am also on MacOS. I am pretty far down the Remnant storyline, so if this is supposed to be unavailable, then that is good to know.

**Comment by Davidb2373** [comment]
Hello I know this is fairly old but I'd just like to add that this issue is still present. I believe when I got to the ship unlock for the remnant scientist missions that was as far as the current content was when I completed those event chains. 

Recently got back into the game using the same save and this is the only issue I've had with my old save file. Want to confirm that I can just land on valhalla and ignore this and carry on or should I keep the mission in the list waiting for a patch? May not need to visit valhalla again but I'm unsure if I'll run into another mission that requires landing there that isn't a generic transport, cargo or etc mission.

**Comment by warp-core** [comment]
Looking at @Galabar001's save file, it looks like they've already done the missions they would get after completing hte active mission pointing to Valhalla.
This mission was added relatively recently, presumably after you did all the other missions.
I'm going to guess the same thing has happened for @Eboy147 and @Davidb2373. You don't need to keep this mission around; you've already done the missions it would unlock.
