### ISSUE TITLE
Use of Creative Commons "noncommerical" licenses

### ISSUE THREAD

**Issue by throwaway1037** [endless-sky/endless-sky#6659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are numerous proprietary files, as listed in `copyright`; any -NC license is proprietary.

### Steps to Reproduce

Search the `copyright` file for "-NC".

### Expected Behavior

No proprietary files should be included in Endless Sky, since it is (meant to be) a libre game.
All proprietary files should ideally be replaced, but it is also acceptable to remove them.
In the worst case scenario in which case they are kept, please may a build-time option be added to omit all proprietary files so as to make a 100% libre build of the game?

### Operating System

This bug affects all systems

### Game Source

Built from source

### Game Version

Bug spotted in 0.9.14

### Additional Information

This bug also affects the `-high-dpi` repo.

**Comment by MCOfficer** [comment]
I take it this is an ideological issue, not a legal one.

That being the case, I for one am fine with having `-NC` licensed assets. This project will never go commercial anyways, and should any fork wish to do so they are free to replace those file.

**Comment by throwaway1037** [comment]
I agree the issue is ideological, not legal, but that does not make it any less important.

The discovery of these files will have a massive knock-on effect on not only Endless Sky itself, but many other projects.
Firstly, Endless Sky can no longer call itself "free" (as in freedom), "libre", or "open-source", because the inclusion of proprietary files means the project as a whole is not any of these things.
Secondly, operating system distributions will have to change the packaging of Endless Sky.
Some will have no move it to a nonfree repo, and the systems which have policies which respect user freedom and as such include no proprietary files will either have to spend time removing or replacing the proprietary files, or perhaps even remove Endless Sky entirely, or at least temporarily, whilst that work is underway.

The issue of whether Endless Sky wishes to go commercial or not misses the point; projects have a moral duty to respect user freedom, and as such should not include proprietary files.

Also, the use of the term ["assets"](https://gnu.org/philosophy/words-to-avoid.html#Asstes) implies that works only have commercial value to society, which especially since you say ES is not planning on going commercial, is silly since the motivation behind ES is not financial, but something more akin to helping others and improving society by developing a libre game for all to play.

**Comment by Zitchas** [comment]
I am admittedly not a lawyer, but there is, as far as I am concerned, a pretty big gap between "can be distributed for free by anyone, with the source code fully available, just a few pieces of it cannot be **sold**, and "proprietary closed source software"

We have some, admittedly very few, contributors who don't want someone else to monetarily profit of their work. While this does admittedly impinge on the "tolerate no restrictions, freedom must be absolute" level of freedoms, it does enable and protect people who may legally not be allowed to contribute to a project that may be used for commercial gain. (The project founder was, I believe, under such contractual obligations for a while, possibly still)

Anyway, while I can't speak to the legal definitions of libre, the presence of NC for should not have any impact on the "free" or "open source" designations.

Likewise, potentially "inflicting" a few files on someone that they can't sell seems like a very low level of harm. To the point of not actually existing at all. This is not disastrous by any means.

**Comment by Amazinite** [comment]
The sound files are unused and could easily be removed, although I only see three, not six. The jpegs were only added a couple months ago when we removed all duplicate landscape images and could therefore simply just be replaced again.

**Comment by Zitchas** [comment]
Also worth noting that the primary distribution and user base is via Steam, which is clearly not libre, or open source. 

So a hard rule insisting on libre files seems both hypocritical and a car of unduly restricting content for no reason. Especially when the only apparent gain is it makes it easier for someone to commercialize our work. Framed like that, I would be more inclined to blanket the whole project with a NC label, rather than prohibit it.

**Comment by throwaway1037** [comment]
@Zitchas, whilst there is a spectrum of how restrictive proprietary files are, the files I pointed out are still proprietary, even though they may be towards the less restrictive end, and as such will still have the knock-on effects I mentioned.

You mention that some people are under contractual obligations not to release their contributions, libre.
Does this mean other parts of ES are proprietary, down to specific commits by certain people?
Do all contributors release all contributions, libre?
If any of these things are true, this may be a bigger disaster than the few proprietary files, as it may mean that many, many more contributions which have long since been mixed into the codebase are proprietary.

Yes, these files will impact designations as they will no longer be true.

The disaster of the few proprietary files is relatively small, but a disaster nonetheless.

**Comment by throwaway1037** [comment]
@mzahniser yes, I do believe in the [free software philosophy](https://gnu.org/philosophy).

However, the latter part of your statement is false; I did not raise a duplicate, but a continuation of a withered discussion, and it is false that their license agreement didn't allow them to liberate their works, only that the current license was not libre. They could have easily liberated the works in question, but chose not to, excluding the sound files from a third-party.

**Comment by throwaway1037** [comment]
@Amazinite there are six `.wav`s in the file tree, but only three regexes are listed in `copyright`.

Thank you for pointing out how they could be replaced.

**Comment by throwaway1037** [comment]
@Zitchas the practical gains include avoiding having to remove all mentions of now-false labelling and the knock-on effects on other distributions, as I described. The ethical gains include respecting the freedom of the users, which is a must.

As for Steam, it is DRM-infested proprietary spyware and I don't see why it should limit the project, despite the fact that it is popular.

**Comment by throwaway1037** [comment]
@quyykk are you absolutely sure?

**Comment by quyykk** [comment]
I don't know who Zitchas is talking about and I'm by no means an expert, but I was under the impression that by opening a PR you implicitly agree for your changes to be released under GPL3, since that is the license used for this game. Except of course for images and sounds, as those can be licensed differently under the copyright file.

**Comment by throwaway1037** [comment]
This sounds good for a jump drive sound effect: https://freesound.org/people/ProfMegavolt/sounds/273357/

**Comment by Amazinite** [comment]
I've spoken with the creator of the red JD sounds and he says we're good to toss them. Roadrunner will also be finding replacements for the four offending landscape images.

**Comment by tehhowch** [comment]
This topic seems rather overblown. If "some distributions" (which ones? There are so many!) need to classify the distro-specific _Endless Sky_ packaged binary in their "you can't take this zip/flatpak/tarball and use it for commercial purposes without contacting one or more rightsholders first" storefronts instead of their "you can obtain all source code and supporting resources for this game for free" storefronts, then they'll need to do that. They _already_ could not put it in their "you can obtain all source code and supporting resources for this game for free and _do whatever with it_" storefront because we license C++ and .txt files as GPL-3 and have CC-BY and CC-BY-SA licenses that require reuse of the same license and attribution. (Anyone attempting to cast _Endless Sky_ being available on a distribution for free as "contributing to commercial advantage"--i.e. violating the NC clause of some of the currently packaged resources--should be laughed out of whatever room they're in.)

Some tangentially related issues: #6104, #3046

FWIW @throwaway1037 I believe you meant to tag @Zireael07

**Comment by Zitchas** [comment]
Thanks for the knowledgeable input, Tehhowch. 

I'd just like to add that - while minimizing the NC stuff is all well and good, I am absolutely against having any rule or even discouragement of having NC contributed. I can't speak for everyone, but I'd personally value having NC contributors over being included in the most extreme of extreme "free in absolutely every sense of the word" repositories. The value loss in excluding potential content creators (especially on the sound and scene side of things, which is where we have the fewest creators) far outweighs the more or less prestige benefit of being included in such a repository.

**Comment by tehhowch** [comment]
A nit, Zitchas: "libre" as used by this throwaway account means that the user is freely able to request, modify, and redistribute the source code _under the same license without further limitation_. Because there are some files whose license limits their _individual_ "allowable reuse," that last bit of the caveat is not met. Thankfully, as noted above, the game will happily reference missing image and sound sources without crashing, so users who wish to repackage can do so even with commercial intent, by also removing those files.

All that said, I _am_ against including "no derivatives" licensed sources, as this game is one big derivative and asking others to not be so inspired as to remix your work into something new goes against this game's origin and process of continual improvement.

**Comment by throwaway1037** [comment]
@tehhowch,

There are over 1000 GNU+Linux distributions and countless other semi-libre OSs, so I couldn't possibly list exactly which ones would have trouble repackaging ES into a different repo if ES remains partially proprietary or would otherwise have to patch out the nonfree files.
I know for certain that Debian and Fedora have relatively strict policies, and that yesterday, [Parabola removed ES whilst liberation work is underway for the next release](https://labs.parabola.nu/issues/3210).

Your mischaracterisations of various OS repos are also misleading because they are not usually set up as you described; generally, the distinction is libre vs proprietary, not "do anything you want" vs "don't do anything you want"; CC-BY-SA and GNU GPL are libre licenses.

> FWIW @throwaway1037 I believe you meant to tag @Zireael07

Whoops!

**Comment by throwaway1037** [comment]
@tehhowch, "libre" in the context of published works is defined by the [Free Cultural Works Definition](https://freedomdefined.org) and for specifically software, by the [Free Software Definition](https://www.gnu.org/philosophy/free-sw.en.html).

The definitions you provided are not the actual definitions.

**Comment by Zitchas** [comment]
> You also used a couple of loaded words: ["content"](https://gnu.org/philosophy/words-to-avoid.html#Content) and ["creator" (in the context of authors of published works)](https://gnu.org/philosophy/words-to-avoid.html#Creator). These words imply support for the authors of published works to restrict people with them.

Yes, definitely. Someone who creates a work does have the right to impose restrictions on those works. I feel that society is best served when the restrictions are light, but that doesn't change the fact that the authors do have the right to set those restrictions wherever they feel like it.

Create derivative works? Sure, that's fair use as far as I'm concerned. Just take it, turn around and sell it? That's just profiteering, and in a lot of cases that's just being a parasite. Some exceptions exist, of course.

Neither the Cree Cultural Works Definition nor the Free Software Definition are authoritatively binding upon the world, either.

**Comment by throwaway1037** [comment]
@Zitchas, I strongly disagree. All works should respect the freedom of their users from the instant they are published. Authors do not have a right to restrict other people's copies of a work.

**Comment by oo13** [comment]
The Debian package endless-sky, endless-sky-data, and endless-sky-high-dpi are apparently abandoned, so they will cause no problem. If someone would update them and put them in the Debian "main" repository, I would report the license violation to Debian devs if needed. You could put them in the Debian "contrib" and "non-free" repositories.
README.md says Endless Sky is a "open source game" (not a "libre game") and "all the artwork is either public domain or released under a variety of Creative Commons licenses." It means ES could contain CC-ND. If you would reject CC-ND, I recommend correcting README.md. (I dislike CC-NC due to the ambiguousness and restricting distribution, but I feel CC-ND has less risk because it can always replace new one and it won't restrict the distribution...)

**Comment by throwaway1037** [comment]
@oo13, ES is not "open source" either due to the inclusion of -NC type licensed works.

**Comment by throwaway1037** [comment]
Moreover ES should be fully liberated in the next version according to @Amazinite.

**Comment by throwaway1037** [comment]
@MCOfficer I agree with the GNU article. I also agree you should be free to choose to use whichever definition you want, but that does not stop some definitions being incorrect.

By the "Open Source Definition", ES is not "open source" because it contains proprietary files.

Regardless, formulating ideas in terms of freedom is much more conducive to logical conclusions than "open source", because that term is misleading and seems to indicate that all that matters is the ph CLI availability of the source form of a work, which totally misses the point.

**Comment by Amazinite** [comment]
We get it, you're a stickler for strict definitions. No need to keep going on about it.
