### ISSUE TITLE
Events/Missions with map changes do not affect the map until launch.

### ISSUE THREAD

**Issue by Hecter94** [endless-sky/endless-sky#6719]
### Problem Description

Any mission or event which would result in a map change, whether that be systems being hidden, unhidden, revealed, visted, unvisted etc. does not trigger until after the player launches even if the event/mission triggers on landing or while landed. 

You can see this most clearly with the "pug invasion" event, while still landed you have full visibility of the systems, however as soon as you launch they become unvisted and disappear off your map.

This mostly causes issues if you have events which should trigger immediately upon landing, but the player can still open their map and see that the changes have not occurred and will not occur until they launch.

### Related Issue Links

Similar issue to do with swizzle changes not updating immediately: https://github.com/endless-sky/endless-sky/issues/6428

### Desired Solution

Events and missions should be able to define whether an action occurs "on launch", "on land", or "on accept" 
If the action is set to occur on launch, it would maintain the current implementation, where the change does not happen until the player launches.
If the action is set to occur on land, it would happen the instant the player lands on the planet and triggers the event/mission
If the action is set to occur on accept, it would happen as soon as the mission is accepted or the event is triggered, useful for spaceport or job board missions.

### Alternative Approaches

Simply modifying the current implementation to trigger the map changes the instant the mission or event is triggered would be a good option as well, and would resolve the underlying issue, however this approach lacks some versatility and functionality of my desired solution and can potentially result in undesirable effects as it will be changing how events and missions are currently implemented.

### Additional Context

As an example:

```
event "pug invasion"
	unvisit Cebalrai
	unvisit Ascella
	unvisit Peacock
	on land
		unlink "Zeta Aquilae" Ascella
		unlink Rasalhague Cebalrai
		unlink Rasalhague Ascella
	on launch
		link Deneb "Zeta Aquilae"
		link Deneb Rasalhague
	on accept
		unvisit "Zeta Aquilae"
		unvisit Rasalhague
		unvisit Orvala
		unvisit Deneb
```

In this case, the instant that the event is triggered the following systems would be unvisted: Zeta Aquilae, Rasalhague, Orvala and Deneb
As soon as the player lands the following systems would be unlinked: "Zeta Aquilae" Ascella, Rasalhague Cebalrai, Rasalhague Ascella
As soon as the player launches, the following systems would become linked: Deneb "Zeta Aquilae", Deneb Rasalhague

and the three systems not included in an action: Cebalrai, Ascella and Peacock would default back to their original functionality to ensure backwards compatibility.

**Comment by tehhowch** [comment]
Events currently don't apply until the next day. Landing does not advance the date, but taking off does. Recall that a mission action ("on ....") event reference declares the time until that event occurs, with the default of "at the next opportunity," not "now."
It's absolutely possible right now to move conversations to occur in an "on enter" action rather than the offer or accept actions, so content authors that need to have synchronous events can mimic it.

Introducing multiple timing keywords to override the default behavior is probably not the way to address it, though. I also wouldn't want to add this capability before we have addressed the existing issues with the landing sequence (e.g. mission resolution & partial state application).

Probably this should be done by supporting an explicit event reference time of 0 (applying at the conclusion of the current mission action or prior to the next conversation text advancement), allowing events to initiate other events with the syntax of missions, and adding a keyword that indicates the event should process at the end of a day rather than the beginning (i.e. upon landing).

Event syntax should generally remain player-agnostic -- these are things happening in the universe, the player has no control over them, cannot refuse or accept them, etc.

**Comment by tehhowch** [comment]
Related: #4855

**Comment by Amazinite** [comment]
> Probably this should be done by supporting an explicit event reference time of 0

This is something I've thought of in the past: make it clear to content creators that `event <name>` with no number is implicitly `event <name> 1`, i.e. do this event tomorrow, but allow for an explicit `event <name> 0` that triggers the event at the time of the action triggering instead of queueing it up for the next day.
