### ISSUE TITLE
Bug: dumping cargo from a recalled fighter deletes the cargo 

### ISSUE THREAD

**Issue by samrocketman** [endless-sky/endless-sky#6727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While a fighter is deployed it might pick up cargo or asteroid flotsam.  If a player wishes to re-deploy the fighter to collect more flotsam they would intuitively dump the cargo for the carrier to pick up.

While a fighter is inside of the parent carrier, dumped cargo gets deleted.

### Steps to Reproduce

1. Have a carrier and a fighter with cargo
2. Collect flotsam with fighter
3. Recall fighter inside of carrier.
4. While fighter is inside carrier dump its cargo.
5. You'll notice that cargo gets completely deleted.

### Expected Behavior

Cargo would dump into space or transfer to parent.

### Operating System

Linux

### Game Source

Built from source

### Game Version

Continuous at 4f3431fda432cf148280de2c8089701b899b7cd9

### Additional Information

This issue was originally reported [in discord chat by **Kezethun**](https://discord.com/channels/251118043411775489/308902312741568512/964249278962864150).  @samrocketman verified the bug is in continuous by building source and play testing with all-content-plugin.

**Comment by vitalchip** [comment]
If we accept the reality that, for now, player carried ships don't transfer their cargo to the carrying ship then we also have to realies that we shouldn't be able to do an 'end run' around this limitation by dumping cargo while docked and haaving it be added to the carrying ship.

It may make sense for externally carried ships to dump their cargo directly to space but not internally carried ships.

For the moment I would say the correct solution is to just disable dumping for ships currently carried. Since these ships have no system, it could be achieved in ShipInfoPanel::CanDump() const by adding a system check.

	if(canEdit || shipIt == player.Ships().end() || (*shipIt)->IsParked() || !(*shipIt)->GetSystem())
		return false;

It may be something to re-visit at a laater point if the rules regarding cargo transfer are changed but for now it eliminates the confusion of disappearing cargo.

**Comment by samrocketman** [comment]
After short discussion with @vitalchip in discord I plan to implement his suggested fix.  I will open a PR and preserve @vitalchip authorship when I do.

**Comment by TomGoodIdea** [comment]
Is anyone going to PR a fix?

**Comment by tibetiroka** [comment]
Can't fighters transfer cargo to their flagship now?

**Comment by TomGoodIdea** [comment]
I've just tested it and it still seems broken
