### ISSUE TITLE
What should happen when all planets of a region are dominated.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#673]
I really feel like when you dominate your first planet of any particular goverment, it should trigger some kind of story prompt. When you finish dominating all the planets of that particular government..all there ships should become friendly. Expanding on this..I'd really like to see planetary conquest as a campaign in its own right. It could be a sort of end game campaign..

**Comment by BuildBruh** [comment]
I could see a light-ish(?) plugin/mechanic that would increase amount of tribute given by each planet under that government/system.

**Comment by bchis17** [comment]
Make a galactic empire:)

**Comment by brendanjones** [comment]
I like this idea. A lot. 

Dominating planets is the ultimate end-game mission, and yet it's without a storyline and it's also kinda monotonous. 

- Capturing a planet is strangely without consequences  - when you've dominated one planet of any faction, they should start a war with you. There should be a massive bounty on your head! Fleets warping in to destroy you!
- Capturing planets is without reward - I don't count a couple of thousand credits a day as much of a reward, since even with every planet dominated it's not even enough to cover your crew costs. You own the entire galaxy, but you don't earn enough to pay your crew? Yeh, right!

**Comment by endless-sky** [comment]
It's possible to have missions trigger when you have dominated a particular planet, but as I've mentioned before, planetary domination is really just there for bored end-game players and is not meant to mesh perfectly with the real story line.

**Comment by brendanjones** [comment]
"planetary domination is really just there for bored end-game players and is not meant to mesh perfectly with the real story line"
Well it's such a big aspect of the game, seems a pity to not have it mesh with the storylines in any way. Just needs someone to do the work, really *looks around for enthusiastic faces
