### ISSUE TITLE
Different species of Crew Members

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#674]
Got the idea from visiting a Pug planet (Pugglemug) Before unlocking it in the storyline, and realize I could buy troops there. It doesn't seem logical to buy HUMAN troops in a non-human inhabited zone, nor does it seem logical to buy human troops in a wanderer are, where you are the only (known) human to ever be. Maybe different types of troops have higher base attack/defence depending on species?

**Comment by Pointedstick** [comment]
Troops? You mean crew?

**Comment by thenerdfreak** [comment]
Yes.. sorry. I call them by a martial term because that's how I use them :p

**Comment by Pointedstick** [comment]
#666

**Comment by endless-sky** [comment]
I think this is another case of realism vs. game play. Yes, it's unrealistic for "crew" to be available on every planet, but making them only available on human worlds would get really annoying as the galaxy grows.

If crew can be of different species, then every ship would have to track how many crew of each species it has, and all the code involving crew would get much more complicated. I don't see any real advantage to that, especially since hand-to-hand weapons already provide a mechanism for improving your crew's characteristics.

**Comment by thenerdfreak** [comment]
I was thinking something along the lines of making the crew feature like an outfit that takes no outfit space but takes up 1or more  "crew space"  depending on the species

**Comment by ph2000bis** [comment]
Or maybe, when you can translate the language, only then can you hire crew. If you can speak to them, you can hire them.

**Comment by Pointedstick** [comment]
I kinda like the idea of having Hai or Wanderer crew members.

**Comment by endless-sky** [comment]
Given that you can already adjust your crew's abilities with hand to hand weapons, I think that having to track different species of crew as well would be way too complicated and wouldn't really add any new strategic choices to the game.
