### ISSUE TITLE
Captured ships doesn't change color until I send them to a planet.

### ISSUE THREAD

**Issue by abmpicoli2** [endless-sky/endless-sky#6773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I capture, say, a pirate ship, it's colors doesn't change, making it difficult to differentiate again which are my ships or which are pirate ships during long engagements.

### Steps to Reproduce

Just go to some system and capture with success a ship.

### Expected Behavior

I would expect that the ship would change colors. It doesn't.

### Screenshots

![image](https://user-images.githubusercontent.com/37077317/165354254-034bd328-95a1-4118-af71-8cb01bf29463.png)
![image](https://user-images.githubusercontent.com/37077317/165354290-d83789d2-01be-42a4-89cd-483d1ee8958b.png)
![image](https://user-images.githubusercontent.com/37077317/165354313-501dc74e-42d1-4d69-ad83-1782b8c17bf7.png)

my ship: wrong color.
![image](https://user-images.githubusercontent.com/37077317/165354384-658c8efe-765c-4bd9-a468-2b0212abcb35.png)

### Operating System

windows 10

### Game Source

Steam

### Game Version

The beta version on steam as of April/26th/2022

**Comment by DeciduousBeard** [comment]
I don't think that's a bug, it's realistic. In the Free Worlds storyline a big deal is made of you changing your colours from merchant to free worlds - the ship needs to be physically repainted in a shipyard. In reality, you are not going to repaint a ship in space. You will repaint it after you land. So the existing behaviour is already correct.

I would always land as soon as possible after capturing anything anyway, because at that point the ships shields and hull are so low that if I get into another fight I'm liable to lose the ship I just captured. If you ARE in a long engagement, and capture a ship, it then runs into the fight and gets destroyed because it's almost dead already. But if you leave it in a disabled state, nobody actively tries to attack it, so it's actually safer. So it's usually better to wait until the engagement is over, leaving the ships that get disabled alone, and then go around at the end capturing everything that's still available. So this is only an issue if you're following a strategy that's going to make you lose ships.

**Comment by movingpictures** [comment]
> I would always land as soon as possible after capturing anything anyway, because at that point the ships shields and hull are so low that if I get into another fight I'm liable to lose the ship I just captured. 

Or you drive out to vacant space and command it to hold .... then when you have a collection, land the flagship ... the captured vessels land automagically without risk of loss.

**Comment by tehhowch** [comment]
Related: #2295 and its referents

As mentioned already, just because you capped it, doesn't mean you painted it, too.

This is a wontfix IMO

**Comment by abmpicoli2** [comment]
Well, in here, I agree to disagree: this is a game: it is not supposed to be realistic. If you want realism, a ship capture wouldn't pause the battle, spaceport landing of 3000 ships would be rejected / cause spaceport congestion, more realistic battles during boarding... no mineral respawn in a single day, and the list goes on and on. Not to mention the artificial physics that make limits on ship max speed and temperature based on size by means of an artificial drag coefficient.

But if you say you won't "fix" it, ok, then.

**Comment by DeciduousBeard** [comment]
I'm with you on the artificial physics @abmpicoli2, that has always struck me as incorrect - a spaceship should be able to infinitely accelerate, I see no reason for the additional complexity of the current physics model that serves only to reduce realism. Surely a more realistic model would actually be simpler to code?

Personally, I think if you're adding complexity that reduces realism, then you're on the wrong track (e.g. painting ships in space, unnecessary physics coefficients), because you are using effort to make it less realistic.
 
But if you're simplifying in a way that reduces realism (e.g. spaceport landings allowing any number of ships, boarding pausing the battle) then that's reasonable - the lack of realism is simply because you haven't coded anything about that yet (and may never bother to if it is unimportant). This way you'll always have things that are unrealistic - but they will be the things that you haven't yet got to (or may never get to).

Just my 2c.

**Comment by Zitchas** [comment]
From what I gather, programming proper physics that allows for realistic physics is kind of hard, and it is even harder to teach the AI how to handle it. Limits establish parameters that make everything work smoother, even if it is "unrealistic." 

Something like changing the color of ships mid-flight is more of a story thing. It might not have huge impacts on the mechanics; but it does tie into the story. I personally like this particular piece of realism.

**Comment by Hurleveur** [comment]
Capping is already too strong in this game. Changing this would make it even easier.

**Comment by Zireael07** [comment]
How would changing colors make the game too easy? This is imho a basic accessibility issue and no space RTS game I know does this this way. Even if the model stays the same, there is some readily visible way to tell "us vs them"

**Comment by Zitchas** [comment]
As a basic accessibility issue, I would like to point out that, for those that would like to have it, the HUD can be activated in the preferences, under the settings tab "Show status overlays."
Here's a picture of me being attacked by three quicksilvers, with a fourth pirate quicksilver that I captured earlier in the battle.
![HUD](https://user-images.githubusercontent.com/32169904/165748891-4272137a-2759-4b5e-a888-53b0480cde51.png)

Note the quicksilver that belongs to me has its shields displayed in green, whereas the hostile ones are displayed in red. While not shown in this image, the selected ship will have red corners bracketing the ship if it is hostile.

While ES admittedly is not perfectly realistic, we do try to stick to it when we can; and this is one instance where said realism is in alignment with both the lore and the intended gameplay behavior. The ship isn't really 100% yours until you can get it back to harbor and repaint it in your fleet colors.

**Comment by Zireael07** [comment]
Thanks for pointing out that option - in that case I retract the "accessibility" objection, as many games also do it by indicating ownership on the HUD.
