### ISSUE TITLE
Killing Militia defense fleets angers the Free Worlds

### ISSUE THREAD

**Issue by thenerdfreak** [endless-sky/endless-sky#678]
If I've started the free worlds missions, they're fighting right? then why do free world's ships still defend some republic planets? I went from top of the line reputation with free worlds to deep red within ten planet dominations (all were republic planets guarded by free worlds)

**Comment by thenerdfreak** [comment]
On another note, I have the a high enough fleet strength and notoriety to capture the Sol System, and yet I get laughed off by a few Buddhist monks living on barely inhabited planet?

**Comment by endless-sky** [comment]
I don't believe any planets have Free Worlds defense fleets. However, there are quite a few that are defended by their own private militias rather than by the Navy, and killing militia ships will make a lot of people mad (including the Free Worlds).

Planetary domination is intended as a sort of separate mini-game for bored players who have advanced to the point where everything else is too easy. Having the story line respond to planetary domination and vice versa would be way too complicated to be worthwhile.

**Comment by thenerdfreak** [comment]
their swizzle was the same as the Free Worlds, and killing them made the Free Worlds angry, didn't get time to see if they were free worlds or not because they were vaporized immediately upon exiting their planet, but seems kinda fruity that I take over a Republic system two jumps from Sol and the free worlds get angry about it

**Comment by DingusShingleton** [comment]
The free worlds are a populist movement, they don't want to see innocent republic civilians killed anymore than their own. In fact, they don't really WANT to kill anyone, they just want to be able to govern themselves as they see fit.

**Comment by Pointedstick** [comment]
It shouldn't be too shocking that people with the name "**Free** Worlds" would disapprove of someone who goes around dominating planets for personal gain. 🙂

**Comment by endless-sky** [comment]
This behavior is intended, because the Free Worlds considers themselves to be allies with the private militias of the poorer planets near their territory.
