### ISSUE TITLE
Incorrect counting of ships unable to leave the system

### ISSUE THREAD

**Issue by pilover100** [endless-sky/endless-sky#6781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When Departing a planet without any ships equipped with any FTL systems (HDs, SDs, JDs... etc) and carrying fighters, the game incorrectly counts the number of ships that can't leave the system.

### Steps to Reproduce

1. Acquire a carrier and strip it of any FTL systems and get some fighters
2. Attempt to depart the planet, note that the count is your carrier + any loose fighters (or other ships without FTL systems)
3. Note that you have more ships that can't leave the system than the game suggests (your carried fighters without any carriers with FTL systems)

### Expected Behavior

The game counts fighters which have no parent capable of inter-system travel as well as "loose" fighters

### Screenshots

Attempting to depart:
![capture1](https://user-images.githubusercontent.com/65236599/165984959-43d5d2f9-3453-400e-bbeb-7614f6009c0f.jpg)
In system - note I have 6 fighters - none with any FTL systems:
![capture2](https://user-images.githubusercontent.com/65236599/165985044-e0c95da2-9992-4220-ab69-5d62b6379720.jpg)

### Link to save file

Any should do, but here's mine (ready to do the bug):
[Katie Hanley.txt](https://github.com/endless-sky/endless-sky/files/8592244/Katie.Hanley.txt)

### Operating System

Windows 10

### Game Source

GitHub Releases

### Game Version

Continuous: Commit #6763

**Comment by daveeater** [comment]
I think the problem here is your expected behavior.  If a fighter is berthed in a carrier, whether his has a FTL drive or not is irrelevant.  Fighters often do not have such capability.  You seem to be asking that the program count berthed fighters - but only if they're berthed in a carrier that lacks FTL capability.  You're asking for a bunch of code to figure this out. As it stands, the program doesn't evaluate berthed fighters, because in normal conditions, there's no reason to do that.  The player needs to be alerted if unberthed fighters will be left behind, and needs to be alerted if other ships (including carriers) will be left behind. The player does **not** need to be alerted if a berthed fighter (or all the berthed fighters) don't have FTL capability - because this is normal
