### ISSUE TITLE
Negative credits when paying to land on a planet

### ISSUE THREAD

**Issue by alepulver** [endless-sky/endless-sky#68]
I had about 20K, but a planet requested 120K to land. The "offer bribe" button was enabled even if I didn't have enough crecits, but after that a negative amount of money appeared (-100K). The issue seemed to disappear after departing, as it was reset to 0, but it turns out the credits reset to 0 after each depart (even after earning credits).

**Comment by endless-sky** [comment]
Good catch! This should be fixed in 7ceb7f0. The reason your credits are getting reset to 0 is because, as a separate bug, your negative credits are getting treated as back pay that is due to your crew. (You'll notice when you take off, there will be a note saying you paid a large amount of salaries. and that's when your credits go to zero.) So, if you earn enough money, eventually your credits should go positive again.
