### ISSUE TITLE
Use of the pilot license ?

### ISSUE THREAD

**Issue by ph2000bis** [endless-sky/endless-sky#680]
Is the pilot license being available at outfitters bring anything to the game for either lore or gameplay purposes ?

**Comment by endless-sky** [comment]
Originally there were a lot of different licenses depending on what sort of ship you wanted to fly. They were intended to reflect the fact that high licensing fees make it hard for small independent captains to compete with large corporations like the Syndicate. I took all the other licenses out because they were really annoying, but left the Pilot's license in place.

**Comment by ph2000bis** [comment]
So it's not essential to have them available for sale in outfitters ?

**Comment by Hyratel** [comment]
so by retaining the Pilot's License, you left the entire mechanic in place, just dummied out? That leaves an awesome hook for modders

**Comment by endless-sky** [comment]
Yes, right now the only way that you acquire new licenses (e.g. the Wanderer ship license) is through missions. But it's still possible for them to be available as an outfit you purchase, instead.
