### ISSUE TITLE
How shall jumpdrives stack?

### ISSUE THREAD

**Issue by Wrzlprnft** [endless-sky/endless-sky#683]
original question: do jumpdrives stack?

http://steamcommunity.com/app/404410/discussions/0/458606248629530650/

**Comment by ItsNickBarry** [comment]
It seems that they do.  Having 17 jump drives also improved the performance of the single jump drive I also had installed; it worked almost like a scram drive.

**Comment by Wrzlprnft** [comment]
So the next question is... are they supposed to stack?

**Comment by ItsNickBarry** [comment]
I don't see why they should.  I had mistyped my previous comment, which now points out that jump drives stack with standard hyperdrives as well, which makes very little sense.

**Comment by endless-sky** [comment]
Jump drives and hyperdrives stack in the sense that installing several of them increases the "jump speed", which is how slow your ship needs to be moving in order to jump. Allowing that attribute to stack will allow various cool effects in the future, such as a species whose ships inherently have a higher jump speed, or outfits that provide an add-on to your hyperdrive that increases your jump speed.

**Comment by Wrzlprnft** [comment]
I like the idea, but i find it strange that the effect stacks linear... i would suggest to let them stack more like interference plating, but only those of the same type

**Comment by DingusShingleton** [comment]
Or higher jump range *salivate*
