### ISSUE TITLE
Minor bug: white sun reactor mass wrong

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#686]
The mass of the white sun reactor is 126 and has an outfit space 127. As I said very minor 'not quite' bug but it is still out of keeping with the rest of the game.

**Comment by thenerdfreak** [comment]
Too be entirely honest I don't believe the mass of an object should reflect the amount of outfit space an object takes up as much as its VOLUME does. But yeah, is out-of-place with the rest of the game

**Comment by endless-sky** [comment]
That's a typo; it was fixed in d481de0.

**Comment by rktaylor** [comment]
I think "mass" and "outfit space" are used interchangeably the way the original games did, because it isn't volume (volume limitations are given by "engine capacity", "weapon capacity," and "hardpoints") it's mass that limits a ship's ability to reach escape velocity.

**Comment by endless-sky** [comment]
Yes, the only reason "mass" and "outfit space" are separate attributes right now is to allow outfits like the mass / cargo expansions.

But in the future, it might be cool if some outfits made of lightweight materials have a mass that is less than their outfit space. That would add another layer of strategy, because lighter outfits would give you a more maneuverable ship.

**Comment by rktaylor** [comment]
Also, Wanderer outfits don't display how much heat they generate in the buying panel (though you bet your butt the reactors produce heat.)

**Comment by endless-sky** [comment]
Closing this, because it's fixed in 0.8.11.
