### ISSUE TITLE
Star system inconsistencies after Ssil Vida reactor repaired

### ISSUE THREAD

**Issue by 3519421** [endless-sky/endless-sky#6860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After activating the Ssil Vida reactor (or possibly when the wormhole is first created, I did not notice immediately), the Caeculus star permanently disappears, regardless of whether the reactor is enabled, the game is reloaded, etc:

![Caeculus-before](https://user-images.githubusercontent.com/101584135/170079070-849b0722-8b8d-4ad9-b3ac-f85469374d06.jpg)

![Caeculus-after](https://user-images.githubusercontent.com/101584135/170079053-467615da-ceb3-4002-8dbf-28c05e43ee8a.jpg)

After activating the Ssil Vida reactor, the jump routes out of Ssil Vida's pocket of systems are permanently lost and never reappear. Ships may jump into the pocket without a keystone, but may not leave without a keystone. (Probably causes #6639)

![Edusa-Postverta-no-stone](https://user-images.githubusercontent.com/101584135/170079838-307b1a54-1690-4251-a620-ba83b6d3b1da.jpg)

![Postverta-Edusa-requires-stone](https://user-images.githubusercontent.com/101584135/170079858-1fd9a8c6-45e6-4119-bfe7-8366ccf7144b.jpg)

### Steps to Reproduce

Affects continuous builds through the current version:
Triggered on 2022/05/24, 13:50 UTC by commit https://github.com/endless-sky/endless-sky/commit/6b9b12f35260848c47c70b60d5f5040e688c46fc (@tehhowch)

### Expected Behavior

I would expect jump routes not to be one-way, and I don't recall the disappearing sun being mentioned in dialog if it was an intentional change.

### Link to save file

[Teacup Petrichor.txt](https://github.com/endless-sky/endless-sky/files/8764488/Teacup.Petrichor.txt)

### Operating System

Windows 8 64-bit

### Game Source

GitHub Releases

### Game Version

6b9b12f

**Comment by Zitchas** [comment]
The jump routes shrinking is intentional, but the stat disappearing is not. I will try to confirm this when I can. More that Ssil Vida does have a basic outfitter with HD and keystones to ensure one can't get permanently stuck there.

**Comment by warp-core** [comment]
In event: "ssil vida activation":
https://github.com/endless-sky/endless-sky/blob/6b9b12f35260848c47c70b60d5f5040e688c46fc/data/remnant/remnant%20events.txt#L315
In map.txt:
https://github.com/endless-sky/endless-sky/blob/6b9b12f35260848c47c70b60d5f5040e688c46fc/data/map.txt#L6184

**Comment by quyykk** [comment]
That's another reason to define events that only change what is necessary (😉 @Zitchas).

**Comment by 3519421** [comment]
> The jump routes shrinking is intentional

Unless there is a lore reason or travel timing/AI issue, would it be better to delete both sides of the jump route, rather than leaving it one-way? It seems slightly counter-intuitive as it is right now, though I guess there's precedent of a sort with the one-way wormhole loops.

**Comment by Amazinite** [comment]
I spotted this while working on 1797f56. Will fix soon. Just needed to hear from Zitchas what was suppose to be happening.

**Comment by Zitchas** [comment]
Unfortunately with the way Jump Drives work currently, their jump distance can only be set by the departure system, not the destination. So unless that changes, the Postverta systems currently act as a trap of sorts. The player can still escape from it, of course, but they'll have to use the wormholes to do so.

The alternative is to apply the reduction across the Ember Waste, or at least as a gradient. That's doable.

**Comment by 3519421** [comment]
> Unfortunately with the way Jump Drives work currently, their jump distance can only be set by the departure system, not the destination. So unless that changes, the Postverta systems currently act as a trap of sorts. The player can still escape from it, of course, but they'll have to use the wormholes to do so.
> 
> The alternative is to apply the reduction across the Ember Waste, or at least as a gradient. That's doable.

On further thought, leaving it as-is would probably be better, as Ssil Vida offers Raider/Dredger jobs, and we've seen evidence of Dredgers coming in and dropping fighters. Clearly the Korath are getting in there somehow, and without keystones added to their outfits, they must be using their jump drives.

**Comment by Zitchas** [comment]
> I spotted this while working on [1797f56](https://github.com/endless-sky/endless-sky/commit/1797f560765d7259d2c265dbba93021005988442). Will fix soon. Just needed to hear from Zitchas what was suppose to be happening.

Basically, what is happening is:
a) When Ssil Vida is activated the player and this collection of systems is translated into a pocket dimension where copies of this cluster of systems exist. They are very similar, but they have different fleets, different mineables, don't have wormholes connecting to outside, and in some cases, planets change. There are still some Korath fleets on the basis that the Korath are exploring this area too, and these fleets represent ships that are getting caught up in the translation. Realistically, there's probably a very finite number of Korath exploring the area, but I'm fine with it this way. It should be noted that when Ssil Vida is activated, it isn't just the player's viewpoint that changes. Someone outside the area will see those wormholes vanish too; nor will anyone be able to jump into the pocket, and in fact shouldn't see those systems as existing at all.

b) When Ssil Vida is deactivated, the everything splits and part of it is translated back to the regular dimension, and this cluster of systems reverts to their old state, while retaining the Jump Distance modifier because things are changing such that it interferes with Jump Drive operation.


I'd actually like there to be a bunch of extra planets in the cluster that appear, but ES *really* doesn't like having missions that go to places that don't exist. Ideally, this mechanism is setup so that people can take the mission, go to Ssil Vida, activate the station, then go land on the planet, do stuff, then go back to the station, deactivate it, and return to the main worlds. Anyway, the point is this mechanism is something I expect the player to need to use repeatedly in Chapter 3, and it will be needed a few times in later chapters as well.

But yeah, these events are big, and they change a lot. And broad unrelated changes like updating stars is likely to cause problems for them.
