### ISSUE TITLE
Drak storyline? Or maybe even somthing better...

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#691]
Yesterday I was thinking about another main storyline, involving all the aliens in-game and all fractions. This is how it goes:
1. Korath launch a massive offensive against the core, crippling the unprepared Syndicate and causing a massive influk of refugees, causing a massive buildup of refugees in the Eastren part of Republic space.
2. Massive Republic fleet headlocks with the advancing Korath, grinding their advancement to a halt. 
3. Unfettered invade Hai space, cerating yet ANOTHER refugee crisis that nearly topples the Republic
4. Free Worlds aids the teetering Republic, saving it from total collapse
5. Priacy is on the rise, due to shortage of active patrol ships
6. Quarg space is de-linked with human space, and drifts out of jump drive range while unfettered destroy Quarg ringworld. Things seem pretty hopeless now.
7. New Hai fleet allows some loosening of the Republic fleet, allowing them to battle the looming pirate threat. A new sense of hope arises.
8. Unfettered, finished capturing Hai space, set their sights on Human space
9. Unfettered take northeren human space, with little resistance. What advantage humaniy had is now taken away on a two-front war that can only be lost.
10. Humanity despratley messages the Drak, who reply that they are tied up in another war with a extemlely powerful foe that can move and entire systems and anilhate entire systems.
11. Humanity is pushed out of Syndicate space and is on the verge of losing Earth to the invaders.
12. Earth falls and the Deep vanishes. The scraps of the defense fleet barley manages to slow down the advances of the aliens. Free Worlds space becomes cloogged with the billions of refugees. All seems lost.
13. A Pug massive fleet pours out of the wormhole in Deneb, and reclaims the few systems around it. At the same time, the Eye opens in Wei and Wanderer warships reforce the struggling Hai and Human fleet. 
14. The Pug and Wanderer renforcements rapidly reclaim lost territory, and restabish the failing human goverments.
15. Pug reconnect the deep, take all but the very core worlds, and wipe out the remaining Unfettered.
16. Korath are subdued, and the few remaining are brainwashed to be peacefull.
17. Pug agree to sell their outfits, and give to patroling Human space.
18. Hai, Humanity, Pug, and remaining Korath merge into a super-race and advance extremly rapidly.
19. Fleet is sent out to recover Quarg worlds, and does.
20. New era of peace and prosperity, poverty and piracy are abolished, and technological advancement soars past the Quargs level.
21. Humanity is greeted by a Drak fleet, warning them about the new galatic enemy they were not able to defeat...
Sorry this is so long! Please post any questions or comments below!

**Comment by natangold** [comment]
According to the in-game lore, the Korath seem to verging on extinction. How are they launching an attack on humanity? Admittedly, they're spread a bit thin from the wars, but the Korath are at this point scavengers, not empire-builders.

Likewise, the Unfettered have been in a deadlock with the Fettered since before the human advent of beer (and thus civilization), why would that spontaneously change?

How are the Hai (or anybody else, for that matter) moving star systems? The amount of energy that would require is...

I like the idea of the Drak asking for help as a late-late-late game sort of thing, but with only 1/3 of the map even filled so far, I don't think we're there yet. (This despite fully expecting the Drak to be the BBEGs, whom the player will need to defeat by uniting all the [unfettered] races in order to put an end to their little galactic petting zoo.)

I'm sorry, I feel like an absolute jerk. There are cool ideas, but I don't think they work quite the way you've mapped out right now. That said, I'd be totally down if you switched the Korath and Unfettered for two new races. (For example, a race moves into Korath space, forcing them into Syndicate turf while another "unfettered" faction of a different race "caged" by the Drak works with the Unfettered, breaking their stalemate. Leading the player to wonder "Where are the heck are the Drak?")

**Comment by endless-sky** [comment]
Since this is about content development rather than new features, would you be willing to move the discussion to the [forum](https://groups.google.com/forum/#!categories/endless-sky/content-creation)? I'm trying to keep the issues list manageable by limiting it to just bug reports and code changes. Thanks!

**Comment by Gkramme** [comment]
@natangold, no you are not acting like a jerk. A good ammount of critisim is needed! You're right. I need to balance the charecters based on their lore. The unfettered could steal many ships from the Hai though.

**Comment by Gkramme** [comment]
@endless-sky, I guess I could move it, but I think it is relevant to both fourms.

**Comment by endless-sky** [comment]
@Gkramme, this isn't a forum, it's a bug tracker.

This list is my primary way of tracking what changes need to be made in
upcoming releases, so it's important that every "issue" represent either a
bug or a limited, concrete change that can be made in the game. If you're
suggesting an idea for an entirely new campaign, you're probably better off
starting out with a plugin that people can test out and contribute to, and
then submitting the plugin's content as a pull request once it's tested and
polished enough to be included in the main game.
