### ISSUE TITLE
You can receive conflicting missions on the spaceport and be forced to lose one

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#70]
The first time I got a mission from the spaceport, I got TWO missions instead, this left me very confused, also the missions were to completely opposite sides of the galaxy (one in the northernmost star and the other to the southernmost star).

I had to cancel one of them, but now I can't see how the mission story went (I cancelled the one about hauling a dragon-like creature)

**Comment by endless-sky** [comment]
I agree that it is confusing to have multiple missions pop up. But, as you get further on in the game, there are situations where you can have multiple mission threads going at the same time, and it's necessary for the next step in both of them to be offered on the same planet at the same time. So, I can't make it a general rule that the game never offers two missions at once.

Right now there's the capability for marking a mission as "high priority," meaning, "if this mission is being offered, do not simultaneously offer any missions with a lower priority." I suppose I could extend that to also have "low priority" missions, so that the "flavor" missions like the courier ones would only be offered if nothing else is available.

**Comment by endless-sky** [comment]
Commit 6a328fd should fix this: it makes it so that missions marked as "minor" are only offered if no other missions are being offered (minor or otherwise). There will still be cases where multiple higher-priority missions are offered simultaneously, but at least there won't be any minor missions competing with them.
