### ISSUE TITLE
Fleets should fly in formation.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#700]
Would it be difficult to change fleets so that they fly in a v formation.

**Comment by rktaylor** [comment]
I imagine this'll be added later, but formations would make little sense when you get those planet conquering fleets of 50+ ships.

More important would be a "Hold Fire" command so my escorts don't roast ships I'm trying to board...

**Comment by mdsmestad** [comment]
Escorts already stop firing when the target is disabled..missile's are notorious for blowing up ships your trying to capture. Try beam weapons.

**Comment by natangold** [comment]
Escorts (i.e., fleet ships) stop firing, but escorts (i.e., ships you are escorting from point A to point B) don't.

**Comment by endless-sky** [comment]
It's actually harder than you'd think to get ships to fly in formation, especially if they're different kinds of ships, and especially with no reverse thrusters - if you're behind, you have to accelerate to catch up with the formation, but then you need to slow down to match speed with it, and the only way to do that is by turning around or by wiggling back and forth and using well-timed bursts of thrust to shed velocity. There's also the question of what the formation should do if the flagship turns - does the whole formation need to rotate?

The only time ships can really manage to fly "in formation" is during a synchronized hyperjump, because then they all have exactly the same acceleration and heading.

**Comment by thenerdfreak** [comment]
Would it be possible to add a variable thrust? as in, pressing w makes you continue moving slowly but holding it raises thrust higher? like a sliding bar, could be incorporated into AI to make them keep formation

**Comment by rktaylor** [comment]
Variable thrust might be a good feature on its own, but I think the "Gather Here" command for Fleets is sufficient for formation--it'd kind of be an aesthetic update to include formations, anyway.

I still want a "Hold Fire" button, even if escorts don't normally kill disabled ships. (And can we do something about the fact that pirates/NPCs kill disabled ships with a vengeance?)

**Comment by Hyratel** [comment]
an "engagement range" adjustable in-game (by the player/admiral would be sufficient for most purposes - a ship might have only missiles, and weak shields so it gets kept back away. or might have heavy lasers and Really Good Shields, so you set its ER very close, so it takes the brunt of an attack. this would be useful early/midgame - fleets of 15MCred to 50MCred or 100MCred combined value

**Comment by thenerdfreak** [comment]
Yeah I can see what @Hyratel talking about being useful. Because if you're a ship with moderately long range weapons and something gets close enough to hit you with a blaster, wouldn't you want to get out of blaster range and then turn again to attack?

**Comment by thenerdfreak** [comment]
Yeah I can see what @Hyratel talking about being useful. Because if you're a ship with moderately long range weapons and something gets close enough to hit you with a blaster, wouldn't you want to get out of blaster range and then turn again to attack?

**Comment by wargwargwarg** [comment]
+1 on engagement range
Also, some simple ordering to my ships (go there, stop, jump away, aggressive, defensive
