### ISSUE TITLE
Have asteroid scanner catalog asteroids while traversing systems

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#7096]
### Problem Description

There is no good way to identify systems that have mine-able asteroids. While the outfitter will update the map with materials, it will only do so for systems where you have actually mined that commodity. This makes building a map of mine-able resources a tedious manual process which further discourage folks from mining. While an asteroid scanner makes it much easier to mine, it provide no value unless you are actually mining. It mostly gets in the way of targeting, further discouraging it's use.

### Related Issue Links

None identified.

### Desired Solution

The asteroid scanner should catalog mine-able resources automatically while traveling through the system. This would update the outfitter map with the resources for all the systems you've visited. This makes having an asteroid scanner useful in the early exploration phases and indeed, might provide an incentive to check out the uninhabited systems for possible resources. Having the map allows the player to make choices about what and where to mine based on safety and returns. Finally it would make writing mining missions more flexible in that if a resource is exhausted in one location, the player has the information to fill the request from another system. The writer need not specify anything to the player and the player has options on whether or not they can fulfill the request within the deadline.

### Alternative Approaches

One alternative would be to have a galactic geological survey map for each faction available for purchase. While convenient, this takes away from the exploration aspect of the game and would not apply in hostile spaces (e.g. Korath, Graveyard).

**Comment by Zitchas** [comment]
Having the asteroid scanner property result in mapping a system's available asteroid types makes sense, especially for an "on interaction" sort of thing.

So there'd be multiple ways to map minerals:
1. directly harvesting them.
2. scanning asteroids with an asteroid scanner (ex. Any asteroid that gets scanned gets added to the map list. It's not a guaranteed "enter the system with an asteroid scanner and suddenly you know all the resources available there).
3. purchase a resource map: (note regarding this: These should only  be available for inhabited and/or controlled territory *not* just a universal everything within x jumps. As far as that goes, I really dislike the regular map for the way it behaves.)

**Comment by samrocketman** [comment]
It is worth noting that the asteroid scanner already automatically catalogs minables when you target them directly.  You don't need to mine it for it to be catalogued.  @Zitchas point 2 suggestion already exists today.

---

However, it would be nice for asteroid scanner to auto-catalog everything within scan range and not just the thing you targeted.  That means if you want to catalog the whole system you need to do one of two things.

1. Fly around the system with an asteroid scanner if you have limited scan range in order to fully catalogue it.
2. Install lots of asteroid scanning on your ship in order to catalog.  This means it would have the trade off of reducing your outfit space for lots of asteroid scanning with the benefit of cataloging systems effortlessly with longer scan range.

----

In my mining PR #6669 I add a new shortcut (V key by default) for asteroid targeting but it only extends the existing targeting system.  It does not take away pressing R to target asteroids when no enemies are in the system.

# Proposal

The automatic catalog everything within scan range would be a minor feature and I think it makes the most sense.  It would also be a significant quality of life feature for mining players.  This is something that wouldn't conflict much with my existing PRs so I would be open to proposing a code enhancement right away.

This means you don't have to target an asteroid for it to catalogue.  It need only be in scan range.

Thoughts?

**Comment by tehhowch** [comment]
I shared this on the proposed change, but it bears repeating here:

I think what I would prefer, to address

> There is no good way to identify systems that have mine-able asteroids. While the outfitter will update the map with materials, it will only do so for systems where you have actually mined that commodity. This makes building a map of mine-able resources a tedious manual process which further discourage folks from mining.

is a map layer that reflects which systems you've been to that have _any minables at all_. After all, you don't need an asteroid scanner to notice a minable right in front of you.
That would maintain the mystery of exactly what is in a given system until you've gone and explicitly "_Found it!_", while easing the "How do I get started doing this?" factor.

**Comment by Zitchas** [comment]
Perhaps a compromise, building on Tehhowch's suggestion, of having the automatic mapping generate data for a map layer that shows the *density* of mineables in a system; but still requires an asteroid to be targeted and/or destroyed to put that specific mineable on the list of stuff present in that system.

So the automatic mapping will give players a good idea of where there's lots of stuff to mine (or where not to bother); but the player still gets to discover stuff for themselves in the details.

**Comment by williaji** [comment]
I honestly don't understand why people are concerned about fully automatic mapping. If the concern is making mining "too easy" consider: 
1) You have to buy an asteroid scanner. At 122K this is 25% of the cost of your initial ship and expensive in terms of both cash and outfit space in the early game. You have to re-jig your ship in many cases to even fit one in and good advice is to drop your hyperdrive to get more cargo space. As an aside, I don't *like* to fly with asteroid scanners because they mess up my targeting. they are, frankly, annoying unless you are actually mining. So, keeping on in is an expression of intent and a gaming action.
2) You have to fly through the systems to map them. Now mostly you are going to be doing this when you are running other missions. But the map will only ever cover where you have traveled. 
3) You have to review the map, decide on the profitability of the location and then go and mine. This behavior is no different than what the map provides for regular commodities. If it's not unbalancing for trade, I don't see how it can be unbalancing for mining.
4) You still have to manually fly your ship, mine the minerals, land and sell them. These tasks are far more intensive game experiences than most normal trading and missions.
Frankly, mining is a hard task requiring patience and good dexterity. It can be profitable in the early game and help you get your second or third ship, but it requires game time dedication to pull off. I doubt many people mine on a regular basis or after they get a first freighter. This change is just about trying to make it easier to work out where to go to do that.

**Comment by samrocketman** [comment]
"Clippy moment": @williaji you might also like https://github.com/endless-sky/endless-sky/pull/6669 :smile:
