### ISSUE TITLE
Make it easier to sell individual plundered outfits

### ISSUE THREAD

**Issue by mrec** [endless-sky/endless-sky#712]
Currently it's easy to sell _all_ plundered outfits via the Trading screen, and it's possible to sell individual plundered outfits via the Outfitter screen. However the latter is
- Clumsy - it's a very big and noisy screen, and visually filtering out the "in cargo" labels from the "installed" and "(not sold here)" is a bit tedious
- Not available on planets without an outfitter. Which seems inconsistent; if can sell all of them here, why can't I sell one of them?

Proposal: when landed on a planet with a Trading screen available, then instead of disabling the "Dump Cargo" button in the ship information window, change its text to "Sell Cargo" and have it do that instead.

I always end up going to ship information anyway to see what I missed when I'm trying to sell "everything except X", so it feels like a natural place to put this, and all the UI scaffolding is in place already.

**Comment by LocalGod79** [comment]
perhaps adding colour coded grid layers (or nested halos) behind outfitter sprites rather than text near the bottom (near where more text appears when outfit is selected).  coupled with collapsing categories, should streamline outfitter interface drastically.

some quick (rough) grid sprites i whipped up to help visualize;
outfit in cargo;
![outfitter unselected cargo](https://cloud.githubusercontent.com/assets/16969517/12696840/63dd578a-c742-11e5-8fe9-4c5989cd84b8.png)

outfit installed;
![outfitter unselected installed](https://cloud.githubusercontent.com/assets/16969517/12696843/63e07a50-c742-11e5-9e09-567864222d4f.png)

outfit not available here;
![outfitter unselected unavailable](https://cloud.githubusercontent.com/assets/16969517/12696841/63dd59a6-c742-11e5-94c9-42562af13aa0.png)
outfit installed, in cargo, and not available here.
![outfitter unselected uic](https://cloud.githubusercontent.com/assets/16969517/12696842/63dd78d2-c742-11e5-86b3-3cd38fd31676.png)

**Comment by mrec** [comment]
I don't think collapsing categories *per se* would help in this case, since you'd need to know what categories your cargo outfits were in.

A more comprehensive filtering approach that would **only** show outfits in cargo, but a) sounds like a lot more work than the cheap and cheesy proposal here, and b) still wouldn't address the inconsistency problem, since you could still only sell cargo outfits at an outfitter,

Conversely, there was a suggestion recently to always offer an outfitter when you had outfits in cargo, which would help a lot with consistency but less so with filtering.

**Comment by Amazinite** [comment]
I think that this might be fixed thanks to the ability to specify what outfits show while in the outfitter; you can switch to only showing what's in cargo, making selling plundered outfits easier as you don't need to scroll around looking for what to sell.
