### ISSUE TITLE
New sub-sonic wave weapon

### ISSUE THREAD

**Issue by ProNooberEX** [endless-sky/endless-sky#7120]
### Problem Description

Currently in endless sky, all of the weapons deals damage toward either the health, fuel levels, heat levels or shields levels. For many experienced players, they might felt bored at the prospect of these levels after a while.

### Related Issue Links

*

### Desired Solution

A good solution will be to provide a weapon that damage the ship internally in some way. A good example of a new outfit weapon that does this is a sub-sonic wave weapon, which kills off crews one by one if expose to it. This weapon's ideas aren't advanced at all; 21 century scientist had already shown that servere levels of sound waves that are below 20Hz could cause nosia, diariea, and death if exposed long enough.As the game already had the setting that too little crew will cause severe drawback in operating a ship, the game mechanic can continously deduct one number from the total hired crew if the ship's collision shape is exposed to the weapon for x seconds, where x can be adjusted to prevent overpowering. If all of the crew are gone using this manner, the ship will stop being able to controlled by the player or ai, instead, floating in space until the attacker, using the weapon, came up and board the ship. The weapon can either fire a laser like beam of sound at the taregt, or sound wave like projectiles toward the ship. For the later option, instead os using x seconds, x amount of these projectiles upon hitting the ship will deduct a crew from the enemy ship.

### Alternative Approaches

*

### Additional Context

*

**Comment by ProNooberEX** [comment]
This weapon is aimed as disableling a ship rather than destroying it, similar toward heat weapons such as flamethrowers. However, this weapon had a significant advantage of not harming the shield or the hull itself, making the boarded ship less vunerable after boarding in a major cross-firefight.

**Comment by ProNooberEX** [comment]
Also this weapons enables 100 percent success when trying to board(Disabling a ship completely with this weapons means killing off all the crew, therefore the defense value of the enemy will be 0)

**Comment by Zitchas** [comment]
While this is a valid potential weapon - as you say, weapons designed to target people specifically and leave structures intact are a thing in the present day.

There's a few reasons this weapon is unlikely to ever be even considered for addition to the game:
1. The disable/capture framework is currently considered severely overpowered; a weapon that makes this easier, faster, or more reliable is unlikely to be added to the game.
2. The structure of the current boarding/capture system is currently utilized to make it virtually impossible to acquire certain ships. Adding a weapon that allows ships to eliminate crew from these ships would nullify this block.
3. Having a ship weapon that kills crew would allow much smaller ships to capture much bigger ships than is currently possible. Currently, the general consensus is that we need to work on *leveling* this gap (as in, making it harder for a ship to capture something bigger than it), not increasing it. This weapon's principles would go directly against the changes we feel are necessary to improve the game.


That being said, I could see a case for the *mechanics* for this being added to the game for plug-in support; and likewise I could see there being justification for these mechanics being used for late-game unique weapons or specials; but that's probably not a priority right now.

As an improvement on this:
- First, have it require shields to be dropped. This would mean that the agressor needs to actually achieve real combat gains before crew can be affected.
- Second, have crew have hp. So instead of a hit killing some crew, it's a hit damages some crew. This means that just hitting the ship once doesn't do anything, but rather the ship needs to work to keep its weapon focused on the target in order to start eliminating crew. 
- Thirdly, have it be temporary. So it isn't killing crew, it's temporarily disabling them, and they'll start to recover almost immediately after the ship stops being hit. This would shift it from being an OP "kills all the ship's crew" weapon to a "temporarily weakens the ships crew" effect. This would make carrying more than the minimum required crew actually useful; and if such weapons were common, it would make medbays and medical outfits useful as well.
- Lastly, since it isn't actually killing crew, they're still present to fight off boarders. Injured crew would probably fight at a penalty until they've fully recovered, so there's still some benefit for the attacking ship; but since it isn't actually eliminating crew, it should allow most of the current capture-blocking strategies to be moderately effective against them.

**Comment by thvk-net** [comment]
I like the idea but I would like you to consider the following: Is there air in space? Because sonic waves need a medium to spread in.

But this is only an argument against the specific weapon proposed by you not against the idea of having weapons with the same effect.

**Comment by Pointedstick** [comment]
Good idea for a plugin, but not for the base game for reasons mentioned. Thanks anyway though!
