### ISSUE TITLE
Escort missions are too easily exploited.

### ISSUE THREAD

**Issue by masterpierround** [endless-sky/endless-sky#715]

**Comment by masterpierround** [comment]
Whoops, forgot to add comment. The problem is that ships outside of your system cannot die. When you take an escort mission, all you need is a fast ship, and outrunning the ship you're supposed to be escorting will keep that ship alive until it catches up. Since you can easily make money off of escort missions by not escorting, they are stupidly good at making money for you.

**Comment by Gkramme** [comment]
I agree, but imagine all the time it would take to implement a system where the game tracks all the ships in all the systems your escorts are in. It would take a ton of coding and slow down your computer to a 1 fps rate.

**Comment by mrec** [comment]
A compromise might be to have the escorted captain get stroppy and refuse to pay up if you left them alone for too long. Doesn't require simulating events in other systems, and removes the perverse incentive.

**Comment by Gkramme** [comment]
@mrec, I like your idea! Maybe instead, they only would pay you half price. But that would be confusing for new players.

**Comment by zwparchman** [comment]
Leaving your escort isn't taking advantage of the mission, it's leaving your paycheck on the table. Capturing the attackers, selling their ships, and re-investing in bettering your flag ship can get you a medium (or possibly heavy) warship in under one in game year. The missions scale nicely with your combat rank so that the ships you protect your escort from are captureable with a suitably equipped ship that you have had the time and funds to acquire. 

I'm not convinced there is anything to fix here. Leaving your escort is playing sub-optimally, and no matter how easy that makes the mission you would be far better off fighting.

**Comment by masterpierround** [comment]
To me, it doesn't matter if doing it gets you a smaller paycheck. The fact is, you can make a profit by doing the opposite of what the game tells you to do. To me this is a problem. My theoretical fix would be that if you go too far away from the ship you should be escorting (2 systems away?) there is a chance that the ship you're escorting becomes disabled. You weren't there to guard it, now look what happened. If you stray too far ahead, you will then possibly be forced to spend time returning to the ship and repairing it, which could cause you to miss your deadline if done too often.

**Comment by lehgogh** [comment]
@Gkramme, we could just check how many systems away a particular ship is each time you jump. You wouldn't have to keep rendering each ship; you'd just have to get what system it's in.

**Comment by Gkramme** [comment]
@lehgogh, But how would damage work like this?

**Comment by lehgogh** [comment]
@Gkramme: I'm not sure if we can damage/disable ships that aren't in the current system, but we could use the compromise mentioned earlier.

**Comment by Gkramme** [comment]
@lehgogh, sounds good!

**Comment by Wrzlprnft** [comment]
How about the ship you have to escort just stays like a parked ship there in case you get a system ahead, and once you are in the same system, starts again. everytime you this happens the payment decreases to 0.95
Would need a official introduction ingame of the "waiting till fleet is ready by holding down J" mechanic though
alternative, the numer of the jumps the escorted ship makes without you jumping with it or being in the system it jumps in decreases the amount of money you get. so you could still speed it up by readying up for jump and instantly jump once the escorted ship arrives, while you escort it by the meanings of escort, kinda: if it's safe enough to wait for you, it will be safe enough for the escorted ship to jump in and jump out again

**Comment by masterpierround** [comment]
You need to be careful about doing anything just one system ahead. If, just before you jump, the escorted ship gets moved by an explosion, it's almost impossible to stop your jump fast enough to stay around while they re-orient.

**Comment by masterpierround** [comment]
Also, would it be nice if a small tutorial opened whenever you began a new mission type? James the tutorial guy takes care of this in the beginning, but there's nothing similar to introduce you to escort/bounty missions.

**Comment by natangold** [comment]
James introduces you to escort missions if you bought a Sparrow.

**Comment by lehgogh** [comment]
@Wrzlprnft: It would be difficult to override the default "jump to the flagship's system" mechanic for *only* escorts, though I'm sure it's possible.
@masterpierround: Optimally, the escort would have to be two/three systems behind before you lose part of your pay, fail the mission, etc.

**Comment by natangold** [comment]
@lehgogh Problem: Let's say I pick up a merchant at Winter (in Yed Prior) who wants to go to Longjump (in Sabik, four jumps away). I have a jump drive installed on my flagship, so my shortest route is via Zubeneschamali (six hyperdrive jumps from Yed Prior). Should I get penalized if I take the automatically chosen route? Realistically, probably - for abandoning my escort in pirate country - but from a gameplay perspective, it would be annoying. And if it ain't broke…

**Comment by lehgogh** [comment]
@natangold: Your escort would follow any route you take, and you would only get penalized if you are X (2-3) systems away from your escort.

**Comment by natangold** [comment]
@lehgogh If my escort doesn't have a jump drive, however, then it cannot, in this case, follow my path. So I would get penalized instantly, because when I jump into Zubenschamali, I'd be five jumps away from my escort (who'd be in… the system with Solace; sorry I don't have the game open at the moment).

**Comment by egilburg** [comment]
I support idea of escorted ships just not moving if you are not in either their system or a system adjacent to theirs.

You are paid to *escort*, not to fly solo to the destination and wait for them to come on their own!

**Comment by lehgogh** [comment]
@natangold I don't think the game even gives you escorts without jump drives. This would make the mission impossible, regardless of a minimum distance.

**Comment by mrec** [comment]
@lehgogh he's talking about jump drives, not hyperdrives. It's a rare outfit that can't be bought, only plundered or obtained via missions.

@natangold #713 is about the problem of jump drives and non-jump-capable escorts, but focussed more on the navcomp route calculation.

**Comment by lehgogh** [comment]
@natangold: Sorry; I didn't know that jump drives existed.

**Comment by masterpierround** [comment]
Really, if you have to escort a ship, you should have change your route to something it can follow.

**Comment by mrec** [comment]
@masterpierround agreed, but it's tedious to do so and very easy to miss the fact that you need to. Rather than letting the navcomp plot your route you have to shift-click (undocumented) on each step manually. If you get one step wrong there's no Undo so you have to start again from the beginning, and the only indication that your escort can't take a particular step is a very faint and equally-undocumented difference in line colour.

**Comment by masterpierround** [comment]
I'm pretty sure the escort follows your route if it is able. It wouldn't change anything unless you have a jump drive, in which case you'd have to manually plot the route. From what has been said here, you would only get penalized if you go around 3+ systems away from the escorted ship. That's enough room for error that a small jump won't incur penalties, but a jump that leaves the escorted ship more than 3 days away from your location will cause a small penalty to be applied. A loss of 5% of your pay for every time

**Comment by masterpierround** [comment]
Accidentally hit comment button. Continued: the ship jumps and ends up at least 3 jumps away means that even jumping to Zubenschamali like the previous poster described would only lead to a penalty of 10-15% of your income. That's not big enough to matter too much, but if it was accompanied by dialogue explaining the penalty, it would give the sense that abandoning the ship wasn't the right thing to do.

**Comment by endless-sky** [comment]
The current escort jobs (not counting special missions) are all either 3 or 4 jumps long, so the ships you're escorting will never be more than 3 jumps away unless you go in completely the wrong direction.

And, escort missions in the story line often don't pay anything, so there's no payment to adjust in the first place.

**Comment by masterpierround** [comment]
So if a pay decrease of 5% occurred every time the escorted ship jumped and you were at least 2 systems away, you would never lose more than 9.75% of your pay. Losing more than that would be mathematically impossible.

**Comment by masterpierround** [comment]
But then (and I'm sorry I keep posting again, is there a way to edit comments here?) for a player like me, jumping directly to the destination (and saving 3 days salary) is still a better choice, because the three days salary I save is worth more than a 10% reduction in my mission pay.

**Comment by Wrzlprnft** [comment]
<img width="937" alt="edit" src="https://cloud.githubusercontent.com/assets/15857993/12616882/7a9deb24-c50d-11e5-8a42-e880d1b63e47.png">

**Comment by masterpierround** [comment]
Not a button on mobile. RIP me :'(

**Comment by friagram** [comment]
Almost all of the escort missions are too easy, at least in the FW campaign. It's possible to just jump to the destination and wait for them to arrive, then land. This is quite noticeable if you have a jump drive, or a ship with very large fuel reserves.

One huge problem is that the escorted ships have their own faction, which is different than yours. If your escorts get attacked by pirates, and you are friendly with pirates, you don't even get a hostile alert. Something should be done that forces a sharing of hostile factions between escort and flagship.. If I am hostile with the Quarg/Republic/Whatever, and my escorts wouldn't normally be, they should be targeted and killed. If I'm friendly with pirates but they are swarming around a system waiting to kill my escorts, they should be flagged hostile and my ship should attack them.

Some solution should be made to this, so that players actually have to participate in the "escort" part of the mission. Perhaps a random chance in each system that the ships will be attacked and disabled/destroyed if they are forced to fly though alone. 

Another option would be to handhold the ships through each system, though this would be annoying.

**Comment by vanesa79** [comment]
You found [escortsbarcelona ](http://www.escortsbarcelona.com/en/escorts-barcelona/)what you were always looking for, a safe place, full of trust, totally discreet and willing to assure you to spend the best time posible with us.

**Comment by jafdy** [comment]
@vanesa79 That is inappropriate, unproductive and completely uncalled-for. Can you please refrain from this kind of content in the future.

**Comment by tehhowch** [comment]
(pretty sure that's a bot / ad account)

I reported the account to GitHub so it should hopefully disappear soon.
