### ISSUE TITLE
Dyson spheres?

### ISSUE THREAD

**Issue by Gkramme** [endless-sky/endless-sky#722]
In addition to ringworlds, the Quarg need an interstellar power source for such an advanced civilisation (type II). I know that there are three types of advancement for civilisations, (1, 2, 3, 4) humanity would be a type 1.05, Hai/Korath would be 1.25, Wanderer 1.55, Pug, 2.15, Quarg 2.25, and Dark would be 3.15. A type two race has dyson spheres, to tap tons power from stars. If the Quarg can make ringworlds, should they also make dyson spheres?

**Comment by endless-sky** [comment]
That was originally what I planned to put in World's End in the Pug galaxy,
but making good-looking Dyson Sphere graphics turns out to be challenging...

**Comment by Gkramme** [comment]
@endless-sky, wouldn't that just be a star image? Having an advancement scale could make things in-game much more intresting. And also, The pug are at a 2.15, not a 1.75.

**Comment by endless-sky** [comment]
I meant that it would be artistically challenging, not that it would be
technically challenging. :) Creating something that big that looks
sufficiently detailed and realistic is hard.

Also, like with the ringworld, my goal was to construct it out of multiple
interlocking sprites instead of one big one, so that the same set of
sprites could be used to create spheres in all different states of
construction or decay.

**Comment by Gkramme** [comment]
@endless-sky, I could try that. Where did you make your models?

**Comment by Nightmareman** [comment]
They don't have to make Dyson spheres to be considered type II having ring worlds around multiple stars would be enough to be considered type II. Besides the creation of ring worlds is much more efficient then building a Dyson sphere as you can just have the ring constantly rotating which would create enough inertia for the inhabitants to live on the inside of the ring without the need of any sort of artificial gravity generators. You can't do the same with a Dyson sphere as only the area near the equator of its spin would produce the required inertia the rest of the inside of the sphere would have to use some other sort of artificial gravity which would be a waste of energy since the whole purpose of a Dyson sphere is to harvest all the energy provided by a star. Plus the resources needed for the construction of an entire Dyson sphere is much greater then that of a ring world. Logically it would be better to just construct several ring worlds rather then a single Dyson sphere. Also you would have to consider that the construction of a Dyson sphere would also eliminate the Heliosphere that a star creates making the system vulnerable to all the things that the Heliosphere would normally protect from.

**Comment by Bladewood** [comment]
The Pug are more advanced than the Drak.
They have wormholes.
The Drak do not.

**Comment by Gkramme** [comment]
@Nightmareman, ah you think that dyson spheres are inhabited. They are not. They cerate massive ammounts of power, and are easier to cerate, just surrounding a star with solar pannels. Also, these systems would be planetless stars, so no damage to the nonexistent planets. I cannot tell you what a dyson sphere is in detail, so if you would want to know more, feel free to look it up.
@Bladewood, The Drak are the galatic overseer. They are so powerful that they can tear apart stars, make planets, and subdue even the most powerful races. They are the most advanced race by far. The Drak were the ones who set up the wormholes in the first place.

**Comment by natangold** [comment]
@Gkramme My current headcanon: The Drak are interdimensional creatures like the mice in the five-book *Hitchhiker's Guide* trilogy. They can appear in our dimension as…however the Quarg see them, and are also the Pugs because of the lolz.

**Comment by Gkramme** [comment]
@natangold, nice reference! Good series. It could be that way, or the two are cooperating galatic powers, one as the military for big issues, one as the police for smaller ones. And lolz, ?

**Comment by masterpierround** [comment]
I think the Pug are underneath the Drak in the galactic hierarchy. Why do I think so? For one, they seem to have weirdly similar goals (universal peace, mainly) but the Pug actually go out and enforce it. Additionally, the Pug are described as a sort of hive mind. Although this is not necessarily proof, it would be far easier for the Drak to control a hive mind than it would for them to control a species of individuals.

**Comment by jafdy** [comment]
The Drak can not create artificial wormholes only the pug have the ability to do that. If you talk to the Quarg after the pug appear then they tell you that.

**Comment by Gkramme** [comment]
@jafdy, oh, really? I guess the Pug make wormholes for the Drak then.

**Comment by Nightmareman** [comment]
@Gkramme I know what a Dyson sphere is also they are actually harder and more resource intensive then a ring world as they have to fight against the constant pull of the stars gravity while a ring world has an easier time of this because of its constant rotation creating centrifugal force which not only lessens the stress created by the stars gravity it also could be used to make the whole interior side of the ring habitable. Also when I refer to the fact the system would be left vulnerable because of the Heliosphere being eliminated I am not talking about planets. I am talking about the structure itself and the ships that would be in system it would also make maintenance on the outside of the Dyson sphere more hazardous then that of a ring world. So why bother when you can get a better return for effort with ring worlds. Generally when people think of Dyson spheres they think of the Shell variant or Bubble variant both of which have the problem of having to deal with the stars gravity as they cant use an orbit to keep from falling into the star.

**Comment by LocalGod79** [comment]
theoretically dyson spheres can be created at a distance where the force of the solar wind (which you seem to be ignoring) equalizes the gravitational pull, and no rotation is required.

**Comment by lor1113** [comment]
The force of solar winds DOES NOT and never will counter the pull of a
stars gravity, sorry

**Comment by LocalGod79** [comment]
you're a physicist?

**Comment by LocalGod79** [comment]
fact: solar wind from our sun exerts a force of ~0.7 g/m2 at 1AU -
sufficient to create a statite condition.

plainly, an object with 1 square metre of surface area facing the sun,
having a mass of 0.7g, at the earths distance from it, would be blown with
the same force as the sun's gravitational pull, and would "hover above" the
sun.

just because we can't do it yet doesn't mean it's not possible.

not sorry,
-LocalGod79

**Comment by endless-sky** [comment]
Fact: grams are a unit of mass, not a unit of force. :)

Wikipedia's article on solar sails says that an 800m x 800m solar sail generates 5 N of thrust. The acceleration due to gravity at 1 AU is about .006 m / s^2. So, for that solar sail to cancel out the force of gravity, its mass must be:

5 kg * m / s^2 = (sail mass) kg * .006 m / s^2
sail mass = 833 kg = 1.3 g / m^2.

That's nearly doable with current solar panel technology, but in terms of strength it would be more like a Dyson soap bubble than a Dyson sphere.

**Comment by Nightmareman** [comment]
@LocalGod79 The cost of building energy collectors supported by solar sails would make it not worth the effort as the solar sail itself can't be used to absorb any light to create energy as it has to reflect almost all the energy that hits it so it can support the structure attached to the solar sail so you would end up having huge solar sails connected to proportionally small energy collectors this makes the whole endeavor very inefficient. So why bother when you can just use those same resources to create rings around multiple different stars which would be both easier and far more efficient.

**Comment by LocalGod79** [comment]
again, just because we cannot currently do it feasibly, doesn't mean that it can't be done.  there are other (structural) properties inherent to spheres that are advantageous over rings...

i think we can all agree, though, that completed dyson spheres would be difficult to make graphically appealing within endless sky (as interesting a concept as it is), and rings, or arrays are probably more worthy pursuits within the game...

**Comment by rktaylor** [comment]
Dyson Spheres could just be a Sun sprite, since we already have different types of suns. Could just be the image of a sun mostly-occluded by "rectangular" blocks around it, with sunshine coming through the cracks.

If it's a star sprite and not a component sprite, it should be easier to implement.

Also a Ring World doesn't need a Dyson Sphere (though I think DS should be in the game.) Ring Worlds would, feasibly, have massive curved solar panels between them and the sun that would rotate slightly faster (closer to the sun) than the ring, spaced apart in such a way to give a 24 hour day/"shade" cycle.

**Comment by jafdy** [comment]
@endless-sky : I think calling it a "Dyson soap bubble" would be dramatically over estimating it's strength. Also were are you finding the 1.3g per m^2 panels?

@LocalGod79 : While it may at some point be possible to use super light panels to make a "Dyson soap bubble" in all likelihood it would be better (cheaper/more efficient/easier) to simply mount heveier and more efficient panels on an orbiting ring. This ring need not even block light from reaching the ring world. Also the stability of this bubble would be reliant on a fairly even and stable solar wind, the first solar flair could tare a hole in it and bring your entire construction crashing down.

**Comment by Gkramme** [comment]
@Nightmareman, the key point here is POWER. Ringworlds do not cerate power, and therefore are worthless in power needs. It would be much more resource efficent to launch a bunch of interlocking solar sails around a sun than to deconstruct an entire gas giant to make a ringworld.
@endless-sky, thank you for clearing that up. :)
@jafdy, think of it in this way: a ringworld still blocks light from planets in a similar orbital plane, so it really makes no differance.

**Comment by rktaylor** [comment]
@Gkramme I think we're speaking past each other. See: http://www.larryniven.net/media/ringworld1024x768.jpg

This is what I mean. That inner "ring" of panels act both as shade for a day/night cycle and as solar collectors. We already know, broadly, how you'd "get" that power from the satellites to the ring, and, therefore, to ships. https://en.wikipedia.org/wiki/Space-based_solar_power#Microwave_power_transmission

**Comment by Gkramme** [comment]
@rktaylor, I understand what you maen by this, but in a system to inhospitable for a ringworld, a dyson sphere would produce much more power at the expense of very little.

**Comment by Nightmareman** [comment]
@Gkramme A Dyson sphere is impractical when compared to a Ring world regardless of technological level for the following reasons.
1) You could easily use a Ring world to create tons of energy if you wished you could have very large solar collectors sticking out of the sides of the ring it would essentially be thin layer wise when compared to the thickness of the main central part of the ring but could be much wider.
2)The cost of the Dyson sphere would be far greater then that of the Ring World the sheer material amounts would be greater then that of a Ring world. For example even if you created solar sails that had a 100% reflection rate (which is probably physically impossible) and had solar collectors that had the exact same weight per square meter of material necessary and also had a 100% efficiency of energy collection and conversion (again probably physically impossible) the best you could get is 50% of the energy that is hitting the whole structure. This isn't even including the weight of whatever device you are using to transmit energy to the structure that is actually using it and the natural loss of energy you would experience in the transmission and conversion again at that structure. Also this isn't even considering the fact that if you used solar sails they would likely be very thin and very fragile so any number of natural occurrence would tear them to pieces such as small meteoroids even space dust could be damaging, plus any of the extreme yet normal solar activity would put the solar sails in danger such as solar flares, or coronal mass ejections protections from such things would make the Dyson sphere even less efficient at energy collection.
3)You could make a energy collection only ring world in systems that are just not suitable for a habitable ring world. In this case the ring would essentially be only energy collectors and transmission stations or manufacturing stations in this case the spin of the ring could be put at a speed where it is basically just in an orbit so the physical stresses it would be under would be far lower then that of a normal Ring world meaning it could be made much thinner and as such would be much cheaper and easier to build.
4) Even if you had the technological ability to make a Dyson sphere the only real reason to actually make it would be to show off your technological prowess to everyone else rather then as something to be practically used. Even if you created some super near invincible like material that was so strong you could use it to encase the star without worry of collapsing it would still be impractical as the amount of resources and energy used to create the sphere would probably outweigh the benefit of its creation.

**Comment by jafdy** [comment]
That last point sums it up. When the Dyson sphere was originally conceived it was as a "swarm" rather than a solid sphere. Any solid Dyson sphere would be be holding itself in place by structural strength not solar wind or orbiting.

**Comment by Gkramme** [comment]
Think of it in this way: if p is the amount of power a rimworld creates, than p•x (where x is the number of times larger area that the Dyson sphere covers) shows how much greater power output a Dyson sphere produces.

**Comment by Bladewood** [comment]
This is an entertaining thread.

**Comment by Gkramme** [comment]
I do think so ; )

**Comment by Bladewood** [comment]
Minor nitpick: Dyson spheres have volume, not area, correct?

**Comment by Gkramme** [comment]
@Bladewood, I used surface area because that effects how much power is picked up, not volume.

**Comment by Nightmareman** [comment]
@Gkramme Reread my whole comment specifically points 2 and 4 and you would realize just how impractical Dyson spheres are this includes both the bubble and shell variations.

**Comment by lehgogh** [comment]
Should we assume that in the game, alien species like the Pug have light/strong enough materials to make Dyson spheres? I mean, we've been arguing for a long time on the technicalities. It's sci-fi; if we want something to be possible, all we have to do is come up with an explanation.

**Comment by jafdy** [comment]
Yes but that's no fun.

**Comment by Gkramme** [comment]
Dyson spheres are possible, but not at our current level of advancement. Just because we can't do somthing now doesn't mean it's not possible. Beleive, people! :)

**Comment by lehgogh** [comment]
According to the original post, the Pug, Quarg, and Drak should already be advanced enough to build Dyson spheres. We may not have the materials, but they might.

**Comment by Gkramme** [comment]
Exactly.

**Comment by Nightmareman** [comment]
You guys obviously aren't reading the entirety of my comment if you did you would realize that a Dyson sphere is impractical regardless of how advance you are its just not worth the effort.

**Comment by Gkramme** [comment]
Please read this: https://en.m.wikipedia.org/wiki/Dyson_sphere#Dyson_shell
A direct quote from the article:
"A spherical shell Dyson sphere in the Solar System with a radius of one astronomical unit, so that the interior surface would receive the same amount of sunlight as Earth does per unit solid angle, would have a surface area of approximately 2.8×1017 km2 (1.1×1017 sq mi), or about 550 million times the surface area of Earth. This would intercept the full 384.6 yottawatts (3.846 × 1026 watts)[22] of the Sun's output. Non-shell designs would intercept less, but the shell variant represents the maximum possible energy captured for the Solar System at this point of the Sun's evolution.[21] This is approximately 33 trillion times the power consumption of humanity in 1998, which was 12 terawatts.[23]"

A ringworld would cerate much less energy, therefore being less effective.

**Comment by Gkramme** [comment]
Also using the equasion E=mc2, you could thereotically cerate matter from the energy output from the star.

**Comment by Nightmareman** [comment]
@Gkramme 1) I have already read that plus I have read far more detailed papers on every version of a Dyson sphere. Also if you actually read that whole page it would list a huge number of problems that come with the Dyson sphere and that is only a fraction of the problems that come with building one its a wiki page so its natural it isn't going to tell you everything about it if you would do actual research you would realize just how bad of an idea both the Shell and Bubble versions are.
2) It doesn't matter how much energy it produces if the production of the structure is impractical which is what I was trying to explain to you but you ether didn't read the comment or just failed to understand. Whichever reason it is I can't help you understand it anymore then I already tried. This situation kind of feels like the number of times I have tried to explain to people why you can't create a perpetual motion machine they just don't get the concept of why it would never work no matter how I try to explain it to them.
3)Yes matter and energy are interchangeable but if you realized how much energy it takes to create matter you would realize you aren't going to be doing it to create a Dyson sphere.
4)If you really really wanted to harvest nearly ALL the energy produced by a star the multiple Ring Worlds of different sizes and orbits would probably be the only practical way to do it. That is assuming you had the technologies necessary to create all the safeties necessary to keep the Ring worlds all in their proper spots to keep them from colliding into each other or unnecessary obstruction of line of sight to the star even in the event one or multiples have catastrophic failures. Of course there will always be some small amount of obstruction but this could be limited if the rings were placed properly.
Even then you would still be eliminating the Heliosphere just like with a Dyson sphere which means every ship and structure in that system is going to have to deal with all the problems that come with eliminating the protection the Heliosphere provides.

**Comment by Gkramme** [comment]
In cerating a ringworld, you need to dismantle all planets in the system and then you still can only build ONE, therefore removing any chance of another. Ringworlds are also more impractical than a dyson sphere, and the materials needed to make one can produce about 2 dyson spheres. A ringworld would consume many more resources than what is needed to make different structures of similar capacity. Again, these both are ways of advanced races showing off their might (not unlike America itself).

**Comment by Nightmareman** [comment]
@Gkramme 1) Did you actually do any real research or are you just making things up? By the way that is a rhetorical question. As I already know that you don't understand the science behind ether.
2) Creating a Dyson sphere takes far more resources then a Ring World and the only Ring Worlds that actually take a comparatively large amount of resources are ones that are inhabited as they would have to be able to withstand the centrifugal force that is used to produce artificial gravity for the inhabitants. Ones that are only used for energy production don't need to be spinning that fast and as such would be much thinner they could also easily be much closer then the inhabited one reducing resource cost even more. Also since they don't rely on something like a solar sail to stay in position they can have energy collectors on 100% of the side facing the star they surround.
3) As I said several times in my previous comments the Dyson sphere is impractical in every way resources used are much higher, elimination of the Heliosphere makes the Dyson sphere and all ships entering the system vulnerable to all the threats the Heliosphere normally gives protection from. The solar sail Bubble version would have vulnerabilities to well pretty much everything as the sails would be a major weak point and almost anything could cause critical damage to them even the normal solar activity such as solar flares and coronal mass ejections could tear holes in the sails not to mention the normal debris found in space such as those the Heliosphere protects from. The solid shell version would be very resource intensive even if you invented some near invincible material allowing it to support itself without the need for solar sails. As the time and energy required to produce such a material would like make it cost prohibitive. Result is both versions wouldn't be made out of actually efficiency or need but rather as a status symbol like a huge statue or a race car not practical for actual use but you could show it off to everyone else to try and make them envious. That is of course till they decide to shoot at it or throw some rocks at it causing it to collapse into the parent star very quickly. Ring Worlds of both types have actually practicality of construction and use oh and even in the event of catastrophic failure they wouldn't just fall into the star so you would have more then enough time to effect repairs or at very least stabilization measures. 
4) The point of deconstructing all planets in a system isn't for the sake of just resources as the number of planets, moons and asteroids will variate greatly from system to system the reason you would dismantle all the planets and asteroid fields is so you don't have to worry about their gravitational pull disrupting the Ring Worlds orbit same goes for a Dyson sphere you wouldn't want the planets pulling on the sphere changing its position relative to the star. You could choose to use all the resources available on a Ring World for habitation by making it wider for a larger possible population or less by making it a bit thinner so saying that a Ring World requires all resources from a system is absurd as amount of resources will vary greatly and the width of each Ring world could also vary greatly as would the diameter as each star is different and has a different habitable zone.

**Comment by Gkramme** [comment]
Look up practicality of a ringworld. Plus this is supposed to be a in-game feature, not a hot debates center. If evreything in the game was based on plausability, I do not know what would be f the game and it's ships. It would just look cool.

**Comment by lehgogh** [comment]
How about this: The oldest Pug/Drak/Quarg worlds have Dyson spheres as a sort of artifact; a reminder of the past when Dyson spheres were considered the superior form of energy production.

**Comment by jafdy** [comment]
Or some one would build a Dyson sphere on a sort of 'galactic crossroads' as a statement of power.

**Comment by Gkramme** [comment]
Thats the whole reason for thatt.

**Comment by lehgogh** [comment]
So, should we just put them at the oldest/largest Pug/Drak/Quarg systems?

**Comment by lehgogh** [comment]
Also, it would have to be around a star that is not the only star at the system (they still need a visible sun) and does not move (it would be hard to get the sphere to orbit at the same speed as the star). Perhaps a system that has a central star with a Dyson sphere and a star orbiting that star?

**Comment by Gkramme** [comment]
Yes, and yes. They could be in a inhospitable system, but I dont really think they block the heliosphere. It would be like Chicago blocking out the magnetic feild.

**Comment by natangold** [comment]
Given that (a) the purpose of a Dyson sphere is to gather [utterly ridiculous quantities of] energy, and (b) all species in Endless Sky have access to FTL speed / communication through the hyperlinks… why would the creators of the Dyson sphere need to live in the system with the sphere? Obviously, that's necessary without access to FTL, because you need to be close enough to be able to *use* the [ridiculous quantities of] energy (rather than shoot it across lightyears of space and hope nothing intervenes in the years it takes before it arrives where you want it). But with hyperlinks, an alien species capable of creating a Dyson sphere could simply direct the raw power through a hyperlink and into one or more nearby inhabited systems. Effectively, the Drak / Quarg / Pug / whatever could literally turn one inhospitable system into the powerhouse of their empire.
