### ISSUE TITLE
Possible Quarg intro mission typo/incorrection?

### ISSUE THREAD

**Issue by toilethinges** [endless-sky/endless-sky#723]
label quarg
			`	"the moon of a great gas giant, on a planet most small"
Is it calling the great gas giant a planet most small, or the moon a planet?

This is probably for a reason, but it seems wrong to me.

**Comment by endless-sky** [comment]
The Quarg don't all speak perfect Human. I didn't do a terribly consistent job of this, but I tried to have each alien species speak in a slightly different way to indicate that each of them is translating their thoughts from their own language into human language, and that each species thinks in a slightly different way. So:

* The Quarg tend to use archaic language constructs, as if they learned human language thousands of years ago and haven't caught up with the modern changes (e.g. using "most" as an intensifier instead of a superlative).

* The Pug (especially the Unfettered) make small grammar errors, particularly leaving out articles or inserting them where they aren't needed (indicating that they have a language like Latin that has no articles).

* The Wanderers' conversation includes multiple alternative translations in brackets because you're using a translation machine, and it's encountered a word with no precise human analogue.

As for the question of whether a moon can be a "planet," the game uses "planet" generically for any world you can land on regardless of its size (including moons). I suppose I could use "world" instead there, but as in Firefly I've been trying to use that mostly as a human slang / vernacular term.

**Comment by toilethinges** [comment]
Okay. Thanks, and... did you mean Hai in the middle paragraph? I haven't yet encountered any Unfettered Pug yet... also, thanks for making such a brilliant game. Endless Sky is definitely my favorite free game of all time, and it even beats a lot of paid ones I've played.
