### ISSUE TITLE
New type of damage that increases ship's effective mass

### ISSUE THREAD

**Issue by endless-sky** [endless-sky/endless-sky#725]
That is, this would reduce the ship's turn rate and acceleration. (An alternative would be an effect that adds "drag," but that would make it easier for a ship to flee to hyperspace, whereas adding mass would make it harder.) Like the ion effect, this would slowly dissipate over time, and might be accompanied by some sort of animations to show how badly affected the ship is.

**Comment by jafdy** [comment]
A nice Idea but what kind of weapon are we talking about? A space glue gun? A mass increasing beam? I think this would be a nice effect to have it is just the problem of how.

**Comment by jafdy** [comment]
Just occurred to me but projectiles with this effect might be a problem as logically the mass on the other ship would come from the projectile would have to have come from your ship at some point. Simply projectiles would have to weigh something on your ship.

**Comment by Wrzlprnft** [comment]
maybe say they just simulate a bigger mass for the computer so the ship acts different.

**Comment by DingusShingleton** [comment]
I think it's doable. It could be a weapon that warps the space-time continuum, like a localized targeted gravity gun. If jj abrams can get away with "red matter" I don't see why this is too much. Obviously it would have to be some seriously advanced secret alien technology with a crazy quest line to even be available to the player, if it even was. Or perhaps it could be a weapon that was only available on one ship cause the ship has to be purpose built for this technology, and then it's a question of balancing it so that everyone doesn't just use that ship all the time.

**Comment by jmhorjus** [comment]
I love this idea.  Just put "gravity" (or "graviton"?) in the name of any weapon that produces this effect and it will make enough sense.  Gravity Blasters, Graviton Beams, Gravity Torpedos.  You could do the works. :)

**Comment by jafdy** [comment]
Ok I think the what weapon problem is fixed, now it needs to be balanced. If a mass increasing weapon  had a noticeable effect then I would want as many as I can get. Could make them unbuyable.

**Comment by natangold** [comment]
@jafdy Does mass "damage", but very little shield or hull damage? Slows the hell out of ships, but does little direct damage, only makes it so that fast, maneuverable ships aren't.

**Comment by mdsmestad** [comment]
I love it! I want more damage types..maybe you could give the ship a sorta ora effect for the animation. Like a glow around the target

**Comment by jafdy** [comment]
This type of effect would still be incredibly good even if ships with only that weapon would be worse.

**Comment by jmhorjus** [comment]
This effect would probably be more of a cool and interesting (and hopefully not super-annoying) challenge for the player when used by AI ships than it would be something players were eager to exploit themselves - unless there were new *very* fast and maneuverable enemies with good regen designed to have these weapons as they Achilles heel.  
Since even a ship that can barely move can still fire back (using turrets at least) it doesn't seem like "gravity damage" will be intrinsically any better than heat or ion damage for purposes of disabling enemies.

**Comment by jafdy** [comment]
True enough. I guess you could always just add them and see what happens. 
If nothing else then it could be used to keep the player still for story line reasons.

**Comment by masterpierround** [comment]
The best part about creating new damage types is that it allows you to create new ships that would previously be horribly unbalanced.

**Comment by LocalGod79** [comment]
first off, thank you Michael for submitting the idea - i'm here now, and eager to contribute

next, thanks for everyone's feedback!

when it occurred to me, a weapon that temporarily adds mass is most easily explained as an "engine(s) disruptor" - sure explosions don't bounce affected ships around the way they used to - disruption of the disruptor field (ie, some thrusters fire unexpectedly), anyone?

coding should be pretty simple, i think - is it possible to duplicate and modify ion damage to affect mass rather than energy?

beyond that, how it stacks onto a target is dependent on firing rate vs. decay, which is mostly outfit/ship specific and subject to plugin testing.

related to this, perhaps a weapon that causes the target to behave as though it's under-crewed (with decaying effect)?

**Comment by endless-sky** [comment]
I've implemented this as "slowing damage" in 0492128.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
