### ISSUE TITLE
request(mechanic): Automatic recovery from being disabled

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#7266]
### Problem Description

I (and many other people) are frustrated when we get disabled. Perhaps we are in an uninhabited system, or maybe one where there are hostiles that have the "disable" personality who thus won't kill me, but can't be bribed to help me either. This leaves the player stranded just floating in space for all eternity.

### Related Issue Links

#4678 This issue is focused on adding attributes that allow a ship to have its hull and shield regen continue functioning even while disabled. While related, this is not the same thing. If 4678 was implemented, In many cases it would supercede this self-recovery. Basically, this self-recovery would be equivalent to the miniscule ramscoop ability that all ships have, whereas the ability for some ships to continue using their regen while disabled is having an actual ramscoop outfit.

### Desired Solution

Have a `"disabled recovery"` value for ships that specifies the base value for how long it takes that ship to recover from being disabled when it has the minimum amount of damage required to make it disabled.
- default value is 3 minutes.
- if set to 0, then the ship cannot normally recover from being disabled. (but could acquire outfits that allow it to do so)
- if set to -1, then it cannot self-recover from being disabled or benefit from outfits that allow it to do so.
- This base time would be modified based on how damaged the ship is. So the time indicated is at the disabled threshold, and when it is down to it's last remaining hull point the time would be doubled. So for a ship using the default 3min recovery time, if it had taken damage so that it was halfway through its disabled range, then it would take 4.5min to recover.
- Crew could affect this. Having more or less crew than the required crew count could change this time by +/- 25%. (probably a linear relationship, so having 5% extra crew makes the recovery 5% faster; but with a cap at 25%.

Recovery: This would be the ship resetting to its disabled threshold value +1 hull point. It could also be treated as if someone had boarded it with the "repair" option, which I think does the same thing. Basically, it becomes active again at the lowest possible hull value it can have.

It is expected that outfits would show up eventually that serve R2-D2 functionality, improving the recovery time of ships. I'd expect these to be subtractive, as in they subtract from the initial ship time to recover, with a hard limit that they can't reduce a ship to less than 1 frame until it recovers.

Note, the 3 minute default is what I think would make an effective value for keeping ships out of combat while not being an excessively long time to force the player to wait around. Perhaps adjust this 3min value to however long it'd take a player with no ramscoops to get enough fuel to hyperjump when their floating aimlessly in the deep void beyond the fence in the average system.

### Alternative Approaches

- Status quo where people get frustrated when they get disabled and can't do anything.
- Revamp the game to ensure that every system everywhere always has at least one neutral ship every few minutes pass through (said ship would have to be slow to ensure the player has a chance to talk to it before it continues on)

### Additional Context

Advantages to this:
- Allows the player the option to recover their ship instead of forcing a reload. (better for immersion.)
- This is better for stories. I feel more like recovering a ship makes for a better story experience than reloading. (Countless sci-fi stories and shows revolve around disabled ships getting disabled and repaired in space)
- This creates a built-in limiter for large ongoing battles like Mesuket. If ships start repairing themselves and either fleeing or re-engaging in battle, then going afk and waiting for dozens or hundreds of ships to get disabled for one to try capturing is no longer a thing. This would solve countless numbers of "Farming the Automata/Hai is OP" comments on here and elsewhere.
- It would allow the Remnant to resume their "Disable" personality (which is what they *should* have) without creating a risk that their systems build up numbers of Korath ships for the player to capture.

In terms of lore, it'd literally be "your crew searched for a solution for many minutes until someone tracked down a major malfunction to being the XYZ on the reactor. You replaced that, and presto, the ship works again." This happens more than once on Firefly, if I recall correctly. And many, many times in other sci-fi shows. This justifies the jump from "damaged and disabled" to "running and just barely healthy enough to function" without any intervening changes. Not all repairs have to be progressively incrementing the health of the ship point by point.

Caveats:
- As Tehhowch mentioned earlier in the #4678  , with such a self-repair system, the default and normal behavior for NPCs with the "Disabled" personality would be that they do *NOT* self-repair. They would continue to function as per the way they do now. That being said, it would be nice to have some sort of additional personality type that starts a ship out as disabled but *does* allow them to self-repair.  This could allow things like, say, a mission to destroy a large automata fleet that was disabled in the past and lost in space. It has drifted into range of a star and is regaining energy. Go destroy it before it can fully recover. So the longer the player waits, the more of those ships are going to have returned to life. Alternatively, if they can get to them really quickly, they could probably destroy quite a few of them. As a side bonus, this sort of mission would really reward people for flying smaller faster ships that could zip around to get all the ships in a spread out area. Or use fighters/drones.

**Comment by Zern9528** [comment]
I would rather just implement heal weapons.
And an AI that keeps a certain distance from hostiles, or runs away when attacked. So you could have some backup drones. 
I believe the weapon part is quite simple, but there are balancing issues that need to be ironed out.
The AI will take quite a while though.

**Comment by Zitchas** [comment]
Having healing weapons and fighters or escorts with AI that knows how to use them is something I'd like to see, but doesn't actually solve the problem. Ships can repair friendly ships already.

None of those do anything for people flying solo, and the point is to enable players to have something close to a Firefly style experience, which includes the possibility of being disabled and recovering from it.

**Comment by Tsunder** [comment]
I wouldn't make the entire process last more than like, 1 minute (for player ships? maybe 2x as long for non-players?).
* non-hardcore players would rather just reload rather than wait several minutes
* ships that get disabled tend to go boom quick due to in-transit projectiles/strays

Other thoughts:
* I think outfits that facilitate emergency repairs should be small (<3t?) as they're insurance/QOL alternative to reloading
* for roleplay/UX reasons there can be messages reporting repair progress + noticable increases in hull%

**Comment by Zitchas** [comment]
I've been mulling this over, and thinking that ideally this would be set up to allow outfits to modify it.

I'm thinking have a base time to recover that's hardcoded into the game. Let's say 1 minute. The  `"self recovery" X` value acts as a divisor to the base time. Smaller values will make it bigger, big values shorten it. 

So the player sees a `"self recovery" X` value. If X=0, then no self-recovery. If negative, then that ship can *never* self-recover, even with outfits that should allow it (basically a lock-out). If positive, use as the denominator to divide the base time to self-recover. Say, 1min. 

So a ship with  `"self recovery" 1` will recover in 1 minute.
So a ship with  `"self recovery" 0.1` will recover in 10 minutes.
So a ship with  `"self recovery" 2` will recover in 30 seconds.

So we could have a ship who, by default, has `"self recovery" 0.1` and thus normally takes ten minutes to recover. This ship could then install an outfit that they pick up somewhere that gives `"self recovery" 0.1`, which would then shorten their recovery time to 5 minutes. Adding another would bring it up to a total of 0.3, which would shorten it to 3ish minutes, etc. Decreasing returns, but probably noticeable to the player. And of course, if the player stacks a whole bunch of them and gets up to `"self recovery" 10`, then their ship recovers in 6 seconds. Which is *really* fast, and we should endevor to make it very expensive to do that, but it isn't a problem from the game perspective.

Having done all that math, I'd probably actually pick 3min as the baseline, as I think that allows for a bit better versatility and tolerance. It'd take a bit more stacking to get into the <30secs, too.

**Comment by Zitchas** [comment]
So:
Baseline time: 3 min.
Ships have a default value of 1. Meaning if they don't specify a `"self recovery"` number, then they are treated as having 1, and recover in 3min.

Ships have a variety of self-recovery times based on their lore, but probably ranging from no less than 0.25 (which would mean they take 12min to recover) to no greater than 3 (which would mean they take 1 minute to recover).

There probably shouldn't be any outfits available in the general human outfitters that change this, however getting an R2D2 style droid that provides a bonus along the lines of 0.5 or so would be an excellent reward for a longer and/or more complex story. Unlocks might also be possible, especially after the automata invasion. These could also be an interesting unlock for some of the upcoming alien races, too.

**Comment by mOctave** [comment]
I would suggest that, generally speaking, smaller ships have shorter recovery times and larger ships have longer ones.
Using Navy ships as examples, there are far fewer Cruisers, Auxiliaries, and Carriers than there are Gunboats. This means that the capital ships are a lot more complex, _and_ can withstand more serious damage than lighter ships without blowing up. Even with the extra crew, repairing a giant hole in the side of your capital ship is going to be harder than repairing your (fairly small) engines. Additionally, the problem described at the top of this page is more an issue for lighter ships – capital ships probably are much more likely to have escorts hanging around, unless they've been disabled too.

Furthermore, warships should probably recover faster, and fighters should have _very_ slow recovery times. I don't think drones should be capable of self-recovery (except the Korath automata, of course).

Suggested values of `"self recovery"`:
- Auxiliary: 0.5
- Carrier: 0.6
- Cruiser: 0.8
- Frigate: 1
- Gunboat: 1.5
- Rainmaker: 1.5
- Lance: 0.25
- Combat Drone: 0 (or maybe -1)

**Comment by ravenshining** [comment]
I think more of a bell curve would be more appropriate, with mid-sized ships like the Frigate being the fastest; although not a fighter I imagine a Rainmaker as being somewhat cramped and low on amenites, plus it's only got 3 standard crew.

The cap at 25% seems a bit restrictive.  A Gunboat and a Frigate both require 7 crew, but a Frigate wouldn't be able to use all those extra bunks for recovery with a 25% cap.  I might do 0.5%, with a 100% cap; I'd like to see more incentive to carry crew besides boarding.

This would also be a great opportunity to provide more differentiation based on faction and role.  Perhaps Betelgeuse ships are known for being easy to repair, Syndicate ships cut corners, and endurance-focused designs like the Scout are deliberately designed for self-support.

Last but not least I would love to have this for an upcoming Korath flavour outfit, a shipboard machine shop.  At the moment it's chiefly a lore thing that's planned to do a few things that are already covered by or similar to others, but allowing a ship so equipped to recover from disabled would make it more unique.  And there's your first "R2-D2" application, albeit a multi-tonne, crew-requiring R2-D2.

**Comment by Zitchas** [comment]
Definitely. The Korath Exile's demonstrated ability to simply live and function in space pretty much requires that they have some method of repairing, working on, and replacing parts of their ships while in-flight.

**Comment by quyykk** [comment]
In most systems you can generally find a friendly ship to help you out, and if there are no friendly ships won't you get immediately disabled again by enemy ships? Also the player can choose to bribe them; it's not always possible, but most common enemies can bribed.

TBH I like something like escape pods more than this. (just imo)

**Comment by Zitchas** [comment]
Well, I would love to have escaped pods too. I don't see them as mutually exclusive. It's like hull and shields: both keep you alive, but there are different situations where one or the other is more useful.

**Comment by Hurleveur** [comment]
I'd like to see this behavior happen, but I feel like when you get repaired from disabled in this case (or even in general) there should be consequences. Could be for another issue but I'd love to see a random outfit staying disabled until you get proper help, except for the hyperdrive.
Like losing temporarily a turret, a shield generator... To indicate your crew did what they could, with limited materials.
Would be nice to see this kind of behavior in general tbh, whenever you take a hull dmg you could lose outfits, that would eventually be repaired by hull repair at some point. This kind of behavior happens in battlefleet gothic armada and I kinda like it.

Anyway, this kind of behavior would mean the auto repair could be quite fast (it being random would be nice) but with some drawback.

**Comment by Zitchas** [comment]
It sounds like a fun mechanic, but it also has vicious implications for factions that are hull-heavy instead of shield-heavy (not to mention it makes going up against factions with effects that bypass/penetrate shields that much deadlier.

I rather wish we had separate "hull" and "armor" hp, to be honest. I like the idea of having armor that, while having advantages and disadvantages compared to shields, is still largely just a protective layer; but start hitting the hull itself... that's when system damage should start happening. I'd very much prefer that instead of just having a perfectly functioning ship until we hit 30% hull (or whatever it is set to for that ship), at which point it is disabled; that starting at, say, 50% we'd start losing stuff until at around around 25% almost everything is offline and we're drifting in space not because we're magically at some disabled threshold, but because we've lost so many systems and run out of power (maybe overheated or ionized too) that we just can't do anything and are frantically trying to rectify that.

**Comment by gendalv** [comment]
I just want a manual option: 
1) select an escort.
2) select a ship I want to recover
3) "click button to recover" 2) with 1).

**Comment by Hurleveur** [comment]
I don't want to allow cheesing, that'd be for another PR (and not by me sorry) and is an entire separate issue tbh.

That said I think that this automatic recovery can easily be coded. All that we need is `hull emergency repair` that repairs your ship whilst disabled with `hull emergency cooldown`, of course, to delay it.

**Comment by Zitchas** [comment]
I agree. This issue is 100% focused on allowing ships to self-recover. 

That being said, having self-recovery be an interactive option would be quite acceptable to me.

For instance, perhaps ships came with a built-in repair kit. When disabled, the player could go to their ship info screen, click the "repair ship" button, and that consumes the repair kit, and won't be able to repair themselves again in this way until they've visited an outfitter and restocked their repair kit.

Compared to the ship repair systems described preivously, this has the advantage of being an "instant" sort of thing, and is player-interactive, which is good thing. Having a trade-off (limited capacity) in exchange for this timely and controllable mechanism would make it different and interesting, too.

**Comment by Hurleveur** [comment]
Well the way I described could be more or less instant too but I like the interactivity... Maybe make it a dialog when you get disabled or smth? Smth you can click? Idk about having to go to a specific screen I think it should be obvious

**Comment by Zitchas** [comment]
The downside with a dialog box is that it's probably instant. Unless it is tied into the previously discussed timers? I don't think people should be able to just pound the "repair" key the split second they get disabled and continue the fight - there needs to be a little lag there.

That being said, in the long term I'd like the ship info screen to be a lot more interactive. Changing turrets from focused fire to opportunistic, setting turrets to auto-track fighters&drones, turning shield and hull regen on and off, perhaps changing power settings... (having my reactor turned off and just run on batteries until I'm approaching a battle, for example...) There's a lot of things that don't need to be tied to in-combat keystrokes, and that a player doesn't forcibly need to even deal with; but would make things much more interesting for players that like that complexity. This screen could display a countdown timer to when the auto-repair systems will have the ship up and running again, along with a button to consume the instant-repair module. (instant might be too strong a word. Perhaps "accelerated repair kit" might be a better term. Something like 10-15seconds to repair the ship, or something similar.

**Comment by xX-Dillinger-Xx** [comment]
I know this is a long read, please bare with me. I just wanted to be as clear as possible. You have made the players read some pretty long dialogues in game, so consider it a little payback. LOL
I'm well aware this is an old conversation, but it was just mentioned in PR #9846 which is related to this issue. It also seemed like the most logical place to put this comment. I am also aware that some of my following ideas may not even be possible at the moment, or may require too much work, and may be best saved for the future.
 
If any of what you read sounds exactly like something you have already said, stand up and pat yourself on the back, because that's probably how the idea got into my head. It's also possible it could be pure coincidence, in which case consider it validation that your idea made sense to at least one other person. Either way you should be happy, well unless I happen to disagree. In that case, I'm sorry. 

 I like to analyze everything and make sense of it. So much so, my wife and daughter constantly remind me "Stop analyzing the movie"
I'm going off on a tangent to start but it will all make sense at the end. (hopefully)

**Shields:**
- shields make sense as they are
- the fact that they are the same across the entire ES space is believable. It is easy to believe that there is only one form of shields. They are all just an energy field surrounding a ship. 
- how strong, fast, if they recover, and even if they exist are all good variables and make sense.

**Hull:**
- the single "hull" metric only makes sense to a point -- more on this later
- the current hull metric makes sense if you think of "hull" representing "hull integrity" and the metric itself doesn't really need to be reworked.
- Hull integrity would indeed vary greatly with ship design, intended use and manufacturing methods. But not necessarily size. Let me explain it like this. If you are out in a small fishing boat with only one compartment and you punch a big enough hole you sink. If you are in the same boat with multiple compartments, you just seal off that compartment and the boat doesn't sink. In ES the intended use of a ship ( i.e. ship type) should have a greater influence on how much "hull integrity" a ship has. I think this is already being considered during ship design but without looking at all the numbers I'm not sure how logically. 

**Current Implementation of the single metric "Hull":** 
- your ships takes hull damage 
- it decreases to the point where you suddenly become disabled and become dead in the space -- this is where self healing would kick in.
- this is where the logic goes wonky
- nothing happens to the crew, outfits or anything else for that matter and now we just wave a magic wand and make it all go away.

**Proposed solution:**
- add some realism to the consequences of taking damage
- as the hull takes damage it's integrity will suffer
- the more the hull integrity suffers the more and more compartments will need to be sealed off.  Some of those compartments will contain things like guns and turrets. Others will contain larger more important outfits like engines, power sources and shield generators. Even worse some of these compartments will have crew in them.
- as the Hull takes more and more damage, more and more systems will shut down until you are finally disabled.  A ship shouldn't remain fully functional and them suddenly be disabled. Well unless they take hits from weapons that deal ion or heat damage, but that's not he same thing. 
- I don't think there needs to be a whole new metric involved. What systems shut down and when could be determined using the current "hull" metric, with some randomization for fun and added realism.  

**On to the Self healing part:**
- the ability to self heal really isn't any magical ability at all
- ships with crew and no hull repair outfits (e.g. humans) would deploy crew members to start repairs as soon as it is safe and should be a bit slow. Therefore, the self repair delay should be longer. Another consideration for ships in this category should be remaining crew numbers. Less crew, longer delay. At the moment, I don't know how you explain what happens in ships with only a pilot. Do fighters even have enough room for someone to leave their seat to start repairs?  I would assume that if they are advanced enough to be in space they should know about nanobot technology.  An option for small ships with limited crew, could be a repair kit that contains just enough nanobots to restore enough Hull Integrity to limp to a shipyard. Humans and Hai can produce nanobots in a lab but haven't figured out how to build a nanobot fabricator small enough or efficient enough to fit in a ship.   I'm a bit uncertain at this point. 
- ships that have nanobot tech like Korath, Coalition, ect start repair as soon as they receive damage and try to keep up with repairs. This is what already happens, so in theory, the self repair should be instant the second the fighting stops, but at the moment there isn't an explanation as to why this doesn't happen. I guess we could explain it as, that because nanobots have a life span and need to be replenished it would take time to replenish enough to start repairs. In this case the self repair delay would be much shorter. 
- I don't know what happens with Remnant ships. @Zitchas Help please. 
- adding self repair as an outfit doesn't make sense, logically. However, it could be enclosed into an invisible non purchasable outfit to make it easier to implement into the game. Another thing for code crunchers to decide. 

Again, I'm very sorry for the long winded post.

**Comment by Hurleveur** [comment]
Just so you know, we dont consider realism as valuable by itself, its more about believability.
Battlefleet gothic armada is a game that has a mechanic like you're describing, but its only because they have much larger amount of hull per ship. Right now this suggestion would make hull worse than it already is (no protection from effects like ion, no good regen options) and we dont need the extra complexity. If we were to add more hull to all ships that might work but idk if its worth it

**Comment by xX-Dillinger-Xx** [comment]
There would not be any reason to add a third layer of armor to ships. Internal damage to outfits should only happen if the hull is being damaged. Damage to the shields would have no effect on any internal outfits.  
In other words, if the hull is less then 100% outfits start to fail at random. First minor systems and progressively more important systems until you are fully disabled. Then self healing or emergency repair delay starts.
Yes, technically you could be disabled faster because the more your hull gets damaged the less functionable your ship becomes, so maybe hull would need to be increased a little. But don't forget your enemy will also be losing functionality, so maybe they balance each other out. 
Logically speaking, how does a ship become disabled if internal systems aren't taking any damage? Having a ship remain fully functional until all "hull" is depleted and then suddenly the entire ship shuts down, doesn't make sense. IMO not believable.
   
I'm aware that it's either too difficult to implement or isn't wanted because this idea has been around since at least 2019 and nothing much has happened.  I chose to revive this idea as a reminder that it should be considered one day. BTW I'm not referring to self healing because that's in the works.

**Comment by Hurleveur** [comment]
> Yes, technically you could be disabled faster because the more your hull gets damaged the less functionable your ship becomes, so maybe hull would need to be increased a little. But don't forget your enemy will also be losing functionality, so maybe they balance each other out.

I feel like this mechanic would only matter for players, because often AI ships just die when their shields are breached and they're focused down by the entire fleet. And we'd just be making it more punishing to be losing a fight, and harder to come back from it? Especially in human space where hull repair isnt found I dont think this'd be a good change.
If I suggested damage *after* coming out of being disabled, its mostly to force you to go at a spaceport to repair and not be able to abuse some AI not finishing you off for infinite free chances.

**Comment by xX-Dillinger-Xx** [comment]
I think I understand what your concern is. 
If you lose outfits during a battle, have no hull repair, and your "hull" is below 100%, how would you get outfits back?

Let's make some adjustments to this concept idea to make it less punishing and still believable:
- need to add a new 3rd invisible metric - lets call it `"outfits damage"`
- it mirrors the current "hull" metric
- it has automatic recovery  - just like "hull repair"
- it could use the same `"hull damage"` attribute we use now, this way weapons remain untouched, only ships need new attributes added. 
- the current "hull" metric remains exactly like it is now 
- it only effects `"outfits damage"` - not "hull"

New example:
- you take `"shield damage"`  - nothing happens to outfits
- you take `"hull damage"` from weapons 
- you start to lose "hull"  and `"outfits damage"` 
- when the new `"outfits damage"` metric drops below a certain threshold (idk 75%) minor outfits start randomly going offline
- as `"outfits damage"` continues to drop (i.e. still receiving `"hull damage"`) progressively more important systems start fail. 
- what outfits and when they go offline should have some sort of random factor to it 
- as soon as you stop taking `"hull damage"` auto recovery kicks in and now the `"outfits damage"` increases. 
- outfits start to progressively come back online

It's is basically the same thing that happens when take to much ION or overheat. It's just tied to the damage you receive, not just a weapon. It's also a little more random, progressive, and really only becomes a major issue during the last 50% of your "hull" life. 
- 100% -75% no issues
- 75% - 50% minor issues
- 50% - 0% major issues

All these issues are TBD

Hopefully this makes more sense. I would like to continue this discussion and refine it further, even if it is only a proof of concept.

**Comment by LepRyot** [comment]
In risk of further topic drifting, it outfits are going to be disabled in-flight, I think that mechanism should be determined by a value on the outfit, not the ship.

**Comment by xX-Dillinger-Xx** [comment]
Are you suggesting each outfit would have it's own "health value" (for lack of a better word)? With each taking damage at different rates? If so that would be very interesting, but sounds complex.

> In risk of further topic drifting

I'm starting to feel the same way, and regret starting this up here. Sorry, i get carried away sometimes. 
I would like to move it to the Discussions area. Does anyone on the team have ability to move it? If not, I guess I could copy and paste my posts over but then I lose the comments from others. As I said, I know it's probably not being considered, but I'm enjoying trying to see how far we can improve the whole concept. Maybe we can turn it into something for the future. 
I wish I had the skills to try and play around with it myself, but sadly I've only played with some scripting languages and a little bit of Java.

**Comment by petervdmeer** [comment]
Closing; I believe this feature request is handled in #9846.
