### ISSUE TITLE
"Join fleet" doesn't start

### ISSUE THREAD

**Issue by MattOTop** [endless-sky/endless-sky#7271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I accept to "join fleet" to defend, from the spaceport, it doesn't lead me to the star map to fight, I just remain on the system interface without anything happening.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'
1. Go to the starport
2. Click on 'join the defense flleet' (or so)
4. Nothing happens

### Expected Behavior

I expect to go to starmap to fight, but nothing happens.

### Link to save file

[Solaar KRULL.txt](https://github.com/endless-sky/endless-sky/files/9636383/Solaar.KRULL.txt)

### Operating System

Debian 11 Bullseyes

### Game Source

GitHub Releases

### Game Version

v0.9.14 (appimage)

### Additional Information

Sometimes, it works as it should, but most of the time, nothing happens when I choose to join fleet.

**Comment by LepRyot** [comment]
The launch on accept defense missions are only if the system you're currently in is the one being attacked. You have active defense missions for neighboring systems; as they will take at least two days to arrive, they'd be no point in automatically launching the player (to get there ASAP) since any amount of time docked on a planet is one day no matter how much IRL time has passed. So you are left free to mingle around the planet and outfit your ships if need be until you're ready to head to the defense site; the mission spawned allied NPCs will follow you there

**Comment by MattOTop** [comment]
Ah OK. In previous versions, I was only invited to defend local system, so I thought it was still the case.
Sorry for this false positive bug report.
