### ISSUE TITLE
Search feature for outfits/ships

### ISSUE THREAD

**Issue by ThatSheepGuy** [endless-sky/endless-sky#728]
There should be a feature on the map screen that allows you to search for specific ships or outfits, akin to how you can search for specific planets/systems. It would highlight systems with outfitters/shipyards that sell that particular outfit/ship, so that you don't have to scroll through the outfitter/shipyard lists to find what you want. It doesn't necessarily have to be a separate function, perhaps just modifying the current search option to allow you to search for outfits and ships in addition to planets and systems.

**Comment by Wrzlprnft** [comment]
I think a it would be better not to extend the search-function of the planets, but make thist feature just auto-scroll and click the outfit in the list

**Comment by IFailAtGaming** [comment]
that feature already exists, i do believe you have to click on "outfits" in the map screen

**Comment by jmhorjus** [comment]
I think he meant a search feature *within* the list that is shown when you click on outfits in the map screen.  Does that already exist?  Like if I've explored everything and finished the campaign, can I look up "where do they sell frag grenades" on the map without scrolling down past every kind of buyable weapon, battery, engine, etc, in the game to get to that bottom category?  (I didn't see a way, but maybe I missed it.)

As more content is added and the number of purchasable outfits increases this may become more and more desired, since the amount of scrolling you'll need to do to find something in a bottom category will only increase.

**Comment by LocalGod79** [comment]
i think that this is one of those problems that would be at least partially addressed by #732

**Comment by endless-sky** [comment]
I've added a find feature in commit 82ffb7b. (This just applies to the shipyard and outfitter maps, not the actual shipyard and outfitter panels on the planets.)

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
