### ISSUE TITLE
Tweak the behavior of ships turning off-course to avoid overlapping

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#729]
It mostly happens with large fleets of only one kind of ship but some times when ships are under thrust they will turn slightly for no apparent reason. I'm fairly sure that it happens to ships that are very close to each other.

**Comment by Gkramme** [comment]
This should occur if they are fighting a target. Auto aim turns your ship so you can be nearer to your target.

**Comment by jafdy** [comment]
No this is definitely when they are just flying along as a fleet.

**Comment by Gkramme** [comment]
That must be a bug then. But I've noticed it happens when I autotarget a ship.

**Comment by endless-sky** [comment]
Ships that have exactly the same movement parameters (acceleration, top speed, etc.) will attempt to keep a certain distance away from each other. Otherwise, their movement paths converge over time and you end up with dozens of ships in the same exact location, overlapping each other. It's mostly just for appearances, but it also makes a difference in combat when you start firing at what you think is a single ship, only to find that it's a stack of 20 ships that has you way outgunned.

**Comment by jafdy** [comment]
Is there a different way of doing this perhaps ships change direction slightly to move apart slowly or to stay a short distance apart.
