### ISSUE TITLE
Hull is extremely fragile compared to shields

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#73]
Most ships have very fragile hulls, specially compared to their own shields, also the game has no "armour" system.

The problem is that this compounds the "kill-steal" issue, and make even when there is no AI present boarding some ships too hard, you are pounding away while they have shields, and then as soon the shield is gone they explode.

This also makes the game slighly hard for the player, I personally don't consider hull amount at all, I count my shield level as my main HP, because as soon the shield is gone I usually die immediately if fighting a strong ship, or get disabled if fighting a much weaker ship (strong ships usually can kill your entire hull in a single salvo, and might accidentally kill you)

**Comment by endless-sky** [comment]
It's intentional that disabling a ship takes a bit more carefulness and restraint than just destroying it. That also helps create a distinction between the beam weapons - which can instantly cut off when your target is disabled - versus the less elegant projectile weapons, where you can't take back the killing shots once you've fired them.

I think there might be a place for ships with much more hull than shields  - say, an alien species with very well-armored ships - but other than that I'm not sure how giving ships more hull strength would make game play more interesting.

**Comment by Phezzan** [comment]
I'm wrestling with the furball effect.  I have a heavy warship covered in pulse cannons, but typically random friendlies get the kills. I can't kill the pirate before they've flown into the middle of a convoy and only the very large pirates can survive that for more than a couple seconds, 

I implemented an armor system and doubled hull values across the board - but it's all paper mache when 3-4 light warships and a few freighters worth of quad blaster turrets are showering that one hawk with a barrage ikaruga fans would consider unfair.  I might try increasing the distance at which you drop out of hyperspace if you detect enemy ships in the system, and I might find a way to have the underdog perform a kiting maneuver... I think I know how to accomplish that first one.

**Comment by Tufton** [comment]
This problem could potentially be solved by adding an armor plating outfit that either A) increased the overall hull value of the ship or B) reduced incoming hull damage by a certain number or % relative to how many and what type of armor plating you buy.  The armor plating would consume outfit space and add a significant amount of mass to the ship.  This way we wouldn't have to create a whole new line of ships but instead a more flexible series of outfits allowing players to decide if the want to focus on shields or armor (armor is tankier but no regen v. weaker shields with regen?)

**Comment by endless-sky** [comment]
If armor plating were an ordinary outfit, it would be very easy to buy enough to double or triple a ship's hull, especially for small ships. That was a problem in EV - basically there was no reason not to buy all the armor upgrades, and for small ships they were way overpowered.

One idea I had early on was to allow you to allow ships to have different hull materials, but not allowing them to stack - i.e. you can exchange your standard hull for a heat-resistant hull, but you can't install both at the same time. Rather than taking up outfit space, changes to the hull would affect your ship's mass. So, there might be one hull that is super lightweight (less mass than the standard hull) but also weak; another that is heat resistant or resists ionization, and other hull types that are stronger but make your ship heavier. Hull price would be multiplied by your number of hull units, so changing the hull on a big ship would be more expensive than on a small one.

I didn't end up adding that because it would add even more complexity to the outfitter, which people already find confusing. But, as the universe expands and new damage types perhaps get added, it may start to make sense to have hulls that let you resist those types of damage or tht give you other advantages.

**Comment by Tufton** [comment]
Couldn't we just up the required outfit space and or mass of the armor
plating to balance it in terms of what you are giving up in exchange for
the armor?  If we make say...a titanium armor plate that doubles your hull
strength (can we increase it by a %?), we can make it take 100 outfit space
(or more) to prevent it from being used on fighters and interceptors.  That
way you have to decide between more shields, more armor, or some other
combination of utility.  That plus the added mass would make it generally
unappealing on fighters because it would get to a point where the fighter
engines would be too weak to push heavily armored fighters at an acceptable
velocity.

As I see it, defensive item stacking already exists in the form of shield
regen (hello triple quarg shield generators and/or S series Hai shields),
the trade-off is just gigantic energy/heat and outfit requirements, plus
expense.  So we already see the issue of small fighters with small shield
capacity and high evasiveness being able to slap on a couple small S-Series
shields and becoming basically unkillable because nothing except tracking
weapons can sustain damage long enough on an evasive target long enough to
destroy it.  At least with the armor you trade tankiness for agility.

**Comment by endless-sky** [comment]
As of 423450f, I've rebalanced hull vs. shields by making all close-range weapons do 1/3 less hull damage (equivalent to increasing hull strength of all ships by 50%).

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
