### ISSUE TITLE
Earth shaper requires crew but has no bunks

### ISSUE THREAD

**Issue by jafdy** [endless-sky/endless-sky#730]
Title said it all. It comes up as 1/0.

**Comment by masterpierround** [comment]
I noticed this as well and thought it was odd. The weirdest part is that it has no required crew in wanderers.txt. This makes me think that the hyperdrive is causing this glitch.

**Comment by Gkramme** [comment]
The hyperdrive requires a person to man it. That makes sense.

**Comment by endless-sky** [comment]
It's because unless a ship's category is "Drone," the game requires it to have one crew. (That's to keep outfits that reduce your required crew from being able to reduce it to zero.) And I can't make the category "Drone," because then it would expect to be carried by a larger ship instead of having a hyperdrive. I probably need a new ship category for uncrewed hyperspace-capable ships.

**Comment by jafdy** [comment]
Fair enough. Still it might be worth wile If more of these sorts of drones are added.

**Comment by endless-sky** [comment]
As of commit 8d48737, a ship can be marked as an "automaton," to allow it to fly without any crew even if it is not in the "Drone" category.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
