### ISSUE TITLE
Add "none" drone bay option

### ISSUE THREAD

**Issue by beccabunny** [endless-sky/endless-sky#7353]
### Problem Description

As specified by the wiki, the current syntax for ship bays is this:
> (fighter | drone) <x#> <y#> [over | under] [left | right | back]

This means that, in order to use the left, right and back keywords you must use over or under before. However, left/right/back doesn't command only the displayed direction of the carried ship's sprite, but also the direction in which it will spawn. While the cases in which someone would want an invisible carried ship that spawns going anywhere but forward aren't a lot, it would still be nice to be able to do so for specific carriers

### Related Issue Links

None I could find

### Desired Solution

Adding a "none" option beside "over/under" to be able to use the left/right/back options relative to the spawn direction of the fighter/drone without making it actually appear over or under the ship

### Alternative Approaches

Adding the right/left/back options to over/under too maybe? But that doesn't seem ideal

### Additional Context

None

**Comment by warp-core** [comment]
If that's what the wiki says, based on this comment in Ship::Load():
```
			// While the `drone` and `fighter` keywords are supported for backwards compatibility, the
			// standard format is `bay <ship-category>`, with the same signature for other values.
```
It ought to be changed.

Anyway, to the point at hand. Based on the code, it doesn't seem to me that the ordering of the `side` (over/under) and `facing` (left, right, back) matters.
Have you tried defining a bay as, say: `bay fighter 10 0 right`?

**Comment by Amazinite** [comment]
1) The brackets around the tokens means the token is optional. So the under/over need not be specified in order to be able to specify left/right/back. The game gets the bay type, the coordinates, then just reads everything after the coordinates to see if the bay should be over/under/left/right/back. The order after the coordinates doesn't matter. If the order mattered then the wiki would format it something more like this: `[(over | under) [left | right | back]]`
2) The wiki does specify the current syntax of `bay <category> x y` instead of `fighter x y` or `drone x y`, but it lists the old syntax first, so that order could be reversed.
3) It's better practice now to specify additional information about a bay beyond its category and coordinates as a child of the bay instead of all on the same line. That is, don't do this:
```
bay "Fighter" x y over left
```
Do this:
```
bay "Fighter" x y
```

**Comment by Amazinite** [comment]
Updated the wiki to list the current syntax first.

**Comment by warp-core** [comment]
Should perhaps also mark the old syntax as old and liable to be removed at some point, if it isn't already.
