### ISSUE TITLE
Change displayed name of "shield energy"

### ISSUE THREAD

**Issue by thomasballinger** [endless-sky/endless-sky#736]
I found "shield energy" and "hull energy" confusing names in the game UI. I wonder if "shield generation energy" and "hull repair energy" might be better?

**Comment by mrec** [comment]
Not sure what you mean. There are three numbers that matter here:

* Hull (not energy), which shows how much punishment the physical structure of the ship can take. This doesn't get repaired except by landing on planets/stations.
* Shield max, which shows how much punishment your shield can absorb before damage starts reducing your hull.
* Shield charge, which shows how quickly shield regenerate (up to the max) after taking damage.

**Comment by thomasballinger** [comment]
I mean Shield Energy, which affects the conversion ratio of energy to shields while they're being recharged: https://github.com/endless-sky/endless-sky/blob/master/source/Ship.cpp#L690

**Comment by thomasballinger** [comment]
(only used by two shield regenerators in the game)

**Comment by egilburg** [comment]
I wish some derived values were visible on your ship stats:

- Full shield recharge time, in seconds ( shield max / shield recharge rate per second)
- Weapon recharge time, in seconds (inherent weapon + battery capacity / reactor recharge rate per second)
- Weapon drain time, in seconds (how long can you fire weapons at full power before your energy runs out) - this would take into account both energy storage capacity, recharge rate, and weapon energy usage, keeping in mind that weapons recharge even while you fire them). Since it's possible for this to be infinite or arbitrary high value (if weapons recharge faster, or almost as fast, as they drain) we can put upper cap and say something like "> 99 seconds" if applicable. Maybe two numbers - one just for weapons, one if also ship is accelerating/turning which also takes up energy.

This would take some manual work of finding these numbers manually. When outfitting a ship I care about these derived stats more than their constituent parts, e.g. I want to build a ship that can fire uninterrupted for 10 seconds while moving, and recharge in another 10 seconds while not firing .
