### ISSUE TITLE
Hai ships of different factions are visually indistinguishable when zoomed out enough for combat.

### ISSUE THREAD

**Issue by UnorderedSigh** [endless-sky/endless-sky#7497]
### Problem Description

The Hai ships are an extreme example of a larger problem in Endless Sky

1. The Hai ships have almost no color, so it is impossible to tell them apart, especially at a chaotic system like Wah Ki, unless you're zoomed in all the way. Zoom in that far, and you can't see where the projectiles are coming from.
2. At Wah Ki, only Shield Beetles and Lightning Bugs are shooting at you, so you can filter out the other designs. Once you do, you don't know who is who without looking at the radar screen.
3. They all use the same projectiles too, so you don't even know who is shooting at you, even if you knew which ship the shot came from.
4. Since you have to look at the radar screen to tell who is who, it is hard to keep track of where the projectiles came from.

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/5123
https://github.com/endless-sky/endless-sky/issues/4732
https://github.com/endless-sky/endless-sky/issues/5893

### Desired Solution

Add a lot more color to Hai ships, and give each faction their own projectiles.

### Alternative Approaches

Implement color rotation or similar techniques on projectiles.
Give the Hai factions their own ships with distinct visual differences, as is done with other races.
Better status overlays (this won't help projectiles though).

### Additional Context

![hai-identical-try2](https://user-images.githubusercontent.com/116329264/199235401-ecc9c5f9-7935-40ee-9072-c675e5011279.png)

**Comment by Anarchist2** [comment]
Why can't you use status overlays?

**Comment by UnorderedSigh** [comment]
@EjoThims I see no changes to existing Hai ships in #7019. It just adds new ships.

@Anarchist2 Status overlay tells me who is hostile, but it doesn't identify the projectiles.

Also, it doesn't help much when there are many overlapping ships since you just get a pile of ships and circles. The circles obscure the ships, and you can't tell if there are friendlies underneath.

**Comment by Zireael07** [comment]
> Also, it doesn't help much when there are many overlapping ships since you just get a pile of ships and circles. The circles obscure the ships, and you can't tell if there are friendlies underneath.

That's what I experienced in moderately busy systems (not necessarily Wah Ki) with status overlays on

**Comment by UnorderedSigh** [comment]
I've added, "better status overlays (this won't help projectiles though)" as an alternative solution in the issue description.

**Comment by mOctave** [comment]
> `@EjoThims` I see no changes to existing Hai ships in https://github.com/endless-sky/endless-sky/pull/7019. It just adds new ships.

The adding of new ships that only exist for the Unfettered should help with this problem, even if it won't fix it entirely. It should be a step toward ` Give the Hai factions their own ships with distinct visual differences, as is done with other races.` even if it doesn't quite achieve that yet.

Furthermore, I think not knowing which projectiles are going to harm you adds something to the game, making it so that it's a good habit to dodge all projectiles.

Overall, I'm not against this change, but I think that it probably isn't necessary.

----
p.s. The only other races with multiple factions are humanity and the Korath, to the best of my knowledge. In the case of the Korath, everything was developed at a similar time by different groups. In the case of humanity, all sorts of factions have overlap, it's just that there tends to be enough differences in the colour scheme that it doesn't matter. In the Hai's case, however, a lot of the ships have probably been around since long before there was Unfettered Hai. It makes sense that there's a lot of overlap in weapons and ships.

**Comment by Saugia** [comment]
I don't think we need to differentiate the Hai's governments so far in that we change weapons, projectiles, or have specific ships for each faction. I don't think zoom distance is really an appropriate factor to consider in distinguishing ship governments - most artwork for the game is made under the assumption that the player is zoomed in often.

If you zoom out in a crowd of human ships, most are grey. Visuals also aren't the sole way to identify hostiles or different governments - the target panel/selecting hostiles is more important to this and is easily read.
