### ISSUE TITLE
Escorts Spawn Without Freighters in "Free Worlds Escort" Mission

### ISSUE THREAD

**Issue by Aneutronic** [endless-sky/endless-sky#7528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When accepting the mission "New Worlds Escort," upon arriving at the mission location, landing, visiting the spaceport, and taking off again, the interceptors provided by the New Worlds to help escort the freighters spawn (1 Sparrow, 3 Furys, and 3 Hawks,) without the freighters. The escorts then permanently stay attached to my fleet, preventing me from disabling any ships with my lasers because their blaster cannons always finish their targets off.

### Steps to Reproduce

1. Accept "New Worlds Escort" mission somewhere in the dirt belt.
2. Visit the mission target planet.
3. Visit the spaceport; (no mission dialogue will occur.)
4. Take off from the planet with your seven interceptor escort. Notice the lack of freighters.
5. Visit Tarazed. Notice the interceptor escort is still with you, and the freighters still have not shown up.
6. Continue playing the game, going wherever you like, and doing whatever you like. The interceptor escort will still follow you and finish off all the ships you disable.

### Expected Behavior

- When visiting the spaceport on the mission target planet, mission dialogue should occur indicating the mission is progressing properly.
- When taking off from the mission target planet, the freighters should spawn alongside the interceptor escort, with a new objective issued telling the player to go to Tarazed.
- Upon visiting Tarazed, more mission dialogue should occur indicating further mission progress.
- Upon visiting the spaceport on the original mission target planet once more, the final mission dialogue should occur, indicating payment was given and the mission was concluded.

### Link to save file

[Gerold Martin~Frere Worlds Escort Tarazed 1.txt](https://github.com/endless-sky/endless-sky/files/9944874/Gerold.Martin.Frere.Worlds.Escort.Tarazed.1.txt)

### Operating System

Windows 10 Pro, Version 10.0.19043 Build 19043

### Game Source

Steam

### Game Version

v0.9.16.1

**Comment by bene-dictator** [comment]
The Free Worlds Escort mission in the prologue should come from a planet in the South or the Rim where the Free Worlds have control over, not from the Dirt Belt. You would have to go to Longjump where the freighters are, and you shouldn't need to go to the spaceport because dialogue would show up. You haven't already become a member of the Free Worlds yet, have you?

**Comment by Aneutronic** [comment]
I meant the South. I received the mission in the South. I did go to Longjump. I am not a member of the Free Worlds yet.

Hope this helps.
________________________________

**Comment by Amazinite** [comment]
Had you previously done the FW Escort missions on this save file before updating your game? I see that all of the FW Escort missions have been offered and completed, so I'm guessing that you already did this line of missions in the past. v0.9.15 added FW Escort 0 before FW Escort 1, so I imagine that you got FW Escort 0 to offer, but upon completion weren't offered FW Escort 1 since you had already done it.

**Comment by Aneutronic** [comment]
I probably did. That would explain why the mission didn’t continue beyond FW Escort 0.

**Comment by Aneutronic** [comment]
I have made a fork and implemented what I believe to be a fix in the "data/human/free worlds 0 prologue.txt" file on the "aneutronic-patch-1" branch, specifically in the "to fail" section of the "FW Escort 0" mission. Could you review my submission @Amazinite and see what you think?
