### ISSUE TITLE
Bug: if you have multiple ships selected, and buy a map...

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#753]
you will buy as many copies of it as you have ships selected (in spite of not being able to otherwise buy more than one copy of the map at a given outfitter)

**Comment by endless-sky** [comment]
I haven't been able to replicate this - if I have multiple ships selected and buy a map, it only charges me for one, and the "installed" count never goes above 1.

Special items (licenses, maps, etc.) are owned by the player rather than by a ship, so they show up as "installed" regardless of what ship is selected. Could that have confused you into thinking you had multiple copies of the map?

**Comment by LocalGod79** [comment]
i watched the 10k marker (i had millions at the time) drop at two separate outfitters when buying a map with 5 ships selected - seemed conspicuous.
