### ISSUE TITLE
Colonization of uninhabited systems

### ISSUE THREAD

**Issue by bchis17** [endless-sky/endless-sky#754]
I'd I like to see colonization of systems because I can't suceed in conquering other planet's and there's nothing to do but it would be a dream to have that.

**Comment by Disiuze** [comment]
This would mean all planets would need to be landable and thus it makes the map.txt much larger.
This would also require missions to colonize all planets, provided you don't want to add new code.
If you would want code, then it would probably be complex seeing as the habitable factor would also have to taken into consideration as it would actually make a difference then.

**Comment by lehgogh** [comment]
Perhaps only make a few systems colonizable?

**Comment by bchis17** [comment]
Yes,it would and you can input your own world info.

**Comment by brendanjones** [comment]
This could be a great follow-on mission after the mission where you help shift the climate on that planet. Can't remember the name off the top of my head. You know the one...you fit an asteroid with ion engines and fly it into the planet?

Anyway - you make just one deserted planet landable. Doesn't matter where, but presumably somewhere on the edge of human space, maybe in the south (or it would have been terraformed by now). When you land, you get an automatic mission pop-up box with the story going something like:

"As you were flying in, your sensors picked up a large quantity of water ice at the poles of [planet name, something random like P3X-118 (pick a planet designation from your fav Stargate episode and put it here. Sorrynotsorry ;) )]. The rest of the planet is a hot, hilly wasteland, but you wonder if the terraforming technique you helped instigate on [that other planet's name that you smashed an asteroid into] would be effective here.

[Planet name] has remained deserted until now due to a lack of valuable resources and the sheer cost of terraforming such a remote planet with traditional terraforming techniques, but you wonder what it would be like to make an entire planet habitable. Your crew have already begun throwing around a few new names for the planet, some of them more appropriate than others.

You think it's time to pay a visit to [girl whose idea it was to use asteroids] back on [that planet's name]."

Then there's a few missions to do with getting her to assess the planet, then terraforming the planet by smashing an asteroid into it, then negotiating your ownership of the planet with the Free Worlds government, maybe some mission for massive cargo to bring in equipment for settling the planet, etc.

Thoughts? Please excuse my crap storytelling.

**Comment by bchis17** [comment]
Great,but once you settled you should get  more credits than dominated planets

**Comment by natangold** [comment]
> Great,but once you settled you should get more credits than dominated planets

How? If you dominate a planet then, story-wise, they are paying you everything they can each day while still maintaining their economy - you are halting all economic growth for that planet, permanently. To give you more than a dominated planet would mean that - before they have had decades (Clark) to millennia (Earth) of economic growth and development - they are somehow providing you with more than the "everything they can each day and still maintain their economy" of a developed planet.

Being a dynamic rather than static figure, sure - as the planet develops, they can give you more money; that makes sense. But we're talking about a literally brand-new colonial settlement; they're not going to have [tens of] thousands of credits a day to be throwing toward their absent evil overlord.

**Comment by brendanjones** [comment]
Natangold, not negating your main point, but just like to clarify that I meant for that mission string to be a peaceful one (except maybe fighting off pirates), so no 'Evil Overlord' - I was more thinking along the lines of 'Benevolent Founder/CEO'. Then again, it could be made into a mission string where you set up a new pirate base.

**Comment by lehgogh** [comment]
What if you wanted to be the evil overlord? *opens up NationStates*

**Comment by endless-sky** [comment]
Since this is content creation rather than a game engine change, it probably belongs in the forum rather than the issue tracker.
