### ISSUE TITLE
[Unpark All]  un-parks all of your ships, even those half a galaxy away

### ISSUE THREAD

**Issue by ChuckStarchaser** [endless-sky/endless-sky#7541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**[Unpark All]** un-parks all of your ships, even those half a galaxy away

### Steps to Reproduce

1. Park a few ships in Coalition space;  a few ships in Wanderer space ...
2. Now hit **[Park All]** on your main fleet in Terran space
3. Do a few things, then come back and ...
4. When you hit **[Unpark All]** suddenly your ships in Coalition and Wanderer space also become un-parked

### Expected Behavior

The **[Unpark All]** button should only unpark all the ships AT THE CURRENT BASE;  NOT all your ships anywhere in the galaxy.

### Screenshots

Nothing photogenic for this.

### Link to save file

No need;  should be easy to understand without a save-file.

### Operating System

Ubuntu (was 20.04, but did full upgrade;  maybe 22.x, donno)

### Game Source

GitHub Releases

### Game Version

9.16.1 (Image)

**Comment by binaryspica** [comment]
I don't think that it is a bug for nothing says that it only affects the ships in your current system, but change it to only affects on the current system would be better than now.

**Comment by vitalchip** [comment]
It's not a bug, 'all' means exactly that. 

As a feature request I'd wonder what options people would want to have?  Unpark 'all ships here' or Unpark 'all ships elsewhere' or Unpark 'all ships in system X', or Unpark 'all Fighters' etc.

The reason I mention this isn't because what you're suggesting is unreasonable, just an observation that as soon as such a feature is added someone else will come along with a different variant on the theme, so it's worth considering from the outset.

We have shift click available in the PlayerInfo screen which can already achieve all of these things, albeit with a bit of work from the player.

As a workaround, if you want all ships in the current system unparked without hunting the PlayerInfo list for them, go to the Shipyard or Outfitter and select them all there (click the first, shift click the last), then CTRL (0-9) to put them in a group. Return to the PlayerInfo screen, press whicever (0-9) you used and they will all be selected ready to press Unpark (not unpark all).

I think there might be a 'sort' facility in later versions of the code which would be quicker but it's not in my version so I can't comment on the effectiveness of that method.

**Comment by Zireael07** [comment]
Can the meaning of All be made more clear, then? All Owned?

**Comment by ChuckStarchaser** [comment]
@vitalchip :

  First, I wasn't sure whether to call it a bug or a feature request, initially.  I went for 'bug', after some thinking, based on that (I think;  but could be wrong, of course) un-parking ships far away has no purpose or utility whatsoever to the player.  From this point of view this is only not a bug in the sense that it is "documented", or consistent with the word 'All';  but it can be called a bug if taken together with the labelling of the button "ALL", given that nobody needs to un-park all, ever (unless I'm mistaken).

  Secondly, there can be many meanings to the word "all".  If we are interacting with the space-port computer, for example, to them, the words "all" and "all here" are synonyms.  In other words, even if the command is "un-park ALL", the word ALL would be more logically connected to what the particular space-port means by "ALL".  That is why I did not suggest a change of name for the button to "ALL here" ...  IMO "here", to any given space-port, is something to be taken for granted.  They neither know nor care to know what ships you have anywhere else.

  Thirdly, quote The reason I mention this isn't because what you're suggesting is unreasonable, just an observation that as soon as such a feature is added someone else will come along with a different variant on the theme, so it's worth considering from the outset. is only true if this is a "feature added".  I called it a 'bug' precisely to make it clear I did not advocate adding an **[un-park ALL HERE]** button, but simply to change the behavior of **[un-park ALL]** to something reasonable.

  That it can be achieved other ways, aware of, I am.  I was simply reporting that the SIDE-EFFECT of the un-park ALL button, namely instantly un-parking ships that are 50,000 light years away, will be perceived as a bug by most players;  it feels like dumb bug;  I reckon it is a dumb bug (unless I'm wrong, of course).

**Comment by ChuckStarchaser** [comment]
And I was, indeed, wrong.  Zitchas just pointed out to me in my earlier forum thread that un-parking ships far away DOES have a use;  it is a way to tell those ships to leave their ports and start navigating towards you.

I guess I got blinded by my own strategies.  The reason I have other fleets is because I only have one jump drive;  so in territories I can only go with one ship, I buy other ships there, locally, and park them when I leave that territory.  I would never have thought of parking ships in various places that they can actually reach me from.  Now I fail to see the point of that;  but failing to see the obvious, probably, I am.

That being so, I would now suggest an addition, plus a change of name.
I'd change the name of **[Un-park All]** to **[Summon All My Ships]** and then add a button **[Un-park All]** that un-parks all _**local**_ ships.

**Comment by ChuckStarchaser** [comment]
And, before this becomes yet another Issue ...
perhaps the **[Summon All My Ships]** button should still NOT un-park ALL ships unconditionally;  perhaps it should check that each ship,

- a) is in flying condition
- b) has enough fuel, or a ramscoop, to reach the player's location
- c) has a jump drive, or can reach the player's location without one

**Comment by binaryspica** [comment]
For me, ALL ships I use equip a Jump Drive, and usually I leave my warships stay in any planet and don't use them unless I want a real combat(against Korath or Unfettered Hai, for example). Since my Bactrians are enough escort for my fleet usually I don't need a warship at all. So when I want those warship, I will unpark them, and they are starting to come for me across the galaxy. That is important because I don't need that much expensive escort to buy and sell stuffs.

**Comment by ChuckStarchaser** [comment]
I understand.  Me, I only have one jump drive, and that's my only reason for having fleets in other places.  My main fleet is made up of 9 scarabs for protection, a StarQueen for people transport, and 9 Behemoths, which are not very good fighters at all, so I need my scarabs.  Perhaps later in the game I will have jump-drives galore.  Right now I'm desperately looking for where to get a second one just to give it to the Unfettered B***TARDS ...

**Comment by ChuckStarchaser** [comment]
Best feature is no feature.  Fastest instruction is no instruction.
I'd go for (a).

**Comment by binaryspica** [comment]
> 

I agreed that, it is weird that they encounter no threats, but if there also the threat then the game should allows micro control through the galaxy as well. And regardless how scattered they are, you still pay for these ships(in fact, its crews) per a day, so I don't think that it is not so unfair either.

Also those suggestions should makes the game chunky as well.

**Comment by ChuckStarchaser** [comment]
@mOctave:  Ahhh, I didn't know you saved crew salaries by parking!  I'm going to adopt your strategy, then.  And (b) sounds better now.

**Comment by quyykk** [comment]
There's a separate button now to park/unpark local ships. I don't think renaming the unpark all button is a good idea, because it's less clear than "unpark" IMO.

If you feel that your issue isn't addressed, feel free to reopen!
