### ISSUE TITLE
A rethink of the landed on planet interface

### ISSUE THREAD

**Issue by ChuckStarchaser** [endless-sky/endless-sky#7550]
### Problem Description

The current interface when landing on a planet is not quite intuitive as to what exactly it represents:

1) For the most obvious example, it has a button labelled "Spaceport", even though if we just got out of the ship, we are presumably IN the spaceport already, and therefore should not need to GO TO it.  Should perhaps the first info you see not be about the spaceport, and then a Planet button display info about the planet?

2) Then the buttons Bank, Trading, Outfitter and Shipyard:  Are those buttons that are transporting me physically to those locations?,  or am I interacting with them electronically?  Is this whole interface, with the text in the middle and the buttons around, is it a computer terminal or info kiosk in a room at the spaceport?  Or is it my personal computer I'm using?  Or is it an galaxy-wide standard app, running on my personal computer, but accessing the local spaceport database?

3) What happens when I hit I (Info)?  Why is the interface now so different?  Is that like I'm switching from a computer at the spaceport to using my own personal computer?  Is this the I interface, or rather, the device where my personal info is?  Am I anonymous when on the spaceport computer?

You could argue that as long as all the functionality is there, there's no need to know what it is.  Perhaps...  But lack of clarity on these questions can lead to lack of clarity in future questions with potential for game-play consequences.

For one example, in discussing possibly making 3D models for spaceports, someone said to me that Bank and Trading should be INSIDE the Spaceport.  Indeed, I never thought otherwise;  presumably the Shipyard and Outfitter should also be leasing space from the Spaceport;  but then I don't understand where we are, when landed, if we need to GO TO the Spaceport.  My idea for the 3D bases was that upon landing we'd be looking at the main atrium of the spaceport, indeed, and seeing the planet outside through its humongous glass windows, and looking a bit downwards you'd see the signs of the bank, the market, the bar, the shipyard and the outfitters;  and you click on one of them and you change backgrounds such that now you are inside a dark and smokey bar.  But yeath, everything starts with the spaceport.  The Planet would be like a monorail train terminal down there, maybe;  an Exit from the spaceport.

For another example, I have this active Bug/Enhancement Issue about the [Un-park All] button.  I was saying that it should unpark only the ships at the location.  Someone argued that the issue is not a bug because All means All.  I argued that at a given spaceport on a given planet,  All and All Here are synonyms, since they could not care less how many ships you own and have parked at what other locations.  But so, in retrospect, I think that he thinks as the Info interface as being personal, wheras I thought of it as belonging to the local spaceport.  Eventually there was some agreement about having an extra [Un-park All Ships Here] button.  I continued to insist on a rename, namely that the current [Un-park All] should be renamed to [Summon All], since the only use of un-parking ships far away is to make them come to you.  And that [Un-park All Here] perhaps should get the older button label, [Un-park All], since "All Here" would be synonymous to "All" at a given spaceport.
  But now I wonder if [Un-park All] (locals) should not be a button on the Spaceport interface, since it appears to me more and more that the [I] (Info) interface is more like a personal device (I could be wrong).

  You see how the lack of clarity in the status quo can engender further lack of clarity in the future.

### Related Issue Links

None.

### Desired Solution

The most desirable solution, I will insist, is that these questions be debated if necessary until clearly answered, the interface organization be fixed, at least on paper, and following that that there be a brainstorm about how to most efficiently express the true nature of these interfaces through in-game art, such as use of background images.

Far from wanting to push a solution, I'll use my current tentative personal fix of the landed interface as an example to illustrate the art concept:
  Ship comes in and lands, and possibly a tube comes and docks onto a hatch on your ship, but none of this needs to be represented.  Eventually you arrive at the main atrium at the space-port, like a huge shopping mall sort of place.
  So, the first "Room" when landed is, indeed, the spaceport's public center.
  From this center, there are the standard facilities, such as the bank, the market, the missions ("employment"?), a bar where you meet the shadier and story characters and get special missions, you have a door to go outside the spaceport, a planetary info kiosk, you have perhaps a restaurant?, a library?, washrooms like in Duke Nukem?, the outfitters and the shipyard, and finally an exit to the launchpad.  All these places are satellites to the spaceport.
  Inside each of these places there are kiosk computers you can use, like at an Internet Cafe.  You click on one, and now your background looks like the kiosk computer almost filling the screen, and the info shows where the screen is.
  It should be very clear that you are using spaceport machines and data, when you are.

  Wherever you are, you can bring up your tablet computer and do things in it that are more personal, such as summoning all of your ships, wherever they be parked, to come to you.
  Unparking those ships of yours that are parked locally would be accomplished by clicking an [Un-park ALL] button in a kiosk computer at the pad.  Where is the pad?  The pad is the exit from the spaceport public court, as you are about to launch.  There you can decide how many ships to take with you.
  When you call up your personal tablet computer, you should see your own fingers around the edges;  there should be no doubt that you are using a personal device.

  So, each "room" is basically a location artistically conveyed by the type of background displaid.

  Now, the question remains where the backgrounds come from.  My suggestion was, and is, modeling a dozen different spaceports in Blender 3D, including the satellite rooms and all;  then producing renders of each room.  One default model for all stations would ensure that no stations end up without textures;  and this default would be the first model.  From the second model onwards, they can be assigned manually, overriding the default.  Or it can all be done using 2D art... Or it can all be done using stock photos.  Variety can be obtained by combining models of stations with models of furniture in different styles, wallpapers in different styles, and each station having large windows, showing a view of the planet in the background.

  This Issue is not about advocating one particular style of art, but rather advocating that there BE art to clarify the landed on planet interface, its place and its function, as well as giving the game more ambiance than a screen full of text and numbers.

### Alternative Approaches

A more challenging approach would be using an actual 3D engine to walk around the spaceport like you are in Doom.

**Comment by Zitchas** [comment]
As just a tidbit of info: In the initial EV/O/N trilogy on which this game is based, the Spaceport was actually the Spaceport Bar. Basically, the iconic cantina from the original Star Wars: The place where independent pilots could go to eat, drink, meet with fellow captains, and be found by people with a need for independent minded captains to do something. I think in order to make it a bit more children friendly (or at least less alcohol centric) it was changed to no longer be an alcohol serving establishment.

Given MZ's admiration of the Firefly series, my expectation is that the planetary setups mirror what we see in the show: The Serenity frequently lands at all sorts of places, but even when landing at large metropolitan centers they typically step off their ship onto what basically feels like the street. The spaceport would be a structure, usually fairly close by, that houses whatever authority governs the landing area, along with facilities catering to starships and their crew. So the "Spaceport" term is probably refering to something more like a mall-like facility that houses a range of services including restaurants. 

For instance, in the Remnant missions, I typically describe the spaceport as being an area that includes an information desk, a mess hall / dining area, and various side rooms; and is typically located in close proximity to but not encompassing shipyards and outfitters. 

That being said, there's also some perspective here: For an outsider living on the world, probably the whole area is referred to as "the spaceport," much like we refer to an airport as being the whole place including hangars, and facilities. To a captain landing at it, though, the spaceport probably refers to the central control tower and main facilities, like a pilot might refer to the main building as being the airport building.

**Comment by ChuckStarchaser** [comment]
Very clearly explaine;  thanks!  I'm now wondering how I'd convey all this artistically.  Unfortunately, I'm not much of a 2D artist to make backgrounds right on Gimp;  to do anything good I need to Blender it.  Anyhow,  so the ship would look like it's on an open air ground landing, an there would be a big mall with a SpacePort sign, and other buidings for the yard and outfitter ...

**Comment by McloughlinGuy** [comment]
> Very clearly explained; thanks! I'm now wondering how I'd convey all this artistically. Unfortunately, I'm not much of a 2D artist to make backgrounds right on Gimp; to do anything good I need to Blender it. Anyhow, so the ship would look like it's on an open air ground landing, and there would be a big mall with a SpacePort sign, and other buildings for the yard and outfitter ...

By the way, all the 2D ship sprites are blender models rendered at an angle. You could just make a 3D model and render it at an angle, though admittedly I'm not much of a 3d artist so idrk if thats feasible. (might take too much work to make it look good even with blender)

**Comment by ChuckStarchaser** [comment]
Making it look good is not hard.  What may be hard is coming up with enough **different** spaceports to avoid monotony.
In Privateer there were about 30 systems in the map;  not 300 or however there are in ES.
The way they provided variety in that the systems were very different, even if they had very similar bases, due to zones of dangerous space rocks, the allegiances of bases, etc;  but the types of bases was limited:
There were three common base types,

-  Agricultural planet base
-  Mining base (asteroid)
-  Refinery (like an oil refinery in space)

But depending on allegiances, the colors and decor could change.
And there were three special, unique bases:

-   New Constantinople (government)
-   Perry Naval Base
-   Eden (The secret planet of the Retros)

For this game, however, I'd say we'd need about 5 standard bases and 5 unique bases for each faction.

**Comment by bene-dictator** [comment]
I think that any 3D environment, that the player is able to interact in, may be out of the scope of the game. For a 2D game, it might be too jarring. I see what you mean, though. It will definitely be a challenge to model hundreds of spaceports, especially for alien planets with architecture we know very little about, but I would like to see how you go about it. I can only see it as part of planet backgrounds, because to me, Endless Sky is beautiful through it's text and numbers. It doesn't have to be 3D. 

One of my favourite things to do (especially when I started playing about 3 years ago) was to fly to as many planets as possible just to know their background and environment, because I wanted to know the variety and history of worlds and how different their cultures and cities were. Unfortunately a lot of these descriptions are just between those two panels on the Planet screen, and event dialogue if the planet's lucky enough. For example, planets like Bourne (a pretty important planet) are not very descriptive. I cannot figure out why Bourne or Solace, major metropolitan planets, have no shipyard, while Glaze, which seems to be more of a desert world, does. This is another discussion though. 

I used to think that having the ship stay in orbit of the planet before choosing a spaceport to land at would improve this situation and give planets more life. But, it is more panels and writing for something that, after a while, the player will not want to bother with and will probably be used once on many occasions. It doesn't immediately add more dynamics to the game unless there is something linked to it. Maybe the player might finally get to land at that private spaceport on Hestia and see it for once, instead of it becoming one or two sentences on the spaceport panel. 

One way to explain having to press Spaceport for missions, is to have potential unique missions be presented to the player upon landing without having to press Spaceport. The player could accept the mission there, or if they decided not to, they could click the Spaceport to reconsider. However, a lot of missions would need to be re-written if it happens. It would help unique missions' exposure (to new players especially), but it increases the chance of missing out on missions that the player would have wanted to pick up but did not have space to accept them. It's not likely that Pookie's owner would wait for you in this instance. 

The Info (I) panel, or some version of it, should really be accessible from the shipyard/outfitters screen. I have a feeling that too many players have missed out on this crucial panel because they didn't read the little bit in the tutorial that talks about it.

**Comment by Zireael07** [comment]
> The Info (I) panel, or some version of it, should really be accessible from the shipyard/outfitters screen. I have a feeling that too many players have missed out on this crucial panel because they didn't read the little bit in the tutorial that talks about it.

Good point

@ChuckStarchaser I think 2-3 per faction + 1-2 specials would be enough for a first pass of this feature IF it ever happens

**Comment by ChuckStarchaser** [comment]
> I think that any 3D environment, that the player is able to interact in, may be out of the scope of the game. For a 2D game, it might be too jarring. I see what you mean, though. It will definitely be a challenge to model hundreds of spaceports, especially for alien planets with architecture we know very little about, but I would like to see how you go about it. I can only see it as part of planet backgrounds, because to me, Endless Sky is beautiful through it's text and numbers. It doesn't have to be 3D.
  Okay, first of all, I wasn't suggesting 3D interactions.  I'd model stations in 3D, and use those models to render images to use as backgrounds.  Right now you land on a planet, and the background is the last shot of the scene in space, which doesn't make too much sense.  Instead, you'd use the rendered image of the spaceport area, perhaps blended on top of a planetary image as is presently shown in a frame.  That same planet image could be auto-scaled to full-screen, and the rendered image of the spaceport area could be blended on top, and then the image of your lead ship could be blended on top, so that you see your ship landed.

> One of my favourite things to do (especially when I started playing about 3 years ago) was to fly to as many planets as possible just to know their background and environment, because I wanted to know the variety and history of worlds and how different their cultures and cities were. Unfortunately a lot of these descriptions are just between those two panels on the Planet screen, and event dialogue if the planet's lucky enough. For example, planets like Bourne (a pretty important planet) are not very descriptive. I cannot figure out why Bourne or Solace, major metropolitan planets, have no shipyard, while Glaze, which seems to be more of a desert world, does. This is another discussion though.
  Yeah, I would advocate a big electronic brainstorm, a withch-hunt of all the things that don't make sense and should be fixed, and fix them.  It's not too much work, I bet, and clean-ups are more rewarding than one tends to think.

> I used to think that having the ship stay in orbit of the planet before choosing a spaceport to land at would improve this situation and give planets more life. But, it is more panels and writing for something that, after a while, the player will not want to bother with and will probably be used once on many occasions. It doesn't immediately add more dynamics to the game unless there is something linked to it. Maybe the player might finally get to land at that private spaceport on Hestia and see it for once, instead of it becoming one or two sentences on the spaceport panel.
  That's always something to keep in mind;  not all good sounding ideas necessarily improve gameplay, once implemented.  That was the sad story of Masters of Orion III ...  they listened to their customers a bit too much, and the game ended up being as fun as database maintenance work.  The options for espionage were enourmous, for example;  but espionage was never a fun part of the game in MOO II in the first place;  and it was even less fun in MOO III.  Too many complications, and LESS graphics ... LESS eye candy.  Sacrilege!

> One way to explain having to press Spaceport for missions, is to have potential unique missions be presented to the player upon landing without having to press Spaceport. The player could accept the mission there, or if they decided not to, they could click the Spaceport to reconsider. However, a lot of missions would need to be re-written if it happens. It would help unique missions' exposure (to new players especially), but it increases the chance of missing out on missions that the player would have wanted to pick up but did not have space to accept them. It's not likely that Pookie's owner would wait for you in this instance.
  Well, it was explained to me that Spaceport used to be the "Spaceport Bar";  but that concerns about spoling the youthful players with ideas of alcohol caused its renaming to just "Spaceport".  Maybe we could meet mission givers are a Spaceport Gym.

> The Info (I) panel, or some version of it, should really be accessible from the shipyard/outfitters screen. I have a feeling that too many players have missed out on this crucial panel because they didn't read the little bit in the tutorial that talks about it.
  I can't remember how I discovered it;  I'm also the kind of guy that won't read a manual if you put a gun to my head.

**Comment by ChuckStarchaser** [comment]
![RENDER4](https://user-images.githubusercontent.com/68339418/203448283-b8202627-dfdb-4775-8df8-897f266c9960.png)

I wasn't going to upload this as it's a very early, unsatisfying attempt.  Those tracks and rails are supposed to look huge, as the round landing platforms are 400 meters in diameter.  The rails are for moving cranes, of which one will be showing on the right, and it's probably going to take many thousands of polygons to model.  There's not enough detail to convey magnitude, yet.  The monorail trains are actually double-deckers, as a normal sized train would have been too small to even see.  The landing platforms are actually about 6 stories high;  I will need to place exterior stairways to convey such height, and again, they may not resolve to the pixel size;  I need to think how else to convey size.

**Comment by Saugia** [comment]
We're pretty content with how the planet interface is designed at the moment. It's intentionally not overly-representative, more-so a generic landing screen with all the menus. I feel like making different scenes for each option or to convey ideas such as "computer panel vs. area" is a bit too excessive and would require a lot of effort for little gain. Also, having 3d spaceports would be a little odd when comparing to the realistic image landscapes, and the idea that a majority of the game is in a top-down view aside form outfits and scenes, which are more case-appropriate.
