### ISSUE TITLE
Aeon delivery to Ssil Vida - mission won't close

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#7554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Triggered mission to deliver Aeon cell from Viminal to Ssil Vida. 

Mission won't "complete" even when parameters have been met.

### Steps to Reproduce

Load savefile provided. Note Aeon cell in cargo. Jump to Ssil Vida. NOte that no dialogue is triggered for completing mission; mission stays active.

### Expected Behavior

Mission should complete.

### Link to save file

[Bass Ackwards~3022-07-14 9 (Aeon delivery borked).txt](https://github.com/endless-sky/endless-sky/files/9966343/Bass.Ackwards.3022-07-14.9.Aeon.delivery.borked.txt)

### Operating System

Ubuntu 21

### Game Source

GitHub Releases

### Game Version

Continuous build Nov 6

**Comment by warp-core** [comment]
I believe the issue is that none of your ships have enough cargo space to hold the Aeon Cell (it can't be split across multiple ships) so it is being (silently) sold when you take off, so you aren't actually delivering it to Ssil Vida.
This is a known issue, but I don't know if there is an issue speciffically for it yet.

**Comment by movingpictures** [comment]
Ah, crud. Yes. I had sold off an older vessel with more cargo space not long before this.

A warning/note would be nice. In similar situations, I believe this is SOP.
