### ISSUE TITLE
Can I make piercing weapons?

### ISSUE THREAD

**Issue by lehgogh** [endless-sky/endless-sky#759]
I want to make [a plugin for healing weapons](https://github.com/lehgogh/endless-sky-plugins/tree/master/ES-Nanobot-Weapons), but I'm afraid that the shields will absorb the projectiles and render them useless (even though they don't do shield damage). Is there any way to make a piercing weapon that bypasses shields?

**Comment by thenerdfreak** [comment]
I ran into this problem as well while trying to make a heal beam, the only way I could figure was to make it do a ton of shield damage all at once to repair the hull :p It only works on my ship's specific build though because they refill almost instantly

**Comment by lehgogh** [comment]
That would be a nice balancing factor. You can get healed, but you're shields are down the whole time.

**Comment by lehgogh** [comment]
Actually, I'll see if I can work my way through the code well enough to add a "piercing" attribute to weapons.

**Comment by DingusShingleton** [comment]
I have actually been thinking about shield piercing for the last few days and how that might function in game. My initial thought was that it would be interesting if every weapon had a very low amount of piercing, I'm talking *very* low, as in almost insignificant. Like a tenth of a percent or something. Not enough to matter in a single battle for instance, but enough that eventually, your hull will deteriorate to the point that you need to start thinking about landing for repairs. It could be explained as small amounts of wear and tear on the shield matrix (and thereby the hull) as it absorbs energy.

That then naturally leads to hull repair as an idea. It could work kind of like the ramscoop, in that it's not designed to actually affect combat, but rather is something that deep space pilots might have to seriously consider to enhance their longevity.

And finally, having set all that up as a game mechanic, you are free to bend the rules and create specifically shield piercing weapons and healing beams. I actually saw [this](https://www.reddit.com/r/scifi/comments/43wtl7/particle_beams_the_ultimate_hard_scifi_weapon/) post on reddit about how particle beams are the ideal scifi weapon because they pierce through everything and it was a perfect fit for a new shield piercing weapon.


But after all that I realized this was a pretty huge idea and would affect game balance, so I figure I should see what room thinks about it. Too much?

**Comment by lehgogh** [comment]
As long as we can keep it balanced, it should be okay. Honestly, I didn't think of having a value for piercing -- just a flag that would make it completely ignore shields. But now that I think about it, adding a small amount of piercing to (nearly) all weapons would be a good idea.

**Comment by lehgogh** [comment]
One question (prepare for gibberish): Given what's already been said, there will be an attribute in the definition of weapons that would appear as `piercing x`, where `x` is a positive nonzero number greater than 1. The attribute will not be required, and leaving it off will set `x` to 0. After this, should I:

1. make the weapon deal (x*100)% of its hull damage to the hull (ignoring shields) and 100% of hull damage to the shields

or

2. make the weapon deal (x*100)% of its hull damage to the hull (ignoring shields) and (100-(x*100))% of hull damage to the shields?

Here's an example, if that doesn't make sense:

A weapon deals 50 damage and has the attribute `piercing 0.1`. Should it

1. deal 5 damage to hull (ignoring shields) and 50 damage to shields

or 

2. deal 5 damage to hull (ignoring shields) and 45 damage to shields?

**Comment by endless-sky** [comment]
Ignoring piercing damage for a second, suppose your ship has 40 shields left, and is hit by a weapon that does 100 shield damage. You then will lose all 40 shields, and take (1 - 40 / 100) = 60% of the weapon's hull damage, too. That is, the weapon behaves as if it has 60% piercing.

More generally, suppose you have N shields remaining and the weapon does S shield damage and H hull damage, where S > N. Then, F = N / S is the percent of the damage that is apportioned to your shields. That is, you take:

- Shield damage = S * F.
- Hull damage = H * (1 - F).

The easiest way to implement piercing damage P, therefore, would be to just allow it to affect the F factor. For example:

- Start with F = 1 - P.
- If S > N, F = min(F, N / S).
- Then, use the same damage equations as above.

I think that would handle all the special situations (e.g. healing beams) correctly. It also has the advantage that the F factor could be used to scale the heat and ion damage. Unshielded ships take twice as much of those types of damage as shielded ships, i.e.:

- Damage fraction = 0.5 * F + 1 * (1 - F) = 1 - .5 * F.

So, the damage calculation code would be:

```C++
double shieldFraction = 1. - weapon.Piercing();
if(weapon.ShieldDamage() > shields)
    shieldFraction = min(shieldFraction, shields / weapon.ShieldDamage());
shields -= weapon.ShieldDamage() * shieldFraction;
hull -= weapon.HullDamage() * (1. - shieldFraction);
heat += weapon.HeatDamage() * (1. - .5 * shieldFraction);
ionization += weapon.IonDamage() * (1. - .5 * shieldFraction);
```

Note that that would imply that a weapon with piercing never does its full "shield damage" amount of damage to the shields, but I think that's preferable to the alternative. That is, if a non-piercing weapon does 50 shield damage and 50 hull damage, you know that it is always going to subtract exactly 50 hit points of some sort from the target. So it makes sense that the same would be true of a piercing weapon, rather than saying that 10% piercing means you do 55 total damage if the shields are up and only 50 once the shields are down.

**Comment by lehgogh** [comment]
If that code works, I'll put it (and the code needed to parse the piercing attribute) into a pull request as soon as I can.

**Comment by lehgogh** [comment]
This has been submitted (untested) in https://github.com/endless-sky/endless-sky/pull/772.
