### ISSUE TITLE
Add command to tell escorts not to fire weapons with limited ammo

### ISSUE THREAD

**Issue by speeder** [endless-sky/endless-sky#76]
I noticed escort ships that have missiles will always fire lots of them until the enemy is dead.

It is not uncommon to see a escort detect a incoming fighter from hyperspace, and them shoot sevearal volleys of missiles before you even figure where the enemy is, missiles that are enough to kill the guy 4 or 5 times over.

Then you land and discover you have to buy 100k in missiles that your ally used to kill a 300k ship.

**Comment by endless-sky** [comment]
I usually refit my escorts with laser weapons. That way, they aren't wasting valuable ammo, and it also means they can stop firing the very instant the target is disabled, reducing the risk that it will get destroyed before you can plunder it.

Just click on the icon of an escort in the "Your Ships:" sidebar to switch to outfitting it instead of your flagship. You can also shift-click or control-click to outfit more than one escort at a time (which is particularly helpful if you have several of the same kind of ship).

**Comment by speeder** [comment]
Oh, I figured that, but I think after you reach 1.0 or something like that and reach a wider release, players will expect this to be "fixed" without they needing a workaround. (I personally also remove ammo-based stuff from ships, but from a gameplay perspective if you end removing it from all your ships, why have them in the game?)

**Comment by akien-mga** [comment]
Maybe there could be some macro-management options, to tell the AI how it should handle escort ships: defensive, aggressive, preserve ammo, etc.

**Comment by endless-sky** [comment]
As of 0.8.8, your escorts will be "frugal" with missiles, but the long term solution is probably to add a preference that lets you toggle between escorts never firing missiles, firing frugally, or always firing.

**Comment by endless-sky** [comment]
In commit 39e28db, I've added a preference that controls whether your ships will expend ammo always, frugally (as in 0.8.8), or never. You can switch it on or off by bringing up the main menu in the middle of a fight, which I know is not ideal, but it's the best option until i get around to making some sort of comprehensive fleet commands UI.

**Comment by endless-sky** [comment]
0.8.9 is now released, so I'm closing this.
