### ISSUE TITLE
Dual Wormhole

### ISSUE THREAD

**Issue by McloughlinGuy** [endless-sky/endless-sky#7605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After the syndicate projection over the wormhole is taken down, there are now two wormholes in Ultima Thule.

### Steps to Reproduce

Play hai reveal up to the point where the wormhole syndicate advertising projection gets removed, and then it should appear.

### Expected Behavior

There will be two wormholes.

### Screenshots

![Screenshot (165)](https://user-images.githubusercontent.com/70719891/201769805-9a11cc73-3001-4b3a-83ab-670cc3b84cdd.png)

### Operating System

Windows 10

### Game Source

ESLauncher2

### Game Version

Continuous 

### Additional Information

The problem doesn't go away even after hai reveal is over. There might need to be a quick fix for players who encountered this bug playing the continuous build, not sure though.

**Comment by warp-core** [comment]
Can you upload your savefile?

**Comment by McloughlinGuy** [comment]
> Can you upload your savefile?

[George Evans.txt](https://github.com/endless-sky/endless-sky/files/10007519/George.Evans.txt)

**Comment by warp-core** [comment]
The issue seems to be that the period of the wormhole is 2158.49, but the events attempting to remove it use 2158.5, so they aren't removing the original, but a new one is still added.
A similar thing seems to be happening in Danoa.
Both thing should be fixed in thsi save file: 
[George.Evans~fixed maybe.txt](https://github.com/endless-sky/endless-sky/files/10007590/George.Evans.fixed.maybe.txt)

**Comment by warp-core** [comment]
Fixed by #7639.

**Comment by McloughlinGuy** [comment]
happiest I've ever been to see my issue get closed
