### ISSUE TITLE
Feature: Choose amount of crew transferred after capturing a ship

### ISSUE THREAD

**Issue by the2nake** [endless-sky/endless-sky#7610]
### Problem Description

When capturing ships with high personnel counts, I often end up with almost no crew left on my flagship, making landing extremely tedious.

### Related Issue Links

[#7608](https://github.com/endless-sky/endless-sky/issues/7608) is tangentially related.
[#4100](https://github.com/endless-sky/endless-sky/issues/4100) is a similar mechanic, but for cargo.

### Desired Solution

Being able to keep most of the surviving crew members on my flagship would make capturing ships (and landing to repair them) a much simpler process. I would like some sort of pop-up window to appear after "You have succeeded in capturing the ship", prompting me to enter the number of crew to move to the new ship, along with an option to automatically assign crew members (as is being done currently).

### Alternative Approaches

An alternative approach could be to set a setting for the percentage of crew members to move by default.

**Comment by bene-dictator** [comment]
I don't think this will happen with ES's current boarding mechanic because it would make a boarding-dominated playthrough potentially much easier, and boarding is already the best thing to do in the game. The most optimal play would be to move one person to each captured ship, which maximises the amount of ships that the player is able to take in one take-off (A ship vastly under the required crew count will automatically land at the planet the player lands at, as long as its in the same system). This would take away the most painful part of boarding, landing without enough crew to pilot the ship. Maybe it's explained by the player shuttling crew back to the new ship once it's captured, after you've landed, but on the other hand, I can't see why I could just have another ship with 500 people to dock with and replenish my crew. 

I think boarding action needs some more thought than almost mindless "click to kill 200 people so you can get this ship" but there isn't really anything simple that could replace it yet. (Somehow, ships' value aren't as affected by murder as houses.)

**Comment by vitalchip** [comment]
Boarding is already so easy, lucrative and consequence free that it would be hard to justify removing the one inconvenience handed to the player, especially when it only happens in marginal battles or if the player is being greedy and trying to capture too many ships in one go.

If you have a ship needing 80 crew, a capture needing 50 but you find yourself with only 100 crew remaining after the battle then they'll be distributed at 62/38 leaving each ship broadly 77% effective.

Allow the player to choose the number and every time they'll transfer 20 because they don't want to face even a minor inconvenience and they know they can use one of the other exploits and not have to care about the partly functional captured ship (jump away and the captured ship is safe or land and the captured ship lands with you)  At that point might as well remove the mechanic altogether.

**Comment by Hurleveur** [comment]
Yes I am totally against something like this until we fix boarding.
