### ISSUE TITLE
[suggestion] "hacking" weapon that would make a ship turn on other ships of its fleet

### ISSUE THREAD

**Issue by egilburg** [endless-sky/endless-sky#764]
Missile-based weapon (really expensive missile with low ammo capacity, maybe just 2-3 ammo). Ideally homing, but dumbfire could work as well.

Once it hits a ship, it would have a probability to hack the ship and make it attack (and be attacked) by other ships of the same fleet. Strong enemy shields and hull would reduce chance of hack. If hack succeeded, the hacked ship would temporarily stop showing up as hostile for you and your fleet, but purposefully damaging the hacked ship (or trying to board it) would stop the effect of the hack.

The goal of hacking a ship isn't an easy kill/capture, but rather an infiltration tactic to deal with large enemy fleets, making enemies turn on each other and causing distraction you could use to slip by or escape. It could also be useful as a quest device. If later stationary defenses such as a turrets or pylons are introduced, those could be hacked in the same fashion.

An important aspect of this feature is aggro. If only the hacked ship detected you hacking it and nobody else, you would not incur enemy aggro, neither same-day aggro nor long-term reputation loss. 

A hacked ship not destroyed would have the hack wear off after a while. It would not remember the circumstances of the hack so would not treat you as an enemy (unless you attacked it after the hack). Note that this depends on your pre-hack status - if you hacked an already hostile ship, it would revert to being hostile once the hack wears off.

**Comment by jafdy** [comment]
If this 'hack torpedo' is capable of guiding and operating a ship all on its own then why wouldn't some one buy, it pull out the computer and put it in their ship then fire their crew to save on their salary? But that beside it's a nice idea.

**Comment by masterpierround** [comment]
Sorry that this isn't terribly relevant to the OP, but people wouldn't use it to replace their crew because a) it wears off, and b) it can't fight. This means that you would have to buy a new one for every day of travel which would be more expensive than crew, presumably, and also, your ship could be captured by a single pirate in a Sparrow, because you have no crew to defend against boarders.

**Comment by lehgogh** [comment]
@masterpierround I agree with you, but this would be a good opportunity for automated defense systems (small ceiling-mounted turrets in front of doors). Actually, why don't those exist in the game yet? (Or do they?)

**Comment by lehgogh** [comment]
Alternatively, it would be simpler to have hacking torpedoes make enemy ships act as if they don't have any/enough crew piloting their ship.

**Comment by jafdy** [comment]
That would be a better option.

**Comment by natangold** [comment]
+1 for hacking torpedoes temporarily giving a ship a temporary negative crew penalty - a hacked ship would be easier to disable and capture, but if you don't have enough to crew the ship afterwards, you might end up with two ships that can't fly straight (figuratively speaking).

Also +1 for robotic crew that take up outfit space rather than bunks, especially if robotic crew could count toward defense against being boarded, but not be useful for boarding another ship (i.e., by counting as [living] crew for defense, but not counting as crew for offense). For balance, these robots would need to be rather expensive up-front ($100-$300k per "crew" slot they provide), but allow for lower daily crew costs (possibly requiring $1-$15 per day per crew replaced in crew costs to account for depreciation and maintenance costs).

**Comment by endless-sky** [comment]
This seems like it would be way too overpowered - I can't think of any good way to balance it.
