### ISSUE TITLE
Scanners have been nerfed too much

### ISSUE THREAD

**Issue by Pointedstick** [endless-sky/endless-sky#7640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Due to the changes in https://github.com/endless-sky/endless-sky/pull/6193, successfully scanning another ship with a single human-space scanner is now practically impossible if the other ship is moving. 

### Steps to Reproduce

Manifestations of the issue:
1. The player needs to install 5 or 10 scanners to have any chance of succeeding at missions that require scanning other ships
2. Other ships with scanners that have the "scans" personality and only one scanner like the Republic Gunboat will never successfully scan the player's ship, resulting in those ships simply following the player around forever futilely trying to scan them.

### Expected Behavior

1. Missions that require scanning other ships that move are at least doable with one scanner, and easier with 2 or 3
2. Other ships that try to scan you can succeed at it

### Link to save file

[Morgan Atrasco.txt](https://github.com/endless-sky/endless-sky/files/10037778/Morgan.Atrasco.txt)

In this save I had to equip 10 outfit scanners to succeed at the active mission. With 2, I found it impossible.

### Operating System

Fedora 37

### Game Source

Built from source

### Game Version

commit SHA d925975124dcf3ae67760b161b5e4459056ace5d

**Comment by Ferociousfeind** [comment]
I see...

Playing around with scanners with some scrutiny, both with a single scanner and also with a large number (40t total, 20 cargo, 10 outfit scanners), I think that the following changes sustains the vision I had- which was drawing out the scanning minigame and maintaining it as a part of the game, even in lategame, even with a significant amount of scanning power behind you.

```
cargo scanner
power of 9 -> 24
speed of 1 -> 5

outfit scanner
power of 16 -> 32
speed of 1 -> 15
```

The power changes I am not attached to, since that has to do with viable scanning distance, and that's a little bit difficult to gauge, and also by the sounds of it, you didn't have trouble _beginning_ a scan, just _finishing_ one.

**Comment by tehhowch** [comment]
Needing to increase scanner speeds by [3 to 18x](https://github.com/endless-sky/endless-sky/pull/7649) to compensate suggests that the implementation from #6193  is flawed.

**Comment by Amazinite** [comment]
Is it, though? #6193 increased the necessary scan time by 10x. It then cause scan speed to decrease with range from 100% at 0 range to 0% at max range. Let's just take the average of that and say scan speeds are cut in half. That's 20x scan time between those two changes alone. Then there's the fact that larger ships now take longer to scan, which could mean 2x to 4x longer depending on ship size, particularly for outfit scanners. So that level of scanner speed increase seems expected to me with the changes that were made in that PR.

**Comment by Ferociousfeind** [comment]
> Needing to increase scanner speeds by [3 to 18x](https://github.com/endless-sky/endless-sky/pull/7649) to compensate suggests that the implementation from #6193 is flawed.

Rather, I say that it shows that scanners were 3x to 18x too strong before the change

Don't forget that you never needed more than maybe 10t of scanners in terms of scanning speed to get basically instantaneous scanning (meanwhile range was fine in mechanics, and I largely did not touch range)

The slowing changes are intended, and it was negligence (forgetting why I changed scan speed to be much larger thsn it used to be, because it has been months since I did that :P) which let scanners remain with 1 scan speed across the board

**Comment by tehhowch** [comment]
I should have stuck with my original comment, which was along the lines of, "needing to increase all definitions of an existing attribute by a nontrivial amount is a breaking change."

It is still possible to do what that PR intended without introducing a breaking change, by translating the existing attribute(s) into new ones during game load. To help plugin authors learn that there is a new way to define these parameters, the game would emit a deprecation warning when processing the old attribute.

Such an approach also doesn't break built-in scanners in e.g. player-purchased ships or those from an accepted mission.

**Comment by Pointedstick** [comment]
Yeah, in addition, I don't think this is fixed yet. Even with the latest change, the "scan a bunch of fast Republic cruisers" mission is painfully slow and un-fun with two scanners. The problem of gunships (with a single scanner) swarming you due to failure to complete their scans hasn't been fixed, either.

Here's me trying in vain to scan a Republic Cruiser (you can see 0% progrss on my scan) while a literal fleet of Gunships try in vain to scan me:

![fleet](https://user-images.githubusercontent.com/1097249/204973025-362973c8-3146-4734-99f2-7819a6b2fda1.jpg)

Maybe turning scanning into a mini-game wasn't the right choice. Frankly it isn't a very fun mini-game, as currently implemented. It makes a chore task seem like more of a chore to me, not more of a game.

**Comment by Ferociousfeind** [comment]
I'd like to gently urge you to adjust your perspective... two scanners is either 2 or 4 tons of stuff. Less than a single energy blaster. Is it reasonable to expect a single energy blaster to dispatch pirates, or anything for that matter? Energy blasters only find strength in numbers, by bringing their total tonnage up.

In the mean time, I can re-jig scanning ships (mostly the gunboats) to simply have more scanners like they should. I'd prefer upping the size of scanners so that this absurdly weak minimum strength isn't achievable in the first place (I'd consider 2 tons of scanners a mistake, just as going into combat with one energy blaster is a mistake) but that would _actually_ (or, _extra_) break things, by interfering with pre-existing player ship builds which include scanners already by going over the outfit space limit.

I could perhaps adjust the changes so that the bare "cargo/outfit scan speed" attribute pair is left untouched, and instead the new mechanics are under a different named attribute pair, but I don't intend to change the name of scanners to accommodate the deprecation of "cargo/outfit scan speed", so this is a bad idea unless there are actual working replacement names (for both scan speed, and the scanning outfits) under consideration.

If I had the utter unwarranted confidence to touch the rendering pipeline, I'd visually spruce up the scanning minigame to better emphasize strategic positioning (either closing in on your target, or shaking off tails trying to scan you) and make it a little visually appealing, but I do not have that confidence, and I wouldn't know what to touch to get a visual cue to scanning to work.

**Comment by Zitchas** [comment]
> I'd like to gently urge you to adjust your perspective... two scanners is either 2 or 4 tons of stuff. Less than a single energy blaster. Is it reasonable to expect a single energy blaster to dispatch pirates, or anything for that matter? Energy blasters only find strength in numbers, by bringing their total tonnage up.

Before we start digging into the size or mass of the scanners I think we need to take a step back and think about the end goal. Is scanning a minigame that is intended to take place as a complimentary activity to other ship tasks (such as combat or transport)? Or is it intended to be an *alternate* or primary minigame compared to these other things?

If it's an *additional* activity that is expected that most ships can undertake... competently... without compromising their primary activities, then scanners should remain quite small. Certain specialist variants may compromise combat and other capabilities in order to have exceptionally good scanning, but general purpose ships should be able to complete general scanning tasks OK.

On the other hand, if scanning is supposed to be a major ship specialization, on par with combat capabilities or cargo or passengers; then it makes sense for it to take up a commensurate amount of space. In this case, ships that *aren't* sacrificing their capabilities in other areas would be expected to have difficulties performing all but the simplest of scanning tasks.

Up until recently, scanning has been in the former category, that of an additional activity that ships can engage in, but is generally expected to be something that ships spend their discretionary space on. That is to say, they spend the space that would normally be filled with non-critical stuff like fuel tanks or cargo expansions or multiple ramscoops. Stuff that can be removed without compromising the core ship capabilities.

Now, I can't speak as to the current state of things, because it is only in the last few days that I've finally been able to play again, so I don't know what scanning jobs are like yet.


My personal expectation is that scanning is generally the former category of activity: An additional thing that we can add to our ship, probably taking up some or all of our "optional outfits" space, but not seriously digging into our core functionality. This is for the run of the mill stuff, though. 

I'd like to see a wider spectrum of scanning task difficulty that, very crucially, is clear about communicating the difference. 

For instance, I'd expect that pretty much anything with a single scanner should be able to do basic jobs for local authorities requesting the player do customs scans of incoming freighters without issue. They're (usually) not dodging the scan, they're not fast ships, etc. This should be the player's intro to scanning, and it should be pretty easy unless the player really puts themselves at a disadvantage.

On the other hand, a job doing a customs scan on a suspected smuggler that operates a high speed transport and is known for avoiding authorities... That should clue people in that this isn't going to be a run of the mill easy job. I'd expect someone to need either 2-3 scanners, or a faster ship, or both.

Then one has a corporate espionage job targeting a fast corporate transport carrying a new prototype manufacturing equipment between two classified labs, and is unlikely to even stray into the inner system of the area identified to scan it. That's the sort of mission that the player should expect to need an actual specialized scanning ship to accomplish. One that has a large amount of scanners on a fast platform, for instance. Actually sacrificing combat, cargo, or passenger capacity in order to get the required capabilities.


Anyway, this is just what I'd expect from scanning jobs. Larger ranges of difficulty, more clarity as to what the difficulties are, and, crucially, the outfits calibrated such that, at the very least, the most basic of scanning jobs can be completed reasonably well in most ships with a single scanner. I don't think we want scanning to be at the same level as combat in terms of space consumption onboard ships, although I certainly wouldn't be averse to having a few jobs/missions that rewarded people for having such impressive scanning setups.

**Comment by Amazinite** [comment]
I think either of the following is in order:
1) pull back on the dropoff so that at max range you're scanning at 50% speed instead of 0% speed, or
2) remove the speed dropoff entirely; bigger ships taking longer to scan should be enough extra depth to scanning, as it isn't a system that needs to be overly complex.

The speed dropoff seems to be the biggest killer from what I can tell. If I'm right on top of a Bactrian with 6 outfit scanners (only 12 tons of space spent on scanners) then it takes a few seconds to scan it, but it's nothing terrible. As soon as I'm trying to scan it from a distance, though, the scan progress moves at a snail's pace.

**Comment by Pointedstick** [comment]
I agree with either of those suggestions.

**Comment by Ferociousfeind** [comment]
I recall at some point considering zero scan strength drop-off until 50% range (and then dropping linearly to 0% strength), which is another possible suggestion.

Also important to keep in mind is that me naively implementing any suggestions would result in a curvy quadratic version (because distance is still being measured as distance squared). That said, making the drop-off from 100% to 50% instead of 0% would be easily doable too.

**Comment by Zitchas** [comment]
I do like the idea of the drop-off, I'm just not sure how well it actually works or affects gameplay, so I'd opt for one of the options that retains it but reduces its impact. 

Just thinking about it, and given that we really have no indication of range, having a linear drop-off from 100% at 0 range dropping down to 50% strength at max range would be the smoothest and probably easiest system for people to figure out, since its continuous, and people can watch it change at different distances. Having the initial "100% out to 50% range, then drop from there" might end up confusing people. If it's all the same linear scale, then people can experiment more easily (say, using really slow ships to test the scan on while they slowly move around it.

**Comment by Pointedstick** [comment]
saw a commit related to scanning (https://github.com/endless-sky/endless-sky/commit/e3d6981a021ee2beffa314a578c7cf052a212e16) so I just tried playing the "scan all the cruisers" mission again with today's git master and I'm sorry to say it still isn't any better from my perspective. I equipped two Cargo Scanners in a Splinter with 410 top speed and 150 accel, and I still can't manage to complete a single scan without giving up in frustration after realizing I'm having negative fun.

Scanning is still agonizingly slow at anything other than point-blank range, which is very difficult to achieve because the souped-up cruisers are faster than my ship. They can also fly away and erase my scan process pretty much at will. It's quite frustrating. I tried with 4 scanners and it was marginally less frustrating but still quite un-fun. At 6 scanners, it became sufficiently un-frustrating that I was able to complete the mission. But that doesn't help the second manifestation of this issue, which is slow gunboats with only one scanner endlessly following the player. And do we *really* want to require that player ships have like 6 human scanners to have any chance of completing a scan of a reasonably fast ship? This seriously devalues Interference Plating, too.

Honestly I think the design goal to turn scanning into a fun mini-game is a failure and ought to be reverted. Scanning is a chore task, and making it harder does not a mini-game make. I really think we should return to scanning tasks to being doable with one scanner, and easy with 2 or 3.

Save file attached.

[Morgan Atrasco.txt](https://github.com/endless-sky/endless-sky/files/10549443/Morgan.Atrasco.txt)

**Comment by UnorderedSigh** [comment]
Here's my fix to un-nerf scanners: a gaussian drop-off of scanning speed. @Pointedstick's save works about as well as scanners did before they were nerfed, but the scan speed still depends on cargo and outfit size.

https://github.com/endless-sky/endless-sky/pull/8288

**Comment by UnorderedSigh** [comment]
I figured out how to solve the other half of the problem and reduce the number of required scanners to a reasonable level so the Navy and players get a reasonable scan time at point-blank range. Amazingly, the solution comes from physical reality!

There is an error in the calculation of the dependence of scan time on ship size. When you're doing remote sensing, you do not scan the entire three-dimensional structure of the target to determine its contents. You scan the cross-section, and the quantity in each pixel is the magnitude of the return. The dependence should be `1/pow(depth,0.6666)` instead of `1/depth`. Also, the `max(10., cargo)` should be more like `max(40., cargo)`. That'll leave you with about 6x as many scanners to scan a Bulk Freighter than a Sparrow, rather than 40x.

That changes the same line of code as #8288, so I think I should wait for that to be merged before PRing this change to the formula.

**Comment by UnorderedSigh** [comment]
I had to put the size dependence update in #8288 otherwise illegal missions were impossible.

That means #8288 should fix *both* of the issues @Pointedstick mentioned, without removing the new mechanics of the ship size dependence and 10-second rule.
