### ISSUE TITLE
"Wanderers: Truce Check" Requires Landing on Restricted Planet to Continue Storyline

### ISSUE THREAD

**Issue by Aneutronic** [endless-sky/endless-sky#7701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After finishing the Free World's campaign, continuing the post-Free World's Wanderers campaign results in being given the "Wanderers: Truce Check" mission which requires landing on Vara K'chrai, a restricted world closed to the player. The planet is un-bribable. Landing on the planet, and thus continuing the campaign, is impossible.

### Steps to Reproduce

1. Complete the pre-Free World's Wanderer campaign.
2. Complete the Free World's campaign.
3. Land on a Wanderer planet.
4. Accept the mission to check on Iktat Rek.
5. Go to the "Vara K'chrai" system.
6. Try to land.
7. If unable to land, try to bribe the officials.

### Expected Behavior

Player is able to land on the planet and complete the mission.

### Link to save file

[Gerold Martin.txt](https://github.com/endless-sky/endless-sky/files/10086740/Gerold.Martin.txt)

### Operating System

Windows 10 Pro

### Game Source

Built from source

### Game Version

v0.9.17-alpha Latest as of 11/23/2022

**Comment by Aneutronic** [comment]
After looking through the game files, it seems that the player is expected to have a reputation of at least 25 to land on Vara K'chrai, but the mission is offered even if the player does not have this reputation. Either the player should be prompted to do more jobs for the Wanderers before taking the mission, or the reputation requirement should be waived to allow the player to land.

**Comment by warp-core** [comment]
Did you update from 0.9.16(.1) since the last time you did a Wanderer mission?

The Hai Reveal story has been merged since that release and adds the required reputation to Vara K'chrai (this was not present previously which is how you were able to land there before). You are expected to complete the Hai Reveal missions which will remove the reputation requirement from Vara K'chrai.

If you do not wish to do this, I suggest returning to the latest proper release to continue the Wanderer or story, or edit your save to raise your reputation with the Wanderers. Others have been able to gain reputation by repairing Wanderer ships, but I suspect this won't be possible for you since I think the Unfettered are not currently attacking the Wanderers.

**Comment by Aneutronic** [comment]
How do I complete the Hai Reveal missions?

**Comment by warp-core** [comment]
If you spend some time jumping around human space and landing on planets, you should get the missions that start Hai Reveal.
It starts on a timer that can be up to 2 months (in game), I think.

**Comment by Aneutronic** [comment]
Okay. Thanks. In the meantime, maybe the "Wanderers: Truce Check" mission should be modified to ensure that it is not given to a player who has not complete the Hai Reveal mission chain.

**Comment by Hurleveur** [comment]
Or even better just give it clearance so ppl are not blocked.

**Comment by warp-core** [comment]
While the player may be more likely to update prior to beginning this mission since it is preceded by a break, they could update at any point in the Wanderer story, and so could have any of the missions destined for Cara K'chrai which would be impossible to complete at this point since they don't have enough reputation to land.

If we decide the solution to this is to either have this mission check for if HR is finished yet, or have it give clearance, we should then add this to every mission, else we'll probably just end up with more issues almost identical to this with people stuck at different points. And, doing it to every mission just seems like the wrong way of doing things. Even if missions to the restricted Vara K'chrai no longer offer, people will instead just get no mission where they were expecting one, this will not only create it's own confusion but then probably also make it much more difficult to pick up the Wanderer story where they left off after doing HR because it could be any one of a variety of planets. And, they would find that Vara K'chrai is restricted when it previously was not. Players may then think they have done something to upset the Wanderers even though they haven't.

Really, this whole interaction between HR and the Wanderer story needs to be reworked before we decide how to create a smooth transition for people who are partway through the Wanderer story when they update.

**Comment by Hurleveur** [comment]
Yeah I totally disagree with the rep limit.

**Comment by MasterOfGrey** [comment]
There is a very simple fix - simply add a mission/event that only triggers if you've already started wanderers before Hai Reveal is included in your game (check for end conditions) and update the wanderers reputation to allow continuation accordingly.

**Comment by Amazinite** [comment]
Fixed by #7889.
