### ISSUE TITLE
duplicate copyright entries

### ISSUE THREAD

**Issue by real-dam** [endless-sky/endless-sky#7711]
### Location

./copyright

### Describe the issue

Thanks for maintaining the copyright and licensing information in one place!

During the upgrade of the Debian package, where there is a very similar file part of the packaging metadata, automated checks discovered that some file patterns are present in more than one stanza with different copyright holders.

I think a similar issue is present in the high-dpi repository, but perhaps for different set of patterns. Will report that separately when I get to it.

Here's the list. I hope this is not very difficult to fix.

 * images/outfit/brig*
 * images/outfit/fuel?pod*
 * images/outfit/gat*
 * images/outfit/jump?drive?(broken)*
 * images/outfit/plasma?repeater*   (three times)
 * images/outfit/proton?turret*
 * images/outfit/scram?drive*
 * images/projectile/korath?digger*
 * images/ship/auxiliary*
 * images/ship/barb*
 * images/ship/vanguard*
 * images/thumbnail/auxiliary*

### Expected content

Can't really propose a fix.

**Comment by quyykk** [comment]
> automated checks discovered that some file patterns are present in more than one stanza with different copyright holders.

Are those automated checks published somewhere? A while back I added a CI run that checks the copyright file for syntax errors using the Debian copyright package, but more checks is always better :smile:

**Comment by real-dam** [comment]
> Are those automated checks published somewhere? A while back I added a CI run that checks the copyright file for syntax errors using the Debian copyright Python package, but more checks is always better

https://lintian.debian.org/sources/endless-sky

But these are run on the Debian package - not suitable for CI.

I also run that on a locally built package exactly to verify if there are potential problems. Lintian (the tool producing the report above) checks for hundreds of problems, so it is not very fast. Also, waiting for the package to build takes several of minutes, so I went on and created a quick and dirty version that only checks the copyright. For now it is available at <https://salsa.debian.org/dmn/cpr-check>.

It is run like `cpr-check copyright`. Some documentation is available via `perldoc cpr-check`. It requires one Perl module - Object::Pad. Perhaps it can be plugged in the CI somehow.

**Comment by Zitchas** [comment]
Just working on a PR to clean this up thanks for pointing it out!

- Brig was originally by Nate and redone by Becca (so should just be listed as Becca derived from Nate.
- Gat is listed as created by Maximilian, but is also listed under Becca derived from Michael. @beccabunny Should this actually be derived from Maximilian? Or did you not use any of Maximilian's work, and instead derived exclusively from Michael?
- jump?drive?(broken)* is listed as Darcy derived from Michael, as well as being a creation of Scrinarii1337. Will take some digging to figure out which is accurate.
- /plasma?repeater* is Darcy from MZ, Becca from MZ, and Becca from Darcy & Michael. This last one is the correct one, I think. Can you confirm, Becca?
- proton?turret* I am only finding once in the main copyright file, however there's both a `proton?turret*` and a `proton turret*`, which are obviously the same thing, and the "Becca derived from Nate & Michael" would be the correct one.
- images/outfit/scram?drive* Originally by Evan, now Becca from Michael. Another one we need to check if Becca just ditched Evan's work and only derived from Michael, or if it should be moved to a "Becca from Evan & Michael" section.
- images/projectile/korath?digger* (I think this one will be changed/fixed in a currently active PR)
- images/ship/auxiliary* Originally Evan from Michael, now Gefullte from Michael. @GefullteTaubenbrust2 Is this correct, or should it be you derived from Evan & Michael?
- images/ship/barb* first listing is by Iaz, second is by Iaz with detailing by Becca. Second is the correct one.
- images/ship/vanguard* first is by Nate, second is by Nate with detailing by Becca. Second is the correct one.
- images/thumbnail/auxiliary* Originally Evan from Michael, now Gefullte from Michael. @GefullteTaubenbrust2 Is this correct, or should it be you derived from Evan & Michael?


Alright, so I'll have a PR up shortly fixing some of these, but I'd appreciate if @beccabunny and @GefullteTaubenbrust2 could confirm the situation with the ones that they did.

One's I'd like Becca to confirm:
- Gat
- plasma?repeater
-  images/outfit/scram?drive*

One's I'd like Gefullte to confirm:
- images/ship/auxiliary* 
- images/thumbnail/auxiliary*

**Comment by GefullteTaubenbrust2** [comment]
So for the Aux, most of the model is still kept from QuargBlock, but the current files are edited versions made by me. You can see the changes made between the two in [#6601](https://github.com/endless-sky/endless-sky/pull/6601). So they're my files, but his copyright still holds, so he should be credited.
