### ISSUE TITLE
Re-add emergency ramscoop and/or an alternative

### ISSUE THREAD

**Issue by ira210** [endless-sky/endless-sky#7736]
### Problem Description

Although the issue of softlock has been resovled after the removal of emergency ramscoop it seems that there is still controversy in the community over the pr and very little consensus. Personnally I don't feel as strongly about it as some but I still think the universal ramscoop does not detreact from anyones experience and can be a helpful safetey net. I also disagree about allowing any ship to cross the galaxy being a lore issue as an emergency ramscoop makes sense as a safetey feature.

### Related Issue Links

https://github.com/endless-sky/endless-sky/pull/7730 the pr this issue takes issue with (no pun intended)
https://github.com/endless-sky/endless-sky/pull/7461 and https://github.com/endless-sky/endless-sky/pull/7460 are alternative aproches which were rejected but may be worht a second look.

### Desired Solution

I think that #7730 should be at least temporarily reverted until there is more consensus that it should be added, an alternative option such as the ones described in the pr is ready to be implemented or it is agreed that emergency ramscoop should be kept.

### Alternative Approaches

The pr could be left merged and this issue used as a public disscussion forum about #7730

**Comment by Amazinite** [comment]
As I mentioned on #7460, I think #5556 is the real solution, because we have people who are really in favor of the universal ramscoop, and people who are really against it. Unless you could choose what you want, we can't please both crowds.

I'll look at reviving #5978 with just the universal ramscoop as our first gamerule.

**Comment by Zireael07** [comment]
#5556 really sounds like the solution since I see the ramscoop is really polarizing...

**Comment by ThrawnCA** [comment]
The name of this issue is confusing, because the Remnant sell an outfit called the Emergency Ramscoop.

**Comment by Zitchas** [comment]
I am firmly of the opinion that our playerbase are mature, intelligent people who are easily capable of meeting the challenge create by the lack of universal ramscooping. I would like to note that this does include using either plug-ins or data file edits to re-add the ramscoop values to the drive outfits `"ramscoop" 0.01`should suffice.

**Comment by Zitchas** [comment]
And a new idea: What if blown up ships had the chance to drop small fuel pods in the same way they drop cargo and outfits? Small debris, each one gives 10-20 fuel, enough debris to equate to some random amount between 0 and 25% of the fuel the ship had, so hunting pirates or the like might actually help refuel a person.

**Comment by vitalchip** [comment]
Surely anyone running out of fuel with a guaranteed save taking them back to the last spaceport will simply learn the lesson and not do it again? 

If not then probably best to put the computer down and have a play with etch-a-sketch insted.

**Comment by Zitchas** [comment]
Oh, and Amazinite is planning on implementing gamerules which would have the option to turn the universal ramscoop back on and set it to whatever one likes, too. So lots of options.

**Comment by Quantumshark** [comment]
> And a new idea: What if blown up ships had the chance to drop small fuel pods in the same way they drop cargo and outfits? Small debris, each one gives 10-20 fuel, enough debris to equate to some random amount between 0 and 25% of the fuel the ship had, so hunting pirates or the like might actually help refuel a person.

Boarding a hostile disabled ship (provided they are carrying fuel) already takes their fuel. In systems where pirates are consistently being destroyed rather than disabled, the friendly ships destroying them can probably be asked for fuel.
Currently, the main difficulty in getting fuel from pirates in uninhabited systems is the large size of systems, because spawns will often not be close enough to the player that they attack rather than immediately leaving.

**Comment by Zitchas** [comment]
Well, it's mostly a "new player friendly" sort of thing. Boarding can be hard, especially if they don't even know about boarding yet.

**Comment by mOctave** [comment]
I'm in favour of the emergency ramscoop, but I can see how some players wouldn't be, and would welcome https://github.com/endless-sky/endless-sky/issues/5556.
Lore-wise, I feel that it makes sense that any ship could cross the galaxy, but it should take hours upon hours of IRL time to do so, as it did before the emergency ramscoop was removed. Sometimes, it takes forever for a friendly ship to show up, thanks to the RNG, and then you have to sit waiting. With the emergency ramscoop, at least you _know_ that your wait won't last forever.

Alternatively, I like Zitchas' ideas, especially 1, 2, and 4.

**Comment by vitalchip** [comment]
Fuel is a fairly meaningless item, very widely available, free and there is always enough to top up every ship to full without any even requiring action from the player at all. A vey visible fuel bar and highly predictable consumption.

Sadly there will still be people who run out and need a magic fuel maker to help them.

There's a paradox where trying to shield people from consequences just makes them less likely to pay attention and they continue to get into trouble.

**Comment by Zitchas** [comment]
Yeah, fuel is kind of a weird dichotomy. On the one hand, it is very visible, very prominent, and used in very predictable ways. It is even used as a significant limiter on what is otherwise a 100% totally superior hyperdrive and Jump Drive.

And on the other hand the player's ships refuel automatically when they land at any planet, every non-hostile ship that has fuel will gladly give the player a jump's worth, it's utterly free (even the people providing it to the player in space, which is directly against their own best interests if the NPC have anything time sensitive to do), there's zero costs, and with the universal ramscoop, zero risk, ever. (Except, amusingly, at Sag A*.)

And it's even weirder because everywhere else in the game that we give risks or stuff to pay attention to, we don't give the player a universal safety net. The same logic that states that universal ramscoop should be a thing could actually be argued that it should be universal fuel generation instead (truly universal, then, and constant, so it would actually help new players that get lost out in deep space instead of punishing them by making it work even slower than next to the sun), and that we should also have universal power, and perhaps the first time pirates stumble across the player in a starbarge, there's no restriction ensuring there's always a cruiser nearby.

The main difference is that, unlike pirates (but very much like heat and energy), the player can *watch it happen.* If they run out of fuel hyperjumping, they can't blame it on RNG or some nasty NPC - they did it to themselves, quite clearly, and obviously.

**Comment by johndh** [comment]
I know this is a radical notion, but is fuel a worthwhile game mechanic? It doesn't do much to actually limit the player and there are so many parts of it that don't make sense. As far as I can tell all it really does is slow you down slightly, and is that something that we actually want? We already don't require fuel for in-system movement, we don't need to replenish food, water, and atmosphere, etc.

**Comment by vitalchip** [comment]
Like so many things it depends on how you perceive the game. There's a lot of people who are quite content to take all the 'freebies' on offer because all they want to do is roam around shooting and capturing, they're playing an arcade game.

Then you have others who think more along the lines of long term, strategy and something which requires actual thought and care.  Things which are in the game should matter.

There is nothing wrong with either position but those two groups are effectively in opposition and as such the game will always be a camel.

Fuel only matters for flaamethrowers, afterburners and cloaking. Ironically for something called hyperspace fuel the area in which it matters least is hyperspacing. Go figure.

**Comment by mOctave** [comment]
> And on the other hand the player's ships refuel automatically when they land at any planet

This isn't true. The player's ships won't automatically refuel on uninhabited planets or some stations, which could come as a shock to new players _expecting_ automatic refuel on landing, who planned their jumps to only get them to that system thinking they could refuel.

> it's utterly free (even the people providing it to the player in space, which is directly against their own best interests if the NPC have anything time sensitive to do

Maybe this should be changed. Maybe each time you ask for fuel you can either pay a small tip in gratitude (maybe 1000-5000 credits), or have your reputation go down with whichever group you just got fuel from.

> A bulk freighter is just as good at doing long-distance urgent courier missions as a Bounder.

This is a little off-topic, but... a while ago I had an idea that I never got around to finishing of offering different extra jobs based off of the player's flagship, as people looking to hire a captain could recognize, at least in their own space the lore-based strengths of each ship. I was planning to do it as a plugin, but maybe it would work as part of vanilla, as a way to make ships be more unique.

**Comment by Zitchas** [comment]
> This is a little off-topic, but... a while ago I had an idea that I never got around to finishing of offering different extra jobs based off of the player's flagship, as people looking to hire a captain could recognize, at least in their own space the lore-based strengths of each ship. I was planning to do it as a plugin, but maybe it would work as part of vanilla, as a way to make ships be more unique.

It might be a little off-topic, but it also sounds like a great idea.

I know there has been people in the past working on making a mission for every planet. Something specific to that world that showcases something special about it.

Now that we have auto-conditions, having something similar for each ship would likewise be awesome. I'd love to have something that gets into a little of the lore of a ship, or just showcases its particular identity a bit.

**Comment by johndh** [comment]
As far as the existence of scout craft, I think they'd be more useful if 1) fuel costs money and 2) fuel consumption is based on mass. If your interceptor uses less fuel than your behemoth, then small ships retain usefulness for courier missions and exploration (the Firefly play style) for a little longer, and it would also slightly curtail the exponential growth that the player experiences, making the early and middle parts of the game last a little longer by making it less of a First Order Optimal Strategy to just get bigger and stronger as quickly as you can afford it. Currently, flying around with 50 captured leviathan escorts doesn't dig into your profits except a relatively cheap crew cost, so there's little advantage to do otherwise. Obviously, fuel capacities would need to be adjusted accordingly.

**Comment by vitalchip** [comment]
Offering jobs based on the players flagship won't prevent switching to another ship to actually do the job. Giving a rush passenger job because they have an Arrow will actually mean nothing because its still the case that *almost* any ship will be able to actually do it,so might as well use a freighter and take some cargo too.

Rush cargo jobs based on a fast flagship could be even worse as it'll get loaded into escorts anyway!

I get that it creates a need to *have* a certain ship or type of ship to get the jobs but you won't need the ship to do the job.

The only way to make jobs ship or ship performance specific is to make those distinctions actually matter, which in terms of game time they don't.

It'll be an analog of Luxury Accomodation, you only need to have it to get the job.

To be fair there's no harm in extra jobs, always welcome but I think it'll just end up like getting an escort job based on your combat rating and then doing the job in a Shuttle because you never actually need to escort the ships at all.

**Comment by mOctave** [comment]
> Offering jobs based on the players flagship won't prevent switching to another ship to actually do the job. Giving a rush passenger job because they have an Arrow will actually mean nothing because its still the case that almost any ship will be able to actually do it,so might as well use a freighter and take some cargo too.

I can see where you're coming from with this, but the point would be that at least there's a reason behind having variety in your ships. People offering you a job would _see_ your flagship come in, and offer the job based on that. You could still switch ships, but you'd need to keep your flagship around if you wanted to take that kind of job again in the future.

> Rush cargo jobs based on a fast flagship could be even worse as it'll get loaded into escorts anyway!

This is definitely a problem, yes. Some code changes would be certainly be appreciated in how loading cargo works.

**Comment by Zitchas** [comment]
Actually, it *might* be possible to do something to the effect of:

```
to fail
     not "flagship: Arrow"
```
(don't copy that, that's just pseudo code. But a proper implementation of it might be possible)

**Comment by Zitchas** [comment]
Still, no guarantees that the passenger doesn't get loaded in an escort anyway, but at least one might be able to ensure that you keep your flagship as the ship in question for the duration of the mission (if that "to fail" condition test works)

**Comment by ThrawnCA** [comment]
You would need to make it quite clear up front that that's a condition of the job.

**Comment by Zitchas** [comment]
Definitely. That being said. "Hey, you have an Flivvr, I've always wanted to fly in one. Could you give me a ride to Luna in your Flivvr?" is pretty explicit that the person hiring the ride clearly wants to ride in a flivvr. It only takes failing one of these once to learn that when they say they want to travel *in the flivvr* that switching to flying a heavy shuttle just isn't going to be acceptable. Especially if it fails visibly, with dialog, the instant you switch ships.

**Comment by mOctave** [comment]
Alternatively, I could just hide all of the requirements entirely, so that people don't realize how to get the job, and so don't switch ships to get at it.

**Comment by Zitchas** [comment]
As an alternative to having global no-ramscoop, we could have a system attribute that disables the universal ramscoop specifically for that system. This could be used to allow certain parts of the galaxy to be higher risk; while allowing players to have the security of the universal ramscoop within most systems.

**Comment by ThrawnCA** [comment]
> Mapping paths manually for jumps is going to get really old, really quickly.

If you're in a position where you have to do a lot of manual work like this, then you should probably buy ramscoops? Removing the universal ramscoop doesn't stop that.

**Comment by ThrawnCA** [comment]
> Ramscoops to accommodate the AI path mapping system is just a waste of precious outfit space.

Outfit space is certainly precious, but if you want to fly a longer path than your fuel tanks will allow, and ramscoops will let you do it, then it seems to me that they're not a waste.

**Comment by Zitchas** [comment]
> Ramscoops for when you're going into dead zones makes sense. Ramscoops to accommodate the AI path mapping system is just a waste of precious outfit space.

Forcing the lore that all ships have built-in ramscoops just to compensate for poor fleet navigation AI seems like a poor choice, to me, too. I suppose I'm fine with using it as a crutch until we figure out a way to make the AI not make dumb choices, but we really should be working on fixing that, not just arguing over the crutch.

**Comment by johndh** [comment]
In any of those scenarios, with the universal scoop you're still waiting long enough that you're probably just going to load anyway, right? If you have a big enough fleet that managing their fuel is difficult, then you probably should have at least one escort that can act as a fuel tender, if not your flagship.

> You're in a hostile system trying to capture a ship, far away from a spaceport or friendlies. You finally manage to capture one, but other hostiles are going to catch up to you very soon, so you need to escape ASAP, or your captured ship with its meagre hull+shields will almost certainly get destroyed.

It seems to me that you shouldn't be able to abandon a nearly-destroyed ship in history territory and expect it to survive on its own. I think this is just a concession to the impracticality of simulating all of the events in every system at once.

> This has made capturing ships in hostile territory harder and more tedious by orders of magnitude.

I'm sympathetic to the frustrations associated with capturing. #7774

**Comment by binaryspica** [comment]
I wonder that, does it solves the escorts without the other system and low on fuel? It is actually a huge problem for those. I have seen some escorts are not able to have enough fuel on the northside of the republic, and I have to press caps lock and wait for hours and get the ships. So it seems that those ships are now stranded forever and I have to edit the save file to warp them manually. I don't understand why removing basic ramscoop is required, or even needed.

**Comment by Zitchas** [comment]
The emergency ramscoop stuff *did* get re-implemented, and there's now a gamerule you can tweak to adjust it. #7730 does have a fairly extensive set of justifications listed in it.

**Comment by RisingLeaf** [comment]
closing as it got implemented
