### ISSUE TITLE
SUGGESTION: Make graviton engines unique somehow to justify price.

### ISSUE THREAD

**Issue by jmhorjus** [endless-sky/endless-sky#780]
Currently the one graviton thruster in the game is about equal in speed to an atomic engine of similar size, but uses like 2.5x more energy, making it not really a very useful engine.  

I actually like that it's not the "best engine in the game" and don't want to accidentally make it that.  You should have to go to different places to get the best outfits in different categories, like you do now.

But it would be cool if there were something unique about it, SOMETHING to justify the fact that it's supposed to be this incredibly advanced technology and is worth freaking 20 million credits compared to an A520's 1 million and takes 1200 energy to the A520's 498.  

Well, if it's based on manipulating gravity, then it shouldn't need to expel a propellant out the back of your ship, so I think it should a unique property to reflect that. 

Two Ideas (B is my preference): 
A.) It can be mounted anywhere - it takes outfit space but doesn't need to be in the "engine section" of the ship (a gravity field would effect your whole ship, including the engine itself, so it wouldn't even need to be particularly well tied down in order to deliver it's thrust).  This would make it something "extra" you could add to a ship that already has other engines to achieve unheard-of speeds (at the cost of all your energy ever).  
B.) It can generate a gravity field to move you in any direction, not just "forward", so it has "reverse thrust" equal to it's thrust.  This would make it the preferred outfit for large flagships that want to have access to reverse thrust maneuvers (the only current reverse thruster isn't well suited to large ships).  But again, there's that energy drain to consider.  

Idea A could be applied to graviton steering as well, but for Idea B, it might make sense to do something even **cooler** with the steering: _combine it into the engine_.  Would they really make two completely different kinds of "gravity generator", one that can **only** go forward and one that can **only** turn?  Combine the two outfits into one: Graviton Engine, which has half the stats of each: weighs 60 tons, uses 600 energy when thrusting plus 300 when turning, and has stats for thrust, turn, and reverse thrust all in one.  
Actually make it weigh 61 tons, just so you can't fit 3 of them perfectly into a Bactrian's 180 engine space - that would be too good. :)

**Comment by jmhorjus** [comment]
PS: If @endless-sky approves of this, I can implement, test, and make a pull request.

**Comment by brick96** [comment]
This sounds amazing. Definitely something different than the other four engines

**Comment by lehgogh** [comment]
Remember: Even if it doesn't get put into the game, it can be made into a plugin (unless it involves changes to the source code).

**Comment by jmhorjus** [comment]
Hmm...if I change them to be 61 tons, then I'd have to change the Quarg ships to have more engine space, and all their stats are such nice round numbers as-is.  It also makes their weight/price ratio just slightly different from Sky-lances. 

However, if I keep them at 60, then a Bactrian can fit 3 of them perfectly...no other engine makes such efficient use of that 180 space and (aside from the much, MUCH higher energy requirement: from 900 something at most to 2700) they become the best way to make a fast/maneuverable Bactrian (which is hands-down the best flagship hull) and thus become a serious contender for "best engine".  

Then again, the best atomic engines come from the Deep, and you already had to go there to get your Bactrian hull in the first place - graviton engines being the best engine specifically for a Bactrian doesn't make "Challenge: Build the best flagship" any simpler.  I'd honestly like some other race to have the real "best engines" for pure speed.  I though it would be the wanderers, but they just don't make anything big enough, so maybe some new race further down the line. 

Right now I'm planning to keep the stats of the new "Graviton Engine" at *exactly* [1/2 a grav thruster + 1/2 a grav engine] in all respects, while adding reverse thrust.  I think the energy requirement is enough of a balance against their advantages, and them being a legitimately good/maybe the best engine for any ship that can power them makes sense. 

Also, I'll be sure to leave the old engines in the files for backward compatibility of save files. 

Pull request will be incoming late tonight sometime.

**Comment by mrec** [comment]
I like the combined thruster+steering idea.

B's reversible thrust by itself sounds very meh; at the point you'll get these you'll also get Skylances, at which point fixed guns become redundant and the main appeal of reverse thrust - being able to fine-tune engagement distance while staying pointed at the target - is much less important.

A I'm not sure about. It's a significant advantage, yes, but maybe too much so, in that it's yet *more* pressure for everyone to end up in the almighty Bactrian. I'm really enjoying my speed-maxed Kestrel and only unpark my Bactrian under protest these days. Variety is good.

**Comment by DingusShingleton** [comment]
I say... why not both? Combine both engines into one outfit that doesn't take up engine capacity. Obviously with such a versatile outfit balance would be extremely important... To wit:

A tremendous energy requirement is just the thing for it, as energy generation simply tops out at a certain point due to heat generation. This would naturally limit the number of Graviton engines that could fit into any ship, including the infamous bactrian. Perhaps the graviton engine could also reduce total energy storage capacity too? I don't know if it's possible for an outfit to modify a stat by a percentage (say, -25% energy storage so that it scales?) but that could also serve to limit its overpoweredness.

If there's one thing I have learned about gravitational waves in the last 36 hours, it's that they are extremely weak and therefore hard to detect (just ask the folks at MIT). This got me thinking that a gravity based engine would be extremely useful for anyone who is inclined toward the stealth arts. Perhaps the graviton engine could somehow boost the effectiveness of the cloaking device? It makes sense, since as @jmhorjus says there is no observable propellant being ejected, no heat signature, almost no observable effect of any kind in fact. I'm not sure how that would be implemented, but the idea is there. And I too am all for variety and interesting, fun synergies. Just a thought.

**Comment by masterpierround** [comment]
I think the way to implement your stealth idea would be to have cloaking devices become available (but very expensive), then have someone develop a scanner outfit that allows your missiles to "see" a heat signature, countering the cloaking device. Then, the gravitron engine, when combined with a cloaking device, would allow you to evade both conventional ships and ships equipped with the new scanner.

**Comment by DingusShingleton** [comment]
Well, there already is a cloaking device in game, it just only becomes available during the FW missions (and even then only if you make a certain choice during them. I've only done the FW missions once and I didn't choose that route so I don't fully know how the cloaking device functions. But there must be some way to create a synergy between the two outfits.

**Comment by jmhorjus** [comment]
Put in https://github.com/endless-sky/endless-sky/pull/782

I kept it simple.

I considered removing the purple engine glow, since I don't see why a gravitational engine would produce such an effect - I would expect the ship to "just move".  However, the purple glow looks cool and I didn't want to change more than necessary.

I also considered adding some snark/lamp-shading of the purple engine glow into the description - something like "This engine also produces a purplish glow at the rear of your ship, which seems unrelated to the thrust being produced. Maybe it's just for show?" Decided against that since the description was a good length already.

**Comment by jafdy** [comment]
The cloaking idea wont work as the device cloaks all signatures but gravitational anyway.

**Comment by DingusShingleton** [comment]
Perfect! It no longer has to cloak a heat signature, so that can translate into a savings. I ended up just adding a cloaking device to my save file just to see how it works. It uses 12 fuel/second, I think if the graviton engines cut that by 2 or 3 fuel/second it would be a nice little synergy that doesn't really affect much but would be a fun goal for players who love stealth.

**Comment by endless-sky** [comment]
The graviton thrusters are really just placeholders - since there are no "intermediate level" aliens yet, it's hard to be sure what sort of equipment the top tier aliens should have. So, tweaks to the graviton thrusters may be a bit premature.

(Also, note that if you remove any outfit from the game, you will break the save files for any players who happen to have ships with those outfits.)

**Comment by jmhorjus** [comment]
Yep, I noticed some other "legacy" outfits in the files, so I followed the same pattern to make sure my pull wouldn't break any saves.

**Comment by Bladewood** [comment]
http://captainforever.wikia.com/wiki/Captain_Successor
My view on this issue: Translocators and transrotators.

**Comment by jmhorjus** [comment]
@Bladewood All rotation in ES is currently "transrotation" in that ships turn without ever gaining angular momentum. Creating an engine that moved a ship but didn't give momentum (or a steering module that did) would be an interesting experiment, but would certainly take source code changes. 
The current outfits (Medium Graviton Thrusters/Steering) are basically placeholders, as @endless-sky said - I just wanted to replace it with something that was more interesting and had a bit of tech flavor and mechanical uniqueness.

**Comment by GalacticRuler** [comment]
Why not roll some (equal)reverse thrust, and a jump-drive into it? It could as a side effect pull lots more energy and be massive...it could probably increase required crew too, you'd need a lot of engineers to keep it running.

Another thought is making it have a built in reactor that outputs it's full energy draw and 400% the heat of the hottest reactor.

**Comment by Bladewood** [comment]
Is the reactor active while the thrusters are inactive?

**Comment by GalacticRuler** [comment]
Probably, just to run the jump drive and charge batteries on the ship maybe? Unless toggleable reactors become possible. Instead of that maybe make it pull no energy but output a load of heat while in use?

**Comment by lehgogh** [comment]
It's just a thruster system, so it wouldn't make sense to let it be a hyperdrive.

**Comment by GalacticRuler** [comment]
The idea I had for it was a large AIO engine setup, too big for human ships but small enough for alien capital ships. Included would be forward and reverse thrust, steering, a jumpdrive and a reactor supplying power to the engines only...drawbacks would be it's size and heat output.

**Comment by MarcelineVQ** [comment]
Does this topic need revisiting? Korath steering and thrusters outclass Medium Graviton equivalents quite handily now, especially since cooling cost much less space than energy generation. Even Hai-space "Bondir" Atomic Steering is much better than Medium Graviton Steering when accounting for energy use.

**Comment by Wrzlprnft** [comment]
Quote MZ 

> The graviton thrusters are really just placeholders

i don't think we have those intermediate level aliens enough developed yet, at least i would wait for the wanderers to gear up.
