### ISSUE TITLE
Katya Missions have insanely low spawn chance. 

### ISSUE THREAD

**Issue by SimulatedKnave** [endless-sky/endless-sky#7850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Katya's first mission has an insanely low spawn chance. 10% base. Given how much of the game content is locked behind them (and how much of that content is written on the basis that you are doing this quickly after secession), this is insane. 

### Steps to Reproduce

1. Start new campaign. 
2. Fly to the FW and intentionally try to start working for them. 
3. Wait two years, get curious, go look at the files. 
4. WTF? 

### Expected Behavior

That if the game's main story is written so it makes the most sense shortly after the secession of the FW, it will actually be likely to trigger shortly after that. Otherwise you can be three or four years into the game and have not made it through what is apparently the prologue. 

### Operating System

Windows 10. 

### Game Source

Steam

### Game Version

0.9.16

### Additional Information

I have already created a pull request about this where I increased the spawn chance for the event to 70% base. While this does start the campaign awfully quickly, I think that's more a consequence of how quickly the Free Worlds comes into existence in the game.

**Comment by IsocratesGrey** [comment]
Currently it is `random < 10 + 7 * "assisted free worlds" * "assisted free worlds"` which if I understand correctly isn't <10 but <10 plus 7 times the number of assisted free worlds you've done squared. So if you complete 4 afw's you should be at  `random < 112`.

If you haven't gotten Katya after completing 4 afw's and landing on Zug then you may have found a bug.

Alternatively, perhaps we need to make Zug a destination for some of the AFWs so that people will go to Zug occasionally.

**Comment by Amazinite** [comment]
The mission will be guaranteed to offer on Zug as of v0.9.17.
