### ISSUE TITLE
Disabled fighters/drones can end up in carriers, which breaks missions that require npc ships to not be disabled

### ISSUE THREAD

**Issue by UnorderedSigh** [endless-sky/endless-sky#7862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

There is another issue, which I *think* may be the same, but I can't be 100% certain. #7662

### Describe the bug

There are many places in the code where fighters/drones are put in carriers without first checking if they're disabled. The reason why that is a problem right now is that the DISABLED flag is only cleared when the drone/fighter is boarded. Hence, any missions that require an NPC ship to not be disabled can't be completed once a disabled drone/fighter is being carried.

As far as I can tell, a carrier *does* board a disabled fighter before docking it (Ship::Board seems to ensure that) so this problem just occurs in the numerous corner cases throughout the code where drones/fighters are put in a carrier forcefully, such as when departing.

**There are three competing solutions to this problem. See the Additional Information section.**

### Steps to Reproduce

Right now, the Stormhold battle in Hai Reveal is the only way I can easily reproduce this. (See #7662)  It happens about half the time.

### Expected Behavior

People have suggested three options:

1. Disabled fighters/drones never end up in carriers.
2. Disabled fighters/drones that are in carriers lose the DISABLED event once they're not disabled.
3. Ban nearly all carrying of disabled fighters/drones. Iteratively remove any remaining cases, fixing bugs that appear along the way.

### Link to save file

[Friction Diction~3026-01-21  should work but does not.txt](https://github.com/endless-sky/endless-sky/files/10212211/Friction.Diction.3026-01-21.should.work.but.does.not.txt)

### Operating System

`Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

### Game Source

Built from source

### Game Version

0e7747e7f

### Additional Information

This is the simple fix that only gets the Stormhold mission to work:

-  #7845 

However, there are many situations that won't be fixed. You need one of these:

**Option 1**: Carriers refuse to carry a disabled fighter. #7866 That means, if you land and depart, the disabled fighter will be in space waiting for repair. This may have many unexpected consequences, but it is the right solution, if you don't mind mountains of testing.

**Option 2**: Carriers repair docked disabled ships as if they had been boarded, including clearing the DISABLED flag (#7848  #7852). This is risk-free, but it'll also give you free repair of ships that should be in space waiting to be repaired.

**Option 3**: Both fixes, sort of. Carriers will nearly always refuse to carry a disabled fighter; Ship::Carry() will have a flag telling it whether carrying a disabled fighter is okay, and fix in option 2 will repair them. Then, we remove these exceptions, one by one, until disabled fighters/drones are never carried.

**Comment by vitalchip** [comment]
Ship::Carry() is the common link, everything goes through there. If you disallow disabled ships there it will solve the problem.

ie.
if(!ship || !ship->CanBeCarried()) || ship->IsDisabled())

The root of this particular problem is in Engine::Place(const list<NPC> &npcs, shared_ptr<Ship> flagship) which (for some reason) checks carriers for destroyed/disabled but only checks the carried ship for destroyed.  Since it calls Carry() in any case then it makes better sense to fix it there as it'll prevent any future added call potentially doing the same.

Once added any disabled carried ships will be placed in space, not in the carrier and then the fleet/player will board to assist (and negate the disable event) as per usual.

**Comment by UnorderedSigh** [comment]
The problem I see with that fix right now is that there's no logic (that I can find) for a carrier to stay behind and fix its fighters/drones before leaving. The code knows how to have non-carriables stay behind to fix non-carriables, but it doesn't handle the special case of a carrier fixing its fighter/drone. That means the consequence of changing Ship::Carry() is that you'll have to go back and repair your fighters/drones, even though you don't have to go back and repair anything else.

**Comment by UnorderedSigh** [comment]
I'm only 80% certain of that, since I haven't searched the entire codebase for that special case.

**Comment by vitalchip** [comment]
Well, if the carrier leaves the fighter (disabled or not) and jumps to another system then the mission won't complete anyway because a ship isn't there Nothing apart from going back and getting it is going to right that situation.

If I were looking at a larger change for this sort of mission I'd be wondering if we should count the likes of drones at all in the requirements, or maybe make it optional. Given how fragile and troublesome they can be would it be fairer to complete accompany if all of the non-carried ships were present and active?

**Comment by UnorderedSigh** [comment]
@vitalchip - Yes, your fix works. Do you want to open a PR for it, or should I? If I do it, I'll give you credit.

I think this is what should happen:

1. Merge #7845 since that fix is indisputably correct (if a fighter is already docked, it has accompanied you).
2. Open a PR with your fix.
3. Have the devs come to this issue and decide which fix to use.

The trade-off I see is:
 - Fixing the bug in Ship::Carry() is the correct way, but it will trigger other bugs that'll have to be fixed after it is merged.
 - Using the workarounds I implemented is safer, but doesn't solve the real problem. However, it will allow the other bugs to be solved iteratively, by checking each place where Carry() is called, and deciding whether it is okay to carry a disabled ship there.

This may impact the timeline for a release, so the devs will need to debate it. If we had infinite resources, I would prefer your fix (Ship::Carry()) followed by lots of testing of corner cases. Those corner cases may be hard to trigger though.

**Comment by vitalchip** [comment]
I'll leave it to you. I don't do Prs so whatever you are most comfortable with. There's no need for credit. I pop by here to chuck some ideas about, see what's going on from time to time and that's plenty for me.

**Comment by UnorderedSigh** [comment]
Pinging @RisingLeaf @Hurleveur @Zitchas @Hecter94 who have expressed interest in this problem in the two competing solutions.

**Comment by Zitchas** [comment]
Is there any potential for the two to be used together? Having disabled fighters never getting placed inside as a general principle, but if they manage to get put there somehow, they are instantly repaired as per the other PR?

**Comment by UnorderedSigh** [comment]
> Is there any potential for the two to be used together? Having disabled fighters never getting placed inside as a general principle, but if they manage to get put there somehow, they are instantly repaired as per the other PR?

Yes, but it's impossible for them to end up inside if Ship::Carry() doesn't allow them to be carried.

The question is whether you want to risk having Ship::Carry() block all attempts to put a disabled ship in a bay.

**Comment by Hurleveur** [comment]
I dont see an issue with blocking those attempts honestly

**Comment by vitalchip** [comment]
Carry has 4 callers,

Board() can't do it because a disabled ship can't move at all, so it can't board the carrier.
PlayerInfo(TakeOff) can't do it because if(!ship->IsParked() && !ship->IsDisabled()) is a condition of toLoad.

Engine::Place() can and does do it because npc.Ships is iterated twice, first to find carriers (destroyed and disabled ships excluded) and second to find carried (destroyed excluded)..  

Fleet::PlaceFighter() I think might be able to do it ( I haven't followed every path all the way back) but these are all newly instantiated ships so it would have to come from a ship definition which was broken, you'd have to create one which perhaps had no hull and so was immediately invalid. For ships which are created and pruned at random what possible purpose could there be to such a thing? Even if instantiated and loaded it would be locked inside the carrier until it was pruned.

I can only imagine that not checking the carried ships being disabled in Engine::Place() was an oversight, the conditions under which it can happen are relatively obscure and those further conditions where it becaomes a problem for a mission even less so.

We could add the check in there but I reckon adding it to Carry() gives the added assurance that if someone adds a future call and forgets to fully check the ships we won't have a repeat.

**Comment by UnorderedSigh** [comment]
I see another option. Do this:

1. Ship::Carry receives a flag that tells whether it's okay to dock a disabled ship.
2. Most places send false to that, except the few that require a disabled ship to be docked.
3. Any docked, disabled, ships are automatically repaired.

This means, as @Zitchas suggested, we use both fixes.

I think the only place we need to allow disabled docked ships, for now, is when they're not in the player's system. It should be safe to have them disabled in space with the player, since the player can see them and repair them. Other situations can be ruled out with more testing.

How does that sound?

**Comment by quyykk** [comment]
Allowing disable ships to dock seems a bit iffy; I don't think we should allow that. So to me #7866 seems like the way to go.

**Comment by UnorderedSigh** [comment]
> Allowing disable ships to dock seems a bit iffy; I don't think we should allow that.

Certainly, I agree. However, this will trigger a lot of corner cases where fighters will unexpectedly be left behind. Keep in mind the choice you are making:

1. Ban all carrying of disabled ships - will break lots of things immediately, which will have to be discovered and fixed.
2. Ban most carrying of disabled ships - will allow iterating towards a 100% solution

It's like deciding whether to go off of medication immediately or fazing out slowly.

**Comment by UnorderedSigh** [comment]
My instinct is to merge #7866 (never carry disabled fighters), and wait a while to see if people find any bugs. If there are lots of bugs, we can put in the workarounds until we have fixes.

**Comment by quyykk** [comment]
> will break lots of things immediately

Is this a hypothetical? I doubt this will actual break anything.

> My instinct is to merge https://github.com/endless-sky/endless-sky/pull/7866 (never carry disabled fighters), and wait a while to see if people find any bugs. If there are lots of bugs, we can put in the workarounds until we have fixes.

That sounds reasonable.

**Comment by quyykk** [comment]
> whoever they are

definitely not me

**Comment by UnorderedSigh** [comment]
@quyykk I have been informed that you are trolling me, so I give you this:

:trollface:

**Comment by UnorderedSigh** [comment]
Closing due to merge of #7866
