### ISSUE TITLE
Boxwing optimisation

### ISSUE THREAD

**Issue by ThrawnCA** [endless-sky/endless-sky#7973]
### Problem Description

Since Boxwings are meant to be the epitome of "cargo space with an engine", it seems odd that they use a fuel cell. A solar panel + supercapacitor is smaller, allowing the player to install a cargo expansion, and also costs less than half as much as a fuel cell, which seems like it suits the Boxwing's design philosophy.

### Related Issue Links

#5590 mentions this Boxwing configuration, and links to a plugin that offers this as an option when purchasing a Boxwing.

### Desired Solution

The Boxwing should use the cheapest and most compact power generation by default.

### Alternative Approaches

The Boxwing's outfit space could be reduced to 40, making this optimisation less useful.

**Comment by Hecter94** [comment]
A lot of ships have a stock loadout that doesn't make a ton of sense for what the player would actually do, or even for what the characters in-universe would do. 
From what I've surmised, that's intentional to entice the player into editing their loadouts themselves to get that little bit of extra performance out of their ships. 

I'm not sure I agree with that philosophy, but that seems to be the intent behind it

**Comment by Amazinite** [comment]
Out of the box (no pun intended), ships typically shouldn't come with the best possibly fitting, just a reasonably viable fitting (so I wouldn't say that existing stock loadouts "don't make a ton of sense," although you're correct that part of the intention is to get the player to mess with their outfits), and I would say that nothing but the smallest engine and smallest self-contained power generation in human space is a reasonably viable fitting for the Boxwing.

Note that, at least in this case, there is the in-universe angle of shipyards cheapening the outfit cost of the ships they sell in order to minimize the expenses for a ship. Shipyards presumably buy outfits from the outfitters to install on their ships before they sell them. It isn't much, 424k vs 435k, but the suggested loadout of X1050 Ion + Supercapacitor + KP-9 Panel + Cargo Expansion is more expensive than just the currently stock X1050 Ion + nGVF-AA Fuel Cell.

**Comment by ThrawnCA** [comment]
> It isn't much, 424k vs 435k, but the suggested loadout of X1050 Ion + Supercapacitor + KP-9 Panel + Cargo Expansion is more expensive than just the currently stock X1050 Ion + nGVF-AA Fuel Cell.

With the Outfit Expansion it's more expensive, yes. But if they didn't add that, and just swapped the fuel cell for a panel+supercapacitor and left the space empty for the player to buy a cargo expansion later, then that would be 19k cheaper.

For even more savings, the Boxwing could be built with slightly less outfit capacity to begin with, relying on the panel+supercapacitor combo to reduce it to 25 total outfit space.

**Comment by Zitchas** [comment]
There's multiple things here on an in-universe side: (these are all real-life things that can be seen in car purchases, and to a lesser extent in aircraft and ship manufacturing as well.)
1. The product: As Amazinite mentioned, ships generally should come with a reasonable viable fitting, but importantly, this should generally be a general purpose one. Worth noting that this purpose should align with predominant in-universe use, not exclusively the player's use. For example, there's quite likely a lot of boxwings being used by private companies for intra-system use. Luna to Mars, for instance. Such companies might prefer having steady power for its reliability over being able to cram a few more tons of cargo in. 
2. Shipyards *aren't* outfitting out of the local outfitter. They are generally bulk manufacturers who can negotiate purchases directly with manufacturers to get deals that the player simply cannot access. In this case, perhaps they got a deal on nGVF-AA fuel cells. Perhaps it might even be a loss leader or a package deal where the manufacturer is providing the fuel cells at vastly below market price because the shipyard is also buying all the rest of the onboard electronics systems for *all* their ships from them. Maybe the shipyards are getting "factory refurbished" equipment, that's always a possibility, and of course they'll pass it on as if it was new.
3. There's also inter-corporate politics/competition to consider. Perhaps solar panels are made by a company that competes in a range of other areas, and the shipyard considers it a net benefit to pay higher costs for the fuel cell in exchange for not supporting a competitor.
4. Lastly, and most importantly, shipyards generally want to make a profit. That means they tend to equip ships with stuff that gives them a higher profit margin, and especially stuff that makes them look good. For something like a freight hauling boxwing, basic reliability is probably one of the few things that they have going for them. Solar panels might be good, but no-one likes drifting along waiting to get enough power to make the course corrections needed to land. Makes for bad PR. Better to ensure people just have the power to get where they are going. (in this case, going back to point 1: The shipyard makes ships for a universal audience, not just the player. Boxwings are actually expected to fly and deliver/pick up cargo. They're not just bay-to-cargo-conversions, despite that being *exactly* (and pretty much *only*) what the player uses them for.)

Stepping out of the in-character lore, there's the meta/gameplay side of things; This is a game that largely revolves around outfitting and personal choice.
A. The more involved the player is in outfitting their ship, the more they are likely to feel it is "their" ship. If they just buy a stock ship off the shelf, they generally have little attachment and are quite willing to sell it and buy a new one as needed. They have sunk virtually zero effort into customizing it, and so there's zero cost in selling it. Easy come, easy go.
B. Players like to feel like they are accomplishing something. No-one likes to try to tweak their new ship and discover that it seems like every change they make is making the ship worse. 
C. Players figuring out more optimum ways of outfitting their ships is rewarding. It makes them feel like they've accomplished something, improved their odds.
D. Fundementally, the fact that the stock configuration is *not* optimized gives the player agency. They can change stuff without automatically making stuff worse, they can play around with it, invest time in it, change out components, and do so with a reasonable possibility that they can at the very least improve things for their particular use case, perhaps overall.

**Comment by ThrawnCA** [comment]
All good points.
