### ISSUE TITLE
Enable missions to be completed immediately

### ISSUE THREAD

**Issue by ThrawnCA** [endless-sky/endless-sky#7984]
### Problem Description

Missions are sometimes eligible for completion as soon as you accept them, eg if you begin a Remnant "broken jump drive" mission and you already have a broken jump drive in cargo, or similarly for the missions where you're supposed to bring samples of technology. Currently you have to depart and land again to trigger the completion.

### Related Issue Links

#5895 is an example of a mission that could have been immediately completed, but was fixed another way.

### Desired Solution

Accepting a mission should be able to trigger a check to see whether it is already completed.

### Alternative Approaches

Broken Jump Drive missions could check for completion when the player visits the spaceport.

**Comment by Amazinite** [comment]
#5895 was not a case of a mission not immediately completing, it was a case of a mission not offering when it potentially could have.

For the broken JD jobs, they could be made to act like the Unfettered JD missions do where they take the outfit on offer instead of asking you to do something else first. If I recall correctly, it was an explicit decision to have the broken JD jobs require that you travel somewhere else first, not a limitation of the game engine that required it.

**Comment by ThrawnCA** [comment]
> if I recall correctly, it was an explicit decision to have the broken JD jobs require that you travel somewhere else first, not a limitation of the game engine that required it.

Some of them do, but I'm pretty sure I've seen the broken jump drive missions sometimes spawn at the current location.

**Comment by Zitchas** [comment]
The lore is that, due to the dangers, the broken JD labs are often in remote locations and this while sometimes deliveries are being transferred, in some cases they may simply be arranging delivery to elsewhere on the planet.

That being said, being able to complete something on the spot would be very much appreciated anyway. I don't like using fails when nothing is actually being failed.

**Comment by ThrawnCA** [comment]
Interestingly, I just pulled a broken jump drive from storage to cargo on a world where I had an open mission for it, and of course nothing happened, but I later had cause to load my saved game on that world - and the mission completed when I did.

**Comment by ThrawnCA** [comment]
This came up again when the Wanderers asked for samples of the Korath drone control components. I already had one of each, so after accepting the mission, I reloaded my saved game to immediately trigger completion.

**Comment by Amazinite** [comment]
With the introduction of autoconditions and conversation actions, we could update those missions to recognize that you already have what is needed for the missions when they offer instead of requiring you to take off and land.
