### ISSUE TITLE
Balance: Nerf Marauder Engine Leviathan and Falcon

### ISSUE THREAD

**Issue by 1010todd** [endless-sky/endless-sky#8124]
### Problem Description

I've always noticed Marauder Engine Leviathans where surprisingly fast but never really looked at its top speed compared to other, now that I did what I saw is comical, something in the realm of Author ships. MELeviathan have top speed of 1000 and turn of 155, it doesn't even catch up smaller ships it will outrun them and run in circle around them. Leviathans were known for being outdated and slow it should still be somewhat slow, I know the variant is specifically buffing engines but running in circle around interceptors is too much, way too much. (It also got the biggest jump going from 352 max speed in other Marauder Leviathan variant.)
Same applies for MEFalcon, yes Falcon is supposed to be a fast warship but 1200 top speed is still a bit much, I've already complained about ridiculous speed already above so I won't repeat.

I haven't look at other Marauders yet but it probably have the same situation going on.

Also this will be a progress towards balancing the game to make smaller ships more useful. If for whatever reason we don't want to drop massive change in one go then we should begin working towards it.

### Related Issue Links

https://github.com/endless-sky/endless-sky/issues/5271

https://github.com/endless-sky/endless-sky/issues/4034

### Desired Solution

Increase drag? Reduce engine space and down grade engines? Nerf atomic engines? I don't care too much about the means but their top speed and acceleration should be less than most regular(non modified) human interceptors (below 600 I think). Same for turning.

### Alternative Approaches

Make smaller ships faster I suppose. Engines thrust/ton over size graph could be flatter ~~like weapons DPS/mass over tier~~, improve other things instead like heat and energy efficiency so stacking smaller engines is still disadvantageous. Not saying thrust/ton don't get better at all, just get better at far far lower rate, iirc right now thrust/ton of largest engine is almost double of smallest.

**Comment by krushia** [comment]
The real solution is to remove drag entirely IMHO.

**Comment by 1010todd** [comment]
> The real solution is to remove drag entirely IMHO.

Doesn't really help and would create more problems for the amoeba-brained AI we have. Acceleration is still an issue as it's proportional to thrust and mass, high top speed often comes with high acceleration as well (I've checked and confirmed at least for the interceptors and MELevi this is true).

I feel like the most appropriate change would be to flatten the thrust/ton increase over the size of the engines but this would have a very wide effect to all ships which in turns mean more testing of a lot of things to account for it. 

I got a plugin for the rescaling human engines but I forgot what's the calculation for it, though it's still a significant cut to thrust for largest engines. With this MELeviathan got its top speed reduced to 658 which is more sane but still not ideal, it's still faster than most regular interceptors.

[Rescaled Engine Override.zip](https://github.com/endless-sky/endless-sky/files/10419760/Rescaled.Engine.Override.zip)

In addition to that big ships still have barely any mass increase that can be easily offsetted by bigger engines so they would need to follow square cube law to some degree and get a major mass increase, something like 20 times. For example Sparrow currently is around 170 tons, x20 is 3400 which along with adjusted engines will reduce the MELevi's acceleration down to 93, appreciably lower than interceptors which are around 200 and lowest being 150. I believe this problem was also mentioned in one of the linked issues.

**Comment by Zitchas** [comment]
The Marauder Leviathan is the epitome of non-sensical ship peformance. The real problem I have with it is that the "cost" (in terms of percentage of outfit space, and total outfit space) that it takes to get something this heavy going this fast is just so extremely high.

If we built the Leviathan like a barb (all engine with just a cockpit and gun attached), then I'd have no problem with it being this fast. But we haven't.

**Comment by 1010todd** [comment]
It's not just trade off, MELeviathan is one of the peak of ES heavy bias towards heavy warships and everything else is just a stepping stone, being HWs but weaker, HW and even weaker, almost the weakest of just another HW, and pointless HW that can be carried on some weak HW. There's already little distinction in combat between Heavy Warship and Interceptor except for sprite size, Interceptors are just Heavy Warships but shittier in every way, slow, weak weapons, fragile. Then MELeviathan comes along and eclipse that by outperforming Interceptors even more in *every single possible* area, tougher? Yes. More cargo? Yes. More weapons? Yes. More fuel? Yes. Faster and more maneuverable? Very yes.

Even if it's built to be 59% engine 40% gun and a speck of cockpit on it something still have to go like acceleration and turn(or hopefully turn acceleration).

**Comment by Zitchas** [comment]
Sorry, I should have specified. When I meant "built like a barb" I meant sure, take whatever the percentages are, but that's it. Basically no hull, no shields, definitely no cargo or extra bunks, barely enough outfit space to fit the power to run that engine + weapon for a single short engagement with an HD, and probably a pathetically small 200-400 fuel. The radical marauder modification in this case would be stripping *off* everything possible in order to get the absolute highest possible engine to total mass ratio possible. And yeah, that means ditching all the "extras" like hull plating and shield regenerators and any fuel beyond what it takes to get to the next system.

**Comment by Quantumshark** [comment]
The engines Leviathan adds 80 engine capacity to the original marauder Leviathan, while the engines Falcon only adds 55 over the marauder Falcon. Considering that the Falcon is supposed to be a faster ship than the Leviathan, maybe we should reduce the added engine capacity on the engines Leviathan and downgrade it to an A520 thruster rather than the A860?

**Comment by wzimrin** [comment]
My concern here is that in the game's current state, my enjoyment of the game is based pretty heavily on the fact that properly geared human heavy warships can run rings around damned near anything in space.  I really don't like "get a big ship with a big fleet and outstat everything" as a playstyle, which pushes me towards the "outrun and outrange" playstyle with stuff like particle cannons and inhibitor cannons.  Meanwhile, smaller ships simply don't have the space to mount enough particle cannons to kill a high tier ship in a reasonable amount of time.  Giving a human heavy warship enough engines to outrun an interceptor and then loading it down with particle cannons lets me play the game in a way I enjoy.

If you just want to nerf the engine capacity of engines-variant marauder leviathans and falcons, then sure, I honestly agree that their engine capacities are simply excessive.  However, if you want to make a larger change to slow down all large ships, then I think you need to pair that with a lot of other work as well.  Like, nerf the turn speed of those larger ships and nerf the turn speed of large ship turrets so that smaller ships can survive in cqb against those larger ships, and then add in forward firing cqb weapons that can let smaller ships actually threaten larger endgame ships.  That would make smaller ships actually relevant (similar to torpedo boats or bombers irl), which would provide a truly alternative playstyle to the usual big ship play.  However, if you just slow down large ships without those other changes, you'll end up in a scenario where large ships are boring to fly while small ships are irrelevant, and that doesn't seem like a net win for anyone.

**Comment by IsocratesGrey** [comment]
Generally, though of course engine quality and the ratio between steering and thrust changes this a lot, a fast ship is one where the drag vs engine capacity and total capacity is favourable.

This means that the technically potentially (of course engine quality changes this) fastest ships are the Wasp, Flivver, Sparrow, Fury, and Arrow. Rounding out the top ten adds in the Shuttle, Heavy Shuttle, Hawk, Headhunter*, and Bounder. So a light warship just barely gets in there. By this calculation the Corvette is the fastest medium warship and the Kestrel (Engines) is the fastest heavy warship. The Falcon then becomes the fastest standard available heavy warship.

Ok, but what happens when we add in the maurader engines versions of the Leviathan and Falcon...

Suddenly the Falcon beats out every single medium and heavy warship in human space. It's now as fast as a headhunter, the fastest light warship. It's faster than a bounder, a ship designed around being fast. It's in the top ten fastest human ships. Basically it's broken.

Leviathan moves from #39 on the speed list all the way up to #19, and it is now faster than every non-maurader heavy warship, it's even faster than the Kestrel (Engines). It's as fast as a Splinter. So yep, that's broken too.

The idea behind the ships being faster than normal makes sense, but essentially it's created two wildly broken ships in a game where closing the distance to a missile primary ship is really important.

Recommended fixes:
1) cut the engine space increase for marauder engine ships by 50% which would mean the Leviathan goes up by 40 instead of 80 (dropping it to the speed of a frigate or standard kestrel) and the Falcon goes up by 27 instead of 55 (dropping it to the speed of a quicksilver or raven).

2) Adjust the drag on heavy warships slightly. 

The range right now is
Falcon 6.7
Vanguard 8
Leviathan 8.1
Kestrel (engines) 10
Cruiser 10.1
Dreadnought 10.1
Protector 10.3
Kestrel 11
Class C Freighter 14
Carrier 17.7

Increasing the Falcon, Vanguard, and Leviathan by one to 7.7, 9, and 9.1 would probably fix a lot of this issue, moving the marauder versions back into the main pack. Again, the M Falcon Engines remains the fastest Heavy Warship, but it's not quite as overpowered.

**Comment by bene-dictator** [comment]
Closed by 9208?
