### ISSUE TITLE
Add warning dialog if departing a planet with cargo or fighters you cannot carry

### ISSUE THREAD

**Issue by macfreek** [endless-sky/endless-sky#815]
A player can end up with a negative amount of available cargo space, thus more cargo in the player's possession then the available cargo space in her/his fleet.

**Steps to reproduce**
1. Get two ships
2. Fill all available cargo space on both ships
3. Sell the escort ship.
Note: There may be missions which also lead to such cargo surpluss.

**Suggested fix:**
When selling a ship which leads to a cargo surplus (more cargo then there is space in the remaining fleet), display a message "Before selling your ship, you unload all its cargo on the platform. Be sure to sell it before departing!"

And the same check upon departure: "You still have more cargo than you can take with you. Do you want to sell it?" and then let the user choose between (1) Cancel departure & go to Trade screen, or (2) automatically sell the surpluss and take off.

**Comment by brick96** [comment]
I think 2 is already in game

**Comment by LocalGod79** [comment]
the game engine automatically sells any excess cargo upon departure - there's no dialog, but it's better than just crashing (which e.s. did in earlier versions)

**Comment by endless-sky** [comment]
As others have said, the game already auto-sells excess cargo when you take off.

I don't want to add a warning message before takeoff, because there is no way for the game to guess whether the player is planning on buying a new ship after selling their old one, and it would be a pain to have an excess cargo warning message shown every time you sell a ship. But, it would be easy enough to add a message on takeoff that says something like, "If you depart now, some of the cargo that you do not have space for will be sold. Do you want to continue and depart from the planet?"

**Comment by macfreek** [comment]
Sounds like an excellent solution, thanks!

**Comment by endless-sky** [comment]
In commit 1383015 I added a warning dialog that is shown when you take off if you are going to have to sell something.
