### ISSUE TITLE
Enhancement: Make AI utilize drifting

### ISSUE THREAD

**Issue by GalacticRuler** [endless-sky/endless-sky#818]
Thrusting to top speed and then drifting vs thrusting at a target until overshooting it and having to turn around to correct course.

Just a minor thing that'd make fleets more manageable and AI ships more realistic.

**Comment by lehgogh** [comment]
I don't like it when I'm waiting for pirates to fly in and my ships are constantly going in circles around me. Telling my fleet to hold position makes them drift slightly away from me. It would be nice to have them actually stay still.

**Comment by GalacticRuler** [comment]
"Almost th...overshot it AGAIN".
Yeah, it really is irritating having a pulsating swarm of ships surround you.

An added benefit of not always thrusting would be less energy drain and heat buildup that could be used for turrets.

**Comment by db47h** [comment]
In order to properly control rotation, realistic ships would have at least two pairs of steering thrusters: two at the fore on each side and two aft. This implies that ships should also be able to move sideways, and that that sideways thrust could be also be used as an alternative mean to (slightly) slow down the ship... Yeah, that'd open up a whole new world of possibilities and make the AI's movement control even more complex.

Anyways... Here's a tentative fix: #849.

**Comment by endless-sky** [comment]
I've just checked in a change that seems to work pretty well: bdf533b. Here's a video of it in action:

https://youtu.be/92t-iNz0d4o

**Comment by endless-sky** [comment]
Closing this because it's fixed in 0.9.1, which is released now.
