### ISSUE TITLE
Accessibility:  Mission tags on the map.

### ISSUE THREAD

**Issue by LadySerenaKitty** [endless-sky/endless-sky#820]
I've noticed the mission tags on the map are color dependent (same graphic with different colors).

I propose adding 4 new graphics for the map mission tags.  The colors can stay, shapes will cancel out color dependence.

**Comment by endless-sky** [comment]
The colors were chosen so that someone who is red-green color blind (the more common form of color blindness) can tell them apart (see #72).

I might consider using different pointer shapes, but it's such a small graphic that it'd be hard to come up with clearly different shapes that still fit is such a small size.

**Comment by LadySerenaKitty** [comment]
My main issue is the "Mission completed" and "Mission incomplete" tags are too close to the same color.  I don't see blue as well as I used to.  Different shapes are best.  You're always going to have someone out there who has a hard time with the colors. :)

**Comment by Amazinite** [comment]
Did 4973ccf fix the problem?

**Comment by tehhowch** [comment]
Please check using the latest release (v0.9.9)

**Comment by quyykk** [comment]
If anybody still thinks the pointers are too hard to differentiate, create a new issue! thanks
