### ISSUE TITLE
A Longer gap should exist between the FW and Hai Reveal

### ISSUE THREAD

**Issue by williaji** [endless-sky/endless-sky#8268]
### Problem Description

At the end of the Free Worlds campaign, I'm generally tired and want some unstructured time to explore, rebuild, and make use of my jump drive. If I follows the prompts, I'm pulled almost immediately into another long running campaign with little time to look outside human and Hai space. 

This feels very much in contrast to the FW, where there is a series of graduated missions to pull you into the story line. At no point do I have a news message and a mission telling me to "go here," at least not until I'm ready to paint my ship.

In my current campaign, I'd met Ivan in the Deep and he'd asked me to bring some keystones. By the time I went to Hai space, did some trading and brought them back, I'm being encouraged to return there before Ivan has even analyzed the keystones. When will I find the Remnant, particularly given that the Wanderers trigger quickly after Hai Reveal?  When will I have a chance to discover the Coalition, which I need for hull regen during the Wanderer campaign?

It is difficult even to ignore the summons and carry on because the destinations that will trigger the campaign are at Allhome (first landing spot) and Hai-Home (the only place you can buy Shield Beetles). I feel like I'm being railroaded into it.

### Related Issue Links

I did not find any other issues.

### Desired Solution

Push the date out for the beginning of Hai Reveal.

### Alternative Approaches

1. Build tension with a progressive set of news articles over a year or two. Let them start as conspiracy theories you see in spaceport news or overheard in spaceport conversations.
2. Bring forward all the Hai Rescue missions ahead of the official HR start so you encounter them out of context and it only makes sense when you meet Teneep.
3. Ensure that missions at Hai-Home and Allhome have opt outs so you don't have to take them immediately. I can't recall if they do this already.

**Comment by Zitchas** [comment]
I did some of the rescue missions before meeting Teneep, some after. One was, I think, before I'd really done anything with Hai Reveal. To be honest, I enjoyed it. Sure, they made more sense after I met Teneep, but I really liked the fact that I was able to slowly piece together on my own that there were people out there who knew about the Hai, and who were actively targetting them. So when I meet Teneep, it was more of a "Yep, what you are saying makes sense because I've already figured out a bunch of this and you are just filling in details." sort of thing. I feel it flows better and makes for a better story than having the rescues be purely an "after meeting Teneep" thing. That being said, I'd like to have more of them.

Regarding the timeline itself.... Having the articles come out a bit more spread out would be good, but only to an extent. Having some quiet for a month or so after the FW would be good, and I don't think the full HR explosion happen until, say, at least 4 months after the FW would be good. But a year or two? While realistic, that's probably much too long. Not everyone is going to be diving into the Deep or Emerald Sword story. Some want to get to the Wanderers. If we arbitrarily force them to wait for a year or two, that's going to cause problems too.

As a compromise: Have the default time be six months. However, if one starts doing the Deep or Emerald Sword missions, have that time extended by a month. If the player is doing a lot of generic human/hai back and forth jobs, shorten the timer for a month or two. Give people a way to cut to the action. And doing a lot of jobs that could contribute to them being revealed makes sense as a mechanism for doing so.

Even better might be to have a short mission early on. Have a tabloid reporter approach the player. "According to travel records you have disappeared into this area of space quite a few times recently. We've got a source that claims there are these aliens that live up there. Our contract with the source gives them full rights and credit for breaking this story, so we won't cite you... But we just want some independent confirmation from someone with experience before we broadcast this story. Can you confirm that there are indeed an alien civilization living in there?
1. Yes, there are. They are called the Hai. (this will probably lead to Hai becoming public knowledge quickly.)
2. No, I can't confirm anything. (this might slow down the public knowledge of the Hai.)

Pick option 1, and Hai Reveal happens really quickly. Pick option 2, and it gets pushed back a few months. And it gives the player some control.

**Comment by williaji** [comment]
Player autonomy and exploration are the key balancing points here. We've reduced both significantly. Wanderers are locked unless you are a dedicated sequence breaker. You can't even land on their planets until after HR unless you work at farming rep. Nor do you get to choose when to engage with HR. With the FW, there is a clear marker of accepting the commission that will sit there until you are ready to take it up. Ironically, people who pick up a jump drive early have more freedom to explore than people who get one from the FW. In addition, the factions that are not story line dependent are pushed to the margins as "after FW/HR/Wanderers," because there is a mission marker at Allhome, Hai-Home, and Vara K'chrai.

Previous to HR, the game felt discovery driven: go and look. Now it feels scripted. Right now, my pilot is in Hai space to pick up 50 keystones for Remnant. I've been directed to Hai-Home to be  an envoy. If I follow the path, the Remnant are on the back burner until the end of HR. To do anything else feels like I'm fighting the game.

**Comment by Hurleveur** [comment]
I think that what bothers me the most about this is it gives you a direction without giving the player a chance to explore. The same happens afterwards between HR and wanderers, but most of my enjoyment of this game when I first played it was discovering things by myself

**Comment by Zitchas** [comment]
Personally, I would like to see access to the Wanderers (and early Wanderer missions) split from the FW-HR-WN main campaign string. Sure, the HR could be required on the route to the Wanderer Campaign. That part makes sense. But to have *all* wanderer interactions blocked behind HR? That does not. 

But that does sort of bring to the forefront that we may need to split up how we reference to things: It's not the Wanderer campaign, it's the Wanderer section of the Main Campaign. It's not Hai Reveal, it's the Hai section of the Main Campaign. 

Wanderer content in general should be accessible somehow whenever the player finds them. The Wanderer section of the main Campaign, on the other hand, should wait until the player has made their way through to it. And there's almost certainly some parts of what is currently the campaign that could be stand alone stuff, but mostly we should have more original content that can be done there.

**Comment by movingpictures** [comment]
> 
>     1. Yes, there are. They are called the Hai. (this will probably lead to Hai becoming public knowledge quickly.)
> 
>     2. No, I can't confirm anything. (this might slow down the public knowledge of the Hai.)
> 
> 
> Pick option 1, and Hai Reveal happens really quickly. Pick option 2, and it gets pushed back a few months. And it gives the player some control.

Like.

**Comment by ziproot** [comment]
> Wanderer content in general should be accessible somehow whenever the player finds them. The Wanderer section of the main Campaign, on the other hand, should wait until the player has made their way through to it. And there's almost certainly some parts of what is currently the campaign that could be stand alone stuff, but mostly we should have more original content that can be done there.

Before Hai Reveal, part of the Wanderers campaign could happen at any time, and then the rest of it was locked behind the FW campaign. What we went back to that, but the rest of the Wanderers campaign was locked behind Hai Reveal instead? That way, you would still need to finish Hai Reveal to finish the Wanderers campaign, but not all interaction would be blocked.

**Comment by Hurleveur** [comment]
I see no reasons why HR should be before Wands.

For FW I can understand balance (and story) wise, but the Hai are not as op as the wanderers.

**Comment by Amazinite** [comment]
I'm currently going through the Hai Reveal campaign and taking notes on changes I'd like to make, and I want to almost entirely redo the introduction. Let me know if these ideas sound good to you guys:
1. Extend the time between when the main campaign ends and when the news report about the Hai happens. Currently, the event happens between 30 and 45 days after the main campaign is finished. As noted, this hardly gives you any time to get your bearings after the major events of the war. I think the time between the end of the war and the start of HR should mirror the time between the start of the game and the bombings of Geminus and Martini. That is, 230 days. (And there have been talks of increasing the time it takes for the bombing to happen, so if that time changes, I think this time should change too.)
2. When the news report does happen, don't immediately send the player to the Hai either by telling them to go there if the player has visited the Hai before or leading them there if they haven't.
3. If the player does end up finding the Hai themselves then they can get things started a little early, but if the player spends some extended amount of time playing and still hasn't found the Hai (perhaps waiting the same length of time as between the end of the main campaign and the news report), then have them be contacted by a character that they know from the main campaign that there's a situation that the character needs help with. That is, for FW players you get contacted by Alondo, by Syndicate players you get contacted by Remington, and for Navy players you may or may not be contacted by Xilin (idk if any Navy campaign storyboards include him), but he'll remain the Republic diplomat. (Any other main campaigns, such as a pirate campaign, will need to think of their own creative ideas of getting the player involved.) Whichever character contacts you would then bring you to Hai space to get you involved. That is, the Hai go to the human diplomats first, instead of first going to you, who may or may not be a war hero and may or may not be seen fondly depending on how your main campaign went.
4. Don't have things go from 0 to 100 so quickly. Right now, the introduction of Hai Reveal involves a massive daylight kidnapping that happens almost immediately after you reach Hai space, after which you're immediately pulled to Hai-home with no option to say no, and then told to bring some human diplomats, during which you hear reports of pirates using Hai weaponry attacking merchant vessels in the Far North. This has very quickly become an "oh shit" moment that you really can't just drop and go do something else given the stakes at hand. These high-stakes events should be something that happens after the introduction. For comparison, imagine if the first battle between the Free Worlds and Navy happened before you even joined. This feels somewhat like that. That is, have these moments happen after the introduction, and have the introduction be more like the FW intro where you're taking time to learn about the faction and set things up for future events. At best there should be murmurs of increased piracy or disappearances, not daylight kidnappings and pirates going ham on merchants with stolen Hai tech. Then at the end of the intro have a similar mission to "Join the Free Worlds" where you're given the option to either join or defer the mission and join later. There is a mission that is somewhat like this at the moment, but it's not as explicit as the Free Worlds mission.
5. Part of these new intro missions should involve building rapport with the Hai, instead of assuming that the events of the main campaign gave you rapport with them.

**Comment by MasterOfGrey** [comment]
> 1. Extend the time ... 230 days.

I'm not against this, the critical thing is that interest needs to be high enough for the right narrative to be able to cause a media storm. If the time is extended I'd like to see a number of discrete events fill out the space in between that prompt renewed interest in the possibility of alien threats. 
(Maybe someone in a Kestrel with stolen/borrowed/smuggled pug weapons got into a fight up in the North and the relatively alien-looking Kestrel with Pug guns got mistaken for an alien ship and caused a panic.)
(Maybe a Korath ship actually got captured by the Syndicate and they brought it to a planet that was Pug occupied for analysis - and it surprised a few of the wrong people that got it on media feeds of more distant areas where people don't know about them before the truth could catch up.)
(Maybe some merchants come across the wreckage of ships shot down by pirates using Hai/other weapons - soon enough to see it wasn't human weapons that did it, but just after the pirates have jumped out - and sound an alarm.)
However it happens, media interest needs to be propped up in the interim if we're going to specifically drag it out.

> 2. When the news report does happen, don't immediately send the player to the Hai either by telling them to go there if the player has visited the Hai before or leading them there if they haven't.

Counter-offer, provide nudges to find the Hai and build rapport with them beforehand, so that the news report is more the final "oh shit, now you gotta go deal with it" trigger?
Idk, this could go either way, but I am ok with it depending on what else it's padded with.
> have them be contacted by a character that they know from the main campaign that there's a situation that the character needs help with.

This probably works well as an alternative to just getting sent there directly either way.

> 3. If the player does end up finding the Hai [...] get things started a little early, but if [... "not" ...] then have them be contacted by a character that they know from the main campaign [...]. Whichever character contacts you would then bring you to Hai space to get you involved. That is, the Hai go to the human diplomats first, instead of first going to you, who may or may not be a war hero and may or may not be seen fondly depending on how your main campaign went.

Definitely a lot of work to do it justice, but I am 100% behind this as a rework pathway in the future.
(So much for this being a mini-campaign... *watches it blow out by another 20-30 missions*)

> 4. Don't have things go from 0 to 100 so quickly. Right now, the introduction of Hai Reveal involves a massive daylight kidnapping that happens almost immediately after you reach Hai space, after which you're immediately pulled to Hai-home with no option to say no, and then told to bring some human diplomats, during which you hear reports of pirates using Hai weaponry attacking merchant vessels in the Far North. This has very quickly become an "oh shit" moment that you really can't just drop and go do something else given the stakes at hand. These high-stakes events should be something that happens after the introduction. 

I think the chain of events (minus collecting the diplomats) is good and should still happen, but if there's a much longer prelude to it then that is definitely desirable (refer above).

> That is, have these moments happen after the introduction, and have the introduction be more like the FW intro where you're taking time to learn about the faction and set things up for future events. 

It is worth noting though that a crisis like this can only happen *so* gradually.  The FW intro is probably too gradual an introduction by comparison. If the player chooses to go and engage before it kicks off though, again, something I support.

> At best there should be murmurs of increased piracy or disappearances, not daylight kidnappings and pirates going ham on merchants with stolen Hai tech. Then at the end of the intro have [...] the option to either join or defer the mission and join later. There is a mission that is somewhat like this at the moment, but it's not as explicit as the Free Worlds mission.

Note: #8243 makes it more explicit than previously. It's also much clearer now, I think, that the intention is to earn a reprieve immediately before it.

> 5. Part of these new intro missions should involve building rapport with the Hai, instead of assuming that the events of the main campaign gave you rapport with them.

~~It doesn't assume that~~
There seems to be some people confused about the difference between actual rapport and pragmatic trust which gives some people strange ideas.
If we do add intro missions to build rapport though I'd *love* to introduce branching paths through certain things where you go one way with actual rapport, and have different challenges if they're operating only out of pragmatic trust.

**Comment by roadrunner56** [comment]
I've just started playing through Hai Reveal, and I definitely agree that it starts way too fast. After the war I just wanted to relax a bit and do some trading, but then I'm thrust into Hai Reveal and more galactic politics right after I fought the Pug. Also not a huge fan of having mission markers directly to Hai space. A lot of the fun of the game for me as a first time player was finding stuff on my own. You can nudge the player towards the Hai, but I'd rather it not be so explicit.

**Comment by roadrunner56** [comment]
That's not to say the story isn't good so far, I'm enjoying it, but I just think it shouldn't come all at once. It was overwhelming for me as a long time player, so I imagine it would be even more intense for a new player. 
"Ok so I just fought off these aliens called the Pug, and apparently there are some other aliens in the core that have been attacking the Syndicate for a while now, and there were Alphas in the Syndicate government, and now apparently there are some new, completely different super secret aliens up north that humans have been living with, and some are super friendly and some aren't and now they're not so secret any more and now there's pirates going through wormholes and I'm a diplomat now and I have to represent humanity to these aliens I wasn't even aware existed 2 seconds ago aaaahhhh!!!"

**Comment by Amazinite** [comment]
> I'm not against this, the critical thing is that interest needs to be high enough for the right narrative to be able to cause a media storm. If the time is extended I'd like to see a number of discrete events fill out the space in between that prompt renewed interest in the possibility of alien threats.

I'm honestly not convinced that we need to put too much stress on things to create a "media storm." Sure, there'd probably be more hysteria with the Pug invasion being almost immediately followed up by the news about the Hai, but say we wait an entire 365 days before Hai Reveal is able to start, are people going to hear the news and just be like, "*Scoff*. Alien invasions? That's so last year"?

And realize too that we need to balance player time and game time. Currently, 30-45 days is almost no time at all for the player. Let's say 230 is too short as well and we make it 365. Or even two full years. Whatever we choose, we're choosing it because it feels like the correct amount of down time for the player. But however long that is, the main campaign will still be rather fresh in the player's mind, so I don't think it's unreasonable for the story to act as if the events are fresher than they actually might be if we were to use game time.

**Comment by MasterOfGrey** [comment]
You might be right, we may not *need* it.
I would still think it'd be well worth it to include some flavour things to sustain it though.

**Comment by movingpictures** [comment]
Having gone through the new Hai reveal twice, I felt it came too quickly,
and felt forced (contrived) into picking it up as well.

Which is to say that a longer delay seems more than appropriate.

**Comment by Zitchas** [comment]
Well, if we're picking an arbitrary time, I'd say 6 months. For me, that would have been a good amount of time. Much more than that and I'd have gotten bored with things. 

That being said, I'd really like an optional mission or two (such as the previously described journalist trying to get confirmation from the player) that could speed up or slow down the reveal. That gives the player some influence, and, also importantly, helps them realize that there's stuff going on that they will be involved in.

The sooner the player "gets busy" with Hai Reveal, the less the fact that Wanderer missions are gated will matter. :)

**Comment by Amazinite** [comment]
The gap between the end of the main campaign and the Hai video news event has been extended to 230 days, similar to the gap between the start of the game and the bombing. The news event also doesn't immediately kick you into the story anymore.
