### ISSUE TITLE
Crime pays because scanning sucks

### ISSUE THREAD

**Issue by movingpictures** [endless-sky/endless-sky#8272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm a bit surprised there hasn't been more of a discussion on the changes to scanning, esp. scanning speed. Right now, a simple scan (ie: for the FW storyline, or the Remnant void sprite missions) requires several stacked scanners. 

But the issue goes both ways: in a recent playthrough, the character packed drugs at *every* opportunity. A few missions triggered benign trips to pirate worlds early, and the revenue generated was staggering - because the Navy ships simply can't lock on the way they used to.

The end result is that there are essentially no negative consequences for packing the "good stuff" across the galaxy.

### Expected Behavior

Get busted more often.

### Game Source

Built from source

### Game Version

Continuous build 29 Jan

**Comment by quyykk** [comment]
> I'm a bit surprised there hasn't been more of a discussion on the changes to scanning, esp. scanning speed.

See #7640

**Comment by UnorderedSigh** [comment]
Please try #8288 and see if it makes your illegal activities more difficult.

**Comment by movingpictures** [comment]
> Please try #8288 and see if it makes your illegal activities more difficult.

Will reply there, as well: I gave that PR a shot and it seems to return scanning to where it used to be - that is, you don't stand a chance.  Navy nabbed poor Lenny Lightfingers and his perfectly not suspicious heavy shuttle "Cheech and Chong II" twice in successive jumps.

**Comment by UnorderedSigh** [comment]
> Will reply there, as well: I gave that PR a shot and it seems to return scanning to where it used to be - that is, you don't stand a chance. Navy nabbed poor Lenny Lightfingers and his perfectly not suspicious heavy shuttle "Cheech and Chong II" twice in successive jumps.

I'm going to adjust the size dependence, too, so you only need 6x as many scanners to scan a Bulk Freighter as a Sparrow. I can adjust the difficulty level of scanning ships while doing that.

**Comment by UnorderedSigh** [comment]
I have adjusted the size dependence in #8288, and I'm able to do illegal missions most of the time. Could you please retest?

**Comment by UnorderedSigh** [comment]
PR #8323 will also help, as it keeps ships closer to their scan targets. You know how they move erratically around a slow-moving scan target, causing them to stay outside of scanner range? They won't do that anymore: if you move slowly, they'll intercept you, as they do when refueling you, and scan from point-blank range.

This will mostly affect big, slow, ships. I expect they'll still almost be "get out of jail free cards" but less so.

**Comment by movingpictures** [comment]
I think enough work has been done on this, so will close.

**Comment by UnorderedSigh** [comment]
@movingpictures Could you please re-open the issue? None of the PRs that are trying to fix the issue have been merged, and some haven't even been reviewed. There's still dissent in the community about whether there's even a problem *at all*, let alone how and whether to fix it. So, we definitely still need this issue open.

**Comment by movingpictures** [comment]
"As you wish."

**Comment by UnorderedSigh** [comment]
> "As you wish."

Thank you for granting my wish!

**Comment by movingpictures** [comment]
I merely quoted the greatest movie of all time.

**Comment by movingpictures** [comment]
So I downloaded the latest version (0.10.0) and ... the scan issue, I would regretfully say, is still less than perfect.

The test I used was the FW scanning mission - the ship I had was simply slower than the navy vessels (albeit by not much) and even with 10 scanners, the mission is exceptionally difficult to complete.

**Comment by UnorderedSigh** [comment]
That's because the fix was not merged before 0.10.0 since there is still a debate among the core developers whether there is a problem, and how or whether to fix it. (Or rather, it is one very senior individual who has turned quite authoritarian recently, and is ignoring *everyone else*.)

Could you please try my fix again?

https://github.com/endless-sky/endless-sky/pull/8288

I have updated it to work with all the other scanning changes recently.

**Comment by UnorderedSigh** [comment]
@movingpictures The devs have released a form that asks, among other things, whether the scanners are perfect. You may want to fill it out.

https://forms.gle/1sfh7YsLwUnLD5hm8

**Comment by movingpictures** [comment]
Done.

**Comment by IsocratesGrey** [comment]
Currently doing a new start on 0.10.0 and the scan the navy missions are painful. It's a combination of the scanner being a bit too slow and a bit too short. Increasing range might help as ships moving away from you won't be as bad, or speeding up the scanning time.

What was originally a fun simple mission where you get a heads up about what you'll face in FW campaign later on is now a slog.

**Comment by UnorderedSigh** [comment]
> Currently doing a new start on 0.10.0 and the scan the navy missions are painful. It's a combination of the scanner being a bit too slow and a bit too short. Increasing range might help as ships moving away from you won't be as bad, or speeding up the scanning time.

This is fixed in #8288, which among other things, increases the scanner range for the 10 second scan time by using a gaussian drop-off.

It hasn't been merged because one of the devs thinks scanners are fine how they are. If you think there are problems with scanners, please fill out the survey so they'll start to listen:

https://forms.gle/1sfh7YsLwUnLD5hm8

**Comment by Saugia** [comment]
If you haven't been keeping up, it has been said multiple times that scanners are in a weird spot right now and can still be adjusted, not that they're simply "fine". I would appreciate you don't use personal feelings with specific devs to instigate things such as surveys to make them 'start listening' as it looks bad and will actually do quite the opposite.

**Comment by IsocratesGrey** [comment]
> > Currently doing a new start on 0.10.0 and the scan the navy missions are painful. It's a combination of the scanner being a bit too slow and a bit too short. Increasing range might help as ships moving away from you won't be as bad, or speeding up the scanning time.
> 
> This is fixed in #8288, which among other things, increases the scanner range for the 10 second scan time by using a gaussian drop-off.
> 
> It hasn't been merged because one of the devs thinks scanners are fine how they are. If you think there are problems with scanners, please fill out the survey so they'll start to listen:
> 
> https://forms.gle/1sfh7YsLwUnLD5hm8

I did fill in the survey, but I was under the impression that the correct method for raising concerns here is through github issues. The specific fix is up to the developers, but commenting here instead of opening a new issue adds to their understanding of why the current implementation is a concern.

**Comment by UnorderedSigh** [comment]
> I did fill in the survey, but I was under the impression that the correct method for raising concerns here is through github issues. The specific fix is up to the developers, but commenting here instead of opening a new issue adds to their understanding of why the current implementation is a concern.

Yes, a good approach, and I'm glad you did that, but you actually got the wrong issue. The one about scanning missions being impossible is here: #7640

**Comment by Saugia** [comment]
>I did fill in the survey, but I was under the impression that the correct method for raising concerns here is through github issues. The specific fix is up to the developers, but commenting here instead of opening a new issue adds to their understanding of why the current implementation is a concern.

Yes. Github issues and discussions are the best source for getting our attention. Third-source things such as surveys aren't a good metric for these sorts of things.

**Comment by UnorderedSigh** [comment]
> Third-source things such as surveys aren't a good metric for these sorts of things.

Why was the survey done, then?

**Comment by Saugia** [comment]
Ah, my mistake. I thought you were linking a survey that someone else started. After-patch releases *are* good examples of surveys because the whole community gets a chance to provide feedback rather than when an individual for one side starts the survey. 

Again, I would just appreciate you hold back your distaste for specific devs and avoid using that as a bargaining chip to get feedback. As I said, "one dev thinks they're fine and we should make them listen" is an incorrect statement.

**Comment by UnorderedSigh** [comment]
> bargaining chip to get feedback

This is the wrong forum for such discussions, but unfortunately, I must respond to this one.

"Feedback" is not a concern; my issue with Management is and has always been abusive treatment of content creators. I make no petty attempts to get feedback; all of my PRs are at the request of someone else, or an attempt to solve a problem that was brought to my attention (generally by one of the devs). I've opened several scanner-related PRs because a dev told me there was a problem, and the exact nature of the problem, knowing I could provide a fix.

> In fact, the dev you are referring to explicitly said the change is temporary and Pirates can have a little fun with scanning for this current patch, and we'll adjust it later on.

I'm glad to hear that. It sounds like internal politics are sorting themselves out, in this case.

**Comment by Saugia** [comment]
If you have any more concerns about that, please contact Grey or Amazinite as you are mistaken a bit as to their interaction. 

Moving back to on-topic, scanner changes are indeed being looked at. There is no ultimate "they're fine", and people are half-and-half on how changes are.

**Comment by Saugia** [comment]
They will be and have always been made public, typically two weeks after they are started.

**Comment by UnorderedSigh** [comment]
A viable alternative to a gaussian drop-off is to simply expand the range of scanners. However, you have to expand it somehow, or slow ships won't be able to do scanning missions. The Navy Cruisers are faster than most human-space warship designs, even ones with significantly smaller hulls.

**Comment by UnorderedSigh** [comment]
> Edit: We typically do so through Derpy's stream, but I'll ask if we can do anything else.

That is a highly inappropriate discussion forum, since:

1. It eliminates the 1/4 of the world that is asleep at the time.
2. The ability to participate depends on the user being able to read and type quickly, which eliminates people with physical issues or who don't have english as their first language.
3. Such a discussion is far more one-sided since it is the streamer talking to his "fans."
4. This allows one user to monetize the Endless Sky community (or at least use it to boost their popularity).
5. People who don't have time to sit through a long stream can't take part.
6. It gives the impression that this is one person's game.

**Comment by Saugia** [comment]
I wouldn't say it's an inappropriate discussion form as it's not the sole one. I think it's beneficial because we get to see the lead Dev's unfiltered opinion, see him work with things in real-time, and gives us a sense of his demeanor as a lot of people are scared and dislike him when he's generally a good guy. It helps bridge the gap with the community a bit. 

1. Those asleep can still access the vod if they're really interested, but as I said, the discussion isn't solely on-stream.
2. Is a good point.
3. This is incorrect - there is a lot of debate that occurs on stream, it is most certainly not one-sided fans.
4. No monetization at all, and not intended to boost popularity.
5. Again, can access vods/discussion happens elsewhere.
6. Perhaps, but that isn't the streamer's fault so much as it is the fact that not many others stream.

I will kindly ask you one more time to withhold your personal gripes and opinions with specific individuals and devs as you seem to be mistaken about things and are a bit exaggerative on certain aspects especially referencing these individuals.

Let's move back to topic, please. I don't want to have to lock this conversation.

**Comment by UnorderedSigh** [comment]
> Let's move back to topic, please

Yes, I should not have brought it up here. It belongs in a different issue.

**Comment by Saugia** [comment]
Clearing up posts as requested.

**Comment by UnorderedSigh** [comment]
> Clearing up posts as requested.

Thank you! I will try not to get so off-topic in the future.
