### ISSUE TITLE
Maximum Heat Mechanic

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#840]
Something that I just found out is that the mass of an item directly relates to the amount of maximum heat that that item gives to the ship. For example, if an outfit has 5 mass to it, then it will increase the maximum heat of a ship by 18. 

This mechanic brings me two problems.
1) I have an item in my plugin that decreases the mass of a ship. But surprise, that also decreases the maximum heat of the ship. That means that you need to add more cooling to the ship to counteract the decrease in maximum heat. I'm not sure if I should try and change that or leave it in as a "balance" kind of thing to think about when choosing this item.

2) The reason I found this out is because of an item I was trying to add: the heat sink. A heat sink would act like a cooling unit, but instead of actually cooling the ship more it would increase the amount of heat that it would take before the ship would overheat. Basically, heat sinks are to cooling units as batteries are to energy generators. My problem is that I don't want to have to give the item a ton of mass to increase the maximum heat, because at that point it's entirely useless and you might as well just put capacitors on.

I tried seeing if a "max heat" attribute would work, but it doesn't actually do anything for the maximum heat. So my question is, does anyone know how I could get around this, or could it be made so that a "max heat" attribute on outfits would actually work?

**Comment by LocalGod79** [comment]
1) yes!  'mass' is indeed a double edged balanced attribute, reducing your ship's heat capacity so that you can turn and accelerate better (and be pushed away faster by powerful hit-force weapons)...

2) if you want something more 'heat sink'y than a supercapacitor, make the outfit space required 1, while the mass is 3...

**Comment by Amazinite** [comment]
That's what I'm doing right now, having different mass and outfit spaces, but that's not really the way that I want it. Like I said, it would be pointless if the only thing to it was having the mass to increase maximum heat, because then you could just fill your extra space with something small in order to get both the increased heat capacity and increased whatever other attribute. And while it's true that a heat sink is a mass that is used to absorb heat, this specific heat sink could be some odd material that increases its heat containing capabilities, without having an increase mass compared to the space. 

If needed, I'd settle with that skewed outfit to mass idea, but I'd much rather have it just give an actual direct change to maximum heat capacity without needing a different mass.

**Comment by jmhorjus** [comment]
Adding the ability to manipulate max-heat independently of mass is within my skill-set. Might take some time, as I've been very busy lately though.
Yes, different types of material have different specific heat (i.e. amount of heat per unit mass required to raise the temperature by one degree Celsius) in the real world. 

I'll probably have an attribute called "heat capacity" which multiplies the heat capacity contributed by the outfit.  So setting it to "1" is the same as not having it, setting it to 10 means if the object has mass X you get as much heat capacity as adding 10X of normal mass.  You could even set it to 0 or a negative number as a disadvantage.  Hmm...maybe be careful with negative numbers though, like always. :)

**Comment by Amazinite** [comment]
Yeah, that was the kind of atteibute I was hoping for.  :)

**Comment by Amazinite** [comment]
Don't mind me, just fat fingering buttons on mobile.

**Comment by endless-sky** [comment]
The way heat works in the game is that your ship overheats if it reaches a certain "temperature," where temperature is defined as total heat energy divided by mass. That's why heat capacity goes up when you add mass.

Meanwhile, the rate at which your ship sheds heat increases as its temperature increases, and also depends on the "heat dissipation" attribute of the ship itself.

It doesn't seem to me that a separate "heat capacity" attribute would really add anything to the game play.  That is, if all you're trying to do is increase the time until your ship overheats, a small cooling system would have exactly the same effect. And, it's not like batteries where adding more just increases the time before you run out; because heat dissipation is nonlinear, adding mass to the ship increases its heat dissipation rate at the high end.

**Comment by endless-sky** [comment]
Since this is a question about game mechanics and seems to be answered, I'm closing this issue.
