### ISSUE TITLE
variants cannot have additional gun ports/turret mounts

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#856]
this is an issue in the recently merged pull #831 , as the Weapons variant of the Marauder Falcon has two additional gun ports specified (but not processed).

if the user should sell any of the guns from that ship, they will not be able to refill those gun ports.

p.r. #854 will remove the variant status of the upper tier ships until this can be resolved.

**Comment by endless-sky** [comment]
I've checked in a change (a48ac0a) that makes it so that if you define coordinates for any weapon hardpoint in a ship variant, the variant's weapon hardpoints completely replace the base ship's. That seemed like the best option to match how the other sections of a variant work - for example, if you redefine any attributes you are required to redefine all of them, and likewise for the outfit list.

**Comment by LocalGod79** [comment]
awesome - i'll get to work updating #854 so that the higher tier ships are variants again.
