### ISSUE TITLE
[Bug]Ships are just drifting off into space

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#8611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm just sitting around in Pantica, and slowly but surely there's a build up of Remnant ships that are just floating off into the void in all directions. Not all ships, just some of them. There's plenty of regular traffic still functioning as regular traffic.

### Steps to Reproduce

1. Go to any Remnant system
2. Wait around in space for a few minutes.
3. See error

### Expected Behavior

Ships should eventually leave, cloak, return to the planet, or something. 

Now, it's the Remnant. I *can* just lore that these ships are just out there doing scientific observations or something. That'd be in character for them, and honestly, kind of desireable even. But I'm reporting it as I suspect that it is actually symptomatic of something breaking in the AI. And even for the Remnant scientific observation missions, they should begin to move again eventually. Maybe after 5-10mins or so?

### Screenshots

![2023-03-31 Vanilla Continuous ship build up](https://user-images.githubusercontent.com/32169904/229132050-8077ae31-f854-4067-8d91-9a7193f7df29.png)

Note that at many of the radar pings in this screenshot are outside the fence and just drifting outwards.

### Operating System

Windows 10 Pro

### Game Source

GitHub Releases

### Game Version

latest release as of 2023-03-31: 0e8ed96

**Comment by Koranir** [comment]
<img width="1921" alt="image" src="https://user-images.githubusercontent.com/101683475/229327887-956e8b51-faa1-4fb0-911c-3df5268f42e3.png">
Can confirm this issue, it seems to break their AI when they finish scanning you sometimes.

**Comment by Koranir** [comment]
<img width="1921" alt="image" src="https://user-images.githubusercontent.com/101683475/229328022-3a142812-af76-4e45-95d6-1225e3388e8f.png">
I looked a bit more, and they reactivate when there is a scanning target, scan them, then go dormant. It leaves this cluster to fighters, lol.

**Comment by Koranir** [comment]
Maybe the need to scan overrides the need to follow the parent, then the parent despawns? Or the ship never stops needing to scan and is stuck in that state, waiting for it's next target?

**Comment by warp-core** [comment]
Some of these ships just stop doing anything because that's just what ships with the "surveillance" personality are told to do when there are no hostile ships nearby, or they have no weapons, and there are no valid scan targets, and they have no hyper, scram, or jump driver, or lack the fuel to use one (though, ships with the capacity for sufficient fuel should ask for help), though it's possible that it was never intended for anything to actually reach this code, though their is no comment indicating this.

Some ships seem to get stuck in a situation where they are beyond the fence and are told to return to the centre of the system, but get stuck figuring out how to do that and end up doing nothing.

**Comment by tibetiroka** [comment]
Sounds like something #8348 would fix.

**Comment by UnorderedSigh** [comment]
PR #8860 fixes this. There were *many* little AI bugs that caused the AI to simply shut down. It didn't decide to do anything, so the ships just wandered at constant velocity until something forced a change in the state of the AI. (Enemy coming into the system, hitting the invisible fence, etc.)
