### ISSUE TITLE
Scram drive balancing

### ISSUE THREAD

**Issue by jerith** [endless-sky/endless-sky#8642]
### Problem Description

The reduced time to jump of a scram drive can be very useful in certain circumstances, but the ongoing cost of ownership (50% extra mass, outfit space, and fuel consumption) is way too high for the occasional benefit. As a result, I've never seriously considered installing one aside from my initial experimentation when I first played the game.

Compare this to a jump drive, which has an equivalent jump speed and can also ignore hyperlanes, for a cost of double the fuel consumption and no extra mass or space. By the time I'm in a ship big enough for the space/fuel cost of a scram drive to be tolerable, I likely have access to at least one jump drive and thus wouldn't be interested in a scram drive anyway.

In their current state, scram drives may make sense for ships with specialist roles that value jump speed over range. We can see this in some of the existing ships in the game that use them. However, the player needs a much more flexible and general-purpose ship for most of the game and scram drives just don't work for that.

Reducing the space/fuel cost, or providing some additional benefit to offset it, could make the scram drive a much more attractive option in the early to mid game and provide some interesting variety, especially for single-ship play.

### Related Issue Links

#8638 mentions the use of a scram drive in a Free Worlds mission.

I didn't find any other relevant issues or PRs, and I didn't search Steam/Discord/Reddit/etc. because I don't use those platforms and I would expect any serious discussion on this sort of topic to end up in GitHub anyway.

### Desired Solution

The simplest solution would be to reduce the fuel cost and thus the range reduction of owning a scram drive. 120 fuel per jump (instead of 150) would reduce an average ship's range by only one or two hops. That's tolerable, but probably not enough on its own. Reducing space/mass as well (perhaps 24 instead of 30) would likely make the drive worth consideration as an alternative to a standard hyperdrive for players who prefer to avoid pirates and other hostiles.

Alternatively, we could add some fuel storage to the scram drive. That would offset the range reduction for ships that don't have much range to begin with but still have a meaningful impact for longer-range builds. I'd combine this with a reduction in fuel consumption: perhaps 100 fuel storage for a size 30 scram drive that burns 120 per jump.

The exact numbers would need some input from people who understand the current game balance far better than I do, so please treat the above as a starting point rather than a well-researched conclusion.

### Alternative Approaches

The ability to switch between scram drive mode (with extra fuel consumption) and hyperdrive mode (with standard fuel consumption) would limit the fuel cost to situations where it buys something useful, in which case paying 10 space/mass for the option to do that is much more reasonable. This would require engine work and add UI complexity for a fairly minor feature, though.

**Comment by jerith** [comment]
If we decide that this is something that needs fixing, I'm happy to open a PR for any data changes we want. Setting up a dev environment and diving into the engine code would probably take more time than I have available, though.

**Comment by Quantumshark** [comment]
Honestly, I'm not sure the Scram Drive needs to both use more fuel _and_ take up more outfit space, I think either would be enough of a downside alone.

**Comment by jerith** [comment]
> Honestly, I'm not sure the Scram Drive needs to both use more fuel _and_ take up more outfit space, I think either would be enough of a downside alone.

Agreed, but I'd be okay with keeping both as long as the overall cost is reduced. Also, a fuel reduction would probably be necessary even if the extra outfit space is removed entirely.

**Comment by Hecter94** [comment]
Scrams are a specialist tool with limited usage. They shouldn't be something appealing for general usage and shouldn't be compared against a hyperdrive for general usage. 
They are ostensibly something you take when you need the extra jump speed and don't care about the downsides.

> In their current state, scram drives may make sense for ships with specialist roles that value jump speed over range. We can see this in some of the existing ships in the game that use them. However, the player needs a much more flexible and general-purpose ship for most of the game and scram drives just don't work for that.

This is their purpose, yes. They are a specialist tool for a specialist role that isn't as flexible or as generally useful as a hyperdrive is. This isn't a flaw that needs to be fixed; that's their purpose for existing.

**Comment by EjoThims** [comment]
IF anything, the specialized functions of the scram should be buffed to the point that it justifies the drawbacks, not the drawbacks reduced until they’re small enough penalty for the function.

**Comment by jerith** [comment]
If the intention is for them to be installed when necessary and then removed afterwards, the extra outfit space is a barrier. In the early game when I'm most likely to need one, freeing up another 10 space to install it is potentially problematic.

Until I ran into #8638, I'd never encountered a problem for which a scram drive is the solution, so maybe the answer here is to add more of those to give the player more reason to think about jump speed. Some new "blockade run" jobs/missions would be a good fit for that.

**Comment by Quantumshark** [comment]
> Until I ran into #8638, I'd never encountered a problem for which a scram drive is the solution, so maybe the answer here is to add more of those to give the player more reason to think about jump speed. Some new "blockade run" jobs/missions would be a good fit for that.

We do have some blockade running jobs, but the blockade is in the destination system so a scram drive isn't helpful for them.

**Comment by ThrawnCA** [comment]
> They shouldn't be something appealing for general usage and shouldn't be compared against a hyperdrive for general usage.

Maybe that's the problem. There are players who would quite like to make scram drives their default hyperdrive option, whether it's to dodge pirates, reduce the real time taken for long distance travel, or just because they look cool. Making scram drives only viable in niche usage is thus a disappointment.

**Comment by Zitchas** [comment]
> We do have some blockade running jobs, but the blockade is in the destination system so a scram drive isn't helpful for them.

> Until I ran into https://github.com/endless-sky/endless-sky/issues/8638, I'd never encountered a problem for which a scram drive is the solution, so maybe the answer here is to add more of those to give the player more reason to think about jump speed. Some new "blockade run" jobs/missions would be a good fit for that.

The big problem with blockade missions - and this is something that seriously impacts the logic of the civil war, too - is that in the current travel structure it is extremely easy to bypass basically everything in every system other than the arrival system. Even the departure system, under the current system, it is extremely easy to escape the system before anything in-system can do anything unless one has the misfortune of having the hostile already in-space but on-top of the planet when you take off. This is likely to always be the case, although there are some solutions, they all have significant costs for the current style of gameplay:

Possible solutions:
1. Have location in the system matter for hyperjumps. As in, if you want to jump North, you have to be on the North side of the system. If you want to jump East, you have to be on the East side of the system. This means that suddenly there's no more "hit jump, then sit back and relax until you reach your destination" because you actually have to cross a portion of every system. This means that suddenly a border system occupied by hostile forces is now actually a blockade that you have to cross before continuing. (I would expect scram drives to provide a small degree of flexibility on this. Ex. If to jump North you have to be on the northern half of the system, then with an SD you'd have to be on the Northern 220 degree arc of the system, or something of the sort. Additional flexibility, but not a complete elimination of the restriction)
2. Buff fighters and interceptors so that they actually have the speeds required to intercept ships that have just arrived before they have the chance to come to a stop, turn, and depart on the next hyperjump.
3. Ensure all factions have a long-range high speed weapon that does enough force to break a hyperjump against most ships (including very large ones), or some other hyperjump disrupting weapon, and that such weapons are sufficiently common that any blockading forces will guaranteed have them. (or have it be a known weakness of said faction that they don't have such weapons, acknowledged by the story)
4. Slow down the average ship to ensure that they actually significant windows of vulnerability when they are in the midst of long hyperjump routes across hostile territory.
5. Implement departure distances so that ships taking off have to actually clear a certain distance before they can jump, allowing the possibility of reasonable blockades in the departure system.

The best solution is probably a combination of all of these in moderation, rather than any one of them taken to the max. 

Solving https://github.com/endless-sky/endless-sky/issues/4034 will probably significantly improve this problem, too. I don't think it will solve it completely, but it will improve it a lot.sdfdds

**Comment by Quantumshark** [comment]
I don't think ideas 2, 3 and 4 on that list are good ideas. What would the counterplay to them be?

> Buff fighters and interceptors so that they actually have the speeds required to intercept ships that have just arrived before they have the chance to come to a stop, turn, and depart on the next hyperjump.

This one is probably the most reasonable of the three, provided that they're not also made too mobile to hit. Even then, needing to deal with attacking fighters quickly before the bulk of their fleet arrives is a DPS check, and DPS checks push people into things like deathfleets or rushing automata before the main campaign. There needs to be a way to solve the problem without resorting to the completely overpowered.

> Ensure all factions have a long-range high speed weapon that does enough force to break a hyperjump against most ships (including very large ones), or some other hyperjump disrupting weapon, and that such weapons are sufficiently common that any blockading forces will guaranteed have them. (or have it be a known weakness of said faction that they don't have such weapons, acknowledged by the story)

If every faction can stunlock you with hit force from across the system, the only possible way to move through any hostile region of space is to either gun down every single hostile ship that spawns there (and good luck doing that if you're not using a death fleet and/or a ship or ships vastly ahead of what you're facing), or spam reload until there are no hostiles spawned along the whole path. Neither of these are good gameplay, and I don't think a change that forces them is a good change.

As it happens, one of the factions of the Naltok that I'm working on uses a suite of weapons specifically designed around jump interdiction, so I do have some subject-specific knowledge here. My goal designing them was to make it hard, but not impossible, to get past them, and to make sure there were multiple ways of doing it. The weapons I designed were a high-speed, burst-firing missile with slowing damage, and a short-range beam weapon which drains fuel, and is mounted on a small, fast ship. There are multiple ways to get round this - you can use an even faster ship and outrun the missiles and the fuel-draining ships alike, you can bring enough DPS to take down the fuel-draining ship before the rest of its fleet arrives and then board the fuel-draining ship to refuel yourself, or if you don't want a challenge you can just use cloaking or bring an enormous fleet that will just outright demolish all the defending forces. The key point here is that you have multiple options, multiple ways to approach this, and crucially some of those options are possible without just cheesing the whole game. 

> Slow down the average ship to ensure that they actually significant windows of vulnerability when they are in the midst of long hyperjump routes across hostile territory.

This either has no effect beyond being mildly irritating, or has the same problem as with the previous idea, depending on whether or not you slow the player down enough to matter.

From a more general view, I don't think being interrupted while you're travelling through systems is fun. I don't think making it harder to travel through systems on your way to a destination would make the game more fun.
Even if you disagree with me on these points, there's an important distinction to be made between making a task impossible without a specific solution that trivialises it, and making a task challenging. "Travelling through hostile systems is impossible with a hyperdrive, but easy with a scram drive" isn't interesting. "Travelling through hostile systems poses challenges depending on what specific faction's systems they are, and you can take any one of several approaches depending on what you're facing", on the other hand, is good game design.

**Comment by Zitchas** [comment]
I'll be honest, number 3 is my least favorite of all the listed options. I presented there. I'll be perfectly happy if it isn't implemented or is restricted to a single faction.

However, one way or another, some method of making all those systems along the way meaningful instead of just being a determinator for how many pages of my book I read before I have to take command again is necessary.

And that's really the point: It's not about just making life hard for everyone. It's about meaning. If an NPC tells you that the Navy has blockaded the borders and shipments can't get through, it should legitimately be hard to get shipments through. Right now it's basically a "Well, I guess every other captain in the galaxy must be incompetent because I can get through no problem" sort of situation. Likewise, if we're told Pirates have infested a system so we can't through it to somewhere else, that should actually mean something more than "don't plan on hanging around ramscooping for a couple minutes."

Meaning, challenges, and fun are the point. 

Anyway, the best situation is to have it such that, for any particular dangerous system, some combination of those attributes is true. For your aliens, it might be having jump interdiction weapons. For the Remnant, it might be having fighters that can reach a ship and start knocking it around no matter where it appears in the system before it can start jumping out again. for the Navy maybe they just have systems well-covered in ships so there's no unthreatened area to jump in to. For some systems maybe there's specific areas you need to be in to jump out in that direction, and those can thus be interdicted. Many systems, especially peaceful and/or well traveled system may not have any of these.

Variety is the best option, really. Any one thing would be boring. But right now, we have none of them, and that's a problem.

**Comment by ThrawnCA** [comment]
> If every faction can stunlock you with hit force from across the system, the only possible way to move through any hostile region of space is to either gun down every single hostile ship that spawns there (and good luck doing that if you're not using a death fleet and/or a ship or ships vastly ahead of what you're facing), or spam reload until there are no hostiles spawned along the whole path.

I think the point is just to make it _possible_ for each faction to lock down a system so no one can casually get through. Not something that every random spawn would carry, but a serious blockading fleet will have a way to intercept and stop players from passing through.

**Comment by IdkSomethingTemporary** [comment]
> Until I ran into #8638, I'd never encountered a problem for which a scram drive is the solution, so maybe the answer here is to add more of those to give the player more reason to think about jump speed. Some new "blockade run" jobs/missions would be a good fit for that.

One use I've found for scram drives is to use them for freighters pre-JD. High jump speed allows you to make more money per IRL time. I'm not sure if it's cheaper than reverse thrusters but it's certainly an option. It also allows you to strip down your weapons, shields and power in order to have more space for cargo expansions and fuel pods. 

As for increasing the difficulty of blockade running, I fully agree with what Zitchas said. With just hyperdrives it's awfully easy to just fly through "blockaded" systems with only a minor threat of a restart, and the very idea of blockades ends the moment you unlock JDs, since there really isn't much in the game, outside of fuel and a dozen archons, that can stop a JD ship from running through a system. In my opinion, the biggest issue really is the time factor. it takes way too little time to travel from one system to another, and any form of interdiction would require the faction in question to be able to immediately slam any ship that jumps in with large amounts of force. The navy at least has it easy in only needing to stop hyperdrives, while most of the other factions need to basically cover the entire system in a drak draining field, which isn't very practical.

I feel like a mix of option 2 and and option 3 and variations of them depending on the faction, combined with a global application of option 1, should do the trick. By forcing the player to travel through the system (regardless of the drive they're using!), it allows the faction-specific interdiction methods to have more time to take effect (the navy actually has a pretty good interdiction game with their particle cannons, it's just that often you're gone before the navy can even turn around. If their fleets can get on top of you then they can actually stop you reasonably well). Specific systems, such as those in the ember wastes, can have more restrictive jump areas (such as being further out from the center of the system or being a smaller arc). The arc could be modified not just by the drive you're using, but also the number, making it more interesting, while more traveled systems (such as most of human space) would have far less restrictive options. The return from travel related missions could be buffed to make up for it - or not, if you want the game to have a slower pace

Or maybe I'm just all wrong. I am by no means anywhere near a expert in any aspect of this game, so please, point out any mistakes I've made.

**Comment by danaris** [comment]
Two thoughts:

First, re: the scram drive itself:
Would it be worthwhile to consider changing it from a completely different hyperdrive you replace yours with, to a "hyperdrive module", that modifies the jump fuel and adds "scram" capabilities, but doesn't allow hyperjumping on its own?
(The jump drive could potentially get this treatment as well—and it would open up the possibility of adding further "hyperdrive modules" to adjust jump speed, scram angle tolerance, jump fuel, etc. But I digress.)

Second, re: blockades:
Rather than preventing the player from jumping by stunlocking them, what about preventing _all_ outgoing hypertravel from the system with a specialized ship that emits a "hyperspace damping field" or something? It would be well short of the kind of hyperlane manipulation the Pug can do (the lanes are still there, the hyperdrive is just overloaded by high-energy tachyon particles or something), and it would make sense to have it require the entire energy output of a largish ship (ie, the ship has no weapons or defenses of its own, and its shields aren't great either); the player then simply has to destroy that ship to be able to leave.

**Comment by Quantumshark** [comment]
> Rather than preventing the player from jumping by stunlocking them, what about preventing all outgoing hypertravel from the system with a specialized ship that emits a "hyperspace damping field" or something? It would be well short of the kind of hyperlane manipulation the Pug can do (the lanes are still there, the hyperdrive is just overloaded by high-energy tachyon particles or something), and it would make sense to have it require the entire energy output of a largish ship (ie, the ship has no weapons or defenses of its own, and its shields aren't great either); the player then simply has to destroy that ship to be able to leave.

Forcing a player to stay and fight makes blockade running no different from a regular combat mission. The whole thing that makes blockade running different is that you can, well, _run the blockade_. For that to be the case, you have to allow the player to move through the blocked system without needing to engage the blockade in combat.

**Comment by ThrawnCA** [comment]
> Forcing a player to stay and fight makes blockade running no different from a regular combat mission. The whole thing that makes blockade running different is that you can, well, _run the blockade_.

So maybe the interdiction has a large but limited range, and you have to get away from the blockading fleet to jump?

**Comment by Zitchas** [comment]
We're testing a variation of that on the Delta fork. We've implemented departure distances, which means that a blockading fleet can control the inner system, and escaping ships need to clear the inner system in order to make the jump. So far, we're finding that it adds a bit more of a "blockade" feel to things since the player can't just jump from anywhere, they actually have to think about "what's the best route to somewhere I can actually jump?" It's got a fair bit of impact and a good feel for missions where the player needs to land at or take off from a blockaded planet; but it doesn't do a whole lot for blockading systems versus ships that are just trying to get through it to some point beyond.
