### ISSUE TITLE
Fleet formations

### ISSUE THREAD

**Issue by wargwargwarg** [endless-sky/endless-sky#866]
Line, battle, loose, tight, flanking, protect the ship (not necessarily the player ship)
All in relation to the player ship and only if the thrusters are being used (fleet doesn't modify the positions if the flagship is just using steering to fire at someone).

**Comment by Wrzlprnft** [comment]
- #302 
- #700 
- #849 

top 2: issues about the same topic. last one: possible solution incoming
sometimes just have a look around ;)

**Comment by wargwargwarg** [comment]
Oups, sorry about duplicating the issue!
The fleet maneuvers wouldn't have to succeed, just the various ships should have to try to get in the designated position relative with the flagship. In battle, at least they'll keep close so you can help them (BIG help). After battle or in a quiet interval, they reform on the flagship. If that isn't running in circles or something

**Comment by Wrzlprnft** [comment]
Don't worry, it happens from time to time, and it also shows which topics the community is most interested in. You could write a comment about  the idea of **pausing the formation during battle** to the pull requestl, though.

**Comment by Alkallid** [comment]
Line and flank might be difficult to manage, but battle exists, the gather command could be used on targeted ships to protect, and loose and tight might not be necassary.

**Comment by wargwargwarg** [comment]
At least the ability to order ships around. Go there! Blast that! Stop engines! Click and click. or better CTRL + number of ship and click + G (go) + click. But, at the current speed of the game , there is no time to do that (hence my previous suggestion Game Time Adjust)

Oh, waypoints for your ship if not for the fleet, to position yourself better versus your attacker: say you have a heavy cruiser bearing in on you, you try to flank him at full speed (to evade a part of the incoming fire, waypoints 1 and 2) than do a sharp turn and spiral till he's down (presumably he will be able to hit you with turrets only)

**Comment by db47h** [comment]
Sorry about the horribly long post...

I wouldn't consider this issue a duplicate if #818 or #849. It just so happens that if we manage to get something working in #849, it will allow ship formations as a side effect. This issue is just the right place to discuss formations.

Just a quick aside: "Go there, blast that" and "stop moving" are already implemented in the game: that's "fire at target" (F key by default) and "hold position" (H). Only you can't select which escorts do what. Also, adjusting the game speed would just turn the combat part of the game into an entirely different game. So exit waypoints and any other micro-management, just make a big enough fleet and blast anything and everything into space dust.

Back to formations, from the various comments here and here on the subject, I've seen people who prefer the current mechanic where escorts just [flock](https://en.wikipedia.org/wiki/Flocking_(behavior)) around the player's, and some would like big scary static battle formations. The saying goes that who can do more can do less, so if the engine allows fleet formations, the current behavior can be somewhat simulated (probably even nicer).

With that out of the way, @wargwargwarg's initial comment is interesting:

> All in relation to the player ship and only if the thrusters are being used (fleet doesn't modify the positions if the flagship is just using steering to fire at someone).

Suppose you have a cross formation (like a "+" with you at the center), my initial thinking was that if you turn 45 degrees in any direction, your escorts would move around and reposition themselves, the formation would then look like an "X". For this to work, the escorts on the far side would need to accelerate faster than your current speed, then turn around to slow down once in position. Pull off some fancy flying maneuvers and it's utter chaos in your fleet.  With @wargwargwarg's suggestion, there would be much less scuttling around, just neat, military order in your ranks ;)

@Wrzlprnft mentioned "pausing the formation during battle". If I understand correctly, that would mean allow escorts to break formation, chase enemy and fire at will. That's not very different from the way the gather command works right now. If no enemy ships are in sight, your escorts gather around you by default. When a hostile shows up, they just go kill it, When "gather" is activated, they only fire at hostiles in shooting range but stay close. If we implement formations, formations would just be how escorts organize themselves around the player's ship, either when idle or when force-gathering them, that's all. I don't see why we'd make formations an alternative to the gather command.

**Comment by nylki** [comment]
>  don't see why we'd make formations an alternative to the gather command.

Yep, it's two things. One is a spatial alignment of escorts (that @db47h PR might help to solve), the other the behaviour of fleets.
Those two could be combined later, but now are independent problems to solve first.

I am working on code for fleet behaviour/stances discussed in #802 that extend the defaults actions (default, gather, hold) with a few more.

**Comment by endless-sky** [comment]
Just to avoid having duplicate issues, could you move any further discussion of formations into #700?
