### ISSUE TITLE
enhancement: shipyards temporarily retains hulls sold by player

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#869]
similar to the way the outfitter temporarily stocks outfits it doesn't normally - perhaps returning outfits to stock variant?

recently merged #864 and #831 have ship descriptions that the user cannot see (until mission content otherwise brings them to a shipyard)

i'm okay with them remaining hidden until such time that a Marauder storyline is conceived and written - i understand some of the complications that this could exacerbate (fusion reactors at valhalla)

just a thought.

**Comment by jmhorjus** [comment]
This is within my skill set; I've already considered adding this to https://github.com/endless-sky/endless-sky/pull/852 since the reduced price of used hulls would give further incentive to potentially "buy back" a sold ship hull from time to time.  

I'll start looking into it next week.  
To avoid any exploits, the hulls would ideally be sold back to you completely empty (since all their outfits already went to the outfitter), so I was planning to create a new section of the shipyard just for derelict hulls, called the "junkyard". :) If you bought a hull at the junkyard it would be automatically parked and unable to take-off until such time as you actually installed enough outfits to pass flight-check.

**Comment by LocalGod79** [comment]
i'll take your word on your behind the scenes concept.  it would definitely add more weight to your branch pull (addressing another raised engine issue).

i'm concerned that #852 seems so wholesale - even more that there doesn't appear to be any feedback from m.z. on any of it.

have you considered breaking it up a little bit?

**Comment by jmhorjus** [comment]
My thought was that breaking it up (with the exception of removing the few smaller/invisible changes noted in the bottom of the pull description) would result in something that wasn't a complete package - i.e. putting in depreciation infrastructure without the ability to actually buy/sell used items or without the random "aging" of captured ships or without adding available outfits/ships to the save file would mean it wasn't quite fully playable or entirely consistent.  

I do agree that continuing to add more and more features, like a ship junkyard, to that same pull is a bad idea - that anything new should go in a new branch.
