### ISSUE TITLE
How to use libEndlessSkyLib.a?

### ISSUE THREAD

**Issue by huangwenxian** [endless-sky/endless-sky#8691]
### Problem Description

I Have cmake Xcode project，and build success libEndlessSkyLib.a

### Related Issue Links

I Have cmake Xcode project，and build success libEndlessSkyLib.a

### Desired Solution

I Have cmake Xcode project，and build success libEndlessSkyLib.a

### Alternative Approaches

I Have cmake Xcode project，and build success libEndlessSkyLib.a

### Additional Context

I Have cmake Xcode project，and build success libEndlessSkyLib.a

**Comment by mOctave** [comment]
It's a little unclear, but I presume what you're saying here is, you built the XCode project successfully using CMake, and now when you try to build and run the XCode project, it tells you it successfully builds "libEndlessSkyLib.a" and then does nothing.

If that's the problem you're having, check your build scheme. It should be set to `EndlessSky`. If it isn't try selecting it and then hitting run, and it should build and run the app automatically.

<img width="1399" alt="Whole Window" src="https://user-images.githubusercontent.com/73318970/234146960-f46e585c-0ec5-4e4e-9122-61207cccc722.png">
<img width="234" alt="Just Dropdown Menu" src="https://user-images.githubusercontent.com/73318970/234146964-4836eea7-243e-4ebf-9023-09476dbfa5b9.png">

_PS: In the future, this kind of thing would probably work better as a discussion, rather than an issue._

**Comment by petervdmeer** [comment]
Closing this issue; I believe mOctaves response answers the question quite completely.
