### ISSUE TITLE
"Max Amount" attribute

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#878]
Limits the maximum amount of a projectile that are active at a time. If the max amount is reached, the oldest projectile detonates. Could be used for something like manually detonated bombs. I don't know, just a thought I had.

**Comment by LocalGod79** [comment]
i assume this is related to the "drak summoning" weapon you posted on Steam, and you're actually requesting a terminating counter for non-unique-submunitions.

this has been requested a number of times for varying purposes - i think i've already told you about the self-replicating hit force munition (basically applying an always active thruster to a point on the target hull) - in addition to your self-propagating weapon.

additionally, this was proposed as a solution in #761

**Comment by Amazinite** [comment]
I thought it up while thinking of another weapon that I'm creating, but it would be useful for other things such as the "drak summoning" weapon so that it doesn't crash your game, or to simply reduce the CPU requirement in some huge battles.

**Comment by LocalGod79** [comment]
i'm concerned that this might be an unintentional nerf for missile systems (since they are the projectiles with longest lifetime) - both an integral factor of those massive battles you mention, and perhaps an already underused outfit set.

**Comment by jmhorjus** [comment]
Missiles are an underused outfit (by players) because they don't play well with disabling ships. If there was a missile that only disabled and never destroyed, everyone would probably use it. :)

**Comment by Amazinite** [comment]
It could be applied where needed. Missiles would obviously be a touchy item to put it on. I'm not exactly sure how much reducing the number of projectiles would affect the CPU during huge battles, so it doesn't need to be used in those cases. It was just a suggestion for a use, and not really me saying how it should be used. If it is added, then it's up to the community and modders where it should be used.

**Comment by LocalGod79** [comment]
@jmhorjus - i didn't specify why they're underused: there are lots of reasons not to, besides disabling difficulties - reloading logistics, running operating $, heavily impeded by asteroids...

i was trying to point out that an engine limit on in-system projectiles would specifically nerf an already underused outfit set.

that said, a per-weapon/per-munition counter has already been suggested/requested - this issue seems redundant.

**Comment by endless-sky** [comment]
This would be rather complicated to implement. For every projectile in existence, you would have to track which particular weapon on which particular ship fired it. And, for every weapon on every ship you'd need to check whether it had exceeded its limit of projectiles on screen.

That doesn't seem worth it, especially because the whole idea that each projectile knows how many "siblings" it has and self-destructs if it's the oldest one, is a little unrealistic.

**Comment by Amazinite** [comment]
Fair enough.
