### ISSUE TITLE
Hai reveal while on Hai-Home

### ISSUE THREAD

**Issue by KimDare75** [endless-sky/endless-sky#8863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I encountered Alonso while _on_ Hai-Home.
I was on the Wanderer Plotline where they send you to Ya Hai after the tiny probes Iktat Rek gives you, and landed on Hai-Home. I got three or four encounters, in fact, first the one you are actually meant to do, then asking an elderly Hai about the normal Hai's view on the Unfettered (wait, was that the original one), the young Hai that shows you the Human News broadcast AND Alonso!
In one landing!

The four (!) encounters aren't the problem here. The main issue is that I now have to _start and land **on** Ya Hai._
_Where we literally just were._ It feels like a malfunctioning mission to me. It's a logic issue.

### Steps to Reproduce

1. Do Wanderers Post-Main Plotline and jump through the Unfettered's systems, and land on Hai-Home.
2. Have good RNG on landing. (Get 2/4 dialouges pop up)
3. Have _even more_ crazy RNG. (click on spaceport to get the other two encounters)
4. Go through all those.
5. Open the map afterwards and wonder **why Alonso Invites you to the literal planet you are currently on.**

### Expected Behavior

I would expect Alonso to realize we are on Hai-Home and not need me to meet his ship in orbit.
aka:
We could exclude Hai-Home from the mission start conditions.
There isn't a way to make the game realize that we **are** on Hai-Home, is there? Technically, being landed on Hai-Home, I met the conditions to complete, right?
I don't know about other possible solutions...

### Screenshots

![20230607165024_1](https://github.com/endless-sky/endless-sky/assets/85624541/a7b3d93b-04e3-40f0-813c-011476b29b39)
See? (as you can't see, I currently am on Ya Hai. But I am.) Alonso wants me "To go land on Hai-Home"!

### Link to save file

[Kim Dare.txt](https://github.com/endless-sky/endless-sky/files/11679127/Kim.Dare.txt)

### Operating System

Ubuntu 22.04.2 LTS

### Game Source

Steam

### Game Version

0.10.1

**Comment by KimDare75** [comment]
Wait, _WHAT?!?!?!_
Alert! Even worse Issue just detected!
Upon opening the Game, the mission requirement dissapeared!
**WITHOUT** showing me Alonso's dialogue!
It must have registered that I was landed on Hai-Home, and skipped the _entire_ dialogue!

**Comment by lumbar527** [comment]
Did you pick up another mission after it vanished?

**Comment by KimDare75** [comment]
Nope! I currently have absolutely no current active missions in the Job panel.

**Comment by KimDare75** [comment]
Lines 2929-2931 from my save :

> 	"Hai Reveal: Early Arrival: Alondo: active" 0
> 	"Hai Reveal: Early Arrival: Alondo: done"
> 	"Hai Reveal: Early Arrival: Alondo: offered"
What does this mean? Does it Help?

**Comment by lumbar527** [comment]
I'm not used to the `0`, but I think all of those mean that you completed the mission.

**Comment by KimDare75** [comment]
As expected, Hmm.
Solving this would seem... complicated

**Comment by lumbar527** [comment]
Haven't tested, but I changed your position to Earth. Maybe it won't auto-complete the mission?
[Kim Dare~potential fix.txt](https://github.com/endless-sky/endless-sky/files/11679504/Kim.Dare.potential.fix.txt)

**Comment by warp-core** [comment]
When you first accept the mission, it is immediately completable, since you're at the destination and so is the NPC you need to escort, but it won't check that and complete the mission at this point because it does that when you first land before offering new missions.
When you load the save, it checks if any of the active missions can be completed, and this one can, so it completes it and removes it from your mission list.
The text you would normally get upon completing this mission is actually associated with the next mission, which would ordinarily trigger upon landing and completing this mission.
But, you didn't land, you got the mission, reloaded, and it was immediately completed, so the next mission is not available at this point. The game only checks for new missions to offer once on each landing, and you've already had that happen, and it doesn't do it upon reloading a save.
If you take off and land you should get the next mission.

This should be fixed by https://github.com/endless-sky/endless-sky/commit/fcafb869e7c5734ae94186fc09a8bad0154291bf which prevents the missions where you first encounter Alondo from being offered on Hai-home. It'll be in 0.10.2 when that is released on Steam (should be some point this month.)

**Comment by warp-core** [comment]
The thing where conditions are listed with a value of 0 was changed by https://github.com/endless-sky/endless-sky/commit/0aaa6795dd9a5d1cde352ea5b49b316b03f4267e, which will also be in 0.10.2.
It's not actually an issue. Those are just conditions that previously had non-zero values but where then set to 0 but not erased from the runtime container that stores them, and not skipped when saving the conditions.
A condition with a value of 0 is no different to if that condition was never mentioned at all and does not cause any bugs, just a some confusion when reading the saved conditions.

**Comment by ixPost** [comment]
What are all those arrows on the map?

**Comment by warp-core** [comment]
> What are those 2 arrows( the pink one and the purple one) on the map?

Those represent wormhole links. The purple one (linking Waypoint and Ultima Thule) indicates that that wormhole is stable and the pink one on the far right indicates that that wormhole is unstable and cannot be traversed without additional requirements.
