### ISSUE TITLE
Problem: Heliarch lore currently encompasses all tech and abilities used by all other factions other than Pug or Drak

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#8924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As best I can tell from statements by the Heliarch faction lead and supported by various others including at least one Dev:
- Tiers, originally meaning purely the combat capability of their ships, also means general technological knowledge.
- Heliarchs are the highest tech civilization this side of the Quarg, Pug, and Drak.
- They have 3 rings worth of Quarg technology and thousands of years studying it. 
- They have more people than basically every civilization *combined* (except for the Quarg)
- They have a post-scarcity economy that has perfect logistics, perfect analytics, and perfect prediction. (See the problems Grey ran into writing a story with a weather related disaster...)
- Arachi has argued (and people seem to be agreeing) that technological development is universal and linear, which means that everyone is on the exact same line of technological progress, and thus all higher tier civilizations automatically have any tech that a lower tier civilization has.
- Arachi has also argued that, by dint of population, they have had every idea, every thought, every dream every moment of inspiration that anyone in any lesser civilization has had. Quite literally the "if you have enough monkeys pounding on enough keyboards, eventually one of them will luck into typing the complete works of William Shakespeare", except with science and technology.
- If any civilization manages to get any insight into anything Quarg related, then by default the Heliarchs also know it. No exceptions, ever. No-one can figure out something about the Quarg that the Heliarchs don't already know.
- They have more resources than anyone, and thus have the resources to fund each and every single one of those ideas.

Extrapolate from all that, and we get:
- The Heliarchs have everything that anyone sub-Quarg  have; and they have 3 rings worth of Quarg stuff, which means basically that they have all the Quarg tech too, they just can't manufacture it yet. (But they probably have enough stockpiles that this is irrelevant for all player related purposes)
- If the Heliarchs *don't* appear to have something, that's just because they've decided it isn't worth producing something that does that thing right now.
- There's zero need for the player/protagonist at all, except as a curiosity.
- No novel development is possible for any other faction.

---

In a nutshell, the Heliarchs have been positioned as being so advanced that they render all other factions obsolete, as no faction can do anything novel or unique without the possibility that someone decides that "Hey, that's neat, let's give it to the Heliarchs too!"

Further more, as they have effectively infinite people, infinite resources, and perfect capabilities of predicting when and where they will be needed, there is no need for the player to be involved at all. As such, it is extremely difficult to foresee any meaningful story in this region. 

Lastly, I anticipate that this will strongly drive other content creator's interest in creating >T2.5 civilizations. After all, most people want to create unique things, not things that will just be imported and given automatically to an existing faction that is already the single most powerful faction the player can have meaningful interactions with.

### Steps to Reproduce

1. Read the lore on the Coalition/Heliarchs.
2. Read the conversations about their capabilities.
3. Think about how the player's protagonist can meaningfully contribute.
4. Think about how this impacts the galaxy and other factions ability to be unique.

### Expected Behavior

The expected behaviour is that:
- Factions develop along their own unique technological lines.
- There should be minimal-to-no overlap unless justified by in-game campaign overlap with said other faction.
- Unique characteristics of other factions should not be added to other factions, especially ones that already have a preponderance of power and dominance, unless there is ample and significant gameplay and campaign reason for doing so.
- Factions should have weaknesses, blind spots, and vulnerabilities.
- Factions should not gain new abilities at their starting points. If they do develop them, they should be only in the course of gameplay and stories. 

---

Desired solution: 
- Merely that the Heliarchs are confined to a single technological line that is restricted to the abilities currently demonstrated on their ships and outfits, in addition to the Quarg outfits they presumably have looted.
- Additions to the Heliarch tech are confined to their existing tech tree and development based on Quarg research, and exclusively take place in mission strings. No retroactive additions to their capabilities, and no casual side inclusions of other faction's unique abilities. If they gain an ability currently found in another faction, they exclusively do so near the end of a long mission chain.

---

Acceptable Alternatives:
- The Coalition/Heliarch are downgraded to T1.5/2.0 (from their current T1.5/2.5)
- Their population is massively reduced. At least halved, if not quartered.

---

Interesting Alternative:
- Rewind the Coalition/Heliarch factions to a point in time just *before* the revolt and war against the Quarg. Then that conflict (either side of it, really) could be the campaign in this sector. That'd be very interesting to play through. So instead of there being one unified government, there'd be three governments (each race), and depending on story choices, they'd perhaps eventually form the Coalition and the Heliarchs... Or perhaps not, depending on choices. I'd love to play that campaign.

### Operating System

Windows 10 Pro

### Game Source

Other (please describe)

### Game Version

continuous

### Additional Information

As they are currently framed, the Heliarchs ensure that no species (unless they are >T2.5) can get anything new, novel, or unique. Anything, no matter how clever a trick it is with their ships, no brilliant but subtle modification or interaction in their technology... Everything is or can be included in the Heliarch's repertoire of innovations under the current setting. Not only that, but there's decent chances that it *will* be included retroactively at some point, whenever someone decides they want to do it.

I can't emphasize enough how damaging they are to the current game. There's quite literally zero point in innovating anything at the <2.5 level because the Heliarchs will already have it, and probably have it a couple centuries or millennia before your faction even thought of it.

**Comment by warp-core** [comment]
Perhaps, instead of presenting your own highly biased view as fact, it would be useful to actually provide people with a link to the place where the discussion you derive your position from took place so they can decide for themselves if the problem you perceive actually exists.

https://github.com/endless-sky/endless-sky/pull/8521

**Comment by Zitchas** [comment]
Because some of that goes to discord comments that have been edited, or could be edited since. Others trace back to DMs that are both subject to that limitation *and* the fact that they are private, so the most I could do is post a screenshot, which can be doctored or fake with ease. So any potential "proof" is about as meaningful as those blurry pictures of UFOs.

**Comment by warp-core** [comment]
> Because some of that goes to discord comments that have been edited, or could be edited since. Others trace back to DMs that are both subject to that limitation _and_ the fact that they are private, so the most I could do is post a screenshot, which can be doctored or fake with ease. So any potential "proof" is about as meaningful as those blurry pictures of UFOs.

This sounds like a strawman argument.

That PR has 95 comments on it.
How many of those refer to comments elsewhere and, of those that refer to comments elsewhere, how many are rendered meaningless without that other information?

If you think the argument that not one of those comments is worth reading because some of them may "go to Discord comments [or] trace back to DMs" is good and reasonable, then I think the same applies here, because everything you've asserted here seems to be based on not only comments made outside of this post, but also your own interpretation of them.

If that's the case, I'm going to close this.

**Comment by MCOfficer** [comment]
This issue is... not how you heal a perceived rift between devs and content creators. If you feel like this warrants a discussion, go ahead, but... "Warning for content creators"? really?

**Comment by Zitchas** [comment]
The point is that the Heliarchs currently have zero limits, and as demonstrated by the Vivid Aether PR, people see no problem with unique abilities of other factions being added to them. It's only fair that other content creators should be aware that anything they do is eligible to be added to the Heliarchs.

Regardless of what you think of my statements above, please go take a look at the game. Heliarchs have no limits, any discussion that involves giving them a weakness gets shot down. For example, in this PR:

https://github.com/endless-sky/endless-sky/pull/6363#issuecomment-997205261

Arachi's very first problem with the premise of a freak storm? That it happened at all. Heliarch weather management is apparently so perfect that it is impossible to have an unexpected storm, ever. Not once in a thousand years.

Then they go on at length to talk about how rich the Coalition is, enough so that they can run a make-work program to coat entire *rings* (eventually) in solar panels for no purpose other than to do so.

specific quote:
> Am I saying the Heliarchs/Coalition can't fail like that? Well, yes, that's the point of advancing as a civilization, you get progressively better at not messing up something you figured out before.

Then later on in https://github.com/endless-sky/endless-sky/pull/6363#issuecomment-1002835589
> Because they have the time, money, resources, and are willing to put in the effort to effectively null the chances of something like this happening

---

Yes, it's a tad overdramatic but that is the level of importance I view this as. With the Heliarchs as currently framed, I see no point in spending any effort whatsoever to create anything novel in any other faction. They deserve to know that anything they do can and may well be just copied over.

**Comment by Amazinite** [comment]
> With the Heliarchs as currently framed, I see no point in spending any effort whatsoever to create anything novel in any other faction.

Except that's not at all what's actually happening here. The Heliarchs being capable of building craft which can withstand high pressures, which as noted is something that even humans today can do, does not then imply that the Heliarchs can do everything and anything. It does not imply that there is only a linear technological progression, only that high pressure craft are low on the progression tree, or in a section of the tech tree that is reasonably shared between all/most factions. 

As for #6363, that's still an outstanding discussion, and should in no way be taken as canon one way or the other.

**Comment by Zitchas** [comment]
Also, just for the record, I have no problems with Arachi. They're doing the best they can with the material they started with. The bulk of our arguments boil down the above arguments about limits; and fundementally, all our arguments have boiled down to "The Heliarchs don't have any."

**Comment by Zitchas** [comment]
> As for #6363, that's still an outstanding discussion, and should in no way be taken as canon one way or the other.

I'll believe it when it gets reverted to closer to the original story and the Heliarchs actually *do* get blindsided by a storm and the player actually *is* essential to solving it.

In any case, it's examplary of the way most of mine and Arachi's discussions go, and so far, most people seem to side with that.

There's enough lore baked into the game about the Heliarch's technology, resources, and population, though, and that's something that has to be dealt with.

**Comment by Hecter94** [comment]
> In any case, it's examplary of the way most of mine and Arachi's discussions go, and so far, most people seem to side with that.

This is a community project after all, if most people seem to agree on a specific point, that's generally the direction it will go.

**Comment by Zitchas** [comment]
We have yet to define what that means, but so far, writing story by committee is going very poorly.

**Comment by Hecter94** [comment]
> so far, writing story by committee is going very poorly.

I'm sorry you feel that way. I don't agree, however. 
Everything that makes it into ES only does so after thorough community feedback and critique, ensuring that it is high-quality material and ensuring that the product we're providing is as best as it can be. "writing story by committee" is exactly how we've achieved that thus far, and how we will continue to do so, as it's one of the greatest strengths of this project as a whole.

**Comment by Zitchas** [comment]
No, you're contrasting reviewing with writing. 

The review process, with mandatory changes required by the writing and grammar editors, and feedback on feel and impact from everyone else.... That's awesome. It's great, and as you say, does wonders for quality. I really enjoy having that.

When everyone gets involved in lore and trying to actually write the story, though.... That's the point of failure. People trying to nail down lore and world build before the writers have finished writing their stories is putting the cart before the horse. If the lore doesn't fit the story, then the lore is bad, end of story. Quite literally. It doesn't matter how consistent our lore is, how perfectly high quality our balancing is, if there's no story. 

So yeah, our quality might be awesome, but if it's all lore and no story.... Well, it's a nice scene, too bad it goes nowhere.

**Comment by Arachi-Lover** [comment]
Suppose I have to give this an answer.

>As best I can tell from statements by the Heliarch faction lead

You've constantly failed over the years to understand and represent my viewpoints and statements acurately, so.

>Heliarchs are the highest tech civilization this side of the Quarg, Pug, and Drak.

That's not someone's statement, and that's not my doing, that's been the case ever since they were added. It remains the case only because no other T2.5 or above is been added after.

>They have 3 rings worth of Quarg technology and thousands of years studying it.

Again not my doing, and again the case ever since they were added.

>They have more people than basically every civilization combined (except for the Quarg)

Yet again not my doing. Yet again the case ever since they were added.

>They have a post-scarcity economy

Yes, much like the Quarg, arguably Hai and Wanderers, though all of them at different levels and extents.

>that has perfect logistics, perfect analytics, and perfect prediction. (See the problems Grey ran into writing a story with a weather related disaster...)

No, not the case, and not what I've ever said, to you or Grey or anyone else.

>Arachi has argued (and people seem to be agreeing) that technological development is universal and linear, which means that everyone is on the exact same line of technological progress, and thus all higher tier civilizations automatically have any tech that a lower tier civilization has.

No I have never done that get it into your head and stop lying about me please.

>Arachi has also argued that, by dint of population, they have had every idea, every thought, every dream every moment of inspiration that anyone in any lesser civilization has had. Quite literally the "if you have enough monkeys pounding on enough keyboards, eventually one of them will luck into typing the complete works of William Shakespeare", except with science and technology.

Again not something I've ever said. Stop strawmanning and extrapolating to insane heights. If you're gonna make such absurd claims as you alter someone else's words to fit your narrative, maybe try and provide direct links to examples, then folks can go and see how ludicrous your lies are.
Stop lying about me, please.

>If any civilization manages to get any insight into anything Quarg related, then by default the Heliarchs also know it. No exceptions, ever. No-one can figure out something about the Quarg that the Heliarchs don't already know.

What would you know, again something I've never said. Again the insane extrapolating. Again the lies.

>They have more resources than anyone, and thus have the resources to fund each and every single one of those ideas.

Care to guess? Yup, again not something I've said, more lying.

>The Heliarchs have everything that anyone sub-Quarg have; and they have 3 rings worth of Quarg stuff, which means basically that they have all the Quarg tech too, they just can't manufacture it yet. (But they probably have enough stockpiles that this is irrelevant for all player related purposes)
If the Heliarchs don't appear to have something, that's just because they've decided it isn't worth producing something that does that thing right now.
There's zero need for the player/protagonist at all, except as a curiosity.
No novel development is possible for any other faction.

Yeah that'd all be very terrible, good thing I never advocated for any of it. You would know if you cared to read what I've actually written instead of inventing the perfect version for you to posit as insanities I've said.

>In a nutshell, the Heliarchs have been positioned as being so advanced that they render all other factions obsolete, as no faction can do anything novel or unique without the possibility that someone decides that "Hey, that's neat, let's give it to the Heliarchs too!"

Care to give an example?
The gas giant exploration in #8521 isn't one, as I've said explicitally here: https://github.com/endless-sky/endless-sky/pull/8521#issuecomment-1471199354
`There are no plans, mine or from anyone else, that I am currently aware of, to add in some manner of gas giant study or other such mission or job to the Coalition/Heliarchs that would necessitate gaslining, but I very much so want that open as a possibility.
The Coalition/Heliarchs don't have 0 capabilities in terms of going down gas giants, it's simply not the case where that's something very useful to them at present moment, with what content is in the game or is planned.`

What I can get an example of, is *you* seeing that the Heliarch ships got Ion Protection, decided that "Hey, that's neat, let's give it to the Remnant too!"

>Further more, as they have effectively infinite people, infinite resources, and perfect capabilities of predicting when and where they will be needed, there is no need for the player to be involved at all. As such, it is extremely difficult to foresee any meaningful story in this region.

They don't, none of that was ever said by anyone (save for when you claim that someone else's said it), and as far as story goes I've for years now shared the plans for the Coalitions campaigns and have been developing it with the help of many folks. Not to mention all the misc mission sets that've been added in/are being worked on for the region (not only by me).

>Lastly, I anticipate that this will strongly drive other content creator's interest in creating >T2.5 civilizations. After all, most people want to create unique things, not things that will just be imported and given automatically to an existing faction that is already the single most powerful faction the player can have meaningful interactions with.

This has absolutely nothing to do with the Heliarchs existing or not, as it was always the case that such things happened before they were ever added in.

>Read the lore on the Coalition/Heliarchs.
Read the conversations about their capabilities.

You definetly should follow that advice yourself.

>Factions develop along their own unique technological lines.
There should be minimal-to-no overlap unless justified by in-game campaign overlap with said other faction.
Unique characteristics of other factions should not be added to other factions, especially ones that already have a preponderance of power and dominance, unless there is ample and significant gameplay and campaign reason for doing so.
Factions should have weaknesses, blind spots, and vulnerabilities.
Factions should not gain new abilities at their starting points. If they do develop them, they should be only in the course of gameplay and stories.
Merely that the Heliarchs are confined to a single technological line that is restricted to the abilities currently demonstrated on their ships and outfits, in addition to the Quarg outfits they presumably have looted.
Additions to the Heliarch tech are confined to their existing tech tree and development based on Quarg research, and exclusively take place in mission strings. No retroactive additions to their capabilities, and no casual side inclusions of other faction's unique abilities. If they gain an ability currently found in another faction, they exclusively do so near the end of a long mission chain.

Find a mirror.

>The Coalition/Heliarch are downgraded to T1.5/2.0 (from their current T1.5/2.5)

lol

>Their population is massively reduced. At least halved, if not quartered.

Calling for the genocide of the Coalition now?

>Rewind the Coalition/Heliarch factions to a point in time just before the revolt and war against the Quarg. Then that conflict (either side of it, really) could be the campaign in this sector. That'd be very interesting to play through. So instead of there being one unified government, there'd be three governments (each race), and depending on story choices, they'd perhaps eventually form the Coalition and the Heliarchs... Or perhaps not, depending on choices. I'd love to play that campaign.

That's not for the game, and would be appropriate only for a total conversion.

>As they are currently framed, the Heliarchs ensure that no species (unless they are >T2.5) can get anything new, novel, or unique. Anything, no matter how clever a trick it is with their ships, no brilliant but subtle modification or interaction in their technology... Everything is or can be included in the Heliarch's repertoire of innovations under the current setting. Not only that, but there's decent chances that it will be included retroactively at some point, whenever someone decides they want to do it.
I can't emphasize enough how damaging they are to the current game. There's quite literally zero point in innovating anything at the <2.5 level because the Heliarchs will already have it, and probably have it a couple centuries or millennia before your faction even thought of it.

And to finish it off, exaggerated nonsense with no proof, lies and misrepresentation.

**Comment by Zitchas** [comment]
Thank you for answering. I appreciate that. And just for the record, I never said that you created the Coalition. I am well aware that they predate you by a long shot.

**Comment by Arachi-Lover** [comment]
Yes we're all aware you want me and the faction I chose to develop gone.

**Comment by Zitchas** [comment]
No, not you. Just the Heliarchs. The Coalition is great!

**Comment by Arachi-Lover** [comment]
If my favorite faction is retconned and changed all to fit your whims, what reason do I have to continue developing content?
If that were to happen, why would I bother working on anything, when all the planned lore and background, textwalls, world building, cultures and characters works I've put together all get flushed out because you don't like the faction?
Do you realize the opposite view, me on the Remnant, is also that that I just really despise how they're done?
It'd be ridiculous to change a whole faction based on one person not liking them.

**Comment by warp-core** [comment]
I'm closing this because the PR the author opened this based on is now merged and, frankly, it should never have been allowed to remain open this long anyway.

All it's continued presence does at this point is encourage others to open issues giving similar commentary on other things.

**Comment by Zireael07** [comment]
Hmm, tangent: could background lore/dev info/comments on factions be put on a Wiki or somewhere generally accessible so that prospective developers can find it instead of having to bug person who did the most for faction X or trawl Discord for relevant convos?
