### ISSUE TITLE
A different status overlay color for the player ship

### ISSUE THREAD

**Issue by slunken** [endless-sky/endless-sky#8955]
### Problem Description

I find it very difficult to distinguish my own ship when flying with a larger fleet, as all ships, including my own, use the same green status overlay color.

This is a problem in general, but especially in combat when all ships are grouped together. Then I find it almost impossible to distinguish my own ship and its position/rotation among the others, as the other ships are often in a tight cluster following my rotation. This often causes problems that could "easily" (which I, as a non-programmer, obviously know nothing about) be avoided.

(I know it's possible to turn off the status overlay, but I think it's a good feature - though it could be improved. I'm also aware that there's a silhouette in the HUD that indicates my ship's rotation, but it's less intuitive, as it requires keeping an eye on a completely different part of the screen in the middle of a battle, and unfortunately it is not very helpful. I often have to put my fleet in "Hold"-mode to be able to distinguish my own ship in a large group).

A BIG THANK YOU for this very entertaining and addictive game!

### Related Issue Links

I could not really find something adressing the exact same thing, but I am probably wrong.
This address issues with seeing ships when status overlay is enabled:
https://github.com/endless-sky/endless-sky/issues/7497

### Desired Solution

It would help a lot if the player ship could be marked with another color than the default green, e.g. purple or orange, or any other functional color. Perhaps even whatever the player want to use, if possible. 

### Alternative Approaches

When I think more about it, maybe a slightly thicker outline (in another color) of the player ship would do better, since another status overlay color really doesn't make the ship pop out much more, and also could interfer with the function of it.

Lower the transparency of the green color for the other ships, so that the leading ship becomes more visible.

Add a slight overlay over the player ship, or something that make it pop out a bit more.

**Comment by warp-core** [comment]
Currently, the flagship status overlay uses the same colours as the escort status overlays, but #8956 changes that.

You may also be interested in the "Highlight player's flagship" setting in the "HUD" section will provide a bright outline around your flagship in the main view, which differentiates it from all other ships.

The colour of this outline and all the colours used for the overlays can be customised either by editing the base game data (not the recommended way to do it because it'll get overwritten when updating and is not easy to revert if you need to for whatever reason, but it is much simpler to actually do) or with a plugin (the recommended way).
Once #8956 is in, you'll be able to customise the flagship overlay colours separately to the escort overlay colours.

This comment: https://github.com/endless-sky/endless-sky/discussions/8614#discussioncomment-5492338 provides some instructions on how to do this.

The default values for the status overlay colours can be found here: https://github.com/endless-sky/endless-sky/blob/02878548f4ea684aa437cabc3e9fc012e7d0a88c/data/_ui/interfaces.txt#L85-L94 (Thought, #8956 changes this by adding lines for the flagship overlay colours.)
And the default colour of the flagship highlight here: https://github.com/endless-sky/endless-sky/blob/02878548f4ea684aa437cabc3e9fc012e7d0a88c/data/_ui/interfaces.txt#L58

**Comment by mOctave** [comment]
Now the #8956 is in, can this be closed? Or is it still an issue because of the difficulties involved in setting a different colour?

**Comment by warp-core** [comment]
I think it can be closed now that's merged.
If @slunken (or anyone else) wants to propose new colours for the flagship or friendly overlay for vanilla to differentiate them from each other, this issue can be reopened, or they can open a new one. (Or, I suppose, if they're confident in their proposal, a PR.)
