### ISSUE TITLE
What was that militia woman pointing her gun at me about?

### ISSUE THREAD

**Issue by ixPost** [endless-sky/endless-sky#8963]
### Problem Description

I think that the event should be changed because:

1. The mission was not urgent for the Free Worlds.
2. She was threatening to kill me.

### Related Issue Links

None

### Desired Solution

Make her offer money or have it voluntary and not have her almost kill me.

### Alternative Approaches

IDK

**Comment by lumbar527** [comment]
You're talking about the mission where you can karate? https://github.com/endless-sky/endless-sky/blob/1306c3529190378db5c1d8eef5bac89c0e3e7848/data/human/free%20worlds%200%20prologue.txt#L1198-L1301

I guess it's a little strange, but maybe she wanted you to have to listen?

> Make her offer money...

Later you learn she pays for these missions with her own money; maybe she doesn't have much.

> ...or have it voluntary...

Like a job board mission `Sign up for the Free Worlds!`?

> ...and not have here almost kill me.
> 1. The mission was not urgent to the Free Worlds

I think it is a little bit urgent, and a they needed a merchant on board.

Also, you can tell Katya that you don't like having guns pointed at you in this option:
 				`	"Fair enough, but I don't like working with people who start conversations by pointing guns at my head. Even unloaded guns. Find someone else to do this job for you."`

**Comment by MCOfficer** [comment]
This entire thing could be preceded by you expressing interest in helping the militia. For example, you strike up a conversation with a militia officer, and he promises to pass your name around in case they need a civilian captain. Unlike in the karate scene, it's perfectly fine to have a `[Note: This decision will start the FW story arch]` during a normal conversation. And one or two landings later Katya, having heard your name, decides to put you to the test.

**Comment by Zitchas** [comment]
That could be good.

Alternatively, we could have other ways of recruiting the player. Maybe this is the route "in" via Katya, but we could have other routes in where it's Ijis or one of the other earlier characters recruits them. Perhaps even on Katya's behalf. It's been a few months since I did the early missions, but I don't think Ijis is the sort to just hang around ignoring nuclear explosions until Katya connects with him. 

We could leave this Katya recruitment being as undiplomatic and unobvious as it is fairly safely if there's alternate routes. Some ideas:
- Recruited by Ijis to help with nuclear research.
- Recruited directly by FW officers if already active in the South/Rim (ex. doing the militia missions)
- Recruited by the Andersons, either as an unwitting accomplice to get them out of the Republic, or as part of a cloak-and-daggers mission set.

The FW officers could recruit the player directly into the Katya missions, basically just an alternate start to it. Ijis and the Andersons would be an alternate route of varying lengths that would skip a few of the Katya missions, then join into it at the appropriate spot.

**Comment by lumbar527** [comment]
Great idea, @Zitchas! (FW could use some more branches)

**Comment by bene-dictator** [comment]
I've been looking at a introduction with Tomek as the guiding character, probably would occur some time after the bombings and be harder to compensate for a later start. It would provide a new angle to the Free Worlds and might encourage more people to go the Checkmate route. I'm travelling at the moment with a ton of work though, so I don't have very much written down yet, but once I get #8654 done (and maybe some other small mission PRs) I'l probably start making notes and sharing more stuff about it.

**Comment by dseomn** [comment]
So I came here to file a bug about this, but found this one while searching existing issues. In case it's useful, here's another idea I had for how to change this.

One of the main purposes of the initial Katya missions is to get the player to trust the FW, mostly by convincing the player that the FW didn't commit or condone the bombings, right? I was thinking that maybe Katya could find out how the player handles high stress situations another way without pointing an unloaded gun at the player, then the Katya missions could otherwise go the same way they do now. E.g., maybe one of the people who will later go on to be in the Wolf Pack meets the player before Katya does, and that person does the unloaded gun thing for some small unimportant mission. Then Katya hears about it, and says to the player something like "I heard about how you handled yourself with that ... mission. I thought <person> was really reckless how they pointed an unloaded gun at you, and I don't condone what they did, but I happen to be looking for someone who can handle situations like that calmly." That way Katya learns how the player handles that type of situation without the player having any reason to distrust her, and it foreshadows a bit about the type of people who are in the Wolf Pack later on (though that part doesn't have to be very obvious).

P.S. I also like the idea above of alternate paths into that mission by Ijs or the Andersons.

**Comment by ixPost** [comment]
@dseomn:
> So I came here to file a bug about this, but found this one while searching existing issues. In case it's useful, here's another idea I had for how to change this.
> 
> One of the main purposes of the initial Katya missions is to get the player to trust the FW, mostly by convincing the player that the FW didn't commit or condone the bombings, right? I was thinking that maybe Katya could find out how the player handles high stress situations another way without pointing an unloaded gun at the player, then the Katya missions could otherwise go the same way they do now. E.g., maybe one of the people who will later go on to be in the Wolf Pack meets the player before Katya does, and that person does the unloaded gun thing for some small unimportant mission. Then Katya hears about it, and says to the player something like "I heard about how you handled yourself with that ... mission. I thought was really reckless how they pointed an unloaded gun at you, and I don't condone what they did, but I happen to be looking for someone who can handle situations like that calmly." That way Katya learns how the player handles that type of situation without the player having any reason to distrust her, and it foreshadows a bit about the type of people who are in the Wolf Pack later on (though that part doesn't have to be very obvious).


I totally agree.
PS: It's very annoying when Iys says that shes a legend. This response I make to what he said is annoying because of the pointing gun mission, besides if she accidentally left the gun loaded or the bullet got trapped or something, it could have killed me!
