### ISSUE TITLE
Mission escort not following through hai wormhole.

### ISSUE THREAD

**Issue by Pshy0** [endless-sky/endless-sky#8969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In mission entitled "Unlikely Encounter", Alondo's NPC is not following me through the Hai wormhole (wormhole alpha), and stays in `Ultima Thule` instead.

### Steps to Reproduce

1. Load the provided save.

### Expected Behavior

Alondo should follow me through the wormhole, so that I can complete the mission.

### Screenshots

![image](https://github.com/endless-sky/endless-sky/assets/44928041/efd2c636-e447-433a-ae3b-06b8bc240200)

### Link to save file

https://gist.githubusercontent.com/Pshy0/e5e4bad308366b32e0eb7f1d496cd16c/raw/4440c5dfc14c6995273a0b0085f3c2a7cdb544a5/save.txt

### Operating System

Ubuntu

### Game Source

GitHub Releases

### Game Version

v0.10.2 (9aaa258)

### Additional Information

Maybe related to #5541

**Comment by Hurleveur** [comment]
Maybe he is part of a wrong government and thus doesnt have access to it

**Comment by lumbar527** [comment]
Is it the Hai government that is hostile with the wormhole? His ship is from that government so you're probably right.

**Comment by Pshy0** [comment]
The ship is of `Hai` government:
```
	npc
		uuid ea285488-44c1-4326-9117-016f3ea8c727
		fail 128
		accompany
		government Hai
```

**Comment by Pshy0** [comment]
So it should be `"Hai (Wormhole Access)"`

**Comment by lumbar527** [comment]
Yes.

**Comment by Pshy0** [comment]
I think this mission is supposed to be offered from a hai planet, before the hai reveal, so within hai space anyway. Somehow it was offered to me AFTER the hai reveal mission chain, and from the Mookcreek station.

**Comment by Pshy0** [comment]
It's an old save, I may have done most of the hai reveal missions in the previous unstable release, so maybe it's just that the conditions changed

**Comment by warp-core** [comment]
It shouldn't be possible for anyone who didn't play the original HR missions on continuous to have this happen, since they won't have any Hai worlds outside of Hai space.
These new missions could possibly be given something like: `near "Ya Hai" 100` in their source filter to prevent them from being offered on any disconnected locations that might have the Hai government and otherwise satisfy the filter.
I'm closing this since it only affects players who used the continuous build or otherwise modified their game, and isn't actually a bug.
