### ISSUE TITLE
Game crash on OSX

### ISSUE THREAD

**Issue by schlamar** [endless-sky/endless-sky#90]
After departing a planet, crash report: https://gist.github.com/schlamar/294907ae785d95b434de

**Comment by endless-sky** [comment]
Is this version 0.8.2 (the one I released yesterday) or 0.8.1 (the one from a week ago)? If it's 0.8.1, the bug may be fixed in 0.8.2.

Also, if you reload that game and depart from the planet again, does it crash again? If so it'd be really helpful if you could post a copy of your saved game file from `<your home folder>/Library/Application Support/endless-sky/saves/` to this thread or to https://groups.google.com/forum/#!forum/endless-sky . Thanks!

**Comment by schlamar** [comment]
Yes, it was reproducible but I worked around this issue by selling my new ship. So I have no save game available. This was with 0.8.1, I'll update right now.

**Comment by endless-sky** [comment]
I'm pretty sure this was the bug that is fixed in commit d78ccec, since the crash report says it happened in `PlayerInfo::TakeOff()`. That bug is fixed in 0.8.3, so I think I can close this issue.
