### ISSUE TITLE
Feature Request: Swizzle (new) in-flight planet indicators

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#900]
according to government - perhaps just the name of the planet? (i noticed hostility is reflected)

it just seems kind of boring almost always seeing blue (or green), and there's opportunity to give the player a better feel for government jurisdiction.

edit: to avoid jarring colour combos, perhaps desaturate the ring indicator somewhat (so it's a blue/green/yellow/red tinted light grey)?

**Comment by endless-sky** [comment]
Here are a few possibilities. One thing I could do is keep the existing colors but add the government name:

![gov label](https://cloud.githubusercontent.com/assets/11450262/14196576/d90bbd4a-f793-11e5-8c55-48c72dba0e6e.jpg)

Or, I could do that but also switch to using the government color if the planet allows you to land there:

![color label](https://cloud.githubusercontent.com/assets/11450262/14196577/e695cad2-f793-11e5-8472-eee4c76f1f77.jpg)

Or as you suggested, I could use the government color but "greyed out" slightly:

![grey label](https://cloud.githubusercontent.com/assets/11450262/14196581/f31474ac-f793-11e5-9514-937acc77d9ab.jpg)

The last option seems to be the least distracting, because it avoids bright colors. The "you can't land here" red is saturated enough that the player might be able to notice it's not a government color.

**Comment by endless-sky** [comment]
Here's how some other governments would look with the greyed out option:

![syndicate](https://cloud.githubusercontent.com/assets/11450262/14196691/fc64d3a2-f794-11e5-8db1-0cc864ec640f.jpg)
![quarg](https://cloud.githubusercontent.com/assets/11450262/14196696/029cb0fa-f795-11e5-9848-24cf6232ee06.jpg)
![korath](https://cloud.githubusercontent.com/assets/11450262/14196699/05a9b162-f795-11e5-83de-9fa9571c8b2d.jpg)
![hostile](https://cloud.githubusercontent.com/assets/11450262/14196701/087e2aa8-f795-11e5-8212-a56a1e530f51.jpg)

**Comment by LocalGod79** [comment]
i actually liked the hostility indicator - perhaps the second ring of the 'sickle' could remain that?

it probably means adding a second indicator for each planet (or a third/fourth, if you further separated the name/government), but if they had a different fade in/out ranges, you might achieve more of your desired 'jarvis' effect...

**Comment by Wrzlprnft** [comment]
Adding 12 or 13 small triangles as "spikes" around the circle for hostile planets?

**Comment by endless-sky** [comment]
@Wrzlprnft, how about this for restricted / hostile planets? (3 spikes means restricted but not hostile; five means hostile).

![restricted](https://cloud.githubusercontent.com/assets/11450262/14210348/9b684018-f7f6-11e5-8a4b-817bb9e5b348.jpg)
![hostile](https://cloud.githubusercontent.com/assets/11450262/14210352/9d162290-f7f6-11e5-9341-bab1168badb3.jpg)

And, @LocalGod79, here's how Tarazed looks:

![dual](https://cloud.githubusercontent.com/assets/11450262/14210357/a90f8212-f7f6-11e5-8f07-533f5cea1e24.jpg)

**Comment by Wrzlprnft** [comment]
looks good :) i personally would like it more evenly placed all around the circle, but that would intefere with that second circle, so i think it is quite fine that way. Don't forget to update the wiki, because that is somehow not as intuitive as i expected it to be. At least the difference between the two.

**Comment by LocalGod79** [comment]
i got a 'preview' (of sorts) of Tarazed when i attacked a Quarg vessel while in-system. :smile: 

perhaps three 'quadrilaterals' for "restricted", with the five triangles for "hostile" - the three triangles implies more aggression than i think is intended.

**Comment by LocalGod79** [comment]
there may be other examples of overlaps, this is in Gienah
![screen shot 2016-04-06 at 4 39 30 pm](https://cloud.githubusercontent.com/assets/16969517/14332165/404b500c-fc16-11e5-9dde-9b7985744fa9.png)

**Comment by Gkramme** [comment]
This looks really cool. It adds a level of si-fi to the game that really embraces the high-tech appeal of the game. You should add an option for desaturated or full colors.

**Comment by lehgogh** [comment]
The planet indicators look nice, but I think that the green rings around the ships seem a little excessive, especially with such large fleets.

**Comment by LocalGod79** [comment]
@lehgogh just happened to be the save that was open when testing another branch - only 20 ships, though...(40 skylances and warders and 20 banishers and quarg a-m.)

@endless-sky did you want to try to squeeze the indicators closer to the planet, or try to adjust the orbits of the satellites?

Algineb, too
![screen shot 2016-04-06 at 11 10 21 pm](https://cloud.githubusercontent.com/assets/16969517/14339471/cf72baf0-fc4c-11e5-8fae-659e6b18d449.png)

**Comment by endless-sky** [comment]
That's actually the effect I want to have - putting the indicators behind absolutely everything else, so they aren't too much of a distraction. If they're hovering on top of everything (like the status overlays) they'll be much too distracting.

The one problem I've still got is that sometimes a planet overlaps the text of the label, not just the ring, but I'm planning to solve that by allowing the labels to change orientation if necessary due to a "collision" with another planet.

**Comment by endless-sky** [comment]
As of e051a8e, the planet labels will now shift to a different side (4 different positions) if necessary to avoid overlap with other planets.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
