### ISSUE TITLE
Make fighters undestroyable with direct fire.

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#906]
With how fighter's are currently implemented they are useless. I've been thinking about this problem for a while and would love to see fighter's actually have a practical purpose in the game. What I propose would be a huge buff to fighters, making them prized as part of your fleet.

As soon as fighters are disabled, all shots should pass through them and they should take no damage unless it's indirect.."Missle AOE, etc.." That way, if a player takes the time, he can collect fighter's after the fight and use them again..Expanded on to this I think fighter's should take 1 day to fully repair after docking into your main ship. 

This would finially give fighters some purpose within the game

**Comment by endless-sky** [comment]
This would make it so that after every battle with the Republic, the system is littered with dozens of fighters and drones for the player to capture.

Also, as mentioned in several other threads, in terms of damage / cost fighters are already quite good. The only reason people don't use them more is that they're costly to replace (and of course, existing ships don't have tons of bays for them, and the one real human carrier is not sold to civilians).

**Comment by wargwargwarg** [comment]
Never used fighters yet so I may be talking bubbles, but wouldn't fighters be nearly unhittable with fixed guns due to their maneuverability ? A big warship ship can't be expected to be able to keep a fighter straight ahead to hit it with fixed guns. Something like a 0.1 probability against fighters (1 in 10 shots connects).
More, heavy turrets (laser, quad, etc), being "heavy" would track marginally better, let's assume 0.3 hit probability.  Normal blaster turrets would track 0.6 and laser turrets would track best at 0.85.

**Comment by LocalGod79** [comment]
actually, as long as you fit large enough turning thrusters, any ship can auto aim with quite deadly accuracy, regardless of the target.  the tradeoff in many cases (mostly larger ships) is, you cannot also chase.

otherwise, most shots from vanilla turrets and auto aim are ~.98 (lower in some cases, especially missiles, or Bactrians tracking clockwise), regardless of the target.

believe me when i say that there has been rigorous (read: tens - possibly even hundreds - of thousands of hours) testing in the combat balance of small vs. large ships, and yes in a fleet battle - some small ships get destroyed by big ships - but on several metrics to base a standard - crew salary, fleet worth - small ship fleets will prevail over large ones.

**Comment by jafdy** [comment]
I think @wargwargwarg meant artificially reducing fighter hit chance. Presumably to simulate fighters dodging in 3D.

**Comment by DingusShingleton** [comment]
Fighters have certainly been discussed plenty, and in fact a flat miss chance against them was one idea put forward. (One that I really like). 

Not to beat a dead horse, but now that I think about it, a major balancing factor could be reducing the weapon space of any ship that has fighters bays. In effect, the fighters are just an extension of the ships weapon capacity, rather than an expensive afterthought.

And if you think about modern aircraft carriers, they obviously lack the major firepower of their battleship brethren, but more than make up for it with deadly short range fighter craft.

**Comment by LocalGod79** [comment]
at the end of the day, there are many complaining that small ships are not strong enough, but the reality is that they are perhaps the opposite - too strong.  with that in mind, i believe that the implemented ships are very mostly well balanced (in fact, i cannot think of any changes i'd make), and cover a range that most are not aware of.

i think it's less a matter of outfit/weapon capacity, and more gun ports (not that capacity is a non-factor).  the ports are the bottleneck to damage output, and fighters add two per bay...i have long held the philosophy that fighters are merely external/expendable gun ports, which is a conversion (bays to ports) one needs to mentally make, similar to mass/heat/energy.

if you further your modern battleships/carriers reference - the battleship will shoot down many of the aircraft, but when the battleship is sunk, some will still be flying, and the carrier will likely _still_ be out of gun range of it...

**Comment by jafdy** [comment]
The main reason i don't use fighters is that I can't be bothered to restock them when they are destroyed and i can't be bothered to change there outfits to something better then they come with.

**Comment by DingusShingleton** [comment]
@jafdy Exactly, that was one of the main thrusts of my reasoning in the last fighter thread. It's just such a hassle to rebuy and reequip fighters, that having them as disposable firepower (which is about all they are now) is self defeating.

@LocalGod79 Fair point, but my overall argument still stands. Reduce the offensive capability of the carrier and boost that of the fighter (or more accurately the defenses of the fighter, because as you said it has a good amount of offense already). 

Personally, I think it's completely nonsensical that any pilot would ever consider using "expendable ships", even if they were rich enough to afford it. It just doesn't hold up when you can spend that money on a bigger ship that *isn't* expendable. Fighter bays are extremely easy to curate, since they only appear on certain ships whose other stats can be tightly controlled, so I see no reason not to make fighters really unique and powerful (again, while reducing the power of the mothership. I'm looking at you, bactrian).

It reminds me of warhammer 40k tabletop. It doesn't matter how powerful any model is, literally anything goes, as long as the point cost is commensurate with its power level. You can have an army with 300 models, or an army with 5 models, that cost the exact same amount of points. So it is with ships in ES. If a ship is spending a lot of its "points" on fighters, it loses an equivalent amount of "points" in gun ports, weapon cap, or what have you, and it remains balanced. At least, that's my opinion, I could be wrong.

**Comment by DingusShingleton** [comment]
@endless-sky Just went back to reread some earlier comments, and one thing I didn't notice: 

> The only reason people don't use them more is that they're costly to replace (and of course, existing ships don't have tons of bays for them, and the one real human carrier is not sold to civilians).

So people don't use them... because they can't use them. Either they are prohibitively expensive during the part of gameplay where they would be most relevant, or there simply aren't ships available that can actually use fighters. Neither reason involves player preference. The cheapest carriers are 4-5 million credits. Ships at that price range are often equipped with heavy lasers, but a fighter will stand against 3 heavy lasers for about 2.5 seconds before disintegrating. 250,000 credits not well spent in my opinion.

I have deep respect for your game design philosophy that balance should be achieved naturally (eg without using artificial limits. You want 100 outfit scanners? Go for it. 40 jump drives? Be my guest.) But in this case, I don't see fighters as having any real place in gameplay, regardless of how effective they appear to be on paper.

**Comment by LocalGod79** [comment]
@DingusShingleton i'm not convinced that you've given a solid argument;
you can spend virtually the same number of credits on an Aerie (with a couple of fighters) or a Corvette.  one has four external gun ports (bringing the total to two more than the other), extra weapons/outfit space that may get destroyed, and an extra turret mount which can't.  consider it a balance point that some of it's hardware can be destroyed/requires replacement for an otherwise superior fleet/ship with the same initial price point.

i believe people don't use them because the actual replacement process is a hassle - mostly the outfitting part.

**Comment by DingusShingleton** [comment]
But think about it. Let's use your example. Those ships are about the same theoretical power level... One on one, the corvette destroys both fighters in about 7 seconds (2x daggers=1800 shields/600 shield damage+600 hull/1200 hull damage). This leaves the aerie outgunned, but more importantly, from a game design perspective, what was the point of having the fighters? they deal 7 seconds of beam damage and then are destroyed. And not for nothing, but if each battle ends up costing me 500,000 credits, I don't think it's fair to say the corvette and the airie cost the same amount.

**Comment by endless-sky** [comment]
@DingusShingleton, it sounds like what you're asking for is ships that are significantly more expensive and powerful, but that can fit inside a fighter or drone bay. That's certainly doable, and in fact the next release will be introducing some new Korath ships that serve exactly that role. But the existing human fighters still serve a useful role as the cheapest possible ship that you can fit with a pair of lasers.

As I've said before, if you pit a capital ship against its cost equivalent of small ships, the small ships always win. In fact, it's not even close. That also applies for non-combat purposes; for example, a swarm of Star Barges has more cargo space and less salary costs than the equivalent cost in Bulk Freighters. That huge advantage that small ships have has been carefully balanced against the fact that replacing them is a constant drain on your resources.

If the game were suddenly changed so that the smallest ships become nearly invincible once they're disabled, their prices would need to be significantly increased to compensate. And, the end result would be that after every Free Worlds battle the player can go around scooping up millions of credits worth of fighters to sell. That just doesn't make sense to me.

**Comment by DingusShingleton** [comment]
Oh no, I'm sorry, I'm not advocating for immunity once disabled, I'm talking about flat evasion across the board to inflate fighter lifetime without boosting shields or hull.

To your point about small ships vs large ships, I think it's somewhat irrelevant since, at least for fighters, they require a carrier to be usable. In order to field 5 million credits worth of fighters, you would need at least 50 million credits worth of carrier (ten aeries). Not a fair comparison. Interceptors, sure. They are fully fledged ships with hyperdrives, and they stand on their own. But fighters are subservient to (as it stands now) medium warships at the least. What good is the cheapest ship you can fit lasers to if it can't leave the system it was purchased in?

**Comment by endless-sky** [comment]
Isn't evasion entirely equivalent to more shields and hull? That is, if a ship has 50% evasion, its survival time against enemy fire would be the same as if it has twice as much shields and hull.

Plus, evasion would add the extra complication of how it's calculated. If you calculate it every time a projectile hits the fighter, there are two problems:

1. Beams would end up flickering from frame to frame.
2. A projectile that misses a ship but still overlaps it in the next turn would have a second chance to hit it.

I think the end result would be that it would look like the collision detection was glitchy, and in terms of game play you could have the same strategic effect by just boosting shields and hull on the fighter.

**Comment by DingusShingleton** [comment]
Well I suppose it's most certainly more simple.... but I will say that I'm tickled by the idea of that one errant missile out of a huge volley hitting its mark and blowing a fighter clean out of the sky. Now *that* would be flavorful. But as you said, it's a ton more work for not much gain, when there is a much easier way to achieve it, which is really the point. But, if nobody else is on board, I'll just shut up about and create a plugin to test.

**Comment by LocalGod79** [comment]
@DingusShingleton , so for 7 seconds, the fighters are getting wiped - in the meantime, the aerie had its two forward cannons and three turrets bearing down - and doesn't have a scratch on her.  finish the job, and capture the ship, and that half mil' is pocket change...

the point is that the Aerie has a scalable attack - it doesn't *need* to deploy its fighters to be effective - they are a force multiplier - just like in real life.  if you nerf carriers as you suggest, those ships become massive wealth sinks - between crew salaries and lost fighters, nobody would use them at all.

**Comment by DingusShingleton** [comment]
preface: this got much longer than I anticipated. Sorry bout that.

> doesn't have a scratch on her. finish the job, and capture the ship, and that half mil' is pocket change..

And now the annoyance of replacing them rears its head. Whereas I could just get a bigger ship that would do the same thing without needed to find a shipyard that sells fighters. And forget about customizing them....

I'm not saying nerf carriers and leave fighters as they are ie money sinks. I'm saying nerf carriers and make fighters strong enough to actually last in battle, or for multiple battles. 

I just had kind of a crazy idea.... Ok so my premise is making fighters stronger and make carriers weaker. What if we make fighters stronger *by* making carriers weaker? Ok, bear with me. 

How can we make fighters more resilient? 

1. Make them get hit less
2. Increase shields/hull
3. Increase shield regen (or hull regen)

That third one got me thinking. 1, as MZ pointed out is really complicated so to heck with that. 2 doesn't make sense from an ingame standpoint. But 3, now we're talking! 

Here's what I'm proposing. Shield regen requires energy. Energy requires outfit space, which fighters lack. *but what if the fighter wasn't generating it?* We just implemented solar collection (thanks to me lol, funny how that works out innit. I didn't plan this I promise). So we strap solar collectors onto fighters, and use a light turret, mounted to the fighter's carrier, to blast the fighter with a beam of energy that can power an outsized shield generator. Boom! 

The fighter now can absorb much more punishment, the carrier is weaker because it is devoting turret slots to the fighters, and the range of the turret can be tweaked to maintain balance. This way, you can't send a fleet of fighters off to kill things while you hang back safe and sound, because they will be just as weak as they always were without mommy bear around to protect them.

If you take out the fuel cell and the shield generator/battery they have now, the two fighters in game have 45 tons of outfit space to work with. The only thing I can think that might be a problem is what shield generator to use, but I think that could be worked around with a specialized generator that only fits on extremely small ships. Fluff wise it could be explained by the peculiarities of the shield matrix and what happens as you scale it up. Pair that with some specialized solar panels and you are in business.

It's crazy, I know. But I think it's really quite elegant. I (as usual) have no idea how hard it would be to code a weapon that would do such a thing, so I have a strong feeling this is a pie in the sky idea. But at least I tried.

**Comment by LocalGod79** [comment]
while i love your concept, it would need to be implemented in an alien species - to implement it in human ships would require excessive retooling of the existing story content to ensure the difficulty remained constant.  that said - a species that employs exclusively carriers, fighters and drones that were tied to their own system *would* be pretty cool...

also, unless you overhaul the targeting ai, your system would *completely* negate the offensive capability of the carrier...someone has already requested an ai that targets friendly vessels when 'healing beams' were equipped - i think you were part of that convo, too...

**Comment by DingusShingleton** [comment]
Drat! I knew there had to be a rub somewhere that I was missing. Now that you mention it I do remember the healing beam issue.

 Yes, implementing it on human ships would be quite the mammoth undertaking... But I would love if the idea could come about in some way, that would be awesome! I might have to fall on the sword and actually learn how to code to make this one happen though... 

Thanks for the feedback

**Comment by jafdy** [comment]
I agree with @LocalGod79. A good way of making fighters more useful would be if you could reload them like you can with missiles.

**Comment by endless-sky** [comment]
Out of all the threads where this has been discussed, the one idea I like the most would be to make turrets take time to turn (instead of turning instantly). That would give small, nimble ships a chance of dodging turret fire even if they're up against lasers. And, it would look a lot more plausible than the lasers just passing above or below them.

There could even be an added factor where turrets track less reliably when a target is moving fast, although that might get annoying for the player if they're the one firing the turrets.

**Comment by LocalGod79** [comment]
couldn't this just be accomplished with a firing effect that delays the actual weapon damage that only the turrets carry?

**Comment by jafdy** [comment]
If turrets are given a limited turn speed then some people will go "why can't my turrets shoot fighters with auto-aim and auto-fire on?".

**Comment by wargwargwarg** [comment]
I like Michaels last proposal (turret tracking speed would mean only part of the time the turret will be aligned to hit the target or shoot towards the target).Same could be said for the ship turning speed, same kind of alignment problem. BUT this will mean a large number of background calculations that will slow down the game (I'm told this slowing became a factor of late). Think about it: 4 turrets on a ship, each with own tracking rate and at various angles at the moment, the game should calculate for each turret where the target should be to get hit with projectiles of varying speeds, also recalculate for shells in flight if the target ship changed course and so on.
I'm all for this and more, but can it be done?

Think now at a simple hit chance based on weapon type and turret tracking speed (that reply of mine 4 days ago). Probabilistic, relatively easy to do.

Plus, on the realism side, are fighter pilots morons? Why choose a career that'll end 8 seconds in the first fight, as @Dingus said earlier?!? For the same money lost, I'd hire myself a sizeable escort to get through the rough spot.

**Comment by LocalGod79** [comment]
@wargwargwarg as @endless-sky has already mentioned, "chance to hit" is not really different than just adding more shields and hull integrity.

i'm not convinced that the system needs balance adjustment in favour of small ships - more to make fighters less inconvenient to replace.

**Comment by wargwargwarg** [comment]
sorry, @LocalGod79, if you add more shields and more hull integrity, you transform the fighter into a  corvette.
Hull integrity means armor (heavy thing) and the actual hull beams to sustain various accelerations without breaking, shields also mean more machinery, bigger engines to be as nimble (more), power plant for bigger engines (even more). So, more mass = so no more a fighter.

As for how fast a fighter gets whacked by npcs, that's because the game focusses on ships and does not micromanage like a player. If it were, a fighter screen would be dropped very fast and very expensive.

Your argument, unless I'm mistaken, is that fighters act like a consumable shield, diverting away some fire for a few decisive seconds and needing to be replaced after each battle, the reasoning being that cost to cost, the fighters are well balanced. 
Setting aside the pilot issue, to make cost reasonable in the hit probability variant, add maintenance per sortie for each fighter. Look at aircraft carriers: they eat away a big part of the military budget of the countries that can afford them, because they're huge, yes, but also because aircraft are fragile nimble things that don't last long under combat stress, not to mention damage. 

So, fighter increased survivability through mobility, at high maintenance costs (-bank) and space needed for parts as well as aircraft, launching bay and so on. Unless countered, they'll be as a light  turret with extended range. To counter them, the ships would need to rearm with lighter turrets that stand a chance in tracking them.

**Comment by DingusShingleton** [comment]
@wargwargwarg What they are saying is that functionally, from a game mechanic perspective, increasing armor and/or shields is the same as adding evasion. From an in-game perspective is doesn't make sense as you say, but there is no difference between a fighter with 2x shield/hull and one that gets hit only 50% of the time, all other things being equal.

That's why I suggested giving fighters a much larger amount of shield generation, because I think it's much easier to explain from an in-game perspective while achieving similar results. Especially with the introduction of shield efficiency as another level to pull, I plan on making a plugin that rebalances fighters with these things in mind and seeing what happens.

**Comment by LocalGod79** [comment]
no, my argument is that the cheapest gun port with enough outfit space to shoot something out of it is on fighters - that they happen to also give your opponent another target to divide their offensive focus is just more bonus (fighting a war on more than one front is generally bad).

further, their expendable nature is balance point to their value in combat (like missiles or torpedoes vs. guns), and for the moment, the additional hassle/effort of replacing them is making them "underpowered".

**Comment by mdsmestad** [comment]
What if fighter's were smaller, cheaper, and more numerous. I was thinking, that perhaps you could make fighters smaller and cost only a little more than a missile (mention something about mass manufacturing as an excuse) and make ships able to hold more like a dozen fighters. I think the bacterian, for instance could hold about 18 tiny fighters an it wouldn't look to strange.w

**Comment by LocalGod79** [comment]
@mdsmestad are you going to rebalance the fw storyline difficulty as well?

**Comment by mdsmestad** [comment]
@LocalGod79 Good point

**Comment by Pointedstick** [comment]
@endless-sky
I hear what you're saying about small ships being fundamentally balanced by various metrics, but the ultimate problem that we're all dancing around is that fighters aren't _fun._ So nobody uses them, no matter how balanced or even potentially overpowered they may be in mechanistic terms. They're no fun.

**Comment by LocalGod79** [comment]
@Pointedstick you're no fun.  i have no suggestions on how to fix this.

fighters being "no fun" might be resolved with "reload", and might not - but it's a suggestion rather than just a complaint.

i have fun with fighters, and yes - flying all the way back to Polaris to unpark some more chasers is a bit of a pain, but they're vicious in a fleet of Bactrians, and i didn't really pay for them, so...*fun*

**Comment by wargwargwarg** [comment]
Thanks for the pro and against arguments.
I find this consumable fighter approach as , well, not repulsive, but close. Too far from reality for even a game about the future. Wastefull. Inhumane. Might work for drones, much weaker, made between battles in your ship from a cargo hold of parts. Even there, chance to hit is the pivotal point.
Balance is needed but inline with a bit of reality. Don't make fighters corevettes and don't make fighters missiles, just to avoid straightening something gone astray.

**Comment by DingusShingleton** [comment]
>Their vicious in a fleet of bactrians

This right here is my major beef though. A fleet of bactrians? Literally the most jacked ship in the game? 5 bactrians is like 125 million credits. At that point fighters are just simply an afterthought, if a fun one. I also had fun with fighters, also in my fleet of 40 bactrians, but it was just because I was bored and had a billion credits in the bank. I think @Pointedstick hit the... stick on the head. Regardless of how balanced and good fighters are on paper, I just don't think they add up to a viable combat strategy that the majority of people would consider.  Which is what really counts at the end of the day. 

At the very least there should be a simple way to repurchase and maintain fighters with the modifications you prefer. That would alleviate the main hassle of trying to use them as a primary strategy.

**Comment by LocalGod79** [comment]
okay, fine - a fleet of Aeries (4x per ¢Bactrian) with Chasers are *even more* vicious...

i think those of us that have been reading and absorbing the back and forth agree that the first step in this balance issue is to make fighters more available, and offering variety of loadout variants (which should be easier after the Marauder/variant commits)

@DingusShingleton you seem to have some opinions on some possible default loadouts of the fighters - would you create a save with a couple of additional loadouts for the Lance and Dagger, and post the save file in the content creation area of google group?
https://groups.google.com/forum/#!forum/endless-sky

**Comment by Wrzlprnft** [comment]
What i always found sad abut fighters is that they don't fit for a flagship. Would be fun if a player who has a fighter selected as a flagship can change to the carrier while docked and back to the fighter when deploying, but goes back to the carrier if the fighter is destroyed. And yes i know this is quite the different topic.

**Comment by LocalGod79** [comment]
indeed - that fact alone makes a case for fighters and or bays as outfits, coupled with "reload", there's a case building...

**Comment by LocalGod79** [comment]
#939 if anyone is interested

**Comment by LocalGod79** [comment]
@DingusShingleton while you're outfitting the fighters, please do a couple of sparrows, too (leave the hyperdrive in) - i've made a new fighter out of them.

**Comment by DingusShingleton** [comment]
Ok, I am working on some variants now. One thing is that with the basic human outfits it's a little harder to work with. Aliens have some really small, useful stuff. One thing I am thinking is that a Hai-equipped fighter would be awesome, maybe with an S-270 regenerator and a pulse cannon. It actually could tie into #928, and be unlockable if the player agrees to transport a bunch of those outfits to wherever. Probably the finch actually. I think tarazed would probably be mosts down for equipping it's fighter with hai tech, but maybe not. Either way. I'll keep tinkering.

**Comment by Alkallid** [comment]
For the mothership recharge idea, how about an energy-draining system outfit that recharges _all allied fighters in a vicinity_ instead of beaming one? It'd weaken with more fighters, of course. 
For turret turn speed, all non anti-missiles(or even?!) could have a turn speed attribute, which is divided by their mass like steering systems. Or maybe a bit less, for the base. However, that might add turret turn heat and power costs...

**Comment by LocalGod79** [comment]
#939 is ready to go, and i believe is the first step to making the true power of fighters more obvious to the player.

after that, a new pull for a Syndicate fighter. (so that it's even easier to restock lost ones, pretty much anywhere in human space)

after that, we need to decide whether adding a "reload" prompt at shipyards for fighters (when bays are present and empty), or more variants (with different outfit load outs) is the best option (i think both is overkill)
