### ISSUE TITLE
Additional Kestrel Variants

### ISSUE THREAD

**Issue by Hecter94** [endless-sky/endless-sky#9168]
### Problem Description

When the Kestrel was originally added **[eight years ago](https://github.com/endless-sky/endless-sky/commit/660b57d659c4d0fc0b86529e68362958a0e6552f)** it was a unique mission reward with an interesting mechanic associated.

The ability to select between the different Kestrel variants was, at the time, and still is, a source of much debate over which variant is the best or which allows for the most interesting builds.
To this day, we still have nothing else like the Kestrel. 

However, Endless Sky has seen a lot of improvements in the past eight years. It is a much bigger game with a lot more to do and a lot more mechanics to play with than it was back when the Kestrel was first added, as such I think the Kestrel should also be expanded with the addition of new variants to maintain it as an interesting, unique and valuable reward.

### Related Issue Links

Of the 18 currently open issues and 63 closed issues that mention the Kestrel, I could not find any relating to additional variants. 
I found several mentions on the Community Discord and Steam, but nothing that disqualified the idea. 
https://discord.com/channels/251118043411775489/935734693008138270/959916829302738974
https://steamcommunity.com/app/404410/discussions/0/135511757694932519/

### Desired Solution

Here are a couple of general ideas for potential new variants, simply as a starting point:

Scout Kestrel  - To fly deep into hostile/uninhabited territory and make it back alive.
+HP
+Fuel
+Ramscoop
+Resistances?
-Weapons Capacity?

Carrier Kestrel - To function as a light support Carrier
+Fighter Bays
+Drone Bays?
+Turrets?
-Engine Capacity?
-Guns?

Courier Kestrel - For transporting cargo/passengers
+Cargo
+Bunks

### Alternative Approaches

Alternatively, rather than adding new variants to the Kestrel itself, we could have additional ships later in the Endless Sky story that functions *like* the Kestrel—allowing the player to pick between several different variants of the same ship based on what they prefer and what the ship's manufacturers can provide. 
Higher-tier races could offer additional attributes and functionality for their special ship that humanity wouldn't reasonably be able to provide, such as built-in cloaking or jump capabilities.

However, I prefer keeping the Kestrel as a special reward and maintaining its uniqueness as the only ship where the player can decide its final stats. I prefer adding new variants to the Kestrel over new ships that function like the Kestrel. 

### Additional Context

We've said we want to avoid adding much more to Humanity, as they're already somewhat bloated regarding ships/outfits. However, as this is simply adding new options for the final version of the Kestrel and not adding more Kestrels, I think that will be fine. 
In the end, only one Kestrel will be available to the player; they simply have a bit more choice about its final stats.

**Comment by Amazinite** [comment]
I think a carrier Kestrel is the only one that really makes sense to do, and is actually something that's been requested a few times in the past. The scout and courier variants don't seem like they bring anything new to the table, as +HP is what the shields Kestrel has, which you could already outfit with extra fuel and ramscoops, and a courier variant could similarly be outfitted from one of the existing variants.

**Comment by Saugia** [comment]
I've done the updated models for the Kestrel using visual queues for each variant, so I can make one for a carrier version as well. With that said, there's a bit of questions to be had - Would it have racks for fighters underneath the wings like Skeins? Would it have small bays like an Aerie? Would it remove guns on the wings either for the first option, and/or have a turret mount on top of each wing instead of them? Etc..

As for the other variants, yeah, they don't really make sense to separate since you can just do that with the Kestrel anyways.

**Comment by Hecter94** [comment]
> I've done the updated models for the Kestrel using visual queues for each variant, so I can make one for a carrier version as well. With that said, there's a bit of questions to be had - Would it have racks for fighters underneath the wings like Skeins? Would it have small bays like an Aerie? Would it remove guns on the wings either for the first option, and/or have a turret mount on top of each wing instead of them? Etc..

I was thinking it could have +3 fighters; give it one more than the Carrier, but no drone bays as those are generally restricted to the Navy. 
One thing is that, on the existing model, I can't see where exactly the existing bays are. It doesn't seem to have external *or* internal bays. 
![image](https://github.com/endless-sky/endless-sky/assets/15916854/5ac9cbef-fa99-4e87-9866-a456fe9ad4bf)

You could argue that these are bays:
![image](https://github.com/endless-sky/endless-sky/assets/15916854/514a678b-6ba6-4cbd-b1fc-4eb3a42d1fb5)

But then some models block those:
![image](https://github.com/endless-sky/endless-sky/assets/15916854/3145ddc6-76b7-4c90-bbe4-c2c1bd65105f)

So how exactly do the other Kestrel variants hold their fighters?

**Comment by Saugia** [comment]
Ah, I forgot the original Kestrel had 2 bays. The idea is some sort of under-belly bay/racks for the fighters that isn't visible in the top view/thumbnail (and therefore not modelled on the ship). The Kestrel is explicitly a reference to EV's Kestrel, and you can see that example here:
![kesbay](https://github.com/endless-sky/endless-sky/assets/93169396/34fd24c9-85be-4eb0-ac9a-d11c601fec07)

**Comment by Zitchas** [comment]
I don't think we need additional variants for things that can already be done with regular outfitting for the Kestrel... But a carrier variant? That sounds great, and definitely an interesting option.

And yeah, the fighter bays were on the belly. Somewhere there was once a picture from below with two lightnings dropping out of it, but I can't find it right now.

**Comment by Saugia** [comment]
I will get to work on a carrier variant.

**Comment by Hecter94** [comment]
We should probably nail down exactly what the changes will be before we make the sprite for it. 
+2 bays? 3? Drone bays? More shield? more turrets?

**Comment by Zitchas** [comment]
Depends what the goal is. Is this a proper carrier? Or is it a Kestrel that happens to be more carrierish?

The general expectation from most players is probably going to be that it's the Kestrel, just with more bays. So it's probably going to have all the same elements that are consistent between the first three versions, but is going to get an additional set of bays. I'd probably go with +3, or even +4 bays. With that sort of additional firepower, though, it probably shouldn't be getting much else anywhere. Perhaps some additional outfit space to hold storage racks.

**Comment by Hecter94** [comment]
We're thinking -2 guns, +3 bays.

**Comment by Zitchas** [comment]
Removing guns, even better. Although if removing guns, I'd definitely be inclined to go with +4 or more bays.

**Comment by Saugia** [comment]
At the moment, we're considering:

+2/3 Bays, -2 Guns
+2/3 Bays, -2 Guns, +1 Turret
+4 Bays, -2 Guns, -2 Turrets
+2/3 Bays, -2 Turrets

I'm mostly leaning towards just losing 2 guns for the bays. I don't think it should gain anything elsewhere besides the bays, since they're the main feature.

Initially I thought 4 more bays is quite a bit, but I was thinking of the Aerie at the time. Compared to the Carrier, which has 6 + 4, I think the Kestrel having 6 can be okay, maybe, but I'd like more opinions. 

Some test art in the process:

Test with the Aerie bays
![image](https://github.com/endless-sky/endless-sky/assets/93169396/41d9a771-e50a-428d-be79-21342e68a073)

Relocation to inbetween the guns
![image](https://github.com/endless-sky/endless-sky/assets/93169396/09deb673-6846-4348-b89e-7ba81dc014ac)

Mirrored bays
![image](https://github.com/endless-sky/endless-sky/assets/93169396/e5556921-595e-4752-9724-5d4bb4ebe300)

Keeping the top bays (most popular, since the bay additions are much more visible on top view here)
![image](https://github.com/endless-sky/endless-sky/assets/93169396/de06a7fc-311a-4557-82ae-11d8ec7674ba)

**Comment by lumbar527** [comment]
I like the mirrored bays image.

**Comment by Hecter94** [comment]
If we're making a carrier variant, I say we go all-in. 
+4 bays, -2 guns, -2 turrets. 
Using the mirrored bays image, with the extra struts and the bridge.

It will struggle to use up its weapon capacity in most normal builds, but the extra space can go towards extra shield/hull generation, extra battery power, or extra ammo storage to better recharge/repair/rearm its fighter complement.

**Comment by Zitchas** [comment]
It's also worth considering that the player is likely to get this after they've already got access to the Bactrian, the Dreadnought, or the Carrier. Possibly also the Ibys or Solifuge. If they're opting for a Carrier variant, then it's got to have something comparable to these other options.

Turrets are generally more important to Carrier type ships, as that tends to be where artillery and AAA weaponry are located; so my suggestion would be that - if we want to remove 4 hardpoints, then I'd suggest doubling down on guns and having it be +4 bays, -4 guns.


As for the images... I love the Kestrel's streamlined top surfaces and the way it has everything tucked under the wings. So that's my personal favorite. That being said, the version with the mirrored bays on top of and underneath the wings also looks promising. Honestly, though, even one of those bays ought to be able to fit 2 fighters by themselves. No need to feel forced to have 4 bays for 4 fighters.

**Comment by Zitchas** [comment]
That's a fair point, however:
a) The Kestrel is not an early-game ship.
b) Our combat environment is kind of a mess, and part of that can be attributed to the fact that most stuff goes in a gun port. Gun? gunport. Missile? Gunport. Torpedo? Gun port. Giant nuclear missile? Gunport. Funky thing that sprays fuel into space and lights it on fire? gunport. Everything goes in gunports. This is a problem, as it leads to everything being gun oriented, and if everything is gun oriented, everything needs to spin like a fighter in order to *use* those gunports. The solution to this starts with moving our heavy capital ships *away* from depending on gunports. It's not the full solution, but it is a part of where the solution starts.

**Comment by Saugia** [comment]
> As for the images... I love the Kestrel's streamlined top surfaces and the way it has everything tucked under the wings. So that's my personal favorite. That being said, the version with the mirrored bays on top of and underneath the wings also looks promising. Honestly, though, even one of those bays ought to be able to fit 2 fighters by themselves. No need to feel forced to have 4 bays for 4 fighters.

I will go ahead and say that there isn't much concern of whether or not a bay visually fits a fighter. In this image, these bays are, somewhat smaller/comparable to the Aerie's underwing bays. Those carry one fighter each, but something Derpy and others, myself included, have said that we could see the Aerie having 4 fighters instead of two (but we wouldn't edit the model for that). So that could apply here as well, since scale is not something we're necessarily modeling around. It could just have the two visual bays for the (additional) ones, be it 2 or 4 fighters.

Removing guns vs. turrets comes down to more balance than it does preference I feel. Regardless of the options, removing 2 guns is probably a given. Removing 2 turrets, or 2 guns beyond that, comes down to the idea that adding 2-4 more fighters is also technically adding several more gun mounts to the overall package. I agree that carriers generally focus more on turrets than guns, but although the Kestrel is a larger Heavy Warship, I also see merit that it is known to be a gun-heavy ship, and it would feel odd that it lose guns for the sake of not losing turrets.

Regardless, I say we start out by just losing the 2 guns, and plan from there. I'd like to do some combat tests at that point. One with -2 guns and 2 additional fighter bays, one with 4.

**Comment by Zitchas** [comment]
Sounds like a good starting point. I'd certainly be happy with just a -2 guns & +4 fighters. The Kestrel struggles enough as it is to be a really relevant ship in the mid/late game as it is (weird esoteric builds like the 12 flamer aside, anyway...), no need to go out of our way to handicap it.

**Comment by Saugia** [comment]
That is true, though what I want to avoid is this variant being particularly strong. The Gun variant can be seen as the most popular, but 4500 additional defense or more choices for engine speed are not to be overlooked, and therefore, I'd like to keep it in balance with the other variants.

**Comment by Hecter94** [comment]
> a) The Kestrel is not an early-game ship. 

After https://github.com/endless-sky/endless-sky/pull/8578 I've seen several people who, on subsequent playthroughs, grind out the Kestrel very early so they can use it to do the FW campaign. 
I also rarely see anyone continuing to use it once T2 ships become available.

With that in mind, and the fact that its stock build will also be using entirely pre-FW tech, I'm primarily balancing it around the idea that it will generally be equipped with Human/Hai tech, with maybe a bit of Korath/Remnant sprinkled in.

**Comment by Zitchas** [comment]
That's true. The joys of a open galaxy. There's people that go to extreme lengths to do the FW campaign in a 512 or a KIV too. Lots of people do the FW in an Albatross, and I've seen a few reports of using a Peregrine to great effect. Personally, it's easier to accomplish starting the FW campaign in a KIV than it is to get the Kestrel.

**Comment by Saugia** [comment]
Alright, we've decided that -2 guns, +4 bays is the plan. I'm thinking about doing a stream next weekend of me modeling it as well.
