### ISSUE TITLE
bunk room thumbnail seems misaligned

### ISSUE THREAD

**Issue by flowers9** [endless-sky/endless-sky#9195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The bunk room thumbnail doesn't seem aligned to the grid the same way as other outfits (such as the outfit expansion or cargo expansion).

### Steps to Reproduce

Go to the Outfitters and take a good look at it.

### Expected Behavior

Should be aligned to the grid like the other outfits.

### Screenshots

Notice how the bottom right seems raised from the grid floor, unlike the bottom left.  Likewise with the upper right versus upper left.
![Screenshot from 2023-08-17 11-13-43](https://github.com/endless-sky/endless-sky/assets/11161996/4061ffc0-4274-4998-a6d7-51146c3e1db1)

For comparison:
![Screenshot from 2023-08-17 20-43-46](https://github.com/endless-sky/endless-sky/assets/11161996/919becd2-8999-44a5-894d-49a86af0562d)

### Operating System

Ubuntu 22.04.3 LTS

### Game Source

Built from source

### Game Version

42e7b96 + my PRs

**Comment by mOctave** [comment]
I'm not sure this is misaligned, more _differently_ aligned. It matches up perfectly with the left "wall" of the outfitter grid (and the expansion), which it wouldn't if it was re-centred.

**Comment by flowers9** [comment]
The problem appears to be a rotation, not a translation.  So, yeah, recentering wouldn't do much.

**Comment by Saugia** [comment]
It's not that it's misaligned, it's more so that the parts that would be there are cut out for the purpose of the visual.
![image](https://github.com/endless-sky/endless-sky/assets/93169396/96b7ce5b-c3f1-4481-8cad-6d8fe5bc3331)
You could argue that that means it could be centered more, but I don't think that's necessary as it'd make it oddly aligned compared to the other "internal room" outfit alignments.
