### ISSUE TITLE
The scan speed cap feels unintuitive (and is too easy to hit)

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#9201]
### Problem Description

I was looking at #8231 to see if after the merging of #8288 whether the added number of scanners was overkill. Instead of downgrading the LP144a to a single LP072a, I downgraded to an LP072 and an LP036a, providing only 10 extra tons for scanners. With this, I bought 4 outfit scanners and 2 cargo scanners, bringing the Gunboat's total to 5 and 3. I then scanned a Carrier and observed that the scan speeds were the same. Thinking it might've just been a coincidence in the ratios between the scan speeds and the Carrier's size, I added 10 more outfit scanners but kept the number of cargo scanners at 3. The scan speeds were still the same. Turns out I'm hitting the scan speed cap, and it only took a relatively small number of scanners to hit it. So I decided to lower the number of outfit scanners while keeping the number of cargo scanners the same to see how few outfit scanners I needed to hit the speed cap (using the speed capped cargo scanners as a frame of reference). With only a single outfit scanner I was hitting the scan speed cap when scanning a Carrier.

Not only does it seem unintuitive to me that adding more scanner wouldn't improve your scan performance due to this cap, the cap also seems far too easy to hit.

### Related Issue Links

#8288 caused the scan speed to be a minimum 2 seconds. No matter how many scanners you have, you can't get any faster.

### Desired Solution

Instead of the cap being a hard cutoff, having it be something that is approached with more scanners being added. Generally, the way things are balanced in Endless Sky is either they provide a flat benefit (most things), or they provide diminishing returns (such as with ramscoops). Rarely if ever is there a hard cutoff beyond which a higher attribute value provides no benefit. If the diminishing returns are great enough, then the hard cap could be only a single frame, with that cap just never being reached in practice.

### Alternative Approaches

Just go back to the drawing board again for scanning. ¯\\\_(ツ)_/¯

**Comment by Hurleveur** [comment]
The integration test with 10k scanning power requiring more time than it used to was indeed an indicator of smth wrong if you ask me, I dont see why we shouldnt be able to scan faster than 2 seconds
I dont see why we should have a lower margin at all actually, just remove it? Spamming 100 scanners should instantly scan smbd

**Comment by Zitchas** [comment]
I don't think 100 scanners should instantly scan anyone; but yes, I agree that there shouldn't be a hard limit. I do think 2 seconds being the point where the diminishing benefit starts getting fairly steep is fairly good, though.

**Comment by UnorderedSigh** [comment]
The scanning that was merged was tuned around typical human ships taking about 3-7 seconds to scan in non-fast-forward mode in practical conditions. With the 2 second clamp, it won't take many more scanners to hit the 2 second minimum time.

> I do think 2 seconds being the point where the diminishing benefit starts getting fairly steep is fairly good, though

Scan time is clamped between 2 and 10 seconds. It is not a "diminishing benefit." There is zero benefit after you reach 2 seconds.

> I don't see why we should have a lower margin at all actually, just remove it?

The AI and the player have the same scan formula. Do you want to scan the AI in one frame? Well, that means they can scan you in one frame. Smuggling will be impossible then.

I think the best solution is a function that asymptotically approaches 0 seconds, rather than a straight-up linear one. Then you don't need to clamp it. Adding more scanners will speed things up, but you won't get one-frame scans.

**Comment by Quantumshark** [comment]
> The AI and the player have the same scan formula. Do you want to scan the AI in one frame? Well, that means they can scan you in one frame. Smuggling will be impossible then.

This ignores the fact that we can control what loadouts the AI has. We can just not give the AI any ships with so many scanners that they can scan you in one frame, and then that isn't an issue.

I don't think there should be a cap on scan speed. If you want to install an absurd number of scanners to scan things quickly, you should be able to do so.

**Comment by Zitchas** [comment]
Seems like a situation for a two-pronged approach. On the one hand, having a setup with decreasing returns so that it is possible to approach but never reach 1 frame scans seems like a good thing.

On the other, we should take care to not setup AI ships such that they have unreasonable scanning capabilities unless needed for the story. That being said, the only time I can think of an instantaneous scan being reasonable is for situations where it's more of a "If the NPC is ever within X range of the player at all, they trigger consequences" sort of thing.

That being said, some parameters might be in order for what the test for reasonableness is. If a big commercial scanner (as in, a setup designed to quickly scan bulk freighters) can scan a fighter in a frame, is that unreasonable?

I'd probably put the target "approach but never achieve" point at about 10 frames for a scan, personally; although for things like the above scenario, instantaneous would be a useful option. I'm not sure that's really scanning, though, and more just using the scanning mechanic to achieve something different, kind of like abusing ships and weapons to make timer ships.

**Comment by UnorderedSigh** [comment]
> This ignores the fact that we can control what loadouts the AI has. We can just not give the AI any ships with so many scanners that they can scan you in one frame, and then that isn't an issue.

Yes. I suggest a non-linear dependence after about 2 second scan time. An exponential drop-off seems apt. It'll asymptotically approach one frame instead of linearly. I was waiting for someone to respond to my prior post before working on it.

(This is essentially the same as what @Zitchas suggested, but more specific. I meant to post it yesterday, but I got distracted and never pressed the "Comment" button. Sorry.)

**Comment by UnorderedSigh** [comment]
I've plotted four options:

1. Minimum scan speed hard limit of 2 seconds.
2. No scan speed adjustment.
3. Exponential drop-off below 2 seconds.
4. Likewise, but with a different exponent.

The plots show how the scan time reduces with more outfit scanners. Each plot is for one hypothetical ship. That ship takes a certain number of seconds to scan at point blank range by a single outfit scanner. I plot up to 20 outfit scanners.

#### The Hai

Hai use more scanners and faster ships. This means they scan from a longer range, with a faster scan rate, using ships you cannot evade. On these plots, assume five (5) human scanners in a nominal Hai space situation.

<details><summary>Ship that takes one half (1/2) of a second to scan with one scanner.</summary>

### Ship that takes one half (1/2) of a second to scan with one scanner.

Representative of early game smuggling in human space. Having less than 2 seconds to get away is dubious. Exponential drop-offs provide a more reasonable single-scanner scan time. Also, they let players scan such ships quicker by spamming scanners.

![scale-half-second](https://github.com/endless-sky/endless-sky/assets/116329264/0e78a91f-2c4d-45c9-a1f7-896c3666c627)

</details>

<details><summary>Ship that takes five (5) seconds to scan with one scanner.</summary>

### Ship that takes five (5) seconds to scan with one scanner.

The effect is noticeable for mid-sized cargo ships.

![scale5s](https://github.com/endless-sky/endless-sky/assets/116329264/4e3aa2e6-2068-478c-8b8a-a23d61b593b4)

</details>

<details><summary>Ship that takes ten (10) seconds to scan with one scanner.</summary>

### Ship that takes ten (10) seconds to scan with one scanner.

The differences are insignificant for especially large ships. You cannot reach a 2 second scan time with 20 scanners regardless of the method. That's the ship size dependence at work.

![scale10s](https://github.com/endless-sky/endless-sky/assets/116329264/c04e3c6e-862d-4b54-bf9b-838d1e9a0efb)

</details>

**Comment by ziproot** [comment]
Are you sure the scan cap is two seconds? All my testing suggests that it's currently ten seconds. This includes:
-Hai surveillance ship on numerous ships in Syndicate space, including sparrow, protector, etc.
-The ship from the "unnerf scanning" PR on both the mission targets and a navy gunboat that was trying to scan me
-The navy gunboat on said ship
-A specialized scout ship which has 99 cargo scanners on a disabled star barge, and several wasps, sparrows, and quicksilvers near me (see uploaded save)

[John Doe.txt](https://github.com/endless-sky/endless-sky/files/13366517/John.Doe.txt)
