### ISSUE TITLE
A way for ships to produce more ships, possibly with weapons

### ISSUE THREAD

**Issue by RisingLeaf** [endless-sky/endless-sky#9216]
### Problem Description

Because someone posted on my closed PR for weapons shooting ships I saw that there were a lot of up votes on a comment that disagreed with closing it. While I see the point in closing it, I think it might be good to talk about alternate approaches.

From Wyrdean on #7750

> Allowing weapons to produce ships would be extremely useful for certain complex weapons, for example, it'd reduce a weapon in my pug defense plugin to less than 50 lines, from 800.
> 
> More specifically, it'd simplify generating a temporary "mothership" that itself generates "lancers" that shoot gridfires at foes
> The reason for having this is drones that are infinitely and easily replaceable, which is a major issue they have currently.
> 
> Edit: Additionally, it adds potential for "hologram" ships generators that draw fire off of the main ship, ammo-based deployable drones that are permanent once created (alleviating much of the replacing drones issue), and many more things besides.
> 
> To go even further, there's no other classes that make sense for these use cases, as they still need to be able to use range, ammo, and other such systems in order to be properly used by both the player and ai.

### Related Issue Links

#7750

### Desired Solution

To be determined, one approach was given in #7750

### Alternative Approaches

N/A

**Comment by Hecter94** [comment]
It doesn't look like there were any objections to the idea of producing new ships, just the implementation of it. 
> I think that having weapons fire anything other than a projectile is a misuse of the Weapon/Projectile classes. If we want some way to produce new ships, we shouldn't hijack these classes to do that.

So, probably what needs to be talked about is how to implement it. Not necessarily an alternate approach.

**Comment by Ferociousfeind** [comment]
As I've said here and there, from time to time, I think Derpy has a point that the _specific_ implementation is a little hacky. Instead of integrating with projectile spawning mechanics, it completely overrides them, and inherits some select traits from the weapon definition. (Obviously some are moot, what does "shield damage" on a fired ship mean?)

I would rather have ships spawned work like submunitions, which would make the system more inline with pre-existing systems and also more versatile. (Now, "shield damage" means something, it's a regular projectile which despawns and then spawns a ship and/or other submunitions in its stead. "shield damage" stops meaning anything when the projectile is dead, and that does not change when it specifies a ship to spawn.)

Like, for example, a launched kill-murder drone that has no allegiance and will rip into the first thing it sees, being first dormant for a set amount of time (a projectile with no homing or turning, which spawns a ship upon dying) to give the mothership time to get tf outta there and not be, itself, targeted by its own trump card.

**Comment by Wyrdean** [comment]
Having the option to spawn a ship as a submunition would work perfectly; still allows the usage of range, ammo, and every other value necessary for proper use by the AI.
The potential applications for this are massive, and as it avoids the issues Derpy mentioned it stands a much better chance of being implemented.
