### ISSUE TITLE
Cargo delivery mission to Martini + "terrorist" attack event

### ISSUE THREAD

**Issue by uhausbrand** [endless-sky/endless-sky#93]
Hi all,

yesterday while playing i stumbled upon a little bug/issue with the generated delivery/transport missions and scripted events. I had a cargo delivery mission to Martini and while flying to this planet the Free Worlds event started which made Martini not accessible for me. I just had to abort the mission.

Only a small issue, but it would probably be wise to tweak the mission generator to not include event planets which could be rendered inaccessible in the mission time.

Best regards

**Comment by akien-mga** [comment]
Arguably, one could estimate that unexpected scripted event *would* disrupt the plans of the peaceful freighter who only minded his own business before entering the Free Worlds :)

**Comment by uhausbrand** [comment]
The problem for me was that this mission seems to be impossible to solve after this event because i'm not allowed to land on the specific planet and nothing tells me about any option when i can land there again. So my only option was to abort this. That is just confusing.

After looking into the event data, it seems that i can get some faction standing to be allowed to land there again, but nothing in the game tells you about this and i'm not sure about the ways how i can get this faction standing.

I think some solutions would be:
* don't include planets which get any major event disruption (like not landable anymore) in the next two to four weeks ( because it doesn't seem logical to exclude these planets forever)
* inform the player about their options to be able to land in these event situations
* automatically cancel not solvable missions with information to the player

But as i said before, it is a small issue which isn't very problematic, just inconvenient.

**Comment by endless-sky** [comment]
From a story-telling perspective, when war breaks out it will be chaos: lots of travelers stranded far from home, merchants unable to make deliveries, and even people cut off from visiting their own families because of those two planets being on lockdown. So, the idea that the player might experience that inconvenience and confusion firsthand is sort of appealing to me, even though I know that from the player's perspective, that will be a frustrating experience.

On a practical level, having the job creation need to go through all pending events and check if any of them would make the destination closed off to the player would increase the complexity of that code significantly. I'm not sure that's worth it just for the 5% of players who might be inconvenienced by it.

**Comment by uhausbrand** [comment]
Your probably right about the code complexity and the gain from that. That solution is not good.

But maybe there could be some information about the mission so it doesn't feel like there is something wrong.

Otherwise it's ok for me if you close this issue.

**Comment by endless-sky** [comment]
I've added to my long term to-do list the possibility of providing a way to check if you have any missions with a given destination, so a different message could be displayed in that case. But for now, I think I'll just leave this as-is.
