### ISSUE TITLE
Feature Request: outfit attribute: "unplunderable"

### ISSUE THREAD

**Issue by LocalGod79** [endless-sky/endless-sky#932]
requested recently on steam.

>So a problem I have as a modder is that my outfits are too easy to steal. I can make the ships stronger so that it's harder to actually kill, but there should be a function to make some items unstealble on a ship (such as how you cannot take hand to hand weapons)

**Comment by LocalGod79** [comment]
#690 
#227

**Comment by Disiuze** [comment]
Agreed, it could also add more realism like with the reactors, as you suggested.

**Comment by jmhorjus** [comment]
I'll see about adding this attribute to the game engine.  
I'll only add it to mass expansions to start, since plundering a mass expansion can cause the plundered ship to go to negative space available.

**Comment by LocalGod79** [comment]
indeed the "cargo expansion" outfit seems like something you'd be unable to plunder as well...

but i guess we start *that* discussion once the feature is available.

**Comment by jmhorjus** [comment]
It's available. :)
https://github.com/endless-sky/endless-sky/pull/933

**Comment by wargwargwarg** [comment]
I'd add to the list of "unplunderables" the higher tier engines and fixed weapons, reason being they're big long objects that can't be maneuvered through the inside of a hull.
Hm, those parts could be ejected and then handled by a specialized salvage  drone into the ship's hold. The cargo hold doors are, presumably, proportional with the ship size and if big enough could admit the plunder.
This would add a "salvage drone bay" that'll need some space but should add more bigger plunder otherwise unavailable...

**Comment by jmhorjus** [comment]
All outfit and cargo and outfit management should be handled via a Tetris-like drag-and-drop interface just like Diablo 2. 

Hmm...I started writing that as a joke, but now "inventory Tetris with spaceships" actually sounds pretty cool. For [some other game](https://www.google.com/search?q=infinite+space+ds) though. Not for Endless Sky. :)

**Comment by wargwargwarg** [comment]
@jmhorjus, why not that "Tetris with spaceship parts" mini-game? Shouldn't be to difficult top make and could, perhaps, be optional in the game menu.
I keep hearing "this is not for ES". Why not? It's in development, add a feature, see the feedback and decide if to improve or remove.

**Comment by jmhorjus** [comment]
re: "Shouldn't be to difficult to make"
In this case it might actually be kinda difficult to make! >_< Just think about it...a whole new GUI panel with new GUI art, new mechanics (which also need to be applied to existing GUI panels), new balance needed for every single existing outfit and ship hull, new art (in interesting Tetris shapes) for every single existing outfit and ship hull, new save-game format, figure out how to be backward compatible with old saves and mods... it would be hundreds and hundreds of hours of work...

It's hard to have a good idea of what will be easy and what will be hard or impossible without significant inside perspective/experience creating code/content/art. Some ideas are just not meant to be for a project with our level of resources here - but that doesn't make them bad ideas or not worth suggesting! It's great to dream, but in the end what actually gets implemented is what's possible - in fact only the subset of what's possible that some real person also actually decides to volunteer enough time from their busy life to make happen. 

I hope you keep the different ideas coming though. Have a thick skin for the ones that no one knows how to implement yet or no one gets behind because they have other priorities. It's worth it for the ones that are just crazy enough to work. :)

**Comment by LocalGod79** [comment]
besides that, this is a space trading/combat game, not a basic puzzle game.

if you keep adding mini-games, E.S. as a whole becomes less, because the player is constantly being bogged down with inane tasks...

**Comment by wargwargwarg** [comment]
it's a fine line between inane and enjoyable. Much easier to get it wrong, even if you try hard to get it right.
That's why an improvement of the game mechanic might be in order:  make those ideas optional from the start (with disclaimer if you want). My reasoning being that the game is unbalanced (those very important heat and energy contraints are not used at all, also making money is dead easy in some cases.

**Comment by LocalGod79** [comment]
@endless-sky would you consider re-adding the "Antimatter Reactor" to the Quarg ships, using this attribute?  it would force players to cheat to get it (in which case they could/would, anyway) and maintain the modularity you had initially aimed for.

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
