### ISSUE TITLE
Thorax Cannon's Lopsided Aiming

### ISSUE THREAD

**Issue by ProNooberEX** [endless-sky/endless-sky#9390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The thorax cannon, a weapon from the bundeo, seems to fire not from the front of the ship, but from an angle toward the side of ship.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected Behavior

The weapon should be able to fire directly forwadr regardless of the type of ship.

### Screenshots

![Uploading 截屏2023-09-30 22.56.17.png…]()

### Operating System

Macbook 2019 Intel Os

### Game Source

Steam

### Game Version

v0.10.2

### Additional Information

N/A

**Comment by EjoThims** [comment]
Screenshot doesn't seem to be working, and please upload save file for replicating.

**Comment by Saugia** [comment]
Some ships in the game also have angled gun ports. If you have one of these ships, the Thorax Cannon may be in one of these ports instead of a forward one. For example, the Dromedary, the Korath Palavret, and the Korath Ra'gru Ik 618, have angled gun ports, as well as a few other Korath and some Gegno Vi ships.
