### ISSUE TITLE
Another idea to make small ships more viable: stronger generators with delay

### ISSUE THREAD

**Issue by RisingLeaf** [endless-sky/endless-sky#9460]
### Problem Description

Fighters and small ships often do not stand a chance against heavy warships, even in not so small groups it is hard to deal damage as shield generation of a HW is a lot stronger than the generation of a LW

### Related Issue Links

N/A

### Desired Solution

Introducing a few smaller shields that have a really good generation but have a delay assigned to them, this would make these shields unusable for large ships as they are not able to leave combat, but small ships could install these shields and then disengage when their shields drop low, only to return a few moments later with full shields. This would obviously only work if the small ships are attacking in a group large enough so that the big ship has multiple targets.

### Alternative Approaches

N/A

**Comment by Saturnalia9** [comment]
Is it possible to slightly lower HW shield regen just a tad to make them more susceptible to smaller fire? Or is shield regen already balanced enough?

**Comment by Ferociousfeind** [comment]
No, shield regen is just pretty bad all across human space, one ton of amortized randomized (human) weapon will counteract six tons of human shield generator- a single heavy laser will counteract the largest shield generator in human space.

The regenerators are another question, though they don't see much use in human space. They are much stronger than shield generators (3-3.7 shields/sec/ton, versus 0.8-1.31 shields/sec/ton), but still not going to be face-tanking much, comparing to the heavy laser (6.8 shields/sec/ton)

My idea was simply buffing shield generators, probably around a flat 2x shield generation (and shield energy), then the shield-delay-burdened outfits with significantly more generation behind that. (The stats I have drafted up right now put ~60 shields per second onto a 10t outfit, with "some" amount of shield delay. Still draft, but that's the magnitude I'm looking for.)

**Comment by danaris** [comment]
As it stands, all shield generation on a ship goes into one big "bucket", as does any shield delay—so this means there's no way to mix & match delays, so that you could have a low-regen shield outfit that has no delay and a high-regen outfit that kicks in after 5 seconds of safety. Worse, if you combine two shield outfits with delay, the delay stacks.

I think it would be best to adjust the code to instead aggregate shield regeneration by the delay amount—so if you had two generators with a 5 second delay, and one with a 0.5 second delay, you'd get two separate shielding effects, one starting 30 frames after the last damage instance and another stacking on after 300 frames with the combined power of those two generators.

**Comment by Ferociousfeind** [comment]
Shield delay stacking is an intentional balance metric- or at least, it is taken into account when I am balancing the outfits. It's also why I think it makes more sense for larger delayed shield outfits to have more delay than smaller ones, because stacking them naturally increases the total delay, even if the delay/ton of the larger shields is smaller than the delay/ton of the smaller ones

While this could be implemented for just shields, I would rather go all the way and implement "treating outfits separately" across the board, for all outfits, which would allow much more customizability of different outfits
