### ISSUE TITLE
Turrets and Turn Rates

### ISSUE THREAD

**Issue by Saturnalia9** [endless-sky/endless-sky#9469]
### Problem Description

We've been discussing turn rates in the game for a bit in the Discord server, and a number of us are in agreement that HW and turret turn rates are rather high, leaving almost no weakness for LWs, interceptors, and fighters to exploit. Between HW turn rates (which ranges from 50 to 200+ [for player-outfitted ships]) and turret turn rates (which range from 60° to over 100°), even the slowest turrets can rotate well over 100°/s, with average-speed turrets usually able to rotate 200°/s. Again, this leaves almost no weakness for HWs unless they're simply outranged.

### Related Issue Links

https://discord.com/channels/251118043411775489/947227869036286033/1162522763202928760
"Also more generally you still need turret turn to change, because the way it is currently they are basically un-dodgeable" - Solarshade

https://discord.com/channels/251118043411775489/308902312741568512/1157806150528544868
"Turret tracking hasn't been touched, but does come up often in this type of discussion as a consideration to adjustment." - Saugia*

https://discord.com/channels/251118043411775489/947227869036286033/1162526028154032220
"But yes, if someone wanted to go through and rebalance turret turn rates to follow some sort of consistent scheme that makes sense, I imagine it would be fairly well accepted." - Hectare4
### Desired Solution

In order to give lighter craft an edge in ship combat against HWs, HW turning and turret turn both need to be brought down a bit. For the average turret, having a total turn rate (HW turn and turret turn added) between maybe 60° and 90° would be ideal. However, this would make HWs nearly unplayable to some people who prefer their HWs fast and mobile (lol?). 

If we had a turret with 100° total turn, that could give a ship 50° turn and the turret with 50° turn. Or if we wanted total turn to be lower, say, 80°, we could have HWs with 40° and turrets with 40°. 

### Alternative Approaches

There has been talks about giving turrets arcs, limiting the swing of turrets on ships. This would be a major rework for nearly every turret hardpoint, but it would be very effective as well. This would allow ship customization to be detailed and thoughtful, rather than simply tossing turrets all over the ship. 

If this change did happen, I would personally like turret arcs to have both acute and obtuse angles for different ranges of playstyles (for instance, someone who valued longer turrets would be able to put their turret in a hardpoint with a larger arc to suit their gameplay. Meanwhile, someone who valued defense would be able to put their defensive turrets in hardpoints with larger arcs to provide cover for their ship.

To expand on this, the PR #6822 is being worked on which would further enhance aggressive vs defensive behaviour with turrets. This would be a nice parallel approach to having anti-fighter vs anti-capital turrets, and/or would potentially help differentiate between the two types.

**Comment by Quantumshark** [comment]
> Between HW turn rates (which ranges from 50 to 200+ [for player-outfitted ships]) and turret turn rates (which range from 60° to over 100°), even the slowest turrets can rotate well over 100°/s, with average-speed turrets usually able to rotate 200°/s. Again, this leaves almost no weakness for HWs unless they're simply outranged.

Player-outfitted ships being able to achieve higher turn rates does not prevent smaller player-controlled ships using their mobility, because _this isn't a pvp game_. It's only AI-controlled ships that players are going to be up against, so it's only those that would need to be made slow enough to outmaneuver if that was desired.

Also, you're starting from the assumption that ships are always using their own turn to help move their turrets around. The AI does not do this, it only uses its own turn to either keep its guns on target or as part of moving around. That's just as likely to be moving the turrets away from their target as towards them.

Now, I agree that broadly speaking turrets could be made to be slower, but you're using incorrect reasoning to claim that the reduction would need to be much larger than is actually the case.

**Comment by Saturnalia9** [comment]
> Also, you're starting from the assumption that ships are always using their own turn to help move their turrets around. The AI does not do this, it only uses its own turn to either keep its guns on target or as part of navigating and moving the ship around. That's just as likely to be moving the turrets away from their target as towards them. So no, the effective turn of a turret is not its turn plus the turn of the ship it's on.
> 
Because turrets do turn so fast in vanilla, it will very seldom turn its turrets away from the target. For instance, the Cruiser and Carrier have a... slow turn rate (relatively) compared to the average turret turn rate that it (the average turret) will almost always be able to continue to track the target unless there is some weird circumstance in which a fighter is running across the path of the said Cruiser or Carrier. Likewise with most other ships and their turrets.

If anything, your scenario would be an improvement where the ship and turret are turning at the same rate, disallowing the turrets to be able to track properly.

**Comment by Hecter94** [comment]
<details>
<summary>For reference, a chart I made a little while back comparing turn rates:</summary>

![image](https://github.com/endless-sky/endless-sky/assets/15916854/712e3572-87e8-407c-b860-d37ea9fb0b9b)

</details>
The obvious answer is"Larger turrets should turn slower," with probably a modifier on them based on how high-tech the outfit is supposed to be. 
DPS/Range could have other tradeoffs, but all else being equal, size and turn seem like the most intuitive stats to link together intrinsically. 

Lowering turn rates a small amount globally and then rebalancing them to follow a consistent scheme based on size seems logical.

**Comment by Saturnalia9** [comment]
> > For reference, a chart I made a little while back comparing turn rates:
> > The obvious answer is"Larger turrets should turn slower," with probably a modifier on them based on how high-tech the outfit is supposed to be. DPS/Range could have other tradeoffs, but all else being equal, size and turn seem like the most intuitive stats to link together intrinsically.
> > 
> > Lowering turn rates a small amount globally and then rebalancing them to follow a consistent scheme based on size seems logical.
> 
> Range in particular is something that benefits (from a gameplay perspective) from having low traverse as the tradeoff. Low traverse is more exploitable at shorter distances, so a turret with a long range and low traverse creates an interesting situation where it is highly effective at long ranges but can be beaten by closing the distance.
> 

The problem I now see arising is the difference between 300 range turrets, 500 range turrets, 700 range turrets, and 1k range turrets. How would we scale these properly?

**Comment by Solarshade** [comment]
> > > For reference, a chart I made a little while back comparing turn rates:
> > > The obvious answer is"Larger turrets should turn slower," with probably a modifier on them based on how high-tech the outfit is supposed to be. DPS/Range could have other tradeoffs, but all else being equal, size and turn seem like the most intuitive stats to link together intrinsically.
> > > Lowering turn rates a small amount globally and then rebalancing them to follow a consistent scheme based on size seems logical.
> > 
> > 
> > Range in particular is something that benefits (from a gameplay perspective) from having low traverse as the tradeoff. Low traverse is more exploitable at shorter distances, so a turret with a long range and low traverse creates an interesting situation where it is highly effective at long ranges but can be beaten by closing the distance.
> 
> The problem I now see arising is the difference between 300 range turrets, 500 range turrets, 700 range turrets, and 1k range turrets. How would we scale these properly?

You make shorter ranged turrets faster, because otherwise they can't do their job? Unless you're asking for a specific formula or something.

**Comment by Saturnalia9** [comment]
> You make shorter ranged turrets faster, because otherwise they can't do their job? Unless you're asking for a specific formula or something.

Any formula we can come up with, to come up with any approximate number. Unless we're just bs'ing numbers.

**Comment by mOctave** [comment]
As long as mass, tech level, and turret purpose are all taken into account, I think this would be a very beneficial change.

On a side note, however, it would be nice if we actually had AM turrets that turn, rather than jump. This is somewhat tangential, but should probably be addressed if we're looking at reworking turrets' purposes in general.

**Comment by Saturnalia9** [comment]
> On a side note, however, it would be nice if we actually had AM turrets that turn, rather than jump. This is somewhat tangential, but should probably be addressed if we're looking at reworking turrets' purposes in general.

When you say jump, I assume you mean turning so fast that it doesn't appear to actually turn?

**Comment by mOctave** [comment]
> When you say jump, I assume you mean turning so fast that it doesn't appear to actually turn?

Yes

**Comment by Hurleveur** [comment]
@Hecter94 looking at the table of turn rates I cant help but feel the wrong method was used, we should look both at ranges and projectile speeds. Also some weapons (like the sunbeam) already dont have very low turning and are almost fine as is.

For an example the 2.4 -> 0.5 turn speed for the ionic prot is super harsh, why would it turn slower than a sunbeam? That said those were probably not final numbers; I definitely like the idea it just feels overkil for some things

**Comment by Hecter94** [comment]
Tech level, range (and, by extension, projectile speed), damage, and purpose were all considered, as I mentioned in my earlier post. Though turret size, range, and purpose were the primary considerations. 

Looking at your specific example.
The Ionic Prototype...
Is 26% larger than the Sunbeam
Has 56% more range
Does 79% less damage
But 107% more "special" damage, granted ion damage isn't as valuable as heat damage generally, so it's perhaps unfair to make a 1-to-1 comparison here. 
And is a "prototype" made by a lower-tier faction.
We don't know much about the "purpose" of the two weapons, but both seem to follow the same philosophy: "Take our existing main weapon and transfer it to a turret mount."

<details>
<summary>Table</summary>

| name         	| Ionic   Turret Prototype       	| Sunbeam   Turret    	| % Diff 	|
|--------------	|--------------------------------	|---------------------	|--------	|
| Category     	| Turrets                        	| Turrets             	|        	|
| Type         	| Projectile                     	| Beam                	|        	|
| Faction      	| Hai                            	| Wanderer            	|        	|
|  Cost        	|  $               1,260,000.00  	|  $    1,970,000.00  	|        	|
| Space        	| 58                             	| 46                  	| 26%    	|
| Range        	| 840                            	| 540                 	| 56%    	|
| Turn         	| 4                              	| 4                   	| 0%     	|
| Reload       	| 70                             	| 1                   	| 6900%  	|
| Burst Count  	| 1                              	| 1                   	| 0%     	|
| Burst Reload 	| 1                              	| 1                   	| 0%     	|
| Shots/Second 	| 0.857143                       	| 60                  	| -99%   	|
| Energy/Shot  	| 371                            	| 5.2                 	| 7035%  	|
| Heat/Shot    	| 259                            	| 6.2                 	| 4077%  	|
| Recoil/Shot  	| 8                              	| 0                   	|        	|
| Energy/s     	| 318                            	| 312                 	| 2%     	|
| Heat/s       	| 222                            	| 372                 	| -40%   	|
| Recoil/s     	| 6.85714                        	| 0                   	|        	|
| Discharge/s  	| 0                              	| 0                   	|        	|
| Shield/s     	| 85.7143                        	| 432                 	| -80%   	|
| Hull/s       	| 42.8571                        	| 180                 	| -76%   	|
| Total DPS    	| 128.5714                       	| 612                 	| -79%   	|
| DPS/Energy   	| 0.4                            	| 1.96                	| -80%   	|
| DPS/Mass     	| 2.22                           	| 13.3                	| -83%   	|
| Special DPS  	| 1500                           	| 726                 	| 107%   	|

</details>

Bearing in mind that more range also reduces the amount of turning needed, the further away a ship is from you, the faster it can move without your turrets being unable to track it, and the knockback on the ionic turret prototype also works in its favor to help keep targets *at* range.
Considering all that, the Ionic Turret Prototype turns slower than the Sunbeam because it is larger, longer-ranged, and lower-tech. 

Now, a few have raised concerns that the slowest-turning turrets in my proposal may be too slow-turning; from my playtesting, I haven't felt the same way, but if the consensus after playtesting is that they're too slow, we could see the lower end raised a bit, perhaps up to the 40° floor mentioned previously. 
That said, even if we raise the floor a bit, I don't see the Ionic Turret Prototype turning faster than the Sunbeam unless its size (and damage) or range is decreased.

**Comment by Hurleveur** [comment]
> range (and, by extension, projectile speed)

I'm sorry but that doesnt make sense to me: the sunbeams **hits instantly its enemy** as it is a laser and those weapons should be more penalised than a weapon that takes ages to hit and may miss (and they already are). Thats the extreme case of what I meant by proj speed, and is not really in the range.
I dont want to go in details for this one example, I'll do it in the PR if I have to, but I was hoping you'd see my point here of projectile speed mattering as much as range. (Especially with lasers)

> We don't know much about the "purpose" of the two weapons, but both seem to follow the same philosophy: "Take our existing main weapon and transfer it to a turret mount."

~~I made it, trust me, ik, and I'd never do smth as simple as just putting a weapon on a turret~~ 
But besides that the phylosophy wasnt just that, quoting from the mission: `due to its high range, small ships and even fighters will never bother you again!"`
Btw prototype is accounted for by the inneficiency for this weapon, and the low usability for the blaster. It doesnt mean its worse than other weapons, only that it has a significant downside.
That said I dont want to get carried away too much, so getting back on point I dont see why it should be tied to tier, it's more about their usage (tier already accounts for dps etc, it doesnt mean everything is better, in fact, as MZ said iirc higher tier stuff isnt just better, its has downside, which for the sunbeam turret is its notoriously slow turn)

> I don't see the Ionic Turret Prototype turning faster than the Sunbeam unless its size (and damage) or range is decreased.

Mb a higher tier faction can make a better turning turret easier but it isnt everything and shouldnt be. Sunbeams should be the floor, as they always have been.

Simply put I agree with the idea and the logic enounced +- but I dont like the numbers you made, with some turrets that already barely turn (like the geg turret) turning so slow its ridiculous. What formula did you use? I think range matters way too much in it.

**Comment by Hecter94** [comment]
I'm sorry to hear my prior explanation didn't convince you. 
To answer a few of your points, to perhaps give some clarity towards my original reasoning. 

> the sunbeams hits instantly its enemy as it is a laser and those weapons should be more penalised than a weapon that takes ages to hit

You are correct; the Sunbeam, as a beam weapon, has a guaranteed hit assuming that the turret can point directly at its target; the "penalty" for that is beam weapons tend to have shorter range and/or less damage than their non-beam counterparts. 
Comparing, for example, the plasma turret to the electron turret, as they're both from the same faction, both developed around the same time, and both fulfill similar purposes:
![image](https://github.com/endless-sky/endless-sky/assets/15916854/d5e3ca82-4df8-417f-8d35-37379b8cff91)

The Electron Turret, as a beam weapon, hits its target instantly and is therefore penalized for that with lower range and less damage*. At the same time, having a similar but slightly faster turn rate. 
(While the Electron Turret does have more hull DPS, and its total DPS is, in fact, higher, most human military ships are skewed quite heavily towards shield HP. If you adjust the DPS to account for that, the plasma turret ends up with a shorter time-to-kill against most human military ships)
![image](https://github.com/endless-sky/endless-sky/assets/15916854/6b3fc3c3-dcd4-4d4f-9e0c-1ab88e84d4d3)

Thus, the Sunbeam would have a lower range compared to the Ionic Turret Prototype as its "penalty" for being a beam weapon, with its DPS being higher due to the tier disparity and a faster turn rate for the reasons given in my prior message,

> due to its high range, small ships and even fighters will never bother you again!"

Yes, and the range is staying the same, which, as Doom pointed out earlier:
`Range in particular is something that benefits (from a gameplay perspective) from having low traverse as the tradeoff. Low traverse is more exploitable at shorter distances, so a turret with a long range and low traverse creates an interesting situation where it is highly effective at long ranges but can be beaten by closing the distance.`

and as I mentioned.
`Bearing in mind that more range also reduces the amount of turning needed; the further away a ship is from you, the faster it can move without your turrets being unable to track it. The knockback on the ionic turret prototype also works in its favor to help keep targets at range.`

With the extra range and knockback, I suspect the ionic turret prototype will excel at range, being able to effectively track its target as long as it is staying at range, with its relatively high knockback helping to keep targets at range once it's able to get some hits on them while as Doom noted, not being as effective at closer ranges due to the lower traverse. 

> Wait the bigger the turret the lower the turn?? That doesnt really make sense as a generic rule either, to me.

Generally, yes, the larger something is, the slower it is. You can see that with a few things in Endless Sky already, namely ships, which get slower as they get larger (and there a few proposals to make this even more so), projectiles, which also tend to move slower the larger they are, and in fact, the existing turrets with their current turn rates show a clear trend that larger turrets turn slower, as you can see in my [chart above](https://github.com/endless-sky/endless-sky/issues/9469#issuecomment-1764789884)

It also, to me at least, makes intrinsic sense that the bigger something is, the harder it's going to be to turn it quickly. A small 5-ton gun on a turret mount can probably turn relatively quickly without a significant investment, whereas a 120-ton artillery piece will probably take a *lot* more effort to reach the same turning speed and end up being slower as a result. 
It shouldn't be the only consideration, of course, range, damage, and overall tech level should be taken into account, but larger=slower doesn't strike me as an unreasonable general guideline. 

With all of that said, if you still don't agree with my proposal as I've laid it out, I would encourage you to make your own proposal weighting the stats how you feel they should be weighted. 
I've given my proposal and the reasoning behind the proposed changes, backed up by specific in-game stats and individual comparisons. If you would like to make your own proposal weighting the stats differently and are prepared to ensure that it is logical, consistent, and resolves the original issue, you are welcome to do so, and then our community, reviewers, and dev team can decide which proposal they agree with.

**Comment by Hecter94** [comment]
> I'm mostly against using tiers as a factor so much, and whilst I see your point that size changing the turning is _realist_, I dont see the use of it so much gameplay wise, leading to some things just turning too slowly and less variety in weapons.

Tiers aren't a major consideration, but they do need to be considered. Otherwise, the Gridfire would be one of the slowest-turning turrets in the game due to its size and range, which doesn't seem appropriate for weaponry made by a faction that is at least T3.

And I wouldn't necessarily argue that it is "realistic," more internally consistent, and matches player expectations. For example, the round from a Ballistic Cannon has less velocity and does more damage than a round from a Choleric Cannon, not because that is more realistic, but because it's consistent and matches the player's expectation that a larger round will be slower and do more damage, even if that isn't necessarily realistic.

Suppose it comes down to deciding between making something realistic or making something that will match players' expectations. In that case, we should usually try to match player expectations if we want a smooth play experience. I would argue that for most people, the idea of "larger=slower" will be what they naturally expect, whether that's ships, rounds, turrets, or most other things, so that's the guideline I'm following.

**Comment by Hurleveur** [comment]
Actually, if we consider lasers and their lower dps as anti fighter weapons then I dont really have any issues.

This makes turrets feel less responsive, and less like garanteed dmg, meaning slow HW feel less good; which is great.

Playtesting is probably what we need for these changes.

**Comment by tibetiroka** [comment]
Resolved by #10043.
