### ISSUE TITLE
Replace 'Captain' with 'Admiral'

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#949]
Replace the prefix 'Captain' before the player's name with 'Admiral' when the player owns more then one ship. Only makes scene, right?

**Comment by Alkallid** [comment]
That'd change _many_ conversations.

**Comment by Alkallid** [comment]
Or not, if it's dependent, but it seems too superficial.

**Comment by gchapyzh** [comment]
Something automatic obviously, an I don't think its too hard. Just replace all 'Captain' with variable and make a small subroutine that decides which of the two you are.

Its just for the looks, sure, but I kinda feel hurt when I own 25 ships and they call me Captain :P 

Could also be used to change rank at later time, maybe if the Navy give you a rank that you go by, rather then just Captain.

**Comment by endless-sky** [comment]
Since "Admiral" is a military rank, it doesn't make sense to apply it to a player who is not part of an actual military. It might eventually make sense to have a "title" variable in the conversations that can be filled in if, for example, you join the Navy, but a private citizen who owns multiple ships is still just a private citizen.

**Comment by LocalGod79** [comment]
one doesn't need to be in an organized navy to hold the "rank" of Admiral - as long as one is in command of a fleet.

ad·mi·ral
ˈadm(ə)rəl/
noun
1.
a commander of a fleet or naval squadron, or a naval officer of very high rank.
...

**Comment by gchapyzh** [comment]
In any way, a system where prefixes are controlled for the player are and would be quite useful once more ranks are introduced.

**Comment by Waladil** [comment]
"Captain" is the default form of address for anyone who is commanding their own ship. This remains true in the real-world military if the commander is higher or lower rank than an actual Captain.
Missile impacts and kills every senior officer on board, and a second lieutenant takes command? That 2nd Lt is now the captain, and it would be proper to address him/her as such. 

So long as the PC is technically a civilian, it would always be correct to call them "Captain," whether they own one or a thousand ships. If insisting on a title for having multiple ships, the next correct title would be "Commodore," especially if the title was being used while not on board one of the PC's ships. Ever calling a civilian "Admiral" would have some...dangerous connotations, because it would imply that that civilian is in command of an independent military unit. Which (turns out) usually makes governments uncomfortable.*

Of course, as the PC would advance in the world, they'd earn actual titles and there are times they'd be referred to by that title. So overall support for a "title" stand-in would be really useful. 

*Of course, the PC can easily accrue enough power to essentially BE an independent military force that can stand toe-to-toe with existing militaries, but I like the implication that most of the galaxy is busy pretending you aren't flying around with an armada that can wipe the floor with the entire Sol defense fleet.

**Comment by gchapyzh** [comment]
> but I like the implication that most of the galaxy is busy pretending you aren't flying around with an armada that can wipe the floor with the entire Sol defense fleet.

Thats a whole new department of suggestions revolving around the idea of the PC having their own military. 

And even is my original idea of Captain/Admiral titles being mobile, the whole idea does seem quite useful, no?

( By the way, are there any capital issues with the idea of a player being able to make their own empire? Just a thought. )

**Comment by Hyratel** [comment]
I'd like if once you have  more than a specific number of ships massing over ... say, 200 tons, you get referred to as Fleet Captain instead of just Captain

**Comment by Isaacssv552** [comment]
It does seem odd that I have a large fleet and have dominated half the republic (Including Sol) and everyone acts as if I'm a small time merchant captain.
