### ISSUE TITLE
Support for secondary turrets?

### ISSUE THREAD

**Issue by timbennett** [endless-sky/endless-sky#95]
This is not a priority but more of a nice-to-have.

I'm trying to create a plugin for a remote shield recharger, which could buff friendly ships. The problem is I'd like it to be an energy-consuming beam turret (which I think would fit game fiction better), but:

* Even though they can occupy a turret slot, I can only get beam-based secondary weapons to fire in the direction I am facing, not towards the selected target (though I could do a homing, projectile based one I suppose).
* I apparently cannot create a secondary weapon unless it uses a consumable (fuel, ammunition) but I would like it to consume energy only.

You would probably need support for this to implement tractor or repulsor beams.

This is how I'm currently accomplishing a shield recharger as a secondary weapon which fires forwards only, and consumes a tiny amount of fuel:

    outfit "Remote Shield Recharger"
	category "Secondary Weapons"
	thumbnail "outfit/heavy laser turret" # placeholder
	cost 100000
	"outfit space" -10
	"weapon capacity" -10
	"turret mounts" -1
	weapon
		sprite "projectile/2x heavy laser"
			"frame rate" 1
		sound "heavy_laser"
		icon "icon/tracker"
		"hit effect" "heavy laser impact"
		"inaccuracy" .4
		"velocity" 400
		"lifetime" 1
		"reload" 1
		"firing energy" 2
		"firing heat" 4.4
		"firing fuel" 0.001
		homing 20
		"shield damage" -3.6
		"hit force" -5	
	description "The Remote Shield Recharger is a useful tool for patching up the defences of friendly ships, though at the cost of some offensive capability."

**Comment by endless-sky** [comment]
I tested your code, and it appears to work fine if you target one of your escorts before firing. (Assuming that everything after the first line is indented more than is shown in your post.) Note that the "homing" line is unnecessary, since all turrets auto-aim. (See [this wiki page](https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits) for a recently created guide to what all the outfit and weapon attributes mean.) Also note that the AI will not know how to use that outfit; it will treat it like any other weapon, and fire it at its enemies rather than at its friends.

I suppose I could add a way for a weapon to be tagged as secondary even if it only uses energy. I'll work on that.

In terms of game balance, shield generators "cost" 1 energy point per 1 shield point recharged. Especially if you're going to give the weapon such a high recharge rate (3.6, compared to 1.3 for a 60 Ton shield generator), the energy and heat costs had better be astronomical (say, 10 times as much energy as the recharge amount) to make up for it.

**Comment by endless-sky** [comment]
I've changed it so that the presence of an "icon" is all it takes to mark a weapon as secondary (8d2f371). So, in the next release it will be possible to create secondary weapons that do not consume ammo or fuel.

**Comment by timbennett** [comment]
Just FYI, I tried targeting an escort (Leviathan) and captured the image below - the beams didn't track the target. This is with the code posted above (appropriately indented).
![screen shot 2015-09-14 at 8 56 47 am](https://cloud.githubusercontent.com/assets/1192790/9839472/b7acad2a-5abe-11e5-9ef7-f4c8d66750ef.png)

**Comment by endless-sky** [comment]
I'm using this code:

```
outfit "Remote Shield Recharger"
	category "Secondary Weapons"
	thumbnail "outfit/heavy laser turret" # placeholder
	cost 100000
	"outfit space" -10
	"weapon capacity" -10
	"turret mounts" -1
	weapon
		sprite "projectile/2x heavy laser"
		    "frame rate" 1
		sound "heavy_laser"
		icon "icon/tracker"
		"hit effect" "heavy laser impact"
		"inaccuracy" .4
		"velocity" 400
		"lifetime" 1
		"reload" 1
		"firing energy" 2
		"firing heat" 4.4
		"firing fuel" 0.001
		"shield damage" -3.6
		"hit force" -5  
	description "The Remote Shield Recharger is a useful tool for patching up the defences of friendly ships, though at the cost of some offensive capability."

outfitter "Common Outfits"
	"Remote Shield Recharger"
```

and I get the turret tracking correctly:

![turret](https://cloud.githubusercontent.com/assets/11450262/9841287/e566bf4c-5a6b-11e5-8c87-1a8627c35605.jpg)

Are you running 0.8.3, or an earlier version? And, on which OS?

**Comment by endless-sky** [comment]
Based on where the beams are coming from in your screenshot, it looks like the weapon got installed in an ordinary gun slot instead of a turret slot, which might mean the "turret mounts" attribute isn't formatted correctly? On a Hauler the turrets are mounted farther back:

![hauler](https://cloud.githubusercontent.com/assets/11450262/9841364/d0451662-5a6c-11e5-856d-64d7305d54e8.jpg)

**Comment by timbennett** [comment]
> You could check the "ship info" display to see whether your recharger weapon is installed in one of the turret slots, or one of the ordinary guns up front.

This is exactly what went wrong. I must have forgotten to sell and re-buy the weapon after changing the mount point from gun to turret, hence they stayed where they were.

Thanks for your help!
