### ISSUE TITLE
Again with the fighters

### ISSUE THREAD

**Issue by gchapyzh** [endless-sky/endless-sky#952]
So: I am sure someone brought this up already, but:

Fighters are weak: I suggest an easy fix:

Instead of forward weapons, give the fighters turret(s) and an AI based of running circles around the target. This will make fighters harder to hit, while letting them land fire on the opponent.

**Comment by endless-sky** [comment]
Fighters are the smallest and cheapest ship available. It makes *sense* for them to be weak. If fighters were more powerful, they would also need to cost more, and if they cost more there would be no reason to buy them rather than interceptors.

**Comment by toilethinges** [comment]
Then what would be the point of the current fighters' gun ports on their sprites? They'd have to be remade to avoid people wondering why there're still gun ports if there aren't gun ports.

This wouldn't help with fighters against the player, as _most_ people like turrets better than guns, so they'd be tracked easily.

**Comment by lehgogh** [comment]
@gchapyzh We could add new turret-only fighters (see #939), if you would like to make a PR.

**Comment by LocalGod79** [comment]
i am planning a Syndicate fighter with a turret mount.  the "Barb" may not end up being what @gchapyzh is hoping for, but it will certainly be an interesting addition to the galaxy.  it is referenced in the conversation of the PR @lehgogh referenced.

**Comment by gchapyzh** [comment]
@endless-sky  Its not really the point of 'Make them stronger/add more firepower', rather, 'make them a bit harder to kill so you don't have to pay death mortgages after every minor battle'.

**Comment by gchapyzh** [comment]
@lehgogh if under 'PR' you mean picture and/or script, then I actually plan on doing something to that degree. Any suggested fighter textures/features?

**Comment by DingusShingleton** [comment]
Actually, you don't pay death mortgage's for crew member's whose ships are destroyed in battle. You only pay them when crew are killed in a boarding action. Which is a little odd. But I am *definitely* not barking up that tree

**Comment by gchapyzh** [comment]
@DingusShingleton Learn something new every day eh?

Still, the point remains: you cant buy fighters at most shipyards, so having larger, stronger ships is more time and price beneficent then loosing fighters in every engagement.

**Comment by DingusShingleton** [comment]
Preaching to the choir, mate. Problem is, in order to rebalance fighters on a fundamental level, a tremendous amount of work has to be done. The whole free worlds story line has to be tinkered with and played through to ensure that it remains balanced. Eventually I want to start messing around with fighter balance, but it's filed under "at some point" right now. Getting the new carriers will be a big step towards making them fun I think, and it will add fighters to five shipyards in the southern reaches of the galaxy. Localgod is also I believe working on a syndicate fighter for that area of space. So there is plenty of fighter love in the works my friend, rest assured.

**Comment by lehgogh** [comment]
@gchapyzh "PR" is shorthand for "pull request", which would include pictures and a script.

**Comment by gchapyzh** [comment]
*nods* Okay. Seems that most people believe fighters are actually worthwhile. And yes I now see that changing the fighters would damage the balance heavily.

However, what would go a against a turret fighter? Too powerful? Unbalanced? Changes gameplay too much?

**Comment by DingusShingleton** [comment]
There is a fighter with a turret mount being designed as we speak. As far as the fighter AI is concerned, that's a horse of another color.

**Comment by jmhorjus** [comment]
We have a strange situation in the game right now, one in which the "economic balance" of optimum fleet composition is almost entirely unexplored.  The game is just not about "_you have X credits to build a fleet to defeat an opponent who also has X credits to build his fleet_."  That never happens.  Maybe it could or should, but it doesn't.  

The game is about pre-determined fleets, defined in fleets.txt, going up against the player.  Most fleets the player goes up against have no fighters. Those that do have very few fighters, "economically speaking".  A republic carrier, the most advanced carrier in the game, costs 20M+ and holds 1M worth of fighters and 1M of drones.  These few fighters and drones are irrelevant to the battle's outcome in most scenarios, because there are only a few of them and they fly ahead of their allies to die immediately against ships 50 times their size.  By the time the actual battle is joined any damage they may have done is usually long since regenerated. 

All that to say:
**Whether fighters are "worthwhile" economically is the wrong question.
**
Better questions would be:

- Are fighters different and interesting? 
- Do they have a significant impact on the outcome of battles and the strategies needed in battle, such that a battle with fighters **feels** different from a battle without them? 
- Do they help to create counter-play and paper-rock-scissors relationships in fleet design? 
- Is piloting a carrier a vastly different experience than piloting a battleship without fighters? 
- Does having fighters cause me to use very different tactics in battle, or do I more often choose not to launch them and rely on battleship tactics even when flying a carrier?

**Comment by lehgogh** [comment]
> and they fly ahead of their allies to die immediately

Perhaps add an AI mechanic that makes them deploy fighters _after_ the big ships start shooting?

**Comment by DingusShingleton** [comment]
@jmhorjus I think with the carriers that have been in the game so far, the answer to most of those questions is no, or probably not. But let me tell you, when you are flying the southern carriers.... you are DEFINITELY deploying those fighters. The fighters comprise such a large portion of the carriers effectiveness, you really can't rely on battleship tactics alone to survive. And even if you could, you have a badass swarm of fighters.

**Comment by jmhorjus** [comment]
I'm also pretty excited about the southern carriers! :) 

I think the approach of "make fighters way better but make carriers way worse at being battleships" is generally the right one.  Making fighters better could mean a lot of things; one option is just to make dedicated carriers hold a [lot ](https://en.wikipedia.org/wiki/Nimitz-class_aircraft_carrier#/media/File:USS_Nimitz_in_Victoria_Canada_036.jpg)more of them.

**Comment by LocalGod79** [comment]
i don't think that #939 makes fighters *way* better...a little faster sure, but they've 200 hull and are much more expensive than their competitors (for those engines!) - the Finch *is* balanced...

the thing that they (and the carriers) *do* is make a mechanic that has been previously hidden from players more plain by increasing overall availability of bays and fighters in the available plot arc.  the carriers themselves "suck" because they're not built at a Navy shipyard (or the Deep) - they're modified 500-year-old cargo freighters.  beastier carriers would have demanded more story, and reworking of the FW plot (and i'm already busy with the Republic).

i think fighters have always been really awesome, but M.Z. was holding back on them for the Republic storyline.  that plot could potentially pursue the style of ship @jmhorjus evoked, as well as drones (an aspect i'm truly excited about in that arc).

**Comment by jmhorjus** [comment]
@LocalGod79 Right, I didn't mean to imply the new fighter was better than old ones or that that change inherently made fighters themselves better at all - I've actually yet to test the branch for myself.  

I just really like that the new carriers are billed as dedicated carriers and not powerful battleships that also happen to hold 1-4 fighters as an afterthought.  They will literally be the first ships ever to have at least as many fighter bays as they have forward gun ports.

**Comment by LocalGod79** [comment]
@jmhorjus i don't mean to nitpick, but the Aerie has two gun ports, and two bays - as many.

so, maybe "first ships with *more* 'bays than 'ports"...

**Comment by jafdy** [comment]
You could also use
 'the fledgling 'free worlds' need a large shipyard to keep there fighting men and women safe. they fund Southbound shipyards to expand and meet that need'
if you need a reason
