### ISSUE TITLE
Hiding In Plain Sight description missing period

### ISSUE THREAD

**Issue by Tangle10** [endless-sky/endless-sky#9524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The description for the Hiding In Plain Sight Hai spaceport mission is missing a period. I'd try to do a pull request for it, but I don't know how- apologies.

### Steps to Reproduce

1. Find the Arthur and Kivu Hiding In Plain Sight mission, either in game or in hai missions.txt
2. Note that the description line is missing a period

### Expected Behavior

It should have a period.

### Operating System

Windows 10

### Game Source

Steam

### Game Version

0.10.4

**Comment by bene-dictator** [comment]
To open a pull request, you need to:

1. Create a fork of the endless-sky repository, by clicking on the "Fork" button on the top right and then clicking "create new repository". Title it whatever you want, but I'd just leave it as Tangle10/endless-sky.
<img width="1439" alt="Screenshot 2023-11-01 at 8 43 37 AM" src="https://github.com/endless-sky/endless-sky/assets/115441627/d8f3d75a-c275-485d-9756-851ad3387a3f">

2. In your new fork, click on the button that says "master". This button displays a menu that shows all of the branches in your fork. Create a new branch to keep your original branch (the "master") clean; the name for the branch doesn't matter, either, but I would name a branch for this fix "hiding-in-plain-sight-typo". <img width="1440" alt="Screenshot 2023-11-01 at 8 45 23 AM" src="https://github.com/endless-sky/endless-sky/assets/115441627/2b5c1aa8-61fd-4366-b4c0-ab6bfd60c9e8">

4. In your new branch, navigate to the "hai missions.txt" file and edit it to add the period. Commit the changes (since you've got repositories on your account, I guess you would be familiar with this). Commit it to your new branch; don't open a pull request to your master branch.

5. Once you've committed the edit, go back to your branch's "code" screen on the top navigation bar (next to issues, pull requests, etc.). There should be a new button that says "Compare and Pull Request". Click that to open the pull request creation screen.
<img width="1440" alt="Screenshot 2023-11-01 at 8 53 10 AM" src="https://github.com/endless-sky/endless-sky/assets/115441627/88f15552-03f4-4269-851e-e1c435fdf749">

6. Title the pull request something like "fix(typo): Hiding in Plain Sight missing period". Edit the description to say that it closes this issue and that you've added that missing period. Then click on "Create Pull Request".
<img width="1440" alt="Screenshot 2023-11-01 at 8 57 11 AM" src="https://github.com/endless-sky/endless-sky/assets/115441627/90ca25e3-c639-40be-a954-d423067170b7">

7. Once you've opened the pull request, we'll look at it and discuss merging it into the master branch of endless-sky/endless-sky.

Hopefully that's you can follow that, it was daunting for me when I started, too.

**Comment by Tangle10** [comment]
Much

**Comment by Tangle10** [comment]
that's not what i meant to do. oops

thank you for the assistance!

**Comment by EjoThims** [comment]
@bene-dictator Thank you for that amazing guide to starting PRs.

We really should get saved somewhere easily accessible :D
