### ISSUE TITLE
Make the physics of turning your ship the same as going forward

### ISSUE THREAD

**Issue by caste17420** [endless-sky/endless-sky#9545]
### Problem Description

I really like the physics of going forward and stopping in the game it is quite good , you have to put some energy in the other way to stop or you will go for ever in the same direction, but it is so frustating that the control of turning is not this way.

When you hit the turn key , the ship goes immediately to max turn speed and directly stops when i release the turn key.
I would like it to be like the thrust, with acceleration depending on turning energy and mass; turning max speed depending on turning energy and mass like it is right now.

This

### Related Issue Links

#9234 talks about an accel ratio for thrust and speed, maybe something like this could be added to turning too.

### Desired Solution

I want that: When I hit the turn button left or right, I would like it to be like the thrust; with acceleration depending on turning energy and mass; turning max speed depending on turning energy and drag like it is right now.

So: 
Turning Acceleration  =  Turning energy / Mass
Turning Max Speed    = Turning energy  / Drag

Also when I release the turn key the ship could keep its turning speed util I put energy in the opposite direction to stop her from turning and thus going straight.

The auto pilot in the game would still work the same just with added outputs for turning.  

 

### Alternative Approaches

This could make flying the ship actually much more enjoyable, with many new possible maneuvers during fights, (like keeping your distance just outrange of enemy lasers without autopilot that will lead you in a death spiral waiting for the strongest ship to die, or dodging missiles which should be funnier and more!) and some added skills to fly your ship, maybe add some racing missions with your ships where you have to really know how to fly it (in the mean time making afterburners more usefull), or missions where you can't hit the enemy ship because you have to capture somebody on board, so you can just fly your ship and make the enemy use all his ammo before boarding it.

We could also add something like if you turn with too much speed for too long, you will start to kill some of your crew members because of too much g forces for too long
To me it is a little thing that endless sky is missing in terms of gameplay, that you can really be a Pilot, or use you autopilot all the time if you want, but with less freeride flying thus less efficient in certain situations.

**Comment by Saugia** [comment]
Something to note is that the design of ES, as well as the type of games it is based upon, is centered around simple movement that responds to actions immediately. The idea of thrust being instant is more so a design choice from the start, rather than say, a lack of more intricate thrust mechanics and such.

Something we often say is we avoid adding more complexities to the game on purpose, and accelerated thrust has been one of those things brought up often. If we suddenly change how thrust works, we're changing how base gameplay works, which is a considerable change. It may be a change that some want, but ES's origins and what's likely a good portion of its audience is centered around more simpler movements. In fact, it's also brought up occasionally that flying the ship is difficult for players, and many players use the auto aim functions as well.

Generally we've avoided accelerated thrust and other mechanics of the likes for the above reasons.

**Comment by Amazinite** [comment]
Rotational momentum would make aiming much more difficult while bringing no real gameplay benefit.

**Comment by caste17420** [comment]
I see it would make it maybe a bit too hard for aiming, thank you guys! :)

**Comment by ixPost** [comment]
It could be added as a setting. About aiming I don't see how it would make it harder, a lot of times I need to keep clicking the turn key because the enemy ship is "orbiting" me.

**Comment by Zitchas** [comment]
On the other hand, the gamerules system was basically created for mechanic level changes such as this, so that's definitely a potential place for controlling something like this. It'd still need a fair amount of code changes, though.
