### ISSUE TITLE
Uncloaking before Boarding a Ship makes the game freeze

### ISSUE THREAD

**Issue by TheDeathStar3** [endless-sky/endless-sky#9585]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I travelled to Kor Nor'peli to attempt to capture a world ship. I entered the system cloaked, then I uncloaked and managed to disable a world ship, and then I cloaked again so that I would not die on the way to the world ship. But after I uncloaked above the disabled ship and pressed B, my computer froze completely to the point that I had to restart my computer to unfreeze. In the end, I could never board the world ship.

### Steps to Reproduce

1. Cloak your ship
2. Jump to a nearby system
3. Uncloak
4. Attack another ship until it is disabled and boardable
5. Cloak
6. Press B to travel to the disabled ship
7. Uncloak when over the disabled ship
8. Press B to **make your computer completely freeze**

### Expected Behavior

1. Cloak your ship
2. Jump to a nearby system
3. Uncloak
4. Attack another ship until it is disabled and boardable
5. Cloak
6. Press B to travel to the disabled ship
7. Uncloak when over the disabled ship
8. Press B to **board the disabled ship**

### Operating System

MacBook Air

### Game Source

GitHub Releases

### Game Version

v0.10.4

**Comment by mOctave** [comment]
> Operating System
> MacBook Air

MacBook Air isn't an operating system. It's a computer. To check what OS you have, click the apple icon in the top-left corner of your screen, and then "About This Mac." There should be an entry that says "macOS," copy down whatever's to the right of that. That is the operating system.

Since you're on a Mac, you also might want to check whether it says "Intel" or "M#." That isn't the operating system either, but it could still be important, for technical reasons.

Finally, it would really help a lot if you provided a save file. There's a chance that there's something else going on to do with that save that's contributing to a crash.

<img height="200" alt="Screenshot 2023-12-02 at 8 14 20 PM" src="https://github.com/endless-sky/endless-sky/assets/73318970/bec346e3-24de-44a3-adc0-7e6b7b782589">
<img height="300" alt="Screenshot 2023-12-02 at 8 15 18 PM" src="https://github.com/endless-sky/endless-sky/assets/73318970/9ff0e4f4-ab32-4af3-8866-7f14356672b9">

**Comment by RisingLeaf** [comment]
I was not able to reproduce this with the steps you gave

**Comment by TheDeathStar3** [comment]
Thank you for letting me know.
I was not using an actual save file, but I do not understand why that would affect it.
If I get this problem again with an actual save file, I will reopen this issue.
