### ISSUE TITLE
Why are the Aliens allways making remarks about how "foolish" wars are?

### ISSUE THREAD

**Issue by ixPost** [endless-sky/endless-sky#9639]
### Problem Description

I don't like how aliens say things like "The Drak were foolish those days makeing great wars"(approx.) --Anonymous Quarg first contact, or how they say that they "became wiser".

### Related Issue Links

None

### Desired Solution

Make most Hai see wars as something unavoidable and the aggressor(if evil) must be eliminated.(Largescale conflict, greed, wierd beliefs(Islam, Nod in Tiberian Dawn)) While almost all Quarg will think that war must be prevented at all costs, partly due to fear of weapons of mass destruction.

### Alternative Approaches

Mixed ideas?

**Comment by mOctave** [comment]
Well, the "no wars" thing is really just a Hai and Quarg thing. Overall, there are lots of mixed ideas, it's just in the early game that there's a tendency towards pacifism in aliens. I presume from your comments that you haven't yet gotten through the main plot or discovered any aliens, so I've hidden the rest of this in case you want to avoid spoilers.

<details><summary>Spoilery details.</summary>
<p>
For the Hai, they've seen how devastating wars are and so want to avoid them. For the Quarg, no one really knows, but they see themselves as the peacekeepers of the galaxy for some reason. The Wanderers have a similar philosophy, but they turn out to be slightly less pacific as they keep getting raided. The Remnant and Pug actively encourage wars in certain contexts. The Heliarch tries to keep the Coalition at peace, but that's because they want to stay in power. Many of the Korath spend their entire lives at war. The Gegno have traditional duels on alternate Tuesdays. The Bunrodea only meet the player after they are attacked. The Ka'het and Automata are pretty much war machines.

The Drak were foolish because, like the Korath, they just about wiped themselves out fighting a pointless war. Now, what remains of them is less foolish, because it/they sees the value in preservation.
</p>
</details>

**Comment by ixPost** [comment]
But how were there wars over nothing?

**Comment by ziproot** [comment]
The alternative approach (mixed ideas) is already in game. The Unfettered Hai wage war against the Wanderers and don't see themselves as foolish.

**Comment by Hurleveur** [comment]
> Make most Hai see wars as something unavoidable and the aggressor(if evil) must be eliminated.(Largescale conflict, greed, wierd beliefs(Islam, Nod in Tiberian Dawn))

in "Ask the Hai about the Unfettered" they say:
`	"Sometimes we make a fire for cooking food. The fire consumes much wood, and the flames are tall, too wild and hot to cook food well. Then the wood becomes coals that burn slowly with no flames or smoke, and when you gather them they are good for roasting meat or even baking bread. Perhaps each species must consume many worlds and many resources before learning to burn slowly, and the wisdom of the Drak is to allow them to do so. But when they find balance, as we did, they no longer need so much space."`
The way I see it the same logic of consuming wars and stuff can be expanded to wars?

As for the Unfettered I'd say they view war as a way to regain their previous might and not grow complacent with peace, as their hails denote. This is also a war for the survival as their way of life; as if they were to stop the raiding to gain food and instead accept food donations, they may as well join up with the rest of the Hai.
I started and will continue expanding on the idea not all UHai think the same way, with the Unfettered campaign.

As for other races, I may be wrong but I think that most humans see war as something that kinda had to happen but could be mitigated during FW, I think? Some pirates do it for their independence, Gegno avoid it as much as they can, the remnants turned it into trade, Korath got consumed by it and cant stop, the Pug see it as a tool, the wanderers something to fix, the heliarch as an excuse to stay in control....
Feels to me like we got plenty of different views on it?

**Comment by alexrovw** [comment]
> But how were there wars over nothing?

It's not that there were wars over nothing. With the wisdom of hindsight, the modern day Hai and Quarg see the past wars as _avoidable_ and therefore foolish. There were undoubtedly reasons for those wars, but the smarter course of action would have not been to engage in violence.

**Comment by Hurleveur** [comment]
From the Hai's quote, it seems to me its a part of species developing for them, and becoming wise, not really that avoidable

**Comment by ixPost** [comment]
Why do the Quargs view Alphas as a internal political issue of humans?

**Comment by Hurleveur** [comment]
Caus humans made them, like they made other weapons. The Korath had to do way worse than that for the Quarg to intervene - and alphas winning would probably just ended with humans in slavery, not wiped out.

That said you can just ask that kind of stuff on the discord, we try to keep closed issues inactive

**Comment by Zitchas** [comment]
> Why do the Quargs view Alphas as a internal political issue of humans?

Because fundementally, Alphas are just a subset of humanity. Humans might not like to think so and view them as being attacked by created servants or some such. But from an outside perspective, it's just humans getting into arguments with other humans that look a little different, and, well, humanity has a lot of color differentiation already. Adding another color to the set doesn't make them "non-human" any more than any of the other colors do.

**Comment by ixPost** [comment]
> Because fundementally, Alphas are just a subset of humanity. Humans might not like to think so and view them as being attacked by created servants or some such. But from an outside perspective, it's just humans getting into arguments with other humans that look a little different, and, well, humanity has a lot of color differentiation already. Adding another color to the set doesn't make them "non-human" any more than any of the other colors do.

But Alphas are not able to have mercy and to love(Somehow).

**Comment by ixPost** [comment]
More over the Hai say they whent throu the wormhole to escape wars in human space, why didn't they fight evil people? (Especially because there so bored of every thing)

**Comment by Saugia** [comment]
As this is an issue and the original answers have been provided, it has been closed. If any further discussion is desired, this would be much better be made a discussion post instead of an issue (when it's not really an issue).
