### ISSUE TITLE
Wiki tier information is outdated

### ISSUE THREAD

**Issue by ziproot** [endless-sky/endless-sky#9703]
### Location

wiki

### Describe the issue

The [tier system](https://github.com/endless-sky/endless-sky/wiki/StoryIdeas) listed by the GitHub wiki doesn't mention new races, such as the Bunrodea or Gegno. It also may have incorrect information on groups such as the Korath Exiles/Efreti (now considered T1.5), Remnant (now considered T1.8) or Hai (now considered T1.2), as per the Fandom wiki.
EDIT: Linked

### Expected content

Information is given on the tiers of the Bunrodea and Gegno, and tier information on the Hai, Remnant, and Korath Exiles/Efreti is updated.

**Comment by Zitchas** [comment]
The Tier system is not canonical, and honestly, serves to cause more arguments than anything else. It's also wrong; or at best denotes information that is often interpreted wildly differently by different people. 

We'd all be better off if the Tier framework was deleted entirely.

**Comment by ziproot** [comment]
This is clearly mentioned in the wiki page:
> It is important to note that tiers are not a concrete way to say that "every ship or outfit from X must be better than every ship or outfit from Y because X is of a greater tier than Y." Tiers are instead a general guideline as to the strength of various factions. Lower factions may still have ships or outfits that are "stronger" in some respects than higher factions, and factions of the same tiers should not be neck-and-neck in all ways.

**Comment by mOctave** [comment]
I think the tier system as it exists is a good way to balance content creation. Since the GitHub wiki exists primarily for content creators, I don't think the tier system should be removed. However, I'm not sure if it's really necessary for every race to be listed there in full. As Zitchas said, there is some fluidity. Human tier increases slightly as a result of the campaign, Remnant somewhat more significantly. Those numbers are ballpark estimates and, I think, are more meant to make sure that no one makes a Hai ship that is way more powerful than a Coalition one.

**Comment by ziproot** [comment]
Closing to move to the endless sky wiki repo

**Comment by ziproot** [comment]
https://github.com/endless-sky/endless-sky-wiki/issues/6
