### ISSUE TITLE
Capturing a Fighter Reduces Crew even when Docked

### ISSUE THREAD

**Issue by QuantumTux** [endless-sky/endless-sky#9747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a flagship that (a) has an unoccupied Fighter bay; and, (b) has no extra crew; captures a Fighter; and the captured Fighter docks and is not deployed, the flagship is affected as if it had a reduced crew, even though the newly-captured Fighter is not deployed.

### Steps to Reproduce

1. Have flagship with at least one Fighter bay (such as a Mule) and the minimum required crew
2. Do not equip the flagship with any Fighters; do equip it with the capability to fight and disable Fighters
3. Launch and go some place where the flagship can encounter and disable Fighters; disable a Fighter
4. Capture the Fighter, allow it to dock, do not deploy it
5. The flagship now functions as if its crew was reduced below the minimum required crew

### Expected Behavior

When a ship is capable of carrying Fighters, the crew requirements of docked Fighters should not count against meeting the minimum crew required for the ship. The crew requirements of carried Fighters should only be considered when they are deployed.

### Operating System

OpenSUSE LEAP 15.5

### Game Source

Other (please describe)

### Game Version

endless-sky RPM v0.10.4-lp155.26.1

### Additional Information

Obviously, this doesn't affect Fighter-carrying ships that have the Fighters when they depart a planet. The only time this particular circumstance comes into play is when a Fighter is captured.

**Comment by Hurleveur** [comment]
I dont see how this is a bug?
One of your crew got transfered to the fighter and is staying in it

**Comment by QuantumTux** [comment]
Why would they sit in the Fighter picking their...nose...when the ship needed them? They were a fully-functional/contributory member of the flagship's crew **before** the Fighter was captured. Now that the Fighter is in the bay, now suddenly they can't do anything else beyond stare at it?

**Comment by Hurleveur** [comment]
If you go with that logic then why would they sit in any fighter, but then we can use navy dropships to make boarding even easier.

Something to keep in mind also is that fighters are intended to be kept fonctional at all time, not just be sitting without crew in your ship, unable to be deployed

**Comment by QuantumTux** [comment]
If the crew member in question was able to function as a "regular" crew member before the Fighter was captured, they should be able to function that way after, as long as the Fighter isn't deployed. Simple.

**Comment by Amazinite** [comment]
This effectively means that we'd need a way to increase the required crew of ships with docked fighters, but reduce the required crew when the fighter launches. Otherwise, having exactly the required crew needed for a ship to run would mean losing crew when fighters are deployed. That is unless we have uncaptured fighters already manned and only captured fighters behave in this way, but at that point this would get unnecessarily complex for what effectively amounts to a realism argument.

Gameplay wise, boarding and capturing a ship means your flagship loses crew to man the ship you just captured. Having this be true for everything except fighters would be more trouble than it's worth. If you're capturing ships that require crew, then bring extra crew in your flagship.
