### ISSUE TITLE
Convert fighter bays to cargo?

### ISSUE THREAD

**Issue by bassgoonist** [endless-sky/endless-sky#978]
In a bactrian I can buy 3 fighters and remove everything and add cargo space getting 30 to 45 extra cargo room depending on how you do it. I think it would make sense to be able to put at least 100 outfits worth of cargo expansions in a fighter bay (since a fighter bay can hold a fighter with 100 units of outfit.)

**Comment by lehgogh** [comment]
Possibly related to #692?

**Comment by endless-sky** [comment]
If ships were *too* customizable, it would erode the differences between them until they were all pretty much the same and the only thing that mattered would be how much space they had. That's why you can't, for example, change the amount of engine space, weapon space, weapon mounts, etc.

**Comment by bassgoonist** [comment]
Well, I'm thinking in "reality" here. So I don't think you could just slap a fighter bay on a ship...like it needs door and special hardware. But there's no reason you couldn't strip out the hardware, leave the door shut, and have a cargo bay...just pondering.

**Comment by jafdy** [comment]
Its the reverse of #692. In reality you absolutely right but we also have to consider game balance.

**Comment by jmhorjus** [comment]
I can't believe I never thought of putting cargo expansions on fighters before...all those unused Bactrian fighter bays all this time...each dagger could have been carrying 45tons! :) 

So long as the conversion is one-way, I don't think it would detract from the uniqueness of carriers much. 

However, in practice, the ships commonly doing this kind of conversion would of course be the Bactrian and Mule - both of which are very powerful  and have quite enough cargo and outfit space to be getting on with already.  So just remember to nerf the base cargo of those two ships to make up for it. :)

**Comment by Gkramme** [comment]
Maybe it could cost a bit and require a special outfit? The outfit could be really heavy, so it would slow down the ship as a trade-off?.

**Comment by jmhorjus** [comment]
Yes, we're talking about an outfit similar to the cargo expansion, but which subtracts a fighter bay instead of outfit space.  

The outstanding question is: "Will anyone volunteer to add the neccessary code support for such an outfit?"

**Comment by bassgoonist** [comment]
@Gkramme I'm not sure why removing the fighter bay hardware would increase the weight...the extra weight would be from the cargo you'd put in there.

@jmhorjus would "-1 cargo bays" require a change of some kind? The shield regenerators(i think they're called) have "-x energy generation" for example.

**Comment by jafdy** [comment]
@bassgoonist It would as the number of fighter bays can't be changed currently and the problem would be compounded by external bays. #939 will make external bays more widely available.

**Comment by bassgoonist** [comment]
@jafdy Ah ok. It's just a fun idea :)

**Comment by pootthedestroyer** [comment]
Without changing any code, a workaround solution is to simply make an absolutely crippled fighter with no stats except cargo space. If you launch them, they'll get killed, and you'll be sad. If you keep them in your bays, you'll have the extra cargo space.

**Comment by LocalGod79** [comment]
anybody have a name suggestion for the "cargo fighter"?

here's my idea so far;
![untitled](https://cloud.githubusercontent.com/assets/16969517/14765380/5a8f0964-09ad-11e6-9145-392bd47516ec.png)

**Comment by pootthedestroyer** [comment]
If you wanted to be cheeky, you could call it the "Amazon" (same-day air delivery by drone!) but something tells me you're looking for names a bit more in-line with the base game's conventions.

Boxwing
Boxcar
Swallow (laden or unladen... African or European?)
Albatross
Packet
Droplet
Cargo Drone (the most creative one by far, but a bit confusing if it's not actually a drone)
A.C.T.S. (Automated Cargo Transport Shuttle)
Honeybee

**Comment by jafdy** [comment]
What about make it an automaton, get rid of the fins and cockpit and call it "detachable cargo pod".

**Comment by LocalGod79** [comment]
@jafdy i considered that.  all other things being equal, it would make the Roost a better base freighter than the Bulk/Behemoth (for less, without these "Pods" costing upward of a mil' each), and i'm hesitant to do that.

since an 'automaton' outfit is likely in the future, i think i'd like to leave that option open, and leave it crewed.

@pootthedestroyer "Boxwing" is going to make the shortlist.  i'm not sure the others quite fit.

**Comment by jmhorjus** [comment]
Retool your 3 cargo pods to hold 6 fighter bays, and then use those fighter bays to hold 6 more cargo pods...
What about a fighter that had two external fighter bays, so they could be nested infinitely? I'm guessing the game engine would choke on that, buy you never know unless you try it right? =P

**Comment by LocalGod79** [comment]
new sprite!

![untitled copy](https://cloud.githubusercontent.com/assets/16969517/14772986/38e10d4c-0a72-11e6-84eb-bf71ab23839d.png)

work in progress - thoughts on the Boxwing?

**Comment by jmhorjus** [comment]
I actually think it's pretty cool.  It would be a bit silly if this caused carriers to become the best freighters though - so I don't know if this kind of "fighter" is destined for the base game or whether it should be in a plug-in instead. To be honest, realizing that you can cram 45 tons of cargo onto a Dagger (nearly equal to the base capacity of a star barge!), was already a bit of a balance faux pas because it draws attention to the (usually overlooked) fact that the game simply does not size these two things (fighters/interceptors, and freighters) realistically relative to one another.  

Large oceangoing cargo ships can hold hundreds of thousands of metric tons of cargo.  Battleships weigh in at ~50,000 tons or more.  Combat aircraft mostly weigh in at under 20 tons when fully loaded. There are like four orders of magnitude difference between the expected sizes of these kinds of vehicles. 

But in a game you want the fighters to at least be *visible* without the battleships taking up the whole screen, so you've got to make allowances.  It just may be best not to intentionally draw attention to the allowances you have to make. :)

**Comment by pootthedestroyer** [comment]
@LocalGod79 I like the new design. It's important that it telegraph its
non-spaceworthiness compared to proper fighters, and I think emphasizing
the squared body does that nicely.

@jmhorjus I think the silliness you're worried about is already baked into
the game. Even without Boxwings, you can turn a Bactrian into what's
arguably a better freighter than the Bulk Freighter. People here will tell
you that everything is fine because credits and crew, so, it is what it is
unless/until MZ says otherwise, or a modder does a complete overhaul that
you find to your liking.

As far as the Boxwing experiment making things even sillier, well, I'm not
sure I agree. A vanilla freighter-Bactrian still has 3 figher bays' worth
of offense/defense that a Bulk Freighter doesn't have, which, even though
it doesn't make it better purely from a cargo space standpoint, still makes
it a better ship overall. Converting that combat advantage to a cargo
advantage doesn't seem all that extreme to me. I think what's rubbing you
the wrong way is that, while cargo expansions have a clearly defined
opportunity cost and inefficiency, a Boxwings' opportunity cost and
inefficiency will never be that clear, even if the creators take pains to
ensure it has both.

**Comment by LocalGod79** [comment]
okay, so i started to think of where this would be sold, to give it a look, and also made some proportion adjustments (the old one was wider than it was long, and too wide, at that)

Southbound's Boxwing (still need to enlarge the access hatch)?
![untitled](https://cloud.githubusercontent.com/assets/16969517/14774012/f5625ec4-0a7e-11e6-9d8e-8a85385a4fcb.png)

**Comment by Wrzlprnft** [comment]
Looks good that way, the only thing i am not sure about is: engine flares are always rendered below sprites. Go put it ingame to see if it creates a irritating look, or if it doesn't matter, before you set things in stone ;)

**Comment by LocalGod79** [comment]
the front arms are actually longer than the back ones (knowing about the engine flare below-renders), so i'm actually pretty happy with what i've got prepared (going to create the pull with it tomorrow).

all the same, i'll take your advice before i do...

**Comment by LocalGod79** [comment]
#995
