### ISSUE TITLE
Add Weapon Charge atribute

### ISSUE THREAD

**Issue by mdsmestad** [endless-sky/endless-sky#982]
Think r-Type series. A type of weapon where you hold down the fire and charge up for a more powerful shot. This would be a really fun weapon type

**Comment by LocalGod79** [comment]
i believe that this has been requested before.  their wording was poorer, so their idea was not effectively conveyed.

that said, their request was as fundamentally implementable as this one is.

i think that a weapon with a long reload time (possibly even a burst weapon) effectively achieves the same thing - forcing the user to carefully time their shot.

this is especially true if the weapon carries the "cluster" attribute, so that multiple copies of the weapon fire simultaneously (and the user is forced to suffer the reload on all of them).

**Comment by Alkallid** [comment]
That might've been me. I was suggesting attributes for the charge weapons. For example, 'hold energy' would've been how much energy it consumed every frame after holding a max charge.

**Comment by Amazinite** [comment]
I think what @mdsmestad and @Alkallid are looking for are weapons that increase in damage and power consumption the longer you hold the fire button, and upon release it fires the shot.

**Comment by Amazinite** [comment]
If something like this does get considered, possibly have an attribute called "charge" that causes the weapon to be able to use the charge mechanic, and a number after this attribute would be the charge multiplier that determines how much the damage is multiplied per second.

The damage dealt could be calculated by taking the base stats and multiplying by the seconds held as well as the charge multiplier.  

"charge projectile" would change the number of projectiles fired multiplied by each whole second held to get the effect of things like the missile salvo launcher idea, and "charge limit" could specify an upper and lower limit to how much you can charge before it fires.

**Comment by mdsmestad** [comment]
@Amazinite Yes, AND a sprite and projectile effect that reflect the damage increase. It would also be great to watch it make your gun points start glowing brighter and brighter...Just like R-Type

**Comment by Amazinite** [comment]
"charge effect" could be used to cause the brightening effect, but I'm not sure how you would get the projectile to always reflect the damage dealt. Maybe increase the size of the projectile the stronger it is, but that may look things look really blurry at the upper limits of a charge weapon's ability.

**Comment by endless-sky** [comment]
The question is, would this add anything new to the game other than eye candy? The burst mechanism already provides for a weapon that, essentially, does different amounts of damage depending on how long you want to spend reloading. And, it has the advantage that you don't need to release the firing key to make it fire (which would work only if the "charge" weapon is a secondary or your primaries are on automatic).

The best implementation would probably be a weapon that creates different projectiles depending on how long it has been "charging" (so that it can have a different size or different appearance, and different damage as well). But even then, I just think it would be hard to aim and would not add anything major by itself compared to a normal weapon with a long reload.

**Comment by Amazinite** [comment]
I would think that a charge weapon would be hard to aim by nature, as it shouldn't really be easy to hit something with a potentially one hit kill weapon, depending on how much charge you have.

**Comment by LocalGod79** [comment]
the point that i and M.Z. are making is that if you (with the existing code) made a weapon that had the attributes;
```
...
	"burst" 120
	"burst reload" 1
	"reload" 5
 	"cluster"
...
```
then the weapon would essentially function by firing a burst of projectiles (one frame apart) for two whole seconds, before having to reload for 10 seconds.

this would ensure that the player only hits "fire" when they were sure they will hit, and they can always let go (or run out of energy) before the full burst count is fired (doing less damage, the way an "incomplete charge" would)...

**Comment by DingusShingleton** [comment]
Respectfully, I beg to differ. Charge weapons have a different feel, anyone who has scored an epic kill with the Spartan laser in halo can attest to that. Perhaps numerically there is little difference but it's too easy to confuse numerical similarity with how a thing actually feels when you use it.

Now having said that, I think I lean towards MZ's position that such a thing wouldn't add so much to endless sky to be worth it. I just don't think burst weapons really equate to charge weapons.

**Comment by Alkallid** [comment]
How about we bring this up when 1.0 gets closer?

**Comment by mdsmestad** [comment]
@DingusShingleton @endless-sky I agree also. The way it feels to see a your weapon charge up is a tried and true element of many many games. How can I say this..It just feels GOOD to watch your huge charged lazer/plasma/whatever shoot out in a massive shot. To watch your enemys crumble to a big well timed beam of death is just sooo satisfying.
