### ISSUE TITLE
Make Quarg ships unplunderable

### ISSUE THREAD

**Issue by Hondolor** [endless-sky/endless-sky#986]
Part of what makes the game a bit boring for players later on is that you can totally bypass exploring for new technology because most players figure out how to farm quarg ships. It's far too easy and why would you want anything but quarg outfits when there so easy to farm.

I suggest disabling the ability to get quarg outfits w/out meeting special conditions of some kind

**Comment by thenerdfreak** [comment]
I've always suggested just making Quarg a small step above Korath. Drak are gonna replace Quarg as most powerful as soon as the new update comes out (sometime this month hopefully) if the storyline is correct.

**Comment by jafdy** [comment]
Current Drak ships can't be disabled. They are also ridiculously powerful to the point where I could just take one down with 40 Wardragons. So people who don't have a death wish will still find a mix of Quarg and Korath outfits to be the most powerful combination.

**Comment by pootthedestroyer** [comment]
This is part of a larger problem of mixing horizontal and vertical progression in a game like this, or in any game with RPG elements. Interesting choices along a horizontal line of power - a tier, as MZ calls it - get completely nullified by the existence of one or two options a tier up. This applies to every category of outfits. It also applies to ships.

That's the underlying reason for why smaller ships being universally worse than bigger ships (in the same tier, anyway) feels bad to so many people. The idea of a galaxy full of different weapons and ships is exciting because it implies different playstyles. Vertical progression eliminates a lot of that sense of wonder and options, especially if higher tiers have comparatively fewer options available.

**Comment by endless-sky** [comment]
It's really hard to "balance" a given set of ships until there are other species at or near the same technology level to balance them against. Right now, the Quarg are just a placeholder (only one weapon, only two ships, only a handful of outfits). So, I think I'm going to put off any re-balancing of them until the galaxy has been populated with other more advanced aliens.

In the meantime, anyone who can even disable a Quarg ship has basically won the game anyway, so the fact that their weapons are overpowered doesn't worry me much.

**Comment by mdsmestad** [comment]
@endless-sky Ahh I see..Well expanding on this issue it really should be impossible to get the top tear outfits without meeting certain conditions. I supposed when the Drak replace the quarg as the strongest race then there weapons should be made unlootable and so on for even stronger ships in the future.

**Comment by Alkallid** [comment]
Everything stat in an Archon would probably be part of the ship, and the weapons it needs should be permanantly attached. It seems like a living thing.

**Comment by jafdy** [comment]
As per my previous comment 

> Current Drak ships can't be disabled.

Well now we have that sorted.

**Comment by Alkallid** [comment]
Aye

**Comment by jmhorjus** [comment]
Just making them un-plunderable would spoil the fun. 
But just letting people take Quarg technology with no consequence is also a bit disappointing. 
Best way is to make players think twice about whether they want to take Quarg tech, by not letting them stay friends with the Quarg so easily after doing so.  

Something like this: 
https://github.com/endless-sky/endless-sky/pull/919

**Comment by Oeleo** [comment]
"In the meantime, anyone who can even disable a Quarg ship has basically won the game anyway, so the fact that their weapons are overpowered doesn't worry me much."

Since the last update, the 2 amazing aliens added are hard to fight even with 20 bactrians with all the aliens outfit except the Quarg's. Personnaly since that i sell all my Quarg outfit i play again the game. As i said month ago, and it's sadly still true, Quarg's are too easy to farm at the beginning (several hours of game) because :
-They is often only one ship at a time in a system (contrary to the new alien species plunderable)
-Their outfit are totally overpowered (")
-After several quarg ships disabled, you can easily farm them (")
-When you disable a ship, you have 100% probability of being able to plunder them (")

That's why i would have hoped to never plunder the Quarg, and i think that it's the same for the people who need challenge to like a game.
By the way amazing update it really rekindle the game, great work !

**Comment by Isaacssv552** [comment]
You may have a 100% probability of plundering a disabled ship but getting a disabled ship, as opposed to a destroyed or destroying ship, can be rather difficult (unless all your weapons are skylances, but that falls under the "you beat the bonus boss" rationale.) The first skylark I managed to disable was destroyed while my ship was en-route to board when a wardragon attacked my fleet. 

Plundering is quite difficult before you figure out the right strategies, like systems where the locals won't destroy disabled pirates, or laser weapons to prevent accidental destruction, or autofire to prevent said lasers from firing for half a second longer than desired and destroying the ship. For example, I never use my Archon for two reasons: 
1: I only have it to test a (solved) bug. 
2: The projectile weapons tend to destroy targets I want to board.

**Comment by Zitchas** [comment]
Just a thought: This issue could probably be closed. 

I don't think making Quarg unplunderable is *ever* going to happen. If anything, this problem is most likely to be made less relevant by the Quarg rebalance and/or many of the proposed boarding changes.

At the end of the day "Game is broke because I can plunder outfits from a more powerful faction" is *always* going to be a thing, because we don't have any sort of tier based lock on what can or cannot be plundered. And I don't think we should have any such locks, either.
