### ISSUE TITLE
Identify source of content - vanilla or plugin

### ISSUE THREAD

**Issue by xX-Dillinger-Xx** [endless-sky/endless-sky#9870]
### Problem Description

I've noticed a recurring issue on Discord. When players are asking questions about outfits, ships, or content, 90% of the time they don't know where it came from.  

### Related Issue Links

Just spend a little time on Discord

### Desired Solution

Provide some way of identifying where the content came from. It would be very helpful to know if  XYZ came from the official game or a plugin. Additionally, which plugin it came from. I would think that the simplest way would be to use tool tips. 

### Alternative Approaches

The information about ships and outfits could be displayed in the shipyard and outfit info panels.  
_**This outfit comes from plugin XYZ**_
Information about planets etc. could be included in the bottom of the planet description panels. 
_**This planet comes from plugin XYZ**_

**Comment by Hecter94** [comment]
This could be challenging given that ships/outfits/missions, etc., can be edited/added to by multiple different plugins. 

Say there's a vanilla ship that gets overwritten by one plugin and then has its stats edited by another plugin; what should the tooltip say? It's a vanilla ship but replaced by a plugin one, with the stats from another plugin.
Remember that the change from either plugin could be as small as a tweak to the sprite or as large as a total replacement. 

You'd need to differentiate between what plugins have edited something and how much each has changed and display that in a way that makes sense to the user.

Otherwise, you get a situation where you're displaying incorrect information to the user, like saying that a vanilla ship was added by a plugin when, in reality, the plugin just edited some of its stats. 
Or saying a ship is vanilla when it was completely overwritten by a different ship from a plugin.

**Comment by xX-Dillinger-Xx** [comment]
Maybe just for unique items them. IDK  Not `"unique" 1` but as is in unique to the plugin.
If it's too challenging then don't worry too much about it. I was just making an observation that might have a solution.

**Comment by xX-Dillinger-Xx** [comment]
I have question but first lets use set up an example. 
Vanilla Falcon
- plugin 1  increases shields
- plugin 2  adds extra guns
- both plugins are installed

What will the player have available in game?
- A - vanilla falcon
- B - falcon with more shields
- C - falcon with more guns
- D - falcon with more shields and guns
- E - ( A, B, and C )

How does the game engine determine which version of the falcon to use?

Could the game engine compare everything available and tag only the items that do not match what's in vanilla? Then only the tagged items would get a tool tip. Would the work load be too high and cause performance issues? Sorry, I'm not an experienced coder.

**Comment by xX-Dillinger-Xx** [comment]
> Edit: for clarity, plugins will overwrite things if they don't specify "add"
Thanks

If I understand this correctly, plugins will overwrite vanilla, but what order do plugins get loaded? I would just like to understand.

> code-wise that'd be easy and player-wise its all we need?

Now, that's the answer I was hoping for.

**Comment by Amazinite** [comment]
If a plugin wants to identify its own content then that plugin could add a line to the descriptions of its content, but I don't think that this should be something that is forced upon all content in the game. If someone is reporting a bug, they should have an understanding of what content is added by the plugins they have installed. If someone suspects that the bug is vanilla, they should attempt to reproduce it on a vanilla save.

> Information about planets etc. could be included in the bottom of the planet description panels.
> This planet comes from plugin XYZ

Planet descriptions are limited in how long they can be before they overflow the UI. Forcefully adding a new line to every plugin planet description could very easily overflow the UI for existing plugins, and would reduce the amount of description space that's available for future plugins.
