### ISSUE TITLE
Allow Enemies to Surrender when boarding their ship

### ISSUE THREAD

**Issue by ixPost** [endless-sky/endless-sky#9899]
### Problem Description

I dislike the idea that the only way you can capture a ship is to kill the enemies. Also I would think that the law would permanently imprison murderers not kill them.

### Related Issue Links

None as far as I know.

### Desired Solution

Allow enemy ships to surrender if out numbered(doesn't require bunks only space).

### Alternative Approaches

\(")/

**Comment by ziproot** [comment]
#253 #364 #3949

**Comment by lumbar527** [comment]
> #253 #364 #3949

I think this issue is about when you've boarded a ship. There is a difference between that and, say, making them bribe you because in this case you could just get the ship. I think both ideas sound interesting but this one (surrendering) would have to happen rarely at least with combat-oriented enemies.

**Comment by ziproot** [comment]
> I think this issue is about when you've boarded a ship. There is a difference between that and, say, making them bribe you because in this case you could just get the ship. I think both ideas sound interesting but this one (surrendering) would have to happen rarely at least with combat-oriented enemies.

Yeah, these are related issues, not duplicates. I should have been more clear.

**Comment by Amazinite** [comment]
> I dislike the idea that the only way you can capture a ship is to kill the enemies. Also I would think that the law would permanently imprison murderers not kill them.

I can't see any way that this could be a balanced game mechanic. What sort of cost would demanding surrender have to the player? If there's no cost, then everyone would just demand surrender of the ship they boarded before trying to engage in H2H combat. Would you only be able to demand surrender once, or after every turn of H2H combat? If it's once and there's no cost to it then you might as well always do it, but if you can demand surrender repeatedly then you'd do so after every attack turn and effectively speaking "kill" the remaining crew instantly as far as the boarding panel is concerned for you capturing the ship.

**Comment by Zitchas** [comment]
Just to throw ideas out there, I'd see surrendering not as something the player can ask for, but rather something that the computer offers under specific circumstances. Probably something along the lines of:

```
if
	AND
		Player crew > 1.5*victim's crew
		Player's total offense > 1.5*victim's defense
		Player's total defense > 1.5*victim's offense
Then:
	Victim offer's to surrender in exchange for:
		AND
			Victim's crew * 500 credits
			5% of total ship value
Misc:
	- If the ship offers to surrender and the player refuses, subsequent deaths result in double reputational hit with the owning government.
	- If the player accepts, the reputational hit for capturing the ship is half what it would have normally been.
```

So in this format, if the player meets the criteria at any point, then they would receive a dialog box at that point giving them the option to accept and pay the cost, or refuse. I would expect the offer to be made only once. 

Some governments could have a "no surrender", "Hard Surrender" and "timid surrender" attribtues (or personalities) that corresponding prevent surrenders entirely, mandate they happen at higher thresholds, or lower thresholds. 

Honestly, I'd rather have terms about "must drop them off at the neaerest world friendly to them" or some such other lore, but I think the above option would work decently. The costs are framed such that - for players introduced in looting for profit, the surrendering would seriously eat into their profit margin. Enough that I suspect most people interesteed in capture & sell wouldn't accept a surrender. But for players interested in the ship because they want the ship, then accepting the surrender is basically buying it at a very steep discount.

In any case, the requirements for the surrender to trigger are set such that players would need a balanced loadout, as simply loading up on gas grenades won't work. They'll need enough defensive outfits to ensure a guaranteed win against a solid and sustained counterattack from the computer too. If this is viewed as "too easy", then I'd be all for bumping those values up to 2* in all three cases. It's meant to be high enough to ensure that, no matter how favorable the home-ground advantage is for the victim, the player has enough resources to absolutely crush them. This makes the surrender mechanic effectively just a way to speed up capture a bit and avoid the "low crew" anoyance at the cost of actually paying for the ship, and only in circumstances where the player winning wasn't even remotely in question.

**Comment by Saugia** [comment]
Even if we were to nuance what rep hits would occur, I don't think it's still a good mechanical idea. Following what Derpy said:

What's stopping the player from demanding surrender and then just pursing the capture anyway? Even if this provides a rep hit, this provides 0 penalty for the actual process of the capture itself, as in, effort in capturing the ship. If anything, you just bypassed an entire capture phase, lost no crew, at a click of a button. Even if this changes rep, this makes capturing essentially a joke.

Not many players will actually care about double hit reps. The cases where asking a ship to surrender would not be very common, if anything, it would be far more used by players looking for an easy capture, not looking for pacifism. If a player wants to capture a ship, they should have to devote themselves to it, including lives. 

And at that point, what determines how the crew surrender? Sure, you could change the changes of the surrender based on odds, but this starts to get too muddy especially with alien factions - why would the coalition ever surrender? The Quarg? The Pug? Why would Pirates always surrender too? Etc.. We wouldn't go as far as to nuance this in order for a surrender to be viable,. It just sounds like an overall capture buff for little gain for an interaction that only sometimes makes sense.

**Comment by Zitchas** [comment]
> What's stopping the player from demanding surrender and then just pursing the capture anyway? Even if this provides a rep hit, this provides 0 penalty for the actual process of the capture itself, as in, effort in capturing the ship. If anything, you just bypassed an entire capture phase, lost no crew, at a click of a button. Even if this changes rep, this makes capturing essentially a joke.

Given that I described this at length, I get the strong impression that you didn't actually read anything I wrote.

1. The player doesn't get to ask them to surrender. Ever. 
2. In order to get them to *offer* the surrender, the player has to meet sufficiently high levels that capturing the ship would be a joke anyway. Double the crew, twice as much offense as the enemy has defense, and twice as much defense as the enemy has offense. With that level of disparity the defending ship doesn't have even a smidgen of a chance regardless. Won't be much crew loss, either. 
3. Of course it hits rep. It should hit rep a bit less because it's not slaughtering people, but it's still a loss.
4. Yes, it does bypass the crew loss, which makes multiple captures more viable. On the other hand, my proposed example costs the player a bit over half of the potential value in selling the ship. That really cuts into the profit margins. Probably enough so that people capturing for profit aren't going to take it.

**Comment by Saugia** [comment]
I was moreso outspeaking in general from what Derpy said, but the point I was addressing that regardless of what you do, having double rep hits I don't find to be a good reason to consider the mechanic regardless of what other conditions are present.

Having it so that something is dependent on the player's crew and ship stats essentially pushes onto the player another reason to have this sort of large discrepancy in the first place, and inevitability leads into the kind of gameplay based around having large fleets or ships outside the realm of what's intended.

Sure, we aren't going to limit the player in such behavior, but we shouldn't be adding more facets that promote such gameplay. Hence why I say, this isn't worth adding a case that only sometimes happens, that introduces another entire gameplay style that affects capturing efficiency. 

Also, bypassing in crew loss in itself is against the principle. If that's part of the equation, it's not a good equation.

**Comment by Saugia** [comment]
I will add that yes, that is how current capturing works, partly why we're looking to adjust it with examples such as https://github.com/endless-sky/endless-sky/pull/8506, but in that venue, I don't think further adding easier ways to mechanically obtain a ship are beneficial overall, separately from what penalties might occur. That's essentially why we disagree with giving such an option.

**Comment by Saugia** [comment]
For me personally, it's that randomness and nuance that is what makes it skeptical. If there's a good way to manage that, as in around the more simple ease of capturing (which as you are saying would come along with future changes), then I would be a little more inclined to be interested in having the variance. Though it also kind of falls under feature creep in that we don't want to necessarily have several x y z features of a given mechanic. The proposed changes in the PR I liked are *almost* mini-game, but nothing like a new window, or direction venues, etc., so I guess for me it would be a matter of how overwhelming it can get for a mechanic we want to keep in a somewhat linear aspect.

**Comment by Zitchas** [comment]
The linearity is precisely what needs to be done away with. So long as boarding is "hammer the attack button until you win or die", it is going to be problematily predictable, and do long as it is entirely predictable, it is going to be OP, boring, and a terrible mechanic, especially in terms of story.

Notre what would be really good is if the surrendering capability could be treated as a node, such that it could give or takeaway outfits, credits, and particularly missions. That would be wonderful if all this could be used to customize it and generate new avenues for missions. It would also allow surrenders to have missions to drop off the captured crew, it things like that. Loss of possibilities to add depth to the story.

**Comment by quyykk** [comment]
Interesting idea Zitchas, however I have one question:

>  This makes the surrender mechanic effectively just a way to speed up capture a bit and avoid the "low crew" anoyance at the cost of actually paying for the ship, and only in circumstances where the player winning wasn't even remotely in question.

Is "low crew" even possible due to the massive crew attack difference? I think in your solution it would never make sense to accept the surrender, since you're basically guaranteed a capture without much crew loses.

**Comment by Zitchas** [comment]
That is probably the best part. It isn't giving the player a guaranteed win, as they had that already. And you are right, they almost certainly aren't at risk of the low crew penalty, either. The only reason the player has to accept the surrender is genuinely being immersed in the story to the point where they are willing to take a hit to their profit in order to avoid since unnecessary deaths. For those players, this is a chance to see other characters make a choice for themselves to offer a surrender, to reinforce that immersion.

It will do nothing for those grinding out a combat rating or back balance. It will do nothing for those just metagaming for a specific ship or outfit, but it is another tool to reinforce the immersion for those who are actually in the game.

**Comment by quyykk** [comment]
I guess that makes sense for immersion, but I'm doubtful that adding a game mechanic that is functionally useless and just acts as lore flavor effectively, is a good idea. At least imo.

**Comment by Zitchas** [comment]
That is fair, but there is also the problem that immersion and story are extremely weak areas for ES. It is probably time we stopped adding mechanics to add more variety to combat without solving any of is problems, and instead prioritize mechanics and functionality explicitly focused on improving immersion. That is really where the work is needed at this point.

**Comment by ziproot** [comment]
I concur. I think that if you have a 100% chance of capturing the ship, the crew should just surrender. You would lose zero crew anyways, and this would just prevent the crew from being killed. In all other cases, they can press their luck, then surrender once the capture chance reaches 100%. This would take about the same amount of time (you would just need to click attack one more time, and now you instead accept their surrender), the same number of crew members, etc.

**Comment by Zitchas** [comment]
I like the idea of having the surrendering crew take up bunks as prisoners, and thus the player still loses crew to staff the new ship.

**Comment by xX-Dillinger-Xx** [comment]
This was discussed in the Camp Fire Chat. Derpy and Saugia don't seem too interested in this idea. In fact, they laughed at it. 
I order to have this even remotely be considered we are going to have to come up with a real solution that makes sense. 
So, @Zitchas Re-work your around the idea of taking prisoners and see what it looks like. 

-  surrendering needs to be an option instead of killing
- surrendered crew and surviving crew, if there was a fight, have to be accounted for
- it can't be considered a buff to capping
- having to deal with the prisoners is what could be the deterrent to help slow down capping, whether there was a fight or a surrender.
  - once your bunks are full you have to deliver you prisoners some where. To make it even a bigger deterrence, prisoner processing can only happen on certain plants

**Comment by ixPost** [comment]
@xX-Dillinger-Xx Otherwise we should make capturing illegal.

**Comment by nickshanks** [comment]
Should it require a Brig? If we're taking prisoners, and the surrender is only offered at very high chances of capture (so minimal crew loss to the player) we could require that the crew are occupied "guarding the prisioners" and can't be used to fly the ship (but don't need to be re-hired when you land and release the prisoners).
