### ISSUE TITLE
[Bug] Far Osk 27 weapon capacity comparison

### ISSUE THREAD

**Issue by Zitchas** [endless-sky/endless-sky#9957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Far Osk 27's description specifies:

> "Because it is piloted by a computer and has no need for a cockpit or life support systems, the FS27 fighter is able to carry far more weaponry than any comparable human ship."

And yet, despite the fact that it is heavier than all the human fighters, it has 6 less weapon space than the Barb, and only 2 more than the Dagger, Finch, and Lance. So the most comparable human fighter has 27% more weapon space than it, and it has only 10% more space than the other three. 

### Steps to Reproduce

1. Look at Far Osk 27 ship stats.
2. Look at Barb stats.
3. See error

### Expected Behavior

Based on the description, I would expect the Far Osk 27 to have a weapon capacity greater than any of the human fighters. 

The two solutions I see are:
a) adjust the description to remove this comparison.
b) adjust the weapon capacity up to 30.

Both solutions are equally easy to do, although I haven't taken the time to analyze the balance implications of such an adjustment. 

Based on the technological disparity and the surrounding lore, I believe option B is more appropriate to the story. 

### Screenshots

n/a

### Operating System

Windows 10 Pro

### Game Source

Built from source

### Game Version

v 0.10.6

### Additional Information

I would be happy to provide a PR appropriate to either solution; but would like input first as to which one would be more suitable.

**Comment by xX-Dillinger-Xx** [comment]
I thought I posted this already. I guess I didn't submit it. 

Increasing the weapon capacity by only 8 points will not change much. The only thing it allows is for the player to swap out to other guns, but there wouldn't be much point. The only ones that 'might' make sense would be Ka'het Annihilator. 
The stock builds would not change because, at 30, there aren't any other Korath guns that would fit. If you went  up to 32 you could use a Thermal Repeater and a Fire Lance but why would you?

**Comment by xX-Dillinger-Xx** [comment]
Just because this issue will just get lost in black hole of forgotten issues, I'm suggesting, just change the description and be done with it.

**Comment by Zitchas** [comment]
Hmmm... I think overall it's better to give player's new options when they expand beyond human space. If 33 is the weapon space required to match the description/lore and also actually give them more options, then that's my preferred option. That'll have it matching the Petrel, too, so the Remnant don't exceed it.

**Comment by xX-Dillinger-Xx** [comment]
I like the idea, I just figured a description change would be a quick acceptable fix, to close this. Doing a PR to alter the stats will just get dragged out in discussion about balance. It's not a shot at anyone, it's just a fact.

**Comment by warp-core** [comment]
I believe, at the time the description was written, the Barb did not exist.
Even though the Barb has more weapon capacity, it can't really carry more weaponry effectively.
It only has one gun port. It does have a turret mount, but it's not easy to find a turret that'll fit that can match two Repeaters. The Repeater turret is just barely too large.
Even if such a weapon did fit, the Barb has significantly less outfit space, so it's going to have some difficulty supporting such weaponry.
The FS27 is still far more capable than any human fighter. It makes more sense to me to modify the description to account for the addition of the Barb, rather than buff the fighter, which is just power creep.

**Comment by Zitchas** [comment]
1. The Far Osk 27's stats were established a long time before many of these Korath weapon options even existed, and should be looked at again with this in mind.
2. The Korath are significantly superior to humanity. I don't think it's "power-creep" to have their weapon capacity reflect that. 

In any case, the fact that the Barb might have trouble making use of that weapon space doesn't really matter much here. I suspect the Far Osk 27 might have similar (although less) difficulty in making use of the extra space. This doesn't mean it should have it, though.

**Comment by Zitchas** [comment]
So by that logic, the "power creep" is on the side of the Barb, then, and that should be correspondingly nerfed; otherwise this is symptomatic of humanity slowly increasing and matching the Korath.

**Comment by ziproot** [comment]
Close as completed?
