### ISSUE TITLE
Bug: Double bribing NPCs causes them to remain friendly

### ISSUE THREAD

**Issue by Amazinite** [endless-sky/endless-sky#997]
Bribing an NPC, shooting them to make them hostile again, then bribing them again will cause them and their faction to be permanently friendly and allow you to disable them without them caring. Shooting another ship of the same faction will make that faction hostile again, but if you keep double bribing ships then they don't be hostile when you shoot ships that you double bribed. 

If you are attacking a very expensive ship, then you could easily double bribe them, capture them, and still make massive profit. Could be highly abuseable.

**Comment by egilburg** [comment]
In general I think it should not be possible to bribe a ship (or the ship's faction) if you initiated same-day aggression against them, they should just refuse to accept your hails.

Attacking them if they were *already* hostile when you entered the sector is OK for bribing purposes (regardless of who shot first), but attacking a ship/faction which was peaceful prior to the attack (either peaceful since you entered sector or peaceful since you bribed them once before on that day) should make further bribing on the same day impossible.

**Comment by Amazinite** [comment]
Yeah, I just checked with demanding tribute from a planet and it works the same. This could be easily abused to capture an entire defense fleet and sell it off.

**Comment by endless-sky** [comment]
Fixed (I think) in 738dada. There's enough different permutations of how you can provoke and bribe different governments that it'd be great if you could test to make sure it's fixed.

**Comment by egilburg** [comment]
@endless-sky WDYT of not allowing player to bribe same faction multiple times on the same day per above comment?

**Comment by endless-sky** [comment]
Closing this because it's included in 0.9.0, which is now released.
